### ISSUE TITLE
[技术咨询]RtpSession.cpp:62 onError | 7D49F9DD receive rtp timeout .什么原因会导致超时？

### ISSUE THREAD

**Issue by Karrys** [ZLMediaKit/ZLMediaKit#1000]
![image](https://user-images.githubusercontent.com/19201279/126424210-502cc0fc-eff3-446d-820a-67d5df9336a9.png)

**Comment by xia-chu** [comment]
接收rtp超时了 是不是udp单端口推流啊？

**Comment by xia-chu** [comment]
可能需要rtcp保活 建议用udp多端口模式。或者用tcp模式
