### ISSUE TITLE
[技术咨询]mac编译报错 master分支

### ISSUE THREAD

**Issue by lovederh** [ZLMediaKit/ZLMediaKit#1001]
报错日志

ZLMediaKit/server/main.cpp:232:9: error: use of undeclared identifier 'setThreadName'
        setThreadName("main thread");
1 error generated.
make[2]: *** [server/CMakeFiles/MediaServer.dir/main.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 99%] Linking CXX executable ../../release/mac/Debug/test_player
[ 99%] Built target test_player
make[1]: *** [server/CMakeFiles/MediaServer.dir/all] Error 2

重现步骤
cd build
cmake ..
make -j4

**操作系统环境**
Mac 64位 非M1系统

**Comment by xia-chu** [comment]
请更新zltoolkit



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lovederh ***@***.***&gt;
发送时间: 2021年7月22日 09:13
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] mac编译报错 master分支 [BUG] (#1001)





 
报错日志
 
ZLMediaKit/server/main.cpp:232:9: error: use of undeclared identifier 'setThreadName'
 setThreadName("main thread");
 1 error generated.
 make[2]: *** [server/CMakeFiles/MediaServer.dir/main.cpp.o] Error 1
 make[2]: *** Waiting for unfinished jobs....
 [ 99%] Linking CXX executable ../../release/mac/Debug/test_player
 [ 99%] Built target test_player
 make[1]: *** [server/CMakeFiles/MediaServer.dir/all] Error 2
 
重现步骤
 cd build
 cmake ..
 make -j4
 
操作系统环境
 Mac 64位 非M1系统
