### ISSUE TITLE
[技术咨询]Hls平滑生成的问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1005]
看了hls生成的相关代码, 应该是获取多少帧就生成多少切片. 这样比如hls拉流的时候有一段代码, 就是如果缓存超过30秒就强制消耗15秒, 这样如果在网络抖动的时候会导致hls生成的m3u8出现跳跃的情况.

比如每段3秒, 那么理论上应该每隔3秒才会更新一次m3u8上的#EXT-X-MEDIA-SEQUENCE, 但是实际上发现这个会出现跳跃, 
之前我也反馈过这个问题, 有时候上一秒#EXT-X-MEDIA-SEQUENCE还是1, 下一妙就变成了7.
这样导致客户端播放会提示跳过分段.

**Comment by xia-chu** [comment]
你说的是拉hls流 生成hls流对吧？ 拉hls流可能抖动特别大，这个一般是网络抖动导致的，zlm也做了平滑处理的，这种极端情况很少的。
生成hls切片时，可以修改下逻辑，就是删除多少时间之前的切片，而不是前几个切片，这样生成的切片，最少能在磁盘上保留一段时间。

**Comment by alexliyu7352** [comment]
这个保留切片数量可以通过config.ini设置, 主要是#EXT-X-MEDIA-SEQUENCE跳动比较大, 有时候一秒内会跳好几个.虽然设定的每个分段是10秒.

**Comment by alexliyu7352** [comment]
我现在删除了您下面这段代码, 这样完全依靠onTick这个方法周期性输入帧, 这样虽然会导致内存消耗增大, 但是平滑一些了.

```
   if (getBufferMS() > 30 * 1000) {
        //缓存超过30秒，强制消费至15秒(减少延时或内存占用)
        while (getBufferMS() > 15 * 1000) {
            MediaSink::inputFrame(_frame_cache.begin()->second);
            _frame_cache.erase(_frame_cache.begin());
        }
        //接着播放缓存中最早的帧
        setPlayPosition(_frame_cache.begin()->first);
    }
```

**Comment by xia-chu** [comment]
最好还是限制下最大缓冲长度 否则可能导致内存溢出。
你可以加大点阈值，但是逻辑不要完全去除

**Comment by alexliyu7352** [comment]
明白了, 谢谢大神
