### ISSUE TITLE
[技术咨询]采用pts还是dts

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1006]
我看最近的更新rtp采用了pts作为时间戳而不是dts了, 但是hls拉流仍旧是采用dts作为相对时间戳.
为何改为了pts呢?
另外, 我看ffmpeg基本上也是采用pts作为相对时间戳, 然后使用视频同步音频的方式保证音视频同步.
所以是否hls拉流也需要改成pts呢?

**Comment by xia-chu** [comment]
hls播放器只是根据dts来平滑输出frame， 由于dts是递增的，不会回退，所以dts放入在map中排序也不会打乱顺序。
