### ISSUE TITLE
[技术咨询] WebRtc公网无法播放

### ISSUE THREAD

**Issue by byna11sina11** [ZLMediaKit/ZLMediaKit#1007]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
WebRtc模块
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
当config.ini的externIP置空时，本地局域网的电脑可以按照
https://192.168.10.201:443/index/api/webrtc?app=live&stream=16&type=play
的格式在ZLM RTC demo中播放，
而使用公网ip将443的tcp/udp分别映射成10443，并将config.ini的externIP修改为公网ip地址时，
使用
https://*.*.*.*:10443/index/api/webrtc?app=live&stream=16&type=play
的格式在ZLM RTC demo中播放，无法播放，控制台也无异常，是不是需要映射其他端口？
![image](https://user-images.githubusercontent.com/16750129/127306581-825aad23-cb24-4eaa-b02a-056be10d6a7f.png)
控制台显示
![image](https://user-images.githubusercontent.com/16750129/127306675-733130a9-00c1-41b5-9b59-dc47c34dd007.png)
缺少某个upd端口吗？
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你需要配置下域名和ssl证书 你有配置吗？ 浏览器在http网页上一般不给打开摄像头的权限的

**Comment by byna11sina11** [comment]
我重新配置了腾讯云的证书，当前chrome已显示安全
![image](https://user-images.githubusercontent.com/16750129/127429704-9d3c36b9-de79-4d05-a7df-995777855793.png)
同样的 是在url中使用带域名的播放地址
https://*.*.*.*:10443/index/api/webrtc?app=live&stream=16&type=play
应该和摄像头没关系，我是使用远程服务器上的ffmpeg采用rtmp的形式自身服务器上的ZLM推流 然后在防火墙上把443端口映射成公网的10443

**Comment by xia-chu** [comment]
webrtc用的udp端口 你都放行了吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: byna11sina11 ***@***.***&gt;
发送时间: 2021年7月29日 12:08
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] WebRtc公网无法播放 (#1007)





 
我重新配置了腾讯云的证书，当前chrome已显示安全
 
 同样的 是在url中使用带域名的播放地址
 https://...:10443/index/api/webrtc?app=live&amp;stream=16&amp;type=play
 应该和摄像头没关系，我是使用远程服务器上的ffmpeg采用rtmp的形式自身服务器上的ZLM推流 然后在防火墙上把443端口映射成公网的10443

**Comment by byna11sina11** [comment]
我估计也是这个原因  会使用什么端口？我服务器的自带防火墙已经关了，需要在公网防火墙上开放那些udp端口？

**Comment by xia-chu** [comment]
udp用的随机端口 一般30000到60000



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: byna11sina11 ***@***.***&gt;
发送时间: 2021年7月29日 12:10
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] WebRtc公网无法播放 (#1007)





 
我估计也是这个原因  会使用什么端口？我服务器的自带防火墙已经关了，需要在公网防火墙上开放那些udp端口？

**Comment by byna11sina11** [comment]
这就很麻烦了  我需要将公网防火墙的所有30000到60000端口映射成服务器的30000到60000？还是仅仅在防火墙上放行即可？

**Comment by xia-chu** [comment]
端口映射本来就有范围映射啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: byna11sina11 ***@***.***&gt;
发送时间: 2021年7月29日 12:14
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] WebRtc公网无法播放 (#1007)





 
这就很麻烦了  我需要将公网防火墙的所有30000到60000端口映射成服务器的30000到60000？还是仅仅在防火墙上放行即可？

**Comment by byna11sina11** [comment]
做这种大范围的映射，我害怕影响其他服务器。。。会导致其他服务器无法使用该端口吧？

**Comment by xia-chu** [comment]
不会的 udp没事



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: byna11sina11 ***@***.***&gt;
发送时间: 2021年7月29日 12:17
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] WebRtc公网无法播放 (#1007)





 
做这种大范围的映射，我害怕影响其他服务器。。。会导致其他服务器无法使用该端口吧？

**Comment by byna11sina11** [comment]
非常感谢，然而webrtc在公网非常卡，flv就相对流畅很多，，，采用的是wvp gb28181推流，flv采用flv.js播放，webrtc采用默认播放器播放，这个是什么情况？

**Comment by xia-chu** [comment]
嗯 前面nack有个bug 最近修复了 你更新下试试？

**Comment by byna11sina11** [comment]
好的  谢谢

**Comment by xia-chu** [comment]
> 好的 谢谢 不过不考虑开通打赏吗？

之前挂过个人的二维码 没什么人打赏，而且现在zlm有比较稳定的开发团队，已经不合适挂私人的二维码了。如果团队的，不太知道国内有啥渠道。不过gitee有打赏功能。

**Comment by byna11sina11** [comment]
我写了关于windows10 启用webrtc编译64位ZLMediaKit的博客，可以放到wiki：zlm启用webrtc编译指南下边，给windows有需要的用户参考下

**Comment by byna11sina11** [comment]
https://blog.csdn.net/byna11sina11/article/details/119786889

**Comment by xia-chu** [comment]
谢谢 我会在wiki引用的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: byna11sina11 ***@***.***&gt;
发送时间: 2021年8月18日 19:47
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] WebRtc公网无法播放 (#1007)





 
https://blog.csdn.net/byna11sina11/article/details/119786889

**Comment by kuaidou** [comment]
我也有同样的问题，我使用的版本是commit: 78d014cf5112854f4180f88d212f376b1065a326

现在仍然需要范围映射udp端口吗？
