### ISSUE TITLE
[技术咨询]addStreamProxy接口拉取rtsp流播放失败

### ISSUE THREAD

**Issue by liangjw-editor** [ZLMediaKit/ZLMediaKit#1011]
**咨询的功能模块**
addStreamProxy接口

**咨询的具体内容和问题**
我使用addStreamProxy接口来拉取rtsp流，返回的是如下错误
![image](https://user-images.githubusercontent.com/77035264/127590171-41de2c41-8c53-4c1c-87aa-12b993c9ea6e.png)

使用vlc播放获取到的编码格式如下，是zlm调用的第三方库不支持该编码格式吗？
![image](https://user-images.githubusercontent.com/77035264/127590190-c9400fa5-6942-47f1-ad6e-4cb2c6c50842.png)

**Comment by xia-chu** [comment]
能否给下sdp？或者rtsp链接？我调试下试试

**Comment by liangjw-editor** [comment]
> 能否给下sdp？或者rtsp链接？我调试下试试
sdp信息是以下这个，rtsp链接是海康平台给的，需要用到华为vpn才能访问到，所以给不出来
![image](https://user-images.githubusercontent.com/77035264/127600299-d65a751f-959d-45e2-9d3f-c356ee71f7bd.png)
抓包信息是以下这个
[sdp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6905072/sdp.zip)

**Comment by liangjw-editor** [comment]
而且最新版本的zlm代理rtsp，使用客户端取流播放画面会慢慢变卡顿，旧版本的zlm就不会出现这种情况

**Comment by xia-chu** [comment]
> > 能否给下sdp？或者rtsp链接？我调试下试试
> > sdp信息是以下这个，rtsp链接是海康平台给的，需要用到华为vpn才能访问到，所以给不出来
> > ![image](https://user-images.githubusercontent.com/77035264/127600299-d65a751f-959d-45e2-9d3f-c356ee71f7bd.png)
> > 抓包信息是以下这个
> > [sdp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6905072/sdp.zip)

有点奇怪 rtsp能否暴露下公网

**Comment by xia-chu** [comment]
> 而且最新版本的zlm代理rtsp，使用客户端取流播放画面会慢慢变卡顿，旧版本的zlm就不会出现这种情况

新版本的zlm采用ntp时间戳来生成时间戳了 之前是存储根据rtp的时间戳 那样可能音视频不同步
但是ntp作为时间戳，如果摄像头生成的sender report ntp时间戳不准，就会导致这个问题

**Comment by xia-chu** [comment]
这个问题如果存在 那么说明原始的rtsp url播放也会慢慢变卡顿

**Comment by liangjw-editor** [comment]
> > > 能否给下sdp？或者rtsp链接？我调试下试试
> > > sdp信息是以下这个，rtsp链接是海康平台给的，需要用到华为vpn才能访问到，所以给不出来
> > > ![image](https://user-images.githubusercontent.com/77035264/127600299-d65a751f-959d-45e2-9d3f-c356ee71f7bd.png)
> > > 抓包信息是以下这个
> > > [sdp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6905072/sdp.zip)
> 
> 有点奇怪 rtsp能否暴露下公网

这些rtsp需要登录华为vpn账号才能外网访问，并且每次生成的rtsp链接有效期只有五分钟，能否邮箱或者qq联系

**Comment by xia-chu** [comment]
qq:1213642868 子悦

**Comment by xia-chu** [comment]
这个是bug 已修复
