### ISSUE TITLE
[BUG]MP4Demuxer Memory LEAK

### ISSUE THREAD

**Issue by cfgrpg** [ZLMediaKit/ZLMediaKit#1018]
**bug现象**
内存泄露
```
==18302== LEAK SUMMARY:
==18302==    definitely lost: 152 bytes in 1 blocks
==18302==    indirectly lost: 81,898 bytes in 15 blocks
==18302==      possibly lost: 0 bytes in 0 blocks
==18302==    still reachable: 0 bytes in 0 blocks
==18302==         suppressed: 0 bytes in 0 blocks
==18302==
==18302== For lists of detected and suppressed errors, rerun with: -s
==18302== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```

代码如下：
```c++
#include "Record/MP4Demuxer.h"
#include "Record/MP4Muxer.h"

using namespace std;
using namespace mediakit;

int main(int argc, char* argv[])
{
	MP4Demuxer::Ptr demuxer = std::make_shared<MP4Demuxer>();

	demuxer->openMP4(argv[1]);

	demuxer->closeFile();
}
```

**bug产生时的使用场景**
- MP4Demuxer

**bug是否可以复现，怎么复现**
- MP4Demuxer 打开一个文件，然后关闭，使用:
  ```
  valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes ./media-bm fmp4.mp4
  ```
 不知道是valgrind误报还是怎么回事！

**zlm代码git commit hash值**
- 6df0ee69e01391d78abe1185bab23f47a9c8f3cd

**操作系统环境**
- Ubuntu20.04 x64
- Vmware

**Comment by wasphin** [comment]
格式调了一下, 可读性会好一些.

测试未复现, 和具体 mp4 文件有关? 是否可以提供一个可以复现的 mp4 文件呢?

**Comment by cfgrpg** [comment]
> 格式调了一下, 可读性会好一些.
> 
> 测试未复现, 和具体 mp4 文件有关? 是否可以提供一个可以复现的 mp4 文件呢?

应该跟mp4文件没有关系吧，我试过好几个文件都一样，另外我还单独测试过同版本目录下的3rdpart/media-server/libmov/test/mov-reader-test.cpp，这个测试程序，没有发现内存泄露，基本可以确认是ZLMediaKit这边的问题吧！不知道是不是C11，检测工具误报！另外我也测试了下，项目里面的test_pusherMp4，也有报异常！
[https://www.aliyundrive.com/s/LLNcfy4LmoP](url) 测试文件链接
`valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --track-origins=yes ./test_pusherMp4 test.mp4`

[完整的输出日志文件：](https://www.aliyundrive.com/s/zh6mCmHvRzz)

下载地址都是阿里云盘的地址。

> ==21734== LEAK SUMMARY:
> ==21734==    definitely lost: 0 bytes in 0 blocks
> ==21734==    indirectly lost: 0 bytes in 0 blocks
> ==21734==      possibly lost: 1,152 bytes in 4 blocks
> ==21734==    still reachable: 763,175 bytes in 1,163 blocks
> ==21734==         suppressed: 0 bytes in 0 blocks

**Comment by cfgrpg** [comment]
Uploading test.mp4…

**Comment by cfgrpg** [comment]
Uploading test.mp4…

**Comment by cfgrpg** [comment]
运行日志文件
[test_pusherMp4-mem.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/6923374/test_pusherMp4-mem.txt)

我测试的代码，把扩展名改成cpp，放到ZLMediaKit\tests，重新cmake .. ，然后make，会自动生成测试程序test_mp4demux，我这每次得到得结果都是如此：
```
==23617== LEAK SUMMARY:
==23617==    definitely lost: 152 bytes in 1 blocks
==23617==    indirectly lost: 82,380 bytes in 25 blocks
==23617==      possibly lost: 0 bytes in 0 blocks
==23617==    still reachable: 0 bytes in 0 blocks
==23617==         suppressed: 0 bytes in 0 blocks
```
[test_mp4demux.cpp.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/6923381/test_mp4demux.cpp.txt)

测试使用的视频文件，下载慢的可以去上面那个阿里云盘下载
https://user-images.githubusercontent.com/26292370/128000727-c85fd8d9-1e4e-44d3-a555-fdf14210414d.mp4

**Comment by wasphin** [comment]
使用上传的 mp4 文件可以复现.

**Comment by wasphin** [comment]
多谢反馈, 可以试一下 `feature/fix-#1018` 分支.

**Comment by cfgrpg** [comment]
> 多谢反馈, 可以试一下 `feature/fix-#1018` 分支.

确实，已经没有报泄露了！十分给力啊！

**Comment by xia-chu** [comment]
非常感谢 @cfgrpg 的反馈， 也非常感谢 @wasphin 的修复！
