### ISSUE TITLE
[BUG]WebRTC关闭播放后，MediaServer内存没释放，导致每次重新播放MediaServer内存都会增加

### ISSUE THREAD

**Issue by hanhxm** [ZLMediaKit/ZLMediaKit#1024]
**bug现象**
WebRTC关闭播放后，MediaServer内存没释放，导致每次重新播放MediaServer内存都会增加

**bug产生时的使用场景**
- WebRTC功能

**bug是否可以复现，怎么复现**
- 播放器播放webrtc视频--->播放器关闭webrtc播放，这样一直重复

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
- centos7.8 64位和Ubuntu18.04 64位系统现象都一样
- cpu core I7  16G内存

**Comment by xia-chu** [comment]
valgrind跑一遍吧， 应该没这个问题的。内存free掉 malloc库不一定立即返还给操作系统的

**Comment by hanhxm** [comment]
确实有问题，我今天测试了一天，写了测试网页，自动的不停的打开视频并关闭视频，间隔5秒执行一次打开关闭视频，到最后MediaServer把系统内存用完程序退出。

**Comment by xia-chu** [comment]
@hanhxm 能否分享下 这个测试网页 我测试下 谢谢！

**Comment by hanhxm** [comment]
<html>
  <meta charset="utf-8">
  <head>
    <title>ZLM RTC demo</title>
    <script src="./ZLMRTCClient.js"></script>
  </head>
    <style type="text/css">
	*{
	    margin: 0;
	    padding: 0;
	}
	.main{
	    width: 100%;
	    height: 100%;
	    position: absolute;
	}
	.quarter-div{
	    width: 32%;
	    height: 32%;
	    float: left;
	}
	.blue{
	    background-color: #5BC0DE;
	}
	.green{
	    background-color: #5CB85C;
	}
	.orange{
	    background-color: #F0AD4E;
	}
	.yellow{
	    background-color: #FFC706;
	}
	.gray{
	    background-color: #666666;
	}
</style>
  <body onbeforeunload="stop()">

  <div class="main">
        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>
        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video1' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video2' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>
        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video3' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video4' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video5' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video6' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video7' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>

        <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF">
          <video id='video8' controls autoplay style="width: 100%; height: 100%;">
            Your browser is too old which doesn't support HTML5 video.
          </video>
        </div>



        <div>
            <button onclick="start()">开始</button>
            <button onclick="stop()">停止</button>
        </div>
    </div>

    <script>
      var player = null
	  var player1 = null
	  var player2 = null
	  var player3 = null
	  var player4 = null
	  var player5 = null
	  var player6 = null
	  var player7 = null
	  var player8 = null
      var recvOnly = true
      var resArr = []
	  var sUrl='http://192.168.1.107/index/api/webrtc?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&app=live&stream=test&type=play';
      function start_play(){
        player = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );

    player1 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video1'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );


			
    
			
        player2 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video2'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );

        player3 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video3'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );
           player4 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video4'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );


        player5 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video5'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );
        player6 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video6'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );

        player7 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video7'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );

        player8 = new ZLMRTCClient.Endpoint(
                {
                    element: document.getElementById('video8'),// video 标签
                    debug: true,// 是否打印日志
                    zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址
                    simulcast:false,//document.getElementById('simulcast').checked,
                    useCamera:false,//document.getElementById('useCamera').checked,
                    audioEnable:true,//document.getElementById('audioEnable').checked,
                    videoEnable:true,//document.getElementById('videoEnable').checked,
                    recvOnly:true,
                   
                }
            );
		/*	*/

      }

      function start()
      {
        stop();
		start_play();
		
      }
      function stop()
      {
          if(player)
          {
            player.close();
            player = null;
          }
          if(player1)
          {
            player1.close();
            player1 = null;
          }
		  if(player2)
          {
            player2.close();
            player2 = null;
          }
		  if(player3)
          {
            player3.close();
            player3 = null;
          }
		  if(player4)
          {
            player4.close();
            player4 = null;
          }
		  if(player5)
          {
            player5.close();
            player5 = null;
          }
		  if(player6)
          {
            player6.close();
            player6 = null;
          }
		  if(player7)
          {
            player7.close();
            player7 = null;
          }
		  if(player8)
          {
            player8.close();
            player8 = null;
          }
      }
    </script>
  </body>
  <script>
      setInterval(function(){ start();},8000); 
  </script>
</html>

**Comment by xia-chu** [comment]
非常感谢！



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hanhxm ***@***.***&gt;
发送时间: 2021年9月3日 10:39
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]WebRTC关闭播放后，MediaServer内存没释放，导致每次重新播放MediaServer内存都会增加 (#1024)





           <title&gt;ZLM RTC demo</title&gt;     <script src="./ZLMRTCClient.js"&gt;</script&gt;        <style type="text/css"&gt; *{     margin: 0;     padding: 0; } .main{     width: 100%;     height: 100%;     position: absolute; } .quarter-div{     width: 32%;     height: 32%;     float: left; } .blue{     background-color: #5BC0DE; } .green{     background-color: #5CB85C; } .orange{     background-color: #F0AD4E; } .yellow{     background-color: #FFC706; } .gray{     background-color: #666666; } </style&gt;                                   
                             
     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video2' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video3' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video4' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video5' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video6' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video7' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div class="quarter-div gray" align="center" style="border:1px solid #FFFFFF"&gt;       <video id='video8' controls autoplay style="width: 100%; height: 100%;"&gt;         Your browser is too old which doesn't support HTML5 video.       </video&gt;     </div&gt;     <div&gt;         <button onclick="start()"&gt;开始</button&gt;         <button onclick="stop()"&gt;停止</button&gt;     </div&gt; </div&gt; <script&gt;   var player = null   var player1 = null   var player2 = null   var player3 = null   var player4 = null   var player5 = null   var player6 = null   var player7 = null   var player8 = null   var recvOnly = true   var resArr = []   var sUrl='http://192.168.1.107/index/api/webrtc?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;app=live&amp;stream=test&amp;type=play';   function start_play(){     player = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         ); player1 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video1'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player2 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video2'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player3 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video3'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );        player4 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video4'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player5 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video5'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player6 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video6'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player7 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video7'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         );     player8 = new ZLMRTCClient.Endpoint(             {                 element: document.getElementById('video8'),// video 标签                 debug: true,// 是否打印日志                 zlmsdpUrl:sUrl,//document.getElementById('streamUrl').value,//流地址                 simulcast:false,//document.getElementById('simulcast').checked,                 useCamera:false,//document.getElementById('useCamera').checked,                 audioEnable:true,//document.getElementById('audioEnable').checked,                 videoEnable:true,//document.getElementById('videoEnable').checked,                 recvOnly:true,                             }         ); /**/   }   function start()   {     stop(); start_play();   }   function stop()   {       if(player)       {         player.close();         player = null;       }       if(player1)       {         player1.close();         player1 = null;       }   if(player2)       {         player2.close();         player2 = null;       }   if(player3)       {         player3.close();         player3 = null;       }   if(player4)       {         player4.close();         player4 = null;       }   if(player5)       {         player5.close();         player5 = null;       }   if(player6)       {         player6.close();         player6 = null;       }   if(player7)       {         player7.close();         player7 = null;       }   if(player8)       {         player8.close();         player8 = null;       }   } </script&gt;       <script&gt;       setInterval(function(){ start();},8000);    </script&gt;

**Comment by xia-chu** [comment]
谢谢 这个问题修复了 ， 您看一下
