### ISSUE TITLE
[技术咨询] webrtc中是否支持opus的编码

### ISSUE THREAD

**Issue by poorboy1991** [ZLMediaKit/ZLMediaKit#1029]
- 请问webrtc中是否支持opus的编码，因为在实际媒体协商过程中，返回的sdp音频编码只有pcmu

**Comment by xia-chu** [comment]
当然支持 只是zlm优先选择pcmu而已，因为rtmp rtsp都支持pcmu.你这里调整下优先级即可：
<img width="1183" alt="图片" src="https://user-images.githubusercontent.com/11495632/129135270-aa555308-24b4-4f5f-9326-9a0d6f2c1c1d.png">

**Comment by poorboy1991** [comment]
收到，谢谢大神
