### ISSUE TITLE
[技术咨询]通过wvp无法播放海康摄像头或者NVR的监控实时视频

### ISSUE THREAD

**Issue by zhengweiqing** [ZLMediaKit/ZLMediaKit#1030]
通过wvp无法播放海康摄像头或者NVR的监控实时视频
我的 ZLMediaKit 跟wvp在同一个服务器上，服务器是基于hyper-v的虚拟机，ubuntu20.4
固定IP地址：192.168.110.11
设备已经主动注册到平台上了，在设备列表中可以看到设备，但是无法播放，具体提示如下错误：
![image](https://user-images.githubusercontent.com/50610421/129144422-82b0849b-b8a1-4745-964e-fb467cc0e406.png)

以下是注册设备列表以及配置
![image](https://user-images.githubusercontent.com/50610421/129144754-84070951-ebc4-4b11-b3d6-ba03eb094ecb.png)

![image](https://user-images.githubusercontent.com/50610421/129144727-d482c276-213a-47a7-bd2b-f05be3326536.png)
下边这张是NVR的配置
![image](https://user-images.githubusercontent.com/50610421/129144826-c66d7211-0873-42d3-b573-f50b630b7ea8.png)
下边是wvp的配置文件
`
# [可选] WVP监听的HTTP端口, 网页和接口调用都是这个端口
server:
    port: 18080

# 作为28181服务器的配置
sip:
    # [必须修改] 本机的IP
    ip: 192.168.110.11
    # [可选] 28181服务监听的端口
    port: 5060
    # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基>层编号组成，参照GB/T 2260-2007）
    # 后两位为行业编码，定义参照附录D.3
    # 3701020049标识山东济南历下区 信息行业接入
    # [可选]
    domain: 1304030049
    # [可选]
    id: 13040300492000000001
    # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
    password: admin123

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器的内网IP
    ip: 192.168.110.11
    # [必须修改] zlm服务器的http.port
    http-port: 80
    # [可选] zlm服务器的hook.admin_params=secret
    secret: 035c73f7-bb6b-4889-a715-d9eb2d1925cc
    # 启用多端口模式, 多端口模式使用端口区分每路流，兼容性更好。 单端口使用流的ssrc区分， 点播超时建议使用多端口测试
    rtp:
        # [可选] 是否启用多端口模式, 开启后会在portRange范围内选择端口用于媒体流传输
        enable: true
        # [可选] 在此范围内选择端口用于媒体流传输,
        port-range: 30000,30500 # 端口范围
    # 录像辅助服务， 部署此服务可以实现zlm录像的管理与下载， 0 表示不使用
    record-assist-port: 0

`

**Comment by xia-chu** [comment]
zlmediakit 服务器部署在哪里？部署ip和http端口是多少?

**Comment by zhengweiqing** [comment]
> zlmediakit 服务器部署在哪里？部署ip和http端口是多少?

服务器在本地局域网内，ZLMediaKit跟WVP在同一台服务器上:
服务器用的是ubuntu 20.4
服务器的配置我上边有发出来
服务器IP是：192.168.110.11
http端口是：80

**Comment by xia-chu** [comment]
@zhengweiqing  嗨 问题解决了吗 忘了跟踪这个问题了 抱歉！

**Comment by zhengweiqing** [comment]
@xia-chu 没有解决，找不到问题，放弃了。

**Comment by xia-chu** [comment]
从wvp日志看 zlm的http端口应该不是80
