### ISSUE TITLE
[BUG] MediaServer not work with a strange rtsp url

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#1031]
**bug现象**
- bug产生时服务器的异常行为(例如: 崩溃/无法访问/丢包花屏)
- bug产生时，打印的上下文日志(可以截图或粘贴文本)
- 调试core文件时，崩溃触发点的函数调用栈(可以截图或粘贴文本)

This rtsp source works fine with VLC but can not work with MediaServer and FFPLAY.
VLC wireshark log:
![ảnh](https://user-images.githubusercontent.com/59004953/129174312-b7bdc4df-ad44-48a6-9a92-0913f3c07d98.png)
[vlc_ok.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6974321/vlc_ok.zip)

FFPLAY error screenshot:
![ảnh](https://user-images.githubusercontent.com/59004953/129174547-2a12fc9a-ad36-405b-a163-10adf85618b3.png)

MediaServer log:
[2021-08-12_00.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6974329/2021-08-12_00.zip)
[zlmediaserver.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6974332/zlmediaserver.zip)
[getMediaListAPI.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6974345/getMediaListAPI.zip)

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的什么功能模块？
AddStreamProxy

**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤

**zlm代码git commit hash值**
- git log查看
latest source code

**操作系统环境**
- 什么类型的操作系统，32位，64位？
- 什么cpu类型？
Window10 64 bit, Intel Core i7 8700

**Comment by xia-chu** [comment]
Can you share your rtsp url to me?

**Comment by pubpy2015** [comment]
I sent email to you: 1213642868@qq.com

**Comment by xia-chu** [comment]
thanks, i will test it some later.

**Comment by xia-chu** [comment]
Hi , friend, are you there? I'm sorry to reply you now,  I was a little free some time ago. I tested your URL and can not found problem at that time. Later, I was busy at work and went to do other things. Recently, I was a little idle, but your RTSP URL seems to be unable to play.
Can you update your rtps url?  thanks!

**Comment by pubpy2015** [comment]
Yes, 
Now it's online.
Please check again.

**Comment by xia-chu** [comment]
The rtsp`s sdp is strange：
```sdp
v=0
o=- 0 0 IN IP4 192.168.20.94
s=LIVE VIEW
c=IN IP4 0.0.0.0
t=0 0
a=control:rtsp://210.245.52.48:9554/?inst=1
m=video 0 RTP/AVP 102
a=rtpmap:102 H265/90000
a=rtpmap:35 H264/90000
a=control:rtsp://210.245.52.48:9554/?inst=1&stream=video
a=recvonly
a=fmtp:102 profile-id=4;sprop-vps=QAEMBP//AWAAAAMAgAAAAwAAAwB7AAC95FAk;sprop-sps=QgEEAWAAAAMAgAAAAwAAAwB7AACgA8CAEOWNveRbtTd3NVJf2AtwENAQCA==;sprop-pps=RAHBLKwnBQKZkA==

```

**Comment by xia-chu** [comment]
Now i can not play the rtsp url.

**Comment by pubpy2015** [comment]
Please try again.

**Comment by pubpy2015** [comment]
Thanks,

It's work fine with both H264 and H265 codec.
