### ISSUE TITLE
[BUG]打开webrtc编译有报错

### ISSUE THREAD

**Issue by huiqiaoqiu** [ZLMediaKit/ZLMediaKit#1032]
**bug现象**
最新版本master 分支代码，enable webrtc 配置项时，编译报错

ZLMediaKit/webrtc/DtlsTransport.cpp:599:46: error: ‘DTLS_set_timer_cb’ was not declared in this scope
   DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);

**bug产生时的使用场景**
- webrtc

**操作系统环境**
- ubuntu

**Comment by huiqiaoqiu** [comment]
应该时openssl版本问题，我再尝试一下

**Comment by huiqiaoqiu** [comment]
更新openssl版本可以搞定，参考 [https://blog.csdn.net/haysonzeng/article/details/116754065](url)

**Comment by xia-chu** [comment]
嗯 是的 webrtc相关功能对openssl版本有要求

**Comment by xianchuhan** [comment]
centos7下打开webrtc开关，编译遇到上述问题，将openssl升级到了1.1.1，然后重新编译，但是又遇到了如下问题，编译zltoolkit报错，如下： 
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::SSL_Initor()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:46: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:47: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:48: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:49: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:50: undefined reference to `OPENSSL_init_crypto'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::setupCtx(ssl_ctx_st*)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:210: undefined reference to `SSL_CTX_set_options'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Box::flush()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:449: undefined reference to `SSL_is_init_finished'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::makeSSLContext(std::vector<std::shared_ptr<x509_st>, std::allocator<std::shared_ptr<x509_st> > > const&, std::shared_ptr<evp_pkey_st> const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_server_method'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_client_method'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::cryptWithRsaPublicKey(x509_st*, std::string const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:311: undefined reference to `X509_get0_pubkey'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/test_wsServer] Error 1

[ 83%] Linking CXX executable ../../release/linux/Debug/test_server
../../release/linux/Debug/libzlmediakit.a(RtmpProtocol.cpp.o): In function `openssl_HMACsha256(void const*, unsigned long, void const*, unsigned long)':
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:36: undefined reference to `HMAC_CTX_new'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:37: undefined reference to `HMAC_CTX_reset'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:41: undefined reference to `HMAC_CTX_reset'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:42: undefined reference to `HMAC_CTX_free'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::SSL_Initor()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:46: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:47: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:48: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:49: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:50: undefined reference to `OPENSSL_init_crypto'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::setupCtx(ssl_ctx_st*)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:210: undefined reference to `SSL_CTX_set_options'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Box::flush()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:449: undefined reference to `SSL_is_init_finished'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::makeSSLContext(std::vector<std::shared_ptr<x509_st>, std::allocator<std::shared_ptr<x509_st> > > const&, std::shared_ptr<evp_pkey_st> const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_server_method'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_client_method'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::cryptWithRsaPublicKey(x509_st*, std::string const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:311: undefined reference to `X509_get0_pubkey'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/test_rtp] Error 1
make[1]: *** [tests/CMakeFiles/test_rtp.dir/all] Error 2
[ 83%] Building CXX object api/CMakeFiles/mk_api.dir/source/mk_h264_splitter.cpp.o
[ 83%] Building CXX object api/CMakeFiles/mk_api.dir/source/mk_httpclient.cpp.o
[ 84%] Building CXX object api/CMakeFiles/mk_api.dir/source/mk_media.cpp.o
../../release/linux/Debug/libzlmediakit.a(RtmpProtocol.cpp.o): In function `openssl_HMACsha256(void const*, unsigned long, void const*, unsigned long)':
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:36: undefined reference to `HMAC_CTX_new'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:37: undefined reference to `HMAC_CTX_reset'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:41: undefined reference to `HMAC_CTX_reset'
/root/hxy/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:42: undefined reference to `HMAC_CTX_free'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::SSL_Initor()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:46: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:47: undefined reference to `OPENSSL_init_ssl'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:48: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:49: undefined reference to `OPENSSL_init_crypto'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:50: undefined reference to `OPENSSL_init_crypto'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Initor::setupCtx(ssl_ctx_st*)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:210: undefined reference to `SSL_CTX_set_options'
../../release/linux/Debug/libzltoolkit.a(SSLBox.cpp.o): In function `toolkit::SSL_Box::flush()':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLBox.cpp:449: undefined reference to `SSL_is_init_finished'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::makeSSLContext(std::vector<std::shared_ptr<x509_st>, std::allocator<std::shared_ptr<x509_st> > > const&, std::shared_ptr<evp_pkey_st> const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_server_method'
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:171: undefined reference to `TLS_client_method'
../../release/linux/Debug/libzltoolkit.a(SSLUtil.cpp.o): In function `toolkit::SSLUtil::cryptWithRsaPublicKey(x509_st*, std::string const&, bool)':
/root/hxy/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SSLUtil.cpp:311: undefined reference to `X509_get0_pubkey'
collect2: error: ld returned 1 exit status
make[2]: *** [../release/linux/Debug/test_server] Error 1
make[1]: *** [tests/CMakeFiles/test_server.dir/all] Error 2

**Comment by xianchuhan** [comment]
是不是zlToolKit库用的openssl函数是1.0的，然后升级到1.1后，1.1中这些函数名称已经变了？

**Comment by xia-chu** [comment]
@xianchuhan 这是原因是你的系统上安装了一老一新的openssl，但是cmake查找到了新版本的openssl头文件，但是链接的却是老版本的库

**Comment by xianchuhan** [comment]
@xia-chu非常感谢，我把ZLMediaKit代码删除掉，然后重新拉了一份代码，按照wiki中的描述搞定了，如下：https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97
![image](https://user-images.githubusercontent.com/82028984/144384703-a2c3f34f-d1ac-4b9d-8475-884cdeb59121.png)
