### ISSUE TITLE
点播的问题[BUG]

### ISSUE THREAD

**Issue by jiang6883** [ZLMediaKit/ZLMediaKit#1036]
**bug现象**
- 实测点播文件超过3G的时候，文件无法点播。
？

**Comment by xia-chu** [comment]
嗯 应该可能有这个问题，好像用的api是32bit的。需要测试下才行，你测试大文件吗？

**Comment by xia-chu** [comment]
你是什么系统

**Comment by jiang6883** [comment]
是windows10的系统，编译的是32位的




***@***.***
 
发件人： 夏楚
发送时间： 2021-08-13 16:31
收件人： ZLMediaKit/ZLMediaKit
抄送： jiang6883; Author
主题： Re: [ZLMediaKit/ZLMediaKit] 点播的问题[BUG] (#1036)
你是什么系统
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
