### ISSUE TITLE
[技术咨询]请问怎么知道录播的时间

### ISSUE THREAD

**Issue by IOTOSPaaS** [ZLMediaKit/ZLMediaKit#1042]
请问录播查询结果，像这种文件名是存在某种规则吗？是创建时间点吗？那请问怎么理解？时-分-秒？
"22-20-30.mp4",
 "22-13-12.mp4",
 "21-57-07.mp4",
 "21-19-18.mp4",
 "21-24-21.mp4",
 "21-15-10.mp4",
 "22-14-14.mp4"

**Comment by xia-chu** [comment]
很明显是的。
