### ISSUE TITLE
[技术咨询]怎样去除announce和record方法？

### ISSUE THREAD

**Issue by jim-king-2000** [ZLMediaKit/ZLMediaKit#1044]
ZLMediaKit貌似支持annource和record这两个方法。那有没有办法去除对这两个方法的支持？

**Comment by xia-chu** [comment]
为什么去除？ 你鉴权时 不允许rtsp推流即可

**Comment by jim-king-2000** [comment]
去除这两个方法是客户的需求。客户说有这两个方法，他们的播放器就无法拉流。有没有可能在不修改源代码的情况下，在options方法中返回的list里面不要包含这两个方法？

> 你在推流鉴权hook中 回复不允许rtsp推流即可

这句没看懂。我们需要rtsp推流啊。

**Comment by xia-chu** [comment]
哦 我以为你你想关闭服务器的推流功能。
你们客户端的播放器有点奇怪啊，这个都能影响播放。

**Comment by xia-chu** [comment]
这里你自己修改下就行了
https://github.com/ZLMediaKit/ZLMediaKit/blob/7b60f8b0936566965c9448020a81482746f233e1/src/Rtsp/RtspSession.cpp#L207

**Comment by jim-king-2000** [comment]
好的，十分感谢。
