### ISSUE TITLE
RTSP地址中有“+”，加号会被替换成空格，导致RTSP请求失败

### ISSUE THREAD

**Issue by seamende** [ZLMediaKit/ZLMediaKit#1045]
通过华为的接口取到了RTSP-URL，但是URL中有“+”字符，url传到了FFMpegSource.cpp的Play函数后，“+”字符被替换成空格，导致取流失败。
华为的地址如下：
rtsp://192.168.10.111:554/03242840536580260101?DstCode=01&ServiceType=4&ClientType=1&StreamID=1&SrcTP=2&DstTP=2&SrcPP=0&DstPP=1&MediaTransMode=0&BroadcastType=0&SV=0&TimeSpan=20210802T040000Z-20210804T040000Z&Token=X-ZV7ODFywnOXnLQ4p7k9HxerN2vf4fZ&Multiplex=kE2IHWUV1a70UfCSrg5+I99sbhYvTLxm&DomainCode=d3ce15416a76417987af0a3d8871a81f&UserId=17&

传到Play函数里面后的地址如下：
rtsp://192.168.10.111:554/03242840536580260101?DstCode=01&ServiceType=4&ClientType=1&StreamID=1&SrcTP=2&DstTP=2&SrcPP=0&DstPP=1&MediaTransMode=0&BroadcastType=0&SV=0&TimeSpan=20210802T040000Z-20210804T040000Z&Token=X-ZV7ODFywnOXnLQ4p7k9HxerN2vf4fZ&Multiplex=kE2IHWUV1a70UfCSrg5 99sbhYvTLxm&DomainCode=d3ce15416a76417987af0a3d8871a81f&UserId=17

ZLM的日志文件内容如下：

2021-08-17 06:44:49.946 T MediaServer[227953-event poller 0] HttpSession.cpp:25 HttpSession | 140429727112128(192.168.239.1:1157) 
2021-08-17 06:44:49.946 I MediaServer[227953-event poller 0] FFmpegSource.cpp:86 play | rtsp://192.168.10.111:554/03242840536580260101?DstCode=01&ServiceType=4&ClientType=1&StreamID=1&SrcTP=2&DstTP=2&SrcPP=0&DstPP=1&MediaTransMode=0&BroadcastType=0&SV=0&TimeSpan=20210802T040000Z-20210804T040000Z&Token=X-ZV7ODFywnOXnLQ4p7k9HxerN2vf4fZ&Multiplex=kE2IHWUV1a70UfCSrg5 I99sbhYvTLxm&DomainCode=d3ce15416a76417987af0a3d8871a81f&UserId=17&
2021-08-17 06:44:49.947 I MediaServer[227953-event poller 0] Process.cpp:148 run | start child process 228107, log file:/home/zxq/ZLMediaKit/release/linux/ffmpeg/ffmpeg.log.228107
2021-08-17 06:44:49.947 I MediaServer[227953-event poller 0] FFmpegSource.cpp:90 play | /usr/bin/ffmpeg -re -i rtsp://192.168.10.111:554/03242840536580260101?DstCode=01&ServiceType=4&ClientType=1&StreamID=1&SrcTP=2&DstTP=2&SrcPP=0&DstPP=1&MediaTransMode=0&BroadcastType=0&SV=0&TimeSpan=20210802T040000Z-20210804T040000Z&Token=X-ZV7ODFywnOXnLQ4p7k9HxerN2vf4fZ&Multiplex=kE2IHWUV1a70UfCSrg5 I99sbhYvTLxm&DomainCode=d3ce15416a76417987af0a3d8871a81f&UserId=17& -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv rtmp://127.0.0.1/live/test
2021-08-17 06:44:59.948 D MediaServer[227953-event poller 0] WebApi.cpp:228 http api debug | 
# request:
GET /index/api/addFFmpegSource?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&src_url=rtsp://192.168.10.111:554/03242840536580260101?DstCode=01%26ServiceType=4%26ClientType=1%26StreamID=1%26SrcTP=2%26DstTP=2%26SrcPP=0%26DstPP=1%26MediaTransMode=0%26BroadcastType=0%26SV=0%26TimeSpan=20210802T040000Z-20210804T040000Z%26Token=X-ZV7ODFywnOXnLQ4p7k9HxerN2vf4fZ%26Multiplex=kE2IHWUV1a70UfCSrg5+I99sbhYvTLxm%26DomainCode=d3ce15416a76417987af0a3d8871a81f%26UserId=17%26&dst_url=rtmp://127.0.0.1/live/test&timeout_ms=10000&enable_hls=0&enable_mp4=0
# header:
Accept : */*
Accept-Encoding : gzip, deflate, br
Connection : keep-alive
Host : 192.168.239.128:8090
Postman-Token : a5e37fd9-d276-46a3-812c-d5a1339144b5
User-Agent : PostmanRuntime/7.28.3
# content:

# response:
{
   "code" : -1,
   "msg" : "等待超时"
}

**Comment by seamende** [comment]
通过调试发发现，下面的函数把Rtsp-Url中的“+”字符替换成了空格，请教一下，这个处理是有其他用途吗？可不可以去掉？
string strCoding::UrlDecode(const string &str) {
    string output = "";
    char tmp[2];
    size_t i = 0, len = str.length();
    while (i < len) {
        if (str[i] == '%') {
            if(i > len - 3){
                //防止内存溢出
                break;
            }
            tmp[0] = str[i + 1];
            tmp[1] = str[i + 2];
            output += StrToBin(tmp);
            i = i + 3;
        } else if (str[i] == '+') {
            output += ' ';
            i++;
        } else {
            output += str[i];
            i++;
        }
    }
    return output;
}

**Comment by seamende** [comment]
上面的函数在StrCoding.cpp文件中

**Comment by xia-chu** [comment]
rtsp url作为http参数 是要转义的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seamende ***@***.***&gt;
发送时间: 2021年8月17日 22:25
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] RTSP地址中有“+”，加号会被替换成空格，导致RTSP请求失败 (#1045)





 
通过调试发发现，下面的函数把Rtsp-Url中的“+”字符替换成了空格，请教一下，这个处理是有其他用途吗？可不可以去掉？
 string strCoding::UrlDecode(const string &amp;str) {
 string output = "";
 char tmp[2];
 size_t i = 0, len = str.length();
 while (i < len) {
 if (str[i] == '%') {
 if(i &gt; len - 3){
 //防止内存溢出
 break;
 }
 tmp[0] = str[i + 1];
 tmp[1] = str[i + 2];
 output += StrToBin(tmp);
 i = i + 3;
 } else if (str[i] == '+') {
 output += ' ';
 i++;
 } else {
 output += str[i];
 i++;
 }
 }
 return output;
 }

**Comment by seamende** [comment]
请教一下如何转义？我加反斜杠也不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月17日(周二) 晚上11:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZLMediaKit/ZLMediaKit] RTSP地址中有“+”，加号会被替换成空格，导致RTSP请求失败 (#1045)




 rtsp url作为http参数 是要转义的 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: seamende ***@***.***&amp;gt; 
 发送时间: 2021年8月17日 22:25 
 收件人: ZLMediaKit/ZLMediaKit ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[ZLMediaKit/ZLMediaKit] RTSP地址中有“+”，加号会被替换成空格，导致RTSP请求失败 (#1045) 
 
 
 
 
 
   
 通过调试发发现，下面的函数把Rtsp-Url中的“+”字符替换成了空格，请教一下，这个处理是有其他用途吗？可不可以去掉？ 
  string strCoding::UrlDecode(const string &amp;amp;str) { 
  string output = ""; 
  char tmp[2]; 
  size_t i = 0, len = str.length(); 
  while (i < len) { 
  if (str[i] == '%') { 
  if(i &amp;gt; len - 3){ 
  //防止内存溢出 
  break; 
  } 
  tmp[0] = str[i + 1]; 
  tmp[1] = str[i + 2]; 
  output += StrToBin(tmp); 
  i = i + 3; 
  } else if (str[i] == '+') { 
  output += ' '; 
  i++; 
  } else { 
  output += str[i]; 
  i++; 
  } 
  } 
  return output; 
  } 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang2349** [comment]
urlencode
