### ISSUE TITLE
[技术咨询]延迟问题

### ISSUE THREAD

**Issue by RippleSoul** [ZLMediaKit/ZLMediaKit#1048]
**咨询的功能模块**
实时播放

**咨询的具体内容和问题**
flv播放器断开播放重启根据播放地址播放延迟在3秒左右，如果不断开一直播放延迟在1秒左右，网络环境在局域网下

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你看到的延时往往是GOP缓存。GOP缓存大小完全看运气，最多增大一个GOP缓存的延时，如果运气好，正好碰到关键帧，那么GOP缓存延时就很低。建议用低延时播放器测试延时，也可以看看wiki关于延时的文章。
