### ISSUE TITLE
[技术咨询]录像功能

### ISSUE THREAD

**Issue by lixiaolang12000** [ZLMediaKit/ZLMediaKit#1049]
请问如何才能停止录像呢，www/record目录下会一直写文件，磁盘很快就满了

**Comment by xia-chu** [comment]
默认不录制



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lixiaolang12000 ***@***.***&gt;
发送时间: 2021年8月17日 21:37
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]录像功能 (#1049)





 
请问如何才能停止录像呢，www/record目录下会一直写文件，磁盘很快就满了

**Comment by zhang2349** [comment]
wvp的配置是录制把

**Comment by answer666** [comment]
你好，我也碰到了，这个问题，请问你怎么解决的啊？
