### ISSUE TITLE
[BUG]MediaServer的openRtpServer接口重复开启端口问题

### ISSUE THREAD

**Issue by HuangRL1989** [ZLMediaKit/ZLMediaKit#1050]
**bug现象**
openRtpServer指定流id申请端口。导致端口重复申请。
另外，特意在centos上测试了半天，好像没发现同样的现象。

**bug产生时的使用场景**
使用MediaServer开启rtp端口接收国标流。

**bug是否可以复现，怎么复现**
陆续openRtpServer2路接收国标流，每隔40秒closeRtpServer，再开openRtpServer2路，一定概率会出现。2路间隔不一定，10+秒，30+秒都有概率。

**zlm代码git commit hash值**
commit 7375889b2e82e921b0273c382cacd1b36db45af6 (HEAD -> 6.0, origin/6.0)

**操作系统环境**
win64位
Intel i7-11700

**Comment by zhang2349** [comment]
因为启用了resue 你传0 open的话 好像是会重复

**Comment by xia-chu** [comment]
> 因为启用了resue 你传0 open的话 好像是会重复

这个确实可能是个bug

**Comment by zhang2349** [comment]
简单测试了下 Windows下 tcp udp都不会重复
CentOS7下 tcp不会重复 udp会重复

**Comment by denniste** [comment]
好象我这里也是会重复，特别是在window下。不设置 reuseport 又不行，等待 close_wait 会等死。反正 openRtpServer中是有锁的，会顺序执行， 所以，我做了个预选, 先 做一个 socket tcp listen, closesocket后 再做个 socket udp bind ，再closesocket ，其间不做任何 setsockctopt 操作。拿到 port 后如果不是偶数就再+1做一次。把这个port 做为后续的 rtpServer的start 参数。目前，好象没有重复了。。反正这段代码不会影响任何现有的代码，等将来夏老大修正了问题，就拿掉它。

**Comment by chatop2020** [comment]
这个情况貌似是一直存在，当初出现rtp串流不知道是不是这个原因造成的
后来为了解决这个问题，我让AKStream接管了udp，tcp端口的分配，openrtpserver的时候，指定端口，后来就没出现过这个问题了。
现在找到原因了，那最好了。

**Comment by xia-chu** [comment]
这个提交应该修复改问题了：6e445614

**Comment by xia-chu** [comment]
先关闭了
