### ISSUE TITLE
一、请问rtsp 协议，我想使用 udp 推流，在哪个参数控制选择呢？二、rtsp花屏严重 [技术咨询]

### ISSUE THREAD

**Issue by dongrixinyu** [ZLMediaKit/ZLMediaKit#1051]
**咨询的功能模块**
- rtsp 推流功能

**咨询的具体内容和问题**
#### 1、rtsp 推流的 udp 设置
- 用 ffmpeg 推流，命令为
```ffmpeg -re -i cut_bb.mp4 -vcodec libx264 -f rtsp -rtsp_transport tcp rtsp://192.168.11.137:8554/live/streamid```
- zlm采用 docker 直接启动
- 用 tcp 播放是成功的，但是非常卡，花屏严重。
- 我想问一下，**改哪里可以成功启用  udp 的方式。**

#### 2、rtsp播放太卡顿花屏了
- 网络为局域网
- 用rtmp推流，播放很流畅，但是用 rtsp(tcp) 推流播放出来，就非常卡，视频图像稍微运动，就花了。
- **请问这种花屏问题的在rtsp 协议本身呢？还是还需要继续对rtsp 进行代码上的优化和改进？**

- 用 vlc 统计了一下，局域网环境，rtsp 播放，4400帧，丢帧129帧，rtmp播放，5640帧丢帧1帧。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
按道理 tcp推流不会丢包和花屏的，你强调docker 难道非docker没问题吗？

**Comment by jim-king-2000** [comment]
RTSP over TCP是不会花屏的。你是不是用了H.265？H.265的RTSP流在VLC上会花屏。换MPV播放器就好了。

**Comment by jim-king-2000** [comment]
还有一种可能就是，网络带宽不够。在我们千兆局域网环境，基本上一帧都不会丢。

**Comment by dongrixinyu** [comment]
> RTSP over TCP是不会花屏的。你是不是用了H.265？H.265的RTSP流在VLC上会花屏。换MPV播放器就好了。

我找到问题了，播放换 rtmp 就可以了，播放器对rtsp 的支持很差导致的。
另外我想问一下rtsp 的传输在框zlm架里如何切换成 udp 的传输方式呢？

**Comment by jim-king-2000** [comment]
> 另外我想问一下rtsp 的传输在框zlm架里如何切换成 udp 的传输方式呢？

这个需要在播放器里设置。不过UDP不是很稳定，个人不推荐。

**Comment by dongrixinyu** [comment]
> > 另外我想问一下rtsp 的传输在框zlm架里如何切换成 udp 的传输方式呢？
> 
> 这个需要在播放器里设置。不过UDP不是很稳定，个人不推荐。

谢谢，也就是，不论rtsp 推流 tcp 和 udp，zlm 都可以自动接收，不用配置什么文件参数的吗？

**Comment by jim-king-2000** [comment]
> 谢谢，也就是，不论rtsp 推流 tcp 和 udp，zlm 都可以自动接收，不用配置什么文件参数的吗？

是的。

**Comment by xia-chu** [comment]
用什么方式传输是客户端决定的
