### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xlsky0713** [ZLMediaKit/ZLMediaKit#1058]
**启用ffmpeg进程进行转码，主进程直接挂掉了**
- 主进程被杀，导致服务无法正常工作
- 日志记录
![图片](https://user-images.githubusercontent.com/17897913/130316487-b27fa51e-fad7-465d-9b7f-fbe5d690ed06.png)

**bug产生时的使用场景**
- 对H265国标流调用 addFFmpeg 接口进行转码

**bug是否可以复现，怎么复现**
- 在我的环境一直可以复现，只要调用转码接口，进程会被杀
- 
**zlm代码git commit hash值**
-  0821 更新的最新代码 
- commit ce41fa268ef208bb09b82893fc76eaf7cb0b7d8f (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: 夏楚 <771730766@qq.com>
Date:   Fri Aug 20 16:03:41 2021 +0800

    Merge pull request #1053 from johzzy/master
    
    fix stun packet memory leak.

**操作系统环境**
-  Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-27-generic x86_64)

**Comment by xia-chu** [comment]
在fork FFmpeg进程时，如果你是前台运行zlm的 会导致zlm进程挂起，这个可以通过nohub运行解决这个问题。在wiki 服务器启动关闭篇有相关描述。

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%AF%E5%8A%A8%E4%B8%8E%E5%85%B3%E9%97%AD

**Comment by xia-chu** [comment]
至于为什么被挂起 现在原因还不明。

**Comment by xlsky0713** [comment]
感谢大佬，确实是这个问题，采勇nohup之后问题解决
