### ISSUE TITLE
[BUG]windows 10 64位录像功能重命名问题。

### ISSUE THREAD

**Issue by xilidedashu** [ZLMediaKit/ZLMediaKit#1061]
**bug现象**
- 视频录制有时获取不到录制的时长，而且不能播放。
- 没有异常的日志，程序正常运行。

**bug产生时的使用场景**
- 使用视频录制的接口进行录制功能，调用录制完成接口，接口返回状态录制完成，但是没有录制的时长，且无法播放。

**bug是否可以复现，怎么复现**
- 不定期偶发现象，而且是一段时间，在多次重启之后可以恢复。

**zlm代码git commit hash值**
- 无

**操作系统环境**
- windows 10 家庭版 64位操作系统？
- X86_64架构？

经查看，应该是录像文件的文件名没有更改过来，但是录像的状态是已经录制完成。
![image](https://user-images.githubusercontent.com/26021385/130378172-6739acef-b874-441e-84da-612153a12795.png)

**Comment by xilidedashu** [comment]
是的，正常情况下会该文件名，但是有时候，录制的状态显示完成了，但是录制的时间显示为0。

**Comment by xia-chu** [comment]
录制的时间显示为0？ 哪里？

**Comment by xilidedashu** [comment]
在zlmediakit录制完成的事件回调里面，time_len这个参数，返回的是0。

**Comment by xia-chu** [comment]
那文件多大

**Comment by xilidedashu** [comment]
文件有大有小，小的几兆，大的有几十兆这样。

**Comment by xia-chu** [comment]
理论上不太可能，我检查过源码， 是通过录制结束时间减去 录制开始时间得出 time_len这个参数的，通过函数time(NULL)获取系统时间戳的，难道你系统时间戳有问题？
