### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by malaohu** [ZLMediaKit/ZLMediaKit#1063]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
海康摄像头rtsp转码后浏览器无法播放

**咨询的具体内容和问题**
海康摄像头 rtsp -> flv 后，VLC可以播放有声音，但是网页不能播放。
按照大佬之前回复的内容，设置了
enable_audio=0

现在可以播放了，但是没有声音。请问大佬这个有解决方案吗？

**Comment by xia-chu** [comment]
说明音频编码不是aac.非aac编码的音频不能通过基于mse的播放器播放，可以用wasm 方案的播放器播放。
