### ISSUE TITLE
[技术咨询][使用咨询]question：有子码流这个功能吗

### ISSUE THREAD

**Issue by iclearwater** [ZLMediaKit/ZLMediaKit#1064]
页面在调用ifream时候内网速率还可以，外网会有一帧一帧的卡顿，是否有子码流这个功能，通过降低清晰度来保证视频通畅性

**Comment by iclearwater** [comment]
或者我该怎么配置能实现子码流这个效果

**Comment by xfdbse** [comment]
zlm不支持。

**Comment by iclearwater** [comment]
![image](https://user-images.githubusercontent.com/24544043/130756721-fac506bc-e81c-49dd-945e-5baecc9f5b33.png)
还有 这种雪花和卡顿是什么问题呢？

**Comment by justdoitgo** [comment]
> 或者我该怎么配置能实现子码流这个效果

兄弟，子码流配置好了么？

**Comment by xia-chu** [comment]
> > 或者我该怎么配置能实现子码流这个效果
> 
> 兄弟，子码流配置好了么？

没有 上面 @xfdbse 已经答复解决方案了
