### ISSUE TITLE
[技术咨询]录制gb28181流为HLS，实际录制到的时间要短，像是缺失了一部分。

### ISSUE THREAD

**Issue by ganttee** [ZLMediaKit/ZLMediaKit#1069]
**咨询的功能模块**
- GB28181
- HLS

**咨询的具体内容和问题**
- MediaServer接RTP流，然后保存为HLS。同时使用tcpdump抓了RTP流。
- 统计以后发现，保存下来的HLS的时间要比RTP流的时间要少

理论上来说，时间应该是一致的。

**Comment by xia-chu** [comment]
嗨， 不好意思，你的issue不小心遗漏，现在才答复。
gb28181 rtp流一般是ps流，有两个时间戳的，一个是rtp的时间戳，一个是ps的时间戳，
ps的时间戳才是准确的，rtp的时间戳其实可以乱写。所以你说的RTP流的时间什么rtp时间戳的增量吗
