### ISSUE TITLE
[技术咨询]拉流播放延迟问题，附测试结果

### ISSUE THREAD

**Issue by vjimrunning** [ZLMediaKit/ZLMediaKit#1071]
**咨询的功能模块**
- 大华摄像头RTSP拉流播放延迟问题

**咨询的具体内容和问题**
- 网络环境
  内网网络环境如下图：
[![hMeNQA.png](https://z3.ax1x.com/2021/08/27/hMeNQA.png)](https://imgtu.com/i/hMeNQA)

- 系统信息
  其中播放器所在系统为win10操作系统，流媒体服务器所在的系统为centos 7.4；
  zlm为5月30日获取代码自行编译版本；目前基本使用默认配置；
- 测试过程
  其中ffplay的使用方式类似：ffplay -i rtmp://192.168.1.69/live/777 -fflags nobuffer
  时间数据采用本项目 wiki 中介绍在线秒表对比方式获取得到；

- 测试结果
  
|测试方式 |流媒体服务器 |媒体源|播放器 |流格式|视频质量 | 延迟（约数）
|:-|:-:|:-:|:-:|:-:|:-:|:-:|
|摄像头官方管理页面查看|无|大华摄像头|大华网页播放器|rtsp|1080P|200ms
|使用ffplay直接查看源视频|无|大华摄像头|ffplay|rtmp|1080P|600ms
|使用ffplay查看rtmp|ZLM|本机OBS推流|ffplay|rtmp|1080P|300ms
|使用easyplayer查看|ZLM|本机OBS推流|easyplayer|ws-flv|1080P|300ms
|使用ffplay查看rtmp|ZLM|大华摄像头|ffplay|rtmp|1080P|1.5s
|使用ffplay查看http-flv|ZLM|大华摄像头|ffplay|http-flv|1080P|1.5s
|使用ffplay查看http-flv|ZLM|大华摄像头|ffplay|http-flv|720P|1.5s
|使用easyplayer查看|ZLM|大华摄像头|easyplayer|ws-flv|1080P|1.5s
|使用h5stream查看|h5stream|大华摄像头|h5steam|ws-flv|1080P|600ms
|使用h5stream查看|h5stream|大华摄像头|h5steam|ws-flv|720P|600ms

不知当前还可以在哪个层面进一步优化系统设置，减少播放时延；

**Comment by vjimrunning** [comment]
> 
> 
> 有没有尝试用zlm提供的test_player播放器测试延时？ 非常感谢你提供这么详实的测试数据！

       最开始顺手使用ffplay来测试本机推流，时延结果是符合预期，只是对接上摄像头之后时延结果有了一个明显的差异，然后对比其他几个场景后判断播放器来带的影响权重不高，最后才聚焦到了zlm本身的优化上了，目前暂时没有使用test_play进行测试；
      不知判断是否有误？另外优化的方向应该如何入手还望各位不吝赐教！团队技术栈目前以java为主

**Comment by jiechengyang** [comment]
mac环境，本地rtp 丢包严重，花屏 如何优化

**Comment by xia-chu** [comment]
@vjimrunning 播放器缓存对延时影响非常大，所以要避免干扰你可以用test_player播放 或者用zlm转的webrtc播放

**Comment by xia-chu** [comment]
> mac环境，本地rtp 丢包严重，花屏 如何优化

调整下系统参数 socket读缓存大小

**Comment by iAoe444** [comment]
## 拉流播放延迟问题更新

@xia-chu 开发大大你好，关于上述rtsp拉流播放延迟问题我也在同步跟进，这些天在进行实验的时候发现可能存在的原因：
   
 ```
zlm在rtsp转rtmp的过程产生了延迟
```

* 实验过程：

![](http://assest.iaoe.xyz/blog/20210901110505.png)

* ffmpeg转封装命令：
```bash
ffmpeg -i {src} -c copy -f flv rtmp://127.0.0.1:1935/live/999
```

* zlm拉流命令：`addStreamProxy`

实验结果发现延迟原因是zlm在rtsp转rtmp的过程发生了延迟，请问是否有这种可能性？
