### ISSUE TITLE
[技术咨询] onRtmpChunk | can not support cmd:|RtmpSampleAccess

### ISSUE THREAD

**Issue by mingkof** [ZLMediaKit/ZLMediaKit#1072]
**咨询的功能模块**
addStreamProxy 

**咨询的具体内容和问题**
拉 海康安防平台中 RTMP 格式的流，使用ffplay 该rtmp流可以正常播放的。转 hls 时，视频流数据不会增加，一会儿又重新开始，查看后台日志发现  **“onRtmpChunk | can not support cmd:|RtmpSampleAccess”**，是什么原因？有什么办法解决
RtmpPlayer.cpp:24 ~RtmpPlayer | 
RtmpPlayer.cpp:60 play | 8.8.8.8:1935 vod openUrl/OsOG4FO
RtmpProtocol.cpp:725 handle_chunk | MSG_WIN_SIZE:2500000
RtmpProtocol.cpp:732 handle_chunk | MSG_SET_PEER_BW:2500000
RtmpProtocol.cpp:692 handle_chunk | CONTROL_STREAM_BEGIN:0
RtmpProtocol.cpp:654 handle_chunk | MSG_SET_CHUNK:4096
RtmpProtocol.cpp:654 handle_chunk | MSG_SET_CHUNK:4096
RtmpProtocol.cpp:692 handle_chunk | CONTROL_STREAM_BEGIN:1
**RtmpPlayer.cpp:368 onRtmpChunk | can not support cmd:|RtmpSampleAccess**
RtmpPlayer.cpp:100 onPlayResult_l | 0 play rtmp success
MediaSource.cpp:414 emitEvent | 媒体注册:hls __defaultVhost__ live test22
MediaSource.cpp:414 emitEvent | 媒体注册:rtmp __defaultVhost__ live test22

**Comment by mingkof** [comment]
目前使用 FFmpeg 拉流的方式 解决
FFmpeg 命令行参数中 增加  **-flvflags no_duration_filesize**

**Comment by xia-chu** [comment]
这条日志打印：RtmpPlayer.cpp:368 onRtmpChunk | can not support cmd:|RtmpSampleAccess
其他没影响的 不影响使用

**Comment by mingkof** [comment]
> 这条日志打印：RtmpPlayer.cpp:368 onRtmpChunk | can not support cmd:|RtmpSampleAccess
> 其实没影响的 不影响使用

我用 FFmpeg 拉流的方式 解决 ，增加 -flvflags no_duration_filesize

**Comment by xia-chu** [comment]
> > 这条日志打印：RtmpPlayer.cpp:368 onRtmpChunk | can not support cmd:|RtmpSampleAccess
> > 其实没影响的 不影响使用
> 
> 我用 FFmpeg 拉流的方式 解决 ，增加 -flvflags no_duration_filesize ，不知道这个参数在您的代码中是否使用。

没啥用，这些东西都不是很重要。你只要能实现rtmp推流和rtmp播放就行，其他都是些不重要的特性的
