### ISSUE TITLE
[技术咨询]api调用问题

### ISSUE THREAD

**Issue by wangwyForNewTime** [ZLMediaKit/ZLMediaKit#1073]
或许有些愚蠢，但是可否演示一下如何调用 api_regist("/index/api/openRtpServer",[](API_ARGS_MAP)，把拉到的流通过国标推出去呢，我看了wiki和代码，但是不知道接口代码应该如何调用，可否演示一下呢

**Comment by wasphin** [comment]
相关接口可以参考这里的配置, 使用的 postman, 可以了解下基本用法.
https://github.com/ZLMediaKit/ZLMediaKit/tree/master/postman

推送国标流应该是调用 `startSendRtp`, 你提的那个应该是接收国标流.

**Comment by wangwyForNewTime** [comment]
> 相关接口可以参考这里的配置, 使用的 postman, 可以了解下基本用法.
> https://github.com/ZLMediaKit/ZLMediaKit/tree/master/postman
> 
> 推送国标流应该是调用 `startSendRtp`, 你提的那个应该是接收国标流.

你好，谢谢你的回复。
我今天下载了postman，然后按照[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81)进行参数配置但遇到了一些问题。

我使用ffmpeg进行rtp推流：
`ffmpeg -re -i C:/Users/wwy/Desktop/12.mp4 -vcodec h264 -acodec aac -f rtp_mpegts rtp://127.0.0.1:10000`
然后MediaServer反应如下：
```
2021-08-29 17:01:16.368 I MediaServer.exe[17740-15132] MediaSource.cpp:414 emitEvent | 媒体注册:rtsp __defaultVhost__ rtp EAC23469
2021-08-29 17:01:16.371 I MediaServer.exe[17740-15132] MediaSource.cpp:414 emitEvent | 媒体注册:ts __defaultVhost__ rtp EAC23469
```
我使用vlc进行播放，url为rtsp://127.0.0.1:554/rtp/EAC23469，播放正常，然后我更改postman里面的参数，app改为rtp，stream改为EAC23469，GET最终的url为
`http://127.0.0.1/index/api/startSendRtp?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=rtp&stream=EAC23469&ssrc=1&dst_url=127.0.0.1&dst_port=10000&is_udp=0`
点击send，但是出现了404，请问我有哪块做得不对嘛？

**Comment by wangwyForNewTime** [comment]
> > 相关接口可以参考这里的配置, 使用的 postman, 可以了解下基本用法.
> > https://github.com/ZLMediaKit/ZLMediaKit/tree/master/postman
> > 推送国标流应该是调用 `startSendRtp`, 你提的那个应该是接收国标流.
> 
> 你好，谢谢你的回复。
> 我今天下载了postman，然后按照[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81)进行参数配置但遇到了一些问题。
> 
> 我使用ffmpeg进行rtp推流：
> `ffmpeg -re -i C:/Users/wwy/Desktop/12.mp4 -vcodec h264 -acodec aac -f rtp_mpegts rtp://127.0.0.1:10000`
> 然后MediaServer反应如下：
> 
> ```
> 2021-08-29 17:01:16.368 I MediaServer.exe[17740-15132] MediaSource.cpp:414 emitEvent | 媒体注册:rtsp __defaultVhost__ rtp EAC23469
> 2021-08-29 17:01:16.371 I MediaServer.exe[17740-15132] MediaSource.cpp:414 emitEvent | 媒体注册:ts __defaultVhost__ rtp EAC23469
> ```
> 
> 我使用vlc进行播放，url为rtsp://127.0.0.1:554/rtp/EAC23469，播放正常，然后我更改postman里面的参数，app改为rtp，stream改为EAC23469，GET最终的url为
> `http://127.0.0.1/index/api/startSendRtp?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=rtp&stream=EAC23469&ssrc=1&dst_url=127.0.0.1&dst_port=10000&is_udp=0`
> 点击send，但是出现了404，请问我有哪块做得不对嘛？

我知道自己哪里错了，因为http协议的80端口被占用，所以一开始我就把http端口设置为了8080
所以send的url需要改为
`http://127.0.0.1:8080/index/api/startSendRtp?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=rtp&stream=EAC23469&ssrc=1&dst_url=127.0.0.1&dst_port=10000&is_udp=0`
