### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by ly616187030** [ZLMediaKit/ZLMediaKit#1075]
**云端录像的功能模块**
- 想咨询zlmediakit，是否支持上级平台查看下级平台的云端录像？

**咨询的具体内容和问题**
- 我们多平台级联，根据业务需求，想要上级平台实时查看下级平台的云端录像

**Comment by xfdbse** [comment]
这不是zlmediakit的功能，你可以看wvp-gb28181项目。

**Comment by xia-chu** [comment]
其使用 wvp-pro项目
