### ISSUE TITLE
[BUG]openRtpServer后，推流到RTP端口，发现www/record/rtp/下自动录制文件。请问如何关闭自动录制？

### ISSUE THREAD

**Issue by 13760777390** [ZLMediaKit/ZLMediaKit#1076]
**bug现象**
openRtpServer后，推流到RTP端口，发现www/record/rtp/下自动录制文件。请问如何关闭自动录制？
（已配置fmp4_demand = 1）

**Comment by xia-chu** [comment]
配置文件注释请详看下

**Comment by 13760777390** [comment]
您说的是下面的配置吗，我已经设成1了，但是还会自动产生
#http[s]-fmp4、ws[s]-fmp4协议是否按需生成.这里若0，则收到国标流时会自动产生mp4
fmp4_demand = 1

**Comment by 13760777390** [comment]
> 配置文件注释请详看下
您说的是下面的配置吗，我已经设成1了，但是还会自动产生
#http[s]-fmp4、ws[s]-fmp4协议是否按需生成.这里若0，则收到国标流时会自动产生mp4
fmp4_demand = 1

**Comment by 13760777390** [comment]
> 配置文件注释请详看下

您说的是下面的配置吗，我已经设成1了，但是还会自动产生
#http[s]-fmp4、ws[s]-fmp4协议是否按需生成.这里若0，则收到国标流时会自动产生mp4
fmp4_demand = 1

**Comment by 13760777390** [comment]
==》ZLmedia 源码 FMP4MediaSourceMuxer.h

 void onReaderChanged(MediaSource &sender, int size) override {
        GET_CONFIG(bool, fmp4_demand, General::kFMP4Demand);
        _enabled = fmp4_demand ? size : true;
        if (!size && fmp4_demand) {
            _clear_cache = true;
        }
        MediaSourceEventInterceptor::onReaderChanged(sender, size);
    }
有没可能是这里导致的问题？烦请告知如何通过配置来禁止国标流产生MP4文件

**Comment by xia-chu** [comment]
有对接on_publish hook接口吗？ 你返回录制了吗？

**Comment by xia-chu** [comment]
### 7、on_publish：

- 解释:

   rtsp/rtmp/rtp推流鉴权事件。
- 触发请求：

  ```http
  POST /index/hook/on_publish HTTP/1.1
  Accept: */*
  Accept-Language: zh-CN,zh;q=0.8
  Connection: keep-alive
  Content-Length: 231
  Content-Type: application/json
  Host: 127.0.0.1
  Tools: ZLMediaKit
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
  
  {
     "mediaServerId" : "your_server_id",
     "app" : "live",
     "id" : "140186529001776",
     "ip" : "10.0.17.132",
     "params" : "token=1677193e-1244-49f2-8868-13b3fcc31b17",
     "port" : 65284,
     "schema" : "rtmp",
     "stream" : "obs",
     "vhost" : "__defaultVhost__"
  }
  
  ```
  
- 请求参数详解：

  |  参数名  |     参数类型     |           参数解释           |
  | :------: | :--------------: | :--------------------------: |
  |  `app`   |     `string`     |           流应用名           |
  |   `id`   |     `string`     |        TCP链接唯一ID         |
  |   `ip`   |     `string`     |           推流器ip           |
  | `params` |     `string`     |         推流url参数          |
  |  `port`  | `unsigned short` |         推流器端口号         |
  | `schema` |     `string`     | 推流的协议，可能是rtsp、rtmp |
  | `stream` |     `string`     |             流ID             |
  | `vhost`  |     `string`     |          流虚拟主机          |
  | `mediaServerId` | `string` |  服务器id,通过配置文件设置   |
  
- 默认回复:

  ```http
  HTTP/1.1 200 OK
  Connection: keep-alive
  Content-Length: 89
  Content-Type: application/json; charset=utf-8
  Date: Fri, Sep 20 2019 07:46:43 GMT
  Keep-Alive: timeout=10, max=100
  Server: ZLMediaKit-4.0
  
  {
     "code" : 0,
     "enableHls" : true,
     "enableMP4" : false,
     "msg" : "success"
  }
  
  ```
  
- 回复参数详解：

     |   参数名    | 参数类型 |        参数解释         |
  | :---------: | :------: | :---------------------: |
  |   `code`    |  `int`   | 错误代码，0代表允许推流 |
  |    `msg`    | `string` | 不允许推流时的错误提示  |
  | `enableHls` |  `bool`  |    是否转换成hls协议    |
  | `enableMP4` |  `bool`  |     是否允许mp4录制     |

**Comment by 13760777390** [comment]
> 配置文件这个参数检查了吗？
> 
> ```ini
> #是否默认推流时mp4录像，hook接口(on_publish)中可以覆盖该设置
> publishToMP4=0
> ```

我已经设置了publishToMP4=0

**Comment by 13760777390** [comment]
> ### 7、on_publish：
> * 解释:
>   rtsp/rtmp/rtp推流鉴权事件。
> * 触发请求：
>   ```httpspec
>   POST /index/hook/on_publish HTTP/1.1
>   Accept: */*
>   Accept-Language: zh-CN,zh;q=0.8
>   Connection: keep-alive
>   Content-Length: 231
>   Content-Type: application/json
>   Host: 127.0.0.1
>   Tools: ZLMediaKit
>   User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
>   
>   {
>      "mediaServerId" : "your_server_id",
>      "app" : "live",
>      "id" : "140186529001776",
>      "ip" : "10.0.17.132",
>      "params" : "token=1677193e-1244-49f2-8868-13b3fcc31b17",
>      "port" : 65284,
>      "schema" : "rtmp",
>      "stream" : "obs",
>      "vhost" : "__defaultVhost__"
>   }
>   ```
> * 请求参数详解：
>   
>   
>   
>   参数名
>   参数类型
>   参数解释
>   
>   
>   
>   
>   `app`
>   `string`
>   流应用名
>   
>   
>   `id`
>   `string`
>   TCP链接唯一ID
>   
>   
>   `ip`
>   `string`
>   推流器ip
>   
>   
>   `params`
>   `string`
>   推流url参数
>   
>   
>   `port`
>   `unsigned short`
>   推流器端口号
>   
>   
>   `schema`
>   `string`
>   推流的协议，可能是rtsp、rtmp
>   
>   
>   `stream`
>   `string`
>   流ID
>   
>   
>   `vhost`
>   `string`
>   流虚拟主机
>   
>   
>   `mediaServerId`
>   `string`
>   服务器id,通过配置文件设置
> * 默认回复:
>   ```httpspec
>   HTTP/1.1 200 OK
>   Connection: keep-alive
>   Content-Length: 89
>   Content-Type: application/json; charset=utf-8
>   Date: Fri, Sep 20 2019 07:46:43 GMT
>   Keep-Alive: timeout=10, max=100
>   Server: ZLMediaKit-4.0
>   
>   {
>      "code" : 0,
>      "enableHls" : true,
>      "enableMP4" : false,
>      "msg" : "success"
>   }
>   ```
> * 回复参数详解：
>   
>   
>   
>   参数名
>   参数类型
>   参数解释
>   
>   
>   
>   
>   `code`
>   `int`
>   错误代码，0代表允许推流
>   
>   
>   `msg`
>   `string`
>   不允许推流时的错误提示
>   
>   
>   `enableHls`
>   `bool`
>   是否转换成hls协议
>   
>   
>   `enableMP4`
>   `bool`
>   是否允许mp4录制

enableMP4这个如果我返回false的话，后续resful api 调用record还可以正常录制MP4吗？

**Comment by xia-chu** [comment]
可以
