### ISSUE TITLE
[技术咨询]想请教Webrtc推流遇到的关于超时的问题

### ISSUE THREAD

**Issue by holychaos** [ZLMediaKit/ZLMediaKit#1078]
您好，我之前在使用ZLMRTCClient.js进行推流时，程序运行得很正常，但是最近在使用时发现程序会被提示“接受rtp和rtcp超时”（如下图），期间并没有修改过程序，想请问这可能是由于哪些方面造成的？
![微信截图_20210830203020](https://user-images.githubusercontent.com/7961697/131348905-9c03be64-f3c3-441e-9c6c-dde7792c87e1.png)

**Comment by holychaos** [comment]
呃，应该是我编译新版本，之后忘记设置externIP了，尴尬……

**Comment by xia-chu** [comment]
看看webrtc sdp 还是有益的

**Comment by xxxxxxbin6** [comment]
请问你是怎么解决啊,我是刚编的新版本也出现这个问题(按照示例唯一不同的地方就是MediaServer目录就在linux目录下,没有Debug目录,其他都是按照示例来的),请问你说的externIP是什么啊,在哪设置的(我在内网测试的)

**Comment by holychaos** [comment]
> 请问你是怎么解决啊,我是刚编的新版本也出现这个问题(按照示例唯一不同的地方就是MediaServer目录就在linux目录下,没有Debug目录,其他都是按照示例来的),请问你说的externIP是什么啊,在哪设置的(我在内网测试的)

设置了externIP就解决了，externIP在配置文件里设置，可以在conf文件夹下找到，进行拷贝修改；或者初次运行MediaServer后会在运行目录下生成config.ini文件，然后再修改配置。

**Comment by xxxxxxbin6** [comment]
谢谢老哥,今早来试了一下,果然可以了!!!!(还有如果是demo里面的推流,拉流时得把stream名字改成test_h)

**Comment by xia-chu** [comment]
> 谢谢老哥,今早来试了一下,果然可以了!!!!(还有如果是demo里面的推流,拉流时得把stream名字改成test_h)

你推流不要勾选simulcast 否则stream_id有后缀的

**Comment by xxxxxxbin6** [comment]
哦哦,原来如此,多谢多谢!

**Comment by xxxxxxbin6** [comment]
你好,请问下我在vue中使用这个demo代码,导入ZLMRTCClient.js能直接用吗

**Comment by xia-chu** [comment]
应该可以吧 我也不懂前端



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xxxxxxbin6 ***@***.***&gt;
发送时间: 2021年9月23日 20:28
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]想请教Webrtc推流遇到的关于超时的问题 (#1078)





 
你好,请问下我在vue中使用这个demo代码,导入ZLMRTCClient.js能直接用吗

**Comment by xxxxxxbin6** [comment]
请问ZlmMediaKit能实现浏览器音视频通话吗,我看demo里只有推拉流

**Comment by poorboy1991** [comment]
> 谢谢老哥,今早来试了一下,果然可以了!!!!(还有如果是demo里面的推流,拉流时得把stream名字改成test_h)

您好，您这边是内网测试的那externIP是设置内网的ip么，但是我看了描述不设置他会自动获取理论上应该会自动获取到内网ip

**Comment by xxxxxxbin6** [comment]
内网好像确实不用设置,我现在在公网测试,需要设置那个externIP,当时只是遇到的问题跟楼主一样

**Comment by poorboy1991** [comment]
> 内网好像确实不用设置,我现在在公网测试,需要设置那个externIP,当时只是遇到的问题跟楼主一样

好的谢谢
