### ISSUE TITLE
[技术咨询]windows下编译webrtc问题

### ISSUE THREAD

**Issue by xilidedashu** [ZLMediaKit/ZLMediaKit#1081]
**咨询的功能模块**
- windwos下编译webrtc问题。

**咨询的具体内容和问题**
- CMAKE在前置步骤都配置好的情况下，报错
CMake Warning at CMakeLists.txt:299 (message):
  srtp未找到, webrtc相关功能打开失败。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by pubpy2015** [comment]
windows编译

可以参考网友大神自制这里

[https://blog.csdn.net/byna11sina11/article/details/119786889](https://blog.csdn.net/byna11sina11/article/details/119786889)

**Comment by xilidedashu** [comment]
我是参考的这个来做的，但是没有成功，报上面的错误，不太清楚问题出在哪里。

**Comment by xilidedashu** [comment]
在开启webrtc之后，生成解决方案也报下面的错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “srtp2/srtp.h”: No such file or directory	test_rtcp_nack	E:\ZLMediaKit\ZLMediaKit\webrtc\SrtpSession.hpp	23

**Comment by pubpy2015** [comment]
step by step:

1. download and install OpenSSL: [http://slproweb.com/products/Win32OpenSSL.html](http://slproweb.com/products/Win32OpenSSL.html)
2. download libsrtp: [https://github.com/cisco/libsrtp/releases/tag/v2.4.0](https://github.com/cisco/libsrtp/releases/tag/v2.4.0)
3. using CMake to config libsrtp with enable openSSL: (press Configure 2 times to auto detect OpenSSL lib): 
[https://blog.csdn.net/byna11sina11/article/details/119786889](https://blog.csdn.net/byna11sina11/article/details/119786889)
![ảnh](https://user-images.githubusercontent.com/59004953/131653344-14d64cae-358c-497a-8bf0-b5f3837ed31d.png)
4. Build libsrtp solution (remember tick build INSTALL project)
5. Add libsrtp to Enviroment Variables
![ảnh](https://user-images.githubusercontent.com/59004953/131653948-5971fc7f-5ce6-4ce2-be67-8f5aea83d2bc.png)
6. Clone ZLMediaKit
7. using CMake to config with enable openSSL and WebRTC
![ảnh](https://user-images.githubusercontent.com/59004953/131654204-3c19099e-ca72-414a-96ae-edd008dda91c.png)

**Comment by xilidedashu** [comment]
我的配置和上面的一模一样，步骤也是一模一样，我这里上传不了图片，还望谅解！

**Comment by xilidedashu** [comment]
您好，我也按照您上面的做了，用了最新的libsrtp包，但是还是同样的错误，我这里目前不能上传图片，还请谅解！

**Comment by xilidedashu** [comment]
对了，我用的是win10 家庭版。

**Comment by xilidedashu** [comment]
感谢夏大大的支持，用了您这个之后还是一样的问题，我已经把您发给我的包的路径设置到环境变量里面了（E:\ZLMediaKit\zlm\srtp2），我之前编译的INSTALL的目录结构和文件与您发我的一致，我怀疑是环境变量设置不生效问题引起的，不知道我的猜想对不对。

**Comment by xia-chu** [comment]
> 感谢夏大大的支持，用了您这个之后还是一样的问题，我已经把您发给我的包的路径设置到环境变量里面了（E:\ZLMediaKit\zlm\srtp2），我之前编译的INSTALL的目录结构和文件与您发我的一致，我怀疑是环境变量设置不生效问题引起的，不知道我的猜想对不对。

你要不在群里面下个别人编译好的吧

**Comment by xilidedashu** [comment]
{
   "code" : 0,
   "data" : [
      "/index/",
      "/index/api/addFFmpegSource",
      "/index/api/addStreamProxy",
      "/index/api/addStreamPusherProxy",
      "/index/api/closeRtpServer",
      "/index/api/close_stream",
      "/index/api/close_streams",
      "/index/api/delFFmpegSource",
      "/index/api/delStreamProxy",
      "/index/api/delStreamPusherProxy",
      "/index/api/downloadBin",
      "/index/api/getAllSession",
      "/index/api/getApiList",
      "/index/api/getMediaInfo",
      "/index/api/getMediaList",
      "/index/api/getMp4RecordFile",
      "/index/api/getRtpInfo",
      "/index/api/getServerConfig",
      "/index/api/getSnap",
      "/index/api/getStatistic",
      "/index/api/getThreadsLoad",
      "/index/api/getWorkThreadsLoad",
      "/index/api/isMediaOnline",
      "/index/api/isRecording",
      "/index/api/kick_session",
      "/index/api/kick_sessions",
      "/index/api/listRtpServer",
      "/index/api/openRtpServer",
      "/index/api/pauseRtpCheck",
      "/index/api/resumeRtpCheck",
      "/index/api/setServerConfig",
      "/index/api/startRecord",
      "/index/api/startSendRtp",
      "/index/api/stopRecord",
      "/index/api/stopSendRtp",
      "/index/hook/on_flow_report",
      "/index/hook/on_http_access",
      "/index/hook/on_play",
      "/index/hook/on_publish",
      "/index/hook/on_record_mp4",
      "/index/hook/on_rtsp_auth",
      "/index/hook/on_rtsp_realm",
      "/index/hook/on_server_started",
      "/index/hook/on_shell_login",
      "/index/hook/on_stream_changed",
      "/index/hook/on_stream_none_reader",
      "/index/hook/on_stream_not_found"
   ]
}

群里windows编译好的，没有看到webrtc的接口...

**Comment by xilidedashu** [comment]
今天突然能编译了，没有改动任何配置，不知道为何 😂😂😂😂

**Comment by a327958099** [comment]
> 5\. libsrtp

你好，请教一下  路径 E:\ZLMediaKit\zlm\srtp2  那变量名设置什么呢？  能把你的环境变量截图看看嘛？我遇到srtp找不到的问题，可能是我哪里弄得不对

**Comment by MrSheng** [comment]
> 今天突然能编译了，没有改动任何配置，不知道为何 😂😂😂😂

您好 编译好的版本可以分享一下吗

**Comment by zhaoyongjun1113** [comment]
> 感谢夏大大的支持，用了您这个之后还是一样的问题，我已经把您发给我的包的路径设置到环境变量里面了（E:\ZLMediaKit\zlm\srtp2），我之前编译的INSTALL的目录结构和文件与您发我的一致，我怀疑是环境变量设置不生效问题引起的，不知道我的猜想对不对。

需要在cmakelist中配置SRTP_PREFIX为自己 srtp包所在的目录,如 set(SRTP_PREFIX "F:/msys64/home/12032/libsrtp-2.4.0/install")，可以查看安装目录下cmake/FindSRTP.cmake,里面寻找srtp包是有SRTP_PREFIX 宏

**Comment by wangzheooo** [comment]
将libsrtp安装的根目录和cmake中设置的srtp的build文件夹中的Release目录（如果编译的是Debug，则这里是Debug目录）路径配置到Windows的系统环境变量Path中。

**Comment by taojin1122** [comment]
编译提示这个错误，是为什么？
```

CMake Error at 3rdpart/CMakeLists.txt:32 (add_library):
  No SOURCES given to target: jsoncpp


CMake Error at 3rdpart/CMakeLists.txt:55 (add_library):
  No SOURCES given to target: mov


CMake Error at 3rdpart/CMakeLists.txt:68 (add_library):
  No SOURCES given to target: flv


CMake Error at 3rdpart/CMakeLists.txt:91 (add_library):
  No SOURCES given to target: mpeg
```

**Comment by zhujianLeo** [comment]
libsrtp 必须用2.x版本 如果用master分支的3.x版本 就会报错的

**Comment by dyl1989** [comment]
![Image](https://github.com/user-attachments/assets/2c01f1bb-876b-4cbc-b62e-d28c300b0383)

![Image](https://github.com/user-attachments/assets/b71426f7-f5db-4010-b6ff-58bcac33b3aa)
编译报错，不知道怎么回事

**Comment by xia-chu** [comment]
> ![Image](https://github.com/user-attachments/assets/2c01f1bb-876b-4cbc-b62e-d28c300b0383)
> 
> ![Image](https://github.com/user-attachments/assets/b71426f7-f5db-4010-b6ff-58bcac33b3aa) 编译报错，不知道怎么回事

这个srtp编译失败还没遇到过 建议vcpkg编译安装srtp
vcpkg install libsrtp\[openssl\]
