### ISSUE TITLE
[技术咨询]有一个rtmp推流, 按照[url规则]说明, 获取到的flv链接无法播放

### ISSUE THREAD

**Issue by ZhangJiaLei123** [ZLMediaKit/ZLMediaKit#1082]
**咨询的功能模块**
- url规则

**咨询的具体内容和问题**
- rtmp链接: rtmp://xxxx:8812/live/livestream101a
- 计算的flv链接: http//xxxx:8812/live/livestream101a.flv

* rtmp 可以正常播放,  flv 播放失败

**Comment by ZhangJiaLei123** [comment]
rtmp和http可以共用一个端口么, 疏忽了

**Comment by xia-chu** [comment]
> rtmp和http可以共用一个端口么, 疏忽了

不可以 ，不过有些情况下 确实可以分析协议内容 然后做不同的协议逻辑分支从而实现单端口多协议。

**Comment by wasphin** [comment]
> > rtmp和http可以共用一个端口么, 疏忽了
> 
> 
> 
> 不可以 ，不过有些情况下 确实可以分析协议内容 然后做不同的协议逻辑分支从而实现单端口多协议。
> 
> 不过还不知道有没有这样的软件，有的话可以告诉我。

brpc 支持，收到数据后先识别协议，后续请求按识别后的协议进行解析。
