### ISSUE TITLE
能不能修改一下webrtc通讯时udp端口能复用

### ISSUE THREAD

**Issue by hanhxm** [ZLMediaKit/ZLMediaKit#1085]
**描述该功能的用处，可以提供相关资料描述该功能*

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

在使用docker模式情况下网络中有防火墙，webrtc通讯时udp使用随机端口，这样需要暴露的外部端口太多而且不固定，很麻烦。而且实际项目中，基本不会允许暴露这么多端口

**描述你期望实现该功能的方式和最终效果**

能不能改进一下udp使用单一的端口复用。

谢谢大佬

**Comment by xia-chu** [comment]
这个是近期的开发计划 不顾最近手头事情比较多 暂时要延缓一下

**Comment by hanhxm** [comment]
好的，谢谢大佬

**Comment by xia-chu** [comment]
已经支持了 单端口、多线程、支持链接迁移是开源界唯一 。

**Comment by hanhxm** [comment]
大佬太牛了，谢谢，辛苦了
