### ISSUE TITLE
RTSP client PTS/DTS issue

### ISSUE THREAD

**Issue by kaspesla** [ZLMediaKit/ZLMediaKit#1086]
I'm using ZLMediaKit to stream RTSP from network cameras.
I'm using the C API.
I was using a library from June, but when I updated to the latest, I no longer receive the correct PTS/DTS for video frames. It is always the same number for each frame. It doesn't change from frame to frame.
Any ideas?
Thanks!
-Ken

**Comment by xia-chu** [comment]
hi, can you tell me the git commit hash of zlmediakit you used.



发自我的iPhone


------------------ Original ------------------
From: kaspesla ***@***.***&gt;
Date: Sat,Sep 4,2021 7:54 AM
To: ZLMediaKit/ZLMediaKit ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [ZLMediaKit/ZLMediaKit] [BUG] (#1086)





 
I'm using ZLMediaKit to stream RTSP from network cameras.
 I'm using the C API.
 I was using a library from June, but when I updated to the latest, I no longer receive the correct PTS/DTS for video frames. It is always the same number for each frame. It doesn't change from frame to frame.
 Any ideas?
 Thanks!
 -Ken

**Comment by kaspesla** [comment]
Hi,

Thanks for getting back to me!

The commit I tried yesterday that did not work was 415bc95dda5aff3c7dfb34d0b921af9e13c94f3b.

After finding the issue, I picked a commit at random and went back to f6eb84b4130f159f8d30ecda4e877612d466d093 (from May) and that worked.

Let me know if you want me to try from a different commit.

Thanks!
-ken

**Comment by xia-chu** [comment]
please update and test!

**Comment by kaspesla** [comment]
You fixed it!

Thanks!!!!!! 

-Ken
