### ISSUE TITLE
内网rtsp服务在外网以udp方式拉取rtsp流时失败

### ISSUE THREAD

**Issue by ziyuyouxia** [ZLMediaKit/ZLMediaKit#1090]
**bug现象**
-内网rtsp服务通过端口映射在外网以udp方式拉取rtsp流时失败，vlc拉取正常

**bug产生时的使用场景**
-内网rtsp服务地址：rtsp://192.167.1.127:554/test
连接到路由盒子，通过端口映射把服务发布到外网，通过地址：rtsp://192.168.1.11:555/test 用zlm拉流，显示超时失败,用vlc正常
通过修改RtspPlayer.cpp可以解决
注释掉pRtpSockRef->send("\xce\xfa\xed\xfe", 4);
这一行可以解决问题。但是感觉这样可能产生其他问题，请教作者

**bug是否可以复现，怎么复现**
- 可以复现

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
- win7，32位

**Comment by xia-chu** [comment]
zlm是rtp over udp方式还是tcp方式拉流？

**Comment by ziyuyouxia** [comment]
rtp over udp方式

**Comment by xia-chu** [comment]
是zlm通过rtp over udp方式拉内网的rtsp流(通过端口映射到公网了)吗？

**Comment by ziyuyouxia** [comment]
是的

**Comment by xia-chu** [comment]
那肯定不行啊 你都没映射udp端口 rtsp设备在内网中 怎么可能用udp方式播放

**Comment by ziyuyouxia** [comment]
好的，多谢解惑
