### ISSUE TITLE
Creating H264Frame from AVPacket

### ISSUE THREAD

**Issue by manoondivakaran** [ZLMediaKit/ZLMediaKit#1091]
Hi,

Thanks for the wonderful repository.

In one of my project I am using libav(ffmpeg) to transcode HEVC to H264
I am using ZLMediaKit to generate HLS out of it. 

Using the below code to generate H264Frame from H264 AVPacket
                        case AVCodecID::AV_CODEC_ID_H264:
                        {
                            auto  fm = FrameImp::create<H264Frame>();
                            fm->_dts = vPacket->dts;
                            fm->_pts = vPacket->pts;
                            fm->_buffer.assign((char*)vPacket->data, vPacket->size);
                            fm->_prefix_size = prefixSize((char*)vPacket->data, vPacket->size);
                            fmt = fm;
                        }
Unfortunately H264Frame never recognize keyframe from it(IDR packet). 
Could you please suggest me right way to create H264Frame out of AVPacket?

Thanks

**Comment by xia-chu** [comment]
Hi , you can refer my code:
```c++
558 class FFmpegEncodedFrame : public Frame {
559	public:
560	    using Ptr = std::shared_ptr<FFmpegEncodedFrame>;
561	
562	    static Frame::Ptr createFrame(std::shared_ptr<AVPacket> pkt, CodecId codec, const AVCodecContext *ctx) {
563	        switch (codec) {
564	            case mediakit::CodecH264: return std::make_shared<H264FrameHelper<FFmpegEncodedFrame> >(std::move(pkt), codec, ctx);
565	            case mediakit::CodecH265: return std::make_shared<H265FrameHelper<FFmpegEncodedFrame> >(std::move(pkt), codec, ctx);
566	            default: return FFmpegEncodedFrame::Ptr(new FFmpegEncodedFrame(std::move(pkt), codec, ctx));
567	        }
568	    }
569	
570	    ~FFmpegEncodedFrame() override {}
571	
572	    uint32_t dts() const override {
573	        return _pkt->dts;
574	    }
575	
576	    uint32_t pts() const override {
577	        if (abs(_pkt->dts - _pkt->pts) > 1000) {
578	            return dts();
579	        }
580	        return _pkt->pts;
581	    }
582	
583	    size_t prefixSize() const override {
584	        switch (_codec_id) {
585	            case mediakit::CodecH264:
586	            case mediakit::CodecH265: return mediakit::prefixSize(data(), size());
587	            case mediakit::CodecAAC: return _data.empty() ? 0 : ADTS_HEADER_LEN;
588	            default: return 0;
589	        }
590	    }
591	
592	    CodecId getCodecId() const override {
593	        return _codec_id;
594	    }
595	
596	    char *data() const override {
597	        return _data.empty() ? (char *) _pkt->data : const_cast<char *>(_data.data());
598	    }
599	
600	    size_t size() const override {
601	        return _data.empty() ? _pkt->size : _data.size();
602	    }
603	
604	    bool keyFrame() const override {
605	        return false;
606	    }
607	
608	    bool configFrame() const override {
609	        return false;
610	    }
611	
612	protected:
613	    FFmpegEncodedFrame(std::shared_ptr<AVPacket> pkt, CodecId codec, const AVCodecContext *ctx) {
614	        _pkt = std::move(pkt);
615	        _codec_id = codec;
616	        if (codec == mediakit::CodecAAC && ctx && ctx->extradata && ctx->extradata_size) {
617	            auto cfg = string(reinterpret_cast<const char *>(ctx->extradata), ctx->extradata_size);
618	            _data.resize(_pkt->size + ADTS_HEADER_LEN);
619	            dumpAacConfig(cfg, _pkt->size, (uint8_t *) (_data.data()), ADTS_HEADER_LEN);
620	            memcpy((uint8_t *) (_data.data()) + ADTS_HEADER_LEN, _pkt->data, _pkt->size);
621	        } else {
622	            _data.clear();
623	        }
624	    }
625	
626	protected:
627	    CodecId _codec_id;
628	    string _data;
629	    std::shared_ptr<AVPacket> _pkt;
630	};
```

**Comment by xia-chu** [comment]
You have to make sure timebase of  `AVPacket`  is 1:1000(millisecond)

**Comment by xia-chu** [comment]
You can create shared_ptr of AVPacket like this:
```c++
20 std::shared_ptr<AVPacket> alloc_av_packet(){
21	    auto pkt = std::shared_ptr<AVPacket>(av_packet_alloc(), [](AVPacket *pkt) {
22	        av_packet_free(&pkt);
23	    });
24	    pkt->data = NULL;    // packet data will be allocated by the encoder
25	    pkt->size = 0;
26	    return pkt;
27	}
```

**Comment by manoondivakaran** [comment]
Thank you very much @xia-chu . I will try and update....

**Comment by manoondivakaran** [comment]
Hi @xia-chu ,

Thanks for your help.

The above code did help me with a small change.
 switch (codec) {
        //case mediakit::CodecH264: return std::make_shared<H264FrameHelper<FFmpegEncodedFrame> >(std::move(pkt), codec, ctx);
        //case mediakit::CodecH265: return std::make_shared<H265FrameHelper<FFmpegEncodedFrame> >(std::move(pkt), codec, ctx);
        default: return FFmpegEncodedFrame::Ptr(new FFmpegEncodedFrame(std::move(pkt), codec, ctx));

//
// H264FrameHelper<FFmpegEncodedFrame>  not working because keyFrame is returning false;
Also added a flag in FFmpegEncodedFrame and updated like below,

 bool FFmpegEncodedFrame::keyFrame() const {
        return _isKeyFrame;
    }


also constructor
FFmpegEncodedFrame::FFmpegEncodedFrame(std::shared_ptr<AVPacket> pkt, CodecId codec, const AVCodecContext* ctx) {
        _pkt = std::move(pkt);
        _codec_id = codec;
        if (_pkt)
        {
            _isKeyFrame = _pkt->flags |= AV_PKT_FLAG_KEY;
        }
        if (codec == mediakit::CodecAAC && ctx && ctx->extradata && ctx->extradata_size) {
            auto cfg = string(reinterpret_cast<const char*>(ctx->extradata), ctx->extradata_size);
            _data.resize(_pkt->size + ADTS_HEADER_LEN);
            dumpAacConfig(cfg, _pkt->size, (uint8_t*)(_data.data()), ADTS_HEADER_LEN);
            memcpy((uint8_t*)(_data.data()) + ADTS_HEADER_LEN, _pkt->data, _pkt->size);
        }
        else {
            _data.clear();
        }
    }

Please correct me if I am wrong.

Many many thanks...

**Comment by xia-chu** [comment]
H264FrameHelper will override the virtual function of `keyFrame()`;
You can read this code:
```c++

template<typename Parent>
class H264FrameHelper : public Parent{
public:
    friend class FrameImp;
    friend class ResourcePool_l<H264FrameHelper>;
    using Ptr = std::shared_ptr<H264FrameHelper>;

    enum {
        NAL_IDR = 5,
        NAL_SEI = 6,
        NAL_SPS = 7,
        NAL_PPS = 8,
        NAL_AUD = 9,
        NAL_B_P = 1,
    };

    template<typename ...ARGS>
    H264FrameHelper(ARGS &&...args): Parent(std::forward<ARGS>(args)...) {
        this->_codec_id = CodecH264;
    }

    ~H264FrameHelper() override = default;

    bool keyFrame() const override {
        auto nal_ptr = (uint8_t *) this->data() + this->prefixSize();
        return H264_TYPE(*nal_ptr) == NAL_IDR && decodeAble();
    }

    bool configFrame() const override {
        auto nal_ptr = (uint8_t *) this->data() + this->prefixSize();
        switch (H264_TYPE(*nal_ptr)) {
            case NAL_SPS:
            case NAL_PPS: return true;
            default: return false;
        }
    }

    bool dropAble() const override {
        auto nal_ptr = (uint8_t *) this->data() + this->prefixSize();
        switch (H264_TYPE(*nal_ptr)) {
            case NAL_SEI:
            case NAL_AUD: return true;
            default: return false;
        }
    }

    bool decodeAble() const override {
        auto nal_ptr = (uint8_t *) this->data() + this->prefixSize();
        auto type = H264_TYPE(*nal_ptr);
        //多slice情况下, first_mb_in_slice 表示其为一帧的开始
        return type >= NAL_B_P && type <= NAL_IDR && (nal_ptr[1] & 0x80);
    }
};

```

**Comment by manoondivakaran** [comment]
Hi @xia-chu 

I tried with H264FrameHelper, but no luck.
The keyFrame() always return false as you can see in the attachment

 
![image](https://user-images.githubusercontent.com/63871004/132457581-1bf6cf82-a5b6-4c47-9a7b-1cca0ab1b69f.png)

**Comment by xia-chu** [comment]
Please do not modify the code of `FFmpegEncodedFrame` and then test.
I'm already using  this code of `FFmpegEncodedFrame`

**Comment by manoondivakaran** [comment]
Yes, I tried your code with any modification, but result was the same. 

The NALU present at the AVPacket ( data[4]) is 0x41. Is there any wrong in encoding?

**Comment by xia-chu** [comment]
`0x41 & 0x1F == 1`  so, this is a `b or p ` fame.

**Comment by manoondivakaran** [comment]
Hi @xia-chu ,

Thanks for your reply.

I checked the Keyframe AVPacket and found that the data prepend with SPS(( data[4]) is 0x67). So the H264FrameHelper keyFrame return false ;

hex dump of AVPacket:
00 00 00 01 67 64 08 1F AC E4 03 C0 49 A1 00 00 03 00 01 00 00 03 00 1E 0F 18 31 12 00 00 00 01 68 EB EC B2 2C 00 00 01 
^sps start                                                                                                                           ^keyFrame start

**Comment by xia-chu** [comment]
Although this `frame` is judged not to be a key frame, it doesn't matter, because zlmediakit subsequent `H264Track` objects will split this frame to `3` frames:
```c++
void H264Track::inputFrame(const Frame::Ptr &frame) {
    using H264FrameInternal = FrameInternal<H264FrameNoCacheAble>;
    int type = H264_TYPE( frame->data()[frame->prefixSize()]);
    if (type != H264Frame::NAL_B_P && type != H264Frame::NAL_IDR) {
        //非I/B/P帧情况下，split一下，防止多个帧粘合在一起
        splitH264(frame->data(), frame->size(), frame->prefixSize(), [&](const char *ptr, size_t len, size_t prefix) {
            H264FrameInternal::Ptr sub_frame = std::make_shared<H264FrameInternal>(frame, (char *) ptr, len, prefix);
            inputFrame_l(sub_frame);
        });
    } else {
        inputFrame_l(frame);
    }
}
```

**Comment by xia-chu** [comment]
So, if you input this frame into `MultiMediaSourceMuxer`, it will also work!

**Comment by manoondivakaran** [comment]
Dear @xia-chu ,

Now, I got it. I am using a custom TsMuxer which bypass the H264Track::inputFrame(not using MultiMediaSourceMuxer). I need to work on it.

Thanks for your great help...

**Comment by xia-chu** [comment]
So, you may read the code of `H264Track`.

**Comment by manoondivakaran** [comment]
yes, thanks
