### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by zhangzhiming1017** [ZLMediaKit/ZLMediaKit#1092]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 你好，请问如何使用zlm进行rtsp拉流，然后通过webrtc播放该rtsp流呢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
wiki url规则篇你可以看下

**Comment by zhangzhiming1017** [comment]
你好，我现在成功地用/index/api/addStreamProxy接口添加了流，vlc接口能够正常播放，用webrtc接口播放显示404，这是啥原因呀。
vlc播放的url是：http://192.168.8.82/live/000.flv
webrtc播放的url是：http://192.168.8.82/index/api/webrtc?app=live&stream=000&type=play

**Comment by xia-chu** [comment]
> 你好，我现在成功地用/index/api/addStreamProxy接口添加了流，vlc接口能够正常播放，用webrtc接口播放显示404，这是啥原因呀。
> vlc播放的url是：http://192.168.8.82/live/000.flv
> webrtc播放的url是：http://192.168.8.82/index/api/webrtc?app=live&stream=000&type=play

你没开启webrtc编译。
cmake -DENABLE_WEBRTC=on

**Comment by zhangzhiming1017** [comment]
成功解决了，谢谢

**Comment by zhangzhiming1017** [comment]
你好，怎么通过/index/api/addStreamProxy接口处理类似于rtsp://admin:admin12345@192.168.5.71/cam/realmonitor?channel=1&subtype=0这样的url呢

**Comment by zhangzhiming1017** [comment]
你好，我知道怎么处理了，谢谢
