### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Dw9** [ZLMediaKit/ZLMediaKit#1094]
**bug现象**
使用最新的zlm，在win上使用test_player,渲染呈現绿屏
![image](https://user-images.githubusercontent.com/36155473/132504658-6c6bfd77-88ba-4001-b734-adba1f9dcc9e.png)

**現象分析**
本机win电脑支持硬解且硬解的优先级较高,生成的格式为NV12，更新到最新的sdl(2.0.16)  SDL_UpdateNVTexture支持渲染NV12
#1093

**Comment by Dw9** [comment]
fixd  #1093 
自测通过

**Comment by pubpy2015** [comment]
Hi @Dw9 ,

Can you share how to build test_player on window ?
I am running CMAKE on my PC but it can not find some libs to create test_player?

![image](https://user-images.githubusercontent.com/59004953/132544994-ffe0f9f9-6d4f-4908-a873-344a5ec9791b.png)

(I am trying download SDL2 at https://www.libsdl.org/download-2.0.php and ffmpeg at https://github.com/BtbN/FFmpeg-Builds/releases, test_player was created but when build on Visual Studio there are many errors.)

**Comment by Dw9** [comment]
1、【player/CmakeLists.txt】  comment line 82 ,then cmake can detect "ENABLE PLAYER".
![image](https://user-images.githubusercontent.com/36155473/132604874-34fea30d-7424-4825-9391-8280325c336c.png)
 2、 configure test_player's environment with ffmpeg & sdl separately .
![image](https://user-images.githubusercontent.com/36155473/132605325-753b2480-3d7b-4780-826b-b755332b0d24.png)
Regards.

**Comment by songoku141** [comment]
Thanks,

I was deleted line 82 in player CmakeList.txt but test_player still disabled:
![image](https://user-images.githubusercontent.com/13082850/132611283-7580a73f-f6bb-4d4a-8092-6513a6d880a5.png)
![image](https://user-images.githubusercontent.com/13082850/132611454-4118431b-d806-42a7-a2bd-6c916ac0ca33.png)

Is any setting in Environment Variables:
![image](https://user-images.githubusercontent.com/13082850/132611801-57f8486b-4c85-4d92-8559-06e5d99fbf4f.png)

**Comment by Dw9** [comment]
hi@songoku141   that's a cmake warnning，just ignore。
 open  build/ZLMediaKit.sln, u will find "test_player"  that's why we need to delete line 82

**Comment by songoku141** [comment]
Yes,

test_player was created but there are some errors:
![image](https://user-images.githubusercontent.com/13082850/132616285-e348b827-1a8b-462b-98a5-8177053e3397.png)

test_player settings:
![image](https://user-images.githubusercontent.com/13082850/132616417-975f1cf1-6fe7-4020-8fc6-9b5ee477cc9d.png)

![image](https://user-images.githubusercontent.com/13082850/132617357-5db93491-f3d4-40c6-a3c1-1a7bfd9edf2b.png)

**Comment by pubpy2015** [comment]
Why you don't let CMake find required libraries ?

**Comment by xia-chu** [comment]
@pubpy2015  Why don't you test on `ubuntu`, Although windows can also compile `test_player`, but it's too much trouble

**Comment by pubpy2015** [comment]
I only work on Windows, since I never built a test_player successfully, just wanted to try it out

**Comment by Dw9** [comment]
@songoku141  cuz  **test_player** ​ include "SDL2/SDL.h"
Create folder “SDL2" ,and put all .h file into SDL2

![image](https://user-images.githubusercontent.com/36155473/132639483-52581608-0861-4fb6-a82a-822d4f93cba3.png)


by the way ,linker->input  

> avcodec.lib
> avformat.lib
> avutil.lib
> avfilter.lib
> avdevice.lib
> postproc.lib
> swresample.lib
> swscale.lib

![image](https://user-images.githubusercontent.com/36155473/132639894-38f7a883-04ac-4441-a147-ac69605732ca.png)

**Comment by songoku141** [comment]
Thank you very much!

Now i can build test_player successfull.

**Comment by pubpy2015** [comment]
Follow step to build with enable test_player on windows:

1. download SDL2 from [https://www.libsdl.org/download-2.0.php](https://www.libsdl.org/download-2.0.php) and save to SDL2 folder:
![ảnh](https://user-images.githubusercontent.com/59004953/132653098-ec1a9250-3b12-4490-ba77-f97baccb19a5.png)
create new folder SDL2 in include folder.
move all files in include folder to SDL2 folder:
![ảnh](https://user-images.githubusercontent.com/59004953/132653502-f7a89e69-cf2b-4f2a-ab80-a78ebbb47f32.png)


2. download ffmpeg share lib from: [https://github.com/BtbN/FFmpeg-Builds/releases](https://github.com/BtbN/FFmpeg-Builds/releases) and save to FFMPEGLIB folder:

![ảnh](https://user-images.githubusercontent.com/59004953/132653790-74cc96f2-6824-4603-93c2-2efb58f84a7b.png)

3. Create Enviroment Variables:
![ảnh](https://user-images.githubusercontent.com/59004953/132654042-2af6d21e-161f-4209-9b4e-a15550c801fc.png)

4. run Cmake
![ảnh](https://user-images.githubusercontent.com/59004953/132654296-af2b0705-1703-435e-9d89-8f37192eee64.png)
