### ISSUE TITLE
[技术咨询]camera设备测使用webRTC协议推流

### ISSUE THREAD

**Issue by huiqiaoqiu** [ZLMediaKit/ZLMediaKit#1095]
**咨询的功能模块**
- webRTC

**咨询的具体内容和问题**
- 想在其他摄像头，例如海康或其他摄像头设备，在可以获取到h264和audio数据帧的前提下，想用webRTC推流，测试了一下zlMedia可能接收webRTC也能推送webRTC，那能参考zlMedia的webRTC模块，移植到camera测去做webRTC协议推流吗？这个思路方案是否可行？

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
zlm的webrtc目前只实现了ice-lite模式，也就是只能作为公网上的服务器 不能作为客户端使用的。因为ice这块实现比较复杂，要实现ice-full还是比较麻烦的。

**Comment by huiqiaoqiu** [comment]
如果想在camera设备上，在已获取到h264视频帧和opus音频数据前提下，要实现webRTC(不用p2p打洞)，只考虑向zlmedia流媒体服务器推webRTC流，有怎样的可行建议吗？

**Comment by xia-chu** [comment]
> 如果想在camera设备上，在已获取到h264视频帧和opus音频数据前提下，要实现webRTC(不用p2p打洞)，只考虑向zlmedia流媒体服务器推webRTC流，有怎样的可行建议吗？

要在交换icecandidate地址后开启ice流程，需要发送stun包等打洞包。可以用libnice实现，不过老陈的[库](https://github.com/ireader/sdk/tree/master/libice)不知道成不成熟，libnice依赖glib，我个人是不喜欢的

**Comment by huiqiaoqiu** [comment]
感谢指点，有个疑问，假如我当前不需要去做p2p的话，只是需要向ZLmedia服务器推流，也需要发送stun等打洞包吗？

**Comment by huiqiaoqiu** [comment]
> > 如果想在camera设备上，在已获取到h264视频帧和opus音频数据前提下，要实现webRTC(不用p2p打洞)，只考虑向zlmedia流媒体服务器推webRTC流，有怎样的可行建议吗？
> 
> 要在交换icecandidate地址后开启ice流程，需要发送stun包等打洞包。可以用libnice实现，不过老陈的[库](https://github.com/ireader/sdk/tree/master/libice)不知道成不成熟，libnice依赖glib，我个人是不喜欢的

**Comment by xia-chu** [comment]
可以了解下这个项目：https://github.com/yangrtc/yangwebrtc

**Comment by huiqiaoqiu** [comment]
感谢作者回复。 这个项目我之前搜到过，他把推流的实现部分封了库使用，没有开出来。
我在自己多学习下webRTC协议的具体内容，然后看看能怎样自己实现个推流

**Comment by xia-chu** [comment]
> 感谢作者回复。 这个项目我之前搜到过，他把推流的实现部分封了库使用，没有开出来。
> 我在自己多学习下webRTC协议的具体内容，然后看看能怎样自己实现个推流

那就是假开源了😂

**Comment by huiqiaoqiu** [comment]
> > 感谢作者回复。 这个项目我之前搜到过，他把推流的实现部分封了库使用，没有开出来。
> > 我在自己多学习下webRTC协议的具体内容，然后看看能怎样自己实现个推流
> 
> 那就是假开源了😂

在那个作者那提了一个issue，作者把封库部分上传了，
