### ISSUE TITLE
[技术咨询]请教webrtc播放的问题

### ISSUE THREAD

**Issue by jiaxiaolong** [ZLMediaKit/ZLMediaKit#1096]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
webrtc
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
您好，我使能webrtc编译成功
终端上用命令./MediaServer 运行
在另一个终端用ffmpeg推流 ffmpeg -rtsp_transport tcp -i rtsp://admin:admin123456@172.16.12.133:554/Streaming/Channels/101?tra -c copy -f flv rtmp://127.0.0.1/live/test 
用VLC测试MediaServer的rtmp,rtsp,http都正常播放。浏览器打打开 http://192.168.75.128:8080/webrtc/index.html，url填入 http://192.168.75.128:8080/index/api/webrtc?app=live&stream=test&type=play
播放后MediaServer不知道什么原因断错误掉了，请问是我哪步操作有问题吗？提示如下
2021-09-09 02:50:56.061 D MediaServer[24855-event poller 0] WebApi.cpp:228 http api debug | 
# request:
POST /index/api/webrtc?app=live&stream=test&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate
Accept-Language : en-US,en;q=0.5
Connection : keep-alive
Content-Length : 2452
Content-Type : text/plain;charset=utf-8
Host : 127.0.0.1:8080
Origin : http://127.0.0.1:8080
Referer : http://127.0.0.1:8080/webrtc/
User-Agent : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
# content:
v=0
o=mozilla...THIS_IS_SDPARTA-88.0 3503656009404016703 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 4D:7D:83:98:FA:55:21:BD:BB:43:FB:4B:08:0D:6D:72:E3:C4:6A:32:47:A2:67:F1:3A:EC:34:7D:CE:06:19:A7
a=group:BUNDLE 0 1
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:381b74508af2e6cb83ec83d0e2c36efa
a=ice-ufrag:6a433652
a=mid:0
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=setup:actpass
a=ssrc:3516754728 cname:{fd709200-ea9d-4d19-b32b-228161bb6436}
m=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98
c=IN IP4 0.0.0.0
a=recvonly
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:5 urn:ietf:params:rtp-hdrext:toffset
a=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:120 max-fs=12288;max-fr=60
a=fmtp:124 apt=120
a=fmtp:121 max-fs=12288;max-fr=60
a=fmtp:125 apt=121
a=fmtp:127 apt=126
a=fmtp:98 apt=97
a=ice-pwd:381b74508af2e6cb83ec83d0e2c36efa
a=ice-ufrag:6a433652
a=mid:1
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:120 transport-cc
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
a=rtcp-fb:121 transport-cc
a=rtcp-fb:126 nack
a=rtcp-fb:126 nack pli
a=rtcp-fb:126 ccm fir
a=rtcp-fb:126 goog-remb
a=rtcp-fb:126 transport-cc
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 goog-remb
a=rtcp-fb:97 transport-cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:120 VP8/90000
a=rtpmap:124 rtx/90000
a=rtpmap:121 VP9/90000
a=rtpmap:125 rtx/90000
a=rtpmap:126 H264/90000
a=rtpmap:127 rtx/90000
a=rtpmap:97 H264/90000
a=rtpmap:98 rtx/90000
a=setup:actpass
a=ssrc:2833860040 cname:{fd709200-ea9d-4d19-b32b-228161bb6436}

# response:
{
   "code" : 0,
   "sdp" : "v=0\r\no=mozilla...THIS_IS_SDPARTA-88.0 3503656009404016703 0 IN IP4 192.168.75.128\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS *\r\nm=audio 42842 UDP/TLS/RTP/SAVPF 0\r\nc=IN IP4 192.168.75.128\r\na=rtcp:42842 IN IP4 192.168.75.128\r\na=ice-ufrag:suMD\r\na=ice-pwd:A0XbWp1zc1UNuO5qamJ0u5FV\r\na=fingerprint:sha-256 0B:E6:7C:CA:B0:A5:48:7D:D4:A4:C7:F3:FB:D5:DE:DA:FD:C0:0B:DD:9F:F8:22:F9:28:1E:6A:D6:59:17:3F:04\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:0 PCMU/8000/1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:0 cname:zlmediakit-rtp\r\na=ssrc:0 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:0 mslabel:zlmediakit-mslabel\r\na=ssrc:0 label:zlmediakit-label\r\na=candidate:udpcandidate 1 udp 100 192.168.75.128 42842 typ host\r\nm=video 42842 UDP/TLS/RTP/SAVPF 126 127\r\nc=IN IP4 192.168.75.128\r\na=rtcp:42842 IN IP4 192.168.75.128\r\na=ice-ufrag:suMD\r\na=ice-pwd:A0XbWp1zc1UNuO5qamJ0u5FV\r\na=fingerprint:sha-256 0B:E6:7C:CA:B0:A5:48:7D:D4:A4:C7:F3:FB:D5:DE:DA:FD:C0:0B:DD:9F:F8:22:F9:28:1E:6A:D6:59:17:3F:04\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:126 H264/90000\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:126 goog-remb\r\na=rtcp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=fmtp:126 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:127 rtx/90000\r\na=fmtp:127 apt=126\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\na=ssrc:4 cname:zlmediakit-rtp\r\na=ssrc:4 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:4 mslabel:zlmediakit-mslabel\r\na=ssrc:4 label:zlmediakit-label\r\na=ssrc-group:FID 2 4\r\na=candidate:udpcandidate 1 udp 100 192.168.75.128 42842 typ host\r\n",
   "type" : "answer"
}

2021-09-09 02:50:56.087 I MediaServer[24855-event poller 0] WebRtcTransport.cpp:68 OnIceServerSelectedTuple | 
2021-09-09 02:50:56.087 I MediaServer[24855-event poller 0] WebRtcTransport.cpp:76 OnIceServerCompleted | 
2021-09-09 02:50:56.087 I MediaServer[24855-event poller 0] WebRtcTransport.cpp:109 OnDtlsTransportConnecting | 
2021-09-09 02:50:56.094 I MediaServer[24855-event poller 0] WebRtcTransport.cpp:98 OnDtlsTransportConnected | 
## stack:     
[0]: ./MediaServer() [0xe23550]
sig_crash(int)
System.cpp:?

[1]: /lib/x86_64-linux-gnu/libc.so.6(+0x354c0) [0x7f68664f74c0]
??
??:0

[2]: ./MediaServer(srtp_get_stream+0) [0x132ce40]
srtp_get_stream
??:?

[3]: ./MediaServer(srtp_protect_mki+0xcf) [0x132cf3f]
srtp_protect_mki
??:?

[4]: ./MediaServer(_ZN3RTC11SrtpSession10EncryptRtpEPhPi+0x3e) [0x13276a2]
RTC::SrtpSession::EncryptRtp(unsigned char*, int*)
??:?

[5]: ./MediaServer(_ZN15WebRtcTransport13sendRtpPacketEPKcibPv+0xe2) [0x1277894]
WebRtcTransport::sendRtpPacket(char const*, int, bool, void*)
??:?

[6]: ./MediaServer(_ZN18WebRtcTransportImp9onSendRtpERKSt10shared_ptrIN8mediakit9RtpPacketEEbb+0x259) [0x127da59]
WebRtcTransportImp::onSendRtp(std::shared_ptr<mediakit::RtpPacket> const&, bool, bool)
??:?

[7]: ./MediaServer() [0x1279750]
WebRtcTransportImp::onStartWebRTC()::{lambda(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)#2}::operator()(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&) const::{lambda(std::shared_ptr<mediakit::RtpPacket> const&)#1}::operator()(std::shared_ptr<mediakit::RtpPacket> const) const
WebRtcTransport.cpp:?

[8]: ./MediaServer() [0x127eb79]
void toolkit::List<std::shared_ptr<mediakit::RtpPacket> >::for_each<WebRtcTransportImp::onStartWebRTC()::{lambda(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)#2}::operator()(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&) const::{lambda(std::shared_ptr<mediakit::RtpPacket> const&)#1}>(WebRtcTransportImp::onStartWebRTC()::{lambda(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)#2}::operator()(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&) const::{lambda(std::shared_ptr<mediakit::RtpPacket> const&)#1}&&)
WebRtcTransport.cpp:?

[9]: ./MediaServer() [0x12797e3]
WebRtcTransportImp::onStartWebRTC()::{lambda(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)#2}::operator()(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&) const
WebRtcTransport.cpp:?

[10]: ./MediaServer() [0x127fb2c]
std::_Function_handler<void (std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&), WebRtcTransportImp::onStartWebRTC()::{lambda(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)#2}>::_M_invoke(std::_Any_data const&, std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)
WebRtcTransport.cpp:?

[11]: ./MediaServer(_ZNKSt8functionIFvRKSt10shared_ptrIN7toolkit4ListIS0_IN8mediakit9RtpPacketEEEEEEEclES9_+0x49) [0xe7926b]
std::function<void (std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&)>::operator()(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&) const
??:?

[12]: ./MediaServer(_ZN7toolkit11_RingReaderISt10shared_ptrINS_4ListIS1_IN8mediakit9RtpPacketEEEEEE6onReadERKS7_b+0x2c) [0xe72910]
toolkit::_RingReader<std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > >::onRead(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > const&, bool)
??:?

[13]: ./MediaServer(_ZN7toolkit21_RingReaderDispatcherISt10shared_ptrINS_4ListIS1_IN8mediakit9RtpPacketEEEEEE5writeES7_b+0x101) [0xe6c101]
toolkit::_RingReaderDispatcher<std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > >::write(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > >, bool)
??:?

[14]: ./MediaServer(_ZZN7toolkit10RingBufferISt10shared_ptrINS_4ListIS1_IN8mediakit9RtpPacketEEEEEE5writeES7_bENKUlvE_clEv+0x69) [0xe64549]
toolkit::RingBuffer<std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > >::write(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > >, bool)::{lambda()#1}::operator()() const
??:?

[15]: ./MediaServer(_ZNSt17_Function_handlerIFvvEZN7toolkit10RingBufferISt10shared_ptrINS1_4ListIS3_IN8mediakit9RtpPacketEEEEEE5writeES9_bEUlvE_E9_M_invokeERKSt9_Any_data+0x20) [0xe729c3]
std::_Function_handler<void (), toolkit::RingBuffer<std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > > >::write(std::shared_ptr<toolkit::List<std::shared_ptr<mediakit::RtpPacket> > >, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
??:?

[16]: ./MediaServer(_ZNKSt8functionIFvvEEclEv+0x32) [0xe179e2]
std::function<void ()>::operator()() const
??:?

[17]: ./MediaServer(_ZNK7toolkit17TaskCancelableImpIFvvEJEEclEv+0x7f) [0x12172ab]
toolkit::TaskCancelableImp<void ()>::operator()() const
??:?

[18]: ./MediaServer(_ZZN7toolkit11EventPoller11onPipeEventEvENKUlRKSt10shared_ptrINS_17TaskCancelableImpIFvvEJEEEEE_clES7_+0x34) [0x1216b30]
toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}::operator()(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&) const
??:?

[19]: ./MediaServer(_ZN7toolkit4ListISt10shared_ptrINS_17TaskCancelableImpIFvvEJEEEEE8for_eachIZNS_11EventPoller11onPipeEventEvEUlRKS5_E_EEvOT_+0x81) [0x1217809]
void toolkit::List<std::shared_ptr<toolkit::TaskCancelableImp<void ()> > >::for_each<toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}>(toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}&&)
??:?

[20]: ./MediaServer(_ZN7toolkit11EventPoller11onPipeEventEv+0x15c) [0x1216d94]
toolkit::EventPoller::onPipeEvent()
??:?

[21]: ./MediaServer() [0x12121d4]
toolkit::EventPoller::EventPoller(toolkit::ThreadPool::Priority)::{lambda(int)#1}::operator()(int) const
EventPoller.cpp:?

[22]: ./MediaServer() [0x1214e1d]
std::_Function_handler<void (int), toolkit::EventPoller::EventPoller(toolkit::ThreadPool::Priority)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&)
EventPoller.cpp:?

[23]: ./MediaServer(_ZNKSt8functionIFviEEclEi+0x48) [0xfb6236]
std::function<void (int)>::operator()(int) const
??:?

[24]: ./MediaServer(_ZN7toolkit11EventPoller7runLoopEbb+0x371) [0x1213d0f]
toolkit::EventPoller::runLoop(bool, bool)
??:?

[25]: ./MediaServer(_ZNKSt12_Mem_fn_baseIMN7toolkit11EventPollerEFvbbELb1EEclIJbbEvEEvPS1_DpOT_+0x9a) [0x122349e]
void std::_Mem_fn_base<void (toolkit::EventPoller::*)(bool, bool), true>::operator()<bool, bool, void>(toolkit::EventPoller*, bool&&, bool&&) const
??:?

[26]: ./MediaServer(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS2_bbEE9_M_invokeIILm0ELm1ELm2EEEEvSt12_Index_tupleIIXspT_EEE+0x7b) [0x12233f9]
void std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::_M_invoke<0ul, 1ul, 2ul>(std::_Index_tuple<0ul, 1ul, 2ul>)
??:?

[27]: ./MediaServer(_ZNSt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS2_bbEEclEv+0x2c) [0x122319c]
std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)>::operator()()
??:?

[28]: ./MediaServer(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt7_Mem_fnIMN7toolkit11EventPollerEFvbbEEPS4_bbEEE6_M_runEv+0x1c) [0x1222f20]
std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (toolkit::EventPoller::*)(bool, bool)> (toolkit::EventPoller*, bool, bool)> >::_M_run()
??:?

[29]: /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f6866e63c80]
??
??:0

[30]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f68671346ba]
??
??:0

[31]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f68665c951d]
??
??:0

Segmentation fault (core dumped)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by jiaxiaolong** [comment]
一步步按流程来，可以了， 谢谢大佬

**Comment by xia-chu** [comment]
嗯 srtp编译 你应该没开启openssl
