### ISSUE TITLE
视频小白咨询 gb28181 的相关内容[技术咨询]

### ISSUE THREAD

**Issue by dongrixinyu** [ZLMediaKit/ZLMediaKit#1097]
**咨询的功能模块**
- GB28181

**咨询的具体内容和问题**
- 流媒体功能图中写了可以接收gb28181 的流，然后转推出去。我想问一下，我在网上看，gb 28181 不是开源的？有人建议我买一套gb 的源码作为插件？
- 是不是zlm 已经完全支持了gb 28181 的 推流，只要再加个信令服务器即可实现整个的，从摄像头推流到服务器，然后再以gb28181 推出去 的整个流程？
- 我在其它的 问题里搜索到了 需要配合一个 wv-pro 的信令服务器，是不是这个信令服务器是只针对从摄像头推流过来的配置，不针对再推出去这个步骤？

**注意事项**
- 已经 star 本项目。
- 确实是视频了解很浅，望大佬赐教。

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by zhang2349** [comment]
wvp-pro 都支持了
连接在readme里

**Comment by xia-chu** [comment]
zlmediakit支持GB28181流媒体相关的东西 wvp-pro支持GB28181信令相关的东西。
两种是互相合作项目，是GB28181完整的解决方案。
