### ISSUE TITLE
[技术咨询]关于webrtc播放rtsp流问题

### ISSUE THREAD

**Issue by zhangzhiming1017** [ZLMediaKit/ZLMediaKit#1098]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- webrtc播放rtsp

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- rtsp源是海康和大华的摄像头，播放码流是pcma+h264,vlc能够正常播放，webrtc播放提示"解析sdp o 字段失败:RTSP Session 0 0 IN IP4 0.0.0.0"，错误代码-400
- 我看readme里说明支持acc+h264,所以pcma+h264用webrtc不能播放是不是正常现象

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
嗯 这个rtsp的流 sdp不规范导致的。有测试地址吗？我测试并修改代码，兼容下

**Comment by xia-chu** [comment]
最近更新了下代码 这个问题应该是修复了，请更新代码测试下
