### ISSUE TITLE
如何关闭文件夹浏览[技术咨询]

### ISSUE THREAD

**Issue by qiaoshubin** [ZLMediaKit/ZLMediaKit#1101]
**咨询的功能模块**
- 如何关闭文件夹浏览

**咨询的具体内容和问题**
- 我配置的HTTP下的port是8000，然后我发现通过HTTP方式访问媒体服务器的8000端口，可以看到以rtp命名的文件夹，请问如何关闭文件夹浏览功能？
![rtp](https://user-images.githubusercontent.com/48425903/133038139-2645397a-1f3d-43f3-abf9-faaa42229e3a.png)

**Comment by xia-chu** [comment]
你都不看配置文件注释吗

**Comment by xia-chu** [comment]
[http]
#是否显示文件夹菜单，开启后可以浏览文件夹
dirMenu=1
