### ISSUE TITLE
[技术咨询] WebRTC Demo 报“not support resolution”异常

### ISSUE THREAD

**Issue by zkbiocloud-open** [ZLMediaKit/ZLMediaKit#1105]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- WebRTC

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 线上Demo地址：http://115.159.38.43/webrtc
-  错误信息：
   "TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at Function.createMediaStream (http://115.159.38.43/webrtc/ZLMRTCClient.js:5736:38)
    at http://115.159.38.43/webrtc/ZLMRTCClient.js:7612:25
    at new Promise (<anonymous>)
    at Object.isSupportResolution$1 [as isSupportResolution] (http://115.159.38.43/webrtc/ZLMRTCClient.js:7609:11)
    at start (http://115.159.38.43/webrtc/:162:24)
    at HTMLButtonElement.onclick (http://115.159.38.43/webrtc/:61:39)"

![image](https://user-images.githubusercontent.com/15901405/133183778-e5df42da-d70a-47d5-a417-6abc4fa634e5.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
打开摄像头需要https的网页的 你的明显不是。 这是浏览器的安全限制

**Comment by xia-chu** [comment]
更新下zlm的源码 你们附带了一个有效证书（`default.pem`）了.
域名是test.zlmediakit.com,不过我设置解析到127.0.0.1了，你在浏览器所在电脑修改下host文件就可以使用https了

**Comment by aihsi** [comment]
> 更新下zlm的源码 里面附带了一个有效证书（`default.pem`）了. 域名是test.zlmediakit.com,不过我设置解析到127.0.0.1了，你在浏览器所在电脑修改下host文件就可以使用https了

配置了host，并且启动了MediaServer,https://default.zlmediakit.com/webrtc/ 

无法访问，可以推流，但是无法使用webrtc拉流，
[日志.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/12192238/default.txt)

![1969E0A7-7345-4d76-8561-5E72E7878EBE](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/5a72307d-7152-4bd6-831b-b36a456f5820)
![F0560875-B337-4adb-898D-70B85C420899](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/d2df1062-25af-4bdc-bce8-7d6609516371)
![E69475DB-AAB3-4b63-9C20-E5AB4BA89779](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/aadfee87-c426-44de-8d9f-52d12912bf92)

**Comment by xia-chu** [comment]
> 无法访问，可以推流，但是无法使用webrtc拉流，
你编译没开启srtp，请参考wiki webrtc篇。
