### ISSUE TITLE
推流H265的RTSP流到服务器，播放器拉到的流音频时间戳错误[技术咨询]

### ISSUE THREAD

**Issue by Luh10032** [ZLMediaKit/ZLMediaKit#1106]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 利用ffmpeg将笔记本摄像头和麦克风的数据，推成H265的RTSP流，推到服务器里，命令：ffmpeg -f dshow -i video="USB2.0 HD UVC WebCam"  -vcodec libx265  -acodec aac   -rtsp_transport tcp  -f rtsp 地址，
- 然后再用ffprobe查看流数据输出信息，发现其中音频流和视频流的pts差距过大，导致有的播放器（mpvPlayer）无法播放音频
- 视频流信息:
[log-video.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/7158577/log-video.txt)
- 音频流信息:
[log-audio.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/7158586/log-audio.txt)
视频：
` {
            "type": "packet",
            "codec_type": "video",
            "stream_index": 0,
            "pts": 87569010,
            "pts_time": "972.989000",
            "dts": 87569010,
            "dts_time": "972.989000",
            "size": "24768",
            "flags": "__"
 },`
音频:
`  {
            "type": "packet",
            "codec_type": "audio",
            "stream_index": 1,
            "pts": 4303177520,
            "pts_time": "537897.190000",
            "dts": 4303177520,
            "dts_time": "537897.190000",
            "duration": 1024,
            "duration_time": "0.128000",
            "size": "260",
            "flags": "K_"
 },`

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你是用rtsp播放的吗

**Comment by Luh10032** [comment]
是的，拉的是rtsp流

**Comment by xia-chu** [comment]
你用ffplay播放 音视频同步吗

**Comment by Luh10032** [comment]
刚连上是同步的，但是会有卡顿，卡顿后就音画不同步了

**Comment by xia-chu** [comment]
ZLM版本多少？ rtsp推流，zlm不会去修改时间戳的，你推的是多少，那么播放的就是多少，特别是你推的是rtsp播放也是rtsp，那么相当于透彻而已
