### ISSUE TITLE
对接由大华平台转推来的华平平台视频流出现异常 解析 ps 或 ts 异常

### ISSUE THREAD

**Issue by songbai1997** [ZLMediaKit/ZLMediaKit#1107]
**咨询的功能模块**
- GB28181、RTP、PS

**咨询的具体内容和问题**
- 我们的任务是用ZLM既要对接大华平台连接的摄像头，也要对接由大华平台转推来的华平平台视频流。ZLM把视频流以RTMP格式推出，VLC播放器播放。目前，直接连接大华平台的摄像头能正常播放，但由大华平台转推来的华平平台视频流不能播放，控制台输出显示丢包较多，10分钟后报告：“GB28181Process.cpp:87 onSearchPacketTail | 解析ps或ts异常”。
![解析ps异常](https://user-images.githubusercontent.com/49902281/133367485-025cdc07-a2a6-4504-89fe-416e70e173de.PNG)

**Comment by songbai1997** [comment]
我们使用开源库（https://github.com/debugger999/gb28181ToH264) 直接将获取到的ps流保存成H264文件，使用ffmpeg推H264文件，在VLC和video-js上均能正常播放，大致可以排除视频流的问题，辛苦博主大大抽空解答一下哟。

**Comment by xia-chu** [comment]
应该是丢包了导致ps解析异常，触发了ps解析库的断言。你可以更新下zlm的代码试试，ps解析异常的反馈已经基本没有了，你可能是老代码

**Comment by songbai1997** [comment]
现象是丢包，因此我们尝试了 issues 中的有关丢包的方案，包括尝试最新的版本了，但是还是丢包。

使用 VLC 无法播放ZLM推出来的 rtmp 流，但是使用 opencv 的 VideoCapture 可以读取流，但是读取过程中循环出现如下的错误提示字段
![opencv输出](https://user-images.githubusercontent.com/49902281/133543686-94e52d5f-1e22-4300-9bb4-6349e41f9693.PNG)
获取的每帧视频下方都很模糊

![opencv 获取的画面](https://user-images.githubusercontent.com/49902281/133544165-84383085-89fe-4818-94a5-b5dafadb6615.png)

希望博主大大给点小建议

**Comment by xia-chu** [comment]
你调整系统默认参数了没？ udp socket默认读缓冲，系统默认参数有限制，调大可以减轻丢包

**Comment by songbai1997** [comment]
这个系统是指 ZLM 还是操作系统？ ZLM 和操作系统的参数我们都没动过，使用的默认参数

**Comment by xia-chu** [comment]
https://blog.csdn.net/test1280/article/details/79776938

**Comment by songbai1997** [comment]
修改系统参数后，依然丢包。

![修改后zlm输出](https://user-images.githubusercontent.com/49902281/133571328-fbb78e4d-3f5b-4aa2-a319-3e9eca8ffa79.PNG)

**Comment by songbai1997** [comment]
博主大大，还有没有其他可能导致丢包的设置（ZLM 或 操作系统）

**Comment by xia-chu** [comment]
你会抓包的话 就能判断是否是网络丢包了

**Comment by songbai1997** [comment]
我们是通过VPN远程连接对方的服务器的，之前尝试过抓包，但是没成功。通过  Opencv 读取 ZLM 推出的 rtmp 流，能够读取每一帧，但是每一帧的画面下方都是模糊的，博主经验丰富，能不能给出您的推测呢

**Comment by songbai1997** [comment]
> 你会抓包的话 就能判断是否是网络丢包了
我们使用开源库（https://github.com/debugger999/gb28181ToH264)  直接把ps流存成h264文件能稳定播放，这是否说明在ps流在到达ZLM前网络没有丢包？至少不会像控制台显示的那么多丢包？

**Comment by xia-chu** [comment]
tcpdump也能抓包，不会的话百度下学习下

**Comment by songbai1997** [comment]
昨天我们使用 ZLM 测试的时候， ZLM 终端显示 60000 多帧只丢了 2 帧，但是视频仍旧播放不了。 我们通过 tcpdump 把包抓下来，然后使用 WireShark 查看文件，发现包（使用的UDP协议）确实到达了端口，所以应该不是公网丢包的原因导致的。希望博主大大，有空的时候帮我们分析一些，万分感谢

**Comment by songbai1997** [comment]
这是我们抓包分析的部分结果， Seq 是连续的

![image](https://user-images.githubusercontent.com/49902281/134468346-1c2b19c8-371e-496b-aff9-4c88940e32a6.png)

**Comment by songbai1997** [comment]
1、“直接连接大华平台的摄像头能正常播放”
2、“由大华平台转推来的华平平台（gb28181 2016版）视频流不能播放”

针对以上两种摄像头，做了以下实验

配置 ZLM 导出调试数据，获取了 mp3 格式声音文件，RTP 文件，video 文件

使用 1 的摄像头：
        VLC 和 KMplayer 都能播放获取的 video 文件（video的属性 format profile 是 High@L4.1） 

使用 2 的摄像头：
        VLC 不能播放获取的 video 文件，但是使用 KMplayer 可以播放（video的属性 format profile 是 Main@L4.2） 

会不会是 H264 的两种不同的规格导致连接 2 的摄像头出现异常情况，多谢解答

**Comment by hwu168** [comment]
你前面提到“直接把ps流存成h264文件能稳定播放”，说明zlm推出后不能播放的问题，应该与H264的具体格式和版本无关。

**Comment by songbai1997** [comment]
接上一条提问：

经过测试，在 windows 环境下把 .video 文件的后缀改为 .h264 后可使用 vlc 播放；直接推 .video 文件到 nginx-rtmp 服务器，其分发的流地址也能正常播放

备注：之前获取的视频画面下方模糊的现象只存在于个别摄像头，因此可忽略

希望博主能抽空帮助一下，万分感谢

**Comment by hwu168** [comment]
zlm导出调试数据中的视频可以播放，应该说明zlm对ps流的解析和gb28181ToH264对ps流的解析同样是正确的。你看看你的问题是否和zlm的某些设置有关呢？具体我懂得也不多，觉得你这个问题确实有些蹊跷。另外，是否和多层的级联有关呢？你这个从摄像头到华平，再到大华，再到zlm，再到客户端。
