### ISSUE TITLE
[技术咨询] 关于海康NVR无法解析ZLMediaKit推的rtsp H265码流

### ISSUE THREAD

**Issue by fenyi2016** [ZLMediaKit/ZLMediaKit#1111]
**咨询的功能模块**
rtsp, H265

**咨询的具体内容和问题**
场景：摄像头h265 rtsp码流，经ffmpeg拉流 不转码直接推流给ZLM转发，然后NVR从ZLM拉流。
现象：NVR预览视频流时黑屏，且无法录像。
推流命令：ffmpeg -rtsp_transport tcp -i "rtsp://******:******@192.168.2.37:554/cam/realmonitor?channel=1&subtype=0" -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test
ZLMediaKit设置：默认设置

已经尝试过：
1. 将copy替换为libx265，NVR无法预览；将copy替换为libx264，可以正常预览
2. 将NVR替换为VLC，VLC可以正常播放H265码流
3. 把摄像头h265 rtsp码流直接推给NVR，NVR可以预览

鉴于评论中ZLM是完全代理转发rtsp，仅在sdp里添加ZLM相关信息，推测是ffmpeg和海康NVR对rtsp的实践不太一致。求教可能的原因？谢谢！

PS：
尝试2中，用wireshark对NVR 访问服务器的抓包，和VLC 访问服务器的抓包如下：
192.168.2.37 摄像头
192.168.2.244 ffmpeg和ZLM（虚拟机）
192.168.2.124 vlc
192.168.2.97 NVR
[h265 rtsp nvr.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/7217015/h265.rtsp.nvr.zip)
[h265 rtsp vlc.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/7217018/h265.rtsp.vlc.zip)

**Comment by wasphin** [comment]
能不能上传一段 NVR 访问服务器的抓包? @fenyi2016

**Comment by xia-chu** [comment]
`ffmpeg -re -i test.mp4 -vcodec libx265 -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test` nvr不可以预览
`ffmpeg -rtsp_transport tcp -i "rtsp://:@192.168.2.37:554/cam/realmonitor?channel=1&subtype=0" -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test` 可以预览

说明什么？ 真说明不了什么，因为都是FFmpeg推的rtsp流，在转发rtsp时，zlm是完全代理转发，只会修改一点点sdp的信息(加入zlm的相关描述)， rtp也是原封不动的转发。

上述两个命令，唯一的差别就是，上面的你是转码了，下面你没转码。

**Comment by xia-chu** [comment]
所以我猜测是，x265默认转码的视频，你的nvr不支持，你可以改成这样`ffmpeg -rtsp_transport tcp -i "rtsp://:@192.168.2.37:554/cam/realmonitor?channel=1&subtype=0" -vcodec libx265 -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test`
估计nvr也是不能播放

**Comment by fenyi2016** [comment]
万分感谢，已补充实验并缩小问题范围

**Comment by xia-chu** [comment]
`ffmpeg -rtsp_transport tcp -i "rtsp://:@192.168.2.37:554/cam/realmonitor?channel=1&subtype=0" -vcodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test` 这样你的nvr还是不能播放？

**Comment by fenyi2016** [comment]
是的

**Comment by xia-chu** [comment]
能否抓个包，就是copy方式推流到zlmediakit后，nvr从zlmediakit拉rtsp流的包。同时观察下zlmediakit的日志是否有异常

**Comment by fenyi2016** [comment]
抓包已更新到问题里，h265 rtsp nvr.zip 是NVR从ZLM拉流的包。
ZLM的日志没有观察到明显异常，如下图：
![nvr](https://user-images.githubusercontent.com/22061290/134653221-0ee0ea0a-f577-4ee1-93ef-4b99ec4266c1.png)

**Comment by xia-chu** [comment]
我是说 你抓包nvr播放zlm的rtsp的流的包

**Comment by wasphin** [comment]
`h265 rtsp vlc.pcapng` 中 `tcp.stream eq 3` 可以过滤出 nvr 向 zlm 申请的包, nvr 使用的 tcp, 在 nvr 抓包的 2205 包中貌似多了一段数据, 导致 wireshark 未能解析出 rtp 包.  而 vlc 使用的 udp, 没这个问题.

**Comment by xia-chu** [comment]
这里有点异常
<img width="1554" alt="图片" src="https://user-images.githubusercontent.com/11495632/134663810-9b42a18a-ccd0-4f7b-ab76-d693d452c05f.png">

**Comment by xia-chu** [comment]
更新下zlm试试？

**Comment by fenyi2016** [comment]
【问题已解决】
经帖子提醒，最终确认是海康NVR无法解析RTP协议里vps等信息的聚合包，只能解单NAL形式的。
https://blog.csdn.net/zhichi202/article/details/105750276

【解决方案】：ZLM的config.ini设置directProxy=0即可。
设置参考 https://github.com/zlmediakit/ZLMediaKit/blob/master/conf/config.ini

万分感谢各位大神的支援！
