### ISSUE TITLE
[技术咨询] 请问为什么我的zlm ws格式的fmp4流没有生成

### ISSUE THREAD

**Issue by addriumruss** [ZLMediaKit/ZLMediaKit#1114]
我的fmp4端口是10020, 平时都这样访问 http://ip:10020/live/abc.live.mp4, 
改为 ws://ip:10020/live/abc.live.mp4后，怎么都播放不了 
请问这是怎么回事呢  是ws流没有生成吗

**Comment by xia-chu** [comment]
我现在还不知道有播放器支持ws-fmp4,如果您知道的话，请告诉我。
