### ISSUE TITLE
[功能请求] 请问HTTP2.0有支持计划吗

### ISSUE THREAD

**Issue by addriumruss** [ZLMediaKit/ZLMediaKit#1115]
http1.1限制单页面播放数量不超过6个，如果支持http2就不受限制了

**Comment by penghd** [comment]
用https、ws都可以解决

**Comment by addriumruss** [comment]
@penghd 谢谢解答！  请问怎么启用https、ws？ 我现在用的是fmp4格式，把地址中的http替换为ws直接无法播放

**Comment by xia-chu** [comment]
flv.js支持ws-flv的，ws-fmp4目前我也不知道什么播放器支持

**Comment by wujincheng2333** [comment]
用nginx http2代理 zlm的http端口

**Comment by addriumruss** [comment]
这个想法挺好 我尽快试下

**Comment by wujincheng2333** [comment]
可以实现的，这种骚操作我玩过，但后来又不用了，http2普及还是不高。

**Comment by addriumruss** [comment]
现在主流浏览器应该都支持http2吧   好像必须是https才行， 这样自己制作的ssl证书，在js播放器那边有没有什么影响，能自动播放吗

**Comment by xia-chu** [comment]
http2暂时不考虑，因为时间和精力实在有限，issue先关闭了。
