### ISSUE TITLE
[技术咨询] Docker 安装，怎么实现 rtsp 流转 flv 

### ISSUE THREAD

**Issue by zeminli** [ZLMediaKit/ZLMediaKit#1116]
docker run -id -p 1935:1935 -p 8080:80 -p 8554:554 -p 10000:10000 -p 10000:10000/udp panjjo/zlmediakit

请问 Docker 安装，怎么实现 rtsp 流转 flv

**Comment by penghd** [comment]
ZLM是以接口提供功能的，请看wiki，API和流地址两章。

**Comment by zeminli** [comment]
好的~

**Comment by zeminli** [comment]
> ZLM是以接口提供功能的，请看wiki，API和流地址两章。

好的~
