### ISSUE TITLE
[技术咨询] HTTP API：添加rtsp/rtmp主动推流如何做到不重试

### ISSUE THREAD

**Issue by bravecat** [ZLMediaKit/ZLMediaKit#1117]
**咨询的功能模块**
- HTTP API：添加rtsp/rtmp主动推流(把本服务器的直播流推送到其他服务器去)

**咨询的具体内容和问题**
- 如何做到不重试？假如传 `retry_count: 0`, 结果会变成 -1

**Comment by xia-chu** [comment]
参数改成1应该可以的

**Comment by bravecat** [comment]
> 参数改成1应该可以的

1会重试1次吧？我是不要重试。

**Comment by xia-chu** [comment]
<img width="1020" alt="图片" src="https://user-images.githubusercontent.com/11495632/135752505-85dfdf7a-6df9-4da9-93fb-f4ce895b55b4.png">
重试次数为0时 确实不会重试。
不过话说会开，重试一次跟不重试本质上不会有什么区别，也不会导致什么后果。

**Comment by bravecat** [comment]
这里会把 0 变成 -1
https://github.com/ZLMediaKit/ZLMediaKit/blob/a83187d25fbc464496256622f0d7df9f8799b2f8/server/WebApi.cpp#L678

这个场景重试1次和不重试有区别的：
1. 媒体服务器A推流到媒体服务器B;
2. B因无人播放关闭流;
3. 如果A重试推流，B又生成流。结果B循环关闭和生成流，而A一直重试推流（因为重试成功后归0）
