### ISSUE TITLE
端口映射后，hls无法播放

### ISSUE THREAD

**Issue by zhuqiyun** [ZLMediaKit/ZLMediaKit#1118]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by penghd** [comment]
没有问题，你检查下映射，直接访问映射IP:端口会列出目录或ZLM自带错误提示吗

**Comment by zhuqiyun** [comment]
> 没有问题，你检查下映射，直接访问映射IP:端口会列出目录或ZLM自带错误提示吗

可以了，忘了出入站规则设置了
