### ISSUE TITLE
[技术咨询] 请问HTTPS怎么配置证书，尝试了没成功

### ISSUE THREAD

**Issue by addriumruss** [ZLMediaKit/ZLMediaKit#1120]
节日快乐！

按照网上教程做了一个ssl.p12证书，放在bin目录下， 重启了mediaserver, 推流，拉流，日志总是提示这个错误：
2021-09-19 22:05:39.782 D MediaServer[4559] SSLBox.cpp:159 findCertificate | can not find any certificate of host:default host
改为直接用-s参数指定ssl.p12再重试，结果还是一样。
请问配置ssl.p12证书是否有什么特殊步骤？
谢谢！

**Comment by penghd** [comment]
wiki里有自签名证书操作和证书格式，但是这样播放的时候浏览器会提示不可靠证书，需要操作允许才能访问，因为ZLM没有界面，只有调视频时访问，很麻烦，只有该机先登录一次，以后才能访问。
你只要有DNS服务器控制权（或者有人能帮你操作），就可以向腾讯云这些发证单位申请免费证书。

**Comment by xia-chu** [comment]
最新的zlmediakit源码自带有效的ssl证书default.pem,对应的域名是default.zlmediakit.com,该域名解析到的ip为127.0.0.1,用户在浏览器中打开 https://default.zlmediakit.com/webrtc/即可开始测试。请先推流后，再测试播放。

**Comment by addriumruss** [comment]
感谢回应！ 
我平时都直接服务器测试，请问默认证书能改为公网IP吗

**Comment by xia-chu** [comment]
可以啊 你在测试主机修改下host文件就行





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: russ ***@***.***&gt;
发送时间: 2021年9月22日 11:36
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] 请问HTTPS怎么配置证书，尝试了没成功 (#1120)





 
感谢回应！
 我平时都直接服务器测试，请问默认证书能改为公网IP吗

**Comment by addriumruss** [comment]
大佬，感谢回应！ 还是没太懂啊  我是centos7云主机，意思是要修改/etc/hosts吗  

现在内容是这样：
[root@video gb28181-server-02]# more /etc/hosts
::1	localhost	localhost.localdomain	localhost6	localhost6.localdomain6
127.0.0.1	localhost	localhost.localdomain	localhost4	localhost4.localdomain4
172.19.98.89	video	video

请问是否要加这么一行： 公网IP  default.zlmediakit.com default.zlmediakit.com

**Comment by xia-chu** [comment]
你不是想`default.zlmediakit.com`指向你服务器公网ip吗？那你在访问`default.zlmediakit.com`的电脑上，修改下host文件，让`default.zlmediakit.com`指向你服务器公网ip就行啊

**Comment by addriumruss** [comment]
这样啊 估计我客户没法认同  
请问自己加证书为啥不成功呢，有什么特别要注意的吗

**Comment by xia-chu** [comment]
你自己都没买域名和证书 怎么测试？

**Comment by addriumruss** [comment]
确实没域名，因为只是用作流媒体服务器就没申请域名，关键是域名备案时间太长。
请问不配域名、证书按百度教程自己制作这样不行吗，真是要命啊，之前不知道浏览器限制只能访问6路

**Comment by xia-chu** [comment]
没域名和证书 那么浏览器默认是不信任的 你要单独设置浏览器，更麻烦

**Comment by xia-chu** [comment]
该问题已经超出了issue讨论的范围了 先关闭了，有问题直接在这答复

**Comment by xia-chu** [comment]
浏览器限制只能访问6路，是单host的情况下 只允许最多6个链接，但是websocket除外，你可以用ws-flv播放
