### ISSUE TITLE
[技术咨询] webrtc demo无法播放视频流

### ISSUE THREAD

**Issue by kuaidou** [ZLMediaKit/ZLMediaKit#1123]
**咨询的功能模块**
- WebRtc模块视频播放问题

**咨询的具体内容和问题**
- 现象描述
  在刚开始使用的时候，可以从webrtc demo里面播放视频，之后某几次试验后无法播放视频（试验是正常的播放与停止，为做其他操作）。使用最新的代码亦是如此。
- 抓包与日志

[抓包.pcapng.gz](https://github.com/ZLMediaKit/ZLMediaKit/files/7208030/pcapng.gz)

[request.log](https://github.com/ZLMediaKit/ZLMediaKit/files/7208042/request.log)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
8000端口都关闭了吧？

**Comment by kuaidou** [comment]
8000端口确实没有开，但是之前为啥是好的额。我代码里没有主动去开启这个端口的udp服务

**Comment by xia-chu** [comment]
webrtc现在改成单udp端口模式了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: kuaidou ***@***.***&gt;
发送时间: 2021年9月22日 14:48
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] webrtc demo无法播放视频流 (#1123)





 
8000端口确实没有开，但是之前为啥是好的额。我代码里没有主动去开启这个端口的udp服务

**Comment by kuaidou** [comment]
开启udp服务后，问题解决
