### ISSUE TITLE
[技术咨询]能否实现按起止时间进行点播回放

### ISSUE THREAD

**Issue by huyji-000** [ZLMediaKit/ZLMediaKit#1124]
**咨询的功能模块**
- mp4点播

**咨询的具体内容和问题**
- wiki只找到了单个MP4的点播功能，请问能否根据起止时间自动拼接多个MP4呢

**Comment by monktan89** [comment]
文件都是有起始时间的，这个自己用模块进行二次开发不难

**Comment by huyji-000** [comment]
> 文件都是有起始时间的，这个自己用模块进行二次开发不难

奈何不懂c++，很难在ZLMediaKit源码上动手脚，请问有什么模块推荐么
