### ISSUE TITLE
[技术咨询]大佬，可以出个windows10详细的编译运行教程不？

### ISSUE THREAD

**Issue by lujingwen2122** [ZLMediaKit/ZLMediaKit#1125]
**新手不懂vs，c++好难搞呀**

 百度的都是只言片语的编译教程，没法解决呀。我用vs2019编译，一直不成功，搞了两天了还没搞好。。其中有个错误是这样的

严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	E0144	"const rsa_st *" 类型的值不能用于初始化 "RSA *" 类型的实体	zltoolkit.lib (D:\ZLMediaKit\release\windows64\Debug\zltoolkit.lib) - x64-Debug	D:\ZLMediaKit\3rdpart\ZLToolKit\src\Util\SSLUtil.cpp	315

希望大佬能帮忙解决一下，我真不适合伸手党，我是翻烂了百度都找不到一点信息，只能来求助大佬了。谢谢

**Comment by xiongguangjie** [comment]
看wiki呀

**Comment by xiongguangjie** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki

**Comment by lujingwen2122** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/wiki

不好意思，我不太懂c++，我就是对着wiki来做的。openssl也安装了最新的3.0.0，打开vs2019点击生成，报了好多错误，请指教

**Comment by xia-chu** [comment]
去这里下载一个openssl安装版吧：http://slproweb.com/products/Win32OpenSSL.html

**Comment by xiongguangjie** [comment]
你用现成的不就行了，加入QQ群去群文件下个现成的

**Comment by lujingwen2122** [comment]
> 去这里下载一个openssl安装版吧：http://slproweb.com/products/Win32OpenSSL.html

我已经下了openssl3.0.0 的64位的，但是还是这样的，有点懵了，我换32位的试一下

**Comment by zhang2349** [comment]
下openssl 1.1.1的 
3.0的版本 返回加了const 所以会报错
