### ISSUE TITLE
webrtc  播放问题

### ISSUE THREAD

**Issue by qwd108114** [ZLMediaKit/ZLMediaKit#1128]
直接拉取RTSP摄像头流，用WEBRTC 播放没有问题
直接拉取NVR RTSP流，用WEBRTC 播放就会有问题，会报
offer answer 交换失败 {code: -400, msg: '解析sdp c 字段失败:IN c=IN IP4 0.0.0.0'}code: -400msg: "解析sdp c 字段失败:IN c=IN IP4 0.0.0.0"[[Prototype]]: Object
目前群主的解决办法是修改config.ini配置文件 directProxy=0 可完美解决这个问题
但相信目前很多人不知道这个解决办法，希望群主能写进wiki 或改进代码，使得我们的ZLM 更完美更强大

**Comment by xia-chu** [comment]
能否提供下nvr rtsp的sdp?

**Comment by xia-chu** [comment]
应该兼容了，麻烦你测试下 谢谢！
