### ISSUE TITLE
[功能请求]播放录像时设置倍速功能

### ISSUE THREAD

**Issue by rqb500** [ZLMediaKit/ZLMediaKit#1129]
目前播放录像时zlm对设置倍速命令有反应，但没有实际调整倍速。希望增加调整播放速度功能，最好可以增加对应的restful接口以便使用，谢谢

**Comment by bwlfhu** [comment]
今天刚想提这个来着，国标级联场景下，录像的VCR控制是其中的功能，希望能增加RTSP信令控制功能

**Comment by xia-chu** [comment]
已实现
