### ISSUE TITLE
[个人建议]使用VS2019编译会报E0144 "const rsa_st *"错误

### ISSUE THREAD

**Issue by lujingwen2122** [ZLMediaKit/ZLMediaKit#1130]
**如题**
- 使用VS2019编译，ZLToolkit项目中的SSLUtil类=》315,342行代码的 RSA *rsa = EVP_PKEY_get0_RSA(private_key);代码会报E0144 "const rsa_st *"错误，建议使用强转，如：RSA *rsa = (RSA *)EVP_PKEY_get0_RSA(private_key);

**Comment by xia-chu** [comment]
这个应该是openssl版本兼容性问题，你用的openssl版本多少？我这边没报这种错

**Comment by lujingwen2122** [comment]
> 这个应该是openssl版本兼容性问题，你用的openssl版本多少？我这边没报这种错

我用的3.0.0 64位 140M的那个，另外，这个E0144好像是vs2019不兼容的问题，csdn有人反映过：https://blog.csdn.net/zhao5269/article/details/105114473

**Comment by zhang2349** [comment]
下openssl 1.1.1的
3.0的版本 返回加了const 所以会报错

**Comment by thewaterislo** [comment]
我也是64位的openssl报这个错误，换成32位的倒是编译成功了
