### ISSUE TITLE
[技术咨询]使用webrtc远程拉流时播放失败

### ISSUE THREAD

**Issue by tonyonce2017** [ZLMediaKit/ZLMediaKit#1131]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
- 大佬, 我在局域网部署ZLM开启webrtc功能, 使用webrtc demo可以正常播放, 我把ZLM部署到外网服务器上, 按照相同的方法部署并且使用的自生成证书, 也把服务器的ip端口加入到谷歌浏览器安全列表(chrome://flags/#unsafely-treat-insecure-origin-as-secure), 播放rtsp, hls流均正常, webrtc流播放失败, 查看ZLM日志如下, 播放界面控制台也显示播放成功, 是否webrtc还需要开放什么端口, 谢谢:
- 
![image](https://user-images.githubusercontent.com/34465929/134500125-8bce34d9-a4a0-4681-8335-345a9af4961d.png)
![image](https://user-images.githubusercontent.com/34465929/134500230-f8562275-05ba-484c-bbf1-0f48fa38abbe.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
配置文件有设置externIP吗

**Comment by xia-chu** [comment]
看你sdp 并没有设置

**Comment by tonyonce2017** [comment]
谢谢大佬, 确实是没设置externIp
