### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Lavc-31** [ZLMediaKit/ZLMediaKit#1132]
**Bug report**
- The CLI prompts for a command to be given but doesn't do anything else regardless of the input I use (I can only kill the process with CTRL+C).
- The bug happens after using the command "sudo docker run panjjo/zlmediakit" in the linux terminal. (Look at right side of the screen in the picture).
![image_2021-09-21_192400](https://user-images.githubusercontent.com/88551937/134609637-c8a84611-1cea-4a26-9c8e-60764620495a.png)
- The bug keeps happening no matter how I run the software.

**OS Enviroment**
- I have the same bug when using 2 different computers (a toshiba notebook with ubuntu 18.04 and a desktop PC with ubuntu 20.04), both with a 64 bits OS so I think it doesn't have to do with the enviroment

**Help is greatly appreciated, thank you in advance**

**Comment by xia-chu** [comment]
The shell command interaction function of zlmediakit is basically abandoned，we don't recommend you use it, we intend to remove it in the future.
But you can type `help -h` to try the only bit little function.

**Comment by xia-chu** [comment]
Since there is a bug blocking stdout in the simultaneous input and output of multiple threads in the shell, this function can be removed.

**Comment by Lavc-31** [comment]
Thank you for the fast answer, I have a couple of little questions regarding what you just said.
When using only zlmediakit in just one shell and nothing more the bug keeps happening. And since shell is not recommended... is there any way to connect the zlmediakit client with a rtsp server from another software? maybe using a given URI from the server? where can I find information on this matter?

**Comment by wasphin** [comment]
>  is there any way to connect the zlmediakit client with a rtsp server from another software? maybe using a given URI from the server? where can I find information on this matter?

You mean to let zlmediakit pull RTSP stream from your `rtsp-simple-server`? If so, you can have a look at the [web api](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy).

**Comment by Lavc-31** [comment]
yes, that's what I meant, thank you very much for your help
