### ISSUE TITLE
[BUG]rtsp流播放，客户端使用base64加密时播放失败

### ISSUE THREAD

**Issue by lifeng1994** [ZLMediaKit/ZLMediaKit#1133]
**bug现象**
客户端在使用base64编码进行rtsp协议通信时，由于content内容带有换行或空格，
导致base64解码失败，进而协议通信失败。在使用live555做服务器时，是能正常播放的。
问题跟踪发现是live555对content的字符做了过滤。
live555的content内容解析如下：
![JODAIYJD_0JX6(MY3{6%VFQ](https://user-images.githubusercontent.com/24370921/134616053-e9a02b25-af9f-44e3-b8f4-2d850f566e39.png)
我对base64做了如下修改后正常播放
![($MS _ K7}WRWVO@XOZW8HV](https://user-images.githubusercontent.com/24370921/134616689-5891e199-0f98-4ee9-b59d-c90d89d221b4.png)

-

**Comment by xia-chu** [comment]
这个代码来自FFmpeg，可能需要修改下

**Comment by penghd** [comment]
对rtsp地址urlencode，就行了，刚解决这问题。

**Comment by lifeng1994** [comment]
> 对rtsp地址urlencode，就行了，刚解决这问题。

你这个应该是从客户端行为解决的吧，我的是服务器，要尽可能的兼容客户端

**Comment by xia-chu** [comment]
@lifeng1994 能否提交个pr？ 谢谢！

**Comment by lifeng1994** [comment]
> @lifeng1994 能否提交个pr？ 谢谢！

好的
