### ISSUE TITLE
[BUG] ZLM rtmp协议修正及原因问询

### ISSUE THREAD

**Issue by HR1025** [ZLMediaKit/ZLMediaKit#1135]
**bug现象**
今日使用 zlm 向 Adobe RTMP服务器推流时出现异常，表现为 socket 断开，但是 ffmpeg 可以正常推流，在对比 ffmpeg 源代码以及使用 wireshark 抓包分析后，修改以下两处地方成功使用 zlm 向 Adobe RTMP 服务器推流。
修改点如下：
1. void RtmpProtocol::sendRequest(int cmd, const string& str) 中的：
sendRtmp(cmd, _stream_index, str, 0, CHUNK_SERVER_REQUEST);  替换为 sendRtmp(cmd, _stream_index, str, 0, CHUNK_CLIENT_REQUEST_BEFORE);
2. void RtmpPusher::onConnect(const SockException &err) 中的：
strong_self->sendChunkSize(60000); 替换为 //strong_self->sendChunkSize(60000); 即注释此句

** rtmp 服务器类型 **
Adobe

**推流测试程序**
test_pusher

**其他**
问题产生原因、分析及修改原因附在附件里，因为有一点点长。

并且附加4个 wireshark 包，分别为 ffmpeg 、zlm修复前、zlm修复1后、zlm修复2后 rtmp推流包。
(Wireshark包发不上来)

[ZLM rtmp协议修正及原因问询.pdf](https://github.com/ZLMediaKit/ZLMediaKit/files/7225538/ZLM.rtmp.pdf)

**Comment by xia-chu** [comment]
大佬 你的文档写的很完善 分析总结的很好，看的出来发费了很多时间和精力。
我觉得setchunksize可以移到后面的流程，只要对比obs等抓包，移动到合适的时机发送即可，去掉后，chunk分包的效率会比较差。由于wireshark对rtmp协议支持有限，在修改chunk size后，可能分析不出rtmp包。所以你说的`不过实际上注释掉 setchunksize好一点不然重连很多`是不是这个意思？

另外，chunk id这个修改得比较慎重，修改后其他服务器都能支持吗？

还有，如果只是把简单握手改成复杂握手，是否能确保推流fms(adobe的rtmp服务器)成功？

**Comment by HR1025** [comment]
在connect阶段set chunk size 会加大重新rtmp三次握手的可能性，可能原因是zlm的定时器时间过短，有几次看到adobe服务器已经响应conect,但是zlm已经开始重新握手了，我也觉得把 set chunk size 移后会好一些。

修改 chunk id后推流几个服务器没有出现问题，但是修改原因暂时不知道，因为还没有找到有关于此新的文档;之后也打算是调查修改此处具体的含义，看看能不能找到相应的文档，以及结合 ffmpeg 与 obs 的源码。
只是修改复杂握手是不行的，或者说问题不出现在于此，我添加复杂握手的方式是不可取的，做法是动态链接 ffmpeg 的 avutil 库，然后全量移植 ffmpeg 有关复杂握手的接口，zlm 临时搭建的复杂握手完全与 ffmpeg 保持一致，即使如此仍然连接不成功。
在这个基础上修改 chunk id 以及 注释 set chunk size 才 connect 成功，这个时候 pdf 三个不同点已经完全一致， ffmpeg 与 zlm 在conect 之前(包括 connect)完全一致。
为了排除我在修改的过程中污染 zlm 的源码，最后面重新 git clone 一份 zlm，仅仅只是修改 chunk id 以及注释 set chunk size 就推流 FMS 成功了，所以我认为推流FMS与复杂握手无关，跟 chunk id 有关。
(最后阅读 ffmpeg 确认 ffmpeg 仅仅支持复杂握手，不存在开关控制复杂与简单握手，并且简单握手的 zero 字段填充的是 flashver，如果我没有记错的话，你可以试下在 ffmpeg 搜索 rtmp_open，这个函数里有一个带有 handshake的函数，里面就有ffmpeg rtmp复杂握手的实现了。)

**Comment by HR1025** [comment]
chunk id 的修改确实需要更加谨慎，要更加细分一点，具体的细分修改在后面确认。

**Comment by HR1025** [comment]
已经确认过 chunk id 修改的合理性，在附件里有对此进行解释；以及为何要这么修改的原因，这里可能从最初就是一个 bug ,或者FMS对 RTMP 协议的检查更加细致。
[zlm rtmp协议修正具体分析.pdf](https://github.com/ZLMediaKit/ZLMediaKit/files/7249489/zlm.rtmp.pdf)

**Comment by xia-chu** [comment]
非常棒 非常感谢！
