### ISSUE TITLE
[BUG]web端无法播放https hls流

### ISSUE THREAD

**Issue by huyji-000** [ZLMediaKit/ZLMediaKit#1136]
**bug现象**
- web端无法播放https hls流

**bug产生时的使用场景**
- 访问hls流时，浏览器会先发一个HEAD请求
- http情况下能够正常返回
- https请求没有收到正常返回，因此没有进行后续取流

**zlm代码git commit hash值**
- HttpSession.cpp中这里sendResponse(200, true)改为sendResponse(200, false)可以解决问题
![image](https://user-images.githubusercontent.com/80040213/134796215-cafa1bcc-1870-40ec-bed4-ac9348733507.png)
- 但是不太清楚c++的连接逻辑，不知道这样不断开连接是否会引起普通http请求的效率问题

**Comment by xia-chu** [comment]
谢谢！

**Comment by qinc998** [comment]
你好，我今天删除ZLMediaKit文件夹，clone代码，重新编译的，还是出现https hls播放超时的问题，vlc、web+hlsjs 都不行，但是http+ip可以正常播放。
证书使用阿里云申请的免费证书，使用telnet 域名 端口，是通的，telnet日志也有反应，80端口已经修改为其他，是不是我哪一步错了

![Dingtalk_20211008152620](https://user-images.githubusercontent.com/36267257/136516087-43a20f5e-6e47-4b62-9dcd-264513032aec.jpg)

![Dingtalk_20211008152515](https://user-images.githubusercontent.com/36267257/136516102-44603296-6809-47e8-9529-0b3aa4516ae8.jpg)

![Dingtalk_20211008152354](https://user-images.githubusercontent.com/36267257/136516105-289c0719-7f22-4d62-b04a-afd89d5a48b3.jpg)

**Comment by xia-chu** [comment]
看日志 你是用https访问http端口去了

**Comment by huyji-000** [comment]
config.ini了解一下
wiki都不看就问的问题，作者估计都答烦了。。。

**Comment by huyji-000** [comment]
有可能是你的vlc版本太老，而证书的tls版本比较高

**Comment by qinc998** [comment]
> 有可能是你的vlc版本太老，而证书的tls版本比较高

感谢，我也感觉是证书问题，web播放报错ERR_SSL_VERSION_OR_CIPHER_MISMATCH，我再自己尝试一下，感谢二位

**Comment by huyji-000** [comment]
阿里云生成的pem文件好像不能拿来用
可以用public.crt加.key文件自己合成一个pem

**Comment by qinc998** [comment]
确实是证书问题，下载阿里apache版本，再按照wiki生成ssl步骤，走一次公私钥合并就可以正常使用了，感谢二位
