### ISSUE TITLE
[功能请求]mk_api增加日志模块文件大小，文件个数的配置

### ISSUE THREAD

**Issue by ChnPhantom** [ZLMediaKit/ZLMediaKit#1138]
mk_env_init1接口只有设置日志保存天数，没有设置日志文件大小和数量的配置。

**Comment by xia-chu** [comment]
嗯 是的 你可以加个api &nbsp;反正 封装下也很简单啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: freesky ***@***.***&gt;
发送时间: 2021年9月27日 15:22
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [功能请求]mk_api增加日志模块文件大小，文件个数的配置 (#1138)





 
mk_env_init1接口只有设置日志保存天数，没有设置日志文件大小和数量的配置。

**Comment by ChnPhantom** [comment]
是的，我们在项目上是这样做的。

**Comment by xia-chu** [comment]
修改后可以提个pr



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: freesky ***@***.***&gt;
发送时间: 2021年9月27日 17:56
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [功能请求]mk_api增加日志模块文件大小，文件个数的配置 (#1138)





 
是的，我们在项目上是这样做的。

**Comment by ChnPhantom** [comment]
我按照gitee的操作提交提示我403错误，我是本地新建一个分支然后合并到master推送的，不知这样做是否正确
