### ISSUE TITLE
[BUG] 项目工程中 Android 工程 , 编译失败.  

### ISSUE THREAD

**Issue by xiaoxianBoy** [ZLMediaKit/ZLMediaKit#1141]
场景:
Android Studio  编译 
Android Studio 4.1.2
NDK 版本 21.1.6352462

bug:
编译失败. 
![image](https://user-images.githubusercontent.com/22361503/135223697-d89fb324-0397-4233-a18d-f5ccc578c6f1.png)

有没有Android 项目能编译成功的Demo?

**Comment by xia-chu** [comment]
该问题已修复
