### ISSUE TITLE
[技术咨询]对 “整理http相关代码”有一些困惑

### ISSUE THREAD

**Issue by varichs** [ZLMediaKit/ZLMediaKit#1144]
**webhook**
- 最新的合并中，对 “整理http相关代码”有一些困惑

`if (res.Url() != "200") {
        auto errStr = StrPrinter << "[bad http status code]:" << res.Url() << endl;
        fun(Json::nullValue, errStr);
        return;
    }`

这部分代码的含义是不是有些歧义，前面的方法名叫做 Url（），但好像下面比较的值是http响应状态码

**Comment by xia-chu** [comment]
是的 这个类最开始是为了解析http请求的，但是同时也可以解析http回复，http回复的状态码 正好跟http请求的url为相同的位置
