### ISSUE TITLE
[技术咨询]使用海康的智能分析叠加的视频流

### ISSUE THREAD

**Issue by taotaochanghe** [ZLMediaKit/ZLMediaKit#1145]
**咨询的功能模块**
- 使用海康的智能分析叠加的视频流

**咨询的具体内容和问题**
- 使用海康的智能分析叠加的视频流，视频流中带有设备商自己的分析数据，只支持设备商的播放库来播放。ZLMediaKit有没有支持自定义视频数据流的分发设计。类似插件机制，分发私有视频流，前端使用厂商自己的播放库来播放。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by tsingeye** [comment]
海康有个码流分析库 可以拿到裸264 265数据

**Comment by xia-chu** [comment]
比如说rtp中可以在ext字段放东西，还可以在padding字段放

**Comment by taotaochanghe** [comment]
感谢作者回复。
