### ISSUE TITLE
通过华平、大华级联到ZLM的视频无法播放

### ISSUE THREAD

**Issue by songbai1997** [ZLMediaKit/ZLMediaKit#1147]
**咨询的功能模块**
RTP、GB28181

**咨询的具体内容和问题**

备注：针对 【#1107】号 issue，由于我们进一步定位了问题，原标题和内容需要重新修改，因此新开了此 issue

我们的任务是用ZLM既要对接大华平台连接的摄像头，也要对接由大华平台转推来的华平平台视频流。ZLM把视频流以RTMP格式推出，VLC播放器播放。目前，直接连接大华平台的摄像头能正常播放，但由大华平台转推来的华平平台视频流不能播放。

针对华平的问题，测试后排除了丢包的原因，通过导出 ZLM 的调试数据，获取了video 文件，直接推 .video 文件到 nginx-rtmp 服务器，其分发的流地址也能正常播放

**Comment by xia-chu** [comment]
你分享下dump出的rtp文件 我测试下试试

**Comment by songbai1997** [comment]
> 对接华平平台似乎要发个Iframe请求

您好，目前我们是使用开源库（https://github.com/debugger999/gb28181ToH264 )，充当 sip 服务器，负责请求开启和关闭摄像头。使用本库（ZLM）充当的流媒体服务器。由于我们不是做这一块的，所以不太懂您的意思，您能具体说一下吗，万分感谢。 @tsingeye

**Comment by xia-chu** [comment]
丢包比较严重啊 @songbai1997

**Comment by xia-chu** [comment]
你这个流有问题 时间戳一直为0：
<img width="1259" alt="图片" src="https://user-images.githubusercontent.com/11495632/137583353-b5d1c322-0c2b-4a9d-854f-f44888d2bb92.png">

**Comment by xia-chu** [comment]
级联平台代码由问题吧？

**Comment by songbai1997** [comment]
1. 据我们所知，大华平台在转推华平平台视频流时没有进行额外处理。
2. 上面代码中输出pts和dts的地方是在调用_on_decode之前，ps流还没有被解析？解析后PES包里应该有pts和dts的信息吧？
3. ZLM平台导出的.video文件能够播放是否说明ps流没有问题？

**Comment by xia-chu** [comment]
这个是日志是解析得到ps中的时间戳，h264能播放没用啊，时间戳一直为0，那么就没法播放。这是最基本的要求
