### ISSUE TITLE
[BUG] webrtc播放rtsp流问题

### ISSUE THREAD

**Issue by zhangzhiming1017** [ZLMediaKit/ZLMediaKit#1148]
**bug现象**
  使用/index/api/addStreamProxy配置rtsp地址进行拉流
  使用项目自带的www/webrtc/index.html播放rtsp视频流。点击“开始”按钮,视频可以正常播放
问题：
1.如果直接关闭页面，下一次再使用该页面播放该rtsp视频流，无法播放。如果mediasever重启后，回复正常。
2.如果点击“停止”按钮,再关闭页面，下一次再使用该页面播放该rtsp视频流，正常播放

![QQ截图20211008152535](https://user-images.githubusercontent.com/52143189/136535920-8da56abf-329b-4913-8e78-617243290b00.png)
mediaserver打印的正常log
![QQ截图20211008152551](https://user-images.githubusercontent.com/52143189/136535958-d70e58d2-7ecb-4899-a779-1da7d293c9f1.png)
mediaserver打印的有问题log

临时性解决方案：
观察index.html源码，其中有个变量player在按“停止”后，会走player.close()逻辑。而直接关闭网页则不会走该逻辑。
通过修改index.html源码获取了关闭网页的事件函数，将player.close()写在里面。重新bug现象问题一恢复正常。

一般情况下，按照上述方式解决问题不会出现问题。极端情况下，如果浏览器发生奔溃而无法触发关闭页面的事件函数，则无法走到play.close()逻辑，从而出现问题，需要重启服务器才能解决。

**bug产生时的使用场景**
使用的是webrtc模块

bug是否可以复现，怎么复现
可以复现，复现方式参考bug现象

**zlm代码git commit hash值**
8d85e6cee063b0f4a63d6886dd8c9353c4ebab75

**操作系统环境**
- windows10 64位
- intel i7 9700

**Comment by xia-chu** [comment]
有可能你关闭页面了 zlm没收到dtls close或rtcp bye消息，导致zlm不知道播放器关闭了。如果下次再播放，且使用同一个udp端口，那么就可能会导致该问题。
