### ISSUE TITLE
[技术咨询] addFFmpegSource fork的进程CPU利用率无法超过 100%

### ISSUE THREAD

**Issue by Jin2022** [ZLMediaKit/ZLMediaKit#1149]
**咨询的功能模块**
- addFFmpegSource，通过 fork FFmpeg 进程的方式拉流代理

**咨询的具体内容和问题**
- addFFmpegSource转码处理2k h265 4m码流为h264时cpu使用无法超过100%，导致处理速度过慢帧率降低到7帧，如果手动用相同命令进行转码推流top命令中cpu使用率可以达到500%+，请问大佬是哪里有限制吗

**Comment by xia-chu** [comment]
我知道原因了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: taojishou ***@***.***&gt;
发送时间: 2021年10月12日 17:54
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] addFFmpegSource fork的进程CPU利用率无法超过 100% (#1149)





 
我也遇到了这个问题啦

**Comment by Jin2022** [comment]
> > 多谢解惑，我暂时注释掉了 set_cpu 后可以正常运行，但理论上取消设置后应该会影响性能吧
> 
> 代码位置是？

ZLMediaKit/ZLToolKit/src/Thread/TaskExecutor.cpp  203行

**Comment by xia-chu** [comment]
> 多谢解惑，我暂时注释掉了set_cpu后可以正常运行，但理论上取消设置后应该会影响性能吧

设置cpu亲和性 理论上可以减少线程切换次数，但是zlm中阻塞本来就很少，性能提升估计不大
