### ISSUE TITLE
[技术咨询]Webrtc推流时是否会对音频和视频单独区分

### ISSUE THREAD

**Issue by poorboy1991** [ZLMediaKit/ZLMediaKit#1153]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
WebRTC是否对纯音频推流与音视频推流的判断逻辑是否不一样，
表现：
iOS设备在推纯音频流成功后，另一端播放请求SDP，ZL返回明显延迟5秒。
iOS设备在推音视频流时，另一端播放请求SDP，ZL正常返回。

**Comment by xia-chu** [comment]
我不知道你在讲啥。。。，这就是你不按照issue模板提问的后果

**Comment by xia-chu** [comment]
你看zlm显示媒体注册的时间分别延时多久

**Comment by poorboy1991** [comment]
媒体注册时间没问题的，5s就是拿注册时间和play的response回来的时间对比的

**Comment by poorboy1991** [comment]
是的 所以这个也是我们很好奇的地方，但是我们换音视频一起push，拉流时间就正常了

**Comment by poorboy1991** [comment]
> > 拿注册时间和play的response回来的时间对比的
> 
> 如果注册都很迅速，那么应该也能很快起播成功的。 “5s就是拿注册时间和play的response回来的时间对比的”,你是说调用/index/api/webrtc接口响应的时间吗？

是的 所以这个也是我们很纳闷的地方，但是我们换音视频一起push，拉流时间就正常了

**Comment by poorboy1991** [comment]
不是，注册是没问题的，推流(纯音频)也很快，只是在调用play接口的时候返回需要5s

**Comment by poorboy1991** [comment]
> “只是在调用play接口的时候返回需要5s” 那是不可能的

2021-10-13 10:09:15.941 D MediaServer[20635-event poller 1] WebApi.cpp:228 http api debug | 
# request:
POST /index/api/webrtc?vhost=__defaultVhost__&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&app=live&stream=2021001-0801-0008123bac&type=push
# header:
Accept-Encoding : gzip
Content-Length : 3536
Content-Type : text/plain;charset=UTF-8
Host : 172.20.52.103
User-Agent : Go-http-client/1.1
# content:
v=0
o=- 2910712577135452856 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS stream
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:0pr4
a=ice-pwd:lpyQ9mKuseRfPT5vD612Cgw0
a=ice-options:trickle renomination
a=fingerprint:sha-256 44:3D:0A:3A:3F:90:83:25:52:90:7D:40:C6:FA:A1:8B:C9:76:B7:9A:EE:6D:F3:FC:9C:D0:BB:9B:F2:08:FF:61
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:stream audio0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1742475464 cname:FABSEZDlvVK+cRke
a=ssrc:1742475464 msid:stream audio0
a=ssrc:1742475464 mslabel:stream
a=ssrc:1742475464 label:audio0
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:0pr4
a=ice-pwd:lpyQ9mKuseRfPT5vD612Cgw0
a=ice-options:trickle renomination
a=fingerprint:sha-256 44:3D:0A:3A:3F:90:83:25:52:90:7D:40:C6:FA:A1:8B:C9:76:B7:9A:EE:6D:F3:FC:9C:D0:BB:9B:F2:08:FF:61
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:stream video0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 2055649859 1623981336
a=ssrc:2055649859 cname:FABSEZDlvVK+cRke
a=ssrc:2055649859 msid:stream video0
a=ssrc:2055649859 mslabel:stream
a=ssrc:2055649859 label:video0
a=ssrc:1623981336 cname:FABSEZDlvVK+cRke
a=ssrc:1623981336 msid:stream video0
a=ssrc:1623981336 mslabel:stream
a=ssrc:1623981336 label:video0

# response:
{
   "code" : 0,
   "sdp" : "v=0\r\no=- 2910712577135452856 2 IN IP4 172.20.52.103\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS stream\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 172.20.52.103\r\na=rtcp:8000 IN IP4 172.20.52.103\r\na=ice-ufrag:140202496544048\r\na=ice-pwd:BK7y912lYnkJt2dKBgOAYm43\r\na=ice-options:trickle\r\na=fingerprint:sha-256 E7:27:64:3A:BE:90:C0:3B:C2:59:C4:FA:64:5A:29:26:57:B4:AE:EC:B1:BF:4F:51:EE:D8:4A:AA:15:5D:56:A4\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=candidate:udpcandidate 1 udp 100 172.20.52.103 8000 typ host\r\nm=video 8000 UDP/TLS/RTP/SAVPF 96 97\r\nc=IN IP4 172.20.52.103\r\na=rtcp:8000 IN IP4 172.20.52.103\r\na=ice-ufrag:140202496544048\r\na=ice-pwd:BK7y912lYnkJt2dKBgOAYm43\r\na=ice-options:trickle\r\na=fingerprint:sha-256 E7:27:64:3A:BE:90:C0:3B:C2:59:C4:FA:64:5A:29:26:57:B4:AE:EC:B1:BF:4F:51:EE:D8:4A:AA:15:5D:56:A4\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=candidate:udpcandidate 1 udp 100 172.20.52.103 8000 typ host\r\n",
   "type" : "answer"
}


2021-10-13 10:09:15.953 I MediaServer[20635-event poller 1] WebRtcSession.cpp:17 WebRtcSession | 140202498168264(10.9.113.31:43471) 
2021-10-13 10:09:15.953 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:75 OnIceServerSelectedTuple | 
2021-10-13 10:09:15.953 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:83 OnIceServerCompleted | 
2021-10-13 10:09:15.953 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:116 OnDtlsTransportConnecting | 
2021-10-13 10:09:15.961 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:105 OnDtlsTransportConnected | 
2021-10-13 10:09:16.871 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:792 createRtpChannel | create rtp receiver of ssrc:1742475464, rid:, codec:opus
2021-10-13 10:09:17.199 T MediaServer[20635-event poller 1] HttpSession.cpp:25 HttpSession | 140202497524136(10.9.114.24:65200) 
2021-10-13 10:09:17.202 T MediaServer[20635-event poller 1] HttpSession.cpp:124 onError | 140202497524136(10.9.114.24:65200) end of file
2021-10-13 10:09:17.202 T MediaServer[20635-event poller 1] HttpSession.cpp:31 ~HttpSession | 140202497524136(10.9.114.24:65200) 
2021-10-13 10:09:17.206 T MediaServer[20635-event poller 1] HttpSession.cpp:25 HttpSession | 140202496602760(10.9.114.24:65201) 
2021-10-13 10:09:18.923 W MediaServer[20635-event poller 1] MediaSink.cpp:56 operator() | cached frame of unready track(opus) is too much, now cleared
2021-10-13 10:09:20.947 W MediaServer[20635-event poller 1] MediaSink.cpp:56 operator() | cached frame of unready track(opus) is too much, now cleared
2021-10-13 10:09:22.954 W MediaServer[20635-event poller 1] MediaSink.cpp:56 operator() | cached frame of unready track(opus) is too much, now cleared
2021-10-13 10:09:24.978 W MediaServer[20635-event poller 1] MediaSink.cpp:56 operator() | cached frame of unready track(opus) is too much, now cleared
2021-10-13 10:09:25.962 D MediaServer[20635-event poller 1] MediaSink.cpp:141 emitAllTrackReady | all track ready use 10001ms
2021-10-13 10:09:25.962 W MediaServer[20635-event poller 1] MediaSink.cpp:148 emitAllTrackReady | track not ready for a long time, ignored: H264
2021-10-13 10:09:25.962 I MediaServer[20635-event poller 1] MultiMediaSourceMuxer.cpp:297 onAllTrackReady | stream: rtc://172.20.52.103/live/2021001-0801-0008123bac?vhost=__defaultVhost__&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&app=live&stream=2021001-0801-0008123bac&type=push , codec info: opus[48000/2/16] 
2021-10-13 10:09:25.963 I MediaServer[20635-event poller 1] MediaSource.cpp:414 emitEvent | 媒体注册:rtmp __defaultVhost__ live 2021001-0801-0008123bac
2021-10-13 10:09:25.963 I MediaServer[20635-event poller 1] MediaSource.cpp:414 emitEvent | 媒体注册:rtsp __defaultVhost__ live 2021001-0801-0008123bac
2021-10-13 10:09:25.963 I MediaServer[20635-event poller 1] MediaSource.cpp:414 emitEvent | 媒体注册:ts __defaultVhost__ live 2021001-0801-0008123bac
2021-10-13 10:09:25.965 D MediaServer[20635-event poller 1] MediaSource.cpp:366 operator() | 收到媒体注册事件,回复播放器:rtsp/__defaultVhost__/live/2021001-0801-0008123bac
2021-10-13 10:09:25.965 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:340 WebRtcTransportImp | 0x7f83700c0c80
2021-10-13 10:09:25.968 D MediaServer[20635-event poller 1] WebApi.cpp:228 http api debug | 
# request:
POST /index/api/webrtc?app=live&stream=2021001-0801-0008123bac&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Content-Length : 4650
Content-Type : text/plain;charset=UTF-8
Host : 172.20.52.103
Origin : https://172.20.52.103
Referer : https://172.20.52.103/webrtc/
sec-ch-ua : "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "macOS"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-origin
User-Agent : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36
# content:
v=0
o=- 459943308462543205 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:In5W
a=ice-pwd:iHrjgOBRtlZc8lqDW6wuEPPe
a=ice-options:trickle
a=fingerprint:sha-256 EA:10:E4:8F:43:0E:E8:6B:9A:E3:6D:44:46:55:EC:1D:32:21:6A:F4:4E:57:C8:D6:84:2F:85:CB:A6:5D:B9:76
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 122 102 121 127 120 125 107 108 109 35 36 124 119 123 37
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:In5W
a=ice-pwd:iHrjgOBRtlZc8lqDW6wuEPPe
a=ice-options:trickle
a=fingerprint:sha-256 EA:10:E4:8F:43:0E:E8:6B:9A:E3:6D:44:46:55:EC:1D:32:21:6A:F4:4E:57:C8:D6:84:2F:85:CB:A6:5D:B9:76
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:122 VP9/90000
a=rtcp-fb:122 goog-remb
a=rtcp-fb:122 transport-cc
a=rtcp-fb:122 ccm fir
a=rtcp-fb:122 nack
a=rtcp-fb:122 nack pli
a=fmtp:122 profile-id=1
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-
# response:
{
   "code" : 0,
   "sdp" : "v=0\r\no=- 459943308462543205 2 IN IP4 172.20.52.103\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 172.20.52.103\r\na=rtcp:8000 IN IP4 172.20.52.103\r\na=ice-ufrag:140202497281152\r\na=ice-pwd:kJt2dKBgOAYm43OwjA2crdPr\r\na=ice-options:trickle\r\na=fingerprint:sha-256 E7:27:64:3A:BE:90:C0:3B:C2:59:C4:FA:64:5A:29:26:57:B4:AE:EC:B1:BF:4F:51:EE:D8:4A:AA:15:5D:56:A4\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:11733 cname:zlmediakit-rtp\r\na=ssrc:11733 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:11733 mslabel:zlmediakit-mslabel\r\na=ssrc:11733 label:zlmediakit-label\r\na=candidate:udpcandidate 1 udp 100 172.20.52.103 8000 typ host\r\nm=video 8000 UDP/TLS/RTP/SAVPF 102 121\r\nc=IN IP4 172.20.52.103\r\na=rtcp:8000 IN IP4 172.20.52.103\r\na=ice-ufrag:140202497281152\r\na=ice-pwd:kJt2dKBgOAYm43OwjA2crdPr\r\na=ice-options:trickle\r\na=fingerprint:sha-256 E7:27:64:3A:BE:90:C0:3B:C2:59:C4:FA:64:5A:29:26:57:B4:AE:EC:B1:BF:4F:51:EE:D8:4A:AA:15:5D:56:A4\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=102\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:0 cname:zlmediakit-rtp\r\na=ssrc:0 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:0 mslabel:zlmediakit-mslabel\r\na=ssrc:0 label:zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\na=ssrc-group:FID 0 2\r\na=candidate:udpcandidate 1 udp 100 172.20.52.103 8000 typ host\r\n",
   "type" : "answer"
}


2021-10-13 10:09:25.978 I MediaServer[20635-event poller 1] WebRtcSession.cpp:17 WebRtcSession | 140202497560600(10.9.114.24:58792) 
2021-10-13 10:09:25.978 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:75 OnIceServerSelectedTuple | 
2021-10-13 10:09:25.978 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:83 OnIceServerCompleted | 
2021-10-13 10:09:25.978 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:116 OnDtlsTransportConnecting | 
2021-10-13 10:09:25.985 I MediaServer[20635-event poller 1] WebRtcTransport.cpp:105 OnDtlsTransportConnected | 
2021-10-13 10:09:26.026 I MediaServer[20635-event poller 1] MediaSource.cpp:414 emitEvent | 媒体注册:fmp4 __defaultVhost__ live 2021001-0801-0008123bac



![image](https://user-images.githubusercontent.com/5009620/137054966-178b44f0-59c0-4cd1-a0c3-e8a2a10c343b.png)
![image](https://user-images.githubusercontent.com/5009620/137055017-7a2aa95b-9012-4b26-950a-a2491810007d.png)

10:09:15 推流成功，16s就开始点击播放按钮，等待了将近10s 响应成功

**Comment by poorboy1991** [comment]
> ios推流时，媒体注册很慢？

奥从表现上看，真的是ios端推纯音频流注册很慢

**Comment by xia-chu** [comment]
> > ios推流时，媒体注册很慢？
> 
> 奥从表现上看，真的是ios端推纯音频流注册很慢
推的默认是711的 应该很快的，有zlm日志吗
