### ISSUE TITLE
[BUG] 对于AAC音频包，如何从RTP packet包提取正确的数据供FFMPeg解码

### ISSUE THREAD

**Issue by pengcx123** [ZLMediaKit/ZLMediaKit#1159]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
音频码流处理
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
目前WebRTC不支持AAC编码，因此将RTSP流转换为WebRTC时，对于AAC音频包，需使用FFMPeg进行转码，在调试转码逻辑时发现如下问题：
1）RTP包长度为1200多，实际AAC包一般为接近300。
想请问如何从RTP包中正确提取AAC数据包供FFMpeg转码
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个那是什么bug啊老兄 你这不是在技术咨询吗？
