### ISSUE TITLE
ABR (Adaptive bitrate encoding)

### ISSUE THREAD

**Issue by xoraingroup** [ZLMediaKit/ZLMediaKit#1164]
Is there any configuration or api that can be used to instruct Media Server to generate multiple hls ts fragments for different resolutions. I know it will require encoding but as per FFMPEG related documentation in api, it requires src and dst url which is not the use case for us. Any help would be appreciated.

What we want 

Stream Ingest -> Media Server -> generates multiple hls ts fragments for different resolution.

**Comment by xia-chu** [comment]
You can pull stream from ZLMediaKit and transcoding to  different resolutions   and then push it to ZLMediaKit by `addFFmpegSource` api.

**Comment by xoraingroup** [comment]
That means Stream Ingest -> ZLMediaKit <- Pull Stream -> encode to ABR -> addFFmpegSource in ZLMediaKit multiple times for different resolutions?

**Comment by xia-chu** [comment]
yes!

**Comment by xoraingroup** [comment]
Ok thank you. :+1:
