### ISSUE TITLE
[技术咨询]录制mp4现在是分段的 如何配置不分段？是直接配置文件时间改大一些？

### ISSUE THREAD

**Issue by taojishou** [ZLMediaKit/ZLMediaKit#1168]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
改大到很大就行
