### ISSUE TITLE
[技术咨询]文档中有关rtpServer的接口无法访问，从getApiList也无法获取

### ISSUE THREAD

**Issue by makexiao113** [ZLMediaKit/ZLMediaKit#1172]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
  有关rtpserver的api接口
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
无法访问文档中提到的listRtpServer、openRtpServer、closeRtpServer接口，是不是有什么配置会打开相关接口，或者是接口已经转移？我在wiki中并没有找到，还请各位大佬指教一下
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by mikite** [comment]
Android上如何打开ENABLE_RTPPROXY呢？我尝试在Cmakelist设置ENABLE_RTPPROXY true不起作用。
WebApi.cpp:899:24: error: use of undeclared identifier 'RtpSelector'

**Comment by xia-chu** [comment]
> Android上如何打开ENABLE_RTPPROXY呢？我尝试在Cmakelist设置ENABLE_RTPPROXY true不起作用。 WebApi.cpp:899:24: error: use of undeclared identifier 'RtpSelector'

add_definitions(-DENABLE_RTPPROXY)
