### ISSUE TITLE
[技术咨询]请问通过addStreamProxy接口添加了一个rtsp的代理，并开启了enable_hls怎么获取转流后输出的可浏览器播放的flv或hls地址呢？

### ISSUE THREAD

**Issue by oblank** [ZLMediaKit/ZLMediaKit#1175]
**咨询的功能模块**
- 转流，将rtsp转为浏览器支持的格式

**咨询的具体内容和问题**
- 请问通过addStreamProxy接口添加了一个rtsp的代理，并开启了enable_hls怎么获取转流后输出的可浏览器播放的flv或hls地址呢？

**Comment by xia-chu** [comment]
wiki中的播放url规则篇你可以看一下
