### ISSUE TITLE
addStreamProxy拉流接口有时会自动将H264编码的源流转码成H265编码格式，如何取消自动转码？[技术咨询]

### ISSUE THREAD

**Issue by BigPotato1** [ZLMediaKit/ZLMediaKit#1176]
**咨询的功能模块**
- addStreamProxy拉流接口

**咨询的具体内容和问题**
- addStreamProxy拉流接口有时会自动将H264编码的源流转码成H265编码格式，如何取消自动转码呢？

![1642bbcb132ed542373ad32e79fdd2f](https://user-images.githubusercontent.com/45842244/138024713-8f96c44f-9db4-407b-9731-dc09222e631a.png)

**Comment by xia-chu** [comment]
老哥 你的摄像头不认url中的h264参数呢

**Comment by BigPotato1** [comment]
> 老哥 你的摄像头不认url中的h264参数呢

您意思是我这个URL“rtsp://user:123qweasd@192.168.53.210:554/h264/ch1/sub/av_stream”实际从摄像头取出的视频流就是H265编码的吗？

**Comment by xia-chu** [comment]
对啊
