### ISSUE TITLE
[功能请求] 测试 RTMP 推流与 WebRTC 播放时，WebRTC 播放出现花屏现象

### ISSUE THREAD

**Issue by sunshally** [ZLMediaKit/ZLMediaKit#1186]
**RTMP 推流与 WebRTC 播放存在花屏现象**

**测试环境**
推流端 OBS，播放端 ZLMediaServer 自带的 Web 网页

**存在问题**
WebRTC 播放存在花屏

**Comment by xia-chu** [comment]
麻烦你再让这个流上线下 这几天有事耽搁了
