### ISSUE TITLE
视频上云录存储的几个问题

### ISSUE THREAD

**Issue by zh19900725** [ZLMediaKit/ZLMediaKit#1187]
**描述该功能的用处，可以提供相关资料描述该功能**
关于历史录像，我这里利用on_record_mp4做了录像上云存储（推到云端cos里存了）
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
这里有两个问题：
1.ZLMediaKit没有明确机器的录像文件是存多久，也没有看到设置
2.我的hook服务写在另一个网络下，录像上云后我想要同步删除机器上的文件目前好像没有这个能力？
**描述你期望实现该功能的方式和最终效果**
能给提供录像文件清理接口

**Comment by GeTOUO** [comment]
@zh19900725 你好，请问你存到云存储之后，点播的时候怎么访问的呢？

**Comment by FCsir** [comment]
@zh19900725 你好，录制mp4视频会自动删除吗，有没有配置设置保留之前的录像设置
