### ISSUE TITLE
[技术咨询]更新最新代码后编译会报错

### ISSUE THREAD

**Issue by superheipi** [ZLMediaKit/ZLMediaKit#1190]
升级最新代码后，编译会报
./media/Common/config.h:131:29: error: ‘Instance’ is not a member of ‘mINI’
     static type arg = mINI::Instance()[key];
的错误，请问是什么情况。

**Comment by xia-chu** [comment]
请把你本地的zlm的源码全部删除，然后重新下载编译zlm。
