### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by FreshManQin** [ZLMediaKit/ZLMediaKit#1191]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- docker作为服务，接口问题

**咨询的具体内容和问题**
-   视频编码格式 : h265
-   目标： 转成网页hls能播放
-  调用/index/api/addStreamProxy 接口时，传入了参数enable_hls = true,日志如下图：
![image](https://user-images.githubusercontent.com/16437244/139044859-298f690c-50de-4ae3-b2b2-04846ec7b941.png)
![image](https://user-images.githubusercontent.com/16437244/139044707-7837d26d-8a0a-4052-a775-7956512a332a.png)
这种是否正常 FFmpeg命令是否应该是hls 不是FLV？如果否，我的思路有问题？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
addFFmpegSource就能满足你的需求 这个接口就是zlm启动管理FFmpeg进程
