### ISSUE TITLE
GB中的PS视频码流依据真实视频判断编码类型

### ISSUE THREAD

**Issue by programcj** [ZLMediaKit/ZLMediaKit#1192]
**描述该功能的用处，可以提供相关资料描述该功能**
有的摄像头发送RTP的PS码流时,  PS头是H264  PS中的视频内容为H265

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
现实问题中的缺陷吧

**描述你期望实现该功能的方式和最终效果**
mpeg-ps-dec.c 中的函数 ps_demuxer_onpes
```
#if 1//可以在这里判断视频流格式是否与codecid一致
    if (codecid == PSI_STREAM_H264 || codecid == PSI_STREAM_H265) {
        printf("%02X---->> ", codecid);
        for (int i = 0; i < 10 && i < bytes; i++) {
            printf("%02X ", ((uint8_t *)data)[i]);
        }
        printf("\n");

        if (ps->_video_code_id == 0)
            ps->_video_code_id = H264 or H265; //固定编码格式,需要寻找到NALU头的Type内容来判断
        return ps->onpacket(ps->param, stream, ps->_video_code_id, flags, pts, dts, data, bytes);
    }  
#endif
```

**Comment by xia-chu** [comment]
虽然可以按照nal类型判断h264还是h265, 但是这种bug真的很烦人， 如果你是做to b项目，你可能不得不兼容下，单作为一个开源项目，为什么要去兼容其他人的bug? 如果这种兼容代价是比较小的，那么偶尔可以这么为之，但是这个bug，要兼容会一定的代价，首先，我们要穷举所有的H264 nal类型，如果不是，再判断是否为H265，但是这个只是这种bug的一种可能而已, 它也可以声明为H265，但其实是H264，到时你又怎么处理？这种bug兼容要加一大坨代码，破坏整个代码流程的简洁性，我觉得作为一个开源项目，没必要为了兼容一个bug的特例情况而且做这么大的改动。

**Comment by xia-chu** [comment]
另外兼容这个bug，还可能引入副作用，就是流注册的时间会延长，因为在判断h264或h265时，必定会引入一定的判断延时。

**Comment by programcj** [comment]
也是,主要还是摄像头不按标准发送
