### ISSUE TITLE
是否可以在getMediaList中返回addFFmpegSource以及addStreamProxy中返回的key

### ISSUE THREAD

**Issue by howielin** [ZLMediaKit/ZLMediaKit#1194]
**描述该功能的用处，可以提供相关资料描述该功能**
如果key丢失，在getMediaList中会有很多删不掉的信息。
或者增加一个clear也不错。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
无
**描述你期望实现该功能的方式和最终效果**
无

**Comment by xia-chu** [comment]
addFFmpegSource和addStreamProxy添加的流 都可以用close_stream[s] 接口删除，你说的丢失key的问题，这是你自己的bug啊
