### ISSUE TITLE
arm64芯片-debian系统下cpu占用率的疑惑

### ISSUE THREAD

**Issue by seamende** [ZLMediaKit/ZLMediaKit#1195]
在arm64芯片-debian系统下，启动ZLM后，用ps 命令找出MediaServer的进程号，再用top -p 进程号查看资源占用情况，发现cpu占用为4%[command这一列显示为main thread],此时没有视频流输入和输出，只是空跑。请问这种情况正常吗？

**Comment by xia-chu** [comment]
没啥问题

**Comment by xia-chu** [comment]
zlm空载时，只有一个线程稍微繁忙点，就是1秒执行1000次的获取系统时间戳函数，这个负载其实很低的，从你的perf top看，也不是这个引起的
