### ISSUE TITLE
[BUG] 6.0版本在ubuntu 16.04无法编译

### ISSUE THREAD

**Issue by sudolee** [ZLMediaKit/ZLMediaKit#1196]
**bug现象**
- 通过build_for_linux.sh编译报错。

- bug产生时，打印的上下文日志：
 ~/ZLMediaKit$ git status
On branch 6.0
Your branch is up-to-date with 'origin/6.0'.
nothing to commit, working directory clean
~/ZLMediaKit$ ./build_for_linux.sh
fatal: destination path 'ZLMediaKit' already exists and is not an empty directory.
fatal: reference is not a tree: ec171caa4b28db0f6ea47bca2c0c9530f345698a
Unable to checkout 'ec171caa4b28db0f6ea47bca2c0c9530f345698a' in submodule path '3rdpart/media-server'

**bug是否可以复现，怎么复现**
- 必现
- git clone https://gitee.com/xia-chu/ZLMediaKit
- git checkout -b 6.0 origin/6.0
- sh ./build_for_linux.sh

**zlm代码git commit hash值**
- 7375889b2e82e921b0273c382cacd1b36db45af6

**操作系统环境**
- ubuntu 16.04，64位
- 什么cpu类型：Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz

**Comment by xia-chu** [comment]
你只下载并仔细build_for_linux.sh文件就行，这个文件本来给ci(持续集成)用的，它会再加载zlm代码的

**Comment by wasphin** [comment]
这个估计是换源导致的, 默认 clone 的是 master 分支, master 分支刚换了 media-server 源, 切换到 6.0 分支的时候需要再同步子模块的地址, 执行:
```
git submodule sync
```
