### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by mikite** [ZLMediaKit/ZLMediaKit#1202]
**咨询的功能模块**
1.Android使用ZLMediaKit
期望通过android设备实现同时承担服务器及推流客户端的功能。貌似issue这里边没看到有这么用的，这个做法是否可行？
目前已经尝试修改了Cmakelist，支持了官方demo里未开放的一些HTTP-API。

**咨询的具体内容和问题**
2.打开openRtpServer正常返回端口，调用startRecord和startSendRtp这里返回找不到MediaSource.
接口参数均按照要求提供，是因为调用顺序出了问题还是其他的原因呢？

接口参数如下图：
 
![23424](https://user-images.githubusercontent.com/5226661/140035471-93ec92a1-d1b1-46a9-af15-b75270ac46d0.png)

**Comment by xia-chu** [comment]
你先推个流给zlm就能开始录制了
