### ISSUE TITLE
addFFmpegSources时，FFmpeg使用多核的问题[功能请求]

### ISSUE THREAD

**Issue by alexjeo** [ZLMediaKit/ZLMediaKit#1203]
**描述该功能的用处，可以提供相关资料描述该功能**
在Linux下，通过addFFmpegSources调用FFmpeg时，FFmpeg只使用一核CPU。
多次调用addFFmpegSources后（不用源地址），一个核心无法满足时，将启动一个新的核心。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

无法均分与多个核心上，导致视频会出现卡顿的情况出现。

**描述你期望实现该功能的方式和最终效果**

修改ZLToolKit/blob/master/src/Thread/TaskExecutor.cpp
第190行，将setThreadAffinity(i % cpus); 改为 setThreadAffinity( -1 );
在linux下，再次测试，FFmpeg平均分布于CPU的多个核心。

麻烦请确认这么修改是否合理，是否会影响到其他的功能点或是平台的性能！

**Comment by xia-chu** [comment]
改成setThreadAffinity( -1 )，相当于cpu亲和性设置无效了，相当于没调用setThreadAffinity函数。
其实我之前设想的是setThreadAffinity( -1 )时 取消cpu亲和性设置，但是无效。

**Comment by xia-chu** [comment]
我的想法是poller线程还是cpu亲和的，但是FFmpeg等fork出的进程不设置亲和性
<img width="1230" alt="图片" src="https://user-images.githubusercontent.com/11495632/140678554-c9ddfb2e-16f7-4391-8e59-58230653fbfb.png">

**Comment by alexjeo** [comment]
我看到这个地方了，这么设置后依然的不起作用，一个核心满了后，然后再过渡到另一个核心上。
后来将TaskExecutor这里去掉，就OK了。
我在一个20核上的CPU测试，fork 9个FFmpeg所有的核心都是100%了，但是我直接运行FFmpeg，反而不会100%。
