### ISSUE TITLE
4K高清摄像头接入问题

### ISSUE THREAD

**Issue by seamende** [ZLMediaKit/ZLMediaKit#1204]
通过wvp的国标协议接入了4K分辨率的摄像头，码率约12Mb/s,刚开始播放的时候能显示出图像，但一两秒后，图像卡住不动了，半分钟左右，流就断了。请教一下：ZML是否支持4K摄像头的正常接入？

**Comment by xia-chu** [comment]
你都出画面了 你说支持不？

**Comment by xia-chu** [comment]
提issue 需要安装模板提 你只说现象 不提供日志抓包等资料 怎么分析问题呢？

**Comment by seamende** [comment]
当时看到这种情况，以为转发出现了问题，后面用VLC测试，播放是正常的，应该是网页播放器解不过来，感谢大佬回复
