### ISSUE TITLE
字幕流[技术咨询]

### ISSUE THREAD

**Issue by kqbi** [ZLMediaKit/ZLMediaKit#1208]
**咨询的功能模块**
- 字幕流打包解析

**咨询的具体内容和问题**
- 大佬有没有支持字幕流的打算

**Comment by xia-chu** [comment]
很多协议不支持的 字幕源自什么协议 去 什么协议？

**Comment by kqbi** [comment]
就rtsp rtmp

**Comment by xia-chu** [comment]
rtsp、rtmp 应该不支持字幕的，而且播放器应该普遍不支持字幕

**Comment by xia-chu** [comment]
字幕一般一些高级的容器才能支持，rtsp一般是es流，基本不可能支持字幕，rtmp是flv，我猜也不支持字幕

**Comment by kqbi** [comment]
好吧，那rtsp协议的sdp里的text类型是干啥的

**Comment by xia-chu** [comment]
> 好吧，那rtsp协议的sdp里的text类型是干啥的

忘了答复了，rtsp sdp里面的text我目前还没遇到过， 我也不知道，感兴趣的可以爬下FFmpeg的代码。
issue我先关闭了。

**Comment by mtdxc** [comment]
rtsp的text sdp好像就是用来加字幕的： https://blog.csdn.net/shizheng163/article/details/83278849 😄
