### ISSUE TITLE
get请求不存在的HTTP API时，服务器会崩溃

### ISSUE THREAD

**Issue by xiejx** [ZLMediaKit/ZLMediaKit#1209]
**产生情景：**  
当我使用get方式请求不存在的url时，服务器会崩溃退出。  
例如我使用get方式请求`/index/api/getMediaList1`路径（正确路径为`/index/api/getMediaList`）时，服务器就崩溃退出了。

**部署方式：**  
使用的是docker容器化部署。镜像版本是：`panjjo/zlmediakit:1.2.6`。

**Comment by xia-chu** [comment]
并没有：
![图片](https://user-images.githubusercontent.com/11495632/141072580-995b61d6-fdc0-48e4-aa9d-ce121bfb0180.png)

**Comment by xiejx** [comment]
感谢你的回复，刚才又试了一下，使用get方式请求不存在的url时，浏览器和curl命令是正常的。
**只有使用postman请求时会崩溃**。

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/141076749-b897f48e-a551-4272-8844-8a2ea8a623cf.png)
