### ISSUE TITLE
[功能请求] WebRTC 相关服务的 C API (SDK)

### ISSUE THREAD

**Issue by Roycent** [ZLMediaKit/ZLMediaKit#1210]
**描述该功能的用处，可以提供相关资料描述该功能**

支持使用API调用ZLMediaKit，提供配置后调用SDK创建WebRTC服务器

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

非缺陷

**描述你期望实现该功能的方式和最终效果**

现有的C API似乎不包括创建RTC服务器的接口（也有可能是我没找到），期望可以像创建rtsp服务器一样创建WebRTC服务，将rtmp流转换为webrtc

**Comment by xia-chu** [comment]
是的 c api目前只包装了 src目录下的代码，还没包装webrtc的

**Comment by xia-chu** [comment]
刚合并c sdk webrtc的pr了 我测试功能ok了 感谢 @Dw9
