### ISSUE TITLE
[技术咨询]docker zlm webrtc配置

### ISSUE THREAD

**Issue by JacksonTu** [ZLMediaKit/ZLMediaKit#1211]
**咨询的功能模块**
- docker zlm webrtc配置

**咨询的具体内容和问题**
docker配置
zlmtest:
        image: panjjo/zlmediakit:latest
        container_name: zlmtest
        restart: always
        ports:
            - "49080:80"
            - "49443:443"
            - "49035:1935"
            - "49350:19350"
            - "49554:554"
            - "49554:554/udp"
            - "49332:332"
            - "49332:332/udp"
            - "10010:10000"
            - "10010:10010/udp"
            - "30000-30500:30000-30500"
            - "30000-30500:30000-30500/udp"
            - "8000:8000"
            - "8000:8000/udp"
        volumes:
            - /home/data/zlmtest/log:/zlmediakit/log
            - /home/data/zlmtest/www:/zlmediakit/www
            - /home/data/zlmtest/ffmpeg:/zlmediakit/ffmpeg
            - /home/data/zlmtest/conf/config.ini:/zlmediakit/config.ini 
            - /home/data/zlmtest/conf/default.pem:/zlmediakit/default.pem
 
wvp连接zlm，从wvp系统调用开始点播接口，得到如下播放路径：
{
  "code": 0,
  "msg": "success",
  "data": {
    "app": "rtp",
    "streamId": "34020000001180000001_34020000001310000016",
    "deviceID": "34020000001180000001",
    "channelId": "34020000001310000016",
    "flv": "http://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.flv",
    "https_flv": "https://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.flv",
    "ws_flv": "ws://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.flv",
    "wss_flv": "wss://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.flv",
    "fmp4": "http://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.live.mp4",
    "https_fmp4": "https://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.live.mp4",
    "ws_fmp4": "ws://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.live.mp4",
    "wss_fmp4": "wss://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.live.mp4",
    "hls": "http://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016/hls.m3u8",
    "https_hls": "https://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016/hls.m3u8",
    "ws_hls": "ws://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016/hls.m3u8",
    "wss_hls": "wss://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016/hls.m3u8",
    "ts": "http://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.live.ts",
    "https_ts": "https://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.live.ts",
    "ws_ts": "ws://192.168.6.150:49080/rtp/34020000001180000001_34020000001310000016.live.ts",
    "wss_ts": "wss://192.168.6.150:49443/rtp/34020000001180000001_34020000001310000016.live.ts",
    "rtmp": "rtmp://192.168.6.150:49035/rtp/34020000001180000001_34020000001310000016",
    "rtmps": "rtmps://192.168.6.150:49350/rtp/34020000001180000001_34020000001310000016",
    "rtsp": "rtsp://192.168.6.150:49554/rtp/34020000001180000001_34020000001310000016",
    "rtsps": "rtsps://192.168.6.150:49332/rtp/34020000001180000001_34020000001310000016",
    "rtc": "https://192.168.6.150:49443/index/api/webrtc?app=rtp&stream=34020000001180000001_34020000001310000016&type=play",
    "mediaServerId": "zZb5HhL4CFWERd3H",
    "tracks": null,
    "transactionInfo": null
  }
}
       
在摄像机推流状态下访问https://192.168.6.150:49443/index/api/webrtc?app=rtp&stream=34020000001180000001_34020000001310000016&type=play，报404
通过https://192.168.6.150:49443可以正常访问
想使用webrtc播放摄像机视频

**Comment by monktan89** [comment]
external ip 设置你对外rtc访问端口即可
