### ISSUE TITLE
ts_demand和fmp4_demand参数无效

### ISSUE THREAD

**Issue by amhoho** [ZLMediaKit/ZLMediaKit#1212]
配置中:
```
#http[s]-ts协议是否按需生成
ts_demand=1
#http[s]-fmp4、ws[s]-fmp4协议是否按需生成
fmp4_demand=1
```
结果:
重起Server后推流时仍然注册ts和fmp4.

**Comment by xia-chu** [comment]
注册还是会注册 为了随时能播放 但是不会转协议的&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: amhoho ***@***.***&gt;
发送时间: 2021年11月11日 08:35
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] ts_demand和fmp4_demand参数无效 (Issue #1212)





 
配置中:
 #http[s]-ts协议是否按需生成 ts_demand=1 #http[s]-fmp4、ws[s]-fmp4协议是否按需生成 fmp4_demand=1  
结果:
 重起Server后推流时仍然注册ts和fmp4.
