### ISSUE TITLE
[技术咨询]webRTC 推流音频编码格式是ADPCM导致有些播放器没有声音

### ISSUE THREAD

**Issue by a327958099** [ZLMediaKit/ZLMediaKit#1214]
**咨询的功能模块**
- wetRTC推流

**咨询的具体内容和问题**
- webRTC 推流录制成MP4，视频的音频编码格式是ADPCM导致我们的播放器播放没有声音，请问webRTC推流音频编码能修改成ACC或者其他编码格式吗？

**Comment by xia-chu** [comment]
webrtc不支持aac的，你也可以选择opus

**Comment by xia-chu** [comment]
zlm rtc推流偏好是g711u 目的是 安防、直播、rtc都支持这个

**Comment by a327958099** [comment]
> webrtc不支持aac的，你也可以选择opus

具体怎么做呢，能给我一个具体的方法吗？我是用前端进行webrtc推流的，使用的是官方提供的ZLMRTCClient.js文件，感谢！

**Comment by xia-chu** [comment]
配置文件rtc.preferredCodecA中的opus提到最前就行了，注意这个需要更新到最新代码，刚提交的特性
```ini
[rtc]
#rtc支持的音频codec类型,在前面的优先级更高
#以下范例为所有支持的音频codec
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
#rtc支持的视频codec类型,在前面的优先级更高
#以下范例为所有支持的视频codec
preferredCodecV=H264,H265,AV1X,VP9,VP8
```

**Comment by a327958099** [comment]
> 配置文件rtc.preferredCodecA中的opus提到最前就行了，注意这个需要更新到最新代码，刚提交的特性
> 
> ```ini
> [rtc]
> #rtc支持的音频codec类型,在前面的优先级更高
> #以下范例为所有支持的音频codec
> preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
> #rtc支持的视频codec类型,在前面的优先级更高
> #以下范例为所有支持的视频codec
> preferredCodecV=H264,H265,AV1X,VP9,VP8
> ```

感谢您的回复，按照你的配置，各个codec类型我的测试过了，最新的代码编译的，也没有解决我遇到的问题，uniapp框架使用video播放使用webrtc推流的视频依然没有声音，使用FFmpeg拉流代理(addFFmpegSource)后则可以正常有声音，但是使用FFmpeg拉流代理后业务业务逻辑变繁琐了，特别不稳定，推流拉流都容易掉线

**Comment by xia-chu** [comment]
咋会 你配置文件改错地方了吧 我可是测试过得



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mufei ***@***.***&gt;
发送时间: 2021年11月15日 16:55
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]webRTC 推流音频编码格式是ADPCM导致有些播放器没有声音 (Issue #1214)





  
配置文件rtc.preferredCodecA中的opus提到最前就行了，注意这个需要更新到最新代码，刚提交的特性
 [rtc] #rtc支持的音频codec类型,在前面的优先级更高 #以下范例为所有支持的音频codec preferredCodecA=PCMU,PCMA,opus,mpeg4-generic #rtc支持的视频codec类型,在前面的优先级更高 #以下范例为所有支持的视频codec preferredCodecV=H264,H265,AV1X,VP9,VP8
  
感谢您的回复，按照你的配置，各个codec类型我的测试过了，最新的代码编译的，也没有解决我遇到的问题，uniapp框架使用video播放使用webrtc推流的视频依然没有声音，使用FFmpeg拉流代理(addFFmpegSource)后则可以正常有声音，但是使用FFmpeg拉流代理后业务业务逻辑变繁琐了，特别不稳定，推流拉流都容易掉线

**Comment by a327958099** [comment]
> 咋会 你配置文件改错地方了吧 我可是测试过得 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Mufei ***@***.***&gt; 发送时间: 2021年11月15日 16:55 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]webRTC 推流音频编码格式是ADPCM导致有些播放器没有声音 (Issue #1214) 配置文件rtc.preferredCodecA中的opus提到最前就行了，注意这个需要更新到最新代码，刚提交的特性 [rtc] #rtc支持的音频codec类型,在前面的优先级更高 #以下范例为所有支持的音频codec preferredCodecA=PCMU,PCMA,opus,mpeg4-generic #rtc支持的视频codec类型,在前面的优先级更高 #以下范例为所有支持的视频codec preferredCodecV=H264,H265,AV1X,VP9,VP8 感谢您的回复，按照你的配置，各个codec类型我的测试过了，最新的代码编译的，也没有解决我遇到的问题，uniapp框架使用video播放使用webrtc推流的视频依然没有声音，使用FFmpeg拉流代理(addFFmpegSource)后则可以正常有声音，但是使用FFmpeg拉流代理后业务业务逻辑变繁琐了，特别不稳定，推流拉流都容易掉线 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

就修改[rtc]preferredCodecA=PCMU,PCMA,opus,mpeg4-generic这个配置对吗？这4个配置的先后顺序我都测试过，还是一样的没有声音？还需要修改其他地方吗？

**Comment by xia-chu** [comment]
你修改的配置文件路径多少？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Mufei ***@***.***&gt;
发送时间: 2021年11月15日 17:08
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]webRTC 推流音频编码格式是ADPCM导致有些播放器没有声音 (Issue #1214)

**Comment by a327958099** [comment]
> 你修改的配置文件路径多少？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Mufei ***@***.***&gt; 发送时间: 2021年11月15日 17:08 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]webRTC 推流音频编码格式是ADPCM导致有些播放器没有声音 (Issue #1214)

/root/ZLMediaKit/release/linux/Debug/config.ini  和MediaServer执行文件是同目录
`
[general]
addMuteAudio=0
enableVhost=0
enable_audio=1
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=300000
mediaServerId=45.125.44.16
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=20000
ts_demand=0

[rtc]
externIP=
port=8000
preferredCodecA=opus,PCMU,PCMA,mpeg4-generic
preferredCodecV=H264,H265,AV1X,VP9,VP8
rembBitRate=1000
timeoutSec=15
`

**Comment by xia-chu** [comment]
你们的播放器支持什么音频编码？只是什么就设置为什么

**Comment by a327958099** [comment]
> 你们的播放器支持什么音频编码？支持什么就设置为什么

我们是使用uniapp框架来开发的，使用的是video标签，支持rtmp流以及MP4，现在是播放都正常的，就是没有声音，在电脑浏览器里播放 http://xxx/1000/102.liv.mp4  是正常有声音的，就是在uniapp里面播放有画面没有声音，但是如果使用FFmpeg拉流代理(addFFmpegSource)后的流播放又是完全正常有声音的，所以应该还是webrtc推流的音频编码不一样导致的

**Comment by xia-chu** [comment]
那不行 基于h5 mse的方案 都不支持aac之外的音频，而webrtc不支持aac
