### ISSUE TITLE
[功能请求]webrtc 模块后续可否支持DataChannel

### ISSUE THREAD

**Issue by poorboy1991** [ZLMediaKit/ZLMediaKit#1216]
**描述该功能的用处，可以提供相关资料描述该功能**
    大神您好，期望的功能就是利用webrtc推流通道 额外建立一条dataChannel用来传输流以外的数据，目前ZL的webrtc的模块暂时好像没有支持，所以想问下后续有支持的可能么

**Comment by xia-chu** [comment]
先不考虑这个 个人开发时间精力有限 诚需更多开发者一起加入共建共享 issue先关闭了
