### ISSUE TITLE
[技术咨询]基于http的mjpeg拉取及录制

### ISSUE THREAD

**Issue by goodtogood** [ZLMediaKit/ZLMediaKit#1217]
非常棒的项目，请问是不支持mjpeg的录制吗？
通过api添加时总提示如下内容

```
http://127.0.0.1:4080/index/api/addStreamProxy?vhost=__defaultVhost__&app=rtp&stream=tz&url=http%3A%2F%2F122.116.35.72%2Fwebcapture.jpg%3Fcommand%3Dsnap%26channel%3D1&timeout_sec=30

{
   "code" : -1,
   "msg" : "DESCRIBE:451 ERROR"
}
```

**Comment by xia-chu** [comment]
不支持 addStreamProxy接口只支持有限的几种协议 包括hls、rtsp、rtmp。其他协议请用 addFFmpegSource接口

**Comment by goodtogood** [comment]
已经尝试使用了 addFFmpegSource，可以成功拉取，但只有一帧就退出了，应该是http的请求结束了，以后会不会考虑在zlm中处理这种情况，比如使用定时器，指定间隔去fork ffmpeg拉取

**Comment by xia-chu** [comment]
> 已经尝试使用了 addFFmpegSource，可以成功拉取，但只有一帧就退出了，应该是http的请求结束了，以后会不会考虑在zlm中处理这种情况，比如使用定时器，指定间隔去fork ffmpeg拉取；或者内置一个方法，这种源用fork的方式效率不大高

addFFmpegSource接口是有退出重试功能的，说明你这个流本来就不是视频流吧 只是一次一张图片而已

**Comment by xia-chu** [comment]
视频一秒30帧，不可能一秒调用30次http请求吧？就算不fork进程方式 也开销极大
