### ISSUE TITLE
[功能请求] player 功能完善

### ISSUE THREAD

**Issue by PioLing** [ZLMediaKit/ZLMediaKit#1218]
1、player音频选项，类似ffmpeg 的-an 或 allowed_media_types:video 或 (*player)[kAudio] = 0;

2、play 的 close 接口 ，截图功能；

3、丰富 支持http-flv/ps/ts/mp2 等协议 ；

4、h265 自动侦测和转换264 开关

**Comment by xia-chu** [comment]
这个是何必呢 这个范例只是演示下zlm的播放器能力，要跟FFmpeg比功能是找虐啊

**Comment by xia-chu** [comment]
一般来说 流媒体服务器的拉流功能 不需要做的太强大的 这个功能主要实现集群用的

**Comment by PioLing** [comment]
> 一般来说 流媒体服务器的拉流功能 不需要做的太强大的 这个功能主要实现集群用的

zlm本身支持多协议就很强大了，服务器客户端通吃 锦上添花啊，哈哈...

**Comment by xia-chu** [comment]
客户端通吃真做不到 现在做播放器的 都绕不开FFmpeg的，有FFmpeg这座大山在 别想超越了。
但是FFmpeg最大的问题是阻塞式api和socket，基本只能做些轻量的客户端开发，在服务端无法拉取海量的流

**Comment by zhang2349** [comment]
可不可以支持下http-flv 毕竟这也是流媒体输出的一种格式

**Comment by xia-chu** [comment]
> 可不可以支持下http-flv 毕竟这也是流媒体输出的一种格式

内部版本已经支持 会择机放出
