### ISSUE TITLE
[技术咨询]ffmpeg_cmd_key 测试用例中postman中应该如何填写，可否给一个样例，非常感谢

### ISSUE THREAD

**Issue by ixingqiao** [ZLMediaKit/ZLMediaKit#1219]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by ixingqiao** [comment]
ffmpeg_cmd_key 测试用例中postman中应该如何填写，可否给一个样例，非常感谢

**Comment by ixingqiao** [comment]
不好意思，找到了答案，非常感谢，知道怎么配置了

**Comment by mingyuejingque** [comment]
找到答案也贴上来啊，

**Comment by ixingqiao** [comment]
不好意思，这个是我理解上失误，这里的ffmpeg_cmd_key 指定的实际上是后台的配置文件的config.ini文件文件的配置文件的key，比如配置文件中增加自定义的配置项：
[ffmpeg]
cmd_ty=%s -re -f rtsp -rtsp_transport tcp -i %s -f flv -an -vcodec copy -acodec aac %s

则对应的ffmpeg_cmd_key的对应的值填写为：“ffmpeg.cmd_ty” 则调用的时候，就会使用这个ffmpeg的模板

**Comment by zh19900725** [comment]
> 

我也遇到了相同的问题，我还以为要自己传一个ffmpeg指令，原来是要提前写到配置文件里

**Comment by xia-chu** [comment]
> > 
> 
> 我也遇到了相同的问题，我还以为要自己传一个ffmpeg指令，原来是要提前写到配置文件里

嗯，随便让提供模板，会存在执行任意命令的风险。
