### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by EdifierX** [ZLMediaKit/ZLMediaKit#1220]
Gradle 4.10.1
Ndk r14b
AndroidStudio编译失败
`What went wrong:
Execution failed for task ':app:generateJsonModelDebug'.
> Build command failed.
  Error while executing process /Users/edison/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/edison/Downloads/ZLMediaKit-master/Android/app/src/main/cpp -B/Users/edison/Downloads/ZLMediaKit-master/Android/app/.externalNativeBuild/cmake/debug/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-15 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/edison/Downloads/ZLMediaKit-master/Android/app/build/intermediates/cmake/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/edison/Documents/android-ndk-r14b -DCMAKE_CXX_FLAGS=-std=c++11 -frtti -fexceptions -DCMAKE_TOOLCHAIN_FILE=/Users/edison/Documents/android-ndk-r14b/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/edison/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja}
  -- Configuring incomplete, errors occurred!
  See also "/Users/edison/Downloads/ZLMediaKit-master/Android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
  
  CMake Error at CMakeLists.txt:1 (project):
    The CMAKE_C_COMPILER:
  
      /Users/edison/Documents/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
  
    is not a full path to an existing compiler tool.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.
  
  
  CMake Error at CMakeLists.txt:1 (project):
    The CMAKE_CXX_COMPILER:
  
      /Users/edison/Documents/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
  
    is not a full path to an existing compiler tool.
  
    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.`

**Comment by xia-chu** [comment]
好像是ndk安装有问题 这个问题我无法解决
