### ISSUE TITLE
[技术咨询] GB28181 UDP推流持续丢包

### ISSUE THREAD

**Issue by addriumruss** [ZLMediaKit/ZLMediaKit#1221]
![1784317cfe6bbbbb2670a849b2f2428](https://user-images.githubusercontent.com/35988105/142096208-35038ab9-4056-44b6-9474-ac5b08154832.png)

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81#%E4%B8%A2%E5%8C%85%E9%97%AE%E9%A2%98%E8%B0%83%E8%AF%95

**Comment by addriumruss** [comment]
感谢回应！ 
抱歉上午着急问题定位和修复，没说明清楚环境！
镜头是今年年中采购的海康镜头，用国标2016版udp协议向平台推流，千兆电信专线带宽，用网线直连交换机和镜头，流媒体用zlm, 国标信令服务采用wvp那个。总共10个镜头，都采用720P分辨率。服务器是100M阿里云固定带宽。
连续测试了一个多月都很正常，今天早上忽然服务器系统盘空间不足，导致所有图像无法播放，于是清理日志释放了几十G磁盘空间，发现视频流还是没有；然后重启zlm和wvp，发现还是不行，具体来说，zlm反复出现上面的rtp丢包错误, wvp似乎国标信令通讯有错, 类似这样: 
![image](https://user-images.githubusercontent.com/35988105/142161179-c5d3d5cd-0a4f-4c20-b365-1363efee5c0f.png)

最后是1个半小时后去现场，看镜头配置页面都显示国标状态是在线，于是重启了一个镜头，这个镜头就立即恢复了国标通讯、视频流上报，能播放；然后大约又等待半小时，其它9个镜头都自动恢复了国标通讯和视频流上报。整个系统恢复正常。 推测是镜头需要大约2小时才能自动恢复。

在镜头都推流正常的情况下，重启zlm和wvp，发现只需要10分钟都能自动恢复。

看了代码CommonRtp.cpp 52行，说是网络问题导致丢包。可惜在现场没找到证据，带宽似乎都正常。
实在没搞懂深层原因，因此写出这些细节供项目研发人员参考。如果有相关思路请随时通知，多谢！

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/142169969-3d53d3ab-3d9d-442c-9f94-011c4811cf48.png)

**Comment by addriumruss** [comment]
大佬，那个页面好像访问不了：
![image](https://user-images.githubusercontent.com/35988105/142170536-c5bf1d00-0172-4af9-b8f7-27b118abb02e.png)

**Comment by xia-chu** [comment]
https://sharechain.qq.com/8ad7ce0e08fe44a35ddf89d92be7b077

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/142171223-dad5a08f-10fe-4f87-9e9b-7afef29f5ee2.png)

**Comment by addriumruss** [comment]
神奇了 为啥我打不开啊

**Comment by addriumruss** [comment]
我10个720P镜头，试下加到10M看行不行

**Comment by xia-chu** [comment]
长大的孩子2021-1-6 09:04:16 
![img](http://shp.qpic.cn/collector/1213642868/4fc9ddda-e4e4-46be-a7ca-9e1a551183ee/0)只有一个

子悦2021-1-6 09:04:45 
[https://www.cnblogs.com/yorkyang/p/7689096.html ](https://www.cnblogs.com/yorkyang/p/7689096.html)

子悦2021-1-6 09:05:18 
![img](http://shp.qpic.cn/collector/1213642868/8c70dd62-150f-4ee3-a815-01a38b51bd71/0)

长大的孩子2021-1-6 09:07:15 
我的是212992

子悦2021-1-6 09:07:56 
加大成4MB

子悦2021-1-6 09:08:13 
应该不会丢了

长大的孩子2021-1-6 09:14:42 
还是会 哈哈哈

长大的孩子2021-1-6 09:14:43 
![img](http://shp.qpic.cn/collector/1213642868/3fc7bac9-4b2e-4d65-afa4-a5374f61ba37/0)

子悦2021-1-6 09:17:47 
用cat /proc/net/snmp | grep -w Udp查看，InErrors 列显示当操作系统UDP队列溢出时丢失的UDP数据包总个数

子悦2021-1-6 09:17:54 
看看内核丢包没

子悦2021-1-6 09:19:27 
zlm显示丢包时 再看看

长大的孩子2021-1-6 09:20:29 
![img](http://shp.qpic.cn/collector/1213642868/4391f28a-4dd4-42e2-a72c-72b07ed722fc/0)

长大的孩子2021-1-6 09:20:32 
一直都在的

长大的孩子2021-1-6 09:20:48 
![img](http://shp.qpic.cn/collector/1213642868/15271b34-0f2e-429d-9c3a-2aee48350c4b/0)

子悦2021-1-6 09:21:42 
那应该是真的丢包了

子悦2021-1-6 09:21:55 
你是udp走的公网吧？

长大的孩子2021-1-6 09:22:18 
是的

子悦2021-1-6 09:22:21 
内核没丢包 说明内核收到的udp数据都被zlm消费掉了

子悦2021-1-6 09:23:25 
![img](http://shp.qpic.cn/collector/1213642868/5ea7479d-7baf-4b40-86a2-65c06b3b785e/0)

子悦2021-1-6 09:23:29 
这个调大试试

子悦2021-1-6 09:23:37 
如果还是丢包 就真的是公网丢包了

长大的孩子2021-1-6 09:23:49 
调整到多少啊

子悦2021-1-6 09:23:53 
100

**Comment by addriumruss** [comment]
多谢大佬！ 

现在没丢包，打印好多遍都是这样：
[root@video guandao]# cat /proc/net/snmp | grep -w Udp
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors
Udp: 11388741680 4992196728 26338 2260572 26338 0 0
[root@video guandao]# cat /proc/net/snmp | grep -w Udp
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors
Udp: 11388755602 4992196728 26338 2260576 26338 0 0
[root@video guandao]# cat /proc/net/snmp | grep -w Udp
Udp: InDatagrams NoPorts InErrors OutDatagrams RcvbufErrors SndbufErrors InCsumErrors
Udp: 11388906948 4992196728 26338 2260596 26338 0 0

现在每天盯着，万一出现丢包再看这个值的情况

**Comment by xia-chu** [comment]
如果使用10000单端口多流模式 需要设置下多队列网卡CPU中断均衡提供性能：
https://blog.csdn.net/linggang_123/article/details/113186750
