### ISSUE TITLE
[技术咨询] zlm可以推出不同分辨率流么

### ISSUE THREAD

**Issue by JacksonTu** [ZLMediaKit/ZLMediaKit#1222]
**咨询的功能模块**
- zlm可以推出不同分辨率流么

**咨询的具体内容和问题**
- zlm可以推出不同分辨率流，比如NVR摄像机分辨率是1080p，通过zlm可以推1080p、720p等分辨率

**Comment by mingyuejingque** [comment]
自己监听推流事件，等有新的NVR推流过来就用ffmpeg拉流来转码再推不同分辨率的进去。

**Comment by 174001602** [comment]
可以试试 同时拉主码流和辅码流

**Comment by JacksonTu** [comment]
有demo没-------- 原始邮件 --------发件人： 174001602 ***@***.***>日期： 2021年11月19日周五 08:49收件人： ZLMediaKit/ZLMediaKit ***@***.***>抄送： JacksonTu ***@***.***>, Author ***@***.***>主    题： Re: [ZLMediaKit/ZLMediaKit] [技术咨询] zlm可以推出不同分辨率流么 (Issue #1222)

可以试试 同时拉主码流和辅码流
