### ISSUE TITLE
[BUG]rtp推流多音轨多音轨声音不正常

### ISSUE THREAD

**Issue by aningxu** [ZLMediaKit/ZLMediaKit#1223]
**bug现象**
尝试向rtp推流，多音轨流，显示推流成功，但播放时，显示只有1个音轨，且无声音。

**bug产生时的使用场景**
RTP

**bug是否可以复现，怎么复现**
推流命令：
```
/usr/local/bin/ffmpeg -re -i input -map 0:v:0 -map 0:a:0 -map 0:a:1 -c:v copy -c:a copy -async 1 -f rtp_mpegts rtp://127.0.0.1:10000
```

**Comment by aningxu** [comment]
用手机VLC播放，2个不同音轨的声音交替出现，应该是2个音轨被合并到了一个音轨上。

**Comment by xiongguangjie** [comment]
不支持多音轨得直播流，建议通过音频得通道（channel）来实现相应得效果
