### ISSUE TITLE
[BUG] 为什么跨域设置不全局统一呢？

### ISSUE THREAD

**Issue by oblank** [ZLMediaKit/ZLMediaKit#1227]
**bug现象**
- 视频流地址 index/api/webrtc 自带header：Access-Control-Allow-Origin:* 但接口地址（eg:/index/api/isMediaOnline）又不带跨域设置

**bug产生时的使用场景**
- 如果反向代理时设置了跨域，浏览器拉取视频时会报 Access-Control-Allow-Origin 重复，不设接口又跨域

**Comment by xia-chu** [comment]
那index/api/webrtc 接口的跨域设置是否应该取消掉？

**Comment by oblank** [comment]
建议统一设或不设，或是一个配置项之类的

**Comment by xiongguangjie** [comment]
只有检查到Origin字段才会设置跨域字段，如果没有就不会设置
