### ISSUE TITLE
[技术咨询]关于播放链接的有效期

### ISSUE THREAD

**Issue by zh19900725** [ZLMediaKit/ZLMediaKit#1229]
请问获取的播放链接，有效期是多久？还是说on_play只要通过后就可以一直播放？

**Comment by xia-chu** [comment]
这个完全根据你的hook自定义实现

**Comment by zh19900725** [comment]
> 

请问下是hook的哪个接口？on_play也只能播放一开始校验鉴权

**Comment by zh19900725** [comment]
> 这个完全根据你的hook自定义实现
请问下是hook的哪个接口？on_play也只能播放一开始校验鉴权

**Comment by zh19900725** [comment]
> 这个完全根据你的hook自定义实现

请问下是hook的哪个接口？on_play也只能播放一开始校验鉴权

**Comment by xia-chu** [comment]
哦 你想人家一直播放 但是只能看一段时间对吧？

**Comment by zh19900725** [comment]
> 哦 你想人家一直播放 但是只能看一段时间对吧？

对的，比如我分发一个链接，他只能用两个小时，两个小时后他必须重新获取链接

**Comment by xia-chu** [comment]
这个功能我不会去开发的 因为这个太业务了，太业务的东西需要自己开发。如果有谁能开发好并提交pr，那么我倒是可以合并下pr。
