### ISSUE TITLE
[技术咨询]SDK 开启hls 无效问题

### ISSUE THREAD

**Issue by skiesme** [ZLMediaKit/ZLMediaKit#1230]
**咨询的功能模块**
- sdk

**咨询的具体内容和问题**
首先十分感谢大大提供了这么遍历的工具，我是以sdk的方式使用的 ZLMediaKit。
现在遇到了一些问题，具体操作如下：
1.  同时开启了 http/rtsp/rtmp 服务;
2. 通过 `mk_proxy_player` 新建代理播放器，并设置参数`hls_enabled = 1`；
3. 通过 `mk_proxy_player_play` 开始进行代理拉流；
4. 最后根据 url 规则生成了 rtsp/rtmp/flv/hls 格式的播放地址，但是 hls 总是无法打开。通过 `server` api 方式添加的内容，可以正常播放。

想咨询一下，在我实际调用sdk api 使用hls 时有什么特殊注意的地方吗? 

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by skiesme** [comment]
SDK：https://github.com/ZLMediaKit/ZLMediaKit/issues/483#issuecomment-692676051
播放链接：
```
"flv": "http://127.0.0.1:10810/live/828fa193-af2a-36cd-823e-388b3d013f59.flv",
"hls": "http://127.0.0.1:10810/live/828fa193-af2a-36cd-823e-388b3d013f59/hls.m3u8"
"rtsp": "rtsp://127.0.0.1:10811/live/828fa193-af2a-36cd-823e-388b3d013f59",
"rtmp": "rtmp://127.0.0.1:10812/live/828fa193-af2a-36cd-823e-388b3d013f59",
```

**Comment by xia-chu** [comment]
播放失败播放器显示什么错误代码？





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 如花与食客 ***@***.***&gt;
发送时间: 2021年11月21日 12:54
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]SDK 开启hls 无效问题 (Issue #1230)





 
咨询的功能模块
  
sdk 
 
咨询的具体内容和问题
 首先十分感谢大大提供了这么遍历的工具，我是以sdk的方式使用的 ZLMediaKit。
 现在遇到了一些问题，具体操作如下：
  
同时开启了 http/rtsp/rtmp 服务; 

通过 mk_proxy_player 新建代理播放器，并设置参数hls_enabled = 1； 

通过 mk_proxy_player_play 开始进行代理拉流； 

最后根据 url 规则生成了 rtsp/rtmp/flv/hls 格式的播放地址，但是 hls 总是无法打开。通过 server api 方式添加的内容，可以正常播放。 
 
想咨询一下，在我实际调用sdk api 使用hls 时有什么特殊注意的地方吗?
 
注意事项
  
 
技术咨询前请先认真阅读readme, wiki,如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue
 

 
技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by skiesme** [comment]
> 我是在mac下 用 IINA [打开留地址的，显示错误内容为：无法打开文件或流！
<img width="672" alt="iShot2021-11-21 13 09 36" src="https://user-images.githubusercontent.com/37571393/142750424-bd8e2a05-5219-4c55-a654-be8a85004154.png">

**Comment by xia-chu** [comment]
用ffplay播放





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 如花与食客 ***@***.***&gt;
发送时间: 2021年11月21日 13:10
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]SDK 开启hls 无效问题 (Issue #1230)





  
我是在mac下 用 IINA [打开留地址的，显示错误内容为：无法打开文件或流！

**Comment by skiesme** [comment]
hls 播放：

<img width="889" alt="iShot2021-11-21 13 17 54" src="https://user-images.githubusercontent.com/37571393/142750621-7e789a68-1c9a-47b0-8c42-fe7befabb083.png">

flv 播放：

<img width="891" alt="iShot2021-11-21 13 17 44" src="https://user-images.githubusercontent.com/37571393/142750626-391ed6f2-bcc1-4d32-bbb4-2917eafbc1de.png">

**Comment by xia-chu** [comment]
看下zlmediakit的日志



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 如花与食客 ***@***.***&gt;
发送时间: 2021年11月21日 13:18
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]SDK 开启hls 无效问题 (Issue #1230)





 
hls 播放：
 

 
flv 播放：

**Comment by skiesme** [comment]
感谢大大，刚才找到问题原因了。
是我设置 `http.rootPath` 和 `hls.filePath` 的问题。
之前将zlmediakit 打成jar包，没设置这两个值，直接使用的话会有问题。
