### ISSUE TITLE
[BUG]ZLMediaKit.postman_collection.json导入失败

### ISSUE THREAD

**Issue by zhangzj03** [ZLMediaKit/ZLMediaKit#1233]
**bug现象**
- bug产生时服务器的异常行为(例如: 崩溃/无法访问/丢包花屏)
- bug产生时，打印的上下文日志(可以截图或粘贴文本)
- 调试core文件时，崩溃触发点的函数调用栈(可以截图或粘贴文本)

![](https://cdn.nlark.com/yuque/0/2021/png/12899489/1637672145382-d86c5cbe-33f2-4328-9b4e-e1676169914b.png)
![](https://cdn.nlark.com/yuque/0/2021/png/12899489/1637673598858-a956b853-0028-4916-8ad6-45d2fe801d67.png)

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的什么功能模块？
postman 无法导入json文件
**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
- 什么类型的操作系统，32位，64位？
- 什么cpu类型？

**Comment by xia-chu** [comment]
昨天晚上已经修复这个问题了 谢谢反馈！
