### ISSUE TITLE
h265的rtsp源拉流后只能播放rtsp的格式，其余格式播放提示找不到解码器[BUG]

### ISSUE THREAD

**Issue by zhexuepizi** [ZLMediaKit/ZLMediaKit#1236]
**bug现象**
-h265的rtsp源拉流后只能播放rtsp的格式，其余格式播放提示找不到解码器[BUG]
- 播放flv或者rtmp时，一直报如下错误：
![image](https://user-images.githubusercontent.com/32978138/143376650-44181caf-162d-4344-8d0b-3bce5ec52aca.png)

代码commit版本为5daf52cafd859adb47c726a3437bf055338ed4fd

ubuntu18.04版本

**Comment by zhexuepizi** [comment]
补充一下ffprobe对应flv或者rtmp的结果：
![Uploading image.png…]()

**Comment by zhexuepizi** [comment]
补充一下ffprobe的结果截图：
![image](https://user-images.githubusercontent.com/32978138/143382114-7c3e6dd5-5bf7-44cc-89ad-9c1f0650fe80.png)
麻烦厦楚大佬看看

**Comment by HammerZhao** [comment]
h265的编码。 可以在 ffmpeg 用flv 格式播放?

**Comment by zhexuepizi** [comment]
好像是不行，那有什么办法可以让网页直接播放h265的视频流吗？请教一下


发自我的iPhone

**Comment by xia-chu** [comment]
https://gitee.com/xia-chu/FFmpeg 用我这个分支可以播放265的flv

**Comment by zhexuepizi** [comment]
> 

感谢夏楚大佬。不知道大佬有没有开个收费视频课的想法？音视频开发学习难度太大，相关资料也比较晦涩，如果能开个视频课程的话那就太好了～

**Comment by xia-chu** [comment]
> > 
> 
> 感谢夏楚大佬。不知道大佬有没有开个收费视频课的想法？音视频开发学习难度太大，相关资料也比较晦涩，如果能开个视频课程的话那就太好了～

qq群友3期共4个视频 你可以看下
