### ISSUE TITLE
[技术咨询] RTMP转推GB28181怎么配置呀?

### ISSUE THREAD

**Issue by al00000** [ZLMediaKit/ZLMediaKit#1238]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

- 想要: RTMP转推GB28181

**咨询的具体内容和问题**
- RTMP转推GB28181
- 
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
rtmp怎么给zlm？
zlm推送GB28181？

**Comment by al00000** [comment]
嗯,zlm接收rtmp的推流, 然后通过zlm配置参数后推流到GB28181的平台

**Comment by al00000** [comment]
我看这个图 https://user-images.githubusercontent.com/11495632/114176523-d50fce80-996d-11eb-81f8-0a2e2715ba7b.png 有这个功能,所以想咨询下

**Comment by xia-chu** [comment]
zlm收到rtmp推流后 会注册媒体源 你可以观察下zlm的日历`媒体注册`条。
然后可以用[web api](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#27indexapistartsendrtp)之 startSendRtp接口 转发为 GB28181 PS RTP推流。
