### ISSUE TITLE
[功能请求]GB28181断流重连

### ISSUE THREAD

**Issue by zh19900725** [ZLMediaKit/ZLMediaKit#1240]
**描述该功能的用处，可以提供相关资料描述该功能**
我用ZLMediaKit接收PS流，因为ps流偶发性会出现异常断流（我没发bye命令流莫名其妙就断了，只能判断是网络不稳定），这里希望
1.ZLMediaKit能在ps流异常断开后通过hook把流在拉起来，而不是立刻回收分配给播放断的播放通道

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
配置文件里rtp_proxy.timeoutSec项，默认配置15，但是实际发现上游ps流发送端的socket断开后，流会立刻被注销，并没有等15秒

**描述你期望实现该功能的方式和最终效果**
希望能有hook把流重新拉起来

**Comment by zh19900725** [comment]
我用on_stream_change 这个hook监听注销事件，注销后我立刻重新拉起，但是发现以下情况：给下游播放器的socket会立刻断开，

**Comment by 174001602** [comment]
个人理解，断流不是zlm自身的问题，其他环节带来的系统问题，让zlm解决过分了

**Comment by zh19900725** [comment]
> 个人理解，断流不是zlm自身的问题，其他环节带来的系统问题，让zlm解决过分了

这个不敢苟同，个人认为作为一个健壮性好不错的服务就应该尽可能考虑容灾、容错。音视频推流总是会有遇到各种场景，偶发的tcp断链其实并不是哪一块服务有问题，可能就是网络波动，我们不能总指望网络绝对的理想，而是应该有一定能力因对常见的异常情况。断流重连策略这个要求其实挺普遍的，甚至在很多播放器其实就有这个能力

**Comment by 174001602** [comment]
例如1.zlm服务正常 用户侧 到 zlm 网络波动 造成播放器中断 这个你的要求播放器自动重连重播 zlm是不是躺枪
2.推流测 到 zlm 网络中断 你认为 zlm 有能力主动说 快推流给我 快推流给我 就能让 推流测 马上就推流zlm 这个我认为不现实 推流测的故障 不能让 zlm 去买单吧，这种情况下 播放端我要播放我要播放 就是你zlm不好 有点偏颇了是不是，至于怎么让断流的时候客户体验好 是不是该 播放测做一些东西
体验的好坏是个系统工程，单独强调zlm 一点没啥意义 ，zlm 只是其中一个环节，咋样用户侧体验好要系统的去看待 去解决

**Comment by zhang2349** [comment]
楼主想法是好的 但是对参数和事件的理解都是错的 肯定达不到你的效果
目前没这个功能
是不是稍微改造下 在断流的时候 把stream_not_found那套逻辑走一遍 ？？

**Comment by xia-chu** [comment]
> **描述该功能的用处，可以提供相关资料描述该功能** 我用ZLMediaKit接收PS流，因为ps流偶发性会出现异常断流（我没发bye命令流莫名其妙就断了，只能判断是网络不稳定），这里希望 1.ZLMediaKit能在ps流异常断开后通过hook把流在拉起来，而不是立刻回收分配给播放断的播放通道
> 
> **该功能是否用于改进项目缺陷，如果是，请描述现有缺陷** 配置文件里rtp_proxy.timeoutSec项，默认配置15，但是实际发现上游ps流发送端的socket断开后，流会立刻被注销，并没有等15秒
> 
> **描述你期望实现该功能的方式和最终效果** 希望能有hook把流重新拉起来

@zh19900725 你说的推流断开了不掐断播放器，重新推流，播放器能接着播放这个特性，其实有些服务器是支持的，比如说srs的rtmp推流功能，但是这样有几个问题。
- 1、重新推流了，时间戳对齐不了，服务器要重新处理时间戳，这个其实zlm有相关代码实现，也不算难。
- 2、重新推流了，视频编解码信息可能会变，这个怎么处理？还是干脆不处理？我感觉直接没法处理，宽高、profile都变了或多条或少条track都由他去吧，反正谁使用该功能，谁就负责保持不变。
- 3、重新推流容忍时间为多少？1分钟？10分钟？1个小时？播放器也不会等你这么久啊，那就是设置1分钟内吧，推流端口了，zlm不去掐断播放器，让播放器主动超时去断开吧（目前srs就这样的），但是这样好像会导致stream数太多时，对象内存得不到及时清理，我看有人反馈过srs这个问题导致的内存泄露。

**Comment by xia-chu** [comment]
还有一点，zlm跟srs不一样啊，srs是单线程啊，zlm是多线程啊，推流端线程会变的，上次推流线程是A，下次是B，这个线程安全逻辑处理也很麻烦啊，虽然可以通过线程切换解决，但是那样比较影响性能。

推流、播放中断导致体验问题，我觉得播放器和推流器还是要做重试功能啊，如果重试做的好，其实体验会有点影响，但是也不是很影响。
