### ISSUE TITLE
[BUG]声明有音频但是无确切数据的国标流无法正常注册

### ISSUE THREAD

**Issue by dawn2zhang** [ZLMediaKit/ZLMediaKit#1241]
**bug现象**
更新新版本后无法正常推流

![微信图片_20211126141723](https://user-images.githubusercontent.com/8624439/143536286-310521fc-6f4f-48e5-a9f3-5e341325610e.png)

**bug产生时的使用场景**
海康DVR
更新版本后（5daf52c/5d56e86c）出现问题
老版本（4c2b323）正常

**bug是否可以复现，怎么复现**
版本

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
centos7

**Comment by xia-chu** [comment]
此现象是否必现？ 其他摄像头是否有次问题？有dump文件供调试吗

**Comment by dawn2zhang** [comment]
> 此现象是否必现？ 其他摄像头是否有此问题？有dump文件供调试吗

只有视频的时候无法正常回调track ready方法

**Comment by xia-chu** [comment]
不是声明有pcmu吗？为什么只有视频？

**Comment by xia-chu** [comment]
zlm等待track ready的超时时间是10秒，10秒zlm还没超时 但是wvp就超时了 导致wvp请求关闭了端口

**Comment by xia-chu** [comment]
这谈不上bug 只能说这个摄像头不规范。之前版本没这个问题是因为后面新增一个判断track是否真实有数据的特性，如果没数据，要十秒超时才会忽略这个track

**Comment by xia-chu** [comment]
新增配置项`wait_track_ready_ms`了，你可以缩短时间，或者直接 修改配置项`enable_audio`为0
