### ISSUE TITLE
[技术咨询] 关于使用C API创建RTP Server接收数据的疑惑

### ISSUE THREAD

**Issue by hctym1995** [ZLMediaKit/ZLMediaKit#1242]
**咨询的功能模块**
基于C API的调用疑惑

**咨询的具体内容和问题**
目前在我的28181项目中，RTP收流使用的是原生的socket接口，希望替换为zlm的c api 中的rtp server模块，但是不同于基于zlm api的rtsp rtmp等可以直接通过回调函数获取视频数据，没有明白如果只想使用rtp server，接收数据，应该如果调用api 

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你想怎么接收数据？接收H264/aac这种吗？还是RTP？

**Comment by hctym1995** [comment]
RTP

**Comment by xia-chu** [comment]
如果是rtp 没必要用`mk_rtp_server.h`下的api啊，因为socket出来的就是rtp, 用TcpServer和UdpServer实现就行啊

**Comment by hctym1995** [comment]
这样的话，是否意着不需要使用zlm的api了。我是不是应该用zltoolkit

**Comment by xia-chu** [comment]
是啊 用UdpServer和TcpServer实现即可，在Session::onRecv中收到的就是rtp

**Comment by xia-chu** [comment]
不过Tcp方式的rtp有坑啊 你可以参考zlm的RtpSession对象

**Comment by hctym1995** [comment]
好的，感谢
