### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by keepmovng** [ZLMediaKit/ZLMediaKit#1243]
1、我把项目直接运行在android设备上，使用ffmpeg -re -i shouzhicao.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://192.168.82.77/live/test往这个android设备推流，但是android设备上并没有打印出任何信息，请问我还需要怎么做？
2、在我项目中我想这么用：运行在android设备上当做服务端，有个客户端往android设备rtsp推流，这个android设备把这个流以rtsp组播方式转发出来，请问这个方案可以实现吗？我具体需要怎么调用接口呢？
非常感谢

**Comment by xia-chu** [comment]
能否在FFmpeg运行的设备上跑下wireshark抓下rtsp包？

**Comment by keepmovng** [comment]
![image](https://user-images.githubusercontent.com/11866656/143559404-9773fba0-12fb-48c3-8350-2ecda7db67cd.png)
有劳了

**Comment by xia-chu** [comment]
网络都不通啊

**Comment by keepmovng** [comment]
ffmpeg -re -i shouzhicao.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://192.168.82.77:8554/live/test
我加上端口号8554就可以推流了

**Comment by keepmovng** [comment]
您好。提问中的第二问题我使用ffmpeg -re -i shouzhicao.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://192.168.82.77:8554/live/test往服务器推流，在windows上开了10个客户端使用udp组播播放ffplay -rtsp_transport udp_multicast rtsp://192.168.82.77:8554/live/test，发现网络占用会很高，请问服务端是往10个客户端分别推流了吗？能否这10个客户端共用一个组播地址呢？
