### ISSUE TITLE
[BUG] FPS高帧率导致视频无法播放，画面花屏

### ISSUE THREAD

**Issue by a327958099** [ZLMediaKit/ZLMediaKit#1245]
webrtc推流
"tracks": [
                {
                    "codec_id": 0,
                    "codec_id_name": "H264",
                    "codec_type": 0,
                    "fps": 0,
                    "height": 480,
                    "ready": true,
                    "width": 640
                },
]
Mac，Windows 7 64位的电脑webrtc推流时，tracks->fps 的值是0  此时浏览器能正常播放视频，使用Windows 10 64位电脑推流时 tracks->fps 的值是60，此时浏览器就无法播放视频了，画面是花屏的

**Comment by xia-chu** [comment]
你用什么协议播放花屏

**Comment by a327958099** [comment]
> 

102.live.mp4  
播放的是已live.mp4结尾的url

**Comment by a327958099** [comment]
> 你用什么协议播放花屏

102.live.mp4
播放的是已live.mp4结尾的url

**Comment by a327958099** [comment]
> 你用什么协议播放花屏

我重新下载最新的代码重新编译后视频可以正常播放了，tracks->fps 这个帧率有会在0~30帧之间，感觉好像是fps 60高帧率的情况下播放就会有问题，是不是H5 video不支持高帧率啊，另外ZLMediaKit能设置这个fps帧率吗？

**Comment by a327958099** [comment]
> 你用什么协议播放花屏

webrtc推流，tracks->fps 这个帧率在0~30帧之间时视频正常，能正常播放，感觉好像是fps 60高帧率的情况下播放就会有问题，是不是H5 video不支持高帧率啊，另外ZLMediaKit能设置这个fps帧率吗？

**Comment by xiongguangjie** [comment]
webrtc 推流有丢包的可能性，会导致花屏，是否可以把直播流下一部分，我分析一下

**Comment by a327958099** [comment]
> tracks->fps

经测试，确定是tracks->fps帧率的问题导致的播放异常，fps到60帧时就会出现播放异常，我是用electron开发的桌面程序webrtc推流，electron版本13出现这个bug，fps要么是0(播放正常)，要么是60(播放异常)，我把electron版本更新到最新的16之后fps高帧率的情况就没有出现了，视频流的fps在0~30之间不固定的(播放正常)，而且这个bug只在Windows 10 专业版 64位的系统上出现，Windows 7 和Mac不会出现，

**Comment by xia-chu** [comment]
哦 那就是electron的bug吗？其实这个fps计算代码有点问题，因为宽高fps在zlme中其实没啥用，所以我就没去更新这个代码了
