### ISSUE TITLE
[BUG]最新版本device_chn模块MP4录制BUG，webrtc https播放、音频推送BUG

### ISSUE THREAD

**Issue by moyidaren** [ZLMediaKit/ZLMediaKit#1247]
**bug现象**
- 1、使用device_chn模块输入H264数据，打开mp4录制功能，设置录制时长60秒，录制文件表现为无法结束、无法播放、大小一直增长

- 2、src\Record\MP4.cpp、src\Record\MP4Demuxer.cpp编译失败，预计是与libmov不匹配导致，改回老版本可编译通过

- 3、使用webrtc推送demo页面单独推送音频，可以在getMediaList看到该流数据过来了，但rtsp打开该流异常，且无法通过demo断开，这个功能老版本(8352f119f28d7eefae0f8bda83a1404e1848cf6a)是正常的

- 4、使用webrtc播放demo页面使用https协议打开视频流失败，能正常https post sdp成功，但看不到视频流，已加载pem证书文件，使用http协议就可以正常工作，这个功能老版本(8352f119f28d7eefae0f8bda83a1404e1848cf6a)是正常的

- 5、src\server\main.cpp 里再打开webrtc功能后，没有引用UdpServer.h，小问题可以修复一下

**bug产生时的使用场景**
1、使用MediaServer.exe，配置好rtsp、rtmp、hls、mp4、ts、rtc服务

**bug是否可以复现，怎么复现**
- 1、1号BUG，可以使用c api 模拟输入H264数据，并在创建通道时打开MP4录制即可重现

- 2、2号BUG，使用最新版本打开MP4，进行编译即可发生报错

- 3、3号BUG，打开MediaServer.exe，并使用https://XX.XX.XX.XX:sslport/webrtc，填好https://XX.XX.XX.XX:sslport/index/api/webrtc?app=live&stream=stream0&type=push，选择push，只打开音频，点击推送，输入http://XX.XX.XX.XX:port/index/api/getMediaList?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc即可发现推送成功，打开vlc 输入rtsp://XX.XX.XX.XX:554/live/stream0 即可发现问题

- 4、4号BUG，打开MediaServer.exe，使用RTSP推流到stream0，并使用https://XX.XX.XX.XX:sslport/webrtc，填好https://XX.XX.XX.XX:sslport/index/api/webrtc?app=live&stream=stream0&type=play，选择play，点击播放 即可发现问题

- 5、5号BUG，使用最新版本打开WEBRTC，进行编译即可发生报错

**zlm代码git commit hash值**
e48342485864c1bd02405603c05fa2cee71e80ae

**操作系统环境**
win10 64位
intel i7-9750H

**Comment by baiyfcu** [comment]
第一个问题，我这一直在这么用没有问题，如果不断在增大说明一直在input，肯定是没有mk_media_release，或者说是不是使用流程有问题

**Comment by moyidaren** [comment]
> 第一个问题，我这一直在这么用没有问题，如果不断在增大说明一直在input，肯定是没有mk_media_release，或者说是不是使用流程有问题

你好，谢谢解答，第一个问题确实是一直input，不过这是实时流，同样的rtsp_push就能MP4录制切割，如果要手动再release会不会导致其他依赖这个device_chn的实时服务出现问题呢？这归根结底应该还是服务模式不一致的问题导致。

**Comment by moyidaren** [comment]
第一个问题已解决，关注Record/MP4Recorder.cpp/inputFrame 里关于_max_second判定

**Comment by xia-chu** [comment]
- 3号问题，不好意思，我本地无法复现，这是截图：
<img width="1602" alt="图片" src="https://user-images.githubusercontent.com/11495632/145351408-9a03581e-7c16-499f-b39a-225fa3e7241e.png">

<img width="1123" alt="图片" src="https://user-images.githubusercontent.com/11495632/145351067-4bdd2ddd-04d0-48b2-81f8-a5fd741c5fb3.png">

**Comment by xia-chu** [comment]
- 4号问题，你要确保你推送的rtsp流没B帧，并且确保配置文件rtsp.directProxy为0, 因为webrtc对rtp和264很挑，一般的rtsp的rtp，webrtc可能播放不了

**Comment by xia-chu** [comment]
-5号问题不存在，因为我都是打开webrtc编译的，GitHub 持续集成编译也是打开的。

**Comment by xia-chu** [comment]
本帖反馈的问题 基本没一个是经得起推敲的，至此结贴

**Comment by moyidaren** [comment]
请看群里反馈的PDF
