### ISSUE TITLE
[android编译]需要增加头文件

### ISSUE THREAD

**Issue by keepmovng** [ZLMediaKit/ZLMediaKit#1248]
System.cpp针对android环境需要增加头文件 #include "stdlib.h"，否则exit()函数找不到

**Comment by xia-chu** [comment]
抱歉 之前你这个问题我处理了 我安装了下Android studio，但是由于Android studio改版太大了 我在grandle阶段就失败了，导致无法验证此问题，今天整理issue时发现此遗留问题，先按照你的建议修改下
