### ISSUE TITLE
[技术咨询] 底层代码修改太频繁

### ISSUE THREAD

**Issue by wujianGit123** [ZLMediaKit/ZLMediaKit#1249]
我们的项目基于ZLM开发，感谢作者的无私奉献。但有一点问题，就是ZLM的底层代码改动太频繁了，而且经常代码结构变动很大，出于业务的需要，我自己在ZLM的代码上做了些定制化的功能增加和修改，虽然我已经尽量避免自己的代码与ZLM原有代码存在交叠，但要完全分开是不现实的，导致每次我要将自己项目的ZLM代码更新到最新版本都需要做大量的新旧代码嵌合和对比工作，现在我已经大半年没有更新ZLM代码了，虽然业务代码整体运行状态还算良好，但还是有个别问题，比如H265编码的hls和fmp4格式播放不能向rtsp那样稳定流畅，经常出现卡顿丢帧之类的问题，所以我总想着是不是更新到最新版本的ZLM这个问题就能解决了。

**Comment by wusopp** [comment]
搞不懂你想表达什么

**Comment by xia-chu** [comment]
可以把比较底层的修改提交pr上来 这样以后由开源项目维护 你就不用为合并冲突苦恼了
