### ISSUE TITLE
[BUG]Sec-WebSocket-Key生成问题

### ISSUE THREAD

**Issue by dsjonline** [ZLMediaKit/ZLMediaKit#1251]
按理说应该是16字节的随机数的被base64编码后的值 makeRandStr(16, false)经过SHA1::encode_bin()长度已经发生变化了

**Comment by xia-chu** [comment]
你想表达什么意思？如果有问题，那zlm的websocket功能应该有问题啊

**Comment by dsjonline** [comment]
导致zlm的websocket client连接其他websocket服务器无法连接 直接400

**Comment by xia-chu** [comment]
能不能抓两个包对比下？正常客户端的和zlmediakit客户端的抓包

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 轻微 ***@***.***&gt;
发送时间: 2021年12月8日 10:21
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]Sec-WebSocket-Key生成问题 (Issue #1251)

**Comment by dsjonline** [comment]
不好抓包，把请求头发出来吧

Request URL: https://127.0.0.1:8002/
Request Method: GET

Request Headers

[postman]
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: UDOECeP1DvRbXOKTEBElLQ==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: 127.0.0.1:8002
Response Headers
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: WMfbF+cVIvhzAZnel6VId5S4OO4=

[zlm]
["Accept"] = "*/*"
["Accept-Language"] = "zh-CN,zh;q=0.8"
["Connection"] = "Upgrade"
["Host"] = "127.0.0.1:8002"
["Sec-WebSocket-Key"] = "SxmHuelQDfsozuXpdd7IHq2N1wA="
["Sec-WebSocket-Version"] = "13"
["Tools"] = "ZLMediaKit(git hash:e4834248,branch:master,build time:Dec  8 2021 11:34:34)"
["Upgrade"] = "websocket"
["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"
