### ISSUE TITLE
好多包，如util，network，thread怎么没有？

### ISSUE THREAD

**Issue by badboywyh** [ZLMediaKit/ZLMediaKit#1253]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by wasphin** [comment]
参考 [获取代码](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B#1%E8%8E%B7%E5%8F%96%E4%BB%A3%E7%A0%81), 那是子模块的内容, 需要初始化并更新 git 子模块.

**Comment by badboywyh** [comment]
谢谢！
