### ISSUE TITLE
[技术咨询]ZLMediaKit编译问题

### ISSUE THREAD

**Issue by zhangzhiming1017** [ZLMediaKit/ZLMediaKit#1255]
**咨询的功能模块**
- ZLMediaKit 在windows环境编译，ide为vs2019专业版 

**咨询的具体内容和问题**
- mediaserver编译失败
- 失败提示：
- FFmpegSource.obj : error LNK2019: 无法解析的外部符号 "public: static class std::shared_ptr<class mediakit::MediaSource> __cdecl mediakit::MediaSource::find(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?find@MediaSource@mediakit@@SA?AV?$shared_ptr@VMediaSource@mediakit@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@000_N@Z)，该符号在函数 "private: void __cdecl FFmpegSource::findAsync(int,class std::function<void __cdecl(class std::shared_ptr<class mediakit::MediaSource> const &)> const &)" (?findAsync@FFmpegSource@@AEAAXHAEBV?$function@$$A6AXAEBV?$shared_ptr@VMediaSource@mediakit@@@std@@@Z@std@@@Z) 中被引用
WebApi.obj : error LNK2001: 无法解析的外部符号 "public: static class std::shared_ptr<class mediakit::MediaSource> __cdecl mediakit::MediaSource::find(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?find@MediaSource@mediakit@@SA?AV?$shared_ptr@VMediaSource@mediakit@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@000_N@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: static class std::shared_ptr<class mediakit::MediaSource> __cdecl mediakit::MediaSource::find(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?find@MediaSource@mediakit@@SA?AV?$shared_ptr@VMediaSource@mediakit@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@000_N@Z)
WebApi.obj : error LNK2019: 无法解析的外部符号 "public: static class std::shared_ptr<class mediakit::MediaSource> __cdecl mediakit::MediaSource::find(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?find@MediaSource@mediakit@@SA?AV?$shared_ptr@VMediaSource@mediakit@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@00_N@Z)，该符号在函数 "public: __cdecl <lambda_2e9486447e6e6019413c06544558fffb>::operator()(class toolkit::SockInfo &,class mediakit::StrCaseMap &,class HttpAllArgs<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct mediakit::StrCaseCompare,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > const &,class Json::Value &,class mediakit::HttpResponseInvokerImp const &)const " (??R<lambda_2e9486447e6e6019413c06544558fffb>@@QEBA@AEAVSockInfo@toolkit@@AEAVStrCaseMap@mediakit@@AEBV?$HttpAllArgs@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@UStrCaseCompare@mediakit@@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@@@AEAVValue@Json@@AEBVHttpResponseInvokerImp@4@@Z) 中被引用
zlmediakit.lib(HttpTSPlayer.obj) : error LNK2019: 无法解析的外部符号 __GSHandlerCheck_EH4，该符号在函数 "public: __cdecl mediakit::HttpRequestSplitter::HttpRequestSplitter(void)" (??0HttpRequestSplitter@mediakit@@QEAA@XZ) 中被引用
zlmediakit.lib(RtmpPusher.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PSDecoder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(TSDecoder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsParser.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtspPlayer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtmpPlayer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsPlayer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtspPusher.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MP4.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PusherBase.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Decoder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtcpFCI.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(G711.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(L16.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PSEncoder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpCache.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(AACRtp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H265Rtp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(CommonRtp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Opus.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H265Rtmp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(AAC.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(AACRtmp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H264Rtp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MP4Demuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H264.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H264Rtmp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(H265.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PlayerBase.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpMultiCaster.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpReceiver.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtmpDemuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(GB28181Process.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpSession.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Rtcp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(UDPServer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtmpMuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MP4Muxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MediaPlayer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MediaPusher.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Stamp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MediaSink.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpSender.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtspMuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpCookieManager.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsMediaSource.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(FlvMuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(WebSocketSplitter.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsMakerImp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(TsMuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpBody.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpConst.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(amf.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Factory.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MP4Recorder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsMaker.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtmpProtocol.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtmpSession.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(ShellSession.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MP4Reader.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpClientImp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpRequester.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtspSplitter.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtspSession.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpProcess.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpSelector.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(RtpServer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpClient.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpSession.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MultiMediaSourceMuxer.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PlayerProxy.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(PusherProxy.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Rtsp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Rtmp.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Recorder.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HttpFileManager.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(MediaSource.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(config.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Parser.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(Frame.obj) : error LNK2001: 无法解析的外部符号 __GSHandlerCheck_EH4
zlmediakit.lib(HlsPlayer.obj) : error LNK2019: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)，该符号在函数 "public: static unsigned __int64 __cdecl std::ctype<char>::_Getcat(class std::locale::facet const * *,class std::locale const *)" (?_Getcat@?$ctype@D@std@@SA_KPEAPEBVfacet@locale@2@PEBV42@@Z) 中被引用
zlmediakit.lib(RtspPusher.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(RtmpPusher.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(HttpTSPlayer.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(PlayerBase.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(PusherBase.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(RtspPlayer.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
zlmediakit.lib(RtmpPlayer.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl toolkit::TcpClient::startConnect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (?startConnect@TcpClient@toolkit@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl mediakit::Demuxer::setTrackListener(class mediakit::TrackListener *,bool)" (?setTrackListener@Demuxer@mediakit@@QEAAXPEAVTrackListener@2@_N@Z)，该符号在函数 "public: __cdecl mediakit::RtspMediaSourceImp::RtspMediaSourceImp(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (??0RtspMediaSourceImp@mediakit@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@00H@Z) 中被引用
webrtc.lib(WebRtcPusher.obj) : error LNK2001: 无法解析的外部符号 "public: void __cdecl mediakit::Demuxer::setTrackListener(class mediakit::TrackListener *,bool)" (?setTrackListener@Demuxer@mediakit@@QEAAXPEAVTrackListener@2@_N@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2019: 无法解析的外部符号 "public: float __cdecl mediakit::RtspDemuxer::getDuration(void)const " (?getDuration@RtspDemuxer@mediakit@@QEBAMXZ)，该符号在函数 "public: void __cdecl mediakit::RtspMediaSourceImp::setProtocolTranslation(bool,bool)" (?setProtocolTranslation@RtspMediaSourceImp@mediakit@@QEAAX_N0@Z) 中被引用
webrtc.lib(WebRtcPusher.obj) : error LNK2001: 无法解析的外部符号 "public: float __cdecl mediakit::RtspDemuxer::getDuration(void)const " (?getDuration@RtspDemuxer@mediakit@@QEBAMXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl mediakit::RtcpContext::onRtp(unsigned short,unsigned int,unsigned __int64,unsigned int,unsigned __int64)" (?onRtp@RtcpContext@mediakit@@UEAAXGI_KI0@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContext::getLost(void)" (?getLost@RtcpContext@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContext::getExpectedPackets(void)const " (?getExpectedPackets@RtcpContext@mediakit@@UEBA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<class toolkit::Buffer> __cdecl mediakit::RtcpContext::createRtcpSR(unsigned int)" (?createRtcpSR@RtcpContext@mediakit@@UEAA?AV?$shared_ptr@VBuffer@toolkit@@@std@@I@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<class toolkit::Buffer> __cdecl mediakit::RtcpContext::createRtcpRR(unsigned int,unsigned int)" (?createRtcpRR@RtcpContext@mediakit@@UEAA?AV?$shared_ptr@VBuffer@toolkit@@@std@@II@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContext::getExpectedPacketsInterval(void)" (?getExpectedPacketsInterval@RtcpContext@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContext::geLostInterval(void)" (?geLostInterval@RtcpContext@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<class toolkit::Buffer> __cdecl mediakit::RtcpContextForSend::createRtcpSR(unsigned int)" (?createRtcpSR@RtcpContextForSend@mediakit@@UEAA?AV?$shared_ptr@VBuffer@toolkit@@@std@@I@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl mediakit::RtcpContextForSend::onRtcp(class mediakit::RtcpHeader *)" (?onRtcp@RtcpContextForSend@mediakit@@UEAAXPEAVRtcpHeader@2@@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl mediakit::RtcpContextForRecv::onRtp(unsigned short,unsigned int,unsigned __int64,unsigned int,unsigned __int64)" (?onRtp@RtcpContextForRecv@mediakit@@UEAAXGI_KI0@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual class std::shared_ptr<class toolkit::Buffer> __cdecl mediakit::RtcpContextForRecv::createRtcpRR(unsigned int,unsigned int)" (?createRtcpRR@RtcpContextForRecv@mediakit@@UEAA?AV?$shared_ptr@VBuffer@toolkit@@@std@@II@Z)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContextForRecv::getExpectedPackets(void)const " (?getExpectedPackets@RtcpContextForRecv@mediakit@@UEBA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContextForRecv::getExpectedPacketsInterval(void)" (?getExpectedPacketsInterval@RtcpContextForRecv@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContextForRecv::getLost(void)" (?getLost@RtcpContextForRecv@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual unsigned __int64 __cdecl mediakit::RtcpContextForRecv::geLostInterval(void)" (?geLostInterval@RtcpContextForRecv@mediakit@@UEAA_KXZ)
webrtc.lib(WebRtcTransport.obj) : error LNK2001: 无法解析的外部符号 "public: virtual void __cdecl mediakit::RtcpContextForRecv::onRtcp(class mediakit::RtcpHeader *)" (?onRtcp@RtcpContextForRecv@mediakit@@UEAAXPEAVRtcpHeader@2@@Z)
E:\github_code\ZLMediaKit\release\windows64\Debug\Release\MediaServer.exe : fatal error LNK1120: 22 个无法解析的外部命令

这是缺少什么库吗?我看readme上，以及相关的教程链接也没有什么提示。

**Comment by xia-chu** [comment]
这个问题仅此一例反馈 我也没Windows编译环境 无能为力啊。

**Comment by xia-chu** [comment]
zlmediakit的代码是经过msvc ci编译通过了的 按道理不应该有你所述问题。
不济的话，建议用vs2017尝试下。
