### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by pkxiao** [ZLMediaKit/ZLMediaKit#1256]
**咨询的功能模块**
- 通过hook配置，无流时自动创建流，无人观看时删除流 

**咨询的具体内容和问题**
- 通过vlc播放器播放视频流时调用钩子创建流，推流接口返回code=0显示推流成功， 但播放器和视频流断开了连接， 提示以下错误：

   MediaServer[1-140007166752512] RtspSession.cpp:65 onError | 140007008390352(10.9.12.45:54030) RTSP播放器(__defaultVhost__/live/14.mp4)断开:end of file,耗时(s):4
   MediaServer[1-140007158359808] RtspSession.cpp:65 onError | 140006807070656(10.9.12.45:54033) RTSP播放器(__defaultVhost__/live/14.mp4)断开:no such track with control url:rtsp://10.4.196.111:554/live/14.mp4,耗时(s):0

- 在没有调用无人观看钩子前，再次点击播放， 能拉流成功， 试了改过很多配置都没有用， 这是哪里的问题？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
请更新下zlmediakit源码再测试下 之前的代码由可能有bug

**Comment by pkxiao** [comment]
刚刚通过build_docker_images.sh重新构建了镜像， 在触发hook  “on_stream_not_found“， ffmpeg进程还没起来， 播放器和服务之间的连接就断开了， 抛出以下两个错误：

1. RtspSession.cpp:65 onError | 334(10.9.12.45:64868) RTSP播放器(__defaultVhost__/live/14.mp4)断开:end of file,耗时(s):4
2. RtspSession.cpp:65 onError | 334(10.9.12.45:64875) RTSP播放器(__defaultVhost__/live/14.mp4)断开:no such track with control url:rtsp://10.4.196.111:554/live/14.mp4,耗时(s):0

hook 调用返回是成功的， 当在没有触发hook  “on_stream_none_reader” 前再次播放， 是能播放成功的。

**Comment by xia-chu** [comment]
> 刚刚通过build_docker_images.sh重新构建了镜像， 在触发hook “on_stream_not_found“， ffmpeg进程还没起来， 播放器和服务之间的连接就断开了， 抛出以下两个错误：
> 
>     1. RtspSession.cpp:65 onError | 334(10.9.12.45:64868) RTSP播放器(**defaultVhost**/live/14.mp4)断开:end of file,耗时(s):4
> 
>     2. RtspSession.cpp:65 onError | 334(10.9.12.45:64875) RTSP播放器(**defaultVhost**/live/14.mp4)断开:no such track with control url:rtsp://10.4.196.111:554/live/14.mp4,耗时(s):0
> 
> 
> hook 调用返回是成功的， 当在没有触发hook “on_stream_none_reader” 前再次播放， 是能播放成功的。

麻烦抓个rtsp的包 我分析下
