### ISSUE TITLE
WebRtc Server Endpoint 

### ISSUE THREAD

**Issue by alessandroferraioli** [ZLMediaKit/ZLMediaKit#1257]
Hello Xia,

My mates and I run into some kind of issue/bug and before we continue the development we would like to get feedback from you.

Here's the thing: we executed the MediaServer test application that it's provided into ZLMediaKit/release/linux/Debug and we executed the file index.html into the www folder.

We used to use the _getIce_ endpoint, but apparently, on the last version that we pulled just yesterday it doesn't work anymore ( it actually returns a 404 error) when we provide the following parameters:

- Rtc Url : http://127.0.0.1/

- Url : rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4 ( of course you can use whatever rtsp video you preferer).

Are we doing something wrong? As I mentioned it used to work with the previous release.

Hopefully, you'll be able to help us,

Have a nice day :)

**Comment by xia-chu** [comment]
You open `http://127.0.0.1/` and return 404?

**Comment by alessandroferraioli** [comment]
Let me explain a little bit better, we would like to achieve the following scheme : 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25391024/145046403-238c4a44-db64-4179-bf53-ffe06481bb17.png)

This means we want to push the RTSP video using your webrtc server, and then be able to play it. Do you believe it's possible? 

Kind regards,

Alessandro

**Comment by wasphin** [comment]
Please provide the following info to clear the problem:
1. config file used, e.g. `config.ini`;
1. logs in the console or under log directory;
1. directory structure of `ZLMediaKit/release/linux/Debug/www`, you can run the following command under directory `ZLMediaKit/release/linux`:
    ```
    find www -type f -exec md5sum '{}' \;
    ```

If possible, please also provide the previous commit hash id that used to work well.

**Comment by xia-chu** [comment]
> Let me explain a little bit better, we would like to achieve the following scheme : ![MicrosoftTeams-image](https://user-images.githubusercontent.com/25391024/145046403-238c4a44-db64-4179-bf53-ffe06481bb17.png)
> 
> This means we want to push the RTSP video using your webrtc server, and then be able to play it. Do you believe it's possible?
> 
> Kind regards,
> 
> Alessandro

@alessandroferraioli You need push rtsp to zlmediakit with `h264` codec without `b frame`, then modfy `config.ini` to set `rtsp.directProxy=0`, so you can play it when `webrtc`

**Comment by xia-chu** [comment]
If you want compile  zlmediakit with `webrtc` enabled, you need to  do this:
- Install `openssl libs` with version above `1.1`.
- git clone the code of `srtp2`, and `configure` it with `--enable-openssl`.
- then compile `srtp2` and install it.
- `cmake` zlmediakit and `make` it.
