### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by scybZhangliang** [ZLMediaKit/ZLMediaKit#1258]
**咨询的功能模块**
接收RTP流后转RTMP

**咨询的具体内容和问题**
接受摄像头推流几十秒之后，会先提示RTMP播放器断开socket send timeout ，然后会报RTP推流器断开 connect reset by peer.
![image](https://user-images.githubusercontent.com/32383393/145038161-78492c29-d040-478c-b71f-91eb57972cab.png)

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
send timeout是因为网速不够 导致数据发送不出去，从而服务器掐断tcp连接，原因可能有两种：
- 本身网络带宽不够，可能是服务器带宽或播放器带宽不够。
- 视频推流时间戳有问题，导致播放器异常，消费数据不及时，可以尝试修改配置文件`rtmp.modfyStamp`为1尝试解决

**Comment by xia-chu** [comment]
rtp推流那个警告是摄像头主动停止的
