### ISSUE TITLE
openssl 依赖问题【mac11.4】和 centos8系统 求助

### ISSUE THREAD

**Issue by wanggq654321** [ZLMediaKit/ZLMediaKit#1259]
centos8 系统 

[ 91%] Built target zlmediakit
[ 91%] Building CXX object CMakeFiles/webrtc.dir/webrtc/DtlsTransport.cpp.o
/root/ZLMediaKit/webrtc/DtlsTransport.cpp: 在构造函数‘RTC::DtlsTransport::DtlsTransport(toolkit::EventPoller::Ptr, RTC::DtlsTransport::Listener*)’中:
/root/ZLMediaKit/webrtc/DtlsTransport.cpp:599:3: 错误：‘DTLS_set_timer_cb’在此作用域中尚未声明
   DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
   ^~~~~~~~~~~~~~~~~
/root/ZLMediaKit/webrtc/DtlsTransport.cpp:599:3: 附注：suggested alternative: ‘SSL_set_cert_cb’
   DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
   ^~~~~~~~~~~~~~~~~
   SSL_set_cert_cb
gmake[3]: *** [CMakeFiles/webrtc.dir/build.make:82：CMakeFiles/webrtc.dir/webrtc/DtlsTransport.cpp.o] 错误 1
gmake[2]: *** [CMakeFiles/Makefile2:381：CMakeFiles/webrtc.dir/all] 错误 2
gmake[1]: *** [CMakeFiles/Makefile2:1092：server/CMakeFiles/MediaServer.dir/rule] 错误 2
gmake: *** [Makefile:534：MediaServer] 错误 2
[root@localhost build]#

**Comment by wanggq654321** [comment]
什么原因？

**Comment by xiongguangjie** [comment]
opnessl 版本不对，看wiki 编译，srtp 需要特定的openssl 版本

**Comment by wanggq654321** [comment]
[root@localhost ~]# openssl version -a
OpenSSL 1.1.1g FIPS  21 Apr 2020
built on: Tue Mar 30 14:31:20 2021 UTC
platform: linux-x86_64
options:  bn(64,64) md2(char) rc4(16x,int) des(int) idea(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wa,--noexecstack -Wa,--generate-missing-build-notes=yes -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DZLIB -DNDEBUG -DPURIFY -DDEVRANDOM="\"/dev/urandom\"" -DSYSTEM_CIPHERS_FILE="/etc/crypto-policies/back-ends/openssl.config"
OPENSSLDIR: "/etc/pki/tls"
ENGINESDIR: "/usr/lib64/engines-1.1"
Seeding source: os-specific
engines:  rdrand dynamic

**Comment by xia-chu** [comment]
@wanggq654321 你是不是centos系统啊？ zlm开启webrtc功能要求openssl要 1.1以上，openssl version -a显示的版本号，应该只是openssl可执行程序的版本，并不是openssl库的版本号，建议你下载openssl新版本源码并编译安装

**Comment by wanggq654321** [comment]
我这边发现项目对openssl依赖太强，这边需要升级系统的openssl，只要升级会导致mac11.4或centos8 系统崩溃不能使用，这边有什么好的建议不升级openssl 也可以正常调试编译libsrtp 使用呢？

**Comment by wanggq654321** [comment]
下面是mac报错信息：
[ 91%] Built target zlmediakit
[ 91%] Building CXX object CMakeFiles/webrtc.dir/webrtc/DtlsTransport.cpp.o
/Users/wanggaoqiang/Desktop/ZLMediaKit/webrtc/DtlsTransport.cpp:599:3: error: use of undeclared identifier 'DTLS_set_timer_cb'
                DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
                ^
1 error generated.

**Comment by wanggq654321** [comment]
目前发现这个 DTLS_set_timer_cb 这个方法对openssl依赖太强

**Comment by wasphin** [comment]
> DtlsTransport.cpp 这个文件 DTLS_set_timer_cb(this->ssl, onSslDtlsTimer); 这个调用是否可以兼容下老版本呢？

这个接口是 2017 年引入的, https://github.com/openssl/openssl/commit/fa4b82cc7cc556c03c652d40bd966ef3d4445592, 如果你的 openssl 版本是 1.1.1g 的话应该是带了的.

执行下如下命名确认下系统的 openssl 库版本
```
rpm -qi openssl-devel
```

并且执行 cmake 时, 打开 `CMAKE_VERBOSE_MAKEFILE` 选项, 比如:
```
cmake -DCMAKE_VERBOSE_MAKEFILE=ON
```
然后贴上完整的日志检查下使用的各依赖库版本是否正确.

**Comment by xia-chu** [comment]
> 我这边发现项目对openssl依赖太强，这边需要升级系统的openssl，只要升级会导致mac11.4或centos8 系统崩溃不能使用，这边有什么好的建议不升级openssl 也可以正常调试编译libsrtp 使用呢？

openssl可以多版本互容的 你下载openssl源码编译安装到指定目录，不要替换系统目录下的openssl就没事

**Comment by wasphin** [comment]
我这边 CentOS 7 下用的就是 1.1.1g 的版本, 没有问题, 我这边 RHEL 8 带的版本是 1.1.1k, 感觉不是 openssl 版本或系统的问题, 还是需要确认编译的环境.

**Comment by wanggq654321** [comment]
@xia-chu  厉害，和我的想法一致，这个我建议这个项目不要过度依赖系统的openssl，可以写一个脚本自动 libsrtp关联下载好的openssl版本，这个方案不知道能否行的通？

**Comment by wanggq654321** [comment]
[100%] Linking CXX executable ../../release/mac/Debug/MediaServer
Undefined symbols for architecture x86_64:
  "_DTLS_method", referenced from:
      RTC::DtlsTransport::DtlsEnvironment::CreateSslCtx() in libwebrtc.a(DtlsTransport.cpp.o)
  "_DTLS_set_timer_cb", referenced from:
      RTC::DtlsTransport::DtlsTransport(std::__1::shared_ptr<toolkit::EventPoller>, RTC::DtlsTransport::Listener*) in libwebrtc.a(DtlsTransport.cpp.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _srtp_aes_gcm_openssl_context_init in libsrtp2.a(aes_gcm_ossl.o)
      _srtp_aes_icm_openssl_context_init in libsrtp2.a(aes_icm_ossl.o)
  "_HMAC_CTX_free", referenced from:
      openssl_HMACsha256(void const*, unsigned long, void const*, unsigned long) in libzlmediakit.a(RtmpProtocol.cpp.o)
      RTC::openssl_HMACsha1(void const*, unsigned long, void const*, unsigned long) in libwebrtc.a(StunPacket.cpp.o)
      _srtp_hmac_dealloc in libsrtp2.a(hmac_ossl.o)
  "_HMAC_CTX_new", referenced from:
      openssl_HMACsha256(void const*, unsigned long, void const*, unsigned long) in libzlmediakit.a(RtmpProtocol.cpp.o)
      RTC::openssl_HMACsha1(void const*, unsigned long, void const*, unsigned long) in libwebrtc.a(StunPacket.cpp.o)
      _srtp_hmac_alloc in libsrtp2.a(hmac_ossl.o)
  "_HMAC_CTX_reset", referenced from:
      openssl_HMACsha256(void const*, unsigned long, void const*, unsigned long) in libzlmediakit.a(RtmpProtocol.cpp.o)
      RTC::openssl_HMACsha1(void const*, unsigned long, void const*, unsigned long) in libwebrtc.a(StunPacket.cpp.o)
  "_OPENSSL_init_crypto", referenced from:
      toolkit::SSL_Initor::SSL_Initor() in libzltoolkit.a(SSLBox.cpp.o)
  "_OPENSSL_init_ssl", referenced from:
      toolkit::SSL_Initor::SSL_Initor() in libzltoolkit.a(SSLBox.cpp.o)
  "_SSL_CTX_set_options", referenced from:
      toolkit::SSL_Initor::setupCtx(ssl_ctx_st*) in libzltoolkit.a(SSLBox.cpp.o)
      RTC::DtlsTransport::DtlsEnvironment::CreateSslCtx() in libwebrtc.a(DtlsTransport.cpp.o)
  "_SSL_is_init_finished", referenced from:
      toolkit::SSL_Box::flush() in libzltoolkit.a(SSLBox.cpp.o)
  "_X509_get0_pubkey", referenced from:
      toolkit::SSLUtil::cryptWithRsaPublicKey(x509_st*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool) in libzltoolkit.a(SSLUtil.cpp.o)
  "_X509_getm_notAfter", referenced from:
      RTC::DtlsTransport::DtlsEnvironment::GenerateCertificateAndPrivateKey() in libwebrtc.a(DtlsTransport.cpp.o)
  "_X509_getm_notBefore", referenced from:
      RTC::DtlsTransport::DtlsEnvironment::GenerateCertificateAndPrivateKey() in libwebrtc.a(DtlsTransport.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../release/mac/Debug/MediaServer] Error 1
make[2]: *** [server/CMakeFiles/MediaServer.dir/all] Error 2
make[1]: *** [server/CMakeFiles/MediaServer.dir/rule] Error 2
make: *** [MediaServer] Error 2
wanggqdeMacBook-Pro:build wanggq$

**Comment by wanggq654321** [comment]
这个是openssl 安装置顶目录的脚本

./Configure darwin64-x86_64-cc  --prefix=/usr/local/
sudo make && make install

**Comment by bluesky4485** [comment]
@wanggq654321 
应该手动修改build/server/CMakeFiles/MediaServer.dir/link.txt中的openssl相关的库的地址应该再make就可以了。

M1版本的mac上面会有这个库的arch不一致的问题
