### ISSUE TITLE
[技术咨询]请教一下,海康NVR推流异常

### ISSUE THREAD

**Issue by MMMMMine** [ZLMediaKit/ZLMediaKit#1261]
**咨询的功能模块**
*国标28181推流  NVR->ZLM*

**咨询的具体内容和问题**
ZLM日志显示一直注册注销,Rtp推流器断开
![image](https://user-images.githubusercontent.com/20126820/145144412-f1013c4a-77a2-4f5a-8941-df410621ffac.png)

从服务器抓包显示UDP包一直在接收.
![image](https://user-images.githubusercontent.com/20126820/145144517-448b10de-68cd-4a31-ac7a-66abcc78ebc3.png)

请问大佬为什么出现的这样情况? 是否为这款型号NVR的问题?
ps: 公司内别的NVR可以正常播放.

**Comment by xia-chu** [comment]
好像是解析不出数据 请使用zlmediakit的dump功能把文件分享出来分析下

**Comment by MMMMMine** [comment]
@xia-chu 大佬请查收,麻烦大佬分析  https://github.com/MMMMMine/ZML-DUMP

**Comment by xia-chu** [comment]
> @xia-chu 大佬请查收,麻烦大佬分析 https://github.com/MMMMMine/ZML-DUMP

大哥 你能不能多传点数据啊 rtp文件就57KB而已。
你可以把文件压缩为zip上传到此issue的
