### ISSUE TITLE
[BUG] rtsp 发送h264流中如果含有sei帧，那么启用nvr 存储到mp4文件会有内存的持续增加。

### ISSUE THREAD

**Issue by HammerZhao** [ZLMediaKit/ZLMediaKit#1263]
**bug现象**
发现如果发送的rtsp h264码流中含有sei帧,如果启用了 nvr 存储内存会持续增加。

**bug产生时的使用场景**
从摄像头获取的数据中含有sei帧 我使用ffmpeg 直接拉流转发没有重新编码 发现的这个问题。
发现如果发送的rtsp h264码流中含有sei帧,如果启用了 nvr 存储内存会持续增加。

后来发现只要抛弃掉sei帧即可
在mp4muxerinterface 类中我通过判断frame drapAble 来丢弃这一阵不存储就不会有这个问题

bool MP4MuxerInterface::inputFrame(const Frame::Ptr &frame) {
    if(frame->dropAble()){
        return true;
    }

**bug是否可以复现，怎么复现**

**zlm代码git commit hash值**
- git log查看
commit 15d84fdf765595c98bf37b4cf4238d220a2095d2 (HEAD -> master, origin/master, origin/HEAD)

**操作系统环境**
- ubuntu 18.04 64位？
- intel x86 

非常感谢夏楚的开源项目  对我学习音视频开发有很大的帮助

**Comment by xia-chu** [comment]
我看了下代码 貌似不应该导致内存持续增加啊。只有FrameMerge对象可能会缓存过多的frame，但是它内部也有最多100帧的限制。你说的内存持续增加，能定位下具体代码吗？

**Comment by HammerZhao** [comment]
> 

我发现问题的过程是这样的 我打开了cmake 中的Enable Memory Debug 选项
![image](https://user-images.githubusercontent.com/9584959/145354945-e4ecc87a-3147-4a6a-a141-c6f1591cd123.png)
1.我修改代码启动一个timer 30秒调用 一次去查询 内存使用 
使用ffmpeg -re -i h264带有sei帧的.mp4  -vcodec copy -an -f rtsp rtsp://127.0.0.1/live/stream1 这样推流 
我调试过代码发现其中带有sei帧 并且已经传到这个MP4Muxer.cpp MP4MuxerInterface::inputFrame(const Frame::Ptr &frame) 这个函数 
后来发现这个内存会持续增加。 然后我就把下面的写入mp4 文件那节 注释了。我怀疑是引入的三方库导致的内存问题。

在以上的操作之前我已经使用过valgrind 检查过内存泄露 根本没发现内存泄露 因此我怀疑可能是 某一个区域把数据一次放到容器中 只有在最终退出的时候容器才释放。

然后我就对下图的位置做了修改发现这里注释掉了以后运行了 24小时并没有内存持续性的增加。

![image](https://user-images.githubusercontent.com/9584959/145354907-8f4ceac1-89b4-4745-b7c8-748964a5b69c.png)

我中间还尝试修改这个编译过程连接到 googleperf tools 带的gmp 就是那个使用tcmalloc 分析heap使用情况的库可能是我使用的有问题没有调出来 我也是第一次使用这个库 后来我就是通过实验 不带sei帧的视频 与带sei帧的视频录制 逐渐缩小范围到 nvr录制过程中可能有问题

**Comment by HammerZhao** [comment]
综合来看可能是 mp4 writer write 这里的操作可能引起的问题

**Comment by xia-chu** [comment]
嗯 说实话 我也觉得zlm导致的内存溢出可能性很低，这个问题有可能是第三方库确实有可能有内存累积的问题，但是销毁对象，内存又会释放，所有valgrind等工具都检测不出问题

**Comment by HammerZhao** [comment]
这个问题 就是只要 判断一下 if(frame->dropAble()) 不写入就可以了 大概就是这样

**Comment by xia-chu** [comment]
能否把那个mp4分享下 我找下深层次问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HammerZhao ***@***.***&gt;
发送时间: 2021年12月9日 18:18
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] rtsp 发送h264流中如果含有sei帧，那么启用nvr 存储到mp4文件会有内存的持续增加。 (Issue #1263)





 
这个问题 就是只要 判断一下 if(frame-&gt;dropAble()) 不写入就可以了 大概就是这样
