### ISSUE TITLE
[技术咨询]WebRtc如何使用公网

### ISSUE THREAD

**Issue by kuaidou** [ZLMediaKit/ZLMediaKit#1264]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

WebRtc模块

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

ZLMediakit commit: 78d014c

问题1： 参见issue(#1007), 需要UDP端口30000到60000范围映射，这个还是必须的吗？  
问题2： 配置文件externIP 是否可以使用域名替代真实IP?

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
- 目前zlm的webrtc udp端口是单端口，默认8000端口即可。
- externIP需要设置为浏览器可见ip，不支持域名
