### ISSUE TITLE
[技术咨询] 服务端录制MP4播放问题

### ISSUE THREAD

**Issue by q7486828035** [ZLMediaKit/ZLMediaKit#1265]
**咨询的功能模块**
服务端录制MP4

**咨询的具体内容和问题**
服务端录制的MP4视频，在火狐浏览器上没用声音，谷歌浏览器正常，请问是否有办法解决？

**Comment by xia-chu** [comment]
能否把mp4发上来，记得压缩为zip

**Comment by q7486828035** [comment]
[09-27-32.mp4.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/7683079/09-27-32.mp4.zip)
就是这个

**Comment by q7486828035** [comment]
![image](https://user-images.githubusercontent.com/45918130/145354033-63af5ce7-7095-474d-ae5d-3be5a777cf19.png)
我也看过这个，更改了一下还是不行

**Comment by xiongguangjie** [comment]
火狐不支持mp4 g711 的播放，这个是浏览器的兼容问题，需要文件音频转码，转码为 aac
