### ISSUE TITLE
[技术咨询]  调用http://ZLMServer:18081/record/on_record_mp4 time out

### ISSUE THREAD

**Issue by jiajunkor** [ZLMediaKit/ZLMediaKit#1266]
**咨询的功能模块**
- /record/on_record_mp4

**咨询的具体内容和问题**
- Windows环境 摄像头推流在www/record/rtp/xxx/目录下生成mp4文件 请求接口http://ZLMServer:18081/record/on_record_mp4 时timeout  
- 
![aaaaa](https://user-images.githubusercontent.com/13203718/145367864-3d078f68-4a38-47cb-9658-cf80f02717a4.png)

- 

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你的hook接口`http://127.0.0.1:18081/record/on_record_mp4` 有问题，这个接口给zlm访问的，你要确保有效
