### ISSUE TITLE
[技术咨询] 服务器端的流的timestamp，是重新生成的吗？

### ISSUE THREAD

**Issue by jim-king-2000** [ZLMediaKit/ZLMediaKit#1267]
亲，客户问我们一个关于timestamp的问题，我们答不上来，特此向亲请教一下。客户问播放器拉流的时候，流的timestamp是重新生成的吗？还是直接copy源视频流的？

**Comment by xia-chu** [comment]
要看具体进出协议



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin ***@***.***&gt;
发送时间: 2021年12月9日 18:12
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] 服务器端的流的timestamp，是重新生成的吗？ (Issue #1267)





 
亲，客户问我们一个关于timestamp的问题，我们答不上来，特此向亲请教一下。客户问播放器拉流的时候，流的timestamp是重新生成的吗？还是直接copy源视频流的？

**Comment by jim-king-2000** [comment]
推拉都是RTSP呀，亲。

**Comment by xia-chu** [comment]
rtsp有点特殊呢，rtsp的时间戳本质上不来自rtp的时间戳，rtp的时间戳相当于相对时间戳，需要rtcp的sender report同步并还原成ntp时间戳。 在推拉都是rtsp的情况下，那么时间戳是不会变的，而且zlm也会通过sender report rtcp发送ntp时间戳

**Comment by xia-chu** [comment]
既然你都有客户了 想必已经把zlmediakit商用了，如果方便的话，可以在此 [issue](https://github.com/ZLMediaKit/ZLMediaKit/issues/511) 为zlmediakit背书下，谢谢！

**Comment by jim-king-2000** [comment]
我们做的执法仪系统采用了zlmediakit。整体用下来zlmediakit表现良好。没有什么问题。

**Comment by jim-king-2000** [comment]
> 既然你都有客户了 想必已经把zlmediakit商用了，如果方便的话，可以在此 [issue](https://github.com/ZLMediaKit/ZLMediaKit/issues/511) 为zlmediakit背书下，谢谢！

已经添加了。

**Comment by jim-king-2000** [comment]
> rtsp有点特殊呢，rtsp的时间戳本质上不来自rtp的时间戳，rtp的时间戳相当于相对时间戳，需要rtcp的sender report同步并还原成ntp时间戳。 在推拉都是rtsp的情况下，那么时间戳是不会变的，而且zlm也会通过sender report rtcp发送ntp时间戳

亲，那zlmediakit生成的rtsp时间戳，有什么配置项或者选项么？

**Comment by xia-chu** [comment]
> > 既然你都有客户了 想必已经把zlmediakit商用了，如果方便的话，可以在此 [issue](https://github.com/ZLMediaKit/ZLMediaKit/issues/511) 为zlmediakit背书下，谢谢！
> 
> 已经添加了。

不好意思 我都忘记了。
`那zlmediakit生成的rtsp时间戳，有什么配置项或者选项么？` 你这么问是有什么需求吗？你的场景 zlm没产生时间戳啊 都是透传的

**Comment by jim-king-2000** [comment]
> 不好意思 我都忘记了。
亲，是我没说清楚。我是看到了你的回帖之后才发的。您没搞错。我应该写成：“我刚刚已经去添加好了哈”。

**Comment by jim-king-2000** [comment]
> 你这么问是有什么需求吗？你的场景 zlm没产生时间戳啊 都是透传的

就是说，拉流的rtp timestamp是根据推流的rtp timestamp生成的，对吗？

**Comment by xia-chu** [comment]
> > 你这么问是有什么需求吗？你的场景 zlm没产生时间戳啊 都是透传的
> 
> 就是说，拉流的rtp timestamp是根据推流的rtp timestamp生成的，对吗？

对 是的，rtp里面的时间戳完全一致

**Comment by jim-king-2000** [comment]
收到。谢谢亲。祝zlmediakit越来越好。

**Comment by xia-chu** [comment]
谢谢
