### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by TungWli** [ZLMediaKit/ZLMediaKit#1268]
在执行 build_docker_images.sh命令得时候提示我
![image](https://user-images.githubusercontent.com/48422731/145545459-e21b4923-308f-4977-9ccb-32a923dc3456.png)
这是什么原因呀？

**Comment by monktan89** [comment]
可以把你完整执行命令发出来看看？第三方库更新了么

**Comment by xia-chu** [comment]
@monktan89 你要不直接在脚本中添加下 git submodule update --init

**Comment by TungWli** [comment]
我改完了dockerfile得脚本, 可以正常运行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 中午11:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (Issue #1268)





 
@monktan89 你要不直接在脚本中添加下 git submodule update --init
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by monktan89** [comment]
> 

看起来是没有更新第三方库，因为我是直接通过copy命令把源码拷贝进去的，在里面执行update有点不合适

**Comment by TungWli** [comment]
我更改了dockerfile成功的运行起来了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (Issue #1268)





   
看起来是没有更新第三方库，因为我是直接通过copy命令把源码拷贝进去的，在里面执行update有点不合适
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by monktan89** [comment]
done
