### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qiangdan** [ZLMediaKit/ZLMediaKit#1269]
**bug现象**
Android Studio 无法运行Android源码，报错CMake Error: CMake can not determine linker language for target: mpeg

如果您那边正常的话能否给我打个包发个安卓APK，QQ号289870510

**Comment by xia-chu** [comment]
这不是bug 你不看文档能怪谁？

**Comment by mozushixin** [comment]
![1666776697191](https://user-images.githubusercontent.com/49932627/197991191-6fddba5d-be55-4b08-b944-574c96b48373.jpg)
