### ISSUE TITLE
[BUG]RTSP拉流压测时MediaServer出现问题

### ISSUE THREAD

**Issue by heyingjie** [ZLMediaKit/ZLMediaKit#1271]
**bug现象**
-RTSP拉流压测时，MediaServer程序RTSP端口会出现问题，具体现象是TCP无法连接该端口，但之前已经连接上的推流端、播放器依旧正常。需要重启MediaServer才能恢复。

**系统环境**
![image](https://user-images.githubusercontent.com/11901953/145668931-e5a500aa-c598-411e-a0a7-b645a17c6ce3.png)

**bug产生时的使用场景**
- 产生bug时，使用的ZLM的RTSP流分发模块
- 使用FFMPEG推送rtsp音频流至MediaServer
- 使用test_bench_pull进行拉流压测

**bug是否可以复现，怎么复现**
- BUG复现率还是比较高的，使用test_bench_pull将路数调的高一点，比如5000路，就容易出现该问题。

**zlm代码git commit hash值**
- 54367fef311ec29a77233cfc7e6a9bf6f774523a

**操作系统环境**
- CentOS 7 (centos-release-7-9.2009.0.el7.centos.x86_64)
- Intel(R) Xeon(R) Bronze 3204

**Comment by xia-chu** [comment]
test_bench_pull 增加路数上不去时 有什么警告日志？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Seth ***@***.***&gt;
发送时间: 2021年12月11日 15:47
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]RTSP拉流压测时MediaServer出现问题 (Issue #1271)





 
bug现象
 -RTSP拉流压测时，MediaServer程序RTSP端口会出现问题，具体现象是TCP无法连接该端口，但之前已经连接上的推流端、播放器依旧正常。需要重启MediaServer才能恢复。
 
系统环境
 
 
bug产生时的使用场景
  
产生bug时，使用的ZLM的RTSP流分发模块 

使用FFMPEG推送rtsp音频流至MediaServer 

使用test_bench_pull进行拉流压测 
 
bug是否可以复现，怎么复现
  
BUG复现率还是比较高的，使用test_bench_pull将路数调的高一点，比如5000路，就容易出现该问题。 
 
zlm代码git commit hash值
  
54367fe 
 
操作系统环境
  
CentOS 7 (centos-release-7-9.2009.0.el7.centos.x86_64) 

Intel(R) Xeon(R) Bronze 3204

**Comment by heyingjie** [comment]
看了下报错的日志，too many open file，系统配置的值太小了，使用ulimit -n设置后，压测数量可以上去了，10000+路目前也正常。

之前出错的时候，退出时会出现段错误，产生coredump。

**Comment by xia-chu** [comment]
@heyingjie 有测试报告和数据可以分享下 作为性能数据参考 谢谢

**Comment by heyingjie** [comment]
> 

ZLMediaKit版本：e48342485864c1bd02405603c05fa2cee71e80ae
MediaServer运行环境：CentOS 7.9
编译配置：Release/启用JEMALLOC

推流端：100路RTSP(TCP)音频流推送至MediaServer,音频码率32Kbps
拉流端：使用test_bench_pull工具进行拉流测试
              `./test_bench_pull -l2 -t6 -i rtsp://192.168.1.18:3324/a/b d1 -Ttcp -c15000`
服务器：MediaServer -l4

6000路RTSP拉流：
![image](https://user-images.githubusercontent.com/11901953/145935067-fbf452b4-aad9-4e79-ac05-0bdeb0868132.png)
现象：
VLC监听播放流畅，拉流端稳定，无断开情况
服务器基础性能数据：
![image](https://user-images.githubusercontent.com/11901953/145934964-07bbbacd-17cc-49f4-8b29-2bf408eacefa.png)
![image](https://user-images.githubusercontent.com/11901953/145934964-07bbbacd-17cc-49f4-8b29-2bf408eacefa.png)


8000路RTSP拉流：
![image](https://user-images.githubusercontent.com/11901953/145934305-fad53a64-07f4-44e0-a528-1566e3e09fda.png)
现象：
VLC监听播放流畅，会出现少量的拉流端断开情况，readerCount在7998~8000之间波动，(客户端日志显示onPlayResult_l | 2 receive rtp timeout )
服务器基本性能数据：
![image](https://user-images.githubusercontent.com/11901953/145934693-2e41f92f-df5c-4f8a-a03b-cc33457438c8.png)
![image](https://user-images.githubusercontent.com/11901953/145934511-b3ea71d0-564e-4a5f-9e91-369db8e733cf.png)

10000路RTSP拉流：
![image](https://user-images.githubusercontent.com/11901953/145932532-196b312d-09e9-4478-b6e9-5fb62e2bf426.png)
现象：
VLC监听播放流畅，会出现少量的拉流端断开情况，readerCount在9990~10000之间波动，(客户端日志显示onPlayResult_l | 2 receive rtp timeout )
服务器基本性能数据：
![image](https://user-images.githubusercontent.com/11901953/145934033-df08deb1-b853-4943-9a7e-f4a9d5359f14.png)
![image](https://user-images.githubusercontent.com/11901953/145933146-46fe3643-d3d1-4d7e-a7d0-0928e8014352.png)

15000路RTSP拉流：
现象：出现VLC播放卡顿、静音，拉流客户端断开情况(客户端日志显示onPlayResult_l | 2 receive rtp timeout )
服务端基本性能数据：
![image](https://user-images.githubusercontent.com/11901953/145931680-08ff2893-5f94-467b-b35c-ce60a431605a.png)
![image](https://user-images.githubusercontent.com/11901953/145932088-5593b858-3f2e-4c44-8c0b-bcd6a90b66c4.png)

**Comment by xia-chu** [comment]
@heyingjie 你这个是纯音频流吗？ 配置文件里可以这样修改：
- 1、修改mergeWriteMS到300，这样能提升服务器分发性能。
- 2、转协议可以修改成按需转协议(hls_demand=1,rtmp_demand=1,ts_demand=1,fmp4_demand=1)，这样提升服务器收流性能。

**Comment by heyingjie** [comment]
上述测试结果中，配置项已经是`hls_demand=1,rtmp_demand=1,ts_demand=1,fmp4_demand=1`。我稍后将mergeWriteMS修改为300看看情况

**Comment by xia-chu** [comment]
你这是存音频啊

**Comment by heyingjie** [comment]
是纯音频

目前在配置文件中将mergeWriteMS修改为300，CPU使用率下降了比较多。
![image](https://user-images.githubusercontent.com/11901953/145961092-cc8a6db7-862b-4205-b007-ea5fd401979d.png)

下图是拉流端日志：
![image](https://user-images.githubusercontent.com/11901953/145961366-22d4af30-cbc2-4b06-8d6f-5dd675a349f5.png)


在拉流客户端路数上来的时候，偶尔VLC播放会出现卡顿，卡顿时日志如下：
![image](https://user-images.githubusercontent.com/11901953/145959088-84aa09ca-8f46-4a39-bf20-78125c215921.png)
![image](https://user-images.githubusercontent.com/11901953/145959357-d92f320f-87a1-4877-bff2-58b14d05d0d6.png)

**Comment by heyingjie** [comment]
刚刚监听中的VLC又静音了，还是buffer too late，会不会是PTS/DTS有点问题

**Comment by heyingjie** [comment]
明白，合并写的确可以提高性能，只是会带来延时和流量的突发。这个只能根据场景来调整了。
目前来讲性能其实已经很好了，Intel 3204 CPU 4%的CPU占用率，10000路的并发，内存也很低。
只是有一点比较困惑，还想请教一下。在目前机器CPU、网络带宽都还比较充裕的情况下，为什么路数再往上就上不去了，瓶颈可能会在哪个方面。

**Comment by heyingjie** [comment]
感谢回复。合并写的确可以提高性能，只是会带来延时和流量的突发。这个只能根据场景来调整了。
目前来讲性能其实已经很好了，Intel 3204 CPU 4%的CPU占用率，10000路的并发，内存也很低。
只是有一点比较困惑，还想请教一下。在目前机器CPU、网络带宽都还比较充裕的情况下，为什么路数再往上就上不去了，瓶颈可能会在哪个方面。

**Comment by xia-chu** [comment]
应该就是带宽瓶颈到了吧

**Comment by xia-chu** [comment]
你带宽已经跑到万兆了都

**Comment by heyingjie** [comment]
带宽还好，因为我发的是音频，单路码率只有32Kbps，所以刚刚10000路的时候网络带宽也只有400M以下。
刚刚又做了个实验，在服务器内部跑了个拉流测试，用127环回地址拉20000路。外部监听用ffplay播放是正常的。可能是交换机不行或者拉流的服务器性能不行，我看看能不能找好一点的设备来测试一下。测试好后，我回来更新测试数据。

另外，回到这个ISSUE最初的问题，在linux ulimit -n 配置的文件描述符小于实际需要用到的文件描述符的情况下，程序会出现问题。我这边也调试一下，看看能不能修改下，提升程序的健壮性。
