### ISSUE TITLE
海康NVR GB28181接入 总是session timeout[技术咨询]

### ISSUE THREAD

**Issue by nocny-x** [ZLMediaKit/ZLMediaKit#1279]
**咨询的功能模块**
- 海康NVR GB28181推流，无法播放

**咨询的具体内容和问题**
- NVR型号：海康 DS-7608N-E2
- ZLM版本：master最新
NVR型号比较老，联系海康客服升级了最新的主控包，现已支持国标平台接入。接入后可以注册到WVP，但是始终不能预览。摄像头直接接入WVP一切正常。
日志、dump文件和抓包文件已附上，麻烦大佬分析下问题出在哪里。谢谢！

dump文件始终都是空的：（dump截图不是抓包的时间）
![image](https://user-images.githubusercontent.com/2148796/146356943-2860a168-e66a-413f-a736-688dddea2b91.png)
日志：
[2021-12-16_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/7726572/2021-12-16_00.log)
抓包文件：
[play_11_failed.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/7726584/play_11_failed.zip)

**Comment by xia-chu** [comment]
172.255.1.42:30000对设备可见吗？
```bash
v=0
o=65230000090000000001 0 0 IN IP4 172.255.1.42
s=Play
c=IN IP4 172.255.1.42
t=0 0
m=video 30000 TCP/RTP/AVP 96 98 97
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
a=setup:passive
a=connection:new
y=0300001793

```

**Comment by xia-chu** [comment]
事实上 端口访问不了：
![图片](https://user-images.githubusercontent.com/11495632/146503182-0f7e6246-5b85-4165-b290-56228c93c1c9.png)

**Comment by xia-chu** [comment]
说明你防火墙没关闭，或者映射没做好

**Comment by nocny-x** [comment]
@xia-chu 是可见的，172.255.1.42这台上的防火墙都已经关闭了

**Comment by xia-chu** [comment]
> @xia-chu 是可见的，172.255.1.42这台上的防火墙都已经关闭了

抓包不会骗人啊

**Comment by nocny-x** [comment]
摄像头和NVR在同一个网络，我从摄像头直连到172.255.1.42上，是完全OK的，通过NVR就不行，说明网络映射应该是没有问题的

**Comment by xia-chu** [comment]
> @xia-chu 摄像头和NVR在同一个网络，我从摄像头直连到172.255.1.42上，是完全OK的，通过NVR就不行，说明网络映射应该是没有问题的，是不是问题出在NVR上？

不是 ICMP报文说端口不可达 那说明肯定端口没开。 有可能推流太晚了，zlm都关闭端口了，你加大下超时时间配置
