### ISSUE TITLE
[功能请求] 流缓冲状态显示

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1280]
比如ffmpeg 就会显示
frame=  189 fps=9.1 q=-1.0 size=    3401kB time=00:00:07.57 bitrate=3678.4kbits/s speed=0.365x
通过这个数据可以判断当前拉流或者推流是否正常.
zlm能否也增加一个这样的功能, 这样可以直接通过接口或者hook返回数据知道是否拉流或者推流的速度正常, 或这个功能如何实现呢?

**Comment by xia-chu** [comment]
getMediaList接口有byteSpeed的统计。
现在播放器没整个统计，你要加个这样的接口也行，我可以合并下pr，不过我本身没这个需求，所以兴趣不大

**Comment by alexliyu7352** [comment]
是的那个统计是有, 但是有些简单, 我觉得如果能类似ffmpeg这样, 可以返回一个比如缓存进度之类的. 
这样对于调试或者运营来说能大大的减少工作量, 因为看返回数据就可以知道流是否正常, 是否卡顿的原因在与拉流或者推流的带宽不足或者网络有问题.

否则客户端卡顿时, 就要先排查客户端与服务器的网络问题, 服务器与源之间的网络问题, 源的编码问题等等的了.
我可以提交这个pr, 但是我不是很清楚如何在zlm下来做这个指标, 您能告诉我下思路么?我来实现

**Comment by xia-chu** [comment]
播放器可以添加个接口来获取数据收发速度

**Comment by alexliyu7352** [comment]
速度是一方面, 另一方面如何获得zlm已经缓存了足够可以播放的帧了?或者说一个达到播放条件的进度.就像您说的播放器一样, 一般来说播放器都有两个接口, 一个是返回缓冲进度, 一个是返回是否缓冲完成可以播放, 或者是缓冲已用完开始缓冲.

我的需求就是如何在zlm中实现这个, 我通过api接口就可以获取或者hook直接反馈给上游系统, 当前缓冲进度, 是否处于缓冲状态等.其实就是一个类似wowza的质量监控分析, 我不知道如何在zlm实现.

**Comment by xia-chu** [comment]
zlm只是一个协议层面的播放器，所以不用判断缓存大小是否可以播放，只有有数据就抛到上游代码去即可。

**Comment by alexliyu7352** [comment]
明白了, 那能否加一个反馈当前除了当前速度以外还有码流率的?这样上层系统就可以进行计算了.

**Comment by xia-chu** [comment]
> , 那能否加一个反馈当前除了当前速度以外还

你可以自行加一下 我合并下pr即可

**Comment by alexliyu7352** [comment]
我正在添加, 仿照速度的接口, 但是有两个问题:
1. 现在的速度接口实际上是正压入buffer的字节数, 并不是拉流的字节数, 比如hls拉流, 在hlsplayer里面还有一个内置的缓存. 这个缓存根据定时器输入帧到下层应用才能进行统计, 但是这个缓存的就没有统计了.
2. 我已经使用平均采样法计算了实时的fps, 但是如果想要周期性的反馈服务器所有流的质量, 不能单靠实时fps与额定fps差值判断, 还应该结合拉流或者推流的速度以及码流率来计算, 这四个指标就可以反映出流的质量. 你google搜索下一些视频云就是这样统计并反馈流质量的. 但是问题就在这里, 我找不到哪里进行码流率的计算, 是否没有这个功能?能否添加下?这样对于运营管理非常方便, 可以上层系统直接对流质量进行监控并报警.
