### ISSUE TITLE
[BUG]hls拉流http协议解析有问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1294]
还是使用这个url进行测试http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8

基本上拉流过来会每隔几分钟频繁的报错, 要么就是这不是一个ts包, 要么就是这不是一个ts流.
但是使用ffmpeg播放是正常的, 使用ffmpeg拉流推流也是正常的, 当出现不是一个ts流或者不是一个ts包的时候, 查看数据一堆的/377/337/377/

应该是解析http协议出现了问题???

**Comment by alexliyu7352** [comment]
```
[h264 @ 0x7f13603b0660] error while decoding MB 88 34, bytestream -10
[h264 @ 0x7f13603b0660] concealing 4041 DC, 4041 AC, 4041 MV errors in P frame
[aac @ 0x7f13600096c0] Number of bands (41) exceeds limit (32).0/0   
[h264 @ 0x7f1360491f60] error while decoding MB 59 65, bytestream -10
[h264 @ 0x7f1360491f60] concealing 350 DC, 350 AC, 350 MV errors in P frame
[aac @ 0x7f13600096c0] Number of bands (43) exceeds limit (32).0/0   
[h264 @ 0x7f1360491f60] error while decoding MB 106 30, bytestream -5
[h264 @ 0x7f1360491f60] concealing 4503 DC, 4503 AC, 4503 MV errors in P frame
[aac @ 0x7f13600096c0] channel element 2.3 is not allocatedB f=0/0   
[h264 @ 0x7f136003d500] error while decoding MB 73 62, bytestream -6 
[h264 @ 0x7f136003d500] concealing 696 DC, 696 AC, 696 MV errors in B frame
[aac @ 0x7f13600096c0] channel element 2.4 is not allocatedB f=0/0   
[h264 @ 0x7f136035bd00] error while decoding MB 13 57, bytestream -10
[h264 @ 0x7f136035bd00] concealing 1356 DC, 1356 AC, 1356 MV errors in P frame
[http @ 0x7f1360001680] Stream ends prematurely at 309677584, should be 18446744073709551615
[http @ 0x7f1360001680] Stream ends prematurely at 309677584, should be 18446744073709551615
[h264 @ 0x7f1360028be0] error while decoding MB 42 60, bytestream -13
[h264 @ 0x7f1360028be0] concealing 967 DC, 967 AC, 967 MV errors in I frame

```

**Comment by alexliyu7352** [comment]
的确我换了一些网上找到的其他流地址, 如果使用ffplay直接播放1小时都没问题.
但是通过zlm拉流然后在播放, 几分钟或者十多分钟后, 就会出现错误导致ffplay退出,
中间zlm会报不是一个ts包或者不是ts流之类的错误.
但是如果ffmpeg拉流在推流到zlm的rtmp端口, 则正常.

**Comment by xia-chu** [comment]
这个流带宽不足吧？我播放很卡顿

**Comment by alexliyu7352** [comment]
这影响不大, 主要是解析协议的时候问题.
带宽不足应该不至于出现这样的错误

**Comment by xia-chu** [comment]
确实有bug&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2021年12月21日 20:06
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]hls拉流http协议解析有问题 (Issue #1294)

**Comment by xia-chu** [comment]
代码更新了 这个问题主要是http客户端连接复用导致的。

**Comment by xia-chu** [comment]
加个qq吧 后面方便沟通

**Comment by alexliyu7352** [comment]
您的qq就是1213642868么?
我后面加您的qq, 主要是我环境都是linux, 一直很难用qq.linux版本的qq一言难尽.所以qq用的比较少.

另外我看了您的修改, 修改的几个地方主要是为了解决同时http请求发起时上一个请求资源还没有释放的问题, 不知道我理解的对不对?

1. HlsPlayer.cpp 因为继承了httpclient, 所以增加一个变量用来确保只有一个http请求在执行.
2. httpClient主要就是在onConnect里面增加了一个_parser.Clear();, 是由于这个没有及时清理释放导致的问题?

**Comment by xia-chu** [comment]
1、HlsPlayer.cpp 因为继承了httpclient, 所以增加一个_waiting_response变量用来确保在上次请求m3u8还未返回前不要发送新的请求，这就是http的队头阻塞问题。
2、httpClient主要是链接复用时 直接调用onConnect时，在派生类中重建了ssl对象，导致tcp未重建，但是ssl重建从而异常。

**Comment by alexliyu7352** [comment]
貌似还是有问题, 
还是测试这个url
http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8

几分钟拉流后就会报错.

```
2021-12-23 21:01:57.254 E MediaServer[3873-event poller 0] Socket.cpp:301 onRead | 触发socket on_read事件时,捕获到异常:Assertion failed: (pes->pkt.size == pes->len), function pes_packet, file /home/alex/CLionProjects/zlm/3rdpart/media-server/libmpeg/source/mpeg-packet.c, line 161.
2021-12-23 21:01:57.257 W MediaServer[3873-event poller 0] HttpTSPlayer.cpp:48 onResponseBody | 可能不是http-ts流
2021-12-23 21:01:57.257 W MediaServer[3873-event poller 0] TSDecoder.cpp:24 onRecvHeader | 不是ts包:71 214
```

**Comment by xia-chu** [comment]
ts下载如果未下载完毕就中断并下载下一个切片 那么就会导致ts数据丢失部分
