### ISSUE TITLE
[BUG]I帧会丢帧

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1296]
比如这个示例视频, ffmpeg播放或者直接切片都正常, 但是http拉流或者ffmpeg拉流在推流给zlm都无法播放.
zlm大量日志显示dts回退, 播放画面是绿屏的. 貌似识别不出I帧, 因此大量丢帧.

https://github.com/alexliyu7352/alexliyu7352.github.io/blob/main/283.ts?raw=true

**Comment by xia-chu** [comment]
你是什么协议推流给zlm？

**Comment by alexliyu7352** [comment]
rtmp

ffmpeg  -probesize 5000000 -analyzeduration 5000000 -re -i ./283.ts -c:v copy -c:a copy -f flv rtmp://127.0.0.1/proxy/test

**Comment by alexliyu7352** [comment]
老大, 帮忙看看怎么办?为什么会出现这样的问题

**Comment by xiongguangjie** [comment]
你这个流很特殊，有一个sps ，两个pps （是合法的），ZLM只会记录一个pps 导致播放rtsp 出错

**Comment by xiongguangjie** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/tree/feature/h264_multi_pps 用这个分支，适配了下rtsp 播放的情况，没有完全解决这种问题

**Comment by alexliyu7352** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/tree/feature/h264_multi_pps 用这个分支，适配了下rtsp 播放的情况，没有完全解决这种问题

谢谢大佬, 我试试看

**Comment by alexliyu7352** [comment]
我用ts流输出一样会有问题
