### ISSUE TITLE
编码格式RAW

### ISSUE THREAD

**Issue by Smallkserver** [ZLMediaKit/ZLMediaKit#1299]
虽然可以要求用户改H264或者H265编码来避免这个问题，但是还是好奇是否方便做兼容。
![1640138795536_13088A44-798C-4d35-9321-D3CAC9643D48](https://user-images.githubusercontent.com/41426631/147022966-07492923-bda4-4a89-af75-f12ad5d8b251.png)

 图片中是海康平台展示的编码格式RAW，推流到ZLM似乎识别不到格式，貌似被过滤掉了，ffplay显示No such stream或者404

**Comment by xia-chu** [comment]
什么是raw格式？rtsp sdp是多少？

**Comment by Smallkserver** [comment]
这个设备是海康平台级联上来的，sip下发的
a=rtpmap:96 PS/90000
a=rtpmap:98 H264/90000
a=rtpmap:97 MPEG4/90000
能收到流注册
您说的这个rtsp sdp指的是什么

**Comment by xia-chu** [comment]
哦 我以为你是rtsp推流。
ps里面负载应该就是264，请你粘贴上zlm的日志，另外提供下zlm dump出的rtp文件

**Comment by Smallkserver** [comment]
好的，业主那边网络做迁移，现在设备不在线，我明天贴一下日志和dump

**Comment by Smallkserver** [comment]
[2021-12-23_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/7766127/2021-12-23_00.log)

注册到注销阶段全部log
streamid: gb_play_33078200002000001212_33078256581314000027

[dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/7766134/dump.zip)

**Comment by xia-chu** [comment]
这个流是大华的专有格式，不是标准的ps流

**Comment by xia-chu** [comment]
18:39:53 对方已成功接收文件“gb_play_33078200002000001212_33078256581314000027.mp2”

- 老陈  18:47:42
这个文件看着就是普通264码流，没有ps封装。

- 老陈  18:48:14
![图片](https://user-images.githubusercontent.com/11495632/147350303-e4a44134-787d-43ba-af90-affc27e7ebed.png)

- 老陈  18:48:25
没有找到ps起始码

- 子悦  18:49:13
哦哦 好的  我都没注意到这点[表情]

- 子悦  18:49:20
ffmpeg能播放

- 子悦  18:49:35
ffmpeg能播放 "
好像我看见711了

- 老陈  18:50:44
![图片](https://user-images.githubusercontent.com/11495632/147350265-bc16e465-06ec-4019-af31-0e79932cde86.png)

- 老陈  18:51:02
ffmpeg 居然识别出dahua文件封装了。

- 老陈  18:52:24
![图片](https://user-images.githubusercontent.com/11495632/147350275-29234e25-4552-4651-a6f2-4f47a5936f3f.png)

- 老陈  18:52:29
17年加的。

- 老陈  18:53:41
![图片](https://user-images.githubusercontent.com/11495632/147350334-81a1d8b7-dab6-45c8-9325-876d28dce506.png)
整个文件没有一行注释。

- 老陈  18:58:36
![图片](https://user-images.githubusercontent.com/11495632/147350351-ebf0ce8f-b156-49f3-9d07-c98baaa86ae2.png)

- 老陈  18:59:21
dahua私有格式，不是ps

- 子悦  19:03:30
估计不是国标

- 老陈  19:03:51
这种肯定不是国标流了额。

**Comment by xia-chu** [comment]
要支持这种格式需要移植下大华的解复用器

**Comment by Smallkserver** [comment]
好的，大佬辛苦了
