### ISSUE TITLE
[功能请求] 断连续推播放器不断开

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1300]
目前播放时候, 是通过MediaSource进行播放读取和压入.
Ringbuffer中就存有一个GOP.
但是有时候会遇到一个问题就是网络抖动.根据您现在的机制是Ringbuffer有数据压入, 另一边才会继续读取.
一旦上游拉流或者接收推流断开, 那么客户端也仅仅只能播放几秒钟.
我想是否可以增加一个配置, 就是可以增加一个延时时间, 或者说缓存时间或者缓存大小. 
这样在网络抖动或者上游网络断开时, 下游会继续播放一段时间, 这期间也许上游的网络问题会解决, 比如已经重新链接了.
那么对于终端用户来说体验比较好, 因为感觉不到由于上游推流或者拉流断开重连造成的卡顿出现.
毕竟对于一般的应用来说, 一个zlm实例可能并不会拉非常多的流, 所以多消耗一些内存其实并无关系.
重要的是客户端用户体验好,才是关键.

我自己尝试进行修改, 主要是修改Ringbuffer和调用的mediaSource, 一方面是扩大了Ringbuffer的容量, 另一方面取消掉了只存储一个gop的限制. 但是我发现结果并没有改善, 当上游断开后, 客户端几秒后就会画面停止断开.

后来我研究了下您的代码发现, 您的ringbuffer如果没有新数据压入, 是不会触发发送新数据给客户端的, 没错吧?

能否增加一个配置, 可以起到这样的缓存的效果?

**Comment by xiongguangjie** [comment]
断开就认为流断开，播放端也会断开，你这种需要在播放器端去做重连之类的

**Comment by alexliyu7352** [comment]
你没有明白我的意思, 我的意思是重连应该是zlm与上游重连, 或者是上游的推送者重新推送流给zlm, 但是不应该要求客户端与zlm重连, 你没有办法控制下游的客户端行为与代码, 而且就算重连了, 目前ringbuffer只缓冲一个gop, 没有新数据压入, 也只是返回这一个. 所以就算客户端重连了, 仍旧是会继续播放重复的画面.

我的想法是是否可以增加一个配置或者机制就是让能主动的缓存一段时间的流, 比如10秒中.

这样发生断流时客户端不会因为读不到流而发生退出重连, 画面卡顿.
因为至少有10秒的播放时间可以让zlm与上游重新建立通信.
只要在这10秒内重新建立通信, 那么客户端就可以无感之这种抖动.

这个wowoza之类的服务器都有这种设计.

**Comment by HammerZhao** [comment]
你的用法是 用zlmediakit 从一个服务A 拉流 然后另外一个播放器 就是从zlmediakit 进行订阅播放，如果这时候拉流的服务连接被切断了 那就直接把订阅全部切断了么？

**Comment by alexliyu7352** [comment]
> 你的用法是 用zlmediakit 从一个服务A 拉流 然后另外一个播放器 就是从zlmediakit 进行订阅播放，如果这时候拉流的服务连接被切断了 那就直接把订阅全部切断了么？

现在的zlm逻辑是这样的, 所以我建议修改, 上游断开, 下游播放器不应该断开, 除非缓存消耗完毕.
那这个缓存时间应该是可以配置的才对.

**Comment by alexliyu7352** [comment]
其实这个功能需求和百度的这个服务器功能很类似
https://github.com/brpc/media-server/blob/master/docs/cn/frame_queue.md


帧队列缓冲（frame queue buffer）

在media-server中，有两种控制每条流的音视频帧缓冲的方法。
min_cache_length(ms)

返回给新用户的第一帧是media-server的帧缓冲中，与当前最新的帧相隔大于min_cache_length（单位毫秒）时间长度的所有音视频帧中最新的关键帧。例如，如果这个值设置为2000ms，那么media-server会返回给新用户2000ms前的第一个关键帧开始的所有数据，这个缓冲队列可以用来缓解卡顿。
-max_cache_length(ms)

返回给新用户的第一帧是media-server的帧缓冲中，与当前最新的帧相隔小于max_cache_length（单位毫秒）时间长度的所有音视频帧中最老的关键帧。例如，如果这个值设置为2000ms，那么media-server会返回给新用户2000ms内的最老的关键帧开始的所有数据，这个缓冲队列可以用来控制最大延迟。

默认情况下，media-server会使用min cache来作为缓冲策略，可以用-min_buffering_ms来为所有的流设置默认缓冲大小。
帧指示（FrameIndicator）

在不同的客户场景下，希望采取不同的缓存策略，media-server提供了如下两种帧指示来为每条流单独设置min_cache_length和max_cache_length。
FrameIndicator::BY_USING_LATEST

总是返回最新的帧。这个Indicator常用在实时性较高的场合中，例如互动直播。注意，当启用时，由于返回给客户端的第一帧不一定是关键帧，所以会出现小间隔的黑屏现象。
FrameIndicator::BY_CONFIG

根据配置设置cache_length，这个配置可以由中心业务服务器统一下发给media-server。

**Comment by xia-chu** [comment]
> 目前播放时候, 是通过MediaSource进行播放读取和压入. Ringbuffer中就存有一个GOP. 但是有时候会遇到一个问题就是网络抖动.根据您现在的机制是Ringbuffer有数据压入, 另一边才会继续读取. 一旦上游拉流或者接收推流断开, 那么客户端也仅仅只能播放几秒钟. 我想是否可以增加一个配置, 就是可以增加一个延时时间, 或者说缓存时间或者缓存大小. 这样在网络抖动或者上游网络断开时, 下游会继续播放一段时间, 这期间也许上游的网络问题会解决, 比如已经重新链接了. 那么对于终端用户来说体验比较好, 因为感觉不到由于上游推流或者拉流断开重连造成的卡顿出现. 毕竟对于一般的应用来说, 一个zlm实例可能并不会拉非常多的流, 所以多消耗一些内存其实并无关系. 重要的是客户端用户体验好,才是关键.
> 
> 我自己尝试进行修改, 主要是修改Ringbuffer和调用的mediaSource, 一方面是扩大了Ringbuffer的容量, 另一方面取消掉了只存储一个gop的限制. 但是我发现结果并没有改善, 当上游断开后, 客户端几秒后就会画面停止断开.
> 
> 后来我研究了下您的代码发现, 您的ringbuffer如果没有新数据压入, 是不会触发发送新数据给客户端的, 没错吧?
> 
> 能否增加一个配置, 可以起到这样的缓存的效果?

目前zlm的数据分发(`RingBuffer`)是立即的、按序的，断开事件(`onDeatch`)也会在数据事件（`onRead`）触发后再触发。
也就是RingBuffer不存在数据丢失的问题，推流器在断开后，其他播放器都能收到它断开前发送的最后一个包。

你说的，推流器断开后保留播放器不断开的特性是可以实现的，很多流媒体服务器也是这么做的，包括srs。
但是我在issue(#1240) 就提过原因了，在此不再复述

**Comment by alexliyu7352** [comment]
我看到大神在 #1240 里面写的原因了.
但是我觉得作为一个工业级流媒体服务器容错还是必须要考虑的.毕竟很多的网络因素是不可控的, 容错很有必要.
很多时候上游的流和下游的客户端都往往是没办法控制的, 唯一能做的只能是尽量增加服务器的容错.
因为大多的产品, 你无法控制客户端, 这些客户端往往都是第三方开发的.而上游的拉流和推流也很多情况下无法控制.
就比如推流很多用obs, 你总不能自己修改obs的代码出一个版本吧?那对于很多zlm的用户来说是无法负担的.而客户端的问题更麻烦, 有些傻逼客户端一旦遇到断流直接就报错了, 连重连都不会. 但是实际情况就是你没有办法要求客户更改其客户端, 或者要求下游的客户端开发商去做相应的处理.比如阿里的那个播放器, 我觉得我们都没资格要求阿里的团队去改他们的播放器.他们也不会听.但是客户如果选择了使用呢?怎么办?
其实就像那个issues里面说的, 不用完全改变, 但是最好能做一个功能选项, 对于有这个需求的人来说可以启用, 对于无需求的人来说可以保持不变.

```
1、重新推流了，时间戳对齐不了，服务器要重新处理时间戳，这个其实zlm有相关代码实现，也不算难。
2、重新推流了，视频编解码信息可能会变，这个怎么处理？还是干脆不处理？我感觉直接没法处理，宽高、profile都变了或多条或少条track都由他去吧，反正谁使用该功能，谁就负责保持不变。
3、重新推流容忍时间为多少？1分钟？10分钟？1个小时？播放器也不会等你这么久啊，那就是设置1分钟内吧，推流断开了，zlm不去掐断播放器，让播放器主动超时去断开吧（目前srs就这样的），但是这样好像会导致stream数太多时，对象内存得不到及时清理，我看有人反馈过srs这个问题导致的内存泄露。
```
 
您说的这几个原因, 我觉得其实可以折中处理.
1. 时间戳问题,  这个肯定需要处理的,  您也说过zlm有相关代码实现. 如果您没空做, 是否可以给我讲解下如何处理?我来实现并提交pr?
2. 这个其实不用考虑, 一般网络抖动导致断开重连后, 这些是基本上不会变的.如果变了就直接算作新流就行了.没必要有复杂的处理逻辑.
3. 容忍时间问题, 我觉得就和我提的这个issues有关了. 实际上我看到一些诸如wowza的流媒体服务器, 它的处理就是上游断开不影响下游, 也就是上游断开了, 保留播放器不断开, 持续不断的消耗环形队列里面的帧, 直到一个阀值, 比如只剩最后一个gop, 或者剩最后几秒的数据包.然后就有两个逻辑了, 一个是重复循环的发送最后的这些数据包. 另外一个就是插入预设的视频发送.比如广告?或者是一个当前流不稳定请耐心等待的视频?直到所有的客户端都断开链接, 在清理上游链接, 断开推流或者拉流的通道.总之处理方式就是上游断开不影响下游输出.让客户端可以无感.我觉得这样并不会造成你说的内存得不到及时清理.因为也就保留了最后一个gop或者是最后几秒的数据包, 这就算几百个视频流也没有多少的.毕竟现在做流媒体服务器的, 有个几十GB, 上百GB内存是很正常的事情.但是对于客户体验, 那就提高了非常多了.
4. "上次推流线程是A，下次是B", 线程切换和安全, 这个到是一个很麻烦的处理. 说实话我到现在也不知道如何能切换到指定线程去.或者新开一个线程, 使用您的接口, 切换到什么线程都是自动判断的, 除非传递poll过去, 使用同样的poll.


综上所述, 我觉得其实就做几个方面的工作就可以, 当然前提设置一个选项并开启才执行以下的逻辑
1. 当发生上游断开事件时候, 播放器缓存会继续的压入到ringbuffer中, 而客户端也会从其继续读, 而不是只是读取最后一个数据包就完了.
2. 当ringbuffer剩余的数据达到阀值, 比如只剩一个gop, 或者剩10秒中的缓冲时, 可根据配置重复循环读取这一部分的数据.以此达到客户端不断开的目的, 或者配置一个默认视频, 比如广告或者其他的, 然后从中读取流并输出给客户端. 
2. 判断当前是否还有客户端链接, 如果没有客户端就可以断开ringbuffer以及上游链接了.
3. 如果这时候拉流或者推流恢复了, 那么就判断是否编码改变, 是否需要当作新流处理.如果不需要就做时间戳的对齐, 然后开始解码压入ringbuff.

当然其实你说的这个issues提到的只是我这个issues提到的其中一个部分, 另外一个部分您可能忽略了.就是我说的通过差异化下发数据包而避免网络抖动造成的影响.
这个逻辑我觉得实现起来应该更简单才对, 您现在不是已经有一个选项就是重新拉流时, 不清除之前的缓存数据么?那么只要做到设置一个延时参数就可以了, 并且实现上述的第一点, 当上游断开时, 不断开播放器, 播放器会继续从ringbuffer中读取数据直到ringbuff耗尽为止.
通过延时参数来决定ringbuffer的最大大小, 然后发送给每个客户端的数据都是从最老的数据包开始, 这样比如设置成10秒, 那么每个客户端新接入的时候都是从播放10秒前的流开始. 这样假设上游断开了, 那么只要在10秒内恢复, 客户端是没有感知的.
这就有了一个很好的容错时间了.也就是我们就有了10秒的容错时间.而当这10秒的数据包消耗完毕后, 如果ringbuffer已经空了, 那么该断开就断开好了.

其实输出hls就能解决这个容错的问题了, 因为hls本身就有延时, 这个延时正好可以用来给上游重连.但是可惜的是并不是所有的用户都会在客户端使用hls, 有些更多的是使用rtmp或者flv之类的.

所以,大神, 你看看如果要实现这样的, 应该怎么做?您如果没有时间, 请告诉我大改的修改逻辑以及相关的修改地方, 我来修改.
当然如果您能修改, 那么就太好了!

**Comment by xia-chu** [comment]
考虑下实现下 以最小代价实现

**Comment by xia-chu** [comment]
不过 只能实现rtsp/rtmp推流的。

**Comment by xia-chu** [comment]
rtmp、rtsp已经支持断连续推功能

**Comment by alexliyu7352** [comment]
请问那么hls什么时候支持?

夏楚 ***@***.***> 于2022年1月10日周一 16:46写道：

**Comment by xia-chu** [comment]
所有播放协议都支持啊，我说的是推流协议支持续推，这些推流参数的url 都不会断开

**Comment by xia-chu** [comment]
zlm也就支持rtsp/rtmp/webrtc推流，这3者目前都支持断连续推了

**Comment by alexliyu7352** [comment]
拉流也要支持阿, 上游断开, 播放器不断.

夏楚 ***@***.***> 于2022年1月11日周二 10:56写道：

**Comment by xia-chu** [comment]
> 拉流也要支持阿, 上游断开, 播放器不断.

不是已经支持了吗？

**Comment by alexliyu7352** [comment]
我是说hls或者ts拉流, 我看代码好像没有这块的阿?
还有就是播放好像播放器不断, 只有rtmp/webrtc不断, http的客户端播放器好像没有看到处理阿?

另外, 有一个疑问请教下
 ```
if (_push_src && continue_push_ms) {
        //取消所有权
        _push_src_ownership = nullptr;
        //延时10秒注销流
        auto push_src = std::move(_push_src);
        getPoller()->doDelayTask(continue_push_ms, [push_src]() { return 0; });
    }
```
我看你的延时处理都是这段代码, 意思是保证push_src10秒内不会被析构达到延时的目的么?

**Comment by xia-chu** [comment]
对 在延时销毁期间 如果有其他推流客户端推流 那么可以复用它

**Comment by alexliyu7352** [comment]
学到了, 大神不愧是大神, 好聪明的用法!
另外, 我问的hls或者ts拉流, 如何保证上游中断时, 下游播放器断开也有一个延时呢?
比如拉hls转ts或者拉ts转hls.

**Comment by xia-chu** [comment]
这篇文章有点介绍：https://github.com/ZLMediaKit/ZLMediaKit/wiki/ZLMediakit%E7%8B%AC%E5%AE%B6%E7%89%B9%E6%80%A7%E4%BB%8B%E7%BB%8D

**Comment by xia-chu** [comment]
> 学到了, 大神不愧是大神, 好聪明的用法! 另外, 我问的hls或者ts拉流, 如何保证上游中断时, 下游播放器断开也有一个延时呢? 比如拉hls转ts或者拉ts转hls.

resetWhenRePlay参数就不会导致注销啊

**Comment by alexliyu7352** [comment]
明白了.感谢

夏楚 ***@***.***> 于2022年1月13日周四 20:23写道：
