### ISSUE TITLE
[BUG]不使能OpenSSL，编译报错

### ISSUE THREAD

**Issue by Leonard76152** [ZLMediaKit/ZLMediaKit#1301]
**bug现象**
```
[ 82%] Building CXX object api/CMakeFiles/mk_api.dir/source/mk_h264_splitter.cpp.o
/usr/bin/ld: ../../release/linux/Debug/libzlmediakit.a(RtmpProtocol.cpp.o): in function `mediakit::RtmpProtocol::startClientSession(std::function<void ()> const&)':
/home/lhz/zlm/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp:293: undefined reference to `mediakit::RtmpHandshake::create_complex_c0c1()'
[ 82%] Building CXX object api/CMakeFiles/mk_api.dir/source/mk_httpclient.cpp.o
```

**bug产生时的使用场景**
最新代码编译。

**bug是否可以复现，怎么复现**
可以复现。

**zlm代码git commit hash值**
commit 4e01c298339c595f8808fa2c49688255f10c2336 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: ziyue <1213642868@qq.com>
Date:   Wed Dec 22 22:20:28 2021 +0800

    Rtmp: 优化复杂握手c0c1生成算法性能

**操作系统环境**
阿里云服务器，CentOS7 64位

**Comment by xia-chu** [comment]
make clean && make -j8 试试

**Comment by Gowa2017** [comment]
同样的问题。

**Comment by moloach** [comment]
windows下编译同样的问题

**Comment by Gowa2017** [comment]
看一下 cmake 提示 是不是没有找到 ssl 库。


我搞定了

**Comment by Leonard76152** [comment]
产生的条件，是没有找到ssl库。cmake执行：
`openssl未找到，rtmp将不支持flash播放器，https/wss/rtsps/rtmps也将失效`
问题是：没有安装OpenSSL，就不能正常编译吗？应该不是吧。我推测，是不是新加的代码，在处理是否开启OpenSSL这块有些问题。

**Comment by xia-chu** [comment]
哦 是的 应该是这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Leonard76152 ***@***.***&gt;
发送时间: 2021年12月25日 13:57
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]不使能OpenSSL，编译报错 (Issue #1301)





 
产生的条件，是没有找到ssl库。cmake执行：
 openssl未找到，rtmp将不支持flash播放器，https/wss/rtsps/rtmps也将失效
 问题是：没有安装OpenSSL，就不能正常编译吗？应该不是吧。我推测，是不是新加的代码，在处理是否开启OpenSSL这块有些问题。

**Comment by xia-chu** [comment]
修复了
