### ISSUE TITLE
[技术咨询]关于zlmediakit建立rtsp服务后ffmpeg拉流无法获得codec parameters的现象

### ISSUE THREAD

**Issue by NagatoRailgun** [ZLMediaKit/ZLMediaKit#1302]
你好，请问大佬，我这边尝试使用zlmediakit建立rtsp服务，方式如下：

```c++
void RtspService::startServer(LibRtspServerContext ncontext){
    context = ncontext;
    cJSON* obj = cJSON_Parse(context.data);
    cJSON* streams = cJSON_GetObjectItem(obj,"streams");
    int port = cJSON_GetObjectItem(obj, "port")->valueint;
    string ip = cJSON_GetObjectItem(obj, "ip")->valuestring;
    
    //init zlmediakit
    mk_config config;
    memset(&config,0,sizeof(config));
    config.thread_num = 4;
    mk_env_init(&config);
    if(mk_rtsp_server_start(port,false)==0){
        return;
    }
    //init stream
    for(int i = 0;i<cJSON_GetArraySize(streams);i++){
        cJSON * item = cJSON_GetArrayItem(streams,i);
        string name = cJSON_GetObjectItem(item, "name")->valuestring;
        int width = cJSON_GetObjectItem(item, "width")->valueint;
        int height = cJSON_GetObjectItem(item, "height")->valueint;
        
        StreamItem * stream = new StreamItem();
        memset(stream->name,0,sizeof(stream->name));
        memcpy(stream->name,name.c_str(),name.size());
        string url = "rtsp://"+ip+":"+to_string(port)+"/live/"+name;
        memset(stream->url,0,sizeof(stream->url));
        memcpy(stream->url,url.c_str(),url.size());
        
        stream->media = mk_media_create("__defaultVhost__","live",name.c_str(),0,0,0);
        mk_media_init_video(stream->media,0,width,height,15);
        mk_media_init_complete(stream->media);
        mk_media_set_on_regist(stream->media,[](void * userData, mk_media_source sender, int regist){
            StreamItem *ctx = reinterpret_cast<StreamItem *> (userData);
            const char *schema = mk_media_source_get_schema(sender);
            if (strncmp(schema, ctx->url, strlen(schema)) == 0) {
                if (regist) {
                    ctx->pusher = mk_pusher_create_src(sender);
                    mk_pusher_publish(ctx->pusher, ctx->url);
                }
            }
        },stream);
        streamList.push_back(stream);
    }
    initSuccess(serverID);
}
```
//================================================
![企业微信截图_20211223170413](https://user-images.githubusercontent.com/44455914/147216499-cd525aaf-ea60-4827-b383-24c8284eb572.png)
我在mk_media_init_video中设置了视频宽高，并且在vlc上能够获取到流媒体信息（不确定vlc是根据流信息还是帧信息显示的），然后我尝试在自己的程序中通过ffmpeg标准方法avformat_open_input然后avformat_find_stream_info获取流媒体信息，如图所示
![企业微信截图_20211223170819](https://user-images.githubusercontent.com/44455914/147216705-18eeaf23-98a6-41b7-b7d4-e128bb609057.png)
在ffmpeg上报出了Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (12000000) and 'probesize' (204800) options的错误，使我无法得到codeccontext，从而无法正常解码。该方法在其他rtsp上能够正常获得解码器信息，是否是我在使用zlmediakit建立服务时缺少了必要的步骤造成发送信息缺失？我尝试根据ffmpeg提示去放大analyzeduration与probesize或取消设置后也无法正常获得。能向您请教一下吗？

**Comment by NagatoRailgun** [comment]
我在一个rtsp服务上建立了两个media对象，以实现rtsp://ip:554/live/video1、rtsp://ip:554/live/video2两个媒体分别输出的效果，是否这个设计会影响到对流信息的获取？

**Comment by xiongguangjie** [comment]
你直接用摄像头的rtsp 也是这样，建议你使用 rtsp tcp ,ffmpeg 需要分析一段流才能知道视频相关信息，你需要调用avformat_find_stream_info()之类的接口

**Comment by NagatoRailgun** [comment]
> 你直接用摄像头的rtsp也是这样，建议你使用rtsp tcp ,ffmpeg需要分析一段流才能视频相关信息，你需要调用avformat_find_stream_info()之类的接口

我在ffmepeg客户端的确是使用了avformat_find_stream_info，在先前我们使用happytime建立的rtsp上使用该方式可以获得码流的配置信息，但同样的方式在这里会出现ffmpeg的报错。比较奇怪。

//ffmpeg客户端代码如下 
 qDebug()<<"[ASJPPSAPI]"<<"avformat_open_input:"<<stream.path;
    stream.formatContext = avformat_alloc_context();
    stream.formatContext->probesize = 200 * 1024;
    stream.formatContext->max_analyze_duration = 12 * AV_TIME_BASE;
    stream.formatContext->flags |= AVFMT_FLAG_NONBLOCK ;
    AVDictionary * pAvdic = nullptr;
    av_dict_set(&pAvdic, "rtsp_transport", "tcp", 0);
    av_dict_set(&pAvdic, "stimeout", "10000000", 0);
    bRet = avformat_open_input(&stream.formatContext, stream.path.toUtf8().data(),nullptr, &pAvdic);
    av_dict_free(&pAvdic);
    if (bRet < 0) {
        char error[100];
        avformat_close_input(&stream.formatContext);
        av_make_error_string(error,100,bRet);
        qDebug()<<"[ASJPPSAPI]"<<stream.path<<" open fail:"<<QString::number(bRet)<<","<<QString(error);
        if(stream.redoTime>0){
            return false;
        }
    }
    if(bRet<0){
        avformat_free_context(stream.formatContext);
        emit initFailMsg(APPSAPI_ERROR_STREAM_CANT_CONNCET,bRet,"init rtsp error");
        return true;
    }
    qDebug()<<"[ASJPPSAPI]"<<stream.path<<" open success";
    av_dump_format(stream.formatContext, 0, stream.path.toUtf8().data(), 0);
    //获取视频流信息
    bRet = avformat_find_stream_info(stream.formatContext, nullptr);/*在这里我去获取码流配置信息*/
    if (bRet < 0) {
        emit initFailMsg(APPSAPI_ERROR_STREAM_NO_INFO,bRet,"init rtsp error");
        avformat_close_input(&stream.formatContext);
        return true;
    }
/*后面是对音视频流分别获取codecContext*/

**Comment by xiongguangjie** [comment]
> > 你直接用摄像头的rtsp也是这样，建议你使用rtsp tcp ,ffmpeg需要分析一段流才能视频相关信息，你需要调用avformat_find_stream_info()之类的接口
> 
> 我在ffmepeg客户端的确是使用了avformat_find_stream_info，在先前我们使用happytime建立的rtsp上使用该方式可以获得码流的配置信息，但同样的方式在这里会出现ffmpeg的报错。比较奇怪。
> 
> //ffmpeg客户端代码如下 qDebug()<<"[ASJPPSAPI]"<<"avformat_open_input:"<<stream.path; stream.formatContext = avformat_alloc_context(); stream.formatContext->probesize = 200 * 1024; stream.formatContext->max_analyze_duration = 12 * AV_TIME_BASE; stream.formatContext->flags |= AVFMT_FLAG_NONBLOCK ; AVDictionary * pAvdic = nullptr; av_dict_set(&pAvdic, "rtsp_transport", "tcp", 0); av_dict_set(&pAvdic, "stimeout", "10000000", 0); bRet = avformat_open_input(&stream.formatContext, stream.path.toUtf8().data(),nullptr, &pAvdic); av_dict_free(&pAvdic); if (bRet < 0) { char error[100]; avformat_close_input(&stream.formatContext); av_make_error_string(error,100,bRet); qDebug()<<"[ASJPPSAPI]"<<stream.path<<" open fail:"<<QString::number(bRet)<<","<<QString(error); if(stream.redoTime>0){ return false; } } if(bRet<0){ avformat_free_context(stream.formatContext); emit initFailMsg(APPSAPI_ERROR_STREAM_CANT_CONNCET,bRet,"init rtsp error"); return true; } qDebug()<<"[ASJPPSAPI]"<<stream.path<<" open success"; av_dump_format(stream.formatContext, 0, stream.path.toUtf8().data(), 0); //获取视频流信息 bRet = avformat_find_stream_info(stream.formatContext, nullptr);/_在这里我去获取码流配置信息_/ if (bRet < 0) { emit initFailMsg(APPSAPI_ERROR_STREAM_NO_INFO,bRet,"init rtsp error"); avformat_close_input(&stream.formatContext); return true; } /_后面是对音视频流分别获取codecContext_/

我使用ffplay 测试过是没问题的，以前我我记得是可以的

**Comment by xiongguangjie** [comment]
你 probesize  与 max_analyze_duration  与 flags 都不要乱设置

**Comment by xia-chu** [comment]
如果ffplay能获取宽高 但是你的代码却不能 那么大概率是你代码有bug

**Comment by xia-chu** [comment]
zlm的c sdk也提供拉流功能，你可以考虑下，性能比ffmpeg好

**Comment by NagatoRailgun** [comment]
> 如果ffplay能获取宽高 但是你的代码却不能 那么大概率是你代码有bug

我将上述提到的三个定制给注释了，
stream.formatContext->probesize = 200 * 1024;
stream.formatContext->max_analyze_duration = 12 * AV_TIME_BASE;
stream.formatContext->flags |= AVFMT_FLAG_NONBLOCK ;

ffmpeg会采用默认值，然后报出同一个错误
[rtsp @ 31bf7fc0] Could not find codec parameters for stream 0 (Video: h264, none): unspecified size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options

我在建立rtsp部分是否有问题？如果没有的话，我看一下能否从客户端着手修改。比较难以定位的是这套ffmpeg代码对于mp4、avi文件和之前的happytime的获取都表现正常，所以我才想确认一下是不是建立rtsp的时候必须添加什么步骤才能发出这个配置信息。

**Comment by NagatoRailgun** [comment]
> zlm的c sdk也提供拉流功能，你可以考虑下，性能比ffmpeg好

后面会考虑尝试，^0^目前在设计给摄像头使用的编码库，对运行资源的占用要求较高，想先由少到多逐步扩展。先引用zlm进行功能验证，后面再尝试给领导去推荐。在rtsp使用上确实比live555人性化很多。

**Comment by NagatoRailgun** [comment]
我们这边尝试了两种版本的ffmpeg案例

> zlm的c sdk也提供拉流功能，你可以考虑下，性能比ffmpeg好

经过我这边对以上开流配置的逐条注释后，目前可以确认当ffmpeg开流时配置av_dict_set(&pAvdic, "rtsp_transport", "tcp", 0);后将必然发生无法获取码流信息的现象，注释此条目后，能够正确获得解码器信息，怀疑可能与tcp配置相关。
![企业微信截图_20211224170019](https://user-images.githubusercontent.com/44455914/147337919-ccf88738-304b-400e-84bb-5a426d2e2d65.png)

**Comment by xia-chu** [comment]
> 如果ffplay能获取宽高 但是你的代码却不能 那么大概率是你代码有bug

还是上面这句话 issue我先关闭了
