### ISSUE TITLE
[BUG]hls拉流http解析问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1304]
频繁出现错误日志, 提示不是ts包, 使用最新代码仍旧是这个问题. 花了很长时间排查, 有可能问题出现在解析的部分.
具体流程如下:
```
void HlsPlayer::onPacket_l(const char *data, size_t len){
    _segment.input(data,len);
}
```
程序走到这一步的时候, len是5246,

```
void HttpRequestSplitter::input(const char *data,size_t len) {
    if (remainDataSize() > kMaxCacheSize) {
        //缓存太多数据无法处理则上抛异常
        throw std::out_of_range("remain data size is too huge:" + to_string(remainDataSize()));
    }
    const char *ptr = data;
    if(!_remain_data.empty()){
        _remain_data.append(data,len);
        data = ptr = _remain_data.data();
        len = _remain_data.size();
    }
```

接下去程序运行到这里后,  len = _remain_data.size();这句代码返回的len却变成了5376, 然后在接着

```
//_content_len == 0，这是请求头
        const char *header_ptr = ptr;
        ssize_t header_size = index - ptr;
```
这里算出来的header_size = 318了, 318正好是188+130, 而130正好是5376-5246,
接下去就会报错不是ts包, 因为header_size不正确了.

**Comment by alexliyu7352** [comment]
这真的很奇怪, 理论上就算_remain_data数据没有消耗完, 剩余个100来字节的数据不够一个ts包的, 但是接下来新数据包压入后应该会紧跟着补足这个ts包, 但是实际上并没有. 不知道哪里有问题, 导致总是会有着几百个字节的数据.

ffmpeg解码这个拉流的也会同样报错

```
[h264 @ 0x7f7028079720] error while decoding MB 95 42, bytestream -14
[h264 @ 0x7f7028079720] concealing 3074 DC, 3074 AC, 3074 MV errors in P frame
[h264 @ 0x7f702847a140] error while decoding MB 99 34, bytestream -8 
[h264 @ 0x7f702847a140] concealing 4030 DC, 4030 AC, 4030 MV errors in P frame
[aac @ 0x7f7028012180] Multiple frames in a packet.sq=    0B f=0/0   
[aac @ 0x7f7028012180] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 0x7f7028012180] Inconsistent channel configuration.
[aac @ 0x7f7028012180] get_buffer() failed
[h264 @ 0x7f702837c520] error while decoding MB 56 50, bytestream -6 
[h264 @ 0x7f702837c520] concealing 2153 DC, 2153 AC, 2153 MV errors in B frame
[aac @ 0x7f7028012180] Number of bands (40) exceeds limit (32).0/0 
```

测试地址依旧是http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8
老大你看看

**Comment by wujincheng2333** [comment]
> 

说明你的 TS 发包发多了。多次响应的 TS 应该不会合并。所以单次的 http响应体必须是 188的倍数

**Comment by xia-chu** [comment]
这个问题是zlmediakit的bug



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wujincheng2333 ***@***.***&gt;
发送时间: 2021年12月24日 11:58
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]hls拉流http解析问题 (Issue #1304)





   
说明你的 TS 发包发多了。多次响应的 TS 应该不会合并。所以单次的 http响应体必须是 188的倍数

**Comment by wujincheng2333** [comment]
> _remain_data

大佬，是这里的问题吗，好像分包没考虑到 http 头部？

`const char *TSSegment::onSearchPacketTail(const char *data, size_t len) {
    if (len < _size + 1) {
        if (len == _size && ((uint8_t *) data)[0] == TS_SYNC_BYTE) {
            return data + _size;
        }
        //尝试解码http响应头部
        auto pos1=HttpRequestSplitter::onSearchPacketTail(data,len);
        if(pos1){
            return (char *) pos1;
        }
        
        return nullptr;
    }
    //下一个包头
    if (((uint8_t *) data)[_size] == TS_SYNC_BYTE && ((uint8_t *) data)[0] == TS_SYNC_BYTE) {
        return data + _size;
    }
    //尝试解码http响应头部
    auto pos1=HttpRequestSplitter::onSearchPacketTail(data,len);
    if(pos1){
        return (char *) pos1;
    }
    auto pos = memchr(data + _size, TS_SYNC_BYTE, len - _size);
    if (pos) {
        return (char *) pos;
    }
    return nullptr;
}`

**Comment by xia-chu** [comment]
@wujincheng2333 你粘贴的代码是ts分包的，就是一段ts分成188个字节的 没问题

**Comment by xia-chu** [comment]
@alexliyu7352 ffmpeg报警告是因为这个流码率太高 但是它的服务器带宽不足，导致很多ts切片下载不够及时 从而超时了，但是ffmpeg没有去下载这个切片的剩余数据，就去下载下一个切片了，导致ts包错乱不对齐了

**Comment by xia-chu** [comment]
我已经修改zlm的hls客户端代码了 切片下载之前有未下载完毕就下载下一个切片的bug，目前已经修复了。
但是这种切片下载超时，到时部分数据丢失的问题 目前没去处理，但是正常情况下，基本不会再报`不是ts包`的问题了。
当然，如果这个警告比较频繁，也可能是网速不佳，可以稍微提高点切片下载超时时间解决，目前超时时间是2倍的切片时长，代码在这里：

```patch
Index: src/Http/HlsPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Http/HlsPlayer.cpp b/src/Http/HlsPlayer.cpp
--- a/src/Http/HlsPlayer.cpp	(revision 5832de7ed8f53a5dea4e1c52361d3b5aa1a2ea13)
+++ b/src/Http/HlsPlayer.cpp	(date 1640323602099)
@@ -117,7 +117,7 @@
     });
 
     _http_ts_player->setMethod("GET");
-    _http_ts_player->sendRequest(url, 2 * duration);
+    _http_ts_player->sendRequest(url, 3 * duration);
 }
 
 void HlsPlayer::onParsed(bool is_m3u8_inner, int64_t sequence, const map<int, ts_segment> &ts_map) {


```

**Comment by wujincheng2333** [comment]
> @wujincheng2333 你粘贴的代码是ts分包的，就是一段ts分成188个字节的 没问题

好吧，尴尬。。。，我在阅读zlm源码，就是好奇 。
按照楼主反馈的问题：
`这里算出来的header_size = 318了, 318正好是188+130, 而130正好是5376-5246,`
有点像http头跟 ts包合并了，走到了memchr 方法
zlm 回调有点多。哈哈

**Comment by xia-chu** [comment]
@alexliyu7352 下次提issue不用重开，再原来你提的issue续着问即可，issue太多我不好处理，而且不便检索。

**Comment by alexliyu7352** [comment]
抱歉, 以后我会注意.
稍后我测试一下

**Comment by alexliyu7352** [comment]
问题仍旧没有完全解决, 仍就会出现不是ts包的情况.
当然这种情况出现在流速度非常慢的情况下, 会先报错下载分片超时, 然后报错不是ts包.
实际上这种情况是否增加一个逻辑, 就是把剩余的包按照188字节提交, 不足的直接抛弃掉.

**Comment by alexliyu7352** [comment]
```
2021-12-25 06:58:51.513 W MediaServer[10772-event poller 1] HlsPlayer.cpp:117 operator() | download ts segment http://39.135.138.59:18890/PLTV/88888910/224/3221225633/1640386608-1-1639679693.hls.ts?ssr_hostlv1=39.134.116.1:18890&ssr_host=117.169.120.151:8080 failed:http request timeout
2021-12-25 06:58:51.518 W MediaServer[10772-event poller 1] TSDecoder.cpp:24 onRecvHeader | 不是ts包:71 355
```

**Comment by xia-chu** [comment]
这个问题的本质是这个流有问题 这个流的带宽不配做直播，所以导致丢部分数据 不管你换何种播放器都是这样的结果。

**Comment by xia-chu** [comment]
此问题与 #1290 相关

**Comment by xia-chu** [comment]
我设置的http下载超时时间是切片时长的2倍，也就是说，2倍的时间都无法消费掉这1倍时间参数的数据，那么这个网速就不配做直播。

**Comment by alexliyu7352** [comment]
```
bool HttpClient::waitResponse() const {
    return !_complete && alive();
}
```

我看修改后的代码这里判断应该是判断如果没有完成以及持有socket是么?但是为什么是&&?应该是||才对阿, 如果没有完成或和持有socket就要等待完成.因为是事件循环, 有时候会出现send_request了, 这样_complete就是false, 但是还没有创建socket, 也就是alive()是false, 这样这个判断就是false了, 但是request实际上已经发出了.

**Comment by wujincheng2333** [comment]
> 问题仍旧没有完全解决, 仍就会出现不是ts包的情况. 当然这种情况出现在流速度非常慢的情况下, 会先报错下载分片超时, 然后报错不是ts包. 实际上这种情况是否增加一个逻辑, 就是把剩余的包按照188字节提交, 不足的直接抛弃掉.

现在zlm就是这样，日志打印后就会丢弃数据。你可以把日志级别提高，就不会打印了。点播跟直播不一样。直播要求延时不能太大。如果是点播，我觉得还是队列下载好，设置一个大很多的超时时间。超时之后重试。全部下载完成分片再往 解码器里面放

**Comment by xia-chu** [comment]
> ```
> bool HttpClient::waitResponse() const {
>     return !_complete && alive();
> }
> ```
> 
> 我看修改后的代码这里判断应该是判断如果没有完成以及持有socket是么?但是为什么是&&?应该是||才对阿, 如果没有完成或和持有socket就要等待完成.因为是事件循环, 有时候会出现send_request了, 这样_complete就是false, 但是还没有创建socket, 也就是alive()是false, 这样这个判断就是false了, 但是request实际上已经发出了.

有概率存在你说的问题 就是tcp连接中状态会导致连接被取消然后发起新的连接请求，这个在tcp三次握手比较慢的情况下容器触发，但是这个问题应该还好，不会导致逻辑bug，做多导致前一次tcp连接作废了。

**Comment by alexliyu7352** [comment]
明白了

**Comment by xia-chu** [comment]
后面再TcpClient加个 isConnecting的方法吧 这样waitResponse在连接中也返回true吧
