### ISSUE TITLE
[BUG]pes->pkt.size == pes->len

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1305]
`onRead | 触发socket on_read事件时,捕获到异常:Assertion failed: (pes->pkt.size == pes->len), function pes_packet, file /home/alex/CLionProjects/TvCloud/3rdpart/media-server/libmpeg/source/mpeg-packet.c, line 161.`

有时候经常报错以上的错误, 检查看是发现pkt.size和pes-len大小不一样, 明显pkt.size要大得多.

**Comment by xia-chu** [comment]
此问题跟 #1304 一致

**Comment by alexliyu7352** [comment]
使用最新代码, 在没有任何代码改动的时候, 有时候遇到下载超时, 码流又特高的情况下, 仍就会触发
执行定时器任务捕获到异常:Assertion failed: (pes->pkt.size == pes->len), function pes_packet, file /home/alex/CLionProjects/TvCloud/3rdpart/media-server/libmpeg/source/mpeg-packet.c, line 161.

而这个断言错误貌似没有捕捉, 所以会出现多次.
另外我不明白, 为何会出现这个错误, 是由于什么原因造成打包的时候计算错误么?

**Comment by alexliyu7352** [comment]
_content_len = onRecvHeader(header_ptr, header_size);
这里会把数据交由mpeg-ts-dec处理, 然后打包成packet.

而他的实现
```
ssize_t TSSegment::onRecvHeader(const char *data, size_t len) {
    if (!isTSPacket(data, len)) {
        WarnL << "不是ts包:" << (int) (data[0]) << " " << len;
        return 0;
    }
    _onSegment(data, len);
    return 0;
}
```

这里提交给下游的数据一定是188字节的数据, 也就是一个ts包.
所以这里有两点我不明白的
1. 这里代码逻辑决定每次调用mepg-ts-dec的一定是188字节的一个ts包.为何最终到打包的时候会出现pes->pkt.size == pes->len?pkt-size有时候有几mb, 而len只有1000多.这是第三方库的bug么?
2. 这里是否要做一个捕捉错误?因为如果触发了断言, 那么没有捕捉, 会导致上层的_remain_data累计, 这里应该发生了错误, 也不影响上层.

**Comment by xia-chu** [comment]
因为中间有ts包丢失了



发自我的iPhone


------------------ Original ------------------
From: alexliyu7352 ***@***.***&gt;
Date: Sat,Dec 25,2021 1:46 PM
To: ZLMediaKit/ZLMediaKit ***@***.***&gt;
Cc: 夏楚 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [ZLMediaKit/ZLMediaKit] [BUG]pes-&gt;pkt.size == pes-&gt;len (Issue #1305)





 
_content_len = onRecvHeader(header_ptr, header_size);
 这里会把数据交由mpeg-ts-dec处理, 然后打包成packet.
 
而他的实现
 ssize_t TSSegment::onRecvHeader(const char *data, size_t len) {     if (!isTSPacket(data, len)) {         WarnL << "不是ts包:" << (int) (data[0]) << " " << len;         return 0;     }     _onSegment(data, len);     return 0; }  
这里提交给下游的数据一定是188字节的数据, 也就是一个ts包.
 所以这里有两点我不明白的
  
这里代码逻辑决定每次调用mepg-ts-dec的一定是188字节的一个ts包.为何最终到打包的时候会出现pes-&gt;pkt.size == pes-&gt;len?pkt-size有时候有几mb, 而len只有1000多.这是第三方库的bug么? 

这里是否要做一个捕捉错误?因为如果触发了断言, 那么没有捕捉, 会导致上层的_remain_data累计, 这里应该发生了错误, 也不影响上层.

**Comment by alexliyu7352** [comment]
老大, 周末还不休息阿..
这应该是第三方库的问题了吧?没有做相应的处理?

**Comment by alexliyu7352** [comment]
如果我在这里处理呢?
ssize_t TSSegment::onRecvHeader(const char *data, size_t len) {
    if (!isTSPacket(data, len)) {
        WarnL << "不是ts包:" << (int) (data[0]) << " " << len;
        return 0;
    }

    try {
        _onSegment(data, len);
    } catch (...) {
        WarnL << "解析ts包错误:" << (int) (data[0]) << " " << len;
    }
    return 0;
}
这样就干脆捕捉了错误, 跳过去
