### ISSUE TITLE
[BUG]httpclient超时问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1306]
最新修改的代码有bug.
```
void HttpClient::clear() {
    _url.clear();
    _header.clear();
    _body.reset();
    _method.clear();
    _path.clear();
    _aliveTicker.resetTime();
    _chunkedSplitter.reset();
    _fTimeOutSec = 0;
    clearResponse();
}
```

当遇到302跳转时
```
if (onRedirectUrl(newUrl, _parser.Url() == "302")) {
            HttpClient::clear();
            setMethod("GET");
            HttpClient::sendRequest(newUrl,_fTimeOutSec);
            return 0;
        }
```

会先调用clear方法, 而这个方法会 _fTimeOutSec = 0; 这样接下去的跳转就会直接超时

**Comment by xia-chu** [comment]
有道理 确实没考虑这个问题 欢迎提个pr



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2021年12月24日 06:46
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]httpclient超时问题 (Issue #1306)





 
最新修改的代码有bug.
 void HttpClient::clear() {     _url.clear();     _header.clear();     _body.reset();     _method.clear();     _path.clear();     _aliveTicker.resetTime();     _chunkedSplitter.reset();     _fTimeOutSec = 0;     clearResponse(); }  
当遇到302跳转时
 if (onRedirectUrl(newUrl, _parser.Url() == "302")) {             HttpClient::clear();             setMethod("GET");             HttpClient::sendRequest(newUrl,_fTimeOutSec);             return 0;         }  
会先调用clear方法, 而这个方法会 _fTimeOutSec = 0; 这样接下去的跳转就会直接超时

**Comment by xia-chu** [comment]
代码已经修改了 简单测试过了 应该没问题了
