### ISSUE TITLE
[功能请求]edge代理模式

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1307]
需求是zlm可以直接作为edge服务器, 这样就不涉及到解复用的流程. 只是推流/拉流请求转发给指定的下一级server.
这样后端下一级server可以具体处理转码等.

需求类似
https://github.com/brpc/media-server/blob/master/docs/cn/edge_server.md

**Comment by xia-chu** [comment]
新增主动溯源的集群部署模式 ： be77f84315f9a98c943d186fb2caaf167d63863b
