### ISSUE TITLE
[技术咨询]能否详细的讲讲整个系统调用流程

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1309]
我的意思是能否从代码层面讲解下整个流程而不是您wiki上的业务层面.
太多的类,派生类, 模板了,看得实在是眼花了.

我就想知道一个代码层面的流程图, 因为现在有些地方让我很费解.
比如拉http hls流, 那么一开始
通过addStreamProxy--->创建PlayerProxy--->判断协议类型创建具体的播放器比如hlsplayer--->设置关闭回调---->开始播放流程PlayerProxy::play--->setOnPlayResult设置播放结果回调[处理播放结果与重试]--->设置关闭时的回调[处理注销流与重试]---........

等等的这类的.
这些大的流程我到是很理解, 主要就在于缓存使用那一块的流程有些迷糊, 理论上来说其他的流媒体服务器都一样, 接收到流或者回源流后进行缓存,达到缓存上限了就开始抛弃掉头部的缓存,压入新的缓存, 终端客户开始播放操作时开始消费这些缓存, 直到缓存消耗干净了, 就断开终端.

基本上这里都是采用诸如环形等队列的, 模式也都是生产者消费者模式,新的帧压入队列底部, 消费者客户端从队列顶部读取流.
当没有新数据压入队列的底部时,消费者仍就会消费队列中的数据, 直到队列变空了就断开链接.

但是我看到的zlm的代码这里有些迷糊, 好像这块处理是环形缓存中压入新的数据后, 才会调用消费者去消费掉数据.
这样就算缓存设置的在大, 一旦没有新的数据进入缓存, 消费者就不会去主动消费掉缓存的数据???还是我的理解有问题?

这部分我修改了一些代码想要实现一个可控的缓存时间, 但是无论我怎么修改, 模拟上游断流后, 客户端几秒后就停止工作了, 哪怕我已经缓存了超过50mb的流了.

我觉得无论是zlm作为一个基础开发库还是脚手架, 还是一个可以直接运行的流媒体系统.
这个功能都是一个很需要的功能, 毕竟zlm不仅仅只是用于监控行业, 其他行对的zlm的需求才是真的广泛.
就像srs一样.

其实我就想要实现这个链接上说的这种效果.
https://github.com/brpc/media-server/blob/master/docs/cn/frame_queue.md

**Comment by xia-chu** [comment]
> 这部分我修改了一些代码想要实现一个可控的缓存时间, 但是无论我怎么修改, 模拟上游断流后, 客户端几秒后就停止工作了, 哪怕我已经缓存了超过50mb的流了.

间而言之，你处理事件的顺序不对。
50MB的数据是50MB的事件，eof也是事件，但是zlm的事件是立即回调的，如果你缓存了50MB的数据，然后收到eof事件了，你会立即去优先处理eof事件，导致50MB的数据直接无效。

你应该像处理数据一样处理eof事件，也就是onShutdown事件。
其实你可以这样处理，数据和eof数据都抽象为task，用functional包装即可，eof事件也需要排队等这50MB数据处理完毕。

非阻塞socket跟阻塞socket不一样啊，阻塞的就是事件一件一件处理的 他是顺序的、线性的，而非阻塞的模型，它更接近cpu的无序、随机调度。

**Comment by xia-chu** [comment]
怎么抽象task，你可以参考下`RtpProcess::doCachedFunc()`,  当时这么设计的目的是想在鉴权hook返回后再按序处理事件，但是这些事件已经在之前就发生了。

**Comment by alexliyu7352** [comment]
感谢大佬的解释, 让我对zlm有了更深入的理解.说实话通过和大佬每次的issues请教, 真的让我收益良多.

但是这部分的代码我看了, 他的逻辑应该是在鉴权发生完成之前, 所有的事件操作都转变成为一个一个的task并压入_cached_func这个队列里面, 一旦收到鉴权完成的通知了, 就按照顺序来执行这个队列里面的task.

我的确把http的eof事件, rtmp的推流超时事件等包装起来并暂时缓存, 直到数据消耗完成后在执行,这点我理解了.
这样可以避免立即断开导致之前的缓存数据还没有消耗掉.

但是这两个怎么实现?
```

min_cache_length(ms)
返回给新用户的第一帧是media-server的帧缓冲中，与当前最新的帧相隔大于min_cache_length（单位毫秒）时间长度的所有音视频帧中最新的关键帧。例如，如果这个值设置为2000ms，那么media-server会返回给新用户2000ms前的第一个关键帧开始的所有数据，这个缓冲队列可以用来缓解卡顿。

-max_cache_length(ms)
返回给新用户的第一帧是media-server的帧缓冲中，与当前最新的帧相隔小于max_cache_length（单位毫秒）时间长度的所有音视频帧中最老的关键帧。例如，如果这个值设置为2000ms，那么media-server会返回给新用户2000ms内的最老的关键帧开始的所有数据，这个缓冲队列可以用来控制最大延迟。
```

现在按照您说的, 我可以在上游播放器类比如hlsplayer, rtmpplayer中控制收到的缓存, 并在上游断开后,也能保持按照tick压入缓存到解码器, 这可以缓解掉上游网络抖动导致的客户端立刻断开.
但是, 我如何能实现控制缓解客户端的卡顿与延迟?

目前我测试的效果就是, 两个客户端一个先开, 一个后开, 无论后开的客户端什么时候开, 都会播放的是最新的帧.这样一旦网络抖动了, 那么两个都会卡顿. 
因为我想能把zlm继续开发直到成为一个不单单适用于单一领域的流媒体服务器,所以要考虑的环境和您的大部分用户可能不一样, 我考虑的基本上都是在互联网上传输的环境, 而不是像您的大部分用户用于企业监控, 那么网络的质量都是比较好的内网或者同一个isp的网络.而我考虑的网络环境那就五花八门了, 而服务器又不是在bgp线路上, 所以抖动的问题很普遍.

而作为一个流媒体服务器, 最重要的就是如何解决这些问题的同时让客户端可以无感之.比如这个缓冲我觉得很重要, 这可以让客户端用户体验好很多.

同样业务有居家监控, 用户设备推流到zlm上, 用户可以通过其他设备进行观看.这样的业务其实也需要流媒体服务器能处理抖动的问题, 有些偷懒的可以通过延长生成hls的分片数量来实现增加延时来换取客户端播放的平滑, 但是我觉得客户端可能不仅仅只是播放hls, 很多也许会播放rtmp或者http流.

那么最好就是有一个缓冲控制, 而这部分我对zlm的理解还是比较困惑和肤浅的.
就现在我通过拜读您的代码发现, 您所有的缓存控制都是统一在ringbuffer里面,而ringbuffer设置只缓存一个gop.
