### ISSUE TITLE
[BUG]EINVAL错误

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1311]
有时候hls拉流会报错, 给上层返回的是eof, 但是实际上跟踪调试到
这里发现并不是eof

```
 do {
            nread = recvfrom(sock_fd, data, capacity, 0, &addr, &len);
        } while (-1 == nread && UV_EINTR == get_uv_error(true));

        if (nread == 0) {
            if (!is_udp) {
                emitErr(SockException(Err_eof, "end of file"));
            }
            return ret;
        }
```
这时nread==0, get_uv_error(true) == -22, 也就是EINVAL错误,

**Comment by alexliyu7352** [comment]
找到一个解释就是

After deleting a local IP address, an application sent data to an existing connection through that IP address. Therefore TCP retransmissions were invoked, then the retransmission continued until the tcp_retries2 sysctl timeout. If finding the routing cache entry failed after tcp_retries1 boundary or after the garbage collection, this will result in the EINVAL error. After that the application called recvfrom() and the connection and got EINVAL error instead of ETIMEDOUT.

但是问题是没有删除本地ip阿?

**Comment by alexliyu7352** [comment]
遇到这个问题是, 我实现了http-ts的拉流.
但是在网络抖动的时候或者长时间拉流的时候会经常的报错eof, 可问题是数据流肯定是没有读完的.
但是这又不是httpclient内部计时器超时的问题, 所以就跟踪调试发现这块出现了问题.

很奇怪的问题, 
在do循环中
执行一次后len就会变成0, get_uv_error就会报EINVAL错误.
由于nread是0, 然后就当作了eof上报上层了.

实际上我对这个比较疑惑.另外我想功能完善后提交pr上来.
但是现在想请求帮助,因为http-ts流需要长时间的拉流, 并且很多的服务器是不支持range的, 所以如何能保证长时间的拉流不间断呢?
我目前的做法就是一个是设置socket的keeepalive, 另外就是重写继承的httpclient的相关超时判断.
这些都做了, 但是目前遇到这个错误, 老是报eof错误, 不知道怎么解决好.

**Comment by xia-chu** [comment]
EINVAL的错误 看翻译是本地ip变化了 导致tcp五元组失效了 那么tcp长连接就不复存在了

**Comment by xia-chu** [comment]
你抓tcp的包有没有收到fin包？

**Comment by alexliyu7352** [comment]
有, 发送了一个fin,ack
然后我这边又回送了一个ack
