### ISSUE TITLE
[BUG]报错basic_string

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1312]
执行定时器任务捕获到异常:basic_string::at: __n (which is 255) >= this->size() (which is 255)

有时候会报错这个玩意, 而且没办法排查. 因为是不定时报错的, 并且是在我的生产服务器上, 所以也不知道是什么原因引起的.
看似是否是输出日志的宏或者StrPrinter出错?

**Comment by xia-chu** [comment]
这个要catch 到才行，否则很难定位。

**Comment by alexliyu7352** [comment]
定位不到阿, 这个不是我刚才提的那个崩溃的bug, 那个是我修改代码造成的, 这个我用没修改过的zlm也会遇到.
我断点也抓不到这个错误在哪里, 因为都是在timer类里面的重试任务的catch到的.

**Comment by xia-chu** [comment]
这个是访问string下标越界导致的。

**Comment by alexliyu7352** [comment]
这个很难捕捉阿, 很难重现这个问题.
我在我本机怎么测试都没有, 扔到生产服务器上, 就会时不时的冒出来.
生产服务器上的代码我没有怎么改动.
就加了一些日志输出以及StrPrinter打印
是否是StrPrinter还是日志的问题?
输入的字符串太多了?
StrPrinter到是IDE提示
Clang-Tidy: Slicing object from type '_StrPrinter' to 'basic_string<char>' discards 392 bytes of state

**Comment by alexliyu7352** [comment]
这个问题已经找到了, 但是又有一个新的问题.
当我teardown_l后,会触发PlayerProxy::rePlay
```
_timer = std::make_shared<Timer>(iDelay / 1000.0f, [weakSelf, strUrl, iFailedCnt]() {
        //播放失败次数越多，则延时越长
        auto strongPlayer = weakSelf.lock();
        if (!strongPlayer) {
            return false;
        }
        WarnL << "重试播放[" << iFailedCnt << "]:" << strUrl;
        strongPlayer->MediaPlayer::play(strUrl);
        strongPlayer->setDirectProxy();
        return false;
    }, getPoller());
```
可为什么这里的timer定时器不起作用?不会运行了? 是析构了?没看到哪里有析构它阿.
