### ISSUE TITLE
[技术咨询]GetSnap 本地网络 需要5-6秒，默认配置，docker部署，api调用，请问是怎么回事？

### ISSUE THREAD

**Issue by na-hui** [ZLMediaKit/ZLMediaKit#1316]
**截图**
- GetSnap 本地网络 需要5-6秒，默认配置，docker部署，api调用，在命令行中直接调用ffmpeg截图，很快

**Comment by xia-chu** [comment]
那请提供下zlm生成的ffmpeg日志

**Comment by na-hui** [comment]
有很多，我贴几个

#### pid=969,cmd=/usr/local/bin/ffmpeg -i http://192.168.99.24/live/21225.flv -y -f mjpeg -t 0.001 /zlmediakit/www/snap/1f4c3a51732a471b198333d95c8cd404/1640245632.jpeg.tmp #####

ffmpeg version git-2020-07-30-1a690e8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --enable-libx265 --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-libx264 --prefix=/usr/local/ffmpeg --enable-cross-compile
  libavutil      56. 57.100 / 56. 57.100
  libavcodec     58. 97.102 / 58. 97.102
  libavformat    58. 49.100 / 58. 49.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, flv, from 'http://192.168.99.24/live/21225.flv':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
    Stream #0:1: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1280x960, 5120 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, mjpeg, to '/zlmediakit/www/snap/1f4c3a51732a471b198333d95c8cd404/1640245632.jpeg.tmp':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
    encoder         : Lavf58.49.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 1280x960, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.97.102 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=7.7 Lsize=      90kB time=00:00:00.04 bitrate=18381.0kbits/s speed=0.455x    
video:90kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%


#### pid=3312,cmd=/usr/local/bin/ffmpeg -i http://192.168.99.24/live/10230.flv -y -f mjpeg -t 0.001 /zlmediakit/www/snap/35a3c1ff8231ee60f2af8e2cced0abc3/1640313041.jpeg.tmp #####

ffmpeg version git-2020-07-30-1a690e8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --enable-libx265 --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-libx264 --prefix=/usr/local/ffmpeg --enable-cross-compile
  libavutil      56. 57.100 / 56. 57.100
  libavcodec     58. 97.102 / 58. 97.102
  libavformat    58. 49.100 / 58. 49.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, flv, from 'http://192.168.99.24/live/10230.flv':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
    Stream #0:1: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 5120 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, mjpeg, to '/zlmediakit/www/snap/35a3c1ff8231ee60f2af8e2cced0abc3/1640313041.jpeg.tmp':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
    encoder         : Lavf58.49.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.97.102 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=10.5 Lsize=     155kB time=00:00:00.04 bitrate=31840.8kbits/s speed=0.31x    
video:155kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%


#### pid=3608,cmd=/usr/local/bin/ffmpeg -i http://192.168.99.24/live/10230.flv -y -f mjpeg -t 0.001 /zlmediakit/www/snap/35a3c1ff8231ee60f2af8e2cced0abc3/1640325283.jpeg.tmp #####

ffmpeg version git-2020-07-30-1a690e8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --enable-libx265 --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-libx264 --prefix=/usr/local/ffmpeg --enable-cross-compile
  libavutil      56. 57.100 / 56. 57.100
  libavcodec     58. 97.102 / 58. 97.102
  libavformat    58. 49.100 / 58. 49.100
  libavdevice    58. 11.101 / 58. 11.101
  libavfilter     7. 87.100 /  7. 87.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, flv, from 'http://192.168.99.24/live/10230.flv':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
  Duration: 00:00:00.00, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 8000 Hz, mono, fltp
    Stream #0:1: Video: h264 (High), yuvj420p(pc, bt709, progressive), 1920x1080, 5120 kb/s, 25 fps, 25 tbr, 1k tbn, 50 tbc
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Output #0, mjpeg, to '/zlmediakit/www/snap/35a3c1ff8231ee60f2af8e2cced0abc3/1640325283.jpeg.tmp':
  Metadata:
    fileSize        : 0
    server          : ZLMediaKit(git hash:56b7a8a,branch:master,build time:Nov 11 2021 03:37:57)
    encoder         : Lavf58.49.100
    Stream #0:0: Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.97.102 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: N/A
frame=    1 fps=0.0 q=11.1 Lsize=     195kB time=00:00:00.04 bitrate=39850.8kbits/s speed=0.203x    
video:195kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

**Comment by na-hui** [comment]
docker 镜像是 panjjo/zlmediakit

**Comment by xia-chu** [comment]
如果流已经注册了 那么截图就能很快 否则会慢很多

**Comment by xia-chu** [comment]
你确保截图时 流已经注册了

**Comment by na-hui** [comment]
确认流已经注册，而且我每次刷新调用 都是同样，我使用的是AddStreamProxy 拉流 RTSP

**Comment by na-hui** [comment]
很奇怪，我重新在centos7编译运行，不使用docker,截图很快，不知道问题出在哪里，另外，问下，拉流的记录是存储在哪个路径，我把www路径映射出来了，但是重启docker，拉流记录就没有了，是不是拉流记录没有存放在www目录下？

**Comment by xia-chu** [comment]
> 很奇怪，我重新在centos7编译运行，不使用docker,截图很快，不知道问题出在哪里，另外，问下，拉流的记录是存储在哪个路径，我把www路径映射出来了，但是重启docker，拉流记录就没有了，是不是拉流记录没有存放在www目录下？还有，getsanp调用能不能用多线程（不太懂c++）,感觉是顺序执行的，我在获取多路视频截图时，感觉是一个一个出来的，如果同时截图几十路的话，时间也会很长，体验不好

截图通过配置文件默认放在`www/snap/下`。你说的用docker截图很慢，但是直接shell执行或在非docker情况下截图很快，这个还要仔细定位下问题。

截图时注释的，需要用一条线程去等待ffmpeg进程截图好并退出，目前截图线程个数是固定的，跟cpu核数相同(如果支持超线程还要x2)，所以如果短时间内截图太多，会导致线程池任务列队积压，导致后面截图请求超时。

**Comment by na-hui** [comment]
2022-01-04 14:29:45.524 I MediaServer[1-work poller 7] Process.cpp:150 run | start child process 183, log file:/zlmediakit/ffmpeg/ffmpeg.log.183
2022-01-04 14:29:52.407 I MediaServer[1-work poller 7] Process.cpp:202 s_wait | process terminated, pid=183, exit code=0
2022-01-04 14:29:52.407 D MediaServer[1-work poller 7] WebApi.cpp:230 http api debug | 

# request:
GET /index/api/getSnap?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&url=http%3A%2F%2F192.168.99.24%2Flive%2F10230.flv&timeout_sec=5&expire_sec=5
....................................................................
# response size:224241

前二行数据，时间用了将近7秒  ,我在docker内部 调用同样的命令（从log 里复制），几乎瞬间完成，是不是后台调用ffmpeg的问题？

**Comment by xia-chu** [comment]
建议你在zlm空载的情况下执行下截图命令试试，看看是否还这么长时间

**Comment by na-hui** [comment]
我现在测试，只拉流了一路视频，而且刚刚测试，timeout_sec 设置小于5秒，全部失败

**Comment by xia-chu** [comment]
> 我现在测试，只拉流了一路视频，而且刚刚测试，timeout_sec 设置小于5秒，全部失败

这些截图的流 用ffplay播放能秒开吗

**Comment by na-hui** [comment]
再次进行测试，我部署了3套，2套docker,1套centos，我使用docker1调用getsnap获取docker2里的流，超时6秒，但是用centos调用获取docker2的流，0.5秒完成，难度是因为docker有什么限制
ffplay 速度没问题，1秒左右

**Comment by na-hui** [comment]
用网页播放器也没有问题，秒开

**Comment by na-hui** [comment]
又发现：centos 截图本机地址，时间超过5秒，但是centos截图非本机的地址，秒回

**Comment by xia-chu** [comment]
你说的我都迷糊了 太神奇了 没规律可言

**Comment by na-hui** [comment]
是呢，奇了怪了，我查看相关部分代码，不至于这样呢，现在只能在我自己的代码部分实现截图了，等你新版本更新后看这部分有没改善再说了。
第二个问题，服务重启后，原来设置的拉流都没有了，是设计上就这样的设计的，还是我哪里设置的不对

**Comment by xia-chu** [comment]
> 是呢，奇了怪了，我查看相关部分代码，不至于这样呢，现在只能在我自己的代码部分实现截图了，等你新版本更新后看这部分有没改善再说了。 第二个问题，服务重启后，原来设置的拉流都没有了，是设计上就这样的设计的，还是我哪里设置的不对

zlm不会去做持久化 需要你自己实现

**Comment by na-hui** [comment]
夏总，使用github上的代码编译出来的版本，ffmpeg 无法支持海康 h265 编码的，docker版本 panjjo/zlmediakit 的 ffmpeg 可以支持，请问一下，编译的版本 怎么搞
编译的版本 ffmpeg version 3.4.8-0ubuntu0.2
docker版本 ffmpeg version git-2020-07-30-1a690e8

**Comment by xia-chu** [comment]
请用这个ffmpeg分支: https://gitee.com/xia-chu/FFmpeg

**Comment by na-hui** [comment]
回头搭建一个docker调试环境试试，先关闭了
