### ISSUE TITLE
[技术咨询]WEB-RTC证书subjectAltName的IP匹配

### ISSUE THREAD

**Issue by mavk** [ZLMediaKit/ZLMediaKit#1319]
**咨询的功能模块**
- WEBRTC证书

**咨询的具体内容和问题**
- 查看WIKI和ISSUE列表，发现ZLMEDIAKIT的证书识别是通过域名识别的，请问支持IP吗？
  注：应用场景是工业互联网，主要业主是各类工厂，基本上没有自己的解析服务，现有解决方案是让业主安装我们自签发的证书(IP识别，流媒体是KurentoMediaServer)；相应业务是想通过ZLMEDIAKIT来拉取摄像头、布控球等RTSP流或国标再转WEBRTC（低延时）到浏览器，内部再通过WEBRTC实现终端与浏览器的实时视频通讯、直播等业务。
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
webrtc如果用于播放 是不需要https的。怎么获取证书域名是通过这个函数获取的, 你看看应该怎么修改获取IP：

```c++
string SSLUtil::getServerName(X509 *cer) {
#if defined(ENABLE_OPENSSL) && defined(SSL_CTRL_SET_TLSEXT_HOSTNAME)
    if(!cer){
        return "";
    }
    //获取证书里的域名
    X509_NAME* name = X509_get_subject_name(cer);
    char ret[256] = { 0 };
    X509_NAME_get_text_by_NID(name, NID_commonName, ret, sizeof(ret));
    return ret;
#else
    return "";
#endif
}
```

**Comment by mavk** [comment]
HTTPS支持是因为我们为了实现浏览器端的实时音视频(SIP电话、视频电话、直播)，我去看下相应代码。
感谢！
