### ISSUE TITLE
[技术咨询]webhook接口报错

### ISSUE THREAD

**Issue by MMMMMine** [ZLMediaKit/ZLMediaKit#1321]
**咨询的功能模块**
- webhook

**咨询的具体内容和问题**
- 
![image](https://user-images.githubusercontent.com/20126820/147648572-c91fdb43-9bb2-4b07-93f8-3e7076097f51.png)

**注意事项**
- 想咨询下什么情况下会触发这个报错, 非常偶发

**Comment by xia-chu** [comment]
你的hook返回数据不合法

**Comment by MMMMMine** [comment]
查到问题了  谢谢大佬
