### ISSUE TITLE
建议在项目说明里面把stream  media server 关键词加上

### ISSUE THREAD

**Issue by alongL** [ZLMediaKit/ZLMediaKit#1325]
要不然，这些弱鸡的搜索引擎竟然索引不到

Streamnode都上榜了，zl竟然没有，这能忍
[The Top 161 Media Server Open Source Projects on Github]
https://awesomeopensource.com/projects/media-server

完全找不到
[github topics]
https://github.com/topics/media-server

**Comment by xia-chu** [comment]
加上了已经 谢谢！
