### ISSUE TITLE
[技术咨询]ZLMediaKit拉流getSnap截图FFmpeg卡死导致ZLMediaKit无法接收其他请求

### ISSUE THREAD

**Issue by LongTraveller** [ZLMediaKit/ZLMediaKit#1327]
**bug现象**  调用ZLMediaKit的截图接口/index/api/getSnap，当视频流不存在时，偶先ffmpeg截图卡死，导致其他发送至ZLMediakit的请求服务一直阻塞
- bug产生时服务器的异常行为(例如: 崩溃/无法访问/丢包花屏)
ffmpeg拉流截图进程一直存在，且ZLMediaKit无法处理其他http请求
- bug产生时，打印的上下文日志(可以截图或粘贴文本)
<img width="648" alt="企业微信截图_16409444159982" src="https://user-images.githubusercontent.com/55306718/147816561-12e6be3a-ebd4-4b5e-8c87-960ce8b4db02.png">
（ffmpeg截图进程一直存在）
![image](https://user-images.githubusercontent.com/55306718/147816700-a3325741-4a62-43f4-95fa-1eda52d3b70b.png)
（提示开始进行ffmpeg拉流截图后，一直没有截图结果，且之后MK没有打印日志）
<img width="836" alt="企业微信截图_16409447373820" src="https://user-images.githubusercontent.com/55306718/147816821-d2d234d1-7418-42bb-a620-81f867f6f84d.png">
（查看ffmpeg的拉流日志，一直卡死，且之后没有日志）

- 调试core文件时，崩溃触发点的函数调用栈(可以截图或粘贴文本)

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的什么功能模块？
调用/index/api/getSnap进行截图
**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤

**zlm代码git commit hash值**
- git log查看
- MK的版本
编译日期: 2021/11/26-06:17:25
当前git分支: master
当前git hash值: c1b78629
-ffmpeg的版本
ffmpeg version 4.1.8-0+deb10u1 Copyright (c) 2000-2021 the FFmpeg developers

**操作系统环境**
- 什么类型的操作系统，32位，64位？
- 什么cpu类型？
操作系统：Ubuntu 20.04.3 LTS    x86-64
cpu：4  AMD Ryzen 3 3200G with Radeon Vega Graphics

**Comment by xia-chu** [comment]
在使用ffmpeg相关功能时，请先`nohup ./MediaServer &`执行，然后exit退出shell，然后执行ffmpeg相关功能，否则会挂起zlm的进程，原因未知，也没去细究。这个我在`服务器启动与关闭`的wiki有提及。
