### ISSUE TITLE
最新版本编译问题（2022.1.1）

### ISSUE THREAD

**Issue by ywwyewenwei** [ZLMediaKit/ZLMediaKit#1331]
**bug现象**

   最新版本无法编译，make提示信息如下：
   Built target mk_api
   /usr/bin/ld: ../../release/linux/Debug/libwebrtc.a(DtlsTransport.cpp.o): in function `RTC::DtlsTransport::CheckRemoteFingerprint()':
   /home/ubuntu/yeww/ZLMediaKit/webrtc/DtlsTransport.cpp:1140: undefined reference to `SSL_get1_peer_certificate'
   collect2: error: ld returned 1 exit status
    make[2]: *** [server/CMakeFiles/MediaServer.dir/build.make:169: ../release/linux/Debug/MediaServer] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1032: server/CMakeFiles/MediaServer.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2
   

**bug是否可以复现，怎么复现**
 1、从github下载最新版本的openssl，编译安装，openssl version 显示：
       OpenSSL 3.1.0-dev  (Library: OpenSSL 3.1.0-dev )
 2、从github下载libsrtp，并编译，安装；
      ./configure --enable-openssl make -j4;sudo make install
 3、从gitee下载ZLMediaKit
       mkdir build 
       cd build
       cmake .. -DENABLE_WEBRTC=true -DOPENSSL_ROOT_DIR=/usr/local/openssl -DOPENSSL_LIBRARIES=/usr/local/openssl/lib
       make -j4

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
ubuntu 20.04 64bit

**Comment by hotcoffie** [comment]
怎么修复的啊，我也遇到了

**Comment by xia-chu** [comment]
这个需要升级openssl到1.1以上，建议在高版本Ubuntu上编译啊 centos上很麻烦
