### ISSUE TITLE
[BUG]不支持pts非连续hls

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1332]
测试网址
https://s3.amazonaws.com/playon-test-videos/discont_test_new/discont_test.m3u8

两个问题:
1. 拉流后ffmpeg没办法完整播放
2. 如下所示

`download ts segment https://s3.amazonaws.com/playon-test-videos/discont_test_new/2befd3aa94_20180313T082811_000025.ts failed: end of file`

```
因为两次触发了这里, 一次是已完成, 一次是报错
 if (err) {
            WarnL << "download ts segment " << url << " failed: " << err.what();
        }
```

```
//content接收完毕
    onResponseBody(data, _total_body_size - _recved_body_size, _total_body_size, _total_body_size);
    bool bigger_than_expected = recved_body_size > (size_t) _total_body_size;
    onResponseCompleted_l();
```

这里触发onResponseCompleted_l, 然后emitOnComplete(SockException(Err_success, "play completed"));
说明分片已经下载完成了, 然后开始下载新的分片.
但是紧接着

```
void HttpClient::onErr(const SockException &ex) {
    if (ex.getErrCode() == Err_eof && _total_body_size < 0) {
        //如果Content-Length未指定 但服务器断开链接
        //则认为本次http请求完成
        onResponseCompleted_l();
    }
    onDisconnect(ex);
}
```

又再次触发一次, 这样不但报错, 而且又提交了一个下载下一个分片task的请求.

查看socket的错误get_uv_error(true) == 0, 为什么会是0???找不到0对应的定义

**Comment by xia-chu** [comment]
这个是HttpTSPlayer::onDisconnect和HttpTSPlayer::onResponseCompleted没做事件区分个过滤导致的，加点代码即可
