### ISSUE TITLE
[意见反馈]RTP推流到zlmediakit中等待track ready的时间是10S，实测可能有点短，建议加长

### ISSUE THREAD

**Issue by huangban** [ZLMediaKit/ZLMediaKit#1333]
【场景】
我做性能测试，手上有一些真实摄像头录制的mp4文件，起了两个zlmediakit，一个服务器A从MP4文件中生成流，推RTP流到另外一个服务器B，发现分组并发推流的时候第二组track ready时间有极大概率超过10s，会报错导致流不能生成。比如第一组并发推10路流到服务器B，track百分之百能ready并生成流，第一组流生成后，并发推第二组10路流到服务器，一般只有一两路能ready。甚至我并发推200路，第一组也是百分百生成流，第二组的流极大概率超过10s。
报错日志  emitAllTrackReady | track not ready for a long time

【问题】
问题1：根据我的猜测，是zlmediakit存在流的时候，接受其他RTP流，track ready时间可能变长？我实测的有部分在10s以上，不过都不会超过15秒。我自己将等待track ready的时间由10s改为30s后，所有推流都能成功。
问题2：track ready超时后会清除track，不过后续用同一个SSRC继续推流，也不会重新生成track，这里应该是可以做个支持重试机制？

【建议】
感觉这个等待track ready的10s有点悬，调整大可能只是流不能ready的场景多费一点内存？建议调大到15。

感谢xiachu大佬的项目，我自己的问题已经解决了，没有能力做更深一步的定位，提供以上反馈，供参考，防止其他人遇到一样的坑。

**Comment by xia-chu** [comment]
在直播、安防领域，10秒一个GOP的设定已经非常长了，我认为最大等10秒，是合理的，因为GOP太长，用户播放延时会非常大，另外由于服务器GOP缓冲长度的限制，不可能无限缓存GOP，那么GOP太大，也会导致播放秒开失败。

这个参数已经暴露在配置文件了，用户可以自行根据使用场景调整，我觉得默认调整到15秒，意义不大。

你用mp4测试的参考性不大，因为录像跟直播又天壤之别，有些mp4的gop贼长。

**Comment by xia-chu** [comment]
由于时间精力有效 现在才回复 抱歉

**Comment by huangban** [comment]
明白了，多谢
