### ISSUE TITLE
RTP推流性能测试数据分享

### ISSUE THREAD

**Issue by huangban** [ZLMediaKit/ZLMediaKit#1334]
# 测试条件说明
条件 | 说明
-- | --
环境 | k8s容器化运行
副本数 | 1
资源配置 | limit和request均为2C4G
流信息 | mp4视频文件，分辨率 1920*1080帧率：20帧/s时长：2分59秒文件大小：51M
版本|2021年8月的版本
配置|rtsp和rtmp关闭了按需生成流，其余协议开启按需生成流
测试方法|在主机启动了一个zlmediakit作为推流端（简称客户端），编写go代码通过http接口调用客户端，sendRtp接口往容器中的zlmediakit（简称服务器）推流，流在服务器生成之后，通过addStreamProxy拉流，测试推拉流的性能。

# 测试过程
1. 初始状态，未进行压测，CPU占比0.5%，内存占比0.4%
![RSSi mede seme QI1S 2MN CA  3](https://user-images.githubusercontent.com/17782796/148012325-eeab4641-d7e7-4512-8854-35b211e968c8.png)

2. 10:44 推拉1路流。CPU占比0.71%，内存占比0.72%
![mede wmer O asn • r23 OST4N on](https://user-images.githubusercontent.com/17782796/148012415-7f1be1af-6f93-4a7c-a54e-591bfce44e16.png)

3. 10:48 推拉10路流。CPU占比2.3%，内存占比3.3%，视频无卡顿
![MTY4ODg1MDMyNjI1MjA1Mg_566164_qSDMUP6VGh1bFWHL_1641091904](https://user-images.githubusercontent.com/17782796/148012426-c6dff689-a7b3-41f0-bebd-f1b59a10c415.png)

4. 10:52 推拉100路流。CPU占比30%，内存占比27%，视频基本无卡顿，5-6秒有一次100ms的卡顿
![pedoeener 652 23 671 11 5713 22300](https://user-images.githubusercontent.com/17782796/148012431-3f1979f2-6e04-41e1-aede-0b9ace63080f.png)

5. 11:10 推拉200路流。CPU占比60%，内存占比54%，视频轻微卡顿，2-3秒有一次100ms的卡顿
![110 1168 11 1112 1184 155 1118 1120](https://user-images.githubusercontent.com/17782796/148012440-a276d30d-10d8-41ca-b227-d977aae612f2.png)

6. 11:30 推拉300路流。CPU占比80%，内存占比54%，视频轻微卡顿，1-2秒有一次100ms的卡顿，偶尔会卡顿0.5秒左右
![051S X J1381 Ke](https://user-images.githubusercontent.com/17782796/148012453-4179b5e7-cff5-469c-994a-276304c76fa9.png)

7. 推拉400路流。CPU占比100%，频繁重启
8. 调整到8核16G，推拉800路流。CPU占比40%，内存占比55%，视频基本无卡顿，5-6秒有一次100ms的卡顿
![MTY4ODg1MDMyNjI1MjA1Mg_982055_esMXtrzbh_FEDmw4_1641098973](https://user-images.githubusercontent.com/17782796/148012643-f3868b8f-2905-4dff-9605-08613e3f0852.png)

# 结论
在我自己的应用场景和硬件配置下，平均1核2G可以比较保守稳妥的应对100路推拉流

附遇到的问题 #1333

**Comment by xia-chu** [comment]
> `在主机启动了一个zlmediakit作为推流端（简称客户端），编写go代码通过http接口调用客户端，sendRtp接口往容器中的zlmediakit（简称服务器）推流，流在服务器生成之后，通过addStreamProxy拉流，测试推拉流的性能。`

你是启动一个zlm(假定`A`)用sendRtp接口推流到另外一个zlm(假定`B`)吗？ addStreamProxy拉流是谁冲谁拉流？

**Comment by huangban** [comment]
A推RTP流到B，然后B中等流生成之后，A再从B拉RTSP流，并录制到本地。

**Comment by xia-chu** [comment]
那你说的卡顿是用播放器播放B的视频卡顿吗？

**Comment by huangban** [comment]
提醒我了，我测试是否卡顿选错了对象，我应该关注的是B里面的RTSP流是否卡顿，测试数据里面是用VLC播放的A里面的addStreamProxy生成的流。

**Comment by xia-chu** [comment]
你这个卡顿测试干扰太多了 有可能是推流的A卡顿导致 也可能是B卡顿导致的。

**Comment by xia-chu** [comment]
建议你搞个zlm `c`, 这个c只接收一路`a`的推流，你播放推给`b`和`c`上的这路流，如果`c`的流不卡顿，那么说明推流端没问题，`b`性能瓶颈导致卡顿了，否则说明推流端就直接卡顿了

**Comment by dujingning** [comment]
测试只推流不拉流，不太好吧，体现不出来正常使用
