### ISSUE TITLE
[技术咨询]国标推流TCP主动

### ISSUE THREAD

**Issue by wanshuangquanzzuli** [ZLMediaKit/ZLMediaKit#1337]
**咨询的功能模块**
- 国标推流使用startSendRtpStream推流

**咨询的具体内容和问题**
-
![image](https://user-images.githubusercontent.com/18186741/148033124-e022823d-2c02-431b-b980-c5b62505a8fe.png)
国标设备TCP为active 时候，startSendRtpStream 推流被拒绝 ，是否是因为startSendRtpStream 的TCP 推流也是主动发起连接的呢？

**Comment by xia-chu** [comment]
startSendRtp接口是让zlm开启一个tcp连接并开始推流
