### ISSUE TITLE
[技术咨询]开个讨论：探讨下接收RTP包时因网络丢包异常的可行性解决方法

### ISSUE THREAD

**Issue by tsingeye** [ZLMediaKit/ZLMediaKit#1339]
讨论概述:
目前zlm在使用udp接收rtp包时，因udp网络天生原因，造成丢包，包序列号不连续，导致视频异常，现提出一种猜想解决方案，欢迎大家一起探讨下，是否可行。

解决方法：
在接收rtp包时，通过缓存一下，重构包序列号、重构rtp打包的时间戳。

欢迎一起讨论及测试。

**Comment by ywwyewenwei** [comment]
包序列号不联系----->包序列号不连续？

**Comment by 648540858** [comment]
> 讨论概述: 目前zlm在使用udp接收rtp包时，因udp网络天生原因，造成丢包，包序列号不联系，导致视频异常，现提出一种猜想解决方案，欢迎大家一起探讨下，是否可行。
> 
> 解决方法： 在接收rtp包时，通过缓存一下，重构包序列号、重构rtp打包的时间戳。
> 
> 欢迎一起讨论及测试。

这样的会导致延迟变高，如果能结合转码使用rtc播放，可以让延迟增加的不明显。可以作为一个配置项使用，公网一般还是建议使用tcp，rtsp/国标/rtmp都是。局域网才建议使用udp。这个时候丢包一般不会太严重。

**Comment by tsingeye** [comment]
> 

rtp over udp 现在绝大多数还是国标28181的场景，延迟具体多少 还需要根据测试值，但是可以优先保障视频，鱼和熊掌不可兼得嘛

**Comment by xia-chu** [comment]
你说的rtp包排序的抖动缓冲区已经有了

**Comment by PioLing** [comment]
RTCP进行媒体流实时丢包重传？
https://blog.csdn.net/dong_beijing/article/details/70185435
