### ISSUE TITLE
[技术咨询]请问webrtc功能依赖openssl1.0.0是否可以

### ISSUE THREAD

**Issue by pzhu10** [ZLMediaKit/ZLMediaKit#1340]
夏楚大神，
      您好，我们想集成 zlmeida 的webrtc的功能到项目中去，奈何项目中使用的多个模块是依赖openssl 1.0.0的（升级到openssl 1.1会有问题），请问zlmedia 的webrtc 是否依赖opensl1.0.0也可以，或者干脆不依赖opensl，只要前端页面可以播放webrtc流即可，不用https也可以

![image](https://user-images.githubusercontent.com/11349256/148183662-1dc01e6d-c4b3-4738-ad43-2aac0b8defb6.png)

**Comment by xia-chu** [comment]
不能 因为srtp/dtls都依赖openssl ，webrtc中这些都是必须的。
并且webrtc要求dtls版本1.1以上，这也决定了openssl版本1.1以上

**Comment by wasphin** [comment]
也可以单独编译一个 openssl 只给 ZLM 用, 静态连接或指定库加载路径都是可以的.
