### ISSUE TITLE
[BUG反馈] VS 2019 下编译出错

### ISSUE THREAD

**Issue by wanstonq** [ZLMediaKit/ZLMediaKit#1343]
ZLMediaKit\3rdpart\ZLToolKit\src\Util\logger.cpp(369,21): error C2039: "_moudle_name": 不是 "toolkit::LogContext" 的成员

**Comment by xia-chu** [comment]
更新下zltoolkit试试

**Comment by xia-chu** [comment]
不好意思 请更新下zltoolkit

**Comment by wanstonq** [comment]
> 

感谢
