### ISSUE TITLE
[BUG]mpegts音频dts不连续问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1344]
**bug现象**
拉取hls或者mpegts流时, 如果音频dts出现不连续情况.客户端观看时画面会频繁卡顿和跳动, 忽快忽慢.
当关闭转协议音频时, 也就是不输出音频时,画面正常, 不会跳动或者忽快忽慢.

当使用ffmpeg拉流并转推rtmp时, 一切正常.
使用的时最新4.4版本的ffmpeg, 之前在19年的时候,ffmpeg修复了dts不连续的问题.

**Comment by xia-chu** [comment]
dts不连续 也就是dts跳跃的问题 zlm应该是可以处理的，因为hls播放器又求相对时间戳的逻辑，可以处理时间戳大幅度跳跃的问题

**Comment by alexliyu7352** [comment]
是处理了, 但是结果就是客户端会不停的跳帧.
除非是过滤掉音频.就正常了
但是ffmpeg拉流转推后, 客户端播放很平滑

夏楚 ***@***.***> 于2022年1月10日周一 11:35写道：

**Comment by xia-chu** [comment]
这个问题不处理 源端要保证时间戳的正确性
