### ISSUE TITLE
[BUG]也不知道算不算bug, adts头的问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1345]
使用ffmpeg拉流在rtmp推流, 经常会出现
dumpAacConfig | 生成adts头失败:-1, aac config:
生成aac config失败, adts header: 70 82
之类的错误提示, 但是客户端经常能正常播放

但是有时候会提示
必须提供adts头才能mpeg-ts打包

这样客户端就没有办法正常播放了,

请教了media-server的作者, 他说"flv/mp4文件里的aac音频是不含adts头的。"
我也看了您的代码, 当不能生成adts头的时候, 如果有实际负载, 仍旧会读入到音频里面.
所以客户端可以正常播放,
但是为何有时候提示"必须提供adts头才能mpeg-ts打包"
这时候就播放就不正常了, 我输出都是输出hls和ts, 不输出rtmp.
这算是bug么?如何解决?

**Comment by xia-chu** [comment]
不算bug 我咋没遇到这个情况 ，ffmpeg的流应该很规范。没有adts头，就无法解码aac，写入ts也没意义



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2022年1月7日 18:37
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]也不知道算不算bug, adts头的问题 (Issue #1345)





 
使用ffmpeg拉流在rtmp推流, 经常会出现
 dumpAacConfig | 生成adts头失败:-1, aac config:
 生成aac config失败, adts header: 70 82
 之类的错误提示, 但是客户端经常能正常播放
 
但是有时候会提示
 必须提供adts头才能mpeg-ts打包
 
这样客户端就没有办法正常播放了,
 
请教了media-server的作者, 他说"flv/mp4文件里的aac音频是不含adts头的。"
 我也看了您的代码, 当不能生成adts头的时候, 如果有实际负载, 仍旧会读入到音频里面.
 所以客户端可以正常播放,
 但是为何有时候提示"必须提供adts头才能mpeg-ts打包"
 这时候就播放就不正常了, 我输出都是输出hls和ts, 不输出rtmp.
 这算是bug么?如何解决?

**Comment by xia-chu** [comment]
你可以rtmp抓个包给我 或给我下ffmpeg命令



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: alexliyu7352 ***@***.***&gt;
发送时间: 2022年1月7日 18:37
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]也不知道算不算bug, adts头的问题 (Issue #1345)





 
使用ffmpeg拉流在rtmp推流, 经常会出现
 dumpAacConfig | 生成adts头失败:-1, aac config:
 生成aac config失败, adts header: 70 82
 之类的错误提示, 但是客户端经常能正常播放
 
但是有时候会提示
 必须提供adts头才能mpeg-ts打包
 
这样客户端就没有办法正常播放了,
 
请教了media-server的作者, 他说"flv/mp4文件里的aac音频是不含adts头的。"
 我也看了您的代码, 当不能生成adts头的时候, 如果有实际负载, 仍旧会读入到音频里面.
 所以客户端可以正常播放,
 但是为何有时候提示"必须提供adts头才能mpeg-ts打包"
 这时候就播放就不正常了, 我输出都是输出hls和ts, 不输出rtmp.
 这算是bug么?如何解决?

**Comment by alexliyu7352** [comment]
"必须提供adts头才能打包"这个错误, 这玩意不好找阿, 我只是从日志上看到了大量还有用户反映推流上去客户端没办法播放来判断的, 但是没办法区分究竟是哪一路.

至于不能生成adts头到是很好找, 这个很经常有.网上随便找个视频推流就会有这个提示

./ffmpeg -err_detect ignore_err  -probesize 5000000 -analyzeduration 5000000 -fflags +discardcorrupt -re -i http://39.134.134.85/000000001000/1000000001000010355/index.m3u8 -c:v copy -c:a copy  -f flv rtmp://127.0.0.1/proxy/aoshi

**Comment by xia-chu** [comment]
我测试 FFmpeg推流aac的config  rtmp包会有两次 第一次是错误的，会导致打印`dumpAacConfig | 生成adts头失败:-1, aac config:`,第二次是正确的，能生成正确的adts头，不会导致ts生成失败

**Comment by alexliyu7352** [comment]
奇怪了, 的确我经常有时会看到打包ts失败, 没有adts头.

我继续跟踪下, 如果找到具体的流是哪一路在仔细调试下, 反馈给您.

说实话现在的日志太难找问题了.

**Comment by alexliyu7352** [comment]
错误仍旧会出现, 使用最新的代码日志上显示
```

2022-01-13 16:25:57.985 D media_server[22542-event poller 9] RtmpSession.cpp:17 RtmpSession | 828(127.0.0.1:23354) 
2022-01-13 16:25:57.985 I media_server[22542-event poller 9] RtmpProtocol.cpp:438 check_C1_Digest | check rtmp complex handshark success!
2022-01-13 16:25:58.076 T media_server[22542-event poller 9] RtmpProtocol.cpp:682 handle_chunk | MSG_SET_CHUNK:60000
2022-01-13 16:25:58.125 D media_server[22542-event poller 9] RtmpSession.cpp:126 operator() | 828(127.0.0.1:23354) publish 回复时间:0ms
2022-01-13 16:25:58.172 W media_server[22542-event poller 9] AACRtmp.cpp:25 getAacCfg | get aac config failed, rtmp packet is: 
af 00                                           ..              

```

**Comment by alexliyu7352** [comment]
另外日志还收到另外一个错误, 以前日志中没有的
```

2022-01-13 16:26:57.585 W media_server[22542-event poller 25] H264Rtmp.cpp:61 inputRtmp | get h264 sps/pps failed, rtmp packet is: 
17 00 00 00 00 01 42 c0 28 ff e4 00 21 67 42 c0 ......B.(...!gB.
28 95 90 07 80 22 7e 5c 04 40 00 00 fa 00 00 30 (...."~\.@.....0
d4 38 00 00 1e 84 80 00 3d 09 1b bc b8 28 00 21 .8......=....(.!
67 42 c0 28 95 90 07 80 22 7e 5c 04 40 00 00 fa gB.(...."~\.@...
00 00 30 d4 38 00 00 1e 84 80 00 3d 09 1b bc b8 ..0.8......=....
28 00 21 67 42 c0 28 95 90 07 80 22 7e 5c 04 40 (.!gB.(...."~\.@
00 00 fa 00 00 30 d4 38 00 00 1e 84 80 00 3d 09 .....0.8......=.
1b bc b8 28 00 21 67 42 c0 28 95 90 07 80 22 7e ...(.!gB.(...."~
5c 04 40 00 00 fa 00 00 30 d4 38 00 00 1e 84 80 \.@.....0.8.....
00 3d 09 1b bc b8 28 04 00 04 68 cb 8f 20 00 04 .=....(...h.. ..
68 cb 8f 20 00 04 68 cb 8f 20 00 05 68 cb 8f 20 h.. ..h.. ..h.. 
00                                              .               

```

**Comment by xia-chu** [comment]
> 另外日志还收到另外一个错误, 以前日志中没有的
> 
> ```
> 
> 2022-01-13 16:26:57.585 W media_server[22542-event poller 25] H264Rtmp.cpp:61 inputRtmp | get h264 sps/pps failed, rtmp packet is: 
> 17 00 00 00 00 01 42 c0 28 ff e4 00 21 67 42 c0 ......B.(...!gB.
> 28 95 90 07 80 22 7e 5c 04 40 00 00 fa 00 00 30 (...."~\.@.....0
> d4 38 00 00 1e 84 80 00 3d 09 1b bc b8 28 00 21 .8......=....(.!
> 67 42 c0 28 95 90 07 80 22 7e 5c 04 40 00 00 fa gB.(...."~\.@...
> 00 00 30 d4 38 00 00 1e 84 80 00 3d 09 1b bc b8 ..0.8......=....
> 28 00 21 67 42 c0 28 95 90 07 80 22 7e 5c 04 40 (.!gB.(...."~\.@
> 00 00 fa 00 00 30 d4 38 00 00 1e 84 80 00 3d 09 .....0.8......=.
> 1b bc b8 28 00 21 67 42 c0 28 95 90 07 80 22 7e ...(.!gB.(...."~
> 5c 04 40 00 00 fa 00 00 30 d4 38 00 00 1e 84 80 \.@.....0.8.....
> 00 3d 09 1b bc b8 28 04 00 04 68 cb 8f 20 00 04 .=....(...h.. ..
> 68 cb 8f 20 00 04 68 cb 8f 20 00 05 68 cb 8f 20 h.. ..h.. ..h.. 
> 00                                              .               
> ```

这个警告是新增的。出现这个错误可能是多个sps 导致的
