### ISSUE TITLE
[功能请求]webrtc建议接入quic协议

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1347]
[**描述该功能的用处，可以提供相关资料描述该功能**

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**](https://github.com/open-webrtc-toolkit/owt-sdk-quic)

就像是
https://github.com/open-webrtc-toolkit/owt-sdk-quic
可以使用quic做webrtc的传输层, 建议采纳.
直接使用quic, 免得自己写udp,还要考虑纠错, 重传等.

**Comment by xia-chu** [comment]
quic的支持 可以缓一缓 让子弹飞一会 因为现在quic标准都不统一 生态还没完善 我觉得不必急于引入，而且这么大一个特性，目前也没太多精力去做。

**Comment by alexliyu7352** [comment]
其实gquic就很稳定, 而且比iquic的实现要速度快很多, 也很稳定.

**Comment by alexliyu7352** [comment]
webrtc支持拉流么?
两个zlm之间如果使用webrtc的udp是否更快速?

**Comment by alexliyu7352** [comment]
其实就是zlm的webrtc是否可以做客户端使用.
这样就省掉了客户端还需要集成google的webrtc或者其他实现来播放.
因为并不是每个客户端都是浏览器, 很多都是专门的程序或者android之类的平台.

**Comment by xia-chu** [comment]
> 这样就省掉了客户端还需要集成google的webrtc或者其他实现来播放.
> 因为并不是每个客户端都是浏览器, 很多都是专门的程序或者android之类的平台.

目前不能 因为没实现ice-full功能 ，只能在公网上使用webrtc

**Comment by alexliyu7352** [comment]
了解了, 谢谢
