### ISSUE TITLE
[BUG]拉流丢包后的处理问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1348]
之前您说过, 当拉流上游出现问题或者网络波动导致拉流超时
    ```
if (!isTSPacket(data, len)) {
        WarnL << "不是ts包:" << (int) (data[0]) << " " << len;
        return 0;
    }
```

这里就有可能出现不是ts包的情况, 而目前的处理就是丢弃掉这些不是ts包的数据.
可是问题反映在客户端就呈现了诸如这样的错误

```
[h264 @ 0x7f145836afe0] error while decoding MB 29 11, bytestream -12
[h264 @ 0x7f145836afe0] concealing 1145 DC, 1145 AC, 1145 MV errors in P frame
[h264 @ 0x7f145883a4c0] error while decoding MB 37 34, bytestream -10
[h264 @ 0x7f145883a4c0] concealing 102 DC, 102 AC, 102 MV errors in P frame
[h264 @ 0x7f14580dfe60] error while decoding MB 15 17, bytestream -6
[h264 @ 0x7f14580dfe60] concealing 889 DC, 889 AC, 889 MV errors in P frame
[h264 @ 0x7f14584edc00] error while decoding MB 38 9, bytestream -8 
[h264 @ 0x7f14584edc00] concealing 1226 DC, 1226 AC, 1226 MV errors in P frame
```

我觉得是否是因为一帧的数据中有部分数据丢弃了导致的?
那么是否有必要增加一个判断, 如果帧不全那么就丢弃整个帧?这样会不会好一些?

**Comment by xia-chu** [comment]
报`不是ts包`的警告没问题，这个是TSSegment对象打印的，它存在的目的就是为了防止丢包没按照ts 包188字节整数倍丢弃导致的问题。

**Comment by xia-chu** [comment]
正因为丢弃了若干的ts包 导致H264帧不完整性 所以解码失败

**Comment by alexliyu7352** [comment]
是的没错, 所以我的意思是能否干脆丢弃这一帧, 这样客户端播放器至少会跳帧, 而不是卡住.

**Comment by alexliyu7352** [comment]
但是如何做呢?请指教

**Comment by xia-chu** [comment]
没法做到 除非ts解复用代码支持这个功能 但是这个是第三方库

**Comment by alexliyu7352** [comment]
https://github.com/ireader/media-server/commit/26ebc0fbec47030fdf79bd504c6d270396a84920
我像老陈提了issues, media-server作者好像已经处理了.
您看看, 如果有效请合并

夏楚 ***@***.***> 于2022年1月13日周四 11:25写道：

**Comment by alexliyu7352** [comment]
老陈的库上次我已经联系过, 新增了相关逻辑以及flag
```
MPEG_FLAG_PACKET_LOST			= 0x1000, // packet(s) lost before the packet(this packet is ok, but previous packet has missed or corrupted)
	MPEG_FLAG_PACKET_CORRUPT		= 0x2000, // this packet miss same data(packet lost)

```

可以解决这个问题.

**Comment by xia-chu** [comment]
> 老陈的库上次我已经联系过, 新增了相关逻辑以及flag
> 
> ```
> MPEG_FLAG_PACKET_LOST			= 0x1000, // packet(s) lost before the packet(this packet is ok, but previous packet has missed or corrupted)
> 	MPEG_FLAG_PACKET_CORRUPT		= 0x2000, // this packet miss same data(packet lost)
> ```
> 
> 可以解决这个问题.

可以提个pr上来

**Comment by alexliyu7352** [comment]
好的.

夏楚 ***@***.***> 于2022年2月22日周二 11:50写道：
