### ISSUE TITLE
[功能请求]aac、g711与opus互转

### ISSUE THREAD

**Issue by wanstonq** [ZLMediaKit/ZLMediaKit#1350]
**描述该功能的用处，可以提供相关资料描述该功能**
rtmp->rtc，aac、g711转opus
rtc->rtmp/http，opus、g711转aac

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
rtmp、rtp与webrtc兼容

**描述你期望实现该功能的方式和最终效果**
rtmp、rtp推流时，rtc可正常播放声音
rtc、rtp直播时，http可正常播放声音

**Comment by xia-chu** [comment]
这个要基于ffmpeg二次开发  暂时没这个计划

**Comment by wanstonq** [comment]
好的，知晓了，谢谢！

**Comment by SuperChrisliu** [comment]
> 这个要基于ffmpeg二次开发 暂时没这个计划

大佬建议增加这个音频转码的功能，在对讲的场景下，音频转码很需要啊

**Comment by xia-chu** [comment]
> > 这个要基于ffmpeg二次开发 暂时没这个计划
> 
> 大佬建议增加这个音频转码的功能，在对讲的场景下，音频转码很需要啊

有利益冲突 你懂得
