### ISSUE TITLE
macos m1 芯片编译失败 [功能请求]

### ISSUE THREAD

**Issue by linsmalldragon** [ZLMediaKit/ZLMediaKit#1351]
**描述该功能的用处，可以提供相关资料描述该功能**

**使用macbook pro m1 max 芯片按文档编辑失败,是否可以在文档里增加m1芯片如何编辑的指导**

**Comment by xia-chu** [comment]
编译失败没编译器日志吗？

**Comment by wl19911028111** [comment]
我这macbook pro  M1编译通过了，如果有问题可以相互探讨下

**Comment by xia-chu** [comment]
我是m1版本的macbook pro， 每天编译
