### ISSUE TITLE
[技术咨询]请问是否支持集群方式部署

### ISSUE THREAD

**Issue by wangfly80** [ZLMediaKit/ZLMediaKit#1352]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by alexliyu7352** [comment]
其实可以集群化部署, 只是有些麻烦, 因为zlm目前并没有edge模式.
所以需要你上层系统来进行调度.
具体就是利用hook接口来实现.

边缘服务器接到请求后, 通过hook接口返回上层服务器, 上层服务器通知边缘服务器从某个上游节点进行拉流.
这样就可以实现边缘服务器了.
推流也是一样的, 边缘服务器接收到推流后会触发hook, 然后上层服务器调度推送到哪个节点.

就是有一点点麻烦而以.

**Comment by xia-chu** [comment]
zlm要新增支持下溯源功能 也就几十行代码的事情 zlm内置的hook api已经有按需拉流的范例，这个就是溯源功能。

**Comment by xia-chu** [comment]
不过我认为基于配置文件的溯源功能太不灵活了。

**Comment by alexliyu7352** [comment]
恩, 目前这个我觉得也够用了, 上层系统调度下就可以了

**Comment by xia-chu** [comment]
已经支持： be77f84315f9a98c943d186fb2caaf167d63863b
