### ISSUE TITLE
sdl2安装检测

### ISSUE THREAD

**Issue by wl19911028111** [ZLMediaKit/ZLMediaKit#1353]
make -j4时会在play文件夹中检测sdl2是否安装，但是之前并没有add这个lib，应在根目录的cmake中添加如下才能找到sdl2目录并编译通过
/***************************************************************************************/
#查找sdl2是否安装
find_package(SDL2 QUIET)
if (SDL2 AND ENABLE_SDL2)
    message(STATUS "found library:${SDL2_LIBRARIES},ENABLE_SDL2 defined")
    include_directories(${SDL2_INCLUDE_DIR})
    add_definitions(-DENABLE_SDL2)
    list(APPEND LINK_LIB_LIST ${SDL2_LIBRARIES})
endif ()
/****************************************************************************************/

**Comment by xia-chu** [comment]
player/CMakeList.txt里面有判断是否安装sdl2等依赖库的 如果没安装 会return，不会编译的，所以没问题
