### ISSUE TITLE
[技术咨询]linux 

### ISSUE THREAD

**Issue by wsmGo** [ZLMediaKit/ZLMediaKit#1354]
ZLMediaKit 守护进程启动失效
./MediaServer -d &  
关闭连接窗口 程序自动关闭

**Comment by wsmGo** [comment]
好了

**Comment by wasphin** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%90%AF%E5%8A%A8%E4%B8%8E%E5%85%B3%E9%97%AD

**Comment by wsmGo** [comment]
谢谢
