### ISSUE TITLE
[技术咨询]ZLMediaKit推流测试

### ISSUE THREAD

**Issue by wsmGo** [ZLMediaKit/ZLMediaKit#1355]
ZLMediaKit推流测试
server端布在linux上 mac使用 ffmpeg推流 返回401 
 method ANNOUNCE failed: 401 Unauthorized
Could not write header for output file #0 (incorrect codec parameters ?): Server returned 401 Unauthorized (authorization failed)
Error initializing output stream 0:0 --

**Comment by xia-chu** [comment]
zlm开启推流鉴权hook才会这样

**Comment by frlmoney** [comment]
大佬推流鉴权如何关闭？

**Comment by frlmoney** [comment]
> zlm开启推流鉴权hook才会这样

大佬推流鉴权如何关闭？

**Comment by xia-chu** [comment]
> > zlm开启推流鉴权hook才会这样
> 
> 大佬推流鉴权如何关闭？

自己看配置文件注释
