### ISSUE TITLE
怎么用C API 实现WEBRTC推流？

### ISSUE THREAD

**Issue by pango99** [ZLMediaKit/ZLMediaKit#1356]
**咨询的功能模块**
- c api 推流

**咨询的具体内容和问题**
请问怎么用C API 实现WEBRTC推流？推流的URL是什么?

**Comment by xia-chu** [comment]
zlm的webrtc只支持服务器模式 不支持客户端，因为ice实现了ice-lte，所以不支持在nat内运行
