### ISSUE TITLE
[BUG] rtsp udp组播拉流崩溃

### ISSUE THREAD

**Issue by JayChen0519** [ZLMediaKit/ZLMediaKit#1357]
**现象**
- 奔溃
- 日志截图，日志文件(2022-01-11_00.log)在附件中
![image](https://user-images.githubusercontent.com/97513129/148916564-2174ebfc-dd4f-4b34-a774-6773949533aa.png)
- 函数的调用栈：
![image](https://user-images.githubusercontent.com/97513129/148916768-74120b8f-7999-462f-8bf3-1673ed6a7e84.png)
-定位代码的位置是RtspPlayer::onBeforeRtpSorted函数这行代码导致奔溃，自己在代码添加了注释，与master分支代码行数不一致：
![image](https://user-images.githubusercontent.com/97513129/148918385-8bbea1c5-a701-4a8d-85d9-77f755237c65.png)

**bug产生时的使用场景**
- 代理拉流，通过addStreamProxy拉取摄像机的视频流，进行截图，会导致奔溃。

**bug是否可以复现，怎么复现**
- 调用addStreamProxy接口，以组播的方式获取摄像机的视频流，进行截图

**zlm代码git commit hash值**
- 15d84fdf765595c98bf37b4cf4238d220a2095d2

**操作系统环境**
- 64位？
- Intel(R) Xeon(R) Gold 6161 CPU @ 2.20GHz 8核。

附件：
[2022-01-11_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/7845450/2022-01-11_00.log)

**Comment by xia-chu** [comment]
流地址能否给下？谢谢

**Comment by JayChen0519** [comment]
> 流地址能否给下？谢谢

可能提供不了，摄像机是部署在生产环境内网中。我可以提供抓包的数据吗？

**Comment by xia-chu** [comment]
你这个代码修改太大了 请使用最新版未修改代码先测试下。
我分析了下代码，你这个是rtp over udp模式拉流，这个问题是_rtcp_sock清空导致，也就是关闭播放器时才会触发这个问题。
但是在RtspPlayer::teardown函数中，在清空_rtcp_sock前，就会清空_sdp_track，这将导致调用handleOneRtp时就会崩溃。
逻辑上解释不通，你就算提供抓包，也很难定位到问题。

**Comment by xia-chu** [comment]
另外 我想说的是 你们这些有能力大幅修改定制代码 却不提交pr 甚至star也不愿意给 改出问题了 又来寻求帮助 我认为这不是高尚的行为。

**Comment by xia-chu** [comment]
从日志内容 和crash文件代码行定位 可以发现你代码修改幅度很大 从这点看 怎么能保证是不是你本身修改导致的bug呢？

**Comment by JayChen0519** [comment]
不好意思，定制代码是前人留下的，我接手不久。上述问题，我会使用最新版本测试确认是否存在问题，感谢作者的指导。

**Comment by alexliyu7352** [comment]
> 另外 我想说的是 你们这些有能力大幅修改定制代码 却不提交pr 甚至star也不愿意给 改出问题了 又来寻求帮助 我不认为这是件高尚的行为。

说的没错, 开源项目作者维护不易, 既然有能力修改, 那么为什么不把修改过的不涉及保密的部分合并到主分支中呢?
这样也能尽量减少bug.而且可以大家一起维护.

一个开源项目想要良性发展下去, 不能光靠作者本身一个人.更需要大家的支持与协助.

建议作者, 有些没提交pr过的又自己修改过代码的就不要回复了.除非他把代码开源出来, 这样一方面便于你寻找代码中的问题, 另一方面可以回馈这个项目本身.
