### ISSUE TITLE
[技术咨询]线程切换问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1358]
我新加了一个协议, 引用了第三方库.
由于新协议拉流自己有自己的socket, 我只有多线程使用.

是否在我新协议的每个回调中都需要使用poller--->async来确保回调后调用zlm都在一个线程中呢?

**Comment by xia-chu** [comment]
> 我新加了一个协议, 引用了第三方库. 由于新协议拉流自己有自己的socket, 我只有多线程使用.
> 
> 是否在我新协议的每个回调中都需要使用poller--->async来确保回调后调用zlm都在一个线程中呢?

你只要确保你的代码没线程安全问题就行，至于被回调者的代码能不能线程安全是他的事情。
当然，你想确保他的线程安全也行，还是看你自己的选择

**Comment by alexliyu7352** [comment]
明白了
