### ISSUE TITLE
请问是否支持输出http的webrtc流[技术咨询]

### ISSUE THREAD

**Issue by 3703liu** [ZLMediaKit/ZLMediaKit#1359]
请问想使用输出的http，应该怎么设置一下？目前输出的https的webrtc流，需要使用证书，在内网使用的时候，使用默认证书，浏览器会报警，ERR_CERT_COMMON_NAME_INVALID，提示不安全的链接。

**Comment by xia-chu** [comment]
webrtc播放一直不需要https的。

**Comment by xia-chu** [comment]
> 浏览器拉webrtc流播放没有声音?(流原本是有声音的)

源流的音频webrtc不支持，webrtc只支持opus 711，不支持aac

**Comment by 3703liu** [comment]
多谢，可以直接用http播放，已经解决。

**Comment by xxxxxxbin6** [comment]
楚哥,我最近碰到个问题,在新版本浏览器上可以拉取webrtc的流并播放,但是在40版本的谷歌浏览器上能拉到流,但是播放的时候能弹出video标签,但是是黑屏的,请问你清楚吗?

**Comment by xia-chu** [comment]
> 楚哥,我最近碰到个问题,在新版本浏览器上可以拉取webrtc的流并播放,但是在40版本的谷歌浏览器上能拉到流,但是播放的时候能弹出video标签,但是是黑屏的,请问你清楚吗?

不清楚 因为我没40版本的chrome

**Comment by xia-chu** [comment]
你可以给个安装包 或者告诉我老版本的下载方式

**Comment by xxxxxxbin6** [comment]
可以,可以加个微信吗,xb19970720,我通过微信发给你,或者你微信多少?

**Comment by xia-chu** [comment]
github上支持发送zip文件 你直接这里传就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xxxxxxbin6 ***@***.***&gt;
发送时间: 2022年3月2日 09:27
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] 请问是否支持输出http的webrtc流[技术咨询] (Issue #1359)





 
可以,可以加个微信吗,xb19970720,我通过微信发给你,或者你微信多少?

**Comment by LemonTao76** [comment]
楚哥，chrome40浏览器压缩包超过100M，git上传不了，下面是网盘链接，里面有配置指引文件，需要配置一下访问目标路径，不然会直接打开高版本chrome浏览器

链接：https://pan.baidu.com/s/1w9ioMcAukARZ7DsTnmLb_Q 
提取码：XCNB

**Comment by rmokerone** [comment]
chrome40 浏览器上运行推流，发现DTLS握手过程中，浏览器不会发送flight5，不知道具体原因是什么？请楚哥帮忙分析下：

如下图：
![image](https://user-images.githubusercontent.com/3683271/156510260-e1671300-bcf1-4460-b455-435eafc88b43.png)

chrome 40版本 推流过程8000端口抓包如下：

[chrome40.pcap.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8175481/chrome40.pcap.zip)


正常播放的高版本浏览器，推流工程8000端口抓包如下：
[chrome_new.pcap.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8175484/chrome_new.pcap.zip)

@xia-chu

**Comment by rmokerone** [comment]
验证过了，加密套件都选定成0xc013后，依旧是p2p webrtc可以播放，zlm的webrtc不能推流。
[chrome40_webrtc_ciphers_set.pcap.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8182741/chrome40_webrtc_ciphers_set.pcap.zip)
