### ISSUE TITLE
[技术咨询]关于RTSP音视频推流时的音频问题

### ISSUE THREAD

**Issue by NagatoRailgun** [ZLMediaKit/ZLMediaKit#1367]
你好，关于rtsp音视频推流的时候有一点问题不解，

我这边通过mk_media_create创建了一个媒体media
然后通过mk_media_init_video给这个media媒体创建了一个h264视频流
再通过mk_media_init_audio给这个media媒体创建了一个G711A音频流
之后开启了pusher推流。

我另外有编码器编码音视频，编码完成以后
通过mk_media_input_h264向media媒体写入h264视频帧
通过mk_media_input_audio向media媒体写入G711A音频帧

当我只使用mk_media_input_h264时，我能够在客户端播放出流畅的音视频，并且能够完整播放完成，这时我看到即使没有mk_media_input_audio，我也能在客户端收到静音音频
但当我把编码后的音频通过mk_media_input_audio写入media媒体后，程序变得非常不稳定，我能够播放个5-6秒音视频后，服务端就会在mk_media_input_audio中崩溃（必现），我确认到输入都不为空。请问我应该对哪个方向进行修改才能避免这种崩溃呢？

**Comment by NagatoRailgun** [comment]
有可能是音视频多线程编码结果一起写入造成崩溃，在input方法上加锁后未出现崩溃

**Comment by xia-chu** [comment]
必须加锁的 api不是线程安全的
