### ISSUE TITLE
关于开启录制功能之后的文件名的那个时间[技术咨询]

### ISSUE THREAD

**Issue by mozeqiu** [ZLMediaKit/ZLMediaKit#1371]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- 
录制之后保存的那个时间文件名是摄像头的时间，还是我流媒体服务器机器的时间呢，我需要按照时间来取出某一个录制文件，要求比较精确
![1642154522(1)](https://user-images.githubusercontent.com/49837457/149497083-deda8b53-b522-4b6a-9c9c-acdc05d5c711.png)

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
肯定是服务器时间啊 服务器怎么能从流里面获取到ntp时间了？
