### ISSUE TITLE
[技术咨询]如何能确保切换到不同的线程

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1373]
我在hls拉流中想要采用多线程同时下载几个分片数据.
大佬, 可能您觉得没有必要. 
但是如果一些网络不好的地方, 比如非洲, 在不采用诸如kcp, quic, srt等协议的情况下, 可能多线程分片来确保拉流的及时性是没办法的办法了.

总之, 我现在的流程是, 开启需要多个线程来下载hls分片.
其中主线程, 下载的数据边下载边提交到decoder, 其余线程下载的应该各自有一个缓存.
当主线成下载完成后, 等待其余线程下载完成.
并把其余线程的缓存按照顺序提交到decoder中.
然后在开始下一个循环下载.

这个合不合理, 有没有必要另说.
我现在想要知道的是, 理论上zlm是一个异步的框架, 也就是我不需要开多个线程来进行处理. 
一个线程也应该也可以同时下载多个分片.
但是实际上我感觉这样下载好像速度起不来?是否底层socket那里是同步的?
所以, 我就给每个下载器使用EventPollerPool::Instance().getPoller(false)分配了一个新的poller, 并且Socket::createSocket(poller, true)创建了新的socket, 但是感觉还是在同一个线程中.并没有随着分配了新的poler而切换到另一个线程中.

如何才能准确的切换到其他线程中呢?还是不需要?底层socket也是异步的?支持同一个线程中多个io请求?

**Comment by xia-chu** [comment]
网速的快慢重来都跟线程数没关系 照你这么说 srs，node.js不要做服务器了

**Comment by alexliyu7352** [comment]
我的意思是, 在同一个poller中, 也就是同一个事件循环中, 我开两个同时下载.
底层会不会有阻塞?

**Comment by xia-chu** [comment]
为什么会阻塞？非阻塞socket/多路复用 原理了解下
