### ISSUE TITLE
[技术咨询]绝对时间戳

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1375]
之前看大佬的提交, 拉流改成了绝对时间戳.
那么为何hls拉流中
_stamp[frame->getTrackType()].revise(frame->dts(), frame->pts(), dts, pts);
这个不是仍旧使用的是想对时间戳么?

**Comment by xia-chu** [comment]
我还没删除相对时间戳的逻辑啊

**Comment by xia-chu** [comment]
hls拉流应该改成绝对时间戳了
