### ISSUE TITLE
webrtc 交换SDP错误

### ISSUE THREAD

**Issue by mrlaozeng** [ZLMediaKit/ZLMediaKit#1377]
Assertion failed: (sscanf(str.data(), "%32[^ ] %" "u" " %15[^ ] %" "u" " %31[^ ] %" "hu" " typ %15[^ ]", foundation_buf, &component, transport_buf, &priority, address_buf, &port, type_buf) == 7, 解析sdp candidate 字段失败:2874545870 1 udp 2122255103 2001::348b:fb58:10f6:d151:4822:ad04 53959 typ host generation 0 network-id 2 network-cost 50), function parse, file /opt/ZLMediaKit/webrtc/Sdp.cpp, line 684.

**Comment by wasphin** [comment]
还没支持 ipv6。
