### ISSUE TITLE
[功能请求]http(s)下载fmp4文件总时长显示问题

### ISSUE THREAD

**Issue by TFlyerMedia** [ZLMediaKit/ZLMediaKit#1378]
使用ZLMediaKit通过http(s)方式下载fmp4文件，存储为本地文件后，用vlc或win10系统自带播放器进行播放时无法显示录像文件总时长,看能否在接口中增加参数(使可以传入录像总时长),以解决本地fmp4文件无法正常显示播放总时长的问题,谢谢!

**Comment by xiongguangjie** [comment]
不行，fmp4 直播流是是绝对时间戳，你要正确的时间需要录像，然后下载下来

**Comment by xia-chu** [comment]
fmp4直播是先生成好了 所有人都共享一份fmp4, 如果每个人时间戳都从0开始播放 那么都要为每个人生成一份fmp4,这个开销、代价、成本都是不可接受的

**Comment by xia-chu** [comment]
另外fmp4直播 他是渐进的 在播放完毕前是无法知道总时长的，这个跟ts/flv都一样。也只有这种容器格式才能实现直播。

**Comment by xia-chu** [comment]
不过一般播放器会先seek完文件所有内容，获取总时长，这样代价比较高，但是也是唯一能实现获取文件总时长的办法
