### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by xslwm** [ZLMediaKit/ZLMediaKit#1379]
请问大佬，本项目有没有将内存中RGB图片数据编码成h264格式实时进行rstp推流的例子呢，还有我通过tcp收到的MP4文件数据（接收速率可能比较慢）进行rtsp推流的例子

**Comment by xia-chu** [comment]
zlm的推流例子使用门槛比较高 建议你直接用FFmpeg推流 FFmpeg直接包含编码和推流 使用的资料也很多的

**Comment by xia-chu** [comment]
mk_media_input_yuv 这个支持yuv编码转h264的mediasource，
mk_pusher对象绑定一个这个mediasource对象就能开始推流，但是使用比较复杂

**Comment by xslwm** [comment]
研究了FFmpeg的编解码，但是FFmpeg没有rtsp服务端，zlm创建一个rtsp服务端有文件流的接口吗，像vlc这种的
![Screenshot_2022-01-18-19-05-10-91_5b19eeae754b18421d48054e4a8744e7](https://user-images.githubusercontent.com/26349693/149925788-baa06bdf-1399-4d7d-b8f6-63caaea6f230.jpg)

**Comment by xia-chu** [comment]
zlm支持mp4文件 rtsp点播，你把文件放在www/record目录下即可 播放url请看wiki url规则篇

**Comment by xslwm** [comment]
这个我试过了可以的，只是我这边的视频文件是边收取就要推流出去

**Comment by xia-chu** [comment]
那就是你一边录制一遍推流吧？你录制的时刻 文件应该还不可用的，你既然都录制了 那应该能把这个Frame输入到zlm 这样也行啊

**Comment by xslwm** [comment]
不是录制的，是别人通过tcp发过来的MP4等视频文件

**Comment by xslwm** [comment]
只要视频的mov在文件头部，边接收边推流和播放是可以的吧

**Comment by xia-chu** [comment]
> 只要视频的mov在文件头部，边接收边推流和播放是可以的吧

理论上可以 不过你要深度定制下mp4解析器 在数据量不够时 需要阻塞下read线程。

**Comment by xslwm** [comment]
是的，我试了vlc库的数据回调函数，是能正常播放的，
/**
 * Callback prototype to read data from a custom bitstream input media.
 *
 * \param opaque private pointer as set by the @ref libvlc_media_open_cb
 *               callback
 * \param buf start address of the buffer to read data into
 * \param len bytes length of the buffer
 *
 * \return strictly positive number of bytes read, 0 on end-of-stream,
 *         or -1 on non-recoverable error
 *
 * \note If no data is immediately available, then the callback should sleep.
 * \warning The application is responsible for avoiding deadlock situations.
 * In particular, the callback should return an error if playback is stopped;
 * if it does not return, then libvlc_media_player_stop() will never return.
 */
typedef ssize_t (*libvlc_media_read_cb)(void *opaque, unsigned char *buf,
                                        size_t len);

我深度定制的话能力不够哦，谢谢大佬的耐心解答(*^O^*)
