### ISSUE TITLE
[BUG] 使用docker镜像panjjo/zlmediakit：1.2.8(2022-01-07) 没有通过webrtc测试

### ISSUE THREAD

**Issue by lwy1111111** [ZLMediaKit/ZLMediaKit#1380]
**bug现象**
- 使用docker镜像panjjo/zlmediakit：1.2.8(2022-01-07) 并按照文档要求配置webrtc端口及相关参数 。启动是并没有发现8000端口，有10000的端口，导致webrtc使用不了
![5b038f0eb7f54ee9f7c21fb4e5e92dc](https://user-images.githubusercontent.com/41666805/150102517-3cdb351c-c6cb-4b1b-8202-eaea152a61af.jpg)

**Comment by xia-chu** [comment]
说明docker没编译webrtc功能



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lwy1111111 ***@***.***&gt;
发送时间: 2022年1月19日 17:30
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] 使用docker镜像panjjo/zlmediakit：1.2.8(2022-01-07) 没有通过webrtc测试 (Issue #1380)





 
bug现象
  
使用docker镜像panjjo/zlmediakit：1.2.8(2022-01-07) 并按照文档要求配置webrtc端口及相关参数 。启动是并没有发现8000端口，有10000的端口，导致webrtc使用不了

**Comment by xia-chu** [comment]
docker是委托第三方维护的 所以可能更新不及时，另外也可能特性不全。
