### ISSUE TITLE
[功能请求]hls平滑生成

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1384]
大佬, 之前不是在http拉流中你要去掉平滑的相关逻辑么?
我觉得可以去掉, 但是在hls生成时需要增加平滑生成hls的逻辑.
避免网络抖动造成的m3u8索引文件更新频率不稳定.

**Comment by xia-chu** [comment]
这个不考虑做，也就hls拉流不平滑，拉流hls再生成hls 这个操作本身就比较迷，我觉得还不如直接用Nginx代理

**Comment by alexliyu7352** [comment]
拉ts流阿, 不是拉hls生成hls, 是拉ts生成hls

**Comment by xia-chu** [comment]
http-ts直播咋可能不平滑？
