### ISSUE TITLE
[功能请求]解析Nginx反向代理情况下真实IP地址识别

### ISSUE THREAD

**Issue by 174001602** [ZLMediaKit/ZLMediaKit#1388]
**描述该功能的用处，可以提供相关资料描述该功能**
Nginx再反向代理的情况下一般会加入X-Forwarded-For头标识告诉被代理者真实IP来源
proxy_set_header X-Forwarded-For

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
目前zlm 对nginx代理的情况 ip 来路识别是 nginx 代理服务器ip

**描述你期望实现该功能的方式和最终效果**
希望可以增强识别代理情况下的 来源真实ip 放到hook类的接口了 给予反馈

**Comment by xia-chu** [comment]
这个功能很早之前讨论了下，就是客户端可能伪造 X-Forwarded-For，它可能在http头中添加这个字段。
怎么确定这个是反向代理服务器的添加的http头，很难判定，触发这样，如果http请求端的ip是127，那么zlm就认X-Forwarded-For字段，但是如果nginx不再本机而是在局域网其他机器上 又会有问题

**Comment by wasphin** [comment]
可以先考虑加个选项，支持放代理后这一功能后再考虑怎么保证的问题。如果部署是在代理后就打开选项，代理负责保证该字段是由它写的；如果不是部署在代理后，可以直接关掉选项。

**Comment by xia-chu** [comment]
@174001602 已经实现，抱歉啊；请在配置文件中修改 `forwarded_ip_header=X-Forwarded-For`
