### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by doitsjz** [ZLMediaKit/ZLMediaKit#1392]
- fMP4
  - 支持ws[s]-fmp4直播 : 这个如何播放呢，有对应的播放器代码么，直接用js 写播放器，播放不了；ws-fmp4 怎么用vlc播放呢？

**Comment by doitsjz** [comment]
同样：- 支持ws[s]-ts直播 ：浏览器端和VLC端如何播放呢？

**Comment by xia-chu** [comment]
https://github.com/numberwolf/h265web.js
https://github.com/v354412101/wsPlayer

了解一个项目时，阅读readme是个基本的要求

**Comment by doitsjz** [comment]
谢谢，看了前面，没看后面

**Comment by doitsjz** [comment]
@xia-chu  谢谢大神，学习了
