### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xianminpan** [ZLMediaKit/ZLMediaKit#1394]
**bug现象**
拉流时，后端出现错误
![image](https://user-images.githubusercontent.com/29617434/150923697-1451d008-5dca-466c-a7fe-529ee7dd8f2f.png)

**bug产生时的使用场景**
拉流

**bug是否可以复现，怎么复现**
可以

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
物理机：centos 7.6， (docker：Ubuntu 20.04 LTS)

**Comment by xianminpan** [comment]
这个问题在换不同的机器部署时大概率会出现。

**Comment by xia-chu** [comment]
你给的信息相当于没给
