### ISSUE TITLE
[技术咨询]rtmp流录制的mp4 没有mov atom数据

### ISSUE THREAD

**Issue by 1983094983** [ZLMediaKit/ZLMediaKit#1396]
录制mp4功能

咨询一个问题：
1.通过之前的issure了解到录制的MP4数据的mov atom数据是在stopRecord之后写入的，这个触发的代码是如何实现的？ 本人找了一遍代码没有发现写入MP4 header的地方
情况：mingw & cmake 编译，调用录制接口录制rtmp 的流，停止录制后发现mp4没有mov atom数据。 有可能是我配置或者是编译的原因导致的吗（编译时没有安装openssl/sdl2/ffmpeg)

**Comment by xia-chu** [comment]
你可以在mov_writer_destroy中打个断点，zlm是通过对象析构隐式调用mov_writer_destroy的

**Comment by 1983094983** [comment]
大概是编译器编译的问题， 我换到msys2 编译后录制MP4没有问题了(在mingw环境中编译的调用到了mov数据的写入，至于为什么文件中没有我就不知道了)

**Comment by xia-chu** [comment]
#970
