### ISSUE TITLE
[技术咨询]WEBRTC播放问题

### ISSUE THREAD

**Issue by doitsjz** [ZLMediaKit/ZLMediaKit#1399]
MediaServer 启动成功后，浏览器访问视频不成功，求救大神，谢谢
![1643165690(1)](https://user-images.githubusercontent.com/5165178/151096471-3d705b6f-8a9a-4b07-8aa7-424f57393ed0.png)

![1643165704(1)](https://user-images.githubusercontent.com/5165178/151096483-152bbfee-468b-4b7d-8e81-30274da30184.png)

**Comment by doitsjz** [comment]
可以了

**Comment by mayomeng** [comment]
我也遇到这个问题了，请问是怎么解决的呀
