### ISSUE TITLE
[技术咨询]摄像头拉流截图/index/api/getSnap偶现花屏等问题

### ISSUE THREAD

**Issue by LongTraveller** [ZLMediaKit/ZLMediaKit#1402]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
拉流截图功能/index/api/getSnap
**咨询的具体内容和问题**
- 对于多个摄像头，调用拉流接口拉取nvr的rtsp的流进行截图，偶现以下问题：
- 1. 截图花屏
- 2. 截图显示时间与实际抓图时间相隔很远（以下图例是14点拉流截图结果，显示时间为昨天晚上23:45）
- 3. 连续截图，返回同一个图片（例如一下图例，在14:00、14:01、14:02拉流，均得到同一张图，请求设置的拉流截图缓存时间为15s)
- 
<img width="759" alt="拉流截图异常" src="https://user-images.githubusercontent.com/55306718/151137011-f5b04a15-5d92-471a-bcc7-a91a121dbf06.png">

- ffmpeg.snap=%s -rtsp_transport tcp -y -i %s -ss 1 -vframes 1 -s 1920x1080 -f image2 -t 1 %s

- 咨询问题：是否是snap设置有问题呢？可以请教优化吗？
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
截图功能是zlm调用FFmpeg命令实现的 你需要观察下zlm的日志和FFmpeg的日志 花屏问题是FFmpeg截图就花屏了。
至于你说的 返回之前的截图 原因是截图失败了 或者还没到超时时间
