### ISSUE TITLE
[BUG]ZLM运行bug

### ISSUE THREAD

**Issue by hwlong2019** [ZLMediaKit/ZLMediaKit#1403]
**bug现象**
- 有文件缺失、找不到、卸载问题
![ZLM运行bug](https://user-images.githubusercontent.com/49428747/151139794-73dd9e42-06ce-48fa-bbdb-fb62aa2cd0cc.png)

1. 64位win7环境

2. 通过git命令获取项目代码：
git clone --depth 1 https://gitee.com/xia-chu/ZLMediaKit
cd ZLMediaKit
git submodule update --init

3. 使用vs2019软件，C++桌面开发
![vs2019配置](https://user-images.githubusercontent.com/49428747/151139386-88e358d0-ac2c-4200-bf58-fe9261b070b0.png)

**Comment by xia-chu** [comment]
老弟 你确定这是zlm的bug？ 你确定你看了基本的wiki文档吗

**Comment by xia-chu** [comment]
这个issue我直接关闭了 你也别回复了 免得我喷你
