### ISSUE TITLE
IPV6 Support  is now inevitable - ZLMediaKit should support ipv6

### ISSUE THREAD

**Issue by xoraingroup** [ZLMediaKit/ZLMediaKit#1406]
ZLMediakit is awesome in all aspects except that its not working with ipv6. 

There is already an issue at https://github.com/ZLMediaKit/ZLMediaKit/issues/576 and it has a PR, I would love to see the PR Merged or at least add ipv6 functionality.

The reason is in IPV4 is exhausting and ipv6 is already rolling out and now its important time for ZLMediaKit to support this as well. 

Waiting for update :)

**Comment by xoraingroup** [comment]
Anything on this?

**Comment by xia-chu** [comment]
IPv6 must be supported, but it may be delayed. There are a lot of things todo. it's the chinese new year recently, so the reply is late

**Comment by xia-chu** [comment]
We need your help! 
We need your code!
We need your pull request!

**Comment by xoraingroup** [comment]
I am not good in C/C++ language. I can help in testing and providing reports.

**Comment by xoraingroup** [comment]
If that can help. :)

**Comment by xia-chu** [comment]
IPV6 now supported!
