### ISSUE TITLE
[BUG] 最新版出现画面抖动

### ISSUE THREAD

**Issue by jianjunchang** [ZLMediaKit/ZLMediaKit#1408]
**bug现象**
- 服务器未见异常日志
- 日志正常
- 未做源码调试，只是简单的起服务应用。

**bug产生时的使用场景**
- 按照 wiki->“ZLMediaKit推流测试”一节中的说明进行推流测试
- 1、sudo ./MediaServer
- 2、ffmpeg -re -i "/path/to/big_buck_bunny.mp4.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8080/live/test
- 3、直接在谷歌浏览器打开http://localhost:8080/live/test.live.mp4
- 4、发现画面抖动的很厉害。
- 5、切换回以前clone下来的代码编译的ZLMediaKit重复上述操作，画面流畅（之前用过的版本一直是正常的，就是最近用最新的代码编译的版本出现了抖动现象）
- 6、以下是新老版本的版本号（左边是老版本，右边是新版本）：
![微信图片_20220202102819](https://user-images.githubusercontent.com/6183488/152084100-6ace518b-db35-4235-b45d-331e6addafad.jpg)

抖动的视频
https://user-images.githubusercontent.com/6183488/152085166-ff5ff7ee-c8c8-4982-a69a-9799db7e3b1b.mp4

正常的视频
https://user-images.githubusercontent.com/6183488/152085195-0f0bb3e3-99aa-42cf-9a9b-921d831a92d9.mp4

**bug是否可以复现，怎么复现**
- 每次都一样复现

**zlm代码git commit hash值**
- 
![image](https://user-images.githubusercontent.com/6183488/152084292-8d762eca-a1ee-42e1-8e85-ce69fdeea843.png)

**操作系统环境**
- 系统：Windows 11 家庭中文版，64位？
- cpu：Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz

**Comment by jianjunchang** [comment]
之前用的windows 11系统中的linux子系统运行的zlm，后来在单独的linux系统中运行，没有发现这个问题，也许是只有在linux子系统中才会出现的问题，linux子系统应该与独立的linux环境存在差异且不常用，所以关闭此issue。

**Comment by xia-chu** [comment]
嗯 昨天我也测试了下chrome播放zlm的fmp4 确实没这个问题
