### ISSUE TITLE
一次崩溃问题[BUG]

### ISSUE THREAD

**Issue by guxinyue** [ZLMediaKit/ZLMediaKit#1410]
**bug现象**
- bug服务崩溃，
-第2天发现视频看不了才发现崩溃
 看日志先
  1、开始是rtp丢包，，
  2、ps解析异常
  3、remain data size is too huge
  4、后来服务就停了
 
![1643955162(1)](https://user-images.githubusercontent.com/20881250/152481411-db006f0e-f82a-42f8-9963-922874c50b18.jpg)

![1643955027(1)](https://user-images.githubusercontent.com/20881250/152481369-7d64d53a-f364-4e8f-8443-b583cb666b6e.jpg)
![1643955101(1)](https://user-images.githubusercontent.com/20881250/152481393-bac073d3-a270-42a6-8358-8ec4fabbcb82.jpg)

**bug产生时的使用场景**
- 第2天发现视频看不了才发现崩溃 

**bug是否可以复现，怎么复现**
- 不可复现，第一次发现

**zlm代码git commit hash值**
-  git hash: edbbaa45

**操作系统环境**
- Ubuntu 18.04 LTS 64位
- 8核 Intel(R) Xeon(R) Bronze 3206R CPU @ 1.90GHz

**Comment by xia-chu** [comment]
有core或crash文件生成吗？看看崩溃函数栈

**Comment by guxinyue** [comment]
没有相关文件生成，改成启在后台再观察一下

**Comment by xia-chu** [comment]
可以实时更新代码了 第三方代码之前有点bug
