### ISSUE TITLE
ZLMediakit可以直接接收通过SDP协商后推送的RTP的音频流（仅包含音频的）吗？

### ISSUE THREAD

**Issue by Haoxw** [ZLMediaKit/ZLMediaKit#1413]
ZLMediakit可以直接接收通过SDP协商后推送的RTP的音频流（仅包含音频的）吗？
例如下面的SDP描述中的情况：
我想让IPC仅将音频流推送至ZLMediakit（172.16.2.2）的30004端口，这样可以吗？ZLMediakit会接收这个流吗？
        Session Description Protocol
            Session Description Protocol Version (v): 0
            Owner/Creator, Session Id (o): 34020000001370000001 0 0 IN IP4 172.16.2.2
            Session Name (s): Talk
            Connection Information (c): IN IP4 172.16.2.2
            Time Description, active time (t): 0 0
            Media Description, name and address (m): audio 30004 RTP/AVP 8
            Media Attribute (a): sendrecv
            Media Attribute (a): rtpmap:8 PCMA/8000
            Unknown: y=0200000001
            Unknown: f=v/////a/1/8/1
            [Generated Call-ID: 697740663]
同时我能不能通过ZLMediaKit的30004端口再反推一路RTP的音频流到IPC，我主要是想利用这个已经建立的连接（sendrecv）来进行NAT的穿越？
谢谢！

**Comment by xia-chu** [comment]
这样可以让zlm接收推流的，再让zlm再用相同端口推回去，也可以，可以通过调用startSend接口实现

**Comment by Haoxw** [comment]
> 这样可以让zlm接收推流的，再让zlm再用相同端口推回去，也可以，可以通过调用startSend接口实现

非常感谢您的回复！
我理解您的意思是，我可以将我要反推的G77A的RTP裸流先推送给给ZLMediaKit，然后再调用startSend接口，将这个流以指定的特定源端口再退回去是吗？
谢谢！

**Comment by xia-chu** [comment]
可以啊

**Comment by weiqinxiao** [comment]
我最近也在实现与ipc的语音对讲功能，使用的是broadcast-invite协商新的tcp端口，ipc接受音频流，不影响视频流。
遇到的问题是，往ipc发语音片段，没有用zlmediakit，没有找到一个更合适的方案，不知道zlmediakit是否有这种接口
@Haoxw 您这采集音频流，发送的方式是啥样的呀，能介绍下吗
