### ISSUE TITLE
[技术咨询]webrtc跨网段如何访问

### ISSUE THREAD

**Issue by allenzhuyi** [ZLMediaKit/ZLMediaKit#1418]
使用webrtc实现相机流的推送，发现如果和流媒体服务器在同一个网段没问题，但是不通网段就不行，其实两个IP网络是通的，是否要stun 服务器，还是如何配置，谢谢

**Comment by allenzhuyi** [comment]
发现是网络防火墙策略问题引起的，关闭问题

**Comment by gocpplua** [comment]
> 发现是网络防火墙策略问题引起的，关闭问题

如何修改
