### ISSUE TITLE
关于fmp4延迟的咨询

### ISSUE THREAD

**Issue by yxw13141618** [ZLMediaKit/ZLMediaKit#1420]
咨询各位大佬，fmp4播放有2-3s的延迟，这个不知能否降低一下。

**Comment by xia-chu** [comment]
ffplay nobuffer播放试试。

**Comment by yxw13141618** [comment]
> ffplay nobuffer播放试试。

感谢大佬回复，ffplay nobuffer的延迟确实要小一点  但是浏览器端直接用video标签播放 就有2-3s的延迟  那这个延迟是播放器端产生的了  大佬知道有什么可行性的办法降低一点嘛？

**Comment by xia-chu** [comment]
有:重写一个chrome



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yxw13141618 ***@***.***&gt;
发送时间: 2022年2月14日 10:10
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] 关于fmp4延迟的咨询 (Issue #1420)

**Comment by yxw13141618** [comment]
> 有:重写一个chrome 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: yxw13141618 ***@***.***&gt; 发送时间: 2022年2月14日 10:10 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [ZLMediaKit/ZLMediaKit] 关于fmp4延迟的咨询 (Issue #1420)

哈哈哈哈  大佬说笑了。。。那我先关闭了，谢谢🙏。
