### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by LeeFang-p** [ZLMediaKit/ZLMediaKit#1422]
**咨询的功能模块**
- 视频截图

**咨询的具体内容和问题**
- 在使用ffmpeg截图的过程中，显示rtsp://192.168.100.32:1935/rtp/06148134.flv: Invalid data found when processing input，请问这个是什么问题呢，传输的为H264文件
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级
![1644654929(1)](https://user-images.githubusercontent.com/53632440/153704018-fdc9167c-86cd-4c05-a59b-0ec12edf3f51.png)
![1644654995(1)](https://user-images.githubusercontent.com/53632440/153704053-b87b73b7-4495-4f05-8464-0f4cbefbf365.png)

**Comment by xia-chu** [comment]
你也是牛掰啊 rtsp://192.168.100.32:1935/rtp/06148134.flv 到底是个什么链接 你发明的吗？

**Comment by xia-chu** [comment]
rtsp://192.168.100.32:1935/rtp/06148134.flv  综合了3种协议
- rtsp
- rtmp
- http-flv
这个协议集合了3种协议的优点，小伙子，你想象力非常丰富
