### ISSUE TITLE
docker版本restful调用restart方法重启失败

### ISSUE THREAD

**Issue by jayuc** [ZLMediaKit/ZLMediaKit#1423]
**bug现象**
- docker版本restful调用restart方法重启失败
![企业微信截图_16448952487679](https://user-images.githubusercontent.com/18511291/153986460-7ac73380-255e-460b-9029-544f0c84995e.png)

**Comment by jayuc** [comment]
docker run -d --name=zlm -p 1935:1935 -p 6080:80 -p 8554:554 -p 10000:10000 -p 10000:10000/udp panjjo/zlmediakit
看看有什么问题吗

**Comment by kuaidou** [comment]
加一个--restart=always

**Comment by jayuc** [comment]
谢谢，已解决
