### ISSUE TITLE
设备端和平台端双向可视对讲，平台端向设备端一对多广播，以及支持私有协议透传[技术咨询]

### ISSUE THREAD

**Issue by choupoem** [ZLMediaKit/ZLMediaKit#1424]
夏总，您好，

       我们现在使用的是七牛云的视频监控平台，我们的业务平台和七牛云的云平台做API接口对接，目前已经实现了如下功能：
       1. 设备端和七牛云的平台端基于GB28181协议的双向语音对讲功能，可以直接在浏览器页面调用笔记本的MIC；
       2. 在七牛云一对一的双向语音对讲基础上，我让他们增加了平台端一对多的API接口，将设备端的单播变成组播或者广播的功能，来实现平台端向设备端一对多广播的功能；
       3. 让七牛云平台增加了私有透传接口，方便我们在GB28181信令基础上增加一些私有透传命令，比如调节设备端音量大小等功能
       以上功能都已经调试通过。

       但是我们在实际项目中会有一些平台本地部署需求（不通互联网的情况），七牛云平台本地部署费用太高，客户以及我们公司都承担不起；而且我们公司平台开发都是使用JAVA，所以想和夏总以及ZLM团队谈下合作（我们愿意承担相应开发费用），在现有ZLM功能基础上增加上述3个功能。QQ添加好友没同意，所以在这里留言下，希望尽快收到您的回复。

谢谢！

**Comment by xiongguangjie** [comment]
这个不是已经有了吗？？？ 国标的信令服务器只要调用接口就可以实现，你们需要学习WVP这个项目，基于这个项目修改是可以实现的

**Comment by choupoem** [comment]
好的，谢谢，我们这边再研究下，感谢指导

**Comment by GLIUYANG** [comment]
> 好的，谢谢，我们这边再研究下，感谢指导

请问解决了此问题吗，我也有相同的需求

**Comment by WangJinFeng19930310** [comment]
夏工你好，我也是您的粉丝，也有在自己的项目中集成zlmediakit，基于我对GB28181协议的研究，zlmediakit现有接口应该是不能满足设备语音广播需求的。以设备端播放服务器下发的音频数据为例：我的理解是GB28181协议invite通信完毕后，设备播放音频流是要请求zlmediakit的rtp音频流的，而音频数据是业务服务器提供的，因此我认为zlmediakit提供实时语音数据加入给指定给ssrc绑定的rtp实时音频流的接口，才能实现这一通信过程。rtp音频流的创建由zlmediakit提供接口，同时提供传入负载数据加入给指定rtp音频流的接口，以及关闭rtp音频流的接口。不知道我的理解是否正确？？？

**Comment by zhuangpengLI** [comment]
我这边也做了个demo

**Comment by xia-chu** [comment]
目前zlm的语音对讲功能已经完善 wvp-pro已经完成对接 不过作者没有把对讲这部分开源出来
