### ISSUE TITLE
[BUG] 将[hook]中的enable=1后，不能触发on_stream_not_found的web hook回调

### ISSUE THREAD

**Issue by chenchengwork** [ZLMediaKit/ZLMediaKit#1425]
**bug现象**
- 将[hook]中的enable=1后，不能触发on_stream_not_found的web hook回调

**bug产生时的使用场景**
- ZLMediaKit服务中没有的视频流地址进行播放，来触发on_stream_not_found的web hook回调

**bug是否可以复现，怎么复现**
- 修改配置文件config.ini,将[hook]中的enable=1，然后调用ZLMediaKit服务中没有的视频流地址进行播放，发现不能触发on_stream_not_found的web hook回调

**zlm代码git commit hash值**
commit 45d9bcd5f422d085227e7134e5b92ce6d9b6e242
Author: xiongziliang <771730766@qq.com>
Date:   Sun Feb 13 22:02:16 2022 +0800

**操作系统环境**
- 操作系统:ubuntu20.04，64位
- cpu类型:intel

**Comment by wasphin** [comment]
该功能已经过多方验证，请再检查一下自己的环境。或贴出相关配置文件、测试环境以及复现步骤。

**Comment by xia-chu** [comment]
此issue我觉得没讨论的价值，建议提问者仔细阅读配置文件注释
