### ISSUE TITLE
[技术咨询] webrtc 观看画面卡住

### ISSUE THREAD

**Issue by xiangshenb** [ZLMediaKit/ZLMediaKit#1426]
编译环境 windows10,64位，开启webrtc，最新版编译成功
1. -s '自己的证书'，运行后 采用 obs rtmp  推流，chrome webrtc 观看画面卡住不动，几秒才动一下，不是流畅的，rtmp 拉流观看正常；
    然后使用 ffmpeg 命令 去推流，webrtc 画面正常 流畅的
2. webrtc 兼容性如何，为何在移动端不能观看？微信 qq浏览器都测试了不能观看
3. webrtc 控制台偶尔报错 connect 超时

**Comment by xia-chu** [comment]
webrtc不支持带B帧的H264, 你说的`几秒才动一下` 大概率是这个问题；你可以选择h264 baseline profile.

**Comment by xiangshenb** [comment]
确实是baseline profile的问题，obs设置这个就可以了
