### ISSUE TITLE
[BUG] freeehome兼容问题

### ISSUE THREAD

**Issue by BlueSky-25** [ZLMediaKit/ZLMediaKit#1427]
**bug现象**
ZLM无法解码rtp文本

**bug产生时的使用场景**
- FreeEhome和ZLM配合适合用

**bug是否可以复现，怎么复现**
1.修改FreeEhome的默认子码流(码率765kb)，改成主码流(码率10M),
2.启动FreeEhome和ZLM,(**抓包可以看到ZLM有接受到1000+数据包,后,tcp断链**)
3.ZLM拉流，但是后台打印**rtp  playload type 未识别，以及非法得rtp,version字段非法**

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
windows10,ZLM(MediaServer_windows64_2022_01_20,已编译好的版本)

**Comment by xia-chu** [comment]
freeehome的支持度 其实我心里也没谱 这个是freeehome团队提交的pr，我合并并维护了，我并没有实际测试过该功能，因为也没测试环境，但是我没收到其他不可用的反馈，所以大概率是能用的，你可以在freeehom项目上提issue，咨询下他们
