### ISSUE TITLE
[技术咨询]RTSP回放录制MP4

### ISSUE THREAD

**Issue by wjjboy** [ZLMediaKit/ZLMediaKit#1430]
我们当前有一个业务场景是需要将大华的回放流（rtsp)录制成mp4格式存储下来，给到业务系统使用。主要想使用restful接口+webhook的形式进行对接。
现在有以下几个问题想咨询下：
1. 使用/index/api/addStreamProxy接口后，查看后台日志不停的在注册流和注销流。之前以为rtsp播放结束后会自动停止，现在不清楚需要怎么停。（是不是对接webhook的on_stream_changed消息，使用/index/api/delStreamProxy接口将拉流关闭）
2. /index/api/addStreamProxy接口的enable_mp4参数设置1之后，什么时候会收到on_record_mp4的webhook消息？
3. /index/api/addStreamProxy接口设置了超时时间和重试次数，请求之后直接返回 【无有效sdp track】 是什么原因导致的？

**Comment by xia-chu** [comment]
请提供zlm的日志和wireshark抓包文件
