### ISSUE TITLE
[技术咨询] 如何才能更快速的从直播流获取截图

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1432]
**咨询的功能模块**
- 直播流截图

**咨询的具体内容和问题**
- 使用自带的getSnap方法截图，因为需要启动ffmpeg再拉流截图，所以比较耗时；因为直播流已经存在在流媒体服务器上了，请问是否有其他更快方式能够直接从直播流生成截图？而不是拉流再截图。

**Comment by xia-chu** [comment]
没有 这种方式是开发量最新，代码侵入最少的方式
