### ISSUE TITLE
[技术咨询]WEBRTC播放非常卡顿

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1433]
**咨询的功能模块**
- webrtc播放

**咨询的具体内容和问题**
- rtsp推流后用webrtc播放非常卡顿，使用rtmp或者其他协议播放都非常流畅，请问是我哪里配置有问题嘛？

**Comment by xia-chu** [comment]
请仔细看配置文件注释



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mayomeng ***@***.***&gt;
发送时间: 2022年2月17日 17:53
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询]WEBRTC播放非常卡顿 (Issue #1433)





 
咨询的功能模块
  
webrtc播放 
 
咨询的具体内容和问题
  
rtsp推流后用webrtc播放非常卡顿，使用rtmp或者其他协议播放都非常流畅，请问是我哪里配置有问题嘛？

**Comment by mayomeng** [comment]
您说的是【rtsp.directProxy=0】嘛，我设置了还是不流畅，感觉是几秒才动一下，您看我的问题是否和 【[#1426](https://github.com/ZLMediaKit/ZLMediaKit/issues/1426)】一样呀？

**Comment by xia-chu** [comment]
那说明有b帧 需要重新编解码才能解决这个问题

**Comment by mayomeng** [comment]
我参照[#1277](url) zlm设置了【rtsp.directProxy=0】，使用ffmpeg推流时设置了禁用B帧，但还是有上述问题，播放的时候每次都跳好几秒，下面是我的ffmpeg推流命令
```
ffmpeg -re -stream_loop -1 -i "F:\录像\test.mp4" -c:v libx264 -x264-params "profile=high:level=3.0" -f flv -y rtmp://192.168.231.12:1935/live/test

ffmpeg -re -stream_loop -1 -i "F:\录像\test.mp4" -vcodec copy -acodec copy –bf 0 -f rtsp -rtsp_transport tcp "rtsp://192.168.231.12:554/live/test"
```

还请大神帮忙看看，多谢

**Comment by wasphin** [comment]
如果仔细看了 #1426 以及 #1277 就会发现, 不只要求不能有 B 帧, 还要求只能是 `baseline` 的 profile.

**Comment by Think-Force** [comment]
解决了吗，我这边现象是ffmpeg推mp4用webrtc播放很卡，rtmp和rtsp都正常。用obs推流mp4和桌面都是不卡的

**Comment by wx5391805** [comment]
解决了吗，我这边现象是ffmpeg推mp4用webrtc播放很卡，rtmp和rtsp都正常。用obs推流mp4和桌面都是不卡的

**Comment by wx5391805** [comment]
不要求baseline，你用了-acodec copy 当然有b帧，bf 0 不起作用的

**Comment by lvlinmufeng** [comment]
只能说失望至极， 这水平怎么商业化的 1秒一模糊
