### ISSUE TITLE
[技术咨询]级联发送rtp包的问题

### ISSUE THREAD

**Issue by ypy31393936** [ZLMediaKit/ZLMediaKit#1435]
**咨询的功能模块**
- 如题

**咨询的具体内容和问题**
- 抓包测试发现，级联时向上发送的rtp包的i帧只含有ba-ps包头,67-sps,68-pps,没有bb-系统头和bc-map头，如果我想在i帧里加上这两个应该要修改哪块代码呢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
麻烦 @ireader 大佬出来解答下

**Comment by ireader** [comment]
libmpeg/source/mpeg-ps-enc.c文件ps_muxer_input函数
![image](https://user-images.githubusercontent.com/1535445/154902590-9f2fe596-dce6-44d4-acd2-f315c427c745.png)

目前大概每30帧生成system header，可以加上关键帧写入system header，代码类似
``` if(0 == (ps->psm_period % 30) || flags & MPEG_FLAG_IDR_FRAME) ```

**Comment by ypy31393936** [comment]
感谢两位大佬解答

**Comment by xia-chu** [comment]
@ireader 大佬 你是不是要更新下你的库？

**Comment by ireader** [comment]
已更新

**Comment by ypy31393936** [comment]
感谢两位大佬
