### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by ChaoII** [ZLMediaKit/ZLMediaKit#1436]
**咨询的功能模块**
- 当前进行推流测试延迟高

**咨询的具体内容和问题**
- 推流采用obs rtmp推流，串流播放器采用（VLC）目前测试延迟有十几秒，看到大佬的文档vlc内部有缓存时长，所以请问有没有对应的推荐的测试播放器

**Comment by xia-chu** [comment]
wiki中有关于延时的wiki 里面有讲怎么排除播放器缓存干扰

**Comment by ChaoII** [comment]
> wiki中有关于延时的wiki 里面有讲怎么排除播放器缓存干扰 请认真查阅

感谢回复，wiki中部分链接失效，无法下载

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/154902441-97ab26a5-6332-4787-8b47-42ff17956a8b.png)

**Comment by xia-chu** [comment]
也用rtc播放测试延时也行
