### ISSUE TITLE
[技术咨询] 流媒体一直报address dismatch错误

### ISSUE THREAD

**Issue by kudingc** [ZLMediaKit/ZLMediaKit#1440]
**咨询的功能模块**
如图：
![lQLPDhsrmQz716fNAajNB7-wY9LSmMw3xSUCGBqa10D0AA_1983_424](https://user-images.githubusercontent.com/20639057/154876935-cec755cc-7109-41e3-abc6-7de66e277009.png)
就一直报这个错。大神有没有遇到过啊？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
请更新zlm代码
