### ISSUE TITLE
[技术咨询] address already in use

### ISSUE THREAD

**Issue by eeead** [ZLMediaKit/ZLMediaKit#1442]
**咨询的功能模块**
zlm提示错误

**咨询的具体内容和问题**
![image](https://user-images.githubusercontent.com/39365090/154892297-bed0795c-b303-4255-b812-bfb85fe778b5.png)
wvp设置了4个收流端口，现在本地有两台监控，一台实时播放，一台录像回放。点击录像回放中的某一个后zlm报错，请教一下错误是什么

**Comment by xia-chu** [comment]
wvp的端口分配不是线程安全的，存在一个端口多次分配的问题
