### ISSUE TITLE
[技术咨询]RTP拉流后推流卡顿与丢帧

### ISSUE THREAD

**Issue by poonweif** [ZLMediaKit/ZLMediaKit#1443]
**咨询的功能模块**
- RTP拉流与推流

**咨询的具体内容和问题**
- 非常感谢您的作品，我在使用的过程中尝试用zlmediakit+wvp的方式实现GB28181摄像头的点播，但是视频在播放的时候会出现2秒的卡顿（摄像头I帧间隔为2000ms），然后我修改了
    [general]->modifyStamp=1
    发现视频的2秒卡顿改善了，恢复正常，但是视频播放时候却丢帧严重。

**Comment by poonweif** [comment]
> 请把rtp dump出来 我分析下

您好，这是dump文件
[#1443 - [poonweif] - dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8114177/1443.-.poonweif.-.dump.zip)
您

**Comment by xia-chu** [comment]
这个摄像头什么牌子的？时间戳有点乱

**Comment by poonweif** [comment]
> 这个摄像头什么牌子的？时间戳有点乱

这个是NVR录像机的，摄像头我直接28181连没问题，那我联系一下厂家，请问这个是怎样可以从dump文件分析出来呢？

**Comment by xia-chu** [comment]
用zlm的test_rtp测试程序加载 我分析时会加点日志
