### ISSUE TITLE
[BUG]: UDPSocket绑定某个端口后，此发送数据引发connection refused异常后OnRead不再可用的问题

### ISSUE THREAD

**Issue by dsjonline** [ZLMediaKit/ZLMediaKit#1444]
UDPSocket绑定某个端口后，使用此Socket发送数据到某个暂时无法到达的端口，ICMP Type: 3 (Destination unreachable) ,引发connection refused异常，此Socket的OnRead不再可用.

**Comment by xia-chu** [comment]
嗯 这个确实不太好 这个问题一般在局域网才会导致

**Comment by wasphin** [comment]
这个确实是这样，目前我这边是通过重试解决。UDP 缺乏一个比较有效的判断，有的对端会回 ICMP，有的可能什么也不回。

**Comment by xia-chu** [comment]
更新了 这个问题应该修复了
