### ISSUE TITLE
[BUG] 干扰的rtp pt导致rtsp拉流花屏

### ISSUE THREAD

**Issue by ken626014896** [ZLMediaKit/ZLMediaKit#1445]
使用ZLMRTSP代理功能，代理部分宇视摄像头出来的RTSP流，用VLC播放时出现花屏 跳秒

**Comment by alexliyu7352** [comment]
你试试看关闭音频输出

**Comment by ken626014896** [comment]
试了，关闭摄像头音频，以及zlm的音频，也是同样的现象

**Comment by xia-chu** [comment]
这个rtsp流在打包fu包时，不符合规范：
<img width="830" alt="图片" src="https://user-images.githubusercontent.com/11495632/155081565-ba7b25df-fc0a-4c3a-b4f7-640ced598dd7.png">

**Comment by xia-chu** [comment]
```C++
+---------------+
|0|1|2|3|4|5|6|7|
+-+-+-+-+-+-+-+-+
|S|E|   FuType  |
+---------------+
````
s、e flags设置错误

**Comment by ken626014896** [comment]
可是这摄像头是买回来的产品，我也看不了，宇视的，就是zlm本身没问题的是吗

**Comment by xia-chu** [comment]
这个问题之前遇到过，但是没同步到git 今天又遇到了，对比FFmpeg代码无果，再分析wireshark抓包再发现是这个问题
