### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by zylantian** [ZLMediaKit/ZLMediaKit#1451]
您好，按照wiki，拉取的最新代码，环境是centos7以上，非docker方式部署，gcc-c++-4.8.5，cmake 3.23, 编译时出现
CMake Warning at CMakeLists.txt:35 (message):
  Compiler doesn't support std::atomic<long long>
请问这个是哪里配置的问题吗？

**Comment by xia-chu** [comment]
CMake Warning一般可以忽略的 也是可以编译通过的
