### ISSUE TITLE
[技术咨询] 使用flv无法播放

### ISSUE THREAD

**Issue by LeeFang-p** [ZLMediaKit/ZLMediaKit#1452]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 使用rtsp协议拉流可以正常播放，
- 
![1645672485(1)](https://user-images.githubusercontent.com/53632440/155451037-22a57377-9e69-48ef-a07d-295f69247883.png)
在使用flv.js流也会过来，但是无法播放
![1645672933(1)](https://user-images.githubusercontent.com/53632440/155451885-976165d5-265d-480b-825a-d8482cc0889a.png)
![1645672937(1)](https://user-images.githubusercontent.com/53632440/155451890-0ffd886f-633d-4dce-989f-ce17c6761c08.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
视频什么格式？ zlmediakit git hash多少? 什么版本？

**Comment by LeeFang-p** [comment]
h.264的文件，使用的docker.io/panjjo/zlmediakit 这个镜像

**Comment by xia-chu** [comment]
勾选isLive试试

**Comment by xia-chu** [comment]
试试这个播放器：http://cloud.liveqing.com:18000/#/liveplayer

**Comment by LeeFang-p** [comment]
谢谢大佬

**Comment by LeeFang-p** [comment]
> 试试这个播放器：http://cloud.liveqing.com:18000/#/liveplayer

我用rtps拉流播放的时候一切流畅，但是用http-flv拉流的时候总是卡顿这点大佬有遇到过吗?

**Comment by LeeFang-p** [comment]
> 试试这个播放器：http://cloud.liveqing.com:18000/#/liveplayer

我用rtps拉流播放的时候一切流畅，但是用http-flv拉流的时候总是卡顿、掉帧这点大佬有遇到过吗?
