### ISSUE TITLE
[技术咨询]fmp4切片设为1

### ISSUE THREAD

**Issue by cn-specter** [ZLMediaKit/ZLMediaKit#1454]
**咨询的功能模块**
- fmp4切片大小修改

**咨询的具体内容和问题**
- 使用wsPlayer时播放ws流延迟大，大神建议修改ZLMediaKit的fmp4切片大小改为1。请问如何修改呢？可否加入使用配置文件方式

**Comment by xia-chu** [comment]
zlm没有fmp4切片老哥 fmp4是一帧图片就会flush

**Comment by xxxxxxbin6** [comment]
@v354412101 @cn-specter  为啥我用wsPlayer播放时会不流畅啊,也是拉的ZLm的流

**Comment by cn-specter** [comment]
@v354412101 这个就不清楚了，我是延迟大！差不多在8s左右，局域网。

**Comment by cn-specter** [comment]
@xxxxxxbin6 不清楚，我是延迟大，局域网

**Comment by cn-specter** [comment]
@v354412101 你测试局域网内在多少延时呢？我差不多在8s了

**Comment by xia-chu** [comment]
延时大 不要找服务器 要找播放器
