### ISSUE TITLE
[技术咨询]推流直播HLS等格式无法播放

### ISSUE THREAD

**Issue by itzhoujun** [ZLMediaKit/ZLMediaKit#1459]
**咨询的功能模块**
关于推流直播

**咨询的具体内容和问题**
1. 我使用以下命令进行了推流：ffmpeg -re -stream_loop -1 -i ./video_tracked-2.mp4 -vcodec h264 -acodec aac -f flv rtmp://127.0.0.1/live/test
2. 使用ffplay rtmp://127.0.0.1/live/test 可以播放，说明推流正常
3. 但是http://127.0.0.1/live/test/hls.m3u8 等其他格式的地址无法播放，是我使用方式有问题么？

**Comment by xia-chu** [comment]
配置文件 publishToHls设置多少？

**Comment by itzhoujun** [comment]
@xia-chu 默认配置：publishToHls=1

**Comment by xia-chu** [comment]
在不 这个问题解决没？

**Comment by xia-chu** [comment]
这个问题步应该是zlm的问题

**Comment by itzhoujun** [comment]
@xia-chu 还没解决中。最近在忙别的，我过两天抽空再研究下

**Comment by itzhoujun** [comment]
@xia-chu 哈喽，问题解决了，原因如下：我按照文档使用docker启动的服务，不知道为啥文档中docker run 时做了端口映射8080:80，而不是80:80。然而”播放url“

**Comment by itzhoujun** [comment]
@xia-chu 哈喽，问题解决了，原因如下：
我按照文档使用docker启动的服务，不知道为啥文档中docker run 时做了端口映射8080:80，而不是80:80。
然而[播放URL规则](https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99)中的示例中hls等链接默认是使用80端口。改成 http://127.0.0.1:8080/live/test就能播放了。这算是文档的一个坑吧。

**Comment by xia-chu** [comment]
我觉得你是个坑😂



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: itzhoujun ***@***.***&gt;
发送时间: 2022年3月20日 00:13
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询]推流直播HLS等格式无法播放 (Issue #1459)





 
@xia-chu 哈喽，问题解决了，原因如下：
 我按照文档使用docker启动的服务，不知道为啥文档中docker run 时做了端口映射8080:80，而不是80:80。
 然而播放URL规则中的示例中hls等链接默认是使用80端口。改成 http://127.0.0.1:8080/live/test就能播放了。这算是文档的一个坑吧。
