### ISSUE TITLE
bug: 最新的docker 运行后无法拉流成功；而对比旧的是可以的

### ISSUE THREAD

**Issue by dualven** [ZLMediaKit/ZLMediaKit#1460]
### 如何复现?

docker run -itd --name zlmserver -p 6080:80 -p 10443:443 -p 10935:1935 -p 19351:19350 -p 10554:554 -p 10554:554/udp -p 10332:332 -p 10332:332/udp -p 10010:10000 -p 10010:10000/udp  -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp  zlmediakit/zlmediakit:Release.last

### 相关日志或截图
​​​​
![image](https://user-images.githubusercontent.com/2209534/156109819-002b6fba-4986-4353-b42e-3747d8a7a08b.png)

原来可以成功的docker: 
docker run -itd --name zlmserver -p 6080:80 -p 10443:443 -p 10935:1935 -p 19351:19350 -p 10554:554 -p 10554:554/udp -p 10332:332 -p 10332:332/udp -p 10010:10000 -p 10010:10000/udp  -p 30000-30500:30000-30500/udp -p 30000-30500:30000-30500/tcp  panjjo/zlmediakit
可以成功

![image](https://user-images.githubusercontent.com/2209534/156109929-724a7c1f-311c-4859-8f02-c46edda8f953.png)

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by dualven** [comment]
@xia-chu  can you give me some help ?

**Comment by xia-chu** [comment]
看日志没什么异常啊，你是说zlm无法拉流还是你无法拉zlm的流？

**Comment by dualven** [comment]
就是我的wvp工程无法拉zlm的流。

**Comment by dualven** [comment]
好像差一个
![image](https://user-images.githubusercontent.com/2209534/156116778-b616d9cd-f5f5-472c-a0be-5c8c6417b7d6.png)

**Comment by dualven** [comment]
![image](https://user-images.githubusercontent.com/2209534/156121040-671879e0-ac81-4fb5-8567-a3f23df52ee8.png)

**Comment by dualven** [comment]
我看了下，好像是拉流的过程 中ffmpeg程序 不对？？？ @xia-chu 


root@4c8fcb06c42c:/opt/media/bin/ffmpeg# tail -f ffmpeg.log.198 
    Metadata:
      creation_time   : 2022-03-02T08:19:17.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Exiting normally, received signal 15.

**Comment by dualven** [comment]
root@4c8fcb06c42c:/opt/media/bin/ffmpeg# tail -f ffmpeg.log.510 
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[h264 @ 0x558168b592c0] concealing 2079 DC, 2079 AC, 2079 MV errors in P frame
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558168b55b20] Failed to add index entry
    Last message repeated 1 times
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'http://10.60.2.199:6080/rtp/34020000001320000003_34020000001340000001.live.mp4':
  Metadata:
    major_brand     : msdh
    minor_version   : 0
    compatible_brands: isommp42msdhmsixiso5iso6
    creation_time   : 2022-03-02T08:46:55.000000Z
  Duration: 00:00:57.57, start: 56.560000, bitrate: N/A
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuvj420p(pc, bt709, progressive), 1920x1080, 8 kb/s, 12.50 fps, 25 tbr, 1k tbn, 2k tbc (default)
    Metadata:
      creation_time   : 2022-03-02T08:46:55.000000Z
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 8000 Hz, mono, fltp, 88 kb/s (default)
    Metadata:
      creation_time   : 2022-03-02T08:46:55.000000Z
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press [q] to stop, [?] for help
Finishing stream 0:0 without any data written to it.
Output #0, mjpeg, to '/opt/media/bin/www/snap/ee9bbc89d923b49dbae892cdd986a74a/1646210828.jpeg.tmp':
  Metadata:
    major_brand     : msdh
    minor_version   : 0
    compatible_brands: isommp42msdhmsixiso5iso6
    encoder         : Lavf57.83.100
    Stream #0:0(und): Video: mjpeg, yuvj420p(pc), 1920x1080, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc (default)
    Metadata:
      creation_time   : 2022-03-02T08:46:55.000000Z
      handler_name    : VideoHandler
      encoder         : Lavc57.107.100 mjpeg
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
frame=    0 fps=0.0 q=0.0 Lsize=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
Exiting normally, received signal 15.

**Comment by xia-chu** [comment]
新的docker http-flv播放地址后缀改成.live.flv了

**Comment by dualven** [comment]
是的，谢谢，这个小问题搞了几天。
“新的docker http-flv播放地址后缀改成.live.flv了

”
