### ISSUE TITLE
代码重复

### ISSUE THREAD

**Issue by yujiaao** [ZLMediaKit/ZLMediaKit#1462]
www下的文件 [ZLMRTCClient.js](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/www/webrtc/ZLMRTCClient.js)
与www/webrtc下和js
[ZLMRTCClient.js](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/www/ZLMRTCClient.js)
一模一样，这么大的文件重复，影响下载和理解，另外，这个是编辑出的结果而不是源码吧？

**Comment by xia-chu** [comment]
为了提高浏览器的兼容性 有些浏览器访问路径异常
