### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by tangrufeng** [ZLMediaKit/ZLMediaKit#1464]
**咨询的功能模块**
http(s)+mp3
**咨询的具体内容和问题**
能否支持这个场景：
1、将Android的采集到音频推到服务器，然后以HTTP(S)+mp3的格式提供给客户端访问。不需要视频只需要音频；

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你的问题太笼统了。
- 1. 你打算用什么协议推流？
- 2. 什么http拉流协议？
最后告诉你一声，zlm现在还不支持mp3

**Comment by tangrufeng** [comment]
> 你的问题太笼统了。
> 
> * 1. 你打算用什么协议推流？
> * 2. 什么http拉流协议？
>      最后告诉你一声，zlm现在还不支持mp3

推流用rtmp，客户端用http的协议，mp3的音频格式，就像蜻蜓fm的收音机电台这种（https://lhttp.qingting.fm/live/387/64k.mp3），因为我们设备单片机只支持mp3格式解码

**Comment by xia-chu** [comment]
不支持，zlm目前不支持mp3格式，也不支持http-mp3直播，这个需要你自己深度定制功能
