### ISSUE TITLE
拉流m3u8，输出的流也是m3u8，无法播放。

### ISSUE THREAD

**Issue by azreal1111** [ZLMediaKit/ZLMediaKit#1465]
**咨询的功能模块**
-拉流播放

**咨询的具体内容和问题**
-  通过postman请求addStreamProxy 接口，拉了一个m3u8的流。播放mp4和ts流都正常，无法播放m3u8类型。初始化的配置文件不行，下面是修改后的也不行。
配置文件截图：
![image](https://user-images.githubusercontent.com/21782429/156310617-62e8b594-6895-4e51-a3b5-64cb1425f46f.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by azreal1111** [comment]
拉流后，查看流列表，并没有HlsMediaSource。所以无法播放m3u8。

**Comment by xia-chu** [comment]
所以 你拉流代理 都没选择开hls



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: azreal1111 ***@***.***&gt;
发送时间: 2022年3月2日 15:29
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] 拉流m3u8，输出的流也是m3u8，无法播放。 (Issue #1465)





 
拉流后，查看流列表，并没有HlsMediaSource。所以无法播放m3u8。
