### ISSUE TITLE
[技术咨询]zlmediakit作为RTSP流服务器延时较高大约6s

### ISSUE THREAD

**Issue by Gpwner** [ZLMediaKit/ZLMediaKit#1466]
**咨询的功能模块**
有哪些有效措施可以降低RTSP延时？

**咨询的具体内容和问题**
当前我使用ffmpeg推流到zlmediakit,后使用vlc播放器拉流，但延时较高，大约6s左右。请问具体可以从哪些方面降低延时（ffmpeg推流、服务器、客户端）?感谢

**Comment by Gpwner** [comment]
参考:
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E6%B5%8B%E8%AF%95ZLMediaKit%E7%9A%84%E5%BB%B6%E6%97%B6%EF%BC%9F 
在经过设置VLC为最低延迟后，发现VLC的延时比使用```ffplay -i rtsp://xxxxxxx -fflags nobuffer```的延时稍低点，但是仍然有很大延时

**Comment by rmokerone** [comment]
你这个问题，只需要考虑ffmpeg推流和客户端，不用考虑是服务器的问题。实测局域网环境，我们优化后的播放器，从摄像头采集到播放的延迟小于500ms。

**Comment by Gpwner** [comment]
> 不用考虑是服务器的问题

@rmokerone 请问您使用的是什么客户端？

**Comment by rmokerone** [comment]
自己写的

**Comment by Gpwner** [comment]
能否共享一个，感谢！

**Comment by xia-chu** [comment]
> 你这个问题，只需要考虑ffmpeg推流和客户端，不用考虑是服务器的问题。实测局域网环境，我们优化后的播放器，从摄像头采集到播放的延迟小于500ms。

实际上，如果推流播放器都是zlm，延时可以控制在200ms以下。如果推流时obs，播放器时zlm，那么延时在200ms左右

**Comment by keepmovng** [comment]
> > 你这个问题，只需要考虑ffmpeg推流和客户端，不用考虑是服务器的问题。实测局域网环境，我们优化后的播放器，从摄像头采集到播放的延迟小于500ms。
> 
> 实际上，如果推流播放器都是zlm，延时可以控制在200ms以下。如果推流时obs，播放器时zlm，那么延时在200ms左右

请问zlm可以作为播放器在android设备上使用吗？

**Comment by rmokerone** [comment]
> > 你这个问题，只需要考虑ffmpeg推流和客户端，不用考虑是服务器的问题。实测局域网环境，我们优化后的播放器，从摄像头采集到播放的延迟小于500ms。
> 
> 实际上，如果推流播放器都是zlm，延时可以控制在200ms以下。如果推流时obs，播放器时zlm，那么延时在200ms左右

我们是从设备上通过WIFI推过来的RTSP数据流，延时500ms是向大了说的，一般就在300ms左右:D

**Comment by xia-chu** [comment]
> > > 你这个问题，只需要考虑ffmpeg推流和客户端，不用考虑是服务器的问题。实测局域网环境，我们优化后的播放器，从摄像头采集到播放的延迟小于500ms。
> > 
> > 
> > 实际上，如果推流播放器都是zlm，延时可以控制在200ms以下。如果推流时obs，播放器时zlm，那么延时在200ms左右
> 
> 请问zlm可以作为播放器在android设备上使用吗？

支持Android，目录下有个大大的Android文件夹看不见？

**Comment by itzhoujun** [comment]
我也遇到这个问题。我使用python opencv读流，然后ffmepg推流给zlm。延迟好几秒。不知道哪个环节出问题

**Comment by xia-chu** [comment]
> 我也遇到这个问题。我使用python opencv读流，然后ffmepg推流给zlm。延迟好几秒。不知道哪个环节出问题

如果你不 明白延时的定义和内在逻辑，建议不要提这个词，你应该多看看wiki

**Comment by copyshop** [comment]
同问 这个问题解决了吗？ 我这边也是，同一个局域网内，大概延迟好5s左右，感觉不应该呀，应该是哪个环节出问题了
