### ISSUE TITLE
[BUG]: <onvif测试工具无法拉ZLM的RTSP流>

### ISSUE THREAD

**Issue by leem001** [ZLMediaKit/ZLMediaKit#1468]
使用onvif 测试工具(v1806_rev1408)没有办法拉取ZLM RTSP码流，从信令结果来看测试工具只会拉视频流，不会拉音频流

拉流信令
![image](https://user-images.githubusercontent.com/8575418/156563759-e061cd0c-b303-45f4-adcb-c5ca4e7fc2d9.png)

**Comment by xia-chu** [comment]
获取复合流的单track功能 zlm确实没考虑 可能确实有bug，这个测试工具只有Windows版本吗

**Comment by leem001** [comment]
我手上只有windows版本的
