### ISSUE TITLE
[技术咨询]android设备RTMP推流屏幕 转RTSP拉流播放，推流端屏幕静止后，播放端的画面会停留在推流端的前几帧画面

### ISSUE THREAD

**Issue by keepmovng** [ZLMediaKit/ZLMediaKit#1469]
您好。
我的使用场景是在android设备上使用rtmp推流屏幕数据到局域网zlm，局域网中另一台设备以rtsp拉流播放。播放器用的是ijkplayer和vlc
遇到的问题是推流端屏幕静止后，播放端的画面会停留在推流端的前几帧。
我尝试过将rtsp.modifyStamp和rtmp.modifyStamp都设置为0，问题依旧。
我尝试过使用FFmpeg推流，问题依旧。

请问下该问题是否有其他参数可以控制，或者我该如何排查？

**Comment by xia-chu** [comment]
这个问题说明，推流端程序并没有把前几帧画面推流过来。

**Comment by keepmovng** [comment]
感谢
