### ISSUE TITLE
[技术咨询GB2818功能 是否支持2011版本协议]

### ISSUE THREAD

**Issue by wjtNo2** [ZLMediaKit/ZLMediaKit#1472]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by monktan89** [comment]
2011协议推流无非就是UDP，zlm支持tcp/udp推流，信令方面需要自己实现。
