### ISSUE TITLE
[BUG]: HLS拉流容错率太低

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1473]
最新版本的代码, 相比之前的代码在hls拉流处理这块的逻辑我觉得有些问题.
之前的代码虽然存在当m3u8文件出现问题时或者网络出现问题时, 会有反复拉取m3u8文件而不是上报到上层业务处理的问题.

但是现在这样修改我感觉问题更大, 这应该算是BUG了.
当拉流m3u8文件第一次成功后, 开始拉取切片 .
之后延时到了开始再次拉取m3u8文件时, 如果网络波动或者其他原因, 导致获取失败.
就直接上报上层重试了, 可是这时候在切片list中的切片应该并没有全部下载完成.
但是hlsPlayer会重新创建, 客户端也会断开.这样是否有点太暴力了.

至少我觉得应该重试几次, 或者判断下切片list是否为空了, 如果为空了又拉不到新的m3u8索引文件, 那么就返回上层, 否则直接重试, 是否这样会好一些?

**Comment by xia-chu** [comment]
看了下代码，确实在`HlsPlayer::onResponseCompleted(const SockException &ex) `如果发现错误了会直接上报上层。
可以在这里加个重试机制，失败几次再上报。

**Comment by alexliyu7352** [comment]
已提交pr
https://github.com/ZLMediaKit/ZLMediaKit/pull/1541
