### ISSUE TITLE
[技术咨询]请问zlm的播放器可以用在android上吗？

### ISSUE THREAD

**Issue by keepmovng** [ZLMediaKit/ZLMediaKit#1483]
请问zlm的播放器可以用在android上吗？

**Comment by urmyfaith** [comment]
请阅读
https://github.com/ZLMediaKit/ZLMediaKit/Readme

请阅读
https://github.com/ZLMediaKit/ZLMediaKit/wiki/快速开始

**Comment by xia-chu** [comment]
zlm的播放器可以在Android上使用，不过你要自己实现解码渲染，这个难度我觉得一般人搞不定，还不如直接用ijkplayer。
