### ISSUE TITLE
webrtc点播地址[技术咨询]

### ISSUE THREAD

**Issue by MicFraye** [ZLMediaKit/ZLMediaKit#1484]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
webrtc 点播功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
前端使用rtsp方式，接入摄像机，使用项目自带webrtc客户端播放实时成功。
实时url为：https://172.18.239.208/index/api/webrtc?app=rtsp&stream=D838B8AD&type=play

MP4录像点播 
[http](http://172.18.239.208/record/rtsp/D838B8AD/2022-03-08/11-27-10.mp4) 使用VLC和浏览器可以播放

1. 请问下webrtc录像播放时的url，应该如何指定mp4文件？
wiki上说的 “http://127.0.0.1/index/api/webrtc?app=record&stream=test.mp4&type=play”
stream=应该如何处理？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
config.ini 有record 的部分关于文件录像与点播的配置路径，stream 就是文件名与rtsp点播的stream 类似

**Comment by MicFraye** [comment]
点播的URL  “http://172.18.239.208/record/rtsp/D838B8AD/2022-03-08/11-27-10.mp4” ，可以用http方式播放
app=record,stream=rtsp/D838B8AD/2022-03-08/11-27-10.mp4

在webrtc播放地址为“http://172.18.239.208/index/api/webrtc?app=record&stream=rtsp/D838B8AD/2022-03-08/11-27-10.mp4&type=play”,后台会报错“"msg" : "[json code]:code=-1,msg=\"feild\"”


2022-03-09 14:28:00.554 T MediaServer[26577-event poller 1] HttpSession.cpp:121 onError | 75(127.0.0.1:42844) end of file
2022-03-09 14:28:00.554 T MediaServer[26577-event poller 1] HttpSession.cpp:33 ~HttpSession | 75(127.0.0.1:42844) 
2022-03-09 14:28:03.096 T MediaServer[26577-event poller 1] HttpSession.cpp:27 HttpSession | 75(172.18.224.1:31108) 
2022-03-09 14:28:03.098 T MediaServer[26577-event poller 1] HttpSession.cpp:121 onError | 75(172.18.224.1:31108) end of file
2022-03-09 14:28:03.098 T MediaServer[26577-event poller 1] HttpSession.cpp:33 ~HttpSession | 75(172.18.224.1:31108) 
2022-03-09 14:28:03.099 T MediaServer[26577-event poller 1] HttpSession.cpp:27 HttpSession | 75(172.18.224.1:31109) 
2022-03-09 14:28:03.104 D MediaServer[26577-event poller 1] WebApi.cpp:243 http api debug | 
# request:
POST /index/api/webrtc?app=record&stream=rtsp/D838B8AD/2022-03-08/11-27-10.mp4&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Content-Length : 5131
Content-Type : text/plain;charset=UTF-8
Host : 172.18.239.208
Origin : https://172.18.239.208
Referer : https://172.18.239.208/webrtc/
sec-ch-ua : " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-origin
User-Agent : Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
# content:
v=0
o=- 979597387939136221 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jlvN
a=ice-pwd:sNEroE/VVoPTHi5ZhQ8+dGfq
a=ice-options:trickle
a=fingerprint:sha-256 9E:DA:AD:44:6F:9F:3A:34:15:FB:DD:DC:D8:C1:74:CD:E7:FA:82:C0:5C:38:43:0C:CC:20:F5:E7:5B:1E:41:AC
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 122 102 121 127 120 125 107 108 109 35 36 124 119 123 118 114 115 116 37
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:jlvN
a=ice-pwd:sNEroE/VVoPTHi5ZhQ8+dGfq
a=ice-options:trickle
a=fingerprint:sha-256 9E:DA:AD:44:6F:9F:3A:34:15:FB:DD:DC:D8:C1:74:CD:E7:FA:82:C0:5C:38:43:0C:CC:20:F5:E7:5B:1E:41:AC
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:122 VP9/90000
a=rtcp-fb:122 goog-remb
a=rtcp-fb:122 transport-cc
a=rtcp-fb:122 ccm fir
a=rtcp-fb:122 nack
a=rtcp-fb:122 nack pli
a=fmtp:122 profile-id=1
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetr
# response:
{
   "code" : -400,
   "msg" : "[json code]:code=-1,msg=\"feild\""
}


2022-03-09 14:28:03.104 W MediaServer[26577-event poller 1] WebHook.cpp:173 operator() | hook http://127.0.0.1:5800/MediaServer/WebHook/OnPlay 3ms,failed[json code]:code=-1,msg="feild":{
   "app" : "record",
   "id" : "75",
   "ip" : "172.18.224.1",
   "mediaServerId" : "your_server_id",
   "params" : "app=record&stream=rtsp/D838B8AD/2022-03-08/11-27-10.mp4&type=play",
   "port" : 31109,
   "schema" : "rtc",
   "stream" : "rtsp/D838B8AD/2022-03-08/11-27-10.mp4",
   "vhost" : "__defaultVhost__"
}

**Comment by xia-chu** [comment]
播放鉴权hook返回错误，你对接hook导致的问题

**Comment by xxxxxxbin6** [comment]
我点播地址http://192.168.3.57/index/api/webrtc?app=record&stream=VID_20220408_151526.mp4&type=play,播放不会报错,但是会有卡顿现象

**Comment by xia-chu** [comment]
@xxxxxxbin6 修改配置文件 把 record.sampleMS改成50~100试试

**Comment by xxxxxxbin6** [comment]
修改这个没效果，应该是手机原相机录制的视频带b帧导致的。另外，我通过rtc录制的文件有办法上传到zlm服务器的www/record目录吗

**Comment by xia-chu** [comment]
zlm内置录制文件就放在www/record啊

**Comment by xxxxxxbin6** [comment]
我意思是自己开发的播放器，能拉取从zlm转发的直播流，也能录制成mp4文件，现在想把录制的文件自动上传到服务器对应的www/record目录

**Comment by xia-chu** [comment]
> 转发的直播流，也能录制成mp4文件，现在想把录制的文件自动上传到服务器对应的www/record目录

这个zlm的http文件服务器还不支持大文件上传的

**Comment by xia-chu** [comment]
你可以用其他服务实现文件上传

**Comment by xxxxxxbin6** [comment]
哦哦，明白了。

**Comment by xxxxxxbin6** [comment]
哦，对了，webrtc的点播怎么实现的啊？或者说我将文件上传到ftp服务器，如果想点播webrtc能做到吗？还是说必须得上传到zlm的指定目录

**Comment by xia-chu** [comment]
目前必须上传到zlm的指定目录
