### ISSUE TITLE
[BUG]: BUG 流注销后，hls文件无法删除，一直停留在硬盘上的问题

### ISSUE THREAD

**Issue by hany-dev** [ZLMediaKit/ZLMediaKit#1485]
### 现象描述

在最新版本的程序中hls文件在流注销后，hls视频文件无法被删除，仍然会停留在硬盘上，追踪程序运行后，发现在2月23好的提交上出现了该问题，commit ID=b2bb37dc5cd1c4dba001fbf7d6c7054e8aef7b33，这次提交中对toolkit进行了修改，使得在File类中删除hls文件夹时，进入到了第一个if分支，将原本的文件夹，判断成了文件，从而无法删除。
### 如何复现?
运行程序，推流一段时间后断流，即可查看到硬盘上未被删除的hls文件

### 相关日志或截图
![图片](https://user-images.githubusercontent.com/39269298/157409614-12fff15d-6e0e-44b6-b110-ff84814600b8.png)

图片中，path是一个路径，右下角为path的具体内容，但是进入到了file的分支，从而没能删除掉

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置
常规配置，无修改

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
常规环境即可

* **代码提交记录/git commit hash**:
commit ID=b2bb37dc5cd1c4dba001fbf7d6c7054e8aef7b33
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
是一个bug https://stackoverflow.com/questions/42876210/c-fopen-opening-directories 类似这种

**Comment by xiongguangjie** [comment]
ZLToolKit 切换到 https://github.com/ZLMediaKit/ZLToolKit/tree/fueature/fix_is_file_error 这个分支修复这个问题

**Comment by xiongguangjie** [comment]
我在linux 上试过了，没问题，手上没windows 的环境不知道是否ok

**Comment by hany-dev** [comment]
好的，辛苦了，谢谢您这么快的完成了修改

**Comment by xia-chu** [comment]
问题修复了 请更新代码
