### ISSUE TITLE
关于在QQ群被子悦踢了整件事。

### ISSUE THREAD

**Issue by leejuen** [ZLMediaKit/ZLMediaKit#1486]
这个事件主要是我根据文档编译时出了一些问题，导致我想问问群友有没有别的编译文档时莫名其妙被子悦踢了。这个未免有些过于霸道了吧？！

**Comment by xia-chu** [comment]
抱歉，你的提问: "有编译zlmediakit的文档吗", 让我以为又是一个完全不看wiki和readme的伸手党，瞬间火气就上来了。
看了下你的资料页，也是最近入群的，按道理不应该没看readme，因为两个qq群号现在都做了隐藏处理，目的就是为了让用户查看readme和wiki，而且入群公告也强调查看wiki的重要性，那个大群也要求必须阅读wiki才能入群，当时踢人确实欠妥，没有给理由和申辩的机会。以上都是在误会的前提下，实属抱歉，情绪管理没做好。
不过，如果下次发现，大群中混进了不看readme和wiki的用户，那么会在等他申辩的情况下，提示让他加入门群，让他自己退群。

**Comment by xue9957** [comment]
> 

还有群能拉一下嘛 有些问题解决不了
