### ISSUE TITLE
[技术咨询]整合ffmpeg的一些请教

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1488]
大佬, 我已经实现了ffmpeg作为解封装的模块.
这样数据都可以压入到ffmpeg来解封装成Avpacket, 然后直接转成frame和tracker, 并进入muxer.
这样就避免了关键帧没办法识别出来的问题, 以及如果流有多个pps与sps解析不完整的问题.

但是现在有一个问题就是如何我不开新线程下,比较理想的实现异步效果呢?

现在我的方案就是:

1. 类似TSDeocoder, 通过方法ssize_t FFmpegDecoder::input(const uint8_t *data, size_t bytes)方法, 压入上层的数据包.
2. 内部有一个toolkit::BufferLikeString _remain_data;作为接收数据的缓存.
3. avio_alloc_context注册一个read回调, 在这个回调内读取_remain_data缓存数据并返回.
4. 然后为了能异步, 创建一个定时器, 周期性运行定时器调用av_read_frame生成avpacket, 然后做时间基转换后生成frame提交给sink.
5. 这样就是读一阵数据, 写入一阵数据.

但是现在问题就是, 如果在定时器内使用while (av_read_frame(_format_context.get(), pkt.get()) >= 0), 尽可能的把缓存数据读取完.
就会造成, 如果 avio_alloc_context注册的读回调中缓存数据已经读完, 返回AVERROR_EOF后, 客户端播放就会花屏, 提示p帧解码出错.

如果不使用while (av_read_frame(_format_context.get(), pkt.get()) >= 0), 而是仅仅只是av_read_frame读取一帧, 那么客户端播放时就是正常的, 只是会卡顿, 因为timer定时器产生的速度远远跟不上播放消费的速度.

后来我又尝试了使用新开线程的方式.在avio_alloc_context的读回调方法里面使用条件锁, 确保一直有数据可以读, 如果没有数据就阻塞在那.这样是可以解决读取帧数据不全的问题, 但是回调到sink压入frame时就只能使用poller创建异步task来做, 让后续流程回到本身的线程中.这样感觉又会频繁的线程切换, 不太理想.

正好大佬, 您以前说过您之前就已经实现了ffmpeg来解封, 所以, 我现在想要请教下, 如何才能把这个逻辑转成zlm的异步方式呢?
或者怎么做才是比较好的方式呢?

**Comment by xiongguangjie** [comment]
你用ffmpeg 的parser 来切分码流（分帧），会正确识别关键帧

**Comment by xiongguangjie** [comment]
你用ffmpeg 的parser 来切分码流（分帧），会正确识别关键帧

**Comment by xiongguangjie** [comment]
参考这个 http://ffmpeg.org/doxygen/4.0/decode_video_8c-example.html

**Comment by xiongguangjie** [comment]
是的
