### ISSUE TITLE
[BUG]: BUG 现象描述 webrtc echo不能正常工作

### ISSUE THREAD

**Issue by idreamerhx** [ZLMediaKit/ZLMediaKit#1489]
### 现象描述
<pre>
webrtc echo不能正常工作
</pre>

### 如何复现?

参考启用webrtc编译zlmediakit。测试push、play已经正常工作（在一个网页push，一个play）
点击echo 无反应。后台报错日志

### 相关日志或截图
<pre>

2022-03-10 15:59:21.286 I MediaServer[2967-event poller 1] H264Rtp.cpp:182 outputFrame | new gop received, rtp:
version:2
padding:0
ext:12
csrc:0
mark:1
pt:102
seq:38434
stamp:2643473103
ssrc:613816643
rtp size:1116
payload offset:16
payload size:1088

2022-03-10 15:59:22.430 I MediaServer[2967-event poller 2] WebRtcTransport.cpp:326 WebRtcTransportImp | zlm_16
2022-03-10 15:59:22.455 W MediaServer[2967-event poller 2] WebRtcTransport.cpp:866 onShutdown | Assertion failed: (!rtp_rtx_ssrc.empty() || !send_rtp), function checkValid, file /opt/ZLMediaKit/webrtc/Sdp.cpp, line 1296.
2022-03-10 15:59:22.455 D MediaServer[2967-event poller 2] WebApi.cpp:243 http api debug |
# request:
POST /index/api/webrtc?app=live&stream=test&type=echo
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br
Accept-Language : zh-CN,zh;q=0.9,en;q=0.8
Connection : keep-alive
Content-Length : 5597
Content-Type : text/plain;charset=UTF-8
Host : 192.168.1.30:4433
Origin : https://192.168.1.30:4433
Referer : https://192.168.1.30:4433/webrtc/
sec-ch-ua : " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-origin
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
# content:
v=0
o=- 2077405846570908114 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:XeAz
a=ice-pwd:PIYvrjgkzUySVI4cZydwZtK/
a=ice-options:trickle
a=fingerprint:sha-256 89:30:9D:C1:35:7F:0F:72:37:CA:1F:38:0C:5D:64:0D:52:C6:C9:13:36:4F:FE:EA:C4:83:37:46:94:16:19:16
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 117 35 36 114 115 116 62 118
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:XeAz
a=ice-pwd:PIYvrjgkzUySVI4cZydwZtK/
a=ice-options:trickle
a=fingerprint:sha-256 89:30:9D:C1:35:7F:0F:72:37:CA:1F:38:0C:5D:64:0D:52:C6:C9:13:36:4F:FE:EA:C4:83:37:46:94:16:19:16
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- 473a1a3c-9eb6-4af0-96a5-e0e9058605cc
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/9
# response:
{
   "code" : -400,
   "msg" : "Assertion failed: (!rtp_rtx_ssrc.empty() || !send_rtp), function checkValid, file /opt/ZLMediaKit/webrtc/Sdp.cpp, line 1296.",
   "sdp" : null
}

2022-03-10 15:59:22.456 I MediaServer[2967-event poller 2] WebRtcTransport.cpp:330 ~WebRtcTransportImp | zlm_16
2022-03-10 15:59:23.995 W MediaServer[2967-event poller 1] H264Rtp.cpp:53 inputRtp | start drop h264 gop, last seq:39003, rtp:
version:2
padding:0

</pre>

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: commit caf6ddf55420c613a09a5775a5a0c4a0a71b556a (HEAD -> master, origin/master, origin/HEAD)
* **操作系统及版本**:Ubuntu 20.04.2 LTS \n \l

* **硬件信息**:
* Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit

* **其他需要补充的信息**:
libsrtp-2.3.0
libssl-dev/focal-updates,now 1.1.1f-1ubuntu2.10

**Comment by xia-chu** [comment]
实测发现Firefox确实测试echo不行，但是chrome却可以，应该是rtp或sdp要做点修改才行
