### ISSUE TITLE
[技术咨询]如何点播时压缩分辨率

### ISSUE THREAD

**Issue by wongdu** [ZLMediaKit/ZLMediaKit#1490]
请教个问题：
现在客户有一个需求：点播视频文件，但是点播过程中，希望能降低视频分辨率，有点类似实时转码。

昨天测试了zlmedia,发现zlmedia已经做了点播，可以播放mp4、flv、mpg等。看了wiki的点播部分，说http直接播放并没有解复用文件，但是想降低原始分辨率，应该是要解析文件，目前想先用mp4文件来做验证。

昨天做了测试，将mp4文件调用ffmpeg进行切片成多个ts文件，然后直接http点播对应的m3u8文件，是可以播放、拖动的。

客户希望播放的时候，实时的压缩分辨率，然后退出播放后，中间产生的临时文件能自动删除，所以昨天测试的那种预先切片的方式不行，打算点播的时候，根据seek的位置来产生ts切片文件，实现点播。

请问这样的思路是对的吗？

**Comment by xiongguangjie** [comment]
建议使用hls 协议多分辨率的方案，由客户端根据情况播放不同的分辨率，事先转码为多个分辨率的源，然后hls 播放，这是成本最低，最可行的方案，其他什么实时转码，代价高得不可想象

**Comment by wongdu** [comment]
谢谢
