### ISSUE TITLE
[技术咨询]有新的tag可使用吗,当前的tag已是两年前的啦~

### ISSUE THREAD

**Issue by qinzhenyi1314** [ZLMediaKit/ZLMediaKit#1491]
**咨询的功能模块**
整个项目

**咨询的具体内容和问题**
你好，已star过咱们的项目啦~
看到ZLMediaKit一直是在更新的，有最新的tag可以使用吗？

**Comment by xiongguangjie** [comment]
master 就可以使用

**Comment by xia-chu** [comment]
因为zlm没有所谓的bata alpha rc release等流程，这个太费时间和精力的。
建议直接用master分支，如果有bug，我会及时修复。
