### ISSUE TITLE
[技术咨询]您好，请教FFMPEG推流RTMP的问题

### ISSUE THREAD

**Issue by poonweif** [ZLMediaKit/ZLMediaKit#1494]
**咨询的功能模块**
- FFMPEG向ZML进行RTMP推流

**咨询的具体内容和问题**
- 您好，想请教一下，我用FFMPEG5.0版本的命令行向ZLM进行RTMP推流时，ZLM会创建多种格式的流，但是使用FFMPEG的代码方式实现向ZLM进行RTMP推流时，ZLM只创建了一个RTMP格式的流，请问会是什么原因呢？我的代码需要根据什么标准设计吗？请不吝赐教，严重感谢^_^

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by wasphin** [comment]
如果使用 API 推的流使用 rtmp 协议播放正常，通常不应该有区别，可以再贴下服务器的日志检查下。

**Comment by xia-chu** [comment]
@poonweif  我觉得应该是代码有bug，可以提供下zlm的日志，以及rtmp抓包

**Comment by poonweif** [comment]
[cap-log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8259356/cap-log.zip)
我也感觉是我的代码有bug，但就不知道是哪里有问题，还请高人提点^_^

**Comment by poonweif** [comment]
> @poonweif 我觉得应该是你代码有bug，可以提供下zlm的日志，以及rtmp抓包
[cap-log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8302786/cap-log.zip)
麻烦高人指点一下，谢谢

**Comment by wasphin** [comment]
这个抓包 wireshark 解析不出来，应该还是自己实现问题，建议再仔细参考 ffmpeg 进行检查一下自己的实现。

**Comment by poonweif** [comment]
> 这个抓包 wireshark 解析不出来，应该还是自己实现问题，建议再仔细参考 ffmpeg 进行检查一下自己的实现。

我把视频流录制到本地，发现用播放器播放视频的时候时间很快（1分钟的视频1秒多播放完），这会是什么问题呢？

**Comment by xia-chu** [comment]
@poonweif 分析zlm日志，你设置ffmpeg avformat的extra data不正确导致的
