### ISSUE TITLE
[技术咨询] 关于IGMP的说明文档

### ISSUE THREAD

**Issue by Caskia** [ZLMediaKit/ZLMediaKit#1496]
你好，在文档中看到该项目支持multicast udp，请问有没有关于multicast，IGMP这方面的部署例子，谢谢。

**Comment by xia-chu** [comment]
rtsp支持组播，组播ip范围由配置文件 `multicast.addrMax` `multicast.addrMin` 设定，端口由 `rtp_proxy.port_range`设定。
在用ffplay测试组播时，可以设定选项`-rtsp_transport udp_multicast`

**Comment by Caskia** [comment]
> rtsp支持组播，组播ip范围由配置文件 `multicast.addrMax` `multicast.addrMin` 设定，端口由 `rtp_proxy.port_range`设定。 在用ffplay测试组播时，可以设定选项`-rtsp_transport udp_multicast`

是否可以使用vlc播放端增加vlcmulticast参数进行测试？

**Comment by xia-chu** [comment]
vlc应该支持组播 自己搜索下资料吧。
