### ISSUE TITLE
[BUG]: 使用rtp_proxy功能，ZLM出现内存泄漏

### ISSUE THREAD

**Issue by sheds00** [ZLMediaKit/ZLMediaKit#1497]
代码版本:https://github.com/ZLMediaKit/ZLMediaKit/commit/4af83cbe7c7940ab483cb95a1c481a79feb02319
配置文件 : 在默认配置文件基础上 把 publishToHls=0和publishToMP4=0 和 rtp_proxy.port=10010
运行环境:ubuntu-18.04 gcc-7.5 硬件: CPU: [i7-6700K@4.00GHz] 4核8线程, 内存:16GB
问题描述:同时128路1080 h264 rtp+ps推流到rtp_proxy tcp服务，推流30秒断开，一直重复循环。 出现内存暴增，并且关闭推流程序，内存不下降情况。

**Comment by xia-chu** [comment]
你提的issue没任何截图以证明你说的观点，我不认为zlm有内存泄露的问题，实时上，issue反馈的多数所谓bug最后证实都不是zlm的bug。
你可以编译zlm时，cmake时指定参数 `-DENABLE_MEM_DEBUG`以开启内存统计功能，然后通过`getStatistic` http api获取统计信息再反馈到issue。

**Comment by sheds00** [comment]
代码版本:[增加RTP端口范围]
日志文件
[2022-03-18_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/8296455/2022-03-18_00.log)

1.推流时zlm进程信息和getStatistic返回结果
![1](https://user-images.githubusercontent.com/70497421/158917758-a5b8e6d1-7584-4006-a416-90170123bbcd.png)

`{
    "code": 0,
    "data": {
        "Buffer": 644489,
        "BufferLikeString": 41985,
        "BufferList": 0,
        "BufferRaw": 479496,
        "Frame": 1408,
        "FrameImp": 1024,
        "MediaSource": 512,
        "MultiMediaSourceMuxer": 128,
        "RtmpPacket": 40704,
        "RtpPacket": 439040,
        "Socket": 188,
        "TcpClient": 0,
        "TcpServer": 43,
        "TcpSession": 129,
        "UdpServer": 16,
        "UdpSession": 0,
        "threadMem": [
            {
                "threadMemBlock": 489,
                "threadMemBlockTypeCount": "0~128:388;128~256:1;256~512:0;512~1024:100;1024~2048:2;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 86306,
                "threadMemUsageMB": 0,
                "threadName": "event poller 0"
            },
            {
                "threadMemBlock": 1235181,
                "threadMemBlockTypeCount": "0~128:945904;128~256:22631;256~512:12688;512~1024:15450;1024~2048:195322;2048~4096:4148;4096~8192:4514;8192~16384:8906;16384~32768:22570;32768~65536:1952;65536~131072:418;131072~262144:314;262144~524288:366;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 1303345844,
                "threadMemUsageMB": 1242,
                "threadName": "event poller 1"
            },
            {
                "threadMemBlock": 244,
                "threadMemBlockTypeCount": "0~128:225;128~256:2;256~512:5;512~1024:11;1024~2048:3;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 27106,
                "threadMemUsageMB": 0,
                "threadName": "event poller 2"
            },
            {
                "threadMemBlock": 172,
                "threadMemBlockTypeCount": "0~128:159;128~256:2;256~512:0;512~1024:8;1024~2048:2;2048~4096:3;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 23803,
                "threadMemUsageMB": 0,
                "threadName": "event poller 3"
            },
            {
                "threadMemBlock": 64,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:0;1024~2048:2;2048~4096:2;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 10809,
                "threadMemUsageMB": 0,
                "threadName": "event poller 4"
            },
            {
                "threadMemBlock": 63,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:2;1024~2048:0;2048~4096:1;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 6689,
                "threadMemUsageMB": 0,
                "threadName": "event poller 5"
            },
            {
                "threadMemBlock": 62,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:2;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 3977,
                "threadMemUsageMB": 0,
                "threadName": "event poller 6"
            },
            {
                "threadMemBlock": 1356638,
                "threadMemBlockTypeCount": "0~128:1038915;128~256:24857;256~512:13936;512~1024:16960;1024~2048:214536;2048~4096:4556;4096~8192:4958;8192~16384:9782;16384~32768:24790;32768~65536:2144;65536~131072:406;131072~262144:380;262144~524288:420;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 1440728534,
                "threadMemUsageMB": 1373,
                "threadName": "event poller 7"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 0"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 1"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 2"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 3"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 4"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 5"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 6"
            },
            {
                "threadMemBlock": 13,
                "threadMemBlockTypeCount": "0~128:15;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 193,
                "threadMemUsageMB": 0,
                "threadName": "work poller 7"
            }
        ],
        "totalMemBlock": 2594318,
        "totalMemBlockTypeCount": "0~128:1986998;128~256:47525;256~512:26692;512~1024:32599;1024~2048:409867;2048~4096:8710;4096~8192:9473;8192~16384:18688;16384~32768:47360;32768~65536:4096;65536~131072:824;131072~262144:702;262144~524288:786;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
        "totalMemUsage": 2746486942,
        "totalMemUsageMB": 2619
    }
}`


2.关闭推流三分钟后,zlm进程信息和getStatistic返回结果
![2](https://user-images.githubusercontent.com/70497421/158917891-6c8c99df-62c2-49fa-850e-78cf4cc6b915.png)

`{
    "code": 0,
    "data": {
        "Buffer": 9,
        "BufferLikeString": 1,
        "BufferList": 0,
        "BufferRaw": 8,
        "Frame": 0,
        "FrameImp": 0,
        "MediaSource": 0,
        "MultiMediaSourceMuxer": 0,
        "RtmpPacket": 0,
        "RtpPacket": 0,
        "Socket": 60,
        "TcpClient": 0,
        "TcpServer": 43,
        "TcpSession": 1,
        "UdpServer": 16,
        "UdpSession": 0,
        "threadMem": [
            {
                "threadMemBlock": 183,
                "threadMemBlockTypeCount": "0~128:180;128~256:1;256~512:0;512~1024:2;1024~2048:2;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 12448,
                "threadMemUsageMB": 0,
                "threadName": "event poller 0"
            },
            {
                "threadMemBlock": 69,
                "threadMemBlockTypeCount": "0~128:69;128~256:0;256~512:0;512~1024:2;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 4316,
                "threadMemUsageMB": 0,
                "threadName": "event poller 1"
            },
            {
                "threadMemBlock": 70,
                "threadMemBlockTypeCount": "0~128:70;128~256:0;256~512:0;512~1024:0;1024~2048:2;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 5757,
                "threadMemUsageMB": 0,
                "threadName": "event poller 2"
            },
            {
                "threadMemBlock": 318,
                "threadMemBlockTypeCount": "0~128:294;128~256:5;256~512:4;512~1024:13;1024~2048:3;2048~4096:1;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 34503,
                "threadMemUsageMB": 0,
                "threadName": "event poller 3"
            },
            {
                "threadMemBlock": 62,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:0;1024~2048:2;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 5385,
                "threadMemUsageMB": 0,
                "threadName": "event poller 4"
            },
            {
                "threadMemBlock": 63,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:2;1024~2048:0;2048~4096:1;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 6689,
                "threadMemUsageMB": 0,
                "threadName": "event poller 5"
            },
            {
                "threadMemBlock": 62,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:2;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 3977,
                "threadMemUsageMB": 0,
                "threadName": "event poller 6"
            },
            {
                "threadMemBlock": 62,
                "threadMemBlockTypeCount": "0~128:62;128~256:0;256~512:0;512~1024:0;1024~2048:2;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 5385,
                "threadMemUsageMB": 0,
                "threadName": "event poller 7"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 0"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 1"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 2"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 3"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 4"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 5"
            },
            {
                "threadMemBlock": 17,
                "threadMemBlockTypeCount": "0~128:19;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 385,
                "threadMemUsageMB": 0,
                "threadName": "work poller 6"
            },
            {
                "threadMemBlock": 15,
                "threadMemBlockTypeCount": "0~128:17;128~256:0;256~512:0;512~1024:0;1024~2048:0;2048~4096:0;4096~8192:0;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:0;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
                "threadMemUsage": 289,
                "threadMemUsageMB": 0,
                "threadName": "work poller 7"
            }
        ],
        "totalMemBlock": 2306,
        "totalMemBlockTypeCount": "0~128:2094;128~256:37;256~512:68;512~1024:87;1024~2048:11;2048~4096:2;4096~8192:1;8192~16384:0;16384~32768:0;32768~65536:0;65536~131072:0;131072~262144:8;262144~524288:0;524288~1048576:0;1048576~2097152:0;2097152~4194304:0",
        "totalMemUsage": 2332917,
        "totalMemUsageMB": 2
    }
}`

**Comment by xia-chu** [comment]
实际上没内存泄露，你停止推流后`totalMemUsageMB`也降低到2MB了。
这个问题可能是malloc库内存碎片问题，也就是zlm把内存释放给malloc库了，但是malloc并没返回给操作系统。

你可以安装jemalloc在cmake再编译zlm，这样zlm会链接jemalloc库，基本就不会存在内存碎片的问题了。

**Comment by xia-chu** [comment]
apt-get install jemalloc这样安装

**Comment by sheds00** [comment]
但是 使用 openRtpServer 和 closeRtpServer 进行多路RTP推流测试，内存就不会出现这种情况，这个正常吗？

**Comment by sheds00** [comment]
但是 使用 openRtpServer 和 closeRtpServer 进行多路RTP推流测试，内存就不会出现这种情况，这个正常吗？

**Comment by xia-chu** [comment]
只要`totalMemUsageMB`能降下去 都是正常的

**Comment by xia-chu** [comment]
单端口和多端口 本质没区别的 数据处理完全逻辑一致

**Comment by sheds00** [comment]
好的,感谢 我试下jemalloc
