### ISSUE TITLE
[技术咨询]请问webrtc模式下，延迟能达到多少，是否要比rtmp低很多

### ISSUE THREAD

**Issue by ivoidcat** [ZLMediaKit/ZLMediaKit#1499]
**咨询的功能模块**
推拉流
**咨询的具体内容和问题**
请问webrtc模式下，延迟能达到多少，是否要比rtmp低很多
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
自己测试一下不就知道了吗
