### ISSUE TITLE
[技术咨询]通过addStreamProxy API 的拉的视频流无声音，IPC音频已设置成AAC

### ISSUE THREAD

**Issue by utopiazeng** [ZLMediaKit/ZLMediaKit#1500]
转出来的视频流，在vlc播放也没有声音，请求帮助

**Comment by xia-chu** [comment]
咋关了？

**Comment by auleaf** [comment]
我也碰到这个问题,麻烦问一下,咋解决的呢?我是拉流代理拉的rtmp, 生成的流然后用vlc播放rtmp声音图像正常,但其它的如hls和网页里用webrtc都没有声音,不知道是不是哪个参数配置不对,已经在ini和拉流代理参数里都设了encode-audio=1
