### ISSUE TITLE
webrtc一顿一顿的，而且一个播放关掉就停止推流了[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by bzyiostream** [ZLMediaKit/ZLMediaKit#1501]
画面转场的时候明显的模糊了，再清晰，再循环这样
同时多个设备播放，一个设备关闭了，就停止推流了
![image](https://user-images.githubusercontent.com/12508540/158561625-568730f7-6cc8-4695-83fb-9f7a6f590ceb.png)

**Comment by xia-chu** [comment]
咋关了？

**Comment by bzyiostream** [comment]
QQ群问过了
