### ISSUE TITLE
[技术咨询]Android是否可以推流

### ISSUE THREAD

**Issue by BeaHugs** [ZLMediaKit/ZLMediaKit#1502]
**咨询的功能模块**
- Android是否可以推流

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
我没明白你想问什么，你是想问zlm支持Android么？

**Comment by inprise1980** [comment]
android可以推rtmp流到zlm。这跟客户端没有必然关联，推rtsp或rtmp流zlm都支持。
