### ISSUE TITLE
[功能请求]MediaSource::for_each_media性能优化

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1504]
这个方法应该是使用频率最高的方法了.
我还是觉得作为一个成熟的流媒体服务器, 随时监控服务器状态是非常重要的.
应该周期性的向上层业务系统反馈服务器状态, 以便于监控.
而服务器状态就应该包含了目前所有流的状态.

之前您说过for_each_media周期性调用会有很大的性能问题.
因为这个地方加了锁, 所以我想是否可以改进这里.

目前几个方案, 一个是采用https://github.com/khizmax/libcds
这类的无锁map来替换掉s_media_source_map, 但是这个方案侵入性比较强.

另外就是采用https://github.com/AlexeyAB/object_threadsafe
的线程安全map, 大概测试了下性能的确不错.侵入性也不强, 但是代码几年没有更新了, 所以不是很清楚稳定性.
不敢放在生产服务器上使用.

另外就是采用读写锁了, 读共享, 写独占.
这样性能应该也比直接锁mutex要好.

所以能否优化下这个地方的代码呢?
否则被您说过后不敢周期性调用for_each_media来反馈服务器状态了.
但是作为成熟的流媒体服务器, 这玩意又是离不开的.

比如srs, 比如百度brpc自带的mediaServer都可以实时的显示或者反馈每个流的状态.

**Comment by xia-chu** [comment]
s_media_source_map这个对象是读的多 写的少，用读写锁性能就足够了

**Comment by xia-chu** [comment]
你在hook中访问s_media_source_map也可以，一般对性能影响不会太大的 但是我觉得，这个功能比较鸡肋，自己要获取，去拉一遍就是了，hook出去，人家又不一定要这个数据

**Comment by xia-chu** [comment]
反正，我不认为目前在hook中添加这个信息是必要的，这个比较适合在你的fork分支中实现。

**Comment by alexliyu7352** [comment]
可以增加一个配置选项嘛.
有需要打开选项, alive那个hook就会反馈.
如果关闭那么就无所谓了.和当前逻辑一样.

夏楚 ***@***.***> 于2022年3月20日周日 14:34写道：
