### ISSUE TITLE
[技术咨询]live和record目录下的ts文件会自动删除吗？ 

### ISSUE THREAD

**Issue by wyzhou007** [ZLMediaKit/ZLMediaKit#1509]
live目录下的ts文件会自动删除吗？
![image](https://user-images.githubusercontent.com/22088756/159219113-ce680ddb-fc72-4d2a-97c0-d2a2a01e0875.png)

**Comment by xia-chu** [comment]
会删除 但是之前有个bug 导致无法删除，你更新下代码，现在会自动删除的

**Comment by wyzhou007** [comment]
docker镜像版本更新了吗，我这主要是用docker版本

**Comment by xia-chu** [comment]
没有更新docker 建议自己编译吧
