### ISSUE TITLE
[技术咨询]MEPG.Cpp中相关逻辑

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#1511]
mpeg_muxer_input
后的flushCache()有什么用?

实际上注释掉这个flushCache一样可以播放.
因为在mpeg_muxer_create的回调中会调用flushCache

所以每个mpeg_muxer_input后的flushCache有什么用?

**Comment by xia-chu** [comment]
mpeg_muxer_create回调中的flushCache是容错代码，防止内存越界，一般不会发生的。

**Comment by alexliyu7352** [comment]
明白了.
