### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by poonweif** [ZLMediaKit/ZLMediaKit#1519]
### 现象描述
   1.MediaServer崩溃
   2.config.ini文件自动清空

### 相关日志或截图

[2022-03-24_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/8337924/2022-03-24_00.log)
![ERR](https://user-images.githubusercontent.com/30920089/159829711-52f4f223-3af9-499a-a252-bad73bbb5674.png)

[Report.wer]
<details>
<summary>展开查看详细日志</summary>
<pre>
Version=1
EventType=BEX64
EventTime=132925613129333963
ReportType=2
Consent=1
ReportIdentifier=4dc0878c-ab17-11ec-80b9-0a94efb269cb
IntegratorReportIdentifier=4dc0878b-ab17-11ec-80b9-0a94efb269cb
NsAppName=MediaServer.exe
Response.type=4
Sig[0].Name=应用程序名
Sig[0].Value=MediaServer.exe
Sig[1].Name=应用程序版本
Sig[1].Value=0.0.0.0
Sig[2].Name=应用程序时间戳
Sig[2].Value=62148863
Sig[3].Name=故障模块名称
Sig[3].Value=MediaServer.exe
Sig[4].Name=故障模块版本
Sig[4].Value=0.0.0.0
Sig[5].Name=故障模块时间戳
Sig[5].Value=62148863
Sig[6].Name=异常偏移
Sig[6].Value=0000000000980eec
Sig[7].Name=异常代码
Sig[7].Value=c0000409
Sig[8].Name=异常数据
Sig[8].Value=0000000000000005
DynamicSig[1].Name=OS 版本
DynamicSig[1].Value=6.3.9600.2.0.0.400.8
DynamicSig[2].Name=区域设置 ID
DynamicSig[2].Value=2052
DynamicSig[22].Name=其他信息 1
DynamicSig[22].Value=85f7
DynamicSig[23].Name=其他信息 2
DynamicSig[23].Value=85f71c51d9590dc3892f49c44969705e
DynamicSig[24].Name=其他信息 3
DynamicSig[24].Value=6fd1
DynamicSig[25].Name=其他信息 4
DynamicSig[25].Value=6fd1a9405435cc88cee54b07d032ce1a
UI[2]=D:\DEV\stream\zlmedia\Debug\MediaServer.exe
UI[3]=MediaServer.exe 已停止工作
UI[4]=Windows 可以联机检查该问题的解决方案。
UI[5]=联机检查解决方案并关闭该程序
UI[6]=以后联机检查解决方案并关闭程序
UI[7]=关闭程序
LoadedModule[0]=D:\DEV\stream\zlmedia\Debug\MediaServer.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[4]=C:\Windows\SYSTEM32\libssl-1_1-x64.dll
LoadedModule[5]=C:\Windows\SYSTEM32\libcrypto-1_1-x64.dll
LoadedModule[6]=C:\Windows\system32\WS2_32.dll
LoadedModule[7]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[8]=C:\Windows\SYSTEM32\VCRUNTIME140.dll
LoadedModule[9]=C:\Windows\SYSTEM32\api-ms-win-crt-time-l1-1-0.dll
LoadedModule[10]=C:\Windows\SYSTEM32\api-ms-win-crt-string-l1-1-0.dll
LoadedModule[11]=C:\Windows\SYSTEM32\api-ms-win-crt-utility-l1-1-0.dll
LoadedModule[12]=C:\Windows\SYSTEM32\api-ms-win-crt-runtime-l1-1-0.dll
LoadedModule[13]=C:\Windows\SYSTEM32\api-ms-win-crt-convert-l1-1-0.dll
LoadedModule[14]=C:\Windows\SYSTEM32\api-ms-win-crt-stdio-l1-1-0.dll
LoadedModule[15]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[16]=C:\Windows\system32\USER32.dll
LoadedModule[17]=C:\Windows\SYSTEM32\api-ms-win-crt-filesystem-l1-1-0.dll
LoadedModule[18]=C:\Windows\SYSTEM32\api-ms-win-crt-heap-l1-1-0.dll
LoadedModule[19]=C:\Windows\SYSTEM32\api-ms-win-crt-environment-l1-1-0.dll
LoadedModule[20]=C:\Windows\system32\NSI.dll
LoadedModule[21]=C:\Windows\system32\RPCRT4.dll
LoadedModule[22]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[23]=C:\Windows\system32\msvcrt.dll
LoadedModule[24]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[25]=C:\Windows\system32\GDI32.dll
LoadedModule[26]=C:\Windows\SYSTEM32\ucrtbase.DLL
LoadedModule[27]=C:\Windows\system32\IMM32.DLL
LoadedModule[28]=C:\Windows\system32\MSCTF.dll
LoadedModule[29]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[30]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[31]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[32]=C:\Windows\system32\rsaenh.dll
LoadedModule[33]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[34]=C:\Windows\system32\mswsock.dll
LoadedModule[35]=C:\Windows\system32\uxtheme.dll
LoadedModule[36]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[37]=C:\Windows\system32\dwmapi.dll
LoadedModule[38]=C:\Windows\system32\ole32.dll
LoadedModule[39]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[40]=C:\Windows\SYSTEM32\DNSAPI.dll
LoadedModule[41]=C:\Windows\System32\rasadhlp.dll
LoadedModule[42]=C:\Windows\System32\fwpuclnt.dll
FriendlyEventName=已停止工作
ConsentKey=BEX64
AppName=MediaServer.exe
AppPath=D:\DEV\stream\zlmedia\Debug\MediaServer.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=BF95C03B80A406971684AB65FB76A556

</pre>
</details>

### 配置
默认配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

服务器环境：
    Windows Server 2012 R2 Datacenter 64-bit (6.3, Build 9600) (9600.winblue_r4.141028-1500)
WEB客户端
   Windows10 家庭中文版64
    Chrome 浏览器

推流：
    javacpp(1.5.7)|ffmpeg(5.0) 进行RTMP推流
拉流：
    前端网页ws协议拉流

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个是触发断言了吧 点击`重试`按钮定位下代码
