### ISSUE TITLE
目前提供的HOOK接口和Restful接口支持获取观看人的IP地址吗[技术咨询]

### ISSUE THREAD

**Issue by wyzhou007** [ZLMediaKit/ZLMediaKit#1520]
目前提供的HOOK接口和Restful接口支持获取观看人的IP地址吗

**Comment by xia-chu** [comment]
都支持 请仔细查看wiki

**Comment by wyzhou007** [comment]
看了wiki,才来提问的，调用/index/api/getMediaList 这个接口，返回的客户端ip和观看人的ip对不上，而且多人观看时只返回一个
![_T DKY%N~UQ~Z4DQX)WY$C7](https://user-images.githubusercontent.com/22088756/159831308-e9e02445-138e-4489-9246-589d91daf2f8.png)
![image](https://user-images.githubusercontent.com/22088756/159831318-781eefaa-c737-4560-b0f2-e7c2702a2733.png)

**Comment by wyzhou007** [comment]
还有个疑问，HOOK的回调接口on_http_access和on_flow_report，返回的客户端ip都是流媒体的ip ,这个是回参mediaServerId=rZUSBjCArt7gd2hk, app=null, ip=192.168.1.43, params=, port=55387, path=/live/210235C1CB9156NXXXXX-1/2022-03-24/11/01-35_0.ts, is_dir=false)
192.168.1.43是内网中流媒体的ip

**Comment by wyzhou007** [comment]
> 都支持 请仔细查看wiki

HOOK的回调接口on_http_access和on_flow_report，返回的客户端ip都是流媒体的ip ,这个是回参mediaServerId=rZUSBjCArt7gd2hk, app=null, ip=192.168.1.43, params=, port=55387, path=/live/210235C1CB9156NXXXXX-1/2022-03-24/11/01-35_0.ts, is_dir=false)
192.168.1.43是内网中流媒体的ip

调用http接口中/index/api/getMediaList 这个接口，返回的客户端ip和观看人的ip对不上，而且多人观看时只返回一个
![image](https://user-images.githubusercontent.com/22088756/159833681-1704cbd1-3851-4956-bd7d-93aec4d70457.png)
![image](https://user-images.githubusercontent.com/22088756/159833713-d7423e05-f634-4511-b994-a3d501e7dc59.png)

**Comment by xia-chu** [comment]
getMediaList返回的是推流客户端的ip。
on_play hook开发返回播放器的ip。

**Comment by xia-chu** [comment]
如果你要获取所有播放器的ip，可以用getAllSesssion接口获取当前所有客户端ip，你过滤下本地端口，就是相应服务正连接中的客户端ip。

**Comment by xia-chu** [comment]
没有接口返回所有正在播放的播放ip。
