### ISSUE TITLE
[BUG]: BUG 现象描述---首屏点播很慢达到了3s

### ISSUE THREAD

**Issue by TristingChen** [ZLMediaKit/ZLMediaKit#1521]
大佬请问一下，我这边的播放(关闭音频)首屏很慢，排查过程如下：
创建openrtp的端口时间：2022-03-25 16:01:18.377
渲染的时间：all track reay use 1ms
hook回调的时间：
on_publish  2022-03-25 16:01:18.377
on_stream_change 2022-03-25 16:01:20.216

主要分析结果为on_stream_change的回调接口占用时间过久

相关zlm日志截图：
![2) `XRXWBL)1PCAF4DEA6)Q](https://user-images.githubusercontent.com/25541522/160087644-2b63ee90-d3b5-4ef6-8949-5ad9a0e2e6e8.jpg)

![BIUN03~7@XCBP1OGLE6D 07](https://user-images.githubusercontent.com/25541522/160087606-0676f8e9-975e-4dfd-8ac2-9929871b3d4e.jpg)

**Comment by xia-chu** [comment]
这个流注册这么慢，可能是on_publish回复太慢导致的，也可能是数据sps pps太晚到达有关
