### ISSUE TITLE
新增加HTTP+ES拉流，客户端播放异常

### ISSUE THREAD

**Issue by seamende** [ZLMediaKit/ZLMediaKit#1526]
版主你好！

想扩充ZLM拉流能力，增加交通部的1078车载视频对接协议，1078协议可以通过http-url去获取到es数据，
我模仿hlsplayer做了一个JT1078Player,代码如下：
class JT1078Player : public  HttpClientImp, public PlayerBase, public HlsParser {
}
class JT1078PlayerImp : public PlayerImp<JT1078Player, PlayerBase>, public MediaSink {
}
在AddStreamProxy里面实例化，代码如下：
PlayerBase::Ptr PlayerBase::createPlayer(const EventPoller::Ptr &poller,const string &url_in) {
   if ((strcasecmp("http",prefix.data()) == 0 || strcasecmp("https",prefix.data()) == 0) && end_with(url, ".m3u8")) {
        return PlayerBase::Ptr(new HlsPlayerImp(poller),releasePlayer);
    }

    if ((strcasecmp("http", prefix.data()) == 0 || strcasecmp("https", prefix.data()) == 0) && end_with(url, ".1078")) {
        return PlayerBase::Ptr(new JT1078PlayerImp(poller), releasePlayer);
    }
}

在JT1078Player的onResponseBody回调函数里面能够获取媒体流【去掉1078的包头后得到ES裸流，保存成文件后，用ffplay能够播放】
将收到的数据包组成一个完整的ES数据帧,把数据放到_frame_cache字典，启动定时器去分发数据，代码如下：
void JT1078PlayerImp::onPacket(const char* data, size_t len)
{
       
        static bool s_First = true;
        if (s_First)
        {
            s_First = false;

            addTrack(std::make_shared<H264Track>());
            //addTrack(std::make_shared<AACTrack>());
            addTrackCompleted();

            _frame_cache.clear();
            _stamp[TrackAudio].setRelativeStamp(0);
            _stamp[TrackVideo].setRelativeStamp(0);
            _stamp[TrackAudio].syncTo(_stamp[TrackVideo]);
            setPlayPosition(0);

            weak_ptr<JT1078PlayerImp> weakSelf = dynamic_pointer_cast<JT1078PlayerImp>(shared_from_this());
            //每50毫秒执行一次
            _timer = std::make_shared<Timer>(0.05f, [weakSelf]() {
               auto strongSelf = weakSelf.lock();
                if (!strongSelf) {
                    return false;
                }
                strongSelf->onTick();
                return true;
                }, getPoller());
        }
    
	    //_timeStamp从收到的数据包中解析出来
        FrameFromPtr::Ptr frameSmart(new FrameFromPtr((char*)data, len, _timeStamp, _timeStamp,4));
   
        frameSmart->setCodecId(CodecH264);
    
        inputFrame(frameSmart);
      
}
	
bool JT1078PlayerImp::inputFrame(const Frame::Ptr& frame) {
        //计算相对时间戳
        int64_t dts, pts;
        _stamp[frame->getTrackType()].revise(frame->dts(), frame->pts(), dts, pts,false);
        //根据时间戳缓存frame
        _frame_cache.emplace(dts, Frame::getCacheAbleFrame(frame));

        if (getBufferMS() > 30 * 1000) {
            //缓存超过30秒，强制消费至15秒(减少延时或内存占用)
            while (getBufferMS() > 15 * 1000) {
                MediaSink::inputFrame(_frame_cache.begin()->second);
                _frame_cache.erase(_frame_cache.begin());
            }
            if(_frame_cache.size() > 0)
            //接着播放缓存中最早的帧
                setPlayPosition(_frame_cache.begin()->first);
        }
        return true;
}

void JT1078PlayerImp::onTick() {
        auto it = _frame_cache.begin();
        while (it != _frame_cache.end()) {
            if (it->first > getPlayPosition()) {
                //这些帧还未到时间播放
                break;
            }

            if (getBufferMS() < 3 * 1000) {
                //缓存小于3秒,那么降低定时器消费速度(让剩余的数据在3秒后消费完毕)
                //目的是为了防止定时器长时间干等后，数据瞬间消费完毕
                setPlayPosition(_frame_cache.begin()->first);
            }

            //消费掉已经到期的帧
            MediaSink::inputFrame(it->second);
            it = _frame_cache.erase(it);
        }
    }
	
客户端能播放，但是播放速度很快，并且画面会回跳，请教一下版主，是我哪里没处理好？

**Comment by seamende** [comment]
void JT1078Player::onResponseBody(const char* buf, size_t size, size_t recvedSize, size_t totalSize) {
        if (recvedSize == size) {
            //刚开始
            _m3u8.clear();
            m_es.clear();
        }
        _m3u8.append(buf, size);

        bool isIdr = false;
        //解析1078音视频数据
        Head1708 head;
        while (true)
        {
            const char cDest[] = { 0x30, 0x31,0x63,0x64,0x00 };
            const int HEADLEN = sizeof(Head1708);// 30;
            const int LENPOS = 28;
            size_t posFind = _m3u8.find(std::string(cDest, strlen(cDest)));
            if (posFind == std::string::npos)
            {
                _m3u8.clear();
                return;
            }
            if (posFind + HEADLEN >= _m3u8.length())
            {
                return;
            }
           
            memcpy(&head, _m3u8.c_str() + posFind, HEADLEN);
            short blockLen = head.m_length;
            unsigned char ucTm0 = *((unsigned char*)(&blockLen));
            unsigned char ucTm1 = *((unsigned char*)(&blockLen) + 1);
            *((unsigned char*)(&blockLen)) = ucTm1;
            *((unsigned char*)(&blockLen) + 1) = ucTm0;
            if (posFind + HEADLEN + blockLen >= _m3u8.length())
            {
                return;
            }
            m_es += _m3u8.substr(posFind + HEADLEN, blockLen);
            _m3u8.erase(0, posFind + HEADLEN + blockLen);
            if ((head.m_type & 0x0f) == 0x00 || (head.m_type & 0x0f) == 0x02)
            {
                //I帧
                if (head.m_type & 0xf0 == 00)
                {
                    isIdr = true;
                }
                break;
            }
        }
        long long timestamp = *((long long*)head.m_timestamp);
        _timeStamp = _WS2_32_WINSOCK_SWAP_LONGLONG(timestamp);
       // cout << "timstamp=" << _timeStamp << endl;

        onPacket(m_es.c_str(), m_es.length());

    }

**Comment by alexliyu7352** [comment]
一般播放速度很快主要是dts的问题.
你可以搜索下dts,pts时间戳校正的相关网页.

你也可以埋点打印下你解析的时间戳是否正确.
