### ISSUE TITLE
[技术咨询]推流正常，但是ts不切分，播放器也无法播放

### ISSUE THREAD

**Issue by dawn2zhang** [ZLMediaKit/ZLMediaKit#1527]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
GB28181流转码
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
GB28181回放推流正常，但是zlmedia中ts文件不切分，一直增大，前端播放器无法播放对应画面
日志中无异常

对应ts现象截图：
![企业微信截图_16485480208400](https://user-images.githubusercontent.com/8624439/160606336-748cc32f-5c88-4c56-a137-cca6c7fa954b.png)
抓包：
[202203291703.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8371145/202203291703.zip)

**Comment by xia-chu** [comment]
这个应该是zlm的一个bug，有两个可能，意思流时间戳有问题，另外可能是一致没等到关键帧

**Comment by dawn2zhang** [comment]
> 这个应该是zlm的一个bug，有两个可能，一是流时间戳有问题，另外可能是一直没等到关键帧

中间有调整过视频编码，这个会造成ts不切分无法播放吗

**Comment by dawn2zhang** [comment]
![Uploading 微信图片_20220330110416.png…]()

**Comment by xia-chu** [comment]
这个视频codec变化导致的问题 那就大了去了 转协议完全不可用了

**Comment by dawn2zhang** [comment]
> 这个视频codec变化导致的问题 那就大了去了 转协议完全不可用了

是的，现在就是完全不行了...流编码变了，解析器是不变的吧

**Comment by xia-chu** [comment]
是的 codec变了 转协议是无法处理的

**Comment by dawn2zhang** [comment]
> 是的 codec变了 转协议是无法处理的

嗯嗯，看了下代码，多谢了~~
