### ISSUE TITLE
[技术咨询]关于ps流的技术咨询

### ISSUE THREAD

**Issue by ypy31393936** [ZLMediaKit/ZLMediaKit#1533]
**咨询的功能模块**
- 接收rtp包

**咨询的具体内容和问题**
- 抓到的包如下图
- 其中  长度为194的rtp包里的信息为   ba ps头   bb ps系统头    bc  ps map头
- 长度为90的rtp包里的信息为  67  SPS
- 长度为74的rtp包里的信息为  68  PPs
- 之后第一个长度为1330的rtp包里的信息为  65  i帧  之后都是i帧的信息  其中还包含了长度为70的rtp包 不知道是什么
- 但我看一些关于ps流的文章例子  他们都是将这些信息放在一个rtp包里的  像这样分开放会不会有影响 或者这样发送的rtp包是对的吗
<img width="823" alt="捕获" src="https://user-images.githubusercontent.com/58900740/161188986-1af7c515-4c43-478b-9c7e-148f945a448f.PNG">

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
只要zlm能正确识别并出视频，那么应该就没问题

**Comment by ypy31393936** [comment]
这种ps流看不了     zlm都没有流注册上来     wvp-pro使用的单端口模式   不知道多端口行不行   这个是gb28181-2011版本推送的  我在试下吧

**Comment by xia-chu** [comment]
可以使用zlm的dump功能 并把rtp文件分享上来 这样我们好分析
