### ISSUE TITLE
[技术咨询] 是否可以将h264或h265裸流数据作为输入源

### ISSUE THREAD

**Issue by liangjw-editor** [ZLMediaKit/ZLMediaKit#1534]
**咨询的功能模块**
作为sdk开发

**咨询的具体内容和问题**
作为C sdk开发时，可以在接收到播放器播放请求后自己将h264或h265裸流数据作为输入源吗？而不是给个url地址让zlmediakit代理。

**Comment by xiangshengjye** [comment]
头文件mk_media.h，自己研究下

**Comment by liangjw-editor** [comment]
感谢，已经验证可以使用裸流数据作为输入源了

**Comment by firawk** [comment]
> 感谢，已经验证可以使用裸流数据作为输入源了

请问有没有样例程序？？能否发我一下，我也想实现

**Comment by liangjw-editor** [comment]
> > 感谢，已经验证可以使用裸流数据作为输入源了
> 
> 请问有没有样例程序？？能否发我一下，我也想实现

没有样例程序，主要用到了mk_media_create创建一个媒体源，用mk_track_create创建音视频轨，用mk_frame_create将码流数据转为frame，用mk_media_input_frame来输入转换好的frame

**Comment by firawk** [comment]
> > > 感谢，已经验证可以使用裸流数据作为输入源了
> > 
> > 
> > 请问有没有样例程序？？能否发我一下，我也想实现
> 
> 没有样例程序，主要用到了mk_media_create创建一个媒体源，用mk_track_create创建音视频轨，用mk_frame_create将码流数据转为frame，用mk_media_input_frame来输入转换好的frame

因为不是做这块的，理解不深，不知道怎么写，如果有一个类似test的程序就能上手快一点。
