### ISSUE TITLE
[技术咨询]addStreamProxy第7路以后的视频无法播放

### ISSUE THREAD

**Issue by hantconny** [ZLMediaKit/ZLMediaKit#1546]
**咨询的具体内容和问题**
使用ffmpeg将本地视频推送到easydarwin，一共推送10路

`ffmpeg -re -stream_loop -1 -i /home/videos/1080p_cam3.mp4 -c:v libx264 -c:a aac -f rtsp rtsp://192.168.41.215/slw/live0`
`ffmpeg -re -stream_loop -1 -i /home/videos/1080p_cam3.mp4 -c:v libx264 -c:a aac -f rtsp rtsp://192.168.41.215/slw/live1`
...
`ffmpeg -re -stream_loop -1 -i /home/videos/1080p_cam3.mp4 -c:v libx264 -c:a aac -f rtsp rtsp://192.168.41.215/slw/live9`

使用addStreamProxy接口按需拉流

`GET http://192.168.41.214/index/api/addStreamProxy?secret=xxx&vhost=192.168.41.214&app=slw&stream=live0&url=rtsp://192.168.41.214/slw/live0&timeout_sec=60.0`
`GET http://192.168.41.214/index/api/addStreamProxy?secret=xxx&vhost=192.168.41.214&app=slw&stream=live1&url=rtsp://192.168.41.214/slw/live1&timeout_sec=60.0`
...
`GET http://192.168.41.214/index/api/addStreamProxy?secret=xxx&vhost=192.168.41.214&app=slw&stream=live9&url=rtsp://192.168.41.214/slw/live9&timeout_sec=60.0`

播放使用videojs，初始化10个video标签分别请求
`http://192.168.41.215/slw/live0.live.mp4`
`http://192.168.41.215/slw/live1.live.mp4`
...
`http://192.168.41.215/slw/live9.live.mp4`

前6路视频没有问题，第7路视频时，虽然api调用成功，但是无法播放。控制台无报错。

**Comment by xia-chu** [comment]
同主机url，浏览器最大支持支持6路http。你可以换ws-flv播放

**Comment by hantconny** [comment]
> 同主机url，浏览器限制最大支持支持6路http。你可以换ws-flv播放，没这个限制

试了下b站的flv.js，使用ws://192.168.41.214/slw/live0.live.flv确实能支持6路以上视频播放，然而一会就把chrome内存溢出了。请问有没有合适的开源库支持多路ws-flv播放？
