### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by Quzhe123** [ZLMediaKit/ZLMediaKit#1547]
**咨询的功能模块**
- 使用addStreamProxy接口拉流。

**咨询的具体内容和问题**
- ZLMediakit+海康NVR，使用addStreamProxy拉取rtsp流，在浏览器端播放对应fmp4。rtsp如果是h264时是正常的，如果是H265时，浏览器端只有声音没有图像，VLC播放一帧后卡顿。
- GET http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&app=live&stream=test&url=rtsp://admin:abcd1234@10.10.10.57:554/Streaming/Channels/1801&rtp_type=0

**Comment by xia-chu** [comment]
嗯 是的 浏览器不支持H265

**Comment by xia-chu** [comment]
vlc对fmp4支持好些不好 你可以实时ffplay

**Comment by Quzhe123** [comment]
好的大佬，我试试

**Comment by xia-chu** [comment]
可以使用wasm方案的播放器 不过体验一般般 高分辨率解码速度感人

**Comment by Quzhe123** [comment]
好的.感谢回答
