### ISSUE TITLE
[技术咨询] sdk无法使用HLS

### ISSUE THREAD

**Issue by swq123459** [ZLMediaKit/ZLMediaKit#1555]
**咨询的功能模块**
- hls

**咨询的具体内容和问题**
开启了httpserver, 创建了media(通过mk_media)，送入了es流， 但是没有看到HLS的媒体注册， 其他http-flv等http相关的都正常

**Comment by swq123459** [comment]
![image](https://user-images.githubusercontent.com/35790719/162650951-ebe47ccb-14ce-4e20-89c1-09bc6b303751.png)
我看正常启动是有HLS的

**Comment by xia-chu** [comment]
mk_media创建时可以指定是否开启hls 你参数设置多少

**Comment by swq123459** [comment]
hls_enabled 设置了1

**Comment by swq123459** [comment]
![image](https://user-images.githubusercontent.com/35790719/162662415-36d476ba-17cc-4cab-9f35-606b03a9e16d.png)
我这里用做了rust的binding，除了hls一切都是工作正常的，用rtsp推也不行，没看看到注册了HLS

**Comment by swq123459** [comment]
我在源码处做了相关打印
![image](https://user-images.githubusercontent.com/35790719/162662673-d236ca76-9a13-4011-a833-739c4338c20d.png)
![image](https://user-images.githubusercontent.com/35790719/162662697-1abdce7e-5475-47a5-b0da-99bb19ed530d.png)

**Comment by xia-chu** [comment]
嗯 能否把H264 es流文件分享上来

**Comment by swq123459** [comment]
我看看，我怀疑是否没有 转 annexb

**Comment by xia-chu** [comment]
hls必须输入annexb格式 其他协议不用，非annexb格式 zlm也会打印警告

**Comment by swq123459** [comment]
可以了，就是这个问题，谢谢，希望还是有更好的错误信息提示，没看到错误信息，sdk的接口，错误回调之类的

**Comment by swq123459** [comment]
- 保持C的API吧，这样二进制兼容，各种语言直接调，哦，既然可以引入异常捕获错误，那为啥不可以传个错误buf进去，通过这个buf返回就好 int func(..., char * errOut, int errOutLen);

- 这样改就是API和旧版不兼容了，但是错误信息对sdk来说很重要

**Comment by xia-chu** [comment]
这个转协议是发散的一个逻辑，是一个1对应N的逻辑 所以用抛异常的方式比较好，当然在c wrapper层可以把这个异常捕获，然后再以参数的方式上传。
不过这个hls非annexb方式输入不生成的问题 我不打算做任何修改，因为这是个约定的问题，如果不按照约定输入数据，那么就不能正常工作，打印提醒日志已经足够了

**Comment by xia-chu** [comment]
当然 你如果不在意性能的话 可以在ts生成相关代码中把非annexb格式转换为annexb格式
