### ISSUE TITLE
[功能请求]推流录制，流断开后在<一定时间内>恢复，流可以写进同一个文件。<一定时间内>时长能否可配置？

### ISSUE THREAD

**Issue by ChandZhang** [ZLMediaKit/ZLMediaKit#1558]
录制mp4文件的场景，当推流断开后，**在一定时间内** 流重新推上来，录制的mp4文件写到一个文件内。

当前版本，"一定时间内"这个我测试大概是10秒左右，有些场景这个时间不太够用。

"一定时间内"这个时长能否支持配置？或者想扩展支持应该从哪里入手？

**Comment by xiongguangjie** [comment]
可以配置，自己看配置文件
