### ISSUE TITLE
[BUG]: 推流断开再次推流等待超时配置项continue_push_ms并不总是能正确执行

### ISSUE THREAD

**Issue by ChandZhang** [ZLMediaKit/ZLMediaKit#1559]
### 现象描述

Version：2022-04-12拉取最新版。

配置项 continue_push_ms 为 15000

使用ffmpeg推流到ZLMediaKit，关闭ffmpeg。此时ZLMediaKit出现两种状态：
1. 日志立即输出一系列“媒体注销”日志。
2. 等待15秒输出一系列“媒体注销”日志。

重复使用ffmpeg推流rtmp，得到上面两种状况，无规律。

查看ZLMediaKit日志，发现是 err 问题，如下：

RtmpSession.cpp:33 onError RTMP推流器(__defaultVhost__/live/stream_film)断开:Stop publishing(5),耗时(s):33
RtmpSession.cpp:33 onError RTMP推流器(__defaultVhost__/live/stream_film)断开:broken pipe(255),耗时(s):28

**即：关闭ffmpeg，得到的事件，有时是 broken pipe(255)，有时是 Stop publishing(5)，且无规律**

### 如何复现?

1. 配置 continue_push_ms 配置项
2. 启动ZLMediaKit
3. 正常使用ffmpeg推流rtmp；
4. 关闭ffmpeg；
5. 重复1-4

### 相关日志或截图

RtmpSession.cpp:33 onError RTMP推流器(__defaultVhost__/live/tchn/stream_film)断开:Stop publishing(5),耗时(s):33
RtmpSession.cpp:33 onError RTMP推流器(__defaultVhost__/live/tchn/stream_film)断开:broken pipe(255),耗时(s):28

**Comment by xia-chu** [comment]
如果zlm发现是推流主动掐断推流的，那么zlm默认关闭断流系统功能，会立即注销流。
如果是由于网络问题导致推流停止的，那么zlm默认开启断流系统功能，会延时注销流。
这样做的目的是在网络不好或其他异常导致推流断开时给 推流器一个重试的机会

**Comment by xia-chu** [comment]
最开始也是所有断开都开启断链续推功能 但是有人提议 推流器主动停止推流 就直接立即注销流

**Comment by xia-chu** [comment]
重新新增了一个提交 应该能规避这个问题
