### ISSUE TITLE
请教本WebRtc内网穿透的方法

### ISSUE THREAD

**Issue by victording123456** [ZLMediaKit/ZLMediaKit#1560]
听闻WebRtc要在互联网上访问，需要先建立STUN Server，本项目的webrtc内没有找到连接STUN Server的地方啊？请问要实现互联网的点对点传输，需要做什么操作？config.ini的 externIP 参数有什么用？

**Comment by xia-chu** [comment]
不支持内网部署zlm的，zlm的webrtc udp端口必须暴露在公网上

**Comment by wanstonq** [comment]
> 不支持内网部署zlm的，zlm的webrtc udp端口必须暴露在公网上

请问，如何通过配置增加ICE Server，使得内网的zlm可以与内网的浏览器进行通信
