### ISSUE TITLE
调用截图的rest api截图时,截取的图片大量重复

### ISSUE THREAD

**Issue by lixinyuan1213** [ZLMediaKit/ZLMediaKit#1561]
### 现象描述

调用截图的rest api截图时,截取的图片大量重复

### 如何复现?

zlmediakit 有100路视频,启动10个线程每隔30s调用rest api截图(每个视频截取一个图片),截取的图片大量重复.
希望截图的图片正常

### 相关日志或截图

![image](https://user-images.githubusercontent.com/8722269/162931009-15641bb9-8f89-426f-a561-db7e5c6291f5.png)

### 配置

默认配置

### 各种环境信息
ubuntu 20.04,16core 32G

**Comment by xia-chu** [comment]
这个图片不是zlm直接产生的吧？zlm的图片文件名是时间戳

**Comment by lixinyuan1213** [comment]
> 这个图片不是zlm直接产生的吧？zlm的图片文件名是时间戳

我通过rest api接口获取到图片后保存的,命名是我通过uuid生成的.

我设置的图片缓存时间是1s,但是我5s请求一次截图的rest api,仍然有大量的重复截图

**Comment by xia-chu** [comment]
你应该分析FFmpeg日志，如果截图失败，那么就会返回上次图片。
你100路视频，建议MediaServer启动时指定启动参数 -t 100

**Comment by xia-chu** [comment]
如果你每30秒同时截图100张，那相当于qps还是100，FFmpeg截图是阻塞式的，截图中耗费一条线程

**Comment by lixinyuan1213** [comment]
> 如果你每30秒同时截图100张，那相当于qps还是100，FFmpeg截图是阻塞式的，截图中耗费一条线程

嗯嗯,谢谢您的回复.
还是原来的场景(100路视频,每隔30s同时截取各路视频的图片).我调整MediaServer的线程数量为100了,并且控制线程,保证线程截取每个视频成功后再去请求(保证每个视频流只有一个线程过来请求,请求成功后下一个再过来),仍然有很多重复的图片.瓶颈在FFmpeg上是吧.MediaServer目前有没有配置,在截图失败后返回异常而不是上一次的图片这样的配置?
十分感谢

**Comment by xia-chu** [comment]
如果截图非常频繁 那么可能会存在多次截图命中同一个GOP缓存的问题，这样截图就会相同。
但是你说每30秒一次，按道理GOP不会这么大，那么这样看来，应该是截图失败了，你应该分析zlm和FFmpeg的日志，看看为什么失败了，是否是截图等待超时了？

**Comment by lixinyuan1213** [comment]
> 如果截图非常频繁 那么可能会存在多次截图命中同一个GOP缓存的问题，这样截图就会相同。 但是你说每30秒一次，按道理GOP不会这么大，那么这样看来，应该是截图失败了，你应该分析zlm和FFmpeg的日志，看看为什么失败了，是否是截图等待超时了？

应该主要是FFmpeg引起的.但是因为zlm截图失败后返回原来的图片,不太符合我们的应用场景.所以截图用了别实现库.十分感谢您给予的帮助.

**Comment by SMJ-YY** [comment]
> > 如果截图非常频繁 那么可能会存在多次截图命中同一个GOP缓存的问题，这样截图就会相同。 但是你说每30秒一次，按道理GOP不会这么大，那么这样看来，应该是截图失败了，你应该分析zlm和FFmpeg的日志，看看为什么失败了，是否是截图等待超时了？
> 
> 应该主要是FFmpeg引起的.但是因为zlm截图失败后返回原来的图片,不太符合我们的应用场景.所以截图用了别实现库.十分感谢您给予的帮助.

你好,请问你用什么实现的截图,我们公司也有类似的需求
