### ISSUE TITLE
[技术咨询]有计划支持RTSP编码类型为MP4V-ES吗？

### ISSUE THREAD

**Issue by mingkof** [ZLMediaKit/ZLMediaKit#1562]
RTSP是”海康综合安防平台“提供的RTSP，这个地址使用海康的SDK（安卓、PC）是可以正常播放的
ffpaly和VLC media player 都没法正常播放；
通过 ZLMediaKit 添加rstp拉流的方式，提示“Factory.cpp:92 getTrackBySdp | 暂不支持该rtsp编码类型:MP4V-ES”。
       ZLMediaKit平台有计划增加支持”MP4V-ES“吗？

**Comment by wasphin** [comment]
这个mp4v-es 是标准格式吗？有没有相关的一些资料什么的？

**Comment by mingkof** [comment]
海康综合安防平台 接口出来的RTSP流地址，其他我也不知道了。

**Comment by xia-chu** [comment]
不打算支持 非转协议目前支持的 转协议无计划支持
