### ISSUE TITLE
[技术咨询]推流录制文件大小

### ISSUE THREAD

**Issue by 1983094983** [ZLMediaKit/ZLMediaKit#1563]
**咨询的功能模块**
 流的录制问题咨询

**咨询的具体内容和问题**
目前在使用ZLM做流媒体服务器, 遇到了流录制的需求, 初步尝试了一段时间,发现使用ffmpeg编码libx264 推流时,开启录制会达到3000kb/s的录制的码率(mediainfo查看的), 总体大小在20M+/min 的情况, 这个是不是有点太大了?我想问问是否有相关的配置或者代码来处理这一块.此外,使用libx265编码时,录制会明显小一些,但是对于推流端来说cpu和内存又会偏高一些, 请问有什么好的办法吗? 谢谢回复~

**注意事项**
我以为这是考虑之内的问题, 暂时没有贴出截图

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
FFmpeg编码264时可以指定比特率的。zlm录制视频不会转码，FFmpeg的比特率是多少就是多少
