### ISSUE TITLE
[技术咨询]国标推流播放卡顿跳帧

### ISSUE THREAD

**Issue by dawn2zhang** [ZLMediaKit/ZLMediaKit#1564]
**咨询的功能模块**
RTP数据转换

**咨询的具体内容和问题**
国标推流，H265+G711，播放flv时卡顿跳帧
大神帮分析下可能的点
附件是RTPdump文件
[202204131429.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8478892/202204131429.zip)

**Comment by justimaging** [comment]
我也遇到同样的问题，播放卡顿，闪屏，请问解决了吗？

**Comment by xia-chu** [comment]
@dawn2zhang 你提供的文件不是zlm dump出来的 无法分析

**Comment by wasphin** [comment]
应该是 https://github.com/irtlab/rtptools 这个工具 dump 的, 可以再使用这个工具重放成网络流.

macOS 可以直接安装:
```
brew install rtptool
```

RHEL/CentOS 7/8 可以使用:
https://copr.fedorainfracloud.org/coprs/wasphin/streaming/

**Comment by wasphin** [comment]
数据不到 1s, 能不能跟再多 dump 点.
