### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by poonweif** [ZLMediaKit/ZLMediaKit#1565]
大神您好：
       我在使用RTP推拉流的过程中遇到了一些疑问，还请大神指教，谢谢！

**咨询的功能模块**
- GB28181-RTP

**咨询的具体内容和问题**
ZLM-02：下级平台
ZLM-01：上级平台
1）从摄像机拉流然后通过FFMPEG转为RTMP，推送至ZLM-02
     * ZLM-02通过【getMediaList】可以查询流信息
2）ZLM-01【openRtpServer】开启RTP
3）ZLM-02【startSendRtp】开始向 ZLM-01 启动推流
4）ZLM-01【getRtpInfo】与【listRtpServer】均可查询信息
5）ZLM-01【getMediaList】查询流信息不存在

这是dump文件
[rtp-dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8479006/rtp-dump.zip)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
startSendRtp推流方式是tcp还是udp？
