### ISSUE TITLE
录制文件没有生成

### ISSUE THREAD

**Issue by machengc** [ZLMediaKit/ZLMediaKit#1566]
### 现象描述

录制功能，没有生成录制文件
### 如何复现?

POST /index/api/startRecord result=true
POST /index/api/isRecording status=true
POST /index/api/stopRecord result=true
POST /index/api/getMp4RecordFile 返回数组中没有录制文件
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
如果自定义了视频录制路径 那么getMp4RecordFile接口就扫描不到文件

**Comment by machengc** [comment]
默认配置，没有自定义路径。
"paths" : [
         "14-05-13.mp4",
         "14-15-20.mp4",
         "14-15-59.mp4",
         "14-23-43.mp4",
         "14-27-21.mp4",
         "14-38-23.mp4",
         "15-09-12.mp4"
      ]。这是之前录制的文件都可以查到，出现这种问题频率较高，一般哪些情况会导致这些问题？

**Comment by xia-chu** [comment]
你可以看看文件夹`www/record`下到底有没有生成mp4文件

**Comment by machengc** [comment]
没有

**Comment by xia-chu** [comment]
那请提供下zlm的日志文件

**Comment by xia-chu** [comment]
你是想问 为什么重新开始录制 没有产生新的录像文件对吧

**Comment by machengc** [comment]
是的

**Comment by xia-chu** [comment]
我在本地测试无法验证这个问题 一切正常 不过我是webrtc推流。你可以打个补丁调试下试试：
```patch
Index: src/Record/MP4.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Record/MP4.cpp	(revision ebe414102695cf162ca4fd37518e53dc7cbb127d)
+++ src/Record/MP4.cpp	(date 1650115501733)
@@ -84,6 +84,7 @@
     if(!fp){
         throw std::runtime_error(string("打开文件失败:") + file);
     }
+    InfoL << "create mp4 file:" << file;
 
     GET_CONFIG(uint32_t,mp4BufSize,Record::kFileBufSize);
 
Index: src/Record/MP4Recorder.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Record/MP4Recorder.cpp	(revision ebe414102695cf162ca4fd37518e53dc7cbb127d)
+++ src/Record/MP4Recorder.cpp	(date 1650115501755)
@@ -82,6 +82,7 @@
         }
         //临时文件名改成正式文件名，防止mp4未完成时被访问
         rename(full_path_tmp.data(), full_path.data());
+        InfoL << "rename mp4 file:" << full_path_tmp << " -> " << full_path;
 
         /////record 业务逻辑//////
         NoticeCenter::Instance().emitEvent(Broadcast::kBroadcastRecordMP4, info);

```

**Comment by machengc** [comment]
感谢
