### ISSUE TITLE
编码风格的建议

### ISSUE THREAD

**Issue by paopaol** [ZLMediaKit/ZLMediaKit#1567]
首先感谢这个项目，功能强大，感谢项目成员的付出。这里就想提个关于编码风格的建议。大致浏览了一下源码，感觉代码风格好不统一，光File类自己都两种风格。类的命名，函数的命名给人的感觉也有些随意，有的类全大写，有的大小写混合，有的大小写加下划线混合。另外就是文件命名感觉也有点随意。虽然这个项目极其强大，但是风格不统一，看代码的时候，实在是感觉不到有什么美感，甚至感觉有点凌乱。作为一个比较知名的项目，建议学学其他的开源项目，比如Qt，google之类的。

**Comment by xia-chu** [comment]
这个项目历史比较久 这些年以来 个人编程风格也发生变化 目前已经稳定。zlm缺少一次全面的代码审核和改造，原因有以下几点
- 1：时间不够，精力有限，前面统一整理了命名空间，都花费不少时间，代码全面审核和风格改造更费时。
- 2：修改api后，容易导致用户需要重新适配，所以对这个也比较谨慎。
