### ISSUE TITLE
[技术咨询]: 在容器里编译zlmediakit报错 'set' does not name a type

### ISSUE THREAD

**Issue by huangban** [ZLMediaKit/ZLMediaKit#1568]
**咨询的功能模块**
- 代码编译

**咨询的具体内容和问题**
- 我使用的编译平台是在centOS 7的主机之上启动了一个基于CentOS 7的自定义镜像的容器，然后在容器里编译zlmediakit代码，编译报错如下。对应的英文应该是'set' does not name a type。
<img width="942" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/17782796/163502879-24b3bbf6-5bb3-4a7e-b3d8-1d85a1988efa.png">
- 作为对照，我在我的mac上面运行上面的编译镜像，然后是可以正常编译，原理上在容器里面编译就和主机没关系了，不知道为什么会产生差异。
- 镜像内的参数如下：CentOS Linux release 7.2 (Final)    gcc 版本 4.9.4。对应的环境变量和gcc的编译参数也用env和echo | gcc -x c++ -v -E -命令查看过，没有差异。

这个编译问题是什么原因造成的，有什么解决办法吗？

**Comment by xia-chu** [comment]
请更新zlm的代码

**Comment by huangban** [comment]
我试试，多谢
