### ISSUE TITLE
[技术咨询]关于hls录制接口循环录制只有20秒

### ISSUE THREAD

**Issue by OliveRuan** [ZLMediaKit/ZLMediaKit#1573]
**咨询的功能模块**
c api 录制HLS流功能

**咨询的具体内容和问题**
通过mk_recorder_start录制hls流时，函数回复成功，在文件夹下能看到m3u8和ts切片文件，但只有9-10个文件，循环滚动（新增ts文件时自动删除了最早的文件），仅仅只有20s不到的ts文件
通过mk_recorder_stop停止hls流时，函数回复成功，但文件夹下包括m3u8和ts文件均被自动删除
请问是需要什么特殊的配置，让hls流正常录制开始和停止吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
配置文件中`hls.segNum`改成0

**Comment by OliveRuan** [comment]
> 

使用的是c api，用的so库，并没有配置文件。。

**Comment by OliveRuan** [comment]
想请问一下，如果用c api的调用方式，如果在项目里引用config.ini这个配置文件？

**Comment by xia-chu** [comment]
```c
    char *ini_path = mk_util_get_exe_dir("c_api.ini");
    char *ssl_path = mk_util_get_exe_dir("ssl.p12");

    mk_config config = {
            .ini = ini_path,
            .ini_is_path = 1,
            .log_level = 0,
            .log_mask = LOG_CONSOLE,
            .log_file_path = NULL,
            .log_file_days = 0,
            .ssl = ssl_path,
            .ssl_is_path = 1,
            .ssl_pwd = NULL,
            .thread_num = 0
    };
    mk_env_init(&config);

**Comment by xia-chu** [comment]
测试程序里面都有范例

**Comment by OliveRuan** [comment]
了解，非常感谢！
