### ISSUE TITLE
[BUG]: on_stream_changed未按预期回调，仅回调HLS

### ISSUE THREAD

**Issue by chenparty** [ZLMediaKit/ZLMediaKit#1576]
### 现象描述

通过GB28181将摄像头的rtp流推送到zlm，zlm的on_publish回调收到后直接通过，按理应该会收到几个转协议的on_stream_changed回调。目前的问题是，推送录像回放流，on_stream_changed会回调hls、rtmp、rtsp等，而推送的实时流，只回调了hls的，导致我flv播放时，会收到回调on_stream_not_found。
请问下on_stream_changed不同协议触发的条件是什么呢，on_publish里面我回复的都是一样的，这个情况可能的原因是什么呢？

### 如何复现?

首先 openRtpServer
然后 通过GB28181通知摄像头推RTP流
期望 on_publish和多个on_stream_changed, 结果 on_publish和仅一个HLS的on_stream_changed

**Comment by xia-chu** [comment]
你先更新zlm代码试试 你代码应该比较老了

**Comment by chenparty** [comment]
好的，我试一下最新版本

**Comment by chenparty** [comment]
更新最新版本后，确实没有hls的了，只有on_publish回调了

**Comment by xia-chu** [comment]
没收到推流 请查看wvp media_ip和sdp_ip设置

**Comment by chenparty** [comment]
确实是配置问题，现在可以收到流了。但是zlm收到流的时间极长，大概十几秒才能注册，好像摄像头没有立即推流，可是这是在局域网的情况下，不应该这样的。

**Comment by xia-chu** [comment]
zlm的配置文件 enable_audio设置为0

**Comment by chenparty** [comment]
您看看上面这张图上的all track ready用了10s，这边耗时太长了。

**Comment by chenparty** [comment]
感谢指导！

**Comment by chenparty** [comment]
感谢指导！
