### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by jiajialaixi** [ZLMediaKit/ZLMediaKit#1579]
###播放rtsp  头部信息不对 H264流应该是 sprop-parameter-sets 而不是config ,profile-level-id格式也不对 这个看着像是mpeg4的流

### 相关日志或截图
    Content-Base: rtsp://125.75.98.191:554/rtp/fad592a2ed9c4acf823235da7008ed20/
    Content-Length: 498
    Content-Type: application/sdp
    CSeq: 1
    Date: Tue, Apr 19 2022 05:59:55 GMT
    Server: ZLMediaKit(git hash:e483424,branch:master,build time:Dec  8 2021 16:17:39)
    Session: iZEqGcBoxrHE
    x-Accept-Dynamic-Rate: 1
    x-Accept-Retransmit: our-retransmit
    
    v=0
    o=- 0 0 IN IP4 0.0.0.0
    s=Streamed by ZLMediaKit(git hash:e483424,branch:master,build time:Dec  8 2021 16:17:39)
    c=IN IP4 0.0.0.0
    t=0 0
    a=range:npt=now-
    a=control:*
    m=video 0 RTP/AVP 96
    a=Media_header:MEDIAINFO=494D4B48030100000400000100000000000000000000000000000000000000000000000000000000;
    a=fmtp:96 profile-level-id=8;config=Z0KAH4iLQCgC3QgAADhAAAr8gCA=,aM44gA==
    a=range:npt=now-
    a=rtpmap:96 H264/90000
    a=control:rtsp://125.74.52.26:554/openUrl/EpIxcA0?streamform=rtp/trackID=0

**Comment by xiongguangjie** [comment]
你是什么推流，你是不是是其他的rtsp 推流呀，如果是把directProxy 的配置改为0,通过addstreamproxy 添加的代理现在是直接代理
