### ISSUE TITLE
[功能请求]发送Rtp包时，能否不打包ts/ps流

### ISSUE THREAD

**Issue by chenxihai** [ZLMediaKit/ZLMediaKit#1580]
当前需求是单独发送G711语音数据时不要打包成PS流。

是否可以在StartSendRTp函数增加标识参数，不需要打包时可以只封装rtp，而不要加入ps

**Comment by xia-chu** [comment]
嗯 现在支持直接打包es 的rtp流了，你看下wiki



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chenxihai ***@***.***&gt;
发送时间: 2022年4月19日 14:50
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [功能请求]发送Rtp包时，能否不打包ts/ps流 (Issue #1580)





 
当前需求是单独发送G711语音数据时不要打包成PS流。
 
是否可以在StartSendRTp函数增加标识参数，不需要打包时可以只封装rtp，而不要加入ps

**Comment by chenxihai** [comment]
感谢夏老师回复，我的需求是指当前只注册音频的媒体（rtp/1B8E98），startSendRtp接口将音频通过rtp发送给别的rtpserver，当前默认发送ps封装后rtp包，能否不封装ps，直接将原始的音频数据发送出去？

**Comment by chenxihai** [comment]
不好意思，最新的有这个功能！谢谢
