### ISSUE TITLE
[功能请求] 是否有计划支持1078的视频协议

### ISSUE THREAD

**Issue by taigege** [ZLMediaKit/ZLMediaKit#1581]
**描述该功能的用处，可以提供相关资料描述该功能**

JTT1078协议与GB28181协议功能类似，1078主要用于车载视频的传输。

[JTT 1078.PDF](https://github.com/ZLMediaKit/ZLMediaKit/files/8511892/JTT.1078.PDF)

主要是这个消息包
![image](https://user-images.githubusercontent.com/36600558/163978157-5ccc0d07-e215-4793-94e6-f9bf06ff71da.png)

**Comment by wusopp** [comment]
欢迎贵司的开发人员提PR。

**Comment by xia-chu** [comment]
其实jt1078还是蛮简单的 之前我在zlm上实现过 不过这个是工作开发成果 所以不能开源，我现在对重新开发jt1078也不太感兴趣，目前也没这个需求。

**Comment by RePtiR** [comment]
You say: 专业闭源版已支持 详情请查看项目主页介绍
but there is no information anywhere on where and how to purchase it.

**Comment by xia-chu** [comment]
> You say: 专业闭源版已支持 详情请查看项目主页介绍 but there is no information anywhere on where and how to purchase it.

@RePtiR https://github.com/xia-chu/zlmediakit-pro
