### ISSUE TITLE
[BUG]: 截图失败报错

### ISSUE THREAD

**Issue by chenparty** [ZLMediaKit/ZLMediaKit#1583]
### 现象描述

rtmp on_stream_changed注册后，我调用截图接口，流地址使用的.live.flv格式。ffmpeg截图失败。

### 如何复现?

1、摄像头推流
2、rtmp on_stream_changed注册回调
3、调用getSnap接口，流地址使用的.live.flv格式
4、截图失败

### 相关日志或截图

![image](https://user-images.githubusercontent.com/16755257/163985723-648bc55e-566d-4c97-92db-64f428312c4e.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
![image](https://user-images.githubusercontent.com/16755257/163985617-a837308d-7c9c-4337-bc8b-7efa8e2bf2b6.png)

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by wasphin** [comment]
`-t 0.001` 这个是配置里添加到吗？

**Comment by chenparty** [comment]
这个是zlm的默认配置，我下的最新版本

**Comment by wasphin** [comment]
@chenparty

看到了😅，试一下把截图参数改成下面的：
```
snap=%s -i %s -y -f mjpeg -frames:v 1 %s
```
看一下这个参数会不会有效果。

**Comment by chenparty** [comment]
![image](https://user-images.githubusercontent.com/16755257/164201008-abbaaa0f-9d54-426c-b403-51059edda424.png)
(⊙﹏⊙)截图还是报错，但是视频在正常播放。

**Comment by xia-chu** [comment]
这个是FFmpeg命令的用法问题了 @chenparty 建议你在shell里面用FFmpeg命令直接截图试试 知道截图成功为止。

**Comment by chenparty** [comment]
好的，感谢！
