### ISSUE TITLE
[技术咨询]rtp推流404错误

### ISSUE THREAD

**Issue by nocny-x** [ZLMediaKit/ZLMediaKit#1586]
**咨询的功能模块**
- rtp推流

**咨询的具体内容和问题**
- 国标(2016)接入海康摄像头，rtp推流，前端提示404，dump文件已附上，大神帮忙分析分析什么原因呢。
- 代码是master分支最新的
![image](https://user-images.githubusercontent.com/2148796/164014708-554b386d-c54f-4982-ac7c-3eda1933a347.png)
![image](https://user-images.githubusercontent.com/2148796/164012922-c1728bca-e740-499e-9f15-26eb4efb916f.png)
[rtp_dump_and_config.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8513297/rtp_dump_and_config.zip)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
wiki 上url 改了录像改了，wiki上有更新
