### ISSUE TITLE
webtrc取流报错

### ISSUE THREAD

**Issue by roxpeng** [ZLMediaKit/ZLMediaKit#1587]
取流地址：http://114.115.134.5/index/api/webrtc?app=rtp&stream=0BEBD90&type=play
错误信息：
{
   "code" : -400,
   "msg" : "Assertion failed: (!offer.empty(), http body(webrtc offer sdp) is empty), function operator(), file /opt/ZLMediaKit/server/WebApi.cpp, line 1415."
}

![image](https://user-images.githubusercontent.com/18020772/164130549-f729619e-b71b-40b9-a533-1ff7e87afc01.png)

**Comment by xiongguangjie** [comment]
要用ZLM配套的播放器才能播放，你看作者讲解的视频(有录像，微信公众号有)与wiki

**Comment by xxxxxxbin6** [comment]
最新代码，webrtc推流，用webrtc拉流播放，显示播放成功，而且状态也是connected，但是一直转圈，不出画面
