### ISSUE TITLE
[BUG]: 配置源站拉流后 先拉RTMP可正常播放,再拉HLS无法正常播放

### ISSUE THREAD

**Issue by gb18030** [ZLMediaKit/ZLMediaKit#1588]
### 现象描述

配置源站拉流后 如果请求的是相同的源
先拉RTMP可正常播放,再拉HLS无法正常播放
先拉HLS可正常播放,再拉RTMP也可正常播放

### 如何复现?

拉相同的源,先拉RTMP,不要关,在拉HLS

### 相关日志或截图

如果我先播放rtmp 就会注册rtmp rtsp fmp4服务 但是不会注册hls 如果我再去请求hls 那么将无法播放
![GK$ED$A6Q8VC XGWHXCZ)_6](https://user-images.githubusercontent.com/19511418/164394114-8e2ef56c-a00f-4f84-bba9-92203cc6b150.png)

除非我先请求hls  这时候所有的服务都注册
![{K`U3{D)(5(8JP1MLF8ETTY](https://user-images.githubusercontent.com/19511418/164394343-23b8957f-d99f-479c-9fa6-b8432e7c66d5.png)
然后我再放什么协议的都没问题

WebHook.cpp:245 pullStreamFromOrigin | pull stream from origin, failed_cnt: 0, timeout_sec: 15, url: rtsp://admin:123456@192.168.3.171:554/stream2?edge=1&vhost=__defaultVhost__

上面这句日志上url之后的 从局域网直接播放时没问题的

播放通过外网拉流(有域名) 在参数后无论是否拼vhost均有此问题

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=rtsp://admin:123456@192.168.3.171:554/%s%s
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
#cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
cmd=%s -i %s -vcodec copy -an -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
continue_push_ms=15000
enableVhost=0
enable_audio=1
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=Gr0mtvNhXJ9gCFma
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=20000
ts_demand=0
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=30.000000
enable=0
on_flow_report=
on_http_access=
on_play=
on_publish=
on_record_mp4=
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_keepalive=
on_server_started=
on_shell_login=
on_stream_changed=
on_stream_none_reader=
on_stream_not_found=
timeoutSec=10

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:c31d44d,branch:master,build time:Apr 20 2022 08:22:10)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
port=10000
port_range=30000-35000
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

; } ---

</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:c31d44d680d6583d5e434016e4eb00a3993fa056
* **操作系统及版本**:Debian buster
* **硬件信息**:cpu:ARM4核A53 RAM:4G
* **其他需要补充的信息**:在docker里编译的  docker里系统也是debian buster

**Comment by xia-chu** [comment]
因为如果溯源是通过hls播放触发的，那么zlm在溯源时，会同时生成hls代理。
如果溯源是非hls协议触发的，那么zlm在溯源时，就不会生成hls代理。
因为生成hls代理，开销会比较大。

**Comment by xia-chu** [comment]
看代码,WebHook.cpp第248行：
```c++
static void pullStreamFromOrigin(const vector<string>& urls, size_t index, size_t failed_cnt, const MediaInfo &args,
                                 const function<void()> &closePlayer) {

    GET_CONFIG(float, cluster_timeout_sec, Cluster::kTimeoutSec);
    auto url = getPullUrl(urls[index % urls.size()], args);
    auto timeout_sec = cluster_timeout_sec / urls.size();
    InfoL << "pull stream from origin, failed_cnt: " << failed_cnt << ", timeout_sec: " << timeout_sec << ", url: " << url;

    ProtocolOption option;
    option.enable_hls =  args._schema == HLS_SCHEMA;
    option.enable_mp4 = false;

    addStreamProxy(args._vhost, args._app, args._streamid, url, -1, option, Rtsp::RTP_TCP, timeout_sec,
                  [=](const SockException &ex, const string &key) mutable {
        if (!ex) {
            return;
        }
        //拉流失败
        if (++failed_cnt == urls.size()) {
            //已经重试所有源站了
            WarnL << "pull stream from origin final failed: " << url;
            closePlayer();
            return;
        }
        pullStreamFromOrigin(urls, index + 1, failed_cnt, args, closePlayer);
    });
}
```

**Comment by gb18030** [comment]
> ```c++
> timeout_sec 
> ```

那我再去拉HLS也不能不给我播吧

**Comment by gb18030** [comment]
> 因为如果溯源是通过hls播放触发的，那么zlm在溯源时，会同时生成hls代理。 如果溯源是非hls协议触发的，那么zlm在溯源时，就不会生成hls代理。 因为生成hls代理，开销会比较大，所以边沿站如果不是hls方式访问，那么溯源不开启转hls协议。

那我先请求RTMP 再去请求HLS 也不能不给我拉吧

**Comment by xia-chu** [comment]
改成这样吧：
`option.enable_hls =  option.enable_hls | args._schema == HLS_SCHEMA;`
