### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by AllroadsleadtoRome** [ZLMediaKit/ZLMediaKit#1589]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
您好，我用ffmpeg把摄像头的rtsp推转流为rtmp至nginx服务器上后，用vlc播放特别卡，在寻找问题时发现了[ZLMediaKit] ，在看了之后请问[ZLMediaKit]是类似于代替nginx的吗，我推流的目标服务器是公网

**Comment by wasphin** [comment]
ZLMediaKit 不是为了替代 nginx，不过可以作为 RTMP 服务器进行使用，应该可以满足你的使用场景。

**Comment by AllroadsleadtoRome** [comment]
> ZLMediaKit 不是为了替代 nginx，不过可以作为 RTMP 服务器进行使用，应该可以满足你的使用场景。

请问是需要调用哪个程序呢
