### ISSUE TITLE
[技术咨询] /index/api/openRtpServer能否增加SSRC校验

### ISSUE THREAD

**Issue by Smallkserver** [ZLMediaKit/ZLMediaKit#1592]
**咨询的功能模块**
- 如题 openRtpServer 能否增加ssrc参数。
- 使用多端口模式下，如果国标控制不当，导致udp无法关闭，播放再使用该端口时会出现串流。想请教一下能否多校验一次流的ssrc，把串流的udp包丢弃掉

**Comment by xia-chu** [comment]
现在不是已经增加了么？

**Comment by Smallkserver** [comment]
wiki里  /index/api/openRtpServer，只有这四个参数。参数里stream_id是端口的流编号

<html>
<body>


参数 | 是否必选 | 释意
-- | -- | --
secret | Y | api操作密钥(配置文件配置)，如果操作ip是127.0.0.1，则不需要此参数
port | Y | 接收端口，0则为随机端口
enable_tcp | Y | 启用UDP监听的同时是否监听TCP端口
stream_id | Y | 该端口绑定的流ID，该端口只能创建这一个流(而不是根据ssrc创建多个)


</body>
</html>

**Comment by xia-chu** [comment]
更新postman了 没更新wiki，以postman最新配置为准：
![图片](https://user-images.githubusercontent.com/11495632/165042528-5ae27abd-9f52-4967-bbab-2647a3037de2.png)

**Comment by Smallkserver** [comment]
好的谢谢。我去测试下
