### ISSUE TITLE
[BUG]: BUG 生成hls文件内容错误

### ISSUE THREAD

**Issue by hany-dev** [ZLMediaKit/ZLMediaKit#1596]
### 现象描述
首先感谢子悦老师贡献出如此优秀的开源项目。
近期在运行中发现，生成的hls无法播放，在对其进行分析之后，发现hls的PMT信息中有三个轨道，却只有2个轨道的数据，所以无法进行播放，如图为vcl中显示的媒体文件信息。以及采用easyice软件对文件分析的结果。
![图片](https://user-images.githubusercontent.com/39269298/165282293-69178a6f-be4d-4293-bbcd-28695a6b7631.png)

![图片](https://user-images.githubusercontent.com/39269298/165281112-058c07ca-9823-4d0b-a774-e0564eb63eea.png)
![图片](https://user-images.githubusercontent.com/39269298/165281177-cf5e1777-5219-4795-bc4d-51a846549634.png)

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

因此对log进行分析，发现在出现这种现象时，会出现，在注册hls之前调用过getmedialist接口，此时仅能查询到H264的轨道而查询不到muted aac轨道，在此时就会出现这种hls中有三个轨道的问题。
![图片](https://user-images.githubusercontent.com/39269298/165281862-2ea9de0c-1c31-45c7-b02b-112c41b1eb77.png)
![图片](https://user-images.githubusercontent.com/39269298/165281955-8afefe2a-d525-4226-9f33-ea776326524a.png)
因为这种现象发生了三次，三次均具备这种情况，所以猜测，是否在媒体注册完成前调用getMediaList接口会对生成文件的轨道数目产生一定的影响。因此附上视频文件一个，请大佬有时间看一下，感谢感谢

### 配置
普通配置即可

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
普通运行环境即可

* **代码提交记录/git commit hash =  a16b6cbc5973b7818bbd1c66a0b7edd3c2428da6  **:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:
[01-18_4633.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8562410/01-18_4633.zip)

**Comment by alexliyu7352** [comment]
给个测试地址
