### ISSUE TITLE
[功能请求]StartSendRtp 能否增加发送Rtcp SR 机制

### ISSUE THREAD

**Issue by chenxihai** [ZLMediaKit/ZLMediaKit#1597]
当前的需求是通过StartSendRtp接口向其它RtpServer发送RTP数据，RtpServer存在认证过程，要求发送端先发送一个RTCP SR包，再开始发送RTP流，接收端通过SR包中的SSRC来确认身份，再接收RTP流，当前ZLM发送RTP流时没有发送SR包，接收端拒绝接收。

老大，看看能否实现这个功能，默认RTCP SR包 的发送端口为RTP发送端口+1，可以只发送一次，后续也可以定期发送。

**Comment by xia-chu** [comment]
已经实现了 rtcp的ssrc也是rtp的ssrc+1

**Comment by bless66** [comment]
请问下 tcp 模式，RTCP SR包是默认会发送的吗？我看 zlm udp 有设置 rtcp 的相关参数，tcp 没有。
