### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by Learnliang** [ZLMediaKit/ZLMediaKit#1599]
抓拍或者说截图 404 问题
我看到 wvp-GB28181-pro 项目中有调用 getSnap的实现。

# request:
POST /index/api/getSnap
# response:
<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit-5.0(build in Feb 18 2021 00:36:33)</center></body></html>

请问现在又对应的接口实现了吗？还是有调用样例吗

**Comment by alexliyu7352** [comment]
请先看wiki.
web api接口写的很详细.
99%的问题其实都已经在wiki中写了.


Learnliang ***@***.***> 于2022年4月27日周三 16:16写道：

**Comment by Learnliang** [comment]
![image](https://user-images.githubusercontent.com/36759700/165479999-b08d08a9-7cee-4c91-b8af-8968ab338158.png)
好的，我看到了。
那麻烦再问一下，这个接口是21年上的吗，还是什么时候，因为我当前所用的项目看着好像是21年2月才部署的

**Comment by Learnliang** [comment]
没事了
