### ISSUE TITLE
[BUG]: 视频播放画面旋转了180度

### ISSUE THREAD

**Issue by supercooc** [ZLMediaKit/ZLMediaKit#1601]
![image](https://user-images.githubusercontent.com/1592352/165668666-e6a62572-c06a-4edd-810d-fc1e57a99b30.png)

如果，版本使用了ZLMediaKit 主干自编译。 搭配 wvp-GB28181-pro

**Comment by xia-chu** [comment]
如果不是webrtc推流 那么这个不是zlm的问题了

**Comment by wasphin** [comment]
这个应该是摄像机的使用方式有关，很可能是摄像机安装的方式不对。和服务器没什么关系。

**Comment by supercooc** [comment]
> 果不是webrtc推流 那么这个不是zlm的问题了
我自己rtsp拉流推到nginx上播放的 
![image](https://user-images.githubusercontent.com/1592352/165688379-59a4ec0e-39ae-4ac4-9b8a-57f4c065fa71.png)
在zml 是国标推流

**Comment by supercooc** [comment]
> 这个应该是摄像机的使用方式有关，很可能是摄像机安装的方式不对。和服务器没什么关系。

问题是我用另外的方式，以及用nvr看都是正常的，就国标推流zml 会翻转180度

**Comment by xia-chu** [comment]
请使用zlm的dump功能 上传rtp文件上来分析下

**Comment by wasphin** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/blob/200a193c04d448fb68a885c63bdb35171859f30c/conf/config.ini#L250

配置文件有个 dump 目录的设置。

**Comment by xiongguangjie** [comment]
看看其他播放器是不是有这个问题，如vlc ffplay flv.js 之类的

**Comment by supercooc** [comment]
> 请使用zlm的dump功能 上传rtp文件上来分析下
[33010200111000000001_33020000001320000001.rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8587765/33010200111000000001_33020000001320000001.rtp.zip)
帮忙分析下

**Comment by xiongguangjie** [comment]
![1](https://user-images.githubusercontent.com/19631632/165879018-9f51a030-7a18-4350-8e9a-1e22a33b9f28.png)
vlc 播放视频是正常的，流基本上没有问题

**Comment by Dw9** [comment]
![image](https://user-images.githubusercontent.com/36155473/165879705-9bcbb8ce-00c1-4b56-82d6-713a93cb982c.png)

我用zlm 导入是这样的 /汪汪

**Comment by supercooc** [comment]
> 用zlm 导入是这样的 /汪汪

刚用vlc 试了下是正常的。那就是 wvp-GB28181-pro 的网页播放器的问题了

**Comment by supercooc** [comment]
说一句，是chrome 一个旧版本导致这个问题
