### ISSUE TITLE
[技术咨询] describe返回多个音频编码时，如何选择指定编码

### ISSUE THREAD

**Issue by SteveWooo** [ZLMediaKit/ZLMediaKit#1602]
**咨询的功能模块**
- 如何让rtp payload指定某个音频编码

**咨询的具体内容和问题**
- 你好，我们在拉取回放视频rtsp流的时候，服务端返回的describe中有多个音频编码，如图。然后我们通过zlmedia推ws流出去后，默认使用了第一个编码（图中的情况就是PCMA，但我们希望能够选择AAC的编码），请问目前有渠道调整这个编码的选择吗？

![image](https://user-images.githubusercontent.com/12856960/165884254-b6edf1f7-ad2e-47cb-be52-e555595ec12d.png)

**Comment by xia-chu** [comment]
这个rtsp怎么协商codec呢？

**Comment by SteveWooo** [comment]
> 这个rtsp怎么协商codec呢？我都不不知道怎么协商的

在rtsp上没有协商codec，客户端向服务器Describe后，就回来了一堆音频编码（如问题描述的截图），代表服务器支持的编码类型，这里似乎是需要客户端去自行选择的。

我去了解了一下，rtsp标准协议上没找到能协商音频编码的字段，但是发现rtp协议包头的pt字段是用于给客户端实时选择音频编码的~

但zlmediaket似乎没有这个配置项，然后在源码里发现，sdp parser的时候，最终只截取了describe回来的第一个音频编码，后面的内容似乎都被丢弃了。如下2图：

服务端返回的describe数据包：
![图1：服务端返回的describe数据包](https://user-images.githubusercontent.com/12856960/167329486-fb4b6a31-8671-4c6e-a852-5d020bce95ae.png)

第二次解析sdp时候，编码列表只保留了第一位：
![图2：解析sdp时候，编码列表只保留了第一位](https://user-images.githubusercontent.com/12856960/167329550-e2bf6fae-a244-495c-89f5-7f96b295d805.png)

于是zlmedia就默认选择了第一个音频编码。

我们希望用zlmedia作为客户端，把rtsp流转给浏览器。所以尽量希望能够使用AAC格式，但rtsp服务端为了兼容多个不同网络环境的客户端，所以提供了多种编码格式给客户端自行选择。但用zlmedia做客户端的时候，就发现不太好操作rtp包去选择音频编码了QAQ。

请问目前有办法对rtp的头提供配置选择吗~？
也由于sdpParser把其他的音频编码丢弃了，所以改起来有点担心留有后患，也想请问一下这个截取的处理逻辑在哪个地方~？

**Comment by xia-chu** [comment]
你可以抓个ffmepg或vlc播放这个视频的包 我分析对比下

**Comment by SteveWooo** [comment]
好的~非常感谢，已经发送到readme的QQ邮箱里啦，请查收

**Comment by SteveWooo** [comment]
你好，我大概定位到问题了。

发现在rtsp.cpp的169行附近，SdpParser::load函数里面解析sdp到case 'm'的时候，这个正则只获取了第一个音频编码。
![image](https://user-images.githubusercontent.com/12856960/167358428-b442f466-84ad-4c16-b4b2-4b1ad87fc053.png)

但对于有多个音频编码的情况，这似乎不太好使。
![image](https://user-images.githubusercontent.com/12856960/167358493-9865d089-c745-4d11-8a45-95170dbdbcf9.png)

目前我的解决方法是在config.ini的配置里面新增了一项默认音频编码，表示优先选择的编码，如果服务端返回的describe不支持这个配置的编码，就走原来的逻辑~
