### ISSUE TITLE
[技术咨询]ffmpeg把mp4转rtmp没有声音

### ISSUE THREAD

**Issue by shiloliao** [ZLMediaKit/ZLMediaKit#1604]
**咨询的功能模块**
   webrtc
**咨询的具体内容和问题**
（1）MP4转rtmp
ffmpeg -re -i abc.mp4 -c copy -f flv -y rtmp://10.0.40.20/live/livestream
（2）webrtc播放没有声音
http://10.0.40.20:8432/index/api/webrtc?app=live&stream=livestream&type=play
**注意事项**

**Comment by Dw9** [comment]
rtc 浏览器不支持 aac等音频格式  你可以尝试 ffmpeg -re -i abc.mp4 -vcodec libx264 -bf 0 -acodec pcm_mulaw -ar 8000 -ac 1 -f flv -y rtmp://10.0.40.20/live/livestream

可以先在issue搜索一下  能找到相关答案
#1481
