### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by ziyaofeng** [ZLMediaKit/ZLMediaKit#1605]
**加入动态插件加载**

**哈哈，忽然有个想法，如果mediakit可以加入动态插件加载就好了。因为mediakit的NoticeCenter功能非常好用。如果可以把mediasource的接口固定，然后插件动态库实现统一初始化NoticeCenter，监听到mediaserver的各种事件，然后使用mediasource的api执行各种操作。那么转码，非标准协议接入mediaserver，视频流分析，特殊需求api，等这种工作就可以通过插件实现了。而且对mediaserver的源码无入侵性，应该能做到更新版本后也能使用**

**希望mediaserver可以支持外部动态库作为插件，动态加载，插件内可以操作各种媒体流，各种track，注册自定义 http api**

**Comment by xia-chu** [comment]
现在zlm的webrtc做成代码插件注册方式设计了。基于dlopen这种'硬插件'方式目前不会考虑，因为这个设计多平台适配特别是ios、Android下的问题。
目前webrtc'软插件'方式我觉得是个发展方向
