### ISSUE TITLE
[技术咨询] webrtc 映射问题

### ISSUE THREAD

**Issue by Smallwhitepig** [ZLMediaKit/ZLMediaKit#1606]
内网向zlm推一个视频如何实现内网外网同时可以播放？
rtc
externIP= 设置公网
内网不可以播放

externIP= 设置内网
公网不可以播放

是否考虑增加设置当内网公网访问的时候指定对应IP的8000端口解析

**Comment by Smallwhitepig** [comment]
就是判断访问的ip 如果不是跟内网IP同个段的 自动调转到另外一个IP解析

**Comment by mtdxc** [comment]
这应该可以通过同时返回内网和externIP两候选地址来解决。

**Comment by xia-chu** [comment]
这个issue我竟然晾了10天没看到。。。

**Comment by xxxxxxbin6** [comment]
Ubuntu20版本编译最新代码，用webrtc推流，再用webrtc拉流测试，显示播放成功，状态是connected，但是video一直在转圈，不出视频

**Comment by xia-chu** [comment]
@Smallwhitepig 合并pr了 现在支持多icecand候选地址了 感谢 @mtdxc

**Comment by Smallwhitepig** [comment]
感谢各位辛苦的付出
