### ISSUE TITLE
[技术咨询]将ZLMedia服务部署在云端时，网页无法通过webrtc进行播放

### ISSUE THREAD

**Issue by zzxusers** [ZLMediaKit/ZLMediaKit#1608]
我在本地部署zlm服务，通过网页访问视频流没有任何问题。但是我将服务部署在阿里云，在网页使用webrtc进行播放时，网页控制台提示播放成功了。但是画面一直时灰色的，如图：
![image](https://user-images.githubusercontent.com/37200124/166265172-3d2f1047-fd59-44b7-95ce-cdff25eb188c.png)
此时查看zlm服务里面发现报错了，rtp接收超时如图：
![image](https://user-images.githubusercontent.com/37200124/166265327-d09a2b84-dca1-4900-834d-9a44d986926f.png)
config.ini 里面的webrtc地址已经改成了公网ip，问题依旧存在，希望各位大佬能够回复一下，感谢！

**Comment by wasphin** [comment]
确认下防火墙是否开通了相关端口，如 udp 的 8000，具体需要结合配置文件中配置的端口看。

**Comment by xia-chu** [comment]
这个问题提问者已经在qq群里面解决了 原因是未映射8000 udp端口
