### ISSUE TITLE
mp4视频录制

### ISSUE THREAD

**Issue by FCsir** [ZLMediaKit/ZLMediaKit#1612]
**MP4视频录制功能**
- mp4录制视频会自动清理之前的视频吗？

**Comment by qiaoro** [comment]
不会自动清理，自己通过crontab 或者其他方式管理

**Comment by FCsir** [comment]
感谢回答，我看到配置文件中有个选项，这个不会影响到视频录制吗？
![image](https://user-images.githubusercontent.com/23648710/167087663-fd51c675-be40-4328-ae60-ba51ec95089a.png)

**Comment by xia-chu** [comment]
> 感谢回答，我看到配置文件中有个选项，这个不会影响到视频录制吗？ ![image](https://user-images.githubusercontent.com/23648710/167087663-fd51c675-be40-4328-ae60-ba51ec95089a.png)

拉流如果重连了 那么不管这个参数 都会重新生成新的mp4切片

**Comment by FCsir** [comment]
理解，那会不会删除之前已经录制的数据呢？

**Comment by shkwi** [comment]
麻烦问一个问题，配置里设置保存文件时长600秒："record.fileSecond": "600",但在录制的时候会出现下图中不到十分钟时间的切片，这种情况一般是什么问题导致的呢，谢谢！
![image](https://user-images.githubusercontent.com/52033281/167391899-d8e65540-9c66-41f2-b1f3-94f479f9a536.png)

**Comment by FCsir** [comment]
调用recordapi的时候好像可以指定max_second.如果都是时间都是一样的话，应该是配置问题。不一样的话有可能是断流了或者停了，然后重新连接这种情况

**Comment by shkwi** [comment]
> 

我这边是多个流代理一起录制的，流代理没有设置max_second,录制的结果是：每个代理录制的视频大小不一致，有些是正常的，有些是会产生上面不到十分钟的切片。
