### ISSUE TITLE
[BUG]: BUG 通过调整zlm的ffmpeg的参数添加水印，会报不支持drawtext

### ISSUE THREAD

**Issue by qiaoro** [ZLMediaKit/ZLMediaKit#1615]
### 现象描述

通过调整zlm的ffmpeg的参数添加水印，ffmpeg.log 中会报错不支持drawtext，直接在服务器上直接执行ffmpeg命令的是可以的

### 如何复现?
1、首先调整ffmpeg参数：cmd_custom=%s -re -i %s -c:a copy -vf "drawtext=text='demo':x=(w-tw):y=(2*lh):fontcolor=white:fontsize:150"  -c:v libx264 -f flv %s
2、然后添加ffmpeg代理时指定 ffmpeg.cmd
3、ffmpeg会报错：[AVFilterGraph @ 0x564c5d07cd40] No such filter:'"drawtext' Error reinitializing filters!

### 相关日志或截图
zlm调用ffmpeg执行的命令行如下：
![mm](https://user-images.githubusercontent.com/8346983/167075531-656cdeba-3452-4c0b-b066-e14d7080e8ee.png)

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:  CentOS 7
* **硬件信息**:
* **其他需要补充的信息**:
使用的是docker方式部署，镜像：zlmediakit/zlmediakit:Release.last

**Comment by xia-chu** [comment]
你可以手动执行FFmpeg命令看看支不支持

**Comment by qiaoro** [comment]
直接手动执行是可以的。

**Comment by xia-chu** [comment]
zlm是这样传参给FFmpeg的：
<img width="1098" alt="图片" src="https://user-images.githubusercontent.com/11495632/167110725-225fc25a-91a8-42fa-8676-9d6203a6941b.png">
这个可能在传递复杂参数时可能有问题

**Comment by xia-chu** [comment]
在执行程序时 并不需要考虑shell转义的问题 所以不需要双引号

**Comment by qiaoro** [comment]
👌 ， 去掉双引号后是正常的了。非常感谢
