### ISSUE TITLE
startSendRTP 收到h264ps流，转发成es流，视频播放失败。

### ISSUE THREAD

**Issue by yplypl** [ZLMediaKit/ZLMediaKit#1617]
### 现象描述
2022-05-22日使用master代码，海康NVR国标录像点播ps流，zlm收到流后通过startSendRTP 发送es流(is_udp=1&use_ps=0&pt=96)，转发出来的es流播放失败。

### 如何复现?
我对ZLM服务器进行抓包，以及本地接收ES流的程序，将rtp里面的payload部分保存出来，保存出来的h264的payload使用eseye_u.exe软件无法播放。

抓包 zlm接收ps流过滤条件：ip.addr == 192.168.111.38 and udp

抓包 zlm转发es流过滤条件：ip.addr == 192.168.109.108 and udp

发送给ZLM的http请求过滤条件：ip.addr == 192.168.108.164 and http

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by yplypl** [comment]
[](url
[zlm接受h264的ps流转发es无法播放.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8655886/zlm.h264.ps.es.zip)
[zlmEs.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8655891/zlmEs.zip)
)

**Comment by xia-chu** [comment]
其实很简单 你直接调用startSendRTP推给zlm自己 看看行不行

**Comment by yplypl** [comment]
@xia-chu 后面我们这边专家排除了下，还是我们自己本身的问题。ES流现在能播放成功的，抱歉了。现在关闭。
