### ISSUE TITLE
[技术咨询] Android 端启用ZlMediaKit服务

### ISSUE THREAD

**Issue by eanfs** [ZLMediaKit/ZLMediaKit#1618]
**咨询的功能模块**
- Android 端启用ZlMediaKit服务

**咨询的具体内容和问题**
- 有些Android的平板，每台设备都有连接的网络摄像头，能不能在Android端启用ZlMediaKit，把和这个Android端绑定的摄像头的视频流拉流并保存到Android本地。
- 有没有相关的文档

**注意事项**
-  无

**Comment by alexliyu7352** [comment]
可以的, 具体参考c api接口

eanfs ***@***.***> 于2022年5月10日周二 10:55写道：

**Comment by ILoveLin** [comment]
可以的, 具体参考c api接口   什么意思 我这边Android app 也想启动服务作为 把我的直播流推到该服务器上,然后自己App再用播放器接收,现在的问题是 不知道如何开启和关闭这个服务?
