### ISSUE TITLE
[技术咨询] 关于音频转码的问题，G711格式H5播放器无法正常播放

### ISSUE THREAD

**Issue by yangshun1996** [ZLMediaKit/ZLMediaKit#1619]
目前采用海康设备语音对讲，但是必须要使用G711格式，目前尝试了很多h5播放器都无法正常播放g711音频格式的视频。
如果用aac的话，GB28181的语音对讲功能就没办法使用。
有没有可以在zlm内部实现G711转aac格式的方法呢？

**Comment by xia-chu** [comment]
可以用webrtc播放器 webrtc支持711，另外也可以用wasm的播放器

**Comment by SuperChrisliu** [comment]
> 可以用webrtc播放器 webrtc支持711，另外也可以用wasm的播放器

微信小程序live-player只支持aac编码，是否可以不通过ffmpeg子进程进行音频转码？音频解码cpu资源占用率还好吧，是否可以让ZLMediaKit内部支持啊

**Comment by xia-chu** [comment]
> > 可以用webrtc播放器 webrtc支持711，另外也可以用wasm的播放器
> 
> 微信小程序live-player只支持aac编码，是否可以不通过ffmpeg子进程进行音频转码？音频解码cpu资源占用率还好吧，是否可以让ZLMediaKit内部支持啊

请使用 addFFmpegSource接口

**Comment by xia-chu** [comment]
feature/transcode分支已经实现
