### ISSUE TITLE
[技术咨询]静态编译

### ISSUE THREAD

**Issue by worldflyingct** [ZLMediaKit/ZLMediaKit#1620]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
编译这部分  
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
zlmediakit实现静态编译，也就是将zlmediakit与openssl都静态编译为单文件  
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
目前会编译出静态库的 只是多个静态库 你把静态库都链接一遍即可
