### ISSUE TITLE
[技术咨询]如何判断浏览器是否支持webrtc

### ISSUE THREAD

**Issue by joyol** [ZLMediaKit/ZLMediaKit#1624]
![image](https://user-images.githubusercontent.com/11680858/167817250-f28ea01f-71d7-476b-9b66-d03b54f8b2c7.png)
![image](https://user-images.githubusercontent.com/11680858/167819537-dcb0cd10-9a77-46e9-8b49-0c4126281ac8.png)

**Comment by joyol** [comment]
win10的ie报语法错误，这个好判断
旧版谷歌浏览器报this.pc.addTransceiver is not a function 这种怎么判断？

**Comment by xia-chu** [comment]
ie好像都不支持webrtc的

**Comment by xxxxxxbin6** [comment]
https://caniuse.com/?search=webrtc

**Comment by xiaosongxiaosong** [comment]
> win10的ie报语法错误，这个好判断 旧版谷歌浏览器报this.pc.addTransceiver is not a function 这种怎么判断？

这种情况下判断 RTCPeerConnection.prototype.addTransceiver 是不是 function

**Comment by xia-chu** [comment]
issue关闭了 这么多小伙伴给出答案了
