### ISSUE TITLE
[技术咨询] flv.js 播放失败

### ISSUE THREAD

**Issue by bravecat** [ZLMediaKit/ZLMediaKit#1626]
**咨询的功能模块**
- addStreamProxy 接口

**咨询的具体内容和问题**
调addStreamProxy接口，拉摄像头rtsp流。
等rtmp流注册成功后，浏览器用flv.js 播放，视频静止，flv.js 报错误`[FlvPlayer] > Maximum buffering duration exceeded, suspend transmuxing task`。等待几秒后，重新播放又正常了。

**Comment by xia-chu** [comment]
这个问题可能是时间戳不好导致的 可以修改配置文件 开启时间戳覆盖试试：
```ini
general.modifyStamp=1
```

**Comment by bravecat** [comment]
> 这个问题可能是时间戳不好导致的 可以修改配置文件 开启时间戳覆盖试试：
> 
> ```ini
> general.modifyStamp=1
> ```

修改后，Mac 系统火狐浏览器在播放窗口报错误“视频无法播放，因为该文件已损坏。“
