### ISSUE TITLE
[技术咨询]http服务器字符编码问题

### ISSUE THREAD

**Issue by sapceman** [ZLMediaKit/ZLMediaKit#1628]
测试机器是windows 11 ，改配置文件http服务器字符编码为utf-8后API中返回的中文是乱码，请问在windows上只能用gb2312吗？

**Comment by xia-chu** [comment]
我打算后面全部改成utf-8的。
现在msvc默认编译成GB2312内码了，但是网页资源又是utf-8的，所以不管咋改，都可能乱码。
所以我打算msvc编译改成utf-8的

**Comment by xia-chu** [comment]
你先打个patch：
```patch
Index: CMakeLists.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- CMakeLists.txt	(revision 301cbf0a8347dd1cce6332dbb5496b4493ee833a)
+++ CMakeLists.txt	(date 1652341312747)
@@ -234,7 +234,7 @@
 endif ()
 
 #set(VS_FALGS "/wd4819 /wd4996 /wd4018 /wd4267 /wd4244 /wd4101 /wd4828 /wd4309 /wd4573 /wd4996" )
-set(VS_FALGS "/wd4819")
+set(VS_FALGS "/wd4819 /utf-8")
 
 #添加mpeg用于支持ts生成
 if (ENABLE_RTPPROXY OR ENABLE_HLS)

```
编译后，修改配置文件为`charSet=utf-8`就不会乱码了

**Comment by sapceman** [comment]
> 你先打个patch：
> 
> ```diff
> Index: CMakeLists.txt
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- CMakeLists.txt	(revision 301cbf0a8347dd1cce6332dbb5496b4493ee833a)
> +++ CMakeLists.txt	(date 1652341312747)
> @@ -234,7 +234,7 @@
>  endif ()
>  
>  #set(VS_FALGS "/wd4819 /wd4996 /wd4018 /wd4267 /wd4244 /wd4101 /wd4828 /wd4309 /wd4573 /wd4996" )
> -set(VS_FALGS "/wd4819")
> +set(VS_FALGS "/wd4819 /utf-8")
>  
>  #添加mpeg用于支持ts生成
>  if (ENABLE_RTPPROXY OR ENABLE_HLS)
> ```
> 
> 编译后，修改配置文件为`charSet=utf-8`就不会乱码了

这样api不会乱码，日志文件和控制台输出又乱码了。还是等你出uft-8的版本吧。

> 你先打个patch：
> 
> ```diff
> Index: CMakeLists.txt
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- CMakeLists.txt	(revision 301cbf0a8347dd1cce6332dbb5496b4493ee833a)
> +++ CMakeLists.txt	(date 1652341312747)
> @@ -234,7 +234,7 @@
>  endif ()
>  
>  #set(VS_FALGS "/wd4819 /wd4996 /wd4018 /wd4267 /wd4244 /wd4101 /wd4828 /wd4309 /wd4573 /wd4996" )
> -set(VS_FALGS "/wd4819")
> +set(VS_FALGS "/wd4819 /utf-8")
>  
>  #添加mpeg用于支持ts生成
>  if (ENABLE_RTPPROXY OR ENABLE_HLS)
> ```
> 
> 编译后，修改配置文件为`charSet=utf-8`就不会乱码了

非常感谢百忙中这么快回复并提出解决方案。这样api不会乱码，日志文件和控制台输出又乱码了。还是等你出uft-8的版本吧。

**Comment by xia-chu** [comment]
控制台输出可以选择输出utf-8模式的，日志文件你用utf-8方式打开也不会乱码
