### ISSUE TITLE
[技术咨询]使用h264分帧器读取264文件播放会花屏

### ISSUE THREAD

**Issue by 4610155** [ZLMediaKit/ZLMediaKit#1637]
**咨询的功能模块**
C API部分

**咨询的具体内容和问题**
参考api用例里面h264_media_server，创建h264分帧器并读h264文件，通过rtmp拉流播放会花屏，似乎是和h264多slice处理有关？这里要如何处理，必须是单slice的264才行吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
可以发个测试264文件上来供我们测试下

**Comment by 4610155** [comment]
[test.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8712500/test.zip)
解压附件就是
拉取的代码版本信息：
commit 4c1f0c9b7fa72b7329284e0ab08177ea89ad4f45 (grafted, HEAD -> master)
Author: ziyue <1213642868@qq.com>
Date:   Tue May 10 17:28:48 2022 +0800

**Comment by xia-chu** [comment]
这个原因是H264的时间戳打的不对，你加上这个patch就行了：
```patch
Index: src/Extension/Frame.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Extension/Frame.cpp b/src/Extension/Frame.cpp
--- a/src/Extension/Frame.cpp	(revision c7d7999f5394790599c11833baf082fe400ae82d)
+++ b/src/Extension/Frame.cpp	(revision 56ec41d406377cdb1fbfaa8ce6580faa32751213)
@@ -114,7 +114,7 @@
                 //缓存中没有有效的能解码的帧，所以这次不flush
                 return _frame_cache.size() > kMaxFrameCacheSize;
             }
-            if (_frame_cache.back()->dts() != frame->dts() || frame->decodeAble() || frame->configFrame()) {
+            if (frame->decodeAble() || frame->configFrame()) {
                 //时间戳变化了,或新的一帧，或遇到config帧，立即flush
                 return true;
             }

```

**Comment by xia-chu** [comment]
这个修改不太敢加入到master分支 影响比较大

**Comment by 4610155** [comment]
之前的可以了，但是感觉问题没彻底解决，我再发个h264。这个是我拿图片用ffmpeg转的
[test1.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8722907/test1.zip)

**Comment by xia-chu** [comment]
另外一个h264需要你自己先尝试解决。
这个测试程序在生成时间戳时，没考虑多slice的情况，所以会这样，如果你输入正确的时间戳 就不会有问题的，所以本质上，zlm的代码是没问题的，上面那个patch只是兼容这种情况，但是合入master分支可能会引入不可预知的风险，所以不打算合入。
