### ISSUE TITLE
zlm点播超时 不清楚具体原因是什么[技术咨询]

### ISSUE THREAD

**Issue by xue9957** [ZLMediaKit/ZLMediaKit#1640]
**咨询的功能模块**
-zlm点播超时

**咨询的具体内容和问题**
- 点播时候zlm日志报超时错误 之前都是先有媒体注册现在是直接报超时 希望大神能够解决一下
![image](https://user-images.githubusercontent.com/77611572/168941125-b946b50d-80de-40b9-bf8c-48eb1563c58b.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by Smallwhitepig** [comment]
WVP点播超时
1 WVP前端后端不要在编译器运行
2 如果是公网部署,请按照WIKI设置部署

**Comment by xue9957** [comment]
> WVP点播超时 1 WVP前端后端不要在编译器运行 2 如果是公网部署,请按照WIKI设置部署

这个我也按照WIKI部署了 也是公网  但是就这个问题是ZLM服务器一直超时  找不到原因

**Comment by Smallwhitepig** [comment]
公网映射有问题,git log 回退版本尝试

**Comment by xue9957** [comment]
> 公网映射有问题,git log 回退版本尝试

![image](https://user-images.githubusercontent.com/77611572/168969038-8830ae10-c4a9-456d-aca9-9714598ee095.png)
这些端口是必须开放嘛

**Comment by xue9957** [comment]
![image](https://user-images.githubusercontent.com/77611572/168979868-d3f3f4e2-fa6c-48f9-a562-11acd2b6bef2.png)
这是我本地起的可以点播 但是在公网话就是执行不了我画圈里面的 直接都是超时异常

**Comment by xue9957** [comment]
> 28181 心跳设置到10秒

是sip服务 还是摄像头端的心跳？

**Comment by xue9957** [comment]
> 28181 心跳设置到10秒

![image](https://user-images.githubusercontent.com/77611572/168991929-0cbaced3-b554-4a14-ad66-7d2c8968654b.png)
还是这样

**Comment by mygithubhey** [comment]
![image](https://user-images.githubusercontent.com/38482285/169243666-1cda6ad9-51bd-4174-8bc5-2e1b5e95ee61.png)
我也出现这种问题了，不知道时什么原因呢，求大神帮忙解答

**Comment by xia-chu** [comment]
rtp timeout的问题 需要你们去wvp的仓库提issue，zlm解决不了

**Comment by xia-chu** [comment]
其实也不用提issue 这个是自己不看配置文件注释导致的

**Comment by shiki-zzzz** [comment]
我遇到过这种问题是因为版本升级了没注意播放地址有变化，播放地址错误了导致的。

> ![image](https://user-images.githubusercontent.com/38482285/169243666-1cda6ad9-51bd-4174-8bc5-2e1b5e95ee61.png) 我也出现这种问题了，不知道时什么原因呢，求大神帮忙解答

**Comment by honorbounds** [comment]
wvp里的media节点配置 
# [可选] 是否自动配置ZLM, 如果希望手动配置ZLM, 可以设为false, 不建议新接触的用户修改
    auto-config: true

**Comment by xia-chu** [comment]
issue关闭了 wvp的使用希望大家好好看下它的文档
