### ISSUE TITLE
[BUG]: 设备倍速流播放无倍速效果，仍然是正常播放速度

### ISSUE THREAD

**Issue by LMiracle** [ZLMediaKit/ZLMediaKit#1642]
### 现象描述

对海康、同为、宇视等品牌设备的设备录像进行回放时，使用倍速播放，但是ZLM推回来的流并没有进行倍速播放仍然是正常播放速度，使用同样的设备使用了liveGBS的测试平台进行倍速播放正常。
liveGBS地址：https://gbs.liveqing.com:10010/login.html

### 如何复现?

ZLM测试：我自身采用了WVP+ZLM来使用，将支持国标的设备的设备录像流推给ZLM，然后发送SIP信令对设备的流速度进行调整，使用VLC、hls.js等播放器进行播放，测试是否已进行倍速播放。
liveGBS测试：匿名登录liveGBS的演示系统->国标设备->查看通道->设备录像->右上列表视图->选择一个进行播放->打开浏览器开发者模式F12获取流地址，然后通过自身的播放器进行播放，在页面上可进行对速度倍速调整。

### 相关日志或截图

图片没法反应录像播放速度，就不贴图了。
下面使用使用WVP+ZLM时，WVP已成功发送SIP信令给设备进行调速的截图
![image](https://user-images.githubusercontent.com/26618535/169004954-35ae6af5-3985-4ded-bcf8-dd4ae6c48fe4.png)

进行倍速播放时，前端也同样检测到下载数据量有上升，但是视频并没有进行倍速播放。我已排查过播放器的原因，同样的播放器，liveGBS可以进行倍速播放，但是使用WVP+ZLM就不行了，所以应该与播放器没关联。
正常播放时的下载数据量：
![image](https://user-images.githubusercontent.com/26618535/169012760-372143a1-7aea-4f45-a2ca-5ce9e0b5817a.png)

4倍速播放时的下载数据量：
![image](https://user-images.githubusercontent.com/26618535/169012689-7e4a9cf9-c0e1-4dc4-bbda-65986a3a1ab7.png)

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
timeout_sec=15

[ffmpeg]
bin=D:\Environment\ffmpeg\ffmpeg-2022-03-03\bin\ffmpeg.exe
cmd=%s -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
addMuteAudio=1
continue_push_ms=3000
enableVhost=0
enable_audio=1
flowThreshold=1024
fmp4_demand=0
hls_demand=0
maxStreamWaitMS=15000
mediaServerId=LORVY158beilorvy
mergeWriteMS=0
modifyStamp=0
publishToHls=1
publishToMP4=0
resetWhenRePlay=1
rtmp_demand=0
rtsp_demand=0
streamNoneReaderDelayMS=10000
ts_demand=0
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=3000

[hls]
broadcastRecordTs=0
deleteDelaySec=0
fileBufSize=65536
filePath=./www
segDur=2
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=30.000000
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.118.47:18080/index/hook/on_play
on_publish=http://192.168.118.47:18080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_server_keepalive=http://192.168.118.47:18080/index/hook/on_server_keepalive
on_server_started=http://192.168.118.47:18080/index/hook/on_server_started
on_shell_login=http://192.168.118.47:18080/index/hook/on_shell_login
on_stream_changed=http://192.168.118.47:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.118.47:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.118.47:18080/index/hook/on_stream_not_found
timeoutSec=20

[http]
charSet=gb2312
dirMenu=1
forbidCacheSuffix=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>�����ʵ���Դ�����ڣ�</h1></center><hr><center>ZLMediaKit(git hash:6254320,branch:master,build time:Mar 28 2022 18:24:33)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
port=10000
port_range=30000-30500
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

; } ---

</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:Windows 10
* **硬件信息**: CPU:Intel i7-7700HQ 2.80GHz    内存:16G 显卡:GTX1050
* **其他需要补充的信息**:WVP+ZLM本地部署使用

**Comment by xia-chu** [comment]
倍速有4个要求：
1、时间戳加倍
2、数据速度加倍
3、没有音频
4、播放器支持


现在zlm没处理时间戳，所以设备推流时间戳应该不是加倍的，另外你要核对下，去掉音频可不可以加倍播放

**Comment by Smallwhitepig** [comment]
这个已经测试过了 倍速播放是没问题的 关键是播放器问题

**Comment by LMiracle** [comment]
播放器，我已经测试过好几款了，都是在liveGBS上可以，在使用WVP+ZLM时不行
以下是我测试过的播放器：
https://github.com/video-dev/hls.js
https://github.com/fuyi501/web-video-live
https://github.com/videojs/video.js

**Comment by LMiracle** [comment]
关于时间戳方面，在四倍速的情况下，发现会有很多断层出现，就是有很多段视频时间戳丢失了，导致不断卡顿。

**Comment by xiongguangjie** [comment]
调整这个参数 https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/playbackRate

**Comment by LMiracle** [comment]
有个问题，倍速播放的实现上有两种方式，
第一种是流媒体服务器推送更长的时间戳给播放器，播放器利用自身的倍速来进行调节，我猜这是目前ZLM的实现方式
第二种是流媒体服务器推送倍速后的流给播放器，播放器不需要对视频流进行任何调节，liveGBS的实现方式
WVP+ZLM目前可以利用第一种方式实现播放器两倍速播放，但是四倍速后时间戳就开始不稳定了，时间戳不断断层，我觉得这种方式存在弊端
liveGBS上实现的是第二种模式，我目前测试下来在四倍速下也十分稳定，这种方式也依赖于设备支持倍速推流，因此需要发送SIP信令给设备进行调速

**Comment by xiongguangjie** [comment]
这个与ZLM+wvp 基本没有太大关系，主要是播放器的问题，倍速播放2倍速是很合适的，4倍速火狐好很多，谷歌很糟糕，如果分辨率很高的话。你可以试一下其他播放器，如rtc ,wasm 之类的，他们可能会有相应的优化

**Comment by hoheyho** [comment]
楼主，请问下您解决了吗？
我也遇到同样的问题，

**Comment by amjack** [comment]
楼主解决问题了吗，想请教下

**Comment by amjack** [comment]
> 楼主，请问下您解决了吗？ 我也遇到同样的问题，

问题解决了吗
