### ISSUE TITLE
[技术咨询]http-flv播放页面关闭后，服务器端大概15秒才收到播放断开事件，ws-flv页面关闭时会即时触发断开事件，是否正常？

### ISSUE THREAD

**Issue by xlsky0713** [ZLMediaKit/ZLMediaKit#1643]
**咨询的功能模块**
- 播放器断开事件

**咨询的具体内容和问题**
- http-flv播放页面关闭后，zlm大概15秒才收到播放断开事件，ws-flv页面关闭时会即时触发断开事件，是否正常？

**Comment by xia-chu** [comment]
可能播放器没立即断开tcp链接

**Comment by xlsky0713** [comment]
浏览器直接关闭了，还是会出现这个延迟

**Comment by xia-chu** [comment]
如果浏览器关闭了 那么socket肯定会被操作系统回收 zlm一定会收到eof的
