### ISSUE TITLE
[技术咨询]麻烦请问下为何要每个推流独立端口?也就是port_range的作用

### ISSUE THREAD

**Issue by Sprlia** [ZLMediaKit/ZLMediaKit#1648]
**咨询的功能模块**
- rtp_proxy模块

**咨询的具体内容和问题**
- 想问下为何每个流独立分配端口进行推流，一个端口也可以用ssrc作为区分吧。之前的版本默认10000端口可以接收不同ssrc的流并以ssrc作为流ID，但是master貌似是修改了，强制不同流使用不同端口，并且一个流只能是一个端口

**Comment by xia-chu** [comment]
不会的 10000端口一直可以接收多个rtp流 同时也是根据ssrc做stream_id。

**Comment by jokbor** [comment]
你是不是配合WVP一起用的，因为WVP是默认开启多端口的，只要运行WVP连接ZLM就会自动修改ZLM的配置，把WVP的开启多端口变成False就可以了

**Comment by xia-chu** [comment]
各有各的好处 自己安装自己需要选择吧

**Comment by Sprlia** [comment]
谢谢大家，理解了
