### ISSUE TITLE
session not found when record

### ISSUE THREAD

**Issue by goodcyg** [ZLMediaKit/ZLMediaKit#1650]
非常感谢作者的辛勤奉献。我在使用的时候sdk报错：session not found when record。始终没有找到原因？我是用HTTPLiveStreaming+GCDAsyncSocket进行rtsp推流，但是ZLMediaKit报错session not found when record。拉流也报错找不到流？
我猜测是没有把流推送上去，但是我用推流的时候打日志，都是有推流数据的。这哪里的问题？期待作者的解答，谢谢？

**Comment by goodcyg** [comment]
这是我session解析失败的原因。我解决了

**Comment by jokbor** [comment]
> 

想请教下是怎么解决的，目前我也有session这块的问题

**Comment by gsw945** [comment]
是 [rtmp-rtsp-stream-client-java](https://github.com/pedroSG94/rtmp-rtsp-stream-client-java) Session解析的bug, 已经提 PR ( https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/pull/1133 ) 去修复了
