### ISSUE TITLE
[技术咨询]UDP接收h264裸流

### ISSUE THREAD

**Issue by boxinl** [ZLMediaKit/ZLMediaKit#1651]
**咨询的功能模块**
- udp接收数据

**咨询的具体内容和问题**
- 在局域网内，一台服务器使用UDP发送h264裸流，在其他电脑部署zlmedia，zlmedia如何接收UDP发送的h264裸流数据，并进行播放。请大佬指点迷津，十分感谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
目前不支持直接接收H264帧数据的，你可以把H264打包成rtp(并且payload type指定为98); 然后推流给zlm 10000 udp端口即可

**Comment by xia-chu** [comment]
H264 rtp打包很简单的 你可以学习下。
由于mtu的限制，你也不可能直接一帧数据直接发给zlm

**Comment by boxinl** [comment]
好的。谢谢大佬，我再学习下
