### ISSUE TITLE
[技术咨询]新版本docker国标问题

### ISSUE THREAD

**Issue by dawn2zhang** [ZLMediaKit/ZLMediaKit#1653]
**咨询的功能模块**
- 国标推流播放问题

**咨询的具体内容和问题**
- 国标推流正常播放（直播、回放），seek指令后，播放停止，无法正常播放
- 使用三方的docker镜像一切正常，社区推荐的docker镜像如上现象
- 以下是抓包文件，帮忙分析下
[1.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8753617/1.zip)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by Smallwhitepig** [comment]
小伙伴你是不是穿越了?
使用WVP28181？
