### ISSUE TITLE
[功能请求]修正hls部分bug，优化hls直播流不再保存到硬盘中，而是缓存在内存中，hls不再依赖于cookie

### ISSUE THREAD

**Issue by wujianGit123** [ZLMediaKit/ZLMediaKit#1655]
修正hls部分bug，优化hls直播流不再保存到硬盘中，而是缓存在内存中，hls播放不再依赖于cookie

代码提交在国内gitee网站：
https://gitee.com/friedrich-hegel/ZLMediaKit
https://gitee.com/friedrich-hegel/ZLToolKit

其中ZLToolKit修改了BufferRaw类

请管理员查看并考虑合并

**Comment by alexliyu7352** [comment]
其实现在使用mmap性能已经不错了, 如果缓存在内存中, 更多是做动态切片.
另外能否以pr的形式提交, 这样作者比较好做代码审查和合并.

**Comment by xia-chu** [comment]
我跟 @wujianGit123 在qq讨论过了 主要还有hls cookie被干掉了 这个影响面太大了 所以不能合并这些特性。
性能方面，共享mmap其实性能已经非常ok了 我认为可能比直接放内存还好，另外其实还可以通过tmpfs内存磁盘解决这个问题，所以这些修改必要性不大

**Comment by swq123459** [comment]
可否做个抽象可以选择文件缓存位置

**Comment by xia-chu** [comment]
> 可否做个抽象可以选择文件缓存位置

现在hls保存可以自定义路径的 但是hls读取不行
