### ISSUE TITLE
strange rtsp source

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#1659]
Hi,

With this rtsp source, MediaServer can not connect while VLC and ffplay work fine.
Here is some logs, i will send you rtsp url to your email.

    Last message repeated 181 times
2022-05-26 18:51:39.990 T MediaServer.exe[18056-event poller 14] RtpReceiver.cpp:61 inputRtp | rtp pt ???:105 !=50

    Last message repeated 154 times
2022-05-26 18:51:40.161 W MediaServer.exe[18056-event poller 14] H264Rtp.cpp:53 inputRtp | start drop h264 gop, last seq:10621, rtp:

version:2

padding:0

ext:0

csrc:0

mark:1

pt:50

seq:10827

stamp:809310000

ssrc:70477949

rtp size:27

payload offset:0

payload size:15

2022-05-26 18:51:40.168 T MediaServer.exe[18056-event poller 14] RtpReceiver.cpp:61 inputRtp | rtp pt ???:105 !=50
2022-05-26 18:51:40.687 T MediaServer.exe[18056-event poller 14] RtpReceiver.cpp:61 inputRtp | rtp pt ???:105 !=50

    Last message repeated 51 times
2022-05-26 18:51:41.245 T MediaServer.exe[18056-event poller 14] RtpReceiver.cpp:61 inputRtp | rtp pt ???:105 !=50

    Last message repeated 44 times
2022-05-26 18:51:41.826 T MediaServer.exe[18056-event poller 14] RtpReceiver.cpp:61 inputRtp | rtp pt ???:105 !=50

**Comment by xia-chu** [comment]
`Last message repeated xx times` do not worry，this log can be deleted.

**Comment by xia-chu** [comment]
zlmediakit just receive some rtp with `payload type` not identified

**Comment by xia-chu** [comment]
I test i can play it

**Comment by xia-chu** [comment]
You can play it by transport `udp`

**Comment by pubpy2015** [comment]
Sory, but still cant play with udp transport ("rtp_type":1,"timeout_sec":45)

ffplay cant play with "-rtsp_transport udp" too.

**Comment by pubpy2015** [comment]
dont know why now it can play (tcp transport).
Seem MediaServer has memory leak in this case. I see that memory increase from 12-> 19MB in ~ 4 hours.

**Comment by pubpy2015** [comment]
I see that when error (MediaServer cant play this source), MediaServer still consumtion network bandwidth and there is an error "start drop h264 gop, last seq:"
![ảnh](https://user-images.githubusercontent.com/59004953/170615559-3e7a2bd5-601b-4fce-b8e8-a6f3418ce43c.png)

**Comment by xia-chu** [comment]
Do you pull this rtsp stream via `rtsp udp` transport ?

**Comment by xia-chu** [comment]
`start drop h264 gop` meaning that, zlmediakt find that some rtp packet droped

**Comment by xia-chu** [comment]
When `rtp droped`, zlmediakit will drop all the `gop` until received new rtp of `key frame`

**Comment by pubpy2015** [comment]
> Do you pull this rtsp stream via `rtsp udp` transport ?

No, can't play with `rtsp udp` transport

**Comment by xia-chu** [comment]
It seemingly that, the camera was on bad network, so it droped som rtp when send blocked on tcp transport.

**Comment by pubpy2015** [comment]
Thanks,
I will consider about network.

How about memory leak in this case ?

> Seem MediaServer has memory leak in this case. I see that memory increase from 12-> 19MB in ~ 4 hours.

**Comment by pubpy2015** [comment]
Seem network problem can't solve immediate.
Do you have a setting or modify in code to make MediaServer can play this stream in this case as VLC or FFplay ?

**Comment by xia-chu** [comment]
> Thanks, I will consider about network.
> 
> How about memory leak in this case ?
> 
> > Seem MediaServer has memory leak in this case. I see that memory increase from 12-> 19MB in ~ 4 hours.

I  do not think so;  it is normal for memory to float up and down slightly

**Comment by xia-chu** [comment]
> Seem network problem can't solve immediate. Do you have a setting or modify in code to make MediaServer can play this stream in this case as VLC or FFplay ?

No,  only UDP transport can solve this problem

**Comment by pubpy2015** [comment]
Thanks.
