### ISSUE TITLE
[BUG]: 以./MediaServer -d &方式运行程序后，首次调用FFmpeg截图会使程序卡住

### ISSUE THREAD

**Issue by hany-dev** [ZLMediaKit/ZLMediaKit#1662]
### 现象描述
感谢夏楚老师的开源项目
   在调试过程中，以./MediaServer -d &方式运行程序后，调用getSnap接口，在log中发现运行到FFmpeg截图会使程序卡住，查看系统进程信息后，进程均显示为暂停。通过kill指令杀死掉守护进程后，则程序可以继续正常运行，此时再调用getSnap接口即可正常获取到截图。
    然而在使用./MediaServer -d的方式运行时，就不存在这个现象，调用getSnap接口可正常返回结果。

### 如何复现?
以./MediaServer -d &方式运行程序后，调用getSnap接口即可。

### 相关日志或截图
程序开启时的截图，调用getSnap接口后卡住
![图片](https://user-images.githubusercontent.com/39269298/170624748-673e498b-490f-40d0-b708-e874deea7495.png)
查询系统进程信息的截图，两个进程均处于 “T” 的状态
![图片](https://user-images.githubusercontent.com/39269298/170624812-b0d196e0-0797-4be1-b53a-3f93901192fc.png)
kill掉一个进程后，再次查看进程状态，可以看到恢复了 Sl 的状态
![图片](https://user-images.githubusercontent.com/39269298/170624886-675e2504-8575-4d2f-8440-0bf314a0fa91.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置
配置未进行修改，从gittee上直接拉取了最新的程序。

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
采用了最新的程序代码 
git commit hash = e2908e9775e3e16344e59717b9e0f4b2d846467b
操作系统采用：ubuntu18.04
硬件采用了普通笔记本  intel处理器

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个调用FFmpeg进程挂起的问题 我在wiki中已经提到了 需要nohup运行。
这个问题我也不知道为什么，由于不是很大的问题，一直没抽时间去解决这个问题。

**Comment by alexliyu7352** [comment]
如果不用nohup的话, 你可以把这段代码加入到startDaemon中.
主要是防止守护进程挂起.
实际上nohup的作用也就是这个

```
if (isatty(STDIN_FILENO)) {
        /* bb_error_msg("ignoring input"); */
        close(STDIN_FILENO);
        open("/dev/null", O_RDONLY, 0666); /* will be fd 0 (STDIN_FILENO) */
    }
    signal(SIGHUP, SIG_IGN);
```

**Comment by hany-dev** [comment]
感谢大佬的解答，感谢

**Comment by zymerry** [comment]
- 经过这几天的研究，发现这里主要和execv里执行ffmpeg命令有关
- 在ffmpeg的进程里会读写控制终端导致，收到了SIGOUT信号。程序里未对SIGOUT信号做特殊处理，所以采用了默认的处理方式，程序暂停

**Comment by xia-chu** [comment]
周末我解决下这个问题

**Comment by xia-chu** [comment]
我实测了下 先启动ffmpeg经常不回挂起zlm了 但是shell输入交互还是受影响

**Comment by xia-chu** [comment]
> 如果不用nohup的话, 你可以把这段代码加入到startDaemon中. 主要是防止守护进程挂起. 实际上nohup的作用也就是这个
> 
> ```
> if (isatty(STDIN_FILENO)) {
>         /* bb_error_msg("ignoring input"); */
>         close(STDIN_FILENO);
>         open("/dev/null", O_RDONLY, 0666); /* will be fd 0 (STDIN_FILENO) */
>     }
>     signal(SIGHUP, SIG_IGN);
> ```

经验证 这个方案可行
