### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by chenparty** [ZLMediaKit/ZLMediaKit#1664]
**咨询的功能模块**
-音频

**咨询的具体内容和问题**
-使用摄像头默认的G711.A编码播放视频时，解码非常慢，一般要等个5~10s才能播放出来；
将摄像头换成AAC编码播放视频时，启动很快，基本秒播。

**Comment by xia-chu** [comment]
GB28181吗，纯音频吗

**Comment by chenparty** [comment]
是GB28181，音视频一起

**Comment by xia-chu** [comment]
你提的issue不规范哈 基本没有啥有效信息。不过根据经验 我猜测是摄像头声明有音频 但其实没有，你可以设置配置文件 关闭音频
