### ISSUE TITLE
[技术咨询]大华摄像头智能编码

### ISSUE THREAD

**Issue by SuperChrisliu** [ZLMediaKit/ZLMediaKit#1665]
**咨询的功能模块**
- rtsp h264

**咨询的具体内容和问题**
- 大华摄像头，web管理界面：
- 
<img width="865" alt="image" src="https://user-images.githubusercontent.com/7054257/170644877-19446930-b425-4e16-8efa-2c0f9223c337.png">
上图里红框圈出来的，智能编码选项，如果选择启用，那么通过addStreamProxy接口拉流，再用ffplay（-fflags nobuffer）播放rtmp流，ffplay会输出如下提示，然后要等很久才能开始播，但是没有延迟。

```

[h264 @ 0x7f987a550540] reference picture missing during reorder0   
[h264 @ 0x7f987a550540] Missing reference picture, default is 198
[h264 @ 0x7f987a584f40] reference picture missing during reorder0   
[h264 @ 0x7f987a584f40] Missing reference picture, default is 298
[h264 @ 0x7f987a55acc0] reference picture missing during reorder0   
[h264 @ 0x7f987a55acc0] Missing reference picture, default is 398
[h264 @ 0x7f987a779ec0] reference picture missing during reorder0   
[h264 @ 0x7f987a779ec0] Missing reference picture, default is 498
[h264 @ 0x7f987a565580] reference picture missing during reorder0   
[h264 @ 0x7f987a565580] Missing reference picture, default is 598
[h264 @ 0x7f987a52eb00] reference picture missing during reorder0   
[h264 @ 0x7f987a52eb00] Missing reference picture, default is 698
[h264 @ 0x7f987a56fe00] reference picture missing during reorder0   
[h264 @ 0x7f987a56fe00] Missing reference picture, default is 798
[h264 @ 0x7f987a546580] reference picture missing during reorder0 

```

上图里红框圈出来的，智能编码选项，如果选择关闭，ffplay没有这样的提示，也很快就能开始播放。

------------其他播放器：

### 小程序

在小程序中测试，使用live-player，智能编码选项为开启时，
- 1.如果先调用addStreamProxy接口拉流，再打开小程序开始播的延迟很大10s左右，且画面很久才能出来，但是如果
- 2.如果先打开小程序开始播，再调用addStreamProxy接口拉流，小程序秒开画面，且延迟很小很稳定

在小程序中测试，使用live-player，智能编码选项为关闭时，无论何时打开小程序，都秒开画面，延迟很低

### flv.js

智能编码选项为开启时，要等很久才能看到画面，且延迟大，智能编码选项为关闭时，秒开画面，且延迟小

想请教一下，以上问题是因为大华设备的智能编码会导致h264流不遵守规范导致的吗

**注意事项**
- 未找到同类问题

**Comment by xia-chu** [comment]
先播放后`addStreamProxy`可以确保播放器拉取到第一个GOP。
先`addStreamProxy`后播放，可能GOP缓存失效了。
开启智能编码时，很可能摄像头在zlm拉流发起时才生成一个关键帧，后面很久才再生成，这样会导致zlm的gop缓存失效，这样你再播放zlm的代理流，由于没有GOP缓存，肯定不能秒开啊，只能等摄像头10几秒后再生成一个GOP

**Comment by mayunxi** [comment]
关键帧的问题，比如海康25帧的视频，250帧才生成一个关键帧
