### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by sang8052** [ZLMediaKit/ZLMediaKit#1668]
### 现象描述

编译时报错 use option -std=c99 or -std=gnu99 to compile your code
出错代码位置为  /api/tests/pusher.c 的 第 95 行 
 for (int i = 0; i < track_count; ++i) {
将变量 i 的定义修改到for 循环外部后 错误修复

### 如何复现?
centos7.9 纯净系统
yum install gcc gcc-c++ openssl openssl-devel cmake 
执行编译

**Comment by xia-chu** [comment]
修改了 感谢反馈！
