### ISSUE TITLE
[技术咨询] ws flv, 建立链接过程中，另一个wsflv无法正常使用

### ISSUE THREAD

**Issue by yuht2019** [ZLMediaKit/ZLMediaKit#1670]
**咨询的功能模块**
- wsflv 多个播放问题

**咨询的具体内容和问题**
利用wsflv播放多个视频流，当第一个websocket在建立链接状态（panding），在点击另一个也会一直在出在建立链接状态。直到第一个超时。请问这个不能并发简历链接吗？

**Comment by xia-chu** [comment]
这个是浏览器的问题 跟zlm无关

**Comment by xia-chu** [comment]
播放一个不存在的流 zlm会挂起播放器，你可以对接hook或者从业务上规避这个问题

**Comment by yuht2019** [comment]
前端播放的时候如果流没有会触发 “on_stream_not_found”事件，我利用这个事件 发送国标的Invite指令，进行拉流，这个过程中这个ws一直处于pending状态（下级出现什么问题一直不返回流），这个时候浏览器请求播放另一个视频，这个ws也一直处于panding状态（服务器也收不到on_stream_not_found事件）， 直到第一个超时，第二个才会收到"on_stream_not_found"事件。这个是浏览器的限制吗？

**Comment by xia-chu** [comment]
当然



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yuht2019 ***@***.***&gt;
发送时间: 2022年5月30日 09:42
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] ws flv, 建立链接过程中，另一个wsflv无法正常使用 (Issue #1670)





 
前端播放的时候如果流没有会触发 “on_stream_not_found”事件，我利用这个事件 发送国标的Invite指令，进行拉流，这个过程中这个ws一直处于pending状态（下级出现什么问题一直不返回流），这个时候浏览器请求播放另一个视频，这个ws也一直处于panding状态（服务器也收不到on_stream_not_found事件）， 直到第一个超时，第二个才会收到"on_stream_not_found"事件。这个是浏览器的限制吗？

**Comment by yuht2019** [comment]
谢谢您的解答， 这个有什么方法解决吗？ 尽量减少对后面ws的影响。

**Comment by xia-chu** [comment]
这个不好解决呢，尽量减少单页面播放器个数吧

**Comment by xia-chu** [comment]
用多域名应该能解决
