### ISSUE TITLE
[意见建议]代码分支管理——是否有切出release分支的规划？

### ISSUE THREAD

**Issue by cxyxiaoli** [ZLMediaKit/ZLMediaKit#1671]
**描述该功能的用处，可以提供相关资料描述该功能**
商用级别的开源代码一般都有release分支和release tag，看了一下ZLMediaKit在2019年的时候有发布过release版本，后续就没有再发布了，目前的代码更新都是在master分支进行。
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
否。
**描述你期望实现该功能的方式和最终效果**
建议可以切一个稳定版本分支和开发分支，一个用于记录每次发布版本的稳定代码，一个用于日常的开发更新。    
这样可以在发布release版本的时候再做一些大规模的压测，也避免中间master分支笔误引入的问题。

**Comment by xia-chu** [comment]
zlm采用滚动发布模式 有问题会及时更新，你fork分支时可以关注下下zlm的提交 可以选择同步bug修复这样的提交。
维护多个分支太费精力了，而且老是讲，特别是解决用户问题时，代码不对齐很难定位。

**Comment by cxyxiaoli** [comment]
好的，感谢作者的回复。
