### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by cxjgithub** [ZLMediaKit/ZLMediaKit#1672]
在使用ZLMediaKit的时候，进行拉流代理添加或者录像停止的时候出现Release目录下的ini文件被替换，里面配置数据被跟新，配置参数的注释都没掉的情况，请教一下什么情况下会出现这样的现象

**Comment by xia-chu** [comment]
wvp托管了zlm的配置文件

**Comment by cxjgithub** [comment]
哦哦，谢谢，如何修改config.ini文件进并生效，我们可能需要对配置文件进行修改，或者wvp有设置途径呢

**Comment by xia-chu** [comment]
`wait http response complete timeout` 原因是访问你的hook服务器超时 你可以抓包分析下 到底是zlm的问题 还是你hook服务器的问题
