### ISSUE TITLE
addStreamPusherProxy转推rtsp流失败：the media source was released

### ISSUE THREAD

**Issue by Jackfeng212** [ZLMediaKit/ZLMediaKit#1675]
环境说明：
   两台阿里云服务器，均部署了最新的官方docker版本。
测速过程：
   本地使用ffmpeg推送rtsp流到服务器A，然后通过postman调用addStreamPusherProxy接口转推rtsp流到服务器B，接口返回错误：
![image](https://user-images.githubusercontent.com/71073400/171150584-21d6b556-51c7-4037-a857-8f9377c44b2a.png)

ffmpeg命令：
   
![image](https://user-images.githubusercontent.com/71073400/171151088-12d141e4-3618-414a-8f7b-a4f4f87b6731.png)

服务器B有收到推送日志，但是即刻就断开了：
![image](https://user-images.githubusercontent.com/71073400/171151299-2e12a120-bce4-4907-9eac-0bdb45230701.png)

改用rtmp推流到服务器A，然后再调用api进行代理转推是正常的，请教下大佬给分析下。

**Comment by xia-chu** [comment]
addStreamPusherProxy必须绑定一个已经注册了的流，你把一个不存在的流转推出去 就会报这个错误

**Comment by xuandu** [comment]
这个是不是不能把RTMP的数据源推给RTSP的地址；http://...addStreamPusherProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc....schema=rtmp&dst_url=rtsp://10.11.123.12/aaa/c1

**Comment by xia-chu** [comment]
> addStreamPusherProxy

不能 协议必须相同
