### ISSUE TITLE
[BUG]: BUG 清空磁盘所有文件的问题

### ISSUE THREAD

**Issue by xilidedashu** [ZLMediaKit/ZLMediaKit#1679]
### 现象描述

当拉流中的域名、应用或者流id中有中文的时候，删除这个拉流，会导致流媒体服务清空整个磁盘文件的问题。

### 如何复现?

添加一个拉流，域名、应用名和流id中有中文。
删除这个拉流信息。

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

Windows 10 64位
* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
此问题仅Windows独有 需要跟踪调试下

**Comment by es12138** [comment]
仅在windows下测试结果
触发条件如下：
1. 准确说不是中文导致，是**添加rtsp/rtmp/hls拉流代理(addStreamProxy)**接口的参数 **stream**(添加的流的id名) 或者 **app**(添加的流的应用名)中包含windows下创建文件夹时的非法字符。
![image](https://user-images.githubusercontent.com/72786149/173269767-1e98c304-84ff-4c58-9f5d-4656e7f2f8dd.png)
  这个更像是在windows下创建文件、文件夹非法字符引起的，只是上面两个参数可以触发这个条件。
2. 同时config.ini中需开启**推流时mp4录像**，如下：
  [general]
  publishToMP4=1

在调用**关闭拉流代理(delStreamProxy)** 时，便会删除盘符下所有文件。（这个bug太痛苦了）

规避的话，可以在config.ini中关闭**推流时mp4录像**
@xilidedashu @xia-chu

**Comment by xia-chu** [comment]
确实 我感觉也是乱传参数导致的 不过应该还是添加一道防火墙保障这个
