### ISSUE TITLE
[技术咨询] make -j4

### ISSUE THREAD

**Issue by chenygs** [ZLMediaKit/ZLMediaKit#1680]
**咨询的功能模块**
-  make -j4

**咨询的具体内容和问题**
![image](https://user-images.githubusercontent.com/29544349/171411712-4e04cdf1-ddf2-44a6-a6dd-7340edadbf4a.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
FFmpeg建议先使用4.4版本 如果你不使用ffmpeg相关功能 可以cmake -DENABLE_FFMPEG=off选择关闭
