### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by dualven** [ZLMediaKit/ZLMediaKit#1683]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
华平的摄像头
AVCON
国际接入有问题，想问下，有没有接入过此类的摄像头呢？谢谢

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
有什么问题？

**Comment by dualven** [comment]
（1）咱们的zlmediaKit 接海康的摄像头，地平线的摄像头，都比较 正常；但接华平的摄像头，就是很难接入，也就是尝试N次，也许只有一次成功。
（2） 视频协议选264，咱们的zlmediakit接入海康，地平线的摄像头都好；但视频协议 换成H.265，就接入不了了？

**Comment by xia-chu** [comment]
需要你提供zlm的日志

**Comment by xia-chu** [comment]
@812063047 后面的截图 zlm没收到任何rtp推流 请检查GB28181 SIP握手是否成功。

**Comment by dualven** [comment]
@xia-chu
（1） 华平推流时，我通过tcpdump有看到摄像头一直在推流。推测是否信令没有对上？疑惑的是海康的都每次正常。
（2）H265就更疑惑了，海康的H264正常，H265应该与信令握手无关吧？ 怎么就不成功的，希望提供下思路 。
我去看看sip握手有没有问题。谢谢

**Comment by dualven** [comment]
@xia-chu
（1） 华平推流时，我通过tcpdump有看到摄像头一直在推流。推测是否信令没有对上？疑惑的是海康的都每次正常。
（2）H265就更疑惑了，海康的H264正常，H265应该与信令握手无关吧？ 怎么就不成功的，希望提供下思路 。
我去看看sip握手有没有问题。谢谢

**Comment by dualven** [comment]
@xia-chu 
我看了下sip报文：下面是正常的地平线摄像头的
![image](https://user-images.githubusercontent.com/2209534/172541412-b9b52bb2-0849-481a-b6e6-62370e4bacc4.png)
下面是不能正常点出播放的华平的
![image](https://user-images.githubusercontent.com/2209534/172541459-15a8a052-adec-44d4-bae2-8db6f3b274da.png)

**Comment by xia-chu** [comment]
可以使用zlm的dump功能 把rtp和ps文件上传上来

**Comment by dualven** [comment]
请教下，应该是参考哪一章进行操作，对这个工程内部细节不太熟，正在学习中。。。。
![image](https://user-images.githubusercontent.com/2209534/172549368-3d6c31f2-0323-47b1-a62a-e02bc92553d0.png)

**Comment by xia-chu** [comment]
不知道在哪里 就全部看一遍

**Comment by dualven** [comment]
[gbcom.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8897893/gbcom.zip)
@xia-chu 
不好意思，之前没有明白 你说的意思，后来群里问了下，其实我已经用tcpdump在zlm上截包了。打包了下。
2.cap 里，就是华平的摄像头的报文，过滤下，可以看到之前四个sip报文的交互，然后开始rtp推流，里面的内容可以详看。
其中10.60.3.56是华平摄像头的地址，10.60.100.192是zlm的地址。
![image](https://user-images.githubusercontent.com/2209534/173530490-c70a8fef-3f45-48c6-9b25-b93db59ced15.png)
主要想问的就是这个华平的报文有没有什么问题，是不是zlm识别的过程中有了啥问题？但没有看到报错的日志？

参考：
1.cap里，是正常的地平线的报文。10.60.2.178是地平线的摄像头。
![image](https://user-images.githubusercontent.com/2209534/173531297-9dce4431-3889-41e5-b11d-7d78772d3f22.png)

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81#%E8%B0%83%E8%AF%95%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90

**Comment by dualven** [comment]
@xia-chu 好的，谢谢。
现象：十次大概有偶尔一次可以播放，不能播放的时候，我tcpdump可以看到rtp在推流。我把dump目录设置后，看到相应的rtp文件，传上来给你帮忙分析下，谢谢！
文件30多M，我放这儿了
http://meshview.gwifi.com.cn:8891/topo/topodata/1.zip

**Comment by dualven** [comment]
@xia-chu 我对比了下，海康在推送RTP时，一起是udp 15060端口，而华平的udp端口，每次都在变化，
根据https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81#%E8%B0%83%E8%AF%95%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90
里面说的：如下，是不是有问题
![image](https://user-images.githubusercontent.com/2209534/173978599-948a4d21-9fc6-4ea8-950e-347380f6221d.png)

我看了下里面issue
https://github.com/ZLMediaKit/ZLMediaKit/issues/267

https://github.com/ZLMediaKit/ZLMediaKit/blob/8efb2da572cd6d963db27605995f746ca805e768/conf/config.ini
2020-11-19号的配置文件，其中的checkSource参数是否已经废弃了？另一个timeoutSec 我们默认设置的是15号。
![image](https://user-images.githubusercontent.com/2209534/173978716-d37daa58-f35f-4199-8b45-9d92e25a8ed4.png)

**Comment by xia-chu** [comment]
@dualven 这个设备的rtp确实有点问题：
<img width="1422" alt="图片" src="https://user-images.githubusercontent.com/11495632/174440005-e290be91-b292-42c9-a578-838a34c57482.png">

它推流不是从GOP开始处推流的，所以前几秒的数据都没用。你可以通过加大配置文件`wait_track_ready_ms`来优化对它的兼容性

**Comment by dualven** [comment]
wait_track_ready_ms  为啥，我修改这个参数从3000->10000,重启后，它自动又变成了3000？？？

**Comment by xia-chu** [comment]
说明被wvp托管了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dualven ***@***.***&gt;
发送时间: 2022年6月19日 18:05
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (Issue #1683)





 
wait_track_ready_ms  为啥，我修改这个参数从3000-&gt;10000,重启后，它自动又变成了3000？？？

**Comment by dualven** [comment]
我在wvp上修改了,不让他托管了；然后在zlm上修改了此参数，就可以了推出视频了！
谢谢！！
