### ISSUE TITLE
ts fragments are huge with 3mbps

### ISSUE THREAD

**Issue by xoraingroup** [ZLMediaKit/ZLMediaKit#1686]
Is there any possibility that a stream is sent via vmix to ZLMediaKit Server and hls configuration is following.

```
[hls]
fileBufSize=65536
filePath=/data/content/hls
segDur=5
segNum=3
segRetain=10
broadcastRecordTs=0
deleteDelaySec=60
```

and the bitrate of stream is 3mbps and you get 15 MB per ts fragment?

Also there is an option in [general] setting -> addMuteAudio=1

What does it do actually in terms of RTMP?

Thank you looking forward to hear for updates.

**Comment by xia-chu** [comment]
How many seconds does TS fragment really have?

**Comment by xia-chu** [comment]
Can you show me the m3u8 file content ?

**Comment by xoraingroup** [comment]
Right now i don't have the m3u8 file, but ts file was 3 seconds only. Is there any latency related issue that can increase the fragment size (which i am doubtful)? Or any other parameter like resolution which was at 1080p that could make the fragment so huge?

I will try to get the m3u8 file again - if i was able to reproduce it.

**Comment by xia-chu** [comment]
This problem is usually caused by abnormal video timestamp， or abnormal `gop` size

**Comment by xoraingroup** [comment]
And this GOP is configurable by encoders. What is the optimum gop size?

**Comment by xia-chu** [comment]
1-5 seconds recommended

**Comment by xoraingroup** [comment]
ok thank you, i will check and come back to you.
