### ISSUE TITLE
[BUG]: RTC推流SDP失败

### ISSUE THREAD

**Issue by jokbor** [ZLMediaKit/ZLMediaKit#1688]
### 现象描述

目前遇到使用/index/api/webrtc中PUSH的SDP交换信息会调用失败，而且一旦失败需要等很长时间才可以恢复重新PUSH，不知道是什么原因想会不会是Seesion已存在,想从这入手把原先的Session踢除后重新PUSH，但是目前遇到怎么把Session踢除的问题：
（1）用kick_session接口踢除，踢除的ID可以在对应getAllSession中查找，但是查找的条件目前只能用peer_ip和peer_port去查找，这个如果过多道网络后客户端压根不知道自己出去的IP是多少[getAllSession中还要sessionId为空现象]；
（2）想着第一个问题getAllSession比较难查找，想换个接口用getMediaList用对应的APP和Stream参数去筛选，但是查出来的Session ID和getAllSession中的无法对应（而且getMediaList中的记录很多重复），然后还发现getAllSession中的ID会经常变化，同一个推流的客户端端口也会变动；
想问下这个推流SDP失败怎么解决
 

<details>
<summary>getMediaList接口信息</summary>
<pre>
{
   "code" : 0,
   "data" : [
      {
         "aliveSecond" : 9,
         "app" : "live",
         "bytesSpeed" : 49644,
         "createStamp" : 1654582126,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "596-zlm_1",
            "local_ip" : "10.89.10.50",
            "local_port" : 8000,
            "peer_ip" : "10.89.10.2",
            "peer_port" : 61923
         },
         "originType" : 8,
         "originTypeStr" : "rtc_push",
         "originUrl" : "rtc://10.89.10.50:8443/live/te?app=live&stream=te&type=push&session=8-520",
         "readerCount" : 1,
         "schema" : "rtsp",
         "stream" : "te",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 0,
               "height" : 900,
               "ready" : true,
               "width" : 1440
            },
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 9,
         "app" : "live",
         "bytesSpeed" : 73595,
         "createStamp" : 1654582126,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "596-zlm_1",
            "local_ip" : "10.89.10.50",
            "local_port" : 8000,
            "peer_ip" : "10.89.10.2",
            "peer_port" : 61923
         },
         "originType" : 8,
         "originTypeStr" : "rtc_push",
         "originUrl" : "rtc://10.89.10.50:8443/live/te?app=live&stream=te&type=push&session=8-520",
         "readerCount" : 0,
         "schema" : "ts",
         "stream" : "te",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 0,
               "height" : 900,
               "ready" : true,
               "width" : 1440
            },
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 9,
         "app" : "live",
         "bytesSpeed" : 73883,
         "createStamp" : 1654582126,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "596-zlm_1",
            "local_ip" : "10.89.10.50",
            "local_port" : 8000,
            "peer_ip" : "10.89.10.2",
            "peer_port" : 61923
         },
         "originType" : 8,
         "originTypeStr" : "rtc_push",
         "originUrl" : "rtc://10.89.10.50:8443/live/te?app=live&stream=te&type=push&session=8-520",
         "readerCount" : 0,
         "schema" : "fmp4",
         "stream" : "te",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 0,
               "height" : 900,
               "ready" : true,
               "width" : 1440
            },
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 9,
         "app" : "live",
         "bytesSpeed" : 73595,
         "createStamp" : 1654582126,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "596-zlm_1",
            "local_ip" : "10.89.10.50",
            "local_port" : 8000,
            "peer_ip" : "10.89.10.2",
            "peer_port" : 61923
         },
         "originType" : 8,
         "originTypeStr" : "rtc_push",
         "originUrl" : "rtc://10.89.10.50:8443/live/te?app=live&stream=te&type=push&session=8-520",
         "readerCount" : 0,
         "schema" : "hls",
         "stream" : "te",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 0,
               "height" : 900,
               "ready" : true,
               "width" : 1440
            },
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 9,
         "app" : "live",
         "bytesSpeed" : 38997,
         "createStamp" : 1654582126,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "596-zlm_1",
            "local_ip" : "10.89.10.50",
            "local_port" : 8000,
            "peer_ip" : "10.89.10.2",
            "peer_port" : 61923
         },
         "originType" : 8,
         "originTypeStr" : "rtc_push",
         "originUrl" : "rtc://10.89.10.50:8443/live/te?app=live&stream=te&type=push&session=8-520",
         "readerCount" : 0,
         "schema" : "rtmp",
         "stream" : "te",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 0,
               "height" : 900,
               "ready" : true,
               "width" : 1440
            },
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            }
         ],
         "vhost" : "__defaultVhost__"
      }
   ]
}
</pre>
</details>

<details>
<summary>getAllSession接口信息（这里有sessionid为空的现象）</summary>
<pre>
第一次8-520正常能够对应上
{
   "code" : 0,
   "data" : [
      {
         "id" : "8-520",
         "local_ip" : "10.89.10.50",
         "local_port" : 8443,
         "peer_ip" : "10.89.10.2",
         "peer_port" : 52962,
         "typeid" : "class toolkit::TcpSessionWithSSL<class mediakit::HttpSession>"
      },
      {
         "id" : "",
         "local_ip" : "10.89.10.50",
         "local_port" : 8000,
         "peer_ip" : "10.89.10.2",
         "peer_port" : 61923,
         "typeid" : "class WebRtcSession"
      }
   ]
}
过段时候后刷新getAllSession接口后就又变化了，没有8-520了
{
   "code" : 0,
   "data" : [
      {
         "id" : "14-660",
         "local_ip" : "10.89.10.50",
         "local_port" : 8443,
         "peer_ip" : "10.89.10.2",
         "peer_port" : 52982,
         "typeid" : "class toolkit::TcpSessionWithSSL<class mediakit::HttpSession>"
      },
      {
         "id" : "",
         "local_ip" : "10.89.10.50",
         "local_port" : 8000,
         "peer_ip" : "10.89.10.2",
         "peer_port" : 61923,
         "typeid" : "class WebRtcSession"
      }
   ]
}
</pre>
</details>

**Comment by xia-chu** [comment]
webrtc sdp交换失败问题 应该跟你说的session无关，你可以提供下失败时zlm的日志

**Comment by jokbor** [comment]
@xia-chu 推流失败的两个现象
（1）SDP交换成功，但是icecandidatestate状态转变为failed：
[SDK.RTC.publish ] onconnectionstatechange --> connecting 
[SDK.RTC.publish ] onconnectionstatechange --> failed 
（2）刷新页面后重新推流提示stream ispublishing：
目前想请教下这两种情况下是用什么方式可以解决。
第二个失败的问题我这边想到的是用kick_session或kick_session去解决；
（1）用kick_session接口去精确的踢除，那先访问getAllSession方法拿到所有的session，然后再根据peer_ip和peer_port去查找对应的session，但是找到的session中typeid是class WebRtcSession时ID是空的无法进行踢的操作，kick_session接口就不允许传ID为空的，所以无法直接用 kick_session
（2）如果用批量kick_sessions接口调用的话用peer_ip去筛选，那就会把这台客户端上的所有推拉流都会踢掉（那这种方式一台客户机只允许推一路流）

**Comment by xia-chu** [comment]
你需要提供zlm的日志

**Comment by jokbor** [comment]
@xia-chu 推拉流失败的时间点在11:50分左右，遇到这种问题可以用什么方式解决并马上重新推拉
[2022-06-10_00.log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8875825/2022-06-10_00.log.zip)

**Comment by xia-chu** [comment]
<img width="849" alt="图片" src="https://user-images.githubusercontent.com/11495632/173005711-f9fa575a-582f-439b-b3d1-6f0a72810821.png">
你配置文件有错误

**Comment by xia-chu** [comment]
支持多个候选地址是2022-5-12才新增的，你的zlm版本是2022-4-23日的

**Comment by jokbor** [comment]
@xia-chu 推拉流失败的时间点在11:50分左右和下午2点以后，这份日志是本地调试的，上面那份发错了是服务端的（刚好帮忙解决了服务器中webrtc端口不生效的问题，就是这个多地址配置的）
[2022-06-10_03.log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8877396/2022-06-10_03.log.zip)

**Comment by xia-chu** [comment]
> 

日志提示超时，请确保10.89.10.50:8000端口可以访问

**Comment by xia-chu** [comment]
这个问题时Windows独有bug 今天应该已经修复了 你拉下最新代码测试下

**Comment by xia-chu** [comment]
跟这两个issue应该是一回事 #1444, #1645

**Comment by jokbor** [comment]
@xia-chu 好的，谢谢，我拉下代码再测试下，麻烦看下这个https://github.com/ZLMediaKit/ZLMediaKit/issues/1703，踢人这块你们是怎么处理的，有没有可以用app、stream、type去查询

**Comment by jokbor** [comment]
@xia-chu 刷新页面后推流失败的问题还是存在，现在就是可刷新的次数多了几次，以前是刷新1、2次就复现了，现在需要刷个5、6次，8，9次出现这个问题，还是在ice交换时报failed问题，时间点在下午3:40分后
[2022-06-13_err.log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8889080/2022-06-13_err.log.zip)

**Comment by xia-chu** [comment]
这个问题确实还存在
<img width="1138" alt="图片" src="https://user-images.githubusercontent.com/11495632/173536752-1f314d6c-b268-4d42-89d0-a7db1f739775.png">

**Comment by xia-chu** [comment]
这个问题优化了 应该彻底解决了 请更新zlmediakit和zltoolkit代码
