### ISSUE TITLE
[功能请求]视频水印

### ISSUE THREAD

**Issue by ydwxb** [ZLMediaKit/ZLMediaKit#1691]
建议新增生成视频流水印功能，设置添加文字或图片水印后，在视频流画面指定位置显示水印。

**Comment by qiaoro** [comment]
这个可以通过ffmpeg来实现，addFFmpegSource API ， ffmpeg_cmd_key

**Comment by qiaoro** [comment]
目前只能通过ffmpeg来实现， @xia-chu 之前有说过zlm不会支持，https://github.com/ZLMediaKit/ZLMediaKit/issues/639

**Comment by xia-chu** [comment]
是的 不会去直接只支持这种业务功能。
可以使用 addFFmpegSource api实现；现在也可以基于feature/transcode分支自己改改
