### ISSUE TITLE
客户端rtp推流如何检测服务端流失效问题

### ISSUE THREAD

**Issue by allenzhuyi** [ZLMediaKit/ZLMediaKit#1692]
我现在使用gb 28181 rtp推流方式，可以推送rtp流到流媒体服务器，但是请教下如果在网络异常或者重复等问题下如何检测这个流在服务器已经失效，因为使用rtp推流，我这边都是udp 方式进行单向推送，没有得到服务器的反馈信息，我这边的发送端如何检测反馈到服务端流已经失效，从而重新生成新的ssrc发起重新推送

**Comment by xia-chu** [comment]
目前zlm的udp多端口模式支持rtcp心跳，也就是rtp+1端口就是rtcp端口，你往rtcp端口发个udp打洞包(内容随意)；后面zlm就会源源不断向你的客户端发送rtcp；如果rtcp停了；zlm就收流结束了

**Comment by allenzhuyi** [comment]
好的，谢谢，发送rtcp的内容可以随意是吧，不一定要严格按照rtcp的报文类型

**Comment by xia-chu** [comment]
> 内容可以随意是吧，不一定要严格按照rtcp的报文类

嗯 只是用于打洞而已
