### ISSUE TITLE
[技术咨询] rtmp 推流url鉴权

### ISSUE THREAD

**Issue by GlodenBoy** [ZLMediaKit/ZLMediaKit#1694]
服务器开启了鉴权。

我在obs 中使用rtmp://x.x.x.x/live/0?token=2222222  这种方式推流，在Api中发现传过来的参数"params" 里始终是空的，没有办法获取到Url中的参数。

是我使用的方法不对吗？
![QQ图片20220608181413](https://user-images.githubusercontent.com/2329528/172592229-c35e80eb-2326-46a7-813c-fd95837937f8.jpg)
![QQ图片20220608181417](https://user-images.githubusercontent.com/2329528/172592247-fa9fd60e-b56b-4239-afe1-0d66114786b3.jpg)
![QQ图片20220608181422](https://user-images.githubusercontent.com/2329528/172592257-e3be00a1-fbaf-493e-918b-1ea4e923c009.jpg)

**Comment by xia-chu** [comment]
这个问题属于obs使用问题了，需要把 `0?token=33333` 放在`串流密钥`中。
