### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by sang8052** [ZLMediaKit/ZLMediaKit#1696]
### 现象描述

ZLMediaKit 自带的 HTTP 端口播放hls 格式流卡顿，无法正常播放的问题

### 如何复现?
这里在ZLMediaKit 的服务器上安装了nginx作为对比实验
使用固定的rtsp 格式的视频源    （视频流一）
用VLC 打开ZLMediaKit 自带的http 端口播放视频流 （视频流二）
地址:http://192.168.9.212:8080/hls/hikvision/live_vyhnnpp5-iw3c-w793-11ic-pqqe7iuvbtrk/hls.m3u8
用VLC打开ZLMediaKit 服务器上的nginx 中的视频流（视频流三）
地址:http://192.168.9.212/mediaserver/www/hls/hikvision/live_vyhnnpp5-iw3c-w793-11ic-pqqe7iuvbtrk/hls.m3u8
发现 视频流二打开速度非常的慢，且存在放几秒中断一次的现象
使用视频流三则没有问题

### 相关日志或截图

![SRPJUZ2XV_7YRP}3KTF%0Q0](https://user-images.githubusercontent.com/31176926/172594155-7cb470ba-de5a-4668-9566-57a5eba3085a.png)
为保护隐私，查看详细过程录像可留下收件邮箱

### 各种环境信息

centos 7.9.2009
ZLMediaKit 编译于 2022-06-07
nginx 1.20.1

**Comment by xia-chu** [comment]
如果使用nginx 没必要用http代理功能；可以把zlm的hls目录直接设置给nginx，nginx直接当做文件服务器即可

**Comment by sang8052** [comment]
> 如果使用nginx 没必要用http代理功能；可以把zlm的hls目录直接设置给nginx，nginx直接当做文件服务器即可

我不认同。我们的 nginx 服务 和 zlm 的服务 是在两台不同的服务器上

**Comment by xia-chu** [comment]
> > 如果使用nginx 没必要用http代理功能；可以把zlm的hls目录直接设置给nginx，nginx直接当做文件服务器即可
> 
> 我不认同。我们的 nginx 服务 和 zlm 的服务 是在两台不同的服务器上

用nginx代理应该也没问题 有人这么干啊

**Comment by xia-chu** [comment]
你说由于cookie问题 是不是nginx代理不支持cookie？

**Comment by sang8052** [comment]
> 你说由于cookie问题 是不是nginx代理不支持cookie？

由于zml 的hls 播放需要cookie 才能正常播放，如果通过vlc 或者跨域播放的话就会出现上面的问题，你可以留下邮箱，我发你一个视频你看看就知道了

**Comment by xia-chu** [comment]
github上可以直接发视频文件的 你发这就行了

**Comment by sang8052** [comment]
视频内容的问题，不方便在github 上发布

**Comment by xia-chu** [comment]
1213642868@qq.com
