### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by st-knight** [ZLMediaKit/ZLMediaKit#1697]
**咨询的功能模块**
- 点播record文件夹

**咨询的具体内容和问题**
- 我们点播文件比较多，而且复杂，有许多文件夹层级，但是里层文件夹内的视频文件无法用rtsp直接点播播放，会显示404 streaming not found。想问下怎么修改config文件才能使record文件夹下所有文件夹下内容都可以被点播播放。

**Comment by xia-chu** [comment]
不会啊 本来就支持多层文件夹

**Comment by st-knight** [comment]
请问支持挂载过去的文件夹么？我发现直接复制过去的没问题，但是挂载过去的文件夹就有问题，权限都开了，很奇怪

**Comment by st-knight** [comment]
错误日志显示no such stream:_defaultVhost_ XXXX XXXX/XXXX/XXXX, 好像吞了两个'/'变成空格了……

**Comment by st-knight** [comment]
或者是把后面XXXX/XXXX/XXXX.XXX当成一个整体了

**Comment by st-knight** [comment]
我用ffplay播放点播文件，用http://点播没问题，使用rtsp://点播就会报stream not found，太迷了

**Comment by xia-chu** [comment]
> 错误日志显示no such stream:_defaultVhost_ XXXX XXXX/XXXX/XXXX, 好像吞了两个'/'变成空格了……

请提供下当时你播放的url地址已经zlm的错误日志截图

**Comment by st-knight** [comment]
> > 错误日志显示no such stream:_defaultVhost_ XXXX XXXX/XXXX/XXXX, 好像吞了两个'/'变成空格了……
> 
> 请提供下当时你播放的url地址以及zlm的错误日志截图

运行命令"ffplay -rtsp_transport tcp rtsp://XXXXXXXXX/record/MMF/MF_h264_baseline_QCIF_128kps_15fps_AACLC.mp4"：
<img width="601" alt="Capture1_cmd1" src="https://user-images.githubusercontent.com/28889890/173724543-74de5ecb-9779-4f4d-b25a-b8f9250918f9.PNG">
![Capture2_cmd1](https://user-images.githubusercontent.com/28889890/173725342-986afa92-ab07-4cfd-9ce1-66552fdbbb4d.png)

运行命令"ffplay http://XXXXXXXXX/record/MMF/MF_h264_baseline_QCIF_128kps_15fps_AACLC.mp4":
<img width="599" alt="Capture1_cmd2" src="https://user-images.githubusercontent.com/28889890/173725023-039a5c5c-2b99-49bd-a5f2-efe4c3827b48.PNG">

**Comment by xia-chu** [comment]
这是你文件存放路径？ `record/MMF/MF_h264_baseline_QCIF_128kps_15fps_AACLC.mp4`

**Comment by st-knight** [comment]
> 这是你文件存放路径？ `record/MMF/MF_h264_baseline_QCIF_128kps_15fps_AACLC.mp4`

是的

**Comment by xia-chu** [comment]
这个问题很可能这个文件不被zlm支持 zlm无法正确解复用

**Comment by st-knight** [comment]
好的，非常感谢！
