### ISSUE TITLE
[技术咨询]Android端怎么开启Media 服务

### ISSUE THREAD

**Issue by sundaylol** [ZLMediaKit/ZLMediaKit#1701]
**咨询的功能模块**
- Android 端启用ZlMediaKit服务

**咨询的具体内容和问题**
- 这边想要在局域网内让安卓设备充当服务端，将HDMI IN获取到的Video Audio 推流过去，然后局域网内其他安卓设备来拉流。
- 想问下本框架怎么在安卓上编译运行，这边能提供一下思路吗，万分感谢。
- 
**注意事项**
-

**Comment by xia-chu** [comment]
zlm自带Android studio工程 里面就是启动一个MediaServer

**Comment by sundaylol** [comment]
> 

好的感谢

**Comment by xia-chu** [comment]
> > 
> 
> 这个android demo看着不是Client端吗

也有server端的

**Comment by deng-yc** [comment]
android  startDemo  启动服务之后，怎么关闭服务呢

**Comment by sundaylol** [comment]
> 

这边需求已实现，感谢

**Comment by sundaylol** [comment]
已实现

**Comment by Yemesoft** [comment]
> > > 
> > 
> > 
> > 这个android demo看着不是Client端吗
> 
> 也有server端的

请问Android服务端的地址在哪儿呀？没找到呢
