### ISSUE TITLE
[功能请求] RTSP拉流鉴权支持Digest SHA256

### ISSUE THREAD

**Issue by chengxuyuanyao** [ZLMediaKit/ZLMediaKit#1702]
**描述该功能的用处，可以提供相关资料描述该功能**
很多新的监控设备支持安全性更高的Digest SHA256 鉴权
![image](https://user-images.githubusercontent.com/41267112/173035746-0c1be0ca-943f-42fb-9bc9-d94fd7073a6e.png)

设备直连url:rtsp://admin:Smbtest00@10.10.20.177/media/video1

**Comment by xia-chu** [comment]
你给我一个局域网的URL 你让我咋测试？
