### ISSUE TITLE
[技术咨询]推流时icecandidatestate状态failed怎么解决

### ISSUE THREAD

**Issue by jokbor** [ZLMediaKit/ZLMediaKit#1703]
推流失败的两个现象
（1）SDP交换成功，但是icecandidatestate状态转变为failed：
[SDK.RTC.publish ] onconnectionstatechange --> connecting
[SDK.RTC.publish ] onconnectionstatechange --> failed
（2）刷新页面后重新推流提示stream ispublishing：
目前想请教下这两种情况下是用什么方式可以解决。

以下是服务日志，推拉流失败的时间点在上午11:50分左右和下午2点以后
[2022-06-10_03.log.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/8878028/2022-06-10_03.log.zip)

**Comment by xia-chu** [comment]
你这个问题跟 #1688 没啥区别吧
