### ISSUE TITLE
[技术咨询] 最新版代码是否已经支持ipv6了

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1706]
**咨询的功能模块**
- 网络

**咨询的具体内容和问题**
- 请问最新代码是否已经支持ipv6了，下载master分支代码就可以把？还要，是否有已经支持ipv6的官方docker镜像提供下载，还是需要自己基于master打镜像？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
已经全面支持
