### ISSUE TITLE
[BUG]: 前端浏览器播放时只有一帧画面的BUG

### ISSUE THREAD

**Issue by sang8052** [ZLMediaKit/ZLMediaKit#1708]
### 现象描述

当使用 RESTFUL 接口请求ZML 拉取RSTP 的视频流，得到code : 0 的正常响应后，立即的将生成的 HTTP-FLV 播放地址进行拼接处理后响应给前端播放器，前端播放器立即开始播放该视频流，就会出现视频卡住在第一帧画面的异常情况。

前端播放器使用 flv.js 和 EasyPlayer 进行了两次独立的测试，均 100% 复现该问题

### 如何复现?
注意，本现象的复现的前提条件是，使用RESTFUL 接口调用 ZML 去拉海康的 RTSP 的视频流，并转码成 HTTP-FLV 格式在前端播放
前端播放器一定要在收到来自服务器响应的RESTFUL 数据后立即播放，才会触发这个BUG
如果是手动复制（设置）播放地址，或在收到数据后，加上2-3 s 的延迟再去播放这个bug ，就不会出现这个问题

**Comment by xia-chu** [comment]
有测试过vlc、ffplay吗？

**Comment by sang8052** [comment]
没有，且我没有办法测试。我很难在请求 RESTFUL 后立刻执行 vlc 或 ffplay 拉流命令

**Comment by xia-chu** [comment]
哦 你说的对 不过你可以先播放 后下发addStreamProxy指令给zlm；因为zlm支持先播放后拉流

**Comment by xia-chu** [comment]
这个问题跟时间戳关系很大 rtsp时间戳后面加了ntp时间戳，另外hls时间戳改成绝对时间戳了

**Comment by Doyle-net** [comment]
> 这个问题跟时间戳关系很大 rtsp时间戳后面加了ntp时间戳，另外hls时间戳改成绝对时间戳了

那应该怎么解决这一问题呢？

**Comment by yu1183688986** [comment]
> > 这个问题跟时间戳关系很大 rtsp时间戳后面加了ntp时间戳，另外hls时间戳改成绝对时间戳了
> 
> 那应该怎么解决这一问题呢？

我也遇到了同样的问题，我修改了一下配置，临时解决了
```
#全局的时间戳覆盖开关，在转协议时，对frame进行时间戳覆盖
#该开关对rtsp/rtmp/rtp推流、rtsp/rtmp/hls拉流代理转协议时生效
#会直接影响rtsp/rtmp/hls/mp4/flv等协议的时间戳
#同协议情况下不影响(例如rtsp/rtmp推流，那么播放rtsp/rtmp时不会影响时间戳)
modifyStamp=0
```

**Comment by xia-chu** [comment]
rtsp的时间戳跳变太严重了 才会导致这个问题；因为rtsp需要rtcp去生成ntp时间戳；但是很多rtsp设备并不规范；而且rtcp发送的太晚 前面一部分rtp ntp时间戳生成是根据服务器当前系统时间戳做参考的；所以会有偏差

**Comment by x-x-p** [comment]
同样也有这个问题。 当视频流正在代理中时， flv可以顺利播放； 当视频流没有在代理中， flv先播放后拉流代理时， flv视频卡住在第一帧画面。

**Comment by x-x-p** [comment]
将这个版本中的Stamp重新添加到代码中之后， flv播放顺畅得多了。

[Http-FLV: http-flv直播采用绝对时间戳并支持las](https://github.com/ZLMediaKit/ZLMediaKit/commit/dce6b27f4fd09b1ecd837d7ee888ddf7bed50368)

**Comment by xia-chu** [comment]
> 将这个版本中的时间修整理器Stamp重新添加到代码中之后， flv播放顺畅得多了。
> 
> [Http-FLV: http-flv直播采用绝对时间戳并支持las](https://github.com/ZLMediaKit/ZLMediaKit/commit/dce6b27f4fd09b1ecd837d7ee888ddf7bed50368)

嗯 不过应该还有其他更优雅的办法解决这个问题 周末我改下试试

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by Doyle-net** [comment]
> > 将这个版本中的时间修整理器Stamp重新添加到代码中之后， flv播放顺畅得多了。
> > [Http-FLV: http-flv直播采用绝对时间戳并支持las](https://github.com/ZLMediaKit/ZLMediaKit/commit/dce6b27f4fd09b1ecd837d7ee888ddf7bed50368)
> 
> 嗯 不过应该还有其他更优雅的办法解决这个问题 周末我改下试试

这个功能修改了嘛？

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by Doyle-net** [comment]
> > > 这个问题跟时间戳关系很大 rtsp时间戳后面加了ntp时间戳，另外hls时间戳改成绝对时间戳了
> > 
> > 
> > 那应该怎么解决这一问题呢？
> 
> 我也遇到了同样的问题，我修改了一下配置，临时解决了
> 
> ```
> #全局的时间戳覆盖开关，在转协议时，对frame进行时间戳覆盖
> #该开关对rtsp/rtmp/rtp推流、rtsp/rtmp/hls拉流代理转协议时生效
> #会直接影响rtsp/rtmp/hls/mp4/flv等协议的时间戳
> #同协议情况下不影响(例如rtsp/rtmp推流，那么播放rtsp/rtmp时不会影响时间戳)
> modifyStamp=1
> ```
我修改modifyStamp为1时，部分视频播放出现花屏。（原始流是hls）
