### ISSUE TITLE
[功能改进] 新增录像

### ISSUE THREAD

**Issue by mrlaozeng** [ZLMediaKit/ZLMediaKit#1710]
建议在录像的时候增加一个自定义标识用于生成录像文件名,可对同一个流同时开启多个录像

**Comment by xia-chu** [comment]
可以指定文件路径 但是不能指定文件名 因为录制是要切片的，最多让你指定文件名前缀

**Comment by xia-chu** [comment]
而且你可以在录制hook中修改文件名的 所以你的需求其实不存在

**Comment by mrlaozeng** [comment]
意思是对同一个流同时进行多个录像这种情况,比如有个全局录像,另外又多个分段录像这种

**Comment by xia-chu** [comment]
全局录像？ 你知不知道大mp4文件在close时要写索引？这些索引在写入文件时非常慢，并且在写索引前这些数据都在内存中，能存会一直增长

**Comment by xia-chu** [comment]
> 大佬 可能是我没表述清楚,我的意思是 在enable_mp4的同时 可以再调用录像接口 开启新的录像并且不影响原来正在录制的mp4

非标准功能需要你自己开发 我们不会去实现这种奇怪的功能的

**Comment by mrlaozeng** [comment]
好的  感谢大佬的回答

**Comment by xia-chu** [comment]
> 大哥请问下hook中怎样修改文件名？我希望通过api传入我自己的文件名前辍，然后调用结束录像api的时候返回该文件的具体播放路径应该要怎样修改，希望大佬指点

你可以hook到本机服务 你在本机修改文件名即可
