### ISSUE TITLE
收不到链接尾部的参数

### ISSUE THREAD

**Issue by zh19900725** [ZLMediaKit/ZLMediaKit#1716]
### 现象描述
前段时间更新了最新的ZLMediakit发现有点问题了，
使用以下链接请求ZLMediaKit，配置了on_stream_not_found，结果发现params是空的，正常应该params=ticket=db5ba84d-aca6-4369-a4bd-63a8779349d8

由于params是空的导致hook里业务鉴权失败

rtmp://192.168.42.28:1935/history/300000000000209095_50173839?ticket=db5ba84d-aca6-4369-a4bd-63a8779349d8

### 如何复现?
以下是我拉取代码的commit id
commit df9a9649b08bbc4ba2954b441ca07468cad27dbf (grafted, HEAD -> master, origin/master, origin/HEAD

配置on_stream_not_found后，使用rtmp://192.168.42.28:1935/history/300000000000209095_50173839?ticket=db5ba84d-aca6-4369-a4bd-63a8779349d8
看看能否收到ticket

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
[2022-06-14 17:26:18.308] [INFO ][1655198778307-nCo4Fv] [http-nio-9192-exec-10] [com.tencent.common.aop.ParamLogAspect beforeMethod 40] - request path: /index/hook/on_stream_not_found ,request args: [{app=rtp, schema=rtmp, vhost=__defaultVhost__, mediaServerId=192.168.42.28, port=56848, stream=300000000000209095_50173839, ip=127.0.0.1, id=10147-48, params=}]
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
[hook]
#在推流时，如果url参数匹对admin_params，那么可以不经过hook鉴权直接推流成功，播放时亦然
#该配置项的目的是为了开发者自己调试测试，该参数暴露后会有泄露隐私的安全隐患
admin_params=secret=secret=b125240d-fbab-47ee-a114-f8debfef2bbe
#是否启用hook事件，启用后，推拉流都将进行鉴权
enable=1
#播放器或推流器使用流量事件，置空则关闭
on_flow_report=http://127.0.0.1:9192/index/hook/on_flow_report
#访问http文件鉴权事件，置空则关闭鉴权
on_http_access=http://127.0.0.1:9192/index/hook/on_http_access
#播放鉴权事件，置空则关闭鉴权
on_play=http://127.0.0.1:9192/index/hook/on_play
#推流鉴权事件，置空则关闭鉴权
on_publish=http://127.0.0.1:9192/index/hook/on_publish
#录制mp4切片完成事件
on_record_mp4=http://127.0.0.1:9192/index/hook/on_record_mp4
# 录制 hls ts 切片完成事件
on_record_ts=https://127.0.0.1:9192/index/hook/on_record_ts
#rtsp播放鉴权事件，此事件中比对rtsp的用户名密码
#on_rtsp_auth=https://127.0.0.1/index/hook/on_rtsp_auth
#rtsp播放是否开启专属鉴权事件，置空则关闭rtsp鉴权。rtsp播放鉴权还支持url方式鉴权
#建议开发者统一采用url参数方式鉴权，rtsp用户名密码鉴权一般在设备上用的比较多
#开启rtsp专属鉴权后，将不再触发on_play鉴权事件
#on_rtsp_realm=https://127.0.0.1/index/hook/on_rtsp_realm
#远程telnet调试鉴权事件
#on_shell_login=https://127.0.0.1/index/hook/on_shell_login
#直播流注册或注销事件
#on_stream_changed=https://127.0.0.1/index/hook/on_stream_changed
#无人观看流事件，通过该事件，可以选择是否关闭无人观看的流。配合general.streamNoneReaderDelayMS选项一起使用
on_stream_none_reader=http://127.0.0.1:9192/index/hook/on_stream_none_reader
#播放时，未找到流事件，通过配合hook.on_stream_none_reader事件可以完成按需拉流
on_stream_not_found=http://127.0.0.1:9192/index/hook/on_stream_not_found
#服务器启动报告，可以用于服务器的崩溃重启事件监听
on_server_started=http://127.0.0.1:9192/index/hook/on_server_started
#server保活上报
on_server_keepalive=http://127.0.0.1:9192/index/hook/on_server_keepalive
#hook api最大等待回复时间，单位秒
timeoutSec=10
#keepalive hook触发间隔,单位秒，float类型
alive_interval=10.0</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:df9a9649b08bbc4ba2954b441ca07468cad27dbf
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你什么什么客户端？

**Comment by wasphin** [comment]
日志里看 app 是 rtp, 这是误识别为 gb 流了?

**Comment by xia-chu** [comment]
> 日志里看 app 是 rtp, 这是误识别为 gb 流了?

不会的 除了`record`是特殊app，其他都不是；`rtp` app只是为了区别rtp推流而已，因为rtp推流没法指定app

**Comment by zh19900725** [comment]
> 

我用B站给的flv播放器，播放器是没有问题的，另外这里日志显示rtp 而我用的live 是因为我先推了rtp , 再用rtp 推了一路拉流代理，之前一直没问题，最近更新代码后发现不行了

**Comment by zh19900725** [comment]
> > 日志里看 app 是 rtp, 这是误识别为 gb 流了?
> 
> 不会的 除了`record`是特殊app，其他都不是；`rtp` app只是为了区别rtp推流而已，因为rtp推流没法指定app

我知道原因了，是我添加拉流代理时触发了on_stream_not_found
