### ISSUE TITLE
[技术咨询] WebRTC按需拉流

### ISSUE THREAD

**Issue by jim-king-2000** [ZLMediaKit/ZLMediaKit#1717]
我们阅读了按需拉流的文档：<https://github.com/ZLMediaKit/ZLMediaKit/wiki/ZLMediaKit%E5%AE%9E%E7%8E%B0%E6%8C%89%E9%9C%80%E6%8B%89%E6%B5%81>，我们还想了解一下，如果我们在播放端使用WebRTC（源端仍然是RTSP），是否也能够拥有按需拉流的功能？

**Comment by xiongguangjie** [comment]
可以

**Comment by jim-king-2000** [comment]
好的。十分感谢。
