### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by imquanke** [ZLMediaKit/ZLMediaKit#1718]
**咨询的功能模块**
- 部署

**咨询的具体内容和问题**
- 如何集群化部署

**Comment by xiongguangjie** [comment]
查看配置文件

**Comment by imquanke** [comment]
嗯，昨天已经找到了。感谢

**Comment by xia-chu** [comment]
下次issue记得加标题 否则直接关闭了哈

**Comment by imquanke** [comment]
> 

查看配置文件里面的cluster部分，有将怎么集群化。我也是刚刚接触视频服务，我的理解是集群化部分分为源站和边沿站，可以按照单机部署方式，部署几台机器，作为源站集群；同样操作部署边沿站集群，然后边沿站里面的配置文件，cluster配置源站的ip列表；源站用于接受推流，边沿站对接播放请求，用于拉流；边沿站可以用nginx做一层负载均衡。

**Comment by jiangzhoukim** [comment]
大佬，不介意的话加个联系方式一起探讨问题，还有一些问题想请教

**Comment by Logers-kcm** [comment]
@imquanke @xiongguangjie 大佬们，我三台机器，一台源站两台边沿站，请问如何负载均衡到两台边沿站上
