### ISSUE TITLE
[兼容华为录像rtsp协议]

### ISSUE THREAD

**Issue by Firefly4H** [ZLMediaKit/ZLMediaKit#1719]
目前华为录像rtsp协议出现一问多答的情况，比如：setup 音频的时时候是1问3答，希望可以做下兼容！
此问题华为知道，他们也对接了很多其他公司的视频均是此做法。

抓包如下：
![QQ图片20220613105827](https://user-images.githubusercontent.com/32868079/173977163-7d45519e-818c-4836-a1d1-fc5830e65836.jpg)
![QQ图片20220613105836](https://user-images.githubusercontent.com/32868079/173977186-1c4d9276-bca1-4239-978d-bc03acef7d0a.jpg)

希望最终达到华为录像视频可以正常播放，感谢！。

**Comment by xiongguangjie** [comment]
给出公网rtsp 地址，否则没法调试

**Comment by Firefly4H** [comment]
> 给出公网rtsp 地址，否则没法调试

不方便公开，可以在qq群里@武汉-墨明棋妙

**Comment by monktan89** [comment]
starred都不给一个，这个工作很难展开啊

**Comment by Firefly4H** [comment]
此问题已经解决，不需要做兼容。此问题由于获取华为rtsp录像时clietType参数不正确导致  =0为不标准协议，=1为标准协议。

**Comment by Firefly4H** [comment]
此问题已经解决，不需要做兼容。此问题由于获取华为rtsp录像时clietType参数不正确导致 =0为不标准协议，=1为标准协议。
