### ISSUE TITLE
[BUG]: 调整后的ffmpeg cmake脚本无法正确找到libswscale

### ISSUE THREAD

**Issue by NetArkDL** [ZLMediaKit/ZLMediaKit#1720]
### 现象描述
调整后的cmake脚本，在执行时会查找ffmpeg相关的库，但是无法正确找到libswscale，导致无法打开ffmpeg开关。我的ffmpeg已经正确安装，并且一直可以正常使用，该问题在更新代码后出现。

### 如何复现?
拉取最新代码，执行cmake ..

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_MMSG_HDR
-- Performing Test HAVE_MMSG_HDR - Success
-- Looking for sendmmsg
-- Looking for sendmmsg - found
-- Looking for recvmmsg
-- Looking for recvmmsg - found
-- -D__STDC_FORMAT_MACROS
-- 编译类型:Release
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Git version is ::2022/06/16-00:21:19
-- found library:/usr/lib/x86_64-linux-gnu/libavutil.so
-- found library:/usr/lib/x86_64-linux-gnu/libavcodec.so
-- found library:/usr/lib/x86_64-linux-gnu/libswresample.so
CMake Warning at CMakeLists.txt:294 (message):
  ffmpeg相关功能未找到

-- found library:/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so,ENABLE_OPENSSL defined
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed
-- ENABLE_MP4 defined
-- ENABLE_RTPPROXY defined
-- ENABLE_HLS defined
-- set_file_group /mnt/hgfs/code/ZLMediaKit/3rdpart/ZLToolKit/src 75
-- set_file_group /mnt/hgfs/code/ZLMediaKit/src 224
CMake Warning at CMakeLists.txt:485 (message):
  srtp未找到, webrtc相关功能打开失败

-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- add c api tester:h264_media_server
-- add c api tester:httpclient
-- add c api tester:pusher
-- add c api tester:server
-- add c api tester:websocket
-- add test:bom
-- add test:tab
-- add test:test_bench_proxy
-- add test:test_bench_pull
-- add test:test_bench_push
-- add test:test_httpApi
-- add test:test_httpClient
-- add test:test_pusher
-- add test:test_pusherMp4
-- add test:test_rtp
-- add test:test_server
-- add test:test_sortor
-- add test:test_wsClient
-- add test:test_wsServer
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/hgfs/code/ZLMediaKit/buildr
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:Ubuntu18
* **硬件信息**:vmware虚拟机
* **其他需要补充的信息**:

**Comment by NetArkDL** [comment]
感谢您的答复，您可以看下cmake执行日志，我有上传，我的系统里是有libswscale的。我也查了一下，也有人在其他项目上出现过find_library找不到库的情况，后来改用了其他方法。
以下是我系统上ffmpeg的信息：
ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100

**Comment by longzhu123** [comment]
我也遇到了这个错误
操作系统: Ubuntu 20.0.4
GCC版本: 9.4.0

执行cmake 出现以下错误
![D)BA9LI@ANO8EQP94Z9QUU1](https://user-images.githubusercontent.com/22900125/174115300-65f60d1a-7c34-46fa-b579-aa1feca590dc.png)

make -j4  出现以下错误
![H8 BHMV}K9Z57DC6U0)T14F](https://user-images.githubusercontent.com/22900125/174115479-e8e33d71-340d-4227-89ae-2ab22154ee1c.png)

**Comment by NetArkDL** [comment]
> > 感谢您的答复，您可以看下cmake执行日志，我有上传，我的系统里是有libswscale的。我也查了一下，也有人在其他项目上出现过find_library找不到库的情况，后来改用了其他方法。 以下是我系统上ffmpeg的信息： ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04) configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared libavutil 55. 78.100 / 55. 78.100 libavcodec 57.107.100 / 57.107.100 libavformat 57. 83.100 / 57. 83.100 libavdevice 57. 10.100 / 57. 10.100 libavfilter 6.107.100 / 6.107.100 libavresample 3. 7. 0 / 3. 7. 0 libswscale 4. 8.100 / 4. 8.100 libswresample 2. 9.100 / 2. 9.100 libpostproc 54. 7.100 / 54. 7.100
> 
> 你是怎么解决的呢？

还没有解决呢

**Comment by NetArkDL** [comment]
我重新在另一台Ubuntu20上重复此操作，问题依旧

**Comment by xia-chu** [comment]
那个编译报错需要你更新下ZLToolKit源码

**Comment by longzhu123** [comment]
> 那个编译报错需要你更新下ZLToolKit源码

ZLToolKit是重新更新过了吗？ 我是按照快速开始一步步走的

**Comment by xia-chu** [comment]
昨天更新了点

**Comment by longzhu123** [comment]
> 昨天更新了点

好，那我重新走一遍全流程

**Comment by NetArkDL** [comment]
> 不会吧 我这都能找到libswscale啊

经过多番尝试任然不能启用ffmpeg，如果不启用的话，会对什么功能造成影响？
还有什么办法能启用ffmpeg吗？

**Comment by longzhu123** [comment]
> 昨天更新了点
重新跑了一遍还是出现编译的问题

**Comment by Loafter-l** [comment]
> 昨天更新了点

我这里库找到了,但是遇到了编译错误
![1](https://user-images.githubusercontent.com/76397588/174263781-81d266a6-a34e-4017-a0e9-9bba5dbb6be8.png)
![2](https://user-images.githubusercontent.com/76397588/174263801-2dcbc712-7112-4844-947e-63a8f47adcb6.png)

**Comment by lovederh** [comment]
遇到同样问题, 我是在全新的ubuntu20.04 上从头开始安装出现的编译错误
![image](https://user-images.githubusercontent.com/8230698/174417189-2b56d2f9-52d8-42b9-8e7b-8c709085767e.png)

**Comment by lovederh** [comment]
有人解决了吗?

**Comment by xia-chu** [comment]
我改成默认关闭ffmpeg了 请重新拉一遍代码编码吧 记住先删除所有缓存
