### ISSUE TITLE
[BUG]: 最新代码在win10环境下编译出现错误

### ISSUE THREAD

**Issue by inprise1980** [ZLMediaKit/ZLMediaKit#1724]
### 现象描述

拉取最新代码，在window10环境下，使用visual studio2022进行编译出现错误。

### 如何复现?
拉取最新代码，按步骤进行编译，就可复现

### 相关日志或截图
![image](https://user-images.githubusercontent.com/35751700/174219315-5380b7e3-1f0b-475b-8e4a-be64407eca89.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 各种环境信息

  * 操作系统及版本, 如: Windows 10,
  * 编译工具：visual studio 2022

**Comment by xia-chu** [comment]
你要选择MediaServer工程编译并启动

**Comment by inprise1980** [comment]
这个问题应该是跟群里说的有个文件编码问题吧，现在是可以了。谢谢。
