### ISSUE TITLE
[BUG]:国标摄像头录制视频生成文件夹层级有误

### ISSUE THREAD

**Issue by liangliang996** [ZLMediaKit/ZLMediaKit#1726]
### 现象描述
国标设备进行录像，app为rtp，stream为21010100001320000005/21010400491320000099  file_path为/zlmediakit/www/record/rtp/21010100001320000005/21010400491320000099/2022-06-17/07-17-13.mp4
，生成的文件夹判定stream中的“/”为一个层级，所以结果就是文件夹多了一层，导致与其他设备结构不符
### 相关日志或截图
![image](https://user-images.githubusercontent.com/50125424/174249161-0fe3d9f7-24ee-4198-9b12-1df7eaa4e469.png)
![Uploading 微信图片_20220617153523.png…]()

**Comment by xiongguangjie** [comment]
你这个stream 不能带有/与其他冲突了怎么办（app与streamid）

**Comment by liangliang996** [comment]
谢谢提醒，原本以为这个是zlmediakit自动生成的，原来是我这边传过去的，感谢，问题已解决
