### ISSUE TITLE
我开启hook后，转码的接口就请求不成功了，是怪哪里没有鉴权？？

### ISSUE THREAD

**Issue by QiaoMaiMian** [ZLMediaKit/ZLMediaKit#1727]
![JR91%XMR)UMZ8BU}W XLO}X](https://user-images.githubusercontent.com/18134644/174255564-1ab15425-2b71-4653-9311-dd461d265d27.png)
![YU$NWPAZR O047@XLNBP8RW](https://user-images.githubusercontent.com/18134644/174255614-9edee992-98f2-4390-a5ae-be449f5090a2.png)
![VIC76)J$O3`7NNELT$1$1N](https://user-images.githubusercontent.com/18134644/174255633-efa3a1db-b4bc-44f1-8e24-80eb5773faf8.png)

**Comment by xiongguangjie** [comment]
webhook 的on_publish 要按照规定允许推流呀

**Comment by xia-chu** [comment]
如果你不懂某个特性 那么你就别开启，否则认真读下wiki；按照wiki去做。而不是在什么都不清楚的情况下尝试某项功能
