### ISSUE TITLE
[技术咨询] mac  本地docker启动zlmedia 后,报 T MediaServer[1-event poller 3] HttpSession.cpp:124 onError | 275683570432(172.18.0.1:58406) session timeout 错误。

### ISSUE THREAD

**Issue by sunchunfeng** [ZLMediaKit/ZLMediaKit#1729]
1.有人知道这个参数（inputFrame | cached frame of track(H264) is too much,）怎么优化吗？
W MediaServer[1-event poller 3] RtpProcess.cpp:119 inputFrame | cached frame of track(H264) is too much, now dropped

2.还有mac  本地docker启动zlmedia 后,报 T MediaServer[1-event poller 3] HttpSession.cpp:124 onError | 275683570432(172.18.0.1:58406) session timeout 错误。

**Comment by xiongguangjie** [comment]
1，这个是h264的关键信息没有解析到，如pps sps 或者I帧没有解析到
2，这个session timeout 忽略，是tcp 建立，超时导致的

**Comment by xia-chu** [comment]
这个是on_publish hook超时导致，我改进了日志提示

**Comment by xia-chu** [comment]
#此镜像为github持续集成自动编译推送，跟代码(master分支)保持最新状态
docker run -id -p 1935:1935 -p 8080:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master
