### ISSUE TITLE
[技术咨询]rtsp推流，然后使用VLC播放器播放对应url，不成功

### ISSUE THREAD

**Issue by imquanke** [ZLMediaKit/ZLMediaKit#1731]
**咨询的功能模块**
-推流及播放

**咨询的具体内容和问题**
- 部署并启动应用后，按照wiki的推流测试，使用rtsp推流，日志中显示注册成功后，马上又注销了；使用VLC播放器播放对应url不成功

![image](https://user-images.githubusercontent.com/39719966/174520044-ceb7b8b6-d881-4e7d-81a8-8190ae293d39.png)

**Comment by xia-chu** [comment]
日志不是写了 你推流器主动断开的吗

**Comment by imquanke** [comment]
我这边想通过推流本地的mp4文件，然后再用播放器打开对应视频文件。不能通过wiki的推流测试命令，然后再用VLC播放器访问对应url实现么？

**Comment by xia-chu** [comment]
可以啊 但是你文件太短了 推流完了吧？

**Comment by xia-chu** [comment]
ffmpeg? 加上-stream_loop -1

**Comment by imquanke** [comment]
按照你的指导，修改推流命令为
ffmpeg -stream_loop -1 -re -i "/root/test.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test
现在日志没有输出媒体注销，但是用VLC播放对应地址（rtsp://116.198.38.96:554/live/test），仍然提示
![image](https://user-images.githubusercontent.com/39719966/174540509-36a9330a-0f40-4d71-920a-610cf6f17344.png)
在浏览器上输入116.198.38.96，在对应live/test目录下的文件如图
![image](https://user-images.githubusercontent.com/39719966/174540680-c56e07fd-c093-42ed-96a5-bb37626ae278.png)
![image](https://user-images.githubusercontent.com/39719966/174540733-cd7c2a27-2c7d-4149-991a-3c0165af49ac.png)

**Comment by xia-chu** [comment]
公网播放 你udp端口有没映射 怎么播放？ vlc默认rtp over udp播放的。

**Comment by imquanke** [comment]
好的，明白了，感谢！

**Comment by xia-chu** [comment]
建议rtp over tcp模式 这样才不会丢包

**Comment by imquanke** [comment]
好的，感谢！
