### ISSUE TITLE
[BUG]: 无法录制视频以及多VLC客户端不能独立播放视频

### ISSUE THREAD

**Issue by wentao786** [ZLMediaKit/ZLMediaKit#1732]
### 现象描述

目前发现两个问题：
1、RTMP推流时，使用http startRecord接口不能录制视频，经单步调试，发现_track_map的size为0，
2、播放录制的视频时，多个客户端调用rtmp://127.0.0.1:1935/record/sample.mp4时，所有的vlc客户端播放显示相同的内容，一个客户端不能独立显示内容，而且不能seek到指定的文件位置播放。

能不能帮忙解释下，谢谢！

**Comment by xia-chu** [comment]
你自己推的流 你不知道？

**Comment by wentao786** [comment]
ffmpeg推流看起来一切都是正常的

**Comment by xia-chu** [comment]
> ffmpeg推流看起来一切都是正常的

所以你就不知道把命令粘贴上来？

**Comment by wentao786** [comment]
可以了，非常感谢
怎么才能请你喝杯咖啡？ ~_~

**Comment by xia-chu** [comment]
gitee官方镜像又捐钱入口 你可以在那里捐赠
