### ISSUE TITLE
对http功能扩展，支持http包头配置，跨域，SharedArrayBuffer容许等[功能请求]

### ISSUE THREAD

**Issue by muye-xx** [ZLMediaKit/ZLMediaKit#1736]
**描述该功能的用处，可以提供相关资料描述该功能**
可配置http请求，header安全感字段。
比如：
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
Access-Control-Allow-Origin *
Access-Control-Allow-Headers 

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
 目前浏览器对敏感操作越来越严格，前端跨域，内存共享，多线程等等，都需要服务器端，添加容许，nginx web服务代理属性天然支持此功能。流媒体服务必然要和web项目搭配使用，跨域，内存共享，多线程这种问题必然会遇到，如果支持这些配置功能，nginx等中间环节可以省掉，方便不少。

**描述你期望实现该功能的方式和最终效果**
只是一个小小的建议，没有啥预期效果，能支持当然最好不是。

**Comment by xia-chu** [comment]
你说的这4个http都是固定的吗？

**Comment by xia-chu** [comment]
有设置跨域的，不过要在请求中有`Origin`头：
<img width="1074" alt="图片" src="https://user-images.githubusercontent.com/11495632/174761698-1c1bff1d-bb53-4f76-a23b-9a214e73885a.png">
