### ISSUE TITLE
[技术咨询]startRecord

### ISSUE THREAD

**Issue by zhujiarun** [ZLMediaKit/ZLMediaKit#1743]
录制视频
前提：zlmediakit通过rtsp(GB28181获得)去NVR拉流
但是，我在录制流，为啥会触发无人观看啊

**Comment by xia-chu** [comment]
在zlm中 录制不算观看 算旁路

**Comment by zhujiarun** [comment]
> 在zlm中观察不到算算

那请问在您的设计中，我录制的流，如何不被【无人观看】给停掉，同时还能停掉正常无人观看的流

**Comment by xia-chu** [comment]
> 

要稍微改下代码

**Comment by zhujiarun** [comment]
> 
> 要稍微改下代码 把录制当做观看者

那，大哥，咋改啊 ,你懂的

**Comment by zhujiarun** [comment]
> star都不给个 你让我很难办



> star都不给个 你让我很难办

你等着，我让我公司的人都给你点个赞

**Comment by xia-chu** [comment]
已经实现

**Comment by zhujiarun** [comment]
> 已经实现

👍
