### ISSUE TITLE
[技术咨询] 使用硬件设备通过RTMP推流至ZLMediaKit，然后通过浏览器WebRtc拉流，视频正常但无声音。

### ISSUE THREAD

**Issue by hehui0123** [ZLMediaKit/ZLMediaKit#1744]
### 推送如下图 ：
![111111111111111111](https://user-images.githubusercontent.com/22097429/175489711-8235fbd9-4868-4fe5-9873-8edb9e8a1168.jpg)
![22222222222222222](https://user-images.githubusercontent.com/22097429/175489738-04cb4d2f-7957-4b23-b649-0e8e27f39887.jpg)

### 目前的问题是： 
   使用VCL播放器播放 rtmp://192.168.88.162/live/test ，视频音频一切正常
   但是使用 浏览器打开 https://192.168.88.162/webrtc， 视频正常，无声音 。

### 期望
   WebRtc有声音。

**Comment by xia-chu** [comment]
webrtc不支持aac 你要换g711

**Comment by mtdxc** [comment]
你可以试试两个transcode分支😁

**Comment by hehui0123** [comment]
> 你可以试试两个transcode分支😁
都试了，还是不行，有没有什么要特别注意的地方？ 以下是我使用的编译指令：
 cmake .. -DENABLE_WEBRTC=true  -DENABLE_FFMPEG=on -DOPENSSL_ROOT_DIR=/usr/local/ssl  -DOPENSSL_LIBRARIES=/usr/local/ssl/lib

**Comment by hehui0123** [comment]
终于可以了，感谢各位。
 以下是我编译的过程： 

 **webrtc 没有声音的解决方案：** 
 
 git  clone  https://github.com/videolan/x265.git
 cd  x265/build
 cmake ../source
 make
 sudo make install
 cd  ../..
 
 sudo apt-get   install    nasm   yasm
 git clone https://gitee.com/xia-chu/FFmpeg.git
 cd  FFmpeg
 ./configure --enable-libx265 --enable-gpl
 make
 sudo make install
 
 
**然后开始ZLMediaKit的编译
我使用的是 feature/transcode2 分支，请确保编译之前切换到这个分支**

 cd ZLMediaKit
 git submodule update --init
 mkdir build
 cd build
 cmake .. -DENABLE_WEBRTC=true  -DENABLE_FFMPEG=on -DOPENSSL_ROOT_DIR=/usr/local/ssl  -DOPENSSL_LIBRARIES=/usr/local/ssl/lib 
 cmake --build . --target MediaServer

**成功之后就可以运行了**
