### ISSUE TITLE
[技术咨询] rtsp 拉流 proxy 方式如何使用

### ISSUE THREAD

**Issue by jeickey** [ZLMediaKit/ZLMediaKit#1750]
**咨询的功能模块**
- rtsp 拉流 proxy , 翻了一遍issue没找到此话题，只好咨询一下

**咨询的具体内容和问题**
- 相机扛的 rtsp 连接数有限, 想以media server为中转作拉流代理, 是否已经支持这样使用？ 但是rtsp 的 url 及参数格式应该怎么写呢？ 请教 : 

![image](https://user-images.githubusercontent.com/11632658/175761246-8a8c19b6-0020-4b72-b114-e50628569c6a.png)

**Comment by wasphin** [comment]
参考这里: https://github.com/ZLMediaKit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy

rtsp 源也类似.

**Comment by jeickey** [comment]
是的, 我是用这个接口把相机的流拉了过来，我在 vlc 里用什么参数 访问 zlm 的这个 rtsp 流呢？

**Comment by wasphin** [comment]
需要结合看你怎么配置的.

ZLM 默认 RTSP 监听端口为 554,`rtsp://服务器地址:554/app/stream` 其中 app 和 stream 是调用接口时传进去的, 你的看截图, 应该分别是 live 和 `v172.16.110.19-554-1-sub`, 具体需要看你怎么调用的.

可以先把 wiki 看一下, 也不多, 了解下 app, stream, vhost 等一些概念.

**Comment by jeickey** [comment]
是这个格式， 可以播了，谢谢 
![image](https://user-images.githubusercontent.com/11632658/175763268-62ab4c88-fd49-4b19-91c7-122e5d8a1f7f.png)
