### ISSUE TITLE
[技术咨询] 线程正在执行本函数

### ISSUE THREAD

**Issue by woshi496964902** [ZLMediaKit/ZLMediaKit#1751]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
多个设备播放，有概率某个只能单线程推流，新手刚刚接触，请大神解答下

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
![image](https://user-images.githubusercontent.com/53846502/175763568-e297579b-5adc-432a-9c73-2c16a8fe18b6.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个问题不是只能单线程 是一个流只能被一个摄像头推，出现这种情况，有两种情况：
- 1、如果是单端口模式，则说明一个ssrc同时分配给多个摄像头了，或者一个摄像头同时推流多次。
- 2、如果是多端口模式，则说明这个端口被分配给多个摄像头，或者被一个摄像头多次推流。
