### ISSUE TITLE
[BUG]: RTP配置部分videoMtuSize和audioMtuSize的设置对RTSP方式回传的视频流无效

### ISSUE THREAD

**Issue by zhao85** [ZLMediaKit/ZLMediaKit#1752]
### 现象描述
对于RTSP方式回传的视频流，在WEBRTC或RTSP方式拉流时，设置的音视频MTU配置无效，发送包会大于设置的值

### 如何复现?
1、设置videoMtuSize为900，audioMtuSize为200
2、使用ffmpeg推送视频流至MediaServer
3、使用RTSP或webrtc观看推送的视频流
4、在MediaServer的运行系统上对输出UDP包进行抓取验证
5、使用rtmp方式发布，重复以上测试

### 相关日志或截图
使用rtsp发布的时候，观看输出流量最大包超过900字节
![image](https://user-images.githubusercontent.com/11971297/175823094-5c560c49-ad75-442c-ab41-97231ecde5a4.png)

使用rtmp发布的时候，观看输出流量最大包为900字节
![image](https://user-images.githubusercontent.com/11971297/175823030-81c02846-a575-464c-a562-6671a87b10f9.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**: Ubuntu 22.04 LTS
* **硬件信息**: 虚拟机环境
* **其他需要补充的信息**: 无

**Comment by xia-chu** [comment]
配置文件directProxy改成0



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhaoyi233 ***@***.***&gt;
发送时间: 2022年6月27日 00:04
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [BUG]: RTP配置部分videoMtuSize和audioMtuSize的设置对RTSP方式回传的视频流无效 (Issue #1752)





 
现象描述
 
对于RTSP方式回传的视频流，在WEBRTC或RTSP方式拉流时，设置的音视频MTU配置无效，发送包会大于设置的值
 
如何复现?
 
1、设置videoMtuSize为900，audioMtuSize为200
 2、使用ffmpeg推送视频流至MediaServer
 3、使用RTSP或webrtc观看推送的视频流
 4、在MediaServer的运行系统上对输出UDP包进行抓取验证
 5、使用rtmp方式发布，重复以上测试
 
相关日志或截图
 
使用rtsp发布的时候，观看输出流量最大包超过900字节
 
 
使用rtmp发布的时候，观看输出流量最大包为900字节
 
  展开查看详细日志 日志内容...   
配置
  展开查看详细配置 配置内容...   
各种环境信息
  
代码提交记录/git commit hash: 

操作系统及版本: Ubuntu 22.04 LTS 

硬件信息: 虚拟机环境 

其他需要补充的信息: 无

**Comment by zhao85** [comment]
测试正常，谢谢！
