### ISSUE TITLE
[技术咨询]Chromium集成Webrtc H265解码，如何通过ZLMRTCClient.js和ZLM可以播放RTSP推送的H265流？

### ISSUE THREAD

**Issue by dsjonline** [ZLMediaKit/ZLMediaKit#1753]
试了下返回 "Assertion failed: (have_active_media, 必须确保最少有一个活跃的track), function checkValid, file /ZLM/src/webrtc/Sdp.cpp, line 1321."

**Comment by xia-chu** [comment]
webrtc不支持265 你说的需求目前做不到；要支持265的话 要换wasm的播放

**Comment by dsjonline** [comment]
比如已经定制开发Chromium 已经让webrtc支持265

**Comment by dsjonline** [comment]
参考 [https://bugs.chromium.org/p/chromium/issues/detail?id=1286132](url)

**Comment by xia-chu** [comment]
360浏览器好像支持265 你可以测试下

**Comment by xia-chu** [comment]
定制chrome也行 不过这个工作量很大
