### ISSUE TITLE
[功能请求]startSendRtp能否增加本地mp4文件的推送

### ISSUE THREAD

**Issue by wulalawulala** [ZLMediaKit/ZLMediaKit#1754]
zlm目前能录制视频文件，以及发送实时流的rtp，但是无法发送mp4问题的rtp，目前ffmpeg发送rtp无法指定ssrc，能否在zlm内置集成mp4文件的功能，让zlm的功能更加完善

**Comment by xia-chu** [comment]
已经支持啊

**Comment by wulalawulala** [comment]
本地的录像文件是不支持的吧

**Comment by wulalawulala** [comment]
> 
本地的录像文件是不支持的吧

**Comment by wulalawulala** [comment]
是指之前的录像文件

**Comment by taojishou** [comment]
ffmpeg发送rtp是可以指定ssrc的

**Comment by wulalawulala** [comment]
ffmpeg -re -i ./output.mp4 -an -c copy -f rtp_mpegts -ssrc 1 rtp://127.0.0.1:10000  这样指定是不行的 
ffmpeg -re -i ./output.mp4 -an -c copy -f rtp -ssrc 1 rtp://127.0.0.1:10000  只有这个才可以 但是这样推zlm收不到


> ffmpeg发送rtp是可以指定ssrc的

**Comment by xia-chu** [comment]
<img width="1242" alt="图片" src="https://user-images.githubusercontent.com/11495632/176343495-2c511bb6-94cd-4d8e-a8e6-dd07e15c9cbe.png">

**Comment by xia-chu** [comment]
<img width="1304" alt="图片" src="https://user-images.githubusercontent.com/11495632/176343618-95303ee3-90e1-43bb-bd1c-3dbe275e5f7d.png">

**Comment by wulalawulala** [comment]
> <img alt="图片" width="1304" src="https://user-images.githubusercontent.com/11495632/176343618-95303ee3-90e1-43bb-bd1c-3dbe275e5f7d.png">

原来是这样用的啊。。之前测试app和stream传入了实时流的参数，from_mp4传了路径，然后发现是推的实时流,,,,以为没这个功能，就改用了gstreamer推指定ssrc的，thankyou（下面这样推好占内存）
mpegtsmux name=mux \
! rtpmp2tpay pt=97 ssrc=1 \
! udpsink host=127.0.0.1 port=10000

**Comment by OliveRuan** [comment]
> <img alt="图片" width="1242" src="https://user-images.githubusercontent.com/11495632/176343495-2c511bb6-94cd-4d8e-a8e6-dd07e15c9cbe.png">

那请教一下，c api里，用的是mk_media_start_send_rtp()，是否有别的类似接口能够提供本地mp4推流rtp的功能呢？

**Comment by OliveRuan** [comment]
> > <img alt="图片" width="1242" src="https://user-images.githubusercontent.com/11495632/176343495-2c511bb6-94cd-4d8e-a8e6-dd07e15c9cbe.png">
> 
> 那请教一下，c api里，用的是mk_media_start_send_rtp()，是否有别的类似接口能够提供本地mp4推流rtp的功能呢？

@xia-chu 在 c api的.h文档里，似乎没有看到mk_media_start_send_rtp()有mp4的接口参数。。

**Comment by xia-chu** [comment]
@OliveRuan 刚合并pr #1822 支持了
感谢 @Dw9

**Comment by supersndqd** [comment]
请教一下,怎么控制播放mp4的起始位置

**Comment by supersndqd** [comment]
感谢

**Comment by supersndqd** [comment]
setRecordSpeed  也是指的录像调用时候的速度了,那比较完美,可以加速了
