### ISSUE TITLE
[技术咨询] 播放失败时，未收到on_flow_report事件

### ISSUE THREAD

**Issue by swq123459** [ZLMediaKit/ZLMediaKit#1756]
使用最新版SDK的时候，配置general.flowThreshold为0，mk_media_create之后， 不送入流(不进行mk_media_init_video和mk_media_init_complete)， 这个时候使用ffmpeg去play，SDK可以收到on_play的消息回调，但是当ffmpeg播放器关闭的时候，没有收到on_flow_report。

看到日志里有HttpSession.cpp:33 ~HttpSession， 说明zl是知道客户端断开的(虽然没有拉到流)，但是为啥没有on_flow_report(我配置了general.flowThreshold为0，按道理即使收不到流也会抛出)， 看了一下代码，感觉是不是把抛出事件卸载析构那里做个RAII，就可以确保HttpSession释放的时候绝对会抛出on_flow_report

**Comment by xia-chu** [comment]
触发on_flow_report的逻辑由下面两个条件决定:
<img width="1082" alt="图片" src="https://user-images.githubusercontent.com/11495632/176343212-3e7f3f78-d5fb-4b62-821a-b18877eb2351.png">
<img width="1415" alt="图片" src="https://user-images.githubusercontent.com/11495632/176343244-597e2f28-e913-46a9-9b36-e28f5ca11841.png">

由于未播放成功，所以不会触发on_flow_report事件

**Comment by swq123459** [comment]
流量统计是0，感觉也应该统计吧，不然SDK二次开发集成客户端连接和断开无法成对

**Comment by swq123459** [comment]
或者，播放失败有事件吗

**Comment by xia-chu** [comment]
你应该在on_not_found事件创建流资源，在on_none_reader事件释放流资源；我不知道你为什么会关注on_play和on_flow_report?

**Comment by swq123459** [comment]
media的释放我是通过on_none_reader，之所以关注on_play和on_flow_report是因为我想监控每个连接的客户端player, on_play显然可以监控客户端的播放事件，on_flow_report是设置流量触发阈值为0，正常情况下(我不是按需拉流，是预拉流)是可以反应客户端断开的事件

**Comment by swq123459** [comment]
我所说的资源是与客户端关联的我的业务资源 😊

**Comment by xia-chu** [comment]
我不知道你为什么要在on_play时要创建一个资源 在on_flow_report时关闭一个资源。这种操作感觉就很迷，不合理。
你自己改下源码吧，主线我就不改了。

**Comment by swq123459** [comment]
这个时候也不会有on_none_reader

**Comment by swq123459** [comment]
没有事件给到上层可以释放这个media

**Comment by xia-chu** [comment]
你未在on_not_found事件创建流资源；当然就不会有播放成功，更不会有on_none_reader啊

**Comment by xia-chu** [comment]
合理的逻辑应该是这样： on_not_found --> mk_media_create -->  stop player --> on_none_reader --> mk_media_release

**Comment by swq123459** [comment]
好的，我试试
