### ISSUE TITLE
[技术咨询]zlm无法访问摄像头地址，是否能够播放

### ISSUE THREAD

**Issue by woshi496964902** [ZLMediaKit/ZLMediaKit#1757]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- zlm无法访问摄像头地址，是否能够播放，摄像头4g网络，服务器只有内网。无法实现播放
- 
![image](https://user-images.githubusercontent.com/53846502/176158058-4aadba52-08dd-4ab6-9085-e7f9ded9846e.png)

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by wasphin** [comment]
不能

**Comment by xia-chu** [comment]
摄像头在内网中(防火墙/NAT内)，那么zlm就不能直接穿越安全限制直接访问摄像头，特别是4G网络这种非对称型NAT；4G网络连一般的P2P软件都无法正常工作，所以zlm更不可能通过主动连接摄像头的方式访问它。

但是你可以让摄像头主动连接zlm，可以通过rtmp和GB28181推流的方式主动连接在公网的zlm

**Comment by woshi496964902** [comment]
> 摄像头在内网中(防火墙/NAT内)，那么zlm就不能直接穿越安全限制访问摄像头，特别是4G网络这种非对称型NAT；4G网络连一般的P2P软件都无法正常工作，所以zlm更不可能通过主动连接摄像头的方式访问它。
> 
> 但是你可以让摄像头主动连接zlm，可以通过rtmp和GB28181推流的方式主动连接在公网的zlm

你好，那我设备是海康的，我用ehome，能解决这个问题嘛。

**Comment by xia-chu** [comment]
可以 你可以了解下FreeEhome项目

**Comment by woshi496964902** [comment]
> 可以 你可以了解下FreeEhome项目

好滴，谢谢
