### ISSUE TITLE
[技术咨询] 按照wiki构建项目报错 【CMake can not determine linker language】

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1761]
**咨询的功能模块**
- 构建和编译项目

**咨询的具体内容和问题**
- 系统版本为Ubuntu-18.04.6，按照wiki进行构建项目，执行【cmake ..】后报错（所有依赖都已经安装）
![image](https://user-images.githubusercontent.com/31432863/176340389-666b430c-ae02-40c2-ae22-349b16a2b06e.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**由于本人不是c++开发者，对cmake不太了解，故此提出此问题，还望解答**

**Comment by xia-chu** [comment]
这个问题再wiki中三令五申提及了 你不按照wiki来编译 就不要提问好不？

**Comment by mayomeng** [comment]
看漏了，不好意思
