### ISSUE TITLE
[BUG]: 在嵌入式设备下编译pusher.c，拉流成功，但 track_count 为0

### ISSUE THREAD

**Issue by lus-zzz** [ZLMediaKit/ZLMediaKit#1764]
### 现象描述
分别在win下和嵌入式linux下编译成功，运行 api_tester_pusher ，win下可以正常拉流推流，嵌入式linux下拉流 on_mk_play_event_func
回调err_code 为0，但track_count 也为0，导致无法正常拉流

### 如何复现?
目前我是在瑞芯微的rk1808硬件上进行调试的

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
我在代码中输出了track_count

![image](https://user-images.githubusercontent.com/33312081/176378080-cc578d44-b7b6-4fc4-ba1f-4206bb081eb8.png)  

win执行日志  
![image](https://user-images.githubusercontent.com/33312081/176380653-1ecd0f2f-aeb0-4586-a721-631082d88dab.png)

嵌入式linux执行日志  
![image](https://user-images.githubusercontent.com/33312081/176378656-a512708b-2355-46e4-9109-a716ca1e95fe.png)  

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**: Windows10  buildroot
* **硬件信息**:Intel i5-7500  rk1808
* **其他需要补充的信息**:

**Comment by lus-zzz** [comment]
用的是同一套呀 ，win用的vs2019编译，linux交叉编译，是将win下的目录映射在容器里边，改了一次 编译两次

**Comment by xia-chu** [comment]
你删除代码 重新拉 ，你linux的代码都不支持ipv6

**Comment by lus-zzz** [comment]
大佬 不好意思 打扰了 linux release编译程序用的debug的库,导致的
