### ISSUE TITLE
[功能请求]大佬能不能出个安卓编译说明文当，直接用AndroidStudio编译不通过，不知道具体用哪个版本的NDK和CMake

### ISSUE THREAD

**Issue by Life1412378121** [ZLMediaKit/ZLMediaKit#1766]
**如果能编译通过，并可以像普通app一样在Android应用层对网络进行动态切换，那基本可以当个录像机去使用**

**Comment by xia-chu** [comment]
你这不是技术咨询吗？
Android都在CI编译通过了：[ci](https://github.com/ZLMediaKit/ZLMediaKit/runs/7127030528?check_suite_focus=true)
