### ISSUE TITLE
相同方式部署在两台不同服务器上的流媒体服务，访问80端口，页面显示文件目录不同，希望答疑，谢谢

### ISSUE THREAD

**Issue by joseshiang** [ZLMediaKit/ZLMediaKit#1767]
### 使用的是docker安装,镜像为`zlmediakit/zlmediakit:master` (几乎同一时间安装)

---
> ### 图1
![image](https://user-images.githubusercontent.com/19600894/176625679-9aba1a37-f3fd-4f9b-a45c-eb33eb696bad.png)

---
> ### 图2
![image](https://user-images.githubusercontent.com/19600894/176625845-5923ca0f-9644-42aa-bb96-d42b7bb7fcde.png)

**Comment by xia-chu** [comment]
这是bug？ 你http根目录文件不一样 当然不一样啊

**Comment by xia-chu** [comment]
请按照issue模板提哈

**Comment by joseshiang** [comment]
> 这是bug？ 你http根目录文件不一样 当然不一样啊

不好意思，目前正在接入`wvp`+`zlm` 视频监控平台开发，服务器上部署完成后，四台测试服务器，分别以相同方式打包部署，其中两台服务器上部署的视频平台是正常的，另外两台服务器部署的视频平台是访问不通的，正在排查问题。
