### ISSUE TITLE
[功能请求]webrtc带宽约束问题

### ISSUE THREAD

**Issue by bin-work** [ZLMediaKit/ZLMediaKit#1768]
**描述该功能的用处，可以提供相关资料描述该功能**

![JKAIDK~}Y) H9K8NXL XV`C](https://user-images.githubusercontent.com/44047515/176814646-b06f8089-ca97-4cd8-bb29-58a9d3fdca34.png)

请问这个webrtc的带宽约束设置为什么不是设置在class RtcMedia里面，一般这个b=AS的约束不是在C=IN后面吗？
我看webrtc的samples示例是这样的https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/bandwidth/js/main.js

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
有道理 这个确实应该在mline里面 也就是放RtcMedia内

**Comment by xia-chu** [comment]
欢迎来个pr
