### ISSUE TITLE
[技术咨询]请问如何录制FLV

### ISSUE THREAD

**Issue by tutengjun** [ZLMediaKit/ZLMediaKit#1775]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
录制功能
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
如何录制成FLV文件，我在record中只找到了录制的MP4文件
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
现在不支持

**Comment by xia-chu** [comment]
flv录制需要开发者自己二次开发，对象是FlvRecorder
