### ISSUE TITLE
[功能请求]关于webRTC中datachannel中消息实现群发

### ISSUE THREAD

**Issue by feizhufanfan** [ZLMediaKit/ZLMediaKit#1776]
分享人在完成webRTC推流之后发送msg消息，所有观看人在观看分享人的画面的同时能够接收到分享人发出的消息

在测试中在分享人的界面发送消息之后只能在分享人的页面接收到发出的消息回传。而其他的观看人页面无法收到分享人发出的消息。

定位到消息返回实在WebRtcTransport.cpp中179行实现消息回显。
尝试修改无法在该类中得到其他参与人的Identifier（socket）不知道如何将消息发送給其他参与者（观看人），希望在这个问题上能够得到解答，谢谢
使用版本：commit 9314a6699b1743f88541e6e7accacd6e3967afbb
gcc：7.5
Ubuntu20.04  x86_64
IDE：clion2022.1.3

**Comment by xia-chu** [comment]
datachannel 在zlm内部其实找不到应用场景的 这个本来就是业务极度藕合的 zlm提供datachannel能力的目的是希望开发者能二次开发，你需要的业务功能需要你自己二次开发

**Comment by feizhufanfan** [comment]
哦哦 了解了 我再去看看其他实现方式
谢啦
