### ISSUE TITLE
[技术咨询] 新版本mk_api接口问题

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#1778]
**咨询的功能模块**
- 创建源及发布流

**咨询的具体内容和问题**
- 最近更新了新版的mk_api接口，出现了这样的问题
- 
![image](https://user-images.githubusercontent.com/19390025/177244121-8024a843-d316-4284-81e7-7a41dafdc900.png)
导致rtsp的流打不开
新版本我是这样创建的源
![image](https://user-images.githubusercontent.com/19390025/177244210-a47c6ec0-a697-42b6-a7fc-d402d1450ddf.png)
输入h264和aac也是按照新版本的接口来的
![image](https://user-images.githubusercontent.com/19390025/177244295-49e98b72-1473-4aaf-9808-b19bf7abed14.png)
aac一帧是包含了adts的，h264帧也是有起始码的
运行结果就会出现上面的问题 '不是Track'

原来旧版是能发布流出来的
如果添加通道用的是旧版本方法
![image](https://user-images.githubusercontent.com/19390025/177245549-f38a2283-234d-41eb-848d-321aecbd3060.png)
也是能发布流出来的
所以现在新版本还有什么需要注意的地方吗  数据都是按照头文件的函数说明来的

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
嗯 新接口确实存在这个问题 mk_track_create原来用于设置解码器的 没考虑设置给mk_media； 所以有这些问题；这算是一个bug

**Comment by xia-chu** [comment]
你先用老接口初始化吧

**Comment by hh-kai** [comment]
另外我用新版的接口mk_frame_create来推数据的时候（初始化用的旧版接口）半小时左右程序就会异常退出（初始化的时候添加了音频track，没有添加音频的不会退出）， 测了3次都会这样。又换了旧版的接口mk_media_input_h264和mk_media_input_aac，测试了2个多小时都是正常的（测试的时候同时用播放器打开rtsp和m3u8）

**Comment by xia-chu** [comment]
程序退出问题可以debug调试下 看看崩溃在什么地方

**Comment by hh-kai** [comment]
我再详细测试一下
