### ISSUE TITLE
请教关于GPU转码问题   [技术咨询]

### ISSUE THREAD

**Issue by zhengjieyuan** [ZLMediaKit/ZLMediaKit#1780]
请问如何在ZLMediaKit配置ffmpeg  GPU转码？是在下面这段配置文件中cmd配置吗？

[ffmpeg]
#FFmpeg可执行程序路径,支持相对路径/绝对路径
bin=/usr/bin/ffmpeg
#FFmpeg拉流再推流的命令模板，通过该模板可以设置再编码的一些参数          
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s   
#FFmpeg生成截图的命令，可以通过修改该配置改变截图分辨率或质量
snap=%s -i %s -y -f mjpeg -t 0.001 %s
#FFmpeg日志的路径，如果置空则不生成FFmpeg日志
#可以为相对(相对于本可执行程序目录)或绝对路径
log=./ffmpeg/ffmpeg.log
# 自动重启的时间(秒), 默认为0, 也就是不自动重启. 主要是为了避免长时间ffmpeg拉流导致的不同步现象
restart_sec=0

**Comment by xia-chu** [comment]
cmd这个模板是作用于 addFFmpegSource接口的，你可以通过addFFmpegSource接口来实现转码
