### ISSUE TITLE
[技术咨询] webrtc推流后马上startRecord会出现找不到流的情况是否可以将find方法改成findasync来解决

### ISSUE THREAD

**Issue by bin-work** [ZLMediaKit/ZLMediaKit#1781]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
录像功能和webrtc问题
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
 webrtc推流后马上startRecord会出现找不到流的情况是否可以将find方法改成findasync来解决
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
本来就不是这样给你用的； startRecord需要再媒体注册后才能调用；也就是你收到on_stream_changed事件才能调用

**Comment by bin-work** [comment]
好的，谢谢
