### ISSUE TITLE
[技术咨询] 是否支持付费咨询

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1783]
**咨询的功能模块**
- addStreamProxy拉流rtmp转rtsp有时无法播放

**咨询的具体内容和问题**
- 之前提过一个相同的issues(#1741)，提供了无法播放的源rtmp地址，作者测试后反馈能播放；可是我这边不管是使用最新版的docker镜像还是本地编译源码后执行，都无法转换为rtsp播放。
- 自己实在是解决不了，所以想问一下，是否支持付费咨询；可以出一些费用，麻烦帮忙一起调试一下，看看是什么问题导致的。应该用不了多少时间的，我这边有外网可以访问的环境。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
rtsp 使用tcp 模式播放

**Comment by xiongguangjie** [comment]
可以留下联系方式

**Comment by mayomeng** [comment]
13998206572
