### ISSUE TITLE
关于GB28181录像暂停出现的问题

### ISSUE THREAD

**Issue by Luo-99** [ZLMediaKit/ZLMediaKit#1785]
GB28181 下, sip 信令服务器通知摄像头推流 zlm 播放录像
 
 sip信令服务器发送sip指令暂停录像回放后,
 摄像头会停止推流, 暂停个几秒还行
 暂停十几秒 vlc 画面直接黑了, 就算告知摄像头再推流也续不上了
 我试过通知摄像头暂停回放前先暂停ZLM的rtp超时检查, 但是还行不行

 目前是只能播放器暂停, 恢复后暂停了多久,就跳多少进度
 不能使用国标的暂停,暂停10秒左右, 再通知摄像头流也接不上了, 好像zlm的收流rtp关掉了

 WVP-PRO 可以测试出该问题

**Comment by xiongguangjie** [comment]
长时间暂停就关闭，短时间暂停就不处理
