### ISSUE TITLE
[技术咨询]startSendRtp是否以关键帧开始发送rtp包

### ISSUE THREAD

**Issue by thinker13** [ZLMediaKit/ZLMediaKit#1787]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
   startSendRtp是否以关键帧开始发送rtp包
  

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
   两个ZlMediaKit级联的时候第一个ZlMediaKit开发发送Rtp包之后第二个ZlMediaKit需要较长的时间才能成功解析出rtp包中的H264数据,测试中的视频关键帧间隔为2秒,第二个ZlMediaKit成功解析的时间则在0ms-2000ms之间,这部分是否可以优化,具体可以调整那部分代码?(ZlMediaKit新手抱歉)
![image](https://user-images.githubusercontent.com/8444469/177764018-b94c8b9d-2d18-450d-b9d9-cb25281d5ae4.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
这个没有保证一定是I帧开头

**Comment by xiongguangjie** [comment]
这个需要修改源码

**Comment by xiongguangjie** [comment]
我看了一下，发现除非新增一个ps 类型的MediaSource 否则还是需要等待I帧，没有太大的意义，只是打印上好看了，效果没有太大差别，只是节省了少量的数据包。感觉开发这个效费比不高

**Comment by thinker13** [comment]
主要的问题是多级级联的情况下,每一级都需要等待0-2000ms才能准备好,在最末端播放体验会非常不好.这部分有相关资料吗?我尝试处理一下,非常感谢回复

**Comment by xiongguangjie** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/tree/feature/rtp_send_wait_key_rtp 这个分支做了处理，但是效果差不多，如果要改，最好做一个PS类型的MediaSource ，才能效果最好

**Comment by thinker13** [comment]
收到,非常感谢,我来尝试处理一下

**Comment by zhang2349** [comment]
这样只是从在发送端丢弃 原来在是接收端丢弃  是一个效果吧
应该从MediaSource 的GOP缓存里读取发送吧 跟原来播放rtsp http-flv rtmp一样吧
