### ISSUE TITLE
[技术咨询]RTSP服务端在接收客户端推流时不支持使用RTSP专属认证,请教一下这样做的原因

### ISSUE THREAD

**Issue by cxyxiaoli** [ZLMediaKit/ZLMediaKit#1788]
**咨询的功能模块**
- RTSP服务--RtspSession：本地作为zlmediakit服务端，在处理客户端的RTSP推流时的认证问题。

**咨询的具体内容和问题**
我看代码在`handleReq_ANNOUNCE`是直接走`Broadcast::kBroadcastMediaPublish`去做webHook的认证，然后没有像拉流那样走获取账号密码的RTSP专属认证。想请教一下，这样做的原因是什么？即为什么服务端在接收RTSP推流时不采用账号密码鉴权认证呢？

**Comment by xia-chu** [comment]
确实rtsp推流 服务器没支持专属认证方式，你可以修改代码支持下 然后提个pr。

**Comment by cxyxiaoli** [comment]
好的，谢谢作者的回复
