### ISSUE TITLE
[技术咨询] 请问如果启用webrtc功能，zlmediakit 是否支持第三方的信令服务器？

### ISSUE THREAD

**Issue by hehui0123** [ZLMediaKit/ZLMediaKit#1793]
请问如果启用webrtc功能，zlmediakit 是否支持第三方的信令服务器？

**Comment by xiongguangjie** [comment]
你自己做网关做转换吧

**Comment by xia-chu** [comment]
> 三方的信令服务器？

zlm的webrtc没所谓的信令；其实就是restful api；你可以让任何信令服务器对接zlm的restful api；当然你也可以直接在浏览器对接zlm的restful api；目前我们的测试demo就是这么做的
