### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by ZhouMin216** [ZLMediaKit/ZLMediaKit#1794]
**咨询的功能模块**
- 请问zlm后续会考虑支持onvif协议吗？

**咨询的具体内容和问题**
- 我们在使用zlm获取rtsp流的时候，都是预先知道rtsp的拉流地址的，但是有时候我们可能一个摄像头，不清楚具体的拉流地址，请问onvif后续会考虑使用onvif协议去扫描局域网的摄像头，并获取rtsp拉流地址后进行拉流吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
onvif本来就有自动生成的框架代码 没必要再zlm中支持吧

**Comment by ZhouMin216** [comment]
> onvif本来就有自动生成的框架代码 没必要再zlm中支持吧

是的，我们现在使用的就是gSOAP生成的onvif代码，然后编译成库来使用的，不知道zlm后续会不会直接集成onvif相关的代码。

**Comment by xia-chu** [comment]
没必要啊 太冗余了

**Comment by ZhouMin216** [comment]
> 没必要啊 太冗余了

了解了，多谢回复！

**Comment by cooperwolfLee** [comment]
@xia-chu 我看到您在11月22号添加了初步对onvif的支持。想问下您，目前这个功能可用吗？

**Comment by xia-chu** [comment]
> @xia-chu 我看到您在11月22号添加了初步对onvif的支持。想问下您，目前这个功能可用吗？

这个只有看代码了 目前没精力做文档
