### ISSUE TITLE
[BUG]: mp4文件录制时长问题, 时长不准确

### ISSUE THREAD

**Issue by x-x-p** [ZLMediaKit/ZLMediaKit#1795]
### 现象描述
使用zlmediakit进行mp4文件进行录制, 时间间隔为10分钟一个, 不间断录制整天, 之后检查数据发现`Broadcast::kBroadcastRecordMP4`广播出来的文件时长有些对不上, 一整天数据中有间隙.

### 疑问
在`Broadcast::kBroadcastRecordMP4`函数中发现mp4录制时长是通过获取新建文件和关闭文件之间的`time(nullptr)`差来得到的, 疑问的是这样获取时间长度准确性好像不高? 然而时长分片又是通过`frame->dts()`, 两个时长不一致.

https://github.com/ZLMediaKit/ZLMediaKit/blob/14da5ab2d8ab9fb739b3aaf2894066af58c5b583/src/Record/MP4Recorder.cpp#L101-L125

在系统负载压力大时, `MP4Recorder::inputFrame`出现积压, 系统时间被调整等影响下, 这个时长都是不准确的.

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by xia-chu** [comment]
@x-x-p 这个不是那么重要吧？如果你比较在意这点 欢迎修改代码并提交pr

**Comment by x-x-p** [comment]
是否可用 `MP4Muxer`中封装的`track_info`中的https://github.com/ZLMediaKit/ZLMediaKit/blob/c19fa29e75b6f173444ab7ed826ff1acceb0de5f/src/Record/MP4Muxer.h#L71-L75

Stamp时间戳https://github.com/ZLMediaKit/ZLMediaKit/blob/c19fa29e75b6f173444ab7ed826ff1acceb0de5f/src/Common/Stamp.h#L63

```
int64_t MP4MuxerInterface::getDurationMS()
{
    Stamp *audio = nullptr, *video = nullptr;
    for(auto &pr : _codec_to_trackid){
        switch (getTrackType((CodecId) pr.first)){
            case TrackAudio : audio = &pr.second.stamp; break;
            case TrackVideo : video = &pr.second.stamp; break;
            default : break;
        }
    }
    if(video) {
        return video->getRelativeStamp();
    }
    if(audio) {
        return audio->getRelativeStamp();
    }
    return 0;
}
````
获取时长以及按时长进行分割？？？

**Comment by xia-chu** [comment]
> 是否可用 `MP4Muxer`中封装的`track_info`中的
> 
> https://github.com/ZLMediaKit/ZLMediaKit/blob/c19fa29e75b6f173444ab7ed826ff1acceb0de5f/src/Record/MP4Muxer.h#L71-L75
> 
> Stamp时间戳
> 
> https://github.com/ZLMediaKit/ZLMediaKit/blob/c19fa29e75b6f173444ab7ed826ff1acceb0de5f/src/Common/Stamp.h#L63
> 
> ```
> int64_t MP4MuxerInterface::getDurationMS()
> {
>     Stamp *audio = nullptr, *video = nullptr;
>     for(auto &pr : _codec_to_trackid){
>         switch (getTrackType((CodecId) pr.first)){
>             case TrackAudio : audio = &pr.second.stamp; break;
>             case TrackVideo : video = &pr.second.stamp; break;
>             default : break;
>         }
>     }
>     if(video) {
>         return video->getRelativeStamp();
>     }
>     if(audio) {
>         return audio->getRelativeStamp();
>     }
>     return 0;
> }
> ```
> 
> 获取时长以及按时长进行分割？？？

可以 这样最好 欢迎提个pr

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by xia-chu** [comment]
done!
