### ISSUE TITLE
关于请求参数转义的问题[技术咨询]

### ISSUE THREAD

**Issue by renyanru1994** [ZLMediaKit/ZLMediaKit#1797]
app调后台java的接口，java再调用 POST /index/api/webrtc?app=app&stream=12224566335&type=push
提示：
"code" : -400,
 "msg" : "Assertion failed: (!origin.empty()), function checkValid, file /usr/local/src/ZLMediaKit/webrtc/Sdp.cpp, line 1305."

打印的请求：
"v=0\r\no=- 6106220190017803932 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS stream\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Z5ts\r\na=ice-pwd:NxUbs/UflWTMrGnzAqrj9iPT\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 A1:F6:75:FD:4A:07:E7:AA:B3:F9:B0:2F:C5:1B:E8:85:96:E2:DD:DC:BD:52:1E:0B:EB:06:87:18:A4:C2:10:A2\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time/r/na=extmap:3) [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01/r/na=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:stream audio0\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:378761526 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:378761526 msid:stream audio0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 35 36 123 122 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Z5ts\r\na=ice-pwd:NxUbs/UflWTMrGnzAqrj9iPT\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 A1:F6:75:FD:4A:07:E7:AA:B3:F9:B0:2F:C5:1B:E8:85:96:E2:DD:DC:BD:52:1E:0B:EB:06:87:18:A4:C2:10:A2\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time/r/na=extmap:13) urn:3gpp:video-orientation\r\na=extmap:3 [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01/r/na=extmap:5) [http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6](http://www.webrtc.org/experiments/rtp-hdrext/playout-delay/r/na=extmap:6) [http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7](http://www.webrtc.org/experiments/rtp-hdrext/video-content-type/r/na=extmap:7) [http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8](http://www.webrtc.org/experiments/rtp-hdrext/video-timing/r/na=extmap:8) [http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4](http://www.webrtc.org/experiments/rtp-hdrext/color-space/r/na=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:stream video0\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 H264/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 VP9/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:35 AV1/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:123 red/90000\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=123\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 2959961480 2087013070\r\na=ssrc:2959961480 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:2959961480 msid:stream video0\r\na=ssrc:2087013070 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:2087013070 msid:stream video0\r\n"

始终有转义字符\r\n

**Comment by wasphin** [comment]
抓包检查下你程序发送的内容，发送的有问题

**Comment by renyanru1994** [comment]
> 抓包检查下你程序发送的内容，发送的有问题
这边是我抓包的结果：
"v=0\r\no=- 6106220190017803932 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS stream\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 63 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Z5ts\r\na=ice-pwd:NxUbs/UflWTMrGnzAqrj9iPT\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 A1:F6:75:FD:4A:07:E7:AA:B3:F9:B0:2F:C5:1B:E8:85:96:E2:DD:DC:BD:52:1E:0B:EB:06:87:18:A4:C2:10:A2\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time/r/na=extmap:3) [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01/r/na=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=sendrecv\r\na=msid:stream audio0\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:63 red/48000/2\r\na=fmtp:63 111/111\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:378761526 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:378761526 msid:stream audio0\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 35 36 123 122 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:Z5ts\r\na=ice-pwd:NxUbs/UflWTMrGnzAqrj9iPT\r\na=ice-options:trickle renomination\r\na=fingerprint:sha-256 A1:F6:75:FD:4A:07:E7:AA:B3:F9:B0:2F:C5:1B:E8:85:96:E2:DD:DC:BD:52:1E:0B:EB:06:87:18:A4:C2:10:A2\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time/r/na=extmap:13) urn:3gpp:video-orientation\r\na=extmap:3 [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01/r/na=extmap:5) [http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6](http://www.webrtc.org/experiments/rtp-hdrext/playout-delay/r/na=extmap:6) [http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7](http://www.webrtc.org/experiments/rtp-hdrext/video-content-type/r/na=extmap:7) [http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8](http://www.webrtc.org/experiments/rtp-hdrext/video-timing/r/na=extmap:8) [http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4](http://www.webrtc.org/experiments/rtp-hdrext/color-space/r/na=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendrecv\r\na=msid:stream video0\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 H264/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP8/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 VP9/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:35 AV1/90000\r\na=rtcp-fb:35 goog-remb\r\na=rtcp-fb:35 transport-cc\r\na=rtcp-fb:35 ccm fir\r\na=rtcp-fb:35 nack\r\na=rtcp-fb:35 nack pli\r\na=rtpmap:36 rtx/90000\r\na=fmtp:36 apt=35\r\na=rtpmap:123 red/90000\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=123\r\na=rtpmap:125 ulpfec/90000\r\na=ssrc-group:FID 2959961480 2087013070\r\na=ssrc:2959961480 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:2959961480 msid:stream video0\r\na=ssrc:2087013070 cname:cmDvbjVRbpg4vS+n\r\na=ssrc:2087013070 msid:stream video0\r\n"
里面就是有/r 和/n的转义字符。

**Comment by renyanru1994** [comment]
@wasphin

**Comment by renyanru1994** [comment]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/66729549/178630618-9aa1ab5b-ab3b-4cc4-a522-9904107ab863.png">
postman 调用 它是没有问题，但是通过后台调用，就出现上述问题

**Comment by renyanru1994** [comment]
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/66729549/178633441-e1a58f8e-8942-4b9f-8aae-71ff790c670e.png">
这是我本地代码中调用的请求，出现以上问题

**Comment by renyanru1994** [comment]
这是ZlmediaKit打印的日志
<img width="1745" alt="image" src="https://user-images.githubusercontent.com/66729549/178634685-953e0673-3213-4578-9e7d-1f1db1a6eb67.png">

**Comment by xia-chu** [comment]
你可以把zlm err msg提示的代码行注释掉试试

**Comment by renyanru1994** [comment]
> 

嗯。已解决

**Comment by xia-chu** [comment]
> > 
> 
> 嗯。已解决

你修改你客户端代码能兼容吗
