### ISSUE TITLE
[技术咨询]RTSP代理，拉流时需要设置RTSP的HEADER，比如Range、Scale，请问应该怎样设值呢？

### ISSUE THREAD

**Issue by zodostffaa** [ZLMediaKit/ZLMediaKit#1800]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
RTSP代理
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
需要从VMS系统那边拉取回放的RTSP流再转发，VMS协议中说：
You should put the "Range" header in your RTSP SETUP and PLAY messages. Note
that this is part of the RTSP specs (RFC 2326), as shown below:
E.g.
Range: clock=20180608T211315Zwhere "Range" is the key of your header, and "clock=20180608T211315Z-" is the value. The
"time" part is not needed in this case (read in above in the RFC to see what it actually does).
Note that the timestamp is in UTC (hence the "Z" at the end of it).

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
一般来说 zlm的rtsp只作为直播用 点播url的代理不支持Range Scale; 不过mp4的rtsp点播支持的
