### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by ssvictor94** [ZLMediaKit/ZLMediaKit#1807]
**咨询的功能模块**
编译问题

**咨询的具体内容和问题**
ubuntu20.04 server 安装完 xubuntu-desktop、obs-studio之后一直编译失败

![2ab924d5d3283d7cd2544568b38b277](https://user-images.githubusercontent.com/40878647/179455199-1e595fe5-f09d-4eae-982b-b932da9eab59.png)

![image](https://user-images.githubusercontent.com/40878647/179455271-de1f0aef-6046-4df1-9765-a12fb784267e.png)

**Comment by xia-chu** [comment]
请make -j1编译。
看日志应该是系统内存不足以多线程编译

**Comment by ssvictor94** [comment]
好的，我试试
