### ISSUE TITLE
[技术咨询]  树莓派 debian 11 上编译失败

### ISSUE THREAD

**Issue by xiazi718** [ZLMediaKit/ZLMediaKit#1810]
我打算在树莓派上安装，但是在make时失败了
具体报错如下
```bash
pi@raspberrypi:~/ZLMediaKit_Stream_Server/ZLMediaKit/build $ make -j4
[ 88%] Built target zltoolkit
[ 88%] Built target srt
[ 88%] Built target flv
[ 88%] Built target mpeg
[ 88%] Built target mov
[ 88%] Built target jsoncpp
[ 88%] Built target zlmediakit
[ 88%] Linking CXX executable ../../release/linux/Release/test_wsServer
[ 88%] Linking CXX executable ../../release/linux/Release/tab
[ 88%] Linking CXX executable ../../release/linux/Release/bom
[ 88%] Built target mk_api
[ 88%] Linking CXX executable ../../release/linux/Release/test_bench_proxy
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMillisecond(bool)':
util.cpp:(.text+0xcec): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0xd08): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMicrosecond(bool)':
util.cpp:(.text+0x100c): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0x1028): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<toolkit::initMillisecondThread()::{lambda()#1}> > >::_M_run()':
util.cpp:(.text+0x1720): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x174c): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x1790): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x17b8): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/tab.dir/build.make:111: ../release/linux/Release/tab] Error 1
make[1]: *** [CMakeFiles/Makefile2:678: tests/CMakeFiles/tab.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMillisecond(bool)':
util.cpp:(.text+0xcec): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0xd08): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMicrosecond(bool)':
util.cpp:(.text+0x100c): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0x1028): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<toolkit::initMillisecondThread()::{lambda()#1}> > >::_M_run()':
util.cpp:(.text+0x1720): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x174c): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x1790): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x17b8): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/bom.dir/build.make:111: ../release/linux/Release/bom] Error 1
make[1]: *** [CMakeFiles/Makefile2:646: tests/CMakeFiles/bom.dir/all] Error 2
/usr/bin/ld: ../../release/linux/Release/libzlmediakit.a(HlsMediaSource.cpp.o): in function `mediakit::HlsCookieData::addByteUsage(unsigned int)':
HlsMediaSource.cpp:(.text+0x1914): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../release/linux/Release/libzlmediakit.a(HlsMediaSource.cpp.o): in function `mediakit::HlsCookieData::~HlsCookieData()':
HlsMediaSource.cpp:(.text+0x1e0c): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMillisecond(bool)':
util.cpp:(.text+0xcec): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0xd08): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMicrosecond(bool)':
util.cpp:(.text+0x100c): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0x1028): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<toolkit::initMillisecondThread()::{lambda()#1}> > >::_M_run()':
util.cpp:(.text+0x1720): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x174c): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x1790): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x17b8): undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(Session.cpp.o): in function `toolkit::Session::getIdentifier[abi:cxx11]() const':
Session.cpp:(.text+0x44): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_wsServer.dir/build.make:111: ../release/linux/Release/test_wsServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:614: tests/CMakeFiles/test_wsServer.dir/all] Error 2
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMillisecond(bool)':
util.cpp:(.text+0xcec): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0xd08): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `toolkit::getCurrentMicrosecond(bool)':
util.cpp:(.text+0x100c): undefined reference to `__atomic_load_8'
/usr/bin/ld: util.cpp:(.text+0x1028): undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Release/libzltoolkit.a(util.cpp.o): in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<toolkit::initMillisecondThread()::{lambda()#1}> > >::_M_run()':
util.cpp:(.text+0x1720): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x174c): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x1790): undefined reference to `__atomic_store_8'
/usr/bin/ld: util.cpp:(.text+0x17b8): undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_bench_proxy.dir/build.make:111: ../release/linux/Release/test_bench_proxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:710: tests/CMakeFiles/test_bench_proxy.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

**Comment by monktan89** [comment]
g++ 什么版本？

**Comment by xiazi718** [comment]
> g++ 什么版本？

10，但是服务器需要11，所以我也觉得是版本的问题，但是不知道该如何让系统忽视这个错误

**Comment by xia-chu** [comment]
需要单独链接下atomic库 需要修改下cmakelist.txt

**Comment by xiazi718** [comment]
> 需要单独链接下atomic库 需要修改下cmakelist.txt
请问是这个路径下的cmakelist吗
`pi@raspberrypi:~/ZLMediaKit_Stream_Server/ZLMediaKit $ sudo nano CMakeLists.txt`
我在这里尝试着链接了atomic库，这是我的代码
`link_directories(/usr/include/c++/10/atomic)`
但是依然出现了相同的报错，请问我在哪里做错了，如果可以能不能教一下具体的链接方法
很抱歉我刚刚接触linux开发，为了推流而现学的，所以问的问题很白痴，很不好意思

**Comment by wasphin** [comment]
临时编译可以在 `CMakeLists.txt` 先找个地方添加
```
list(APPEND LINK_LIB_LIST atomic)
```

**Comment by xiazi718** [comment]
> 

我在`CMakeLists.txt`的第五行添加了该句
`list(APPEND LINK_LIB_LIST atomic)`
（另外我发现`CMakeLists.txt`本来就有这句话
但依然出现了这个报错，请问是我写的地方不对，还是需要别的补充？
`/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::store(unsigned long long, std::memory_order)':
/usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::store(unsigned long long, std::memory_order)':
/usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/tab.dir/build.make:109: ../release/linux/Debug/tab] Error 1
make[1]: *** [CMakeFiles/Makefile2:678: tests/CMakeFiles/tab.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/bom.dir/build.make:109: ../release/linux/Debug/bom] Error 1
make[1]: *** [CMakeFiles/Makefile2:646: tests/CMakeFiles/bom.dir/all] Error 2
/usr/bin/ld: ../../release/linux/Debug/libzlmediakit.a(HlsMediaSource.cpp.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: ../../release/linux/Debug/libzlmediakit.a(HlsMediaSource.cpp.o): in function `std::__atomic_base<unsigned long long>::operator+=(unsigned long long)':
/usr/include/c++/10/bits/atomic_base.h:342: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(Session.cpp.o): in function `std::__atomic_base<unsigned long long>::operator++()':
/usr/include/c++/10/bits/atomic_base.h:326: undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::store(unsigned long long, std::memory_order)':
/usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:404: undefined reference to `__atomic_store_8'
/usr/bin/ld: ../../release/linux/Debug/libzltoolkit.a(util.cpp.o): in function `std::__atomic_base<unsigned long long>::load(std::memory_order) const':
/usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
/usr/bin/ld: /usr/include/c++/10/bits/atomic_base.h:426: undefined reference to `__atomic_load_8'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/test_wsServer.dir/build.make:109: ../release/linux/Debug/test_wsServer] Error 1
make[1]: *** [CMakeFiles/Makefile2:614: tests/CMakeFiles/test_wsServer.dir/all] Error 2
[ 86%] Built target mk_api
make: *** [Makefile:149: all] Error 2`

**Comment by wasphin** [comment]
印象中记得先前确实改过一次 atomic 的检查，应该能适应不同情况。

暂时没有设备，等晚上我回去再试试。

**Comment by xiazi718** [comment]
> 印象中记得先前确实改过一次 atomic 的检查，应该能适应不同情况。
> 
> 暂时没有设备，等晚上我回去再试试。

好的好的，我也再试试别的解决方案

**Comment by wasphin** [comment]
在这里针对树莓派上编译做过适配 https://github.com/ZLMediaKit/ZLMediaKit/pull/1405

**Comment by xiazi718** [comment]
> 在这里针对树莓派上编译做过适配 #1405

嗯，我在`CMakeLists.txt`见到了这段，但依然不行

**Comment by Dw9** [comment]
@xiazi718  hi 你烧录的树莓派是什么版本的？
我这边32位的Raspbian10是可以编译通过的
<img width="570" alt="image" src="https://user-images.githubusercontent.com/36155473/179997858-5eee5910-871e-461d-a513-a15f6d4fdfd8.png">

**Comment by xiazi718** [comment]
树莓派最新的系统，
![image](https://user-images.githubusercontent.com/84230174/180004049-321b0c7f-2c49-47d2-9ceb-06595ab28cd2.png)


> @xiazi718 hi 你烧录的树莓派是什么版本的？ 我这边32位的Raspbian10是可以编译通过的 <img alt="image" width="570" src="https://user-images.githubusercontent.com/36155473/179997858-5eee5910-871e-461d-a513-a15f6d4fdfd8.png">

**Comment by wasphin** [comment]
@xiazi718 你也登录到设备上执行下: `lsb_release -a` 看看吧, 我和 @Dw9 的环境一样, gcc 是 8.3.0, 上面看你的 gcc 是 10 的.

**Comment by wasphin** [comment]
应该是 debian 11, 我看 11 下 gcc 版本是 10, 等我升个级

**Comment by xiazi718** [comment]
![image](https://user-images.githubusercontent.com/84230174/180011125-2377b23f-28ae-4286-b1e5-ba86bdb6b2b6.png)

**Comment by xiazi718** [comment]
> @xiazi718, 先临时改一下吧, 需要在后面链接 `atomic` 库, 后面再看怎么调整下. 设备上编译实在是太慢了, 后面得配一个交叉编译环境.
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index a2edf606..4fa65ee3 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -510,6 +510,8 @@ if (ENABLE_SRT)
>      message(STATUS "srt 功能已开启")
>  endif()
>  
> +list(APPEND LINK_LIB_LIST ${CMAKE_REQUIRED_LIBRARIES})
> +
>  #添加c库
>  if (ENABLE_API)
>      add_subdirectory(api)
> ```

啊，解决了！直接在那个地方链接atomic库就行，我之前是链接错了地方。
非常感谢大佬的帮助！
顺带问一下，交叉编译环境对于后续推流使用来说有增益吗

**Comment by wasphin** [comment]
这个开着吧，我们调一下类似库的链接顺序。交叉编译和直接设备上编译对功能没区别。

**Comment by wasphin** [comment]
编译应该没问题了，两台设备上测过了，有问题可以随时反馈。
