### ISSUE TITLE
国标rtp推送失败 [技术咨询]

### ISSUE THREAD

**Issue by supercooc** [ZLMediaKit/ZLMediaKit#1812]
**咨询的功能模块**
- 国标rtp 推送 

**咨询的具体内容和问题**
- 搭配 WVP视频平台 做上下级视频推送，视频UDP包已发送，但是上级视频平台未收到视频流
-  A 和 B 两个服务器都部署了 ZLMediaKit 以及 WVP.  A 作为B 的下级。 当B 点播A上的国标视频时 ， A上的 WVP 通过 startSendRtp接口通知 A上的ZLMediaKit 推送视频搭配B 服务器，此时在A上用tcpdump 抓包可以看到发送了 udp 数据包。但B服务器上的ZLMediaKit 却没有收到视频流，用tcpdump 也无法收到udp数据包。 
- 更诡异的是，如果直接用postman 使用wvp 相同的参数来调用接口发送视频流，一切都正常。即先在B使用 openRtpServer创建接收服务器，然后在A上调用 startSendRtp接口， B就可以收到视频流了，B上的tcpdunp抓包也正常。   
- 以上问题困扰好几天，没有明白WVP 调用 和 postman 调用咋会出现两种不一样的表现

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
建议这个issue在wvp项目上提 你说的现象说明zlm应该没问题 我觉得可能是 openRtpServer与startSendRtp接口调用顺序的问题；需要先openRtpServer再startSendRtp
