### ISSUE TITLE
[技术咨询]WebRTC推拉流失败调用接口提示401问题

### ISSUE THREAD

**Issue by eanfs** [ZLMediaKit/ZLMediaKit#1816]
- WebRTC推拉流问题

- 使用https://default.zlmediakit.com/webrtc/ webrtc推拉流失败，调用接口提示401，请问下有什么配置不对吗？
   使用Docker启动zlm服务的

- 如下图：
- 
![image](https://user-images.githubusercontent.com/5432110/179908967-1f273d9e-0419-4c0d-b2ff-35d82a895512.png)

**Comment by xia-chu** [comment]
这个是你的on_play hook接口返回鉴权失败

**Comment by eanfs** [comment]
解决了，增加了sign参数可以了
https://default.zlmediakit.com/index/api/webrtc?app=live&stream=test3&type=play&sign=191258cd8c1d0078239986c0595d5a77

**Comment by eanfs** [comment]
另外 webrtc推流只支持 720P吗

![image](https://user-images.githubusercontent.com/5432110/179918605-c0a98596-fc8b-46e7-8047-9c86939e7f93.png)

**Comment by xia-chu** [comment]
看你摄像头吧
