### ISSUE TITLE
[技术咨询] 设备录像下载

### ISSUE THREAD

**Issue by 513571357** [ZLMediaKit/ZLMediaKit#1819]
**咨询的功能模块**
- 录像下载

**咨询的具体内容和问题**
- record文件夹偶尔有几次可以完整生成一个设备录像文件，其余都是生成10个左右文件大概10M左右就停止了。wvp和抓包都显示推流完毕，请大佬帮忙看看是不是配置项哪里没填对

[2022-07-21_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/9159598/2022-07-21_00.log)
<img width="667" alt="record" src="https://user-images.githubusercontent.com/54172308/180222121-867fc958-1d27-4993-9b1d-6b893ab0b122.png">

**Comment by xia-chu** [comment]
可能跟时间戳回退 或者流不稳定导致 你要多看看zlm日志
