### ISSUE TITLE
sip连接ZLMediaKit[技术咨询]

### ISSUE THREAD

**Issue by taxi886** [ZLMediaKit/ZLMediaKit#1823]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- gb28181注册媒体平台

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
gb28181连接媒体平台后，开始可以正常连接，时间久了就连不了上，重启后又可以连拉，请问一下是不是哪个配置有问题？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个我不认为是zlm的问题 建议你自己分析下gb28181 sip服务器日志
