### ISSUE TITLE
chrome播放webrtc，画面出来卡主几秒后才能正常播放

### ISSUE THREAD

**Issue by victording123456** [ZLMediaKit/ZLMediaKit#1824]
咨询webrtc在前端的播放问题

使用chrome播放webrtc，画面出来了，会加速播放1-3秒缓存的画面，继而会卡住几秒，再播放，后面就正常了。这是什么原因呢？我在两个客户端机器上测试过：1、无集成显卡，cpu软解码；2、RTX 2060 super显卡，能使用硬解码。两种类型的客户机都会卡主几秒，后面一直都很流畅。不知道为什么？需要做什么设置吗？我用的服务器是凝思操作系统，arm架构；客户端是windows10

我怀疑可能的原因是：
1、前端解码的问题，解码器有缓存，播放时先播放一下缓存，播放器在等待得新的流解码；
2、ZLM后端多余的给了上一次结尾的视频流；
3、我没有使用ssl，是不是和这个有关系？

我做过的努力：1、chrome升级到103版，禁用chrome的硬件解码，使用cpu软解码。此方法没有解决问题
                          2、对config.ini进行各种可疑参数进行尝试，没能解决问题。

**Comment by Smallwhitepig** [comment]
视频源是通过什么推给Zlm的？

**Comment by victording123456** [comment]
通过ffmpeg推的桌面到rtmp，再使用自带的webrtc播放器播放

**Comment by Smallwhitepig** [comment]
把ffmpeg 的命令发出来

**Comment by victording123456** [comment]
ffmpeg.exe -hide_banner -f gdigrab -draw_mouse 0 -i desktop -pix_fmt yuv420p -vcodec h264_nvenc -f flv rtmp://192.168.140.4/live/test

**Comment by victording123456** [comment]
补充一下∶我在有的电脑上，比如I7处理器，rtx1660Ti显卡的机器上播放就不存在这个问题，刷新网页时，黑2秒左右的屏就可以播放了，实时性很强，我是做远程操控桌面的，鼠标操作体验很好。第一个帖子里面的那两台电脑，除了刚开始出以前的画面并卡几秒之外，后面操作实时性也很强。我看了一些你们的文章，推测是不是播放器或推流端缓存的问题呢？如何去掉缓存再测试一下呢

**Comment by victording123456** [comment]
> 把ffmpeg 的命令发出来

ffmpeg.exe -hide_banner -f gdigrab -draw_mouse 0 -i desktop -pix_fmt yuv420p -vcodec h264_nvenc -f flv rtmp://192.168.140.4/live/test

麻烦您帮我分析一下好吗？

**Comment by xia-chu** [comment]
@victording123456   请你更新下最新的zlm(包括zltoolkit)然后测试看看，如果问题尚未解决，请录制个视频传上来

**Comment by victording123456** [comment]
请问，哪个是最新版：6.0、feature/hls_record_disk、feature/async_write_file、feature/rtc_proxy&nbsp; &nbsp;?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月26日(星期二) 中午11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] chrome播放webrtc，画面出来卡主几秒后才能正常播放 (Issue #1824)





 
@victording123456   请你更新下最新的zlm(包括zltoolkit)然后测试看看，如果问题尚未解决，请录制个视频传上来

**Comment by HammerZhao** [comment]
你有使用firefox webrtc 拉流测试了么？

**Comment by victording123456** [comment]
> @victording123456 请你更新下最新的zlm(包括zltoolkit)然后测试看看，如果问题尚未解决，请录制个视频传上来

请看以下视频，我在15秒时点击刷新，会显示12秒-14秒的历史画面，然后停留几秒后就正常了：
https://user-images.githubusercontent.com/9878531/181501209-661fc5a4-857c-4224-8988-3252b4106629.mp4

**Comment by xia-chu** [comment]
@victording123456 master分支是最新

**Comment by victording123456** [comment]
> @victording123456 请你更新下最新的zlm(包括zltoolkit)然后测试看看，如果问题尚未解决，请录制个视频传上来

我下载了最新master并编译，现象依然存在。
请看以下视频，我在15秒时点击刷新，会显示12秒-14秒的历史画面，然后停留几秒后就正常了：

https://user-images.githubusercontent.com/9878531/181503788-e550e569-56f2-4f28-80ec-018a2fd214f7.mp4

**Comment by xia-chu** [comment]
@victording123456 你这视频怎么画面突然跳到其他画面了？

**Comment by victording123456** [comment]
那个画面是首页html内 video的背景图：
&nbsp; &nbsp; &nbsp; &nbsp;<video class="webrtc-video" id='video' poster="./bg.jpg" muted autoplay oncontextmenu="return false" &gt;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Your browser is too old which doesn't support HTML5 video.&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;</video&gt;

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] chrome播放webrtc，画面出来卡主几秒后才能正常播放 (Issue #1824)





 
@victording123456 你这视频怎么画面突然跳到其他画面了？

**Comment by gateslu** [comment]
我也遇到了类似的问题，画面会开几秒，然后到下个画面又卡几秒，而我用rtsp请求相同media，则没有这个问题
，通过wireshark抓包分析了一下rtp包，发现webrtc发送的payload是有问题的，无法通过正常的方法解析nal的类型

常规的解析nal类型方法：
uint8_t nal_type = (rtp_payload[0] & kHevcTypeMask) >> 1;

这是正常能解析rtp包的rtsp抓包
![image](https://user-images.githubusercontent.com/1697700/181687254-c59f00c9-5951-46d4-983d-fbd022a280b2.png)

这是无法正常解析rtp包的webrtc抓包，都是一些奇怪的数值
![image](https://user-images.githubusercontent.com/1697700/181688299-600b9eba-5c15-4e73-bf2e-61fd278d2cab.png)

![image](https://user-images.githubusercontent.com/1697700/181688382-375845e0-3125-4e96-a780-393539b05204.png)

**Comment by xia-chu** [comment]
@gateslu 你这个是265 rtsp 的？

**Comment by gateslu** [comment]
> 

0x62的是vlc请求zlm的rtsp/h265的payload第一个字节

下面那些无规则的是请求zlm的webrtc/h265的payload第一个字节

**Comment by xia-chu** [comment]
zlm支持265的webrtc 但是浏览器不支持 你可以用metaRTC测试

**Comment by gateslu** [comment]
> 

浏览器已经改过了，是定制的chromium，已经支持请求265，但是收到的rtp包看着不对

**Comment by xia-chu** [comment]
> 无法按照正常的

怎么会不对，你不信可以rtsp播放试试 zlm中rtsp和webrtc是互通的

**Comment by gateslu** [comment]
> > 无法按照正常的
> 
> 怎么会不对，你不信可以rtsp播放试试 zlm中rtsp和webrtc是互通的

这个是我的问题，srtp搞错了，我再检查一下解码的代码吧，谢谢

**Comment by ftanx** [comment]
关键帧间隔搞小一些，即使能正常接收解码，接收端也是要收到关键帧才能解码的
ffmpeg的x264 的关键帧间隔默认是250.。。  假设是25fps，也要10s才能确定有一个关键帧

**Comment by victording123456** [comment]
您好，
&nbsp; &nbsp; &nbsp;请教个问题。
&nbsp; &nbsp; &nbsp;在网络条件差的时候，会出现首次连接缓慢，打开后间歇性画面中断的情况，过个几秒就恢复了，这个怎么破解？
&nbsp; &nbsp; &nbsp;说明：我用的是ffmpeg把桌面的画面压缩成h264，使用rtmp往ZLM推流，再在浏览器端使用webrtc拉流。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 上午8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] chrome播放webrtc，画面出来卡主几秒后才能正常播放 (Issue #1824)





 
关键帧间隔搞小一些，即使能正常接收解码，接收端也是要收到关键帧才能解码的
 ffmpeg的x264 的关键帧间隔默认是250.。。  假设是25fps，也要10s才能确定有一个关键帧
