### ISSUE TITLE
最新版本的使用日志打印接口，出现无法解析的外部符号[技术咨询]

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#1826]
**咨询的功能模块**
- 打印日志

**咨询的具体内容和问题**
换了最新版的 出现打印日志的问题
![image](https://user-images.githubusercontent.com/19390025/180740283-4feeaa95-e2f5-46a5-a608-71e2fb722241.png)
我把库换回6月25号编译的版本就可以正常编译，换今天编译的就出现上面的问题，试了debug和release版本的都是这样的问题

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个好像是编译缓存的问题 我们在msvc的持续集成编译中是没问题的 建议你重新clone代码重新编译试试

**Comment by hh-kai** [comment]
重新clone了代码，并且全部编译成功，试了，只要是使用了DebugL、InfoL这种方式的日志输出就会出现上面的错误；
但是使用log_debug(*)这样的日志方式，就没问题。
换回旧版的6.25号clone编译的，没有任何问题
编译时候的代码和编译脚本都没有改动过


测试的时候还发现，只要打开了hls，无论是否有播放，都会导致程序异常退出(有时半小时就会退出，有时2、3个小时才会退出)，退出前都会打印 ‘Stamp expired is abnormal:22000000’；我看了这个时间大概是在22*1000*1000左右
不打开hls，播放ts、fmp4、ws这些流，几个小时，几十个小时的播放都不会出现问题，主要使用的播放vlc、ffplay、potplay和网页同时播放这些流。
上面的测试都是测试了几天的结果

**Comment by xia-chu** [comment]
你都是windows下测试吗？程序异常退出有捕获到崩溃代码行吗？另外听你的意思是 你基于zlm做了二次开发？

**Comment by hh-kai** [comment]
都是windows下的
试过debug版本的，但是一直没有运行起来，现在知道就是退出前肯定会打印'Stamp expired is abnormal'这个
用的mk_api做二次开发的

**Comment by xia-chu** [comment]
打印Stamp expired is abnormal 没关系的

**Comment by xia-chu** [comment]
二次开发需要自己debug定位bug

**Comment by hh-kai** [comment]
好的 我自己再测试看看
