### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by WXMENG** [ZLMediaKit/ZLMediaKit#1830]
搜索文件系统，获取流对应的录像文件列表或日期文件夹列表
/index/api/getMp4RecordFile
写了自定义搜索路径：customized_path，为什么还是配置文件默认路径？
![image](https://user-images.githubusercontent.com/36003303/180939439-d6f17f5e-df76-4413-85f4-5600b7b1ead6.png)
![image](https://user-images.githubusercontent.com/36003303/180920129-224cf105-3ba6-464c-86a6-9e9a79dd9da1.png)
![image](https://user-images.githubusercontent.com/36003303/180920200-cbafeb3e-660a-45ec-bbe5-0f5563a832fa.png)

**Comment by xiongguangjie** [comment]
代码要最新的
