### ISSUE TITLE
[技术咨询]webrtc接口请求响应时长问题

### ISSUE THREAD

**Issue by boxinl** [ZLMediaKit/ZLMediaKit#1843]
**咨询的功能模块**
- 前端页面请求接口/index/api/webrtc响应时长问题。

**咨询的具体内容和问题**
- 前端页面请求接口/index/api/webrtc（同一个已经注册好的RTSP流），有时响应就几毫秒，有时就要几秒，为何会出现这种不一样的响应时间，服务器与客户端都是千兆网。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
响应几秒是因为这个流在zlm上开始并不存在；等这个流注册了，zlm才会立即返回

**Comment by xia-chu** [comment]
你是按需拉流还是按需推流？你是wvp用户？

**Comment by boxinl** [comment]
大佬，我在config.ini设置rtsp_demand=0，这个流已经注册好的了。不是wvp用户，我怎么判断按需拉流还是按需推流？我用接口addStreamProxy注册RTSP流，再到页面进行调用/index/api/webrtc，多次调用/index/api/webrtc播放的时候不会秒开视频观看。RTSP流会有丢帧情况，这会影响webrtc秒开播放吗（刚好RTSP流丢帧，zlm没有成功获取到流）

**Comment by xia-chu** [comment]
你addStreamProxy拉的什么流？如果是rtsp流 需要设置配置文件 directProxy=0

**Comment by boxinl** [comment]
RTSP流，配置文件也设置了directProxy=0。另外若是第一次流注册后再调用/index/api/webrtc播放，为何这段响应会慢呢，有时需要等待3秒以上，会给人体验不好。
{
  "aliveSecond": 65,
  "app": "rtsp",
  "bytesSpeed": 236519,
  "createStamp": 1659322384,
  "isRecordingHLS": false,
  "isRecordingMP4": false,
  "originSock": {
    "identifier": "",
    "local_ip": "192.168.4.150",
    "local_port": 62938,
    "peer_ip": "192.168.4.150",
    "peer_port": 35555
  },
  "originType": 4,
  "originTypeStr": "pull",
  "originUrl": "rtsp://192.168.4.150:35555/live/20",
  "readerCount": 0,
  "schema": "rtsp",
  "stream": "4f800def-401b-401d-8563-1e61a01aa625_1",
  "totalReaderCount": 0,
  "tracks": [
    {
      "codec_id": 0,
      "codec_id_name": "H264",
      "codec_type": 0,
      "fps": 25,
      "height": 288,
      "loss": -1,
      "ready": true,
      "width": 720
    },
    {
      "channels": 1,
      "codec_id": 2,
      "codec_id_name": "mpeg4-generic",
      "codec_type": 1,
      "loss": -1,
      "ready": true,
      "sample_bit": 16,
      "sample_rate": 8000
    }
  ],
  "vhost": "__defaultVhost__"
}

**Comment by xia-chu** [comment]
之前directProxy=1直接代理时GOP缓存是失效的；刚修复这个问题了，你更新代码吧

**Comment by boxinl** [comment]
感谢作者修复问题。但我这实际应用上还是有个问题，RTSP流已经通过/index/api/addStreamProxy这个注册好，调用接口/index/api/webrtc播放响应也是毫秒级，同一个已经注册好的流播放（播放前会调用videoplayer.close(),videoplayer=null）点击多次播放，网页端使用ZLMRTCClient.js会显示connecting到connected这个时间有时快（毫秒级），有时慢（超过3秒），这个能帮忙查看下是什么问题吗

**Comment by xia-chu** [comment]
connecting到connected慢这个问题可以通过udp抓包分析下。你抓包下目标端口8000的udp看看

**Comment by boxinl** [comment]
用wireshark过滤udp.port==8000，发现Protocal里STUN开始发送到UDP接收的这两个的Arrival Time时间间隔有时会超过300ms，更长的是超过500ms，同样RTCP到UDP也会这样的问题。还有现象，发送STUN的时候，也会发DTLSv1.2

**Comment by xia-chu** [comment]
能否把抓包上传上来 或者截个图？
看你的描述，是浏览器发送比较慢吗还是zlm回复慢？

**Comment by boxinl** [comment]
![1](https://user-images.githubusercontent.com/61399749/182367169-5e9fe1fe-488e-473f-b66b-ef6a01033843.png)
![2](https://user-images.githubusercontent.com/61399749/182367187-9d796198-3f35-4e91-82ef-8c58ba75acbd.png)
![3](https://user-images.githubusercontent.com/61399749/182367221-c20c9c5e-042e-4a91-a455-58ba5cdce944.png)
![4](https://user-images.githubusercontent.com/61399749/182367230-69f7b646-a569-4f19-95a0-e989b756997a.png)
![5](https://user-images.githubusercontent.com/61399749/182367233-3126a9d2-75d0-47fa-8ab1-40095cd1da10.png)
![6](https://user-images.githubusercontent.com/61399749/182367236-12fc5b45-c801-4adf-8e5c-b8a3f2076d7e.png)
![7](https://user-images.githubusercontent.com/61399749/182367241-4b298b26-6020-4b97-95e0-945b6e54df05.png)
![8](https://user-images.githubusercontent.com/61399749/182367246-34ff69b7-54b3-476c-8090-c8c19a5810a7.png)
![9](https://user-images.githubusercontent.com/61399749/182367250-b6058129-c327-48eb-beed-099a5c001abd.png)
![10](https://user-images.githubusercontent.com/61399749/182367253-f2f076f0-60c5-48e5-aaa5-9ab57d442287.png)
![11](https://user-images.githubusercontent.com/61399749/182367257-128b9b7e-4056-4d1e-97d8-aae39cb0fd3b.png)

**Comment by boxinl** [comment]
大佬您看下是否还需要补充什么内容吗。另外QQ加您好友，关于定制功能的那个验证，麻烦通过下

**Comment by xia-chu** [comment]
看日志 zlm还是回复的很快啊

**Comment by boxinl** [comment]
> 看抓包截图 zlm还是回复的很快啊

部分还是会超500ms的响应。对了第一次注册调用addStreamProxy到/index/api/webrtc这段时间是否可以优化呢，16路视频在大屏上播放看都是要等待几秒后才能观看

**Comment by xia-chu** [comment]
> > 看抓包截图 zlm还是回复的很快啊
> 
> 部分还是会超500ms的响应。对了第一次注册调用addStreamProxy到/index/api/webrtc这段时间是否可以优化呢，16路视频在大屏上播放看都是要等待几秒后才能观看

已经是最佳优化了 你要观察zlm的日志 看onAllTrackReady耗时

**Comment by boxinl** [comment]
根据您说的观察zlm的日志 看onAllTrackReady耗时，我去测试了下addStreamProxy接口，onAllTrackReady平均耗时会超过3秒以上，若某个流断开后zlm重新拉流也是需要那么长时间。
![微信截图_20220804153517](https://user-images.githubusercontent.com/61399749/182794708-a24b6bb3-4a5d-442a-a6e6-0f952fe4f7cb.png)
![微信截图_20220804153955](https://user-images.githubusercontent.com/61399749/182794722-925ed97a-afa0-412a-b3d7-c3bffc553f24.png)
![微信图片_20220804153609](https://user-images.githubusercontent.com/61399749/182794728-45325f8b-a7f1-4cfd-9f18-b5d11288d087.png)
![微信图片_20220804153657](https://user-images.githubusercontent.com/61399749/182794733-05f4eb69-e4f5-4949-9663-f5ea6d8558c8.png)
![微信图片_20220804153824](https://user-images.githubusercontent.com/61399749/182794738-f5b201a7-abe5-4ac6-b914-640e59ff325d.png)
![微信图片_20220804153913](https://user-images.githubusercontent.com/61399749/182794740-b84253aa-615e-44f2-80af-364d299105c8.png)

**Comment by xia-chu** [comment]
onAllTrackReady耗时太长导致注册很慢 你可以先禁用音频试试

**Comment by boxinl** [comment]
> onAllTrackReady耗时太长导致注册很慢 你可以先禁用音频试试

禁用音频确实提升了，有部分流因为不稳定，onAllTrackReady耗时还是会很长，这个您是否有什么方法优化

**Comment by xia-chu** [comment]
> > onAllTrackReady耗时太长导致注册很慢 你可以先禁用音频试试
> 
> 禁用音频确实提升了，有部分流因为不稳定，onAllTrackReady耗时还是会很长，这个您是否有什么方法优化

你可以修改下配置： https://github.com/ZLMediaKit/ZLMediaKit/blob/master/conf/config.ini#L89

**Comment by boxinl** [comment]
> 这个值wait_add_track_ms设置多少比较合适。0ms是否可行

**Comment by xia-chu** [comment]
> > 这个值wait_add_track_ms设置多少比较合适。0ms是否可行

干1000秒即可

**Comment by boxinl** [comment]
好的。感谢大佬。QQ的跟您说的事，麻烦您考虑下！
