### ISSUE TITLE
RTSP流在播放端使用UDP多播进行播放的技术问题

### ISSUE THREAD

**Issue by TaoHanny** [ZLMediaKit/ZLMediaKit#1844]
夏大，您好，首先要感谢您开源了这么优秀的项目供我们使用。针对你在这个 #24 issue回复的，使用ijkPlayer通过UDP_组播的方式拉取RTSP流，我目前遇到一个问题。
 
> > 所以，基于WiFi场景，可能没法很好的满足这个场景的需求吗？
> 
> 如果你是高清节目，那么rtp组播可能会丢包，具体还要你自己测试才好。 你可以用ijkplayer播放器测试下，它是基于FFmpeg的，支持rtsp组播

我知道在PC上使用ffplay 播放RTSP流，只需要设置`-rtsp_transport udp_multicast`参数就行了。

但是在ijkPlayer_Android项目中使用`-rtsp_transport`这个参数时，只能指定使用’TCP‘或者‘UDP’,并没有‘udp_multicast’这个选项，而且ijkPlayer0.8.8的协议列表中，我也没看到这个相关协议，协议列表如下：

![image](https://user-images.githubusercontent.com/30739724/182031675-e04be590-3b08-4d64-8219-36c61fe9f29c.png)

请问这个RTSP流在ijkplayer中需要如何处理才能实现UDP多播呢？我在ijkplayer下查了一圈，没找到相关的信息。

**Comment by wasphin** [comment]
我觉得这个问题还是去 ijkplayer 问比较好

**Comment by xia-chu** [comment]
已在 #24 答复此问题。

@wasphin ijkplayer是bilibili开源的项目 都停止维护好几年了 open状态的issue和pr都好几千了
