### ISSUE TITLE
[技术咨询][编译问题]

### ISSUE THREAD

**Issue by clpz299** [ZLMediaKit/ZLMediaKit#1847]
环境
Win 10 
VS2022
CMake 3.22

![(DZOS~XFB{~}6F(1GXCH)X5](https://user-images.githubusercontent.com/30864698/182076627-746b64a6-9c41-40be-a6c0-0ab7f14a593e.png)

##编译发生错误求助

**Comment by wasphin** [comment]
日志麻烦贴全，现在只能看到是检测某个依赖时出错了，不确定是检测的什么依赖。

也可以更新代码并清楚缓存后试试。

**Comment by clpz299** [comment]
> 日志麻烦贴全，现在只能看到是检测某个依赖时出错了，不确定是检测的什么依赖。
> 
> 也可以更新代码并清楚缓存后试试。

严重性	代码	说明	项目	文件	行	禁止显示状态
错误		CMake Error at F:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "F:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x64/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: F:/wvp/ZLMediaKit/out/build/x64-Debug/CMakeFiles/CMakeTmp
    
    Run Build Command(s):F:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe cmTC_43096 && [1/2] Building C object CMakeFiles\cmTC_43096.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_43096.exe
    FAILED: cmTC_43096.exe 
    cmd.exe /C "cd . && "F:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_43096.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- "F:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\link.exe" /nologo CMakeFiles\cmTC_43096.dir\testCCompiler.c.obj  /out:cmTC_43096.exe /implib:cmTC_43096.lib /pdb:cmTC_43096.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_43096.dir/manifest.res CMakeFiles\cmTC_43096.dir/manifest.rc" failed (exit code 0) with the following output:
    系统找不到指定的文件。
    ninja: build stopped: subcommand failed.
    
    

  

  CMake will not be able to correctly generate this project.		F:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake	69

**Comment by clpz299** [comment]
@wasphin 这是控制台中的完整日志，提示缺少cmTC_xxx.exe  不太清楚这是什么

**Comment by wasphin** [comment]
> @wasphin 这是控制台中的完整日志，提示缺少cmTC_xxx.exe 不太清楚这是什么

这个是 CMake 检测某些依赖时执行的测试编译程序。上面还有其他日志输出吗？

**Comment by clpz299** [comment]
> > @wasphin 这是控制台中的完整日志，提示缺少cmTC_xxx.exe 不太清楚这是什么
> 
> 这个是 CMake 检测某些依赖时执行的测试编译程序。上面还有其他日志输出吗？

没有了耶，全部贴出来了

**Comment by wasphin** [comment]
@clpz299 解决了吗？怎么解决的？

**Comment by clpz299** [comment]
没有解决，换了一种编译方式用cmake-gui编译后可以使用了




?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [技术咨询][编译问题] (Issue #1847)





 
@clpz299 解决了吗？怎么解决的？
