### ISSUE TITLE
[功能请求]zlm支持设置turn/stun服务器

### ISSUE THREAD

**Issue by jim-king-2000** [ZLMediaKit/ZLMediaKit#1849]
**描述该功能的用处，可以提供相关资料描述该功能**
我们希望能够使用WebRTC的turn/stun功能，在公网上安全的传输WebRTC视频流。这样，就可以通过zlm把RTSP/RTMP等其它格式的视频流，在公网上通过WebRTC安全的传输。

**描述你期望实现该功能的方式和最终效果**
该功能只需要通过zlm的API把turn/stun服务器的地址（或域名）设置到zlm即可。这个功能非常有必要，而且是WebRTC的标准场景。希望支持。谢谢。

**Comment by xiongguangjie** [comment]
现在不是这样吗，只支持ice-little 而已

**Comment by jim-king-2000** [comment]
> 现在不是这样吗，只支持ice-little 而已

如何设置？有文档吗？

**Comment by xia-chu** [comment]
> > 现在不是这样吗，只支持ice-little 而已
> 
> 如何设置？有文档吗？

下载zlm只支持ice-little 模式；也就是zlm必须在公网上(对客户端可见)；所以这种方式是不需要turn/stun服务器的；
只要ice-full模式(服务器在内网中)才需要turn/stun服务器

**Comment by jim-king-2000** [comment]
绝大多数国内的办公环境，都是NAT。所有的机器共享一个Internet出口，并且IP是会变化的。需要固定公网IP的话，要么去运营商申请，要么上云。换句话说，媒体服务器在这样的环境下，想要视频流出局域网，是非常麻烦的。此外，公网上暴露zlm的IP，相对而言也不够安全。因为我们只需要WebRTC上公网，并不希望其它功能上公网。

我们希望能够率先做出创新。让NAT网络能够轻易地跨网远程传输视频。那么turn/stun是一个比较容易的选择。基本上属于一劳永逸的解决方案。并且对zlm的改动也并不大。准确的说，zlm只需增加一个配置即可支持。

除此之外，我们也有别的解决方案。我们可以再增加一层WebRTC的转发，公网走我们自己的WebRTC代理，然后WebRTC代理转发给zlm。但这样一来，2层转发会增加视频延时，而且方案复杂。

殷切希望zlm能增加一个turn/stun的配置项。我之前给该项目捐过1000元人民币。如果能够实现该功能，我愿意再捐赠2000元。

最后，zlm是一个非常棒的产品。希望zlm越做越好，打败其它开源媒体服务器。

**Comment by xia-chu** [comment]
好像并不是"增加turn/stun的配置项" 这么简单吧？你的意思只要把"turn/stun" icecandidate地址添加进sdp即可？

**Comment by jim-king-2000** [comment]
在创建`RTCPeerConnection`的时候，增加一个参数即可。
```javascript
myPeerConnection = new RTCPeerConnection({
  iceServers: [
    {
      urls: "stun:stunserver.example.org"
    }
  ]
});
```
这个参数的值可以来自配置文件，也可以来自发offer的时候附加的参数。你们可以自行选择。

**Comment by jim-king-2000** [comment]
@xia-chu 期待回复。

**Comment by xia-chu** [comment]
> 在创建`RTCPeerConnection`的时候，增加一个参数即可。
> 
> ```js
> myPeerConnection = new RTCPeerConnection({
>   iceServers: [
>     {
>       urls: "stun:stunserver.example.org"
>     }
>   ]
> });
> ```
> 
> 这个参数的值可以来自配置文件，也可以来自接收offer的时候附加的参数。你们可以自行选择。

没用的 因为zlm不接收开发端的icecand地址，客户端可以用任意地址访问zlm；客户端也可以在nat内，也无须stun/turn地址辅助即可直接与zlm通信，不过zlm必须要求在公网上

**Comment by jim-king-2000** [comment]
> 因为zlm不接收客户端的icecand地址

这句话我没太理解。是zlm对接stun/turn服务器在技术上做不到么？

**Comment by wasphin** [comment]
> > 因为zlm不接收客户端的icecand地址
> 
> 这句话我没太理解。是zlm对接stun/turn服务器在技术上做不到么？

不是技术上做不到，而是场景很有限，实现却又复杂，客户端是一个配置的事，但服务端不是。

**Comment by jim-king-2000** [comment]
> 不是技术上做不到，而是场景很有限，实现却又复杂，客户端是一个配置的事，但服务端不是。

WebRTC是P2P的，没有所谓的客户端和服务端。只要尝试连接的两端都设置了上述的stun/turn服务器，那么两边在交换candidate的时候，就可以把自己的外网IP发给对方。我们现在已经做了一个demo，在网页端连接zlm，并且网页端设置了stun服务器。我们能够看到，网页端会把自己的公私网ip全部都发给zlm。但是zlm只能获取自己的私网ip，并且只用自己的私网ip去连接网页的公网ip和私网ip，这当然是连不通的。现在就差把stun服务器设置给zlm了。

至于场景，其实是非常的广阔。现在家用和企业网全部都是NAT，并且公网IP会隔一段时间变化一次。在这种场景里，是没有办法使用现有的zlm的方案的。那么zlm只能上云，导致企业网和家用网其实没有直连，流量上下都走云，就会产生额外的费用。

**Comment by xia-chu** [comment]
没办法 目前zlm做不到p2p, 你可以了解下janus，它支持内网部署

**Comment by jim-king-2000** [comment]
好吧。希望你们能够早日支持P2P。
