### ISSUE TITLE
关于配置文件中[general]>>[modifyStamp]的疑问

### ISSUE THREAD

**Issue by zhu-jiaquan** [ZLMediaKit/ZLMediaKit#1850]
在此感谢作者的无私奉献！！！

**咨询的功能模块**
- 关于配置文件中[general]>>[modifyStamp]的疑问

**咨询的具体内容和问题**
- 我的使用场景是拉取摄像头的rtsp转flv在H5中播放
- 部分型号摄像头播放一段时间后刷新页面重新加载，发现视频加载的时间特别长，于是就尝试修改了配置modifyStamp=1。
- 修改后效果明显，但随之而来又有另外一个问题，对接海康部分型号摄像头的时候，出现播放异常，异常可见附件。
- 此时将modifyStamp改回0，又加载正常了。
- 在此想请教下，这个modifyStamp配置具体的意义在哪，另外以上所描述的问题是否有解法？
- 望指教。
[zlm错误日志.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/9233392/zlm.txt)

**Comment by xia-chu** [comment]
modifyStamp后面我改成单个流可配置的吧 目前来说，全局配置作用不大

**Comment by monktan89** [comment]
m
