### ISSUE TITLE
[技术咨询]  ZLMediaKit无法接收海康威视Ehome RTP推流

### ISSUE THREAD

**Issue by longxinmengfei** [ZLMediaKit/ZLMediaKit#1855]
**咨询的功能模块**
- 使用海康威视的Ehome2.0 RTP推流给ZLMediaKit

**咨询的具体内容和问题**
- 打印错误日志如下：
-  **GB28181Process.cpp:116 inputRtp | rtp payload type未识别(1),已按ts或ps负载处理**
-  **RtpSession.cpp:116 onRtpPacket | invalid rtp version，开始搜索ssrc以便恢复上下文**
-  **RtpSession.cpp:62 onError | 1-500(192.168.120.16:25060) DC654B32 remain data size is too huge, now cleared:1052670**
-  **RtpProcess.cpp:54 ~RtpProcess | DC654B32(192.168.120.16:25060) RTP推流器(__defaultVhost__/rtp/DC654B32)断开,耗时(s):0**

请问这是bug还是我设置出问题了，非常感谢！
![微信截图_20220804152036](https://user-images.githubusercontent.com/18612497/182787886-bfb4ee0f-b9b6-4fcf-a709-e802823fb858.png)

**Comment by xia-chu** [comment]
Ehome协议我没测试过 这个是其他贡献者提的pr。。。

**Comment by longxinmengfei** [comment]
感谢回复，我再努力找一下原因

**Comment by ZzzHekmatyar** [comment]
ehome2.0协议用子流码就可以接收到信息了，isup5.0协议直接gg

**Comment by laiguorong** [comment]
请问一下海康ehome推流是怎么推流？在海康ISUP能获取到字节流，要怎么才能推流到ZLMediaKit？通过采用RTP协议的客户端把字节流推流到服务？
