### ISSUE TITLE
[技术咨询]内网穿透问题咨询

### ISSUE THREAD

**Issue by zouyaoji** [ZLMediaKit/ZLMediaKit#1857]
**咨询的功能模块**
- 想咨询zlmediakit内网穿透相关的问题。

**咨询的具体内容和问题**

 我的情况是将zlm+wvp部署到同一个内网windows服务器上，编译部署成功。这个机器是虽然是内网机器，但有互联网，并且走一个公网ip映射了几百个端口到这个机器，我已经用到的端口都保证在映射范围内。
用外网的海康摄像头测试，通过GB28181协议推流。发现列表中能出来这个摄像头，但是播放视频流提示超时。经过我的排查，发现是配置中hook中设置的用于推给wvp的公网IP+端口在这台机器本身没通导致的。也就是这台机器没办法访问映射给它自己公网地址导致推流失败。

按理说这应该是网络问题，但人家营运商不给解决，想问这种情况下还有破解办法吗？我看跟这个需求有点像又不完全一样:
https://github.com/ZLMediaKit/ZLMediaKit/issues/1606

所以我想问问hook有类似的处理逻辑吗？

**Comment by zouyaoji** [comment]
研究wvp文档发现似乎支持，先睡觉，明天验证了来分享。

**Comment by zouyaoji** [comment]
已解决。有类似情况的同学可以在 尝试在
zlm配置文件的rtc选项设置内外网ip。

wvp的配置项设置

#zlm 默认服务器配置
media:
    # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId
    id:   你的id
    # [必须修改] zlm服务器的内网IP
    ip: 内网地址
    # [可选] 返回流地址时的ip，置空使用 media.ip
    stream-ip: 外网地址
    # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip
    sdp-ip: 外网地址
    # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip
    hook-ip: 内网地址

**Comment by xia-chu** [comment]
很多人不看wvp配置文件说明 会犯这种错误。

**Comment by zouyaoji** [comment]
嗯 确实。

不过这样也算不上完美解决，因为内网没法播放，完美方案还是要解决网络才行。
但我们主要是在外网看，也就没管他啦。

再次感谢有这么好的库存在。

**Comment by qilin2008201** [comment]
> 嗯 确实。
> 
> 不过这样也算不上完美解决，因为内网没法播放，完美方案还是要解决网络才行。 但我们主要是在外网看，也就没管他啦。
> 
> 再次感谢有这么好的库存在。



> 已解决。有类似情况的同学可以在 尝试在 zlm配置文件的rtc选项设置内外网ip。
> 
> wvp的配置项设置
> 
> #zlm 默认服务器配置 media: # [必须修改] zlm服务器唯一id，用于触发hook时区别是哪台服务器,general.mediaServerId id: 你的id # [必须修改] zlm服务器的内网IP ip: 内网地址 # [可选] 返回流地址时的ip，置空使用 media.ip stream-ip: 外网地址 # [可选] wvp在国标信令中使用的ip，此ip为摄像机可以访问到的ip， 置空使用 media.ip sdp-ip: 外网地址 # [可选] zlm服务器的hook所使用的IP, 默认使用sip.ip hook-ip: 内网地址


请问开放了那些公网端口的映射？我们开放了如下，
8000/udp, 1935/tcp,9000/udp,10000/tcp,10000/udp, 80/tcp, 443/tcp，554/tcp，不行。

send-port-range: 30000,30500需要公网端口映射吗？
谢谢
