### ISSUE TITLE
[功能请求]媒体流缓存，事件触发存文件

### ISSUE THREAD

**Issue by boxinl** [ZLMediaKit/ZLMediaKit#1859]
**描述该功能的用处，可以提供相关资料描述该功能**'
我们在现实业务中会有某些事件触发，通过调用API告知zlm存视频，存视频的时间段在触发事件前的N秒前，然后进行回放视频查看。希望zlm可以有缓存媒体流的功能和参数设置媒体流的缓存时间，比如10秒，一直缓存某个流的10秒内的视频帧，并可以调用API生成MP4文件。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
这个功能太定制化了 需要自己实现 我们不会再开源项目中实现这种功能的。
其实换种用法；你用hls也能实现这个功能，zlm开启hls后；总是会保留多少秒前的hls文件；这个时候你去拉hls流 正好是很多秒前的视频
