### ISSUE TITLE
[功能请求]index/api/getMediaList  该接口能否支持分页功能默认获取10条，start为0，count为10

### ISSUE THREAD

**Issue by oaup** [ZLMediaKit/ZLMediaKit#1860]
**描述该功能的用处，可以提供相关资料描述该功能**
index/api/getMediaList  该接口能否支持分页功能默认获取10条，start为0，count为10。
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
目前返回所有的媒体信息数据，不好做前端展示，如果1000个并发，一次请求返回4000个"originSock" 
**描述你期望实现该功能的方式和最终效果**
该接口能否支持分页功能默认获取10条，start为0，count为10。
用户可以每次请求getMediaList接口，根据pagesize和start来分页

**Comment by xiongguangjie** [comment]
这样做就很复杂了，不会加这种功能，可以通过webhook 自己做缓存

**Comment by xia-chu** [comment]
> 这样做就很复杂了，不会加这种功能，可以通过webhook 自己做缓存

主要是这种功能没法实现；因为数据可能一直在变的 怎么分页？分页排序用什么规则？这又不是数据库；怎么可能分页
