### ISSUE TITLE
rtsp丢包的话zlmediakit有HTTP API接口可以查看丢包率吗？图像数据走TCP或UDP推流端和ZLMediaKit都要设置吗？

### ISSUE THREAD

**Issue by jellygithub** [ZLMediaKit/ZLMediaKit#1861]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- 各位大佬好！问题可能有点小白，请问rtsp丢包的话zlmediakit有HTTP API接口可以查看丢包率吗？图像数据走TCP或UDP推流端和ZLMediaKit都要设置吗？我用的gstreamer的rtspclientsink好像只能设置tcp+udp-mcast+udp模式（应该是控制tcp+图像udp）

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
ZLM rtsp 支持tcp,推流端与拉流端来控制的,rtsp 没有获取丢包率的接口
