### ISSUE TITLE
[技术咨询] zlm推流后播放器缓存问题

### ISSUE THREAD

**Issue by poonweif** [ZLMediaKit/ZLMediaKit#1862]
**咨询的功能模块**
 RTMP推流，缓存播放

**咨询的具体内容和问题**
大神您好，请问解码文件以RTMP方式推流到ZLM，然后播放器进行播放。比如在3分钟内已经把30分钟的帧数据都推到ZLM，ZLM的录像文件也正常，这种情况下播放器可实现帧缓存吗？

**Comment by xia-chu** [comment]
如果你按照非正常数据推流到zlm zlm也会正常转发；至于你播放器正不正常；要看你播放器怎么实现了
