### ISSUE TITLE
[技术咨询] 拉rtsp流，怎么转flv/http-flv

### ISSUE THREAD

**Issue by LIUJINWEN01** [ZLMediaKit/ZLMediaKit#1864]
你好，根据文档，使用restful接口addStreamProxy可以把rtsp流转hls,rtmp，但不知道怎么转成flv/http-flv。是需要使用restfule接口的addFFmpegSource吗？使用接口addFFmpegSource的性能怎么样?

**Comment by xia-chu** [comment]
> ddStreamProxy可以把rtsp流转hls,rtmp，但不知道怎么转成flv/http-flv。是需要使

默认全转；请阅读wiki url规则篇
