### ISSUE TITLE
[技术咨询]录制的视频，通过http点播黑屏

### ISSUE THREAD

**Issue by WXMENG** [ZLMediaKit/ZLMediaKit#1868]
![image](https://user-images.githubusercontent.com/36003303/183597504-6561eef0-768d-4883-abf7-17c16edd8deb.png)
直接点击文件播放，没问题
![image](https://user-images.githubusercontent.com/36003303/183602962-f4582541-8b9c-4b33-8c8d-df79546c242f.png)

**Comment by xiongguangjie** [comment]
视频编码格式有问题吧，是265的？？？？

**Comment by WXMENG** [comment]
视频是使用默认的配置、rtsp拉流进行录制的，怎么查看修改视频编码格式……

**Comment by x-x-p** [comment]
chrome浏览器还不支持hevc解码， 可以下载开源的[chromium浏览器](https://github.com/StaZhu/enable-chromium-hevc-hardware-decoding/releases)

**Comment by funbinary** [comment]
> 视频是修改使用默认的配置、rtsp拉流进行录制的，如何查看视频编码格式……

可以使用ffmpeg查看和转码

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by xia-chu** [comment]
新版chrome话说已经支持265硬件解码了 issue先关了
