### ISSUE TITLE
[BUG]: 对接奥威亚平台，调用addStreamProxy导致zlm服务直接崩溃

### ISSUE THREAD

**Issue by zhu-jiaquan** [ZLMediaKit/ZLMediaKit#1869]
### 现象描述

在使用zlm拉取奥威亚平台的rtsp流的时候，mediaserver服务直接奔溃
### 如何复现?

1.使用windows开启mediaserver
2.调用addStreamProxy接口拉取奥威亚的rtsp流

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
1.使用vlc直接播放奥威亚rtsp流，视频正常，但是看消息发现音频处理异常，截图如下
视频正常：
![vlc播放奥威亚](https://user-images.githubusercontent.com/32922921/183641713-3be899d8-6b14-44ad-aa5c-d99de925ad9d.png)

音频异常：
![VLC播放奥威亚音频异常](https://user-images.githubusercontent.com/32922921/183641271-7c6098c0-cb77-471f-a86a-304868b5fc25.png)

2.调用addStreamProxy拉流时的日志内容如下，从日志上看没什么特殊的
[崩溃时的日志.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/9290116/default.txt)

3.通过收集windows的dmp信息，使用vs打开后发现在程序上处理有漏洞（本人不是c++开发人员，不知道有没有搞对），这里可以看出分母为0的时候~~
![企业微信截图_16600457539531](https://user-images.githubusercontent.com/32922921/183641430-2b108b07-1cee-437c-9cac-4169e3605d3c.png)

4.此时windows直接报zlm崩溃
![zlm崩溃](https://user-images.githubusercontent.com/32922921/183641396-0ba48baf-2710-454b-8c51-957d30aefd87.png)

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
window server 2016
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
将流暴露到公网上，否则无法调试，我的邮箱为xiong_panda@163.com 看情况好像是rtp封包没按照标准来，看看vlc直接播放会出现什么问题

**Comment by MQFountain** [comment]
没法暴露哦，给你个抓包数据，看看有没有办法模拟下。
[抓包信息.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9295683/default.zip)

**Comment by xia-chu** [comment]
这个流aac打包有问题，那个截图除0的bug已经很明显了 这个只能忽略音频了

**Comment by zhujiaquan-cn** [comment]
夏总，有时间的话可否尽快帮忙修复下？

**Comment by xia-chu** [comment]
你更新试试

**Comment by zhujiaquan-cn** [comment]
貌似还有些问题，现在服务不会崩溃了，但是webrtc的画面出不来。
![企业微信截图_16601113151208](https://user-images.githubusercontent.com/32922921/183826892-a3ec6fd9-c5fd-4f66-93a1-f443145f2633.png)

**Comment by zhujiaquan-cn** [comment]
flv协议的视频可以播放，就是加载的时间会久一点

**Comment by xia-chu** [comment]
配置文件 directProxy改为0

**Comment by zhu-jiaquan** [comment]
感谢！！
