### ISSUE TITLE
[技术咨询]wvp + zlm 级联音频编码的问题

### ISSUE THREAD

**Issue by zouyaoji** [ZLMediaKit/ZLMediaKit#1870]
**咨询的功能模块**

- 想咨询 wvp + zlm 音频编码的问题。具体是有些平台作为下级级联到 wvp + zlm 平台音频编码变了。

**咨询的具体内容和问题**

我查了相关的内容，感觉和 https://github.com/ZLMediaKit/ZLMediaKit/issues/1801 有点像。

经过我测试情况是这样的：

1、首先说一下正常的情况：我有一个海康的设备，直接将设备走国标注册到wvp，视频正常播放，音频编码是 pcma，音频正常。如果作为下级 级联 给另外一个  wvp + zlm 的上级流媒体服务，发现也是 pcma，能正常播放。以下是截图是直连情况：
![image](https://user-images.githubusercontent.com/24430116/183669434-a8d1f2a5-4dbd-43e4-860d-de336ebfe6fa.png)

2、异常情况（1）：设备先注册到LiveGBS，然后作为下级 级联到wvp+zlm平台，音频编码就变了 成 mpeg4-generic，视频能正播放，无音频。下图是将设备注册到 LiveGBS 再级联推到wvp+zlm平台的，可见音频编码变成了 mpeg4-generic。

![image](https://user-images.githubusercontent.com/24430116/183670969-3830116c-412b-4370-bfc2-dd5118c21eae.png)

3、异常情况（2）：这也是我的实际情况，碰到这个问题了再才有的上面的2个测试。有的设备也无法直接注册到wvp，猜测是海康的ehome平台，只能作为级联的方式推给 wvp，音频编码也变成了 mpeg4-generic，视频能正播放，音频听不了。和2类似。
![image](https://user-images.githubusercontent.com/24430116/183672407-956cf32c-a6a3-4682-b0ce-2ee9119c4ab2.png)

目前确实不知道为什么会变这样，导致没有了音频，我问了海康人，得到的回复是他们平台只转发没重新编码。

![image](https://user-images.githubusercontent.com/24430116/183673133-f8801fa0-412a-431e-ba93-84523d61a2af.png)

目前主要就卡在音频上了，希望能在这儿得到一些线索。

**Comment by xia-chu** [comment]
说明zlm没收到音频数据 主动忽略了音频 但是配置文件默认添加静音aac音频了 所以你看到`mpeg4-generic`音频。
你可以修改zlm的配置文件，把 `general.addMuteAudio`置0。

**Comment by zouyaoji** [comment]
嗦嘎，general.addMuteAudio置 0，确实没看到音频了，那这就好确定原因了，应该是他们没推过来。

在 general.addMuteAudio 为 0 的情况下，如果对方推了音频过来就是有的是吧？

**Comment by xia-chu** [comment]
> 嗦嘎，general.addMuteAudio置 0，确实没看到音频了，那这就好确定原因了，应该是他们没推过来。
> 
> 在 general.addMuteAudio 为 0 的情况下，如果对方推了音频过来就是有的是吧？

没有 可能只是ps中声明有音频 但是没任何音频数据

**Comment by xia-chu** [comment]
> > 嗦嘎，general.addMuteAudio置 0，确实没看到音频了，那这就好确定原因了，应该是他们没推过来。
> > 在 general.addMuteAudio 为 0 的情况下，如果对方推了音频过来就是有的是吧？
> 
> 没有 可能只是ps中声明有音频 但是没任何音频数据；你可以观察zlm的日志 关注下`track not ready for a long time, ignored:`的日志

**Comment by zouyaoji** [comment]
![image](https://user-images.githubusercontent.com/24430116/183796435-4b089e15-afa8-4e2a-a049-99ba4e20dd95.png)

**Comment by xia-chu** [comment]
你这个是忽略了264 不算

**Comment by zouyaoji** [comment]
今天日志用这个关键字就搜到这一个~

**Comment by xia-chu** [comment]
你图片暴露了你zlm公网地址了

**Comment by zouyaoji** [comment]
问题不大 我这测试的 用完了就关了

**Comment by xia-chu** [comment]
> 今天日志用这个关键字就搜到这一个~

说明ps也没声明有音频啊

**Comment by zouyaoji** [comment]
那就是确定是海康平台推的时候没推音频了呗。

**Comment by baiyfcu** [comment]
> 那就是确定是海康平台推的时候没推音频了呗。

![image](https://user-images.githubusercontent.com/12823763/183816150-5f6de6e9-8fdf-4213-9df4-a1728f8f5e4a.png)
异常2中，可以看下livegbs中，是不是音频开关是关闭状态，默认是关闭

**Comment by zouyaoji** [comment]
> > 那就是确定是海康平台推的时候没推音频了呗。
> 
> ![image](https://user-images.githubusercontent.com/12823763/183816150-5f6de6e9-8fdf-4213-9df4-a1728f8f5e4a.png) 异常2中，可以看下livegbs中，是不是音频开关是关闭状态，默认是关闭


思路很对哈，异常2中 LiveGBS 就没音频。可能推到 LiveGBS 中是就丢了音频了。

主要是还看异常3。 海康自己的平台是有声音的。以国标推过来就没了。

**Comment by baiyfcu** [comment]
以上分析基本就明确了，级联推流没有音频数据

**Comment by zouyaoji** [comment]
嗯 我明天让朋友搞一下他的 LiveGBS看看能不能先把音频搞好再推过来。如果正常，更说明是海康平台推过来出来问题。

**Comment by zouyaoji** [comment]
@xia-chu 
大佬，再次请教一下。今天又来解决这个问题，通过抓包发现，海康应该是发了音频过来的，RTP协议，然后音频编码是 G722_1 格式的。是咱们不支持，所以丢失音频了吗？

**Comment by zouyaoji** [comment]
请忽视，就是不支持。我再想想办法

**Comment by xia-chu** [comment]
嗯 不支持 主要是转协议麻烦

**Comment by zouyaoji** [comment]
@xia-chu 大佬，help，有时间的话会考虑支持 G722 的音频编码吗？

海康平台级联过来的编码是 G722。我在他们平台配置转码成G711也不成。

![image](https://user-images.githubusercontent.com/24430116/189263429-d481c40e-b190-4b4c-a8e9-04871af78d5a.png)


但设备直接注册到wvp+zlm是G711的，先到海康平台，再过来就变G722了。海康同仁说这种情况要等适配，
很被动，希望咱们能直接支持G722的编码。

**Comment by xia-chu** [comment]
@zouyaoji 监控有没音频好像也不是那么重要吧 我也希望支持的编码格式越多越好 不过没太多时间精力去做这个

**Comment by zouyaoji** [comment]
@xia-chu 是应急行业，必须要音频呀 - - ，而且有对讲需求~

**Comment by xia-chu** [comment]
> @xia-chu 是应急行业，必须要音频呀 - - ，而且有对讲需求~

我建议你自己修改下zlm的源码 添加下对G722的支持，开源都是这么玩的，如果什么功能都寄托开源主要贡献者去实现，那我们要累死。

**Comment by zouyaoji** [comment]
好的 感谢

**Comment by xia-chu** [comment]
你是国标用户 应该只要实现ps容器对G722的支持 工作量不大的 只要封装下即可，第三方库应该已经支持G722了

**Comment by zouyaoji** [comment]
收到 我这边也跟我们开发反馈一下。感谢作者大大答复。

**Comment by xia-chu** [comment]
开发中有什么难题可以随时找我交流

**Comment by zouyaoji** [comment]
非常感谢
