### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by TristingChen** [ZLMediaKit/ZLMediaKit#1872]
环境：
wvp+zlm，centos环境，使用gb28181协议进行推流

现象:
1.wvp开启音频之后，设备本身选择音频编码aac，但是经过zlm推流之后的拉流地址中，使用vlc播放显示的却是pcm的音频编码
2.设备端的rtsp经过vlc拉流观看显示的确是aac的音频编码，证实设备音频编码是生效的

相关的抓包文件如下：

[服务端抓包.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9299877/default.zip)

经过wireshark解析qi'zho其中一次h264编码经过vlc的播放，显示的音频编码流：audio MPEG Layer 1/2 (mpga)
![image](https://user-images.githubusercontent.com/25541522/183899090-d4a04e36-e454-4f00-b960-17b0b70310c9.png)

请问该现象是什么原因造成的

**Comment by TristingChen** [comment]
通过mediainfo的工具分析设备推流到zlm的视频流，得出设备推流的音频格式的确是aac的，但是zlm却识别为pcma格式的音频
![a8c10c5683c0f0144f74b7ce2c236d5](https://user-images.githubusercontent.com/25541522/184078080-d2ecf360-0014-45f1-887d-3c06a339cefb.jpg)

**Comment by xiongguangjie** [comment]
我分析了这个封装stream type 为0x90是g711a 的音频表示，按照国标的标准定义

**Comment by xiongguangjie** [comment]
这个码流在国标上，识别为g711a 是正常的

**Comment by TristingChen** [comment]
那么请问：
1.该设备的国标推流听不到声音，但是摄像头自身的rtsp流却可以听到声音
2.为什么使用其他工具如：mediainfo,vlc播放解码，提示推流的音频依旧是aac啊

**Comment by xiongguangjie** [comment]
这个我也不清楚，你要问这个设备的厂家，按照ps的标准 stream type 为0x0f 才是aac。mediainfo 与vlc 为何识别为音频，我就不是很清楚了。摄像头的rtsp流与国标不是同一回事，要具体看国标的实现

**Comment by TristingChen** [comment]
请教一下，你用的什么工具来分析的ps流的编码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 上午10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [BUG]: BUG 现象描述 (Issue #1872)





 
这个我也不清楚，你要问这个设备的厂家，按照ps的标准 stream type 为0x0f 才是aac。mediainfo 与vlc 为何识别为音频，我就不是很清楚了。摄像头的rtsp流与国标不是同一回事，要具体看国标的实现

**Comment by xia-chu** [comment]
> 请教一下，你用的什么工具来分析的ps流的编码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZLMediaKit/ZLMediaKit" ***@***.***&gt;; 发送时间:&nbsp;2022年8月12日(星期五) 上午10:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [BUG]: BUG 现象描述 (Issue #1872) 这个我也不清楚，你要问这个设备的厂家，按照ps的标准 stream type 为0x0f 才是aac。mediainfo 与vlc 为何识别为音频，我就不是很清楚了。摄像头的rtsp流与国标不是同一回事，要具体看国标的实现 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这种一般通过代码调试

**Comment by TristingChen** [comment]
好的，谢谢二位了；

我使用另一个国标平台livegbs,发现和zlm的音频编码识别是一致的，所以初步判断应该是设备端处理有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月12日(星期五) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [BUG]: BUG 现象描述 (Issue #1872)





  
请教一下，你用的什么工具来分析的ps流的编码
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZLMediaKit/ZLMediaKit" @.&gt;; 发送时间:&nbsp;2022年8月12日(星期五) 上午10:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [BUG]: BUG 现象描述 (Issue #1872) 这个我也不清楚，你要问这个设备的厂家，按照ps的标准 stream type 为0x0f 才是aac。mediainfo 与vlc 为何识别为音频，我就不是很清楚了。摄像头的rtsp流与国标不是同一回事，要具体看国标的实现 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这种一般通过代码调试
