### ISSUE TITLE
视频编码格式有问题吧，是265的？？？？

### ISSUE THREAD

**Issue by Searchld** [ZLMediaKit/ZLMediaKit#1873]
{
            "aliveSecond": 143587,
            "app": "test",
            "bytesSpeed": 248840,
            "createStamp": 1660035601,
            "isRecordingHLS": false,
            "isRecordingMP4": false,
            "originSock": {
                "identifier": "",
                "local_ip": "192.168.2.41",
                "local_port": 40023,
                "peer_ip": "192.168.190.109",
                "peer_port": 554
            },
            "originType": 4,
            "originTypeStr": "pull",
            "originUrl": "rtsp://***:****@1XX.XXX.X9/Streaming/Channels/1",
            "readerCount": 0,
            "schema": "rtsp",
            "stream": "444",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 8000
                },
                {
                    "codec_id": 1,
                    "codec_id_name": "H265",
                    "codec_type": 0,
                    "fps": 50,
                    "height": 1080,
                    "ready": true,
                    "width": 1920
                }
            ],
            "vhost": "__defaultVhost__"
        },
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/22090418/184047743-dd871756-e7e2-4d0c-899d-0f665074e4fa.png">

视频编码格式有问题吧，是265的？？？？
录制的时候能改编码吗？从哪个地方修改
_Originally posted by @xiongguangjie in https://github.com/ZLMediaKit/ZLMediaKit/issues/1868#issuecomment-1209256254_

**Comment by xiongguangjie** [comment]
你检查下视频编码格式

**Comment by xiongguangjie** [comment]
这个是h265的编码格式，我看json串的返回
