### ISSUE TITLE
[功能请求] 可以通过API获取RTP over UDP丢包率

### ISSUE THREAD

**Issue by swwheihei** [ZLMediaKit/ZLMediaKit#1877]
**描述该功能的用处，可以提供相关资料描述该功能**
互联网上使用RTP over UDP时，丢包率很高，经常导致播放效果不理想，但很多老设备又不支持RTP over TCP。
现在想要通过api统计丢包率，RESTful API或者 HOOK API均可。

我看刚合并的代码提供了相关统计 - 新增rtp udp收流增加丢包率 #1829
https://github.com/ZLMediaKit/ZLMediaKit/pull/1829
@dcan123 
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

如能提供，非常感谢！

**Comment by energyjry** [comment]
获取RTP over UDP 丢包率的新功能已经验证。但是只对多端口收流模式有效，能否把单端口收流的丢包率也加上？

**Comment by xia-chu** [comment]
> over UDP 丢包率的新功能已经验证。但是只对多端口收流模式有效，能否把单端口收流的丢包率也加上？

后面考虑都加上下

**Comment by xia-chu** [comment]
已经实现
