### ISSUE TITLE
[技术咨询]  我们需要ipv4, 请问这种只监听ipv6怎么使用？ 要怎么配置？

### ISSUE THREAD

**Issue by qihuagao** [ZLMediaKit/ZLMediaKit#1878]
请问这种只监听ipv6怎么使用？ 要怎么配置？
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/12494341/184295002-53bc6955-0d22-41cb-b7fa-897ff3c4f718.png">

**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个只能修改代码 目前是ipv4/ipv6都打开的
