### ISSUE TITLE
[技术咨询]我配置了SSL和域名，但是为什么播放器里面提供的地址还是IP的？

### ISSUE THREAD

**Issue by yunjianyao** [ZLMediaKit/ZLMediaKit#1879]
**咨询的功能模块**
- 域名转发与播放

**咨询的具体内容和问题**
- 我配置了SSL和域名，但是为什么播放器里面提供的地址还是IP的？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你这个问题我摸不着头脑 你是不是想问wvp的问题？
