### ISSUE TITLE
[BUG]: Cmake 文件修改后, MediaKit_Root 未设置导致打包或者安装失败

### ISSUE THREAD

**Issue by snysmtx** [ZLMediaKit/ZLMediaKit#1882]
建议修改:
`src/CMakeLists.txt`

修改内容:
1. 设置 `MediaKit_Root` 路径为当前路径;
2. 将文件中的 `CMAKE_CURRENT_SOURCE_DIR` 替换为`MediaKit_Root`;

**Comment by xia-chu** [comment]
@wasphin 请解答下

**Comment by wasphin** [comment]
@snysmtx 理由呢？

**Comment by snysmtx** [comment]
未设置 `MediaKit_Root`, 导致安装时路径是根目录, 直接安装了整个系统

**Comment by wasphin** [comment]
一会儿我检查下
