### ISSUE TITLE
[技术咨询] 播放鉴权

### ISSUE THREAD

**Issue by LIUJINWEN01** [ZLMediaKit/ZLMediaKit#1883]
你好，对于播放鉴权，MediaServer的hook有没有可以传递header中的token到认证服务器的方式？

hook触发on_play的鉴权，好像只能通过url链接传递参数，比如我想传递token，要放在url参数里（如/live/123/hls.m3u8?token=aaaaaxx），我的认证服务器才能接收到MediaServer传来的params中的token。但是，放在url好像不够安全，请问有没有其他方式？
![image](https://user-images.githubusercontent.com/38368113/184786190-d5ea2d6c-237b-4de2-b17b-30860272491f.png)

**Comment by xia-chu** [comment]
不能 因为播放协议很多种 on_play是通用的抽象的播放鉴权机制，有些播放协议就没header。

**Comment by xia-chu** [comment]
只能通过播放url来鉴权
