### ISSUE TITLE
[意见建议] cmake寻找头及其库的相关建议

### ISSUE THREAD

**Issue by leo94666** [ZLMediaKit/ZLMediaKit#1885]
建议在.cmake文件里的find_path、find_library里添加**PATHS**变量，能更加准确的寻找三方库及其头文件

![image](https://user-images.githubusercontent.com/71742460/184793175-07eebd37-7432-488c-a506-75636235934c.png)

**Comment by xia-chu** [comment]
可以 欢迎提个pr @

**Comment by wasphin** [comment]
可以看是不是有更标准的查找方式，之前想用 pkg-config 找部分像 ffmpeg 这样的依赖，但好像部分平台不支持，可以参照 cmake 其他库的查找方式修改完善下
