### ISSUE TITLE
docker ZLMediaKit stop server to use ssl

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#1886]
I want to use rtsps  stream in the server.  and I run the docker. when the docker run, it auto run the ZLMediaKit. and I cannot give the 
parameter s.

**Comment by xia-chu** [comment]
目前docker就这么运行的 只能修改配置文件。启动参数其实也没啥需要给你指定的。

**Comment by fengmao31** [comment]
没法在docker里面配置-s启动rtsps流推送了。只能自己本地编译服务器了。

**Comment by fengmao31** [comment]
#882
这个问题提问者最后说通过 ENTRYPOINT 指定启动参数，能够docker安装情况下配置参数启动ssl模式服务器。这个是如何配置的参数的？

**Comment by xia-chu** [comment]
MediaServer不指定-s参数时，也会默认加载可执行文件当前目录下的default.pem证书文件 所以也不需要启动参数
