### ISSUE TITLE
[技术咨询] webrtc播放器播放aac编码音频出错

### ISSUE THREAD

**Issue by flowller** [ZLMediaKit/ZLMediaKit#1888]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
- 大佬，我在ffmpeg推送MP3文件，使用aac编码，用vlc可以播放用webrtc播放报错。
推流：
`ffmpeg -re -stream_loop -1 -i "test.mp3"  -acodec aac-ac 1 -ar 44100 -f rtsp -rtsp_transport tcp rtsp://192.168.111.160:30554/909094/test`
- 报错:
`{
   "code" : -400,
   "msg" : "Assertion failed: (have_active_media, 必须确保最少有一个活跃的track), function checkValid, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 1321."
}`

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by flowller** [comment]
目前单纯在webrtc播放音频的话只有pcm_alaw格式才能播放成功，且采样频率为8000，若采样频率超过8000播放出来的音质就会变形。

**Comment by flowller** [comment]
流列表的信息如下，是有track的
`{
    "code": 0,
    "data": [
        {
            "aliveSecond": 15,
            "app": "909094",
            "bytesSpeed": 747,
            "createStamp": 1660734230,
            "isRecordingHLS": true,
            "isRecordingMP4": true,
            "originSock": {
                "identifier": "34412-41",
                "local_ip": "10.244.112.60",
                "local_port": 554,
                "peer_ip": "192.168.111.160",
                "peer_port": 62053
            },
            "originType": 2,
            "originTypeStr": "rtsp_push",
            "originUrl": "rtsp://192.168.111.160:30554/909094/test",
            "readerCount": 0,
            "schema": "hls",
            "stream": "test",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "loss": -1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 44100
                }
            ],
            "vhost": "__defaultVhost__"
        },
        {
            "aliveSecond": 15,
            "app": "909094",
            "bytesSpeed": 178,
            "createStamp": 1660734230,
            "isRecordingHLS": true,
            "isRecordingMP4": true,
            "originSock": {
                "identifier": "34412-41",
                "local_ip": "10.244.112.60",
                "local_port": 554,
                "peer_ip": "192.168.111.160",
                "peer_port": 62053
            },
            "originType": 2,
            "originTypeStr": "rtsp_push",
            "originUrl": "rtsp://192.168.111.160:30554/909094/test",
            "readerCount": 0,
            "schema": "ts",
            "stream": "test",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "loss": -1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 44100
                }
            ],
            "vhost": "__defaultVhost__"
        },
        {
            "aliveSecond": 15,
            "app": "909094",
            "bytesSpeed": 50253,
            "createStamp": 1660734230,
            "isRecordingHLS": true,
            "isRecordingMP4": true,
            "originSock": {
                "identifier": "34412-41",
                "local_ip": "10.244.112.60",
                "local_port": 554,
                "peer_ip": "192.168.111.160",
                "peer_port": 62053
            },
            "originType": 2,
            "originTypeStr": "rtsp_push",
            "originUrl": "rtsp://192.168.111.160:30554/909094/test",
            "readerCount": 0,
            "schema": "rtsp",
            "stream": "test",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "loss": -1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 44100
                }
            ],
            "vhost": "__defaultVhost__"
        },
        {
            "aliveSecond": 15,
            "app": "909094",
            "bytesSpeed": 0,
            "createStamp": 1660734230,
            "isRecordingHLS": true,
            "isRecordingMP4": true,
            "originSock": {
                "identifier": "34412-41",
                "local_ip": "10.244.112.60",
                "local_port": 554,
                "peer_ip": "192.168.111.160",
                "peer_port": 62053
            },
            "originType": 2,
            "originTypeStr": "rtsp_push",
            "originUrl": "rtsp://192.168.111.160:30554/909094/test",
            "readerCount": 0,
            "schema": "rtmp",
            "stream": "test",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "loss": -1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 44100
                }
            ],
            "vhost": "__defaultVhost__"
        },
        {
            "aliveSecond": 15,
            "app": "909094",
            "bytesSpeed": 0,
            "createStamp": 1660734230,
            "isRecordingHLS": true,
            "isRecordingMP4": true,
            "originSock": {
                "identifier": "34412-41",
                "local_ip": "10.244.112.60",
                "local_port": 554,
                "peer_ip": "192.168.111.160",
                "peer_port": 62053
            },
            "originType": 2,
            "originTypeStr": "rtsp_push",
            "originUrl": "rtsp://192.168.111.160:30554/909094/test",
            "readerCount": 0,
            "schema": "fmp4",
            "stream": "test",
            "totalReaderCount": 0,
            "tracks": [
                {
                    "channels": 1,
                    "codec_id": 2,
                    "codec_id_name": "mpeg4-generic",
                    "codec_type": 1,
                    "loss": -1,
                    "ready": true,
                    "sample_bit": 16,
                    "sample_rate": 44100
                }
            ],
            "vhost": "__defaultVhost__"
        }
    ]
}`

**Comment by xiongguangjie** [comment]
webrtc web 端不支持aac

**Comment by flowller** [comment]
尊敬的朋友：     您好，多谢您的来信！     为了更好的学习工作，本人决定减少自己在电脑和智能手机上花费的时间，同时专注于生活的每一位朋友，每一处美景，每一个idea。故可能无法及时回复您的信息。     为了达到更好的交流效果：1、有急事？请电联我；2、重要的事？请短信联系我；3、联系电话：18813291622。     谢谢您的配合，祝您生活愉快！
