### ISSUE TITLE
[技术咨询]大华摄像机 GB方式拉流后 rtp流在一定时间后会断开

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#1896]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
GB28181

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

通过gb方式请求到大华摄像机的流后，播放一段时间后大华相机停止rtp推流

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by zhang-chuanfeng** [comment]
这与大华相机RTP推流有关吧   感觉与推流保活相关。我测试rtp推流后  大概接近3分钟会主动停止发送RTP流

**Comment by xia-chu** [comment]
> 机RTP推流有关吧 感觉与推流保活相关。我测试rtp推流后 大概接近3分钟

openRtpServer开启的udp端口是支持rtcp保活的
