### ISSUE TITLE
[技术咨询] 几个关于NAT穿透的问题

### ISSUE THREAD

**Issue by cjy123cjy** [ZLMediaKit/ZLMediaKit#1897]
**咨询的功能模块**
- NAT穿透

**当前的场景**
- 有相机端和监控端两部分，均在NAT后面；
- zlm部署在相机端，拉RTSP流，再以webRTC的REST API推出去；监控端通过公网调取webRTC的rest API，在web上显示画面。

**咨询的具体内容和问题**
- 我可以coturn+zlm结合着用吗？
我看[[功能请求]zlm支持设置turn/stun服务器](https://github.com/ZLMediaKit/ZLMediaKit/issues/1849) 里面说zlm只有ice-lite模式。我想确认一下，是不是没法这样结合着用。

- 可以用虚拟组网的方式来穿透吗？
因为公司的运维推荐了一款开源的穿透软件zerotier，这个的原理是不是跟coturn完全两码事。我用这种方式，使zlm对监控端可见，可以吗？

- 可以用ipsec vpn的方式来做穿透吗？
因为现在公司的网络就是用的ipsec的方式来做的，在ipsec环境下测试，感觉延迟和稳定性都挺不错的。但是我看没有人拿这种方式做，是因为成本比较高吗？

**参考过的issue**
- [[技术咨询]zlm的webrtc是否实现NAT穿越通信](https://github.com/ZLMediaKit/ZLMediaKit/issues/1721) (#1721)
- [[功能请求]zlm支持设置turn/stun服务器](https://github.com/ZLMediaKit/ZLMediaKit/issues/1849) (#1849) 这个issue没有看太懂，所以决定new一个issue咨询一下。issue里面夏楚大大提到的janus-gateway，我也尝试用过了，但是跟海康的IPC不太兼容：拉RTSP的流一直报401认证失败，拉bigbuckbunny的流也有问题。所以我还是决定用zlm。

**小白提问，可能概念理解有误，麻烦大佬指教啦！**

更新：
修改了一部分问题，我是不是理解有错误，把coturn（stun/turn服务器）和zerotier（虚拟组网vpn）混为一谈了。。。

**Comment by fengmao31** [comment]
虽然没看懂，但是提醒你webrtc可能存在h264转vp8。所以所有流程下来延迟可能800ms以上。最新版的webrtc才支持h264。低版本的需要手动写。总耗时不如纯rtsp的速度。
但纯rtsp流不带加密。而那个鉴权在身份认证上抗不了暴力攻击，也无法加密数据包。rtsps流zlmediakit仅仅是服务器证书认证，不是双向证书认证。服务器实现的对称加密加密rtp包的加密方式，感觉可能有风险。等我以后找点资料问问作者。

**Comment by cjy123cjy** [comment]
@fengmao31 额，大佬我没看懂。。

**Comment by fengmao31** [comment]
就是说你的方案可能存在转码，webrtc这样的速度还不如纯rtsp。但rtsp要另外做加密。

**Comment by cjy123cjy** [comment]
@fengmao31 好的受教了，但是外网这部分我还是要想个方法才是，如果把zlm放在公网上+IPC主动推流到zlm是不是就可以绕过stun/turn了？但是我又没找到主动推流的方法。。

**Comment by xia-chu** [comment]
@cjy123cjy 你能确保zlm公网可见 那么就能这样使用
