### ISSUE TITLE
[BUG]: mk_api动态库死锁

### ISSUE THREAD

**Issue by huangxiuqi** [ZLMediaKit/ZLMediaKit#1898]
### 现象描述

引入mk_api动态库时，程序卡死

### 如何复现?

引入最新代码编译动态库

### 相关日志或截图
调试发现红框这句导致死锁，回退至前一个版本则正常。
![image](https://user-images.githubusercontent.com/6236507/185866676-cdd36aae-4b91-4bda-9086-5575a67acd6c.png)
![image](https://user-images.githubusercontent.com/6236507/185867640-30474566-f047-4918-9a85-a983590227ed.png)

**Comment by xia-chu** [comment]
此问题已修复 请更新代码。
