### ISSUE TITLE
[技术咨询]编译成功后使用daemon模式运行HTTP访问超时

### ISSUE THREAD

**Issue by JunoGuan** [ZLMediaKit/ZLMediaKit#1900]
**Daemon模式下http访问超时**
在Debian11下编译成功,root用户使用-d参数启动后,日志正常输出,端口启动正常,访问http端口超时无响应
移除-d启动参数后,http访问恢复正常.
代码版本:c6a0e3ad66e3134ecbb1a9e476248f45912113f3

**Comment by xia-chu** [comment]
应该不会有这个问题

**Comment by JunoGuan** [comment]
在44ba971版本上测试已恢复正常

**Comment by JunoGuan** [comment]
问题已解除
