### ISSUE TITLE
[技术咨询] webrtc不支持H265？

### ISSUE THREAD

**Issue by flowller** [ZLMediaKit/ZLMediaKit#1901]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
- 在使用webrtc播放H265的视频流时只有声音没有画面，切换到H264后播放正常。请问webrtc是否不支持H265编码，如果想要支持H265需要做哪些设置，谢谢。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
ZLM支持，要播放器与浏览器支持，web浏览器是不支持的，可以使用metaRTC

**Comment by urmyfaith** [comment]
> ZLM支持，要播放器与浏览器支持，web浏览器是不支持的，可以使用metaRTC

web浏览器 使用wasm，修改ffmpeg 应该是支持的。
