### ISSUE TITLE
国标点播无人观看时未触发回调

### ISSUE THREAD

**Issue by jokbor** [ZLMediaKit/ZLMediaKit#1902]
### 现象描述

 级联点播时，上级国标和下级国标均无人观看视频，但是过一段时间（至少15分钟后）再去用下级国标看之前的视频流还可以播放

### 如何复现?

  此现状也是偶然发现，是通过国标级联方式拉取流，上级国标拉取流后一直播放着，但是部署上级国标的笔记本过一段时间会自动待机，待机后网络无法通讯，下级国标认为上级国标离线，然后关闭上级国标的推流操作，但是下级国标中的媒体服务对这个流还是认为一直有人观看，下面是我调取ZLM中的getMediaList接口查看的观看人数信息，其实没有一个协议是有人观看的，但是总观看人数任然为1

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
{
   "code" : 0,
   "data" : [
      {
         "aliveSecond" : 8170,
         "app" : "rtp",
         "bytesSpeed" : 263305,
         "createStamp" : 1661227237,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "34020000001310000001_34020000001310000001",
            "local_ip" : "::",
            "local_port" : 30043,
            "peer_ip" : "172.17.0.1",
            "peer_port" : 57021
         },
         "originType" : 3,
         "originTypeStr" : "rtp_push",
         "originUrl" : "rtp://__defaultVhost__/rtp/34020000001310000001_34020000001310000001",
         "readerCount" : 0,
         "schema" : "hls",
         "stream" : "34020000001310000001_34020000001310000001",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            },
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 25,
               "height" : 1080,
               "ready" : true,
               "width" : 1920
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 8170,
         "app" : "rtp",
         "bytesSpeed" : 263305,
         "createStamp" : 1661227237,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "34020000001310000001_34020000001310000001",
            "local_ip" : "::",
            "local_port" : 30043,
            "peer_ip" : "172.17.0.1",
            "peer_port" : 57021
         },
         "originType" : 3,
         "originTypeStr" : "rtp_push",
         "originUrl" : "rtp://__defaultVhost__/rtp/34020000001310000001_34020000001310000001",
         "readerCount" : 0,
         "schema" : "ts",
         "stream" : "34020000001310000001_34020000001310000001",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            },
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 25,
               "height" : 1080,
               "ready" : true,
               "width" : 1920
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 8170,
         "app" : "rtp",
         "bytesSpeed" : 264384,
         "createStamp" : 1661227237,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "34020000001310000001_34020000001310000001",
            "local_ip" : "::",
            "local_port" : 30043,
            "peer_ip" : "172.17.0.1",
            "peer_port" : 57021
         },
         "originType" : 3,
         "originTypeStr" : "rtp_push",
         "originUrl" : "rtp://__defaultVhost__/rtp/34020000001310000001_34020000001310000001",
         "readerCount" : 0,
         "schema" : "rtmp",
         "stream" : "34020000001310000001_34020000001310000001",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            },
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 25,
               "height" : 1080,
               "ready" : true,
               "width" : 1920
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 8170,
         "app" : "rtp",
         "bytesSpeed" : 275868,
         "createStamp" : 1661227237,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "34020000001310000001_34020000001310000001",
            "local_ip" : "::",
            "local_port" : 30043,
            "peer_ip" : "172.17.0.1",
            "peer_port" : 57021
         },
         "originType" : 3,
         "originTypeStr" : "rtp_push",
         "originUrl" : "rtp://__defaultVhost__/rtp/34020000001310000001_34020000001310000001",
         "readerCount" : 0,
         "schema" : "rtsp",
         "stream" : "34020000001310000001_34020000001310000001",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            },
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 25,
               "height" : 1080,
               "ready" : true,
               "width" : 1920
            }
         ],
         "vhost" : "__defaultVhost__"
      },
      {
         "aliveSecond" : 8170,
         "app" : "rtp",
         "bytesSpeed" : 259846,
         "createStamp" : 1661227237,
         "isRecordingHLS" : true,
         "isRecordingMP4" : false,
         "originSock" : {
            "identifier" : "34020000001310000001_34020000001310000001",
            "local_ip" : "::",
            "local_port" : 30043,
            "peer_ip" : "172.17.0.1",
            "peer_port" : 57021
         },
         "originType" : 3,
         "originTypeStr" : "rtp_push",
         "originUrl" : "rtp://__defaultVhost__/rtp/34020000001310000001_34020000001310000001",
         "readerCount" : 0,
         "schema" : "fmp4",
         "stream" : "34020000001310000001_34020000001310000001",
         "totalReaderCount" : 1,
         "tracks" : [
            {
               "channels" : 1,
               "codec_id" : 2,
               "codec_id_name" : "mpeg4-generic",
               "codec_type" : 1,
               "ready" : true,
               "sample_bit" : 16,
               "sample_rate" : 8000
            },
            {
               "codec_id" : 0,
               "codec_id_name" : "H264",
               "codec_type" : 0,
               "fps" : 25,
               "height" : 1080,
               "ready" : true,
               "width" : 1920
            }
         ],
         "vhost" : "__defaultVhost__"
      }
   ]
}
</pre>
</details>

**Comment by monktan89** [comment]
更新最新代码试试

**Comment by xia-chu** [comment]
调用startSendRtp接口，zlm也算是观看人数的。
