### ISSUE TITLE
[技术咨询] 推音频流时采样率不一致

### ISSUE THREAD

**Issue by flowller** [ZLMediaKit/ZLMediaKit#1905]
**咨询的功能模块**
- rtsp 音频推流

**咨询的具体内容和问题**
- 音频编码pcm_alaw 采样频率使用 44100 和 48000 推语音流。但是从流列表信息查看到的采样率一直都是8K。想问一下大神有没办法拿到采样率和推流时设置的采样率一致。aac编码格式没有此问题，因为webrtc不支持aac所以我使用的是pcma编码。

**Comment by xia-chu** [comment]
pcma最好就设置为8K，因为48K的是非标的，很多协议不支持非8K的pcma
