### ISSUE TITLE
[技术咨询]配置ssl证书后出现无法访问页面问题

### ISSUE THREAD

**Issue by zyftxwd** [ZLMediaKit/ZLMediaKit#1907]
配置了腾讯云申请的ssl证书后出现了----浏览器显示 使用了不受支持的协议， 协议不受支持
客户端和服务器不支持一般 SSL 协议版本或加密套件。
请问这个问题要怎样解决，感谢

**Comment by jokbor** [comment]
需要吧腾讯的证书放入到ZLM中，ZLM会比对腾讯和自己默认的证书是否一致，如果不一致则无法访问

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E7%94%9F%E6%88%90SSL%E8%87%AA%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6%E5%B9%B6%E6%B5%8B%E8%AF%95

**Comment by zyftxwd** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E7%94%9F%E6%88%90SSL%E8%87%AA%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6%E5%B9%B6%E6%B5%8B%E8%AF%95



我是直接指定腾讯云的pem文件启动的，但是出现了上述问题，但是那个不能直接使用，我合并他的文件后解决了问题，万分感谢







> 需要吧腾讯的证书放入到ZLM中，ZLM会比对腾讯和自己默认的证书是否一致，如果不一致则无法访问

万分感谢
