### ISSUE TITLE
[技术咨询] 返回的播放地址有时候是通道Id，有时候是流Id，请问是哪个配置影响了该功能

### ISSUE THREAD

**Issue by liugt34** [ZLMediaKit/ZLMediaKit#1910]
有时候是设备Id加通道ID，有时候又是流Id ,请问是哪里设置的问题么？
求解惑

![image](https://user-images.githubusercontent.com/8056013/186823008-ea6a5a5f-0094-4a11-b5cf-d516c71a529b.png)

![image](https://user-images.githubusercontent.com/8056013/186822884-fcf3eaf6-785d-45c7-8cda-2a078c1c3abd.png)

![image](https://user-images.githubusercontent.com/8056013/186822823-11542130-b779-4bce-81f9-3973cadc2302.png)

**Comment by xia-chu** [comment]
单端口模式就是使用ssrc做流id，
多端口就是用设备sip号。

**Comment by liugt34** [comment]
谢谢大佬解惑
