### ISSUE TITLE
[技术咨询]国标级联startSendRtp上级平台ignored: H264

### ISSUE THREAD

**Issue by jiamengyi** [ZLMediaKit/ZLMediaKit#1911]
**咨询的功能模块**
- startSendRtp

**咨询的具体内容和问题**
- 场景：国标级联，设备A-平台B-平台C-平台D，平台C和D媒体服务器均使用MediaServer，平台B、C、D均通过28181级联
- 现象：平台C点播设备A的实时视频可正常播放，平台D点播设备A的实时视频前端播放器黑屏，通过查看日志发现track not ready for a long time, ignored: H264，也就是说音频一直在播放、视频被忽略了。
- 初步分析：平台B推送到平台C的rtp流无音频，平台C的媒体服务器增加了静默音频。平台C推送到平台D的rtp流应该是需要很久才能收到包含sps、pps的帧，MediaServer应该在超过3秒后忽略了。
- 疑问：平台C收到rtp流后可正常解析并最终播放，而经过startSendRtp发送到平台D后却出现了上述问题，这个原因需要请求具体分析下。
以下是平台C推送到平台D的抓包文件：
传不上来。。。

**Comment by xia-chu** [comment]
这个问题的原因是GOP太大了，zlm在调用startSendRtp接口时，不会缓存gop，这样会导致zlm发送rtp不是从sps pps开始发送的，这个如果GOP太大的话，会导致D获取sps pps超时。
解决的方法就是修改D的配置参数，加大wait_track_ready_ms参数

**Comment by xiongguangjie** [comment]
在群里问过，就不要在这里问了

**Comment by jiamengyi** [comment]
> 这个问题的原因是GOP太大了，zlm在调用startSendRtp接口时，不会缓存gop，这样会导致zlm发送rtp不是从sps pps开始发送的，这个如果GOP太大的话，会导致D获取sps pps超时。 解决的方法就是修改D的配置参数，加大wait_track_ready_ms参数

修改D的配置参数，加大wait_track_ready_ms，需要等待20多秒，这个体验太差了。gop太大是B发过来的码流大吗？C从点播到显示大概3秒。B到C是tcp，C到D是udp，和这个有关系吗？还有GOP太大的话可以从源头解决吗？

**Comment by jiamengyi** [comment]
> 在群里问过，就不要在这里问了

现在这里发的，没等到回复，就在群里问了，不好意思。

**Comment by xia-chu** [comment]
GOP太大的话只能从源头设置

**Comment by xia-chu** [comment]
不过安防摄像头的GOP一般也就3~5秒而已 不会太大的

**Comment by jiamengyi** [comment]
> 不过安防摄像头的GOP一般也就3~5秒而已 不会太大的

是的，C的MediaServer一直没有问题，转发到D的MediaServer却有问题。能否给个邮箱，我把c收到的流和发出去的流抓包发您看看？

**Comment by xia-chu** [comment]
那奇怪了

**Comment by jiamengyi** [comment]
> 那奇怪了， 可以把D收到的rtp dump出来

c发出来的就有问题，我看sps pps很久才收到

**Comment by jiamengyi** [comment]
> 那奇怪了， 可以把D收到的rtp dump出来

而且我用c的MediaServer发送到c的MediaServer也是一样的问题

**Comment by xia-chu** [comment]
那可能ps生成有点问题

**Comment by jiamengyi** [comment]
[c-d.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441416/c-d.zip)
[b-c.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441425/b-c.zip)
以上是2个抓包

> 那可能ps生成有点问题

**Comment by xia-chu** [comment]
> [c-d.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441416/c-d.zip) [b-c.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441425/b-c.zip) 以上是2个抓包
> 
> > 那可能ps生成有点问题

需要用zlm本身的dump功能 你看下配置文件 搜索下dump字段

**Comment by jiamengyi** [comment]
> > [c-d.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441416/c-d.zip) [b-c.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441425/b-c.zip) 以上是2个抓包
> > > 那可能ps生成有点问题
> 
> 需要用zlm本身的dump功能 你看下配置文件 搜索下dump字段

好的

**Comment by jiamengyi** [comment]
> 需要用zlm本身的dump功能 你看下配置文件 搜索下dump字段

dump的文件可以发送到你邮箱嘛？

**Comment by jiamengyi** [comment]
> > [c-d.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441416/c-d.zip) [b-c.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9441425/b-c.zip) 以上是2个抓包
> > > 那可能ps生成有点问题
> 
> 需要用zlm本身的dump功能 你看下配置文件 搜索下dump字段

[rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9449237/rtp.zip)
dump的rtp文件

**Comment by xiongguangjie** [comment]
你这两个rtp dump 的包，我跑了都没问题c.rtp 马上就能注册上，马上就能播，d.rtp 需要等待5秒左右才能注册上，也能播
