### ISSUE TITLE
RingBuffer的write函数[技术咨询]

### ISSUE THREAD

**Issue by zhangjp0405** [ZLMediaKit/ZLMediaKit#1913]
你好，我在阅读RingBuffer.h源码的时候，发现RingBuffer类的write函数里会执行_storage->write()函数，而在_storage->write()函数前面一句RingReaderDispatcher::Ptr通过write函数又会 执行一次_storage->write()函数，这是不是多重复执行了一次_storage->write()函数。
![1661557553255](https://user-images.githubusercontent.com/48978473/187003812-af16ac58-4a01-4d47-b1cd-650bbaf10361.png)
![微信截图_20220827074453](https://user-images.githubusercontent.com/48978473/187003895-913c4c04-112c-4fdb-83a0-aa72f6b222b4.png)

**Comment by mtdxc** [comment]
两个_storage不是同一个，每个RingReaderDispatcher都有一个自己线程的_storage
详见RingReaderDispatcher的构造

**Comment by zhangjp0405** [comment]
> 两个_storage不是同一个，每个RingReaderDispatcher都有一个自己线程的本地_storage 详见RingReaderDispatcher的构造

*^_^*谢谢提醒！
