### ISSUE TITLE
[技术咨询] cluster.origin_url是否可以动态更新

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1914]
**咨询的功能模块**
- 集群模式

**咨询的具体内容和问题**
- cluster.origin_url发生变化是否可以不用重启，直接生效？我试过通过setServerConfig接口更新cluster.origin_url,如不不重启是无法生效的。这个后续有计划改为动态更新的嘛？因为如果每次增加或者减少源站，就需要重启服务器的话对客户端体验不太好。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
是可以生效的呀？？？

**Comment by mayomeng** [comment]
通过setServerConfig设置后，配置是改了，但是修改的内容貌似并没有被程序加载，需要重启后才能自动从源站拉流

**Comment by xiongguangjie** [comment]
程序代码上是生效的，可以动态更新的

**Comment by xiongguangjie** [comment]
把日志传上来

**Comment by xia-chu** [comment]
重载配置文件生效会打印`reload config`相关的日志的

**Comment by mayomeng** [comment]
应该是我传cluster.origin_url的时候没有encode【%s】，导致后台报错了
