### ISSUE TITLE
[技术咨询]请教本框架集成智能分析的思路和办法

### ISSUE THREAD

**Issue by zdz72113** [ZLMediaKit/ZLMediaKit#1915]
- 请教本框架集成智能分析的思路和办法

**咨询的具体内容和问题**
- 作者好，现在市面上常见的智能视频分析一般的输出：视频播放器里面把人脸或物体框起来，监控到特定物体或事件后台会生成报警。想咨询下本框架是否可以支持集成智能视频分析（比如修改代码，API等调用）？如果不支持集成的话，是不是需要先拿到ZLMediaKit的输出直播流后，再基于输出直播流进行智能分析，这样的话分析完我是不是还需要重新构建直播流呢？作者有没有什么好的思路和推荐呢？本人视频小白，如果有理解不对的地方请指正，谢谢。

**Comment by xia-chu** [comment]
ai分析相关代码需要涉及到编解码 、ai处理；建议使用`拉流->解码->抽帧->分析处理->输出结构化数据/或叠加视频元素->编码->推流`方式

**Comment by xia-chu** [comment]
可以直接用FFmpeg进行二次开发 没必要再zlm框架中实现
