### ISSUE TITLE
[BUG]: ZLM录像生成的文件时间与视频中的时间相差大

### ISSUE THREAD

**Issue by LMiracle** [ZLMediaKit/ZLMediaKit#1916]
### 现象描述
ZLM录直播流生成的文件，文件名的时间与视频中的文件时间相差大。
如，文件名为15-59-00.mp4，但是视频中的时间为16:00:04
多台设备的时间都是延迟了一分钟，请问文件名中的时间生成采用的是怎样的规则？

### 如何复现?
1.开启设备的视频流
2.ZLM进行拉流
3.开启ZLM的录像
4.获取ZLM生成的mp4视频切片
5.期望mp4视频切片的时间与视频中的录像视频时间一致

### 相关日志或截图
![image](https://user-images.githubusercontent.com/26618535/187151792-b8365859-1451-4513-9f42-cc14f371db83.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
无
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
1.多台摄像头，品牌有海康、同为、宇视
2.wvp信令服务器+ZLM
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:CentOS 7
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
说明你摄像头的时间不准

**Comment by LMiracle** [comment]
> 说明你摄像头的时间不准

但是多台设备都出现同样的问题，而且相差的时间都一样，请问ZLM生成这个时间是不是获取的是系统时间？

**Comment by xia-chu** [comment]
文件名根据zlm接收数据时的系统时间戳而来 跟视频内容完全无关
