### ISSUE TITLE
I can't play H265 stream after transcoding from IP camera (by FFmpeg) in NVR

### ISSUE THREAD

**Issue by benpar2** [ZLMediaKit/ZLMediaKit#1917]
Hello,

I use ZLMediaKit as the RTSP server for re-streaming the transcoded stream from the IP camera using FFmpeg. In my project after receiving the stream from IP cameras, I do transcoding for decreasing its bandwidth, and after transcoding I re-stream it.

Everything is fine when I use players like VLC for playing the transcoded stream (h264 and h265). But in the NVR there is a problem, only I can play the h264 (transcoded) stream, and I can't play the h265 transcoded stream. I noticed NVR (Hikvision) knows my h265 stream as an h264 stream!

The NVR can play the original h265 stream from the IP camera without using ZLMediaKit. I tried it with some cameras (different brands) and the NVR is OK with their h265 original streams (without transcoding).

I checked it with Dahua NVR, and the same issue is in there plus the h264 stream can't play smoothly, it has some lags, and the framerate is 1 fps!

The FFmpeg command is:
`ffmpeg -rtsp_transport tcp -i "rtsp://admin:Password1@192.168.1:12:554/Steaming1/Channel1/101" -vcodec hevc -profile:v main -b:v 500k -preset veryfast -acodec aac -b:a 32k -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test`

I would appreciate any help to solve the issue, playing the transcoded stream (H265) by ZLMediaKit/FFmpeg in NVR.

**Comment by xia-chu** [comment]
When i use ffmpeg push a mp4 file to zlmediakit by rtsp like this:
```bash
ffmpeg -re -i ~/Downloads/mp4/Quantum.mp4 -vcodec hevc -profile:v main -b:v 500k -preset veryfast -acodec aac -b:a 32k -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test
```

Then i play it by ffpay like this:
```bash
ffplay rtsp://127.0.0.1/live/test
```

It work very  fine:
<img width="1280" alt="图片" src="https://user-images.githubusercontent.com/11495632/187339202-bbfc8eda-fc11-4f00-8931-5aa8f1721bd5.png">

**Comment by benpar2** [comment]
@xia-chu Thank you for checking. Yes, I can play the transcoded stream by VLC and ffplay smoothly without any issues, but the problem is in NVR. I can't play h265 on Hikvision or Dahua NVR when I transcode it by FFmpegg, I don't know the reason, is it the codec problem or NVR?

**Comment by xia-chu** [comment]
Can you expose the URL of NVR to the public network？

**Comment by benpar2** [comment]
@xia-chu I can't, Unfortunately, my ports don't open to the public.

**Comment by xia-chu** [comment]
@benpar2 hey, do you know the project:  "https://github.com/fatedier/frp" ?

**Comment by benpar2** [comment]
@xia-chu Thank you. Good project, I will check it. Also, may I have your WeChat ID? I am in Shenzhen, and I'd like to send the NVR to you for the test because the web browser part of the NVR is different than the NVR, of course, if you agree about it. My email address is: behfarteam@gmail.com

**Comment by SuperCatss** [comment]
> @xia-chu Thank you for checking. Yes, I can play the transcoded stream by VLC and ffplay smoothly without any issues, but the problem is in NVR. I can't play h265 on Hikvision or Dahua NVR when I transcode it by FFmpegg, I don't know the reason, is it the codec problem or NVR?

@benpar2 你现在有任何解决方案吗，我也遇到了相同的问题，我使用OBS推流至zlmediakit ，使用nvr播放，它的帧数大约为3秒1fps。但是当我使用vlc播放时，没有任何问题。

**Comment by ParhamJ** [comment]
> > @xia-chu Thank you for checking. Yes, I can play the transcoded stream by VLC and ffplay smoothly without any issues, but the problem is in NVR. I can't play h265 on Hikvision or Dahua NVR when I transcode it by FFmpegg, I don't know the reason, is it the codec problem or NVR?
> 
> @benpar2 你现在有任何解决方案吗，我也遇到了相同的问题，我使用OBS推流至zlmediakit ，使用nvr播放，它的帧数大约为3秒1fps。但是当我使用vlc播放时，没有任何问题。

@SuperCatss 不，我找不到问题。 尽管如此，我仍在寻找问题所在。 不幸的是，海康威视没有人回答我的问题。 那你呢，找到了吗？

**Comment by xia-chu** [comment]
> > @benpar2 你现在有任何解决方案吗，我也遇到了相同的问题，我使用OBS推流至zlmediakit ，使用nvr播放，它的帧数大约为3秒1fps。但是当我使用vlc播放时，没有任何问题。
> 
> @SuperCatss 不，我找不到问题。 尽管如此，我仍在寻找问题所在。 不幸的是，海康威视没有人回答我的问题。 那你呢，找到了吗？

This issue should be resolved later. This is caused by the NVR of hikvision not supporting stap-a H264 rtp packaging。
Please update zlmediakit to the latest code， and set  `rtp.h264_stap_a` to `0`,  `rtsp.directProxy` to `0`.

**Comment by ParhamJ** [comment]
> This issue should be resolved later. This is caused by the NVR of hikvision not supporting stap-a H264 rtp packaging。 Please update zlmediakit to the latest code， and set `rtp.h264_stap_a` to `0` and `rtsp.directProxy` to `0` in `config.ini` file.

@xia-chu Thank you for your help. Now, the NVR can play the h265 stream from FFmpeg. Is it the permanent solution?
