### ISSUE TITLE
[技术咨询] config.ini中是否可以使用环境变量？

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1918]
**咨询的功能模块**
- 配置文件

**咨询的具体内容和问题**
- 配置文件中是否可以使用系统环境变量？可以的话，该如何引用？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
不行，配置选项太多，环境变量不方便
