### ISSUE TITLE
RTSPS流和RTSP流隔离

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#1919]
我发现rtsp流和rtsps流没有进行隔离。由于是对rtsp和rtsps拆分到不同端口接受和发送，共用其他模块。导致出现了rtsps流推送，rtsp可以拉取的问题。rtsp流推送也可以使用rtsps流进行拉取。

**Comment by fengmao31** [comment]
但是这样你加密传上去。任何一个人都可以非加密端口拉取下来解密的内容。加密还有什么意义？

**Comment by xiongguangjie** [comment]
你不开放非加密端口不就行了，如果你有隔离的需求，开两个服务不就行了

**Comment by fengmao31** [comment]
你的意思是同时运行两个服务器？其中一个关闭rtsp554这种端口？
我去测测速度去。
