### ISSUE TITLE
ubuntu下交叉编译在ARM下运行，不存在ipv6在址的情况下，还是绑定到IPV6,且不能能过IPV4地址访问

### ISSUE THREAD

**Issue by corner4world** [ZLMediaKit/ZLMediaKit#1921]
现象描述
ubuntu下交叉编译在ARM下运行，不存在ipv6在址的情况下，还是绑定到IPV6,且不能能过IPV4地址访问
![image](https://user-images.githubusercontent.com/20147562/187463636-ca22f49a-f98e-4dc1-93c3-319ba6990607.png)

_Originally posted by @corner4world in https://github.com/ZLMediaKit/ZLMediaKit/issues/1638#issuecomment-1231736250_

**Comment by xia-chu** [comment]
你看了下代码:
<img width="941" alt="图片" src="https://user-images.githubusercontent.com/11495632/187828994-88255450-da44-4005-8180-9dc782ce006d.png">

**Comment by xia-chu** [comment]
就算绑定ipv6的地址 也是可以接收ipv4的请求的
