### ISSUE TITLE
编译报错 SCTP_LIBRARIES-NOTFOUND

### ISSUE THREAD

**Issue by xiangshenb** [ZLMediaKit/ZLMediaKit#1923]
SCTP_LIBRARIES-NOTFOUND
系统 centos stream
安装了 sctp 协议
编译命令
cmake .. -DENABLE_WEBRTC=true  -DOPENSSL_ROOT_DIR=/opt/openssl1.0  -DOPENSSL_LIBRARIES=/opt/openssl1.0/lib
![图片](https://user-images.githubusercontent.com/17942071/187612797-f7e687c1-50a6-4228-8bef-a842e06a41e9.png)

**Comment by xiangshenb** [comment]
请问这个 SCTP_LIBRARIES-NOTFOUND 应该安装什么才能解决，这个不装的话有什么影响

**Comment by xiongguangjie** [comment]
不用rtc 的data channel 不用管
