### ISSUE TITLE
[BUG]: 请求的m3u8文件内容一直不变，导致视频无法播放

### ISSUE THREAD

**Issue by LIUJINWEN01** [ZLMediaKit/ZLMediaKit#1925]
### 现象描述
使用nginx代理的，MediaServer运行在8890端口。
在另一个机器中make后，直接打包/release/linux/Debug的到另一个机器使用。
使用hls协议，请求中的m3u8文件内容一直是没有变化，导致视频卡着不动，刷新后返回几秒前播放然后也卡着，不知道什么问题。
![Snipaste_2022-08-31_19-08-24](https://user-images.githubusercontent.com/38368113/187668318-228d50b8-30ba-46fd-acb9-207b8307a79b.png)

### 服务器中的文件路径跟请求的不一致，服务器的是/20，请求是/18.
![image](https://user-images.githubusercontent.com/38368113/187680038-e2f8530b-014a-48ab-a6fb-fac2af32508d.png)
![image](https://user-images.githubusercontent.com/38368113/187680250-3093e636-7094-4c5c-9e35-629219b489b4.png)

查看文件是有更新的
![Snipaste_2022-08-31_19-10-04](https://user-images.githubusercontent.com/38368113/187666496-b5483f7d-3623-4968-8919-d0ec1e7a6376.png)

![Snipaste_2022-08-31_20-17-58](https://user-images.githubusercontent.com/38368113/187677245-b0d08f46-05c6-4eb4-8374-6b5aac0f23ab.png)

**Comment by xia-chu** [comment]
可能nginx代理缓存的问题

**Comment by LIUJINWEN01** [comment]
确实是缓存的问题，禁用浏览器缓存后，就正常了
![image](https://user-images.githubusercontent.com/38368113/187878580-c79142cc-777e-4238-a9d1-29915568f1a6.png)
![image](https://user-images.githubusercontent.com/38368113/187878967-20a99657-f1da-431c-b3c7-23960574f28e.png)
