### ISSUE TITLE
[技术咨询]视频播放断流

### ISSUE THREAD

**Issue by penghui-luna** [ZLMediaKit/ZLMediaKit#1926]
**咨询的功能模块**
- 视频流的推流问题

**咨询的具体内容和问题**
- 作者大大你好，我这边在测试视频的回放功能的时候，拉取到的视频流，在播放的时候，经常会自动断掉，导致暂停播放；我查看流列表接口，发现，流列表返回的接口中，字段aliveSecond，即流的存活时间，都是个位数或者2位数，请问，怎么可以让视频流不断流呢？这断流是啥原因导致的呢？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
GB28181视频回放？和WVP一起？

**Comment by xia-chu** [comment]
那你看下zlm日志 有没有重连

**Comment by penghui-luna** [comment]
![5](https://user-images.githubusercontent.com/40514537/187912392-964fb739-6d2f-477b-979e-85baea8d1c73.png)
这是断流之后，打出的日志。

**Comment by penghui-luna** [comment]
作者大大，为啥我没启用hook事件，zlm打出的日志还是会触发无人观看事件呢，而且，一直都是反复的：注册流，然后触发无人观看事件，然后注销流，又是重新注册流。

**Comment by custompal** [comment]
> ![5](https://user-images.githubusercontent.com/40514537/187912392-964fb739-6d2f-477b-979e-85baea8d1c73.png) 这是断流之后，打出的日志。

这里已经提示接收rtp超时了，是设备的rtsp流有问题吧？最好抓个包看看
![image](https://user-images.githubusercontent.com/50011641/188558905-3b07d55b-4035-48a5-a64b-d842114ee69b.png)

**Comment by custompal** [comment]
> 作者大大，为啥我没启用hook事件，zlm打出的日志还是会触发无人观看事件呢，而且，一直都是反复的：注册流，然后触发无人观看事件，然后注销流，又是重新注册流。

无人观看事件是内部机制，跟启没启用hook没有关系，只是没启用hook事件你就收不到通知而已，另外即使触发了无人观看事件zlm也不会主动注销流的，你这个应该是拉取rtsp流过程中一段时间没收到流才自动注销的，然后拉流器会自动重试，重试又能成功拉取流才会出现媒体注册，但是后面又接收流超时又注销，所以反复注册和注销

**Comment by penghui-luna** [comment]
嗯，非常感谢解答。用vlc播放rtsp流试了一试，确实发现有些rtsp流，中间会断掉，但是有些rtsp流又是很稳定的。

**Comment by xia-chu** [comment]
> 嗯，非常感谢解答。用vlc播放rtsp流试了一试，确实发现有些rtsp流，中间会断掉，但是有些rtsp流又是很稳定的。

可能网络不稳定吧

**Comment by xia-chu** [comment]
先关闭issue了 后面有问题再此反馈
