### ISSUE TITLE
[技术咨询] addStreamProxy 拉流代理

### ISSUE THREAD

**Issue by yanpeijie** [ZLMediaKit/ZLMediaKit#1927]
**addStreamProxy 拉流代理**
addStreamProxy 拉流代理部分

**咨询的具体内容和问题**
输入一个hls的流，这个m3u8的视频文件是30分钟的。接口返回代理成功，用flv的格式播放，视频从不确定的时间点开始播放。几分钟，十几分钟，二十几分钟的情况都有。
m3u8文件的标签：
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:1800
#EXTINF:120, S1661839281-E1661839401-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830140121-20220830140321.ts
#EXTINF:120, S1661839401-E1661839521-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830140321-20220830140521.ts
#EXTINF:120, S1661839521-E1661839641-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830140521-20220830140721.ts
#EXTINF:120, S1661839641-E1661839761-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830140721-20220830140921.ts
#EXTINF:120, S1661839761-E1661839881-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830140921-20220830141121.ts
#EXTINF:120, S1661839881-E1661840001-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830141121-20220830141321.ts
#EXTINF:120, S1661840001-E1661840121-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830141321-20220830141521.ts
#EXTINF:120, S1661840121-E1661840241-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830141521-20220830141721.ts
#EXTINF:120, S1661840241-E1661840361-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830141721-20220830141921.ts
#EXTINF:120, S1661840361-E1661840481-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830141921-20220830142121.ts
#EXTINF:120, S1661840481-E1661840601-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830142121-20220830142321.ts
#EXTINF:120, S1661840601-E1661840721-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830142321-20220830142521.ts
#EXTINF:120, S1661840721-E1661840841-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830142521-20220830142721.ts
#EXTINF:120, S1661840841-E1661840961-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830142721-20220830142921.ts
#EXTINF:120, S1661840961-E1661841081-c8784d10-1218-4105-a4cd-21838a0b54d9
/data/record/nfs1/34020000001320000008/2022-08-30/c8784d10-1218-4105-a4cd-21838a0b54d9-20220830142921-20220830143121.ts
#EXT-X-ENDLIST

zlm日志会报警告，感觉应该没啥问题
WarnL << "may not a hls video: "
WarnL << "may not a mpeg-ts video: "

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个报警的原因是 http返回的content-type不对导致的 你用的http服务器是什么类型？

**Comment by yanpeijie** [comment]
<html>
<body>


application/json;charset:utf-8;
--



</body>
</html>

**Comment by xia-chu** [comment]
所以hls的文件这么会是json?

**Comment by yanpeijie** [comment]
hls的content-type：application/vnd.apple.mpegurl
ts的content-type：application/octet-stream

**Comment by xia-chu** [comment]
addStreamProxy对直播支持比较好 对点播支持不好
