### ISSUE TITLE
SSL_ENABLE_SNI导致CTX为空

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#1928]
SSL_ENABLE_SNI导致本地IP调试时候，默认读取空CTX。

然后触发回调调用findcertificates，在读取可用的证书。这对新人不友好。希望项目默认关闭SSL_ENABLE_SNI。

![image](https://user-images.githubusercontent.com/19343842/187829735-ade47cc2-4aca-4e46-bad0-bd415554b9de.png)

![image](https://user-images.githubusercontent.com/19343842/187829668-a4042b21-18df-475f-94ab-90768f7bbe78.png)

**Comment by xia-chu** [comment]
关闭sni后就不支持多域名证书了
