### ISSUE TITLE
[BUG]: BUG  在回看NVR录像时，报错

### ISSUE THREAD

**Issue by MrSe7enPlus** [ZLMediaKit/ZLMediaKit#1932]
![V09V@6F{3$SE JG5CS9I}XL](https://user-images.githubusercontent.com/25544839/188122560-8e9fa60f-8940-44b8-ab5f-6302c34c3da1.png)
![image](https://user-images.githubusercontent.com/25544839/188122782-9c371ae2-8c7f-43bc-947f-a4f16b95599e.png)

回看发送请求后，无响应，查看ZML日志，发现这边会报错

**Comment by xia-chu** [comment]
Trace的日志是最不重要的日志 你说的不是这个原因

**Comment by penghui-luna** [comment]
我这边也是报错，会出现断流
![6](https://user-images.githubusercontent.com/40514537/188266768-da00fa8e-9500-4985-8ad7-3143cc8814d7.png)

**Comment by MrSe7enPlus** [comment]
> Trace的日志是最不重要的日志 你说的不是这个原因

是否有解决得方法？确实 我使用回看功能，有时候能放 不过时长不会很长，1分钟以内。大部分的时候是无法播放的。播放器会显示超时

**Comment by monktan89** [comment]
你的日志不全 无法判定是否nvr有没有持续推流

**Comment by MrSe7enPlus** [comment]
> 你的日志不全 无法判定是否nvr有没有持续推流

![image](https://user-images.githubusercontent.com/25544839/188346563-03cdacdd-bdac-4343-8b1e-0c594a971cba.png)
[2022-09-05_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/9486186/2022-09-05_00.log)
这个是日志和UI播放器的截图

**Comment by xiongguangjie** [comment]
你可以把nvr的录像流暴露在公网上吗，我看你提供的日志根本无法判断
