### ISSUE TITLE
[技术咨询] 适合流媒体服务器得负载均衡策略

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#1934]
**咨询的功能模块**
- 流媒体服务器负载均衡

**咨询的具体内容和问题**
- 想请教一下本地化部署得时候，什么负载均衡软件比较适合做流媒体服务器集群得前置负载均衡；主要是应对国标设备端rtp推流和客户端rtmp或者http-flv拉流；我目前只能想到LVS比较适合这种大流量得负载均衡，但是LVS对网络配置的限制比较多，有没有比LVS更加简便性能差不多的负载均衡方案，多谢多谢！！！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
一般是源站是一级，拉流的是另外一级，也可能有多级级联，拉流负载主要是通过多个机器来进行的，推流的负载均衡也是一样

**Comment by xiongguangjie** [comment]
没有几千路并发，就每必要搞集群

**Comment by mayomeng** [comment]
目前预计后续要接入2万个左右摄像头（公网IP还有限。。。），但是之前没有对大并发视频码率负载均衡的相关经验，所以想请教一下，是否有功能更强大的适合视频码流的负载均衡解决方案（目前觉得只有LVS最适合，但是不支持容器化部署，还需要对服务器网络配置进行修改。。。）

**Comment by xiongguangjie** [comment]
如果IP有限，可以做端口映射，把不同范围的端口映射到不同的机器上，来做GB28181的媒体集群，拉流的话，也可以将不同的链接转发到不同的机器上，来做集群。这个你可以查查关于iptable 与 nat的资料（linux的）

**Comment by mayomeng** [comment]
多谢
