### ISSUE TITLE
[技术咨询] c api 拉流客户端到期后踢出

### ISSUE THREAD

**Issue by huangxiuqi** [ZLMediaKit/ZLMediaKit#1935]
**咨询的功能模块**
c api

**咨询的具体内容和问题**
请问c api能否实现踢掉某个指定拉流客户端？
我想实现的功能是给拉流客户端加个有效期，超过有效期踢掉这个客户端。

**Comment by xia-chu** [comment]
可以添加踢掉客户端的api 但是不会去实现定时踢掉的这个动作
