### ISSUE TITLE
[BUG]: 在同时使用代理访问和直接访问时，无法获取客户端IP地址

### ISSUE THREAD

**Issue by AlphaWu** [ZLMediaKit/ZLMediaKit#1939]
### 现象描述

流媒体服务器对外通过代理提供服务，对内直接提供服务。在未配置forwarded_ip_header时，on_play获取的是代理服务器ip和内网客户端ip，配置forwarded_ip_header后，能够获取外网客户真实ip，内网ip为空。

### 如何复现?
使用代理，配置forwarded_ip_header后即可复现。

**Comment by xia-chu** [comment]
感谢pr
