### ISSUE TITLE
[BUG]: 关于获取截图（getSnap）接口相关BUG反馈

### ISSUE THREAD

**Issue by keDaYao** [ZLMediaKit/ZLMediaKit#1943]
### 现象描述

-  当需要截图的URL停止推流时，调用ZLM的获取截图接口，在等待失败超时时间后依旧返回最后一次截取成功的图片，而不是返回配置的默认截图图片

### 如何复现?
- 1、先向ZLM推流
- 2、调用getSnap截取图片
- 3、停止向ZLM推流
- 4、再次调用getSnap截取图片
- 5、此时步骤4获取的图片依旧是步骤2获取的图片
期望：步骤5获取config配置的默认截图图片

### 相关日志或截图
- 1、向ZLM推流
![image](https://user-images.githubusercontent.com/36600558/188837945-f199bb6e-23ed-4cb0-bcf4-44ff9f1d313f.png)

- 2、调用getSnap截取图片
![image](https://user-images.githubusercontent.com/36600558/188838067-43523603-fe03-4596-8b22-9c99921c80c8.png)

- 3、停止向ZLM推流
![image](https://user-images.githubusercontent.com/36600558/188838200-86107469-d0c2-4205-ba86-b76a715484f8.png)

- 4、再次调用getSnap截取图片
![image](https://user-images.githubusercontent.com/36600558/188838413-689dde94-5bcb-46eb-bd93-500d5fb311e1.png)

可见步骤4获取的截图在经过了超时时间10秒后，依旧返回了步骤2获取的截图。

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:  4f47b7a5fefca56fe9b130f0141f1d643bc36edb
* **操作系统及版本**:  centos7
* **硬件信息**: 8C16G
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
是的 zlm就是这么设计的 个人以为 返回上次截图照片比默认图好点

**Comment by xia-chu** [comment]
默认图只有在完全截图失败的情况下才会返回

**Comment by keDaYao** [comment]
原来如此，感谢大佬的回复！
