### ISSUE TITLE
gb28181相关问题[技术咨询]

### ISSUE THREAD

**Issue by wangdemon** [ZLMediaKit/ZLMediaKit#1944]
我不是很理解gb28181协议，我也看了本项目gb28181相关内容部分。本项目通过Postman请求后，获取rtp推流端口，然后使用ffmpeg推流，最后使用vlc播放rtsp、rtmp等协议的流媒体。
我的需求：
(1) 在局域网搭建自己的gb28181的推流拉流系统；
(2) 使用本地视频文件，或者USB摄像头等，通过ffmpeg推流；
(3) 通过[gosip](https://github.com/panjjo/gosip)作为sip服务器。
不知道能不能使用ZLMediaKit实现上面需求，如果能实现，希望博主大大，指点一下。

**Comment by monktan89** [comment]
可以实现，但是不懂协议搞起来难受

**Comment by wangdemon** [comment]
> 可以实现，但是不懂协议搞起来难受

老哥，给点提示，不胜感激

**Comment by wangdemon** [comment]
> 可以实现，但是不懂协议搞起来难受

老哥，给点提示，不胜感激

**Comment by monktan89** [comment]
> 

建议先看下28181协议，把zlm wiki看完，看下群里面gb协议常见抓包，有个整体认知

**Comment by manhere** [comment]
可以看下 [wvp-GB28181-pro](https://github.com/648540858/wvp-GB28181-pro)，应该能满足你的需求。

**Comment by tianya2222** [comment]
你好，我这边部署后播放大华网络摄像机视频流时，前端页面总是提示：收流超时，zlm日志显示openRtpServer 和closeRtpServer都正常，日志有打印：RtpProcess timeout，不知道是什么原因，哪位大神能给点提示？

**Comment by xia-chu** [comment]
> 你好，我这边部署后播放大华网络摄像机视频流时，前端页面总是提示：收流超时，zlm日志显示openRtpServer 和closeRtpServer都正常，日志有打印：RtpProcess timeout，不知道是什么原因，哪位大神能给点提示？用的是wvp-GB28181-pro

说明你wvp配置文件没配好

**Comment by tianya2222** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by tianya2222** [comment]
> 

![image](https://user-images.githubusercontent.com/90952378/192694303-5b8cbf9e-470e-4494-aa62-32274ec61f0b.png)
这上是我的配置，反复琢磨了几天都没发现问题，帮瞅瞅看问题在哪

**Comment by tianya2222** [comment]
日志可在issues/2001里看

**Comment by xia-chu** [comment]
@wangdemon 你这个回复很有指导意义
