### ISSUE TITLE
[技术咨询]如何向在鉴权的适合加入params参数呢

### ISSUE THREAD

**Issue by bbwl521** [ZLMediaKit/ZLMediaKit#1946]
**咨询的功能模块**
- 使用rtmp推流鉴权

**咨询的具体内容和问题**
- 在使用obs推流工具并配置了地址为rtmp://192.168.33.33:1935/live/1?token=123的推流地址后，我不太清楚这个token是不是放在这里使用，我通过docker日志发现params参数使用空，请问如何正确的配置鉴权参数

**Comment by xia-chu** [comment]
这个是obs的怎么用的问题了 `1?token=123`应该放在obs的`密钥`输入框

**Comment by bbwl521** [comment]
好的，谢谢
