### ISSUE TITLE
[BUG]: webrtc前端关闭视频和音频但是不关闭通道，也就是rtcp还有继续发送，流就被超时断掉

### ISSUE THREAD

**Issue by funbinary** [ZLMediaKit/ZLMediaKit#1951]
### 现象描述

webrtc前端关闭视频和音频但是不关闭通道，也就是rtcp还有继续发送，流就被超时断掉
### 如何复现?
看代码是因为rtcp收到sr没有重置超时定时器导致。
![image](https://user-images.githubusercontent.com/44047515/189319204-a17095d3-79bd-4ccb-a82c-888e93becbd0.png)

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by funbinary** [comment]
我将SR增加了定时器重置是可以支持前端关闭视频和音频的

**Comment by xiongguangjie** [comment]
好的我修改一下，重置定时器

**Comment by xiongguangjie** [comment]
已经修改了
