### ISSUE TITLE
[功能请求]新增单流多文件保存

### ISSUE THREAD

**Issue by cslinwang** [ZLMediaKit/ZLMediaKit#1954]
**描述该功能的用处，可以提供相关资料描述该功能**

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
现有一个流只能保存到一个文件

**描述你期望实现该功能的方式和最终效果**
流的保存路径可以编程list，支持多个文件设置。

**Comment by xia-chu** [comment]
录制一样的mp4文件没有意义 还不如录制完成事件中你再拷贝到多个路径
