### ISSUE TITLE
[BUG]: BUG 目录遍历漏洞？

### ISSUE THREAD

**Issue by szy833** [ZLMediaKit/ZLMediaKit#1960]
### 现象描述

ip:port可以访问服务器文件的根目录，这个是否属于目录遍历漏洞？应该怎么解决？
### 相关日志或截图

![image](https://user-images.githubusercontent.com/31844882/190184332-071db11c-b9f6-4bcb-8816-0621a426b10b.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by wasphin** [comment]
目前是这么开发的，欢迎提个 pr 添加开关来控制是否需要显示目录

**Comment by xiongguangjie** [comment]
有配置文件 dirMenu配置选项可以关闭掉

**Comment by szy833** [comment]
> 有配置文件 dirMenu配置选项可以关闭掉

确实好使，谢谢
