### ISSUE TITLE
[技术咨询]视频增加音频的直播推流

### ISSUE THREAD

**Issue by wildwindyevan** [ZLMediaKit/ZLMediaKit#1970]
**咨询的功能模块**
- 多个通道的音视频推流

**咨询的具体内容和问题**
已经实现- 从摄像头获取yuv输入到一个pusher推流到rtmp
问题1- 如何将yuv与pcm同步输入到一个source，然后推流到rtmp地址

代码是先接收到YUV视频包
    mk_media_init_video(mctx->media, 0, pFrameInfo->nWidth, pFrameInfo->nHeight, pFrameInfo->nFrameRate, 2 * 1024 * 1024);
   mk_media_set_on_regist(mctx->media,ipcs::on_mk_media_source_regist_func, mctx);

接着收到PCM音频包
   codec_args v_args={0};
                a_args.audio.channels = pFrameInfo->nWidth;
                a_args.audio.sample_rate = pFrameInfo->nFrameRate;
                mk_track a_track = mk_track_create(MKCodecAAC,&a_args);
                 mk_media_init_track(mctx->media,a_track);
                 mk_track_unref(a_track);

等到初始化完了再执行
mk_media_input_yuv和mk_media_input_pcm
执行的结果是
mk_media_input_pcm 一直返回 0 失败

请问这个逻辑有没有问题？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
mk_media_input_pcm需要编译时开启facc相关特性： -DENABLE_FAAC=on，否则会返回false
