### ISSUE TITLE
[BUG]: BUG 不定时出现core掉的情况，错误点是：src/Player/PlayerBase.cpp:29

### ISSUE THREAD

**Issue by wu1wen2lin3** [ZLMediaKit/ZLMediaKit#1971]
### 现象描述

不定时出现挂掉的情况。

2022-08-23 01:21
2022-08-25 15:31
2022-08-28 03:28
2022-09-16 12:42
2022-09-16 17:55
2022-09-17 12:58

检查core的情况，都是同样的错误，出问题点是：/data/ZLMediaKit/src/Player/PlayerBase.cpp:29
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./MediaServer -d'.
Program terminated with signal 6, Aborted.
#0  0x00007f70f79f91f7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-51.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-16.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-16.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt
#0  0x00007f70f79f91f7 in raise () from /lib64/libc.so.6
#1  0x00007f70f79faa28 in abort () from /lib64/libc.so.6
#2  0x00007f70f82ffac5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f70f82fda36 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f70f82fc9e9 in ?? () from /lib64/libstdc++.so.6
#5  0x00007f70f82fd654 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007f70f7d96903 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007f70f7d96e37 in _Unwind_Resume () from /lib64/libgcc_s.so.1
#8  0x0000000000f51b75 in mediakit::PlayerBase::__lambda76::operator() (__closure=0x7f70ecaea5a8, ptr=0x7f70ec48c348) at /data/ZLMediaKit/src/Player/PlayerBase.cpp:29
#9  0x0000000000f557bb in std::_Sp_counted_deleter<mediakit::HlsPlayerImp*, mediakit::PlayerBase::createPlayer(const Ptr&, const string&)::__lambda76, std::allocator<int>, (__gnu_cxx::_Lock_policy)2u>::_M_dispose(void) (this=0x7f70ecaea590) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:347
#10 0x0000000000c3c47c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f70ecaea590) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
#11 0x0000000000c3a96b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f70f517f8d8, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
#12 0x0000000000dd6848 in std::__shared_ptr<mediakit::PlayerBase, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f70f517f8d0, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
#13 0x0000000000f5168f in std::__shared_ptr<mediakit::PlayerBase, (__gnu_cxx::_Lock_policy)2>::operator=(std::__shared_ptr<mediakit::PlayerBase, (__gnu_cxx::_Lock_policy)2>&&) (this=0x7f70ec02e0a0, 
    __r=<unknown type in /data/ZLMediaKit/release/linux/Debug/MediaServer, CU 0x1784be5, DIE 0x181a636>) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:860
#14 0x0000000000f51504 in std::shared_ptr<mediakit::PlayerBase>::operator=(std::shared_ptr<mediakit::PlayerBase>&&) (this=0x7f70ec02e0a0, 
    __r=<unknown type in /data/ZLMediaKit/release/linux/Debug/MediaServer, CU 0x1784be5, DIE 0x1819f3a>) at /usr/include/c++/4.8.2/bits/shared_ptr.h:291
#15 0x0000000000f50cbf in mediakit::MediaPlayer::play (this=0x7f70ec02dff8, url="http://175.6.9.195:7086/live/cameraid/1000347%247/substream/1.m3u8") at /data/ZLMediaKit/src/Player/MediaPlayer.cpp:40
#16 0x0000000000dd11a1 in mediakit::PlayerProxy::__lambda84::operator() (__closure=0x7f70ec0034a0) at /data/ZLMediaKit/src/Player/PlayerProxy.cpp:141
#17 0x0000000000dd5bfe in std::_Function_handler<bool(), mediakit::PlayerProxy::rePlay(const string&, int)::__lambda84>::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/4.8.2/functional:2057

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**: CentOS Linux release 7.4.1708 (Core) 
* **硬件信息**: Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz 
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
代码版本多少 已经对不上最新代码了

**Comment by wu1wen2lin3** [comment]
不好意思，我这边更新下最新版本。
