### ISSUE TITLE
[技术咨询] 大华设备跳秒问题

### ISSUE THREAD

**Issue by walkTtalk** [ZLMediaKit/ZLMediaKit#1974]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**

前几天升级的zlm，海康设备不跳秒，大华设备跳秒。后来发现是海康的音频是ACC，大华的音频是G711A，然后把大华的音频改成ACC就不跳秒了，但是没有声音了。

![image](https://user-images.githubusercontent.com/20769982/191296042-8d68c35e-6256-4057-9489-9ddec29e429e.png)

今天升级了zlm。大华跳秒问题解决。音频和视频都正常。可以普及一下相关原因吗。

**注意事项**

- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个我请教media-server库作者老陈才知道他的库其实是有些优化的 不过需要宏开启

**Comment by walkTtalk** [comment]
![image](https://user-images.githubusercontent.com/20769982/191429099-fcd2f0a9-fc61-4eac-83da-3347440798f5.png)
@Luo-99 截图了

**Comment by walkTtalk** [comment]
@Luo-99 切换tcp推流，的确视频很卡，zlm只有这个日志

2022-09-21 21:41:14.355 W MediaServer[2601362-event poller 0] H264Rtp.cpp:53 inputRtp | start drop h264 gop, last seq:20834, rtp:
version:2
padding:0
ext:0
csrc:0
mark:0
pt:96
seq:20847
stamp:152326710
ssrc:44
rtp size:1400
payload offset:0
payload size:1388


2022-09-21 21:41:27.958 W MediaServer[2601362-event poller 1] CommonRtp.cpp:53 inputRtp | rtp丢包:47837 -> 47840

**Comment by walkTtalk** [comment]
@Luo-99 视频卡感觉是安装的宽带的问题。同一台zlm，一处安装的是联通宽带上传和下载测试都超过10M，但是容易绿屏和卡。

神奇的是。另外一处安装的是移动宽带上传和下载不超过5M。视频也不出现绿幕，视频很流畅。

不知道宽带除了上传和下载还有什么影响导致这个视频卡现象

**Comment by walkTtalk** [comment]
@xia-chu 可以帮分析上面联通宽带导致视频出现绿幕或者卡顿是什么原因吗，感谢~

**Comment by walkTtalk** [comment]
@xia-chu 可以帮分析上面联通宽带导致视频出现绿幕或者卡顿是什么原因吗，感谢~

**Comment by walkTtalk** [comment]
联通宽带白天绿幕和视频卡，几率是100%。到晚上10点以后，绿幕就没有了。难道是是运营商进行了限制吗。但测试上传和下载速度在10M以上呀。

**Comment by walkTtalk** [comment]
![image](https://user-images.githubusercontent.com/20769982/191654270-2b476ef4-70ba-4e31-9e02-6efb62f2e9b3.png)
这是白天的情况。

**Comment by walkTtalk** [comment]
我把摄像头配置码率调小了就没有绿幕了。但是正常码率上限2048也没有多大呀。调小512码率，才没有绿幕

**Comment by walkTtalk** [comment]
![image](https://user-images.githubusercontent.com/20769982/191678383-479cfad2-35fd-4480-819c-f1ec00de0dc3.png)
产生绿屏的主要是: 无法渲染的画面有些用黑色填充，有些用绿色填充，有些用上一帧画面填充。 视频参数改变， 而解码端的SPS&PPS信息未及时重新获取更新，会导致画面无法正常渲染，继而导致绿屏的现象出现。
References:
现象：播放画面出现图像紊乱，大面积的异常颜色的方块图，或者绿屏现象

1.丢失参考帧导致的
一般 H.264 码流有 I、B、P 三种帧类型，I 帧是关键帧，B 帧是双向预测内插编码帧，P 帧是前向预测编码帧。
I 帧由于是帧内压缩，因此可以独立解码播放，而 B 帧，一旦丢失了 I 帧或者后面的 P 帧，则会解码失败，而 P 帧一旦丢失了前面的 I/B/P 帧，也会导致解码失败。
对于丢失了参考帧而导致的解码失败，一般就会出现花屏的现象，花屏的严重程度依赖于丢失的参考帧对即将解码的帧的重要程度。


那么，什么情况下会丢失参考帧呢 ？
首先，推流/播放的代码层面，需要注意，不要丢弃编码后、解码前的视频帧数据，不过实际场景中，遇到下面的情况，难免还是会产生丢帧：
网络不好，编码后的数据发不出去
系统低内存，队列里面无法承受更多的帧数据
因此，在这些极端的情况下，不得不丢帧的话，最合理的策略就应该是一次丢一整个 GOP，即：一旦开始丢了一个 I 帧，那么在遇到下一个 I 帧之前的所有视频帧，均丢弃掉，这样即可有效避免播放器端产生解码花屏。


2.播放器没有从关键帧开始解码
原理依然如上面所述，如果不从关键帧开始解码，则必然会由于丢失了参考信息而导致解码花屏。
因此，播放器，无论是首播，还是断网重连后，都应该判断第一帧视频是否是关键帧，如果不是，则应该等到第一个关键帧到达之后再送入解码器。
基于 ffmpeg 的播放器，如何判断关键帧，可以参考文章：《FFMPEG Tips (3) 如何读取每一帧的信息》


3.码流中视频尺寸发生变化
很多直播 App，横屏直播和竖屏直播，使用的是不同的推流尺寸 ，当主播由竖屏推流改为横屏推流，同时又不改变推流地址的话，观众端拉到的流就会出现中间发生了视频尺寸的变化，比如：从 848 x 480 变成了 1280 x 720 等等。
播放器需要实时检测，如果发现视频尺寸发生了变化，则需要重置解码器以及相关逻辑，否则容易出现解码花屏或者出现内存越界等异常。

**Comment by walkTtalk** [comment]
是流媒体服务器需要优化吗。摄像头配置都是默认配置呀

**Comment by walkTtalk** [comment]
支持265吗。265zen'me怎么全花呀。

![image](https://user-images.githubusercontent.com/20769982/191680034-ec4d7464-7254-42d8-b656-895884f93d19.png)

**Comment by walkTtalk** [comment]
刚刚测试264，easycvr一点花屏都没有很流畅。是不是服务器带宽太小了的原因。服务器入网10M，出网带宽6M。服务器带宽应该配置多大呢。是否是出网太小了

**Comment by walkTtalk** [comment]
265的easycvr测试。

**Comment by walkTtalk** [comment]
@Luo-99 上面说绿幕，是我的服务器出网6M，入网10M。

easycvr没有绿幕，很流畅正常的

**Comment by walkTtalk** [comment]
好像又不是带宽问题。又测试了一下easycvr的h264编码

![image](https://user-images.githubusercontent.com/20769982/191685183-5fe85aa3-1e93-48d5-b063-fbdde622b7cd.png)

**Comment by xia-chu** [comment]
udp丢包花屏问题无解。
tcp你们反馈的现象是摄像头有bug，在发送tcp时，如果网络不好，写入数据到非阻塞socket会返回-1或部分数据，一般来说，程序需要保存未发送成功的数据，但是如果没处理，就会导致tcp上下文错乱了。

tcp协议是流式协议，是上下文强相关的，如果中间丢失数据就无法rtp包对齐，无法从一堆数据中找到什么地方是rtp开头。

**Comment by xia-chu** [comment]
国标这种协议 使用ps封装就是败笔 根本不适合互联网传输

**Comment by walkTtalk** [comment]
摄像头设置1080p，码率512花屏没有了。就是之前一直说的解决方案。修改码率为512。可是码率512有点小哦。

**Comment by xia-chu** [comment]
没bug的摄像头使用tcp推流 有bug的使用udp吧 没什么好办法了。全部用tcp推流也行，反正大部分情况应该都能恢复tcp上下文

**Comment by walkTtalk** [comment]
好的，感谢作者大大。持续跟踪这个花屏和绿幕问题。

**Comment by xia-chu** [comment]
国标本来就是设计给公安系统的专网使用的
