### ISSUE TITLE
[技术咨询] MediaRecorder 录制 rtsp addStreamProxy 的 webrtc 流

### ISSUE THREAD

**Issue by FireWild** [ZLMediaKit/ZLMediaKit#1975]
**咨询的功能模块**
- MediaRecorder 录制 webrtc

**咨询的具体内容和问题**
- webrtc 是 rtsp 通过 addStreamProxy 转的，用 MediaRecorder 录制 后得到的视频黑屏 mimeType 为 video/webm;codecs=H264     通过 ffmpeg 查看视频信息如下：
Input #0, matroska,webm, from '2022-09-21-11-11-20.webm':
  Metadata:
    encoder         : Chrome
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0(eng): Audio: opus, 48000 Hz, mono, fltp (default)
  Stream #0:1(eng): Video: h264 (Constrained Baseline), yuv420p(progressive), 2880x1620, SAR 1:1 DAR 16:9, 1k tbr, 1k tbn (default)
- 如何解决黑屏问题，感谢

**Comment by xia-chu** [comment]
webrtc能正常播放吗？

**Comment by FireWild** [comment]
> webrtc能正常播放吗？

能正常播放，我们又测试了录制纯webrtc的流，还是黑屏，应该跟addStreamProxy无关了。
现在的情况是getUserMedia的流可以正常录制，webrtc拉的流录制就会黑屏

**Comment by xia-chu** [comment]
能正常播放说明不是zlm的问题 可以参考下webrtc录制范例

**Comment by FireWild** [comment]
close

**Comment by FireWild** [comment]
@xia-chu hi 打扰一下
现在的问题是：getUserMedia 的流通过webrtc传输后可以录制，rtsp 转webrtc的还是不行。我们猜想可能跟流的codecs 有关，想了解一下zlm是否在rtsp转webrtc的时候设置过codecs，不知是否方便回答一下？

**Comment by xia-chu** [comment]
当有有设置啊 你自己看浏览器输出 有打印sdp啊

**Comment by FireWild** [comment]
> 当有有设置啊 你自己看浏览器输出 有打印sdp啊

是否可以提个需求让addStreamProxy api 支持自定义codecs呢

**Comment by xia-chu** [comment]
> 提个需求让addStreamProxy api 支持自定义codecs呢

你这个需求是什么我没明白

**Comment by FireWild** [comment]
> 你这个需求是什么我没明白

就是调用addStreamProxy的时候 新增一个参数来指定 webrtc流的 codec

**Comment by xia-chu** [comment]
> > 你这个需求是什么我没明白
> 
> 就是调用addStreamProxy的时候 新增一个参数来指定 webrtc流的 codec

不能 编码格式是多少就是多少 我不认为是这个问题了

**Comment by mtdxc** [comment]
将MedaRecord格式改成MP4会不会好点
正常webm存vp8，vp9
h264存在mp4中比较多点
