### ISSUE TITLE
[功能请求] /index/api/getMp4RecordFile 返回结果 rootPath 可以与其他接口一样统一用下划线分割而不是驼峰命名吗

### ISSUE THREAD

**Issue by TopSpoofer** [ZLMediaKit/ZLMediaKit#1976]
**描述该功能的用处，可以提供相关资料描述该功能**

现在返回的结果：
{
   "code" : 0,
   "data" : {
      "paths" : [ "2020-01-25", "2020-01-24" ],
      "rootPath" : "/www/record/live/ss/"
   }
}

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

一些json库通过配置同时只能支持下划线或者驼峰命名的其中一种，zlm 一些模块返回的是下划线分割的结果，一些是驼峰命名的。

**描述你期望实现该功能的方式和最终效果**

建议统一用下划线的分割方式。

**Comment by xia-chu** [comment]
对外暴露的接口不好改了 改动会影响其他用户

**Comment by TopSpoofer** [comment]
> 对外暴露的接口不好改了 改动会影响其他用户

也是

**Comment by xia-chu** [comment]
历史渊源 在实现api时比较草率 没有统一指导思想 比较随意

**Comment by xia-chu** [comment]
api hook统一修改下 开发量不会太多 但是就怕赞成兼容性问题

**Comment by TopSpoofer** [comment]
路径加 version 或者是种方法~

**Comment by xia-chu** [comment]
> 路径加 version 或者是种方法~

那代码直接膨胀翻倍了 而且不可能同时触发两次hook

**Comment by TopSpoofer** [comment]
> > 路径加 version 或者是种方法~
> 
> 那代码直接膨胀翻倍了 而且不可能同时触发两次hook

所以挺难搞的

**Comment by xia-chu** [comment]
你别用那么先进的反射就行了

**Comment by xia-chu** [comment]
> 建议加新接口，然后在大版本更新的时候弃用掉旧接口

涉及面太广 生态项目不一定跟的上节奏 而且收益有限。
