### ISSUE TITLE
ZLMediaKit怎么停止录制？录制文件在www/record下

### ISSUE THREAD

**Issue by jellygithub** [ZLMediaKit/ZLMediaKit#1977]
**咨询的功能模块**
- www/record

**咨询的具体内容和问题**
- ZLMediaKit怎么停止录制？录制文件在www/record下,硬盘被占满了

**Comment by houge101** [comment]
wvp-pro的配置文件设置如下为false
![NN}8_Z_~48KCL~7B_B06MZ3](https://user-images.githubusercontent.com/3355923/191453900-6dfdaf21-cc2e-4a9b-a58e-e443a291f3b0.png)
