### ISSUE TITLE
[技术咨询] 配置ssl数字证书后，请求rtp流地址报错

### ISSUE THREAD

**Issue by lanwilliam** [ZLMediaKit/ZLMediaKit#1979]
**咨询的功能模块**
SSL数字证书配置问题
**咨询的具体内容和问题**
将域名的数字证书下载后，用域名pem替代default.pem，然后用-s default.pem加载数字证书启动。
wvp已经配置同域名数字证书，也配置了ssl相关参数，并且wvp可以正常运行，设备注册成功。
通过监控页面拉取设备视频时，黑屏无反应。
查看请求地址，已经存在https://域名的视频流链接。
![image](https://user-images.githubusercontent.com/8511385/191642361-93515906-df6d-4107-a6f8-cdce958de26a.png)
wvp配置：
![image](https://user-images.githubusercontent.com/8511385/191642408-966537c0-709a-4e04-aec1-6f58b2515400.png)
ZML启动：
![image](https://user-images.githubusercontent.com/8511385/191642489-9114a818-7ab5-47df-88cd-6c352442be07.png)
ZML错误信息：
![image](https://user-images.githubusercontent.com/8511385/191642545-c9c0f6ab-fbe9-45f7-9e0a-a4d29a948d11.png)
![image](https://user-images.githubusercontent.com/8511385/191642599-9c4121a3-bb43-4ef8-8918-52b183a206a0.png)

fffmepg日志：
![image](https://user-images.githubusercontent.com/8511385/191642657-c152ce2b-0bdc-4a76-9c7f-20a172ee5dd1.png)

感觉哪里配置有问题导致ffmepg这边走的http协议，引起的问题
求大佬指点

**Comment by xia-chu** [comment]
zlm能通过公网地址再访问自己的http端口吗？

**Comment by fengmao31** [comment]
rtp服务器没起吧？推流没推上去。播放端自然拉不到。播放端拉流器拉不到应该会报没有此track。

**Comment by fengmao31** [comment]
把服务器和两端的控制台打印都贴上。

**Comment by xia-chu** [comment]
这种一般是使用环境问题 先关闭issue了
