### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by tanzhenguoCN** [ZLMediaKit/ZLMediaKit#1981]
在arm机器上启用webrtc,在创建srtp时会失败，同样编译在x86上成功，返回错误：unspecified failure (srtp_err_status_fail)
同时其他流正常

**Comment by xia-chu** [comment]
编译 srtp时有 --enable-openssl吗

**Comment by tanzhenguoCN** [comment]
> 

我现在直接使用apt安装的额，是需要编译带openssl么，我试试离线编译的，那请问为什么x86的可以呢？

**Comment by tanzhenguoCN** [comment]
> 编译 srtp时有 --enable-openssl吗

谢谢您呀，是srtp编译没带openssl的问题，非常感谢!
