### ISSUE TITLE
[BUG]: Wiki中一些数据类型不准确

### ISSUE THREAD

**Issue by Washington-DC** [ZLMediaKit/ZLMediaKit#1983]
Wiki文档中，Http Hook  ->  on_record_mp4 请求参数中： file_size和start_time 应该为 uint64

**Comment by xia-chu** [comment]
wiki json数据类型描述 没区分整型长度 没做的那么严谨，而且有些语言也没有 uint64 uint32，只有long这种，所以就没格外声明有无符号和整型长度

**Comment by xia-chu** [comment]
感谢反馈 后面会注意这个问题
