### ISSUE TITLE
[技术咨询] 如何使用ca提供的key和pem生成ZML需要的pem文件。

### ISSUE THREAD

**Issue by lanwilliam** [ZLMediaKit/ZLMediaKit#1985]
**咨询的功能模块**
- 生成pem数字证书问题

**咨询的具体内容和问题**
- 我从运维那边拿到了ca给签发的数字证书，只有key和pem文件。
- 我尝试直接将pem文件通过-s制定给MediaServer启动使用，但是wvp拉流会出现错误
- 根据MediaServer的wiki说明，先通过ca提供的key生成csr，然后通过csr生成crt，然后通过crt和key生成ssl.pem，将ssl.pem通过-s制定给MediaServer启动加载，依旧不能拉通。
- 请问，针对这种通过真实域名支持https访问的情况，我应当如何把ca平台提供的key和pem进行转换，满足ZMLMediaServer的需求。
- wvp这边根据说明，通过pem生成jks文件是可以使用的。现在wvp已经可以https访问。

**Comment by lanwilliam** [comment]
对了，crt是从wiki第二步开始操作的，只有第一部生成key这里，直接用了ca给的key文件

**Comment by lanwilliam** [comment]
参考了default.pem的内容。
ca给的pem文件只包含证书，但是ZML应该是为了方便期间，把key和证书的内容都合并的pem中了。
所以只需要吧.key文件和.pem文件中的文本合并到一起，另存一个pem文件就可以了。
此pem非彼pem。不能直接用ca签发的pem文件。
也不需要按照wiki那样一步步操作。

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD
