### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by huliyan** [ZLMediaKit/ZLMediaKit#1986]
**咨询的功能模块**
- 开始tcp passive被动发送rtp(startSendRtpPassive)

**咨询的具体内容和问题**
-调测发现，使用startSendRtpPassive接口推rtp码流，但是如果传递src_port为0，接口调用后内部分配端口，会延迟等待client连接，等待连接建立后接口才返回，但使用内部分配随机端口，如果接口不返回，外部不知道zlm具体监听的实际端口号，无法通知client连接，请问如何让接口不需要等待先返回监听端口？
以下是zlm中片段代码：
![image](https://user-images.githubusercontent.com/114202694/191882416-54a394ed-3ec4-4b9a-8e74-0bad1afbff14.png)
以下是postman接口调用：
![image](https://user-images.githubusercontent.com/114202694/191882623-af9e6858-69ae-4e5b-b836-75dc4ae3cae7.png)

不胜感谢！
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
使用随机端口逻辑上是有bug,如果自己管理端口就没问题了

**Comment by huliyan** [comment]
感谢回复，另外如果自己管理端口，不知道zlm内部监听的时间，需要重复探测，增加应用设计复杂度，请问下这个bug有其他解决方案么？

**Comment by xiongguangjie** [comment]
只能修改代码

**Comment by xiongguangjie** [comment]
我修改一下吧，在一个分支，是否合并到主线看情况

**Comment by xiongguangjie** [comment]
使用这个分支 https://github.com/ZLMediaKit/ZLMediaKit/tree/feature/gbsendpassive_random_port_return_immediately 试一下，是否合并到主分支，看看作者的想法吧

**Comment by huliyan** [comment]
感谢各位！！！我们更新确认下

**Comment by huliyan** [comment]
> 感谢各位！！！我们更新确认下

谢谢，master版本已经支持
