### ISSUE TITLE
[技术咨询]webrtc丢包10%以上就会出现卡住的现象，请问有没有什么方法减少卡住的现象

### ISSUE THREAD

**Issue by funbinary** [ZLMediaKit/ZLMediaKit#1987]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
webrtc推流还是拉流？

**Comment by funbinary** [comment]
webrtc推流，丢包使用的clumy模拟的

**Comment by xia-chu** [comment]
zlm接收推流的抗丢包算法实现的比较初级 确实效果一般般

**Comment by xia-chu** [comment]
卡住不会花屏吧？zlm实现了基于GOP的丢包 确保不花屏

**Comment by funbinary** [comment]
不花屏

**Comment by funbinary** [comment]
关于这方面有没有什么优化方向，我参考参考

**Comment by xia-chu** [comment]
这些参数你可以调整下试试：

https://github.com/ZLMediaKit/ZLMediaKit/blob/master/webrtc/Nack.h#L44

**Comment by funbinary** [comment]
好的

**Comment by xia-chu** [comment]
webrtc nack和jitter buffer算法重构了 现在抗丢包算法可以达到10%以上了
