### ISSUE TITLE
是否考虑新增海康ISUP5.0（Ehome5）rtp推流解析适配[功能请求]

### ISSUE THREAD

**Issue by fengbozs** [ZLMediaKit/ZLMediaKit#1990]
经过测试目前系统对于海康Ehome5(ISUP5.0)设备推送的流数据无法解析，后期是否考虑增加此项适配？此类协议大量使用于移动手持设备，具有较大的使用场景。

**Comment by xiongguangjie** [comment]
协议文档，设备都没有怎么适配

**Comment by fengbozs** [comment]
谢谢，找到另外的解决方案了，用ehome协议的人可以借鉴：使用海康免费提供的设备网关服务器，ehome设备推流到网关服务器后可提供rtsp拉流，再进入zlmediakit进行转发

**Comment by fengbozs** [comment]
谢谢，找到另外的解决方案了，用ehome协议的人可以借鉴：使用海康免费提供的设备网关服务器，ehome设备推流到网关服务器后可提供rtsp拉流，再进入zlmediakit进行转发

**Comment by xiongguangjie** [comment]
这个网关的链接是什么能分享一下吗？？？？

**Comment by xiongguangjie** [comment]
无意中看到了网关的链接 https://open.hikvision.com/download/5cda567cf47ae80dd41a54b3?type=10&id=f893fd659ea143e7bb75bf05de2730ce
