### ISSUE TITLE
推流使用 H264 over RTP 进来，播放通过webrtc 协议，是否可以直接将RTP 包下行发出去，不再进行拆包封包 ？ 

### ISSUE THREAD

**Issue by kubbo** [ZLMediaKit/ZLMediaKit#1995]
**RTP 透传  webrtc **
推流端使用 RTP 协议封装H264 直接推流，播放走webrtc，请问是否可以直接将上行的RTP不变拆包封包，通过rtc 的方式推到播放端， 这样可以减少拆包封包带来的耗时，而且可以直接使用播放端的 webrtc 进行 jitter buffer 控制

**Comment by xia-chu** [comment]
透传目前不支持 不过支持rtp es推流 然后转webrtc

**Comment by kubbo** [comment]
好的，感谢哈
