### ISSUE TITLE
[技术咨询]通过mk_media_start_send_rtp接口发送数据，阅读源码发现在Frame.cpp文件中，数据进行了缓存，收到下一帧数据才会触发将缓存的上一帧数据去进行PS封装，录像回放时存在最后一帧数据无法发送，请问该问题该如何处理，感谢

### ISSUE THREAD

**Issue by zhangxinying** [ZLMediaKit/ZLMediaKit#1996]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
嗯 确实是有这个问题 PacketCache对象在缓冲rtp时 确实会导致最后一点数据无法flush

**Comment by zhangxinying** [comment]
现在是尝试在Frame.cpp文件中启动了一个线程并增加了一份缓存，来数据先缓存，通过线程不断读取数据再送去本文件_frame_cache缓存中，该方式疑似影响了原来的逻辑，请问是否有更好的办法可以将最后的数据flush，确保录像回放时数据不丢失，谢谢

**Comment by xia-chu** [comment]
嗯 FrameMerger对象也会引入一帧缓存

**Comment by zhangxinying** [comment]
请问这个问题可以优化吗

**Comment by xia-chu** [comment]
可以 在stop时flush下即可 后面优化下试试

**Comment by xia-chu** [comment]
done
