### ISSUE TITLE
[BUG]: zlm接收国标281814倍速下载流，录制的mp4视频丢失前15s片段

### ISSUE THREAD

**Issue by TristingChen** [ZLMediaKit/ZLMediaKit#1997]
使用环境：
unbuntu20+wvp+zlm

使用功能：
gb28181中的倍速下载

使用异常：
同一款设备（dvr），在livegbs中进行4倍速下载，几乎无视频丢失
在zlm中进行4倍速下载，视频录制的mp4文件丢失前15s的视频

抓包记录如下：
1.服务端抓包
2.zlm录制的mp4文件

初步结论：设备端推流正常，rtp无视频流丢失，但是zlm录制的视频却是丢了15s

[抓包记录.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9642679/default.zip)

**Comment by xia-chu** [comment]
开启zlm的rtp dump功能 然后把rtp分享上来 另外把你的mp4也分享上来

**Comment by TristingChen** [comment]
rtpdump与mp4文件如下：
[rtpdump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9642992/rtpdump.zip)

**Comment by TristingChen** [comment]
@xia-chu 大佬以上文件是否满足你的分析需要，能给出结论吗

**Comment by eanfs** [comment]
@TristingChen 怎么实现GB28181的四倍速下载的，正好在做这部分有点困难

**Comment by TristingChen** [comment]
你参考一下wvp和结合livegbs就可以了。

我自己做了设备录像下载数据归类切分---最大30分钟，避免到时候文件合并（原wvp是每10s生成一个mp4文件，最后合并成一个文件：优点--有下载进度，缺点：合并过程耗时很久），但是目前zlm没有下载进度的hook接口，所以我这里暂时没有下载进度

4倍速下，我的实现30分钟设备录像，下载耗时是8分钟左右--基本都是设备推流耗时




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月29日(星期四) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [BUG]: zlm接收国标281814倍速下载流，录制的mp4视频丢失前15s片段 (Issue #1997)





 
@TristingChen 怎么实现GB28181的四倍速下载的，正好在做这部分有点困难

**Comment by xia-chu** [comment]
@TristingChen 看了下你提供的rtp 原因是声明提供了aac 但是却没有，导致触发了`cached frame of unready track(H265) is too much, now cleared`,解决办法有3种：

- 1、配置文件全局关闭音频`enable_audio=0`
- 2、配置文件减小等待track就绪时间`wait_track_ready_ms=1000`
- 3、推流鉴权hook(on_publish)返回`enable_audio=0`(仅对该流有效)
