### ISSUE TITLE
[BUG]: test_server代理rtsp流，http-flv播放失败

### ISSUE THREAD

**Issue by pzhu10** [ZLMediaKit/ZLMediaKit#1998]
### 现象描述
编译test_server.cpp进行代理摄像头rtsp流测试，http-flv播放失败
[rtsp://127.0.0.1:554/live/chn0](rtsp://172.16.212.222:555/live/ch0)  rtsp代理地址可以正常播放
[http://127.0.0.1:80/live/chn0.live.flv](http://172.16.212.222:6881/live/helmet.live.flv) http-flv播放出3~4秒后卡住

### 如何复现?
直接使用test_server.cpp源码代理摄像头rtsp流即可复现

### 相关日志或截图
![image](https://user-images.githubusercontent.com/11349256/192216935-71873b4c-3882-402e-9b35-0ee1ce22ecf2.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:2022/9/25 master 分支最新代码
* **操作系统及版本**: ubuntu 16.04
* **硬件信息**: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
* **其他需要补充的信息**: 
@xia-chu 大神，是不是最近提交代码把http-flv改坏了~~~~

**Comment by xia-chu** [comment]
不是 可能改摄像头的时间戳有问题 导致时间戳跳变

**Comment by xia-chu** [comment]
zlm的http-flv时间戳又相对时间戳改成绝对时间戳了 如果源时间戳跳变 可能导致http-flv播放器异常

**Comment by pzhu10** [comment]
> zlm的http-flv时间戳又相对时间戳改成绝对时间戳了 如果源时间戳跳变 可能导致http-flv播放器异常

大神，请问 是不是可以通过修改 config.ini 的配置项 恢复使用 相对时间 时间戳

**Comment by xia-chu** [comment]
某些时间戳紊乱的rtsp流在开启转协议时可能会存在这个问题 不是普遍现象 先关闭了
