### ISSUE TITLE
[BUG]: 大华摄像头打开G711A花屏严重

### ISSUE THREAD

**Issue by LECYWZA** [ZLMediaKit/ZLMediaKit#2000]
测试设备: 大华摄像头[不需要依赖录像机], 摄像头自带国标平台, 打开G711A花屏严重

大华摄像头推流到之前版本的ZLM,只要摄像头是单独的, 不依赖录像机的, 京东淘宝随便入手一个大华, 打开G711A音频推国标,ZLM都会跳秒卡顿, 其他品牌没这个情况

自从ZLM经过下图这次更新后...
![image](https://user-images.githubusercontent.com/22796879/192481544-96d63cb2-c688-4394-8833-f0897472f4e8.png)
图片后续版本的ZLM已经不会卡顿跳秒了, 但是还是不太兼容, 只要摄像头开启了G711A音频, 用手在摄像头前晃动, 大概率会出现花屏,一堆马赛克, 关闭G711A音频画面完好,也没有花屏的情况 
![image](https://user-images.githubusercontent.com/22796879/192482552-dcb99a12-747e-43ae-8497-d79018ad7e4f.png)
![image](https://user-images.githubusercontent.com/22796879/192482804-eae60cfb-9c1e-4f00-9947-e21593379b3f.png)

花屏时我看了ZLM的控制台并无打印丢包和SSR不匹配等情况

这种花屏情况是大华摄像头的BUG吗? 如果ZLM能适配优化, 还是希望优化一下.....

**Comment by monktan89** [comment]
以前是完全不行，现在是半兼容？

**Comment by zxa225** [comment]
> 

看了你的抓包文件，大华摄像机的音频流貌似没有做ps封装

**Comment by zxa225** [comment]
在流媒体的配置文件中将enable_audo设置为0可以解决这个问题

**Comment by zxa225** [comment]
那你要改流媒体解析音频那部分的代码了，做没有ps封装的适配

**Comment by laoLiangLoveProgram** [comment]
海康的摄像头也有这个问题，我把音频编码切成AAC就好了，摄像头型号：DS-2DE3Q140MY-T/GLSE

**Comment by laoLiangLoveProgram** [comment]
换摄像头吧，如果不是甲方必须要求这个类型的摄像头，完全可以换个型号开发，你先把自己手上功能完成了，他们这是属于设备功能不完善造成的，你要么改源码，要么就换设备。

**Comment by xia-chu** [comment]
意思是  视频时PS封装 但是音频是ES裸流？

**Comment by zxa225** [comment]
> 意思是 视频时PS封装 但是音频是ES裸流？

是这个意思

**Comment by luo1227135067** [comment]
@monktan89 @xia-chu  看了历史讨论的情况, 请问ZLM后续有打算或是计划适配视频是ps封装, 音频是ES裸流的这种情况吗? 这个应该是摄像头的问题吧, 有这种问题是不是让厂家那边做出调整更好

**Comment by xia-chu** [comment]
> ZLM后续有打算或是计划适配视频是

不打算适配 这个太蛋疼了 这种单独的case zlm也没法适应

**Comment by xia-chu** [comment]
> @xia-chu 如果能让大华那边适配，我是不是只要和对面开发说，音频不要发ES裸流，也要和视频一样进行PS封装就行了。

嗯 音视频一起打包到ps容器即可

**Comment by xia-chu** [comment]
@LECYWZA  这个问题 建议在jessibuca项目提issue
