### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by tianya2222** [ZLMediaKit/ZLMediaKit#2001]
**咨询的功能模块**
- GB28181推拉流问题

**咨询的具体内容和问题**
- 部署后播放大华网络摄像机视频流时，前端页面总是提示：收流超时，zlm日志显示openRtpServer 和closeRtpServer都正常，日志有打印：RtpProcess timeout，不知道是什么原因，哪位大神能给点提示？用的是wvp-GB28181-pro。设备注册正常，心跳正常

**Comment by tianya2222** [comment]
![image](https://user-images.githubusercontent.com/90952378/192684377-7c96a525-b7ae-4d16-85e8-72cc141405f5.png)

**Comment by tianya2222** [comment]
前端现象：

**Comment by xia-chu** [comment]
这个不是bug 这个是wvp配置问题 请仔细查看wvp配置文件注释

**Comment by tianya2222** [comment]
我是当成技术问题咨询下的，实在找不到原因才到这里来试一试
