### ISSUE TITLE
报错ssrc不匹配

### ISSUE THREAD

**Issue by ytw1ytw** [ZLMediaKit/ZLMediaKit#2003]
**咨询的功能模块**
报错ssrc不匹配

**咨询的具体内容和问题**
配置固定流后会报错
![图片](https://user-images.githubusercontent.com/114635488/192932576-bc6dffbd-8005-4aa5-b8e3-7ce7226c7689.png)

**Comment by xia-chu** [comment]
可以看到是在两个ssrc之间来回切换 说明被推流了2次

**Comment by ytw1ytw** [comment]
> 可以看到是在两个ssrc之间来回切换 说明被推流了2次

这个会有什么影响，需要怎么操作能固定流地址

**Comment by xia-chu** [comment]
> > 可以看到是在两个ssrc之间来回切换 说明被推流了2次
> 
> 这个会有什么影响，需要怎么操作能固定流地址

你用的wvp-pro吧？ 建议更新下它试试 这个是sip服务器调度bug
