### ISSUE TITLE
[BUG]: 目录遍历漏洞

### ISSUE THREAD

**Issue by TaoistMagicianBX** [ZLMediaKit/ZLMediaKit#2005]
### 现象描述

在使用过程中出现了目录遍历漏洞，通过修改配置文件中的dirMenu参数的值使得 http://x.x.x.x:81/../../../../../etc/passwd 这种方式被拦住了，但是当格式变为 http://x.x.x.x:81/..%2f..%2f..%2f..%2f..%2fetc/passwd 这种依然会出现目录遍历

### 相关日志或截图

![image](https://user-images.githubusercontent.com/73626305/192972929-eada5df8-26e6-421e-810f-6c4d7e3bc01e.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
是个漏洞

**Comment by xiongguangjie** [comment]
你什么版本的，这个bug 在最新的版本中已经被修复了呀

**Comment by xiongguangjie** [comment]
在最新的版本无法复现
