### ISSUE TITLE
[技术咨询]将RTSP流地址录制为MP4文件

### ISSUE THREAD

**Issue by eanfs** [ZLMediaKit/ZLMediaKit#2006]
- MP4录制功能

- 是否可能直接调用哪个方法，将RTSP流地址录制为MP4文件

**Comment by xia-chu** [comment]
addStreamProxy接口

**Comment by eanfs** [comment]
这个接口调用成功了，
但录制过程中会分成好几个文件是什么原因？
谢谢

**Comment by xia-chu** [comment]
> 这个接口调用成功了， 但录制过程中会分成好几个文件是什么原因？ 谢谢

mp4必须切片 否则中途断电就白录了
