### ISSUE TITLE
推流黑屏

### ISSUE THREAD

**Issue by Small-North** [ZLMediaKit/ZLMediaKit#2008]
**咨询的功能模块**
- rtmp推流

**咨询的具体内容和问题**
我这边对接前端设备推流，rtmp 264。能收到推流，但是播放是黑屏的。本地用FFmpeg推流是正常的。请问这个问题应该怎么排解和解决？谢谢

**Comment by xia-chu** [comment]
建议ffplay播放一下 观察下ffplay日志 然后贴上ffplay的日志截图

**Comment by Small-North** [comment]
![Uploading 1657095683752.png…]()

**Comment by Small-North** [comment]
![Uploading 1657095683752.png…]()

**Comment by Small-North** [comment]
截图，感觉是265转码错了
![Uploading 1657095683752.png…]()

**Comment by Small-North** [comment]
![1657095683752](https://user-images.githubusercontent.com/43372031/193243981-dfc888c3-d023-40b6-8955-713244a1154c.png)
感觉是265转264错误

**Comment by Small-North** [comment]
![1664531218823](https://user-images.githubusercontent.com/43372031/193244098-cc7032c6-8342-4a1a-aefb-3da6220a8689.jpg)
ga感觉是265转264错误

**Comment by Small-North** [comment]
我关闭了开启录制就好了，我搜了下：当ts封装转mp4封装的时候，尽管音频编码aac和视频编码h264是拷贝复用关系，但是某些参数还是需要进行解码aac或者h264才能拿到的，所以ffmpeg必须支持 --enable-decoder=aac 以及 --enable-decoder=h264 。这和自己之前的理解确实存在很大的出入。

**Comment by sctstech** [comment]
请问怎么关闭开启录制？ @Small-North

**Comment by xia-chu** [comment]
所以推流本身就有问题？

**Comment by sctstech** [comment]
@xia-chu 我采用zlm+wvp，发现应该是虚拟机的问题，两台虚拟机服务器在wvp里都看不了视频。而在另一台物理机上登录wvp就可以看，但是wvp里视频是上下颠倒的，调用接口播放又是正的

**Comment by Small-North** [comment]
@xia-chu 请问录制是调用ffmpeg进行录制吗？是不是配置文件ffmpeg配置错误或者ffmpeg版本问题。
[ffmpeg]
bin = ffmpeg
cmd=%s -rtsp_transport tcp -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264  -f flv %s
log = ./ffmpeg/ffmpeg.log
snap = %s -i %s -y -f mjpeg -t 0.001 %s

![1657095683752](https://user-images.githubusercontent.com/43372031/194685624-13531dfe-81bc-41a7-b460-f3a3ad02d1db.png)

**Comment by Small-North** [comment]
@xia-chu 请问录制是调用ffmpeg进行录制吗？是不是配置文件ffmpeg配置错误或者ffmpeg版本问题。
[ffmpeg]
bin = ffmpeg
cmd=%s -rtsp_transport tcp -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log = ./ffmpeg/ffmpeg.log
snap = %s -i %s -y -f mjpeg -t 0.001 %s
![1665199239182](https://user-images.githubusercontent.com/43372031/194685652-2b2d8ae5-5be4-4825-b46f-60d0342dd8f3.png)

**Comment by Small-North** [comment]
@sctstech 有接口调用开启录制和关闭录制。你看下wiki。https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API

**Comment by xia-chu** [comment]
> @xia-chu 请问录制是调用ffmpeg进行录制吗？是不是配置文件ffmpeg配置错误或者ffmpeg版本问题。 [ffmpeg] bin = ffmpeg cmd=%s -rtsp_transport tcp -fflags nobuffer -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s log = ./ffmpeg/ffmpeg.log snap = %s -i %s -y -f mjpeg -t 0.001 %s ![1665199239182](https://user-images.githubusercontent.com/43372031/194685652-2b2d8ae5-5be4-4825-b46f-60d0342dd8f3.png)

zlm的mp4录制不借助FFmpeg任何代码
