### ISSUE TITLE
[BUG]: 调用 /index/api/stopRecord 提前结束录像，结束后超时不触发无人观看主动关闭流

### ISSUE THREAD

**Issue by laoLiangLoveProgram** [ZLMediaKit/ZLMediaKit#2010]
### 现象描述

- 调用 /index/api/stopRecord 提前结束录像，结束后超时不触发无人观看主动关闭流

### 如何复现?
1. 配置文件中 [general] 下 streamNoneReaderDelayMS=30000， [record] 下 mp4_as_player=1
2. 开启正常推流，正常播放
3. 调用 /index/api/startRecord 开启录像， max_second 设置 600 秒
4. 关闭播放器
5. 调用  /index/api/stopRecord 停止录像 , 该步骤需在 max_second 设定的结束时间之前
6. streamNoneReaderDelayMS设定超时时间到达，但是并未触发  无人观看主动关闭流， 必须等到 max_second 设定的结束时间到达以后
7. 结果：提前结束录像，超时不触发无人观看主动关闭流

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
编译日期: 2022-09-19 09:11:50
当前git分支: master
当前git hash值: b77c19c

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
修复了 你测试下
