### ISSUE TITLE
[技术咨询]不同分辨率视频源合并后的m3u8文件播放异常

### ISSUE THREAD

**Issue by AlphaWu** [ZLMediaKit/ZLMediaKit#2012]
**咨询的功能模块**
- m3u8文件相关

**咨询的具体内容和问题**
- 网络机顶盒一台，提供ZLM的拉流数据源。网络机顶盒的输入是笔记本电脑，在多人使用情况下，多台笔记本电脑的分辨率是不一致的。这时候，将所有ts文件合并后的m3u8文件，在分辨率切换的ts文件，会出现异常，导致整个文件不能正常播放。

**Comment by xia-chu** [comment]
zlm hls拉流该设备吗？按道理，zlm是支持分辨率切换的

**Comment by AlphaWu** [comment]
是使用zlm进行拉流的，拉流内容是机顶盒的ts文件，拉流地址是http://192.168.1.1/0.ts。在使用ffmpeg进行拉流，不会出现这种情况，后面我再详细测试一下，把出现问题的ts文件发上来。

**Comment by AlphaWu** [comment]
文件说明：
压缩包有5个文件，分别是
0.ts 正常文件，文件长度约6秒，输入源是台式机
1.ts 不正常文件，文件实际长度约9秒，ZLM记录的长度约6秒。在该文件生成过程中，切换了输入源，该文件应该是包含了3个源，分别是：台式机，推流盒子默认画面，笔记本电脑；
2.ts 正常文件，文件长度约6秒，输入源是笔记本电脑
3.ts 正常文件，文件长度约6秒，输入源是笔记本电脑

现象描述：
1.在本地用PotPlayer播放所有文件都正常；
2.将文件放到Web服务器上，播放有异常；
2.1 如果播放index.m3u8文件，播放到10秒左右，进度条会直接跳转到结尾，无法拖到；异常。
2.2 修改index.m3u8文件，仅保留1.ts，播放到4秒钟左右，会直接跳到结尾；异常。
2.3 修改index.m3u8文件，仅保留2.ts和3.ts，播放正常。
2.4 修改index.m3u8文件，仅保留0.ts、2.ts和3.ts，播放到7秒后，直接跳转到结尾；异常。

结论：
？不同的输入源，不能合并为单一的m3u8文件？

 @xia-chu 请老大帮忙看看。

[test.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/9840194/test.zip)
