### ISSUE TITLE
[技术咨询]请问溯源模式是随机还是按分号（；）分隔的先后顺序

### ISSUE THREAD

**Issue by ladycwd** [ZLMediaKit/ZLMediaKit#2014]
**咨询的功能模块**
- [cluster]
#设置源站拉流url模板, 格式跟printf类似，第一个%s指定app,第二个%s指定stream_id,
#开启集群模式后，on_stream_not_found和on_stream_none_reader hook将无效.
#溯源模式支持以下类型:
#rtmp方式: rtmp://127.0.0.1:1935/%s/%s
#rtsp方式: rtsp://127.0.0.1:554/%s/%s
#hls方式: http://127.0.0.1:80/%s/%s/hls.m3u8
#http-ts方式: http://127.0.0.1:80/%s/%s.live.ts
#支持多个源站，不同源站通过分号(;)分隔
origin_url=

**咨询的具体内容和问题**
- 1、请问溯源模式是随机还是按分号（；）分隔的先后顺序；
- 2、请问源站支持域名吗；

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
1、源站按照轮询方式拉流，源站不分主次，被溯源的概率一致。
2、源站支持域名
