### ISSUE TITLE
[技术咨询]webrtc直推直拉的情况，多路拉流耗cpu高

### ISSUE THREAD

**Issue by jayy1943** [ZLMediaKit/ZLMediaKit#2017]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
- 使用自带的webrtc测试页面，推笔记本720p摄像头的rtc流，服务器的ZLMediaKit的cpu占用稳定在1.5%左右，然后用Chrome同时拉9路webrtc流，发现服务器的ZLMediaKit的cpu占用上升到6%。cpu为i7-11800H，在主频低的机器上测试的话，cpu的占用会更高。
- 问题是：webrtc直推直拉的情况，理论上服务器的ZLMediaKit不需要做转码吧，不知是什么情况，导致多路拉流的cpu消耗基本呈现一个线性的增长？烦请大佬解惑，感谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
你可以把转协议关闭了 配置文件`_demand`相关的配置全部置1，不过这个只对推流能节省cpu。
拉流节省cpu的做法是加大配置文件的`mergeWriteMS`,不过这个会影响体验

**Comment by xia-chu** [comment]
你是linux上测试的吗? 你说的6%应该是单核cpu使用率

**Comment by jayy1943** [comment]
> 你可以把转协议关闭了 配置文件`_demand`相关的配置全部置1，不过这个只对推流能节省cpu。 拉流节省cpu的做法是加大配置文件的`mergeWriteMS`,不过这个会影响体验

是的，这个_demand的相关配置我在测试前也都关了，确实也只是对推流省cpu；mergeWriteMS验了500ms和1000ms的情况，没有看到改善。。可能跟跑在docker里有关系？我后续测一下直接跑的情况。


> 你是linux上测试的吗? 你说的6%应该是单核cpu使用率
是的，单核6%，相信压测更多路的话，多核性能可以发挥出来。不知您有无了解，webrtc做直播的话，能否支撑的下几千路的拉流。。这方面有没什么优化建议呢？感谢！

**Comment by jayy1943** [comment]
我这边测了linux下直接跑，跟docker的没什么区别。
发现调整rembBitRate参数有比较明显的变化，改为1M码率的话，推一路720p摄像头的rtc流，拉36路，基本稳定在15%的cpu占用；如果是改为4M码率的话，推一路720p摄像头的rtc流，拉36路，基本稳定在30%的cpu占用。上述测试都是在mergeWriteMS=0的情况下进行。
从这个角度看的话，是否可以说明cpu的消耗集中在twcc自动调整码率上，或者remb的转码消耗呢？

**Comment by xia-chu** [comment]
不是 twcc开启后 码率一般比较高 remb模式时 是固定码率 一般比twcc模式码率低。
低码率情况下 会更节约cpu
