### ISSUE TITLE
[技术咨询]zlm可以创建推流地址吗

### ISSUE THREAD

**Issue by Desiki-high** [ZLMediaKit/ZLMediaKit#2019]
**具体问题**
- 使用javacv拉取摄像头的rtsp流之后进行帧处理，处理结束后想推送到zlm，javacv提供的方法需要提供一个推流地址，请问zlm可以创建一个推流地址让javacv进行主动推流吗？

**Comment by Washington-DC** [comment]
推刘德华，推流地址是你自己定义的

**Comment by Washington-DC** [comment]
推流的话，地址是你自己定义的

**Comment by xia-chu** [comment]
zlm的推流地址你想设置多少就多少 你只要在on_publish hook时返回鉴权通过即可
