### ISSUE TITLE
使用ffplay拉取rtsp码流采用udp传输媒体时，客户端无法接收到码流

### ISSUE THREAD

**Issue by chenshan911210** [ZLMediaKit/ZLMediaKit#2020]
### 现象描述
ZLMediait部署在公网阿里云服务器上边，采用obs推送一路rtmp码流(包含音视频)，然后使用ffplay采用rtsp协议播放这路码流(媒体传输采用udp的方式)，ffplay无法正常播放。ffplay在公司内网环境，公司网络可以和阿里云上的服务器网络是可以连通的

### 如何复现?
首先：ZLMediait部署在公网阿里云服务器上边，采用obs推送一路rtmp码流(包含音视频)。
然后：使用ffplay采用rtsp协议播放这路码流(媒体传输采用udp的方式)
期望：ffplay可以正常观看到obs推送到服务器上的视频
结果：ffplay无法看到obs推送到服务器上的视频
问题原因：ZLMediakit 作为rtsp的server端的时候，没有根据客户端的udp媒体通道的udp穿透包使用的端口来替换掉setup协商出来的端口，导致的服务器无法把媒体数据发送到客户端去

### 相关日志或截图
rtsp端口协商截图
![4D01C83D-E525-4179-8840-DC8CE3211D17](https://user-images.githubusercontent.com/12842114/194755738-9c769bbd-e85f-4f18-8d52-bcbb661e65b8.png)

媒体通道抓包截图
![微信截图_20221009200742](https://user-images.githubusercontent.com/12842114/194756135-0252d55a-2f5a-4869-8011-497867341758.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by chenshan911210** [comment]
121.41.102.126 为阿里云服务器的公网ip，10.168.216.186为阿里云服务器的内网ip， 27.27.243.142 ffplay的ip

**Comment by xia-chu** [comment]
zlm支持接收rtsp播放器的udp打洞包 可以给nat内的rtsp播放器发udp rtp的

**Comment by chenshan911210** [comment]
从抓包上边来分析这个问题,rtsp播放器是打洞失败了的,zml并没有往接收到的打洞包的地址发包,仍然再往setup时协商的地址在发包,是需要在配置文件中开启什么配置么?

**Comment by phlahut** [comment]
同样遇到类似的问题  运行zlm官方docker镜像，推一路rtmp视频流到zlm后，然后ffplay播放rtsp视频流失败，但是播放rtmp视频流正常

**Comment by phlahut** [comment]
> > 从抓包上边来分析这个问题,rtsp播放器是打洞失败了的,zml并没有往接收到的打洞包的地址发包,仍然再往setup时协商的地址在发包,是需要在配置文件中开启什么配置么?
> 
> 不用改配置文件 可能你没映射udp端口

![image](https://user-images.githubusercontent.com/21032464/195377471-d448185d-8273-4479-a0c5-4027ab2440d9.png)

**Comment by xia-chu** [comment]
zlm在公网部署时 是支持给内网中的player发rtp udp数据的，zlm也支持了player的udp打洞包

**Comment by xia-chu** [comment]
zlm的udp端口默认范围是30000~30500 ,请设置安全组；docker也需要映射udp端口
