### ISSUE TITLE
[技术咨询]ws模块主动发送数据

### ISSUE THREAD

**Issue by yangwei1987** [ZLMediaKit/ZLMediaKit#2021]
**ws模块**
- 请描述您想咨询zlmediakit的哪部分功能

您好websocket主动推送数据功能是用一下函数实现的吗，有没有别的方法可以实现websocket 的实时推送
-  //每隔一段时间触发，用来做超时管理
    void onManager() override{
        DebugL;
    }

**Comment by xia-chu** [comment]
可以用flv.js播放ws-flv的流
