### ISSUE TITLE
[技术咨询]请问一下ZLM能够实现webrtc的p2p视频播放吗

### ISSUE THREAD

**Issue by jamesZHANG500** [ZLMediaKit/ZLMediaKit#2022]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
webrtc

**咨询的具体内容和问题**
 有这样的设想，想实现浏览器与摄像头之间通过webrtc 以p2p的方式直播看视频 ，如果p2p不通，除非鉴权才能通过中继服务器播放视频
 了解webrtc需要搭建服务器，能否之间使用zlmediakit 搭建到公网作为webrtc中继服务器
浏览器需要播放视频，通过第三方支持webrtc的js播放器，播放
摄像头端 是否也可以用zlmediakit 移植到嵌入式设备（比如海思摄像头） 作为peer端，可以使用p2p播放视频

**Comment by xia-chu** [comment]
不能 zlm是定位sfu服务器 必须部署在公网上

**Comment by jamesZHANG500** [comment]
好的，了解了，谢谢回复
