### ISSUE TITLE
[BUG]: hls录制达到十个小时以上时，片段长度会突然从2秒一个，切换到5秒一个片段，多路同时录制hls，现象一样，时间一致

### ISSUE THREAD

**Issue by taohongyan** [ZLMediaKit/ZLMediaKit#2024]
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
会不会是流的编码gop编程5秒了?

**Comment by taohongyan** [comment]
> 会不会是流的编码gop编程5秒了?


我场景是这样的，推一路流到zlm，实时视频用webrtc，音频是g711A，实时视频没问题，但是我还需要录像hls，切片ts，但是mpegts容器不支持g711系列音频格式，所以我用addFFmpegSource拉了一路出来，音频从g711转aac，做hls切片，但是测试了2个晚上，都是ffmpeg工作了13小时14分钟左右，导致zlm切片异常，从配置的2秒变成了5秒，看ffmpeg日志发现报了“输出流中的非单调DTS”,初步怀疑是音频做了转码，导致音视频不同步了，13小时14分钟这个数字好像就是rtp时间戳4个字节能表示的最大时间戳了，也就是时间戳溢出导致的。

**Comment by taohongyan** [comment]
![Uploading 1665653373867.png…]()

**Comment by taohongyan** [comment]
[Uploading 54-29_23934.zip…]()
