### ISSUE TITLE
[技术咨询]请问一下怎么在录制时按自己的要求存储mp4文件名

### ISSUE THREAD

**Issue by ladycwd** [ZLMediaKit/ZLMediaKit#2025]
**咨询的功能模块**
-  api录制

**咨询的具体内容和问题**
- 请问一下怎么在录制时按自己的要求存储mp4文件名并在使用stop接口停止录像后在接口中返回录制的文件路径及文件名

**Comment by ladycwd** [comment]
请问怎样修改开始录制和结束录制的API，找了一晚上了还是不知道从哪里下手，
我想完成的功能是：
1、在startRecord增加可选参数Mp4RecordName_Custom，判断API地址参数中是否带了录像文件名，如果有文件名就按指定文件名存储，超过切片时间的再在自定义文件名后加-1、-2这样的文件名标识；
2、在startRecord增加可选参数Mp4RecordMaxTime_Custom，判断地址中是否带了该参数，如果有到了指定的时间后自动结束录像并存储文件，防止在调用stopRecord时失败而一直在录，在开始时就定好默认的时间，如果没有就按默认配置执行录像任务；
3、在stopRecord中先判断该stream录像状态，如果正在录制就停止录像，并返回该文件的播放地址，如果是接口调用失败已经自动停止了的就直接返回播放地址
由于业务需求，希望获取到比较精准的录像片断，给前端使用，前端只需要在调用stopRecord时返回该文件的访问地址，
请大佬指点一下我应该怎样修改这个两个接口？

**Comment by Washington-DC** [comment]
主要代码是 src\Record\MP4Recorder 这个文件，你可以看一下里边有文件命名和开始结束录制相关代码，FYI

**Comment by ladycwd** [comment]
上面的兄弟能不能再请教一下，您说的这个文件似乎是修改业务存储逻辑，但是具体的判断接口参数是应该修改哪个文件呢

**Comment by eanfs** [comment]
官方建议是在回调里面处理文件名

**Comment by Washington-DC** [comment]
> 

你可以从installwebapi这里可以看到 是怎么从web请求到开始录制的过程，以及接口参数的处理。
或者如上面所说，在文件录制完成的回调中处理文件名称。

**Comment by xia-chu** [comment]
在on_record_mp4 hook中修改文件或上传云存储，本地文件名没什么意义 哪怕是uuid随机字符串都行 最终要结合数据库使用 url也不会直接给用户看到细节
