### ISSUE TITLE
[功能请求]startSendRtp转发丢数据

### ISSUE THREAD

**Issue by lsc102** [ZLMediaKit/ZLMediaKit#2027]
**描述该功能的用处，可以提供相关资料描述该功能**
国标转发的时候，没有缓存机制，如果gop长度较大时，转发后需要等待很久才出画面
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
是，现在startSendRtp接口转发时，没有缓存GOP，会导致首画面比较慢。
**描述你期望实现该功能的方式和最终效果**
调用startSendRtp接口时，发送数据第一个是I帧，这样首画面比较快，体验会很好。

感谢大佬，请考虑下这个功能！

**Comment by mayunxi** [comment]
目前也是遇到这个问题，海康相机25帧，开启smart264智能编码，可能会存在250fps才一个I帧，也就是10s秒一个I帧，导致首播时间过长的问题。https://github.com/ZLMediaKit/ZLMediaKit/issues/2199#issue-1531868466。可以缓存最新的I帧，是一个好办法。

**Comment by xia-chu** [comment]
这个特性已经在 2023/4/17 支持了： 978143c8
