### ISSUE TITLE
[BUG]: TS文件被删除，hls.m3u8文件被删除

### ISSUE THREAD

**Issue by itweixiang** [ZLMediaKit/ZLMediaKit#2030]
### 现象描述

现有一个功能，【只播放筛选时间内的视频】。

如有02:22:34-02:32:34.mp4、02:32:35-02:42:34.mp4两个文件。想要查看[02:28:34-02:38:34]之间的视频

wvp+zlm的方式，是通过查看mp4录像文件，然后依次点播这两个文件，拖曳进度条到02:28:34进行播放。

这样操作比较繁琐。

我想使用hls索引的功能，根据原先hls.m3u8索引文件的内容，通过我自己的代码生成02:28:34-02:38:34.m3u8。

但是在实现的过程，**ts录像文件和hls.m3u8索引文件，经常被删除**。

### 如何复现?

由于不大清楚zlm的代码，所以只能根据我自己的使用过程简单描述。

- 在修改wvp和zlm的port_range的时候，很高的概率会导致**ts\m3u8索引文件被全部删除**
- 在重启wvp的时候，概率会导致m3u8索引文件**原先的内容被清空（reset）**
- 在调用wvp接口/api/playback/start的借口失败时，高概率会导致m3u8索引文件**原先的内容被清空（reset）**
- 将resetWhenRePlay=1，重启zlm，必把hls.m3u8文件给reset

我在HlsPlayer.cpp的代码中，看到有很多reset()的方法，相信你们应该也是知道这个情况的。可能是我自己不大清楚你们的设计思想或者使用方法有误。

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

resetWhenRePlay=0

[hls]
fileBufSize=65536
filePath=./www
segDur=2
segNum=0
segRetain=50000000
broadcastRecordTs=0
deleteDelaySec=0
segKeep=1

**Comment by itweixiang** [comment]
我应该怎么避免hls.m3u8文件和ts文件被reset\删除？或者我应该怎么实现我想做的【只播放筛选时间内的视频】？

**Comment by xiongguangjie** [comment]
你这个直播是会删除老的ts文件的，除非是录像就不会删除

**Comment by xiongguangjie** [comment]
你指定开始与结束时间，就需要你录制保存ts片段，然后记录ts片段的开始与结束时间，最后生成m3u8 来对外提供服务

**Comment by xiongguangjie** [comment]
保存ts片段，需要hls作为录像
