### ISSUE TITLE
[BUG]: Windows 11上无法启动，于是尝试使用VS2022调试，失败，遇到异常

### ISSUE THREAD

**Issue by Looong01** [ZLMediaKit/ZLMediaKit#2034]
### 现象描述

一步一步按照《快速开始》进行编译、运行调试
双击MediaServer.exe或者powershell、cmd使用.\MediaServer运行后闪退
于是使用vs进行调试，发现问题：
0x00007FFB16A7F9C7 (libcrypto-3-x64.dll)处(位于 MediaServer.exe 中)引发的异常: 0xC0000005: 读取位置 0x0000000000000069 时发生访问冲突。
如图：
![image](https://user-images.githubusercontent.com/69568351/196909587-8d0853ae-f547-49c8-ace4-715539b639bd.png)

### 如何复现?
1. 获取代码
git clone --depth 1 https://gitee.com/xia-chu/ZLMediaKit
cd ZLMediaKit
git submodule update --init
2. 安装依赖库
安装openssl，在给定的网站下载一键安装
3. 使用VS2022打开
![image](https://user-images.githubusercontent.com/69568351/196910362-fca372a9-1a42-4f18-8f5b-a450b35338b4.png)
![image](https://user-images.githubusercontent.com/69568351/196910498-e3acf843-1295-4db3-baca-fb510e100870.png)
![image](https://user-images.githubusercontent.com/69568351/196910677-14fa30fd-1b21-4583-83b3-1aea2de8863c.png)

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
处理器	AMD Ryzen 5 5600X 6-Core Processor                3.70 GHz
机带 RAM	32.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	为 10 触摸点提供笔和触控支持

版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎5/‎15
操作系统版本	22621.741
体验	Windows Feature Experience Pack 1000.22636.1000.0
Visual Studio 2022

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你好 闪退的原因是依赖的ssl和crypto库在主机上不存在导致的，请把ssl和crypto库的dll文件复制到MediaServer.exe文件当前目录。
