### ISSUE TITLE
有没有微信群?我想智能识别后，自己推流，先建立流，然后自己发图像推流？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ZLMediaKit/ZLMediaKit#2035]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xinsuinizhuan** [comment]
windows、linux ubuntu平台下，自己使用opencv识别后，把识别后的cv::Mat格式图像，推到推流器里面，来推识别后的结果图像流？我看demo都是直接转发推流，有没有单独图像输入推流的接口？

**Comment by xia-chu** [comment]
> ubuntu平台下，自己使用opencv识别后，把识别后的cv::Mat格式图像，推到推流器里面，来推识别后的结果图像流？我看demo都是直接转发推流，有没有单独图像输入推流的接口？

其实原理一样的 你只要能产生H264 后续用法一致

**Comment by xia-chu** [comment]
ZLMediaKit/api/tests/pusher.c

**Comment by jakesom** [comment]
兄弟你做出来了吗，现在我也是卡在这里，只能拉流、解码、识别、编码，但是卡在了将编码好的视频流传入推流器里，求请教
