### ISSUE TITLE
[BUG]: 音频转码分支ZLMediakit-feature-transcode, HIK-IPC  H264+AAC  rtsp拉流测试，webrtc播放有2-3秒延迟现象

### ISSUE THREAD

**Issue by taohongyan** [ZLMediaKit/ZLMediaKit#2040]
测试发现，ZLMediakit-feature-transcode分支音频转码aac-opus情况下，HIK-IPC RTSP拉流测试， webrtc 播放视频画面会有2-3秒左右延时，但是，在开启HLS录制的情况下，又没有延迟现象，请问，这种现象怎么出现的？谢谢

**Comment by xia-chu** [comment]
@mtdxc 大佬 这个问题有时间麻烦看下

**Comment by mtdxc** [comment]
> 测试发现，ZLMediakit-feature-transcode分支音频转码aac-opus情况下，HIK-IPC RTSP拉流测试， webrtc 播放视频画面会有2-3秒左右延时，但是，在开启HLS录制的情况下，又没有延迟现象，请问，这种现象怎么出现的？谢谢

你是用transcode还是transcode2分支的代码？

**Comment by taohongyan** [comment]
@mtdxc  ZLMediakit-feature-transcode分支

**Comment by taohongyan** [comment]
@mtdxc 两个分支都试过了，都有延时现象

**Comment by taohongyan** [comment]
我们场景很简单，是这样的：
1.2个HIK IPC摄像机，支持AAC+G711系列音频格式，一路配置为AAC音频格式，一路配置为G711音频格式
2.zlm使用API 调用addStreamProxy添加rtsp拉流地址 
3.同时使用webrtc播放（摄像机和服务器均经过NTP校时），一路AAC-OPUS，另一路G711
4.对比2路图像webrtc播放画面的时间戳，发现经过音频转码的图像比不转码的慢2-3秒

**Comment by mtdxc** [comment]
不好意思手头上没有带aac编码的摄像头，不过我用obs推了路aac的rtmp流，来模拟你这情况；
测试发现 rtc音频转码播放是不会造成多少延迟的；
![image](https://user-images.githubusercontent.com/569005/198012563-47295fdb-f1a9-4cbf-a5b5-80132306db80.png)
我建议你别用两个摄像头测试，你先用rtc浏览器打开aac转码后的摄像头流；
然后通过 ffplay -fflags nobuffer rtsp拉流地址，然后观看同一台摄像头出的流之间的延迟。

**Comment by mtdxc** [comment]
你将这个条件判断去掉，再试看看...
            _audio_enc->setOnEncode([this](const Frame::Ptr& frame) {
                //if (_enabled || !_on_demand) {
                    RtspMuxer::inputFrame(frame);
                //}
            });
