### ISSUE TITLE
[技术咨询]gst-launch-1.0推rtsp流超时问题

### ISSUE THREAD

**Issue by wangdanfeng0416** [ZLMediaKit/ZLMediaKit#2045]
使用gst-launch-1.0推rtsp流，超时连接不上
gst推流命令：gst-launch-1.0 rtspsrc location=rtsp://admin:xxx@xxx ! queue ! rtph264depay ! h264parse ! queue ! nvv4l2decoder ! m.sink_0 nvstreammux name=m width=1920 height=1080 batch-size=1 live-source=1 ! nvinfer config-file-path=config_nano_S8.txt ! nvmultistreamtiler  ! nvvideoconvert  ! nvdsosd ! nvvideoconvert ! nvv4l2h264enc ! rtspclientsink location=rtsp://xxx/live/test216 sync=1
![微信图片_20221025101504](https://user-images.githubusercontent.com/37286554/197666337-0a02a40f-49db-4809-9cc4-37dfabcada02.jpg)
求大佬帮忙！

**Comment by xia-chu** [comment]
你需要指定rtsp传输方式为tcp。 看看rtspclientsink插件还支持什么参数吧

**Comment by wangdanfeng0416** [comment]
> 你需要指定rtsp传输方式为tcp。看看rtspclientsink插件还支持什么参数吧

谢谢大佬，我加了protocols=tcp测试通了！谢谢！
