### ISSUE TITLE
[功能请求] getMp4RecordFile获取MP4录像列表添加文件大小，和录像时长

### ISSUE THREAD

**Issue by mrzkai** [ZLMediaKit/ZLMediaKit#2046]
**描述该功能的用处，可以提供相关资料描述该功能**

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
录像列表如果没有录像时长的话不够直观

**Comment by xia-chu** [comment]
文件大小可以获取到 但是文件时长获取不到 这个接口只是遍历文件系统；复杂的检索需要你结合数据库失效，zlm在生成mp4文件时会触发on_record_mp4 hook，需要你记录元数据到数据库

**Comment by mrzkai** [comment]
可否根据文件的修改时间来定义为结束时间，再根据生成的文件名的开始时间来计算出录像时长

**Comment by mrzkai** [comment]
根据on_record_mp4的回调将生成mp4文件的信息存储到自己数据库中来查询获取，那就不再需要去调用getMp4RecordFile了是吧

**Comment by xia-chu** [comment]
是的 getMp4RecordFile接口本来是合并的一个pr 我个人是不赞成这种使用方式的

**Comment by huo-huo** [comment]
> 文件大小可以获取到 但是文件时长获取不到 这个接口只是遍历文件系统；复杂的检索需要你结合数据库失效，zlm在生成mp4文件时会触发on_record_mp4 hook，需要你记录元数据到数据库

时长是否可以已文件名的形式记录下来 现在的MP4文件是开始时间命名 是否可以在结束时吧结束时间也添加到文件名中

**Comment by xia-chu** [comment]
> 时长是否可以已文件名的形式记录下来 现在的MP4文件是开始时间命名 是否可以在结束时吧结束时间也添加到文件名中
你可以自行实现这种功能 自己解析文件名

**Comment by mrzkai** [comment]
感谢，已根据回调的start_time、time_len和file_size结合自己的数据库实现了
