### ISSUE TITLE
[技术咨询] GB281级联，上级平台收流为单端口，调用startSendRtp函数端口相同时会报错

### ISSUE THREAD

**Issue by yangshun1996** [ZLMediaKit/ZLMediaKit#2047]
上级平台每次收流的地址都为固定的端口
目前级联调用的startSendRtp函数
上级每次用相同端口收流第二次的时候，zlm就会返回address not available

**Comment by yangshun1996** [comment]
{
    "app":"rtp",
    "src_port":30000,
    "vhost":"__defaultVhost__",
    "use_ps":"1",
    "is_udp":"1",
    "pt":96,
    "stream":"1001041",
    "ssrc":"0200001041",
    "dst_port":30002,
    "dst_url":"192.168.1.20",
    "only_audio":"0"
}

**Comment by yangshun1996** [comment]
{
    "app":"rtp",
    "src_port":30000,
    "vhost":"__defaultVhost__",
    "use_ps":"1",
    "is_udp":"1",
    "pt":96,
    "stream":"1001041",
    "ssrc":"0200001041",
    "dst_port":40000,
    "dst_url":"192.168.1.20",
    "only_audio":"0"
}

**Comment by xia-chu** [comment]
你为什么两次请求都用同一个src_port端口？

**Comment by xia-chu** [comment]
你觉得一个端口能connect两次吗
