### ISSUE TITLE
[技术咨询] addStreamPusherProxy 无法推 rtmps 流

### ISSUE THREAD

**Issue by hskent** [ZLMediaKit/ZLMediaKit#2049]
addStreamProxy将流拉到本地后使用addStreamPusherProxy 转推
rtmp -> 正常推流
rtmps -> 得到提示
{
    "code" : -1,
    "msg" : "connection timed out"
}

用的是docker方式

**Comment by xia-chu** [comment]
编译zlm时是否开启openssl相关功能了？

**Comment by hskent** [comment]
尝试在centos7环境编译,webrtc能播放,openssl应该是没问题的
但是转推 rtmps 还是持续得到 connection timed out 提示

**Comment by xia-chu** [comment]
> 续得到 connection timed out 提示

你可以尝试推给zlm本身试试

**Comment by hskent** [comment]
推给zlm本身确实可以,但须要指定端口
加上端口后 推到外部提示变成"end of file"

**Comment by xia-chu** [comment]
> 推给zlm本身确实可以,但须要指定端口 加上端口后 推到外部提示变成"end of file"

那说明对方掐断链接了

**Comment by hskent** [comment]
但改用ffmpeg从zlm拉流转推出去是正常的,不太明白其中差异

**Comment by xia-chu** [comment]
所以它不兼容zlm的推流客户端？什么协议？

**Comment by hskent** [comment]
其实就是telegram的直播功能,rtmps的
想搞个长时间的音乐轮播

**Comment by hskent** [comment]
测试了其他使用rtmps的平台比如FB,转推正常
错误似乎只发生在推到飞机群

**Comment by xia-chu** [comment]
先关闭了 兼容性问题 是个持续性工作 需要不断测试 而我很多情况下没测试环境 需要大家一起提交pr解决
