### ISSUE TITLE
SSL_box会不会产生内存泄漏

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#2050]
我现在采用RTSPS对等验证的传输流媒体数据。

但是我发现SSL_box并没有SSL_free和SSL_CTX_free，BIO_free等函数的调用，来释放SSL创建的相关资源，仅仅出现了一个CONF_modules_free。我担心会产生内存泄漏，在实际使用中造成隐患。

**Comment by xiongguangjie** [comment]
看 3rdpart/ZLToolKit/src/Util/SSLUtil.cpp 中看智能指针的自定义析构 来释放，bio 是通过了SSL_set_bio 应该是通过ssl的释放来释放的

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/198182015-10df6ce5-6f8a-48ee-9b2d-12abea50a20a.png)
是我vscode编辑器搜索的问题。这是个废问题。

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/198182256-4178582f-3db8-4658-b3f8-b72de32d267c.png)
![image](https://user-images.githubusercontent.com/19343842/198182302-f7c70816-ea80-45fa-8e33-abcb010016d3.png)
![image](https://user-images.githubusercontent.com/19343842/198182255-8d4b73eb-1b13-4dca-9cf5-74f0aaecd59e.png)

**Comment by xia-chu** [comment]
@fengmao31 你这什么工具 很厉害啊

**Comment by fengmao31** [comment]
@xia-chu 

## 安装软件
```
sudo apt install lttng-tools
sudo apt install lttng-modules-dkms
```
## 安装图形可视化分析工具
https://github.com/tahini/lttng-utils
## 软件使用
```
lttng-record-trace -p libc 程序名称
sudo usermod -a -G tracing <user>
newgrp tracing
```

**Comment by fengmao31** [comment]
@xia-chu 不好意思，才看到。github邮件通知有时候不太灵的感觉。
