### ISSUE TITLE
[技术咨询] c SDK在手机端支持wss+fmp4解码播放吗

### ISSUE THREAD

**Issue by bravepiper** [ZLMediaKit/ZLMediaKit#2051]
**咨询的功能模块**
wss+fmp4模块

**咨询的具体内容和问题**
你好：
现在开发一个手机app，包括iOS和Android，服务器端推流的方式是wss+fmp4，我想在app使用ZLMediaKit来实现wss+fmp4的解码播放，请问ZLMediaKit可以实现这个功能吗？

谢谢

**Comment by xia-chu** [comment]
不行 因为zlm只支持wss-fmp4服务器 不支持播放器，要支持需要二次开发，建议你采用https-fmp4协议，这样用ijkplayer就可以播放了

**Comment by bravepiper** [comment]
了解了，谢谢回复
