### ISSUE TITLE
mk_api静态库链接缺少函数实现，链接失败

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#2052]
vs2019环境下，源码只打开ENABLE_API_STATIC_LIB宏，编译mk_api静态库成功。然后编译api的测试程序，报错。结果如下：

![img_v2_eaba693a-823e-4635-b1ed-8516573b821g](https://user-images.githubusercontent.com/19343842/198007746-73f64c6d-8b3d-41a9-88f7-b25e0e7c2b64.jpg)

**Comment by xia-chu** [comment]
`mk_handle_*`这个是什么api？zlm中原本没这个的。打开ENABLE_API_STATIC_LIB宏编译确实可能有问题，但是我没测试环境。建议你还是用动态库，因为静态库一般不能把多个库合并到一起 容易出链接符号问题

**Comment by quxiaohuixiangxuexue** [comment]
作者您好，mk_handle_*是我基于mk_pusher和mk_player二次封装的api接口，以支持外部输入实时流作为媒体源并推流的业务逻辑。Linux环境下，我原本设想的是只需要链接一个mk_api静态库。现在看来似乎必须同时链接zlmediakit静态库和zltoolkit静态库吗？

**Comment by Dw9** [comment]
@fengmao31 api/CmakeLists 修改一下试试 ，貌似是导出的宏GENERATE_EXPORT没找到
![image](https://user-images.githubusercontent.com/36155473/198191666-39a7388f-7726-481c-9820-1baadd23d0fb.png)

**Comment by quxiaohuixiangxuexue** [comment]
@Dw9 修改之后，已经能正常链接mk_api静态库了。感谢！

**Comment by fengmao31** [comment]
感谢！
