### ISSUE TITLE
[技术咨询] send rtp connection lost: end of file

### ISSUE THREAD

**Issue by Wszl** [ZLMediaKit/ZLMediaKit#2054]
`2022-10-27 15:40:31.329 W MediaServer[1-event poller 1] RtpSender.cpp:309 onErr | send rtp connection lost: end of file`
调用startSendRtp 向对方服务器推流，对方也不怎么配合调试。想问问这种一般是什么问题
我这边是webrtc推到zlk,然后应用服务器调用startSendRtp 向对面服务器推流
startSendRtp 的参数是https://HOST:28443/index/api/startSendRtp?app=audio-talk&dst_port=6479&dst_url=xxx.xx.xx.xxx&is_udp=0&only_audio=1&ssrc=588741175&stream=STREAMID&use_ps=1&vhost=__defaultVhost__  敏感参数掩饰了一下

**Comment by xiongguangjie** [comment]
对方断开了

**Comment by Wszl** [comment]
> 对方断开了

对方回复说是我们主动断开的。。

**Comment by xia-chu** [comment]
> > 对方断开了
> 
> 对方回复说是我们主动断开的。。

很简单 抓包下看看谁先发的tcp fin包

**Comment by Wszl** [comment]
> 



> > > 对方断开了
> > 
> > 
> > 对方回复说是我们主动断开的。。
> 
> 很简单 抓包下看看谁先发的tcp fin包

谢谢指点，我去抓一下
