### ISSUE TITLE
SSLUtil读取不到证书或者证书非法格式会造成崩溃

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#2055]
![image](https://user-images.githubusercontent.com/19343842/198232053-40a64bdc-b950-45ce-a14d-fdcbb0c34157.png)
SSLUtil读取不到证书或者证书非法格式会造成崩溃。因为提前释放了SSL_CTX导致SSL_Read出现异常。如果不释放SSL_CTX，则可以使用智能指针完成垃圾。崩溃后无法断线重连和回收资源，如果此处不free则可以在每次重连的时候完成垃圾回收。
![image](https://user-images.githubusercontent.com/19343842/198233148-f3889dc3-35fd-42ca-a69e-a1d190b657cd.png)
![image](https://user-images.githubusercontent.com/19343842/198239224-1cb5ac99-2884-4ebe-85dd-7dbb38e58ec4.png)

**Comment by xia-chu** [comment]
方便修正下提个pr吗

**Comment by fengmao31** [comment]
我又检查了一遍。发现服务器方没有事情。如果服务器读不到或者为空。会自动使用ctx_empty。然而我用于客户端模式没有使用ctx_empty的语句。

**Comment by fengmao31** [comment]
按个爪，供其他人参考。根证书钥加载失败后无泄漏。在加载根证书失败时候不free。失败5次断开测试如下：
![image](https://user-images.githubusercontent.com/19343842/198258851-db171307-a1c7-4ac4-98ac-c833ed427dd5.png)

![image](https://user-images.githubusercontent.com/19343842/198258082-7206b5b2-1afd-4177-ac2e-d69c5cfe7d6f.png)
这里free不free都没事。free了就用ctx_empty的ctx依然没有根证书。不free反正是函数无法读取的根证书也是没有根证书。

**Comment by fengmao31** [comment]
不不不。服务器会崩溃。那个是if(!server_mod)。前面没有读到vhost都去创建empty_ctx了。最后又变成了服务器主机。
![image](https://user-images.githubusercontent.com/19343842/198260669-163a10dc-d1e8-4499-9136-c7ba88f11985.png)

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/198261028-889515a9-7c37-4786-bf1f-48507dfee420.png)

**Comment by fengmao31** [comment]
我这周末提交个pr。麻烦的是is_default离的很遥远。我看看前面在哪里修改可以同时适配服务器和客户端。

**Comment by fengmao31** [comment]
修好了。可以适配客户端和服务器。

**Comment by fengmao31** [comment]
周末我检查一下。

**Comment by xia-chu** [comment]
感谢

**Comment by fengmao31** [comment]
![image](https://user-images.githubusercontent.com/19343842/198872173-d1104719-bea6-43c9-b856-7f7fc0ec7a29.png)

这里ssl建立失败。但是没有任何处理。导致后面ssl_read会崩溃。修改后这种错误也不会显示ssl_disable这地方的打印了。

修改后，会自动使用空的SSL_CTX建立SSL。持续TLS握手失败。不会崩溃。同时兼容关闭SSL_ENABLE_SNI的客户端。原版服务器在默认开启SSL_ENABLE_SNI加密链接的时候在这里每次会出现证书失败失败然后从可用的证书中找一个重新建立连接。这个我不懂SSL_ENABLE_SNI，所以我都是注释掉的。
// openssl版本是否支持sni
//#define SSL_ENABLE_SNI

这里只修复了[SSLUtil读取不到证书或者证书非法格式会造成崩溃。因为前面读取证书失败，free掉了ctx，后面建立ssl失败。最后ssl_read引发服务器和客户端崩溃。
下图为修改后的打印情况。
![image](https://user-images.githubusercontent.com/19343842/198871920-6f4bd18b-8d5f-4454-8af5-c802907a3500.png)

**Comment by fengmao31** [comment]
我发现x86版本的libssl-dev1.1.1f库openssl有个bug。加载根证书时候不写后缀名，不会显示读不到文件的报错。
```
  // 设置信任根证书
        if (SSL_CTX_load_verify_locations(ctx, "/home/fengmao31/ZLMediaKit_rtsps_peer/server_public", NULL)!= 1) {
            WarnL << "加载根证书失败:" << getLastError();
            // SSL_CTX_free(ctx);
            // return nullptr;
        }
```

**Comment by fengmao31** [comment]
x86版本的libssl-dev1.1.1f库openssl的bug2.
![image](https://user-images.githubusercontent.com/19343842/198873530-854e978b-22e8-446d-9ee8-c2b33add8d02.png)

![image](https://user-images.githubusercontent.com/19343842/198873492-4a485a5b-2a8f-49cd-9738-4458381c0ff0.png)

**Comment by xia-chu** [comment]
原来你在gitee上提的pr 我都没注意到 抱歉啊！

**Comment by xia-chu** [comment]
合并了 感谢！
