### ISSUE TITLE
[技术咨询] 您好，我想问下关于证书的问题

### ISSUE THREAD

**Issue by XiaoQiTong** [ZLMediaKit/ZLMediaKit#2056]
**咨询的功能模块**
作者您好，我想咨询下关于证书报错的问题：
- 我现在使用证书启动服务会报这个错误
- 
![image](https://user-images.githubusercontent.com/69035114/198532139-84b46429-da93-4d9a-9cbb-6614fd630177.png)
![image](https://user-images.githubusercontent.com/69035114/198532181-20bbb587-2115-456d-99cd-c7b4cab1dba2.png)

网页访问会报这个错
![image](https://user-images.githubusercontent.com/69035114/198534349-6df8f106-65bd-4f0a-86a1-98a5f0cd6f2a.png)

**咨询的具体内容和问题**
- 操作系统：redhat
- openssl版本：
![_2 LB48OI IOR_CXJVGTKQ8](https://user-images.githubusercontent.com/69035114/198533495-f0c1fec2-9196-477d-99a4-b779082c539b.jpg)

我做过的尝试：
1、使用zlm自带证书、自签名证书、其他项目证书均有此问题，于是排除了证书的问题
2、因为centos和redhat是一家，所以我尝试使用centos上运行没问题的包放过来跑还是不行

**Comment by XiaoQiTong** [comment]
> 请仔细认真阅读此维基： https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD

感谢您的回复，原来是访问sip信令报的错，zlm本身部署没问题

**Comment by AlphaWu** [comment]
你的ZML加载的证书是颁发给ttsl.jjsxczx.cn，你访问的使用的是这个域名么？你图片马赛克掉了，看不出来，如果不是这个域名，就会提示证书错误。

**Comment by xia-chu** [comment]
证书里面的域名和访问url的域名要一致

**Comment by XiaoQiTong** [comment]
> 你的ZML加载的证书是颁发给ttsl.jjsxczx.cn，你访问的使用的是这个域名么？你图片马赛克掉了，看不出来，如果不是这个域名，就会提示证书错误。

感谢感谢，是我这的问题，是zlm回调的url设置的https://ip的问题

**Comment by XiaoQiTong** [comment]
> 证书里面的域名和访问url的域名要一致

感谢感谢，是我这设置的hook url出现的问题

**Comment by kodyds** [comment]
请问你设置的hook url具体是出现了什么问题呢？
