### ISSUE TITLE
[技术咨询]win编译及生成正常，centos7.9 make执行到75%报错，请问是哪里问题呢

### ISSUE THREAD

**Issue by hxqz** [ZLMediaKit/ZLMediaKit#2062]
**咨询的功能模块**

gcc版本 4.8.5
make版本3.82
如下图，make执行到75%报错： /ZLMediaKit/webrtc/DtlsTransport.cpp:601:46: error: ‘DTLS_set_timer_cb’ was not declared in this scope
   DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
![微信截图_20221101122511](https://user-images.githubusercontent.com/63330489/199158428-7b6e0241-aef7-44b6-8c87-54ae75a2b5cc.png)

**咨询的具体内容和问题**

请问这个是代码本身的问题还是环境或者依赖问题呢，如何解决呢？

**Comment by xiongguangjie** [comment]
openssl 版本有问题或者与已有的存在冲突（有多个openssl 版本），看wiki
