### ISSUE TITLE
[BUG]: 海康IPC GB28181/H265 RTP收流播放，播放器闪屏

### ISSUE THREAD

**Issue by dongruxue** [ZLMediaKit/ZLMediaKit#2066]
环境：
     Docker，海康IPC，GB/T28181-2015,H265
问题：收流后转发后，VLC和jessibucabo播放闪屏，切为H264正常

**Comment by xia-chu** [comment]
可以把h265 rtp dump出来并提交上来

**Comment by dongruxue** [comment]
[请下载](http://iot.ghibms.com:9000/svr/file30034)
