### ISSUE TITLE
[技术咨询]使用addStreamProxy创建成功,但webrtc播放失败；麻烦作者以及各位大佬帮忙看一下。感谢！！！

### ISSUE THREAD

**Issue by deilsky** [ZLMediaKit/ZLMediaKit#2070]
**咨询的功能模块**
- webrtc页面播放失败。
- 
**咨询的具体内容和问题**
- addStreamProxy接口调用成功，对应路径下也生成了相关文件夹以及文件；
- 使用ip:port/webrtc页面播放时，debug模式下，控制台输出 当前状态==> failed
- 通过debug跟踪到index/api/webrtc?app=live&stream=stream&type=play 以及内容为 Response返回内容；
- {
	"code" : 0,
	"id" : "zlm_3",
	"sdp" : "v=0\r\no=- 8702418017759941545 2 IN IP4 10.10.18.102\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=video 8000 UDP/TLS/RTP/SAVPF 123 119\r\nc=IN IP4 10.10.18.102\r\na=rtcp:8000 IN IP4 10.10.18.102\r\na=ice-ufrag:zlm_3\r\na=ice-pwd:kfiLoOjtVQP7fHQa4x6fH9B6\r\na=ice-options:trickle\r\na=fingerprint:sha-256 75:CC:69:30:80:A8:98:FA:65:6F:7E:BC:91:89:C2:24:A3:53:9F:CF:72:93:F7:21:9D:3D:A1:71:B4:4A:38:01\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=rtcp-fb:123 transport-cc\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=123\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 cname:zlmediakit-rtp\r\na=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 mslabel:zlmediakit-mslabel\r\na=ssrc:1 label:zlmediakit-label\r\na=ssrc:3 cname:zlmediakit-rtp\r\na=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:3 mslabel:zlmediakit-mslabel\r\na=ssrc:3 label:zlmediakit-label\r\na=ssrc-group:FID 1 3\r\na=candidate:udpcandidate 1 udp 130 10.10.18.102 8000 typ host\r\na=candidate:udpcandidate 1 udp 120 10.10.18.39 8000 typ host\r\na=candidate:udpcandidate 1 udp 110 127.0.0.1 8000 typ host\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 10.10.18.102\r\na=rtcp:8000 IN IP4 10.10.18.102\r\na=ice-ufrag:zlm_3\r\na=ice-pwd:kfiLoOjtVQP7fHQa4x6fH9B6\r\na=ice-options:trickle\r\na=fingerprint:sha-256 75:CC:69:30:80:A8:98:FA:65:6F:7E:BC:91:89:C2:24:A3:53:9F:CF:72:93:F7:21:9D:3D:A1:71:B4:4A:38:01\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=inactive\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\na=candidate:udpcandidate 1 udp 130 10.10.18.102 8000 typ host\r\na=candidate:udpcandidate 1 udp 120 10.10.18.39 8000 typ host\r\na=candidate:udpcandidate 1 udp 110 127.0.0.1 8000 typ host\r\n",
	"type" : "answer"
}
- 以及为config.ini相关配置；
- externIP=10.10.18.102,10.10.18.39,127.0.0.1
- directProxy=0

**Comment by deilsky** [comment]
> 需要看zlm日志才能确定

2022-11-04 09:55:58.728 I MediaServer[19200-event poller 0] MediaSource.cpp:461 emitEvent | 媒体注册:hls://__defaultVhost__/live/stream
2022-11-04 09:56:13.062 T MediaServer[19200-event poller 1] HttpSession.cpp:27 HttpSession | 2-156(10.10.18.102:50045)
2022-11-04 09:56:13.793 T MediaServer[19200-event poller 1] HttpSession.cpp:27 HttpSession | 3-157(10.10.18.102:50046)
2022-11-04 09:56:27.650 T MediaServer[19200-event poller 0] HttpSession.cpp:119 onError | 1-153(10.10.18.102:50024) session timeout
2022-11-04 09:56:27.650 T MediaServer[19200-event poller 0] HttpSession.cpp:33 ~HttpSession | 1-153(10.10.18.102:50024)
2022-11-04 09:56:28.130 I MediaServer[19200-event poller 1] WebRtcTransport.cpp:404 WebRtcTransportImp | zlm_1
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:456 CreateSslCtx | setting SRTP cryptoSuites for DTLS: SRTP_AEAD_AES_256_GCM:SRTP_AEAD_AES_128_GCM:SRTP_AES128_CM_SHA1_80:SRTP_AES128_CM_SHA1_32
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:538 GenerateFingerprints | sha-1   fingerprint: A8:F0:AC:1D:EF:A0:87:16:96:C1:8E:E7:72:32:E0:1D:B6:C0:D2:8B
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:538 GenerateFingerprints | sha-224 fingerprint: 91:23:DC:71:FF:D5:D7:01:9F:7D:3B:9B:0F:1B:3F:E4:41:0D:18:79:9C:E6:F6:5E:37:E0:F5:A0
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:538 GenerateFingerprints | sha-256 fingerprint: 08:83:7B:AA:DD:38:6B:6F:BE:0A:3F:E9:AA:FD:81:0D:1D:19:31:D5:E8:BE:11:23:26:04:FD:75:3F:56:E5:4B
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:538 GenerateFingerprints | sha-384 fingerprint: 21:CC:24:E4:E5:C0:05:B0:18:7B:CF:A5:F0:2C:C9:23:54:1C:E4:B4:EB:FA:C3:76:EC:FD:B3:3C:76:FC:D6:77:E5:57:00:2B:9E:F0:83:26:AF:30:DF:EA:86:01:5F:2F
2022-11-04 09:56:28.130 D MediaServer[19200-event poller 1] DtlsTransport.cpp:538 GenerateFingerprints | sha-512 fingerprint: DB:EE:60:30:20:AC:67:43:4D:BF:3E:E1:49:CF:5B:61:D3:42:7F:80:9D:DE:6B:2E:78:A4:1F:3A:1C:7F:CC:17:B6:3A:17:24:24:4D:62:C5:3B:4A:D6:65:69:0B:D8:33:07:07:D0:C7:A8:6A:0A:98:77:6C:6A:55:2C:8F:6D:CA
2022-11-04 09:56:28.133 D MediaServer[19200-event poller 1] WebApi.cpp:249 http api debug |
# request:
POST /index/api/webrtc?app=live&stream=stream&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Content-Length : 6386
Content-Type : text/plain;charset=UTF-8
Host : 10.10.17.150:8888
Origin : http://10.10.17.150:8888
Referer : http://10.10.17.150:8888/webrtc/
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
# content:
v=0
o=- 3153093817737446767 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 35 36 37 38 102 122 127 121 125 107 108 109 124 120 39 40 41 42 43 44 45 46 47 48 123 119 114 115 116 49
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:sfQd
a=ice-pwd:A1SFdBymH//3S9q3Q/v5OvxK
a=ice-options:trickle
a=fingerprint:sha-256 07:A8:31:48:91:61:78:A6:9B:70:F7:50:F6:C6:3C:F1:21:14:15:24:15:C7:53:35:77:C2:4F:3F:9E:08:FC:33
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:35 VP9/90000
a=rtcp-fb:35 goog-remb
a=rtcp-fb:35 transport-cc
a=rtcp-fb:35 ccm fir
a=rtcp-fb:35 nack
a=rtcp-fb:35 nack pli
a=fmtp:35 profile-id=1
a=rtpmap:36 rtx/90000
a=fmtp:36 apt=35
a=rtpmap:37 VP9/90000
a=rtcp-fb:37 goog-remb
a=rtcp-fb:37 transport-cc
a=rtcp-fb:37 ccm fir
a=rtcp-fb:37 nack
a=rtcp-fb:37 nack pli
a=fmtp:37 profile-id=3
a=rtpmap:38 rtx/90000
a=fmtp:38 apt=37
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=4d001f
a=rtpmap:40 rtx/90000
a=fmtp:40 apt=39
a=rtpmap:41 H264/90000
a=rtcp-fb:41 goog-remb
a=rtcp-fb:41 transport-cc
a=rtcp-fb:41 ccm fir
a=rtcp-fb:41 nack
a=rtcp-fb:41 nack pli
a=fmtp:41 level-asymmetry-allowed=1;packetizatio
# response:
{
        "code" : 0,
        "id" : "zlm_1",
        "sdp" : "v=0\r\no=- 3153093817737446767 2 IN IP4 10.10.18.102\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=video 8000 UDP/TLS/RTP/SAVPF 123 119\r\nc=IN IP4 10.10.18.102\r\na=rtcp:8000 IN IP4 10.10.18.102\r\na=ice-ufrag:zlm_1\r\na=ice-pwd:CQUh4WtENmtHNtIevHDwzoiV\r\na=ice-options:trickle\r\na=fingerprint:sha-256 08:83:7B:AA:DD:38:6B:6F:BE:0A:3F:E9:AA:FD:81:0D:1D:19:31:D5:E8:BE:11:23:26:04:FD:75:3F:56:E5:4B\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 urn:3gpp:video-orientation\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:123 H264/90000\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=rtcp-fb:123 transport-cc\r\na=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f\r\na=rtpmap:119 rtx/90000\r\na=fmtp:119 apt=123\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 cname:zlmediakit-rtp\r\na=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 mslabel:zlmediakit-mslabel\r\na=ssrc:1 label:zlmediakit-label\r\na=ssrc:3 cname:zlmediakit-rtp\r\na=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:3 mslabel:zlmediakit-mslabel\r\na=ssrc:3 label:zlmediakit-label\r\na=ssrc-group:FID 1 3\r\na=candidate:udpcandidate 1 udp 130 10.10.18.102 8000 typ host\r\na=candidate:udpcandidate 1 udp 120 10.10.18.39 8000 typ host\r\na=candidate:udpcandidate 1 udp 110 127.0.0.1 8000 typ host\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 10.10.18.102\r\na=rtcp:8000 IN IP4 10.10.18.102\r\na=ice-ufrag:zlm_1\r\na=ice-pwd:CQUh4WtENmtHNtIevHDwzoiV\r\na=ice-options:trickle\r\na=fingerprint:sha-256 08:83:7B:AA:DD:38:6B:6F:BE:0A:3F:E9:AA:FD:81:0D:1D:19:31:D5:E8:BE:11:23:26:04:FD:75:3F:56:E5:4B\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=inactive\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\na=candidate:udpcandidate 1 udp 130 10.10.18.102 8000 typ host\r\na=candidate:udpcandidate 1 udp 120 10.10.18.39 8000 typ host\r\na=candidate:udpcandidate 1 udp 110 127.0.0.1 8000 typ host\r\n",
        "type" : "answer"
}
麻烦您帮忙看一下。感谢

2022-11-04 09:56:43.133 W MediaServer[19200-event poller 1] WebRtcTransport.cpp:1027 onShutdown | 接受rtp/rtcp/datachannel超时
2022-11-04 09:56:43.133 I MediaServer[19200-event poller 1] WebRtcTransport.cpp:408 ~WebRtcTransportImp | zlm_1
2022-11-04 09:56:45.649 T MediaServer[19200-event poller 1] HttpSession.cpp:119 onError | 3-157(10.10.18.102:50046) session timeout
2022-11-04 09:56:45.649 T MediaServer[19200-event poller 1] HttpSession.cpp:33 ~HttpSession | 3-157(10.10.18.102:50046)
2022-11-04 09:56:59.652 T MediaServer[19200-event poller 1] HttpSession.cpp:119 onError | 2-156(10.10.18.102:50045) session timeout
2022-11-04 09:56:59.652 T MediaServer[19200-event poller 1] HttpSession.cpp:33 ~HttpSession | 2-156(10.10.18.102:50045)

**Comment by xia-chu** [comment]
你没做udp端口映射吧？@deilsky

**Comment by deilsky** [comment]
> 你没做udp端口映射吧？@deilsky

**Comment by monktan89** [comment]
10.10.18.102 这个看着像内网ip 你应该使用最外层服务IP 然后从外到内映射8000

**Comment by deilsky** [comment]
> 10.10.18.102 这个看着像内网ip 你应该使用最外层服务IP 然后从外到内映射8000
好的，感谢！
