### ISSUE TITLE
RTSP流经过流媒体服务的转换，得到http格式的流，转换前后视频的时间不一致。

### ISSUE THREAD

**Issue by penghui-luna** [ZLMediaKit/ZLMediaKit#2076]
### 现象描述

我这边将RTSP流，推送到流媒体服务，转换成http流格式，发现，转换前后，播放的时间不一致。
这个是我本地传的RTSP流地址：
rtsp://ut:1q2w3E4R5T@192.168.53.56:554/Streaming/tracks/101?starttime=20221107t040001z&endtime=20221107t155959z

Rtsp流播放的时间画面：
![RTSP流播放时间](https://user-images.githubusercontent.com/40514537/200256743-d18042ce-bb7e-4e5c-b836-54c10a5c78ff.png)

### 相关日志或截图

![推流时间](https://user-images.githubusercontent.com/40514537/200256059-da0b21be-f4ba-4419-8eeb-575eb7567e9d.png)

转换成http流之后播放的画面时间：
![转换之后的流播放时间](https://user-images.githubusercontent.com/40514537/200256093-6aeea7bd-6a4f-41e9-b9ba-646dbdecd855.png)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by penghui-luna** [comment]
请各位大神帮忙解惑

**Comment by xiongguangjie** [comment]
这个要抓包对比分析

**Comment by xia-chu** [comment]
是的 请分别抓zlm请求rtsp和vlc请求rtsp的包看下

**Comment by mtdxc** [comment]
addStreamProxy中的url rtsp://ut:1q2w3E4R5T@192.168.53.56:554/Streaming/tracks/101?starttime=20221107t040001z&endtime=20221107t155959z，中间的?号是不是也得转义下，
将zlm实际请求rtsp的url地址打出来，可能就能得到答案。

**Comment by xuandu** [comment]
hello。后来你的问题怎么处理的。我也遇到了同样的问题，拉的时间不对；

**Comment by xia-chu** [comment]
可能跟content-base有关

**Comment by xuandu** [comment]
> 可能跟content-base有关

是的，海康回复的content base确实是跟其他两家不一样，还有play，还要用range；另一个issue里，大熊猫大佬给看了；感谢夏大回复
