### ISSUE TITLE
[技术咨询]rtsp推流，vlc拉流。vlc拉流会有失败情况

### ISSUE THREAD

**Issue by skyjally** [ZLMediaKit/ZLMediaKit#2077]
**咨询的功能模块**
- rtsp推流

**咨询的具体内容和问题**
- 使用rtsp推流，vlc拉流。vlc拉流时会有失败情况。失败情况的抓包rtsp请求不完整，咨询下大佬这中情况是什么原因造成的。
- vlc拉流失败时日志&抓包：
[VLC拉流失败ZLM日志.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/9966531/VLC.ZLM.txt)
![VLC拉流失败抓包](https://user-images.githubusercontent.com/9696323/200715687-73c43509-8d30-4be5-b407-5e9f5ec3f27b.png)
- vlc拉流成功时日志 & 抓包：
[VLC拉流成功ZLM日志.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/9966540/VLC.ZLM.txt)
![VLC拉流成功抓包](https://user-images.githubusercontent.com/9696323/200715757-785e37bd-9f6d-4461-bfce-929aefb91513.png)
- ZLM版本：
![ZLM版本](https://user-images.githubusercontent.com/9696323/200715786-d9863a34-caad-4cdc-a81f-b6b14ef68233.png)

**Comment by xia-chu** [comment]
失败的情况下 SETUP没带trackID, zlm不知道vlc要设置音频还是视频

**Comment by skyjally** [comment]
> 失败的情况下 SETUP没带trackID, zlm不知道vlc要设置音频还是视频

感谢大佬解答，VLC工具的问题，换了ffplay是OK的
