### ISSUE TITLE
[技术咨询]MP4录制功能可否录制触发前几秒的内容

### ISSUE THREAD

**Issue by zhink** [ZLMediaKit/ZLMediaKit#2079]
**咨询的功能模块**
- MP4录制功能

**咨询的具体内容和问题**
- 在智能视频项目中录制事件前后几秒的视频是一个强需求；ZLMediaKit是否支持；若不支持，在定制开发此功能时需要从哪方面下手？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
不支持 需要你把前后几个gop放在内存中 然后录制。
怎么缓存gop的 可以查看RingBuffer相关代码
