### ISSUE TITLE
How does webrtc to flv conversion works

### ISSUE THREAD

**Issue by tangenttechno** [ZLMediaKit/ZLMediaKit#2080]
In SRS, webrtc is converted to RTMP before converting to FLV/HLS/DASH etc. How does the same works in ZLMediakit?

**Comment by xia-chu** [comment]
In `ZLMediakit`, the media sources of rtsp and webrtc are the same，webrtc is a way of transport of `RtspMediaSource`.

You can push live stream to `ZLMediaKit` by `rtp/rtsp/rtmp/webrtc`, and ZLMediaKit will automatic transfer to other protocols, such as `rtsp/rtmp/flv/fmp4/hls/ts/webrtc/srt...`, you can control what to transfer by [on_push hook](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-HOOK-API#7on_publish).

Also,  you can let `ZLMediaKit` pull and proxy a livestream by useing `[addStreamProxy http api](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy)`, and there are many params to control what protocols to transfer.

**Comment by tangenttechno** [comment]
@xia-chu so in ZLMediakit, webRTC streams are directly transferred to other protocols(for example HLS) without any intermediate conversion(RTMP), right?  Thank you for the reply.

**Comment by tangenttechno** [comment]
@xia-chu Thank you
