### ISSUE TITLE
如何关闭mp4录制

### ISSUE THREAD

**Issue by liangzyayw** [ZLMediaKit/ZLMediaKit#2083]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个问题不用问 wiki都有写



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CentOS_k8s ***@***.***&gt;
发送时间: 2022年11月11日 09:28
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] 如何关闭mp4录制 (Issue #2083)

**Comment by liangzyayw** [comment]
> 这个自己不用问 wiki 有写问题的 iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人：CentOS_k8s ***@*** .***>发送时间022年11月11日09:28：/Z***：ZL***2***MediaKitKit ***>抄送：已订阅***@***.* **>主题： Re: [ZLMediaKit/ZLMediaKit] 如何关闭mp4记录（Issue #2083）

你好 在哪一个模块

**Comment by xia-chu** [comment]
wiki需要你全部看完

**Comment by liangzyayw** [comment]
您说的是通过接口关闭录制吗，我的意思是：我用摄像头上了一个国标设备，每次点开都会自动录像，怎么关闭录像



***@***.***
 
发件人： 夏楚
发送时间： 2022-11-11 10:18
收件人： ZLMediaKit/ZLMediaKit
抄送： CentOS_k8s; Author
主题： Re: [ZLMediaKit/ZLMediaKit] 如何关闭mp4录制 (Issue #2083)
wiki需要你全部看完
