### ISSUE TITLE
[技术咨询]RTP推流示例

### ISSUE THREAD

**Issue by wuxianshen** [ZLMediaKit/ZLMediaKit#2086]
**咨询的功能模块**
- RTP推流

**咨询的具体内容和问题**
- 作者您好，新手请问ZLMediaKit有没有获取RTSP流，而后进行RTP推流的例子呢？工程中没有找到mk_media_start_send_rtp接口的使用例子，两个pusher的example里也没有找到直接RTP推流的方法，谢谢作者！

**Comment by mingyuejingque** [comment]
请参考：
https://github.com/mingyuejingque/zlm_test

**Comment by wuxianshen** [comment]
谢谢回复！

**Comment by Lebron8997** [comment]
> 请参考： https://github.com/mingyuejingque/zlm_test
> 
> #2058

我这边在Ubuntu 18.04下编译，Makefile需要增加依赖库如下，请您考虑
`g++ -o test *.cpp \
                -L/home/pi/packages/ZLMediaKit/release/linux/Debug \
                -L/home/pi/inst/ffmpeg-v4.4/lib \
                -I/home/pi/packages/ZLMediaKit/api/include \
                -I/home/pi/inst/ffmpeg-v4.4/include \
                -lpthread \
                -lmk_api -lzlmediakit -lzltoolkit -lflv -ljsoncpp -lsrt -lmpeg -lmov\
                -lavformat -lswscale -lavcodec -lavdevice  -lswresample -lavutil -lavfilter \
                -lz -lX11 -lxcb -lcrypto -lssl\
                -lxcb -lxcb-shm -lxcb-shape -lxcb-xfixes -lz \
                -lXau -lXdmcp -ldl -lrt \
                -lm \
`

**Comment by mingyuejingque** [comment]
好的，我记录一下。多谢指导。
