### ISSUE TITLE
[技术咨询]寻求一款真正能用的跟ZLMediaKit相关的WebUI程序

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2088]
[**咨询的功能模块**]
- 跟ZLMediaKit相关的WebUI程序

**咨询的具体内容和问题**
- 寻求一款跟ZLMediaKit相关的WebUI程序，在linux上真正能跑出视频来的。本人是搞C++服务器的，奈何对前端开发不熟，根据wiki在Linux ubuntu上部署了ZLMediaKit，根据wiki也尝试过AKStream+AKStreamNVR，AKStreamWebUI等UI程序，却都一一失败了，要么是页面配置好后点播放，提示请求失败返回400，要么就是播放了几秒钟就卡了(用ffmpeg手动推RTSP流是OK的)，要么就是AKStreamWebUI登录不上，提示代理不对什么的。本想好好研究下ZLMediaKit，却被WebUI整得焦头烂额，就是刷不出视频流。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by longkin** [comment]
目前已经实现了debian11和centos7运行，服务端.net core，前端vue、uni-app，支持GB28181和RTMP，可以加微信bluezsoftcom聊

**Comment by xia-chu** [comment]
@zzgghhzzgghh 项目主页有介绍第三方合作项目 目前wvp做的最完善 它也支持管理添加rtsp/rtmp流，不过它主要还是GB28181管理平台。

zlmediakit是由非营利性开源爱好者发起和维护的，任何相关功能，基本都在非盈利情况下开发完成，我们目前主要贡献者在前端开发领域经验也并不充分，所以是否有什么好用的前端项目，完全不是我们能决定的，我们这些开发者也是由共同爱好而聚集在一起的，并没有什么强制约束，贡献多寡也完全看个人兴趣。

开源生态能否繁荣，靠的是广大贡献者的共建共享，如果你们能开发出一个好用的合作项目，一起来完事生态，那么后来者就不会有像你当前一样的苦恼了。
