### ISSUE TITLE
SSLbox为什么解密是不定长的解密？然而定长发送？这个是怎么做到的？

### ISSUE THREAD

**Issue by fengmao31** [ZLMediaKit/ZLMediaKit#2089]
我统计加解密次数，发现不一致。原来接收到不定长的buff包进行解密。使用定长的buff数组加密发送。
![image](https://user-images.githubusercontent.com/19343842/202100741-1f388c25-2d6b-4848-bd63-721d48555e4b.png)
图中1000次统计为旧的统计，实际上是每次加解密的打印。

这里不定长的buff包解密是I帧P帧划分的吗？还是固定时间接收到的buff包立刻进行解密？

**Comment by xia-chu** [comment]
定长发送应该是定长加密导致 很多加密算法是定长的

**Comment by fengmao31** [comment]
应该是TCP粘包造成的收端收到的包数量不可能确定。
