### ISSUE TITLE
[技术咨询] 不同播放器的流延时测试，使用ffplay nobuffer 播放也有3s延时

### ISSUE THREAD

**Issue by Wszl** [ZLMediaKit/ZLMediaKit#2093]
**咨询的功能模块**
zlm延时部分

**咨询的具体内容和问题**
![image](https://user-images.githubusercontent.com/19342733/202618757-a46bc512-1fc6-48b2-97bc-4e6fb4ff7824.png)

我这边是通过addStreamProxy 拉一个rtmp流，视频流是h264,音频是pcma，经过zlm后视频不变，音频编码变成了mp4a，这刚好也符合我们的需求，需要在浏览器播放。
现在的问题是延时，在仔细看完wiki部分后，我知道播放器是导致延时的最常见原因。但是我这里发现排除播放器的因素也有3s延时
最上面是ffplay播放器 播放命令是ffplay -i https://xxxxxx:28443/streamProxy/61010102031320000023.live.flv -fflags nobuffer -x 600 -y 400  播放的是zlm代理的流
中间的是vlc播放zlm代理的流
最下面的是rtmp源流。
发现源流和ffplay播放的流之间有3s延时，这个时间大概是哪里产生的呢？

**Comment by xia-chu** [comment]
请使用webrtc测试延时

**Comment by xia-chu** [comment]
或者用zlm自带的test_player测试延时

**Comment by bzyiostream** [comment]
@xia-chu 同感，zlm的http-flv延迟是有点大，没有设置gop的地方

**Comment by Wszl** [comment]
用webrtc测了，比vlc播放源rtmp还快。看来是播放器问题

**Comment by xia-chu** [comment]
> @xia-chu 同感，zlm的http-flv延迟是有点大，没有设置gop的地方

gop是编码端控制 跟zlm无关

**Comment by bzyiostream** [comment]
@xia-chu  那http-flv延迟出在哪里，一般不是服务器会缓存一个gop达到画面秒开的效果

**Comment by xia-chu** [comment]
在播放器端

**Comment by bzyiostream** [comment]
@xia-chu 这个我就有点不认同了，同样的推流端，同样的播放端，只是换了服务器部分，就局域网rtmp推，http-flv拉，一般都是500ms以内，zlm超过1秒多

**Comment by Wszl** [comment]
> 

夏楚说的是对的，基本都是播放器的问题，我们用zlm提供的webrtc播放器解决了。如果你们是cs架构，就要考虑下换其他播放器了

**Comment by Wszl** [comment]
> @Wszl 你好，打扰了，我也是一样的问题，请问后面有优化处理吗

夏楚说的是对的，我们是bs架构，最后换zlm提供的webrtc 播放器解决了。如果你们是cs架构就要考虑换其他播放器了
