### ISSUE TITLE
[功能请求]请问大佬：GB28181只支持设备推PCMA上来吗？设备侧选择其他音频格式例如AAC不能识别，变成杂音，PCMA推流上来是正常的

### ISSUE THREAD

**Issue by ouxiand** [ZLMediaKit/ZLMediaKit#2094]
**描述该功能的用处，可以提供相关资料描述该功能**
请问下GB28181只支持设备推PCMA上来吗？设备侧选择其他音频格式例如AAC不能识别，变成杂音，PCMA推流上来是正常的

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
GB28181与RTP推流
支持UDP/TCP RTP(PS/TS/ES)推流服务器，可以转换成RTSP/RTMP/HLS等协议
支持RTSP/RTMP/HLS等协议转rtp推流客户端，支持TCP/UDP模式，提供相应restful api，支持主动被动方式。
支持H264/H265/**AAC/G711/OPUS编码**
支持海康ehome推流
支持GB28181主动拉流模式

主页介绍有支持aac和opus，请问下是否配置或命令问题，感谢？

**Comment by xia-chu** [comment]
也支持AAC 配置好你的设备后请重启设备

**Comment by ouxiand** [comment]
大佬，测试了还是不行，是否GB28181配置有关？我看到track一直是PCMA,实际上设备选择了AAC，getMediaList结果如下：
 "tracks" :
                        [
                                {
                                        "channels" : 1,
                                        "codec_id" : 3,
                                        "codec_id_name" : "PCMA",
                                        "codec_type" : 1,
                                        "ready" : true,
                                        "sample_bit" : 16,
                                        "sample_rate" : 8000
                                },
                                {
                                        "codec_id" : 0,
                                        "codec_id_name" : "H264",
                                        "codec_type" : 0,
                                        "fps" : 0.0,
                                        "height" : 720,
                                        "ready" : true,
                                        "width" : 1280
                                }
                        ],


----------附上配置信息--------------------------------
ZLM的config.ini里面


[rtp]
#音频mtu大小，该参数限制rtp最大字节数，推荐不要超过1400
#加大该值会明显增加直播延时
audioMtuSize=600
#视频mtu大小，该参数限制rtp最大字节数，推荐不要超过1400
videoMtuSize=1400
#rtp包最大长度限制，单位KB,主要用于识别TCP上下文破坏时，获取到错误的rtp
rtpMaxSize=10
# rtp 打包时，低延迟开关，默认关闭（为0），h264存在一帧多个slice（NAL）的情况，在这种情况下，如果开启可能会导致画面花屏
lowLatency=0

[rtp_proxy]
#导出调试数据(包括rtp/ps/h264)至该目录,置空则关闭数据导出
dumpDir=
#udp和tcp代理服务器，支持rtp(必须是ts或ps类型)代理
port=2403
#rtp超时时间，单位秒
timeoutSec=15
#随机端口范围，最少确保36个端口
#该范围同时限制rtsp服务器udp端口范围
port_range=2404-2500

#rtp h264 负载的pt
h264_pt=98

#rtp h265 负载的pt
h265_pt=99

#rtp ps 负载的pt
ps_pt=96

#rtp ts 负载的pt
ts_pt=33

#rtp opus 负载的pt
opus_pt=100

#rtp g711u 负载的pt
g711u_pt=0

#rtp g711a 负载的pt
g711a_pt=8

**Comment by ouxiand** [comment]
zlm log如下：
[36m2022-11-28 10:48:06.781 I gb28181[91442-event poller 1] RtpProcess.cpp:256 operator() | 061465FC(172.26.228.48:9704) 允许RTP推流[0m
[36m2022-11-28 10:48:06.880 I gb28181[91442-event poller 1] GB28181Process.cpp:168 onRtpDecode | 061465FC judged to be PS[0m
[36m2022-11-28 10:48:06.881 I gb28181[91442-event poller 1] Decoder.cpp:240 onTrack | got track: H264[0m
[36m2022-11-28 10:48:06.881 I gb28181[91442-event poller 1] Decoder.cpp:240 onTrack | got track: PCMA[0m
[36m2022-11-28 10:48:06.881 I gb28181[91442-event poller 1] Decoder.cpp:159 onStream | add track finished[0m
[32m2022-11-28 10:48:06.881 D gb28181[91442-event poller 1] MediaSink.cpp:136 emitAllTrackReady | all track ready use 1ms[0m
[36m2022-11-28 10:48:06.882 I gb28181[91442-event poller 1] MultiMediaSourceMuxer.cpp:368 onAllTrackReady | stream: rtp://__defaultVhost__/rtp/061465FC , codec info: PCMA[8000/1/16] H264[1280/720/0] [0m
[32m2022-11-28 10:48:06.882 D gb28181[91442-event poller 0] MediaSource.cpp:412 operator() | 收到媒体注册事件,回复播放器:rtsp://__defaultVhost__/rtp/061465FC[0m
[36m2022-11-28 10:48:06.883 I gb28181[91442-event poller 1] MediaSource.cpp:461 emitEvent | 媒体注册:rtsp://__defaultVhost__/rtp/061465FC[0m

**Comment by xia-chu** [comment]
如果zlm说是pcma 那就是pcma

**Comment by ouxiand** [comment]
实际设备网页设置的是AAC

**Comment by ouxiand** [comment]
![image](https://user-images.githubusercontent.com/95113887/204240992-8f0e3934-7b11-4d00-ba50-e0bf8e8802fc.png)

**Comment by xia-chu** [comment]
你这网页端对国标无效
