### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by rsxieliang** [ZLMediaKit/ZLMediaKit#2097]
**咨询的功能模块**
- 代理拉流接口 addStreamProxy

**咨询的具体内容和问题**
- 新增的代理拉流第一次总是失败 失败后 马上第二次拉流有可以了 等流关闭后 再次拉流又要第二次才会拉取成功，超时时间设置的20秒 554端口只开放了 tcp, 指定拉流也选择的是 tcp

>

**Comment by rsxieliang** [comment]
![微信图片_20221119212554](https://user-images.githubusercontent.com/33095958/202853036-6acbc421-92da-44bd-9955-5705f205c7bf.png)


![微信图片_20221119212616](https://user-images.githubusercontent.com/33095958/202853042-67ce2aab-da16-4a7f-9e67-744f3423b5c1.png)


还请大佬指点指点 是哪里出了问题

**Comment by xia-chu** [comment]
在addStreamProxy未返回前 请勿重复请求 因为在`播放结果`返回前，第二次addStreamProxy都会返回成功

**Comment by xia-chu** [comment]
那你换其他rtsp url试试 看看这是不是孤例子。
另外 第一次失败时 请抓包分析原因
