### ISSUE TITLE
[功能请求]按小时生成m3u8回放文件

### ISSUE THREAD

**Issue by AlphaWu** [ZLMediaKit/ZLMediaKit#2099]
**描述你期望实现该功能的方式和最终效果**
在保存hls录像的情况下，将m3u8文件按小时生成，比如每天可以生成00.m3u8...23.m3u8文件。
每个**.m3u8文件是该小时目录下所有ts文件的列表。

**目前我的实现方式**
自己写了一个C代码，做成了定时任务进行合并，能够基本实现，缺点是不知道每个ts文件的时长，只能取一个固定值，导致播放时长不准确。

**Comment by xia-chu** [comment]
不是你想切片就能切片的 切片的时机不是连续的 而是离散的 准确的说 是遇到关键帧才切片 但是一个关键帧好几秒 所以不可能按照你的要求准点准秒切片。
另外zlm可以指定切片大小，这个已经足够了，因为hls录像是有m3u8索引的，也就是说ts文件多长 名称是什么 其实没任何意义

**Comment by AlphaWu** [comment]
感谢夏大的回复。现在ts文件是按照时间分目录存储的，我想在时间的目录之外，生成一个包含该时段的m3u8文件。类似于这样。
![image](https://user-images.githubusercontent.com/612701/202889484-d6a16a01-859f-428b-ada3-06102aebbd9a.png)

**Comment by AlphaWu** [comment]
现在的m3u8文件是我事后合并的，已经基本上可以用，唯一有问题的是不知道每个ts文件的具体时长，现在只能写死。

#EXTINF:8,
