### ISSUE TITLE
RTSP推流时打印警告信息

### ISSUE THREAD

**Issue by quxiaohuixiangxuexue** [ZLMediaKit/ZLMediaKit#2100]
RTSP推流端推送H264给公网媒体服务时，若使用UDP协议传输RTP数据包，推流正常，可是会打印警告日志，截图如下：
![image](https://user-images.githubusercontent.com/56460673/202892841-ea0417a4-bfd0-4348-8ee4-651239a75ab7.png)

请问这是为什么？尽管我可以注释这条警告信息

**Comment by quxiaohuixiangxuexue** [comment]
![image](https://user-images.githubusercontent.com/56460673/202892890-c84199b9-44ff-4429-b82f-6629aaf6fc19.png)
推流端打印的这条警告日志

**Comment by xia-chu** [comment]
这个socket被对方关闭了 但是udp还在一直发

**Comment by quxiaohuixiangxuexue** [comment]
服务端在接收码流，甚至能用VLC拉到这路流

**Comment by quxiaohuixiangxuexue** [comment]
服务端运行的MediaServer，不是docker启动的
