### ISSUE TITLE
Intercepting Frames from RTSP Stream

### ISSUE THREAD

**Issue by perara** [ZLMediaKit/ZLMediaKit#2101]
Hello!

Amazing work on ZLMediaKit, especially with the wise support for protocols.

I wish to access the video streams from cameras directly without using the RTSPPlayer available so to minimize latency.

So far ive yet to find a way to "hook" rtsp streams.
How would i go about to do this?

Essentially what i want is:
Camera =》 RTSP STREAM =》ZLMediaKit =》 AvFrame access

Thanks for help and i apologize for not being able to communicate in other but English!

**Comment by perara** [comment]
I eventually found a hacky way of accessing the frames directly by overriding RtspSession and making the `_push_src` protected instead of private.
`class InjectedRtspSession : public mediakit::RtspSession`
and overriding the `onRecv`
```
   void onRecv(const toolkit::Buffer::Ptr &buffer) override {
        RtspSession::onRecv(buffer);

        // Setup decoding
        if(!decoder && _push_src){
            setupDecoder();
        }
    }```
This gives me roughly 40ms less latency than connecting using the example player.

**BUT** i still would need a better way of accessing the `_push_src`, without chaning the codebase.

1. How would I be able to access `_push_src`
2. Would it be possible to make a accessor if this is not possible?

**Comment by xia-chu** [comment]
Do you want to pull rtsp streaming from camera to get video frame？

**Comment by perara** [comment]
@xia-chu Correct. I send a camera feed to the RTSP server and I wish to postprocess this stream before republishing the stream.

I've found another way of doing this using the `NoticeCenter`, but I could not find a specific broadcast for "RTSP Started" which would be helpful:
Currently, I'm doing the following:
```
        NoticeCenter::Instance().addListener(nullptr, mediakit::Broadcast::kBroadcastMediaChanged, [&](const bool &bRegist, MediaSource &sender) {

            if(bRegist && sender.getSchema() == "rtsp"){

                auto track = sender.getTrack(mediakit::TrackType::TrackVideo);
                if(!track && track->getCodecId() != supportedTrack->getCodecId()){
                    return;
                }

                track->addDelegate([&](const mediakit::Frame::Ptr &frame) {
                    auto dec_frm = decoder->inputFrame(frame, true, true);
                    return dec_frm;
                });
            }
        });
```

**Comment by xia-chu** [comment]
Why not use `MediaPlayer` to pull rtsp stream?  Please ref these [code](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/player/test_player.cpp)

**Comment by perara** [comment]
@xia-chu This is certainly possible, and was my initial approach, however, this adds a layer of complexity which adds latency. Although I'm not 100% certain of the underlying logic, It seems like it the `MediaPlayer` connects to the RTSP stream and then pulls the RTSP Stream, which there is no reason for when the server itself needs access to the stream.

I did some testing and using the MediaPlayer approach adds 60-80ms latency, compared to the approaches above.
If the MediaPlayer were able to pull RTSP stream without going through loopback network, this would be a good interface

**Comment by xia-chu** [comment]
You require too strict on delay. Generally speaking, `MediaPlayer` do not increase latency, we have nowhere to deliberately increase the delay。If you want to pull the rtsp stream, you cannot evade the `MediaPlayer` object
