### ISSUE TITLE
[技术咨询] 视频运动画面闪动

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2102]
**咨询的具体内容和问题**
部署方式：1， wvp-GB28181-pro + zlm编译部署
                   2，AKStream+AKStreamNVR+zlm编译部署
                  以上两种部署(国标的方式)在UI界面都可以播放出视频，但在UI的播放器，VLC，还有几款其它的播放器中视频运动画面闪动，不平滑，时间表的秒数变化有时候也会出现闪动。
尝试过的方法：首先确认过海康摄像头本身的视频画面是OK的，再调整摄像头的一些视频参数(编码复杂度，平滑度等)，均没有效果，所以咨询下问题是否跟zlm相关，谢谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
可以用zlm的dump功能把rtp dump出来并上传上来给我们分析下
