### ISSUE TITLE
[技术咨询]webrtc访问不存在

### ISSUE THREAD

**Issue by xiaokyiba** [ZLMediaKit/ZLMediaKit#2104]
项目启动后webrtc用默认的访问，资源不存在；

我是想用工具拉 rtsp流，通过 webrtc播放，但是现在项目启动后，默认的webrtc访问不到

![111](https://user-images.githubusercontent.com/115332764/203015605-fccd77c4-4d5a-43d9-8f51-d98f5a3fd160.jpg)

**Comment by xiongguangjie** [comment]
去看wiki

**Comment by xia-chu** [comment]
@xiaokyiba 需要把源码中的www目录拷贝到 MediaServer当前目录。这个拷贝动作本来在cmake构建时就会执行的
