### ISSUE TITLE
[BUG]: BUG 现象描述: api接口mk_media_input_frame()调用一会儿报错.

### ISSUE THREAD

**Issue by 1004749822** [ZLMediaKit/ZLMediaKit#2106]
### 现象描述
1. 从海康相机中获取到流数据(相机可设置H264或H265编码格式), 使用mk_media_input_frame()这个api接口送入后再转发，大概一月前(22年10月份)的代码编译后，使用均是正常的。
2. 最近(应该在10月份之后吧)几次更新的代码，编译后，每次数据在送入mk_media_input_frame()这个接口时，连续送入几次后，接口就报错崩溃了。 换成原来(10份的).so)库，就正常.

### 如何复现?
海康的SDK中有个接口 NET_DVR_SetESRealPlayCallBack，在这个回调中，将数据送入mk_media_input_frame()，即可复现.

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你都不说报什么错 你让我们怎么解决？

**Comment by xia-chu** [comment]
zlm后面更新做了很多线程安全方面的检查，如果你是在poller线程中创建的mk_media对象，那么要求调用input_frame时的线程跟创建mk_media的线程一致；你把报错的那句代码注释掉就行的

**Comment by xia-chu** [comment]
<img width="1058" alt="图片" src="https://user-images.githubusercontent.com/11495632/203274022-feaf6018-9e5c-4b68-b4e8-d0e7956c4711.png">

**Comment by 1004749822** [comment]
嗯，明白了，感谢大佬~

**Comment by xia-chu** [comment]
c sdk有些接口如果使用不当，会有线程安全的问题；
mk_media对象建议在poller线程中创建、使用。

**Comment by xia-chu** [comment]
提问issue的 请star本项目支持下

**Comment by 1004749822** [comment]
好的， 我都试试。  最后我还是根据大佬的建议，修改使用poller中处理线程安全。
