### ISSUE TITLE
[功能请求] Return current recording file name

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#2108]
**描述该功能的用处，可以提供相关资料描述该功能**

other application can using this info to reference /linkage to their events,...

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

in some cases I monitored, startRecord API return empty data or take a long time to return. => may be call startRecord  many time but the real recording file name was created at first time call startRecord.

**描述你期望实现该功能的方式和最终效果**

Add this info to APIs:
startRecord
getMediaList,
getMediaInfo,
isRecording,
...

**Comment by xia-chu** [comment]
You mean record file path ?   Here is the content of `on_record_mp4` hook， what info do you want?
```json
{
   "mediaServerId" : "your_server_id",
   "app" : "live",
   "file_name" : "15-53-02.mp4",
   "file_path" : "/root/zlmediakit/httpRoot/__defaultVhost__/record/live/obs/2019-09-20/15-53-02.mp4",
   "file_size" : 1913597,
   "folder" : "/root/zlmediakit/httpRoot/__defaultVhost__/record/live/obs/",
   "start_time" : 1568965982,
   "stream" : "obs",
   "time_len" : 11,
   "url" : "record/live/obs/2019-09-20/15-53-02.mp4",
   "vhost" : "__defaultVhost__"
}
```

**Comment by pubpy2015** [comment]
yes, only file_path:
"file_path" : "/root/zlmediakit/httpRoot/__defaultVhost__/record/live/obs/2019-09-20/15-53-02.mp4",

**Comment by pubpy2015** [comment]
For me now perhaps just on_record_mp4 is enough information.
Thanks.
