### ISSUE TITLE
[功能请求]使用同一端口收流并且发流的功能新增（用于语音对讲）。

### ISSUE THREAD

**Issue by shanyuanzz** [ZLMediaKit/ZLMediaKit#2109]
**描述该功能的用处，可以提供相关资料描述该功能**
    在语音对讲双向通信中，有需要用到使用同一个端口收流并且发流的场景。
    如使用openRtpServer接收对方语音流，而后使用startSendRtp来发送本地语音流。
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
    目前语音双向对讲，在UDP方式下，可以使用两个端口进行收流和发流，实现语音对讲。
     但是如果在TCP协议下，需要使用同一个端口与对方建立收流和发流的链接，就限制了语音双向对讲的实现。
**描述你期望实现该功能的方式和最终效果**
     
     可以startSendRtp接口增加一个额外的可以收流的功能
     或者可以在openRtpServer接口增加一个可以复用的发流功能。
      使得同一个端口实现语音流的收发。

**Comment by Caoxw156** [comment]
我想请问一下，你这个语音对讲是使用webrtc实现的么

**Comment by shanyuanzz** [comment]
采集用户语音这部分我打算用上webrtc，如果有其他方式我也会考虑



在 2022-11-30 18:11:12，"Caoxw156" ***@***.***> 写道：

我想请问一下，你这个语音对讲是使用webrtc实现的么

**Comment by xia-chu** [comment]
startSendRtp接口已经新增参数`recv_stream_id`, 用于指定接收流的流id。
使用方法如下：
- 1、用webrtc推流给zlmediakit.
- 2、sip控制设备双向对讲。
- 3、调用zlmediakit的startSendRtp接口(指定recv_stream_id参数)，把webrtc推流的这路流再推给设备。
- 4、设备发送rtp给zlmediaikit startSendRtp接口创建的端口(也就是用于发送和接收rtp的端口)。
- 5、zlmediakit收到设备发送的rtp，生成新的一路流，流id为recv_stream_id参数指定。
- 6、使用webrtc协议或其他协议播放rtp/recv_stream_id这路流。

**Comment by xia-chu** [comment]
需要指出的是 双向对讲 zlmediakit收到的流 也会触发on_publish鉴权hook，原因是用户可以通过hook控制转协议
