### ISSUE TITLE
[技术咨询] on_stream_none_reader 的默认行为

### ISSUE THREAD

**Issue by Wszl** [ZLMediaKit/ZLMediaKit#2110]
**咨询的功能模块**
webhook的on_stream_none_reader

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

我在打开了日志后看到on_stream_none_reader时间后会自动输出
{
   "close" : true,
   "code" : 0
}
是不是相当于ZLM内建默认关闭流
因为我本身这里有没有人看的流，打印出了日志
readerCount" : 0,
"schema" : "hls",
"stream" : "61000002041320019217",
"totalReaderCount" : 0,

但还是一直没有关闭。
所以想问问这个webhook是不是必须要自己实现，还是说默认就是可以关闭流

**Comment by xiongguangjie** [comment]
wiki 上不上有吗

**Comment by xia-chu** [comment]
on_stream_none_reader默认行为不关闭无人观看的流 如果你要关闭 必须对接该hook 并且返回：
```json
{
"close" : true,
"code" : 0
}
```
