### ISSUE TITLE
[BUG]: BUG early destruction of the logger

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#2111]
Hello, this example results in a segfault on exit in linux

```
#include "Common/Device.h"

int main(int argc, char *argv[]) {

    mediakit::ProtocolOption option;
    mediakit::DevChannel::Ptr test = mediakit::DevChannel::Ptr(new mediakit::DevChannel("__defaultVhost__", "live", "test", 0, option));
    sleep(3);

    return 0;
}
```
![test](https://user-images.githubusercontent.com/55526028/203610306-32cc6654-1fb7-4a78-bce5-7ab03a40e1e2.png)

**Comment by xia-chu** [comment]
Sorry, we can not recurring the bug.
We had test on macos and linux , this case not occured.

Do you compiled zlmediakit with option `ENABLE_HLS/ENABLE_MP4`?

**Comment by a-ucontrol** [comment]
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_INSTALL_PREFIX=$DESTDIR/x86_64-pc-linux-gnu -
-DENABLE_WEBRTC=ON \
-DENABLE_PLAYER=OFF \
-DENABLE_CXX_API=ON \
-DENABLE_API_STATIC_LIB=ON

**Comment by a-ucontrol** [comment]
But this is only if you use DevChannel, with MultiMediaSourceMuxer everything is fine.
