### ISSUE TITLE
[技术咨询]  集成海康SDK协议接入设备

### ISSUE THREAD

**Issue by phlahut** [ZLMediaKit/ZLMediaKit#2112]
**咨询的功能模块**
- 协议接入

**咨询的具体内容和问题**
- 是否可以支持，集成海康SDK协议接入设备，通过海康HCNetSDK接入海康设备，并且提供http接口，用户通过调用HTTP接口，就可以通过海康SDK方式接收设备的视频流注册到ZLM中

**Comment by xia-chu** [comment]
这是你的工作 需要你自己完成
