### ISSUE TITLE
[技术咨询] 删除拉流代理后，播放器端没有自动关闭播放

### ISSUE THREAD

**Issue by zhink** [ZLMediaKit/ZLMediaKit#2113]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 1、删除拉流代理后,ffplay播放http-flv时，打印RTMP_ReadPacket, failed to read RTMP packet header后，没有关闭窗口
- 2、如若拔掉IPC网络然后恢复网络，使用ffplay播放http-flv，zlmediakit会反注册、然后注册流，但是ffplay播放画面停在拔掉IPC网络时。
- 这两个问题应该怎么良好的处理

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
ffplay没超时自动关闭功能
