### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by TopSpoofer** [ZLMediaKit/ZLMediaKit#2114]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

推流地址

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

我的推流地址：
rtmp://192.168.2.91:1935/hls/7f88757a-fb39-4ba0-8479-96122003b2c8

但我在日志中发现：
app = hls
streamId = 7f88757a-fb39-4ba0-8479-96122003b2c8/7f88757a-fb39-4ba0-8479-96122003b2c8

对， 7f88757a-fb39-4ba0-8479-96122003b2c8 重复了。

![image](https://user-images.githubusercontent.com/5953930/203758330-4d3183eb-45eb-4246-90d2-82744c1669c4.png)

然后我用 SRS 做同样的验证，结果如下：
![image](https://user-images.githubusercontent.com/5953930/203758492-b2373322-2b22-42a3-b6f1-96db95285e0d.png)

可以发现，在 SRS 中，
app = hls/7f88757a-fb39-4ba0-8479-96122003b2c8
streamId = 7f88757a-fb39-4ba0-8479-96122003b2c8

也就是 7f88757a-fb39-4ba0-8479-96122003b2c8 是重复的。

我的捉包结果：
![image](https://user-images.githubusercontent.com/5953930/203758791-8daa6725-e52a-4345-843f-89f72f1f654f.png)

![image](https://user-images.githubusercontent.com/5953930/203758858-90fe9964-5255-46e8-8b74-79a3b03eb99c.png)

![image](https://user-images.githubusercontent.com/5953930/203758912-a4c4cfa4-0172-4647-8c67-5fc68c87528f.png)

![image](https://user-images.githubusercontent.com/5953930/203759519-bc76719e-9b0c-4064-9565-b46cb640ca03.png)

最后我的问题是：
我在 捉包结果中，看着挺正常的，但为啥 7f88757a-fb39-4ba0-8479-96122003b2c8 是重复的？

**Comment by xia-chu** [comment]
你是什么推流客户端?

**Comment by TopSpoofer** [comment]
> 你是什么推流客户端?

不知道，他们自研的。我也看不到源码。按他们说的是，推到nginx+rtmp没有问题，但我推到SRS就跟ZLM一样。RTMP协议我没有详细研究过，所以咨询一下你们，看看哪方面可能会出问题。

**Comment by TopSpoofer** [comment]
> 你是什么推流客户端?

这个根据请求生成 appid、streamid 在哪个个cpp？我可以自己去调试的

**Comment by xia-chu** [comment]
很明显 tcUrl不能包含stream_id

**Comment by xia-chu** [comment]
FFmpeg/obs都是这么做的

**Comment by TopSpoofer** [comment]
> FFmpeg/obs都是这么做的

我抓包了，ZLM 这边没啥问题，他本身推流的 tcUrl 就是：rtmp://192.168.2.91:1935/hls/7f88757a-fb39-4ba0-8479-96122003b2c8 导致重复
