### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by cnyinfei** [ZLMediaKit/ZLMediaKit#2118]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

请问zlm现在能否支持在addStreamProxy中将源h265视频流转换为h264视频流？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

之前有用zlm的拉流代理功能拉取IPC摄像机的RTSP流，实现多路播放的分发，避免多客户端同时拉取IPC原始视频流，在IPC为H264的情况下工作正常，现在在实际使用中遇到一批H265编码的IPC，由于不可抗力因素，不能修改其编码，因此想咨询当前zlm的拉流代理功能能否支持H265->H264的转码？（条件限制未采用ffmpeg推流的方案）

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
不支持



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: cnyinfei ***@***.***&gt;
发送时间: 2022年11月27日 10:44
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (Issue #2118)





 
咨询的功能模块
  
请描述您想咨询zlmediakit的哪部分功能 
 
请问zlm现在能否支持在addStreamProxy中将源h265视频流转换为h264视频流？
 
咨询的具体内容和问题
  
此处展开您咨询内容的描述 
 
之前有用zlm的拉流代理功能拉取IPC摄像机的RTSP流，实现多路播放的分发，避免多客户端同时拉取IPC原始视频流，在IPC为H264的情况下工作正常，现在在实际使用中遇到一批H265编码的IPC，由于不可抗力因素，不能修改其编码，因此想咨询当前zlm的拉流代理功能能否支持H265-&gt;H264的转码？（条件限制未采用ffmpeg推流的方案）
 
注意事项
  
 
技术咨询前请先认真阅读readme, wiki,如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue
 

 
技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by cnyinfei** [comment]
感谢作者大大，非常棒的项目。
