### ISSUE TITLE
[BUG] RtspPlayer 出现死循环bug

### ISSUE THREAD

**Issue by x-x-p** [ZLMediaKit/ZLMediaKit#2121]
当RtspPlayer拉流失败时触发SockerErr, 而`onPlayResult_l`中又因为`RtspPlayer::sendRtspRequest("TEARDOWN", _content_base);` 从而`SockSender::send(std::move(printer));`,又出现了`Socket::flushData`中`emitErr(toSockException(err));`在此触发SockerErr, 死循环了

https://github.com/ZLMediaKit/ZLMediaKit/blob/fef9d3163163527ca97298029766f2315583c8c0/src/Rtsp/RtspPlayer.cpp#L129-L133
https://github.com/ZLMediaKit/ZLMediaKit/blob/fef9d3163163527ca97298029766f2315583c8c0/src/Rtsp/RtspPlayer.cpp#L678-L721
https://github.com/ZLMediaKit/ZLMediaKit/blob/fef9d3163163527ca97298029766f2315583c8c0/src/Rtsp/RtspPlayer.cpp#L36-L46
https://github.com/ZLMediaKit/ZLMediaKit/blob/fef9d3163163527ca97298029766f2315583c8c0/src/Rtsp/RtspPlayer.cpp#L581-L628

**Comment by x-x-p** [comment]
zlmediakit 添加代理流，拉取摄像头， 然后动态修改摄像头的音频格式，直接导致zlmediakit死循环崩溃。

**Comment by xia-chu** [comment]
嗯 这个是改出问题了

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by xia-chu** [comment]
打下补丁吧
```c++
Index: src/Network/Socket.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Network/Socket.cpp b/src/Network/Socket.cpp
--- a/src/Network/Socket.cpp	(revision 617b6b1db23f13e2592b29204b84b1b9dbbf81c0)
+++ b/src/Network/Socket.cpp	(date 1669616699001)
@@ -340,7 +340,7 @@
             return false;
         }
     }
-
+    closeSock();
     weak_ptr<Socket> weak_self = shared_from_this();
     _poller->async([weak_self, err]() {
         auto strong_self = weak_self.lock();
@@ -354,8 +354,6 @@
             ErrorL << "Exception occurred when emit on_err: " << ex.what();
         }
     });
-
-    closeSock();
     return true;
 }
 

```
