### ISSUE TITLE
[技术咨询]NAT网络环境推流和拉流行为问题

### ISSUE THREAD

**Issue by goodtogood** [ZLMediaKit/ZLMediaKit#2122]
zlm版本为 [9fd5152](https://github.com/ZLMediaKit/ZLMediaKit/commit/9fd5152aa116ea0c896d40fdd20ccceb9731b828) 
zlm运行在内网HostA上，运行所有默认服务，防火墙均已经开放所有默认服务端口，
网关上也进行了相应的NAT端口映射，主要网络拓扑如下

   HostA： 
          192.168.1.1 内网地址
          live.aabb.com 外网地址

配置文件中除启用虚拟主机外，其它均为默认

`enableVhost=1`

**咨询的具体内容和问题**

在HostA中使用ffmpeg向zlm推流  rtmp://192.168.1.1/live/test
此时使用以下地址拉流均正常

```
rtmp://192.168.1.1/live/test
rtsp://192.168.1.1/live/test
http://192.168.1.1/live/test.live.flv
http://192.168.1.1/live/test.live.mp4
```
此时如果用外网的域名拉流，均不可访问

```
rtmp://live.aabb.com/live/test
rtsp://live.aabb.com/live/test
http://live.aabb.com/live/test.live.flv
http://live.aabb.com/live/test.live.mp4
```

此情况下日志大致都为类似

```
2022-11-28 15:40:53.358 W MediaServer[325612-331028] RtmpSession.cpp:33 onEr
ror | 4-632(192.168.8.254:60497) RTMP播放器(//)断开:end of file,耗时(s):4

2022-11-28 15:42:19.258 W MediaServer[325612-331412] HttpSession.cpp:105 onE
rror | 9-620(192.168.8.1:60520) FLV/TS/FMP4播放器(__defaultVhost__/live/test)断
开:end of file,耗时(s):11
```

如果推流时用外网域名方式，则上面域名拉流可以正常访问，请问这和情况是正常的吗？
把虚拟主机禁用也是如此

**Comment by xiongguangjie** [comment]
https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99 是正常的，虚拟主机禁用，需要重新推流，如果是修改配置文件修改的需要重启服务

**Comment by goodtogood** [comment]
明白了，谢谢
