### ISSUE TITLE
[技术咨询]在自己的项目中引用开源播放器播放webrtc会报CORB同源问题

### ISSUE THREAD

**Issue by wmp370481** [ZLMediaKit/ZLMediaKit#2124]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个问题我没遇到过 我也不熟悉前端开发 所以爱莫能助

**Comment by wmp370481** [comment]
感谢回复，确实是三方开源播放器的问题，我使用了您提供播放器是没有问题的。p s:我已实现了在vue项目使用您提供的插件进行webrtc播放，实时延时在0.5s以下，有需要知道的其他同行可以在这留言
