### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by Caoxw156** [ZLMediaKit/ZLMediaKit#2130]
**咨询的功能模块**
WebRTC一路通道收发数据实现语音对讲

**咨询的具体内容和问题**
我测试了webrtc的demo页面，推流和拉流都是一个通道单独收或者发数据，至于echo功能是同一个页面直接两个窗口的推拉，我想实现两台电脑之间通过一个媒体url访问，来实现单通道直接收发数据的语音对讲功能。不知道现有项目是否支持该功能。还是说我需要单独再此基础上开发。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
自己独立开发，或者不使用zlm的rtc sfu ,使用rtc 的p2p 模式
