### ISSUE TITLE
[技术咨询]拉取裸数据接口

### ISSUE THREAD

**Issue by cunyu-wxy** [ZLMediaKit/ZLMediaKit#2131]
**ZLM拉取裸数据**
- ZLM拉流

**ZLM服务一起来就去拉取裸数据**
-我想在服务一起来就去我的摄像头拉取裸数据，然后封装成一个指针和长度丢出去，但一直没找到好的方法，尝试过模仿MP4Recorder写了一个h264recorder,用inputFrame确实能取到裸数据，但这样我在上层想调用就要共享内存了，实在没找到别的更合适的方法，想咨询一下ZLM是否有类似接口提供调用，非常感谢！

**Comment by xia-chu** [comment]
你可以参考test_player.cpp的代码 里面不是有拉流获取H264的代码么？
