### ISSUE TITLE
[使用咨询] 如何关闭record功能

### ISSUE THREAD

**Issue by HuangDayu** [ZLMediaKit/ZLMediaKit#2133]
**咨询的功能模块**
- record

**咨询的具体内容和问题**
- 开启record后，会占用大量磁盘，还需手动删除，请问如何关闭该项功能。

**Comment by cunyu-wxy** [comment]
通过restful关一下

**Comment by Washington-DC** [comment]
配置文件中有相关配置，是否开启推流时进行录制等功能

**Comment by xia-chu** [comment]
请仔细阅读wiki

**Comment by sherrywasp** [comment]
如果是配合 WVP-PRO 使用的话，修改 WVP-PRO 项目配置文件 application.yml，将 record-sip 配置为 false
```yml
user-settings:
  record-sip: false 
```
