### ISSUE TITLE
[技术咨询]Socket::flushData关于 poller_thread参数疑惑

### ISSUE THREAD

**Issue by zhouxiaojun2008** [ZLMediaKit/ZLMediaKit#2135]
**咨询的功能模块**
- bool Socket::flushData(const SockFD::Ptr &sock, bool poller_thread) 

**咨询的具体内容和问题**
- 关于 poller_thread参数，在这个函数里面反复提到“如果是poller线程，...”，
   大佬文章之前说过，“一个TcpSession由一个epoll实例掌管其生命周期，其他线程不得直接操作该TcpSession对象（必须通过线 
   程切换到对应的epoll线程来完成操作）；所以从某种意义上来说TcpSeesion是单线程模型的；”，另外我自己看代码理解，也 
   是这样的。那这个flushdata都是在自己对应的poller线程调用的话， poller_thread这个参数是否就没太大意义，大佬能解惑一 
   下么这个参数吗？我唯一看到赋值为true的地方是在Socket::onWriteAble函数，其他地方都为false，当这个参数为false的时 
   候，Socket::flushData在未发送完全的时候，会调用startWriteAbleEvent。

**Comment by xia-chu** [comment]
因为还有TcpClient的使用场景，zlm在底层socket是允许非poller线程操作Socket对象的，如果限制必须使用Poller线程使用Socket对象，那么使用者会比较痛苦

**Comment by xia-chu** [comment]
好在zlm的主程序MediaServer基本不存在非Poller线程操作的问题，所以我其实也有想法去除Socket对象的锁并且加上线程安全判断的断言，但是这样的话，c api的使用者和二次开发者可能会比较痛苦，不过这样也好，可以规避很多隐藏的线程安全问题

**Comment by zhouxiaojun2008** [comment]
多谢大佬百忙解惑。
srs和zlmediakit各有千秋，之前我搞srs比较多，srs作者偏向互联网，rtmp主协议开发，
zlm一看是安防背景，rtsp起家。
我看zlm的srt实现居然是自己实现协议，没用libsrt，真厉害

**Comment by xia-chu** [comment]
srt是我们团队一位大佬 @xiongguangjie 实现的，欢迎您使用zlm并发现问题同时一起参与开发贡献代码。
