### ISSUE TITLE
[技术咨询] RTSP支持REDIRECT命令吗

### ISSUE THREAD

**Issue by SteveWooo** [ZLMediaKit/ZLMediaKit#2136]
**咨询的功能模块**
- rtsp按需拉流功能（addStreamProxy）

**咨询的具体内容和问题**
- 请问用zlmedia拉rtsp流时，有没有处理流的重定向请求呢~？我看到rtspPlayer.cpp里面处理了DESCRIBE和OPTIONS时候的重定向，但不太确定有没有处理后续的REDIRECT这个指令。在旧issue中看到说已经处理了rtsp的重定向，所以想提问确认下这个ヾ(•ω•`)o

**Comment by xia-chu** [comment]
不支持REDIRECT命令 但是支持302回复自动跳转，你说的是不是这个？

**Comment by SteveWooo** [comment]
嗯嗯 对的，明白了，非常感谢回复！
