### ISSUE TITLE
[技术咨询] ZLMediaKit 生成rtmp推流地址的接口

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2140]
**咨询的具体内容和问题**
- 大家好，想咨询下：ZLMediaKit有没有提供一个生成rtmp推流地址，供外部调用的接口。又或者说外部如何能获取rtmp推流地址。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
看wiki
