### ISSUE TITLE
[BUG]: vlc 拉流时抓包发现server会发两个序列号一样的rtp分片到播放端

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2141]
用vlc通过 ./MediaServer  拉流的时候，vlc播放正常，但是抓包发现server会发两个序列号一样的rtp分片到vlc，请问这个情况是正常吗
 
![QQ图片20221202192048](https://user-images.githubusercontent.com/23181609/205281632-3d80456a-81c5-4f29-87bb-2a2169c19c9a.png)

**Comment by xiongguangjie** [comment]
我抓包，没问题呀，是否你播放了两路呀
