### ISSUE TITLE
[BUG]: startRecord 等 API 需要提供录制文件的路径，customized_path 参数没有进行 url decode，导致各种乱码的情况

### ISSUE THREAD

**Issue by TopSpoofer** [ZLMediaKit/ZLMediaKit#2144]
### 现象描述

startRecord 等 API 需要提供录制文件的路径，此参数没有进行 url decode，导致各种乱码的情况 

### 如何复现?

1、window 10 编译

2、postman 发送请求：
customized_path 设置为 C:\Users\123456\Desktop\还好h   

```
http://localhost:8888/index/api/startRecord?secret=xxx&stream=acf712e5-e3aa-4c43-9c76-d66fa6fe4364&app=hls&vhost=__defaultVhost__&type=1&customized_path=C:\Users\123456\Desktop\还好h
```

3、期望存储到 C:\Users\123456\Desktop\还好h，实际上 "还好h" 乱码了

**Comment by xiongguangjie** [comment]
应该是请求房做转义

**Comment by TopSpoofer** [comment]
> 应该是请求房做转义

确实是要在请求方做转义，但我看到ZLM日志输出的是已经做了转码的样子（一堆%%%%xxx的），不清楚postman有没有做转码。

**Comment by TopSpoofer** [comment]
> zlm 是做过url decode 的，但是windows 中文路径，这个最好避免，我也没测试过

我调试了，我这边的问题是 akka http 已经做了一次 encode 导致的。

**Comment by youth7** [comment]
在winddows下，录像的目录确实会出现乱码，在zlmedia server的控制台显示是正常的，但是创建出来却是乱码的，并且有一定概率创建失败。

例如在控制台看到是这样的，此时显示正常符合预期：

<img width="748" height="86" alt="Image" src="https://github.com/user-attachments/assets/d27b12e7-da74-4ca0-ab97-ddb6f0435d3c" />

但最终创建出来却是这样的：

<img width="304" height="116" alt="Image" src="https://github.com/user-attachments/assets/e9290bda-67c5-43b8-bfe3-2ca0afdb25f1" />

@xiongguangjie
