### ISSUE TITLE
[BUG]: BUG 分支: feature/transcode G771A转AAC不Work

### ISSUE THREAD

**Issue by Haoxw** [ZLMediaKit/ZLMediaKit#2145]
您好 使用了最新的 feature/transcode分支进行编译测试，ffmpeg为5.1.1版本，视频的快照是正常的，但是在FLV格式的视频播放链接的回放中，G711A转AAC这个功能不工作，我实际拿VLC 去查看音频的编码格式还是G711A，但是在之前的版本中我曾经测试是可以，这个新合并的版本是需要修改配置文件吗？还是存在Bug，谢谢！
=============================================
[root@fzb01 RELEASE]# ./MediaServer  -v
编译日期: 2022-12-05 20:50:44
当前git分支: feature/transcode
当前git hash值: 128af38
=============================================
谢谢！

**Comment by Leonnash** [comment]
我经作者指点
因为zlm分支是所需转码,需要拉流才生效
#是否将mp4录制当做观看者
mp4_as_player=1 打开设置为1
才进行转码，但打开是指会有如果一直录制无法触发web hook无人观看

**Comment by Haoxw** [comment]
feature/transcode分支和 feature/transcode2 分支有什么区别吗？我实际测试了，即使是将“mp4_as_player=1 打开设置为1”，依然会不转码G771A至AAC，我明天再编译一下“ feature/transcode2 分支”再测试一下。

**Comment by Leonnash** [comment]
> feature/transcode分支和 feature/transcode2 分支有什么区别吗？我实际测试了，即使是将“mp4_as_player=1 打开设置为1”，依然会不转码G771A至AAC，我明天再编译一下“ feature/transcode2 分支”再测试一下。

feature/transcode2一直有人维护

**Comment by Haoxw** [comment]
feature/transcode 这个分支 我看也有合并最近的Master分支代码上去 ， feature/transcode 这个分支没有人维护吗 ？

**Comment by Haoxw** [comment]
我今天测试使用了feature/transcode2 这个分支，但是在执行“git submodule update --init”的时候报错了

**Comment by Leonnash** [comment]
> 我今天测试使用了feature/transcode2 这个分支，但是在执行“git submodule update --init”的时候报错了

可以的，先clone ,git submodule update --init，再切分支

**Comment by Haoxw** [comment]
好的 我试试   谢谢 
再一个我发现一个问题，我在编译的时候发现报这个警告“  ffmpeg 相关功能未找到”，难道在编译的时候，还需要在cmake的编译选项中指定“ffmepg”的相关参数配置吗，具体的配置参数是什么，能提供一线吗？谢谢！
**
CMake Warning at CMakeLists.txt:214 (message):
  Compiler doesn't support std::atomic<long long>


CMake Warning at CMakeLists.txt:305 (message):
  ffmpeg 相关功能未找到

**

**Comment by Leonnash** [comment]
> 好的 我试试 谢谢 再一个我发现一个问题，我在编译的时候发现报这个警告“ ffmpeg 相关功能未找到”，难道在编译的时候，还需要在cmake的编译选项中指定“ffmepg”的相关参数配置吗，具体的配置参数是什么，能提供一线吗？谢谢！ ** CMake Warning at CMakeLists.txt:214 (message): Compiler doesn't support std::atomic
> 
> CMake Warning at CMakeLists.txt:305 (message): ffmpeg 相关功能未找到
> 
> **

得先装上得4.0以上ffmpeg，包括源码有dockerfile 写了编译过程得
https://github.com/ZLMediaKit/ZLMediaKit/blob/master/docker/centos7/Dockerfile.runtime

**Comment by xia-chu** [comment]
CMake Warning警告你可以不用关注

**Comment by mtdxc** [comment]
transcode分支没711转码功能，transcode2最新版本才有转码开关，具体为啥没有，请详见代码哈。。

**Comment by Haoxw** [comment]
您好，大神，“transcode2最新版本有711转码开关”，这个转码开关配置是在配置文件里吗？我编译了您昨天刚刚强推的“transcode2”版本，但是实际测试还是没有转换？音频依然是711A，我哪里配置有问题吗？谢谢！
@mtdxc

**Comment by mtdxc** [comment]
嗯，在配置文件里面的，默认是关闭的，你是什么场景，这个开关只在进出rtc时才进行转码
`// 是否转码G711音频，做到: 出rtc将g711转成aac，入rtc将g711转成opus
const string kTranscodeG711 = RTC_FIELD "transcodeG711";

// webrtc单端口udp服务器
const string kPort = RTC_FIELD "port";

const string kTcpPort = RTC_FIELD "tcpPort";

static onceToken token([]() {
    mINI::Instance()[kTimeOutSec] = 15;
    mINI::Instance()[kExternIP] = "";
    mINI::Instance()[kRembBitRate] = 0;
    mINI::Instance()[kPort] = 8000;
    mINI::Instance()[kTcpPort] = 8000;
    mINI::Instance()[kTranscodeG711] = 0;
});`

**Comment by Haoxw** [comment]
我播放实时流时使用的是F LV格式的，但是原始的视频流是通过RTP协议推送上来的，RTP推送上来的是G711A的音频编码，FLV无法播放，需要转换转换成AAC，才能播放。

**Comment by Haoxw** [comment]
是在 配置文件的“[protocol]”的节点中添加“transcodeG711=1”这个配置项吗？
[protocol]
transcodeG711=1

**Comment by mtdxc** [comment]
你这场景没法转码，
我说了好几次了，这只能转码rtc音视频。
transcodeG711配置项是在rtc下的
你得自己改改代码了。。

**Comment by mtdxc** [comment]
> 我播放实时流时使用的是F LV格式的，但是原始的视频流是通过RTP协议推送上来的，RTP推送上来的是G711A的音频编码，FLV无法播放，需要转换转换成AAC，才能播放。

我刚又重新确认下transcode代码，你这个需求应该是能转码的，transcode2只转码rtc的，
但transcode默认是将aac音频转成opus，传到rtc； 接着是将非aac的音频都转成aac入rtmp;
说应该是能转码的，可能是ffmpeg没编译进去导致的吧？
