### ISSUE TITLE
[技术咨询] RTSP over RTP 推流数据如何加密

### ISSUE THREAD

**Issue by Shilling-H** [ZLMediaKit/ZLMediaKit#2146]
**咨询的功能模块**
- RTSP 拉流&推流

**咨询的具体内容和问题**
- 使用ZLMediaKit从本地的RTSP server端拉流后推送到公网的RTSP server端，流为实时视频流，在连接公网环境带宽不好的情况下rtsps方式比较卡顿，所以只能通过RTSP UDP方式推流，但UDP裸流安全性不高，期望对推送的RTP UDP码流进行AES加密

**Comment by xia-chu** [comment]
目前做不到 只能通过rtsps over tcp方式
