### ISSUE TITLE
[BUG]: “feature/transcode2”分支在Clone代码后执行 “ git submodule update --init”会出现问题

### ISSUE THREAD

**Issue by Haoxw** [ZLMediaKit/ZLMediaKit#2147]
“feature/transcode2”分支在Clone代码后执行 “ git submodule update --init”会出现下面的问题：
**
fatal: 引用不是一个树：17c659fa3d51130e1364b27bf0fa2acba9bb830a
无法在子模组路径 '3rdpart/ZLToolKit' 中检出 '17c659fa3d51130e1364b27bf0fa2acba9bb830a'
**

[root@fzb01 ZLMediaKit_depth0]# git submodule update --init
子模组 'ZLToolKit' (https://gitee.com/xia-chu/ZLToolKit) 已为路径 '3rdpart/ZLToolKit' 注册
子模组 '3rdpart/jsoncpp' (https://gitee.com/mirrors/jsoncpp.git) 已为路径 '3rdpart/jsoncpp' 注册
子模组 '3rdpart/media-server' (https://gitee.com/ireader/media-server) 已为路径 '3rdpart/media-server' 注册
正克隆到 '3rdpart/ZLToolKit'...
remote: Enumerating objects: 7575, done.
remote: Counting objects: 100% (559/559), done.
remote: Compressing objects: 100% (437/437), done.
remote: Total 7575 (delta 384), reused 204 (delta 118), pack-reused 7016
接收对象中: 100% (7575/7575), 31.47 MiB | 186.00 KiB/s, done.
处理 delta 中: 100% (5742/5742), done.
fatal: 引用不是一个树：17c659fa3d51130e1364b27bf0fa2acba9bb830a
正克隆到 '3rdpart/jsoncpp'...
remote: Enumerating objects: 8755, done.
remote: Counting objects: 100% (8755/8755), done.
remote: Compressing objects: 100% (2780/2780), done.
remote: Total 8755 (delta 5637), reused 8755 (delta 5637), pack-reused 0
接收对象中: 100% (8755/8755), 2.58 MiB | 65.00 KiB/s, done.
处理 delta 中: 100% (5637/5637), done.
子模组路径 '3rdpart/jsoncpp'：检出 '8190e061bc2d95da37479a638aa2c9e483e58ec6'
正克隆到 '3rdpart/media-server'...
remote: Enumerating objects: 12660, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 12660 (delta 33), reused 55 (delta 22), pack-reused 12569
接收对象中: 100% (12660/12660), 3.30 MiB | 166.00 KiB/s, done.
处理 delta 中: 100% (9541/9541), done.
子模组路径 '3rdpart/media-server'：检出 '357ef885afa5112c8cb873eab21d94d26744c0ab'
无法在子模组路径 '3rdpart/ZLToolKit' 中检出 '17c659fa3d51130e1364b27bf0fa2acba9bb830a'
[root@fzb01 ZLMediaKit_depth0]# git submodule update --init
fatal: 引用不是一个树：17c659fa3d51130e1364b27bf0fa2acba9bb830a
无法在子模组路径 '3rdpart/ZLToolKit' 中检出 '17c659fa3d51130e1364b27bf0fa2acba9bb830a'
[root@fzb01 ZLMediaKit_depth0]# git submodule update --init
fatal: 引用不是一个树：17c659fa3d51130e1364b27bf0fa2acba9bb830a
无法在子模组路径 '3rdpart/ZLToolKit' 中检出 '17c659fa3d51130e1364b27bf0fa2acba9bb830a'

**Comment by xia-chu** [comment]
@mtdxc 大佬 请核对下 是否你用了自己私有版本的依赖？

**Comment by mtdxc** [comment]
好，这我处理下，估计是一不小心提交上去了

**Comment by mtdxc** [comment]
> @mtdxc 大佬 请核对下 是否你用了自己私有版本的依赖？

不对呀，最新的提交ci是通过的，应该没用自己版本的toolkit，估计是toolkit近期重推了吧。

没事，刚好最近也有修改，等会我重推个版本上去。

**Comment by Haoxw** [comment]
收到 多谢 大神！！！ @mtdxc

**Comment by mtdxc** [comment]
> 收到 多谢 大神！！！ @mtdxc

这个版本与之前版本有些区别，转码配置项移到protocol.audio_transcode中，
并增加rtc.transcodeG711，用来控制是否对g711音频开启转码；
最后由于我是强推代码，你可能要先fetch，然后reset --hard feature/transcode2下

**Comment by Haoxw** [comment]
我直接“git clone -b feature/transcode2”这个分支，测试了是可以，多谢大神！
@mtdxc
