### ISSUE TITLE
startSendRtp推流语音一直是电流音

### ISSUE THREAD

**Issue by 1328786726** [ZLMediaKit/ZLMediaKit#2148]
**咨询的功能模块**
- startSendRtp接口

**咨询的具体内容和问题**
- 进行实时语音对讲的时候,推流到摄像头 一直是电流音无法正常说话,如果前端采集并通过webrtc发送的不是 rtpmap 8 PCMA/8000,在startSendRtp接口中指定pt为8之后是否会将音频流转码.

**Comment by xiongguangjie** [comment]
startSendRtp 不会将音频转码
