### ISSUE TITLE
GB28281-2016能支持对讲吗

### ISSUE THREAD

**Issue by QwQuan** [ZLMediaKit/ZLMediaKit#2149]
您好：

目前使用GB28281-2016推流的功能，但是不知道能不能在这个功能上实现语言广播，达到语言对讲功能；

感谢大佬开源

**Comment by vjeson** [comment]
期待同样的功能，很多家用摄像头都有类似的对讲功能

**Comment by lovederh** [comment]
期待中... 
我现在用的Wvp的sipserver, 在上面自己做了一个转发语音的程序, 先凑和用呐, 期待官方版本

**Comment by QwQuan** [comment]
> 期待中... 我现在用的Wvp的sipserver, 在上面自己做了一个转发语音的程序, 先凑和用呐, 期待官方版本

效果怎么样，延迟方面

**Comment by sxh-netizen** [comment]
@lovederh  请问你是在wvp上面做的转发语音程序吗

**Comment by 1328786726** [comment]
> 

你有做级联方面的语音广播处理吗 请教个问题  wvp 做为下级 假设livegbs是上级 你怎么处理的sdp和sip报文的,求教一下.

**Comment by 1328786726** [comment]
@lovederh 你有做级联语音广播的处理吗?国标的.有的话请教个问题 wvp作为下级 livegbs之类的做为上级   语音应答和Invite 你是怎么处理的 求教.

**Comment by xia-chu** [comment]
startSendRtp接口已经新增参数`recv_stream_id`, 用于指定接收流的流id。
使用方法如下：
- 1、用webrtc推流给zlmediakit.
- 2、sip控制设备双向对讲。
- 3、调用zlmediakit的startSendRtp接口(指定recv_stream_id参数)，把webrtc推流的这路流再推给设备。
- 4、设备发送rtp给zlmediaikit startSendRtp接口创建的端口(也就是用于发送和接收rtp的端口)。
- 5、zlmediakit收到设备发送的rtp，生成新的一路流，流id为recv_stream_id参数指定。
- 6、使用webrtc协议或其他协议播放rtp/recv_stream_id这路流。

本方案全程不需要调用openRtpServer接口。

**Comment by xia-chu** [comment]
需要指出的是 双向对讲 zlmediakit收到的流 也会触发on_publish鉴权hook，原因是用户可以通过hook控制转协议

**Comment by zhuangpengLI** [comment]
我这边也做了个demo

**Comment by xia-chu** [comment]
> 我这边也做了个demo

可以开源出来给大家学习一下吗？

**Comment by lovederh** [comment]
> @lovederh 你有做级联语音广播的处理吗?国标的.有的话请教个问题 wvp作为下级 livegbs之类的做为上级 语音应答和Invite 你是怎么处理的 求教.

我当时做的时候感觉zlm应该也是能转发语音的, 不过当时没深入研究, 所以就自己做了语音的转发, 我是通过wvp做的语音对讲发起, 和摄像头协商好语音对讲的数据格式和发送服务的ip、端口, 最后由wvp来转发的设备发过来的语音数据
