### ISSUE TITLE
[技术咨询] Is it possible to empty streamId

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#2150]
Helo!

Is it possible?
```MultiMediaSourceMuxer("__defaultVhost__", "test", "", 0, option);```

and ffplay rtsp://127.0.0.1/test

**Comment by xia-chu** [comment]
No, zlmediakit requires at least two levels of url, stream_id can not be empty, If you do this, will result in undefined behavior or connection rejection

**Comment by a-ucontrol** [comment]
Thanks
