### ISSUE TITLE
[技术咨询]APP端想要支持切换分辨率

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2156]
**咨询的具体内容和问题**
- 大家好！咨询下：设备端只支持一路流，APP想要支持分辨率的切换(高清，超清，标清)，ZLMediaKit能支持不同分辨率流的切换么，该怎么操作呢？谢谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
可以支持分辨率切换 你输入不同分辨率的视频一般是可以正常工作的

**Comment by wu-xiaohua** [comment]
有找到合适的方法吗，我也想要这个
