### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by mayongbin** [ZLMediaKit/ZLMediaKit#2157]
**咨询的功能模块**
 zml返回的播放地址

**咨询的具体内容和问题**
IPC通过gb28181注册到了wvp，点击播放，请求了zml播放地址，日志如下
![微信截图_20221212233501](https://user-images.githubusercontent.com/19423532/207088426-d8c7aea8-92f1-4b47-bd2e-9720a298c311.png)

返回了地址不是我的服务器ip，而是我的服务器名，所以我想知道vhost=__defaultVhost__ 是在哪里需改吗，下图是应用获取到的地址
![dc76a2e38ad7ca1794eef566db853eb](https://user-images.githubusercontent.com/19423532/207088521-9b0b1273-0c26-4af3-b841-426c5dbace27.png)

**Comment by xia-chu** [comment]
这个是wvp配置相关的问题 请在wvp项目提issue
