### ISSUE TITLE
[技术咨询]ZLM怎么支持URL防盗链

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2162]
**咨询的具体内容和问题**
- 大家好，咨询下：ZLM支持URL防盗链么，是已经支持了还是得自已另外再开发，若是二次开发，怎么操作呢？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
需要你对接on_play hook。
