### ISSUE TITLE
[功能请求]基于websocket的录制mp4文件点播

### ISSUE THREAD

**Issue by goodtogood** [ZLMediaKit/ZLMediaKit#2164]
**描述该功能的用处，可以提供相关资料描述该功能**

在web中同一页面显示多个录制mp4

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

http协议对于同域名下资源请求并发数有限制，使用ws没有此问题

**描述你期望实现该功能的方式和最终效果**

是否可以加入基于websocket的录制mp4文件点播功能

**Comment by xia-chu** [comment]
zlm已经支持websocket-fmp4直播
