### ISSUE TITLE
[BUG]: streamNoneReaderDelayMS 参数不生效，导致 on_stream_none_reader 回调时间不正确

### ISSUE THREAD

**Issue by TopSpoofer** [ZLMediaKit/ZLMediaKit#2167]
### 现象描述

#某个流无人观看时，触发hook.on_stream_none_reader事件的最大等待时间，单位毫秒
#在配合hook.on_stream_none_reader事件时，可以做到无人观看自动停止拉流或停止接收推流
streamNoneReaderDelayMS=20000

streamNoneReaderDelayMS 参数不生效， 设置了 20000 实际事件回调是 60 秒

系统： windows 10，版本是前几天拉的 master 代码

**Comment by xia-chu** [comment]
HLS不一样 hls不是长链接 是http短链接组成的 所以它断开后 不能断定它就停止播放了 是通过cookie超时来判断是否停止播放 
cookie超时时间为60秒

**Comment by TopSpoofer** [comment]
> HLS不一样 hls不是长链接 是http短链接组成的 所以它断开后 不能断定它就停止播放了 是通过cookie超时来判断是否停止播放 cookie超时时间为60秒

怪不得那么奇怪~ 好呢，正准备换到 FMP4 去！
