### ISSUE TITLE
[技术咨询] 性能方面的咨询

### ISSUE THREAD

**Issue by TopSpoofer** [ZLMediaKit/ZLMediaKit#2168]
### 架构

设备(只有一个，1080p, 30帧) <-- 拉流 --- ZLM_A 服务（机器 32核，ubuntu）<--拉流-- ZLM_B 服务（CPU：AMD 5800H，16线程，win 10） <--- 用户播放

简单的架构描述如上，现在 在 ZLM_B 上开启了  100 个直播到 ZLM_A 上拉流，它们都指向 ZLM_A 上的同一个流：
```
ZLM_B live1  ---拉流----> ZLM_A:1935/proxy/test?id=1
ZLM_B live2  ---拉流----> ZLM_A:1935/proxy/test?id=2
ZLM_B live3  ---拉流----> ZLM_A:1935/proxy/test?id=3
........
```
如上，live 1 到 100 都到 ZLM_A:1935/proxy/test 上拉流，只不过参数 id 不一样而已。

### 发现的问题
现在在 ZLM_B  播放 live 的时候，用的是 hls，ZLM_B   上 hls 的配置为：
```
#hls最大切片时间
segDur=3
#m3u8索引中,hls保留切片个数(实际保留切片个数大2~3个)
#如果设置为0，则不删除切片，而是保存为点播
segNum=3
```

现在发现，ZLM_B:8080/live/id（1-100）/hls.m3u8 播放非常慢（只播放其中一个直播，并且只有一个人在播放），卡顿，延时非常大，甚至一直在转圈圈，处于无法使用的状态。

但是 ZLM A 的 cpu、men、网络都用不满，cpu 50-60%不到，men 占用非常低，网络用nload 看到的是 outing 100+MBit/s 也不高。

现在发现，ZLM_B 上调用 listMedias 会返回空（多刷两次就会出现空的情况），然后调用 close_stream 也会 closed: 0。当然close_stream 接口会调用 listmedia 相似的逻辑去获取流是否存在的。所以这个逻辑通的，找不到，不 close。那为啥 stream 会不存在呢？

经过一下午的测试，当我同时开几十个（现在是 60个）直播，直播一段时间后，同时请求 close_streams 关闭这些直播时，部分关闭操作是会失效的。返回的结果：
```
2022-12-16 17:09:00.239 D GoldlokMediaServer.exe[18672-event poller 18] WebApi.cpp:250 http api debug |
# request:
GET /index/api/close_streams?secret=045c73f7-bb6b-4889-a715-d9eb2d1825ac&force=1&schema=rtmp&stream=ae21ce73-6a9b-4d52-9800-2d950e667bbf&app=gl_live&vhost=__defaultVhost__
# header:
Host : localhost:8888
User-Agent : akka-http/10.2.7
# content:

# response:
{
        "code" : 0,
        "count_closed" : 0,
        "count_hit" : 1
}


2022-12-16 17:09:00.239 D GoldlokMediaServer.exe[18672-event poller 18] WebApi.cpp:250 http api debug |
# request:
GET /index/api/close_streams?secret=045c73f7-bb6b-4889-a715-d9eb2d1825ac&force=1&schema=rtmp&stream=ae21ce73-6a9b-4d52-9800-2d950e667bbf&app=gl_live&vhost=__defaultVhost__
# header:
Host : localhost:8888
User-Agent : akka-http/10.2.7
# content:

# response:
{
        "code" : 0,
        "count_closed" : 0,
        "count_hit" : 1
}
```

如上日志，stream=ae21ce73-6a9b-4d52-9800-2d950e667bbf 关闭了两次，但是没有一次关闭成功的。

现在不知道那里是瓶颈。

**Comment by xiongguangjie** [comment]
你自定义开发了？？？？我感觉你的url 感觉很乱，ZLM_B:1935/proxy/test?id=x 不管id是多少，ZLM都认为是同一个流，就会复用的

**Comment by TopSpoofer** [comment]
> 你自定义开发了？？？？我感觉你的url 感觉很乱，ZLM_B:1935/proxy/test?id=x 不管id是多少，ZLM都认为是同一个流，就会复用的

没有自定义开发，前两天编译的版本，我其实是因为没有太多的摄像头设备，所以用 ZLM_A 来提供多个流出去而已，因为 ZLM_A 的cpu 比较厉害。

**Comment by TopSpoofer** [comment]
> 你自定义开发了？？？？我感觉你的url 感觉很乱，ZLM_B:1935/proxy/test?id=x 不管id是多少，ZLM都认为是同一个流，就会复用的

但从网络的使用来看，并没有复用，ZLM_A outing 在 100MBit，而 ZLM_B 也是这个数。如果复用，不可能这样的。

**Comment by zhang2349** [comment]
你B写100路hls 写不过来吧

**Comment by TopSpoofer** [comment]
> 你B写100路hls 写不过来吧

暂不清楚，B 的磁盘是 SSD，比较power的笔记本了。

**Comment by xia-chu** [comment]
可以用getThreadsLoad接口看看zlm负载，top命令显示负载是cpu的负载 但是zlm中 如果文件io很重 这种情况下 虽然cpu是空闲的 但是这部分时间是无法做其它工作的 所以看起来top负载低 但是zlm负载高的原因

**Comment by TopSpoofer** [comment]
> 可以用getThreadsLoad接口看看zlm负载，top命令显示负载是cpu的负载 但是zlm中 如果文件io很重 这种情况下 虽然cpu是空闲的 但是这部分时间是无法做其它工作的 所以看起来top负载低 但是zlm负载高的原因

![image](https://user-images.githubusercontent.com/5953930/210471957-846bb420-19f9-44a4-bb6e-e8210fe42371.png)
我这阵子发现是 ZLM_A  中出现很多超时错误：RtmpSession.cpp:33 onError | 1499-202(192.168.2.49:55193) RTMP播放器(__defaultVhost__/proxy/test)断开:end of file,耗时(s):33，如上图。

全文此时我要如何优化 ZLM_A?

**Comment by xia-chu** [comment]
zlm到你播放器间的带宽不足导致 的

**Comment by TopSpoofer** [comment]
> zlm到你播放器间的带宽不足导致 的

是的，换台服务器好了~
