### ISSUE TITLE
[技术咨询] docker 容器内无法顺利推流到rtsp server 

### ISSUE THREAD

**Issue by WangFengtu1996** [ZLMediaKit/ZLMediaKit#2172]
**咨询的功能模块**
- RTSP server部分
**咨询的具体内容和问题**
- 首先，我源码编译该项目启动该服务器 `sudo ./MediaServer -d &`
- 我推原始的流到该服务器上 `ffmpeg -re -i test.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://10.0.20.221/live/test`
![anTtzKgB1X](https://user-images.githubusercontent.com/21277368/208633107-ebc2c625-4b81-4ee6-bfe2-9ebc9e294a15.jpg)
- 然后在宿主机上启动我自己写的gstreamer 推流应用， 可以在server log中看到该服务被顺利的推上去
![Y83cdCBwMP](https://user-images.githubusercontent.com/21277368/208633302-1bca26b4-4c27-4267-b918-4134662d12f8.jpg)
- 但是，在容器中，启动我自己同样的程序，但是我这边没有办法成功tui推山上去，log如下
![CkJJ2XT7jP](https://user-images.githubusercontent.com/21277368/208633440-af7429ec-608f-46da-a6a7-3a91341bfb20.jpg)
 
docker 启动命令 `--net host` 建立了全网卡映射，

 - 您这边测试的话，可以搭建一条pipeline 推流试试。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
请把你的mp4压缩成zip再传到github
