### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by 1328786726** [ZLMediaKit/ZLMediaKit#2173]
**咨询的功能模块**
- openRtpServer TCP被动模式

**咨询的具体内容和问题**
- 上级进行语音推流得时候 上级无法正常进行推流 对方模式为active

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级
![1](https://user-images.githubusercontent.com/56616609/208811017-fa5fd8af-35c4-440b-8b7b-ca5792b41374.png)
![2](https://user-images.githubusercontent.com/56616609/208811076-d27617dd-abe1-45a2-b502-ee0eb04582bf.png)

**Comment by xia-chu** [comment]
让对方法udp吧 对方有bug

**Comment by 1328786726** [comment]
@xia-chu 他语音这个 搞不了udp 改了几个地方的tcp->udp 进行语音广播的时候都还是发的tcp 自平台测试倒是没问题 livegbs作为下级平台也没问题 唯独作为上级平台有问题 唉

**Comment by xia-chu** [comment]
你的意思他们tcp推流给其他平台就没什么问题吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 1328786726 ***@***.***&gt;
发送时间: 2022年12月21日 15:11
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (Issue #2173)





 
@xia-chu 他语音这个 搞不了udp 改了几个地方的tcp-&gt;udp 进行语音广播的时候都还是发的tcp 自平台测试倒是没问题 livegbs作为下级平台也没问题 唯独作为上级平台有问题 唉

**Comment by 1328786726** [comment]
@xia-chu 没有测试过,只试过他们自己平台tcp互推没有问题.   没有条件进行更多的测试.

**Comment by xia-chu** [comment]
你问下他们 有32KB的rtp包吗？

**Comment by 1328786726** [comment]
@xia-chu 他们客服还没有同意进群,技术也没有回复.

**Comment by 1328786726** [comment]
@xia-chu 之前问的东西他们也没有回复,如果回复了 我问问看.

**Comment by 1328786726** [comment]
他们不支持 解析不了

**Comment by 1328786726** [comment]
@xia-chu 他们不支持 解析不了

**Comment by xia-chu** [comment]
你说 我这边收到32KB的rtp包了 如果不是它们设置的这么长 就是他们tcp发送缓冲区溢出了 导致tcp上下文错乱了

**Comment by 1328786726** [comment]
@xia-chu livegbs那边不在意这个...表示没时间处理... 只能这样了 谢谢大佬

**Comment by xia-chu** [comment]
你把配置文件 `rtp.rtpMaxSize` 改成64试试 如果还不行 就是他们bug

**Comment by 1328786726** [comment]
@xia-chu 好的 谢谢
