### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by yflisa** [ZLMediaKit/ZLMediaKit#2174]
- 国标接入，使用webrtc在web端浏览 ，是否支持该功能

- 使用 wvp接入国标摄像头 或者 使用post的openRtpServer接口获取到端口号后使用ffmpeg推流，在web端使用 http://127.0.0.1/webrtc 拉流失败，看到相关的wiki没有讲述这部分内容。看到MediaServer后台打印看到可以转的流是rtmp/rtsp/ts/hls，这部分看到在wiki上面有

**Comment by xia-chu** [comment]
wiki url规则篇看一遍
