### ISSUE TITLE
[技术咨询]addStreamPusherProxy接口推流业务过程链路异常是否有触发的hook回调

### ISSUE THREAD

**Issue by huliyan** [ZLMediaKit/ZLMediaKit#2175]
**咨询的功能模块**
- addStreamPusherProxy接口

**咨询的具体内容和问题**
- addStreamPusherProxy接口推流业务过程链路异常是否有触发的hook回调，或者通过什么接口能获取到推流业务异常

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
没有
