### ISSUE TITLE
[技术咨询]RTMP推流时怎么根据传输层动态调节编码器的码率呢？

### ISSUE THREAD

**Issue by zhangmGoL** [ZLMediaKit/ZLMediaKit#2176]
**咨询的功能模块**
- RTMP推流

**咨询的具体内容和问题**
- 怎么根据网络情况动态调节编码器的码率呢，有没有能提供传输层发送情况的回调?现在的推流是否支持这个特性?

**Comment by xia-chu** [comment]
你是说zlm的MediaPusher接口吗？

**Comment by zhangmGoL** [comment]
是的，我看了下RTMP Pusher的源代码，没发现哪里可以做这个功能. 通过网络情况给到编码器自适应调节码率是比较常用的功能．

**Comment by xia-chu** [comment]
> 是的，我看了下RTMP Pusher的源代码，没发现哪里可以做这个功能. 通过网络情况给到编码器自适应调节码率是比较常用的功能．

这个没太考虑到 一般通过判断tcp发送缓存列队长度来做控制 如果列队太长 应该降低码率

**Comment by xia-chu** [comment]
可以根据Socket::getSendSpeed() 接口获取发送网速
