### ISSUE TITLE
[BUG]: BUG 现象描述

### ISSUE THREAD

**Issue by wobenfanchen** [ZLMediaKit/ZLMediaKit#2177]
![image](https://user-images.githubusercontent.com/39585737/209090780-bab4c1e5-29a2-49f8-9718-f1f819931cfb.png)

就是推流进来的流，在日志当中没有看到注册成功的日志，一直看到流断开，怎么解决呢

**Comment by xia-chu** [comment]
请重新按照模板规范重新提issue

**Comment by xiongguangjie** [comment]
这个rtmp 流不标准
