### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by jellygithub** [ZLMediaKit/ZLMediaKit#2182]
**咨询的功能模块**
- RTMP推流

**咨询的具体内容和问题**
- RTMP推流报错具体报错

RtmpSession.cpp 33 OnError | 5700-62（）RTMP推流器（_defalutVhost_/live/WK）断开:can only set metadata 耗时

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
什么推流器？ rtmp抓个包我分析下

**Comment by jellygithub** [comment]
服务器监听的端口麻烦大佬看下
链接：https://pan.baidu.com/s/1DrQ8YIyv7tO5gU84pW8Jhg 
提取码：ops0

**Comment by jellygithub** [comment]
onMetaData的协议规范问题
