### ISSUE TITLE
[技术咨询]docker部署的服务，前端页面访问视频地址会有跨域问题

### ISSUE THREAD

**Issue by wdzhao3** [ZLMediaKit/ZLMediaKit#2185]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
因为有比较多的部署，我想在服务端解决这个跨域，请问能进入docker修改，来设置跨域吗

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiangshengjye** [comment]
zlmediakit支持跨域的，你自己的HTTP服务器不支持跨域导致的问题

**Comment by j10220428** [comment]
看下是否打开了8000端口
