### ISSUE TITLE
[BUG]: HLS流没有音频，拉取对应的rtsp有音频

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2186]
### 现象描述

海康相机国标方式推流到媒体服务器，使能服务器转hls、rtsp协议，发现hls没有音频 ，rtsp流有音频

### 如何复现?
正常相机RTP国标推流  推流包含视频和音频数据，vlc拉取视频播放查看是否有音频，查看hls流没有音频

### 相关日志或截图
hls拉流
<img width="290" alt="5" src="https://user-images.githubusercontent.com/59160162/210731715-cb2316b3-29b8-4a93-9b5d-a09b99338ad6.png">

rtsp拉流
<img width="297" alt="2" src="https://user-images.githubusercontent.com/59160162/210731743-5fbf335f-e0aa-4fa5-bf56-93261712f93f.png">

日志截图
<img width="623" alt="3" src="https://user-images.githubusercontent.com/59160162/210731008-cebda2a5-4e96-4d0d-94c4-1e745add0943.png">

### 配置
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[protocol]
modify_stamp=0
enable_audio=1
add_mute_audio=1
continue_push_ms=15000
enable_hls=1
enable_mp4=0
enable_rtsp=1
enable_rtmp=1
enable_ts=0
enable_fmp4=0
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
hls_save_path=./www
hls_demand=0
rtsp_demand=0
rtmp_demand=0
ts_demand=1
fmp4_demand=1

[general]
enableVhost=0
flowThreshold=1024
maxStreamWaitMS=15000
streamNoneReaderDelayMS=20000
resetWhenRePlay=1
mergeWriteMS=0
mediaServerId=media-server00
wait_track_ready_ms=10000
wait_add_track_ms=3000
unready_frame_cache=100

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
filePath=./www
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=30.000000
enable=1
on_flow_report=
on_http_access=http://127.0.0.1:8090/index/hook/on_http_access
on_play=http://127.0.0.1:8090/index/hook/on_play
on_publish=http://127.0.0.1:8090/index/hook/on_publish
on_record_mp4=http://127.0.0.1:8090/index/hook/on_record_mp4
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=
on_server_keepalive=
on_server_started=http://127.0.0.1:8090/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://127.0.0.1:8090/index/hook/on_stream_changed
on_stream_none_reader=http://127.0.0.1:8090/index/hook/on_stream_none_reader
on_stream_not_found=http://127.0.0.1:8090/index/hook/on_stream_not_found
retry=1
retry_delay=3.000000
timeoutSec=10

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:a16b6cbc,branch:master,build time:Mar 24 2022 11:08:20)</center></body></html>
port=18081
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fastStart=0
fileBufSize=65536
filePath=./www
fileRepeat=0
fileSecond=3600
mp4_as_player=0
sampleMS=500

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
timeoutSec=15
ts_pt=33

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

**Comment by xiongguangjie** [comment]
ts 封装不支持 g711音频编码

**Comment by xiongguangjie** [comment]
检查下音频的编码格式

**Comment by zhang-chuanfeng** [comment]
ok
