### ISSUE TITLE
[技术咨询]RTMP推流到ZLM，ZLM怎么转码成HLS

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2188]
**咨询的具体内容和问题**
作者，你好，请教一 下啊：目前在研究ZLM的源码，但弄不清楚RTMP推流到ZLM，ZLM怎么转码成HLS的，希望能给予一些相关的代码流程，及相应的源码文件，主要的函数等。谢谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by li-yueping** [comment]
作者您好，当前rtmp推流后，只能看到rtmp流注册，没有其它协议的url吗？
