### ISSUE TITLE
[BUG]: rtsp流无法截图

### ISSUE THREAD

**Issue by itzhoujun** [ZLMediaKit/ZLMediaKit#2196]
### 现象描述
使用以下地址无法获取截图

```
http://ip:port/index/api/getSnap?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&url=rtsp://xxxxx&timeout_sec=30&expire_sec=1
```
问题同：https://github.com/ZLMediaKit/ZLMediaKit/issues/1583
### 如何解决

问题已找到，应该是默认的snap命令有问题，将 -t 0.001参数挪到前面即可。修改后如下：
```
snap=%s -t 0.001 -i %s -y -f mjpeg %s
```

建议夏老哥修改下默认配置，避免其他朋友遇到相同问题

### 建议
顺带提一个建议：当截图失败时，建议不要返回http 200，否则客户端（非浏览器）无法知道是否截图成功

**Comment by itzhoujun** [comment]
问题同：https://github.com/ZLMediaKit/ZLMediaKit/issues/1583

**Comment by xia-chu** [comment]
这个要修改配置文件截图FFmpeg模板 加上-rtsp_transport tcp
