### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by mayunxi** [ZLMediaKit/ZLMediaKit#2198]
**咨询的功能模块**
国标中使用startSendRtp接口

**咨询的具体内容和问题**

海康相机25帧，开启smart264智能编码，可能会存在250fps才一个I帧，也就是10s秒一个I帧，导致首播时间过长的问题。具体原因为：
请求摄像机发rtp流到zlmedia后，由于相机发送的首帧为I帧，等待注册zlmeida成功后，使用startSendRtp，这时发送的就不一定是I帧，导致首播时间可能会过长。

所以怎么解决这个问题，可不可以startSendRtp先等待，一有流了马上发送？修改源码使用MediaSource::findAsync？

**Comment by xia-chu** [comment]
对 可以使用MediaSource::findAsync

**Comment by mayunxi** [comment]
我打算缓存一个I帧，然后startSendRtp时，发送这个I帧

**Comment by mayunxi** [comment]
> 我打算缓存一个I帧，然后startSendRtp时，发送这个I帧
