### ISSUE TITLE
[技术咨询] docker run 后 http 公网无法访问的问题，防火墙策略己开启

### ISSUE THREAD

**Issue by lyongdee** [ZLMediaKit/ZLMediaKit#2200]
**咨询的功能模块**
- docker run 后 http 公网无法访问的问题，防火墙策略己开启

**咨询的具体内容和问题**
- Windows 系统，docker run -id -p 1935:1935 -p 8080:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master
- 本地访问正常 192.168.1.10:8080，生产环境 http 公网地址访问不通，己开启防火墙端口映射策略(其它端口映射访问正常)。
![image](https://user-images.githubusercontent.com/369124/212339033-a824c552-fef1-4224-af72-1a00145f2cf5.png)

**Comment by lyongdee** [comment]
config.ini 还需要啥配置吗

**Comment by xia-chu** [comment]
按照你的描述 显然不是docker和配置文件的问题 你需要配置下安全组

**Comment by 18290888765** [comment]
博主，我也遇到了相同的问题，请问您解决了吗？
