### ISSUE TITLE
GB28181语音广播-[技术咨询]

### ISSUE THREAD

**Issue by liangxl2018** [ZLMediaKit/ZLMediaKit#2201]
老师，我进行语音对讲时，完整的通信流程如下图片，但设备就是没声音输出。可以帮忙分析下什么原因吗？
一、webrtc推送音频流至zlm
![1](https://user-images.githubusercontent.com/45931895/212522329-3a15513e-5386-44e1-b9ac-4c65c8e57cbb.PNG)
二、设备请求INVITE
![2](https://user-images.githubusercontent.com/45931895/212522332-7854a31b-9a11-4b5a-acee-32880720d5ac.PNG)
三、响应设备INVITE
![3](https://user-images.githubusercontent.com/45931895/212522338-91610c31-547c-42cf-ace2-1bcb988899c6.PNG)
四、设备ACK
![4](https://user-images.githubusercontent.com/45931895/212522344-38bba7c5-8329-46ee-9212-ae8dc6da6eb5.PNG)
五、zlm推送rtp
![5](https://user-images.githubusercontent.com/45931895/212522347-e7092cea-1150-41af-b4d2-1a14a8ed6482.PNG)
六、向设备发送rpt流抓包
![6](https://user-images.githubusercontent.com/45931895/212522351-e0960817-cdbc-4fae-ac25-d4e77646dbe6.PNG)

**Comment by xiongguangjie** [comment]
你指定了recvonly 呀

**Comment by xiongguangjie** [comment]
你好好学习下sdp的offer answer 模型，关于 sendonly recvonly sendrecv 是什么意思

**Comment by liangxl2018** [comment]
> 你好好学习下sdp的offer answer 模型，关于 sendonly recvonly sendrecv 是什么意思

1、recvonly是摄像头向sip服务发出的INVITE请求的sdp信息。对摄像头来说是接收音频流。
2、sip服务器向摄像头回应INVITE时,是sendonly。表示zlm向摄像头推送rtp流。
3、所有在这里，是没有问题的。

**Comment by liangxl2018** [comment]
> 你指定了recvonly 呀

视频点播、回看没有问题。我这里是在调试语音广播(语音对讲)

**Comment by xiongguangjie** [comment]
> > 你好好学习下sdp的offer answer 模型，关于 sendonly recvonly sendrecv 是什么意思
> 
> 1、recvonly是摄像头向sip服务发出的INVITE请求的sdp信息。对摄像头来说是接收音频流。 2、sip服务器向摄像头回应INVITE时,是sendonly。表示zlm向摄像头推送rtp流。 3、所有在这里，还请老师指教

sendonly 之类的都是对于本身而言，你搞反了

**Comment by xiongguangjie** [comment]
你的网络情况是什么

**Comment by xiongguangjie** [comment]
语音广播好像不支持ps格式吧

**Comment by xiongguangjie** [comment]
![8U5DCQGTDTXH%X6GZ5TT9C5](https://user-images.githubusercontent.com/19631632/212536154-b7b192f0-6464-4092-b0dd-90345ebe84d8.png)

**Comment by vowor** [comment]
startSendRtp接口已经新增参数recv_stream_id, 用于指定接收流的流id。
使用方法如下：

1、用webrtc推流给zlmediakit.
2、sip控制设备双向对讲。
3、调用zlmediakit的startSendRtp接口(指定recv_stream_id参数)，把webrtc推流的这路流再推给设备。
4、设备发送rtp给zlmediaikit startSendRtp接口创建的端口(也就是用于发送和接收rtp的端口)。
5、zlmediakit收到设备发送的rtp，生成新的一路流，流id为recv_stream_id参数指定。
6、使用webrtc协议或其他协议播放rtp/recv_stream_id这路流。
本方案全程不需要调用openRtpServer接口。

上面是作者的回复，但是目前我也还没有调试通，你可以参考下，如果调通了把流程发下噢

**Comment by liangxl2018** [comment]
> ![8U5DCQGTDTXH%X6GZ5TT9C5](https://user-images.githubusercontent.com/19631632/212536154-b7b192f0-6464-4092-b0dd-90345ebe84d8.png)



> ![8U5DCQGTDTXH%X6GZ5TT9C5](https://user-images.githubusercontent.com/19631632/212536154-b7b192f0-6464-4092-b0dd-90345ebe84d8.png)

![1111](https://user-images.githubusercontent.com/45931895/212584911-0ce435d0-e6ef-491d-bbfd-0fdb89960bb6.png)
这个是摄像机的INVITE,里面指示可以接收PS和PCM。如果推送PCM，但webrtc推送给zlm的又是PCMU或PCMA且采样率是8000，如果可以调整推送PCM且采样率为16000,设备大概率会响(目前按推送PCMU/8000到摄像机,摄像机是有尖叫声)

**Comment by liangxl2018** [comment]
> recv_stream_id

可以。如果调试通了，互向分享下。

**Comment by xiongguangjie** [comment]
这个语音广播我也没调试过，但是听别人说，不能用PS流，这个要实测为准，rtc 只支持 g711 8khz的采样率，但是ZLM start_send_rtp 发送音频流时，是可以选择发送es还是ps流的，详细的看wiki

**Comment by vowor** [comment]
兄弟，  你的流程是啥样的额？   我这边调试   摄像头一点反应都没有   
我的流程是
1. 前端WebRTC推送音频流到ZLM
2. 请求/index/api/startSendRtp接口(指定recv_stream_id参数)，把webrtc推流的这路流再推给设备。
但是设备一点反应没有，我的请求参数是
{
    "secret": "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
    "vhost": "__defaultVhost__",
    "app": "rtp",
    "stream": "34020000001320000001_34020000001370000001",
    "ssrc": "1545201657 ",
    "dst_url": "10.10.40.231",
    "dst_port": "5060",
    "is_udp": "1",
    "pt": "8",
    "use_ps": "0",
    "only_audio": "1",
    "recv_stream_id": "34020000001320000001_34020000001370000002"
}
我用另外一个浏览器拉流34020000001320000001_34020000001370000002是有声音的

**Comment by liangxl2018** [comment]
> 兄弟， 你的流程是啥样的额？ 我这边调试 摄像头一点反应都没有 我的流程是
> 
> 1. 前端WebRTC推送音频流到ZLM
> 2. 请求/index/api/startSendRtp接口(指定recv_stream_id参数)，把webrtc推流的这路流再推给设备。
>    但是设备一点反应没有，我的请求参数是
>    {
>    "secret": "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
>    "vhost": "**defaultVhost**",
>    "app": "rtp",
>    "stream": "34020000001320000001_34020000001370000001",
>    "ssrc": "1545201657 ",
>    "dst_url": "10.10.40.231",
>    "dst_port": "5060",
>    "is_udp": "1",
>    "pt": "8",
>    "use_ps": "0",
>    "only_audio": "1",
>    "recv_stream_id": "34020000001320000001_34020000001370000002"
>    }
>    我用另外一个浏览器拉流34020000001320000001_34020000001370000002是有声音的

我的流程就是那几张图片所示

**Comment by huyji-000** [comment]
![image](https://user-images.githubusercontent.com/80040213/212855123-51c10b51-1354-430c-b572-2e1637a3a75f.png)
要按照设备给的标准去推流
你这个设备编码格式-1，没有搞懂是啥意思

另外这个f=这行，invite响应也要带上

**Comment by xia-chu** [comment]
我感觉这个问题的本质是 怎么把pcm推送给设备。看你们的描述，设备只支持播放pcm的音频，但是webrtc却不支持pcm的音频，所以目前还没办法通过webrtc推送音频给zlmediakit然后推给配备

**Comment by xia-chu** [comment]
> ![image](https://user-images.githubusercontent.com/80040213/212855123-51c10b51-1354-430c-b572-2e1637a3a75f.png)
> 
> 要按照设备给的标准去推流
> 
> 你这个设备编码格式-1，没有搞懂是啥意思
> 
> 
> 
> 另外这个f=这行，invite响应也要带上

如果能控制设备接受g711就好了

**Comment by huyji-000** [comment]
> 如果能控制设备接受g711就好了

确实是，我用一款海康设备实现过对讲
他INVITE要求的码流格式是这样的：
a=rtpmap:8 PCMA/8000
f=v/////a/1/8/1

webrtc音频直接就能用

**Comment by xia-chu** [comment]
> /

也就是说 可以通过sdp f字段控制设备使用g711对讲的

**Comment by liangxl2018** [comment]
感谢各位老师的指导。

**Comment by vowor** [comment]
兄弟，你调试通了吗？   能不能协助下我呀？

**Comment by liangxl2018** [comment]
> 兄弟，你调试通了吗？ 能不能协助下我呀？

可以。可以联系我qq。278540660。

**Comment by criver31** [comment]
> > 兄弟，你调试通了吗？ 能不能协助下我呀？
> 
> 可以。可以联系我qq。278540660。

你好，qq搜不到，可以请教一下你关于这块吗

**Comment by vowor** [comment]
参考我的这个 #2217  里面的大哥提供的东西可以实现语音对讲

**Comment by criver31** [comment]
> 参考我的这个 #2217 里面的大哥提供的东西可以实现语音对讲

感谢，我去学习一下

**Comment by weijunnan1992** [comment]
> 参考我的这个 #2217 里面的大哥提供的东西可以实现语音对讲

@vowor 大佬能帮看一下，不知道哪里的问题
