### ISSUE TITLE
[技术咨询] webrtc静态页面转rtmp，拉流很慢

### ISSUE THREAD

**Issue by funbinary** [ZLMediaKit/ZLMediaKit#2204]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

webrtc转rtmp
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
webrtc推流如果推动态视频流(视频，在线秒表、gif)使用ffplay拉取rtmp比较快(1-2秒)，静态(文档，首页之类)就很久才能打开画面(5-50秒)
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个可能根gop大小有关 目前zlmediakit会每隔2秒发送pli给浏览器让其生成关键帧。如果浏览器不生成关键帧，那么就无法秒开
