### ISSUE TITLE
[技术咨询] 使用addStreamProxy接口添加rtsp/rtmp/hls拉流代理的配置, 在服务器重启后就无法使用?

### ISSUE THREAD

**Issue by jassonc** [ZLMediaKit/ZLMediaKit#2205]
**咨询的功能模块**
- 配置保存问题

**咨询的具体内容和问题**
- 我使用docker运行服务器, 然后使用addStreamProxy接口添加rtsp/rtmp/hls拉流代理的配置, 在docker 重启后就无法在使用先前的配置, 使用getMediaList也是没有内容, 请问这是ZLMediaKit的特性吗？这部份的逻辑需要由自己来实现？

**Comment by xia-chu** [comment]
是的 zlmediakit的api绝大部分不支持持久化的 一般都是操作内存 所以重启后就丢失了 你需要自己结合数据库完成持久话
