### ISSUE TITLE
[技术咨询]显卡Video Decode一直是0，正常吗？

### ISSUE THREAD

**Issue by lyongdee** [ZLMediaKit/ZLMediaKit#2208]
**咨询的功能模块**
![1673949222119](https://user-images.githubusercontent.com/369124/212866661-89a2f5c8-950d-47c6-b23f-a9dc000d036d.png)

**咨询的具体内容和问题**
- Docker 环境，有一个比较奇怪的地方，GPU 的 Video Decode 一直是0，正常吗？

**Comment by xia-chu** [comment]
正常 zlmediakit一般不转码
