### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by quxiaohuixiangxuexue** [ZLMediaKit/ZLMediaKit#2210]
**咨询的功能模块**
- ZLMediaKit的WebRTC功能模块

**咨询的具体内容和问题**
- 您好，我打算封装WebRTC源码提供的PeerConnection Demo作为WebRTC客户端；ZLMediaKit作为WebRTC媒体服务，部署在公网，并且UDP端口是对客户端可见的；另外WebRTC信令服务由自己开发，通过Resetful API中的/index/api/webrtc接口交换SDP，这种方案可行吗？如果可行的话，WebRTC收集的Candidate怎么处理呢？

**Comment by xia-chu** [comment]
zlmediakit定位是sfu，需要部署在公网上，所以是不需要知道客户端的icecand地址的
