### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by yanshanshu** [ZLMediaKit/ZLMediaKit#2212]
**咨询的功能模块**
- 暂时没有找到Android如何进行集成推流。

**咨询的具体内容和问题**
- 我获取到原始视频流数据，但是Android如何集成推流不清楚，没有看到对应的集成文档，不知道是否支持？
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
android 的视频采集与编码应该是没有的，ZLM的android 工程没有android 视频采集与编码的部分，你可以参考这个工程https://github.com/begeekmyfriend/yasea

**Comment by yanshanshu** [comment]
不需要采集和解码，我自己能获取到源码流，现在不知道安卓怎么推流到服务器

**Comment by yanshanshu** [comment]
> android 的视频采集与编码应该是没有的，ZLM的android 工程没有android 视频采集与编码的部分，你可以参考这个工程https://github.com/begeekmyfriend/yasea

不需要采集和解码，我自己能获取到源码流，现在不知道安卓怎么推流到服务器

**Comment by xiongguangjie** [comment]
这个要参考C的API接口封装 jni 才能做到
