### ISSUE TITLE
zlm启动时,无法指定ssl证书

### ISSUE THREAD

**Issue by mml-stepom** [ZLMediaKit/ZLMediaKit#2214]
<img width="1077" alt="Snipaste_2023-01-31_09-33-23" src="https://user-images.githubusercontent.com/68891889/215639216-3b00bcd5-3804-4934-ab30-10728ecd084b.png">

**Comment by xiongguangjie** [comment]
命令选项，指定 -c

**Comment by mml-stepom** [comment]
-c 指定配置文件，感觉这个和配置文件应该没有关系吧
下图是在其他机器上启动时，没有指定任何参数的，会指定一个默认的证书
<img width="899" alt="Snipaste_2023-01-31_11-08-53" src="https://user-images.githubusercontent.com/68891889/215653108-36cbb926-ea1c-4060-9f0c-8173bc253813.png">
，

**Comment by xia-chu** [comment]
是不是你编译zlm没开启openssl相关功能

**Comment by mml-stepom** [comment]
编译的时候，怎么主动开启？
没找到，哭！！！

**Comment by xia-chu** [comment]
你好好看看wiki吧

**Comment by mml-stepom** [comment]
升级 openssl 版本至1.1.1，重新编译后问题已经解决（自带的版本过低）
谢谢二位道友
