### ISSUE TITLE
[技术咨询] 对讲模式一个peer 是否支持sendreceive

### ISSUE THREAD

**Issue by wangpeng1** [ZLMediaKit/ZLMediaKit#2219]
你好，目前srs，mediasoup，都是支持会议sfu 模式，创建一个peer  sdp协商可以是send 也可以receive，但是没有sendreceive。这主要是因为会议本身结构影响。但是有个场景是多人对讲，一个人说话，其他人听，当这个人说完其他人说，另外的人听，虽然类似会议主持人模式，但是不想用srs，mediasoup形式，因为一个peer结束，send和receive 都结束了，而且一个人对讲如果建立两个peer，在网络不好的情况下，建立失败或者延迟的几率变大。 所以我想知道此工程 是采用什么方式解决我的问题的。

**Comment by xia-chu** [comment]
你在说WebRtc的sendreceive吗？ 其实支持的， webrtc测试页面有个echo模式 就是sendreceive模式
