### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by xingulun** [ZLMediaKit/ZLMediaKit#2220]
录制的mp4文件一直处于隐藏状态

使用docker部署的ZLMediaKit，重启了容器之后，mp4录制不正常了。在目录下产生了隐藏的.mp4文件，当推流关闭后，隐藏的.map4文件没有改为正常文件。手动将.13-58-14.mp4 改为 13-58-14.mp4下载下来也无法正常播放。

**Comment by xiongguangjie** [comment]
.开头的文件是ZLM正在操作的文件，不要修改，程序重启会导致文件不可用

**Comment by xingulun** [comment]
> .开头的文件是ZLM正在操作的文件，不要修改，程序重启会导致文件不可用

你好，推流程序已经停止了，我发现文件还是隐藏状态，想着恢复下数据，就修改了文明名称，试试能不能正常播放。

**Comment by xingulun** [comment]
很奇怪，我将操作系统重启后，在启动zlm docker容器，录制mp4正常了，但是原因还是不知道哎。另外之前隐藏的mp4是有内容的，如何才能修复为正常的mp4文件呢。

**Comment by xia-chu** [comment]
不要强制关闭zlm就不会有这个问题了

**Comment by xingulun** [comment]
> 不要强制关闭zlm就不会有这个问题了
您好，请问下，隐藏文件能否手动修复为正常的mp4文件嘛

**Comment by xingulun** [comment]
> 不要强制关闭zlm就不会有这个问题了



您好，请问下，隐藏文件能否手动修复为正常的mp4文件嘛

**Comment by xia-chu** [comment]
非fmp4方式不行 可以把zlm的mp4录制改成fmp4模式 但是这样对web点播seek操作不友好。
mp4就是因为有丰富的索引信息所以适合网络点播。
