### ISSUE TITLE
[技术咨询]How to get continuous stream statistics

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#2221]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
API/HOOK

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

I am using API "getMediaList" to get all streams info (with interval 10 seconds) but sometime MediaServer cannot reply or reply with incomplete json content. 
 I also tried "on_flow_report" hook event, but cannot get any info.
Can you add a new hook, ex: "on_stream_statistic", report every 10s, include some info: frame rate, bitrate, isRecording, codec, resolution ... ?

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
How many streams when you visit `getMediaList` api? 
If `getMediaList`  do not reply or reply with incomplete json content, it is a bug, we need fix it.

**Comment by pubpy2015** [comment]
~ 300 streams, it happens randomly, but usually appears after running about 1-2 days.

**Comment by xia-chu** [comment]
300 streams, 1500 `MediaSource`,  It may be that the json serialization time is too long, which causes the response timeout of `getMediaList`.

**Comment by pubpy2015** [comment]
Yes,
Can you create other API or Hook event with some basic stream info (frame rate, bitrate, isRecording, codec, resolution ... )?

**Comment by xia-chu** [comment]
Whey do you not pick some schma such as `rtsp` ?

**Comment by xia-chu** [comment]
And you can disable some protocol such as `ts/hls/fmp4/rtmp`

**Comment by pubpy2015** [comment]
> Whey do you not pick some schema such as `rtsp` ?

Yes, I've used with "schema=rtsp"

**Comment by pubpy2015** [comment]
I am disable audio and some info as: originSock, originUrl,... for deacrease size of json content but this problem still exists.
Sometime only get response:
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Lengt
```
Seem this problem only appears after running about ~ 2 days.

**Comment by xia-chu** [comment]
How is zlmediakit's log?

**Comment by pubpy2015** [comment]
Because i am setting log level = Error so the log file is empty.

**Comment by xia-chu** [comment]
> Because i am setting log level = Error so the log file is empty.
How is http client log ?  Wait timeout?

**Comment by pubpy2015** [comment]
Timeout = 15000 miliseconds
Only get this: 
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Lengt
```

**Comment by xia-chu** [comment]
We need find out which side send `tcp fin packet` first

**Comment by xia-chu** [comment]
And you can increase  timeout arguments in your http request side.

**Comment by pubpy2015** [comment]
Thanks,

After increase timeout + disable some infomation not necessary (for me, in response of getMediaList API), i dont receive any incomplete json message.

I am manual record stream by call API startRecord/stopRecord, but sometime get incorect response like bellow:
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Lengt
```
How to debug this?

**Comment by xia-chu** [comment]
startRecord/stopRecord is a short request api, they usually respond very quickly.
I wonder if you recorded too many files, which led to the bottleneck of disk io ？
