### ISSUE TITLE
[BUG]: 录制MP4大小一直为0

### ISSUE THREAD

**Issue by taojishou** [ZLMediaKit/ZLMediaKit#2222]
rtmp推流H265+aac hls没有正常输出，录制mp4 也一直0

Input #0, flv, from 'rtmp:/127.0.0.1/live/cctv1':
  Metadata:
    encoder         : Lavf58.49.100
    server          : ZLMediaKit(git hash:878f1a5/2023-02-02T11:59:40+08:00,branch:master,build time:2023-02-04T10:16:03)
  Duration: 00:00:00.00, start: 8810.998000, bitrate: N/A
    Stream #0:0: Data: none
    Stream #0:1: Audio: aac (LC), 48000 Hz, 5.1, fltp, 488 kb/s
    Stream #0:2: Video: h264 (High), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tb

录制文件大小也一直是0不增长
-rw-r--r--. 1 root root 0 2月   4 10:41 cctv1/2023-02-04/.10-41-36.mp4
rtmp rtsp 正常 hls fmp4 和录制不正常
f
[cctv1.live.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/10607727/cctv1.live.zip)

**Comment by xiongguangjie** [comment]
正在录制，等待切片

**Comment by taojishou** [comment]
一直是0，其他录制的是有大小变化了

**Comment by xiongguangjie** [comment]
提交 a52e9d6ba832ff74d3c09d30a7937b79b7d69b48 修复了此bug
