### ISSUE TITLE
[技术咨询]国标相关

### ISSUE THREAD

**Issue by ketaxiang** [ZLMediaKit/ZLMediaKit#2224]
**咨询的功能模块**
- 国标相关

**咨询的具体内容和问题**
- 部署了wvp+zlm作为上级接入下级视频平台；在录像回放时，调用了暂停，过了一段时间30秒左右，收到了视频平台发来的bye消息；想请教一下是什么原因。
- 在录像回放时，遇到下级平台自定义ssrc的情况，这个时候需要修正ssrc，当前做法是先closeRtpServer，然后使用原端口重新openRtpServer，但是有时候会报端口在使用中的情况，在两接口调用中间加了一个200ms延迟后暂未遇到问题，请教一下是否有更妥善的解决方案。

**Comment by xia-chu** [comment]
`视频平台发来的bye消息` 这个问题应该在wvp项目上提issue，恕我无法答复。
你没必要先closeRtpServer再openRtpServer吧？你不用指定ssrc了现在，zlm现在天然过滤多余的推流了

**Comment by ketaxiang** [comment]
谢谢。因为不知道哪里的原因，两边都问了下。
我猜测是否与保活机制有关，暂停后是调用了pauseRtpCheck，是否有影响？
另外你说的不用指定ssrc我不太理解，openRtpServer如果不提供stream_id会返回“缺少必要参数”。

**Comment by xia-chu** [comment]
pauseRtpCheck只是zlm不做超时检测了 但是rtp rtcp处理逻辑不暂停的
