### ISSUE TITLE
[技术咨询] 国标推流成功后，通过RTMP协议访问视频流，发现首屏加载时间很长

### ISSUE THREAD

**Issue by Huachao** [ZLMediaKit/ZLMediaKit#2225]
**咨询的功能模块**
- RTMP协议播放国标流首屏时间较长

**咨询的具体内容和问题**
- 国标推流ZLM后按照RTMP协议播放，但是首屏加载时间很长，我用`ffprobe`需要超过10s才能检测出视频流metadata。请问这个一般是什么原因造成的，我该如何排查，谢谢、
<img width="852" alt="image" src="https://user-images.githubusercontent.com/2796177/216930616-17c90ee0-9311-4dc5-b36b-c8484d884143.png">
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/2796177/216930758-aef1f2e9-1223-498d-898c-2c07b3cffd5c.png">

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
zlm日志中，媒体注册日志打印没？

**Comment by Huachao** [comment]
@xia-chu 夏楚大佬，不好意思，播放器首屏没有问题，问题只出现在我用`ffprobe`去探测，我发现时间主要卡在下图里的红框的两行中间，不知道您知不知道这大概什么原因，是和设备本身的视频流编码特性有关吗
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/2796177/216938751-f732c288-489c-4008-835e-2bb424e24b6e.png">

**Comment by xia-chu** [comment]
ffprobe -analyzeduration 1000000 试试
