### ISSUE TITLE
[技术咨询] 在另一台机器上用ffplay拉取zlmediakt安装机器上的流是不是要鉴权？

### ISSUE THREAD

**Issue by huguodong** [ZLMediaKit/ZLMediaKit#2228]
**咨询的功能模块**
 推流拉流

**咨询的具体内容和问题**
在另一台机器上用ffplay拉取zlmediakt安装机器上的流是不是要鉴权？
在本地使用使用`ffmpeg -re -i test.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://192.168.1.181/live/test`推流成功
推流之后我本地使用`ffplay -i rtsp://192.168.1.181/live/test`播放报错
![image](https://user-images.githubusercontent.com/12368323/217406872-522401a3-8018-45c8-a169-96b47dd6b9de.png)
ZLMediaKit日志：
![image](https://user-images.githubusercontent.com/12368323/217406950-a4278167-fee4-44d7-a27d-f1400625cfb1.png)
但是如果我是在装了ZLMediaKit的机器上播放就没有问题，一开始怀疑是防火墙问题，但是防火墙都关了，ZLMediaKit用的是docker安装的方式。

**Comment by xia-chu** [comment]
zlmediakit官方docker默认关闭鉴权的

**Comment by xia-chu** [comment]
你需要ffplay rtsp://xxxxx -rtsp_transport tcp

因为rtsp 默认走udp端口传输rtp，你没映射udp端口

**Comment by huguodong** [comment]
> 你需要ffplay rtsp://xxxxx -rtsp_transport tcp
> 
> 因为rtsp 默认走udp端口传输rtp，你没映射udp端口

谢了，我改为本地编译运行就好了
