### ISSUE TITLE
[BUG]: 通过fork FFmpeg进程的方式拉流代理，自定义ffmpeg的cmd，steam名称带“\n”

### ISSUE THREAD

**Issue by huguodong** [ZLMediaKit/ZLMediaKit#2229]
1:统统vim命令编辑config.ini文件自定义ffmpeg命令`h264=%s -rtsp_transport tcp -i %s -vcodec h264 -f rtsp %s`
![image](https://user-images.githubusercontent.com/12368323/217971526-a0320b66-f046-4aa4-9073-74ca0704d392.png)
2.请求addFFmpegSource接口:
`/index/api/addFFmpegSource?src_url=rtsp://192.168.0.47:554/user=admin_password=6QNMIQGe_channel=1_stream=0&dst_url=rtsp://192.168.0.183/live/test&timeout_ms=10000&ffmpeg_cmd_key=ffmpeg.h264`
3.通过getMediaList获取流列表发现stream是"test\n"
![image](https://user-images.githubusercontent.com/12368323/217972056-b93190dd-ef7d-4417-9d18-bafde4beae6f.png)

**Comment by xia-chu** [comment]
我这测试没问题 看看是不是你FFmpeg模板配置的问题？我用的默认模板

**Comment by huguodong** [comment]
> 我这测试没问题 看看是不是你FFmpeg模板配置的问题？我用的默认模板 ![图片](https://user-images.githubusercontent.com/11495632/218358041-598db36e-9ec0-489f-9e36-3873279a97af.png)

我用的模板命令是h264=%s -rtsp_transport tcp -i %s -vcodec h264 -f rtsp %s
转换成命令应该是ffmpeg -rtsp_transport tcp -i "rtsp://192.168.0.1/xxx" -vcodec  h264 -f rtsp  rtsp://192.168.0.183/live/test

**Comment by xia-chu** [comment]
按照你的模板也没问题了

**Comment by huguodong** [comment]
> 按照你的模板也没问题了

我用的vim编辑的config.ini，难道是编辑问题？

**Comment by xia-chu** [comment]
<img width="776" alt="图片" src="https://user-images.githubusercontent.com/11495632/218358815-d44bb2bd-910d-43a8-b254-16426e13013f.png">
<img width="1581" alt="图片" src="https://user-images.githubusercontent.com/11495632/218358860-ed7943b4-e9db-4df2-8f5b-bdecab0959e5.png">
![图片](https://user-images.githubusercontent.com/11495632/218358776-ae9fd32a-03e0-49ce-a8db-c4956cee0c48.png)
![图片](https://user-images.githubusercontent.com/11495632/218358932-aa6a0e0e-bdda-477d-a028-7e4d1807d0ea.png)

**Comment by huguodong** [comment]
![image](https://user-images.githubusercontent.com/12368323/218359676-b190b5da-8e56-48e3-ba99-637354e1a192.png)
wode我的日志多了一行空的

**Comment by huguodong** [comment]
找到原因了，是我的问题，dst_url参数是复制的有个换行但是在postman里看不出来。。。。
![image](https://user-images.githubusercontent.com/12368323/218360469-c4332734-05c7-42da-89bb-3cc0af292f97.png)
![image](https://user-images.githubusercontent.com/12368323/218360484-20f0ddf0-1c37-42a4-bc05-55f533c0503a.png)
