### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by AndiG3** [ZLMediaKit/ZLMediaKit#2237]
是否支持对下接入摄像头至少2个，对上国标GB28181传到第三方平台

**Comment by xiongguangjie** [comment]
这个与ZLM无关，这个主要看gb28181信令服务器

**Comment by AndiG3** [comment]
对下能接入两个摄像头吗，怎么配置，平台就是普通的国标服务器，这面要怎么配置，还是这个代码压根不适用这个模式
