### ISSUE TITLE
[技术咨询] rtp推流时，报already existed

### ISSUE THREAD

**Issue by mayomeng** [ZLMediaKit/ZLMediaKit#2238]
**咨询的功能模块**
- rtp推流

**咨询的具体内容和问题**
- 1.报错原因是多个rtp推流包含相同的ssrc，请问zlm是否是通过src ip, src port来判断是否为同一rtp码流的？
- 2.有没有配置项可以支持不同来源rtp码流包含相同ssrc?
注:之所以会有这种请求是因为zlm前置的负载均衡问题，导致同一设备的码流被不同src port转发给zlm

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
使用openrtpserver 不要使用默认的10000端口

**Comment by xia-chu** [comment]
请更新下zlm 新版本对重复推流有底层过滤逻辑了 可以减轻这个问题

**Comment by mayomeng** [comment]
多谢多谢
