### ISSUE TITLE
[技术咨询]以MP4为源，直接使用startSendRtp向目标发送rtp包，发现rtp包出现错误

### ISSUE THREAD

**Issue by 1739773679** [ZLMediaKit/ZLMediaKit#2239]
**咨询的功能模块**
- rtpsender发送rtp

**咨询的具体内容和问题**

- 以MP4为源，直接使用startSendRtp向目标发送rtp包，发现rtp包出现错误，播放时出现卡顿和花屏的现象，请问是什么原因。
<img width="515" alt="图片1" src="https://user-images.githubusercontent.com/125345447/218675350-c1b912db-08d8-4bc3-9a21-26d44d3000aa.png">
<img width="892" alt="图片2" src="https://user-images.githubusercontent.com/125345447/218675355-89e23d02-4e5b-4fb8-b62b-676a54d696d7.png">

**Comment by xia-chu** [comment]
你用TCP推流 wireshark无法正确识别的 请使用udp推流

**Comment by 1739773679** [comment]
依然出现该问题。我将rtp写到文件使用vlc播放时出现花屏问题。请问是我的使用方法有问题吗。
写入方法：
<img width="589" alt="图片1" src="https://user-images.githubusercontent.com/125345447/218695448-85b9d24f-2174-4ba2-b1d8-dcff2e50e871.png">
vlc日志：
<img width="388" alt="图片2" src="https://user-images.githubusercontent.com/125345447/218695511-49db6709-ac07-4035-819b-ed4949d5d6f4.png">

**Comment by xia-chu** [comment]
提issue都不给star 老兄你这让我们做开源的没积极性啊

**Comment by 1739773679** [comment]
抱歉第一次用issue

**Comment by 1739773679** [comment]
还是不行，依然出现该问题

**Comment by xia-chu** [comment]
那你偏移两个字节 vlc应该是不支持加载rtp文件的

**Comment by 1739773679** [comment]
使用wireshark的插件导出h264文件用vlc播放也播放不了，是不是我方法调用或参数设置有缺漏呢
[log.log](https://github.com/ZLMediaKit/ZLMediaKit/files/10739557/log.log)

**Comment by xia-chu** [comment]
你应该推给zlm本身开验证rtp是否正常 zlm支持接收ps ts es rtp流
