### ISSUE TITLE
[技术咨询]公网nginx负载均衡到内网，多个端口包含同一个ssrc，如何解决？

### ISSUE THREAD

**Issue by ZeeRoLee** [ZLMediaKit/ZLMediaKit#2240]
设备通过nginx负载均衡推流到内网，多个worker造成多个端口，看不了直播
![image](https://user-images.githubusercontent.com/125425972/218922959-c36adc5e-be63-443a-bb12-d7ae3c090abd.png)
我是新手，描述问题可能不到位

**Comment by xia-chu** [comment]
你这是GB28181 tcp模式推流吗？

**Comment by ZeeRoLee** [comment]
> 你这是GB28181 tcp 多端口模式推流吗？ 还是GB28181 udp单端口模式推流？

udp单端口接受rtp码流

**Comment by ZeeRoLee** [comment]
> 

对标的是海康威视摄像头，传输协议是udp，设备通过公网地址由nginx负载到内网接收码流，我用tcpdump抓包显示一堆端口发送过来了，解析后它们包含的是同一个ssrc

**Comment by xia-chu** [comment]
这种只能忽略某些流

**Comment by ZeeRoLee** [comment]
> 



> 这种只能忽略某些流

好的，感谢您的解答
