### ISSUE TITLE
addStreamProxy接口将rtsp转成hls格式进行页面播放，播放时页面提示【您访问的资源不存在！】

### ISSUE THREAD

**Issue by 13280624107** [ZLMediaKit/ZLMediaKit#2242]
页面播放hls报错
![image](https://user-images.githubusercontent.com/125328750/218992038-8c8f6d98-6a3e-49ff-b634-7a7260ca29e0.png)
ZLMediaKit后台报错：
![image](https://user-images.githubusercontent.com/125328750/218991011-28bffdb6-26c7-448e-a714-5f96ce102537.png)

**Comment by xiongguangjie** [comment]
rtsp 源是否正常，vlc与ffplay 是否可以播放?
