### ISSUE TITLE
[BUG]: rtpServer关闭后，端口占用没有释放。

### ISSUE THREAD

**Issue by ynlaodiao0919** [ZLMediaKit/ZLMediaKit#2245]
_on_clearup = [rtp_socket, process, stream_id]() {
        if (rtp_socket) {
            //去除循环引用
            WarnL << "去rtp_socket除循环引用." ;
            rtp_socket->setOnRead(nullptr);
            //清空套接字
            //rtp_socket->setOnFlush(nullptr);
            **/////////////////增加了关闭socket连接代码后，发现还是不能解决端口占用问题。//////////////////
            rtp_socket->closeSock();**
        }
        if (process) {
            //删除rtp处理器
            WarnL << "删除rtp处理器，对应流id为：" << stream_id ;
            RtpSelector::Instance().delProcess(stream_id, process.get());
        }
    };

![image](https://user-images.githubusercontent.com/33620165/219544726-765727e9-0ad6-49ae-8274-7b5d4cae413b.png)
监听进程一直在，无法释放。

**Comment by ynlaodiao0919** [comment]
zlm节点开放端口30000-30500，如果频繁点播开启rtpServer，由于端口无法释放，最后会没有可用端口。

**Comment by xia-chu** [comment]
你要lsof -p看下zlmediakit占用哪些端口

**Comment by xia-chu** [comment]
如果你不知道怎么看zlm占用多少端口了 也可以通过getStatistic接口查看Socket实例个数：
```json
{
    "code": 0,
    "data": {
        "Buffer": 9,
        "BufferLikeString": 1,
        "BufferList": 0,
        "BufferRaw": 8,
        "Frame": 0,
        "FrameImp": 0,
        "MediaSource": 0,
        "MultiMediaSourceMuxer": 0,
        "RtmpPacket": 0,
        "RtpPacket": 0,
        "Socket": 73,
        "TcpClient": 0,
        "TcpServer": 51,
        "TcpSession": 1,
        "UdpServer": 24,
        "UdpSession": 0
    }
}
```

**Comment by xia-chu** [comment]
我本地测试并没有你反馈的问题

**Comment by ynlaodiao0919** [comment]
![image](https://user-images.githubusercontent.com/33620165/219564944-31ab7408-982a-4645-abb5-1a501cc139af.png)

**Comment by ynlaodiao0919** [comment]
![image](https://user-images.githubusercontent.com/33620165/219565288-5fe8e168-ffa8-4e24-8fc7-034f4ac0852f.png)
![image](https://user-images.githubusercontent.com/33620165/219565347-d5cd93a4-e09c-4b06-a8ad-bd00c5ab3bcd.png)

**Comment by ynlaodiao0919** [comment]
> 如果你不知道怎么看zlm占用多少端口了 也可以通过getStatistic接口查看Socket实例个数：
> 
> ```json
> {
>     "code": 0,
>     "data": {
>         "Buffer": 9,
>         "BufferLikeString": 1,
>         "BufferList": 0,
>         "BufferRaw": 8,
>         "Frame": 0,
>         "FrameImp": 0,
>         "MediaSource": 0,
>         "MultiMediaSourceMuxer": 0,
>         "RtmpPacket": 0,
>         "RtpPacket": 0,
>         "Socket": 73,
>         "TcpClient": 0,
>         "TcpServer": 51,
>         "TcpSession": 1,
>         "UdpServer": 24,
>         "UdpSession": 0
>     }
> }
> ```
> 
> 另外，zlm在回收端口时 也会打印日志：
> 
> ```shell
> 2023-02-17 14:11:43.574 I [MediaServer] [24441-event poller 0] TcpServer.cpp:49 ~TcpServer | Close tcp server [::]: 30000
> 2023-02-17 14:11:43.577 I [MediaServer] [24441-event poller 0] Rtsp.cpp:402 operator() | return port to pool:30000-30001
> ```

{
    "code": 0,
    "data": {
        "Buffer": 42,
        "BufferLikeString": 2,
        "BufferList": 0,
        "BufferRaw": 40,
        "Frame": 0,
        "FrameImp": 0,
        "MediaSource": 0,
        "MultiMediaSourceMuxer": 0,
        "RtmpPacket": 0,
        "RtpPacket": 0,
        "Socket": 285,
        "TcpClient": 1,
        "TcpServer": 203,
        "TcpSession": 1,
        "UdpServer": 80,
        "UdpSession": 0
    }
}

**Comment by xia-chu** [comment]
- 1、你可以先看getStatistic接口 Socket 个数，然后疯狂调用openRtpServer接口
- 2、然后马上看再看getStatistic接口 Socket 个数
- 3、过段时间(大概15秒)后，再看getStatistic接口 Socket 个数。

如果阶段2 Socket实例数上升很快，但是阶段3恢复到阶段1的个数，那么说明Socket和fd数都恢复正常了。
你用netstate和lsof都可以验证到这点。

至于你说的address already in use问题本来就是正常的，在关闭socket时，端口会进入TIME_WAIT状态，要等2MSL时间才能恢复，如果你不想等，那么可以设置re_use_port为1

**Comment by ynlaodiao0919** [comment]
> * 1、你可以先看getStatistic接口 Socket 个数，然后疯狂调用openRtpServer接口
> * 2、然后马上看再看getStatistic接口 Socket 个数
> * 3、过段时间(大概15秒)后，再看getStatistic接口 Socket 个数。
> 
> 如果阶段2 Socket实例数上升很快，但是阶段3恢复到阶段1的个数，那么说明Socket和fd数都恢复正常了。 你用netstate和lsof都可以验证到这点。
> 
> 至于你说的address already in use问题本来就是正常的，在关闭socket时，端口会进入TIME_WAIT状态，要等2MSL时间才能恢复，如果你不想等，那么可以设置re_use_port为1

好的，3q，我验证下。
