### ISSUE TITLE
[技术咨询]tcp推流rtp包可以关闭ssrc验证吗

### ISSUE THREAD

**Issue by MengFanLu1** [ZLMediaKit/ZLMediaKit#2247]
**咨询的功能模块**
- tcp推流rtp包可以关闭ssrc验证吗

**咨询的具体内容和问题**
- 您好，tcp推流rtp包可以关闭ssrc验证吗

**Comment by xia-chu** [comment]
现在你是遇到什么问题了吗

**Comment by MengFanLu1** [comment]
> 现在你遇到什么问题了吗

现在做国网B接口的开发（和gb28181协议相似）,ssrc这个参数是摄像机在推流时第一个包RTCP里边携带过来的，没办法通过openRTP这个接口指定

**Comment by xia-chu** [comment]
那你不指定就行 zlm会绑定收到第一个rtp包的ssrc

**Comment by MengFanLu1** [comment]
> 那你不指定就行 zlm会绑定收到第一个rtp包的ssrc； 所以你的问题应该是zlm把第一个rtcp识别成rtp了 绑定了错误的ssrc 吗
是的，所以控制台就输出ssrc不相等的错误

**Comment by xia-chu** [comment]
> 的，所以控制台就输出ssrc不相等的错误

这个问题应该好兼容

**Comment by ketaxiang** [comment]
> > 那你不指定就行 zlm会绑定收到第一个rtp包的ssrc； 所以你的问题应该是zlm把第一个rtcp识别成rtp了 绑定了错误的ssrc 吗
> > 是的，所以控制台就输出ssrc不相等的错误

ZLMRTPServerFactor中createRTPServer方法中param.put("ssrc", ssrc);这行注释掉试试。

**Comment by xia-chu** [comment]
> > > 那你不指定就行 zlm会绑定收到第一个rtp包的ssrc； 所以你的问题应该是zlm把第一个rtcp识别成rtp了 绑定了错误的ssrc 吗
> > > 是的，所以控制台就输出ssrc不相等的错误
> 
> ZLMRTPServerFactor中createRTPServer方法中param.put("ssrc", ssrc);这行注释掉试试。

不是这个问题 是zlm把第一个rtcp包当做rtp去处理了 这样获取和绑定了错误的ssrc了 不过ssrc支持自动切换啊 ：
<img width="981" alt="图片" src="https://user-images.githubusercontent.com/11495632/221412471-43d98538-00f8-4231-8e78-84221afd1602.png">

**Comment by zhang2349** [comment]
> > > > 那你不指定就行 zlm会绑定收到第一个rtp包的ssrc； 所以你的问题应该是zlm把第一个rtcp识别成rtp了 绑定了错误的ssrc 吗
> > > > 是的，所以控制台就输出ssrc不相等的错误
> > 
> > 
> > ZLMRTPServerFactor中createRTPServer方法中param.put("ssrc", ssrc);这行注释掉试试。
> 
> 不是这个问题 是zlm把第一个rtcp包当做rtp去处理了 这样获取和绑定了错误的ssrc了 不过ssrc支持自动切换啊 ： <img alt="图片" width="981" src="https://user-images.githubusercontent.com/11495632/221412471-43d98538-00f8-4231-8e78-84221afd1602.png">

这里ssrc变了 发现一个问题  
两个流的rtp的序号可能会相差很大 导致排序的时候 丢掉了

**Comment by xia-chu** [comment]
@zhang2349 两路流同时发给zlm一个对象去处理 本身就是sip调度错误的用法。不过这种问题zlm也做了兼容，zlm会绑定其中一路流，另外一路直接忽略了：

<img width="1461" alt="图片" src="https://user-images.githubusercontent.com/11495632/221466691-57081b3b-fa43-411f-b95d-5494d91ec655.png">

**Comment by zhang2349** [comment]
> @zhang2349 两路流同时发给zlm一个对象去处理 本身就是sip调度错误的用法。不过这种问题zlm也做了兼容，zlm会绑定其中一路流，另外一路直接忽略了：
> 
> <img alt="图片" width="1461" src="https://user-images.githubusercontent.com/11495632/221466691-57081b3b-fa43-411f-b95d-5494d91ec655.png">

我知道会忽略了  但恢复到只有一路的时候
ssrc切过来了   但是rtp的seq相差大于 65535/2的时候  在排序的时候给忽略了  这段时间就没流了 等rtp的seq到下一个轮回的时候才正常

**Comment by MengFanLu1** [comment]
> > > > 那你不指定就行 zlm会绑定收到第一个rtp包的ssrc； 所以你的问题应该是zlm把第一个rtcp识别成rtp了 绑定了错误的ssrc 吗
> > > > 是的，所以控制台就输出ssrc不相等的错误
> > 
> > 
> > ZLMRTPServerFactor中createRTPServer方法中param.put("ssrc", ssrc);这行注释掉试试。
> 
> 不是这个问题 是zlm把第一个rtcp包当做rtp去处理了 这样获取和绑定了错误的ssrc了 不过ssrc支持自动切换啊 ： <img alt="图片" width="981" src="https://user-images.githubusercontent.com/11495632/221412471-43d98538-00f8-4231-8e78-84221afd1602.png">

1.	首先感谢作者对问题的解答，我看到你关于本问题昨天提交的代码了，目前使用udp的方式收流是可以，但是考虑到稳定性还是想使用tcp的方式，我今天构建最新zlmedia，tcp收流还是报ssrc不匹配，ssrc丢弃，我再详细描述一下
2. 这是报错日志
![a](https://user-images.githubusercontent.com/42708971/221487374-4205f286-29f6-49d6-aa83-bd257a0b3d6d.png)
3.这是国家电网B接口描述
![b](https://user-images.githubusercontent.com/42708971/221487531-bafdf8f2-8489-46ec-8ddf-386dc4eba02c.png)
4.是不是这个payload的问题，和gb28181里边的定义不一样，这是B接口payload定义
![c](https://user-images.githubusercontent.com/42708971/221487687-e5fbcaa3-f7fb-4773-8cca-096e660bd1e5.png)
5.这是调阅实时视频下发指令抓包
![d](https://user-images.githubusercontent.com/42708971/221487819-3ef9b4fb-6f27-4d34-9f7a-267d2e3cc119.png)
6.这是抓到的rtcp包
![e](https://user-images.githubusercontent.com/42708971/221487929-5bb6bc14-da61-4b5f-945e-b13cd85ea649.png)

**Comment by xia-chu** [comment]
tcp模式wireshark抓不到rtp包的（没法分析）；你可以用zlm的dump功能 把rtp文件上传到这供我分析

**Comment by MengFanLu1** [comment]
> tcp模式wireshark抓不到rtp包的（没法分析）；你可以用zlm的dump功能 把rtp文件上传到这供我分析

zlm的dump功能应该是修改config.ini配置文件中的dumpDir配置，我修改后可以生成rtp文件，但是没有抓取到内容，wireshark可以抓取到rtp包，步骤如下

**Comment by MengFanLu1** [comment]
> tcp模式wireshark抓不到rtp包的（没法分析）；你可以用zlm的dump功能 把rtp文件上传到这供我分析

zlm的dump功能应该是修改config.ini配置文件中的dumpDir配置，我修改后可以生成rtp文件，但是没有抓取到内容，wireshark可以抓取到rtp包，步骤如下
1.右键，Decode As..
![image](https://user-images.githubusercontent.com/42708971/221520809-36ff1438-9584-4edd-bbba-331aa9f2c240.png)
2.选择
![1677488960357](https://user-images.githubusercontent.com/42708971/221521450-0cb80584-5ced-4a80-bb86-d761c0eaf965.jpg)
3.结果
![image](https://user-images.githubusercontent.com/42708971/221521541-8bc3bf92-0446-4f1d-a463-ee4e73749d69.png)
![image](https://user-images.githubusercontent.com/42708971/221521597-c2e8ba2a-79d3-4325-a178-41ab22c234bc.png)
4.抓包
抓包发你邮箱了，谢谢您，帮忙分析下吧

**Comment by xia-chu** [comment]
我需要zlm dump出的rtp文件 这样zlm才能加载和调试

**Comment by MengFanLu1** [comment]
> 我需要zlm dump出的rtp文件 这样zlm才能加载和调试

tcp的方式由于ssrc不匹配rtp包都被丢弃了，使用zlm dump不到本地，我用udp的方式播放dump包到本地发给你可以吗？

**Comment by zhang2349** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/blob/dc8508c58f9e6b3570b45a6415cf88e9c154619a/src/Rtp/RtpSession.cpp#LL110C11-L110C15
作者忘了这里还有过滤 所以最新代码的 rtp服务器过滤非rtp包 没起到作用

**Comment by xia-chu** [comment]
> 作者忘了这里还有过滤

确实 是这里问题

**Comment by MengFanLu1** [comment]
> > 作者忘了这里还有过滤
> 
> 确实 是这里问题

这个还会修改，提交新的代码吗？

**Comment by xia-chu** [comment]
> > > 作者忘了这里还有过滤
> > 
> > 
> > 确实 是这里问题
> 
> 这个还会修改，提交新的代码吗？

会 你也可以提个pr上来

**Comment by MengFanLu1** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/blob/dc8508c58f9e6b3570b45a6415cf88e9c154619a/src/Rtp/RtpSession.cpp#L110-L115
> 
> 
> 作者忘了这里还有过滤 所以最新代码的 rtp服务器过滤非rtp包[8f10839](https://github.com/ZLMediaKit/ZLMediaKit/commit/8f108395a5dfefbc909b12c2152dcaff08e3c450) 没起到作用

非常感谢

**Comment by MengFanLu1** [comment]
> > > > 作者忘了这里还有过滤
> > > 
> > > 
> > > 确实 是这里问题
> > 
> > 
> > 这个还会修改，提交新的代码吗？
> 
> 会 你也可以提个pr上来

拉取新代码后现在可以了，非常感谢

**Comment by zhang2349** [comment]
> > @zhang2349 两路流同时发给zlm一个对象去处理 本身就是sip调度错误的用法。不过这种问题zlm也做了兼容，zlm会绑定其中一路流，另外一路直接忽略了：
> > <img alt="图片" width="1461" src="https://user-images.githubusercontent.com/11495632/221466691-57081b3b-fa43-411f-b95d-5494d91ec655.png">
> 
> 我知道会忽略了 但恢复到只有一路的时候 ssrc切过来了 但是rtp的seq相差大于 65535/2的时候 在排序的时候给忽略了 这段时间就没流了 等rtp的seq到下一个轮回的时候才正常

@xia-chu 不好意思 这里回复看错了   
我的意思 碰到了 从同一个ip和端口 发过来的流 可能是对方是出了什么问题
对方发流的ssrc 和 seq 重新生成了

(https://github.com/ZLMediaKit/ZLMediaKit/blob/91efab281ef57bbf825f68c3255d080777957f74/src/Rtsp/RtpReceiver.cpp#L71-L1)
这对代码做了 ssrc切换的功能 但重新生成的seq 跟原来的 next_seq 相差太大 被丢掉了
