### ISSUE TITLE
[功能请求]支持websocket-raw传输模式

### ISSUE THREAD

**Issue by pedoc** [ZLMediaKit/ZLMediaKit#2248]
**描述该功能的用处，可以提供相关资料描述该功能**
支持websocket-raw传输模式,和websocket-flv类似,区别在于直接传输裸流数据以节省带宽

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
支持rtmp/rtsp推流自动转码为websocket-raw模式

**Comment by xiongguangjie** [comment]
为何要这样做，这样搞没意义呀，ws-flv 也可以播放呀，节省的带宽，可以忽略不计

**Comment by xia-chu** [comment]
websocket-raw传输H264吗？目的是什么？把时间戳都丢失了，而且还不支持多track 虽然简单 但是限制太多了；
而且你说的节省带宽的观点基本不成立，容器格式只会加入一点点信息冗余

**Comment by pedoc** [comment]
感谢各位的回复.
这只是我个人这边遇到的业务需求,可能不具有普适性.
我们这边前端播放器支持直接解码raw格式视频,在级联/中转了很多层之后,视频都会受到网络的严重影响.所以想从可能的地方尽量节省带宽,减轻带宽压力.

当前我们使用的是ws-flv

**Comment by xia-chu** [comment]
换H265吧 这样带宽低
