### ISSUE TITLE
[功能请求] 转协议时音频支持g711转aac

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2250]
**描述该功能的用处，可以提供相关资料描述该功能*

有些场景下流推送上来  音频编码时g711格式  转协议后  转成 ts流 或 MP4 标准里面默认不不支持g711   转协议后   如果使用hls或fmp4  音频流就没有了。在安防监控里面g711音频是常见的。希望能支持 转hls或fmp4时  支持可选 g711转aac。

像我之前做国标喊话只支持g711的音频，相机上配置成g711后    视频预览的音频就是g711   一旦配置成aac喊话功能就失效了。
希望能支持  ts和MP4  转协议时 支持音频g711转aac

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

转ts流或mp4支持 g711转aac

**Comment by xia-chu** [comment]
这个短期是不会被支持的 转码不是流媒体的核心功能
