### ISSUE TITLE
[技术咨询]关于http-flv直播流实时获取，解封装

### ISSUE THREAD

**Issue by zzgghhzzgghh** [ZLMediaKit/ZLMediaKit#2251]
各位请教下啊：我从zlm拉取http-flv直播流，想提取里面的关键帧，现在的问题是怎么样收到流，解封装呢？（前提是不用ffmepg的av_read_frame，不想用ffmepg，太重量级了）还有其他轻量级的库么

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by zhang2349** [comment]
这部分作者还没开源
