### ISSUE TITLE
[技术咨询] 请问溯源方式的集群支持webrtc推流到源站，然后在边沿站拉流吗？

### ISSUE THREAD

**Issue by devhh** [ZLMediaKit/ZLMediaKit#2254]
**咨询的功能模块**
- webrtc 集群

**咨询的具体内容和问题**
- 你好，新手请教个问题，目前在调研webrtc视频会议的媒体服务器的选型，意向选ZLMediaKit(感谢xiacu提供这么优秀的流媒体服务)，目前在集群上遇到不懂的问题，我想通过webrtc推流到源站，然后通过边沿站拉rtc流播放，请问这样是否支持呢？万分感谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
rtsp拉流，然后转成rtc 就可以了

**Comment by devhh** [comment]
好的，感谢！
