### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by peterwangfeng** [ZLMediaKit/ZLMediaKit#2255]
**咨询的功能模块**
- Gb28181 

**咨询的具体内容和问题**
- 上级平台的TCP主动模式流传输,目前zlmediakit支持吗

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
startSendRtpPassive接口你可以了解下

**Comment by xia-chu** [comment]
openRtpServer + connectRtpServer 接口你也可以了解下

**Comment by peterwangfeng** [comment]
thanks
