### ISSUE TITLE
[技术咨询]请问如何对hls打水印，水印位置不固定，每个流都可能有本身对应的水印位置

### ISSUE THREAD

**Issue by ouxiand** [ZLMediaKit/ZLMediaKit#2256]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
[技术咨询]请问如何对hls打水印，水印位置不固定，每个流都可能有本身对应的水印位置

**咨询的具体内容和问题**
试着用ffmpeg进行转码生成文件，然后在zlm播放，延时增加很大，比zlm原有的hls慢太多（慢一分钟），还时不时卡顿，隔断时间才能恢复
./ffmpeg -re -i rtsp://172.21.209.121:5303/rtp/061468D0 -c copy -g 0 -f hls  -hls_list_size 3 -hls_flags 2 -hls_time 2 /record/record/rtp/555/hls.m3u8
zlm播放：https://172.21.209.121:5303/rtp/555/hls.m3u8  
请教大佬们，有没有更佳的解决方案？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
目前没啥更好的手段 都是通过ffmpeg方式实现

**Comment by ouxiand** [comment]
只能ffmpeg转码  没其他招
