### ISSUE TITLE
[技术咨询]ZLM播放已经录好的hls文件，如何知道前端多少人在观看？目前发现实时推流的时候hls有连接总数，播放历史hls文件没有发现

### ISSUE THREAD

**Issue by ouxiand** [ZLMediaKit/ZLMediaKit#2261]
**咨询的功能模块**
- HLS播放追踪问题，请问大佬是否支持这个hls播放追踪问题？

**咨询的具体内容和问题**
[技术咨询]ZLM播放已经录好的hls文件，如何知道前端多少人在观看？目前发现实时推流的时候hls有连接总数，播放历史hls文件没有发现。
举例：路径 /rtp/061468EE/hls.m3u8   ,保存好的文件
zlm播放：http://******/rtp/061468EE/hls.m3u8  ，可以正常播放，但是不知道有没有人在看！想跟踪这个信息。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
接口getMediaList 有观看人数

**Comment by xia-chu** [comment]
> getMediaList正在推流可以看 ， 播放历史hls文件没有

播放历史hls文件是当做http文件服务器用的 所以是没有统计的。hls历史文件可以使用任意的http文件服务器，大家都没这个功能，要二次开发
