### ISSUE TITLE
[技术咨询]rtsp音视频推流拉流时音频拉流不正常

### ISSUE THREAD

**Issue by wang1398366941** [ZLMediaKit/ZLMediaKit#2263]
**咨询的功能模块**
- rtsp音视频推流拉流

**咨询的具体内容和问题**
1  在RK平台上使用，使用C SDK开发，使用RK平台编码的音视频流，音频g711a，使用mk_media_input_h264、mk_media_input_audio方法，成功生成RTSP流，并且同样在RK平台上，使用mk_player_play播放RTSP，tracks[1]获取到的视频流没有问题，正常解码出图像，tracks[0]获取到的音频流则有问题，zlm本身没有报错，但就是音频流每包获取到的数据长度只有160字节，实际mk_media_input_audio时，数据长度有1536字节，最终导致解码音频不对，并且获取每包音频流的速度好快

2  使用2021年的10月份的版本，712bdf7310c0e80bcbccd16e7245fb3db9e42d2d，之前产品上一直使用的都是这版，则是没有任何问题，音视频RTSP推流拉流都没问题，mk_media_input_audio音频1536字节，拉流获取的也是1536字节

![lQLPJw2MqUDzJxhOzQO6sKSqVJWYuCXIA_jD2fcAcwE_954_78](https://user-images.githubusercontent.com/126658865/222105903-c26aa06e-c4c4-4d81-bba3-aea3dfe7128b.png)

![lQLPJwzEkoMZZxjMi80Ey7BncwMu8Mg1MQP4w9oDgBMA_1227_139](https://user-images.githubusercontent.com/126658865/222105916-3471c27a-733d-4467-9d38-bf8d9b607d00.png)

![lQLPJwZok6jzhxjMw80EhbBM6wo26pT2PwP4w9oFAPkA_1157_195](https://user-images.githubusercontent.com/126658865/222105920-c83915b8-12e5-47df-bdd2-f7ebdcdffd69.png)

![lQLPJxwLZkeiJxjNAorNA4-wDeGgKOYhhk4D-MPZ9wBzAA_911_650](https://user-images.githubusercontent.com/126658865/222105927-a418302f-a090-48a3-8621-4e9f310237dd.png)

**Comment by wang1398366941** [comment]
硬件平台是RK3568

**Comment by xiongguangjie** [comment]
设计如此，rtc 音频g711 必须是20ms一个帧，才能正常播放，这个需要你在解码时处理一下

**Comment by xiongguangjie** [comment]
你这个音频采样率也不对呀，默认g711a 是8khz

**Comment by wang1398366941** [comment]
2021年的10月份的版本我就是这样用，没问题的，只是我发现新版本的zlm，出图像更快了，所以才想替换，所以这问题是采样率不对导致的吗

**Comment by wang1398366941** [comment]
2021年的10月份的版本我就是这样用，没问题的，只是我发现新版本的zlm，出图像更快了，所以才想替换，所以这问题是采样率不对导致的吗

**Comment by xia-chu** [comment]
g711a请强制使用8K采样率 否则很多地方会有兼容性问题

**Comment by wang1398366941** [comment]
好的，谢谢解疑，我试试
