### ISSUE TITLE
[技术咨询] 求助ZLMediaKit对于RTP H264推流的支持情况

### ISSUE THREAD

**Issue by fancylear** [ZLMediaKit/ZLMediaKit#2269]
**咨询的功能模块**
- RTP推流支持模块

**咨询的具体内容和问题**
- 经查看，ZLMediaKit支持 PS-RTP和RTP_mpegts推流，请问是否支持ffmpeg 默认的RTP模式推流？（H264）
- 比如这样推流命令ffmpeg -re -i d:\videos80P.264 -vcodec copy **-f rtp** rtp://127.0.0.1:1234  是否能支持和解析 ?

**Comment by xia-chu** [comment]
zlm的rtp服务器同时支持 ps ts es推流，其中es推流需要你在配置文件中指定payload type, 否则zlm不知道是什么codec的rtp

**Comment by fancylear** [comment]
> zlm的rtp服务器同时支持 ps ts es推流，其中es推流需要你在配置文件中指定payload type, 否则zlm不知道是什么codec的rtp

谢谢~配置文件这了是指在config.ini里面的rtp_proxy -> h264_pt=98 h265_pt=99 这里制定就可以吗？
