### ISSUE TITLE
ffplay take long time to play stream from MediaServer (non-existing PPS 0 referenced)

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#2275]
Hi,

I am using addStreamProxy to add a rtsp source to MediaServer.
When using FFplay to play this source, it's very fast to open. "non-existing PPS 0 referenced" appears only once:
![ảnh](https://user-images.githubusercontent.com/59004953/223033228-10cb0ca1-e1ef-4608-a7cf-02fe5d5881b8.png)
but when add this rtsp source to MediaServer, ffplay take ~ 20 seconds to play:
ffplay -rtsp_transport tcp rtsp://127.0.0.1:8554/proxy/cam8
![ảnh](https://user-images.githubusercontent.com/59004953/223035668-73d9a5e0-48c2-425a-a720-a982a58816eb.png)

**Comment by xia-chu** [comment]
How is your config.ini file ?

**Comment by pubpy2015** [comment]
Hi,

Am using default config.ini, created by MediaServer and nothing changed.
Attached files areconfig.ini and log.
[2023-03-06_00.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/10895067/2023-03-06_00.zip)

[config.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/10895062/config.zip)
