### ISSUE TITLE
[编译问题]: 下载Demo直接打开andorid项目报错C:\Users\Administrator\Desktop\ZLMediaKit-master\Android\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: CMake can not determine linker language for target: mpeg

### ISSUE THREAD

**Issue by ILoveLin** [ZLMediaKit/ZLMediaKit#2276]
[编译问题]: 下载Demo直接打开andorid项目报错:
C:\Users\Administrator\Desktop\ZLMediaKit-master\Android\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: CMake can not determine linker language for target: mpeg

**Comment by xiongguangjie** [comment]
子模块你没拉下来吧

**Comment by ILoveLin** [comment]
> 基本的快速开始wiki都不看？
谢谢回复,我重新拉了,跑起来了,但是提示,我该如何操作?博主
![FF82F677
![6B855DF24F59B9ADD49CE51A1FD83EE6](https://user-images.githubusercontent.com/20768182/224635226-9390b0ec-b457-4d96-926d-0eb1e6fe2856.jpg)
BE7537AD42DABD4B32927FDF](https://user-images.githubusercontent.com/20768182/224635223-306a222f-a81c-45c0-a944-a8083879ae91.jpg)

**Comment by xia-chu** [comment]
运行成功了 MediaServer就这样 无界面





------------------ 原始邮件 ------------------
发件人: tongzhengtong ***@***.***&gt;
发送时间: 2023年3月13日 15:31
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, State change ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [编译问题]: 下载Demo直接打开andorid项目报错C:\Users\Administrator\Desktop\ZLMediaKit-master\Android\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: CMake can not determine linker language for target: mpeg (Issue #2276)
