### ISSUE TITLE
[技术咨询]transcode分支咨询

### ISSUE THREAD

**Issue by wuchingyy** [ZLMediaKit/ZLMediaKit#2278]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
使用transcode和transcode2想测试下aac推，opus拉是否可以，发现通过webrtc播放器是没声音的（喇叭按钮灰色）
不知道是否使用姿势不对，配置文件也没看到转码相关的配置
ffprobe查看了一下，声音还是aac的

**注意事项**
wiki和issue都翻了一遍，没有看到相关的

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by mtdxc** [comment]
你是不是没把ffmpeg编译进去？

**Comment by wuchingyy** [comment]
“没把ffmpeg编译进去“这个怎么理解？我已经按照wiki里面说的，把ffmpeg安装到系统了，现在在/usr/bin/下，对应的config文件里面的ffmpeg路径也是正确的
还是说要把ffmpeg编译成库文件让zlmediakit调用的意思？

请指点一下具体应该怎么操作？

**Comment by xia-chu** [comment]
apt-get install libavcodec-dev libswscale-dev libswresample-dev

**Comment by xia-chu** [comment]
你安装的是ffmpeg命令行 不是一回事

**Comment by wuchingyy** [comment]
哦应该是这个了，我这就去试试，因为看wiki说的是 “供ZLMediaKit的test_player测试程序使用”，就没安装了，谢谢谢谢！！

**Comment by wuchingyy** [comment]
刚刚又试了一遍，已经apt-get install libavcodec-dev libswscale-dev libswresample-dev过了，重新走cmake，结果还是没看到aac转成opus的，有什么日志/调试的方式可以看到哪里的问题么？
无论transcode还是transcode2都试过了，aac进，仍然是aac出

**Comment by mtdxc** [comment]
贴下你的cmake的输出吧。ffmpeg的版本号也有要求的。。

**Comment by wuchingyy** [comment]
是有看到这个输出了 without ffmpeg disable audio_transcode
那是说明还是没有编译ffmpeg进去么？

我已经apt-get install libavcodec-dev libswscale-dev libswresample-dev过了

**Comment by wuchingyy** [comment]
刚确认过，avcodec, swscale, swresample的版本是4.4.2

**Comment by wuchingyy** [comment]
再补充下cmake输出
![截屏2023-03-07 17 37 11](https://user-images.githubusercontent.com/126573758/223382786-d5e7caa3-bdcf-4d0b-826c-b01488da7892.png)

**Comment by mtdxc** [comment]
这个ffmpeg应该是没开启的 cmake -DENABLE_FFMPEG=true 看看

**Comment by wuchingyy** [comment]
感谢感谢，加上这个参数可以了～
另外再请问下transcode和transcode2的差异是在哪？
我的场景是想aac转opus的话建议使用哪个分支？

**Comment by mtdxc** [comment]
如果只要做rtc和其他格式的音频转码的话，两个都可以，
transcode2是transcode的代码重构版本，并把转码限制成只在进出webrtc才会启用

**Comment by wuchingyy** [comment]
明白了，感谢，close了哈
