### ISSUE TITLE
[技术咨询]关于RTP送流超时断开socket的问题咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2284]
**咨询的功能模块**
Linux服务器部署ZLM，接收摄像头->转码库来的RTP，然后再发给客户端服务平台（服务平台也是ZML接收然后进行转发）
：摄像机->[转码库-》ZML发流（Linux服务器）]---socket----win平台ZML接收和转发；

**咨询的具体内容和问题**
在实际测试中，发现RTP socket发流的时候是一级缓存->二级缓存->socket;并且当二级缓冲刷新间隔超过10秒就会断开socket；（其实我并没找到怎么从外部改这个值，因为我测试的时候发现有好几个socket）；
上层限制的是bufffercount /fps <1S就提升编码质量。如果在1~15秒之间就不改变转码库编码质量；当buffercount（就是你内部的一二级缓冲总数的那个getsendbuffercount（socket.cpp））大于15秒，开始下调编码质量【这样其实有问题的，因为大于15秒的时候有可能已经20秒或者更多了】，并且限制了Linux带宽，100K左右；实际测试中发现会出现socket断开；

基于此我进行打印排查，发现socket。cpp的flushAll里边的这个超时时间一直是10，我也改不了，这个其实是二级缓冲全部消耗掉的用时；说明我上一次一级缓冲的帧放到二级缓冲后，在网络进行发送，超过了十秒；

他们诉求是，不能断开socket；一开始我想，我强制先把 max_send_buffer_ms g改成20秒，因为这样即便我一级缓冲缓存了15秒的数据，发送超时设置20秒肯定能发送了（当然，编码质量高，带宽固定，有可能20秒不一定发送完二级缓冲所有数据），可是我意识到，我把这个超时值改大，那同时一级缓冲也在持续的手转码库来的数据，一级缓冲数据因此会缓存更多数据，等下一次送到二级缓冲，那二级缓冲中的帧消耗时间会更长；

另外我发现，二级缓冲是大约4秒直接消耗100帧左右（30FPS），假设我的二级缓冲缓存10秒=300帧的帧数，这个二级缓冲的消耗是第一个4秒消耗了120帧，然后第二个4秒消耗120，剩下的60帧其实是需要等到下一个4秒一次性消耗完，打印看并不是一帧一帧消耗的；也就是说我这10秒的数据其实需要3*4=12秒才消耗掉；

链接ZML的上下游其实没有什么预测算法；所以我只能想一些简单的方法看能不能达到他们的诉求；---------初学，也是真不懂这里边的一些东西；

我后来想，我能不能加个判断，一旦二级缓冲数据量变少，我就reset一下begin的时间，就像你每次二级缓冲为空的时候reset一下；但是这样其实等到二级缓冲消耗完一级缓冲还是已经存了更多时间的帧；

即便阻塞也不要断网；但是其实我也可以在flushALL 的超时判断处，把那个emitError断开socket给删掉。但是总觉得自己理解的不对；

所以来求助一下；希望能得到一些指点所以来求助一下；希望能得到一些指点。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xuandu** [comment]
1条件，限制Linux服务器带宽；并且根据缓冲帧，转成时间，回调给转码库进行QP调整；
2 会有二次开发，但是非常少，就是加些打印，或者有些参数适配摄像头的码流；你的整体逻辑都不会改的，只是加些回调
3 我其实在rtpsender.cpp里回调给外边buffer数量等信息；但是它其实包含的是音视频总数；并不能拿到视频帧的数量，记得您说可以通过getmedialist？？？我其实有点赶鸭子上架，不太了解全部接口的作用；

**Comment by xia-chu** [comment]
你的核心诉求其实是想根据网络带宽质量动态调整编码码率，我的建议是这样：
- 1、通过Socket::setSendTimeOutSecond把发送socket的超时时间加大，比如收60秒，让超时尽量无效。
- 2、在编码时，每隔一段时间通过Socket::getSendBufferCount() 获取待发送包个数，如果这个值在上升，应该降低编码码率。
- 3、其实也更应该通过Socket::getSendSpeed() 来获取发送速率，如果这个值低于你编码码率，那么你应该降低编码码率，如果高于你编码码率，应该适当提高(但是应该设置上限)，这样能确保自适应带宽编码。

**Comment by xia-chu** [comment]
我建议你用Socket::getSendSpeed() 方法吧 能满足你的需求
