### ISSUE TITLE
[技术咨询]webrtc播放并发20个左右，服务器上行带宽未达上限，多个客户端出现卡顿现象

### ISSUE THREAD

**Issue by youdeveloper** [ZLMediaKit/ZLMediaKit#2285]
**咨询的功能模块**
使用webrtc并发播放

**咨询的具体内容和问题**
推流和拉流都在局域网环境内，千兆网口。
服务器：CPU24核，内存128GB
操作系统：ubuntu

ZLMediaKit使用Docker方式启动，默认配置。

Step 1: ffmpeg推流

将局域网的中的海康摄像头，通过ffmpeg推送主码流到ZLMedia，主码流帧率为2Mbps。
我在测试中一共同时推送了6台摄像头。

Step 2: webrtc播放

写一个html，通过webrtc，同时播放6路画面。

打开3个html，也就是同时播放3*6=18个画面，画面基本流畅，此时服务器监控出口流量为36megabits/s左右。

当再增加并发数量1-2个，并发19-20个时，很多客户端就开始卡顿了，此时服务器监控出口流量为40megabits/s左右。

服务器CPU，内存，此时的占用率都是很低的状态，应该不是服务器性能问题。

补充：
同时也测试了带宽上限，相同硬件网络环境下，使用janus拉摄像头rtsp流（2M主码流）转webrtc，然后浏览器webrtc播放，并发可达50以上，服务器监控出口流量达到100megabits/s以上，客户端才会开始卡顿。

按测试情况来看，我这边局域网环境千兆网口正常出口流量达到100megabits/s，应该是没什么问题，但是使用ZLMediaKit并发播放rtc达到40megabits/s，就开始卡顿。

请问有其他排查的思路或优化的方案吗

**Comment by xiongguangjie** [comment]
是不是拉流端，资源被耗尽了

**Comment by youdeveloper** [comment]
应该不是拉流端问题，我还刻意拿了3台电脑分别播放6路以上的视频，确实会卡顿，而且每台电脑都会有几个画面卡顿了。

**Comment by xiongguangjie** [comment]
我写个程序验证一下吧，明天回复你

**Comment by youdeveloper** [comment]
@xia-chu
我再测试了一遍，也用了getThreadsLoad。
1、ffmpeg分别拉10路摄像头rtsp，2Mbps主码流，推送rtmp
2、一个html中写了10个video，对应10路，使用webrtc播放。我打开了2个html。（2台电脑分别打开）
3、两个html中，分别会有一些视频存在卡顿。
图1是服务器的流量统计。统计入口流量20megabits/s，对应10个2Mbps的摄像头推流进来；出口流量41megabits/s，对应20个webrtc播放的客户端。
图2是其中一个html页面，已经可以看到绿屏了。
图3是此时调用getThreadsLoad的结果（我已经刷了很多次了这接口了，尽量选择了load值比较大的截图了），delay基本都是0。

补充：我还是怀疑是不是服务器出口带宽上限只有megabits/s，但是我之前测试过上限是可以达到100megabits/s的。就很奇怪。
不清楚是否还有其他思路可以排查一下呢。
![image](https://user-images.githubusercontent.com/16471056/223683541-c3828816-44ee-4d01-9745-64b15d1feb78.png)
![image](https://user-images.githubusercontent.com/16471056/223683573-d193f937-35eb-429a-996f-024439449a10.png)
![image](https://user-images.githubusercontent.com/16471056/223683591-2a349778-7af1-4658-942e-9fdb313dd951.png)

**Comment by xia-chu** [comment]
那说zlm根本就没到性能瓶颈

**Comment by xiongguangjie** [comment]
你的linux内核版本是不是很低,导致不支持udp 链接的特性，从而导致会竞争锁而导致出现这种问题

**Comment by xiongguangjie** [comment]
我昨天网上写了个测试程序，没有发现这个问题，客户端去拉100路rtc ,然后浏览器播放一路，都是正常的，没有出现你这种问题

**Comment by youdeveloper** [comment]
@xiongguangjie 我这是Ubuntu系统，刚查了内核`Linux 5.15.0-67-generic x86_64`，挺高的吧。

**Comment by youdeveloper** [comment]
我再找一台centOS再测试一下

**Comment by youdeveloper** [comment]
`我用一台CentOS7（内核`3.10.0-1160.el7.x86_64`）测试下来，可以超出20个并发了，大概到30-40个才开始卡。

**Comment by youdeveloper** [comment]
@xiongguangjie @xia-chu 我这里解决了，排查到是我这里网络布置问题，导致出口百兆都不到。换到正常的千兆网口下，并发是没有问题的。感谢。
