### ISSUE TITLE
[BUG]: 关闭rtp端口然后快速的打开rtp端口，会出现address already in use

### ISSUE THREAD

**Issue by alex03226** [ZLMediaKit/ZLMediaKit#2286]
### 现象描述
wvp拉流，当协商的ssrc不一致时，wvp会告知zlm关闭closeRtpServer(32000) -> getRtpInfo -> openRtpServer(port=32000)，这个时候zlm会输出 Bind socket failed: address already in use

### 如何复现?
快速的关闭RtpServer然后再打开指定端口的RtpServer

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
核心日志：
2023-03-08 15:47:42.818 D MediaServer[10-event poller 24] WebApi.cpp:249 http api debug | 
# request:
POST /index/api/openRtpServer
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310786586&port=0&ssrc=115006702&enable_tcp=1
# response:
{
	"code" : 0,
	"port" : 32438
}

POST /index/api/closeRtpServer
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310786586
# response:
{
	"code" : 0,
	"hit" : 1
}

# request:
POST /index/api/getRtpInfo
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310786586
# response:
{
	"code" : 0,
	"exist" : false
}

2023-03-08 15:47:46.292 W MediaServer[10-event poller 24] sockutil.cpp:396 bind_sock6 | Bind socket failed: address already in use
# request:
POST /index/api/openRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 134
Content-Type : application/x-www-form-urlencoded
Host : 192.168.0.1:89
User-Agent : okhttp/4.10.0
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310786586&port=32438&ssrc=115006676&enable_tcp=1
# response:
{
	"code" : -400,
	"msg" : "Listen on :: 32438 failed: address already in use"
}
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: head
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
openRtpServer时 请re_use_port设置为1

**Comment by alex03226** [comment]
是不是，把这个值默认改为  true ，会更适合zlm

**Comment by xia-chu** [comment]
你不传这个参数 那么就是默认false

**Comment by liwenyan703** [comment]
> 
你知道你在哪里设置吗

**Comment by liwenyan703** [comment]
> 你不传这个参数 那么就是默认false
你知道在哪个地方设置吗

**Comment by alex03226** [comment]
我是直接修改了 zltoolkit 里面的 listen 新增了 re_use_port 参数
RtpServer.cpp: 183 中里面 tcp_)server->start(Rtp[Session>(port, ip, re_use_port)

**Comment by alex03226** [comment]
`
diff --git a/src/Network/Socket.cpp b/src/Network/Socket.cpp
index 709e32c..2945614 100644
--- a/src/Network/Socket.cpp
+++ b/src/Network/Socket.cpp
@@ -495,8 +495,8 @@ bool Socket::listen(const SockFD::Ptr &sock){
     return true;
 }
 
-bool Socket::listen(uint16_t port, const string &local_ip, int backlog) {
-    int sock = SockUtil::listen(port, local_ip.data(), backlog);
+bool Socket::listen(uint16_t port, const string &local_ip, bool re_use_port, int backlog) {
+    int sock = SockUtil::listen(port, local_ip.data(), re_use_port, backlog);
     if (sock == -1) {
         return false;
     }
diff --git a/src/Network/Socket.h b/src/Network/Socket.h
index cb47fc7..d40374c 100644
--- a/src/Network/Socket.h
+++ b/src/Network/Socket.h
@@ -301,7 +301,7 @@ public:
      * @param backlog tcp最大积压数
      * @return 是否成功
      */
-    virtual bool listen(uint16_t port, const std::string &local_ip = "::", int backlog = 1024);
+    virtual bool listen(uint16_t port, const std::string &local_ip = "::", bool re_use_port = false, int backlog = 1024);
 
     /**
      * 创建udp套接字,udp是无连接的，所以可以作为服务器和客户端
diff --git a/src/Network/TcpServer.cpp b/src/Network/TcpServer.cpp
index d404d93..a96a5e6 100644
--- a/src/Network/TcpServer.cpp
+++ b/src/Network/TcpServer.cpp
@@ -165,8 +165,8 @@ Session::Ptr TcpServer::onAcceptConnection(const Socket::Ptr &sock) {
     return session;
 }
 
-void TcpServer::start_l(uint16_t port, const std::string &host, uint32_t backlog) {
-    if (!_socket->listen(port, host.c_str(), backlog)) {
+void TcpServer::start_l(uint16_t port, const std::string &host, bool re_use_port, uint32_t backlog) {
+    if (!_socket->listen(port, host.c_str(), re_use_port, backlog)) {
         //创建tcp监听失败，可能是由于端口占用或权限问题
         string err = (StrPrinter << "Listen on " << host << " " << port << " failed: " << get_uv_errmsg(true));
         throw std::runtime_error(err);
diff --git a/src/Network/TcpServer.h b/src/Network/TcpServer.h
index bbd6d31..bb2819c 100644
--- a/src/Network/TcpServer.h
+++ b/src/Network/TcpServer.h
@@ -43,14 +43,14 @@ public:
     * @param backlog tcp listen backlog
     */
     template<typename SessionType>
-    void start(uint16_t port, const std::string &host = "::", uint32_t backlog = 1024) {
+    void start(uint16_t port, const std::string &host = "::", bool re_use_port = false, uint32_t backlog = 1024) {
         //Session创建器，通过它创建不同类型的服务器
         _session_alloc = [](const TcpServer::Ptr &server, const Socket::Ptr &sock) {
             auto session = std::make_shared<SessionType>(sock);
             session->setOnCreateSocket(server->_on_create_socket);
             return std::make_shared<SessionHelper>(server, session);
         };
-        start_l(port, host, backlog);
+        start_l(port, host, re_use_port, backlog);
     }
 
     /**
@@ -79,7 +79,7 @@ protected:
 private:
     void onManagerSession();
     Socket::Ptr createSocket(const EventPoller::Ptr &poller);
-    void start_l(uint16_t port, const std::string &host, uint32_t backlog);
+    void start_l(uint16_t port, const std::string &host, bool re_use_port, uint32_t backlog);
     Ptr getServer(const EventPoller *) const;
 
 private:
diff --git a/src/Network/sockutil.cpp b/src/Network/sockutil.cpp
index 8585933..9bc9ea4 100644
--- a/src/Network/sockutil.cpp
+++ b/src/Network/sockutil.cpp
@@ -467,7 +467,7 @@ int SockUtil::connect(const char *host, uint16_t port, bool async, const char *l
     return -1;
 }
 
-int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
+int SockUtil::listen(const uint16_t port, const char *local_ip, bool re_use_port, int back_log) {
     int fd = -1;
     int family = support_ipv6() ? (is_ipv4(local_ip) ? AF_INET : AF_INET6) : AF_INET;
     if ((fd = (int)socket(family, SOCK_STREAM, IPPROTO_TCP)) == -1) {
@@ -475,7 +475,11 @@ int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
         return -1;
     }
 
+#if 0   //20230316
     setReuseable(fd, true, false);
+#else
+    setReuseable(fd, true, re_use_port);
+#endif
     setNoBlocked(fd);
     setCloExec(fd);
 
diff --git a/src/Network/sockutil.h b/src/Network/sockutil.h
index 8a9d739..0d13086 100644
--- a/src/Network/sockutil.h
+++ b/src/Network/sockutil.h
@@ -69,7 +69,7 @@ public:
      * @param back_log accept列队长度
      * @return -1代表失败，其他为socket fd号
      */
-    static int listen(const uint16_t port, const char *local_ip = "::", int back_log = 1024);
+    static int listen(const uint16_t port, const char *local_ip = "::", bool re_use_port = false, int back_log = 1024);
 
     /**
      * 创建udp套接字
`

**Comment by xia-chu** [comment]
@alex03226 现在zlmediakit新增updateRtpServerSSRC接口了 wvp已经适配了 所以这个问题就不存在了

**Comment by alex03226** [comment]
great
