### ISSUE TITLE
[技术咨询] 压测频繁出现 RtspPlayer 报错 receive rtp timeout

### ISSUE THREAD

**Issue by hongshuai1994** [ZLMediaKit/ZLMediaKit#2287]
**咨询的功能模块**
**test_bench_pull**、**RtspPlayer**

**咨询的具体内容和问题**
你好，我们最近考虑使用ZLMediakit（下称zlmk），目前正在压测zlmk，我们压测的数据链路是：
**机器分布**：服务器A部署了zlmkA，服务器B部署了zlmkB，在服务器C上运行test_bench_pull对zlmkB进行压测
**数据流方向**：ffmpeg推流到zlmkA的rtspURLA上，然后我们把rtspURLA注册了1.3w次到zlmkB上，得到了1.3条新的rtspURL[0,12999]，然后我们使用test_bench_pull去拉rtspURL[0,12999]
**机器资源**：
- 服务器A：Intel Xeon 104 核 / 251G内存，上下行均50Gbps带宽
- 服务器B：Intel Xeon 104 核 / 251G内存，上下行均50Gbps带宽
- 服务器C：Intel Xeon 104 核 / 251G内存，上下行均50Gbps带宽

我们开始压测，发现有如下问题：
1. rtspURLA 的码率是1500kbps，但是1.3w路就把服务器B带宽给几乎打满了，50Gbps带宽应该支持4w多路才对，为啥1.3w路就打满了呢？
2. 我们先在zlmkB上注册了1.3w路得到了1.3条新的rtspURL[0,12999]，然后我们在服务器C上用test_bench_pull去拉这1.3w路，发现：test_bench_pull的RtspPlayer.cpp:689 报 receive rtp timeout 错，然后就重连；我们怀疑是带宽打满了，网络拥塞的表现，但是降到7000路去拉的时候，还是会频繁出现test_bench_pull的RtspPlayer.cpp:689 报 receive rtp timeout 错，同时zlmkB打recv teardown request log，合并写开关打开和关闭都是如此；test_bench_pull 重试后都可继续播放，想问下：
--> 1. 是不是无论test_bench_pull从zlmkB拉1000路还是1w路，频繁出现上面报错但重试ok的情况，是正常的吗？报错并重试成功，会导致播放卡顿吧？
--> 2. ZLMediakit给出的[压测报告](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95)，在压测的时候，有频繁出现上面的报错吗？还是说只要重试可继续播放就算ok呢？还是说压测这里的压测结果是稳定没有任何报错的呢？

**Comment by hongshuai1994** [comment]
![image](https://user-images.githubusercontent.com/80237674/223901281-e9a7631b-a93d-4222-a1e5-2bbdbd71053b.png)
这张图是test_bench_pull侧的log，看着有问题的log是：receive rtp timeout和handleResPAUSE
出现了ResPAUSE，表示播放短暂暂停了吗？之后重试又继续播放了吗

**Comment by hongshuai1994** [comment]
@xia-chu 大佬求看

**Comment by xia-chu** [comment]
"然后我们把rtspURLA注册了1.3w次到zlmkB上" 是通过addStreamProxy接口注册到zlmkB上的吗？

**Comment by hongshuai1994** [comment]
> "然后我们把rtspURLA注册了1.3w次到zlmkB上" 是通过addStreamProxy接口注册到zlmkB上的吗？

是的

**Comment by xia-chu** [comment]
所以 zlm B上有1.3万个流吗？

**Comment by xia-chu** [comment]
一般来说 分发数据比较容易做到高并发 你用zlm B拉流，其实本质跟test_bench_pull拉流一样，只是zlm B从zlm A拉一个流,
而test_bench_pull从 zlm B拉很多个流。但是由于zlm B要对外提供1.3w个url，那么它的负载要比提供1个url的zlm A高很多。

**Comment by xia-chu** [comment]
由于分发数据需要线程切换，因为拉流代理线程是一个线程，但是播放器可能随机分配在其他线程上，所以你现在又用1.3W个播放器去播放zlm B上这1.3W个流，那么zlm B进程中，每时每刻都发生着海量的线程切换事件，而且这些事件没法合并切换，zlm B的性能会急剧下降。

**Comment by xia-chu** [comment]
你是104核心的cpu，这1.3W个流以及1.3W个播放器随机分配(一般比较均匀)在这104个线程上，但是由于流需要转发到播放器上，那么意味着104个线程间频繁的数据交换 会出现大量的锁竞争与数据拷贝(智能指针引用的拷贝)， 所以性能会非常拉胯

**Comment by xia-chu** [comment]
但是如果你流比较少的情况下 播放器比较多的情况下 就不会存在这种情况，因为zlm做了线程切换批量操作的优化，
比如说你有10W个播放器播放一个流，这10W个播放器分布在104个线程上，那么我们在分发数据时，不会做10W次线程切换，
只会做104次线程切换。但是你测试的场景做不到这个优化。

**Comment by xia-chu** [comment]
一般流媒体服务器分为源站和边缘站，他们的使用场景是
1、源站节目多，但是分发少，这些节目大部分无人看，不分发。
2、边缘站节目少，但是分发多。

你的这种场景，节目多还要全部分发，那么性能就得不到保障
