### ISSUE TITLE
[技术咨询] 在openRtpServer后调用getRtpInfo返回exist:false

### ISSUE THREAD

**Issue by pinkcao** [ZLMediaKit/ZLMediaKit#2288]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

zlmediakit的提供的http接口

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

目的：创建一个rtp服务器用来接收rtp流

1.使用wvp，程序逻辑为先getRtpInfo,如果当前stream_id对应的rtpServer未建立，则建立一个指定的rtpServer
2.建立完成后，其他流媒体开始往zlmediakit指定rtpServer port开始推流，可抓到相关rtp数据包，在zlmediakit服务器上也可抓到相关数据包
3.zlmediakit http hook: on_rtp_server_timeout 返回信息，参数均为openRtpServer时指定参数无误

以上为测试getRtpInfo的原因
下面为使用postman测试getRtpInfo过程：

1.调用openRtpServer
![创建rtp服务器](https://user-images.githubusercontent.com/36530450/223908598-882cbc8c-371a-4d18-ab8d-41a769ee9cd5.png)
其中stream_id为test

2.调用listRtpServer
![获取rtp服务器](https://user-images.githubusercontent.com/36530450/223908710-007a305d-1571-4402-b9d6-262e79204152.png)
返回了带有stream_id的rtpServer，端口号为自动指定的30132

3.调用getRtpInfo

![获取rtp推流信息](https://user-images.githubusercontent.com/36530450/223908833-38db462d-a69c-4b0f-8587-743db3af7d50.png)
stream_id参数为test
返回exist:false

其中调用1 2 3过程中该rtpServer均为超时

因此想知道在正常流程中，openRtpServer后立即调用getRtpInfo应该返回什么内容，目前返回的是否正确

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xiongguangjie** [comment]
正确，exist 为false 是因为没有接收到rtp数据

**Comment by pinkcao** [comment]
好的

**Comment by QingQiuGeek** [comment]
您好，问题解决了吗，我这边也是false，什么情况下会是收不到rtp数据呢
