### ISSUE TITLE
[BUG]: RTMP url parse错误

### ISSUE THREAD

**Issue by TempoTian** [ZLMediaKit/ZLMediaKit#2298]
### 现象描述

RTMP 协议规定 在发送connet 命令时 tcurl定义如下，可以包含app instance
https://rtmp.veriskope.com/docs/spec/#72-command-messages
![image](https://user-images.githubusercontent.com/110106787/224610026-2b5720fe-f77c-4df5-9147-307be8b40758.png)

app instance和stream name是相同的定义，参考
https://docs.aws.amazon.com/medialive/latest/ug/origin-server-rtmp.html
Stream name. Also called application instance or app instance or stream key.

目前代码中直接保存tcUrl并于streamid拼接来查找有没有对应的stream导致查找错误

正确的做法是从tcUrl中提取出只包含appname的url然后进行拼接
例如下面的代码
```c
void RtmpSession::onCmd_play(AMFDecoder &dec) {
    dec.load<AMFValue>();/* NULL */
    // code to parse app url
    string app_url = _tc_url;
    string header  = string(RTMP_SCHEMA) + "://";
    size_t header_pos = header.size()-1;
    size_t stream_pos = _tc_url.rfind('/');
    size_t app_pos = _tc_url.rfind('/', stream_pos- 1);
    if (app_pos != header_pos) {
        app_url = app_url.substr(0, stream_pos);
    }
    cout << "Play app url:" << app_url << endl;
    _media_info.parse(app_url + "/" + getStreamId(dec.load<std::string>()));
    // code to parse url end
    _media_info._schema = RTMP_SCHEMA;
    doPlay(dec);
}
```

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
嗨 感谢您的反馈 您代码查看的这么仔细专业 能否进一步麻烦能否提个pr？

**Comment by yjkhtddx** [comment]
VLC测试，播放地址为:"rtmp://192.168.1.41:1935/live/test"时
connect命令交互时，tcUrl的值为:"rtmp://192.168.1.41:1935/live"
VLC为什么会在发送tcUrl时，故意裁掉test的用意是什么呢？
![image](https://user-images.githubusercontent.com/11830708/224633727-87dda1ad-902f-4b18-a5e7-c8441964b834.png)

**Comment by TempoTian** [comment]
> 嗨 感谢您的反馈 您代码查看的这么仔细专业 能否进一步麻烦能否提个pr？

**Comment by xia-chu** [comment]
先不关闭了 修复了这个问题再关吧

**Comment by TempoTian** [comment]
可以直接导入下面的patch
spec虽然有规定，但各个push/pull端可能实现的方式不大相同
用ngix rtmp， 带streamname和不带都是OK的

```txt
diff --git a/src/Rtmp/RtmpSession.cpp b/src/Rtmp/RtmpSession.cpp
index 9d8acf51..14d0931c 100644
--- a/src/Rtmp/RtmpSession.cpp
+++ b/src/Rtmp/RtmpSession.cpp
@@ -90,6 +90,13 @@ void RtmpSession::onCmd_connect(AMFDecoder &dec) {
         //defaultVhost:默认vhost
         _tc_url = string(RTMP_SCHEMA) + "://" + DEFAULT_VHOST + "/" + _media_info._app;
     } else {
+        size_t protocol_end  = _tc_url.find("://") + 2;
+        size_t stream_start = _tc_url.rfind('/');
+        size_t app_start = _tc_url.rfind('/', stream_start - 1);
+        if (app_start != protocol_end) {
+            // contain stream name part
+            _tc_url = _tc_url.substr(0, stream_start);
+        }
         auto pos = _tc_url.rfind('?');
         if (pos != string::npos) {
             //tc_url 中可能包含?以及参数，参见issue: #692
@@ -341,7 +348,7 @@ void RtmpSession::doPlayResponse(const string &err,const std::function<void(bool
         cb(false);
         return;
     }
-
+    
     //鉴权成功，查找媒体源并回复
     weak_ptr<RtmpSession> weak_self = dynamic_pointer_cast<RtmpSession>(shared_from_this());
     MediaSource::findAsync(_media_info, weak_self.lock(), [weak_self,cb](const MediaSource::Ptr &src){
```

**Comment by yjkhtddx** [comment]
![image](https://user-images.githubusercontent.com/11830708/224637637-7c448c79-1ef5-435a-a3b5-07c644f8e268.png)
是不是顺序搞错了，如果if (app_start != protocol_end) 成立，后面的问号都被裁剪掉了，还找啥子问号。

**Comment by TempoTian** [comment]
？一般用与认证，这个是之前代码就有的
认证可能也有两种url
rtmp://yourserver.tld:1935/user1/stream?livekey=UserKey1

rtmp://yourserver.tld:1935/user1?livekey=UserKey1

第一种提取只包含app的url ？ 滤掉了，第二种还在

**Comment by xia-chu** [comment]
已修复 感谢诸位
