### ISSUE TITLE
[技术咨询]请教一下webrtc如何测试推流呀

### ISSUE THREAD

**Issue by wangxiaoer3924** [ZLMediaKit/ZLMediaKit#2299]
我部署到我的ubuntu20.04系统上 
参考ffmpeg 推流 rtsp 命令成功推流后，浏览器登录 https://default.zlmediakit.com/webrtc/ 点击播放是没问题的，
但是我要是想推webrtc的流该如何操作呀，或者说这个webrtc的url是啥，我如何分享给别人使用呢

**Comment by xia-chu** [comment]
请用公网测试服务器测试吧：https://zlmediakit.com/webrtc/
