### ISSUE TITLE
[技术咨询]webrtc在一次会话同时传输多路视频流

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#2306]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
webrtc功能模块
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
您好，请问zlmediakit在一次webrtc会话中支持同时传输多路视频流吗？
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
支持simulcast多路推流
