### ISSUE TITLE
[技术咨询]webrtc支持同时传输多路视频流吗？

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#2307]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
webrtc功能模块
- 此处展开您咨询内容的描述
您好，请问zlm在一次webrtc会话中支持传输多路视频流吗？支持PlanB还是UnifiedPlan呢？

**Comment by xia-chu** [comment]
支持UnifiedPlan，不支持多视频mline，但是支持simulcast推流

**Comment by quxiaohui-debug** [comment]
如果我想要传输多路不同的视频流，就必须创建多个webrtc会话吗？

**Comment by quxiaohui-debug** [comment]
我更期待在一个webrtc会话中同时传输

**Comment by xia-chu** [comment]
> 如果我想要传输多路不同的视频流，就必须创建多个webrtc会话吗？

你说推流吗？

**Comment by quxiaohui-debug** [comment]
推流和拉流都需要

**Comment by quxiaohui-debug** [comment]
比如同时传输桌面流和摄像机的媒体流

**Comment by xia-chu** [comment]
你建议你用多peerconnection方案 这样最灵活

**Comment by xia-chu** [comment]
多视频mline方案 除非是多人视频会议 否则意义不大

**Comment by quxiaohui-debug** [comment]
感谢作者的答复，我再研究研究
