### ISSUE TITLE
[BUG]: 提示绑定端口失败

### ISSUE THREAD

**Issue by alex03226** [ZLMediaKit/ZLMediaKit#2310]
### 现象描述
调用 openRtpServer (port=32344) -> closeRtpServer() -> openRtpServer(port=34344)，概率会返回端口绑定失败。

### 如何复现?
模拟：postMan发送 openRtpServer (port=8888)，然后再发送一次 openRtpServer(8888)，windows没有提示失败，docker ubuntu20.4会提示 bind failed。

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
2023-03-15 21:24:56.747 I [event poller 23] Rtsp.cpp:393 getPortPair | got port from pool:32344-32345
2023-03-15 21:24:56.748 I [event poller 23] TcpServer.cpp:200 start_l | TCP server listening on [::]: 32344
2023-03-15 21:24:56.748 D [event poller 23] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/openRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 130
Content-Type : application/x-www-form-urlencoded
Host : 192.168.0.1:89
User-Agent : okhttp/4.10.0
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310141290&port=0&ssrc=115001013&enable_tcp=1
# response:
{
	"code" : 0,
	"port" : 32344
}


2023-03-15 21:24:57.337 I [event poller 12] RtpProcess.cpp:123 inputFrame | 13010100002000000115_31011500001310862468 192.168.18.216:26576 cfg frame
2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame
2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame
2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:273 inputFrame | 0115004464 192.168.18.66:32482 send key frame
2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013
2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013
    Last message repeated 256 times
2023-03-15 21:24:57.819 I [event poller 23] TcpServer.cpp:40 ~TcpServer | Close tcp server [::]: 32344
2023-03-15 21:24:57.819 I [event poller 23] Rtsp.cpp:402 operator() | return port to pool:32344-32345
2023-03-15 21:24:57.819 D [event poller 23] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/closeRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 95
Content-Type : application/x-www-form-urlencoded
Host : 192.168.0.1:89
User-Agent : okhttp/4.10.0
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310141290
# response:
{
	"code" : 0,
	"hit" : 1
}


2023-03-15 21:24:57.821 W [event poller 23] sockutil.cpp:396 bind_sock6 | Bind socket failed: address already in use
2023-03-15 21:24:57.821 D [event poller 23] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/openRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 149
Content-Type : application/x-www-form-urlencoded
Host : 192.168.0.1:89
User-Agent : okhttp/4.10.0
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&re_use_port=1&stream_id=13010100002000000115_31011500001310141290&port=32344&ssrc=0115008598&enable_tcp=1
# response:
{
	"code" : -400,
	"msg" : "Listen on :: 32344 failed: address already in use"
}
```
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
re_use_port设置为1





------------------ 原始邮件 ------------------
发件人: alex03226 ***@***.***&gt;
发送时间: 2023年3月16日 11:00
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [BUG]: 提示绑定端口失败 (Issue #2310)





 
现象描述
 
调用 openRtpServer (port=32344) -&gt; closeRtpServer() -&gt; openRtpServer(port=34344)，概率会返回端口绑定失败。
 
如何复现?
 
模拟：postMan发送 openRtpServer (port=8888)，然后再发送一次 openRtpServer(8888)，windows没有提示失败，docker ubuntu20.4会提示 bind failed。
 
相关日志或截图
  展开查看详细日志 
2023-03-15 21:24:56.747 I [event poller 23] Rtsp.cpp:393 getPortPair | got port from pool:32344-32345
 2023-03-15 21:24:56.748 I [event poller 23] TcpServer.cpp:200 start_l | TCP server listening on [::]: 32344
 2023-03-15 21:24:56.748 D [event poller 23] WebApi.cpp:250 http api debug |
 
request:
 
POST /index/api/openRtpServer
 
header:
 
Accept-Encoding : gzip
 Connection : Keep-Alive
 Content-Length : 130
 Content-Type : application/x-www-form-urlencoded
 Host : 192.168.0.1:89
 User-Agent : okhttp/4.10.0
 
content:
 
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;stream_id=13010100002000000115_31011500001310141290&amp;port=0&amp;ssrc=115001013&amp;enable_tcp=1
 
response:
 
{
 "code" : 0,
 "port" : 32344
 }
 
2023-03-15 21:24:57.337 I [event poller 12] RtpProcess.cpp:123 inputFrame | 13010100002000000115_31011500001310862468 192.168.18.216:26576 cfg frame
 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame
 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame
 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:273 inputFrame | 0115004464 192.168.18.66:32482 send key frame
 2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013
 2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013
 Last message repeated 256 times
 2023-03-15 21:24:57.819 I [event poller 23] TcpServer.cpp:40 ~TcpServer | Close tcp server [::]: 32344
 2023-03-15 21:24:57.819 I [event poller 23] Rtsp.cpp:402 operator() | return port to pool:32344-32345
 2023-03-15 21:24:57.819 D [event poller 23] WebApi.cpp:250 http api debug |
 
request:
 
POST /index/api/closeRtpServer
 
header:
 
Accept-Encoding : gzip
 Connection : Keep-Alive
 Content-Length : 95
 Content-Type : application/x-www-form-urlencoded
 Host : 192.168.0.1:89
 User-Agent : okhttp/4.10.0
 
content:
 
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;stream_id=13010100002000000115_31011500001310141290
 
response:
 
{
 "code" : 0,
 "hit" : 1
 }
 
2023-03-15 21:24:57.821 W [event poller 23] sockutil.cpp:396 bind_sock6 | Bind socket failed: address already in use
 2023-03-15 21:24:57.821 D [event poller 23] WebApi.cpp:250 http api debug |
 
request:
 
POST /index/api/openRtpServer
 
header:
 
Accept-Encoding : gzip
 Connection : Keep-Alive
 Content-Length : 149
 Content-Type : application/x-www-form-urlencoded
 Host : 192.168.0.1:89
 User-Agent : okhttp/4.10.0
 
content:
 
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;re_use_port=1&amp;stream_id=13010100002000000115_31011500001310141290&amp;port=32344&amp;ssrc=0115008598&amp;enable_tcp=1
 
response:
 
{
 "code" : -400,
 "msg" : "Listen on :: 32344 failed: address already in use"
 }
 


  
配置
  展开查看详细配置 配置内容...   
各种环境信息
  
代码提交记录/git commit hash: 

操作系统及版本: 

硬件信息: 

其他需要补充的信息:

**Comment by alex03226** [comment]
代码： SockUtil::listen 里面 setReuseable() 端口重用设置为了0
void TcpServer::start_l(uint16_t port, const std::string &host, uint32_t backlog) {
    if (!_socket->listen(port, host.c_str(), backlog)) {
        //创建tcp监听失败，可能是由于端口占用或权限问题
        string err = (StrPrinter << "Listen on " << host << " " << port << " failed: " << get_uv_errmsg(true));
        throw std::runtime_error(err);
    }


int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
    int fd = -1;
    int family = support_ipv6() ? (is_ipv4(local_ip) ? AF_INET : AF_INET6) : AF_INET;
    if ((fd = (int)socket(family, SOCK_STREAM, IPPROTO_TCP)) == -1) {
        WarnL << "Create socket failed: " << get_uv_errmsg(true);
        return -1;
    }

    setReuseable(fd, true, false);
    setNoBlocked(fd);
    setCloExec(fd);

**Comment by alex03226** [comment]
> re_use_port设置为1
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: alex03226 ***@***.***&gt; 发送时间: 2023年3月16日 11:00 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: Re: [ZLMediaKit/ZLMediaKit] [BUG]: 提示绑定端口失败 (Issue #2310) 现象描述 调用 openRtpServer (port=32344) -&gt; closeRtpServer() -&gt; openRtpServer(port=34344)，概率会返回端口绑定失败。 如何复现? 模拟：postMan发送 openRtpServer (port=8888)，然后再发送一次 openRtpServer(8888)，windows没有提示失败，docker ubuntu20.4会提示 bind failed。 相关日志或截图 展开查看详细日志 2023-03-15 21:24:56.747 I [event poller 23] Rtsp.cpp:393 getPortPair | got port from pool:32344-32345 2023-03-15 21:24:56.748 I [event poller 23] TcpServer.cpp:200 start_l | TCP server listening on [::]: 32344 2023-03-15 21:24:56.748 D [event poller 23] WebApi.cpp:250 http api debug | request: POST /index/api/openRtpServer header: Accept-Encoding : gzip Connection : Keep-Alive Content-Length : 130 Content-Type : application/x-www-form-urlencoded Host : 192.168.0.1:89 User-Agent : okhttp/4.10.0 content: secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;stream_id=13010100002000000115_31011500001310141290&amp;port=0&amp;ssrc=115001013&amp;enable_tcp=1 response: { "code" : 0, "port" : 32344 } 2023-03-15 21:24:57.337 I [event poller 12] RtpProcess.cpp:123 inputFrame | 13010100002000000115_31011500001310862468 192.168.18.216:26576 cfg frame 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:270 inputFrame | 0115004464 192.168.18.66:32482 send cfg frame 2023-03-15 21:24:57.337 I [event poller 12] RtpSender.cpp:273 inputFrame | 0115004464 192.168.18.66:32482 send key frame 2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013 2023-03-15 21:24:57.793 W [event poller 23] RtpServer.cpp:204 operator() | ssrc不匹配,rtp已丢弃:115008598 != 115001013 Last message repeated 256 times 2023-03-15 21:24:57.819 I [event poller 23] TcpServer.cpp:40 ~TcpServer | Close tcp server [::]: 32344 2023-03-15 21:24:57.819 I [event poller 23] Rtsp.cpp:402 operator() | return port to pool:32344-32345 2023-03-15 21:24:57.819 D [event poller 23] WebApi.cpp:250 http api debug | request: POST /index/api/closeRtpServer header: Accept-Encoding : gzip Connection : Keep-Alive Content-Length : 95 Content-Type : application/x-www-form-urlencoded Host : 192.168.0.1:89 User-Agent : okhttp/4.10.0 content: secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;stream_id=13010100002000000115_31011500001310141290 response: { "code" : 0, "hit" : 1 } 2023-03-15 21:24:57.821 W [event poller 23] sockutil.cpp:396 bind_sock6 | Bind socket failed: address already in use 2023-03-15 21:24:57.821 D [event poller 23] WebApi.cpp:250 http api debug | request: POST /index/api/openRtpServer header: Accept-Encoding : gzip Connection : Keep-Alive Content-Length : 149 Content-Type : application/x-www-form-urlencoded Host : 192.168.0.1:89 User-Agent : okhttp/4.10.0 content: secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&amp;re_use_port=1&amp;stream_id=13010100002000000115_31011500001310141290&amp;port=32344&amp;ssrc=0115008598&amp;enable_tcp=1 response: { "code" : -400, "msg" : "Listen on :: 32344 failed: address already in use" } 配置 展开查看详细配置 配置内容... 各种环境信息 代码提交记录/git commit hash: 操作系统及版本: 硬件信息: 其他需要补充的信息: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

设置为了1

**Comment by alex03226** [comment]
toolkit::bind_sock6(int, ...) 
toolkit::bind_sock(int, ...) sockutil.cpp:424
toolkit::SockUtil::listen(unsigned short, ...) sockutil.cpp:482
toolkit::Socket::listen(unsigned short, ...) Socket.cpp:499
toolkit::TcpServer::start_l(unsigned short, ...)  TcpServer.cpp:169
void toolkit::TcpServer::start<mediakit::RtpSession>(unsigned short, ...) TcpServer.h:53
mediakit::RtpServer::start(unsigned short, ...) 
openRtpServer(unsigned short, ...)

**Comment by alex03226** [comment]
我的猜想listen里面停止了re_use_port是，想防止：业务1本地打开了一个监听port=8888，业务2再次打开port=8888的监听，防止业务2收到了业务1的连接，

**Comment by xia-chu** [comment]
我数说openRtpServer接口支持re_use_port参数

**Comment by alex03226** [comment]
openRtpServer 接口我传的是 re_use_port=1的
我模拟的：
第一次：   port=8888&enable_tcp=1&stream_id=3&re_use_port=1&ssrc=11111
第二次：   port=8888&enable_tcp=1&stream_id=4&re_use_port=1&ssrc=11111

**Comment by alex03226** [comment]
日志里面的re_use_port没有提现出来，是因为，我直接吧re_use_port默认值改为了1

**Comment by alex03226** [comment]
修改 ZLToolKit代码，start里面新增了 re_use_port 参数
```
diff --git a/src/Network/Socket.cpp b/src/Network/Socket.cpp
index 709e32c..2945614 100644
--- a/src/Network/Socket.cpp
+++ b/src/Network/Socket.cpp
@@ -495,8 +495,8 @@ bool Socket::listen(const SockFD::Ptr &sock){
     return true;
 }
 
-bool Socket::listen(uint16_t port, const string &local_ip, int backlog) {
-    int sock = SockUtil::listen(port, local_ip.data(), backlog);
+bool Socket::listen(uint16_t port, const string &local_ip, bool re_use_port, int backlog) {
+    int sock = SockUtil::listen(port, local_ip.data(), re_use_port, backlog);
     if (sock == -1) {
         return false;
     }
diff --git a/src/Network/Socket.h b/src/Network/Socket.h
index cb47fc7..d40374c 100644
--- a/src/Network/Socket.h
+++ b/src/Network/Socket.h
@@ -301,7 +301,7 @@ public:
      * @param backlog tcp最大积压数
      * @return 是否成功
      */
-    virtual bool listen(uint16_t port, const std::string &local_ip = "::", int backlog = 1024);
+    virtual bool listen(uint16_t port, const std::string &local_ip = "::", bool re_use_port = false, int backlog = 1024);
 
     /**
      * 创建udp套接字,udp是无连接的，所以可以作为服务器和客户端
diff --git a/src/Network/TcpServer.cpp b/src/Network/TcpServer.cpp
index d404d93..a96a5e6 100644
--- a/src/Network/TcpServer.cpp
+++ b/src/Network/TcpServer.cpp
@@ -165,8 +165,8 @@ Session::Ptr TcpServer::onAcceptConnection(const Socket::Ptr &sock) {
     return session;
 }
 
-void TcpServer::start_l(uint16_t port, const std::string &host, uint32_t backlog) {
-    if (!_socket->listen(port, host.c_str(), backlog)) {
+void TcpServer::start_l(uint16_t port, const std::string &host, bool re_use_port, uint32_t backlog) {
+    if (!_socket->listen(port, host.c_str(), re_use_port, backlog)) {
         //创建tcp监听失败，可能是由于端口占用或权限问题
         string err = (StrPrinter << "Listen on " << host << " " << port << " failed: " << get_uv_errmsg(true));
         throw std::runtime_error(err);
diff --git a/src/Network/TcpServer.h b/src/Network/TcpServer.h
index bbd6d31..bb2819c 100644
--- a/src/Network/TcpServer.h
+++ b/src/Network/TcpServer.h
@@ -43,14 +43,14 @@ public:
     * @param backlog tcp listen backlog
     */
     template<typename SessionType>
-    void start(uint16_t port, const std::string &host = "::", uint32_t backlog = 1024) {
+    void start(uint16_t port, const std::string &host = "::", bool re_use_port = false, uint32_t backlog = 1024) {
         //Session创建器，通过它创建不同类型的服务器
         _session_alloc = [](const TcpServer::Ptr &server, const Socket::Ptr &sock) {
             auto session = std::make_shared<SessionType>(sock);
             session->setOnCreateSocket(server->_on_create_socket);
             return std::make_shared<SessionHelper>(server, session);
         };
-        start_l(port, host, backlog);
+        start_l(port, host, re_use_port, backlog);
     }
 
     /**
@@ -79,7 +79,7 @@ protected:
 private:
     void onManagerSession();
     Socket::Ptr createSocket(const EventPoller::Ptr &poller);
-    void start_l(uint16_t port, const std::string &host, uint32_t backlog);
+    void start_l(uint16_t port, const std::string &host, bool re_use_port, uint32_t backlog);
     Ptr getServer(const EventPoller *) const;
 
 private:
diff --git a/src/Network/sockutil.cpp b/src/Network/sockutil.cpp
index 8585933..9bc9ea4 100644
--- a/src/Network/sockutil.cpp
+++ b/src/Network/sockutil.cpp
@@ -467,7 +467,7 @@ int SockUtil::connect(const char *host, uint16_t port, bool async, const char *l
     return -1;
 }
 
-int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
+int SockUtil::listen(const uint16_t port, const char *local_ip, bool re_use_port, int back_log) {
     int fd = -1;
     int family = support_ipv6() ? (is_ipv4(local_ip) ? AF_INET : AF_INET6) : AF_INET;
     if ((fd = (int)socket(family, SOCK_STREAM, IPPROTO_TCP)) == -1) {
@@ -475,7 +475,11 @@ int SockUtil::listen(const uint16_t port, const char *local_ip, int back_log) {
         return -1;
     }
 
+#if 0   //20230316
     setReuseable(fd, true, false);
+#else
+    setReuseable(fd, true, re_use_port);
+#endif
     setNoBlocked(fd);
     setCloExec(fd);
 
diff --git a/src/Network/sockutil.h b/src/Network/sockutil.h
index 8a9d739..0d13086 100644
--- a/src/Network/sockutil.h
+++ b/src/Network/sockutil.h
@@ -69,7 +69,7 @@ public:
      * @param back_log accept列队长度
      * @return -1代表失败，其他为socket fd号
      */
-    static int listen(const uint16_t port, const char *local_ip = "::", int back_log = 1024);
+    static int listen(const uint16_t port, const char *local_ip = "::", bool re_use_port = false, int back_log = 1024);
 
     /**
      * 创建udp套接字
```

**Comment by alex03226** [comment]
修改zltoolkit代码

**Comment by xia-chu** [comment]
这个修改会有问题 比如说其他进程占用这个端口后 zlm也可以在这个端口上开启listen。
实际上“bind failed”错误有真的去找实质的原因吗？zlm只支持在close后的socket立马再listen的

**Comment by alex03226** [comment]
没有其它进程占用，docker分配了固定的32000-32500端口。
这个是概率问题。我的猜测是tcp端口在wait中，然后触发了新的，tcpserver，去绑定该端口。但这个端口又不是reuse方式，于是出现了，该问题。

**Comment by alex03226** [comment]
wvp同步请求的，调用close返回后再调用open的

wvp的日志(运行在同一台机器上的，时间一致)
```
	行 10243: 2023-03-15 21:24:57.818  INFO 7 --- [wvp-3410] c.g.iot.vmp.media.zlm.ZLMRESTfulUtils    : [访问ZLM] http://192.168.0.1:89/index/api/closeRtpServer 请求参数 <<< {stream_id=13010100002000000115_31011500001310141290}
	行 10252: 2023-03-15 21:24:57.821  INFO 7 --- [wvp-3410] c.g.iot.vmp.media.zlm.ZLMRESTfulUtils    : [访问ZLM] http://192.168.0.1:89/index/api/openRtpServer请求参数 <<< {re_use_port=1, stream_id=13010100002000000115_31011500001310141290, port=32344, ssrc=0115008598, enable_tcp=1}
```

zlm 日志 closeRtpServer的日志在 openRtpServer前面
```
2023-03-15 21:24:57.819 I [event poller 23] TcpServer.cpp:40 ~TcpServer | Close tcp server [::]: 32344
2023-03-15 21:24:57.819 I [event poller 23] Rtsp.cpp:402 operator() | return port to pool:32344-32345
2023-03-15 21:24:57.819 D [event poller 23] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/closeRtpServer
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=13010100002000000115_31011500001310141290
# response:
{
	"code" : 0,
	"hit" : 1
}


2023-03-15 21:24:57.821 W [event poller 23] sockutil.cpp:396 bind_sock6 | Bind socket failed: address already in use
2023-03-15 21:24:57.821 D [event poller 23] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/openRtpServer
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&re_use_port=1&stream_id=13010100002000000115_31011500001310141290&port=32344&ssrc=0115008598&enable_tcp=1
# response:
{
	"code" : -400,
	"msg" : "Listen on :: 32344 failed: address already in use"
}
```

**Comment by xia-chu** [comment]
那加下延时吧 `return port to pool:32344-32345` 说明已经释放端口了，你下一个接口调用才过了几毫秒而已。
而且为什么要重复使用同一个端口呢？你一次openRtpServer用的随机端口，第二次为什么不用随机端口呢？zlm在分配端口时，冷却期很长的，不会有这个问题

**Comment by alex03226** [comment]
这个问题主要出现在与级联的海康平台有关。海康平台有个现象或者叫bug更合适。
wvp  -> zlm   -> 返回端口 32000
wvp  -> 海康 -> ssrc=20000001
海康 -> wvp  -> ssrc=89000001
wvp  -> zlm  -> 关闭 32000
wvp  -> zlm  -> 绑定 32000
流程中因为 海康 回复的sdp时，未使用wvp告知的ssrc，于是触发wvp关闭端口，再打开端口。

**Comment by alex03226** [comment]
我认为主要原因在与 RtpServer.cpp: 183 中 tcp_server->start<RtpSession>(port, ip) 后面没有传入 re_use_port 参数导致，listen 代码里面没有 打开 re_use 开关。
listen() 中默认 setReuseable(fd, true, false) 中 re_use_port 默认是 false
于是我新增了 re_use_port 参数传入  listen 接口中。

**Comment by xia-chu** [comment]
现在zlmediakit新增updateRtpServerSSRC接口了 wvp已经适配了 所以这个问题就不存在了
#2286 #2390
