### ISSUE TITLE
[技术咨询]startSendRtp接口在tcp-rtp模式下使用同一个端口来发送音视频数据

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2311]
**咨询的功能模块**
- startSendRtp接口在tcp-rtp模式下使用同一个端口来发送音视频数据

**咨询的具体内容和问题**
- startSendRtp接口，当use_ps 为0时，有效。为1时，发送音频；为0时，发送视频；不传时默认为0。
在使用tcp发送发送rtp音视频数据时，需要调用一次startSendRtp发送视频(only_audio=0)，然后再调用一次startSendRtp发送音频(only_audio=1)
问题：
1.startSendRtp接口为什么要分别设置only_audio这个参数，用来区分音频和视频.
2.项目中需要再tcp-rtp模式下使用同一个端口来发送音视频数据,请问修改思路是怎样的。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
对接什么服务器需要同一个端口同时发送音视频es流？

**Comment by HalcyonHuang** [comment]
> 对接什么服务器需要同一个端口同时发送音视频es流？

内部使用的自研服务

**Comment by xia-chu** [comment]
你们内部服务器接收两个不同端口推流就行了 不要现在一个源端口就行 这个又机会不需要改动什么
