### ISSUE TITLE
[技术咨询]配置里ffmpeg.cmd中能否自定义添加%s

### ISSUE THREAD

**Issue by xinhaoliang** [ZLMediaKit/ZLMediaKit#2314]
**自定义ffmpeg命令模板**
- 比如我要添加不同的水印图片，%s -i %s -i **logo.png** -filter_complex 'overlay=main_w-overlay_w-10:main_h-overlay_h-10' %s
- 我想改成 s%.png 可以吗，是否有额外传入参数的地方

**Comment by xia-chu** [comment]
不可以 除非你自己改代码





------------------ 原始邮件 ------------------
发件人: xinhaoliang ***@***.***&gt;
发送时间: 2023年3月17日 18:14
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] 配置里ffmpeg.cmd中能否自定义添加%s (Issue #2314)





 
自定义ffmpeg命令模板
  
比如我要添加不同的水印图片，%s -i %s -i logo.png -filter_complex 'overlay=main_w-overlay_w-10:main_h-overlay_h-10' %s 

我想改成 s%.png 可以吗，是否有额外传入参数的地方
