### ISSUE TITLE
请问如何将RTMP流转换为RTSP流

### ISSUE THREAD

**Issue by FredLiu0512** [ZLMediaKit/ZLMediaKit#2315]
我用docker安装了ZLMediaKit，希望能够将RTMP流转换成RTSP流，但是我没有找到相关文档。
请问能不能帮我一下，或者告诉我相关文档的URLs？

**Comment by xia-chu** [comment]
- 1、先把wiki看完，可以执行看下addStreamProxy接口和url规则篇。
- 2、提issue请按照模板提。
