### ISSUE TITLE
[技术咨询] Record buffer

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#2318]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

API startRecord / MP4Recorder

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

I am using API startRecord to record stream when an event (of other system) happen. It's work fine.
Can i buffer some video frames (or 2-3 seconds) for when call startRecord, MP4Recorder will start reccord from 2-3 seconds before ?

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
No，we can not do that now, why do you start record at the beginning?

**Comment by pubpy2015** [comment]
Because I want to record before and after the event. This function same with some NVR:
![ảnh](https://user-images.githubusercontent.com/59004953/226533731-bbe7b175-069a-4524-b40a-3baf3fa2fd35.png)

**Comment by xia-chu** [comment]
This function requires secondary development, and I have done similar work before

**Comment by pubpy2015** [comment]
can you tell me how to do that ?

**Comment by xia-chu** [comment]
I saved some frame data in memory

**Comment by pubpy2015** [comment]
Yes,
Can you tell me where is in ZlMediaKit i can save frame ?

**Comment by xia-chu** [comment]
You can cache frame in MultiMediaSourceMuxer::onTrackFrame

**Comment by pubpy2015** [comment]
Thank,
Now i can pre-record stream by create 2 list:
`toolkit::List<Frame::Ptr> buffer_frames;
toolkit::List<Frame::Ptr> recording_frames;`

in MultiMediaSourceMuxer::onTrackFrame i will add frame to list:
`auto mp4 = _mp4;
    if (mp4) {
        //ret = mp4->inputFrame(frame) ? true : ret;
        recording_frames.push_front(frame);
        ret = true;

    } else {
        if (buffer_frames.size() > 100)
            buffer_frames.pop_back();
        buffer_frames.push_front(frame);
    }`

when call startRecord => start a timer for recording all frames from buffer_frames and recording_frames:
`auto mp4 = _mp4;
    if (mp4) {
        if (buffer_frames.size() > 0) {
            InfoL << "buffer_frames: " << buffer_frames.size();
            Frame::Ptr frame = buffer_frames.back();
            mp4->inputFrame(frame);
            buffer_frames.pop_back();
        } else {
            if (recording_frames.size() > 0) {

                InfoL << "recording_frames: " << recording_frames.size();
                Frame::Ptr frame = recording_frames.back();
                mp4->inputFrame(frame);
                recording_frames.pop_back();
            }
        }
    }`

**Comment by pubpy2015** [comment]
I am buffer 100 frames for pre-record.
Can i dynamic set this param for each stream ?

**Comment by xia-chu** [comment]
You can add record length param in `strartRecord` http api, or add it in `ini config file [protocol] field`。

**Comment by xia-chu** [comment]
And maybe you need add it in https://github.com/ZLMediaKit/ZLMediaKit/blob/master/src/Common/MediaSource.h#L207

**Comment by xia-chu** [comment]
And when you cache frame in MultiMediaSourceMuxer, you need pay attention to `video gop start position`, such as `sps/pps/idr`

**Comment by pubpy2015** [comment]
> And when you cache frame in MultiMediaSourceMuxer, you need pay attention to `video gop start position`, such as `sps/pps/idr`, because mp4 record must start at `video gop start position`

You mean I have to check if the first frame is an I-Frame at the start of the recording?

**Comment by xia-chu** [comment]
> > And when you cache frame in MultiMediaSourceMuxer, you need pay attention to `video gop start position`, such as `sps/pps/idr`, because mp4 record must start at `video gop start position`
> 
> You mean I have to check if the first frame is an I-Frame at the start of the recording?

No, you don't usually need that, but if you don't judge like that, it will waste more memory, and many of those 100 frames are usually not saved

**Comment by xia-chu** [comment]
```c++
static inline bool isKeyFrame(const Frame::Ptr &frame) {
    return frame->keyFrame() || frame->configFrame();
}

void saveFrame(const Frame::Ptr &frame) {
    _frame_cache.emplace_back(frame);
    if (frame->getTrackType() == mediakit::TrackVideo) {
        _decoder->inputFrame(frame, false, true);
        if (frame->keyFrame()) {
            //遇到关键帧才判断是否需要移除多余的帧，降低cpu占用率
            eraseFrontGop();
        }
        for (auto it = _tasks.begin(); it != _tasks.end();) {
            auto &task = it->second;
            task.muxer->inputFrame(frame);
            if (task.stamp.relativeStamp(frame->dts()) >= (int64_t)task.video_front_ms) {
                task.video_front_ms = std::numeric_limits<decltype(task.video_front_ms)>::max();
                it = _tasks.erase(it);
                continue;
            }
            ++it;
        }
    }
    if (_frame_cache.size() > 1024 * 4) {
        // 防止内存溢出
        _frame_cache.clear();
        ErrorL << "Frame cache overflow!";
    }
}

void eraseFrontGop() {
    bool last_is_key = false;
    DeltaStamp stamp;
    for (auto it = _frame_cache.rbegin(); it < _frame_cache.rend(); ++it) {
        if ((*it)->getTrackType() != TrackVideo) {
            continue;
        }
        stamp.relativeStamp((*it)->dts());
        if (isKeyFrame(*it)) {
            last_is_key = true;
            continue;
        }

        // 时间是递减的，所以要取正值
        if (last_is_key && (-stamp.relativeStamp()) >= (int64_t)_video_back_ms) {
            // 距离上一个关键帧最近的帧
            _frame_cache.erase(_frame_cache.begin(), it.base());
            break;
        }
        last_is_key = false;
    }
}

void saveFile(const string &file, const FileTask::onFile &cb, size_t video_front_ms) {
    CHECK(!file.empty() && cb);
    weak_ptr<MultiMediaSourceMuxer> weak_self = shared_from_this();
    _poller->async_first([weak_self, file, cb, video_front_ms]() {
        auto strong_self = weak_self.lock();
        if (!strong_self) {
            return;
        }
        auto pr = strong_self->_tasks.emplace(file, FileTask {});
        if (!pr.second) {
            WarnL << "Save file task existed: " << file;
            return;
        }
        auto &task = pr.first->second;
        task.muxer = std::make_shared<MP4Muxer>();
        task.on_file = cb;
        task.video_front_ms = video_front_ms;

        // 先保持前20秒视频
        task.muxer->openMP4(file);
        for (auto &track : strong_self->_tracks) {
            if (track) {
                task.muxer->addTrack(track);
            }
        }
        task.muxer->addTrackCompleted();
        //再次移除多余的帧，确保不多录制视频
        strong_self->eraseFrontGop();
        for (auto &frame : strong_self->_frame_cache) {
            task.muxer->inputFrame(frame);
        }
    });
}

**Comment by pubpy2015** [comment]
Thank you very much.
I am closing this, if there is any problem, I will ask you later.
