### ISSUE TITLE
[技术咨询]WebRTC在集群中的部署方式

### ISSUE THREAD

**Issue by AHAOAHA** [ZLMediaKit/ZLMediaKit#2319]
**ZLMediaKit作为WebRTC推流服务器在集群中如何部署**

我遇到的问题是ZL在集群中部署后，生成的SDP信息（answer）中的候选地址为pod在集群内网中的ip地址，所以在外网的浏览器无法通过sdp中的地址与zl建立ice连接。

首先，我通过nodeport向公网开放了rtp udp&tcp的服务端口，将zl中rtc.externIP这个配置修改为一个公网的域名，通过域名+端口的方式，浏览器可以与内网的zl成功建立ice连接，但当pod的个数增加时（>=2），由于生成sdp时，在特定pod上生成了session信息，但建立ice连接时，域名+端口的方式不保证刚好连接建立到了session所在的pod中，导致连接失败。

想咨询的问题有：
- 当zl作为webrtc推流服务器部署时，通常的做法都是单实例部署吗？
- webrtc推流时，溯源模式理论上是否可以实现？

非常感谢！

**Comment by xia-chu** [comment]
当然你可以自研rtc代理服务器，我已经做了，可以给你一张图片参考下：
![图片](https://user-images.githubusercontent.com/11495632/226561681-81ac2c87-b18a-4927-844b-5b2bf96da85d.png)

**Comment by AHAOAHA** [comment]
在内网中部署一个stun服务器，客户端推流生成offer时使用这个stun服务器产生公网地址，是否也可以实现nat这个流程呢？

**Comment by xia-chu** [comment]
不可以 你要共享公网地址 就要自研rtc代理服务器

**Comment by Lcmasdf** [comment]
上图中的rtc proxy 是否可以简化为ice-proxy

**Comment by JeffreyWang873670235** [comment]
> 公网ip+端口
如果直接放meida server的话，由于前面的NAT或者负载均衡会随机选择一个media server来推流，会无法保证DTLS连接的建立和推送的流固定到一台media 上。现在用的rtc proxy其实就相当于一个无状态的集群，负载均衡随意连到哪个上面都行，由rtc proxy根据一定的规则保证请求打到后面相同的一台media server上。 我这个理解应该是对的吧？
