### ISSUE TITLE
解析ps异常

### ISSUE THREAD

**Issue by kendn1993** [ZLMediaKit/ZLMediaKit#2326]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- rtp推流无法成功

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 
![image](https://user-images.githubusercontent.com/27141040/227404685-652de19f-f490-46aa-af90-abc102850f58.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
这个是触发了第三方库的断言 (assert) zlm把断言hook了并且用抛异常的方式来解决程序退出的问题

**Comment by xia-chu** [comment]
你可以把触发断言的哪句代码注释掉试试：
![图片](https://user-images.githubusercontent.com/11495632/227409072-1dc2eca3-1443-4784-b753-3bdc8dd0569b.png)

**Comment by kendn1993** [comment]
好的 ,感谢
