### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by SCKCZJ2018** [ZLMediaKit/ZLMediaKit#2328]
你好，我想咨询一下，如何使用ZLMediaKit提供的C API推流。
我在Wiki和test程序中没有找到合适的用例。
目前我参照test程序和Issue中答复的内容，写了如下的程序，但是evnets listen也没有通知，期间函数调用也没有错误。
![image](https://user-images.githubusercontent.com/29282370/227444949-1e01348c-44ce-4117-b044-6498d8e0c90e.png)

**Comment by xia-chu** [comment]
提issue时请按照模板格式并添加标题，谢谢！
