### ISSUE TITLE
[技术咨询] RTP推流视频播放时会两秒一卡

### ISSUE THREAD

**Issue by zoushuanglong** [ZLMediaKit/ZLMediaKit#2330]
**咨询的功能模块**
- GB28181 RTP推流

**咨询的具体内容和问题**
- 接收设备的RTP推流之后, 播放媒体服务FLV格式的流会两秒一卡, 就是会卡一秒, 然后再快速播放两秒(见下方的gif时间), 使用RTP导出功能导出.video与.mp2文件, 再使用ffplay播放这两个文件, .mp2后缀文件的播放速度是正常的, 但是.video后缀文件就加速播放了

![CPT2303241757-580x400](https://user-images.githubusercontent.com/23564919/227489951-673a8ec9-1a31-40ea-8415-b1ad3bb40e4f.gif)

dump下来的三个文件
.rtp: .video. mp2文件下载地址: https://www.wenshushu.cn/t/aswykitx4sJhGCPH

**Comment by xia-chu** [comment]
flv的时间戳完全来自mpeg容器，所以如果出现这个问题，那么一般是这个设备产生的流就有问题，如果只是个别设备这样，我认为没必要关注。另外你可以升级下zlm试试，看看问题是否还存在。
