### ISSUE TITLE
[技术咨询]咨询下集群的回源策略

### ISSUE THREAD

**Issue by wuchingyy** [ZLMediaKit/ZLMediaKit#2331]
假设我部署了10个源站（用作推流），边缘节点上把10个源站都配置好，当播放器朝边缘节点拉流时是挨个源站串行的回源还是并行的？
如果是串行的估计会影响到开播速度

wiki里面提到的集群回源只有两个参数，一个是重试次数，一个是超时时间

另外，由于有多个源站，如果源a和源b都存在相同的app和stream的话，边缘是会匹配上其中一个就拉流的对么？

**Comment by xia-chu** [comment]
mk_media_input_h264 后会触发MediaSource注册事件，可以通过mk_media_set_on_regist接口监听，触发这个事件后，你可以通过mk_media_start_send_rtp接口发送ps rtp流

**Comment by xia-chu** [comment]
回源采用轮训方案

**Comment by wuchingyy** [comment]
那如果源流是在编号10的机器上，边缘节点岂不是要到最后一个才会查询到对应的流？这样会影响了观看体验吧？

**Comment by xia-chu** [comment]
你那么多源站 而且流还只在其中一个实例上 那这说明你的架构设计就有问题。

**Comment by xia-chu** [comment]
如果是这种情况 你就应该自己对接http api和hook，zlm触发stream not found hook事，你查询redis或数据库再调用zlm的addStreamProxy接口

**Comment by wuchingyy** [comment]
> 你那么多源站 而且流还只在其中一个实例上 那这说明你的架构设计就有问题。

我想的是说，推流端一个流对应一个源站，目的是为了减少带宽压力，假设一个源站我们设计限制50个推流端，设置10个源站可以接受500个推流，所以会有这个情况

至于后面提到的方案，通过hook来处理这个情况，我感觉是可以的，就不知道会不会引起延迟问题

**Comment by xia-chu** [comment]
你说的延迟是秒开延迟 只要不是太大 不会影响用户体验。
另外 你一个源站才10个流 是不是对源站的理解有误啊？哪有这样使用源站的。
源站一般很多流的，你这样搞很多个源站，那边缘站怎么知道再哪里？轮询不要时间吗？
