### ISSUE TITLE
[技术咨询]在H264/H265添加ps头后通过RTP推流的实现方法

### ISSUE THREAD

**Issue by MissionCompleted** [ZLMediaKit/ZLMediaKit#2333]
**咨询的功能模块**

想开发C API用从硬件拿到的H264数据加PS头后推PS-RTP流的应用

**咨询的具体内容和问题**

用C API拿到H264数据加PS头后推RTP流,数据加头后直接用mk_media_input_h264/5会推送失败,如果我的场景就是打算这么用有没有什实现思路?

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
mk_media_input_h264 后会触发MediaSource注册事件，可以通过mk_media_set_on_regist接口监听，触发这个事件后，你可以通过mk_media_start_send_rtp接口发送ps rtp流

**Comment by MissionCompleted** [comment]
> mk_media_input_h264 后会触发MediaSource注册事件，可以通过mk_media_set_on_regist接口监听，触发这个事件后，你可以通过mk_media_start_send_rtp接口发送ps rtp流

我按照你说的试了一下,发现目标机器上确实可以稳定的收到RTP包.我的场景是想从编码器拿到h264数据数据后加上PS头再喂给mk_media_input_h264,这样好像在要推给的那台机器上抓不到RTP包了,不知道H264数据加PS头以后调mk_media_start_send_rtp推RTP这种场景通过CAP好不好实现?

**Comment by xia-chu** [comment]
既然zlm实现ps容器封装 你为什么要多此一举呢？

**Comment by MissionCompleted** [comment]
> 既然zlm实现ps容器封装 你为什么要多此一举呢？

因为我想用来做一个GB推流客户端,仔细看了一下没想到怎么加自定义GB头的地方,麻烦指导一下?

**Comment by MissionCompleted** [comment]
> > 既然zlm实现ps容器封装 你为什么要多此一举呢？
> 
> 如果我想用来做一个GB推流客户端,是不是得在PSEncoder里面想办法增加我自己定义的头?

**Comment by xia-chu** [comment]
你要自定义ps头可以修改第三方库media-server库

**Comment by MissionCompleted** [comment]
> 你要自定义ps头可以修改第三方库media-server库

好的这么修改应该能满足我的需求！！
