### ISSUE TITLE
[技术咨询]webrtc播放

### ISSUE THREAD

**Issue by ketaxiang** [ZLMediaKit/ZLMediaKit#2336]
**咨询的功能模块**
- webrtc播放

**咨询的具体内容和问题**
- 最近看到有webrtc方面的优化，所以从docker拉取了最新镜像进行更新，然后发现原来播放流畅的画面，现在出现了非常频繁的跳帧现象，想请教一下是什么原因，谢谢！

**Comment by ketaxiang** [comment]
谢谢！换了根网线后没再出现跳帧。现在发现移动的物体有时候会出现残影；另外播放的时候有时候会遇到画面停止，但是我抓包看过，视频流一直在传输中，然后不管它，有时候又能回复画面播放。请教一下原因，怎么排查。谢谢！

**Comment by ketaxiang** [comment]
谢谢！换了根网线后没再出现跳帧。现在发现移动的物体有时候会出现残影；另外播放的时候有时候会遇到画面停止，但是我抓包看过，视频流一直在传输中，然后不管它，有时候又能回复画面播放。请教一下原因，怎么排查。谢谢！

**Comment by xia-chu** [comment]
我提了3个问题 你都没回答我 你给我的信息严重不足 我无法答复

**Comment by ketaxiang** [comment]
1、是内网环境，未做过相关测试；我会尝试将https://zlmediakit.com/webrtc/部署到内网zlm服务下试一下。
2、因为一些原因不能录制视频。
3、是国标平台推送的实时视频流到zlm，然后取的rtc地址进行播放，原平台视频都是正常的。
谢谢！

**Comment by xia-chu** [comment]
那zlmediakit有打印丢包日志吗？

**Comment by ketaxiang** [comment]
有时候会打印丢包，相对于播放时常算个别吧。将官方的webrtc测试页面部署内网后进行测试，有同样的问题移动物体有时候会出现残影现象。

> 那zlmediakit有打印丢包日志吗？

**Comment by xia-chu** [comment]
可以播放器rtsp协议： ffplay -i rtsp://xxxx/rtp/ssrc -rtsp_transport tcp

如果ffplay没报解码失败日志 说明没丢包 mediakit没问题

**Comment by xia-chu** [comment]
或者用zlm的dump功能 把rtp dump出文件供我分析下

**Comment by ketaxiang** [comment]
> 可以播放器rtsp协议： ffplay -i rtsp://xxxx/rtp/ssrc -rtsp_transport tcp
> 
> 如果ffplay没报解码失败日志 说明没丢包 mediakit没问题

webrtc和rtsp同时开着有10分钟左右，期间ffplay有过一次解码报错，总体正常；webrtc画面有过多次移动物体残影，同时的ffplay画面正常。

**Comment by xia-chu** [comment]
那说明你这个流的时间戳可能有点问题 时间戳有问题 rtsp基本不影响解码 但是会影响webrtc解码
