### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by 1085665987** [ZLMediaKit/ZLMediaKit#2339]
**咨询的功能模块**
RESTful接口getServerConfig

**咨询的具体内容和问题**
通过RESTful接口setServerConfig设置之后，但是RESTful接口getServerConfig返回的是原ZML初始化配置文件的内容
![问题](https://user-images.githubusercontent.com/57886182/228172672-370cf3e9-7d8b-4dd4-829b-4feddbc3115c.png)

**Comment by xia-chu** [comment]
提issue时请按照模板格式并添加标题，谢谢！
