### ISSUE TITLE
拉流播放出现花屏和卡顿

### ISSUE THREAD

**Issue by wangdemon** [ZLMediaKit/ZLMediaKit#2341]
**咨询的功能模块**
- 局域网下，zlmediakit  拉流播放出现花屏和卡顿

**咨询的具体内容和问题**
- zlmediakit部署在ubuntu，推流使用ffmpeg推流本地视频，推流和zlmediakit服务器，在同一个主机上
- 局域网下，在wins上，使用VLC和ffplay拉流播放，均会出现花屏和卡顿。
- zlmediakit使用master, hash值是5cdaf98，看下图
![1](https://user-images.githubusercontent.com/20681339/228184606-9d5de61a-7c5a-4610-9269-1e4b191361c2.png)

- 不存在网络的问题，因为服务器和拉流客户端在通过网线连接同一个路由器。
- 可以看下面演示视频

[视频链接](https://www.youtube.com/watch?v=5BtgGapyxoc)

**Comment by wangdemon** [comment]
> 

加上-rtsp_transport tcp后，播放不花屏了，但是还是有卡顿

可以看下面播放拉流视频效果

https://user-images.githubusercontent.com/20681339/228191181-747b8fc2-ce9e-4299-b164-5fdb4ddb1512.mp4

**Comment by xia-chu** [comment]
有没有可能你推流就是卡顿的？rtsp推流可是直接代理

**Comment by wangdemon** [comment]
> 有没有可能你推流就是卡顿的？rtsp推流可是直接代理

那怎么判断推流是否卡顿？

**Comment by xia-chu** [comment]
你安装个live555试试

**Comment by wangdemon** [comment]
好的，谢谢大佬。
