### ISSUE TITLE
[技术咨询] 如何使用API函数推送内存中的音视频

### ISSUE THREAD

**Issue by dchld** [ZLMediaKit/ZLMediaKit#2343]
咨询相关接口函数调用。
已经通过某种方式将摄像机的码流保存到了内存中，需要调用哪些接口函数将音视频码流推送给ZLM media server。调用流程如何

**Comment by xia-chu** [comment]
- 可以参考这个[范例](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/api/tests/h264_media_server.c)来学习怎么产生一个MediaSource。
- 可以参考这个[范例](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/api/tests/pusher.c) 学习怎么把MediaSource推流到rtsp/rtmp服务器。
