### ISSUE TITLE
[技术咨询] webrtc只能用系统的video控件吗？

### ISSUE THREAD

**Issue by huguodong** [ZLMediaKit/ZLMediaKit#2347]
**咨询的功能模块**
webrtc

**咨询的具体内容和问题**
webrtc只能用系统的video控件吗？我想用第三方播放器播放要怎么办呢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
需要遵循zlm的webrtc sdp交换流程，rtc没有统一的播放器，各个服务器播放器都不一样

**Comment by xia-chu** [comment]
@huguodong 补充了一个webrtc的[文档](https://github.com/ZLMediaKit/ZLMediaKit/wiki/webrtc%E4%BF%A1%E4%BB%A4%E4%BA%A4%E4%BA%92%E6%A0%BC%E5%BC%8F) 你可以看看
