### ISSUE TITLE
[技术咨询] RTP推流丢包问题

### ISSUE THREAD

**Issue by 513571357** [ZLMediaKit/ZLMediaKit#2348]
**咨询的功能模块**
- 使用wvp录像文件下载时，文件无法正常保存。

**咨询的具体内容和问题**
-zllog文件中报出
CommonRtp.cpp:53 inputRtp | rtp丢包:23727 -> 23732
RtpReceiver.h:168 output | packet dropped: 24186 -> 26131, latest seq: 26132,
 jitter buffer size: 1, jitter buffer ms: 1
2023-03-29 18:26:53.629 W [MediaServer] [84628-event poller 2] RtpReceiver.h:168 output | packet dropped: 36392 -> 36534, latest seq: 36649, 
jitter buffer size: 115, jitter buffer ms: 28等异常丢包信息，但是抓包查看并没有seq丢失或乱序问题

想请问一下需要在哪方面排查问题

![image](https://user-images.githubusercontent.com/54172308/228512721-6052e0f7-5526-406d-adc8-bd511290895e.png)
![image](https://user-images.githubusercontent.com/54172308/228512828-d82c34f2-b57d-4579-9ff9-57e4065b481b.png)

**Comment by xia-chu** [comment]
可以参考此[issue](https://github.com/ZLMediaKit/ZLMediaKit/issues/1221) 修改系统内核参数：/proc/sys/net/core/rmem_max

**Comment by 513571357** [comment]
> MP4录像需要写mp4文件 会存在磁盘io的问题，磁盘io是阻塞的，可能会阻塞网络线程比较长时间，那么这种情况下就可能导致udp接收不及时从而socket读buffer溢出而丢包。 这种问题可以通过以下几种方式定位：
> 
> * 1、MP4保存目录设置为内存tmpfs， 这样提高文件io速度，验证下是否确实是阻塞io导致丢包。
> * 2、减少视频路数，看看是否降低丢包概率。
> * 3、提高内核socket 读buffer上限参数到4MB。
> 
> 另外，需要您补充下抓包是在服务器上进行的吗？

目前是zl部署在虚拟机ubuntu的环境，抓包是在zl同环境下抓的，并且测试只有一个视频路数，测试下载文件的大小最低为60M左右。
经通过1、3的做法，日志中偶然出现CommonRtp.cpp:53 inputRtp | rtp丢包这类报错，但是RtpReceiver.h:168 output | packet dropped:这种提示还是有。
wvp下载时会设置Mp4_max_second参数为10s，我把它改大点或去掉可以减少异常次数，但是如果下载文件超过100M以上依旧会出现packet dropped现象

**Comment by xia-chu** [comment]
mp4_max_second这个参数理论上不会影响文件io性能的
