### ISSUE TITLE
【技术咨询】对摄像头的RTSP音频流打时间戳的代码在哪里？

### ISSUE THREAD

**Issue by honesty2023** [ZLMediaKit/ZLMediaKit#2349]
**咨询的功能模块**
- 对RTSP拉流推流时对音频打时间戳的具体代码

**咨询的具体内容和问题**
- 我自己代码从摄像头拉流以后打音频时间戳时，对一些品牌的摄像头打的时间戳经常出错，想借鉴学习一下ZLM是怎么对RTSP流打音频的时间戳的，麻烦告知具体代码的位置，谢谢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
zlm作为流媒体服务器 只负责分发 不产生数据，所以zlm一般情况不会去产生时间戳，时间戳都是从上游来的。
当然zlm支持开启时间戳覆盖，可以根据接收时间打时间戳，但是我不建议你采用这种方式，这种方式是不得已而为之。

一般来说，摄像头的时间戳是在采集yuv/rgb时就产生了，这个时间戳其实就是系统时间戳，不过可能经过了取相对值和转换时间戳单位操作，然后再把数据拿去编码，最后协议打包。

很多开发者对时间戳了解不深刻，往往把原始时间戳弄丢了，然后再编码后生成时间戳，这是不科学的，因为编码有时间延迟，而且输出还不平滑，如果编码器一次性输出多帧P帧 还会导致多帧P帧时间戳相同，这种情况会导致解码异常花屏或播放不同步或不流畅。

**Comment by xia-chu** [comment]
时间戳对流媒体来说非常重要，它的重要程度不亚于视频数据本身，一定不要把原始时间戳弄丢了，否则恢复起来非常困难

**Comment by honesty2023** [comment]
我本来计划是把摄像头的RTSP流推给ZLM，让ZLM对音频G711转码为AAC，结果发现从ZLM拉TS流播放时只有视频没有声音（修改时间戳、音频转码、静音开关三个都打开了）。所以现在打算在推流到ZLM之前我对原始的音频流在把G711转为AAC时自己打时间戳，所以请教一下，ZLM打时间戳的代码是哪个文件，我参考一下试试。

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/blob/8b970763725249c4db49c31e5709a195c17cb83e/src/Common/MultiMediaSourceMuxer.cpp#LL415C34-L415C44
