### ISSUE TITLE
[技术咨询] ZLM拉流代理rtsp流，无法正常获取到流

### ISSUE THREAD

**Issue by DrugHua** [ZLMediaKit/ZLMediaKit#2352]
**咨询的功能模块**
- 拉流代理

**咨询的具体内容和问题**
- ZLM拉流代理rtsp流，无法正常获取到流。通过ffplay看传进去的rtsp流会给301状态码重定向到新的流地址，但是zlm好像还是反复在拉重定向前的流，大佬，这种情况应该如何处理。

![301](https://user-images.githubusercontent.com/61667555/229079908-50d7f057-0c59-4faf-920b-a204a402c871.png)
![zlm](https://user-images.githubusercontent.com/61667555/229079928-1a9cded8-ddb6-4c5e-9f17-b06a558024eb.png)

**Comment by xia-chu** [comment]
zlm 支持301的：
<img width="1157" alt="图片" src="https://user-images.githubusercontent.com/11495632/229084941-a34a8d65-469d-43c3-8a52-4f73dc4e96da.png">

**Comment by xia-chu** [comment]
为什么不用rtsp over tcp模式拉流 而是要用udp模式？
