### ISSUE TITLE
[技术咨询] "转协议是否开启音频"选项打开后，ZLM拉流代理rtsp流,G711a音频是否会转aac

### ISSUE THREAD

**Issue by dchld** [ZLMediaKit/ZLMediaKit#2353]
**咨询的功能模块**
  音频，代理拉流转协议

**咨询的具体内容和问题**
 在配置文件中将  "转协议是否开启音频"选项打开（enable_audio=1）。用ZLM代理拉RTSP流，并转为TS流播放出去，ZLM是否会将源RTSP流中G711A音频转码为AAC格式音频放到输出的TS流中。

 我最初希望的是，用ZLM代理拉RTSP流（音频G711A）后，用VLC播放ZLM服务器输出的对应的TS流，VLC熊播放出声音（ZLM对音频进行转码为AAC格式）。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
ts默认不支持g711的 所以播放器不支持

**Comment by xia-chu** [comment]
zlm也默认不会转码的
