### ISSUE TITLE
[BUG] lambda 表达式中捕获的参数在多线程函数执行时已经失效,导致段错误

### ISSUE THREAD

**Issue by lifeng1994** [ZLMediaKit/ZLMediaKit#2354]
```c++
void RtspSession::onAuthDigest(const string &realm,const string &auth_md5)
{
	weak_ptr<RtspSession> weak_self = dynamic_pointer_cast<RtspSession>(shared_from_this());
    onAuth invoker = [realInvoker,weak_self](int blogin){
auto strong_self = weak_self.lock();
};

    if(!NoticeCenter::Instance().emitEvent(Broadcast::kBroadcastOnRtspAuth, _media_info, realm, username,nonce,uri,response, false, invoker, static_cast<SockInfo &>(*this))){}
}
```
在RtspSession.cpp中截取如上代码段作为参考：
复现环境：
监听的Broadcast::kBroadcastOnRtspAuth事件的处理函数中，出于某种原因需要，将 lambda移交到其它线程线程处理，移交后立即返回，随后在其它线程处理invoker调用时，出现weak_self.lock(）调用段错误，或weak_self.lock(）非空但实际已经是无效值，导致后面执行的操作出现段错误退出。
此处为什么 weak_self会失效原因分析：
 由于移交lambda函数到其它线程后立即返回，导致onAuthDigest()函数执行结束， weak_self作为onAuthDigest作用域内的局部变量生命周期结束，因此此处捕获的weak_self是一个无效值了。

**Comment by xiongguangjie** [comment]
你改了代码？？？ 这个lambda 表达式回调声明有问题，你看没修改过的源码看看

**Comment by lifeng1994** [comment]
> 你改了代码？？？ 这个lambda 表达式回调声明有问题，你看没修改过的源码看看

修改过，简单验证把weak_self 声明为static运行即正常了

**Comment by xia-chu** [comment]
我只能告诉你 zlm原代码没问题 你修改出的bug除非能把patch粘贴上来 否则我们不帮你找bug。

**Comment by xia-chu** [comment]
另外`NoticeCenter::Instance().emitEvent(Broadcast::kBroadcastOnRtspAuth...` 的参数列表你做了修改 但是你却没修改对应的`BroadcastOnRtspAuthArgs`宏 导致触发事件和接收事件的代码不一致，肯定要出问题啊，否则我们吃了没事定义`BroadcastOnRtspAuthArgs`宏干啥？

**Comment by xia-chu** [comment]
另外 你不star本项目 就不要提issue ok?  你自己改成bug了 提issue说我们代码有bug合适吗？

**Comment by lifeng1994** [comment]
> 另外 你不star本项目 就不要提issue ok? 你自己改出bug了 提issue说我们代码有bug合适吗？

很抱歉没有先start。关注了这个项目很久,一直想把这个流媒体移植到我们工程中，最近才有时间实施。
我需要把认证信息传到其它模块进行认证，所以对于BroadcastOnRtspAuthArgs已经进行过修改
![image](https://user-images.githubusercontent.com/24370921/229390346-31cb9859-c535-4227-a852-10a8907dd98c.png)
同时修改过RtspSession::onAuth定义，因为回调后直接是认证后的结果：
![image](https://user-images.githubusercontent.com/24370921/229390822-71517532-4bb7-4f0b-9078-60f2f0a1e702.png)

我提这个issue并不是想让你们帮我找bug，我已经解决了才过来提的。我把weak_ptr定义为指针类型，分配了内存，再进行捕获，运行即不再存在问题。
我对weak_ptr这个智能指针不太熟，一开始我认为这个指针想c里面的指针一样，他是指向型的可以一直存在，但经过测试，可以发现weak_ptr的生存期也仅限制与他所在的作用域内，也就是说RtspSession::onAuthDigest函数结束后，weak_ptr定义的对象会被销毁。
如上对weak_ptr的言论只是我的个人测试得出的一个理解，如果有错误，希望批评指出。

**Comment by xia-chu** [comment]
如果你说主线代码有问题 你应该是在未自行修改版本代码的基础上测试出来bug；现在你只给一点你修改代码的代码片段截图，说实话，我们很难给你分析代码问题，而且老实讲，我们也不想分析这种问题，这种问题正确的提issue姿势应该是，你提一个技术咨询的issue，把你修改部分代码的patch粘贴上来，这样我们可以根据patch在本地应用并测试，你就截个图，我们还要去自行修改代码，这种谁有这么多功夫啊？
