### ISSUE TITLE
[BUG] EventPollerPool::kOnStarted does not exists

### ISSUE THREAD

**Issue by perara** [ZLMediaKit/ZLMediaKit#2356]
The following constant does not exist in main, hence it would not compile.
https://github.com/ZLMediaKit/ZLMediaKit/blob/master/src/Http/HttpRequester.cpp#L274

**Comment by xia-chu** [comment]
This is not a bug, you need update submodule of `ZLToolKit` like this :
```bash
git submodule update
```

**Comment by perara** [comment]
Ah! I did not realize.
Thanks @xia-chu!

**Comment by xia-chu** [comment]
Hi, do you think it was a virtue to star a repository before commit a issue ?

**Comment by persysOne** [comment]
@xia-chu. Clearly, I must have missed it. I realized you blocked me whilst attempting to contribute to this project via a pull request. Unfortenately, I cannot do that while blocked.

Further, I would have had no issue in starring this repository, but it feels innapropriate if not welcomed, and further I feel it as a unwise strategy if you would want to maximize for stars.

Best,

**Comment by xia-chu** [comment]
No, i will not blocked who commit a issue without staring,
Certainly, be honestly, we hope that everyone stared the repository who commit a issue, i'm not willing to spend too much time to answer people with a technical consulting question issue(bugs excluded) who do not stared repository.

I am trying to communicate with you and hope you can star this repository, and i will thank you after your feedback.
But after waiting for some days without your reply so I was a bit angry and blocked you.

I am sorry for my reckless behavior, and i have already unblocked you.

**Comment by xia-chu** [comment]
I'm sorry, it's my fault. I shouldn't be so stingy
