### ISSUE TITLE
[技术咨询] fmp4使用VLC无法正常播放

### ISSUE THREAD

**Issue by wujianGit123** [ZLMediaKit/ZLMediaKit#2358]
fmp4格式流使用VLC播放器能出来一帧画面，但是画面会一直保持不变(同一个fmp4使用vlc播放偶尔能正常，而且只要正常播放就一直维持正常)，使用ffplay播放则无此问题，vlc的报错如下：

```
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
main warning: picture is too late to be displayed (missing 9210 ms)
main warning: picture is too late to be displayed (missing 9112 ms)
main warning: picture is too late to be displayed (missing 9021 ms)
main warning: picture is too late to be displayed (missing 8970 ms)
main warning: picture is too late to be displayed (missing 9061 ms)
avcodec warning: More than 11 late frames, dropping frame
```

**Comment by xia-chu** [comment]
有没有一种可能 这个流的时间戳不好？其他流是否也有该现象？

**Comment by wujianGit123** [comment]
> 

这个流原始是一个rtsp流，使用vlc播放是正常的，但在ZLM中使用PlayerProxy拉流生成fmp4之后就出现这样的情况，照理说fmp4的时间戳是重新编排的，MP4MuxerInterface::inputFrame里面会修正时间戳，奇怪的是同一个流我测试录制mp4文件使用vlc播放却又正常。

**Comment by xia-chu** [comment]
不会的 zlm现在不做任何时间戳修改了 直接透传时间戳的

**Comment by wujianGit123** [comment]
> 

rtsp://171.105.57.185:10003/3CMB03551200E1F_0?key=a313e9b901c58344a9ca74350d9b85b1&tk=6ceed95a-6c1c-406a-97b6-f9ddaa52176b&appId=8854786247&reqId=5d133cc616d440199928447f8b7ac493
这个是原始rtsp流，这个url仅20分钟内有效

**Comment by wujianGit123** [comment]
> 

不是把，我clone的是最新版本的代码呀，
`track_info.stamp.revise(dts, pts, dts_out, pts_out);`
这行代码里面不是修正时间戳么？

**Comment by wujianGit123** [comment]
看起来确实可能是这个流的时间戳问题，使用ffmpeg推流不停的报警告
![时间戳](https://user-images.githubusercontent.com/49545139/229401292-a715dcc2-1713-4d28-a49e-05ddf4dc99d5.png)

**Comment by xia-chu** [comment]
哦哦 fmp4有点修改 不过那只是获取相对时间戳&nbsp;





------------------ 原始邮件 ------------------
发件人: wujianGit123 ***@***.***&gt;
发送时间: 2023年4月3日 10:51
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] fmp4使用VLC无法正常播放 (Issue #2358)





   
不是把，我clone的是最新版本的代码呀，
 track_info.stamp.revise(dts, pts, dts_out, pts_out);
 这行代码里面不是修正时间戳么？

**Comment by wujianGit123** [comment]
或者直接在ffmpeg上把音频去掉(-an)，就不会出现在这个问题

**Comment by xia-chu** [comment]
fmp4可能不支持g711a 这个要问下 @ireader 大佬

**Comment by wujianGit123** [comment]
> fmp4可能不支持g711a 这个要问下 @ireader 大佬

好的，我在github上咨询他们了

**Comment by ireader** [comment]
mp4和fmp4都支持g711alaw，使用方法跟aac基本相同。

fmp4使用时需要注意：
1. 确保添加视频、音频track后再调用fmp4_writer_init_segment ；
2. 确保调用fmp4_writer_init_segment后再调用fmp4_writer_write；

**Comment by xia-chu** [comment]
我测试vlc也是有声音 但是视频不动 估计是vlc还有兼容性问题

**Comment by ireader** [comment]
> 我测试vlc也是有声音 但是视频不动 估计是vlc还有兼容性问题

我这边vlc播放正常, 是不是时间戳有问题?  把文件发一下我看看?

**Comment by xia-chu** [comment]
@ireader 可能跟vlc版本有关 我公司mac vlc播放不了 但我私人电脑可以，vlc版本如下：
<img width="451" alt="图片" src="https://user-images.githubusercontent.com/11495632/230084530-1ae4a72e-bc22-46e4-bdad-c8362531d527.png">

**Comment by wujianGit123** [comment]
> @ireader 可能跟vlc版本有关 我公司mac vlc播放不了 但我私人电脑可以，vlc版本如下： <img alt="图片" width="451" src="https://user-images.githubusercontent.com/11495632/230084530-1ae4a72e-bc22-46e4-bdad-c8362531d527.png">

我电脑vlc是偶尔能正常播放

**Comment by ireader** [comment]
偶尔能播放是什么意思, 同一个文件偶尔能播放吗?   不能播的是不是文件内容本身的问题?

**Comment by wujianGit123** [comment]
> 偶尔能播放是什么意思, 同一个文件偶尔能播放吗? 不能播的是不是文件内容本身的问题?

就是同一个fmp4视频流，使用vlc打开url偶尔能正常播放，但试很多次才会有少数几次是正常的

**Comment by xia-chu** [comment]
不是文件 是webrtc推流转fmp4直播 时间戳可能不是从0开始 因为所有fmp4直播客户端都共享数据 不可能为每个客户端都生成从0开始的视频





------------------ 原始邮件 ------------------
发件人: Chen ***@***.***&gt;
发送时间: 2023年4月6日 10:45
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] fmp4使用VLC无法正常播放 (Issue #2358)





 
偶尔能播放是什么意思, 同一个文件偶尔能播放吗?   不能播的是不是文件内容本身的问题?

**Comment by wujianGit123** [comment]
> 不是文件 是webrtc推流转fmp4直播 时间戳可能不是从0开始 因为所有fmp4直播客户端都共享数据 不可能为每个客户端都生成从0开始的视频

我的测试方法是使用ffmpeg拉一个rtsp，然后转推到ZLM，还有就是使用ffmpeg将MP4文件转rtsp推到ZLM

**Comment by ireader** [comment]
> 不是文件 是webrtc推流转fmp4直播 时间戳可能不是从0开始 因为所有fmp4直播客户端都共享数据 不可能为每个客户端都生成从0开始的视频

fmp4不要求时间戳从0开始.

可以把播放不正常的流保存一份， 上传给我分析下？

**Comment by wujianGit123** [comment]
> fmp4不要求时间戳从0开始.
> 
> 可以把播放不正常的流保存一份， 上传给我分析下？

可以用这个来测试https://gb.gxxcnet.cn/stream03/xcmp/6TPCA4506400CVS.live.mp4

**Comment by xia-chu** [comment]
> > fmp4不要求时间戳从0开始.
> > 可以把播放不正常的流保存一份， 上传给我分析下？
> 
> 可以用这个来测试https://gb.gxxcnet.cn/stream03/xcmp/6TPCA4506400CVS.live.mp4

这个地址vlc播放图片卡住 FFmpeg正常

**Comment by wujianGit123** [comment]
> > 可以用这个来测试https://gb.gxxcnet.cn/stream03/xcmp/6TPCA4506400CVS.live.mp4
> 
> 这个地址vlc播放图片卡住 FFmpeg正常

使用vlc偶尔又是能正常播放的，我现在就测出了一次，还没关掉^_^

**Comment by wujianGit123** [comment]
我测试了之前旧版本的代码，也有这个问题，但是明显没现在这么严重，现在几乎是必现，而旧版本的代码很少会出现这种情况

**Comment by xia-chu** [comment]
别关掉吧 晚上我回去用我电脑老版本vlc测试

**Comment by wujianGit123** [comment]
> 别关掉吧 晚上我回去用我电脑老版本vlc测试

这个不会关

**Comment by ireader** [comment]
对比了实时流和保存的文件：
- 实时流只有音频，视频挺住；
- 从实时流保存的文件用VLC可以播放；

实时流播放时，从VLC Message窗口可以不定期看到错误信息，如下：
```
avcodec warning: More than 11 late frames, dropping frame
avcodec warning: More than 11 late frames, dropping frame
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
avcodec error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
```

分析保存的fmp4文件：
![image](https://user-images.githubusercontent.com/1535445/230552094-bfebb4af-bb59-4f57-a525-c1812a02f050.png)
音视频时间戳交织不错。


_有可能是H265 2K视频解码慢导致VLC丢弃视频帧，可以降低视频分辨率到720P验证下。_

**Comment by xia-chu** [comment]
家里面的老版本vlc可以正常播放

**Comment by xia-chu** [comment]
@ireader 感谢答复！
