### ISSUE TITLE
[技术咨询]m3u8拉流后无法获取播放地址

### ISSUE THREAD

**Issue by wangran99** [ZLMediaKit/ZLMediaKit#2362]
**咨询的功能模块**
- 电视直播流拉流后无法获取点播地址

**咨询的具体内容和问题**
- wvp拉流，拉流地址：https://live.v1.mk/api/bestv.php?id=cctv1hd8m/8000000 ，该地址vlc、potplayer都能播放，但是zlm不能获取播放地址。
- 
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by wangran99** [comment]
怀疑跟aac有关系

**Comment by xiongguangjie** [comment]
ZLM有报什么错之类的

**Comment by alexliyu7352** [comment]
地址已失效, 请提交一个新地址

**Comment by alexliyu7352** [comment]
测试可以正常拉流.
请用post方式提交addStreamProxy接口参数

**Comment by wangran99** [comment]
> https://live.v1.mk/api/bestv.php?id=cctv1hd8m/8000000&ext=.m3u8



> 测试可以正常拉流. 请用post方式提交addStreamProxy接口参数 并且给url末尾增加一个.m3u8比如 https://live.v1.mk/api/bestv.php?id=cctv1hd8m/8000000&ext=.m3u8
> 
> 或者修改PlayerBase::Ptr PlayerBase.cpp
> 
> ```
> if ((strcasecmp("http", prefix.data()) == 0 || strcasecmp("https", prefix.data()) == 0)) {
>         if (end_with(url, ".m3u8") || end_with(url_in, ".m3u8")) {
>             return PlayerBase::Ptr(new HlsPlayerImp(poller),releasePlayer);
>         }else if (end_with(url, ".ts") || end_with(url_in, ".ts")) {
>             return PlayerBase::Ptr(new TsPlayerImp(poller),releasePlayer);
>         }
>         return PlayerBase::Ptr(new HlsPlayerImp(poller),releasePlayer);
>     }
> ```

非常感谢，拉流推流正常了。之前没有直接用接口调用，用wvp页面添加的。
