### ISSUE TITLE
zlmediakit知识星球开通了！

### ISSUE THREAD

**Issue by xia-chu** [ZLMediaKit/ZLMediaKit#2364]
不知不觉，zlmediakit开源已经6年了，期间我们结识了很多真挚的朋友，大家在为zlmediakit默默的不求回报的付出，在众人的呵护下，目前小有成绩，在流媒体界颇有影响力，服务了广大的开发者和中小企业； 在此，非常感谢大家一如既往的陪伴和支持!

之前，我们主要通过issue和qq群的方式为广大开发者服务；目前zlmediakit qq群(两个)已经达到4000人最大限额，由于精力有限，以后将不再创建新qq群，当前qq群也将停止新人申请加入(只保留邀请加入)，今后将引导新用户加入知识星球，大家还可以像之前一样在qq群和issue提问，不过我们将主要投入精力运营知识星球，目的是为了实现更良好的投入和收益比，这样项目成员才能不用用爱发电，项目才能更良性发展；如果后续这方面发展的不错，也许我们还能全职开发运营项目，为大家带来更好的服务和更令人惊喜的特性。

知识星球提供的服务主要包括：

- **关于zlmediakit的技术咨询，包括编译、开发、使用、运维等任何相关技术问题，我们将优先服务知识星球内用户。**
- **编程技巧和思想分享，特别是现代c++编程思想的布道，分享方式主要是精彩代码片段分享、技术文章分享等。**
- **最新的内部未发布特性小规模分享，给用户提供内部专属未发布到开源版本的特性。**
- **力所能及的其他编程相关问题咨询，比如各种开源库的相关问题。**

星球地址为：https://t.zsxq.com/0cVcuquPJ

目前星球草创阶段，还没什么内容，暂定￥199每年，最近一个月加入，可减免40元：
![图片](https://user-images.githubusercontent.com/11495632/229433075-3d323634-0cf0-4ad8-8081-098f3f350148.png)

**Comment by xia-chu** [comment]
> 这个项目很不错，已加入星球

感谢支持！

**Comment by xia-chu** [comment]
@dualven  感谢支持！

**Comment by xia-chu** [comment]
## 关于qq群的一些解释
- 问: qq群放不下更多人了，为什么不创建新群？
   答：两个qq群4000人加一个微信群几百人，还有issue等需要处理，没时间和精力维护更多qq群了。

- 问: 为什么不维持之前的政策，群满员了踢人留位置给新人？
   答：因为踢人的标准不好把控，踢少了不够位置，踢多了又可能一刀切。

- 问：为什么qq群还有少量空位，却不再让新人加入？
   答：因为很多人只是为了解决眼前问题加入qq群，没有任何忠诚和感激可言，问题解决后要么退群要么不再理会，曾经遇到过有         人三进三出，把我们当做活字典的，所以要提高入群门槛，筛选掉只为了解决当前问题而刷字典的人。

- 问：为什么要创建付费的知识星球？
  答：要提高技术服务门槛，这样用户才会珍惜，才不会解决问题后就弃之如敝履；我们希望我们的服务和感情得到尊重，任何人都厌恶白眼狼。另外知识星球的回答有记录有沉淀，用户可以查询，也可以跟帖回复，而qq群做不到这一点。另外知识星球有一定的收入，这样我们才更有动力对正在需要的人提高服务质量。

- 问：qq群将来有重新开放入群通道的可能吗？
  答：有，不过会卡一段时间的申请，我们会筛选掉那种把我们当做工具人的用户，主要筛选掉为了当前问题加入群解决后就退群的那种人。

**Comment by xia-chu** [comment]
关注zlmediakit公众号，获取教程视频与相关技术文章：
![图片](https://user-images.githubusercontent.com/11495632/232451424-4e1dabfe-26c8-40f5-adaa-d2ee4fe073d5.png)

**Comment by xia-chu** [comment]
知识星球专属福利，zlmediakit新增支持jt1078部标推流协议，使用方法与GB28181完全一致，支持单端口和多端口模式(建议单端口模式)。目前该特性暂不打算开源，现只邀请知识星球用户加入私有仓库，欢迎大家加入知识星球获取源码分支。

**Comment by zhouanche** [comment]
addStreamProxy h265转h264没用，播放的仍然是265

**Comment by uncleyoung** [comment]
除了知识星球，是否有考虑类似付费直播课程或者视频课程，以简单但具体业务为例，完整的demo出一个如何使用框架的流程方法？

**Comment by xia-chu** [comment]
> 除了知识星球，是否有考虑类似付费直播课程或者视频课程，以简单但具体业务为例，完整的demo出一个如何使用框架的流程方法？

还没开始搞 精力不太够
