### ISSUE TITLE
[技术咨询] GB28181,RTP推流，能否换源

### ISSUE THREAD

**Issue by fuyuzhou011** [ZLMediaKit/ZLMediaKit#2365]
**咨询的功能模块**
GB28181,RTP推流 

**咨询的具体内容和问题**
addStreamProxy拉流成功后，startSendRtp推流，推流成功一段时间后发现在无限重试播放拉流地址，但是地址有过期时间，导致拉流地址失效，能否在这时换拉流源。
或者大佬们有什么思路或解决方案

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
不会，startSendRtp的数据源来自addStreamProxy代理的流，如果原始流没数据了 zlmediakit会重试拉流；如果配置文件general.resetWhenRePlay设置为1 那么重试时会重置MultiMediaSourceMuxer对象，该对象上面挂载的RtpSender对象(由startSendRtp接口创建)会全部清空，这些rtp转发会全部失效，如果不想失效，需要设置配置文件general.resetWhenRePlay为0。

如果重连时，地址需要重新生成，可以新增一个重试拉流前的hook，在hook中你的业务系统返回新的拉流地址即可
