### ISSUE TITLE
嵌入式设备录制视音频到硬盘

### ISSUE THREAD

**Issue by hatedog** [ZLMediaKit/ZLMediaKit#2367]
**咨询的功能模块**
- 视音频录制为本地文件

**咨询的具体内容和问题**
嵌入式设备，把摄像机采集的视频和音频 按mp4录制在设备的硬盘上。
原本是想按照ts流来存储，这样设备偶尔退出再进入可以保证文件还能访问。
结果发现zlm的recorder只支持mp4和hls。

1.  考虑到mp4格式的特殊性，想避免丢失数据，按照10秒钟一片来存储。
设置了enable_hls=0, enable_mp4=1, mp4_max_second=10；
现在开起来工作良好，不知道这个方式是否合理。

2. 每日要进行视频归档，归档时需要将mp4的分片进行合并成一个独立文件，
用什么方式合并比较简单和高效？

**Comment by xia-chu** [comment]
zlm录制ts也是可以的，只是需要稍微修改点代码，另外也可以录制为fmp4,不过也需要略微修改点代码，改动更小。
我建议改成fmp4录制比较合理，改动比较小的同时，还不怕丢失，也不用合并切片。

录制成fmp4可以参考 #658
