### ISSUE TITLE
[技术咨询] rtsp流（非直接代理）转websocket-flv的首帧是否是关键帧

### ISSUE THREAD

**Issue by ShuiFan0** [ZLMediaKit/ZLMediaKit#2369]
**咨询的功能模块**
- rtsp流（非直接代理）转websocket-flv

**咨询的具体内容和问题**
- 我在使用【rtsp流（非直接代理）转websocket-flv】时，遇到了播放器报首帧缺失的问题，进而导致了其它异常行为。
- 这是否是因为本项目没有保证这部分的功能的首帧是关键帧？

**Comment by xia-chu** [comment]
请使用rtsp over tcp方式拉流

**Comment by ShuiFan0** [comment]
啊，我的意思可能没说清楚，在注册拉流后，马上去获取ws-flv资源

> 请使用rtsp over tcp方式拉流，你的疑虑是多虑的，你说的基本体验功能 zlm都有做

啊，我的意思可能没说清楚，我是在注册拉流后，马上去获取ws-flv资源

**Comment by xia-chu** [comment]
也有的 触发媒体注册需要关键帧 没关键帧压根就不会注册
