### ISSUE TITLE
[技术咨询] zlm提供的api中暂时没有找到可以根据指定的ip和端口拉取视频的接口

### ISSUE THREAD

**Issue by fengyunpt** [ZLMediaKit/ZLMediaKit#2375]
**咨询的功能模块**
- zlm去指定的第三方ip和端口中拉流生成视频

**咨询的具体内容和问题**
- 我是用wvp+zlm 结合gb28181做的上级平台，对接海康设备端请求视频的时候，海康会提供个ip和端口，让我去主动拉流生成视频，请问大神zlm有哪个api可以用吗？暂时没有找到合适的。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
目前zlm未实现主动拉取GB28181流的功能 目前只提供被动收取 需要对方推流给zlm。
如果是rtsp/rtmp/hls取流，zlm支持addStreamProxy接口取流
