### ISSUE TITLE
[技术咨询] zlm中restApi：openRtpServer接口问题

### ISSUE THREAD

**Issue by fengyunpt** [ZLMediaKit/ZLMediaKit#2376]
**咨询的功能模块**
- zlm中的提供的restApi：openRtpServer接口问题

**咨询的具体内容和问题**
- 我调用restApi：openRtpServer接口 参数传递指定port端口后 过一会这个端口就关闭了（通过listRtpServer接口查询），想问下在什么情况下会自动关闭这个端口，有没有配置的地方？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
openRtpServer创建的端口需要再一定时间内(10秒左右)接收到流，否则zlm会主动回收端口，目的是为了防止开发者忘记主动closeRtpServer

**Comment by fengyunpt** [comment]
tcp_mode	Y	0 udp 模式，1 tcp 被动模式, 2 tcp 主动模式。 (兼容enable_tcp 为0/1)
tcp被动模式下，接收设备端推送的视频流一段时间后，会主动发送fin 主动断开链接，不知道为什么？

**Comment by fengyunpt** [comment]
> openRtpServer创建的端口需要再一定时间内(10秒左右)接收到流，否则zlm会主动回收端口，目的是为了防止开发者忘记主动closeRtpServer造成端口资源泄露

我这测试的好像没有10s就关闭了，这块能不能搞个配置参数？

**Comment by fengyunpt** [comment]
> openRtpServer创建的端口需要再一定时间内(10秒左右)接收到流，否则zlm会主动回收端口，目的是为了防止开发者忘记主动closeRtpServer造成端口资源泄露

我这测试的好像没有10s就关闭了，测试的时候设备端一直在推流突然端口就关闭了-偶发，不知道是不是因为设备端推送的流有问题还是什么原因？，这块能不能搞个配置参数？

**Comment by xia-chu** [comment]
你需要分析zlmediakit完整日志 里面会打印原因

**Comment by fengyunpt** [comment]
> 你需要分析zlmediakit完整日志 里面会打印原因
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/19603937/230096537-b795099d-7ddf-4319-9c35-f55188034d2f.png">

麻烦帮我看下有么有问题，在媒体注销的时候是不是已经关闭端口了？ 还是 rtp pt类型不得超过2种! 导致的？

**Comment by xia-chu** [comment]
你这推的es流还是ps流？

**Comment by fengyunpt** [comment]
> 你这推的es流还是ps流？

据说是ps流，还有个视频卡顿的问题，正常来说是不是只应该有一个pt类型？

**Comment by xia-chu** [comment]
如果偶发可以不关注
