### ISSUE TITLE
[技术咨询] zlm开启收流端口后主动发送fin断开连接问题

### ISSUE THREAD

**Issue by fengyunpt** [ZLMediaKit/ZLMediaKit#2377]
**咨询的功能模块**
- zlm中的提供的restApi：openRtpServer接口开启端口后续

**咨询的具体内容和问题**
- 我调用restApi：openRtpServer接口 参数传递指定port端口 tcp_mode=1 tcp被动模式，开始接收设备端推送的视频流，可是收流一段时间后主动发送了fin断开链接了，请教下原因，详细抓包信息如下：
- （设备端ip：10.191.103.18，zlm服务器ip：10.193.144.224）
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/19603937/229960551-04b8b20a-1d41-4b42-a325-084e5baff005.png">

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by fengyunpt** [comment]
zlm开启的收流端口：31658， tcp_mode = 1 tcp被动模式 
设备端tcp推送流的端口：5660 
正常来说zlm不会发生fin主动断开链接吧，不知道为什么发送了fin？

**Comment by fengyunpt** [comment]
> **咨询的功能模块**
> 
> * zlm中的提供的restApi：openRtpServer接口开启端口后续
> 
> **咨询的具体内容和问题**
> 
> * 我调用restApi：openRtpServer接口 参数传递指定port端口 tcp_mode=1 tcp被动模式，开始接收设备端推送的视频流，可是收流一段时间后主动发送了fin断开链接了，请教下原因，详细抓包信息如下：
> * （设备端ip：10.191.103.18，zlm服务器ip：10.193.144.224）
> 
> <img alt="image" width="1263" src="https://user-images.githubusercontent.com/19603937/229960551-04b8b20a-1d41-4b42-a325-084e5baff005.png">
> 
> **注意事项**
> 
> * 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue
> * 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by fengyunpt** [comment]
是不是zlm关闭端口后服务器发送的fin， 但是抓包看设备端一直在推流，不知道怎么就关闭端口了，是不是视频流有问题？ 自己也没有手动关闭，这块能不能优化下，不要主动关闭端口，改成可配置的。

**Comment by xia-chu** [comment]
zlm会打印日志的 你分析下
