### ISSUE TITLE
[BUG] 国际推流，音频播放不出来，附rtp  debug文件

### ISSUE THREAD

**Issue by dualven** [ZLMediaKit/ZLMediaKit#2379]
现象：可以播放视频，但是声音没有
经过debug,发现有报错：

rtp debug文件地址：
http://www.login-wifi.com/gmes/1.tar.gz

![image](https://user-images.githubusercontent.com/2209534/230581874-3740b032-bd20-494b-be3a-215abab18061.png)

**Comment by dualven** [comment]
@xia-chu 帮忙看看

**Comment by xiongguangjie** [comment]
这个是测试程序的bug,我已经修复了，这个码流的问题是 ps声明了pcma的音频，但是没有数据过来，导致要等待10s,才会注册成功，而且默认配置会添加静音的音频。

**Comment by dualven** [comment]
好的，谢谢，我测试下

**Comment by dualven** [comment]
![image](https://user-images.githubusercontent.com/2209534/230818468-50438de5-5ec0-4a6b-ba7f-b8bb8e828392.png)

@xiongguangjie  帮忙看看，可以看到在播放，但是就是听不到声音； test_rtp 里面也不报错了。

![image](https://user-images.githubusercontent.com/2209534/230818763-044a567a-5900-46a8-a433-03479c6028ae.png)
http://www.login-wifi.com/gmes/3.tar.gz

**Comment by xia-chu** [comment]
pcma的track被忽略了 说明没收到它的数据

**Comment by xia-chu** [comment]
```bash
ffprobe 34010200001130000001_34010200001310000001.mpeg -show_frames | grep audio
```
没发现任务音频包

**Comment by xia-chu** [comment]
这个设备假装自己有音频 实际没有

**Comment by dualven** [comment]
好的谢谢，我再问问设备侧的同事 。
