### ISSUE TITLE
RTC是如何做到客户端网络切换支持连接迁移的

### ISSUE THREAD

**Issue by doitsjz** [ZLMediaKit/ZLMediaKit#2381]
配置文件说到，但不知道如何实现的呢，对于UDP，可以通过心跳包重新建立句柄与IP&PORT的关系，但对于TCP 是怎么做呢？

#rtc udp服务器监听端口号，所有rtc客户端将通过该端口传输stun/dtls/srtp/srtcp数据，
#该端口是多线程的，同时支持客户端网络切换导致的连接迁移

port=8000
#rtc tcp服务器监听端口号，在udp 不通的情况下，会使用tcp传输数据
#该端口是多线程的，同时支持客户端网络切换导致的连接迁移

**Comment by xia-chu** [comment]
@jonzzy 感谢答复！
@doitsjz 提交issue时请按照模板提交，不符合格式要求的issue将***直接关闭***，另外重申下，技术咨询类的issue要求提问者先star收藏本项目。
