### ISSUE TITLE
服务可以禁用options请求吗

### ISSUE THREAD

**Issue by suMessi** [ZLMediaKit/ZLMediaKit#2385]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
http服务器还是rtsp的？目的是什么？

**Comment by suMessi** [comment]
>我这边安全测试不允许有options请求，所以才会有这个问题， 已经通过nginx配置给options请求给排掉了
