### ISSUE TITLE
[功能请求] 是否考虑播放端RTSP连入的时候以实时视频信息重新构造SDP而不是使用传入的SDP

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2387]
IPC---转码----ZLM----->rtsp-->--播放器：

之前在群里跟熊猫大佬反馈过，我这边有一个送数据端变分辨率，但是未重启RTPserver的案例，只是清了一下包缓冲，保证相同的SSRC，然后就送了其他分辨率的同源视频，但是其实此端口的媒体源部分的SDP仍然是变分辨率前的SDP；并且H265flush首个GOP并没有在I帧前打配置帧，就导致多种播放器播放首个GOP要么是花屏，要么因为没有PPS而显示不出来；

后来big panda大佬给修改了H265封包，I帧前添加了配置帧，经过测试在接入播放器后，I帧前确实有配置帧了，并且我保存了flush数据单独解析SPS，宽高也是变分辨率之后的宽高；我测试诸如海康播放器，是可以正常显示的；但是VLC（3.0.18 vetinari）仍然首个GOP花屏（花屏部分媒体信息中的宽高是变分辨率之前的宽高）所以我猜测有些播放器即便关键帧打了正确的SPS，它仍然使用SDP中的SPS进行首个GOP的解码；

后来我本地修改了部分代码，H265Track判断配置帧SPS宽高改变后，更新下rtsp打包层的SDP；发现VLC播放首个GOP的时候不在花屏，宽高也是与实际数据对应；

所以，如果别人给了我ZLM一个错误的SDP，再有播放器新接入ZLM播放的时候这个错误的SDP就会继续传递下去；不过这可能与各家播放器的处理逻辑存在关系，有些厂家首个GOP的解码用的配置帧，有些厂家用的SDP的配置信息；

**描述你期望实现该功能的方式和最终效果**
所以是否考虑有新的reader 以RTSP方式接入的时候，如果是ZLM送SDP媒体信息的时候，总是以当前视频信息中的实际配置帧进行SDP生成，而不是使用送流端接入是给的原始SDP（最初保存的一个SDP）；

**Comment by xia-chu** [comment]
如果rtp中有sps pps；那么播放器应该优先使用rtp中的(而不是sdp中的)

**Comment by xuandu** [comment]
好的；

**Comment by xia-chu** [comment]
vlc对这个兼容性有问题 我觉得可以不理会 首先这种分辨率变更的情况不多见 另外不支持的播放器也不多见。
虽然可以实现你说的功能，但是我觉得代价和收益不成正比(性能有损失 还有线程安全问题) 不值的去做
