### ISSUE TITLE
docker镜像拉取不了，显示no found

### ISSUE THREAD

**Issue by dconnan** [ZLMediaKit/ZLMediaKit#2392]
![image](https://user-images.githubusercontent.com/49008992/231931700-63db1b71-c49f-4055-b5dd-759261129a3b.png)
能搜索，但是拉取不到，是什么问题呢

**Comment by xiongguangjie** [comment]
![``5A%IDNCI{UM4QR7ZO5_N8](https://user-images.githubusercontent.com/19631632/231951743-bced1a74-660f-4584-9085-d2e9ff43613b.png)
可以呀，你是不是网络有问题呀，设置下docker镜像

**Comment by penghd** [comment]
centos要重新安装docker-ce，用docker-io是不行的
