### ISSUE TITLE
地址端口占用视频就无法播放了，会提示拉流失败，大部分都可以播放，只有偶尔会出现错误的时候无法播放

### ISSUE THREAD

**Issue by liwenyan703** [ZLMediaKit/ZLMediaKit#2394]
### 现象描述

当出现下面的占用以后视频就无法播放了，会提示拉流失败，大部分都可以播放，只有偶尔会出现错误的时候无法播放，不过过一会再次点击就又可以播放了，我对接的是海康的gb28281
<img width="1280" alt="无标题" src="https://user-images.githubusercontent.com/39700864/232038255-04870225-d107-4cd5-8f93-cd9086c3e69f.png">
![image](https://user-images.githubusercontent.com/39700864/232038326-b310eec0-786a-490c-bccc-2d5c5883cca3.png)

### 如何复现?

 1. 首先 ... 点击播放按钮
    2. 然后 ... 后台会打印不是每次一次都能出现，有时候出现 了等待10秒左右再次播放视频就出现了这个问题zlmediakit_1  | 2023-04-14 19:14:33.854 W [MediaServer] [7-event poller 0] sockutil.cpp:421 bind_sock6 | Bind socket failed: address already in use
    3. 不出现 占用的情况
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
zlmediakit_1  | 2023-04-14 19:14:33.854 W [MediaServer] [7-event poller 0] sockutil.cpp:421 bind_sock6 | Bind socket failed: address already in use
zlmediakit_1  | 2023-04-14 19:14:33.854 D [MediaServer] [7-event poller 0] WebApi.cpp:250 http api debug | 
zlmediakit_1  | # request:
zlmediakit_1  | POST /index/api/openRtpServer
zlmediakit_1  | # header:
zlmediakit_1  | Accept-Encoding : gzip
zlmediakit_1  | Connection : Keep-Alive
zlmediakit_1  | Content-Length : 132
zlmediakit_1  | Content-Type : application/x-www-form-urlencoded
zlmediakit_1  | Host : 43.87.122.11:8080
zlmediakit_1  | User-Agent : okhttp/4.10.0
zlmediakit_1  | # content:
zlmediakit_1  | secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=43100200002000000001_43100200001310168604&port=30172&ssrc=2004200&enable_tcp=1
zlmediakit_1  | # response:
zlmediakit_1  | {
zlmediakit_1  | 	"code" : -400,
zlmediakit_1  | 	"msg" : "Listen on :: 30172 failed: address already in use"
zlmediakit_1  | }
zlmediakit_1  | 
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
  ; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s

[general]
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=30.000000
enable=1
on_flow_report=
on_http_access=
on_play=http://43.87.122.11:18080/index/hook/on_play
on_publish=http://43.87.122.11:18080/index/hook/on_publish
on_record_mp4=
on_record_ts=
on_rtp_server_timeout=http://43.87.122.11:18080/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://43.87.122.11:18080/index/hook/on_send_rtp_stopped
on_server_keepalive=http://43.87.122.11:18080/index/hook/on_server_keepalive
on_server_started=http://43.87.122.11:18080/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://43.87.122.11:18080/index/hook/on_stream_changed
on_stream_none_reader=http://43.87.122.11:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://43.87.122.11:18080/index/hook/on_stream_not_found
retry=1
retry_delay=3.000000
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:9fdb3de/2023-03-05T23:24:55+08:00,branch:master,build time:2023-03-05T16:33:29)</center></body></html>
port=8080
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=0
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
tcpPort=8000
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=19350

[rtp]
audioMtuSize=600
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-30500
ps_pt=96
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
sslport=332

[shell]
maxReqSize=1024
port=9000

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:centos7
* **硬件信息**:Intel
* **其他需要补充的信息**:

**Comment by tongwoo** [comment]
可以参考 #2286 试试

**Comment by liwenyan703** [comment]
> 可以参考#2286试试
是这个位置吗 我测试的这么不行啊
![image](https://user-images.githubusercontent.com/39700864/232179188-fac0bef2-99da-40fa-96f6-072839e97539.png)

**Comment by liwenyan703** [comment]
> 可以参考 #2286 试试
是这个吗？帮看一下谢谢

**Comment by xia-chu** [comment]
更新wvp+zlm吧 这个问题应该解决了

这个不是bug。

**Comment by liwenyan703** [comment]
是什么造成的




1184490717
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 下午5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] 地址端口占用视频就无法播放了，会提示拉流失败，大部分都可以播放，只有偶尔会出现错误的时候无法播放 (Issue #2394)





 
更新wvp+zlm吧 这个问题应该解决了
 
这个不是bug。

**Comment by xia-chu** [comment]
关注zlm/wvp的提交日志和wvp公告吧。
请star本项目以示支持！
