### ISSUE TITLE
[技术咨询] 咨询描述(必填) External socket descriptor

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#2397]
Helo

Is it possible to pass a socket descriptor to ZLM so that it sends an fmp4 stream to it?

I did something like this:

fd is socket descriptor of incoming connection
httpSrv is toolkit::TcpServer::Ptr

```cpp
    EventPoller::Ptr ep = EventPollerPool::Instance().getPoller();
    Socket::Ptr s       = Socket::createSocket(ep, false);
    ep->async([this, s, fd]() {
      s->setPeerSock(fd);
      httpSrv->createSession(s);
    });
```
but that's not enough

**Comment by xiongguangjie** [comment]
use cloneFromPeerSocket to switch poller ,reference https://github.com/ZLMediaKit/ZLMediaKit/blob/master/webrtc/WebRtcSession.cpp onRecv_l

**Comment by a-ucontrol** [comment]
Exception occurred when do async task: Copy a SockFD with same poller

**Comment by a-ucontrol** [comment]
The attachEvent and setPeerSock methods are private.
Can I make a pull request to ZLToolKit to make them public or protected?

**Comment by a-ucontrol** [comment]
Now the patch looks like this:

```patch
cat ZLMediaKit.patch 
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h      2022-11-11 12:00:14.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h    2022-11-24 18:54:00.910286895 +0300
@@ -20,6 +20,7 @@
 #include "util.h"
 #include "List.h"
 #include "Thread/semaphore.h"
+#include <cstdarg>
 
 namespace toolkit {
 
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Network/Socket.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.h   2023-04-10 13:12:54.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Network/Socket.h 2023-04-18 07:02:03.243356996 +0300
@@ -482,9 +482,12 @@
     uint16_t get_peer_port() override;
     std::string getIdentifier() const override;
 
+protected:
+    SockFD::Ptr setPeerSock(int fd);
+    bool attachEvent(const SockFD::Ptr &sock);
+
 private:
     SockFD::Ptr cloneSockFD(const Socket &other);
-    SockFD::Ptr setPeerSock(int fd);
     SockFD::Ptr makeSock(int sock, SockNum::SockType type);
     int onAccept(const SockFD::Ptr &sock, int event) noexcept;
     ssize_t onRead(const SockFD::Ptr &sock, bool is_udp = false) noexcept;
@@ -495,7 +498,6 @@
     void stopWriteAbleEvent(const SockFD::Ptr &sock);
     bool listen(const SockFD::Ptr &sock);
     bool flushData(const SockFD::Ptr &sock, bool poller_thread);
-    bool attachEvent(const SockFD::Ptr &sock);
     ssize_t send_l(Buffer::Ptr buf, bool is_buf_sock, bool try_flush = true);
     void connect_l(const std::string &url, uint16_t port, const onErrCB &con_cb_in, float timeout_sec, const std::string &local_ip, uint16_t local_port);
 
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Network/TcpServer.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Network/TcpServer.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Network/TcpServer.h        2023-04-10 13:12:54.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Network/TcpServer.h      2023-04-18 07:16:22.666709860 +0300
@@ -76,6 +76,8 @@
     virtual Session::Ptr onAcceptConnection(const Socket::Ptr &sock);
     virtual Socket::Ptr onBeforeAcceptConnection(const EventPoller::Ptr &poller);
 
+    std::function<SessionHelper::Ptr(const TcpServer::Ptr &server, const Socket::Ptr &)> _session_alloc;
+
 private:
     void onManagerSession();
     Socket::Ptr createSocket(const EventPoller::Ptr &poller);
@@ -90,7 +92,6 @@
     std::shared_ptr<Timer> _timer;
     Socket::onCreateSocket _on_create_socket;
     std::unordered_map<SessionHelper *, SessionHelper::Ptr> _session_map;
-    std::function<SessionHelper::Ptr(const TcpServer::Ptr &server, const Socket::Ptr &)> _session_alloc;
     std::unordered_map<const EventPoller *, Ptr> _cloned_server;
     //对象个数统计     ObjectStatistic<TcpServer> _statistic;

```

**Comment by xiongguangjie** [comment]
@xia-chu the patch can merge to master ??????

**Comment by xia-chu** [comment]
how about this patch?
```patch
Index: src/Network/Socket.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Network/Socket.h b/src/Network/Socket.h
--- a/src/Network/Socket.h	(revision ca26e43a5f62986bb8a007226e0bad148d154abc)
+++ b/src/Network/Socket.h	(date 1681871552410)
@@ -112,7 +112,8 @@
     typedef enum {
         Sock_Invalid = -1,
         Sock_TCP = 0,
-        Sock_UDP = 1
+        Sock_UDP = 1,
+        Sock_TCP_Server = 2
     } SockType;
 
     SockNum(int fd, SockType type) {
@@ -311,6 +312,13 @@
      */
     virtual bool bindUdpSock(uint16_t port, const std::string &local_ip = "::", bool enable_reuse = true);
 
+    /**
+     * 包装外部fd，本对象负责close fd
+     * 内部会设置fd为NoBlocked,NoSigpipe,CloExec
+     * 其他设置需要自行使用SockUtil进行设置
+     */
+    virtual bool fromSock(int fd, SockNum::SockType type);
+
     ////////////设置事件回调////////////
 
     /**
Index: src/Network/Socket.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Network/Socket.cpp b/src/Network/Socket.cpp
--- a/src/Network/Socket.cpp	(revision ca26e43a5f62986bb8a007226e0bad148d154abc)
+++ b/src/Network/Socket.cpp	(date 1681871683720)
@@ -499,7 +499,7 @@
     if (sock == -1) {
         return false;
     }
-    return listen(makeSock(sock, SockNum::Sock_TCP));
+    return fromSock(sock, SockNum::Sock_TCP_Server);
 }
 
 bool Socket::bindUdpSock(uint16_t port, const string &local_ip, bool enable_reuse) {
@@ -508,13 +508,29 @@
     if (fd == -1) {
         return false;
     }
-    auto sock = makeSock(fd, SockNum::Sock_UDP);
-    if (!attachEvent(sock)) {
-        return false;
-    }
-    LOCK_GUARD(_mtx_sock_fd);
-    _sock_fd = std::move(sock);
-    return true;
+    return fromSock(fd, SockNum::Sock_UDP);
+}
+
+bool Socket::fromSock(int fd, SockNum::SockType type) {
+    SockUtil::setNoSigpipe(fd);
+    SockUtil::setNoBlocked(fd);
+    SockUtil::setCloExec(fd);
+    
+    closeSock();
+    switch (type) {
+        case SockNum::Sock_TCP:
+        case SockNum::Sock_UDP: {
+            auto sock = makeSock(fd, type);
+            if (!attachEvent(sock)) {
+                return false;
+            }
+            LOCK_GUARD(_mtx_sock_fd);
+            _sock_fd = std::move(sock);
+            return true;
+        }
+        case SockNum::Sock_TCP_Server: return listen(makeSock(fd, SockNum::Sock_TCP_Server));
+        default: return false;
+    }
 }
 
 int Socket::onAccept(const SockFD::Ptr &sock, int event) noexcept {

```

**Comment by xia-chu** [comment]
Please use `Socket::fromSock(int fd)` api

**Comment by a-ucontrol** [comment]
It works, thank you!

Please add:

```patch
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h      2022-11-11 12:00:14.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h    2022-11-24 18:54:00.910286895 +0300
@@ -20,6 +20,7 @@
 #include "util.h"
 #include "List.h"
 #include "Thread/semaphore.h"
+#include <cstdarg>
 
 namespace toolkit {
 
```

Without this when building with uclibc:

```
FAILED: 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o 
ccache /opt/media-sdk-3.1/uclibc/bin/arm-nic-linux-uclibcgnueabihf-g++ -DENABLE_OPENSSL -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -DPATH_MAX=1024 -I/sdk/ZLMediaKit/bu -I/sdk/ZLMediaKit/3rdpart -I/sdk/ZLMediaKit/3rdpart/ZLToolKit/src -Os -DNDEBUG -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -std=gnu++11 -MD -MT 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -MF 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o.d -o 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -c /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.cpp
In file included from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/TimeTicker.h:15,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SpeedStatistic.h:14,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.h:20,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Session.h:15,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Server.h:16,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.h:14,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:13:
/sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h:401:121: ошибка: «va_list» не был декларирован
  401 |     static void printLogV(Logger &logger, int level, const char *file, const char *function, int line, const char *fmt, va_list ap);
      |                                                                                                                         ^~~~~~~
ninja: build stopped: subcommand failed.
```

**Comment by a-ucontrol** [comment]
And can add in TcpServer?

```c++

template <typename SessionType>
    void start() {
      _session_alloc = [](const toolkit::TcpServer::Ptr &server, const toolkit::Socket::Ptr &sock) {
        auto session = std::make_shared<SessionType>(sock);
        return std::make_shared<SessionHelper>(server, session);
      };
    }

```

**Comment by xia-chu** [comment]
Yes, please use `TcpServer::createSession`

**Comment by a-ucontrol** [comment]
FAILED: 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/Socket.cpp.o 
ccache /opt/media-sdk-3.1/uclibc/bin/arm-nic-linux-uclibcgnueabihf-g++ -DENABLE_OPENSSL -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -DPATH_MAX=1024 -I/sdk/ZLMediaKit/bu -I/sdk/ZLMediaKit/3rdpart -I/sdk/ZLMediaKit/3rdpart/ZLToolKit/src -Os -DNDEBUG -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -std=gnu++11 -MD -MT 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/Socket.cpp.o -MF 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/Socket.cpp.o.d -o 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/Socket.cpp.o -c /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp
In file included from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/TimeTicker.h:15,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SpeedStatistic.h:14,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.h:20,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.cpp:13:
/sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h:401:121: ошибка: «va_list» не был декларирован
  401 |     static void printLogV(Logger &logger, int level, const char *file, const char *function, int line, const char *fmt, va_list ap);
      |                                                                                                                         ^~~~~~~
[89/291] ccache /opt/media-sdk-3.1/uclibc/bin/arm-nic-linux-uclibcgnueabihf-g++ -DENABLE_OPENSSL -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -DPATH_MAX=1024 -I/sdk/ZLMediaKit/bu -I/sdk/ZLMediaKit/3rdpart -I/sdk/ZLMediaKit/3rdpart/ZLToolKit/src -Os -DNDEBUG -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -std=gnu++11 -MD -MT 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -MF 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o.d -o 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -c /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.cpp
FAILED: 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o 
ccache /opt/media-sdk-3.1/uclibc/bin/arm-nic-linux-uclibcgnueabihf-g++ -DENABLE_OPENSSL -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -DPATH_MAX=1024 -I/sdk/ZLMediaKit/bu -I/sdk/ZLMediaKit/3rdpart -I/sdk/ZLMediaKit/3rdpart/ZLToolKit/src -Os -DNDEBUG -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -std=gnu++11 -MD -MT 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -MF 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o.d -o 3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Network/UdpServer.cpp.o -c /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.cpp
In file included from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/TimeTicker.h:15,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/SpeedStatistic.h:14,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Socket.h:20,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Session.h:15,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/Server.h:16,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.h:14,
                 from /sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:13:
/sdk/ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h:401:121: ошибка: «va_list» не был декларирован
  401 |     static void printLogV(Logger &logger, int level, const char *file, const char *function, int line, const char *fmt, va_list ap);
      |                                                                                                                         ^~~~~~~
ninja: build stopped: subcommand failed.

**Comment by a-ucontrol** [comment]
> Yes, please use `TcpServer::createSession`

Now my code is like this:

```c++
  httpSrv = TcpServer::Ptr(new TcpServer());
  httpSrv->start<HttpSession>(0); //Need port
```

```c++
      EventPoller::Ptr ep = EventPollerPool::Instance().getPoller();
      Socket::Ptr sock    = Socket::createSocket(ep, false);
      sock->fromSock(fd, SockNum::Sock_TCP);
      ep->async([this, sock]() { httpSrv->createSession(sock); });
```

And it works.

But you can add to TcpServer :

```c++
template <typename SessionType>
    void start() {
      _session_alloc = [](const toolkit::TcpServer::Ptr &server, const toolkit::Socket::Ptr &sock) {
        auto session = std::make_shared<SessionType>(sock);
        return std::make_shared<SessionHelper>(server, session);
      };
    }
```

Then you can call start without port and no listen

```
  httpSrv = TcpServer::Ptr(new TcpServer());
  httpSrv->start<HttpSession>();

```

Thank you for ZLMediaKit!

**Comment by xia-chu** [comment]
But your modifications will prevent `onManager` from being scheduled；
By the way, you need assign EventPoller to TcpServer when create it:
```c++
      EventPoller::Ptr ep = EventPollerPool::Instance().getPoller();
      // Assign EventPoller to TcpServer
      httpSrv = TcpServer::Ptr(new TcpServer(ep));
      httpSrv->start<HttpSession>();
      Socket::Ptr sock   = Socket::createSocket(ep, false);
      sock->fromSock(fd, SockNum::Sock_TCP);
      ep->async([this, sock]() { httpSrv->createSession(sock); });
```

**Comment by a-ucontrol** [comment]
Company: "НИЦ Технологии", https://www.nic-tech.ru/
In the developed line of IP cameras we use ZLM

**Comment by a-ucontrol** [comment]
Let me remind you about 
```patch
diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h
--- ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h      2022-11-11 12:00:14.000000000 +0300
+++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h    2022-11-24 18:54:00.910286895 +0300
@@ -20,6 +20,7 @@
 #include "util.h"
 #include "List.h"
 #include "Thread/semaphore.h"
+#include <cstdarg>
 
 namespace toolkit {
 
```
And this issue can be closed

Thank you for ZLM!

**Comment by xia-chu** [comment]
> Let me remind you about
> 
> ```diff
> diff -Naur ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h
> --- ZLMediaKit/3rdpart/ZLToolKit/src/Util/logger.h      2022-11-11 12:00:14.000000000 +0300
> +++ ZLMediaKit-m/3rdpart/ZLToolKit/src/Util/logger.h    2022-11-24 18:54:00.910286895 +0300
> @@ -20,6 +20,7 @@
>  #include "util.h"
>  #include "List.h"
>  #include "Thread/semaphore.h"
> +#include <cstdarg>
>  
>  namespace toolkit {
>  
> ```
> 
> And this issue can be closed
> 
> Thank you for ZLM!

Ok, thanks!  If you don't mind, you can submit zltoolkit a pull request or wait me merge it at the weekend

**Comment by a-ucontrol** [comment]
I'll wait, don't forget, please, thank you

**Comment by xia-chu** [comment]
ok thanks





------------------ 原始邮件 ------------------
发件人: a-ucontrol ***@***.***&gt;
发送时间: 2023年4月20日 14:49
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Assign ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] 咨询描述(必填) External socket descriptor (Issue #2397)
