### ISSUE TITLE
重启MediaServer程序后，之前的拉流代理可以恢复么？

### ISSUE THREAD

**Issue by wangxiaoer3924** [ZLMediaKit/ZLMediaKit#2398]
重启MediaServer程序后，之前的拉流代理可以恢复么？我测试了一下，没有重新拉流，我想请教一下是否有这个功能，如果有从哪里配置的呀

**Comment by Dw9** [comment]
这种持久化的业务zlm应该不会加入；
你可以自己结合webhook的on_stream_channged等通知 把相关参数写到数据库里面 
重启后再去拉流
