### ISSUE TITLE
zlm启用webrtc编译时，操作系统能否使用RedHat6.5

### ISSUE THREAD

**Issue by 201811510218lh** [ZLMediaKit/ZLMediaKit#2399]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by monktan89** [comment]
这个尝试一下不就明朗了。

**Comment by 201811510218lh** [comment]
目前还申请不到环境，需要对redhat系统进行可行性分析，有用过redhat系统编译的能否给个解答？
