### ISSUE TITLE
[技术咨询] 咨询 WebRTC 播放请求与声音转码问题

### ISSUE THREAD

**Issue by jaelys** [ZLMediaKit/ZLMediaKit#2400]
**咨询的功能模块**
WebRTC 

**咨询的具体内容和问题**

编码器RTMP推流 -> ZLMediaKit(docker) -> 转协议WebRTC

1. 请问支持 webrtc://192.168.1.2/live/stream 这种格式的播放吗 ?
2. 请问容器版本，支持rtmp 中 audio aac 转 webrtc audio opus 吗?
    或是如何使用容器的情况下，透过接口处理音频转码的正确做法?

感谢伟大的项目

**Comment by xia-chu** [comment]
wiki有webrtc交互协议文档

**Comment by xia-chu** [comment]
测试地址是这种格式：
https://zlmediakit.com/index/api/whip?app=live&stream=test
https://zlmediakit.com/index/api/whep?app=live&stream=test

**Comment by jaelys** [comment]
> 测试地址是这种格式： https://zlmediakit.com/index/api/whip?app=live&stream=test https://zlmediakit.com/index/api/whep?app=live&stream=test

测试后请求成功，但返回error msg "Response missing location header"
查看whep.js，发现会获取location这个字段，不过服务器无返回
```
if (!fetched.headers.get("location"))
			throw new Error("Response missing location header")
```

请问我是否可能哪边没有注意到细节?

**Comment by xia-chu** [comment]
是的 没返回location这个字段 所以说是初步支持，能推流播放就行

**Comment by jaelys** [comment]
我后来测试容器分支 feature-transcode2
和 线上 https://zlmediakit.com/index/api/whep?app=live&stream=test
皆会收到 Request rejected with status 406 error

我使用服务自带的webrtc/index.html 测试正常 

我尝试建议前端改为 ZLMRTCClient.js 试试，非常感谢您
后续持续关注whep，有测试成功再回报您

我先关闭此issue

**Comment by xia-chu** [comment]
transcode2分支应该还没合入whip/whep特性 转码分支目前是其他小伙伴在维护
