### ISSUE TITLE
[技术咨询] 关于UDP服务器不绑定peer的IP和端口的影响咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2402]
**咨询的功能模块**
您好，为了能让rtpserver（openrtpserver）支持同一个streamID的不同质量流推给ZLM相同端口。目前修改了部分ZLM代码
（1）SSRC变了之后直接用新的覆盖，支持改变SSRC
（2）UDP传输RTP包的时候rtp服务器绑定的内容删除
` if (!bind_peer_addr) {
                            //绑定对方ip+端口，防止多个设备或一个设备多次推流从而日志报ssrc不匹配问题
                            bind_peer_addr = true;
                            rtp_socket->bindPeerAddr(addr, addr_len);
                        }`

**咨询的具体内容和问题**
经过测试同一个streamID源，切换SSRC，甚至是port，在发给ZLM可以了；当然这涉及给ZLM发流的逻辑不甚合理，切换编码质量不一定需要改变SSRC和源port，但是不在我能改变范畴里；

想请问的问题是 udp :绑定对方ip+端口,如果 我注释掉这个代码。会对ZLM的处理逻辑有什么影响吗？？？？；源端会保证发送端不会乱发的，不会出现多个源都往一个ZLM端口里发送数据的；

**注意事项**

**Comment by xiongguangjie** [comment]
不会有影响

**Comment by xuandu** [comment]
感谢大熊猫大佬；
