### ISSUE TITLE
[技术咨询] c sdk接口按需推流咨询

### ISSUE THREAD

**Issue by liangjw-editor** [ZLMediaKit/ZLMediaKit#2403]
**咨询的功能模块**
c sdk接口

**咨询的具体内容和问题**
我现在有个业务是在播放器播放rtsp地址后在没有找到流的接口里再去摄像头那边取流，然后再将摄像头的码流数据通过mk_frame_create给到zlmediakit，但是现在有个问题是如果取到流的时间过长，还没有将码流数据给到zlmediakt，这时候就没有注册到MediaSource，这时候播放器超时就关闭了，但是此时不会触发无人观看的接口，那么这个摄像头的码流就不可控了，无法知道现在不需要该摄像头的流了，无法回收资源。这种情况我应该怎么解决。

**Comment by yduis6554** [comment]
我初学zlmediakit，根据目前测试的情况看，这个问题不存在。

当发了指令给摄像头，马上关闭播放。此时如果摄像头有媒体数据上来，正常的业务逻辑，应该就会调用 mk_frame_create 创建媒体，然后写入媒体数据。只要媒体注册成功，就必然会 触发 On_mk_media_no_reader 接口。这个流程我测试过的，没有发现问题。

**Comment by xia-chu** [comment]
按需取流时间太长，导致播放器停止播放，可以增加配置文件参数，把时间调长。
