### ISSUE TITLE
如何开启zlm的录像跨天逻辑判断

### ISSUE THREAD

**Issue by sxh-netizen** [ZLMediaKit/ZLMediaKit#2405]
**咨询的功能模块**
- 如何开启zlm的录像跨天逻辑判断

**咨询的具体内容和问题**
- 我这边采取了24小时不间断录像，但是遇到了 一个录像 从 23点 40分到 隔天的凌晨 0点 10分，跨天没有处理分片逻辑，请问是我配置有问题吗
![image](https://user-images.githubusercontent.com/58098910/233241570-13c15629-a500-4258-99c5-d8cd8c17c926.png)

**Comment by xia-chu** [comment]
没问题 切片跟跨天没关系

**Comment by sxh-netizen** [comment]
好的

**Comment by xia-chu** [comment]
你跨天要切片 可以改代码逻辑 但是我觉得这个需求应该不存在

**Comment by sxh-netizen** [comment]
哦哦，好的，我和前端沟通一下，谢谢
