### ISSUE TITLE
[BUG] 国标中PS起始码冗余导致错过关键帧解析

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2409]
### 现象描述

 对接海康平台的时候发现有时候海康送流了，但是ZLM一直收不到RTP包。然后过一会超时关服务了
通过抓包看，这里有个PSdecode的bug，就是如果PSH起始码前边是00 00 00 01， 就是这个样子的00 00 00 01 00 00 01 ba ；那关键帧解析就跳过去了，调试看因为第一个01后边是00 ，然后下次找起始码就从 00 01 ba 开始，完美的错过了起始码；然后ZLM就没解析到关键帧，我测试的情况是过了一会就超时了，服务器就关闭了；

### 如何复现?
通过 rtp_test复现了该问题；

    1. 首先  这里我通过改变00 00 00 01 00 00 01 ba这里的字节内容验证了这里解析起始码存在bug
    1. 然后：这个bug影响了解析关键帧，创建视频轨道；
    1. 期望 ：这个问题应该不是ZLM的源码的，来源于3rdmediaserver ;不过我测试了4-07的版本（看最近应该没有改过同类问题），是有此问题的；如下图，这个起始码解析的时候如果v8是00，是不是应该倒退一个offset；

### 相关日志或截图
码流发送至预留邮箱：[1213642868@qq.com](mailto:1213642868@qq.com)

![图片](https://user-images.githubusercontent.com/18655816/233664636-a031b989-0297-41e5-949f-706d68c89a82.png)

**Comment by xuandu** [comment]
来更新下这个bug进展；因为ps_demuxer_header里边是没有跳过bd的实际长度的，所以遇到00 00 00 01 00 的时候我seek回去一下也行；但是实际上这个 红色位置的00 00 00 01 是他的bd 私有帧长度内容里的东西；取bd后的一个short跳过也能解决；

**Comment by xuandu** [comment]
另外在使用test rtp测试的过程中，发现RTSP拉流播放结束会崩溃；不过应该与我上边说的不bug无关，我有使用其他平台的RTP数据进行测试，任然会出现析构过程崩溃；

每次崩溃的位置可能略有不同，大部分时候是loger;如果是我操作的问题，请指正；

启动rtptest后，VLC拉取rtsp流 ：rtsp://127.0.0.1:554/rtp/700E6714
![图片](https://user-images.githubusercontent.com/18655816/233772141-399fc2ae-dcf0-4986-996e-590862e55839.png)

**Comment by xiongguangjie** [comment]
崩溃的原因应该是主线程退出，但是线程池的线程还没退出，导致崩溃了，那个ps解析的问题，你反馈到media-server 或者把码流上传的github ，我分析一下

**Comment by xuandu** [comment]
[hksss.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11302647/hksss.zip)

**Comment by xiongguangjie** [comment]
> 00 00 01
```
diff --git a/libmpeg/source/mpeg-ps-dec.c b/libmpeg/source/mpeg-ps-dec.c
index 932601f..85beaad 100644
--- a/libmpeg/source/mpeg-ps-dec.c
+++ b/libmpeg/source/mpeg-ps-dec.c
@@ -214,6 +214,7 @@ static int ps_demuxer_header(struct ps_demuxer_t* ps, struct mpeg_bits_t* reader
             r = psd_read(&ps->psd, reader);
             break;
 
+        case PES_SID_PRIVATE_1:
         case PES_SID_PRIVATE_2:
         case PES_SID_ECM:
         case PES_SID_EMM:
```
如此修复此bug,我先提交pr给media-server 的，后面再同步

**Comment by xuandu** [comment]
大佬，貌似您这样修改针对我那个码流是没有完全解决问题的；
因为您的修改是找到第一个PSH （line183:    if (!ps->sync && v8 != PES_SID_START) ）以后的事情，再出现PD进行跳过；

码流里实际的问题是，在第一个PSH前就有01 pd,并且pd私有帧里的内容 影响了找第一个PSH；

我们自己临时的修改方案有两种：
（1）不解析 01 pd，只处理PSH起始码解析的问题，因为如果出现00 00 01 00 00 01ba 这种，码流，如果第一个01后边是00 ，代码再次找PSH的时候会从00 后边开始，也就是00 00 01 00 00 01ba的第五位开始找PSH，所以就错过了PSH；
所以我在第182行，找PSH的前边加了个这个；反跳；但是我写的并不好，因为做无符号减法回跳seek，边界之类的判断我也没做；
![图片](https://user-images.githubusercontent.com/18655816/233819665-a9e36aea-d6f7-4355-b671-a9992433ca8f.png)

（2）第二种方式，可以在找到PSH，000001ba前如果找到了01 BD ,就取BD私有帧的长度进行跳过SKIP，恰巧就跳过了那个影响查找第一个PSH的00000001；
也是在182行左右，找到PSH前如果遇到的是私有帧BD进行跳过
 if (v8 == PES_SID_PRIVATE_1) {
                mpeg_bits_skip(reader, mpeg_bits_read16(reader));
            }

我们只是临时修改，规范的修改方式还需要大佬来改；

**Comment by xiongguangjie** [comment]
私有帧是有长度的，你那个ps流，ffmpeg 是可以播放的，如果ffmpeg 都无法播放，那就是码流的问题了，就不会改了。还有什么问题吗？？？？？

**Comment by xuandu** [comment]
码流是正常的，我只说问题并没有完全修改；
在下边这个位置加一个private1并不能完全解决问题，因为我一开始也是在这里加的，第一个关键帧的PSH还是找错了位置；
`  case PES_SID_PRIVATE_2:
        case PES_SID_ECM:
        case PES_SID_EMM:
        case PES_SID_DSMCC:
        case PES_SID_H222_E:
            // stream data
        case PES_SID_PADDING:`

--------------------------------------------
这个码流在关键帧的PSH BA前有bd, 现在media server的代码逻辑是先找PSH BA；BA前边（数据bd私有帧的内容部分的00 00 00 01）的 00 00 00 01会影响找第一个BA；

找第一个BA的位置不对：
![微信图片_20230423135554](https://user-images.githubusercontent.com/18655816/233822447-c75eaf69-6ae4-4fa3-b154-011f9db69efd.png)
![微信图片_20230423135606](https://user-images.githubusercontent.com/18655816/233822451-cf53747d-74fc-404e-b705-2e31872cb87b.png)

私有帧的内容会影响找BA；您在case那里加的是要找到BA之后才行，但是关键帧前边的01bd（里边的 00000001，图中的绿色部分）会有影响找第一个PSH

**Comment by xiongguangjie** [comment]
你的意思是说，第一个0xBA 会被忽略掉，因为等待0xBA的要求

**Comment by xuandu** [comment]
是的;因为他的逻辑是先找BA。但是海康这个辣鸡私有帧，刚好在视频帧前边，重点是他这个私有帧里的末尾部分的 00 00 00 01正好在00 00 01 ba的前边；以现在的PS解析逻辑，如果不先跳过BD私有帧，等它找到第一个蓝箭头的位置之后，发现V8=00，然后从下一位也就是我图中红箭头的位置开始找startcode，刚好错过了正确的 00 00 01 BA；所以我修改的方案1，回跳一个才会起作用；
另外我那个修改方案2，因为刚好跳过我红框前边的那些个00，所以没有影响到找第一个ba; 
![图片](https://user-images.githubusercontent.com/18655816/233823230-edfd952a-07fa-4d1f-9774-429edd26ae17.png)

**Comment by xiongguangjie** [comment]
太巧了，这么修改吧
```
diff --git a/libmpeg/source/mpeg-ps-dec.c b/libmpeg/source/mpeg-ps-dec.c
index 932601f..d5e62e8 100644
--- a/libmpeg/source/mpeg-ps-dec.c
+++ b/libmpeg/source/mpeg-ps-dec.c
@@ -165,6 +165,21 @@ static int ps_demuxer_packet(struct ps_demuxer_t *ps, const uint8_t* data, size_
     return r;
 }
 
+static int ps_demuxer_sid_can_skip(uint8_t sid){
+     switch (sid)
+        {
+        case PES_SID_PRIVATE_1:
+        case PES_SID_PRIVATE_2:
+        case PES_SID_ECM:
+        case PES_SID_EMM:
+        case PES_SID_DSMCC:
+        case PES_SID_H222_E:
+        case PES_SID_PADDING:
+            return 1;
+        default:
+            return 0;
+        }
+}
 static int ps_demuxer_header(struct ps_demuxer_t* ps, struct mpeg_bits_t* reader)
 {
     int r;
@@ -179,9 +194,14 @@ static int ps_demuxer_header(struct ps_demuxer_t* ps, struct mpeg_bits_t* reader
         v8 = mpeg_bits_read8(reader);
         if (mpeg_bits_error(reader))
             break;
-
-        if (!ps->sync && v8 != PES_SID_START)
-            continue; // wait for 00 00 01 BA
+        
+        if (!ps->sync && v8 != PES_SID_START){
+            if(ps_demuxer_sid_can_skip(v8)){
+                // skip some no useless data
+            }else{
+                continue; // wait for 00 00 01 BA
+            }
+        }
 
         // fix HIK H.265: 00 00 01 BA 00 00 01 E0 ...
         if (0x000001 == (mpeg_bits_tryread(reader, 3) & 0xFFFFFF))
@@ -214,6 +234,7 @@ static int ps_demuxer_header(struct ps_demuxer_t* ps, struct mpeg_bits_t* reader
             r = psd_read(&ps->psd, reader);
             break;
 
+        case PES_SID_PRIVATE_1:
         case PES_SID_PRIVATE_2:
         case PES_SID_ECM:
         case PES_SID_EMM:
```

**Comment by xuandu** [comment]
ok,完美；感谢熊猫大佬
