### ISSUE TITLE
cpu i711代 内存8g服务器 在局域网中 单台服务器能支持多少客户端播放?

### ISSUE THREAD

**Issue by luguomeng** [ZLMediaKit/ZLMediaKit#2410]
博主你好，我在本地装了一个centos7的虚拟机，配置如下：
![image](https://user-images.githubusercontent.com/15061664/233813635-5674b5b8-c889-49b3-8f8d-882c3d28c54d.png)
推流服务器用的是obs,协议用的是rtmp,用zlm做拉流推流时，浏览器有30个播放器，全部处于卡死状态，截图如下：
![image](https://user-images.githubusercontent.com/15061664/233813711-d60cb325-c945-404b-9263-6d4cd2e36e2d.png)
zlm 打印的日志如下：
![image](https://user-images.githubusercontent.com/15061664/233813735-94cc41ad-f657-43d0-b0fe-54930f4d34a7.png)

![image](https://user-images.githubusercontent.com/15061664/233813747-ddd6ff1d-1c36-4d3a-b09c-0eff212fff25.png)

top 信息:
![image](https://user-images.githubusercontent.com/15061664/233813767-66c595e2-8914-4334-82ce-a6a515b18d7e.png)

我现在不清楚是我配置有问题   zlm 具体单台服务器可以支撑多少  希望博主能回复一下（在局域网中测试，浏览器中5个播放器可以正常播放）

**Comment by xia-chu** [comment]
如果你很忙 不按照issue模板提交 那么我们也可以说 我们很忙 可以拒绝回答issue。

**Comment by luguomeng** [comment]
牛
