### ISSUE TITLE
addStreamProxy 添加流代理 极限是多少

### ISSUE THREAD

**Issue by orangezh0806** [ZLMediaKit/ZLMediaKit#2411]
**咨询的功能模块**
- addStreamProxy 添加流代理 极限是多少

**咨询的具体内容和问题**
- 最大能支持同时添加多少，我测试到的极限是1000左右，是否还能更大？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
单进程可以上万，具体跟你的配置文件、协议、码率、机器配置有关系

**Comment by orangezh0806** [comment]
主机配置：
OS：Windows Server

**Comment by orangezh0806** [comment]
主机配置：
OS：Windows Server

**Comment by orangezh0806** [comment]
主机配置：
OS：Windows Server
CPU：32C 64线程
Memory：64G

配置文件：
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/OZ-Dev/tools/ffmpeg/bin/ffmpeg.exe
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -t 0.001 %s

[general]
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=FQ3TF8yT83wh5Wvz
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.101.128:18080/index/hook/on_play
on_publish=http://192.168.101.128:18080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtp_server_timeout=http://192.168.101.128:18080/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://192.168.101.128:18080/index/hook/on_send_rtp_stopped
on_server_keepalive=http://192.168.101.128:18080/index/hook/on_server_keepalive
on_server_started=http://192.168.101.128:18080/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://192.168.101.128:18080/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.101.128:18080/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.101.128:18080/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
timeoutSec=20

[http]
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:Git_Unkown_commit/Git_Unkown_time,branch:Git_Unkown_branch,build time:2023-02-01T09:36:38)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=0
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
tcpPort=8000
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
modifyStamp=0
port=1935
sslport=0

[rtp]
audioMtuSize=600
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-30500
ps_pt=96
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

视频协议为：RTSP
码率：~700Kbps

**Comment by xia-chu** [comment]
要实地压测的 评估不准确的

**Comment by xia-chu** [comment]
这里适当关闭一些协议，可以提高性能
```ini
[protocol]
add_mute_audio=1
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=0
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0
```

**Comment by orangezh0806** [comment]
> 

好的，谢谢大佬的指导，非常感谢！！！

**Comment by orangezh0806** [comment]
> 总之 zlm各方面性能都是开源界的顶峰

哈哈哈，确实牛 (๑•̀ㅂ•́)و✧
