### ISSUE TITLE
[技术咨询] WebRTC支持H265

### ISSUE THREAD

**Issue by flyskyosg** [ZLMediaKit/ZLMediaKit#2414]
请问，现在的服务能否支持WebRTC通过DataChannel传输H265的视频流数据给前端，前端再解析？如果可以推送，有哪些调用流程和注意事项？
谢谢

**Comment by xiongguangjie** [comment]
需要二次开发，现在是不支持的

**Comment by xia-chu** [comment]
这种非标功能也不会去支持
