### ISSUE TITLE
[技术咨询] 使用容器feature-transcode2，设置hook on_publish 鉴权，webrtc无声音或未转码

### ISSUE THREAD

**Issue by jaelys** [ZLMediaKit/ZLMediaKit#2417]
**咨询的功能模块**
webrtc

**咨询的具体内容和问题**
rtmp (h.264 + aac ) -> ZLMediaKit -> webrtc

使用容器feature-transcode2
如果hook中 on_publish 不设置，webrtc 播放可以正常听到转码后的opus声音，log记录查看，可以看见aac转码opus
如果hook中 on_publish  设置鉴权，并设置返回如下json，webrtc播放无法时没有声音或没有aac转码，log记录查看，推流时未启动aac转码
```
{
  "code" = 0,
  "msg" = "success",
  "enable_mp4" = true
}
```
请问是否我的返回参数不完整造成?，我尝试了多种返回值，都是相同的问题
查看文挡，有个默认回复参数，我的理解是非必需参数，应会采用服务器预设设置值
请指导我该如何正确的完成此功能，再次感谢您

设置文件部份如下：

```ini
[hook]
enable=1
on_flow_report=
on_http_access=
on_play=
on_publish=https://func.goodjob.com/api/on-publish?code=xxxxxxxx
on_record_mp4=https://func.goodjob.com/api/on_record_mp4?code=xxxxxxxx
on_record_ts=
on_rtp_server_timeout=
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=

[protocol]
add_mute_audio=1
audio_transcode=1
continue_push_ms=15000
enable_audio=1
enable_fmp4=0
enable_hls=1
enable_mp4=0
enable_rtc=1
enable_rtmp=1
enable_rtsp=0
enable_ts=0
fmp4_demand=0
hls_demand=1
hls_save_path=./www
modify_stamp=0
mp4_as_player=1
mp4_max_second=7200
mp4_save_path=./www
rtc_demand=0
rtmp_demand=1
rtsp_demand=1
ts_demand=1
```

**Comment by xia-chu** [comment]
@mtdxc 大佬可否看下？

**Comment by mtdxc** [comment]
你试着返回这个看看。
{
  "code" = 0,
  "msg" = "success",
  "enable_mp4" = true,
  "audio_transcode" = true
}

**Comment by jaelys** [comment]
> 你试着在Hook中返回这个看看。
> 
> ```
> {
>   "code" = 0,
>   "msg" = "success",
>   "enable_mp4" = true,
>   "audio_transcode" = true
> }
> ```

尝试加了"audio_transcode" = true，还是一样没有声音

**Comment by mtdxc** [comment]
那你发下zlm的日志看看吧。

**Comment by mtdxc** [comment]
你这都触发加静音帧的操作了，on_pulish发的这流刚开始没发音频帧么？zlm有个机制10s没收到音频帧的话会主动增加静音帧，之后再来流也加不进去了。

**Comment by jaelys** [comment]
是的我检查过，发流的是编码器设备，RTMP推流，有无设置鉴权，RTMP Play时都能正常听见，音频流是推有出来

**Comment by mtdxc** [comment]
@xia-chu 你怎么看呢，我这边没法重新这bug，单从提供的日志上看是连续10s没音频，增加静音音轨导致的。。

**Comment by xia-chu** [comment]
@jaelys  这个问题能用ffmpeg推流复现吗？

**Comment by jaelys** [comment]
好的抱歉，我没有做好测试回复，我准备一下新环境验证，并用ffmpeg及 obs测试一下，非常感谢

**Comment by jaelys** [comment]
@mtdxc 您好，
之前的测试结果，后面经过多次的测试，确认设备推流是有带音频的，但是无法通过鉴权顺利启动AAC转码
ffmpeg没有这个问题，但是只要先让ffmpeg推流启动aac转码，设备接着推流鉴权，也是能启动aac转码的，
我还能提供哪方面的记录，能帮助厘清这个问题，可以的话方便指导我，非常感谢

**Comment by mtdxc** [comment]
> @mtdxc 您好， 之前的测试结果，后面经过多次的测试，确认设备推流是有带音频的，但是无法通过鉴权顺利启动AAC转码 ffmpeg没有这个问题，但是只要先让ffmpeg推流启动aac转码，设备接着推流鉴权，也是能启动aac转码的， 我还能提供哪方面的记录，能帮助厘清这个问题，可以的话方便指导我，非常感谢

加我Q：305066675 私聊吧

**Comment by mtdxc** [comment]
你修改下AACRtmp.cpp，加入如下InfoL的日志，
```
void AACRtmpDecoder::inputRtmp(const RtmpPacket::Ptr &pkt) {
    // add this log
    InfoL << "got rtmp " << pkt->stream_index << "," << pkt->time_stamp << ", cfg=" << pkt->isCfgFrame();
    if (pkt->isCfgFrame()) {
        _aac_cfg = getAacCfg(*pkt);
        if (!_aac_cfg.empty()) {
            onGetAAC(nullptr, 0, 0);
        }
        return;
    }

    if (!_aac_cfg.empty()) {
        onGetAAC(pkt->buffer.data() + 2, pkt->buffer.size() - 2, pkt->time_stamp);
    }
}
```
然后用推流器+鉴权推RTMP，看看有没有got rtmp输出，一般来说有一行 cfg=1的输出，如下：
```
AACRtmp.cpp:36 inputRtmp | got rtmp 1,0, cfg=1
```

**Comment by jaelys** [comment]
好的，我很久没有编译 C的经验了，目前我都使用云容器部署，我搭建一下VM环境，可能需要多些时间，回应太慢请见谅

**Comment by mtdxc** [comment]
有没有发现差别，用设备推的RTMP包没有cfg=1的输出，ffmpeg推第一个包cfg=1。
应该是设备推aac流没发aac的cfg帧吧

**Comment by jaelys** [comment]
> 有没有发现差别，用设备推的RTMP包没有cfg=1的输出，ffmpeg推第一个包cfg=1。 应该是设备推aac流没发aac的cfg帧吧， 我截的代码也说的很清楚，!_aac_cfg为空的话，不往下回调数据，而_aac_cfg在收到cfg=1时更新

如果不透过鉴权回调，可以顺利开启aac转码
透过鉴权回调的话，则出现大佬说的这种情况
请问能否指导一下更好的解决方案，设备是厂家的，我无法改变

**Comment by jaelys** [comment]
@mtdxc 大佬您好，

最近在排查 flv.js 无法播放声音的问题时，发现相同的现象，只要鉴权了，就会发生无声音
[FLVDemuxer] > Parsed onMetaData
[FLVDemuxer] > Parsed AVCDecoderConfigurationRecord
[FLVDemuxer] > Parsed AudioSpecificConfig  <-- 鉴权后，此行永远不会出现，取消WebHook on_publish ，此行就能正常

有可能设备是有发送的，但不知为何经过鉴权后，就无法正常，能否请大佬指导一下

**Comment by mtdxc** [comment]
你们用master版本测看看，如果问题依旧的话，建议提到主线上去。
这应该是rtmp客户端协议和服务器实现的不匹配问题，
我rtmp协议也不是很熟哈，这项目有其他rtmp协议高手会处理哈。

**Comment by mtdxc** [comment]
@jaelys  我在transcode2分支为你这情况做了个特殊处理，你拉下代码，看问题修复了没？

**Comment by jaelys** [comment]
@mtdxc 大佬没问题了，测试了一下其他hls ts 拉流也都可以，请问transcode分支也会同时支持这个解决方案吗?

**Comment by mtdxc** [comment]
就一个提交你自己cherry-pick过去transcode分支就行，同时我也建议 @xia-chu cherry-pick 最后一个提交到主线上去，
你这种RTMP推流器在主线代码中应该也是会遇到这问题的。

**Comment by xia-chu** [comment]
> 就一个提交你自己cherry-pick过去transcode分支就行，同时我也建议 @xia-chu cherry-pick [274a1d5](https://github.com/ZLMediaKit/ZLMediaKit/commit/274a1d5ca5f700e0946689c8f08e96f37a5710d9) 到主线上去， 像这种RTMP推流器在主线代码中要遇到鉴权的话，应该也是会遇到这问题的。

为了兼容这种不规范的推流器，曾经在提交 d2fec801c98c71c73170d664e565cd93cb154a80 中有优化。
当时在鉴权返回前缓存了metadata，但是忘了缓存config frame。

这种推流器很奇葩，服务器没返回成功，就开始推送metadata和数据了。

**Comment by mtdxc** [comment]
> 就一个提交你自己cherry-pick过去transcode分支就行，同时我也建议 @xia-chu cherry-pick [274a1d5](https://github.com/ZLMediaKit/ZLMediaKit/commit/274a1d5ca5f700e0946689c8f08e96f37a5710d9) 到主线上去， 像这种RTMP推流器在主线代码中要遇到鉴权的话，应该也是会遇到这问题的。

transcode分支也cherry-pick这个提交了，这个issue你看下，应该可以关了。

**Comment by xia-chu** [comment]
等我在master分支缓存config frame再关吧

**Comment by xia-chu** [comment]
我这样写的：
```c++
Index: src/Rtmp/RtmpSession.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtmp/RtmpSession.cpp b/src/Rtmp/RtmpSession.cpp
--- a/src/Rtmp/RtmpSession.cpp	(revision b05463272720633820e9482d2c5ccc99eb063cd4)
+++ b/src/Rtmp/RtmpSession.cpp	(revision 157aa31f36036f16d329cea535be064ff5d865cd)
@@ -536,7 +536,14 @@
     case MSG_AUDIO:
     case MSG_VIDEO: {
         if (!_push_src) {
-            WarnL << "Not a rtmp push!";
+            if (_ring_reader) {
+                throw std::runtime_error("Rtmp player send media packets");
+            }
+            if (packet->isConfigFrame()) {
+                auto id = packet->type_id;
+                _push_config_packets.emplace(id, std::move(packet));
+            }
+            WarnL << "Rtmp pusher send media packet before handshake completed!";
             return;
         }
 
@@ -544,6 +551,12 @@
             _set_meta_data = true;
             _push_src->setMetaData(_push_metadata ? _push_metadata : TitleMeta().getMetadata());
         }
+        if (!_push_config_packets.empty()) {
+            for (auto &pr : _push_config_packets) {
+                _push_src->onWrite(std::move(pr.second));
+            }
+            _push_config_packets.clear();
+        }
         _push_src->onWrite(std::move(packet));
         break;
     }
Index: src/Rtmp/RtmpSession.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtmp/RtmpSession.h b/src/Rtmp/RtmpSession.h
--- a/src/Rtmp/RtmpSession.h	(revision b05463272720633820e9482d2c5ccc99eb063cd4)
+++ b/src/Rtmp/RtmpSession.h	(revision 157aa31f36036f16d329cea535be064ff5d865cd)
@@ -97,6 +97,7 @@
     MediaInfo _media_info;
     std::weak_ptr<RtmpMediaSource> _play_src;
     AMFValue _push_metadata;
+    std::map<uint8_t, RtmpPacket::Ptr> _push_config_packets;
     RtmpMediaSourceImp::Ptr _push_src;
     std::shared_ptr<void> _push_src_ownership;
     RtmpMediaSource::RingType::RingReader::Ptr _ring_reader;

```

**Comment by mtdxc** [comment]
> 我这样写的：
> 
> ```diff
> Index: src/Rtmp/RtmpSession.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Rtmp/RtmpSession.cpp b/src/Rtmp/RtmpSession.cpp
> --- a/src/Rtmp/RtmpSession.cpp	(revision b05463272720633820e9482d2c5ccc99eb063cd4)
> +++ b/src/Rtmp/RtmpSession.cpp	(revision 157aa31f36036f16d329cea535be064ff5d865cd)
> @@ -536,7 +536,14 @@
>      case MSG_AUDIO:
>      case MSG_VIDEO: {
>          if (!_push_src) {
> -            WarnL << "Not a rtmp push!";
> +            if (_ring_reader) {
> +                throw std::runtime_error("Rtmp player send media packets");
> +            }
> +            if (packet->isConfigFrame()) {
> +                auto id = packet->type_id;
> +                _push_config_packets.emplace(id, std::move(packet));
> +            }
> +            WarnL << "Rtmp pusher send media packet before handshake completed!";
>              return;
>          }
>  
> @@ -544,6 +551,12 @@
>              _set_meta_data = true;
>              _push_src->setMetaData(_push_metadata ? _push_metadata : TitleMeta().getMetadata());
>          }
> +        if (!_push_config_packets.empty()) {
> +            for (auto &pr : _push_config_packets) {
> +                _push_src->onWrite(std::move(pr.second));
> +            }
> +            _push_config_packets.clear();
> +        }
>          _push_src->onWrite(std::move(packet));
>          break;
>      }
> Index: src/Rtmp/RtmpSession.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Rtmp/RtmpSession.h b/src/Rtmp/RtmpSession.h
> --- a/src/Rtmp/RtmpSession.h	(revision b05463272720633820e9482d2c5ccc99eb063cd4)
> +++ b/src/Rtmp/RtmpSession.h	(revision 157aa31f36036f16d329cea535be064ff5d865cd)
> @@ -97,6 +97,7 @@
>      MediaInfo _media_info;
>      std::weak_ptr<RtmpMediaSource> _play_src;
>      AMFValue _push_metadata;
> +    std::map<uint8_t, RtmpPacket::Ptr> _push_config_packets;
>      RtmpMediaSourceImp::Ptr _push_src;
>      std::shared_ptr<void> _push_src_ownership;
>      RtmpMediaSource::RingType::RingReader::Ptr _ring_reader;
> ```

嗯，应该没问题的，主要原理都是缓存帧后重放下，
当然了，实际得 @jaelys 协助测试下，我们都没这推流器哈。

**Comment by jaelys** [comment]
感谢大佬们，我这周测试一下三个docker，再来汇报一下。

**Comment by jaelys** [comment]
很抱歉隔了很久才来汇报，手里有的推流设备硬件都能正常，感谢伟大的项目及大佬门的支持反馈
