### ISSUE TITLE
证书到期，证书新建后，服务是否需要重启

### ISSUE THREAD

**Issue by cwy1996** [ZLMediaKit/ZLMediaKit#2420]
**咨询的功能模块**
- ssl

**咨询的具体内容和问题**
- 当部署的证书到期后，新建证书覆盖到default.pem中，zlm服务是否需要重启进行加载，还是不用进行重启自动会加载

**Comment by linj121** [comment]
请问后来是怎么解决的呢，我这边也有同样问题，每次更新完证书需要

**Comment by cwy1996** [comment]
> 请问后来是怎么解决的呢，我这边也有同样问题，每次更新完证书需要手动重启服务器，用`killall -2 MediaServer`热更新没用

没走自带的，走的代理

**Comment by linj121** [comment]
> > 请问后来是怎么解决的呢，我这边也有同样问题，每次更新完证书需要手动重启服务器，用`killall -2 MediaServer`热更新没用
> 
> 
> 
> 没走自带的，走的代理

是什么代理呢？可否展开说下

**Comment by cwy1996** [comment]
> > > 请问后来是怎么解决的呢，我这边也有同样问题，每次更新完证书需要手动重启服务器，用`killall -2 MediaServer`热更新没用
> > 
> > 
> > 没走自带的，走的代理
> 
> 是什么代理呢？可否展开说下

nginx 或者 openresty 代理你的对应端口走 443

**Comment by linj121** [comment]
> > > > 请问后来是怎么解决的呢，我这边也有同样问题，每次更新完证书需要手动重启服务器，用`killall -2 MediaServer`热更新没用
> 
> > > 
> 
> > > 
> 
> > > 没走自带的，走的代理
> 
> > 
> 
> > 是什么代理呢？可否展开说下
> 
> 
> 
> nginx 或者 openresty 代理你的对应端口走 443

ok明白了，感谢解答
