### ISSUE TITLE
[技术咨询] zlm处理视频流时 TCP window update 问题

### ISSUE THREAD

**Issue by fengyunpt** [ZLMediaKit/ZLMediaKit#2421]
**咨询的功能模块**
- zlm收到海康推送的视频流后的处理问题

**咨询的具体内容和问题**
-  zlm收到海康推送的视频流后的，经抓包分析 如下（海康ip：10.191.103.18  zlm：10.193.144.224）
   最后zlm服务器发送了 TCP window update ，是海康推送的视频太快了，服务器来不及处理吗？需要怎么优化？能给个建议吗
![image](https://user-images.githubusercontent.com/19603937/234227077-cd569c35-15a0-4a1c-8b59-b36b02b50ec9.png)

   
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by fengyunpt** [comment]
echo 8388608 > /proc/sys/net/core/rmem_max

echo 8388608 > /proc/sys/net/core/rmem_default

echo 8388608 > /proc/sys/net/core/wmem_default

echo 8388608 > /proc/sys/net/core/wmem_max

echo "4096 8388608 8388608" > /proc/sys/net/ipv4/tcp_rmem

echo "4096 8388608 8388608" > /proc/sys/net/ipv4/tcp_wmem 

朋友们帮我看看这样配置行不行， Linux version 3.10.0-1160.49.1.el7.x86_64   centos7

**Comment by alexliyu7352** [comment]
没必要全部增大, 一般增加读的缓存就可以.
实际上读缓存还可以增加更大一些

fengyunpt ***@***.***> 于2023年4月25日周二 18:19写道：

**Comment by xia-chu** [comment]
TCP的服务都不要格外调整内核参数，因为tcp有流控，除非zlm负载太高 否则不会有问题

**Comment by xia-chu** [comment]
可以提高下zlm的日志

**Comment by fengyunpt** [comment]
如下是不同情况的日志信息： 
1: onError | 612-56(10.191.103.18:5886) 12011000002000000088_12011010001311522339 2(receive rtp timeout)
2: 未就绪的的track，不能缓存太多的帧，否则可能内存溢出
config.xml 
如果track未就绪，我们先缓存帧数据，但是有最大个数限制，防止内存溢出 unready_frame_cache=100
--------
第一种情况：是不是海康推送的视频流有问题，tcp方式？
第二种情况：是不是海康推送的视频流track有问题？

**Comment by xia-chu** [comment]
不是 你是不是开启hls/mp4录制了 而且录制很多路了？

**Comment by fengyunpt** [comment]
> 不是 你是不是开启hls/mp4录制了 而且录制很多路了？

没有开启录制，www下面也没有录制文件
#是否开启转换为hls
enable_hls=1
#是否开启MP4录制
enable_mp4=0
#是否开启转换为rtsp/webrtc
enable_rtsp=1
#是否开启转换为rtmp/flv
enable_rtmp=1
#是否开启转换为http-ts/ws-ts
enable_ts=1
#是否开启转换为http-fmp4/ws-fmp4
enable_fmp4=1

#是否将mp4录制当做观看者
mp4_as_player=0
#mp4切片大小，单位秒
mp4_max_second=3600
#mp4录制保存路径
mp4_save_path=./www

**Comment by xia-chu** [comment]
不要开hls





------------------ 原始邮件 ------------------
发件人: fengyunpt ***@***.***&gt;
发送时间: 2023年4月27日 21:30
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] zlm处理视频流时 TCP window update 问题 (Issue #2421)





  
不是 你是不是开启hls/mp4录制了 而且录制很多路了？
  
没有开启录制，www下面也没有录制文件
 #是否开启转换为hls
 enable_hls=1
 #是否开启MP4录制
 enable_mp4=0
 #是否开启转换为rtsp/webrtc
 enable_rtsp=1
 #是否开启转换为rtmp/flv
 enable_rtmp=1
 #是否开启转换为http-ts/ws-ts
 enable_ts=1
 #是否开启转换为http-fmp4/ws-fmp4
 enable_fmp4=1
 
#是否将mp4录制当做观看者
 mp4_as_player=0
 #mp4切片大小，单位秒
 mp4_max_second=3600
 #mp4录制保存路径
 mp4_save_path=./www
