### ISSUE TITLE
port_range配置的端口范围需要允许公网访问吗

### ISSUE THREAD

**Issue by shishuai19910217** [ZLMediaKit/ZLMediaKit#2424]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
port_range配置的端口范围给rtsp/rtp服务器使用，如果你要开启这个服务，需要对公网暴露。
***技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue***
