### ISSUE TITLE
[技术咨询] 关于265打包的问题-不确定是不是bug所以提了技术咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2425]
**咨询的功能模块**
ZLM服务器转协议（rtmp转rtsp），H265大于MTU的时候是会使用FU打包方式分包的；这边遇到一个奇怪的ZLM输出，这个P帧是个单包1400长度的；但是这个包还是使用了FU模式打包，按理说应该走的signal-nalu打包的；可是输出走的数据是0x62 0x01 0x41;

我为什么确定他是单包数据呢，首先，ZLM输出的RTSP我保存下来，别人反馈给我的现象是丢P帧后边全部灰色花屏了（给了我RTsp解析出的265裸流），然后我手动从ZLM的RTSP输出中把 0x62 0x010x41后边的那帧数据的字节全部拷贝出来，粘贴到265裸流的对应位置，加上起始码，然后265再用elecard播放就不会花屏了；

我反复看了打包的代码感觉没什么问题，但是抓包的RTSP 却在花瓶帧位置出现两个连续的0x62 0x01 0x41,这个感觉不太对，因为播放端（VLC，不知道里边怎么实现的），丢的这帧1391字节（算上 00 00 00 01 02 01），按代码正常逻辑该打0x620x010x81的；可是这个单包居然是FU-A 0x62 0x01 0x41,起始码；按照代码的逻辑长度就是1386~1387字节；这里有点对不上；

播放端未能正确解析出来的帧：
![图片](https://user-images.githubusercontent.com/18655816/234516607-ff6358ee-e06c-4f1a-84ad-3ef9fd6bd83b.png)

![图片](https://user-images.githubusercontent.com/18655816/234516345-4a64c84a-7fe2-4522-954d-5a6541719580.png)
![图片](https://user-images.githubusercontent.com/18655816/234516500-eb375bfd-16c1-4f9a-9b06-f53e2faab0f3.png)

然后我对照着264 的代码看了一下：

假设264的一个P帧是1386~1387；逻辑上其实并没有才用FU打包；

![图片](https://user-images.githubusercontent.com/18655816/234518480-af3d2352-ec30-4c3a-ab96-a28d76e58262.png)

**咨询的具体内容和问题**
感觉这里打包还是有些差异的，尽管看输出，ZLM输出的RTP数据是存在的，但是VLC解析后并不能解析；尽管我可以说数据正常，，但是往往用户就想用某个软件看；只能在这找不同了；

附件是ZLM输出的数据；在1626帧；位置出现异常；
8518	2023-04-24 14:54:02.947510	61.27.178.101	61.27.31.69	H.264	1470	PT=DynamicRTP-Type-96, SSRC=0x5BB76, Seq=56481, Time=3017086304, Mark Slice-A；希望能看看是否存在265打包异常；
因为我这帧异常的P帧，并不是1386-1387字节，所以我理解他要么是stap-A ,要么应该是 0x62 0x01 0x81,不太可能是 0x62 0x010x41,假设真的那么凑巧这个P帧就是1386~1387字节，为什么不是像264一样，采用signal-nalu、

[rtsp-1 -origin.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11330773/rtsp-1.-origin.zip)

**Comment by xuandu** [comment]
[265.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11330822/265.zip)
这是实际VLC播放的265和我根据RTSP输出手动补缺失P帧的265；

**Comment by xiongguangjie** [comment]
修改配置文件 videoMtuSize的大小，先解决

**Comment by xiongguangjie** [comment]
ffplay 没问题，vlc 播放花了

**Comment by xuandu** [comment]
你觉得他会不会是不支持FU单包打包的数据；话说您怎么播放的那个RTSP；有没有什么趁手工具，大佬分享下

**Comment by xiongguangjie** [comment]
vlc也是用live555 来拉取rtsp流的，我也是用ffplay 来播放测试的，没什么好用的工具

**Comment by xuandu** [comment]
我已经验证过了，应该就是VLC不支持单包FU-A打包；我是这样操作的，我把RTSP那个有问题的P帧手动修改了字节，我那帧就能用工具解析出来了
![图片](https://user-images.githubusercontent.com/18655816/234545733-1b9263a1-121d-4fee-8d19-18249bfd21a9.png)
但是可能我对协议不是很了解，我改完这帧，这个P帧是能显示了，但是后边的帧都没解析出来

**Comment by xuandu** [comment]
所以是否考虑给这里跟H264同步，
![图片](https://user-images.githubusercontent.com/18655816/234546693-cd8e9bba-ec26-45f4-be12-331642037c86.png)
感觉现在很多厂家的播放器估计单包都不会打FU-A；有些播放器会做支持，有些播放器不做支持；他可能会认为这个单包为什么没有start-fu

**Comment by xiongguangjie** [comment]
> 所以是否考虑给这里跟H264同步， ![图片](https://user-images.githubusercontent.com/18655816/234546693-cd8e9bba-ec26-45f4-be12-331642037c86.png) 感觉现在很多厂家的播放器估计单包都不会打FU-A；有些播放器会做支持，有些播放器不做支持；他可能会认为这个单包为什么没有start-fu

改了之后应该还是有问题，我这样改的，还是会花屏
```
diff --git a/src/Extension/H265Rtp.cpp b/src/Extension/H265Rtp.cpp
index 246b3ea..23bbb10 100644
--- a/src/Extension/H265Rtp.cpp
+++ b/src/Extension/H265Rtp.cpp
@@ -302,7 +302,7 @@ void H265RtpEncoder::packRtpFu(const char *ptr, size_t len, uint64_t pts, bool i
 }
 
 void H265RtpEncoder::packRtp(const char *ptr, size_t len, uint64_t pts, bool is_mark, bool gop_pos){
-    if (len + 3 <= getMaxSize()) {
+    if (len <= getMaxSize()) {
         //signal-nalu 
         RtpCodec::inputRtp(makeRtp(getTrackType(), ptr, len, is_mark, pts), gop_pos);
     } else {
```

**Comment by xuandu** [comment]
不好意思我要更正下我的说法，我这边因为看到VLC也花屏【我并不知道怎么用RTSP的dump跟VLC一起测试】，我同事给了个工具能拿RTSP里边的H265（不知道谁写的，无法溯源）花屏效果和VLC一样，所以我就认为它和VLC内部是一个处理逻辑了；因为我手动改了字节后，我那个工具能解析出那个花屏的P帧1626【252】；所以我的说法可能有些误导了

**Comment by xuandu** [comment]
您能顺便教一下怎么用dump的RTSP来给ZLM输入，用VLC测试吗？因为我这边不知道如何复用这个dump回滚给ZLM，在VLC拉流测试；所以如果你这样改还不行，我自己就没有进一步看问题的手段了。“改了之后应该还是有问题，我这样改的，还是会花屏”---能教一下测试过程吗

**Comment by xiongguangjie** [comment]
> 您能顺便教一下怎么用dump的RTSP来给ZLM输入，用VLC测试吗？因为我这边不知道如何复用这个dump回滚给ZLM，在VLC拉流测试；所以如果你这样改还不行，我自己就没有进一步看问题的手段了。“改了之后应该还是有问题，我这样改的，还是会花屏”---能教一下测试过程吗

https://blog.csdn.net/weixin_34319374/article/details/91961180 参考这个，你这个有些数据没有抓到

**Comment by xiongguangjie** [comment]
你可以在服务器端抓包用tcpdump，不一定在客户端抓

**Comment by xuandu** [comment]
给到我只有这个dump。我们自己的设备和机器，测试不到这种情况；到我手里的就只有这个demp了；我把你那天给改的打配置帧给回退他们现场就测试不到花屏了，但是我觉得这个问题和配置帧没有关系，这个花的位置就是个P帧，跟打配置帧木有关系呀；我再反复要求人家给我提供数据包，现场估计有点困难【手动笑哭】

**Comment by xiongguangjie** [comment]
> 给到我只有这个dump。我们自己的设备和机器，测试不到这种情况；到我手里的就只有这个demp了；我把你那天给改的打配置帧给回退他们现场就测试不到花屏了，但是我觉得这个问题和配置帧没有关系，这个花的位置就是个P帧，跟打配置帧木有关系呀；我再反复要求人家给我提供数据包，现场估计有点困难【手动笑哭】

是哪个提交，就是那个videoMtuSize 配置修改后就不会出现了？？？

**Comment by xuandu** [comment]
我不要误导哈，就是那天我不是跟你反馈过一个SDP宽高与实际宽高不对应，您在265打包的关键帧前边加了配置帧，那个改动；后来回退回去他们说测测不出现了，但是我觉得没关系，配置帧和这个P帧的问题离得老远；可能是只是HK的码流不出现那种单包的数据了我估计；

**Comment by xuandu** [comment]
![图片](https://user-images.githubusercontent.com/18655816/234571040-97f4e741-084b-4391-a0fc-48d7846812af.png)
你说你这样改还花？应该不是花在同一个位置了吧；还是1626？

**Comment by xiongguangjie** [comment]
> ![图片](https://user-images.githubusercontent.com/18655816/234571040-97f4e741-084b-4391-a0fc-48d7846812af.png) 你说你这样改还花？应该不是花在同一个位置了吧；还是1626？

这个是我推vlc的那个265有花屏，我不清楚是不是你的码流比较特殊，ffplay 没问题，但是vlc感觉问题有些多

**Comment by xiongguangjie** [comment]
vlc 播放265,我一般是用ffplay 测试的，vlc用得少，明天再看看用其他265看是否会出现吧

**Comment by xuandu** [comment]
> 我不要误导哈，就是那天我不是跟你反馈过一个SDP宽高与实际宽高不对应，您在265打包的关键帧前边加了配置帧，那个改动；后来回退回去他们说测测不出现了，但是我觉得没关系，配置帧和这个P帧的问题离得老远；可能是只是HK的码流不出现那种单包的数据了我估计；

我大概知道为什么回退修改Commits on Apr 6, 2023 那天的不会花了；我这个P帧正好是1387字节；按照你之前的代码1387是会走startcode（else分支）打包的，只有大于1387才会走fu.  但是现在的代码1387字节会走FU打包；

**Comment by xiongguangjie** [comment]
那个这个1400 不也是会出现一样的问题

**Comment by xuandu** [comment]
不会呀：Commits on Apr 6, 2023 这个代码1400会走FU分包的；现在的代码1400也会分包；
但是假设是1387：Commits on Apr 6, 2023 会走single-nale;现在的代码走fu-a"FU单包END打包"；我想说的不是它走不走fu-a；而是它走的是FU-A 分包打包还是单包打包； 1387字节走fu-A ,如果把你说的MTU调小，也会走FU分包打包【有start  0x62 0x01 0x81,有end 0x41】
我想说的是你上一个版本走FU的都是有start有end的，不会是单包FU-A；

**Comment by xiongguangjie** [comment]
> 不会呀：Commits on Apr 6, 2023 这个代码1400会走FU分包的；现在的代码1400也会分包； 但是假设是1387：Commits on Apr 6, 2023 会走single-nale;现在的代码走fu-a"FU单包END打包"；我想说的不是它走不走fu-a；而是它走的是FU-A 分包打包还是单包打包； 1387字节走fu-A ,如果把你说的MTU调小，也会走FU分包打包【有start 0x62 0x01 0x81,有end 0x41】 我想说的是你上一个版本走FU的都是有start有end的，不会是单包FU-A；

有道理，如果是这种情况，就会导致 第一个包就是fu-a的结束包，这样改应该就没有问题了

```
diff --git a/src/Extension/H265Rtp.cpp b/src/Extension/H265Rtp.cpp
index 246b3ea..23bbb10 100644
--- a/src/Extension/H265Rtp.cpp
+++ b/src/Extension/H265Rtp.cpp
@@ -302,7 +302,7 @@ void H265RtpEncoder::packRtpFu(const char *ptr, size_t len, uint64_t pts, bool i
 }
 
 void H265RtpEncoder::packRtp(const char *ptr, size_t len, uint64_t pts, bool is_mark, bool gop_pos){
-    if (len + 3 <= getMaxSize()) {
+    if (len <= getMaxSize()) {
         //signal-nalu 
         RtpCodec::inputRtp(makeRtp(getTrackType(), ptr, len, is_mark, pts), gop_pos);
     } else {
```

**Comment by xiongguangjie** [comment]
用最新的，应该可以修复，再观察观察吧
