### ISSUE TITLE
调用addStreamProxy接口想被局域网内的其他机器获取到视频流，应该咋配置参数

### ISSUE THREAD

**Issue by wangxiaoer3924** [ZLMediaKit/ZLMediaKit#2426]
当我使用ffmpeg命令行推流时，比如 ffmpeg -re -i rtsp://admin:dixin_Admin123@192.168.96.245/Stream1 -codec copy -f flv rtmp://0.0.0.0/live/test
这样局域网内的电脑通过流媒体部署环境的IP是可以访到这个视频流的，但是我调用addStreamProxy拉转推代理的时候，就不行了，我不知道该如何配置才能达到让局域网内的其他设备都能访问到这个视频流

**Comment by xia-chu** [comment]
请调用addStreamPusherProxy接口

**Comment by wangxiaoer3924** [comment]
嗯嗯 已经知道如何使用了  不好意思
