### ISSUE TITLE
Frames decoded from player_opencv.c cannot be displayed on screen.

### ISSUE THREAD

**Issue by kimcheolhee80** [ZLMediaKit/ZLMediaKit#2427]
I added the following code to the on_frame_decode() function, but the decoded frame cannot be displayed on the screen. someone please help

There is no problem with opencv related dll files.

```c
void API_CALL on_frame_decode(void *user_data, mk_frame_pix frame) 
{
    Context *ctx = (Context *)user_data;
    int w = mk_get_av_frame_width(mk_frame_pix_get_av_frame(frame));
    int h = mk_get_av_frame_height(mk_frame_pix_get_av_frame(frame));

#if 0
    uint8_t *bgr24 = (uint8_t *)malloc(w * h * 3);
    mk_swscale_input_frame(ctx->swscale, frame, bgr24);
      
    free(bgr24);

#else

    cv::Mat mat = cv::Mat(720, 1280, CV_8UC3, cv::Scalar(0, 0, 0));

    mk_swscale_input_frame(ctx->swscale, frame, (uint8_t *)mat.data);

    cv::imshow("TestShow3", mat);

#endif

    log_trace("decode frame output, pts:%d, w:%d, h:%d", mk_get_av_frame_dts(mk_frame_pix_get_av_frame(frame)), w, h);
}
```

**Comment by xia-chu** [comment]
You need call `mk_swscale_input_frame` to convert `yuv420p` to "bgr".

**Comment by kimcheolhee80** [comment]
Looking at the source code above, the mk_swscale_input_frame() function has already been called.
The resolution of the connected IP camera is 1280x720.

* And where is the Star?

**Comment by xia-chu** [comment]
on_frame_decode will be called in backgroud thread(not main thread), can it work?

**Comment by xia-chu** [comment]
You can save `bgr24` image to file, and play it by ffmpeg.

**Comment by xia-chu** [comment]
Usually, ui drawing is only allowed to occur on the main thread。
Yes, you have already stared zlmediakit.
