### ISSUE TITLE
支持JT1078的端口是多少啊，文档中没有详细写，在智慧星球看到是新版支持了1078协议的，麻烦解答一下，谢谢大佬

### ISSUE THREAD

**Issue by lcx9325** [ZLMediaKit/ZLMediaKit#2430]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by mrluoqiang** [comment]
> 此功能目前只开放给知识星球用户

进知识星球能 解决 1078协议rtp视频流  转 rtsp流嘛

**Comment by xia-chu** [comment]
> > 此功能目前只开放给知识星球用户
> 
> 进知识星球能 解决 1078协议rtp视频流 转 rtsp流嘛

可以

**Comment by Niu1234561221** [comment]
> > > 此功能目前只开放给知识星球用户
> > 
> > 
> > 进知识星球能 解决 1078协议rtp视频流 转 rtsp流嘛
> 
> 可以
你好，请问进知识星球之后还会有后续的收费嘛。我也需要支持1078协议。

**Comment by xia-chu** [comment]
> 你好，请问进知识星球之后还会有后续的收费嘛。我也需要支持1078协议。

加入星球后免费获取1078分支代码

**Comment by qiuchao323** [comment]
有多大的延迟呢？
