### ISSUE TITLE
mk_media_input_aac 最后一个参数adts可以为空，但是却做了判断，导致设置为NULL会崩溃

### ISSUE THREAD

**Issue by xinsuinizhuan** [ZLMediaKit/ZLMediaKit#2432]
![图片](https://user-images.githubusercontent.com/40679769/235289961-bc2aef33-82eb-4c90-9bcf-42acaf622031.png)
但是，这里却做了判断，导致设置为NULL，则直接崩溃
![图片](https://user-images.githubusercontent.com/40679769/235289986-513276ed-5901-4464-b2c8-9882f00a5d32.png)

推裸流的时候，最后两个参数都是未知的，所以会设置为0和NULL，但是设置为NULL时，直接判断崩溃了

**Comment by xia-chu** [comment]
这个是个小bug 可以直接提pr来修复这个问题 或者等周末我们修复下
