### ISSUE TITLE
[技术咨询] 点播 http-mp4 转 rtsp

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2434]
**咨询的功能模块**
- 点播 http-mp4 转 rtsp

**咨询的具体内容和问题**
- 项目中需要实现一个媒体网关.
1.客户端通过rtsp向网关请求音视频数据。
2.媒体网关需要主动通过http-mp4从网络上拉流(点播)，然后吧音视频数据发送给客户端。
3.网关需要实现 http-mp4(点播) 的 seek功能.  客户端通过自定义协议向网关请求seek播放。  
 咨询相关接口函数调用。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
zlm目前不支持http-mp4拉流， addStreamProxy接口不支持该种类型的url

**Comment by xia-chu** [comment]
你代码没看出什么问题 但是如果h264_media_server.c不崩溃 但是你代码崩溃 那么大概率是你代码问题

**Comment by HalcyonHuang** [comment]
已经通过ffmpeg来实现http-mp4的拉流和拖动功能了，并且在内存里面吧音视频数据传递给zlmediakit来实现http-mp4点播转rtsp直播，现在需要实现rtsp的拖动转http-mp4拖动，请问应用层怎么获取zlmedakit的rtsp的拖动报文消息。
