### ISSUE TITLE
[BUG] BUG现象描述(必填) Stream slow down after run longtime

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#2436]
### 现象描述

I am using addStreamProxy to add rtsp source of IP camera to MediaServer.
After 3-4 days, some stream slow down. If I remove this stream from MediaServer and add again, it works normaly.

### 如何复现?
This problem seems to only happen with some cameras, not all. But i am seeing "[MediaServer.exe] [33336-event poller 0] H264Rtp.cpp:54 inputRtp | start drop h264 gop, last seq:36425, rtp:" in log file.

### 相关日志或截图

[2023-05-05_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/11405049/2023-05-05_00.log)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

default config, dump by MediaServer

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

Windows 11, Intel Core i9 9900X

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:
ZLMediaKit(git hash:ffed4b3/2023-05-03T21:46:25+08:00,branch:master,build time:2023-05-05T16:22:59)

**Comment by pubpy2015** [comment]
I really don't know why. But very strange, at the time stream from MediaServer slow down, rtsp source from camera still play nornaly with VLC, and if I remove it from MediaServer and add it again, stream from MediaServer will also be normal again.
Do you think this camera need a special Keep Alive signal ?

**Comment by xia-chu** [comment]
> Do you think this camera need a special Keep Alive signal ?

I do not think so, zlmediakit will send `rtcp reciver report` and `GET_PARAMETER or OPTIONS` to camera。

**Comment by xia-chu** [comment]
This is just a bug of camera.

**Comment by pubpy2015** [comment]
Thanks,

Can I disable these code for continuos streaming ?
![ảnh](https://user-images.githubusercontent.com/59004953/236593816-207082cf-6ed3-4f00-a52c-ad4c7063b956.png)

**Comment by xia-chu** [comment]
No, i do not suggest so ，this will cause screen flicker during packet loss.
Your problem is packet loss, not caused by this logic

**Comment by pubpy2015** [comment]
Because this problem only occurs when running for a long time. Very difficult to detect.

- Can I automatic restart stream after number of _gop_dropped ?
- The system can have multiple cameras. In the log file, can i know which camera has _gop_dropped ?
![ảnh](https://user-images.githubusercontent.com/59004953/236600879-46075b3d-a85f-4d76-8d16-7153fb0194c9.png)

**Comment by pubpy2015** [comment]
When stream slow down, video like this:

https://user-images.githubusercontent.com/59004953/236601834-d51f168b-d025-481b-bb18-210b3c468273.mp4

**Comment by pubpy2015** [comment]
Hi,

I'm still wondering about this problem.
At this time, the manufacturer has no new firmware, so i want find a quick way to reduce dropped frame.

I am trying disable drop frame like this but the problem still exists. Do I have to edit anywhere else?
![ảnh](https://user-images.githubusercontent.com/59004953/236977732-7c872054-bcea-4bc8-8c5d-064405ba46cb.png)

**Comment by xia-chu** [comment]
Drop gop when dropped rtp packet is a good logic，you can `tcpdump` or `wireshark` to catch this rtp network transport packet to determine whether  rtp have already dropped when camera sent it.

**Comment by pubpy2015** [comment]
I am using wireshark to capture this:
Here is log on MediaServer:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/a83ad346-2039-4f9c-8469-843f41cd940f)
Here is on wireshark
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/e4d5dec2-0626-4bc1-9d23-f5e0a5034a66)

Attached file is wireshark log, ip address of camera is 192.168.20.10

[drop_grop.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11431947/drop_grop.zip)

**Comment by pubpy2015** [comment]
After camera send MarkSender Report, the Seq increase from 54446 to 5640
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/2af84772-0e19-4055-8728-55e62f219857)

And other, seq increase from 39194 to 39374:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/139caad4-f3b6-4c10-8cd4-e3faab0838d5)

**Comment by pubpy2015** [comment]
Wireshark capture when using VLC:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/039939ac-c708-497d-82a0-b7484cd988d3)
[vlc_cap.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11437434/vlc_cap.zip)

**Comment by xia-chu** [comment]
You see here, seq inexplicably jumps and grows：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/c0c84119-08b2-4227-aa0e-d8bd41342395)

**Comment by xia-chu** [comment]
I think this is just a bug of camera

**Comment by pubpy2015** [comment]
Did you find any difference between VLC and MediaServer's logs ?

I have this problem (as video bellow) for camera Bosch, Dahua, Uniview,... both internet and local network.

> When stream slow down, video like this:
> 20230506_121652.mp4

**Comment by xia-chu** [comment]
> Did you find any difference between VLC and MediaServer's logs ?
> I have this problem (as video bellow) for camera Bosch, Dahua, Uniview,... both internet and local network.

And vlc played ok without any issues?

**Comment by xia-chu** [comment]
VLC played via `udp` transport and `MediaServer` played via `tcp` transport.

**Comment by xia-chu** [comment]
Your video showed that, the video frame had not be dropped, just played unsmooth, this is usually a timestamp issue

**Comment by pubpy2015** [comment]
> > Did you find any difference between VLC and MediaServer's logs ?
> > I have this problem (as video bellow) for camera Bosch, Dahua, Uniview,... both internet and local network.
> 
> And vlc played ok without any issues?

Yes, at the time stream slow down, vlc works fine.

can you tell me where is in code ?

**Comment by xia-chu** [comment]
ZLMediaKit will recv `sender report rtcp` from camera,  and convert  `rtp stamp` to `ntp stamp`.
What protocol do you played from zlmediakit after it proxy a rtsp stream?

**Comment by pubpy2015** [comment]
I am using RTSP protocol: rtsp://127.0.0.1:8554/proxy/cam8

**Comment by xia-chu** [comment]
I'm confused right now. You seem to have two questions
One is the problem of camera `rtp seq` jumping
One is the `ntp timestamp` problem

**Comment by xia-chu** [comment]
We need to first solve the problem of `rtp seq jump growth`

**Comment by pubpy2015** [comment]
rtp seq jumping seem is not the cause because:
- in MediaServer log, "_gop_dropped" not much.
- when i am disable "_gop_dropped", the problem still exists.
- i remember that, I tried changing to udp transport before but the problem still exists.

I watched the video again, maybe your opinion about ntp timestamp is more correct.

**Comment by pubpy2015** [comment]
Other info:
System with 72 streams, when normal: memory usage ~ 200 MB, when stream slow down, memory increase to ~ 4.5 GB

**Comment by xia-chu** [comment]
>  System with 72 streams, when normal: memory usage ~ 200 MB, when stream slow down, memory increase to ~ 4.5 GB

Please use `getStatistic http api` to get more information

**Comment by pubpy2015** [comment]
System with 64 streams:
when startup (normal): 120 MB
{
	"code" : 0,
	"data" : 
	{
		"Buffer" : 16414,
		"BufferLikeString" : 2499,
		"BufferList" : 1,
		"BufferRaw" : 8645,
		"Frame" : 3010,
		"FrameImp" : 1564,
		"MediaSource" : 385,
		"MultiMediaSourceMuxer" : 64,
		"RtmpPacket" : 838,
		"RtpPacket" : 7201,
		"Socket" : 237,
		"TcpClient" : 64,
		"TcpServer" : 122,
		"TcpSession" : 33,
		"UdpServer" : 21,
		"UdpSession" : 0
	}
}

When some streams slow down: 2.2 GB
{
	"code" : 0,
	"data" : 
	{
		"Buffer" : 15298,
		"BufferLikeString" : 2179,
		"BufferList" : 0,
		"BufferRaw" : 8539,
		"Frame" : 2586,
		"FrameImp" : 1350,
		"MediaSource" : 385,
		"MultiMediaSourceMuxer" : 64,
		"RtmpPacket" : 750,
		"RtpPacket" : 7076,
		"Socket" : 219,
		"TcpClient" : 64,
		"TcpServer" : 122,
		"TcpSession" : 15,
		"UdpServer" : 21,
		"UdpSession" : 0
	}
}

**Comment by pubpy2015** [comment]
Sorry i dont know about jemalloc.
I am trying to enable it in Cmake but get the error message
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/6f3f393a-3936-48f1-9fea-c3372f841448)

**Comment by xia-chu** [comment]
You are on windows, this is not my familiar field

**Comment by pubpy2015** [comment]
Follow the instruction: https://github.com/jemalloc/jemalloc/blob/dev/INSTALL.md
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/0a47ec9a-5ee7-4ad0-b7ca-3340664656d2)

Now i can build jemalloc on windows, can i manual add it to ZLmediaKit ?

**Comment by xia-chu** [comment]
I suggest you test  it on the linux system,  there are many testing tools that I am familiar with on it

**Comment by pubpy2015** [comment]
Thanks,
I still want to build the system on windows (I really don't know much about linux) and this is small system with ~36 cameras (36 x 2  = 72 streams) so building on windows will be more convenient.

I will try build jemalloc again and try to edit cmakelists.txt
found a relate here: https://github.com/ZLMediaKit/ZLMediaKit/issues/807

**Comment by pubpy2015** [comment]
Sorry, i can't link jemalloc lib on windows.
I sent you the rtsp url of this type camera in email. When you have free time, please test it.

found new log here:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/828b2d3c-ab09-42c3-b4d3-9c3714a745ed)

**Comment by xia-chu** [comment]
@pubpy2015 Maybe this [issue](https://github.com/ZLMediaKit/ZLToolKit/issues/161) ?

**Comment by pubpy2015** [comment]
I am not sure, but after update [this version](https://github.com/ZLMediaKit/ZLMediaKit/tree/5ca4ed53b2afc5902ca48377cf49a756181911c6) and disable HLS, TS, fMP4 for all streams, RAM didn't go huge same as before (still doubles from startup and stable there). Now MediaServer can work normaly.
Thank you for your support.

**Comment by xia-chu** [comment]
fmp4 may cause memory increase when stream alive long time

**Comment by pubpy2015** [comment]
It seems that memory overflow is still a big problem for me. I will try your latest code again.

**Comment by pubpy2015** [comment]
Hi,

I tested the latest version, after a period of time, packet loss occurred and MediaServer's RAM memory increased continuously, causing many video streams to lose connection. Turn off MediaServer and turn it back on and the system will work normally again.

Can you take a look at this drop gop mechanism to see if a memory leak error might occur there?

**Comment by pubpy2015** [comment]
This problem occurs when the system has many cameras and maybe due to insufficient bandwidth, packet loss (or connection loss) occurs. When MediaServer's RAM increases to 2GB, almost all video streams lose connection.

**Comment by pubpy2015** [comment]
Hi,

I pull the rtsp stream from the camera with transport tcp.
I will try now

**Comment by pubpy2015** [comment]
I am using an application in C# on windows to connect to the rtsp stream of MediaServer

**Comment by pubpy2015** [comment]
But most of the time, no client connected at all. I have disabled hls, rtmp, fmp4, ts and set on demain for these servers. Only prioritize rtsp streaming.
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/3d1d2064-8326-4f26-a3e1-cea1b00977f6)

After setting the rtp_proxy.gop_cache parameter to 0 in config.ini, MediaServer uses less RAM and speeds up a bit slower.
However, RAM still increases and the loss of connection to the video stream still occurs. Meanwhile VLC can still play normally (I have set transport to RTP over RTSP (TCP))


![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/8dcbff39-354d-4b9b-bd67-cc5b5990e70e)

**Comment by pubpy2015** [comment]
Hi,

Because I set log level = error, there is not much information in the log.
Sometimes I see logs with lines like this:
RtspPlayer.cpp:693 onPlayResult_l | 255 Unknown system error -10060
RtpReceiver.h:167 output | packet dropped: 38272 -> 38272, latest seq: 38529, jitter buffer size: 220, jitter buffer ms: 172
RtpReceiver.h:167 output | packet dropped: 19440 -> 19440, latest seq: 19697, jitter buffer size: 233, jitter buffer ms: 110
RtspPlayer.cpp:693 onPlayResult_l | 255 Assertion failed: (next_line && next_line > ptr), function mediakit::Parser::parse
RtspPlayer.cpp:693 onPlayResult_l | 255 Assertion failed: (next_blank && next_blank < next_line), function mediakit::Parser::parse

If you need the full log, I will send it back later
Here is the response  of /index/api/getStatistic:
{
	"code" : 0,
	"data" : 
	{
		"Buffer" : 47213,
		"BufferLikeString" : 1396,
		"BufferList" : 0,
		"BufferRaw" : 44941,
		"Frame" : 876,
		"FrameImp" : 672,
		"MediaSource" : 631,
		"MultiMediaSourceMuxer" : 312,
		"RtmpPacket" : 0,
		"RtpPacket" : 44901,
		"Socket" : 1128,
		"TcpClient" : 631,
		"TcpServer" : 321,
		"TcpSession" : 93,
		"UdpServer" : 81,
		"UdpSession" : 0
	}
}

**Comment by pubpy2015** [comment]
I send you the log file.
I set each recording file to be 10 minutes instead of 60 minutes as default. After each file is created, I see that the RAM memory has decreased a bit.
at the startup, MediaServer uses 660 MB of RAM. The end is 2.5 GB
[2023-12-15_00.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/13681524/2023-12-15_00.zip)

**Comment by pubpy2015** [comment]
I use the getMediaList API every 30 seconds to check the video stream parameters (to see if the camera lost connection, is recording, or stopped recording). Does this affect performance and increase RAM memory?

**Comment by pubpy2015** [comment]
I tried another user's Windows build: https://github.com/AvenSun/ZLMediaKit/releases/tag/windows-20231212
However, we still encounter the phenomenon of RAM increasing after a short period of time, even when we don't see log drop frames or rtsp timeouts occurring.
The camera I use is Uniview.

**Comment by pubpy2015** [comment]
I send you the responses in the attached file.

getStatistic.json and getThreadsLoad.json are responses at startup.

[getStatistic.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702361/getStatistic.json)
[getStatistic2.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702362/getStatistic2.json)
[getStatistic3.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702363/getStatistic3.json)
[getStatistic4.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702364/getStatistic4.json)
[getThreadsLoad.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702365/getThreadsLoad.json)
[getThreadsLoad2.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702366/getThreadsLoad2.json)
[getThreadsLoad3.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702367/getThreadsLoad3.json)
[getThreadsLoad4.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13702368/getThreadsLoad4.json)

**Comment by pubpy2015** [comment]
> Please set `rtp_proxy.gop_cache` to `0` in `config.ini` file.

![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/83c75f93-f6a8-44a9-a1e6-e8a681c9d1b4)

I am only enable rtsp
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/540f04cb-d5e0-4242-85eb-875211709028)

**Comment by pubpy2015** [comment]
Now, when MediaServer using ~ 2.3 GB RAM, It takes a long time to get a response from getMediaList and takes even longer (sometimes no response) from getThreadsLoad
[getStatistic5.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13704536/getStatistic5.json)
[getThreadsLoad5.json](https://github.com/ZLMediaKit/ZLMediaKit/files/13704537/getThreadsLoad5.json)

**Comment by pubpy2015** [comment]
How to pause it ? Did you tell me to debug on Visual Studio?

**Comment by pubpy2015** [comment]
Currently I can't try it because the computer is far away and there is no internet. Can you tell me another way to debug?
When running, MediaServer only usage ~10% CPU.
Is that error due to MediaServer not running on all CPU cores?

**Comment by pubpy2015** [comment]
Maybe the problem is still in timestamp. 
Previously, all cameras had the wrong date and time. The problem of increasing RAM memory and dropping frames occurs continuously, in a short time after startup. 
Even though I have set rtp_proxy.gop_cache to 0, disabe all streams except rtsp, put on demain or disable servers and try to set modify_stamp=0,1,2 the problem still occurs. After a short period of time, streams are almost removed from MediaServer.

Then I set the NTP server for the cameras (The NTP server is the PC on which MediaServer is installed), restarted the cameras, and fortunately, the MediaServer worked fine. Up to now it has been running for 10 hours.

**Comment by pubpy2015** [comment]
Thanks,

I have set those parameters. Now that MediaServer has been running longer than before, RAM still increases during recording but will be released when the mp4 file is created. I'll follow up in a few days.

**Comment by pubpy2015** [comment]
MediaServer is still running continuously until now. RAM increases during recording and is released when the mp4 file is created. However, not all of the RAM used for the mp4 index is release. => It is possible that MediaServer will fail after 1-2 weeks, when RAM increases to ~ 2GB. I will continue to follow.

**Comment by pubpy2015** [comment]
I don't have the conditions to test again with that system. But later I got a few similar cameras. If the time is not synchronized between the PC where MediaServer is installed and the camera, the problem of increasing RAM will occur. I close this issue here.

**Comment by xia-chu** [comment]
I think unsynchronized timestamps shouldn't cause memory increase in zlmediakit. This might be more of a memory fragmentation issue, which could potentially be addressed by linking with the jemalloc library to ensure timely memory release.
