### ISSUE TITLE
[技术咨询] 如果线程按照自己输入的内核序号进行绑定是否影响EPoller工作

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2437]
**咨询的功能模块**
我看您新加了是否设置线程与内核序号亲和性绑定；
我现在因为arm服务器内核有大小，我不想从核0开始绑定EPoller；
![图片](https://user-images.githubusercontent.com/18655816/236432319-706b27ba-20d8-4c51-bbe2-2e763008d86b.png)

我们尝试关闭CPU 亲和性绑定，使用taskset -c 1,2,3 这样，到那时发现我设置的3个线程，三个event Poll都运行在1号核上了，并没有均匀的运行在 1，2，3 上，top -p  查看的（P = Last Used Cpu (SMP)   H查看到eventpoller 用的内核号）；

然后我写了个指定线程绑定核号的功能，让他线程1，2，3，4 从内核1开始绑定，不从0开始。稍稍修改了您的设置亲和性的那块代码：
如：设置4个线程，使用的核分别是 1，2，3，5；然后我接收一个外边传过来的数组参数1，2，3，5.设置亲和性那个遍历的位置：

```c++

size_t TaskExecutorGetterImp::addPoller(const string &name, size_t size, int priority, bool register_thread, bool enable_cpu_affinity) {
    auto cpus = thread::hardware_concurrency();
    bool extsetAff = _setCoreAff;//外部设置CPU亲和性序号
    vector<int> v1; // 声明v1
    v1.assign(_vecCoreAff.begin(), _vecCoreAff.end()); // 我外边传过来的数组，记录核号使用，如4线程，传递1，2，3，5，4，6，7，0，让他从1号核还是创建Epoller

    size = size > 0 ? size : cpus;
    for (size_t i = 0; i < size; ++i) {
        auto full_name = name + " " + to_string(i);
        EventPoller::Ptr poller(new EventPoller(full_name, (ThreadPool::Priority) priority));
        poller->runLoop(false, register_thread);
        poller->async([i, cpus, full_name, enable_cpu_affinity, extsetAff,v1]() {
            setThreadName(full_name.data());
            if (enable_cpu_affinity) {
                if (extsetAff)
                {
                    setThreadAffinity(v1[i % cpus]);
                } else {
                    setThreadAffinity(i % cpus);
                }
                
            }
        });
        _threads.emplace_back(std::move(poller));
    }
    return size;
}

```

**咨询的具体内容和问题**
- 我不知道这样是否会影响整个线程运行逻辑；希望能给予方案上的指正

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
应该改成`setThreadAffinity(v1[i % v1.size()]);` 否则会越界啊
另外`vector<int> v1;`可以改成set<int>, 这样方式重复设置cpu序号

**Comment by xia-chu** [comment]
cpu亲和性设置个人认为没那么重要。

**Comment by xuandu** [comment]
感谢大佬看的好仔细；就是setThreadAffinity(v1[i % v1.size()]);您这样；
因为需求如此，他们就想用那几个大核，我怕我这样乱改会影响创建线程；所以还是问下您比较保险
感谢~~~~~~~~

**Comment by xiongguangjie** [comment]
这个没用吧（除了addffmpeg 有用），zlm分配链接是根据poller 的负载来分配的，是根据最小的来分配，你这样最好设置线程数，然后才设置亲和性才有用吧

**Comment by xuandu** [comment]
> 这个没用吧（除了addffmpeg 有用），zlm分配链接是根据poller 的负载来分配的，是根据最小的来分配，你这样最好设置线程数，然后才设置亲和性才有用吧

嗯嗯，是想要调设置两个参数的，一个是线程数，一个是使用的核号的数组，然后创建线程的时候就在这几个CPU核号上设置亲和性；
如：10个线程；不过一般就3-4个线程；然后设置使用1，2，3，5号内核，
thread1：1-cpu
thread2:  2-cpu
thread3: 3-cpu
th4: 5-cpu
th5:1-cpu
th6:2-cpu
th7:3-cpu
th8:5-cpu
th9:1-cpu
th10:2-cpu
.......

**Comment by xuandu** [comment]
> cpu亲和性设置个人认为没那么重要。

来问个问题；因为我是在add"eventpoller"的时候设置的使用核号，那workpollerpoll应该是不受我这个代码的影响的；
跑起来也没问题，然后我看所有的eventpoller也有运行在我设置的核号上，满足了我的需求；但是我发现了一个小问题就是top -p 查看上次运行的核号的时候下边没有workpoller运行的在哪个核的打印了，可是整个服务运行又没啥问题；

然后我在win上运行一个拉流播放，我看打印也没有创建workpollerpoll;

所以想问下什么时候会创建workpoller；我一直理解成evenpoller是处理socket的，workpoller是处理内部逻辑的，但是我感觉我应该是理解错了；

**Comment by xia-chu** [comment]
workpoller目前仅处理的逻辑有：
- 1、dns异步解析
- 2、mp4文件rtsp/rtmp/flv点播
- 3、mp4 close
