### ISSUE TITLE
[技术咨询] 除了手动更新配置文件，还有能进行对mediaServerId进行更改的方法吗？

### ISSUE THREAD

**Issue by tms2003** [ZLMediaKit/ZLMediaKit#2440]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
除了手动更新配置文件，还有能进行对mediaServerId进行更改的方法吗？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
比如，我们使用docker部署zlmediakit，每次需要手动去容器里更新一次mediaserverid。请问还有其它的方式吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
wiki中有写setServerConfig接口

**Comment by tms2003** [comment]
@xia-chu  谢谢！文档中开始是没有！

**Comment by xia-chu** [comment]
wiki中早就有这个接口 懒就懒 别找借口





------------------ 原始邮件 ------------------
发件人: tms ***@***.***&gt;
发送时间: 2023年5月6日 20:47
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] 除了手动更新配置文件，还有能进行对mediaServerId进行更改的方法吗？ (Issue #2440)





 
@xia-chu  谢谢！文档中开始是没有！

**Comment by tms2003** [comment]
@xia-chu 不好意思啊，没有表达清楚。我是指文档中的内容getServerConfig响应的结果为：
```
{
   "code" : 0,
   "data" : [
      {
         "api.apiDebug" : "1",
         "api.secret" : "035c73f7-bb6b-4889-a715-d9eb2d1925cc",
         "ffmpeg.bin" : "/usr/local/bin/ffmpeg",
         "ffmpeg.cmd" : "%s -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
         "ffmpeg.log" : "/Users/xzl/git/ZLMediaKit/cmake-build-debug/bin/ffmpeg/ffmpeg.log",
         "general.enableVhost" : "1",
         "general.flowThreshold" : "1024",
         "general.maxStreamWaitMS" : "5000",
         "general.streamNoneReaderDelayMS" : "5000",
         "hls.fileBufSize" : "65536",
         "hls.filePath" : "/Users/xzl/git/ZLMediaKit/cmake-build-debug/bin/httpRoot",
         "hls.segDur" : "3",
         "hls.segNum" : "3",
         "hook.access_file_except_hls" : "1",
```
其中不包括mediaserverid,所以以为没有。不是指没有那个Api.:-)

**Comment by xia-chu** [comment]
getServerConfig会返回所有配置项，包括mediaserverid:
<img width="1044" alt="图片" src="https://user-images.githubusercontent.com/11495632/236978740-c369def3-d883-4e21-8e59-67c720bf31b9.png">
