### ISSUE TITLE
[BUG] Windows Server 2022 Datacenter 启动MediaServer.exe，报：应用程序无法正常启动0xc00007b

### ISSUE THREAD

**Issue by ice-ko** [ZLMediaKit/ZLMediaKit#2441]
### 现象描述

在服务器上部署运行，启动报错：应用程序无法正常启动0xc00007b
### 如何复现?

点击直接运行 MediaServer.exe 

### 相关日志或截图

未生成日志文件，运行截图：
![QQ截图20230506172018](https://user-images.githubusercontent.com/20471045/236615551-3922af32-852d-4b31-ab3d-5eee246cbf1c.png)

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:   Windows Server 2022 Datacenter
* **硬件信息**:  Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz   2.50 GHz
* **其他需要补充的信息**:

**Comment by wasphin** [comment]
需要确认依赖库释放完整。

Windows 有类似 depend 的检查工具。
