### ISSUE TITLE
[技术咨询] ZLM做UDP组播中转服务方案咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2443]
**咨询的功能模块**
想咨询下用ZLM做一个UDP中转服务器的方案。如图，上边的部分是原始的样子，UDP：//输出到组播地址
然后我们想在中间做点操作，就是图中的下半部分
![UDP中转流程](https://user-images.githubusercontent.com/18655816/236728057-b857b846-949d-4eb8-b055-c3328640af15.jpg)

**咨询的具体内容和问题**
（1）由于ZLM并不支持输出到组播地址，所以我想既然我都用FFmpeg拉源了（粉色部分），是不是也就可以ZLM输出的时候在用ffmpeg转一道（紫色部分）；我简单测试了一下您代码中的addffmpegsource是支持拉本地流，输出UDP；
我这样试了一下，看wireshark抓包是有TS传向组播地址的：
http://127.0.0.1:580/index/api/addFFmpegSource?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&src_url=rtsp://127.0.0.1/live/test2&dst_url=udp://239.255.255.250:54546 &timeout_ms=10000&enable_hls=0&enable_mp4=0

但是，我现在看着这个逻辑就感觉很笨重；要经过两次FFmpeg；

（2）因为我不确定二压输出是不是一定RTP（TS），所以如果我想简单开发一个类似startsendrtp的接口来专门发UDP：// TS,是不是也行？而且如果我就限制二压输出的就是RTP TS，那我就有现成的TS用了；
        但是基于此我要修改或者添加哪些部分的代码呢？

您觉得哪样好一点，因为我现在只是测试了我的方案1，但是总感觉好笨重；
并不想修改客户的原始组播逻辑；我们自己的逻辑接入就是我图中圆圈圈起来的；

或者是否有更好的想法指导？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
方案一我理解了 我觉得是有可行性的 不过链路太长了 容易出错 而且控制逻辑不好些 另外性能也一般。
方案二我没理解 但是其实我觉得 FFmpeg已经支持组播流输入--> 视频处理 --> 组播流输出，所以zlmediakit完全没存在的意义啊。

**Comment by xuandu** [comment]
说的有道理；FFmpeg其实就把我想做的UDP功能给做了；
我能理解的产品们的想法，估计是想（1）兼容原始IPC拉流逻辑，全部走ZLM；避免过多应用层逻辑改动；（2）ZLM负载均衡方面很好；所以处处有ZLm的身影

我自己再好好想想，等我想明白在来问，感谢指点

![未命名绘图 drawio](https://user-images.githubusercontent.com/18655816/237014337-b6157504-17c2-4d23-ab2e-65b74313cdd1.png)

**Comment by xia-chu** [comment]
主要是你那个方案太复杂 链路太多 出问题都没法定位
