### ISSUE TITLE
[技术咨询] GB28181 RTP推流丢包问题

### ISSUE THREAD

**Issue by yand9807** [ZLMediaKit/ZLMediaKit#2446]
**咨询的功能模块**
- GB28181 RTP推流提示丢包无法拉流

**咨询的具体内容和问题**
- 使用GB28181协议通过RTP进行推流时是指报rtp丢包，日志如下：
![image](https://user-images.githubusercontent.com/53848372/236817446-ca036408-2c21-4106-8603-207f9fd7bf6e.png)
- 使用rtp_poxy.dumpDir导出视频数据用播放器打开花屏但是能够播放
- 参考了[2348](https://github.com/ZLMediaKit/ZLMediaKit/issues/2348)等issue中的方法都没有用
- 下载下来的视频文件播放时用播放器查看属性显示是H264，但是看log里面写的是H265？
- `[MediaServer] [7-event poller 14] Decoder.cpp:240 onTrack | got track: H265`

**Comment by yand9807** [comment]
还有一个日志信息，我记得rtp流注册认证时hook未返回认证通过的时候会出现这个，但是这里我把hook都关掉了，应该是不需要认证了
![image](https://user-images.githubusercontent.com/53848372/236832767-ff6bf514-636a-4a1e-aaf4-28ee0a981bbf.png)

**Comment by xia-chu** [comment]
- 1、关于H264识别为H265的问题 可以把dump文件上传上来 我们分析下
- 2、丢包问题，可能是磁盘io导致网络接收不及时，请适当降低zlmediakit负载同时关闭mp4/hls录制等功能。
- 3、如果还是丢包，可以用tcpdump抓包看看是否真的丢包了。

**Comment by yand9807** [comment]
这是dump文件58s左右
[dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11427074/dump.zip)
mp4/hls录制也都关闭了，磁盘io占用并不高，这个流媒体只处理了这一路流，负载不高
目前通过抓包命令看并没有丢包，用tcpdump抓出来的数据保存成.rtp文件也是能播的，跟dump中的文件基本一致

**Comment by xia-chu** [comment]
tcpdump抓出来的数据播放不花屏？

**Comment by yand9807** [comment]
> tcpdump抓出来的数据播放不花屏？

也花屏

**Comment by xia-chu** [comment]
你就是说明真的丢包了

**Comment by x-x-p** [comment]
不知道和我遇到问题是否一样， 我简单描述下
使用使用海康IPC国标接入, 流传输模式为 TCP被动或TCP主动模式， 在嵌入式arm64系统下出现丢包现象， 但 UDP没问题， 而且在x86的ubuntu下也没问题
dump出来保存的 .rtp 数据中也发现seq有缺失。
调试发现在RtpReceiver.h 的PacketSortor::needForceFlush 中, distance(seq) 距离过长导致。

**Comment by xia-chu** [comment]
> 不知道和我遇到问题是否一样， 我简单描述下 使用使用海康IPC国标接入, 流传输模式为 TCP被动或TCP主动模式， 在嵌入式arm64系统下出现丢包现象， 但 UDP没问题， 而且在x86的ubuntu下也没问题 dump出来保存的 .rtp 数据中也发现seq有缺失。 调试发现在RtpReceiver.h 的PacketSortor::needForceFlush 中, distance(seq) 距离过长导致。

那就是丢包了 而且丢了很多

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by x-x-p** [comment]
> > 不知道和我遇到问题是否一样， 我简单描述下 使用使用海康IPC国标接入, 流传输模式为 TCP被动或TCP主动模式， 在嵌入式arm64系统下出现丢包现象， 但 UDP没问题， 而且在x86的ubuntu下也没问题 dump出来保存的 .rtp 数据中也发现seq有缺失。 调试发现在RtpReceiver.h 的PacketSortor::needForceFlush 中, distance(seq) 距离过长导致。
> 
> 那就是丢包了 而且丢了很多

是的，丢包很多， 当时我查找了很多关于系统层网络问题， 也自己模拟tcp数据接收，还是没有解决，后来才仔细看代码想看看是不是分包处理调了，是不是在不同架构下某些处理不一致导致，于是就把原始数据包dump下来，然后自己写工具对比看丢失的是那个包，对比发现只有长度为256的包才有丢，才分包处发现isEhome函数，打印日志才发现问题出现isEhome函数了。
可以查看这个pr #2490

**Comment by xia-chu** [comment]
> 包很多， 当时我查找了很多关于系统层网络问题， 也自己模拟tcp数据接收，还是没有解决，后来才仔细看代码想看看是不是分包处理调了，是不是在不同架构下某些处理不一致导致，于是就把原始数据包dump下来，然后自己写工具对比看丢失的是那个包，对比发现只有长度为256的包才有丢，才分包处发现isEhome函数，打印日志才发现问题出现isEhome函数了。
> 可以查看这个pr #2490

你的意思是误判为ehome的包了？这么巧合吗？

**Comment by xia-chu** [comment]
嗯 不巧合 确实有这个问题 这个问题也是合并一个pr后导致的 测试不足啊

**Comment by xia-chu** [comment]
这个ehome逻辑判断 应该锁定后 就不能再变更了

**Comment by xia-chu** [comment]
请更新代码试试 问题应该修复了
