### ISSUE TITLE
[技术咨询] mix模块还在吗？有需求要实现两路流合并播放

### ISSUE THREAD

**Issue by bxlx** [ZLMediaKit/ZLMediaKit#2447]
**咨询的功能模块**
- 有需求要实现两路流合并播放，问下mix模块还在吗？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
从来没存在过，怎么还在？？
