### ISSUE TITLE
[技术咨询] 用jessibuca pro播放ZLM拉流代理转发流时遇到时间戳问题

### ISSUE THREAD

**Issue by sj1101** [ZLMediaKit/ZLMediaKit#2450]
**咨询的功能模块**
- 拉流代理转发流的时间戳相关的问题

**咨询的具体内容和问题**
- 前端播放器是jessibuca pro，sip信令是基于wvp最新版本, 在前端通过websocket拉取zlm拉流代理转发的flv码流，每隔40秒左右发现前端播放器jessibuca pro会打印出Timestamp时序异常，zlm后台打印的log没有看出什么问题。想咨询一下，这个问题是否受zlm拉流代理转发的码流中的ts影响？是否有地方可以打印log对这类问题进行调试？
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/7875688/5b85ed74-8ada-4bcf-ab17-0e4171a70db4)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by sj1101** [comment]
刚又出现了时间戳的另一种异常。
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/7875688/a64ca343-efd2-4f87-9165-676a08d42aae)

**Comment by xia-chu** [comment]
代理的什么类型的流？播放协议是什么？
