### ISSUE TITLE
请求MPEG-TS拉流功能，目前只有HLS拉流正常，很遗憾不能MPEG-TS拉流

### ISSUE THREAD

**Issue by zwfcz** [ZLMediaKit/ZLMediaKit#2457]
请求MPEG-TS拉流功能，目前只有HLS拉流正常，很遗憾不能MPEG-TS拉流。

**Comment by alexliyu7352** [comment]
可以拉取http-ts流的, 请保证url的后缀是.ts

**Comment by zwfcz** [comment]
> 可以拉取http-ts流的, 请保证url的后缀是.ts

问题就是出在网直后缀没有.ts

**Comment by alexliyu7352** [comment]
你可以自己在url中添加一个参数阿, 比如
原始url 
http://xxx.ex.com/12345

你添加一个
http://xxx.ex.com/12345?name=.ts

**Comment by zwfcz** [comment]
> 你可以自己在url中添加一个参数阿, 比如 原始url http://xxx.ex.com/12345
> 
> 你添加一个 http://xxx.ex.com/12345?name=.ts

好的，我试试
