### ISSUE TITLE
[BUG] Mac OS平台交叉编译 iOS 静态库，zltoolkit 中 Socket.h 报错

### ISSUE THREAD

**Issue by cievon** [ZLMediaKit/ZLMediaKit#2459]
### 如何复现?
在 Mac 上交叉编译 iOS player c api

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
编译完iOS平台的工程库，使用xcode build 报错，zltoolkit 中 Socket.h 文件
static void setConnected(int fd) {
#if defined(OS_IPHONE)
        setSocketOfIOS(_fd);
#endif // OS_IPHONE
    }

错误信息：Call to non-static member function without an object argument，静态方法中调用了实例对象方法
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**: 20230511 编译最新代码

**Comment by xia-chu** [comment]
改出点bug了 你直接注销掉 setSocketOfIOS(_fd); 吧 
这个不影响的
