### ISSUE TITLE
[技术咨询] Mapping MediaSource and WebRtcSession

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#2461]
Hello

There is a **_media_info** variable in RtspSession, but how to get streamId in WebRtcSession?

**Comment by xiongguangjie** [comment]
WebRtcSession -> WebRtcTransportImp( sub class is WebRtcPusher or WebRtcPlayer both has _media_info)

**Comment by a-ucontrol** [comment]
> WebRtcSession -> WebRtcTransportImp( sub class is WebRtcPusher or WebRtcPlayer both has _media_info)

Thanks, now _transport and _media_info are private. Is it possible to make these changes in ZLM?

```patch
diff -Naur ZLMediaKit/webrtc/WebRtcPlayer.h ZLMediaKit-m/webrtc/WebRtcPlayer.h
--- ZLMediaKit/webrtc/WebRtcPlayer.h    2023-05-11 15:13:45.000000000 +0300
+++ ZLMediaKit-m/webrtc/WebRtcPlayer.h  2023-05-13 10:02:48.586818854 +0300
@@ -21,6 +21,7 @@
     using Ptr = std::shared_ptr<WebRtcPlayer>;
     ~WebRtcPlayer() override = default;
     static Ptr create(const EventPoller::Ptr &poller, const RtspMediaSource::Ptr &src, const MediaInfo &info, bool preferred_tcp = false);
+    MediaInfo getMediaInfo() { return _media_info; }
 
 protected:
     ///////WebRtcTransportImp override///////
diff -Naur ZLMediaKit/webrtc/WebRtcSession.h ZLMediaKit-m/webrtc/WebRtcSession.h
--- ZLMediaKit/webrtc/WebRtcSession.h   2023-05-11 15:13:45.000000000 +0300
+++ ZLMediaKit-m/webrtc/WebRtcSession.h 2023-05-13 10:00:57.363481109 +0300
@@ -35,6 +35,9 @@
     void onManager() override;
     static EventPoller::Ptr queryPoller(const Buffer::Ptr &buffer);
 
+protected:
+    WebRtcTransportImp::Ptr _transport;
+
 private:
     //// HttpRequestSplitter override ////
     ssize_t onRecvHeader(const char *data, size_t len) override;
@@ -47,7 +50,6 @@
     bool _find_transport = true;
     Ticker _ticker;
     std::weak_ptr<toolkit::TcpServer> _server;
-    WebRtcTransportImp::Ptr _transport;
 };
 
 }// namespace mediakit
```

**Comment by xiongguangjie** [comment]
> > WebRtcSession -> WebRtcTransportImp( sub class is WebRtcPusher or WebRtcPlayer both has _media_info)
> 
> Thanks, now _transport and _media_info are **private**. Is it possible to make these changes in ZLM?
> 
> ```diff
> diff -Naur ZLMediaKit/webrtc/WebRtcPlayer.h ZLMediaKit-m/webrtc/WebRtcPlayer.h
> --- ZLMediaKit/webrtc/WebRtcPlayer.h    2023-05-11 15:13:45.000000000 +0300
> +++ ZLMediaKit-m/webrtc/WebRtcPlayer.h  2023-05-13 10:02:48.586818854 +0300
> @@ -21,6 +21,7 @@
>      using Ptr = std::shared_ptr<WebRtcPlayer>;
>      ~WebRtcPlayer() override = default;
>      static Ptr create(const EventPoller::Ptr &poller, const RtspMediaSource::Ptr &src, const MediaInfo &info, bool preferred_tcp = false);
> +    MediaInfo getMediaInfo() { return _media_info; }
>  
>  protected:
>      ///////WebRtcTransportImp override///////
> diff -Naur ZLMediaKit/webrtc/WebRtcSession.h ZLMediaKit-m/webrtc/WebRtcSession.h
> --- ZLMediaKit/webrtc/WebRtcSession.h   2023-05-11 15:13:45.000000000 +0300
> +++ ZLMediaKit-m/webrtc/WebRtcSession.h 2023-05-13 10:00:57.363481109 +0300
> @@ -35,6 +35,9 @@
>      void onManager() override;
>      static EventPoller::Ptr queryPoller(const Buffer::Ptr &buffer);
>  
> +protected:
> +    WebRtcTransportImp::Ptr _transport;
> +
>  private:
>      //// HttpRequestSplitter override ////
>      ssize_t onRecvHeader(const char *data, size_t len) override;
> @@ -47,7 +50,6 @@
>      bool _find_transport = true;
>      Ticker _ticker;
>      std::weak_ptr<toolkit::TcpServer> _server;
> -    WebRtcTransportImp::Ptr _transport;
>  };
>  
>  }// namespace mediakit
> ```
> 
> And make **protected** _mediaInfo in **HttpSession**?

you can pull request on github , author will consider and judge if merge

**Comment by xia-chu** [comment]
Thank for you pr!

**Comment by a-ucontrol** [comment]
> Thank for you pr!

Thank for you ZLMediaKit!
