### ISSUE TITLE
文件索引目录如何关掉？

### ISSUE THREAD

**Issue by zwfcz** [ZLMediaKit/ZLMediaKit#2466]
文件索引目录如何关掉？浏览器访问80端口就列出文件索引目录，请教如何关掉？列出来很不安全

**Comment by BackT0TheFuture** [comment]
config.ini每行都有注释，使用前最好看一看，事半功倍

**Comment by xia-chu** [comment]
> config.ini每行都有注释，使用前最好看一看，事半功倍

@BackT0TheFuture 感谢答复 

他连issue模板都不看一遍 你觉得你有时间看config.ini注释么？
