### ISSUE TITLE
[功能请求] 关于webhook提供视频播放结束的hook

### ISSUE THREAD

**Issue by moyels** [ZLMediaKit/ZLMediaKit#2470]
**描述该功能的用处，可以提供相关资料描述该功能**
目前使用中有一个需求需要获取某个客户端开始播放视频、视频播放结束的时机，做一些日志记录的操作，目前的on_play鉴权可以获取到播放的时机，但是结束的时机无法获取，而在ZLMediaKit本身的日志记录中，似乎是有视频结束的日志记录，但是没有开始时的日志记录。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
否

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
on_flow_report hook 在播放器或推流器断开时触发 有参数判断是否是播放或推流。
你把流量阈值设置为0，就相当于结束的hook
