### ISSUE TITLE
[技术咨询] 点播 http-mp4 转 rtsp

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2471]
**咨询的功能模块**
- 点播 http-mp4 转 rtsp

**咨询的具体内容和问题**
- 项目中需要实现一个媒体网关.
1.客户端通过rtsp向网关请求音视频数据。
2.媒体网关需要主动通过http-mp4从网络上拉流(点播)，然后吧音视频数据发送给客户端。
3.网关需要实现 http-mp4(点播) 的 seek功能. 客户端通过自定义协议向网关请求seek播放。
咨询相关接口函数调用。

@xia-chu 已经通过ffmpeg来实现http-mp4的拉流和拖动功能了，并且在内存里面吧音视频数据传递给zlmediakit来实现http-mp4点播转rtsp直播，现在需要实现rtsp的拖动转http-mp4拖动，请问应用层怎么获取zlmedakit的rtsp的拖动报文消息。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
zlm的MediaSourceEvent接口有on_seek回调 你要自己适配下

**Comment by HalcyonHuang** [comment]
1.rtsp的协议里面，像vlc这样的客户端如何获取点播文件的播放时长。
2. 通过ffmpeg获取http-mp4的音视频数据然后在内存里面传递给zlmediakit，但是vlc使用rtsp协议播放速度不对。而且报异常:MPEG.cpp:79 inputFrame | 必须提供adts头才能mpeg-ts打包.
3.有哪些函数可以添加adts头数据

代码片段如下:
其中  视频 in_time_base  num:1 den:90000     out_time_base num:1 den:90000
          音频 in_time_base  num:1 den:44100     out_time_base num:1 den:48000

void on_frame(int codec_id, uint64_t dts, const char *data, int size) {
    mk_frame frame = mk_frame_create(codec_id, dts, dts, data, size, NULL, NULL);
    mk_media_input_frame(m_media, frame);
    mk_frame_unref(frame);
}

bool TrancodeWrite(AVPacket* pkt)
{
    int codec_id = MKCodecH264;
    AVRational in_time_base;
    AVRational out_time_base;
    if (stream_mapping[pkt->stream_index] == video_stream_index){
        in_time_base = m_in_video_time_base;
        out_time_base.den = 90000;
        out_time_base.num = 1;
        codec_id = MKCodecH264;
    }else if (stream_mapping[pkt->stream_index] == audio_stream_index){
        in_time_base = m_in_audio_time_base;
        out_time_base.den = 48000;
        out_time_base.num = 1;
        codec_id = MKCodecAAC;    return true;
    }else{
    }
    /* copy packet */
    pkt->pts = av_rescale_q_rnd(pkt->pts, in_time_base, out_time_base, (AVRounding)(AV_ROUND_NEAR_INF|AV_ROUND_PASS_MINMAX));
    pkt->dts = av_rescale_q_rnd(pkt->dts, in_time_base, out_time_base, (AVRounding)(AV_ROUND_NEAR_INF|AV_ROUND_PASS_MINMAX));
    pkt->duration = av_rescale_q(pkt->duration, in_time_base, out_time_base);
    pkt->pos = -1;
    on_frame(codec_id,pkt->dts,(const char *)pkt->data,pkt->size);
    return true;
}



void run()
{
    AVBitStreamFilterContext* h264bsfc = av_bitstream_filter_init("h264_mp4toannexb"); 
    AVBitStreamFilterContext* aacbsfc = av_bitstream_filter_init("aac_adtstoasc"); 
 
    while (running)
    {
        ret = av_read_frame(ifmt_ctx, pkt);
        if(ifmt_ctx->streams[pkt->stream_index]->codec->codec_id == AV_CODEC_ID_H264){
            av_bitstream_filter_filter(h264bsfc, ifmt_ctx->streams[pkt->stream_index]->codec, NULL, &pkt->data, &pkt->size, pkt->data, pkt->size, 0);
        }else if(ifmt_ctx->streams[pkt->stream_index]->codec->codec_id == AV_CODEC_ID_AAC){
            av_bitstream_filter_filter(aacbsfc, ifmt_ctx->streams[pkt->stream_index]->codec, NULL, &pkt->data, &pkt->size, pkt->data, pkt->size, 0);
        }
    }
}

**Comment by xia-chu** [comment]
1、rtsp协议可以通过sdp和setup握手获取时长信息。
2、adts头可以通过extra_data生成：
<img width="829" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/8e6c1541-d3e2-4a0c-802f-8f4904cf415b">

**Comment by HalcyonHuang** [comment]
@xia-chu 问题1 和3都解决了。
问题2:通过ffmpeg获取http-mp4的音视频数据然后在内存里面传递给zlmediakit，但是vlc使用rtsp协议播放速度不对。

怀疑是和时间戳或者流控有关。因为我的应用场景是http-mp4点播转rtsp直播，流控应该怎么做呢，有建议吗

**Comment by HalcyonHuang** [comment]
@xia-chu 由于问题2没能解决, 打算换个思路。

我的应用场景是http-mp4点播转rtsp点播。
在rtsp的消息 void RtspSession::emitOnPlay()消息里面通过 HttpDownloader 吧http-mp4文件下载到本地，然后接下来就是正常的rtsp本地文件点播流程了，但是由于http下载慢，每次都报错:
  MediaServer[24872-event poller 0] MediaSource.cpp:585 createFromMP4 | 打开文件失败:/home/ubuntu/work/ZLMediaKit-trancode/release/linux/Debug/www/record/test_20230420_153704.mp4

我应该怎么调整播放流程？

**Comment by xia-chu** [comment]
你肯定不能用HttpDownloader类啊 因为你没法做流控啊 而且还是磁盘中转的。
你要自己做一个类型http-ts播放器这样的类，要自己根据时间戳控制拉流速度的。
建议还是用FFmpeg实现吧
