### ISSUE TITLE
WEBRTC模块可否增加FLEX-FEC或RS-FEC冗余算法

### ISSUE THREAD

**Issue by doitsjz** [ZLMediaKit/ZLMediaKit#2472]
**描述该功能的用处，可以提供相关资料描述该功能**
用于流媒体服务器与移动端直接的弱网对抗，在丢包时通过冗余比直接重传更能够提供实现性。
FLEX-FEC：https://datatracker.ietf.org/doc/html/rfc8627
RS-FEC： https://www.rfc-editor.org/rfc/rfc6865

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
fec一般只对音频生效 视频不加fec的 因为fec会大大提高带宽使用量的。
老实讲，目前没时间去规划实现fec的事情 这个不是很重要，我也用不到，而这个工作量不小。
开源项目共建共享，欢迎您实现fec 然后提个pr 这样后人就不会有你当前的烦恼了
