### ISSUE TITLE
[addStreamPusherProxy 多推] 是否可以支持同时推多路功能

### ISSUE THREAD

**Issue by c1ngular** [ZLMediaKit/ZLMediaKit#2473]
**描述该功能的用处，可以提供相关资料描述该功能**

有些时候需要推送一路流到多个目的地，比如直播的时候可以同时推送到多个平台

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

addStreamPusherProxy支持一个流同时推送到多个目的地，不需要多次调用这个接口，可以节省资源，还可以保持推出去的多个流画面和时间同步。

**Comment by xiongguangjie** [comment]
可以的，你调用多次不就可以了

**Comment by c1ngular** [comment]
@xiongguangjie  好的，谢谢大佬。我本来以为多次调用和单次调用在实现（性能）和效果（多路的同步）上会不一样
