### ISSUE TITLE
[功能请求] 希望支持PSI_STREAM_MPEG4_AAC_LATM格式的音频

### ISSUE THREAD

**Issue by zhang2349** [ZLMediaKit/ZLMediaKit#2475]
**描述该功能的用处，可以提供相关资料描述该功能**

一些执法记录仪等移动设备的AAC格式的音频流类型是PSI_STREAM_MPEG4_AAC_LATM
希望能支持这种格式

**Comment by xia-chu** [comment]
这种需求需要你自己实现 因为我没测试环境 也没这个需求 欢迎你实现后提交pr
开源项目共建共享 你今天能解决这个问题并做出贡献 那么后人就没你现在的苦恼。
