### ISSUE TITLE
[技术咨询] 点播相关咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2477]
**咨询的功能模块**
您好，最近我们在开发录像点播，想点播观看一个时间段内的视频，于是乎修改了部分您MP4reader的代码；可以读多个已经存在的并且时间在我指定的时间段内的MP4片段；
但是会有这样一个需求，就是起始时间是过去，截止时间是未来；
如：点播功能，我想点播一段时间的视频，比如现在17点，我从早上就开着录像，然后我想点播今天中午12:00到晚上9点的视频，但是现在才下午5点，可是我从12:00开始看视频，等我点播播放到下午5点左右，其实真实的北京时间已经是晚上9点了，录像也有相应的文件了；

但是现在问题是，我一次点播，只能拿到截止当前点播时候的录像【假设我一直开着录像】；未来时间的录像我是拿不到的

**咨询的具体内容和问题**
于是我想了两个办法
（1）判断点播截止时间是否是未来时间，如果是，当我点播功能读完本次能访问的文件夹内的所有文件，之后，在遍历文件夹，找到新产生的文件，如果时间在点播截止时间之前，就接着送打包输出，让点播终端能接着看；
但是这样做的弊端在于，我读完部分文件，就要遍历一次文件夹；文件夹我还要从头遍历，是否产生新的文件；就感觉文件夹访问也是很耗时的；
（2）由于录像类和点播类没有共同的资源，所以我写了个全局函数和变量保存新生成的录像，一旦我点播的时间包含未来时间 or 未产生录像的时间，那我就标记下,每次录像结束后，吧新文件写进来，我就不用像（1）一样访问文件夹了；
但是这样就避免不了使用锁，不知道会不会影响录像和点播，尤其是多路的时候；

我的研发能力和见识比较浅薄

`  
#include <mutex>
#include <map>
#include<vector>
namespace mediakit {

// 用于点播未来时间，记录录像新生成文件，避免频繁遍历文件夹
static std::recursive_mutex playBackMp4FileLock;
// 存储新生成的录像文件,只有点播截止时间是未来时间的，才会存在这里
static std::map<std::string, std::vector<std::string>> newRecordFileMap;
// 录像与点播共用函数
void addPrePlaybackStreamInfo(const std::string &streamID) {
    std::lock_guard<std::recursive_mutex> lock(playBackMp4FileLock);
    std::vector<std::string> Filelist;
    newRecordFileMap[streamID] = Filelist;
}
//点播的截止时间已经到了，删除预存
void delPrePlaybackStreamInfo(const std::string &streamID) {
    std::lock_guard<std::recursive_mutex> lock(playBackMp4FileLock);
    auto it = newRecordFileMap.find(streamID);
    if (it != newRecordFileMap.end())
    {
        newRecordFileMap.erase(it);
    }
  
}

void saveNewMP4FileToReader(const std::string &streamID, const std::string &fileName) {
	//MP4录像完成一个文件之后如果该streamID在map中就把新生成的文件存入list
    //一旦未来时间已经到达，要记得删除这个streamID在map中的记录
    std::lock_guard<std::recursive_mutex> lock(playBackMp4FileLock);
    auto it = newRecordFileMap.find(streamID);
    if (it != newRecordFileMap.end())
    {
        it->second.emplace_back(fileName);
    }
}

void readNewMp4FileToReader(const std::string &streamID, std::vector<std::string> &readerList) {
    ////mp4reader点播完现有文件，还未到点播结束时间，如果有新生成的文件，继续点播
    std::lock_guard<std::recursive_mutex> lock(playBackMp4FileLock);
    if (!newRecordFileMap.empty())
    {
        readerList.insert(readerList.end(), newRecordFileMap[streamID].begin(), newRecordFileMap[streamID].end());
        std::vector<std::string>().swap(newRecordFileMap[streamID]); // 清除容器

    }
}

} 
`

**注意事项**
您觉得哪种好点，因为我的开发能力一般，现在能想到的也就这样；或者是否有更好的提议？

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
你了解下hls event 流，直播时移动，比较合适你的情况，但是这个与ZLM无关
