### ISSUE TITLE
[feature]C API missing getMediaInfo (codec/fps/samplerate/....) and getStaticstic method

### ISSUE THREAD

**Issue by c1ngular** [ZLMediaKit/ZLMediaKit#2480]
is it not implemented in C api , or i missed it somewhere ?  it is quite essential information to MediaSource and MediaServer.

**Comment by xia-chu** [comment]
C SDK just had wrapped the main core streaming related capabilities.
Many logic in `MediaServer` had not be wrapped. 
Welcom for your pull request if you need it.

**Comment by c1ngular** [comment]
Thanks , I would love to contribute to this wonderful project,   but my C++ experience is basically zero .  Is it possible to use C SDK with web hooks and APIs at same time ? 

For instance, use C SDK to start the servers , and then use web APIs / hooks to implement my business logics ?

**Comment by c1ngular** [comment]
@xia-chu i did give a try , could not managed to make C SDK work with web APIs/hooks , no hooks neither restful API works when using  C SDK .

**Comment by xia-chu** [comment]
Please apply this patch:
```patch
Index: api/include/mk_common.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/include/mk_common.h b/api/include/mk_common.h
--- a/api/include/mk_common.h	(revision d4f80171171cdfc00c6be27fab33124eae6a1bdd)
+++ b/api/include/mk_common.h	(date 1680489558714)
@@ -204,6 +204,8 @@
  */
 API_EXPORT uint16_t API_CALL mk_shell_server_start(uint16_t port);
 
+int start_main(int argc,char *argv[]);
+
 #ifdef __cplusplus
 }
 #endif
Index: api/CMakeLists.txt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/CMakeLists.txt b/api/CMakeLists.txt
--- a/api/CMakeLists.txt	(revision d4f80171171cdfc00c6be27fab33124eae6a1bdd)
+++ b/api/CMakeLists.txt	(date 1684898265364)
@@ -22,11 +22,13 @@
 #
 
 include(GenerateExportHeader)
+add_definitions(-DDISABLE_MAIN)
 file(GLOB API_SRC_LIST
   include/*.h
   source/*.c
   source/*.cpp
-  source/*.h)
+  source/*.h
+ ../server/*.cpp)
 
 set(LINK_LIBRARIES ${MK_LINK_LIBRARIES})
 
Index: server/main.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/main.cpp b/server/main.cpp
--- a/server/main.cpp	(revision d4f80171171cdfc00c6be27fab33124eae6a1bdd)
+++ b/server/main.cpp	(date 1684898397025)
@@ -190,6 +190,7 @@
 //全局变量，在WebApi中用于保存配置文件用
 string g_ini_file;
 
+extern "C" {
 int start_main(int argc,char *argv[]) {
     {
         CMD_main cmd_main;
@@ -401,6 +402,7 @@
     InfoL << "程序退出完毕!";
     return 0;
 }
+}
 
 #ifndef DISABLE_MAIN
 int main(int argc,char *argv[]) {

```

**Comment by xia-chu** [comment]
You need call `start_main` to start `MediaServer`.

**Comment by c1ngular** [comment]
@xia-chu thanks a lot , i was using your c sdk with golang on desktop environment , i have successfully imported (most of ) C APIs needed in go , i was thinking to retrieve tracks information in your current on_mk_media_changed callback implementation ,but have not got a clue yet , would you mind some guidelines to that ? 

thanks again for your time and patience .

**Comment by c1ngular** [comment]
@xia-chu thanks a lot , i was using your c sdk with golang on desktop environment , i have successfully imported (most of ) C APIs needed in go , i was thinking to retrieve tracks information in your current on_mk_media_changed callback implementation ,but have not got a clue yet , would you mind some guidelines to that ? 

thanks again for your time and patience .

**Comment by xia-chu** [comment]
Pease apply this patch:
```patch
Index: api/source/mk_events_objects.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/source/mk_events_objects.cpp b/api/source/mk_events_objects.cpp
--- a/api/source/mk_events_objects.cpp	(revision 7e1078bbcc8e4c2c0c1deb1f66b10fce9a4a6ee6)
+++ b/api/source/mk_events_objects.cpp	(date 1686119907642)
@@ -198,6 +198,22 @@
     return src->totalReaderCount();
 }
 
+API_EXPORT int API_CALL mk_media_source_get_track_count(const mk_media_source ctx) {
+    assert(ctx);
+    MediaSource *src = (MediaSource *)ctx;
+    return src->getTracks(false).size();
+}
+
+API_EXPORT mk_track API_CALL mk_media_source_get_track(const mk_media_source ctx, int index) {
+    assert(ctx);
+    MediaSource *src = (MediaSource *)ctx;
+    auto tracks = src->getTracks(false);
+    if (index < 0 && index >= tracks.size()) {
+        return nullptr;
+    }
+    return reinterpret_cast<mk_track>(& (tracks[index]));
+}
+
 API_EXPORT int API_CALL mk_media_source_close(const mk_media_source ctx,int force){
     assert(ctx);
     MediaSource *src = (MediaSource *)ctx;
Index: api/include/mk_events_objects.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/api/include/mk_events_objects.h b/api/include/mk_events_objects.h
--- a/api/include/mk_events_objects.h	(revision 7e1078bbcc8e4c2c0c1deb1f66b10fce9a4a6ee6)
+++ b/api/include/mk_events_objects.h	(date 1686119870812)
@@ -12,6 +12,7 @@
 #define MK_EVENT_OBJECTS_H
 #include "mk_common.h"
 #include "mk_tcp.h"
+#include "mk_track.h"
 #ifdef __cplusplus
 extern "C" {
 #endif
@@ -95,6 +96,10 @@
 API_EXPORT int API_CALL mk_media_source_get_reader_count(const mk_media_source ctx);
 //MediaSource::totalReaderCount()
 API_EXPORT int API_CALL mk_media_source_get_total_reader_count(const mk_media_source ctx);
+// get track count from MediaSource
+API_EXPORT int API_CALL mk_media_source_get_track_count(const mk_media_source ctx);
+// get track by index from MediaSource
+API_EXPORT mk_track API_CALL mk_media_source_get_track(const mk_media_source ctx, int index);
 /**
  * 直播源在ZLMediaKit中被称作为MediaSource，
  * 目前支持3种，分别是RtmpMediaSource、RtspMediaSource、HlsMediaSource
  *
```

I'm sorry for replying now. If you don't mind, please submit a pull request!

**Comment by c1ngular** [comment]
@xia-chu  thanks , as I mentioned earlier in this post, I am willing to contribute to this wonderful project , but I have very little confidence in my c/c++ knowledge and coding standards .  I have learned quite a lot from your work , thanks again .

**Comment by c1ngular** [comment]
@xia-chu patch cause panic , I tested your patch in simple code below :

`void API_CALL on_media_changed(int regist,const mk_media_source sender) {
    int trackCnt=mk_media_source_get_track_count(sender);
    for(int n=0;n<trackCnt;n++){
        mk_track track= mk_media_source_get_track(sender, n);
        printf("codec name： %s\n", mk_track_codec_name(track)); //panic here whenever I call any methods from mk_track.h 

    }

    onMediaChanged(regist,sender);
}`

I could not find the cause of panic , would you mind take a look , thanks .

**Comment by xia-chu** [comment]
> @xia-chu patch cause panic , I tested your patch in simple code below :
> 
> ` void API_CALL on_media_changed(int regist,const mk_media_source sender) { int trackCnt=mk_media_source_get_track_count(sender); for(int n=0;n<trackCnt;n++){ mk_track track= mk_media_source_get_track(sender, n); printf("codec name： %s\n", mk_track_codec_name(track)); //panic here whenever I call any methods from mk_track.h
> 
> ```
> }
> ```
> 
> } `
> 
> I could not find the cause of panic , would you mind take a look , thanks .

It worked very fine on my machine:
<img width="1323" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/346ef302-b4a2-40fd-88b8-51f9fa66e8df">

**Comment by xia-chu** [comment]
Please update code to #2541
