### ISSUE TITLE
[技术咨询] 使用docker部署时如何定义日志级别

### ISSUE THREAD

**Issue by lystormenvoy** [ZLMediaKit/ZLMediaKit#2483]
**咨询的功能模块**
- docker官方镜像

**咨询的具体内容和问题**
- 目前docker运行的话似乎固定的-l 0，如果需要调整似乎只有自制镜像一途？
- 能否将日志级别的定义放在配置文件里

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
如果配置文件和命令行同时指定 那么以哪个为优先？docker镜像默认开启所有日志 我认为是合适的 你又不天天盯着他看。。。

**Comment by lystormenvoy** [comment]
> 如果配置文件和命令行同时指定 那么以哪个为优先？docker镜像默认开启所有日志 我认为是合适的 你又不天天盯着他看。。。

主要是担心访问量大或者出现特定故障疯狂刷写日志导致日志文件过大的问题，所以一般业务都只开ERROR级别日志避免占用空间，需要调试问题才调整级别。

**Comment by xia-chu** [comment]
日志文件会自己删除的

**Comment by lystormenvoy** [comment]
> 日志文件会自己删除的

好的，谢谢
