### ISSUE TITLE
[技术咨询] 关于海康NVR拉取ZLM RTSP流无法预览的问题

### ISSUE THREAD

**Issue by SuperCatss** [ZLMediaKit/ZLMediaKit#2486]
**咨询的功能模块**
- 关于推拉流与rtp。

**咨询的具体内容和问题**
- 在同一局域网内，在Linux中使用docker部署ZL，在win10中使用obs推流，obs提示无法连接服务器。使用telnet 对docker run 命令中所用到的端口进行测试，端口都可以连通。

以下为docker logs 日志

> 2023-05-23 20:08:08.022 T [MediaServer] [7-event poller 0] TcpServer.h:54 operator() | 12-49(192.168.2.69:4954) mediakit::RtspSession
2023-05-23 20:08:36.523 T [MediaServer] [7-event poller 0] TcpServer.h:54 operator() | 13-50(192.168.2.69:4989) mediakit::HttpSession
2023-05-23 20:08:38.023 T [MediaServer] [7-event poller 0] TcpServer.cpp:173 operator() | 12-49(192.168.2.69:4954) mediakit::RtspSession on err: 1(end of file)
2023-05-23 20:08:38.023 W [MediaServer] [7-event poller 0] RtspSession.cpp:64 onError | 12-49(192.168.2.69:4954) RTSP播放器(//)断开:end of file,耗时(s):30
2023-05-23 20:08:38.023 T [MediaServer] [7-event poller 0] TcpServer.h:51 operator() | 12-49(192.168.2.69:4954) ~mediakit::RtspSession
2023-05-23 20:09:06.525 T [MediaServer] [7-event poller 0] TcpServer.cpp:173 operator() | 13-50(192.168.2.69:4989) mediakit::HttpSession on err: 1(end of file)
2023-05-23 20:09:06.525 T [MediaServer] [7-event poller 0] TcpServer.h:51 operator() | 13-50(192.168.2.69:4989) ~mediakit::HttpSession

使用wireshark 抓包，从点击开始直播，到提示无法连接服务器如下内容。

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/24800663/dd8462f7-3197-4589-bf68-1467720aa864)

另外还想请教一个问题，对于rtsp流，在视频编码为H264时，RTP对于NALU的打包方式是如何选择的，是否可以配置？（之前在接入海康nvr的时候发现使用ZL出来的RTSP流，NALU会有STAP和FU两种格式交替使用，海康自身IPC只有FU，这可能会导致ZL出来的rtsp流无法在nvr中正常预览播放，所以想请教一下）

谢谢！

**注意事项**
- 已搜索相关issue
[[参考issue](https://github.com/ZLMediaKit/ZLMediaKit/issues/1111)](https://github.com/ZLMediaKit/ZLMediaKit/issues/1111)

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by SuperCatss** [comment]
> 所以obs什么时候支持rtsp推流了吗？

抱歉确实是我的问题，使用rtmp推流正常。
才接触音视频，请见谅。
但是还是有一些问题想要请教，在redeme中有写到rtsp支持 rtp over udp rtp over tcp rtp over http rtp组播 四种RTP传输方式，
这4种传播方式，是如何协商，选择的，能否自己配置？
另外对于rtp中H264 对于nalu的打包，ZL是如何选择的？能否自己配置，之前抓包有遇到过这样一种情况 H264中的SPS,PPS 帧使用的是STAP-A，多NAUL打包，但是I帧使用的是FU-A，分片打包。因为需要接入NVR，所以对比了海康IPC的RTP传输包，IPC本身SPS,PPS,I 帧，都使用的是FU-A 分片打包。个人感觉海康nvr可能不支持多naul打包，因为接入nvr无法正常预览。

才接触音视频，可能描述不明确，还请作者指定。谢谢

**Comment by SuperCatss** [comment]
> > 所以obs什么时候支持rtsp推流了吗？
> 
> 抱歉确实是我的问题，使用rtmp推流正常。 才接触音视频，请见谅。 但是还是有一些问题想要请教，在redeme中有写到rtsp支持 rtp over udp rtp over tcp rtp over http rtp组播 四种RTP传输方式， 这4种传播方式，是如何协商，选择的，能否自己配置？ 另外对于rtp中H264 对于nalu的打包，ZL是如何选择的？能否自己配置，之前抓包有遇到过这样一种情况 H264中的SPS,PPS 帧使用的是STAP-A，多NAUL打包，但是I帧使用的是FU-A，分片打包。因为需要接入NVR，所以对比了海康IPC的RTP传输包，IPC本身SPS,PPS,I 帧，都使用的是FU-A 分片打包。个人感觉海康nvr可能不支持多naul打包，因为接入nvr无法正常预览。
> 
> 才接触音视频，可能描述不明确，还请作者指点。谢谢

第一个问题，在另外的issue 找到了答案 [https://github.com/ZLMediaKit/ZLMediaKit/issues/1051](https://github.com/ZLMediaKit/ZLMediaKit/issues/1051)

**Comment by xia-chu** [comment]
zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。

解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式

**Comment by SuperCatss** [comment]
> zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> 
> 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式

这是固定行为吗，是否可以配置呢？

**Comment by SuperCatss** [comment]
> > zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> > 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式
> 
> 在同一个流会话中，SPS,PPS 使用STAP-A 打包，I 帧使用FU-A打包是固定行为吗？能否在同一会话中，都使用同一种打包方式呢？ 或者会考虑按需打包吗？

和海康技术沟通了，海康确实是不支持对于STAP这种组合包的解码，所以想请问作者，后续会有考虑增加按需打包的的功能吗？另外也告诉我，海康nvr 可能在有B帧的情况下，会出现解码问题导致卡帧的情况。
此外在没有征得作者同意的前提下向海康推荐了这个开源项目。如果有冒犯，请作者见谅。

> zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> 
> 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式

和海康技术沟通了，海康确实是不支持对于STAP这种组合包的解码，所以想请问作者，后续会有考虑增加按需打包的的功能吗？另外也告诉我，海康nvr 可能在有B帧的情况下，会出现解码问题导致卡帧的情况。
此外在没有征得作者同意的前提下向海康推荐了这个开源项目。如果有冒犯，请作者见谅。

**Comment by SuperCatss** [comment]
> zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> 
> 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式

和海康技术沟通了，海康确实是不支持对于STAP这种组合包的解码，所以想请问作者，后续会有考虑增加按需打包的的功能吗？另外也告诉我，海康nvr 可能在有B帧的情况下，会出现解码问题导致卡帧的情况。
此外在没有征得作者同意的前提下向海康推荐了这个开源项目。如果有冒犯，请作者见谅。

**Comment by xia-chu** [comment]
> > zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> > 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式
> 
> 和海康技术沟通了，海康确实是不支持对于STAP这种组合包的解码，所以想请问作者，后续会有考虑增加按需打包的的功能吗？另外也告诉我，海康nvr 可能在有B帧的情况下，会出现解码问题导致卡帧的情况。 此外在没有征得作者同意的前提下向海康推荐了这个开源项目。如果有冒犯，请作者见谅。

嗨 忘了及时答复你 感谢推广zlmediakit项目！你说`考虑增加按需打包` 是说新增一个配置文件 是否去掉STAP-A打包模式而是采用`Single NAL unit packet per H.264`模式吗？

**Comment by SuperCatss** [comment]
> 

是的，增加一个配置文件。按照配置文件的配置，选择STAP-A打包方式或者Single NAL unit packet per H.264打包方式。
另外，在和海康进行远程调试以后，最新的进度是这样的。海康最新的播放固件是只是STAP-A 这种聚合包的打包方式的。
给海康提供了Dump文件，反馈给我从ZLM拉取的RTSP流时间戳存在回退的问题，现在我还在排查这个问题。

**Comment by SuperCatss** [comment]
> > > zlmediakit的264 rtp打包使用的FU-A/STAP-A方式，使用STAP-A方式是因为webrtc不支持` Single NAL unit packet per H.264` 模式。
> > > 解包支持FU-A/STAP-A/Single NAL unit packet per H.264方式
> > 
> > 
> > 和海康技术沟通了，海康确实是不支持对于STAP这种组合包的解码，所以想请问作者，后续会有考虑增加按需打包的的功能吗？另外也告诉我，海康nvr 可能在有B帧的情况下，会出现解码问题导致卡帧的情况。 此外在没有征得作者同意的前提下向海康推荐了这个开源项目。如果有冒犯，请作者见谅。
> 
> 嗨 忘了及时答复你 感谢推广zlmediakit项目！你说`考虑增加按需打包` 是说新增一个配置文件 是否去掉STAP-A打包模式而是采用`Single NAL unit packet per H.264`模式吗？

是的，增加一个配置文件。按照配置文件的配置，选择STAP-A打包方式或者Single NAL unit packet per H.264打包方式。
另外，在和海康进行远程调试以后，最新的进度是这样的。海康最新的播放固件是只是STAP-A 这种聚合包的打包方式的。
给海康提供了Dump文件，反馈给我从ZLM拉取的RTSP流时间戳存在回退的问题，现在我还在排查这个问题。

**Comment by xia-chu** [comment]
你是rtmp推流给zlmediakit的 zlmediakit会再生成ntp时间戳 rtp时间戳是不会回退的 如果你的系统时间戳回退 可能导致ntp时间戳回退

**Comment by SuperCatss** [comment]
> 

这个问题我目前还没有头绪，我可以提供以下抓包文件，能麻烦帮忙看看吗，我对比了直接从海康IPC拉取流的抓包记录，发现使用zlm的rtp时间戳，两帧之间的差值有些不太正常，太大了。IPC拉取的，差值就比较正常。

**Comment by SuperCatss** [comment]
> 你是rtmp推流给zlmediakit的 zlmediakit会再生成ntp时间戳 rtp时间戳是不会回退的 如果你的系统时间戳回退 可能导致ntp时间戳回退

这个问题我目前还没有头绪，我可以提供以下抓包文件，能麻烦帮忙看看吗，我对比了直接从海康IPC拉取流的抓包记录，发现使用zlm的rtp时间戳，两帧之间的差值有些不太正常，太大了。IPC拉取的，差值就比较正常。

**Comment by SuperCatss** [comment]
> 



> rtmp推流跟rtsp有啥关系 没可比性

实际场景是，我使用rtmp推流至ZLM，海康使用RTSP从ZLM拉流。本身没有对这两种协议做什么比较。只是想知道为什么海康说从ZLM拉取的流存在时间戳异常的问题。我使用vlc也用rtsp拉取这个流进行播放，能正常播放。但是两个包中间的时间戳间隔好像有些异常。
这里截取了部分使用vlc从ZLM拉取RTSP流播放时的包记录。
[new100_00000_20230525112353.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11590299/new100_00000_20230525112353.zip)

**Comment by xia-chu** [comment]
海康的人要给截图给证据 否则我只能看做是胡说八道

**Comment by SuperCatss** [comment]
> 



> 海康的人要给截图给证据 否则我只能看做是胡说八道

方便帮我看看这个包记录吗？两个包的时间戳差值，为什么这么大呢？
差值计算不是计算相邻Seq的包差值吗?

**Comment by xia-chu** [comment]
你这时间戳都是回退的：
<img width="935" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/b0f9393f-9094-40be-8a66-ffae05b1a470">

**Comment by SuperCatss** [comment]
> 你这时间戳都是回退的： <img alt="图片" width="935" src="https://user-images.githubusercontent.com/11495632/241831562-b0f9393f-9094-40be-8a66-ffae05b1a470.png">

我也发现了这个现象，但是没有想明白是为什么出现的，有什么情况会导致这种情况呢？
这种情况下我使用vlc 也能正常拉流播放。就很费解。
