### ISSUE TITLE
[BUG] 配置文件手动修改后被自动覆盖

### ISSUE THREAD

**Issue by qiuzhangming** [ZLMediaKit/ZLMediaKit#2487]
### 现象描述
配置文件会被程序自动覆盖

### 如何复现?
    1. 首先 修改 ZLMediaKit/release/linux/Debug/config.ini 文件
    2. 然后 使用 ./MediaServer -d & 命令启动程序
    3. 期望 使用自己修改后的参数配置
    4. 结果 查看 ZLMediaKit/release/linux/Debug/config.ini 文件，修改后的类容又被覆盖掉了

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: 7e4010df83ffd9b513daaea02f93b53f77a26716
* **操作系统及版本**: Ubuntu 22.04.1 LTS 
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你是否配合wvp使用了？wvp会调用setServerConfig接口接管zlmediakit的配置文件

**Comment by yuetsao** [comment]
> 你是否配合wvp使用了？wvp会调用setServerConfig接口接管zlmediakit的配置文件

我遇到了同样的问题，对于这个十分苦恼，这样我每次启动都要重新配置serverid和secret，况且如果是在k8s或者docker环境中就更难了，因为他们都在一个镜像中（zlm和java应用）

**Comment by Farrahchen** [comment]
我也遇到了这个问题，大家是怎么解决的？？？
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/49346335/3f506224-147b-4267-b183-de4ab29aaf63)

而且我在wvp配置文件里面已经配置了关闭，重启后仍然会覆盖ZLM的配置，变成启用鉴权？？
