### ISSUE TITLE
添加hls录像后无法通过getMp4RecordFile来获取ts文件路径，添加录像不能按照录像文件大小进行切片

### ISSUE THREAD

**Issue by 22727** [ZLMediaKit/ZLMediaKit#2491]
**描述该功能的用处，可以提供相关资料描述该功能**
1.添加hls录像后无法通过getMp4RecordFile来获取ts文件路径，getMp4RecordFile只能获取mp4存储路径。期望解决
2.添加录像入参：切片时间大小，只对类型为MP4格式的生效。hls想要切片只能修改配置文件中切片最大时间来控制。期望解决
3.添加录像 只能选择按切片时间，进行切片。不能选择按录像文件大小进行切面。 期望解决
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
欢迎提交pr
