### ISSUE TITLE
[技术咨询] 可以修改SSL加密算法吗

### ISSUE THREAD

**Issue by qinc998** [ZLMediaKit/ZLMediaKit#2492]
**咨询的功能模块**
- https SSL部分

**咨询的具体内容和问题**
- 可以修改算法配置吗，被扫出漏洞了。。。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36267257/ff39d4de-6b0e-4ffe-87b5-45690b213926)

**Comment by xia-chu** [comment]
这个之前有人在qq群里面问过 给了修复方案 应该是修复了 但是后面不知道怎么忘了同步到ZLToolKit

**Comment by xia-chu** [comment]
需要修改这里: 
https://github.com/ZLMediaKit/ZLToolKit/blob/b30eeca034456417dfca72aa0d2258031013a5e6/src/Util/SSLBox.cpp#LL187C1-L187C77

**Comment by qinc998** [comment]
> 需要修改这里: https://github.com/ZLMediaKit/ZLToolKit/blob/b30eeca034456417dfca72aa0d2258031013a5e6/src/Util/SSLBox.cpp#LL187C1-L187C77

非常感谢大佬

**Comment by xia-chu** [comment]
等你反馈修改后的补丁

**Comment by qinc998** [comment]
> 等你反馈修改后的补丁

大佬，我发现扫到的是19350端口，我直接给关了 sslport=0
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36267257/067a6f06-32f5-451e-acdb-da5bb06048ef)
而且我看过我这里旧版本源码后也没找到DES、3DES，都不知道他们怎么扫出来的。。。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36267257/9c3988de-7826-4f55-8afa-64faf41ff053)
非常感谢大佬回复！！！！

**Comment by xia-chu** [comment]
!DES:!3DES 应该才是关闭吧

**Comment by qinc998** [comment]
> !DES:!3DES 应该才是关闭吧

哦，好吧，我记着了！！！！
