### ISSUE TITLE
[技术咨询] m3u8请求中的set-cookie

### ISSUE THREAD

**Issue by lystormenvoy** [ZLMediaKit/ZLMediaKit#2494]
**咨询的功能模块**
- zlm实践中发现我们播放器请求hls流，在getMediaList中统计时会对每一次m3u8请求进行计数，也就是一个客户端统计成七八个，经了解应该是ZL_COOKIE没有传输？

**咨询的具体内容和问题**
- m3u8请求中的Set-Cookie头中有个path属性，里面的值与我们页面应该是不匹配的，查阅Set-Cookie相关资料，因为path不匹配页面地址所以浏览器应该是不会保存这个cookie的，所以后面也就不会回传，不知道有没有办法自定义这个path值为/之类的呢？
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6795312/2e13b939-df7e-4c91-a54f-7c3ec3b6949d)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
你的页面要设置SameSite 的头部相关信息，具体操作去网上搜索

**Comment by xia-chu** [comment]
你跨域了 所以cookie设置失败。

**Comment by lystormenvoy** [comment]
> 你跨域了 所以cookie设置失败。

这里没有跨域。不过m3u8和ts是通过nginx反代zlm获取的。

**Comment by xia-chu** [comment]
没有 目前只能通过cookie追踪统计播放器

**Comment by lystormenvoy** [comment]
> 你跨域了 所以cookie设置失败。

这个问题通过nginx里的proxy_cookie_path / /media-server/; 使得path里的地址正确。

然后发现expires会比Date头里的日期还要早。原因是服务器时间不准，是否可以添加一个配置项， 配置expires的时间为120s或180s之类的，以提高宽容度？

**Comment by xia-chu** [comment]
你修改这个代码试试吧 
<img width="936" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/3327c27d-0e1c-42f9-ac2d-c6b662f5a2f5">

另外为什么要代理zlm的hls呢？zlmediakit的hls建议直接暴露公网

**Comment by nickfan** [comment]
> > 你跨域了 所以cookie设置失败。
> 
> 这个问题通过nginx里的proxy_cookie_path / /media-server/; 使得path里的地址正确。
> 
> 然后发现expires会比Date头里的日期还要早。原因是服务器时间不准，是否可以添加一个配置项， 配置expires的时间为120s或180s之类的，以提高宽容度？

能否分享一下nginx和zlm的配置如何解决cookie的path和主机host的问题的？

**Comment by lystormenvoy** [comment]
> > > 你跨域了 所以cookie设置失败。
> > 
> > 
> > 这个问题通过nginx里的proxy_cookie_path / /media-server/; 使得path里的地址正确。
> > 然后发现expires会比Date头里的日期还要早。原因是服务器时间不准，是否可以添加一个配置项， 配置expires的时间为120s或180s之类的，以提高宽容度？
> 
> Can you share how to configure nginx and zlm to solve the cookie path and host problems?
> 
> > > > 你跨域了 所以cookie设置失败。
> > 
> > 
> > 这个问题通过nginx里的proxy_cookie_path / /media-server/; 使得path里的地址正确。
> > 然后发现expires会比Date头里的日期还要早。原因是服务器时间不准，是否可以添加一个配置项， 配置expires的时间为120s或180s之类的，以提高宽容度？
> 
> 能否分享一下nginx和zlm的配置如何解决cookie的path和主机host的问题的？
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

```
location ~* /media-server/hls/(.*)/hls.m3u8 {
                include conf.d/options.conf;
                #proxy_cache_valid 200 302 1s;
                include conf.d/cache_lite.conf;
                error_log logs/live_error.log warn;
                access_log  logs/live_mshls_access_$logDate.log;
                #add_header 'Access-Control-Allow-Origin' '*';
                #add_header 'Access-Control-Allow-Credentials' 'true';
                proxy_pass http://rtmp_server/hls/$1/hls.m3u8?$args;
                #proxy_pass http://rtmp_server/media-server/hls/$1/hls.m3u8;
                proxy_cookie_path / /media-server/;
                proxy_set_header Cookie $http_cookie;
                proxy_max_temp_file_size 0;
        }

#切片文件的匹配
        location ~* /media-server/hls/(.*)/(.*).ts {
                include conf.d/options.conf;
                proxy_cache_valid 200 302 40s;
                include conf.d/cache_lite.conf;
                error_log logs/live_error.log warn;
                access_log  logs/live_mshls_access_$logDate.log;
                proxy_pass http://rtmp_server/hls/$1/$2.ts;
                #proxy_pass http://rtmp_server/media-server/hls/$1/$2.ts;
                proxy_cookie_path / /media-server/;
                proxy_set_header Cookie $http_cookie;
                proxy_max_temp_file_size 0;
        }
```

我记得主要是 proxy_cookie_path / /media-server/;这个配置

**Comment by lystormenvoy** [comment]
> > 你跨域了 所以cookie设置失败。
> 
> 这个问题通过nginx里的proxy_cookie_path / /media-server/; 使得path里的地址正确。
> 
> 然后发现expires会比Date头里的日期还要早。原因是服务器时间不准，是否可以添加一个配置项， 配置expires的时间为120s或180s之类的，以提高宽容度？

@nickfan
