### ISSUE TITLE
[BUG] virtualPath功能，通过virtualPath访问文件响应要超过10s

### ISSUE THREAD

**Issue by lystormenvoy** [ZLMediaKit/ZLMediaKit#2495]
### 现象描述

配置了virtualPath功能，然后访问很慢

### 如何复现?

**通过virtualPath地址：**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6795312/dda448be-c082-402b-8b17-153616dc7c89)

**不通过virtualPath地址：**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6795312/be87b31b-61a0-4b77-90b2-8702a14c489c)

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

````
#http服务器监听端口
port=6080
#http文件服务器根目录
#可以为相对(相对于本可执行程序目录)或绝对路径
rootPath=./www
#http文件服务器读文件缓存大小，单位BYTE，调整该参数可以优化文件io性能
sendBufSize=65536
#https服务器监听端口
sslport=4443
#是否显示文件夹菜单，开启后可以浏览文件夹
dirMenu=1
#虚拟目录, 虚拟目录名和文件路径使用","隔开，多个配置路径间用";"隔开
#例如赋值为 app_a,/path/to/a;app_b,/path/to/b 那么
#访问 http://127.0.0.1/app_a/file_a 对应的文件路径为 /path/to/a/file_a
#访问 http://127.0.0.1/app_b/file_b 对应的文件路径为 /path/to/b/file_b
#访问其他http路径,对应的文件路径还是在rootPath内
virtualPath=media-server,/home/ZLMediaKit/www
#禁止后缀的文件使用mmap缓存，使用“,”隔开
#例如赋值为 .mp4,.flv
#那么访问后缀为.mp4与.flv 的文件不缓存
forbidCacheSuffix=
#可以把http代理前真实客户端ip放在http头中：https://github.com/ZLMediaKit/ZLMediaKit/issues/1388
#切勿暴露此key，否则可能导致伪造客户端ip
forwarded_ip_header=
````

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
````
[root@zlm ZLMediaKit]# ./MediaServer -v
编译日期: 2023-05-08T11:35:06
代码日期: %aI
当前git分支: feature/transcode
当前git hash值: 11de725
````

* **代码提交记录/git commit hash**:
* **操作系统及版本**:Linux gx-prod.avawe.cn 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这个是因为hls流未注册，导致的等待超过10s才返回，而且你的hls流请求url也不正确，是三级地址，这个也算个可以优化的地方吧，后面再去优化，三级及以上的地址，直接返回文件

**Comment by xiongguangjie** [comment]
尝试修复一下，看看如何
```
diff --git a/src/Http/HttpFileManager.cpp b/src/Http/HttpFileManager.cpp
index fbd9c17..4b4ffe3 100644
--- a/src/Http/HttpFileManager.cpp
+++ b/src/Http/HttpFileManager.cpp
@@ -13,6 +13,7 @@
 #include <dirent.h>
 #endif //!defined(_WIN32)
 #include <iomanip>
+#include <algorithm>
 #include "HttpFileManager.h"
 #include "Util/File.h"
 #include "HttpConst.h"
@@ -22,6 +23,7 @@
 #include "Common/config.h"
 #include "strCoding.h"
 
+
 using namespace std;
 using namespace toolkit;
 
@@ -355,7 +357,8 @@ static string pathCat(const string &a, const string &b){
  * @param cb 回调对象
  */
 static void accessFile(Session &sender, const Parser &parser, const MediaInfo &media_info, const string &file_path, const HttpFileManager::invoker &cb) {
-    bool is_hls = end_with(file_path, kHlsSuffix);
+    bool is_hls = end_with(file_path, kHlsSuffix) && (std::count(media_info._streamid.begin(),media_info._streamid.end(),'/') <= 1);
+    
     if (!is_hls && !File::fileExist(file_path.data())) {
         //文件不存在且不是hls,那么直接返回404
         sendNotFound(cb);
```

**Comment by xia-chu** [comment]
@xiongguangjie 跟三级目录无关吧 url本来就支持多级
根本原因是它把zlm的http服务器当做纯粹的文件服务器了，但是zlmediakit在处理hls点播时，会有格外操作。

@lystormenvoy 你把 hls.m3u8文件改成record.m3u8就行了 就不会有这个问题了

**Comment by xiongguangjie** [comment]
> @xiongguangjie 跟三级目录无关吧 url本来就支持多级 根本原因是它把zlm的http服务器当做纯粹的文件服务器了，但是zlmediakit在处理hls点播时，会有格外操作。
> 
> @lystormenvoy 你把 hls.m3u8文件改成record.m3u8就行了 就不会有这个问题了

如果是/hls.m3u8,会被认为是直播hls流，导致其等待，这个可以优化下，如果是多级目录，就认为是文件请求

**Comment by xia-chu** [comment]
> > @xiongguangjie 跟三级目录无关吧 url本来就支持多级 根本原因是它把zlm的http服务器当做纯粹的文件服务器了，但是zlmediakit在处理hls点播时，会有格外操作。
> > @lystormenvoy 你把 hls.m3u8文件改成record.m3u8就行了 就不会有这个问题了
> 
> 如果是/hls.m3u8,会被认为是直播hls流，导致其等待，这个可以优化下，如果是多级目录，就认为是文件请求

那人家推流url真的是多级怎么办？

**Comment by xiongguangjie** [comment]
> > > @xiongguangjie 跟三级目录无关吧 url本来就支持多级 根本原因是它把zlm的http服务器当做纯粹的文件服务器了，但是zlmediakit在处理hls点播时，会有格外操作。
> > > @lystormenvoy 你把 hls.m3u8文件改成record.m3u8就行了 就不会有这个问题了
> > 
> > 
> > 如果是/hls.m3u8,会被认为是直播hls流，导致其等待，这个可以优化下，如果是多级目录，就认为是文件请求
> 
> 那人家推流url真的是多级怎么办？

你是规定只能二级吗？ url 被规定死了呀

**Comment by xiongguangjie** [comment]
还是说streamid 允许携带/这种特殊字符吗？？？

**Comment by xia-chu** [comment]
如果推流是这种 rtmp://ip/app/1/2/3/4/streamid 也是可以的 只是不能少于二级

**Comment by lystormenvoy** [comment]
> 这个是因为hls流未注册，导致的等待超过10s才返回，而且你的hls流请求url也不正确，是三级地址，这个也算个可以优化的地方吧，后面再去优化，三级及以上的地址，直接返回文件

hls不是按需拉流的，另外是每一次m3u8加载慢，不是首次请求。今天补充测试了一下，使用vlc开着播放rtmp和hls流，用于测试的网页也是一样加载缓慢。
另外ts的加载似乎影响没那么大。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6795312/8536cd76-76b7-47cf-81ec-c80e97ec30e2)

关于 @xia-chu 说的
> 根本原因是它把zlm的http服务器当做纯粹的文件服务器了，但是zlmediakit在处理hls点播时，会有格外操作。

我目前是hls直播。我的理解hls直播本质上是http文件服务器，hls走的也是[http]这块的端口。vitrual path这块配置应该同样正常工作与hls流的。

**Comment by xiongguangjie** [comment]
> media-server

你这个hls_demand 没有设置为1 吧，如果设置为1 ，会导致hls 源是按需生成的

**Comment by lystormenvoy** [comment]
> > media-server
> 
> 你这个hls_demand 没有设置为1 吧，如果设置为1 ，会导致hls 源是按需生成的

我的意思是，我hls_demand设为0，一直生成的。况且是请求m3u8一直慢，不是第一次，所以不是等待流生成导致的慢。况且我另外开vlc拉着hls流，hls流早已生成的。

**Comment by xiongguangjie** [comment]
> > > media-server
> > 
> > 
> > 你这个hls_demand 没有设置为1 吧，如果设置为1 ，会导致hls 源是按需生成的
> 
> 我的意思是，我hls_demand设为0，一直生成的。况且是请求m3u8一直慢，不是第一次，所以不是等待流生成导致的慢。况且我另外开vlc拉着hls流，hls流早已生成的。

我知道原因了，你做了虚拟路径映射后，就无法快速找到流了，只能通过访问文件，来访问hls.m3u8,但是你通过hls.m3u8访问的话，会被认为是hls直播流，无法找到流，会等待15s左右才会返回文件内容，这个设计如此，直播没有去考虑virtual_path

**Comment by xia-chu** [comment]
> > > > media-server
> 
> > > 
> 
> > > 
> 
> > > 你这个hls_demand 没有设置为1 吧，如果设置为1 ，会导致hls 源是按需生成的
> 
> > 
> 
> > 我的意思是，我hls_demand设为0，一直生成的。况且是请求m3u8一直慢，不是第一次，所以不是等待流生成导致的慢。况且我另外开vlc拉着hls流，hls流早已生成的。
> 
> 
> 
> 我知道原因了，你做了虚拟路径映射后，就无法快速找到流了，只能通过访问文件，来访问hls.m3u8,但是你通过hls.m3u8访问的话，会被认为是hls直播流，无法找到流，会等待15s左右才会返回文件内容，这个设计如此，直播没有去考虑virtual_path 


确实是这个问题 导致解析的app 和 stream id不对，搜索MediaSource不到，只能多等10多秒

**Comment by xia-chu** [comment]
不过按道理 如果支持cookie 只会搜索一遍MediaSource而已

**Comment by xiongguangjie** [comment]
> 不过按道理 如果支持cookie 只会搜索一遍MediaSource而已
MediaSource 一直找不到

**Comment by lystormenvoy** [comment]
> > > > media-server
> > > 
> > > 
> > > 你这个hls_demand 没有设置为1 吧，如果设置为1 ，会导致hls 源是按需生成的
> > 
> > 
> > 我的意思是，我hls_demand设为0，一直生成的。况且是请求m3u8一直慢，不是第一次，所以不是等待流生成导致的慢。况且我另外开vlc拉着hls流，hls流早已生成的。
> 
> 我知道原因了，你做了虚拟路径映射后，就无法快速找到流了，只能通过访问文件，来访问hls.m3u8,但是你通过hls.m3u8访问的话，会被认为是hls直播流，无法找到流，会等待15s左右才会返回文件内容，这个设计如此，直播没有去考虑virtual_path

了解了，这只是我想找到set-cookie问题的一个衍生设置而已，实际上可以不用这个功能。

**Comment by xiongguangjie** [comment]
先关闭了

**Comment by xia-chu** [comment]
这个问题在代码上也不好做处理 zlmediakit的http服务器不是普通的文件服务器 对hls.m3u8的文件是有特殊处理的
