### ISSUE TITLE
[技术咨询] 在获得标准H265帧的情况下如何使用ZLMediaKit将其使用Rtsp进行推流

### ISSUE THREAD

**Issue by Fujimiya-Asuka** [ZLMediaKit/ZLMediaKit#2497]
**咨询的功能模块**
关于使用ZLMediaKit进行Rtsp推流的流程

**咨询的具体内容和问题**
我在安卓上进行开发，现在我可以拿到H265的标准帧，想知道如何对其进行RTSP推流。
创建一个推流器并绑定一个MeidaSource，我应该如何创建这个MediaSource并将我得到H265帧进行输入呢？是用DevChannel吗？我看到里面有个inputH265Frame的方法。如何将这个DevChannel变成MediaSource呢

**Comment by xia-chu** [comment]
是的 你用DevChanne输入H265帧就行 内部会创建并注册MediaSource
