### ISSUE TITLE
[技术咨询]关于代理拉流RTSP交互问题咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2501]
**咨询的功能模块**
用ZLm分别拉大华，海康，宇视的回放流；大华和宇视还是挺不错的，回复的也很规范，但是海康的RTSP交互就有些问题了
我想拉0点的视频，但是跟海康设备交互的时候他给我的是个录像起始时间的流，相当于我给他的starttime参数没起作用；

这个问题一定程度上并不是ZLM的问题；不过VLC是可以正常拉到我想看的时间的；我看ZLm代码注释是参考live555的，故是否这里与VLC的live555还是有一定的差异

比如：我在使用ZLM拉流：
rtsp://gbuser:gbuser123@172.*.*.*/cam/playback?channel=1&subtype=0&starttime=2023_05_22_00_00_00&endtime=2023_05_23_00_00_00
这个地址跟大华进行RTSP交互的时候，describe请求的回复中，base-content：上边完整URL

但是我使用：
rtsp://admin:master007@10.11.107.46/Streaming/tracks/101?starttime=20230524t000000z&endtime=20230525t000000z
这个地址拉还海康设备的时候，VLC拉这个地址，显示的是早上8:00；海康VSplayer也是8:00
但是ZLM拉的是前一天的七点（经过测试，和直接这样rtsp://admin:master007@10.11.107.46/Streaming/tracks/101?，拉到的结果相同）
我在看协议交互过程只看到：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/e4a20df0-90fd-4411-a5dd-1cbafe9ecba2)
它回复的basecontent不对（没有包含我请求的starttime）
![iwEcAqNwbmcDAQTRBaIF0QLWBrB6SGP3_gd8KARnJCNqQBYAB9I97nacCAAJomltCgAL0gABOq4 png_720x720q90](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/db4a97a3-21e4-459c-9c6b-73a5c0721dde)

因为play请求的时候用了basecontent，这个后来我把代码中这里改了一下：

![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/d7396e0a-3daa-4bd4-b915-e44924112a5a)
但是仍然没有什么用；

所以来问问是否能看出VLC和ZLm拉流的一些差异；
附件是VLC直接拉的海康那个录像地址；和ZLm拉的；我看着URL之类的基本已经一样了，可是拉出来的视频内容并不相同；
[Desktop.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11575282/Desktop.zip)

**咨询的具体内容和问题**

是否能从协议的角度看看ZLM和VLC与设备交互还有哪些差异；
**注意事项**

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
vlc 也是用live555 来拉流的，你要对比去分析，而且你这个附件也下载不了呀

**Comment by xuandu** [comment]
[拉流dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11587741/dump.zip)
不好意思传递了无法下载的文件；
我对比了下VLC和ZLM，RTSP交互，现在我的每一个请求都是完整带参数的URL了；但是实际拉到的时间点还是不对；不知道是不是还有什么重要的交互参数我没看到；

**Comment by xuandu** [comment]
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/4e6c2b4e-70c3-4d07-9e67-814d774185cf)
不知道这里是不是标准做法，但是网上查了下，以及根据VLC和一些安防厂的抓包看；descreib返回401后，都是再发一次describe的；尽管我这样改了看着几乎跟VLC抓包一模一样了。但是ZLm仍然得到的不是正确的定位时间；
只是发现这里和一些主流播放器可能不太一样；不知道是否需要改。

**Comment by xiongguangjie** [comment]
根据抓包 我看ZLM与VLC 的url中开始与结束时间的字母大小写不一样，你仔细看一下

**Comment by xuandu** [comment]
那个不影响的，starttime驼峰大小写都是可以的，VLC支持T,Z以及starttime首字母大写的；我也问了海康的技术支持，他们说VLC可以，让我照着VLC改；我现在抓包看除了一些换行符号，已经一毛一样了；哎

**Comment by xiongguangjie** [comment]
不对呀，一个有音频，一个没有怎么回事

**Comment by xuandu** [comment]
[修改后dump件夹.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11590416/dump.zip)

**Comment by xuandu** [comment]
你可以看下这个，我今天抓的时候看到VLC交互的时候回复没有音频后来重新抓了一个；吧代码我圈出来的地方，以及URI都改了；现在请求也都是 option-describe-describe-setup-setup-play；但是得到的内容，VLC是早上8点，ZLm是前一天的晚上的画面；抓包看感觉已经看不出啥了；

**Comment by xuandu** [comment]
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/69384a45-7309-40d1-bc33-29aaafce06ad)
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/e8d930cc-0d0a-4c35-b359-8ddbd0065744)
因为我一直在一台机器上测试的，看到差异有些地方就写死测试的；感觉真的没啥区别了。。。。跟VLC拉回放时候的dump比

**Comment by xiongguangjie** [comment]
这个有人使用ZLM拉取过海康的录像流，这个固件是否可以更新试一下呀

**Comment by xuandu** [comment]
您说更新哪个？设备？好像没办法；因为我的上层一直给我强调VLC可以；就让我照着VLC改ZLM；我就只能从本地改ZLM，做拉流尝试；公司还就这一台，大写的尴尬

**Comment by xiongguangjie** [comment]
> 您说更新哪个？设备？好像没办法；因为我的上层一直给我强调VLC可以；就让我照着VLC改ZLM；我就只能从本地改ZLM，做拉流尝试；公司还就这一台，大写的尴尬
> 
> 其实不是拉不到，只是同样的URL，VLC，VSplayer，ffmpeg，拉到的时间都是早上8点；ZLm拉到的时间不对（经测试应该是starttime endtime没起作用）

play 方法加上header range ，对照这vlc加，试一下

**Comment by xuandu** [comment]
好的。我试试；看到了去年有人在这问同样的问题，但是他没写怎么解决的；我先试试你说的吧

**Comment by xuandu** [comment]
芜湖~~~，可以了耶。range；

**Comment by xiongguangjie** [comment]
> 芜湖~~~，可以了耶。range；熊猫大佬，火眼金睛；手动10万赞

最少的修改，提交一个PR,我没环境，不知道怎么修改合适

**Comment by xuandu** [comment]
我吧改的逐一测试下，把没用的修改删掉，然后报给您修改点，您看看之后在自己改；我个渣渣，可不敢提pr;我待会测试完跟您汇报下至少修改哪些；

**Comment by xiongguangjie** [comment]
> 我吧改的逐一测试下，把没用的修改删掉，然后报给您修改点，您看看之后在自己改；我个渣渣，可不敢提pr;我待会测试完跟您汇报下至少修改哪些；

大胆提交，如果有问题，我会修改的

**Comment by xuandu** [comment]
必要修改点：
两处：（1）play命令要有range
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/2cabdf4b-13e8-464e-8306-8f4a039a6028)
（2）由于海康设备反馈的content-base与请求的URL不一样，play的时候要使用带参URL：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/8a7c37aa-31b5-4264-bb94-921f38a4c911)

-------------------------------------------------------------------------------------------------------------------------
非必要修改点：describe返回401后 VLC和VSplayer-海康，都是二次发送describe命令的，ZLm是发送option的，不过不影响结果，可以不改
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/06c5be28-bfb5-4786-94e0-9632c482831b)
修改后测试拉取大华地址，与VLC和ffplay一样，不受影响

[RtspPlayer.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11591263/RtspPlayer.zip)
好了；您来改吧

**Comment by xiongguangjie** [comment]
```
diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
index 67d0b28..8f7b95b 100644
--- a/src/Rtsp/RtspPlayer.cpp
+++ b/src/Rtsp/RtspPlayer.cpp
@@ -432,8 +432,8 @@ void RtspPlayer::sendPause(int type , uint32_t seekMS){
             sendRtspRequest("PAUSE", _content_base);
             break;
         case type_play:
-            sendRtspRequest("PLAY", _content_base);
-            break;
+            //sendRtspRequest("PLAY", _content_base);
+            //break;
         case type_seek:
             sendRtspRequest("PLAY", _content_base, {"Range",StrPrinter << "npt=" << setiosflags(ios::fixed) << setprecision(2) << seekMS / 1000.0 << "-"});
             break;
@@ -624,7 +624,7 @@ void RtspPlayer::sendRtspRequest(const string &cmd, const string &url,const StrC
     }
 
     _StrPrinter printer;
-    printer << cmd << " " << url << " RTSP/1.0\r\n";
+    printer << cmd << " " << _play_url << " RTSP/1.0\r\n";
     for (auto &pr : header){
         printer << pr.first << ": " << pr.second << "\r\n";
     }
```
这样修改试一下，看是否可行？？

**Comment by xuandu** [comment]
printer << cmd << " " << _play_url << " RTSP/1.0\r\n"; 这里不行
SETup请求的时候URL就不对了：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/2d064361-c032-47c7-8cfb-1a666fa9697e)

**Comment by xiongguangjie** [comment]
> printer << cmd << " " << _play_url << " RTSP/1.0\r\n"; 这里不行 SETup请求的时候URL就不对了： ![图片](https://user-images.githubusercontent.com/18655816/241869278-2d064361-c032-47c7-8cfb-1a666fa9697e.png) [wiresharkZLM.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11596889/wiresharkZLM.zip) setup请求用的 control-URL；直接全用play_url不行； ![图片](https://user-images.githubusercontent.com/18655816/241875591-75d0d9f6-6d6e-4d2d-9873-0ec6d8d51401.png)

好吧还是按照你的来修改吧

**Comment by xia-chu** [comment]
@xuandu 在吗 play命令如果采用content-base做url 会导致一些[兼容性问题](https://github.com/ZLMediaKit/ZLMediaKit/issues/2624)。 我分析vlc就是用content-base作play命令url的。为什么当时你用vlc能正常seek，但是zlm不行呢？
当时zlmediakit也是用content-base作play命令url的。

**Comment by xuandu** [comment]
我在本帖的提问中zlm拉流地址是直接后缀在原始拉流接口后边的，并没有放在postman  body-json里，我这个的问题是海康nvr点播必须要play请求里有range_npt.
但是vlc我并没有关注它是不是把我的拉流地址放在content-base里，因为我当时的抓包里交互过程的zlm与nvr和vlc与nvr的交互url都是一致的。

**Comment by xuandu** [comment]
![微信截图_20230706151919](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/fee7b310-6f46-4d6c-80fb-8a2ffeafa778)
![微信图片_20230706151656](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/b7f39811-3d36-40e4-bb2b-128c6cf1a46e)
这个是我当时VLC拉海康NVR的dump，如图，海康返回给VLC的content-base也是不带starttime endtime的，但是VLC下次的play请求，却还是完整的URL

**Comment by xia-chu** [comment]
@xiongguangjie 反馈把输入url的params截取出来追加到content-base即可 这种方案比较简单可行

**Comment by xuandu** [comment]
ok感谢两位大佬。

**Comment by MainBlackMan** [comment]
> 好的。我试试；看到了去年有人在这问同样的问题，但是他没写怎么解决的；我先试试你说的吧

最后怎么解决的，是已经修复了吗？
