### ISSUE TITLE
Need HLS Streaming Help

### ISSUE THREAD

**Issue by skazmidts** [ZLMediaKit/ZLMediaKit#2503]
Hi,

I have some queries about zlmediakit.

I want RTSP to HLS streaming so that I can play it on modern browsers or if there is any other way through which I can play RTSP on modern browsers.

1- How can I add authentication in HTTP server?
2- How can I lower latency in HLS streaming?
3- How can I record audio/video to file?
4- Is there any way, I can convert zlmediakit streaming module into vb.net like create DLL or something?
5- Is there any event to capture If RTSP camera got disconnected or reconnected?

I will greatly appreciate any help.

Thanks!

**Comment by xia-chu** [comment]
1、Yes, you can turn on authentication in  HTTP server with set a `on_http_access` url on `config.ini` file.
2、HLS live stream is always high latency almost 10 seconds due to the characteristics of the protocol, you can use `webrtc` instead hls.
3、Please set `enable_mp4` to `1` in `config.ini` file.
4、zlmediakit provide a `c sdk` named `mk_api.dll`, you can build it default.
5、You can call `addStreamProxy` http api to proxy a rtsp stream by zlmediakit, what dou you mean `event` ?

**Comment by skazmidts** [comment]
Thanks for you answer.

1- What do you mean by set a on_http_access url on config.ini file.
2- Can you please let me know or send me kind of demo how can I stream rtsp to webrtc. and do need I turn or stun server for this?
3 - Thanks I got it.
4 - Sorry I didn't get it. How can I buid it default?
5- Event means listener like if camera stopped streaming or camera started streaming a function can be called.

Thanks

**Comment by xia-chu** [comment]
1、zlmediakit uses web hook to let your business system decide whether to allow clients to access zlmediakit's HTTP directory, please see [wiki](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-HOOK-API#5on_http_access).

2、You can use [addStremProxy](https://github.com/zlmediakit/ZLMediaKit/wiki/MediaServer%E6%94%AF%E6%8C%81%E7%9A%84HTTP-API#12indexapiaddstreamproxy) to pull a rtsp/rtmp stream to zlmediakit, and you can play it by [webrtc](https://github.com/ZLMediaKit/ZLMediaKit/tree/master/www/webrtc).

4、When you build zlmediakit on windows, it will output c sdk with source header and mk_api.dll.

5、You can set [callback](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/api/include/mk_events.h#L59) in c sdk when player vist zlmediakit, and when player closed, zlmediakit will emit this [callback](https://github.com/ZLMediaKit/ZLMediaKit/blob/master/api/include/mk_events.h#L66)

**Comment by skazmidts** [comment]
1- Got it.
2- I added the stream by using addStreamProxy function and tried to play it by webrtc. It didn't work.
4- I will dig into it
5- Got it.

**Comment by xia-chu** [comment]
2. When you compile zlmediakit, you need [enable webrtc](https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97). You can test it [here](https://zlmediakit.com/webrtc/).  And you can use [docker](https://hub.docker.com/r/zlmediakit/zlmediakit/tags) if you do not want  compile zlmediakit.

**Comment by c1ngular** [comment]
@skazmidts  use web API is highly recommended (you will need a web server to receive the events you want) , C SDK got less features (deployment friendly , you can distribute single executable file).
