### ISSUE TITLE
H265技术咨询

### ISSUE THREAD

**Issue by davidxiao2022** [ZLMediaKit/ZLMediaKit#2506]
**咨询的功能模块**
- zlmediakit的tests中的test_pusher.cpp模块

**咨询的具体内容和问题**
- **使用海康摄像头输出rtsp输出h265视频流，使用potplayer播放器可以打开视频流，确实是HEVC（H265输入）然后将其转换为rtmp的视频流：rtmp://127.0.0.1/live/rtsp_push；只是更改了以下这个地方；具体代码如下：**
- int main(int argc, char *argv[]) {
    return domain("rtsp://admin1:a123456789@192.168.0.163:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1", "rtmp://127.0.0.1/live/rtsp_push");
}
从日志可以看出：暂不支持该rtsp编码类型:MPA；和0 rtsp play success；感觉拉流没有成功；导致没有视频输出，只有音频流输出；
问题：1，test_pusher模块不支持h265的rtsp拉流吗？
           2.  我是想通过拉取海康的h265视频流，输出rtmp的h265视频流；此测试代码可以实现吗？
[log0529.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/11591969/log0529.txt)
[test_pusher.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/11592025/test_pusher.txt)

**Comment by xia-chu** [comment]
MPA是mp4负责格式的rtp zlmediakit不支持ts/mpa的rtsp流
