### ISSUE TITLE
[技术咨询] WebRtcSession区分pusher还是player

### ISSUE THREAD

**Issue by wuchingyy** [ZLMediaKit/ZLMediaKit#2512]
在WebRtcSession这个类里面的onManager函数有没有办法区分是pusher还是player产生的，想做下针对需求的二开
参考过RtmpSession，里面有比较严格意义上可以判断是pusher还是player的
但似乎WebRtcSession里面也按照RtmpSession的方式来实现的话不太可行，RtmpSession有私有变量_push_src_ownership，并且在onCmd_publish的时候就可以设置好这个变量，而WebRtcSession并没有这个步骤，要在WebRtcPusher这个类才有相关的步骤才有

作者有什么思路提供一下么？

**Comment by xiongguangjie** [comment]
> 在WebRtcSession这个类里面的onManager函数有没有办法区分是pusher还是player产生的，想做下针对需求的二开 参考过RtmpSession，里面有比较严格意义上可以判断是pusher还是player的 但似乎WebRtcSession里面也按照RtmpSession的方式来实现的话不太可行，RtmpSession有私有变量_push_src_ownership，并且在onCmd_publish的时候就可以设置好这个变量，而WebRtcSession并没有这个步骤，要在WebRtcPusher这个类才有相关的步骤才有
> 
> 作者有什么思路提供一下么？

使用std::dynamic_cast

**Comment by xia-chu** [comment]
通过std::dynamic_cast看看能转换为哪种派生类实现 当然还有很多方法判断 比如说通过sdp通过虚函数
