### ISSUE TITLE
[功能请求] 请问大神可以增加JT/T1078协议推流吗

### ISSUE THREAD

**Issue by yy1261633791** [ZLMediaKit/ZLMediaKit#2514]
**描述该功能的用处，可以提供相关资料描述该功能**
部标JT/T1078推流
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
已经支持：https://github.com/ZLMediaKit/ZLMediaKit/issues/2364
