### ISSUE TITLE
[BUG] 使用127.0.0.1进行推流时候无法激活推流hook事件(必填)

### ISSUE THREAD

**Issue by ldflovewr** [ZLMediaKit/ZLMediaKit#2515]
### 现象描述

我在使用ZLMediaKit的ffmpeg拉流代理时候转推地址填的rtmp://127.0.0.1（因为是政府客户服务器且使用docker部署，只能暴露一个web端口无法暴露1935端口），但是发现没有进行hook事件回调，导致转推出来的流没有按照设置app进行转码。

### 如何复现?

直接使用rtmp://127.0.0.1推流，并不会进行任何hook回调。

使用本地的内网ip推流则无此问题

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:  CentOS Docker
* **硬件信息**: Intel 
* **其他需要补充的信息**:

**Comment by BackT0TheFuture** [comment]
用本地回环访问是不是会触发hook的

**Comment by ldflovewr** [comment]
> 用本地回环访问是不是会触发hook的

是否可以加个开关控制是否触发啥的，目前主要添加ffmpeg拉流代理这块会用到往本地rtmp://127.0.0.1推

**Comment by xia-chu** [comment]
这不是bug 127本机访问是不触发鉴权的 目的是为了测试方便
