### ISSUE TITLE
[编译问题]请问大神 编译开启faac选项有什么用吗？音频转码为aac开启ffmpeg编译选项不就可以了吗？

### ISSUE THREAD

**Issue by daimalvtu** [ZLMediaKit/ZLMediaKit#2517]
### 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
没啥用 历史代码 你可以忽略它
