### ISSUE TITLE
[技术咨询] 通过zlm转发摄像头rtsp到rtsp over tcp,使用ffmpeg播放rtsp over tcp发现有UINT32回环问题，每13小时15分钟出现

### ISSUE THREAD

**Issue by ShiSimon** [ZLMediaKit/ZLMediaKit#2518]
模块：
rtsp over tcp转发

通过zlm转发摄像头rtsp到rtsp over tcp,使用ffmpeg播放rtsp over tcp发现有UINT32回环问题，每13小时15分钟出现, ffmpeg解析出的pts为-5470990左右，持续时间接近61秒。

**Comment by xia-chu** [comment]
你是addStreamProxy接口拉rtsp流 然后对外提供rtsp流？

**Comment by ShiSimon** [comment]
是的，目的是只拉一路摄像头，在服务器内部处理和转码推多个rtmp/rtsp地址出去。

**Comment by xia-chu** [comment]
不对啊 addStreamProxy接口转发rtsp默认直接代码模式啊  时间戳来自源视频，不做任何修改啊

**Comment by xia-chu** [comment]
这个问题复现成本太高了。。。。

**Comment by ShiSimon** [comment]
确实是有很大的时间成本，但对于时间戳完全来自于源视频我同样有些疑问。
从摄像头拉的时候只有前几帧，甚至仅第一帧是负值或FFMPEG中的AV_NOPTS，但从zlm转发出来的至少超过一秒有负值。

**Comment by xia-chu** [comment]
配置文件directProxy设置为1？

**Comment by ShiSimon** [comment]
是的，默认为1。

**Comment by xia-chu** [comment]
设置为0 回环是正常的 因为zlmediakit的时间戳用的毫秒，uint32记录的，13个小时正好回环

**Comment by ShiSimon** [comment]
好的，我试一下，用现在最新的代码，明天来更新结果

**Comment by xia-chu** [comment]
@ShiSimon 搞定？

**Comment by ShiSimon** [comment]
抱歉，这个问题我能够稳定复现. 当video的pts到了接近0x100000000的时候出现问题。

[20230619 23:27:57.286]  - --[WARNING]-- - [0] pts < 0 -5543196  ffffffffffab6ae4, lastPts=4289421040 ffab5ef0
[20230619 23:27:57.286]  - --[WARNING]-- - We may met wraparound issue, try to correct it
[20230619 23:27:57.286]  - --[WARNING]-- - org_pts=-5543196, correct_pts=4289424100
[20230619 23:27:57.286]  - --[WARNING]-- - We may met wraparound issue
这里我拿到的pts是-5543196，尝试转换后和上一帧的差值是3060，符合fps30时，34ms。
更奇怪的是，因为我一开始拉到了21年的代码，当时使用的是uint32_t的结构，那时我并没有复现该问题
