### ISSUE TITLE
视频播放时，报收流超时，会是什么原因导致的呢

### ISSUE THREAD

**Issue by Xjccheng** [ZLMediaKit/ZLMediaKit#2521]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/135321090/b241182d-38c1-458c-b058-8c9fd4bac1ef)
控制台报：[点播超时] 收流超时 deviceId: 34020000001110000001, channelId: 34020000001320000264，端口：10000, SSRC: 0200004966

**Comment by xia-chu** [comment]
此问题去wvp项目提交

**Comment by Xjccheng** [comment]
ok，感谢，已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月5日(星期一) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ZLMediaKit/ZLMediaKit] 视频播放时，报收流超时，会是什么原因导致的呢 (Issue #2521)





 
此问题请去wvp项目提
