### ISSUE TITLE
通过addStreamProxy接口注册的流在重启应用后数据丢失

### ISSUE THREAD

**Issue by albertyxq** [ZLMediaKit/ZLMediaKit#2522]
你好，老师！
       我是初次使用你们的服务，解决了一直困扰我的监控视频转流的难题，这是一个高效率的转流应用，在这里非常感谢作者和各位大牛们的技术贡献。
       当前我正在享受ZLMediaKit给我带来的畅快的体验和服务，有一个问题咨询老师，启动服务后通过addStreamProxy接口注册一个rtsp流，在服务关闭重启后，之前注册的流丢失，此时只能重新注册。这个会给生产环境带来相当的不便。
        敬请老师指导，有什么方法可以避免上述问题。
        非常感谢！

**Comment by xia-chu** [comment]
设计使然
