### ISSUE TITLE
C接口mk_api中，有没有开启hls服务器的接口？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ZLMediaKit/ZLMediaKit#2527]
在mk_common.h中接口如下，但是没有开启hls服务的接口，如何使用接口启动hls服务？
/**
 * 创建http[s]服务器
 * @param port htt监听端口，推荐80，传入0则随机分配
 * @param ssl 是否为ssl类型服务器
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_http_server_start(uint16_t port, int ssl);

/**
 * 创建rtsp[s]服务器
 * @param port rtsp监听端口，推荐554，传入0则随机分配
 * @param ssl 是否为ssl类型服务器
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_rtsp_server_start(uint16_t port, int ssl);

/**
 * 创建rtmp[s]服务器
 * @param port rtmp监听端口，推荐1935，传入0则随机分配
 * @param ssl 是否为ssl类型服务器
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_rtmp_server_start(uint16_t port, int ssl);

/**
 * 创建rtp服务器
 * @param port rtp监听端口(包括udp/tcp)
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_rtp_server_start(uint16_t port);

/**
 * 创建rtc服务器
 * @param port rtc监听端口
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_rtc_server_start(uint16_t port);

//获取webrtc answer sdp回调函数
typedef void(API_CALL *on_mk_webrtc_get_answer_sdp)(void *user_data, const char *answer, const char *err);

/**
 * webrtc交换sdp，根据offer sdp生成answer sdp
 * @param user_data 回调用户指针
 * @param cb 回调函数
 * @param type webrtc插件类型，支持echo,play,push
 * @param offer webrtc offer sdp
 * @param url rtc url, 例如 rtc://__defaultVhost/app/stream?key1=val1&key2=val2
 */
API_EXPORT void API_CALL mk_webrtc_get_answer_sdp(void *user_data, on_mk_webrtc_get_answer_sdp cb, const char *type,
                                                  const char *offer, const char *url);

API_EXPORT void API_CALL mk_webrtc_get_answer_sdp2(void *user_data, on_user_data_free user_data_free, on_mk_webrtc_get_answer_sdp cb, const char *type,
                                                  const char *offer, const char *url);

/**
 * 创建srt服务器
 * @param port srt监听端口
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_srt_server_start(uint16_t port);

/**
 * 创建shell服务器
 * @param port shell监听端口
 * @return 0:失败,非0:端口号
 */
API_EXPORT uint16_t API_CALL mk_shell_server_start(uint16_t port);

**Comment by xinsuinizhuan** [comment]
使用C接口，启动了http服务，但是是使用hls取流，取不到。

**Comment by c1ngular** [comment]
on_mk_media_publish 回调中 mk_publish_auth_invoker_do设置

**Comment by xinsuinizhuan** [comment]
> on_mk_media_publish 回调中 mk_publish_auth_invoker_do设置

有没有其他设置方法，这个events需要C++20，我目前是Qt+VS2019，设置CONFIG  += c++2a任然不对
mk_events events = {
            .on_mk_media_publish = on_mk_media_publish
        };

**Comment by xinsuinizhuan** [comment]
然后，我使用如下代码，没有回调回来：
mk_events events;
        events.on_mk_media_changed = NULL;
        events.on_mk_media_publish = on_mk_media_publish;
        events.on_mk_media_play = NULL;
        events.on_mk_media_not_found = NULL;
        events.on_mk_media_no_reader = NULL;
        events.on_mk_http_request = NULL;
        events.on_mk_http_access = NULL;
        events.on_mk_http_before_access = NULL;
        events.on_mk_rtsp_get_realm = NULL;
        events.on_mk_rtsp_auth = NULL;
        events.on_mk_record_mp4 = NULL;
        events.on_mk_shell_login = NULL;
        events.on_mk_flow_report = NULL;
        MYLOG<<"mk_events_listen";
        mk_events_listen(&events);

**Comment by xia-chu** [comment]
http服务器就是hls服务器。开启hls协议可以通过mk_media_create/mk_media_create2接口指定
