### ISSUE TITLE
[技术咨询]关于拉流源URL放置位置引起的不同结果问题

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2528]
**咨询的功能模块**
因为我不确定这个是不是一个已知的“认为合理的”逻辑，所以以技术咨询形式提问下

**咨询的具体内容和问题**
我在使用ZLm进行代理拉流的时候，源URL是可以写在GET总体URL的后边，也可以写在body里的；一部分人为了保证拉流源URL不被解码，可能会放到body里：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/53222db3-9138-4242-ab87-400bc1964f61)

GET请求：
http://127.0.0.1:80/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=live&url=rtsp://*.*.*.*/live/TestSample/TestSample_03_01&stream=test212

测试中发现：
（1）如果我把URL放到body里；我第一次拉流返回OK，与此同时我在点击第二次的时候，ZLM返回405
       WarnP(this) << "不支持该命令:" << cmd;

（2）如果我把拉流的源URL放到GET请求的后边，不放在body-raw里，返回OK；代码走这里：
                 if (s_proxyMap.find(key) != s_proxyMap.end()) {
                        //已经在拉流了
                        cb(SockException(Err_success), key);
                        return;
                    }

（3）如果我在调用addstreamproxy接口的时候，源URL：url=rtsp://*.*.*.*/live/TestSample/TestSample_03_01&stream=test212相同，连续调用两次拉流代理接口，前后的streamID不同，的时候，源URL放在body-raw里；第二次调用addstreamproxy，返回405，   WarnP(this) << "不支持该命令:" << cmd;
    打印：
    HttpSession.cpp:73 onRecvHeader | 1-732(127.0.0.1:57583) 不支持该命令:{"url":"rtsp://172.17.228.156/live/TestSample/TestSample_03_01"}GET

（4）如果我在调用addstreamproxy接口的时候，源URL：url=rtsp://*.*.*.*/live/TestSample/TestSample_03_01&stream=test212相同，连续调用两次拉流代理接口，前后的streamID不同，源URL放在GET请求的后边；第二次调用addstreamproxy，返回OK，   并且会创建新的代理；

尽管可能很少人这样调用，但是基于合理调用下，只是URL放置的位置不同，就产生了不同的拉流结果；不知道这是否是一个已知的结果；

综上，根据打印“不支持该命令”的时候的打印，发现这里可能、是否、需要优化下逻辑：
避免产生这种“ HttpSession.cpp:73 onRecvHeader | 1-732(127.0.0.1:57583) 不支持该命令:{"url":"rtsp://172.17.228.156/live/TestSample/TestSample_03_01"}GET”请求；
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/2df46028-2494-4deb-978a-859865038734)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xuandu** [comment]
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/12520f0d-3974-4d42-9d0a-266d3f1bc2d1)

**Comment by xiongguangjie** [comment]
> ![图片](https://user-images.githubusercontent.com/18655816/243286944-12520f0d-3974-4d42-9d0a-266d3f1bc2d1.png) ![微信图片_20230605162212](https://user-images.githubusercontent.com/18655816/243295849-4c5c41a3-1031-4a0e-9b83-790da9c29926.png) 在找packet尾巴的时候，不知道postman是否规范，好像写在body里的东西，会多一行空格，然后index就指向{url:"rtsp://****"}

这个一般GET是不应该携带body 的，但是标准里面是可以携带的，这个需要修改避免下

**Comment by xiongguangjie** [comment]
这样修改应该就可以了
```
diff --git a/src/Http/HttpSession.cpp b/src/Http/HttpSession.cpp
index b443dfe..869003a 100644
--- a/src/Http/HttpSession.cpp
+++ b/src/Http/HttpSession.cpp
@@ -82,6 +82,11 @@ ssize_t HttpSession::onRecvHeader(const char *header,size_t len) {
     ssize_t content_len = 0;
     (this->*(it->second))(content_len);
 
+    if(content_len == 0){
+        //检查Content-length
+        content_len =  _parser["Content-Length"].empty() ? 0 : atoll(_parser["Content-Length"].data());
+    }
+
     //清空解析器节省内存
     _parser.Clear();
     //返回content长度
@@ -406,16 +411,19 @@ void HttpSession::Handle_Req_GET_l(ssize_t &content_len, bool sendBody) {
 
     if (checkLiveStreamFlv()) {
         //拦截http-flv播放器
+        content_len = -1;
         return;
     }
 
     if (checkLiveStreamTS()) {
         //拦截http-ts播放器
+        content_len = -1;
         return;
     }
 
     if (checkLiveStreamFMP4()) {
         //拦截http-fmp4播放器
+        content_len = -1;
         return;
     }
```

**Comment by xuandu** [comment]
测了下，修改后和直接吧URL放在请求行里，结果一样了；感谢热心的熊猫大佬

**Comment by CLAYUP** [comment]
我用curl添加流代理
```shell
curl -X GET http://127.0.0.1/index/api/addStreamProxy?vhost=__defaultVhost__&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&app=proxy&stream=0&url=rtsp://****:******@172.22.31.25/s01/1
````
然后这是它返回结果，但是我如果直接把这个url粘贴到浏览器就能添加成功。。。
```json
 {
        "code" : -300,
        "msg" : "\u7f3a\u5c11\u5fc5\u8981\u53c2\u6570:\"vhost\",\"app\",\"stream\",\"url\""
}
```

**Comment by xia-chu** [comment]
> 

在shell中输入http url时要用引号包裹 否则&会被shell认为你要后台执行curl

**Comment by CLAYUP** [comment]
悟了，感谢大佬！

**Comment by xia-chu** [comment]
修复了这个问题
