### ISSUE TITLE
on_mk_media_publish 使用ffmpeg推流，走回调；使用mk api mk_media_input_h264来推流，不会走mk_publish_auth_invoker_do回调

### ISSUE THREAD

**Issue by xinsuinizhuan** [ZLMediaKit/ZLMediaKit#2531]
使用如下代码：
char *ini_path = mk_util_get_exe_dir("c_api.ini");
char *ssl_path = mk_util_get_exe_dir("ssl.p12");

mk_config config;
config.ini = ini_path;
config.ini_is_path = 1;
config.log_level = 0;
config.log_mask = LOG_CONSOLE;
config.log_file_path = NULL;
config.log_file_days = 0;
config.ssl = ssl_path;
config.ssl_is_path = 1;
config.ssl_pwd = NULL;
config.thread_num = 0;
mk_env_init(&config);
free(ini_path);
free(ssl_path);

mk_http_server_start(80, 0);
mk_http_server_start(443, 1);
mk_rtsp_server_start(554, 0);
mk_rtmp_server_start(1935, 0);
mk_shell_server_start(9000);
mk_rtp_server_start(10000);
mk_rtc_server_start(8000);
mk_srt_server_start(9000);

 mk_events events;
events.on_mk_media_changed = NULL;
events.on_mk_media_publish = on_mk_media_publish;
events.on_mk_media_play = NULL;
events.on_mk_media_not_found = NULL;
events.on_mk_media_no_reader = NULL;
events.on_mk_http_request = NULL;
events.on_mk_http_access = NULL;
events.on_mk_http_before_access = NULL;
events.on_mk_rtsp_get_realm = NULL;
events.on_mk_rtsp_auth = NULL;
events.on_mk_record_mp4 = NULL;
events.on_mk_shell_login = NULL;
events.on_mk_flow_report = NULL;
mk_events_listen(&events);

使用ffmpeg推流：
ffmpeg -re -stream_loop -1 -i D:\test_source\test_video\object\traffice_test.mp4 -vcodec copy -acodec copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:554/Media/Camera2
会走on_mk_media_publish回调函数

但是，我使用mk api来推流：
mk_media_create然后，mk_media_input_h264，来推流，不会走on_mk_media_publish回调函数

**Comment by xinsuinizhuan** [comment]
可以了。make api的mk_media_create有参数开启。

**Comment by fancong5201314** [comment]
@xinsuinizhuan 请问一下，这个mk_media_create接口的哪个参数可以开启啊？我也遇到同样的问题

**Comment by xia-chu** [comment]
```c++
mk_ini *opt = mk_ini_create();
// 设置配置, 参考配置文件protocol下的选项
// 如果不单独指定，则使用全局配置文件
mk_ini_set_option(opt, "enable_mp4", "1");
mk_ini_set_option(opt, "enable_rtsp", "1");

mk_media_create2("vhost", "app", "stream", 0, opt);
mk_ini_release(opt);
```

**Comment by fancong5201314** [comment]
谢谢大神指点
