### ISSUE TITLE
推送仅视频流，从zlmediakit播放会包含音视频

### ISSUE THREAD

**Issue by zhoutianyou00** [ZLMediaKit/ZLMediaKit#2540]
### 现象描述

使用ffmpeg或者gstreamer推送视频流到zlmediakit，播放同一路流，会包含视频和音频。

### 如何复现?
1.使用ffmpeg推送视频到zlmediakit
ffmpeg -re -stream_loop -1 -i car1.mp4 -vcodec copy -an -f flv rtmp://127.0.0.1/live/car
2.使用ffmpeg查看流信息
ffmpeg -i rtsp://10.0.201.57/live/car
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45677131/133f9f19-7f49-4c20-8153-e88f50b53f29)

3. zlmediakit 版本信息
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45677131/8e1209e3-06da-47f4-b502-cbec0aa84729)

**Comment by xia-chu** [comment]
ffmpeg什么时候可以不指定输出直接播放url了？你是不是把ffplay和ffmpeg命令搞混了？

**Comment by xia-chu** [comment]
看错了 你提问的是为什么有音频。

原因是zlmediakit默认添加静音音频 配置文件你可以选择关闭
