### ISSUE TITLE
[技术咨询] httpflv等跨域

### ISSUE THREAD

**Issue by ypy31393936** [ZLMediaKit/ZLMediaKit#2548]
**咨询的功能模块**
- HttpSession.cpp

**咨询的具体内容和问题**
- sendResponse函数中，如果不加上
- headerOut.emplace("Access-Control-Allow-Origin", "*");
- 
- 网页访问m3u8 flv  http-fmp4  http-ts等全部报跨域错误
- 
- 配置文件里的allow_cross_domains=1只解决了options的跨域请求问题

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
要不来个pr?

**Comment by fusionshen** [comment]
您好，我使用docker部署也碰到了类似跨域问题，这次修复大概什么时候会更新

**Comment by xia-chu** [comment]
> 您好，我使用docker部署也碰到了类似跨域问题，这次修复大概什么时候会更新

比较急的话可以把这个patch提交为pr 我合并提交 不急等我们周末改下

**Comment by fusionshen** [comment]
> 

谢谢，按照您正常进度就行。
我使用下面命令部署服务
```docker run -id -p 1935:1935 -p 9080:80 -p 9443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master```
我在内网中192.168.xxx.xxx访问的hls地址是http://192.168.160.158:9080/proxy/d57244dd-a4bf-4f91-b5e7-ea0561b5378a/hls.m3u8?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc，vlc能够正常播放，但是videojs播放就报跨域。

**Comment by fusionshen** [comment]
> > 您好，我使用docker部署也碰到了类似跨域问题，这次修复大概什么时候会更新
> 
> 比较急的话可以把这个patch提交为pr 我合并提交 不急等我们周末改下

谢谢，按照您正常进度就行。
我使用下面命令部署服务
```docker run -id -p 1935:1935 -p 9080:80 -p 9443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master```
我在内网中192.168.xxx.xxx访问的hls地址是http://192.168.160.158:9080/proxy/d57244dd-a4bf-4f91-b5e7-ea0561b5378a/hls.m3u8?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc，vlc能够正常播放，但是videojs播放就报跨域。

**Comment by xia-chu** [comment]
修复了

**Comment by fusionshen** [comment]
docker镜像拉取报错
```
root@jfe-ai:~# docker run -id -p 1935:1935 -p 9080:80 -p 9443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master
Unable to find image 'zlmediakit/zlmediakit:master' locally
master: Pulling from zlmediakit/zlmediakit
7c457f213c76: Pulling fs layer
7f81a709f3d5: Pulling fs layer
e587f4196076: Pulling fs layer
4f4fb700ef54: Waiting
eb4798c03728: Waiting                                                                                                                                       373a382d44f9: Waiting
53d06e5f3638: Waiting
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/16/169854c7f9146a39647750ffe59ca6be14e7001080c810abda041036014ef759/data?verify=1686980316-8EUtskzMJmAv4W6alkkF4yghleE%3D: dial tcp 104.18.121.25:443: i/o timeout.
See 'docker run --help'.
```

**Comment by fusionshen** [comment]
Dockerfile编译也报错
```
root@jfe-ai:~/ZLMediaKit# sh build_docker_images.sh
build_docker_images.sh: 27: [[: not found
build_docker_images.sh: 32: [[: not found
build_docker_images.sh: 37: [[: not found
build_docker_images.sh: 42: [[: not found
unknown cpu-arch
Use 'docker buildx ls' to get supported ARCH
```

**Comment by fusionshen** [comment]
> 修复了
谢谢，我这边已验证成功，跨域问题已经成功解决。
但是今天一天拉取dockerhub镜像都会报错，阿里云上也是如此，我只好Dockerfile编译。
docker镜像拉取报错
```
root@jfe-ai:~# docker run -id -p 1935:1935 -p 9080:80 -p 9443:443 -p 554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master
Unable to find image 'zlmediakit/zlmediakit:master' locally
master: Pulling from zlmediakit/zlmediakit
7c457f213c76: Pulling fs layer
7f81a709f3d5: Pulling fs layer
e587f4196076: Pulling fs layer
4f4fb700ef54: Waiting
eb4798c03728: Waiting                                                                                                                                       373a382d44f9: Waiting
53d06e5f3638: Waiting
docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/16/169854c7f9146a39647750ffe59ca6be14e7001080c810abda041036014ef759/data?verify=1686980316-8EUtskzMJmAv4W6alkkF4yghleE%3D: dial tcp 104.18.121.25:443: i/o timeout.
See 'docker run --help'.
```
