### ISSUE TITLE
[技术咨询] 关于录像写网络盘对性能的影响

### ISSUE THREAD

**Issue by Luosh** [ZLMediaKit/ZLMediaKit#2555]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

目前使用zlm主要用到的是录像和直播功能， 源并发300+左右。

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

 因为录像存储基本都是使用nas，挂载nfs网络盘。 这样在开录像的情况， nfs的网络可能出现不稳定，容易导致zlm直播出现卡顿，api请求超时的情况。有没有可能将录像改成异步写，nfs 网络阻塞时，不影响其他功能。

**Comment by xiongguangjie** [comment]
> **咨询的功能模块**
> 
> * 请描述您想咨询zlmediakit的哪部分功能
> 
> 目前使用zlm主要用到的是录像和直播功能， 源并发300+左右。
> 
> **咨询的具体内容和问题**
> 
> * 此处展开您咨询内容的描述
> 
> 因为录像存储基本都是使用nas，挂载nfs网络盘。 这样在开录像的情况， nfs的网络可能出现不稳定，容易导致zlm直播出现卡顿，api请求超时的情况。有没有可能将录像改成异步写，nfs 网络阻塞时，不影响其他功能。

这个最好是单独用另外一个程序来录制，磁盘io本来就很低，如果搞在一起会阻塞，如果搞成异步的会导致内存一直增长

**Comment by Luosh** [comment]
有想过起两个zlm进程，一个zlm只录，应该也是会有同样的情况， 导致录制拉流阻塞，数据丢失。
还是用其他方案的推拉流录制功能， 比如srs/monibuca， 这些如果录制是异步的，内存应该也会一直增长吧？

zlm录制异步， 是否可以解决 因nfs 网络故障或抖动， 导致的整体功能卡顿故障。内存增长不知道是否可以通过限制待写的队列大小来控制， 或者是nfs本身的一些本地缓存机制来优化。 

不用zlm自身的录像功能， 总感觉有些浪费～

**Comment by xiongguangjie** [comment]
> 有想过起两个zlm进程，一个zlm只录，应该也是会有同样的情况， 导致录制拉流阻塞，数据丢失。 还是用其他方案的推拉流录制功能， 比如srs/monibuca， 这些如果录制是异步的，内存应该也会一直增长吧？
> 
> zlm录制异步， 是否可以解决 因nfs 网络故障或抖动， 导致的整体功能卡顿故障。内存增长不知道是否可以通过限制待写的队列大小来控制， 或者是nfs本身的一些本地缓存机制来优化。
> 
> 不用zlm自身的录像功能， 总感觉有些浪费～

这个主要是你的存储系统的IO存储写入速度的限制，与ZLM关系不大，异步录制无法解决写入速度的限制

**Comment by Luosh** [comment]
写入速度是一回事， 只是发现现在录像的阻塞对直播影响比较大， 哪怕只录一路。

**Comment by xiongguangjie** [comment]
> 写入速度是一回事， 只是发现现在录像的阻塞对直播影响比较大， 哪怕只录一路。

在同一个进程当然会影响，除非你的写入速度快，一般是录制与直播分开来，避免影响
