### ISSUE TITLE
GB级联过程中调用startSendRtp接口返回失败

### ISSUE THREAD

**Issue by houge101** [ZLMediaKit/ZLMediaKit#2556]
**咨询的功能模块**
- startSendRtp接口返回失败

**咨询的具体内容和问题**
- 我在开发一个GB级联wvp代码。我现在我用startSendRtp接口进行GB的rtp流转发到wvp平台，现在我代码所在平台zlm能接收摄像头推流（vlc能看到推流视频），但是调用startSendRtp接口返回说找不到原视频流。
![LV%3BJ8ZFRQ%9T}VXVN} LF](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/04a5f7a9-1b47-46af-aa8d-13a28cd04dbc)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/115f5a8e-eef5-44be-ae72-06c7d40fef47)

![}_A 72A}U4 3JOAQ93 BN85](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/e8a74695-b9a0-48ef-9cdf-709919807876)

我的开发流程是这样的：摄像头注册到我的平台，我的平台级联到wvp。wvp拉取摄像头信息发送给我时，我回复一个181给wvp，然后给摄像头发送invite信息，等待摄像头发送成功后，调用startSendRtp接口转发rtp视频。
![%GP _TV%09UL4O~FWX Q$U](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/151515f3-c678-4420-adf0-39cea343c3f7)

150是wvp平台IP，241是我代码平台IP，87是摄像头IP

- 已经star(收藏)本项目

**Comment by xia-chu** [comment]
请先看一遍wiki：
1、https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81
2、https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99

**Comment by houge101** [comment]
> 请先看一遍wiki： 1、https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81 2、https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99

我是看过之后才问的。现在问题基本解决了。借助这个issues写一下注意事项吧
1.GB服务器级联转发流程如下
1）wvp发送INVITE请求到服务器，服务器回复181，告诉wvp正在转接
2）服务器向对应的IPC发送INVITE请求，IPC回复带SDP的200 OK
3）服务器收到200 OK之后，向IPC回复ACK，并向wvp发送第一步INVITE对应的cseq的带SDP的200OK（有点儿绕，慢慢读）
4）wvp向服务器发送一个ACK，服务器收到wvp的ack后向zlm发送startSendRtp请求，zlm转发视频流到对应的平台

startSendRtp地址需注意如下事项
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/84f64190-b87c-4ad8-8542-860bfb732c08)
1.vhost填写默认的__defaultVhost__，app填写rtp。这些不能变（反正我变了就不通）
2.stream填写流媒体注册时候分配的值（反正我填写国标的那些值是不同）
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/74f9adff-ff8d-4ab4-96fe-122a1276304e)
否则会报 -500 找不到流的错误
3.ssrc填写y字段的值（反正我填写其它，wvp会报ssrc错误）
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/3355923/9656cf28-3b50-455a-8017-fe0ff338d531)
4.dst_url和dst_port填写wvp通过sip协议发送过来的值
5.is_udp赋值为1

我上面提的issues问题出在了：http的url不对和流程中没有回复wvp带SDP的200OK

**Comment by houge101** [comment]
另外还有一个问题想咨询一下：我在收到wvp的ACK后里面发送startSendRtp是会报 -500 找不到流的错误的。我需要有延时才能正常调用。这个有其它解决办法吗？

**Comment by xia-chu** [comment]
> 我需要有延时才能正常调用。这个有其它解决办法吗？
 因为开始接收推流 并不代表这个流能立马注册成功
需要流注册了 才能调用startSendRtp接口。
