### ISSUE TITLE
[技术咨询] vlc播放器拉zlm生成的FLV/TS/FMP4流过程中，暂停导致超时断开

### ISSUE THREAD

**Issue by zhangssk** [ZLMediaKit/ZLMediaKit#2557]
**咨询的功能模块**
- rtsp流推流到zlm,用vlc播放器拉zlm生成的FLV/TS/FMP4流

**咨询的具体内容和问题**
- 拉流播放过程中暂停，超过配置文件中设置的http链接超时时间keepAliveSecond，播放器连接会断开
   日志显示2023-06-15 17:44:02.152 W [MediaServer] [84859-event poller 0] HttpSession.cpp:105 onError | 67-28(10.50.12.57:6552) FLV/TS/FMP4播放器(__defaultVhost__/live/test)断开:socket send timeout,耗时(s):59
  请问是因为暂停后也在一直向socket发送缓存队列里写数据吗？能否在暂停后一直保持连接？谢谢

**Comment by xia-chu** [comment]
直播是不能暂停的 vlc暂停时 zlmediakit也是无感知的 
vlc只是停止了socket数据的读取 导致zlmediakit socket发送缓冲区溢出从而关闭socket了。
这是预期行为，就是这么设计的。

**Comment by zhangssk** [comment]
好的，非常感谢解答
