### ISSUE TITLE
[技术咨询] 使用VLC播放HLS流过程中，再使用ffplay播放http-ts流发现播播不了，HLS播放也断掉了

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2565]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

HLS和http-ts

**咨询的具体内容和问题**

我想通过ffplay播放 http-ts流 。在确定hls能播的过程中，用ffplay播放http-ts  发现ffplay播放不出来 一直卡住。vlc播放HLS直接退出了。

下面是我播放截图
HLS播放
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/28d2c0ff-c9f9-45d9-98dc-e2f6cebbe4c4)

ffplay   http-ts流后出现
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/a62873c7-11db-41a5-a8a4-81e827b5797b)

服务器配置
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/5654bd9f-f456-411a-b084-31efbdb0fa0a)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by zhang-chuanfeng** [comment]
> 404很明显就是流不存在啊

我先测试hls拉流播放是正常的 才来测试ts拉流的。在拉ts流没有拉到，影响到hls流播放了。hls停了

**Comment by xia-chu** [comment]
不会的 互不影响的

**Comment by zhang-chuanfeng** [comment]
> 不会的 互不影响的

我这边是国标RTP推流上来的，确实测试影响到hls了。正常播hls不会断掉的。
