### ISSUE TITLE
用addStreamProxy拉流代理填入rtsp地址，转协议之后的rtmp地址用vlc无法播放

### ISSUE THREAD

**Issue by bobin168** [ZLMediaKit/ZLMediaKit#2566]
**咨询的功能模块**
- 用addStreamProxy拉流代理填入rtsp地址，转协议之后的rtmp地址用vlc无法播放，提示无法连接，zlmediakit服务器也安装了nginx和nginx-rtmp-module模块并启动成功。

**Comment by xia-chu** [comment]
说明你端口错误

**Comment by bobin168** [comment]
http-flv格式的可以播，但是rtmp无法播，端口用的1935没错

**Comment by bobin168** [comment]
> 说明你端口错误

http-flv格式的可以播，但是rtmp无法播，端口用的1935没错
