### ISSUE TITLE
通过webrtc去zlm拉流的时候，zlm支持AAC的音频格式转发吗（webrtc已经支持AAC了）

### ISSUE THREAD

**Issue by coderWu1990** [ZLMediaKit/ZLMediaKit#2567]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by mtdxc** [comment]
哪个webrtc支持aac音频了，是自己魔改的么？

**Comment by coderWu1990** [comment]
> 
是自己改的。现在走webrtc拉流，音频协商是走的aac，但是没有aac的数据包过来

**Comment by mtdxc** [comment]
那你得确认下是zlm没转发数据包；还是转发了，被webrtc框架给丢了。两边都打打日志看下吧。
aac需要一个配置字段，这应该是在sdp中传输的，rtp好像没位置放这东西，你魔改的webrtc有解析么？

**Comment by xia-chu** [comment]
mpeg4-generic就是aac

**Comment by xia-chu** [comment]
看下zlmediakit回复的sdp

**Comment by coderWu1990** [comment]
服务器打印到这了：WebRtcTransport.cpp:874 createRtpChannel | create rtp receiver of ssrc:4000389824, rid:, codec:AAC

**Comment by xia-chu** [comment]
按照rtsp的习惯 这里应该叫mpeg4-generic 而不是aac
<img width="910" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/c7c0b9df-d845-4405-a645-4b2cb20669c8">

**Comment by ayw** [comment]
@coderWu1990  大佬魔改的webrtc 代码可以参考一下吗？
