### ISSUE TITLE
[技术咨询] 拉流重试时间间隔

### ISSUE THREAD

**Issue by zhaohuangmin** [ZLMediaKit/ZLMediaKit#2568]
**咨询的功能模块**
- /index/api/addStreamProxy拉流代理

**咨询的具体内容和问题**
- 此/index/api/addStreamProxy这个接口每一次拉流重试的的时间间隔是多少可以调整吗

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
不能调整 这个间隔不是固定的 是跟重试次数相关的

**Comment by pubpy2015** [comment]
Hi,

I also have a problem here.

![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/da702b34-7c90-436f-9f4f-a1c04e119fe4)

Because the connection to the camera is unstable, MediaServer will try to reconnect to the camera's rtsp source when the connection is lost, but sometimes, the connection is not lost, only the ping response time increases to 4-20 ms, VLC is still playing fine but MediaServer is still trying to reconnect to the camera.

Can I modify the condition to reconnect to the camera, e.g. 30 frames dropped continuously or frames dropped for xxx seconds?

**Comment by xia-chu** [comment]
> MediaServer will try to reconnect to the camera's rtsp source when the connection is lost, but sometimes, the connection is not lost, only the ping response time increases to 4-20 ms, VLC is still playing fine but MediaServer is still trying to reconnect to the camera.
> 
> Can I modify the condition to reconnect to the camera, e.g. 30 frames dropped continuously or frames dropped for xxx seconds?

Here is setting of `rtp packet recv timeout`
https://github.com/ZLMediaKit/ZLMediaKit/blob/master/src/Player/PlayerBase.cpp#LL72C1-L72C60

**Comment by pubpy2015** [comment]
Thank,

I will try increase both kTimeoutMS and kMediaTimeoutMS:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/957c34fa-04de-4dd8-a120-7cc914615784)

**Comment by pubpy2015** [comment]
My problem still exist. Media Server still reconnect to camera after "receive rtp timeout" (while VLC work fine).
Can you give me advice for debugging?

**Comment by xia-chu** [comment]
> My problem still exist. Media Server still reconnect to camera after "receive rtp timeout" (while VLC work fine). Can you give me advice for debugging?

You can use wireshark/tcpdump to debug whether  had zlmediakit received rtp packet

**Comment by pubpy2015** [comment]
Hi,

Affter first "receive rtp timeout" message, if prevent reconnect by:
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/6a79551c-4091-491b-9d14-b3cfc2846cf9)
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/79c79173-2f92-4c3d-94e8-585e576a2b74)

media server can't receive any more packets.
this is screenshot from wireshark 
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/2ea58522-6ede-4a5f-ac39-765578cbc0ce)

Can you remote to my Windows Laptop by teamviewer ?

**Comment by pubpy2015** [comment]
I am trying your last code, problem still exist,
Why in the log, there is a "success" event before "receive rtp timeout" event ?
![ảnh](https://github.com/ZLMediaKit/ZLMediaKit/assets/59004953/8b610da7-2c9a-4409-a4b3-3fc0424f5eff)

**Comment by xia-chu** [comment]
Hi, `success` mean that, zlmediakit had rtsp handshark success with camera.
And then zlmediakit receive rtp timeout from camera.
