### ISSUE TITLE
[技术咨询] wvp整合zlm播放webrtc格式视频失败，播放其它格式正常

### ISSUE THREAD

**Issue by fanfanertan** [ZLMediaKit/ZLMediaKit#2577]
**咨询的功能模块**
- 播放webrtc格式视频

**咨询的具体内容和问题**
- wvp整合zlm播放webrtc格式视频失败，播放其它格式正常，zlm使用的是github上提供的docker镜像
- 具体报错如下
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/32301941/55913d0d-dc3a-48e0-af4c-df9b09218e02)

**Comment by xia-chu** [comment]
请查看下[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97) QA部分

**Comment by fanfanertan** [comment]
thanks，后来发现功能是好的，是视频加载的时间有些长，我误以为没有播放失败了

**Comment by xia-chu** [comment]
加载长可能没收到关键帧？
