### ISSUE TITLE
[技术咨询] 请问如何从内存中接受数据

### ISSUE THREAD

**Issue by vaptu** [ZLMediaKit/ZLMediaKit#2580]
**咨询的功能模块**
- MediaSource相关功能

**咨询的具体内容和问题**
- 我在尝试将内存中的MP4编码数据发送至ZLMediaKit进行解包并推流。我发现默认支持的协议均为网络协议(rtmp/rtsp...)。请问用什么途径可以实现通过文件句柄或者pipe来接收内存中的数据吗

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
目前zlmediakit的播放器支持rtsp/rtmp/hls/http-ts/http-flv, http-fmp4目前还不支持呢。
你可以先把mp4解复用为帧数据 然后输入给zlmediakit处理。

**Comment by vaptu** [comment]
好的，感谢
