### ISSUE TITLE
[技术咨询] rtp先拉流后推流机制导致推流首帧画面延迟问题

### ISSUE THREAD

**Issue by huliyan** [ZLMediaKit/ZLMediaKit#2584]
**咨询的功能模块**
- rtp先拉流后推流机制导致推流首帧画面延迟问题

**咨询的具体内容和问题**
具体调用过程：
1、调用openRtpServer接口，启动zlm收流
2、等待收到推流端的ps码流后hook返回stream注册成功后，调用startSendRtp或者startSendRtpPassive开始推流（未注册调用接口推流，会导致接口调用返回-500或-300错误）
3、推流开始后，zlm需要等待下一个i帧才能往外推流，导致存在一个gop的延迟（大概2s），如果多级zlm级联，会导致较大延迟

**注意事项**
请各位大神帮忙分析下，gb先注册后推流机制如何优化首帧延迟问题

**Comment by zhang2349** [comment]
最新版本好像支持缓存GOP了 会直接从上个i帧开始发

**Comment by xia-chu** [comment]
> 最新版本好像支持缓存GOP了 会直接从上个i帧开始发 [978143c](https://github.com/ZLMediaKit/ZLMediaKit/commit/978143c86db1d393049c056576ba33ae1cf2ca6a)

正解 startSendRtp接口已经支持gop缓存了

**Comment by huliyan** [comment]
> > 最新版本好像支持缓存GOP了 会直接从上个i帧开始发 [978143c](https://github.com/ZLMediaKit/ZLMediaKit/commit/978143c86db1d393049c056576ba33ae1cf2ca6a)
> 
> 正解 startSendRtp接口已经支持gop缓存了

非常感谢@xia-chu，感谢各位大佬，我们拉版本测下
