### ISSUE TITLE
[功能请求] 希望增加on_server_exited webhook通知

### ISSUE THREAD

**Issue by pedoc** [ZLMediaKit/ZLMediaKit#2585]
**描述该功能的用处，可以提供相关资料描述该功能**
如果ZLMediaKit正常退出(比如Ctrl+C终止而不是coredump等没有控制权的时候),触发对on_server_exited webhook的调用(如果没有设置则忽略)

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
当前我们可以同时启动多个ZLM实例并利用on_server_started事件感知到实例上线,从而能够自行在后端管理这些实例并提供负载均衡的能力.当前端调用接口时,我们会先从已注册实例集合中找到可用的实例,然后和此实例的API进行交互.
此时,如果有ZLM实例退出(正常退出),我们只能利用keeplive超时来判定.这会在至少一个keeplive超时周期内,让其他api拿到不可用的ZLM实例.
我们希望ZLM能够在正常退出时,即时主动通知后端,这样就可以实时的从已注册实例中移除,从而尽可能避免ZLM不可用的问题.
当前,我们可以将keeplive的周期设置为1s一次,这样可以在1s的周期内感知到ZLM超时,但是这样对资源的浪费比较严重.

**描述你期望实现该功能的方式和最终效果**
和on_server_started事件类似,在进程退出的时候,触发对on_server_exited webhook的调用.

**补充**
如果能够在异常退出的情况下(比如kill -9),也能通知的话那就最好了,但是这个可能很难实现(watchdog?).
在Windows下,如果在进程正常运行时用户进行关机动作,好像可以收到关机通知,linux下我不太了解.如果可以对这种情况也做一个处理,那就更加完善了.

**Comment by pedoc** [comment]
作为补充,好像配置文件中的``http.keepAliveSecond``并不是``hook.on_server_keepalive``的周期,看起来目前还无法配置``hook.on_server_keepalive``周期?

**Comment by zhang2349** [comment]
间隔是hook.alive_interval 但好像只有启动时候读取 不能通过api修改生效

**Comment by pedoc** [comment]
> 间隔是hook.alive_interval 但好像只有启动时候读取 不能通过api修改生效

感谢提醒,的确存在此配置

**Comment by xia-chu** [comment]
> 好像只有启动时候读取 不能通过api修改生效

这个不支持热加载 因为定时器已经创建好了
