### ISSUE TITLE
[BUG]vlc拉zlmediakit转出来的http-fmp4流，音频和视频都只能播放其中一个，其他类型流音视频正常

### ISSUE THREAD

**Issue by daimalvtu** [ZLMediaKit/ZLMediaKit#2586]
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by daimalvtu** [comment]
将发送的fmp4存储下来发现每个moof里面只有一帧数据，如何实现moof里面能添加多个traf和多帧数据

**Comment by xiongguangjie** [comment]
现在ZLM只支持一个音频，一个视频的模式，不支持多个音频或者多个视频的模式
