### ISSUE TITLE
mp4_max_second=3600   不起作用的原因

### ISSUE THREAD

**Issue by Dadong-88** [ZLMediaKit/ZLMediaKit#2587]
**咨询的功能模块**
mp4_max_second=3600 

**咨询的具体内容和问题**
mp4_max_second=3600   
为什么保存的录像都是  24s  而不是3600.  可能的原因有哪些

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
可能流中途断了

**Comment by Dadong-88** [comment]
假如流断了   也不能24s断一次  这么有规律呀   我没想通哪点有问题    难道跟设备有关？

**Comment by xia-chu** [comment]
> 能24s断一次 这么有规律呀 我没想通哪点有问题 难道跟设备有

需要分析zlmediakit日志

**Comment by Dadong-88** [comment]
好像又好了。。。  感谢
