### ISSUE TITLE
/index/api/openRtpServer请求报错

### ISSUE THREAD

**Issue by guanxiangkai** [ZLMediaKit/ZLMediaKit#2596]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/85926080/500ece60-26fd-4a29-9be9-3dcce4e881fe)

**Comment by pedoc** [comment]
这提示不是写了缺少参数吗

**Comment by guanxiangkai** [comment]
是的，我没注意到，现在已经改好了。不过我是按照文档写的接口
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/85926080/7b61346a-5614-40a2-9d12-76c002c0b346)

**Comment by pedoc** [comment]
> 不过我是按照文档写的接口

文档这里也都是标记为Y(必选)的

**Comment by pedoc** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6604230/32ad5347-5aeb-42f1-b51e-b7294c05a88d)
代码在此处,这个enable_tcp是为了兼容老版本的,新版还是用tcp_mode

**Comment by guanxiangkai** [comment]
好的，明白了，谢谢
