### ISSUE TITLE
【功能请求】config.ini中的配置，能否支持通过环境变量设置？

### ISSUE THREAD

**Issue by itouxin** [ZLMediaKit/ZLMediaKit#2597]
如果可以通过环境变量设置config.ini中的任何配置，可以方便docker或者k8s等容器的快速部署，不需要每次去修改ini文件。

**Comment by monktan89** [comment]
docker或者k8s最好用configmap挂载的方式来处理配置文件

**Comment by ada-hou** [comment]
可以启动一个任务脚本去根据实际环境修改配置
/index/api/setServerConfig
