### ISSUE TITLE
[功能请求] rtsp点播音频文件(wav、mp3等格式)功能

### ISSUE THREAD

**Issue by qq93420999** [ZLMediaKit/ZLMediaKit#2599]
**通过rtsp点播服务器上存储的音频文件，包含常见的音频格式如wav、mp3等**

**该功能是否用于改进项目缺陷，如果是，目前项目可以通过http进行录音点播,但是存在需要将文件下载后才能进行播放，当录音文件较大时，点播的效果并不好；另客户管理者不想让语音文件通过http方式轻易被前端人员下载到**

**系统可以通过rtsp请求点播服务器上存储的音频文件，支持常规的暂停，停止，拖拽等操作**

**Comment by xia-chu** [comment]
这个不打算支持 如果能收到pr 倒是乐意合并下
