### ISSUE TITLE
[技术咨询] zlMedia使用webrtc获取数据流里SEI数据

### ISSUE THREAD

**Issue by wuyuxi** [ZLMediaKit/ZLMediaKit#2601]
使用webrtc获取数据流里的SEI用户信息数据的时候，没有获取到，应该如何获取呢

**Comment by xiongguangjie** [comment]
只能通过rtc 之类的sdk，如metaRtc 谷歌的rtc 实现，来提取，而且很可能需要二次开发，web端的rtc 是没有提供这种接口的

**Comment by wuyuxi** [comment]
> 

RTCRtpReceiver.getReceivers.getContributingSources()和RTCRtpReceiver.getParameters()这两个方法好像可以获取到SEI数据，但是zlmedia在做分发的时候，webrtc的我抓包没有收到SEI数据，flv的抓包收到了SEI数据

**Comment by xiongguangjie** [comment]
> > 
> 
> RTCRtpReceiver.getReceivers.getContributingSources()和RTCRtpReceiver.getParameters()这两个方法好像可以获取到SEI数据，但是zlmedia在做分发的时候，webrtc的我抓包没有收到SEI数据，flv的抓包收到了SEI数据
这两个方法无法获取码流，rtc有srtp加密的，你是无法知道nal类型的

**Comment by wuyuxi** [comment]
> 

哦哦，那如果视频流每帧都有数据需要我去取，webrtc可以用什么方式取吗？

**Comment by wuyuxi** [comment]
> 这两个方法无法获取码流，rtc有srtp加密的，你是无法知道nal类型的

那如果我需要获取到sei数据需要使用到编解码器吗

**Comment by xiongguangjie** [comment]
说了只能使用C++的方式二次开发
