### ISSUE TITLE
How to get a fragment in jpeg

### ISSUE THREAD

**Issue by TheMadius** [ZLMediaKit/ZLMediaKit#2606]
Hi, there is a need to get a preview for it from a stream so it can be displayed on the web. Is it possible to get a jpeg image from Frame::Ptr &frame?

**Comment by urmyfaith** [comment]
see https://github.com/ZLMediaKit/ZLMediaKit/blob/master/server/WebApi.cpp#L1553

**Comment by TheMadius** [comment]
Thanks.
From the example it has a method to return the file '.jpeg'. I know how to return it, the question is more about how to get a fragment from the stream in jpeg format.
Namely whether the 'Frame::Ptr frame' object can be converted to jpeg format.

**Comment by TheMadius** [comment]
Thanks.
Didn't notice makeSnap
