### ISSUE TITLE
可以实现批量推拉流吗 ？

### ISSUE THREAD

**Issue by boyup6** [ZLMediaKit/ZLMediaKit#2608]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个需要二次开发 可以从数据库或配置文件导入流。
http api不支持批量 因为批量不好返回结果啊。

**Comment by boyup6** [comment]
> 这个需要二次开发 可以从数据库或配置文件导入流。 http api不支持批量 因为批量不好返回结果啊。
那可以实现批量操作设备吗

**Comment by boyup6** [comment]
还有个问题  我添加设备之后显示添加成功，但是调设备列表是空  数据库里有数据

**Comment by boyup6** [comment]
好的好的    操作设备也是wvp那边的事吗？

**Comment by xia-chu** [comment]
对
