### ISSUE TITLE
在线http url拉流代理 

### ISSUE THREAD

**Issue by lironghai** [ZLMediaKit/ZLMediaKit#2613]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- 在线http url拉流代理 

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

使用在线的http地址进行拉流代理，日志显示不支持，是我拉取的不是最新代码还是真的不支持。在线的url是可以正常访问播放的

PlayerProxy.cpp:176 play | not supported play schema:http://192.168.10.254:9000/pvlc-record-2022-03-30-11h16m24s-rtsp___openUrl_YyEeNe8-.mp4

**Comment by xia-chu** [comment]
目前zlmediakit的addStreamProxy接口不支持http-mp4拉流 你可以用addFFmpegSource接口拉
