### ISSUE TITLE
[技术咨询] 奇怪的fmp4 end of file问题

### ISSUE THREAD

**Issue by mopooo** [ZLMediaKit/ZLMediaKit#2615]
**咨询的功能模块**
- fmp4拉流播放

**咨询的具体内容和问题**
- zl从上游的相机rtsp拉实时流，然后浏览器端从zl进行fmp4拉流播放，但是播放一段时间（几分钟到几小时甚至十几小时不等）后，会出现两次end of file错误，然后播放中断无法恢复，相关日志如下：

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6480394/f5b74497-4292-48a0-9d43-f71542a94382)

浏览器端的player是video-react（基于video.js），从chrome日志来看第一次连接（正常播放）持续时间是几分钟到几小时，第二次一般只有几百毫秒，但是server返回都是http 200，看起来好像是player请求了一下数据后就关闭了连接，但不确定是怎么触发的，是否和zl有关联，请问这种情况大概是什么原因？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
从zlmediakit日志看是播放器主动断开的 播放器为什么端口要看播放器日志

**Comment by mopooo** [comment]
> 从zlmediakit日志看是播放器主动断开的 播放器为什么端口要看播放器日志

因为有时候播放几个小时才会出现，chrome的devtools会卡死，偶尔没卡死的只能看network和timing的信息，media的信息不知道为啥看不了，另外需要打开video.js或者video-react的debug选项之类吗？还是有比较通用的debug日志？多谢

**Comment by xia-chu** [comment]
播放这快我不熟悉 你可以同时结合ffplay播放测试

**Comment by mopooo** [comment]
抓了一下chrome media的日志，好像有audio decoding的报错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6480394/8c84ba53-d942-48e3-bfe5-1811456a76c6)

**Comment by mopooo** [comment]
> 播放器这快我不熟悉 你可以同时结合ffplay播放测试

@xia-chu 更新一下观测情况，先是试着关闭了音频输出，发现会出现更多的播放中断，于是切回来了。
然后昨天长测时发现一个有趣的现象，就是如果用vlc同时播放同一个mp4地址时，浏览器里的播放也不会中断了，从zlm的日志来看连续两次end of file的log仍然存在，但好像可以续命续上了，不会导致zlm端等待20秒后触发无人观看事件销毁。

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6480394/f321436d-a3ea-4918-9112-94e1e7c61760)

虽然vlc更稳定，保持了连接，但无人观看的超时有20秒，即便只有浏览器端播放，为什么就没有自动续上呢？另外昨天单独测浏览器播放的时候，发现时间长了会出现明显的延迟（对比vlc慢1秒多），可能夜晚的时候自动追上来了，那这个连续end of file有没有可能是delay超标导致player尝试去追进度，然后超过了20秒？

**Comment by xia-chu** [comment]
ring buffer detached是流注销导致的主动端口事件

**Comment by mopooo** [comment]
> ring buffer detached是流注销导致的主动端口事件

确实，刚才发现了上游rtsp断连的log
