### ISSUE TITLE
/index/api/setRecordSpeed   接口一直返回 set failed

### ISSUE THREAD

**Issue by hoheyho** [ZLMediaKit/ZLMediaKit#2618]
/index/api/setRecordSpeed   接口文档上没有详细说明，
调用的时候，
一直返回：
{
    "code": -1,
    "msg": "set failed",
    "result": -1
}

请问下这是因为什么呢？

**Comment by xiongguangjie** [comment]
有这个接口？？？？

**Comment by hoheyho** [comment]
请求参数是：
![e100a10d915461be53fd35e92d8fb15](https://github.com/ZLMediaKit/ZLMediaKit/assets/55080154/e2d6b363-da47-4314-8351-dc35d79ef3e1)

**Comment by xiongguangjie** [comment]
> 请求参数是： ![e100a10d915461be53fd35e92d8fb15](https://user-images.githubusercontent.com/55080154/251086524-e2d6b363-da47-4314-8351-dc35d79ef3e1.png)

ZLM日志报什么错误

**Comment by hoheyho** [comment]
ZLM没有报错信息
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/55080154/f3381c04-7424-496d-8c37-f46adfce7938)



> > 请求参数是： ![e100a10d915461be53fd35e92d8fb15](https://user-images.githubusercontent.com/55080154/251086524-e2d6b363-da47-4314-8351-dc35d79ef3e1.png)
> 
> ZLM日志报什么错误

**Comment by xiongguangjie** [comment]
你这个不是录像的rtsp流，就无法使用这个功能

**Comment by hoheyho** [comment]
> rtsp流，

录像的rtsp 具体是指？？ 我看这个就是录像的啊？
还请指教 

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/55080154/6267239c-970f-4017-b34c-11532d85586e)

**Comment by xiongguangjie** [comment]
> > rtsp流，
> 
> 录像的rtsp 具体是指？？ 我看这个就是录像的啊？ 还望指教，非常感谢
> 
> ![image](https://user-images.githubusercontent.com/55080154/251091824-6267239c-970f-4017-b34c-11532d85586e.png)

这个是指zlm的mp4 录像文件，如果你想通过flv倍数播放，就需要用到这个接口

**Comment by xiongguangjie** [comment]
你这个是国标录像，需要你信令控制就可以了

**Comment by hoheyho** [comment]
> 你这个是国标录像，需要你信令控制就可以了

**Comment by hoheyho** [comment]
> 



> 你这个是国标录像，需要你信令控制就可以了

发信令就是指，直接给nvr盒子发送指令对吧？ 不需要通过ZLMediaKit  对吧？

**Comment by xiongguangjie** [comment]
> > 
> 
> > 你这个是国标录像，需要你信令控制就可以了
> 
> 发信令就是指，直接给nvr盒子发送指令对吧？ 不需要通过ZLMediaKit 对吧？

是的，国标信令，我看你是通过国标来接的

**Comment by xia-chu** [comment]
setRecordSpeed接口只对mp4点播流有效
