### ISSUE TITLE
RTSP 拉流当rtsp地址参数中有-的时候不能解析RTSP 

### ISSUE THREAD

**Issue by 981030048** [ZLMediaKit/ZLMediaKit#2619]
成功解析：
rtsp://203.195.93.125:9003/0c9e5fdf3df247c6ecc75d2e74ac706e/0_0?signid=7f43686dea1d37b986993bafc1074b81ac2e172d9ab3f372115f70dbb8dce3db1615fa4e6ef4156f5cc442cb188cb315&reqid=beac0c7992d648a79188dae369be096d
失败解析：
rtsp://203.2.167.27:10003/3TPCA444448CPAW_0?key=2f7a7bcb6ae8ec88341254b57fed5a4a&tk=3c476089-046c-4ddd-871a-ab27004dc74c&appId=8854786247&reqId=e28152eee99c4f09aeb626ee86efdff1
失败日志 后面的参数无法获取
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33341618/0c32c45c-9a1f-40f2-9d17-ece774f7db24)

**Comment by xiongguangjie** [comment]
我看看

**Comment by 981030048** [comment]
> &后的参数全部丢失 请求地址/index/api/addStreamProxy

**Comment by xiongguangjie** [comment]
![@)9FYQ07JHF7{ EF3%9SRYI](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/02d809b4-3bae-46ef-895c-acc66b90abf4)
这个不是正常的吗打印日志，携带了你传入的全部参数
![)KXAZFV$I5AMDYMPT@UJ39N](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/0b6a891d-ca0a-4426-a200-178f3f838d2e)
如上调用

**Comment by xiongguangjie** [comment]
你这个url作为参数传入需要做转义

**Comment by 981030048** [comment]
> 哦哦 感谢 懵逼了
