### ISSUE TITLE
[技术咨询] 使用固定单端口10000推流，可以自定义播放的streamId吗

### ISSUE THREAD

**Issue by kelpliu** [ZLMediaKit/ZLMediaKit#2621]
**咨询的具体内容和问题**
- 当ZLM开启多端口模式，使用下面的接口可以开启推流端口，并指定该推流端口的streamId,然后使用此id可以播放流
  `{{ZLMediaKit_URL}}/index/api/openRtpServer?secret={{ZLMediaKit_secret}}&port=0&tcp_mode=1&stream_id=test`
- 如果使用固定的10000端口推流，streamId是**随机的16进制数**。 
- 我想咨询的是，使用单端口模式推流，可以自定义推流的streamId吗？因为我想使用单端口点播多个设备，并返回拉流地址

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个你指定ssrc 就可以了

**Comment by xia-chu** [comment]
单端口模式 使用ssrc作为stream_id 没法自定义，除非做个stream_id的映射才行

**Comment by kelpliu** [comment]
非常感谢大佬们的解答，感恩。那我用ssrc好了
