### ISSUE TITLE
[BUG] linux下ffmpeg通过协议 rstp 推流 摄像头的mjpeg输出， obs拉取的时候是绿屏

### ISSUE THREAD

**Issue by geekli** [ZLMediaKit/ZLMediaKit#2622]
### 现象描述
linux下ffmpeg通过协议 rstp 推流 摄像头的mjpeg输出， obs拉取的时候是绿屏

### 如何复现?
linux下 使用罗技摄像头C925E，
1. 执行命令
`ffmpeg -hide_banner -f video4linux2  -input_format mjpeg -i /dev/video1 -c:v copy  -f rtsp -rtsp_transport tcp rtsp://live.myserver.cn:8554/live/test `

2. 打开OBS 创建媒体源，输入地址rtsp://live.myserver.cn:8554/live/test

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
ffmpeg -hide_banner -f video4linux2  -input_format mjpeg -i /dev/video1 -c:v copy  -f rtsp -rtsp_transport tcp rtsp://live.xxxx.cn:8554/live/test
Input #0, video4linux2,v4l2, from '/dev/video1':
  Duration: N/A, start: 11213297.551965, bitrate: N/A
    Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
Output #0, rtsp, to 'rtsp://live.xxxx.cn:8554/live/test':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 640x480, q=2-31, 30 fps, 30 tbr, 90k tbn, 1000k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
Press [q] to stop, [?] for help
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided
    Last message repeated 22 times
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided=1.44x
    Last message repeated 14 times
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided=1.22x
    Last message repeated 15 times
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided=1.16x
    Last message repeated 14 times
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided=1.12x
    Last message repeated 14 times
[rtp @ 0xcb5f90] RFC 2435 suggests two quantization tables, 3 provided=1.09x
    Last message repeated 6 times
frame=   91 fps= 33 q=-1.0 Lsize=N/A time=00:00:02.99 bitrate=N/A speed=1.08x

</pre>
</details>

<details>
<summary>zlmediakit 服务端 日志</summary>
<pre>

media-zlmediakit-1  | 2023-07-05 18:08:53.458 T [MediaServer] [7-event poller 1] RtspSession.cpp:408 onAuthSuccess | 231-68(218.xx.xx.17:4939)
media-zlmediakit-1  | 2023-07-05 18:08:55.577 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 229-48(218.xx.xx.17:4931) RTSP播放器(__defaultVhost__/live/test)断开:no such stream:__defaultVhost__/live/test,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:08:55.577 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 229-48(218.xx.xx.17:4931)
media-zlmediakit-1  | 2023-07-05 18:08:58.095 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 230-50(218.xx.xx.17:4934) RTSP播放器(__defaultVhost__/stream51/)断开:no such stream:__defaultVhost__/stream51/,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:08:58.095 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 230-50(218.xx.xx.17:4934)
media-zlmediakit-1  | 2023-07-05 18:09:03.131 D [MediaServer] [7-event poller 1] RtspSession.cpp:55 RtspSession | 232-48(218.xx.xx.17:13906)
media-zlmediakit-1  | 2023-07-05 18:09:03.144 T [MediaServer] [7-event poller 1] RtspSession.cpp:408 onAuthSuccess | 232-48(218.xx.xx.17:13906)
media-zlmediakit-1  | 2023-07-05 18:09:05.629 D [MediaServer] [7-event poller 1] RtspSession.cpp:55 RtspSession | 233-50(218.xx.xx.17:13908)
media-zlmediakit-1  | 2023-07-05 18:09:05.639 T [MediaServer] [7-event poller 1] RtspSession.cpp:408 onAuthSuccess | 233-50(218.xx.xx.17:13908)
media-zlmediakit-1  | 2023-07-05 18:09:08.459 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 231-68(218.xx.xx.17:4939) RTSP播放器(__defaultVhost__/stream52/)断开:no such stream:__defaultVhost__/stream52/,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:09:08.459 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 231-68(218.xx.xx.17:4939)
media-zlmediakit-1  | 2023-07-05 18:09:18.146 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 232-48(218.xx.xx.17:13906) RTSP播放器(__defaultVhost__/stream51/)断开:no such stream:__defaultVhost__/stream51/,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:09:18.146 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 232-48(218.xx.xx.17:13906)
media-zlmediakit-1  | 2023-07-05 18:09:18.484 D [MediaServer] [7-event poller 1] RtspSession.cpp:55 RtspSession | 234-48(218.xx.xx.17:2775)
media-zlmediakit-1  | 2023-07-05 18:09:18.492 T [MediaServer] [7-event poller 1] RtspSession.cpp:408 onAuthSuccess | 234-48(218.xx.xx.17:2775)
media-zlmediakit-1  | 2023-07-05 18:09:20.641 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 233-50(218.xx.xx.17:13908) RTSP播放器(__defaultVhost__/live/test)断开:no such stream:__defaultVhost__/live/test,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:09:20.641 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 233-50(218.xx.xx.17:13908)
media-zlmediakit-1  | 2023-07-05 18:09:23.182 D [MediaServer] [7-event poller 1] RtspSession.cpp:55 RtspSession | 235-50(218.xx.xx.17:2780)
media-zlmediakit-1  | 2023-07-05 18:09:23.192 T [MediaServer] [7-event poller 1] RtspSession.cpp:408 onAuthSuccess | 235-50(218.xx.xx.17:2780)
media-zlmediakit-1  | 2023-07-05 18:09:23.253 D [MediaServer] [7-event poller 1] RtspSession.cpp:55 RtspSession | 236-68(218.xx.xx.17:39402)
media-zlmediakit-1  | 2023-07-05 18:09:23.366 I [MediaServer] [7-event poller 1] MediaSource.cpp:525 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/test
media-zlmediakit-1  | 2023-07-05 18:09:23.572 W [MediaServer] [7-event poller 1] Factory.cpp:289 getRtmpCodecByTrack | 暂不支持该CodecId:JPEG
media-zlmediakit-1  | 2023-07-05 18:09:23.572 D [MediaServer] [7-event poller 1] MediaSink.cpp:149 emitAllTrackReady | All track ready use 248ms
media-zlmediakit-1  | 2023-07-05 18:09:23.572 T [MediaServer] [7-event poller 1] MediaSink.cpp:271 addMuteAudioTrack | Mute aac track added
media-zlmediakit-1  | 2023-07-05 18:09:23.572 I [MediaServer] [7-event poller 1] MediaSource.cpp:525 emitEvent | 媒体注册:fmp4://__defaultVhost__/live/test
media-zlmediakit-1  | 2023-07-05 18:09:23.572 I [MediaServer] [7-event poller 1] MultiMediaSourceMuxer.cpp:372 onAllTrackReady | stream: rtsp://live.xxxx.cn:8554/live/test , codec info: mpeg4-generic[8000/1/16] JPEG[640/480/31]
media-zlmediakit-1  | 2023-07-05 18:09:23.581 I [MediaServer] [7-event poller 1] MediaSource.cpp:525 emitEvent | 媒体注册:ts://__defaultVhost__/live/test
media-zlmediakit-1  | 2023-07-05 18:09:23.581 I [MediaServer] [7-event poller 1] MediaSource.cpp:525 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/test
media-zlmediakit-1  | 2023-07-05 18:09:30.681 D [MediaServer] [7-event poller 2] RtspSession.cpp:55 RtspSession | 237-69(218.xx.xx.17:2783)
media-zlmediakit-1  | 2023-07-05 18:09:30.702 T [MediaServer] [7-event poller 2] RtspSession.cpp:408 onAuthSuccess | 237-69(218.xx.xx.17:2783)
media-zlmediakit-1  | 2023-07-05 18:09:30.710 I [MediaServer] [7-event poller 2] Rtsp.cpp:393 getPortPair | got port from pool:30014-30015
media-zlmediakit-1  | 2023-07-05 18:09:30.718 I [MediaServer] [7-event poller 2] RtspSession.cpp:798 handleReq_Play | 237-69(218.xx.xx.17:2783) rtsp seekTo(ms):0
media-zlmediakit-1  | 2023-07-05 18:09:30.718 I [MediaServer] [7-event poller 2] RtspSession.cpp:828 handleReq_Play | 237-69(218.xx.xx.17:2783) 指定播放track:0
media-zlmediakit-1  | 2023-07-05 18:09:33.493 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 234-48(218.xx.xx.17:2775) RTSP播放器(__defaultVhost__/stream52/)断开:no such stream:__defaultVhost__/stream52/,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:09:33.493 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 234-48(218.xx.xx.17:2775)
media-zlmediakit-1  | 2023-07-05 18:09:38.193 W [MediaServer] [7-event poller 1] RtspSession.cpp:67 onError | 235-50(218.xx.xx.17:2780) RTSP播放器(__defaultVhost__/stream51/)断开:no such stream:__defaultVhost__/stream51/,耗时(s):15
media-zlmediakit-1  | 2023-07-05 18:09:38.193 D [MediaServer] [7-event poller 1] RtspSession.cpp:61 ~RtspSession | 235-50(218.xx.xx.17:2780)
media-zlmediakit-1  | 2023-07-05 18:09:43.216 D [MediaServer] [7-event poller 3] RtspSession.cpp:55 RtspSession | 238-48(218.xx.xx.17:2791)
media-zlmediakit-1  | 2023-07-05 18:09:43.222 T [MediaServer] [7-event poller 3] RtspSession.cpp:408 onAuthSuccess | 238-48(218.xx.xx.17:2791)
media-zlmediakit-1  | 2023-07-05 18:09:43.515 D [MediaServer] [7-event poller 3] RtspSession.cpp:55 RtspSession | 239-50(218.xx.xx.17:2792)
media-zlmediakit-1  | 2023-07-05 18:09:43.536 T [MediaServer] [7-event poller 3] RtspSession.cpp:408 onAuthSuccess | 239-50(218.xx.xx.17:2792)

 </pre>
</details>

### 配置

 
<details>
<summary>展开查看详细配置</summary>
<pre>
version: '2'
services:

  zlmediakit:
    image: zlmediakit/zlmediakit:master
    ports:
        - "1935:1935"
        - "8080:80"
        - "8443:443"
        - "8554:554"
        - "10000:10000"
        - "10000:10000/udp"
        - "8000:8000/udp"
        - "9000:9000/udp"
  wvp_pro:
    image: 648540858/wvp_pro
    ports:
        - "18080:18080"
        - "30000-30500:30000-30500/udp"
        - "30000-30500:30000-30500/tcp"
        - "8083:80"
        - "5060:5060"
        - "5060:5060/udp"
        - "554:554/udp"
        - "554:554"
    environment:
        - WVP_IP=192.168.2.98

    volumes:
        - ./record:/opt/media/www/record

</pre>
</details>

### 各种环境信息

<pre>
ffmpeg端
  硬件： 树莓派4b
  系统： Linux pi-xxx 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux
  ffmpeg版本： ffmpeg version 4.3.5-0+deb11u1+rpt3 Copyright (c) 2000-2022 the FFmpeg developers

服务端： zlmediakit 安装在docker环境下 
Ubuntu 22.04.2 LTS
docker 20.10.21
ZLMediaKit(git hash:950f33b/2023-03-17T02:04:00+08:00,branch:master,build time:2023-03-16T18:12:31)

</pre>

**Comment by geekli** [comment]
用ffplayer播放 也是绿屏，显示如下错误日志



```[mjpeg @ 000001c8ad3b4bc0] error dc
[mjpeg @ 000001c8ad3b4bc0] error y=0 x=10
[mjpeg @ 000001c8ad3b4bc0] mjpeg_decode_dc: bad vlc: 0:0 (000001c8ac649288)
[mjpeg @ 000001c8ad3b4bc0] error dc
[mjpeg @ 000001c8ad3b4bc0] error y=0 x=10
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 1 packets
[rtsp @ 000001c8a6353e00] Missing packets; dropping frame.
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 9 packets
[rtsp @ 000001c8a6353e00] Missing packets; dropping frame.
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 14 packets
[rtsp @ 000001c8a6353e00] Missing packets; dropping frame.
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 18 packets
[rtsp @ 000001c8a6353e00] Missing packets; dropping frame.
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 13 packets
[rtsp @ 000001c8a6353e00] Missing packets; dropping frame.
[rtsp @ 000001c8a6353e00] max delay reached. need to consume packet
[rtsp @ 000001c8a6353e00] RTP: missed 4 packets
[mjpeg @ 000001c8ad3b4bc0] mjpeg_decode_dc: bad vlc: 0:0 (000001c8ac649288)
[mjpeg @ 000001c8ad3b4bc0] error dc
[mjpeg @ 000001c8ad3b4bc0] error y=0 x=10
[mjpeg @ 000001c8ad3b4bc0] mjpeg_decode_dc: bad vlc: 0:0 (000001c8ac649288)
[mjpeg @ 000001c8ad3b4bc0] error dc
[mjpeg @ 000001c8ad3b4bc0] error y=0 x=10
[mjpeg @ 000001c8ad3b4bc0] mjpeg_decode_dc: bad vlc: 0:0 (000001c8ac649288)
[mjpeg @ 000001c8ad3b4bc0] error dc
[mjpeg @ 000001c8ad3b4bc0] error y=0 x=10
[mjpeg @ 000001c8ad3b4bc0] mjpeg_decode_dc: bad vlc: 0:0 (000001c8ac649288)
```

**Comment by xia-chu** [comment]
ffplay播放rtsp时请加上 -rtsp_transport tcp

**Comment by geekli** [comment]
> ffplay播放rtsp时请加上 -rtsp_transport tcp

添加后还是有问题，另外docker镜像也拉取了最新的版本

`ffplay.exe   -rtsp_transport tcp  rtsp://live.xxxx.cn:8554/live/test`


```
Input #0, rtsp, from 'rtsp://live.xxxx.cn:8554/live/test':f=0/0
  Metadata:
    title           : Streamed by ZLMediaKit(git hash:6b9889a/2023-07-02T12:45:07+08:00,branch:master,build time:2023-07-02T04:47:17)
  Duration: N/A, start: -1.515456, bitrate: N/A
  Stream #0:0: Video: mjpeg (Baseline), yuvj422p(pc, bt470bg/unknown/unknown), 1280x720 [SAR 1:1 DAR 16:9], 29.75 tbr, 90k tbn
[mjpeg @ 0000016943600e00] mjpeg_decode_dc: bad vlc: 0:0 (0000016943799fc8)
[mjpeg @ 0000016943600e00] error dc
[mjpeg @ 0000016943600e00] error y=0 x=10
[swscaler @ 000001694359dc40] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 1 times
[swscaler @ 00000169438aab00] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 1 times
[mjpeg @ 0000016943600e00] mjpeg_decode_dc: bad vlc: 0:0 (0000016943799fc8)
[mjpeg @ 0000016943600e00] error dc
[mjpeg @ 0000016943600e00] error y=0 x=10
[mjpeg @ 0000016943600e00] mjpeg_decode_dc: bad vlc: 0:0 (0000016943799fc8)
[mjpeg @ 0000016943600e00] error dc
[mjpeg @ 0000016943600e00] error y=0 x=10
[mjpeg @ 0000016943600e00] mjpeg_decode_dc: bad vlc: 0:0 (0000016943799fc8)
[mjpeg @ 0000016943600e00] error dc
[mjpeg @ 0000016943600e00] error y=0 x=10
[mjpeg @ 0000016943600e00] mjpeg_decode_dc: bad vlc: 0:0 (0000016943799fc8)
```

**Comment by geekli** [comment]
通过
```ffmpeg -hide_banner -f video4linux2 -input_format mjpeg -i /dev/video1 -c:v copy -t 10  -f mjpeg out.mjpeg```
录视频文件
```ffplayer out.mjpeg``` 可以正常播放

然后 
推流该视频文件到 ZLMediaKit
```ffmpeg -hide_banner -re  -i out.mjpeg  -c:v copy  -f rtsp -rtsp_transport tcp rtsp://live.xxxx.cn:8554/live/test ```
同时 
```ffplay.exe   -rtsp_transport tcp  rtsp://live.xxxx.cn:8554/live/test```  也是绿屏

**Comment by xia-chu** [comment]
你这样设置mjpeg的参数试试：`-vcodec mjpeg -pix_fmt yuv420p -color_range jpeg -huffman 0 -force_duplicated_matrix 1 `

**Comment by geekli** [comment]
@xia-chu  非常感谢 
现在手头没摄像头，用之前录得视频试了下，正常了。
`ffmpeg -hide_banner -re  -i out.mjpeg  -c:v copy -pix_fmt yuv420p -color_range jpeg -huffman 0 -force_duplicated_matrix 1 -f rtsp -rtsp_transport tcp rtsp://live.xxxx.cn:8554/live/test`

明天我在用摄像头试下

**Comment by kaikaimiao** [comment]
-c:v copy加了就不会绿屏了
