### ISSUE TITLE
RTSP 拉流转义后 不能请求到资源 但是通过VLC可以播放

### ISSUE THREAD

**Issue by 981030048** [ZLMediaKit/ZLMediaKit#2624]
RTSP拉流  RTSP中带有&符带参  需要对&转义 变成%26 通过index/api/addStreamProxy 请求
请求后 ZL日志打印反编译后的RTSP %26转回& 直接复制日志中的地址 VLC可以播放 
ZL 返回404
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33341618/dc0be6ba-8559-471c-b835-89560913eb47)
哪里处理的有问题吗
/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=spzm.shanxiszxc.com:12800/spzm&app=live&stream=3TPCA444448CPAW&url=rtsp://203.2.167.27:10003/3TPCA444448CPAW_0?key=2f7a7bcb6ae8ec88341254b57fed5a4a%26tk=8e5d8b5d-2865-478b-9440-ba47fbfe5dfb%26appId=8854786247%26reqId=9e4b654c6fcf4db7b19d9ba3e43d90ae

**Comment by xiongguangjie** [comment]
肯定有问题呀，你用postman 去试，看它是如何转义的

**Comment by 981030048** [comment]
> 肯定有问题呀，你用postman 去试，看它是如何转义的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33341618/b7618bbe-8b30-46fb-abfe-8b69cb51bddb)
我在使用POSTMAN的转义后还是存在问题
rtsp://203.2.167.27:10003/3TPCA444448CPAW_0?key=2f7a7bcb6ae8ec88341254b57fed5a4a&tk=6d4f593e-7a51-4a56-936c-a861a932d20f&appId=8854786247&reqId=3b437a2af795400284181ba0431e5078
能测试下吗 20分钟有效
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33341618/ef4f35aa-45a4-43a2-9573-21a0f0e15c50)

**Comment by xiongguangjie** [comment]
postman 会自动给你转义的，你直接把能播放的地址贴上去就行了，然后看看postman 给出的等价curl 命令参数是怎么写的

**Comment by 981030048** [comment]
> postman 会自动给你转义的，你直接把能播放的地址贴上去就行了，然后看看postman 给出的等价curl 命令参数是怎么写的
播放地址放上去 不能直接使用 会有&参数丢失的问题 昨天你让我编译URL
你看POSTMAN图中的地址 已经是编译后的 请求到ZL之后 也能正常反编译 但是请求到的是404 我直接复制ZL日志中的地址 放到VLC能播放 昨天修改RTSP中的cpp直接 写死地址 也是404

**Comment by 981030048** [comment]
> postman 会自动给你转义的，你直接把能播放的地址贴上去就行了，然后看看postman 给出的等价curl 命令参数是怎么写的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33341618/f35ff099-5e3f-490f-83a5-1f1408fd8dcf)

**Comment by xia-chu** [comment]
这是zlm的bug，请打上补丁：
```patch
Index: src/Rtsp/RtspPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
--- a/src/Rtsp/RtspPlayer.cpp	(revision 6b9889a883a91d7ba906f44f3c5288311dc883a4)
+++ b/src/Rtsp/RtspPlayer.cpp	(date 1688614578481)
@@ -451,7 +451,7 @@
             case type_pause: WarnL << "Pause failed:" << parser.status() << " " << parser.statusStr(); break;
             case type_play:
                 WarnL << "Play failed:" << parser.status() << " " << parser.statusStr();
-                onPlayResult_l(SockException(Err_shutdown, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
+                onPlayResult_l(SockException(Err_other, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
                 break;
             case type_seek: WarnL << "Seek failed:" << parser.status() << " " << parser.statusStr(); break;
         }
@@ -502,9 +502,8 @@
         if (trackIdx == -1) {
             return;
         }
-        handleOneRtp(
-            trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate, (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize,
-            len - RtpPacket::kRtpTcpHeaderSize);
+        handleOneRtp(trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate,
+                     (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize, len - RtpPacket::kRtpTcpHeaderSize);
     } else {
         trackIdx = getTrackIndexByInterleaved(interleaved - 1);
         if (trackIdx == -1) {
@@ -615,11 +614,7 @@
     }
 
     _StrPrinter printer;
-    if (cmd == "PLAY") {
-        printer << cmd << " " << _play_url << " RTSP/1.0\r\n";
-    } else {
-        printer << cmd << " " << url << " RTSP/1.0\r\n";
-    }
+    printer << cmd << " " << url << " RTSP/1.0\r\n";
 
     for (auto &pr : header) {
         printer << pr.first << ": " << pr.second << "\r\n";
@@ -743,7 +738,7 @@
     if (_sdp_track.size() == 1) {
         return 0;
     }
-    throw SockException(Err_shutdown, StrPrinter << "no such track with type:" << getTrackString(track_type));
+    throw SockException(Err_other, StrPrinter << "no such track with type:" << getTrackString(track_type));
 }
 
 ///////////////////////////////////////////////////
```

**Comment by 981030048** [comment]
感谢 问题已经解决了

**Comment by xiongguangjie** [comment]
> 这是zlm的bug，请打上补丁：
> 
> ```diff
> Index: src/Rtsp/RtspPlayer.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
> --- a/src/Rtsp/RtspPlayer.cpp	(revision 6b9889a883a91d7ba906f44f3c5288311dc883a4)
> +++ b/src/Rtsp/RtspPlayer.cpp	(date 1688614578481)
> @@ -451,7 +451,7 @@
>              case type_pause: WarnL << "Pause failed:" << parser.status() << " " << parser.statusStr(); break;
>              case type_play:
>                  WarnL << "Play failed:" << parser.status() << " " << parser.statusStr();
> -                onPlayResult_l(SockException(Err_shutdown, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
> +                onPlayResult_l(SockException(Err_other, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
>                  break;
>              case type_seek: WarnL << "Seek failed:" << parser.status() << " " << parser.statusStr(); break;
>          }
> @@ -502,9 +502,8 @@
>          if (trackIdx == -1) {
>              return;
>          }
> -        handleOneRtp(
> -            trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate, (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize,
> -            len - RtpPacket::kRtpTcpHeaderSize);
> +        handleOneRtp(trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate,
> +                     (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize, len - RtpPacket::kRtpTcpHeaderSize);
>      } else {
>          trackIdx = getTrackIndexByInterleaved(interleaved - 1);
>          if (trackIdx == -1) {
> @@ -615,11 +614,7 @@
>      }
>  
>      _StrPrinter printer;
> -    if (cmd == "PLAY") {
> -        printer << cmd << " " << _play_url << " RTSP/1.0\r\n";
> -    } else {
> -        printer << cmd << " " << url << " RTSP/1.0\r\n";
> -    }
> +    printer << cmd << " " << url << " RTSP/1.0\r\n";
>  
>      for (auto &pr : header) {
>          printer << pr.first << ": " << pr.second << "\r\n";
> @@ -743,7 +738,7 @@
>      if (_sdp_track.size() == 1) {
>          return 0;
>      }
> -    throw SockException(Err_shutdown, StrPrinter << "no such track with type:" << getTrackString(track_type));
> +    throw SockException(Err_other, StrPrinter << "no such track with type:" << getTrackString(track_type));
>  }
>  
>  ///////////////////////////////////////////////////
> ```

这个又于那个海康rtsp录像流冲突了

**Comment by xia-chu** [comment]
> > 这是zlm的bug，请打上补丁：
> > ```diff
> > Index: src/Rtsp/RtspPlayer.cpp
> > IDEA additional info:
> > Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> > <+>UTF-8
> > ===================================================================
> > diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
> > --- a/src/Rtsp/RtspPlayer.cpp	(revision 6b9889a883a91d7ba906f44f3c5288311dc883a4)
> > +++ b/src/Rtsp/RtspPlayer.cpp	(date 1688614578481)
> > @@ -451,7 +451,7 @@
> >              case type_pause: WarnL << "Pause failed:" << parser.status() << " " << parser.statusStr(); break;
> >              case type_play:
> >                  WarnL << "Play failed:" << parser.status() << " " << parser.statusStr();
> > -                onPlayResult_l(SockException(Err_shutdown, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
> > +                onPlayResult_l(SockException(Err_other, StrPrinter << "rtsp play failed:" << parser.status() << " " << parser.statusStr()), !_play_check_timer);
> >                  break;
> >              case type_seek: WarnL << "Seek failed:" << parser.status() << " " << parser.statusStr(); break;
> >          }
> > @@ -502,9 +502,8 @@
> >          if (trackIdx == -1) {
> >              return;
> >          }
> > -        handleOneRtp(
> > -            trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate, (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize,
> > -            len - RtpPacket::kRtpTcpHeaderSize);
> > +        handleOneRtp(trackIdx, _sdp_track[trackIdx]->_type, _sdp_track[trackIdx]->_samplerate,
> > +                     (uint8_t *)data + RtpPacket::kRtpTcpHeaderSize, len - RtpPacket::kRtpTcpHeaderSize);
> >      } else {
> >          trackIdx = getTrackIndexByInterleaved(interleaved - 1);
> >          if (trackIdx == -1) {
> > @@ -615,11 +614,7 @@
> >      }
> >  
> >      _StrPrinter printer;
> > -    if (cmd == "PLAY") {
> > -        printer << cmd << " " << _play_url << " RTSP/1.0\r\n";
> > -    } else {
> > -        printer << cmd << " " << url << " RTSP/1.0\r\n";
> > -    }
> > +    printer << cmd << " " << url << " RTSP/1.0\r\n";
> >  
> >      for (auto &pr : header) {
> >          printer << pr.first << ": " << pr.second << "\r\n";
> > @@ -743,7 +738,7 @@
> >      if (_sdp_track.size() == 1) {
> >          return 0;
> >      }
> > -    throw SockException(Err_shutdown, StrPrinter << "no such track with type:" << getTrackString(track_type));
> > +    throw SockException(Err_other, StrPrinter << "no such track with type:" << getTrackString(track_type));
> >  }
> >  
> >  ///////////////////////////////////////////////////
> > ```
> 
> 这个又于那个海康rtsp录像流冲突了

所以这些兼容性真的是很扯淡问题

**Comment by xia-chu** [comment]
不过分析vlc 它是用content-base来play的 也就是打补丁后的行为

**Comment by xuandu** [comment]
VLC 用的不一定是contentbase的URL的；下图是我当时VLC拉海康VNR的；截图看返回的content-base并不完整；但是play请求确是完整的
![微信截图_20230706151919](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/5eed5f26-78d6-40ca-9815-2c433f11f43f)
![微信图片_20230706151656](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/9fd311e3-a2c5-4bbd-b364-42c88bf02034)

**Comment by xuandu** [comment]
> 感谢 问题已经解决了

哥哥，你的_play_url 和url 区别是啥？你把VLC拉流的dump和ZLM拉流的dump都给一下；
希望大佬能改个都能兼容的版本，嘤嘤嘤

**Comment by xiongguangjie** [comment]
> > 感谢 问题已经解决了
> 
> 哥哥，你的_play_url 和url 区别是啥？你把VLC拉流的dump和ZLM拉流的dump都给一下； 希望大佬能改个都能兼容的版本，嘤嘤嘤

@xuandu @981030048 使用这个分支测试下，看是否有问题，https://github.com/xiongguangjie/ZLMediaKit/tree/rtsp_player_like_vlc

**Comment by xuandu** [comment]
不好意思因为很久没有更新代码了，才来反馈；这个07-09号的版本我更新了，但是测试海康拉流时间是不对的；VLC看还是没有能正常点播准确时间段；还是会出现我原帖中的问题
![微信截图_20230724112552](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/ddc4ed29-1e00-494f-a82e-ce7a72d5ca5a)

**Comment by xiongguangjie** [comment]
> 不好意思因为很久没有更新代码了，才来反馈；这个07-09号的版本我更新了，但是测试海康拉流时间是不对的；VLC看还是没有能正常点播准确时间段；还是会出现我原帖中的问题 ![微信截图_20230724112552](https://user-images.githubusercontent.com/18655816/255464710-ddc4ed29-1e00-494f-a82e-ce7a72d5ca5a.png) @xia-chu @xiongguangjie

你原贴中不是vlc播放正常吗？？？

**Comment by xuandu** [comment]
> > 不好意思因为很久没有更新代码了，才来反馈；这个07-09号的版本我更新了，但是测试海康拉流时间是不对的；VLC看还是没有能正常点播准确时间段；还是会出现我原帖中的问题 ![微信截图_20230724112552](https://user-images.githubusercontent.com/18655816/255464710-ddc4ed29-1e00-494f-a82e-ce7a72d5ca5a.png) @xia-chu @xiongguangjie
> 
> 你原贴中不是vlc播放正常吗？？？

抱歉打错了字，是用wireshark看zlm和那个海康设备的交互，点播还是不对，客户端播放的时间段不是我点播的时间段

**Comment by xiongguangjie** [comment]
> > > 不好意思因为很久没有更新代码了，才来反馈；这个07-09号的版本我更新了，但是测试海康拉流时间是不对的；VLC看还是没有能正常点播准确时间段；还是会出现我原帖中的问题 ![微信截图_20230724112552](https://user-images.githubusercontent.com/18655816/255464710-ddc4ed29-1e00-494f-a82e-ce7a72d5ca5a.png) @xia-chu @xiongguangjie
> > 
> > 
> > 你原贴中不是vlc播放正常吗？？？
> 
> 抱歉打错了字，是用wireshark看zlm和那个海康设备的交互，点播还是不对，客户端播放的时间段不是我点播的时间段

代码是最新的吗？？吧zlm拉流的抓包发给我

**Comment by xuandu** [comment]
![Snipaste_2023-07-23-00](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/db5338a0-a3af-4ffb-81f3-bc1cec6c8b7d)
![VLC-2023-07-23-00-00-00](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/10c386a8-3e99-4e03-8443-632941ba7046)
代码是7月10号，您更新之后的版本；
[ZLM拉海康录像.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12157549/ZLM.zip)

**Comment by xiongguangjie** [comment]
![企业微信截图_16902644753752](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/3ebffad9-be51-4915-8da9-623b75845b5c)
代码不对，cimmit ash 对不上，你用最新的代码试一下

**Comment by xiongguangjie** [comment]
要这个才行 
![企业微信截图_169026463776](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/59cb65e4-b445-40c3-a3b3-fcf500178bd2)

**Comment by xuandu** [comment]
> 要这个才行 ![企业微信截图_169026463776](https://user-images.githubusercontent.com/19631632/255803013-59cb65e4-b445-40c3-a3b3-fcf500178bd2.png)

![1](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/fdf0b6a6-baeb-4dec-a6af-84fdf4460a26)
![2](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/d29e12ff-9b7d-4f8b-b652-c0d8e15c09c4)
代码是7月10好的代码，我打断点看的；而且我用的是git原生代码。

**Comment by xuandu** [comment]
![3](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/0a171a3f-130c-45f9-b35f-aab69d658183)
[ZLM拉海康2.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12157797/ZLM.2.zip)
用7-15号的daima 也是一样的

**Comment by xiongguangjie** [comment]
> ![3](https://user-images.githubusercontent.com/18655816/255809638-0a171a3f-130c-45f9-b35f-aab69d658183.png) [ZLM拉海康2.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12157797/ZLM.2.zip) 用7-15号的daima 也是一样的

我代码的问题，等下我修复一下

**Comment by xiongguangjie** [comment]
使用这个分支看看如何，应该可以了 https://github.com/xiongguangjie/ZLMediaKit/tree/fix_hik_record_player

**Comment by xiongguangjie** [comment]
@xuandu 怎么样？？？？

**Comment by xuandu** [comment]
> @xuandu 怎么样？？？？

可以了；点播时间对了；感谢
