### ISSUE TITLE
[BUG] HLS播放器中的bug

### ISSUE THREAD

**Issue by joyouswind** [ZLMediaKit/ZLMediaKit#2628]
### 现象描述
HLS播放器在播放vod点播文件时由于下载速度过快导致无法正常播放

### 如何复现?

点播m3u8文件时必现

### 相关日志或截图

<img width="464" alt="微信截图_16886272242040" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/7953947/e1a59c5c-1888-4db6-a470-109b885dc905">

时间单位不对导致永远以毫秒延迟拉取下一个片，此处改为秒级延迟后播放正常

另外，我看新加入的http-flv播放器应该只能实现直播的播放，对于Content-Type为binary/octet-stream的FLV文件FlvPlayer中不支持，我看了下代码，在ZLToolkit的异步框架上对于这种文件流好像不好改（在同一个连接中不太好控制延迟读取socket），对于点播文件的Player后续是否有计划？

### 各种环境信息

* **代码提交记录/git commit hash**:[7c6b612](https://github.com/ZLMediaKit/ZLMediaKit/commit/7c6b612a4d0a0b966c4bdb7f4475b2d037408f53)
* **操作系统及版本**:Ubuntu20.04
* **硬件信息**:4C8G

**Comment by xia-chu** [comment]
是的对于长链接 确实不好做下载速度控制， 但是hls这种短链接还是可以的，您的修改意见可否提个pr上来？
对于长链接下载速度的控制，可以通过Socket::enableRecv接口来控制，不过由于zlmediakit的MediaPlayer接口 
本来几乎没考虑点播的情况，所以这个缺陷我觉得可能并不是那么致命。

**Comment by joyouswind** [comment]
应用场景是想用ZL实现拉流转推，遇到了需要点播HLS文件进行转推的逻辑，一对一转推之前多会采用ffmpeg命令模式。

**Comment by xia-chu** [comment]
> 应用场景是想用ZL实现拉流转推，遇到了需要点播HLS文件进行转推的逻辑，一对一转推之前多会采用ffmpeg命令模式。

现在zlm点播hls流好像还是有播放速度控制问题 需要你确认下

**Comment by joyouswind** [comment]
请问您是直接用播放器测试的点播文件吗？修改后的程序，我用test_bench_forward测试了几个HLS的点播文件和直播文件的拉流转推，通过rtmp转推到其他的源站，目前看都是播放正常的。

**Comment by xia-chu** [comment]
合并您的pr了 感谢！
同时我找到一个zltoolkit的bug(导致hls拉流重试失效)，也修复了。
