### ISSUE TITLE
[BUG] 国标RTP推流后，HLS拉流花屏

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2630]
### 现象描述
相机通过国标RTP方式推流，转HLS播放发现花屏，必现。怀疑和码流解析有关。

### 如何复现?
相机国标RTP推流

希望相机国标RTP推流后没有花屏，正常播放。

### 相关日志或截图
用vlc拉hls流
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/12b8be0c-3d73-4454-9477-40bc09709071)

抓取的相机RTP推流包

[抓包.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/11966245/default.zip)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置
[rtp]
audioMtuSize=600
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
g711a_pt=8
g711u_pt=0
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
timeoutSec=15
ts_pt=33

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
linux

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by pedoc** [comment]
一般花屏都和丢包乱序有关,你这个抓包wireshark自身的分析就能看出丢包乱序
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6604230/da4e0513-4491-4935-8085-aa2aa1607c35)

从相机取流的协议建议切换为TCP取流

**Comment by zhang-chuanfeng** [comment]
> 从相机取流的协议建议切换为TCP取流

后面看能不能tcp看看

**Comment by zhang-chuanfeng** [comment]
> zlmediakit有打印丢包日志吗

![Uplo
<img width="815" alt="2" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/04533152-7c21-4582-b502-63387f01b4ad">
ading 1.png…]()

**Comment by zhang-chuanfeng** [comment]
> zlmediakit有打印丢包日志吗

<img width="827" alt="1" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/91a9fcec-f735-4b14-907a-d7ebd3bf601b">
<img width="800" alt="3" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/8d9cb6b6-90fb-44ee-acb4-df4691c5458c">

**Comment by xia-chu** [comment]
> 一般花屏都和丢包乱序有关,你这个抓包wireshark自身的分析就能看出丢包乱序 ![image](https://user-images.githubusercontent.com/6604230/251605561-da4e0513-4491-4935-8085-aa2aa1607c35.png)
> 
> 从相机取流的协议建议切换为TCP取流

@pedoc 感谢分析 8%的丢包率很高了
