### ISSUE TITLE
宇视视频监控系统通过国标接入视频回放不成功

### ISSUE THREAD

**Issue by myskybeyond** [ZLMediaKit/ZLMediaKit#2632]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
宇视视频监控平台推流，宇视视频监控系统通过国标接入视频回放不成功，zlmediakit日志报错，
**咨询的具体内容和问题**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/37172114/0b129ed7-d5cd-4e22-9ddd-dae9e40ce3b3)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
请使用udp模式吧 宇视的tcp有发送缓冲溢出覆盖问题

**Comment by myskybeyond** [comment]
宇视监控视频系统中外域配置的就是UDP,配置如下图：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/37172114/9c5be828-64ea-43df-9bef-a6acad6e3fb3)
实时视频点播，云台控制都没问题，就视频回放zlmediakit报上面的问题，这个是不校验ssrc的情况下报的错，如果校验ssrc则报下面的错误：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/37172114/9e1f6a5d-abe5-45be-99d9-feced7b3aca7)

**Comment by xia-chu** [comment]
你截的图也太模糊了 看不清

**Comment by myskybeyond** [comment]
![微信截图_20230707220002](https://github.com/ZLMediaKit/ZLMediaKit/assets/37172114/19581b0b-8593-467f-85f2-8508a11fcb29)

**Comment by myskybeyond** [comment]
不校验ssrc的情况下报的错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/37172114/70793f5d-3002-4852-ad37-d33269dd9502)

**Comment by myskybeyond** [comment]
> 你截的图也太模糊了 看不清

不好意思啊，上传后图片应该自动压缩了，重新上传了配置截图，

**Comment by xia-chu** [comment]
宇视的设备真实垃圾 一堆问题 可以wiresharek抓个包给我分析下吗

**Comment by myskybeyond** [comment]
> 宇视的设备真实垃圾 一堆问题 可以wiresharek抓个包给我分析下吗
确实垃圾，现在没环境无法抓包，等再去客户现场了我再抓包，我先把issue关了。

**Comment by myskybeyond** [comment]
暂时不具备复现环境，关闭issue。
