### ISSUE TITLE
[BUG] 在测试 WebRTC 功能时, 使用 Chrome 浏览器访问 ZLMediait 自带网页，如果只有一个流，该流不会出现在已存在的流列表中

### ISSUE THREAD

**Issue by tjpgt** [ZLMediaKit/ZLMediaKit#2634]
### 现象描述

在测试 WebRTC 功能时, 使用 Chrome 浏览器访问 ZLMediait 自带网页，如果只有一个流，该流不会出现在已存在的流列表中

### 如何复现?

使用addStreamProxy接口添加一个流并且只启用enable_rtsp，其他的enable_hls、enable_mp4之类的通通不启用，然后打开ZLMediait自带的WebRTC demo

### 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/29495241/8c81825e-5827-47b2-92bc-788fc933aab9)

* **其他需要补充的信息**:
原因应该是该网页的如下代码中，有一个stream单词拼错了
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/29495241/3e5deb79-4de3-47f1-a5f7-7f7802a8e57a)

**Comment by xiongguangjie** [comment]
方便提交个pr吗？？

**Comment by tjpgt** [comment]
> 方便提交个pr吗？？

https://github.com/ZLMediaKit/ZLMediaKit/pull/2636

**Comment by xiongguangjie** [comment]
> > 方便提交个pr吗？？
> 
> #2636

已经合并pr
