### ISSUE TITLE
[BUG] c api进行视频录制会导致进程崩溃

### ISSUE THREAD

**Issue by beliefsky** [ZLMediaKit/ZLMediaKit#2638]
异常信息：terminate called after throwing an instance of 'mediakit::AssertFailedException'
  what():  Assertion failed: (getOwnerPoller(MediaSource::NullMediaSource())->isCurrentThread(), Can only call setupRecord in it's owner poller), function setupRecord

对比了下c api和WebApi.cpp内实现方式，WebApi.cpp会异步切换到流所在的线程执行

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36815107/f46625cd-0228-42c4-a23b-a5d00f0527cd)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36815107/87cadd43-d54a-4015-9c8f-ce26c58a49dd)

**Comment by xia-chu** [comment]
嗨 这个问题修复了：https://github.com/ZLMediaKit/ZLMediaKit/commit/e6a19c4eccfeac1f3f06433469379f0e75cbf017

**Comment by beliefsky** [comment]
测试已修复
