### ISSUE TITLE
通过GB28181拉流720P，怎么配置ffmpeg转成D1推出去

### ISSUE THREAD

**Issue by chogao** [ZLMediaKit/ZLMediaKit#2652]
你好，由于现在国标协议不支持码流切换，我前端IPC配置GB28181拉720P码流，怎么配置可以推D1或CIF流

**Comment by xia-chu** [comment]
sip握手时 在sdp中可以约定分辨率。
```c++
enum class GB28181VideoSolution : uint8_t {
    QCIF = 1,
    CIF = 2,
    CIF4 = 3,
    D1 = 4,
    HD720P = 5,
    HD1080P = 6,
};
```

**Comment by chogao** [comment]
现在使用wvp作为28181服务，未在代码里看到你贴的部分实现

**Comment by xia-chu** [comment]
> 现在使用wvp作为28181服务，未在代码里看到你贴的部分实现

当然没有了 他是java的 我只是贴了我实现的部分，原理是类似的，你看看wvp有没有生成sdp f= 字段。
