### ISSUE TITLE
推多路webrtc时，zlm docker容器退出，退出代码139

### ISSUE THREAD

**Issue by tjfyjp** [ZLMediaKit/ZLMediaKit#2653]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
我准备用zlm做webrtc sfu服务器，当超过18个向zlm推webrtc流，其他终端通过webrtc播放的方式，实现webrtc互动，常出现容器自动停止，用docker ps -a查看，zlm容器状态为已退出，错误码是139.
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by lexang** [comment]
webrtc怎么推流啊

**Comment by tjfyjp** [comment]
我是用的zlmrtcclient.js来进行推流的，我感觉容器自动退出是zlm的一个bug，当webrtc推流路数多了，加上webrtc推流有可能不稳定，有断了重推等，有时会导致无效内存引用异常。
