### ISSUE TITLE
[技术咨询] 点播wss

### ISSUE THREAD

**Issue by tank520** [ZLMediaKit/ZLMediaKit#2657]
场景：国标设备点播功能。

问题描述：通过点播接口返回的播放地址，使用ws_flv能够正常播放，使用wss_flv播放不了，443端口正常。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/25721782/05fad9ba-ffe8-4b56-98fa-f42831fd94a1)

请问造成这个的原因是什么？

**Comment by xia-chu** [comment]
1、你需要买个域名
2、你需要用域名申请一个ssl证书，有免费的，请参考wiki https篇。

如果这些你都不想做，请使用 https://zlmediakit.com 测试
