### ISSUE TITLE
[BUG] 国标ps流转rtp流，p帧内杂带有aud的数据

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2658]
#

### 现象描述

使用zlmediakit接收国标ps流，然后转成rtp-udp发送到自研的媒体服务上，然后再网页上播放，在网页上播放时出现花屏，通过抓包发现

1.ipc发来的媒体数据，每个视频帧前面都有aud帧。

2.zlmediakit转发的rtp数据里面，普遍发现，p帧内杂带有aud的数据，请问这种做法是正确的吗

 
### 相关日志或截图
#
/
![0224014D-47DF-46fe-B2F7-C3B9FC112216](https://github.com/ZLMediaKit/ZLMediaKit/assets/23181609/bcceb57e-7eac-48b5-8ddd-0ec5fef5424c)

/
![9C892EE6-A67A-4e85-95C5-C1DCE823B8E9](https://github.com/ZLMediaKit/ZLMediaKit/assets/23181609/0d421bb7-ec4e-4554-94b6-7bb1b6158a6a)

抓包文件附件:
[target_5_48 (1).zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12049446/target_5_48.1.zip)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
请使用zlm的dump功能 把rtp dump出并上传上来

**Comment by HalcyonHuang** [comment]
[124CD310_rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12065613/124CD310_rtp.zip)
[124CD310_mp2.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12065614/124CD310_mp2.zip)
[124CD310_video.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12065615/124CD310_video.zip)

**Comment by HalcyonHuang** [comment]
[124CCBF0_video.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12067331/124CCBF0_video.zip)
[124CCBF0_rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12067337/124CCBF0_rtp.zip)
[124CCBF0_mp2.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12067339/124CCBF0_mp2.zip)

**Comment by xia-chu** [comment]
我分析原始数据 你们有SEI AUD帧 这样的:
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/5fdabc93-5432-4710-a2b2-f7f9da5f516d)

这个流用ffplay可以正常播放rtmp。

**Comment by xia-chu** [comment]
你可以打上个patch:
```c++
Index: src/Extension/H264.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Extension/H264.cpp b/src/Extension/H264.cpp
--- a/src/Extension/H264.cpp	(revision 3d6cf314798ab0dc4f3801f7aca6aff0a2b337d0)
+++ b/src/Extension/H264.cpp	(date 1689662738876)
@@ -194,6 +194,7 @@
             ret = VideoTrack::inputFrame(frame);
             break;
         }
+        case H264Frame::NAL_AUD: return false;
         default:
             // 避免识别不出关键帧
             if (_latest_is_config_frame && !frame->dropAble()) {

```

**Comment by xia-chu** [comment]
准确的讲 不是zlm在p帧内夹杂aud帧 而是zlm把时间戳相同的帧 打包到一起了
sei aud p帧时间戳都相同

**Comment by HalcyonHuang** [comment]
我的视频流里面，经常出现在一个视频帧中间有 55  83  15  ac  2a  0  0  0  1  6  5  ff  ff  a0  81  6d  38  4e  99  或者 xx  xx  0  0  0  0  0  0  0  1  6  5  ff  ff  a0  81  6d  38  4e  99 这样的数据排列 
代码里面的查找视频帧函数会误判断为 NAL_SEI 帧，从而吧一个完整的视频帧分成两个帧。但实际上只有一个帧。


int mpeg_h264_find_nalu(const uint8_t* p, size_t bytes, size_t* leading)
{
    size_t i, zeros;
    for (zeros = i = 0; i + 1 < bytes; i++)
    {
        if (0x01 == p[i] && zeros >= 2) //这里判断出错
        {
            assert(i >= zeros);
            if (leading)
                *leading = (zeros > 2 ? 3 : zeros) + 1; // zeros + 0x01
            return (int)(i + 1);
        }

        zeros = 0x00 != p[i] ? 0 : (zeros + 1);
    }

    return -1;
}

类似 xx  xx  0  0  0  0  0  0  0  1  6  5 这样的排列容易修复，只要吧判断条件 if (0x01 == p[i] && zeros >= 2)  改成  if (0x01 == p[i] && (zeros == 3 || zeros == 4)) 即可，
但是如果一个帧中间出现 ac  2a  0  0  0  1  6  5  ff  ff 这样的排列，就不要处理了。

**Comment by xia-chu** [comment]
@HalcyonHuang 那说明你这个流有问题 如果数据中有 0x 00 00 01，那么应该转义。
你这个H264哪怕是给ffmpeg解析 也是会误判的

**Comment by xia-chu** [comment]
H264 nal负载部分是不能有0x00 00 01的，如果有有转义规则可循
