### ISSUE TITLE
[技术咨询] ZLMediaKit 将两个180度摄像头推的视频流 结合成一个360度

### ISSUE THREAD

**Issue by lexang** [ZLMediaKit/ZLMediaKit#2665]
**咨询的功能模块**
- 推流

**咨询的具体内容和问题**
- ZLMediaKit 将两个180度摄像头推的视频流 结合成一个360度，怎么做

**Comment by xiongguangjie** [comment]
这需要在客户端做，需要投影，同步，合并，编码等操作，在ZLM做不合适

**Comment by lexang** [comment]
> 这需要在客户端做，需要投影，同步，合并，编码等操作，在ZLM做不合适

客户端做是什么意思，能大致讲下吗，谢谢了

**Comment by lexang** [comment]
请问有人帮忙吗 提供个思路也行
