### ISSUE TITLE
mp4录像等hook 接口携带推流参数params功能

### ISSUE THREAD

**Issue by lidp888** [ZLMediaKit/ZLMediaKit#2666]
**描述该功能的用处，可以提供相关资料描述该功能**
有时候推流+录像需要和具体业务流关联，比如推流时携带事件id，此id需要与当前推流/监控的录像文件做关联，在实际项目中有这种需求，目前在on_publish接口有携带params参数，但是在mp4录像接口没用携带，导致监控和录像关联到具体上层业务时无法关联，建议增加透传params参数能力，给外围基于http事件二次开发更多灵活性。谢谢。
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
可以返回originUrl这个值 也就是getMediaList接口返回的那个。
你们拿到后自己去解析吧，不过在录制hook触发时 这个值不一定有，因为MediaSource可能已经注销了。

很多功能没实现，是由于代码层级结构和抽象后所限导致的。你说的录制hook不仅推流会触发，addStreamProxy也会触发，
但是这在zlmediakit中是统一的 你告诉我怎么从拉流代理中获取推流参数？

**Comment by xia-chu** [comment]
想想还是不好做 因为做起来有很多不完美的地方 干脆就不做算了

**Comment by lidp888** [comment]
如果能用originUrl参数携带也是可以满足业务需求的，addStreamProxy也是外部api触发拉流，也是上层业务自己调用的，期望的是能通过标准url透传业务参数，这样好关联业务，实际场景是这样：摄像头告警，业务控制系统根据告警自动发起监控，会自动录像，以及这个告警关联的任务，这一些列内容需要通过一次事件id做关联，方便统计。

**Comment by xia-chu** [comment]
现在已经支持了
