### ISSUE TITLE
[技术咨询] 无人观看时关闭流的选项是否能关闭？ 

### ISSUE THREAD

**Issue by gotliuyan** [ZLMediaKit/ZLMediaKit#2668]
**咨询的功能模块**
- mp4录制

**咨询的具体内容和问题**
- 推流时总是因“MP4点播无人观看,自动关闭:hls://__defaultVhost__/record” ， 这个选项是否可以配置文件中关闭？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
配置文件有个mp4_as_palyer 设置为1，就可以避免
