### ISSUE TITLE
使用vlc播放视频流卡顿

### ISSUE THREAD

**Issue by ArnoHand** [ZLMediaKit/ZLMediaKit#2671]
**咨询的功能模块**
- 使用vlc播放视频流卡顿

**咨询的具体内容和问题**
- 我在ubuntu上用的源码编译运行，用第三方用国标28181推送过来，用“rtmp://127.0.0.1:1935/%s/%s”和“http://127.0.0.1:80/%s/%s/hls.m3u8”方式播放，视频一直循环卡顿，然后倍速播放，向问下这个怎能解决，是我哪里没配置对吗

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个问题信息不足 无法判断。
可以换ffplay/flv.js等播放器测试对比一下
