### ISSUE TITLE
http-flv 兼容问题

### ISSUE THREAD

**Issue by PioLing** [ZLMediaKit/ZLMediaKit#2679]
代码提交记录:
编译日期: 2023-07-10T13:46:54
代码日期: 2023-07-09T13:24:52+08:00
当前git分支: master
当前git hash值: 8ee91d7

操作系统及版本:Ubuntu SMP Wed May 24 00:51:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux 

### 现象描述
   大佬们，我在用addStreamProxy() 添加代理 livegbs 的 http-flv 流失败，
失败日志如下：
 TcpClient.cpp:75 operator () | class mediakit::FlvPlayerBase<class mediakit::FlvPlayer>-1 on err: 255(Expected a string)

### 如何复现?
调用 
/index/api/addStreamProxy 接口
url 参数：
http://{ip:port}/sms/{app}/flv/hls/{xxx}.flv

**Comment by xiongguangjie** [comment]
https://github.com/xiongguangjie/ZLMediaKit/tree/fix_flv_player_livegbs 这个分支修复

**Comment by xia-chu** [comment]
这个本身是livegbs参数的流不规范导致的，他们生成的metadata flv  tag是错误的：
```bash
2023-07-20 14:17:53.695 I [test_flv] [46333-4415733056] FlvSplitter.cpp:92 onRecvContent | 
05 00 00 00 00 01 73 12 01 00 00 00 02 00 0a 6f ......s........o
6e 4d 65 74 61 44 61 74 61 03 00 06 53 65 72 76 nMetaData...Serv
65 72 02 00 1e 4c 69 76 65 51 69 6e 67 20 28 67 er...LiveQing (g
69 74 68 75 62 2e 63 6f 6d 2f 4c 69 76 65 51 69 ithub.com/LiveQi
6e 67 29 00 05 77 69 64 74 68 00 40 9e 00 00 00 ng)..width.@....
00 00 00 00 06 68 65 69 67 68 74 00 40 90 e0 00 .....height.@...
00 00 00 00 00 0c 64 69 73 70 6c 61 79 57 69 64 ......displayWid
74 68 00 40 9e 00 00 00 00 00 00 00 0d 64 69 73 th.@.........dis
70 6c 61 79 48 65 69 67 68 74 00 40 90 e0 00 00 playHeight.@....
00 00 00 00 08 64 75 72 61 74 69 6f 6e 00 00 00 .....duration...
00 00 00 00 00 00 00 09 66 72 61 6d 65 72 61 74 ........framerat
65 00 00 00 00 00 00 00 00 00 00 03 66 70 73 00 e...........fps.
```

这个打印的代码定位在这：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/d8faca25-f17c-4129-a7d1-fd2ed81dff49)

**Comment by PioLing** [comment]
> https://github.com/xiongguangjie/ZLMediaKit/tree/fix_flv_player_livegbs 这个分支修复

我测试了，现在代理live 的flv 可以了，谢谢~

**Comment by xia-chu** [comment]
我们看它
第1个字节是 0x05, 对应的类型是AMF0_NULL, 只占用一个字节；
第2个字节是0x00, 对应的类型是AMF0_NUMBERL, 后续应该跟上8个字节长度的内容，也就是 `00 00 00 01 73 12 01 00`;
第10个字节是00， 对应的类型是AMF0_NUMBERL, 后续应该跟上8个字节长度的内容，也就是 `00 02 00 0a 6f 6e 4d 65`;
但是这样显然不对，已经覆盖了`onMetaData` 字符串了。

**Comment by xia-chu** [comment]
调试ffmpeg分析该flv文件 发现ffmpeg发现不合法 直接把这个flv tag给忽略掉了：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/b06f3883-50a1-4c1c-88ad-93e328ba6a84)

**Comment by xiongguangjie** [comment]
是不标准，但是第三方播放器能播（ffmpeg），我们也兼容下
