### ISSUE TITLE
"rtsp ring buffer detached" and "rtp over udp player timeout" errors

### ISSUE THREAD

**Issue by codeRATny** [ZLMediaKit/ZLMediaKit#2681]
When relaying video streams from cameras to the tcp rtsp zlmedia server, these errors sometimes appear
At this time, the proxyplayer tries to reconnect. After reconnecting, this error appears almost immediately after connecting. This happens until the proxyplayer object is re-created.

Also the value of the time at the first in udp timeout is too large

How can I solve this problem?

Logs:
```
12.07.2023 00:19:39 WARNING LWP2177799 [RtspSession.cpp:56 [zlmedia] 10887-1680(127.0.0.1:45708) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):2965
12.07.2023 00:29:11 WARNING LWP2177810 [RtspSession.cpp:56 [zlmedia] 10899-1998(127.0.0.1:52180) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):482
12.07.2023 00:30:51 WARNING LWP2177816 [RtspSession.cpp:56 [zlmedia] 10902-1998(127.0.0.1:43206) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):97
12.07.2023 00:45:55 WARNING LWP2177825 [RtspSession.cpp:56 [zlmedia] 10904-1258(127.0.0.1:44710) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):818
12.07.2023 01:01:23 WARNING LWP2177846 [RtspSession.cpp:56 [zlmedia] 10918-2986(127.0.0.1:43896) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):42
12.07.2023 01:26:55 WARNING LWP2177846 [RtspSession.cpp:56 [zlmedia] 10920-2986(127.0.0.1:57830) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):1288
12.07.2023 01:51:24 WARNING LWP2177801 [RtspSession.cpp:56 [zlmedia] 10927-3103(127.0.0.1:56260) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):1035
12.07.2023 02:57:36 WARNING LWP2177824 [RtspSession.cpp:56 [zlmedia] 10934-3103(127.0.0.1:37196) RTSP播放器 (__defaultVhost__/live/6ecb2288-0d0b-4529-94a0-886fd55d681b)断开:rtsp ring buffer detached,耗时(s):3721

13.07.2023 04:49:58 WARNING LWP2177796 [RtspSession.cpp:56 [zlmedia] 10211-2843(127.0.0.1:37708) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):148495
13.07.2023 04:51:27 WARNING LWP2177799 [RtspSession.cpp:56 [zlmedia] 43228-1297(127.0.0.1:40152) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):60
13.07.2023 04:52:29 WARNING LWP2177816 [RtspSession.cpp:56 [zlmedia] 43236-1461(127.0.0.1:45956) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):61
13.07.2023 04:53:31 WARNING LWP2177826 [RtspSession.cpp:56 [zlmedia] 43244-1461(127.0.0.1:44058) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):61
13.07.2023 04:54:32 WARNING LWP2177830 [RtspSession.cpp:56 [zlmedia] 43250-1461(127.0.0.1:33004) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):60
13.07.2023 04:55:33 WARNING LWP2177847 [RtspSession.cpp:56 [zlmedia] 43257-1460(127.0.0.1:37492) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):61
13.07.2023 04:56:34 WARNING LWP2177800 [RtspSession.cpp:56 [zlmedia] 43263-1460(127.0.0.1:45650) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):61
13.07.2023 04:57:35 WARNING LWP2177808 [RtspSession.cpp:56 [zlmedia] 43271-1425(127.0.0.1:38152) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):60
13.07.2023 04:58:35 WARNING LWP2177823 [RtspSession.cpp:56 [zlmedia] 43278-1425(127.0.0.1:51150) RTSP播放器 (__defaultVhost__/live/be86fd36-c866-4d55-96c9-a77c1cb83e1c_low)断开:rtp over udp player timeout,耗时(s):60
```

**Comment by xia-chu** [comment]
`rtp over udp player timeout` mean that, zlmediakit did not recv any rtcp/rtsp commond from player.
You can increase `rtsp.keepAliveSecond` in `config.ini` file to avoid this problem.

To avoid `rtsp ring buffer detached` , you need set `general.resetWhenRePlay` to `0` in `config.ini` file .

**Comment by codeRATny** [comment]
Thanks for the answer!

I didn't change the default .keepAliveSecond
It has a value of (15 seconds), but log message have ticker's time ≈ 150 seconds, and then this stream endlessly reconnects and exits with too little timeout
I find this very strange, because if recreate the player object, then the first connection is successful and without a timeout

**Comment by Goga1992** [comment]
> Thanks for the answer!
> 
> I didn't change the default .keepAliveSecond It has a default value (15 seconds), but log message have ticker's time ≈ 150 seconds, and then this stream endlessly reconnects and exits with too little timeout I find this very strange, because if recreate the player object, then the first connection is successful and without a timeout

I have a similar problem with a time much larger than 15 seconds

**Comment by xia-chu** [comment]
> Thanks for the answer!
> 
> I didn't change the default .keepAliveSecond It has a default value (15 seconds), but log message have ticker's time ≈ 150 seconds, and then this stream endlessly reconnects and exits with too little timeout I find this very strange, because if recreate the player object, then the first connection is successful and without a timeout

Please provide a complete log of zlmediakit.

**Comment by codeRATny** [comment]
I couldn't find the necessary logs
They are too mixed and because of this it is not possible to find the necessary zlmedia logs for specific streams
But I found that upd streams ended with the same problem almost at the same time and then could not recover

Thanks for solution for rtsp ring buffer detach error
I couldn't find the necessary logs
They are too mixed and because of this it is not possible to find the necessary zlmedia logs for specific streams
But I found that upd streams ended with the same problem almost at the same time and then could not recover

Thanks for solution for rtsp ring buffer detach error
