### ISSUE TITLE
[技术咨询] ffmpeg rtp 方式推流 无法正常播放

### ISSUE THREAD

**Issue by dodu2014** [ZLMediaKit/ZLMediaKit#2684]
zlmediakit 默认配置

在使用rtp推流测试时，日志也显示推流成功，可播放的时候无法正常播放，请问是怎么回事？

``` shell
# h264推流
ffmpeg -re -i "video.mp4" -vcodec h264 -acodec aac -f rtp_mpegts rtp://127.0.0.1:10000
```

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15245544/97e28666-850b-41d9-9ff7-98451307fbce)

播放地址为：http://127.0.0.1/rtp/0DD53FC1.flv

使用 VLC 播放器测试，提示：您的输入无法被打开

**Comment by xia-chu** [comment]
请阅读wiki url规则篇。
