### ISSUE TITLE
如何支持大奖无人机的GB28181

### ISSUE THREAD

**Issue by FuXiangGit** [ZLMediaKit/ZLMediaKit#2685]
我如何用搭建无人机推GB28181，哪里配置sip服务器端口，sip服务器iD，视频通道编码
![f0a1508d184082bb6fcef14c09c7293](https://github.com/ZLMediaKit/ZLMediaKit/assets/5907168/59aa8a8a-4fdc-402c-8d5e-7fa5517fc0af)
ID，万分感谢能提供些建议。

**Comment by xia-chu** [comment]
zlmediakit只支持GB28181 流媒体部分，如果要支持sip信令 要搭配wvp-pro或akstream使用
