### ISSUE TITLE
[BUG]HLS切片录制时间配置未生效，之前的版本是正常的

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2686]
视频推流到媒体服务器使用HLS拉流播放发现切片时间和设置最大切片时间不一致。测试之前版本发现切片最大周期是正常的。
设置的切片最大周期2s，发现切片大小有10s时间

配置的切片最大时间
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/8d3c6c60-8012-4804-8536-e6b152c0786f)
hls拉流返回时间，在服务器上确定切片文件有10s
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/e06ce12a-7a99-4d55-80e0-a6a27ad18d72)

### 现象描述
hls切片周期时间和设置的最大周期不一致。设置2s，切片时间有10s

### 如何复现?
推流到服务端，开启hls ts切片，拉流查看m3u8或服务器上查看切片文件时间长度

### 相关日志或截图
hls配置
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/380de607-b050-49a7-909f-3853b0142557)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息
linux x86

git log
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/47417c88-e152-451f-8dfd-72ba89a2b859)

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这不是bug 这说明你这个流的gop非常大 超过2秒

**Comment by zhang-chuanfeng** [comment]
ok
