### ISSUE TITLE
多个客户端同时点播一个MP4文件，客户端间会相互干扰

### ISSUE THREAD

**Issue by lixiaochun** [ZLMediaKit/ZLMediaKit#2687]
### 现象描述

版本信息：Master主干版本
问题描述：多个RTSP客户端同时点播回放同一个MP4文件，会出现多个客户端间相互干扰，播放进度会强制拉齐的问题

### 如何复现?

譬如两个RTSP客户端A和B，同时回放test.mp4文件
A先放到一半，B再开始点播，此时A和B的画面会相关干扰，强制将B的画面同步到A，B无法从头开始播放，同时在时间进度同步期间内，A的画面也会停顿
希望A和B会话独立，互不影响，都可以独立控制播放进度

### 相关日志或截图
暂无日志

### 配置

config.ini缺省配置，未做修改

<details>
<summary>展开查看详细配置</summary>
<pre>
[record]
#mp4录制或mp4点播的应用名，通过限制应用名，可以防止随意点播
#点播的文件必须放置在此文件夹下
appName=record
#mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能
fileBufSize=65536
#mp4点播每次流化数据量，单位毫秒，
#减少该值可以让点播数据发送量更平滑，增大该值则更节省cpu资源
sampleMS=500
#mp4录制完成后是否进行二次关键帧索引写入头部
fastStart=0
#MP4点播(rtsp/rtmp/http-flv/ws-flv)是否循环播放文件
fileRepeat=0

[rtsp]
#rtsp专有鉴权方式是采用base64还是md5方式
authBasic=0
#rtsp拉流、推流代理是否是直接代理模式
#直接代理后支持任意编码格式，但是会导致GOP缓存无法定位到I帧，可能会导致开播花屏
#并且如果是tcp方式拉流，如果rtp大于mtu会导致无法使用udp方式代理
#假定您的拉流源地址不是264或265或AAC，那么你可以使用直接代理的方式来支持rtsp代理
#如果你是rtsp推拉流，但是webrtc播放，也建议关闭直接代理模式，
#因为直接代理时，rtp中可能没有sps pps,会导致webrtc无法播放; 另外webrtc也不支持Single NAL Unit Packets类型rtp
#默认开启rtsp直接代理，rtmp由于没有这些问题，是强制开启直接代理的
directProxy=1
#rtsp必须在此时间内完成握手，否则服务器会断开链接，单位秒
handshakeSecond=15
#rtsp超时时间，如果该时间内未收到客户端的数据，
#或者tcp发送缓存超过这个时间，则会断开连接，单位秒
keepAliveSecond=15
#rtsp服务器监听地址
port=554
#rtsps服务器监听地址
sslport=0
#rtsp 转发是否使用低延迟模式，当开启时，不会缓存rtp包，来提高并发，可以降低一帧的延迟
lowLatency=0
#强制协商rtp传输方式 (0:TCP,1:UDP,2:MULTICAST,-1:不限制)
#当客户端发起RTSP SETUP的时候如果传输类型和此配置不一致则返回461 Unsupported transport
#迫使客户端重新SETUP并切换到对应协议。目前支持FFMPEG和VLC
rtpTransportType=-1
[shell]
#调试telnet服务器接受最大bufffer大小
maxReqSize=1024
#调试telnet服务器监听端口
port=0
</pre>
</details>

### 各种环境信息

操作系统及版本：Windows 10

**Comment by xia-chu** [comment]
这不是bug 就是这么设计的 如果不想互相干扰 请使用http-mp4点播

**Comment by lixiaochun** [comment]
> 这不是bug 就是这么设计的 如果不想互相干扰 请使用http-mp4点播

多谢大佬回复哈，想了解下RTSP点播要改成互不干扰的，不知好改吗？

**Comment by xia-chu** [comment]
> > 这不是bug 就是这么设计的 如果不想互相干扰 请使用http-mp4点播
> 
> 多谢大佬回复哈，想了解下RTSP点播要改成互不干扰的，不知好改吗？

对我来说挺好改 对不熟悉的人来说 估计不好改
