### ISSUE TITLE
[技术咨询] rtsp使用udp回传视频的时候，服务端能否使用固定端口

### ISSUE THREAD

**Issue by BerryCol** [ZLMediaKit/ZLMediaKit#2696]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
rtsp 视频回传协议
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
udp回传的时候，能使用固定一个端口吗
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
rtsp 采用udp传输方式时 udp端口从端口池中顺序分配，目前默认是30000到30500之间 可以在配置文件中修改

**Comment by BerryCol** [comment]
能否用一个固定的udp端口呢

**Comment by xia-chu** [comment]
那么多播放器咋使用同一个端口？
