### ISSUE TITLE
Android设备，使用webrtc推流，接口返回成功了，但是没有流，烦请大神帮忙看看是什么原因？

### ISSUE THREAD

**Issue by thjjava** [ZLMediaKit/ZLMediaKit#2699]
### 现象描述
使用Android设备，通过调用/index/api/webrtc?type=push&app=rtc&stream=test接口向流媒体推流，接口返回成功了，但是调用/index/api/webrtc?type=play&app=rtc&stream=test 播放时，却提示:
 {
  "code": -400,
  "msg": "stream not found"
}

### offer sdp：
v=0
o=- 4658061084969688204 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS mediaStream
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:/gwU
a=ice-pwd:rgpVo6OEpntlJp9gg1it5e5Y
a=ice-options:trickle renomination
a=fingerprint:sha-256 3A:55:A9:A3:A4:23:56:64:96:83:B6:13:0C:96:52:15:B6:C1:DD:C3:40:B9:F2:E9:E2:D8:21:91:A5:4A:C9:14
a=setup:actpass
a=mid:video
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 urn:3gpp:video-orientation
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 ulpfec/90000
a=ssrc-group:FID 3194817162 1026485041
a=ssrc:3194817162 cname:DPW26w+7qsAeg0Pk
a=ssrc:3194817162 msid:mediaStream 100
a=ssrc:3194817162 mslabel:mediaStream
a=ssrc:3194817162 label:100
a=ssrc:1026485041 cname:DPW26w+7qsAeg0Pk
a=ssrc:1026485041 msid:mediaStream 100
a=ssrc:1026485041 mslabel:mediaStream
a=ssrc:1026485041 label:100

### 接口返回
{
	"code" : 0,
	"id" : "zlm_426",
	"sdp" : "v=0\r\no=- 4658061084969688204 2 IN IP4 101.91.172.152\r\ns=-\r\nt=0 0\r\na=group:BUNDLE video\r\na=msid-semantic: WMS mediaStream\r\na=ice-lite\r\nm=video 53000 UDP/TLS/RTP/SAVPF 98 99\r\nc=IN IP4 101.91.172.152\r\na=rtcp:53000 IN IP4 101.91.172.152\r\na=ice-ufrag:zlm_426\r\na=ice-pwd:LX7Q5eGbOussXtjzCElxwdCI\r\na=ice-options:trickle\r\na=fingerprint:sha-256 5C:A0:0F:E6:EE:B0:02:61:FB:74:39:36:D4:EA:4E:89:DC:B2:B3:1C:1C:2D:27:B3:E4:9F:A4:55:71:6C:37:62\r\na=setup:passive\r\na=mid:video\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=rtcp-fb:98 transport-cc\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=candidate:udpcandidate 1 udp 110 101.91.172.152 53000 typ host\r\n",
	"type" : "answer"
}

### 流媒体抓包文件

[media-03.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12143756/media-03.zip)

**Comment by xia-chu** [comment]
这个需要提供zlmediakit的日志 看你提供的信息是流不存在 未注册成功。

**Comment by thjjava** [comment]
对，看zlmediakit的日志，是流没注册成功。不理解的是，在内网环境中是成功的，一旦到公网环境，就失败了。我把zlmediakit日志贴上来
![1](https://github.com/ZLMediaKit/ZLMediaKit/assets/7507156/13d7cfd8-49c5-4771-9933-9914c64cf13d)

**Comment by thjjava** [comment]
sdp中的视频编码是VP8和VP9这两种，在内网环境下webrtc推流成功了，但是换成公网环境就失败了。根据抓的zlmediakit服务器的包对比，发现公网环境是SRTP，而内网环境的是RTP，不知道是不是因为这个原因造成的。
![公网环境](https://github.com/ZLMediaKit/ZLMediaKit/assets/7507156/662f01ed-b5d2-4516-be37-43fd6a15f3ce)

**Comment by xia-chu** [comment]
externIP是否设置了？

**Comment by thjjava** [comment]
> externIP是否设置了？

设置了

**Comment by xia-chu** [comment]
用公网测试吧 ： https://zlmediakit.com/webrtc/

**Comment by xia-chu** [comment]
你这种问题无非是自己不看wiki 不看配置文件注释导致

**Comment by xia-chu** [comment]
vp9 不支持转协议 ， directProxy需要设置为1

**Comment by thjjava** [comment]
> vp9 不支持转协议 ， directProxy需要设置为1

directProxy改成1后就成功了，实在是没想到会是这个原因，在测试时，onPublish的返回结果中所有转协议的参数都是FALSE了，一直以为webrtc的推流跟rtsp的相关配置没多大关系，实在是不好意思，辛苦了！非常感谢！
