### ISSUE TITLE
[技术咨询] 使用GB28181推流延迟大概在5-10秒左右，并未达到500毫秒内，请问如何优化以减少延迟时间！

### ISSUE THREAD

**Issue by aihsi** [ZLMediaKit/ZLMediaKit#2703]
**咨询的功能模块**
- GB28181推流

**咨询的具体内容和问题**
- 延迟大概在5-10秒左右，并未达到500毫秒内，请问如何优化以减少延迟时间！
![D2E7E0AB-EC01-431e-8BEF-7443301CA402](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/0c350a39-cc14-4f0c-bfd9-138584052dc4)

**Comment by xia-chu** [comment]
请使用webrtc播放测试延时

**Comment by aihsi** [comment]
> 请使用webrtc播放测试延时

在使用webrtc播放时，直接播放是播放不了的，推流没有直接生成webrtc的播放地址，需要使用srs进行转换，比如RTMP to RTC，请问这个过程是必须的吗？
![5002B021-31B3-4e75-BB44-2FF91913996A](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/79acca03-a810-4650-a1a6-35ac82d5f969)
![315EBAD7-E8F2-4da7-A40F-13D99FD01E27](https://github.com/ZLMediaKit/ZLMediaKit/assets/82032727/eca8c7f3-bdee-42e6-bbfa-1393d731fef3)

**Comment by xia-chu** [comment]
zlm支持webrtc 你要开启该功能才行 请参考wiki webrtc篇

**Comment by xia-chu** [comment]
这个延时不是不是zlm导致的
