### ISSUE TITLE
ZLMediaKit的websocket协议

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#2705]
**咨询的功能模块**
请问ZLMediakit能作为wss加密协议的服务端吗？为什么我运行zlmediakit编译的websocket服务端测试程序，并用wss测试工具测试连接时，连接不上，并打印以下日志：
**咨询的具体内容和问题**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/56460673/fe0378c2-c468-4413-938c-934ad1d971ec)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
换衣是证书问题 你用default.pem这个证书吧 这个证书是合法有效的

**Comment by quxiaohui-debug** [comment]
是的，改了证书之后就可以运行了
