### ISSUE TITLE
[BUG] ip白名单allow_ip_range置空情况下不做限制无效

### ISSUE THREAD

**Issue by 31434116** [ZLMediaKit/ZLMediaKit#2706]
### 现象描述

allow_ip_range置空情况，访问http文件仍返回Your ip is not allowed to access the service.

**Comment by xia-chu** [comment]
`allow_ip_range=`是置空
`#allow_ip_range=` 不是置空
这个配置默认值不是空

**Comment by xia-chu** [comment]
更新下代码吧 这个bug修复了

**Comment by 31434116** [comment]
谢谢

**Comment by tongfuhu** [comment]
docker运行还是有问题，allow_ip_range=这样配置也不行

**Comment by xia-chu** [comment]
> docker运行还是有问题，allow_ip_range=这样配置也不行

你在docker内调用getServerConfig接口 把json粘贴上来

**Comment by tongfuhu** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/23081080/0e93a7e5-319c-4e63-b286-fab45eac8197)

**Comment by tongfuhu** [comment]
我看提示返回说少必要参数secret

**Comment by tongfuhu** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/23081080/44e51c30-91d8-49a5-a631-d82caacbbdac)

**Comment by tongfuhu** [comment]
{
        "code" : 0,
        "data" : 
        [
                {
                        "api.apiDebug" : "1",
                        "api.defaultSnap" : "./www/logo.png",
                        "api.secret" : "0VKonpXyOLgNhtvGhOs3oIr7y4UFpLii",
                        "api.snapRoot" : "./www/snap/",
                        "cluster.origin_url" : "",
                        "cluster.retry_count" : "3",
                        "cluster.timeout_sec" : "15",
                        "ffmpeg.bin" : "/usr/bin/ffmpeg",
                        "ffmpeg.cmd" : "%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
                        "ffmpeg.log" : "./ffmpeg/ffmpeg.log",
                        "ffmpeg.restart_sec" : "0",
                        "ffmpeg.snap" : "%s -i %s -y -f mjpeg -frames:v 1 %s",
                        "general.check_nvidia_dev" : "1",
                        "general.enableVhost" : "0",
                        "general.enable_ffmpeg_log" : "0",
                        "general.flowThreshold" : "1024",
                        "general.maxStreamWaitMS" : "15000",
                        "general.mediaServerId" : "your_server_id",
                        "general.mergeWriteMS" : "0",
                        "general.resetWhenRePlay" : "1",
                        "general.streamNoneReaderDelayMS" : "20000",
                        "general.unready_frame_cache" : "100",
                        "general.wait_add_track_ms" : "3000",
                        "general.wait_track_ready_ms" : "10000",
                        "hls.broadcastRecordTs" : "0",
                        "hls.deleteDelaySec" : "10",
                        "hls.fileBufSize" : "65536",
                        "hls.segDur" : "2",
                        "hls.segKeep" : "0",
                        "hls.segNum" : "3",
                        "hls.segRetain" : "5",
                        "hook.alive_interval" : "10.0",
                        "hook.enable" : "0",
                        "hook.on_flow_report" : "https://127.0.0.1/index/hook/on_flow_report",
                        "hook.on_http_access" : "https://127.0.0.1/index/hook/on_http_access",
                        "hook.on_play" : "https://127.0.0.1/index/hook/on_play",
                        "hook.on_publish" : "https://127.0.0.1/index/hook/on_publish",
                        "hook.on_record_mp4" : "https://127.0.0.1/index/hook/on_record_mp4",
                        "hook.on_record_ts" : "https://127.0.0.1/index/hook/on_record_ts",
                        "hook.on_rtp_server_timeout" : "https://127.0.0.1/index/hook/on_rtp_server_timeout",
                        "hook.on_rtsp_auth" : "https://127.0.0.1/index/hook/on_rtsp_auth",
                        "hook.on_rtsp_realm" : "https://127.0.0.1/index/hook/on_rtsp_realm",
                        "hook.on_send_rtp_stopped" : "https://127.0.0.1/index/hook/on_send_rtp_stopped",
                        "hook.on_server_exited" : "https://127.0.0.1/index/hook/on_server_exited",
                        "hook.on_server_keepalive" : "https://127.0.0.1/index/hook/on_server_keepalive",
                        "hook.on_server_started" : "https://127.0.0.1/index/hook/on_server_started",
                        "hook.on_shell_login" : "https://127.0.0.1/index/hook/on_shell_login",
                        "hook.on_stream_changed" : "https://127.0.0.1/index/hook/on_stream_changed",
                        "hook.on_stream_none_reader" : "https://127.0.0.1/index/hook/on_stream_none_reader",
                        "hook.on_stream_not_found" : "https://127.0.0.1/index/hook/on_stream_not_found",
                        "hook.retry" : "1",
                        "hook.retry_delay" : "3.0",
                        "hook.stream_changed_schemas" : "rtsp/rtmp/fmp4/ts/hls/hls.fmp4",
                        "hook.timeoutSec" : "10",
                        "http.allow_cross_domains" : "1",
                        "http.allow_ip_range" : "127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255",
                        "http.charSet" : "utf-8",
                        "http.dirMenu" : "1",
                        "http.forbidCacheSuffix" : "",
                        "http.forwarded_ip_header" : "",
                        "http.keepAliveSecond" : "30",
                        "http.maxReqSize" : "40960",
                        "http.notFound" : "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>\u60a8\u8bbf\u95ee\u7684\u8d44\u6e90\u4e0d\u5b58\u5728\uff01</h1></center><hr><center>ZLMediaKit(git hash:e628cba/2023-08-14T00:05:32+08:00,branch:master,build time:2023-08-13T16:07:25)</center></body></html>",
                        "http.port" : "80",
                        "http.rootPath" : "./www",
                        "http.sendBufSize" : "65536",
                        "http.sslport" : "443",
                        "http.virtualPath" : "",
                        "multicast.addrMax" : "239.255.255.255",
                        "multicast.addrMin" : "239.0.0.0",
                        "multicast.udpTTL" : "64",
                        "protocol.add_mute_audio" : "1",
                        "protocol.auto_close" : "0",
                        "protocol.continue_push_ms" : "15000",
                        "protocol.enable_audio" : "1",
                        "protocol.enable_fmp4" : "1",
                        "protocol.enable_hls" : "1",
                        "protocol.enable_hls_fmp4" : "0",
                        "protocol.enable_mp4" : "0",
                        "protocol.enable_rtmp" : "1",
                        "protocol.enable_rtsp" : "1",
                        "protocol.enable_ts" : "1",
                        "protocol.fmp4_demand" : "0",
                        "protocol.hls_demand" : "0",
                        "protocol.hls_save_path" : "./www",
                        "protocol.modify_stamp" : "2",
                        "protocol.mp4_as_player" : "0",
                        "protocol.mp4_max_second" : "3600",
                        "protocol.mp4_save_path" : "./www",
                        "protocol.rtmp_demand" : "0",
                        "protocol.rtsp_demand" : "0",
                        "protocol.ts_demand" : "0",
                        "record.appName" : "record",
                        "record.fastStart" : "0",
                        "record.fileBufSize" : "65536",
                        "record.fileRepeat" : "0",
                        "record.sampleMS" : "500",
                        "rtc.externIP" : "",
                        "rtc.port" : "8000",
                        "rtc.preferredCodecA" : "PCMU,PCMA,opus,mpeg4-generic",
                        "rtc.preferredCodecV" : "H264,H265,AV1,VP9,VP8",
                        "rtc.rembBitRate" : "0",
                        "rtc.tcpPort" : "8000",
                        "rtc.timeoutSec" : "15",
                        "rtmp.handshakeSecond" : "15",
                        "rtmp.keepAliveSecond" : "15",
                        "rtmp.port" : "1935",
                        "rtmp.sslport" : "0",
                        "rtp.audioMtuSize" : "600",
                        "rtp.h264_stap_a" : "1",
                        "rtp.lowLatency" : "0",
                        "rtp.rtpMaxSize" : "10",
                        "rtp.videoMtuSize" : "1400",
                        "rtp_proxy.dumpDir" : "",
                        "rtp_proxy.gop_cache" : "1",
                        "rtp_proxy.h264_pt" : "98",
                        "rtp_proxy.h265_pt" : "99",
                        "rtp_proxy.opus_pt" : "100",
                        "rtp_proxy.port" : "10000",
                        "rtp_proxy.port_range" : "30000-35000",
                        "rtp_proxy.ps_pt" : "96",
                        "rtp_proxy.timeoutSec" : "15",
                        "rtsp.authBasic" : "0",
                        "rtsp.directProxy" : "1",
                        "rtsp.handshakeSecond" : "15",
                        "rtsp.keepAliveSecond" : "15",
                        "rtsp.lowLatency" : "0",
                        "rtsp.port" : "554",
                        "rtsp.rtpTransportType" : "-1",
                        "rtsp.sslport" : "0",
                        "shell.maxReqSize" : "1024",
                        "shell.port" : "0",
                        "srt.latencyMul" : "4",
                        "srt.pktBufSize" : "8192",
                        "srt.port" : "9000",
                        "srt.timeoutSec" : "5"
                }
        ]
}

**Comment by tongfuhu** [comment]
发现问题了，解决了。谢谢。

**Comment by xiaonannet** [comment]
解决方案：allow_ip_range= （置为空，后面是一个空格）
然后重启容器即可
