### ISSUE TITLE
http请求响应ip问题

### ISSUE THREAD

**Issue by yuzhihaoGitHub** [ZLMediaKit/ZLMediaKit#2707]
对接问题

Your ip is not allowed to access the service.

2023-07-27 04:07:25.977 D [MediaServer] [7-event poller 0] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getServerConfig
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 43
Content-Type : application/x-www-form-urlencoded
Host : 192.168.8.86:8383
User-Agent : okhttp/4.10.0
# content:
secret=999c73f7-bb6b-4889-a715-d9eb2d1925cc
# response:
{
	"code" : -100,
	"msg" : "Your ip is not allowed to access the service."
}

<img width="668" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/53512354/6623df58-c046-45dc-9386-960a28c8f740">

没有看到IP相关配置还是192.168的网段有问题

**Comment by xia-chu** [comment]
更新下代码吧 这个bug修复了
