### ISSUE TITLE
[BUG] server never send EOF when stream is terminated

### ISSUE THREAD

**Issue by gdesmott** [ZLMediaKit/ZLMediaKit#2711]
- start  streaming to ZLMediaKit using OBS
- read this stream using a RTMP client (GStreamer in my case but it shouldn't matter)
- stop streaming from OBS by hitting the "Stop Streaming" button.
-  OBS sends `unpublish` and `deleteStream`
- client's connection is dropped but does not receive [`Stream EOF`](https://rtmp.veriskope.com/docs/spec/#717user-control-message-events) before.

Shouldn't the server send `EOF` before disconnecting the connection? If not, how the client can know if the stream was properly terminated by the sender?

**Comment by xia-chu** [comment]
How about this patch?
``` patch
Index: src/Rtmp/RtmpSession.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtmp/RtmpSession.cpp b/src/Rtmp/RtmpSession.cpp
--- a/src/Rtmp/RtmpSession.cpp	(revision a2a4e251ae870d186cb3e0d01fa49e83ba99b219)
+++ b/src/Rtmp/RtmpSession.cpp	(date 1690608525474)
@@ -327,6 +327,7 @@
         if (!strong_self) {
             return;
         }
+        strong_self->sendUserControl(CONTROL_STREAM_EOF/*or CONTROL_STREAM_DRY ?*/, STREAM_MEDIA);
         strong_self->shutdown(SockException(Err_shutdown,"rtmp ring buffer detached"));
     });
     src->pause(false);

```

**Comment by gdesmott** [comment]
> How about this patch? Please test it:

Thanks for the quick response.

That does work but `EOF` is also sent when the sender did not properly terminate the stream (on timeout), which I think is wrong (but I'm no RTMP expert).

**Comment by xia-chu** [comment]
> That does work but EOF is also sent when the sender did not properly terminate the stream (on timeout), which I think is wrong (but I'm no RTMP expert).

You should be right, but I think these details may not be significant.

Moreover, when implementing the rtmp protocol, zlmediakit did not strictly follow the specifications, which is more of an empirical implementation

**Comment by gdesmott** [comment]
> You should be right, but I think these details may not be significant.

Actually it is important for me, as the whole point here for me is to be able to distinguish between these two use cases:
- stream properly terminated because sender stopped it (`EOF` received)
- stream was terminated because of an error or timeout  (`EOF` not received)

Does that make sense?

**Comment by xia-chu** [comment]
Yes, this makes sense, but it requires a high level of developer demand, and many SDKs do not recall this information

**Comment by xia-chu** [comment]
Currently, this eof message can only be sent when the rtmp push terminates， 
But why the pusher is disconnected, whether it has timeout or deleted the stream, cannot be determined。

**Comment by xia-chu** [comment]
Additionally, it should be noted that there are many ways to generate rtmp streams, and not all rtmp streams are generated by rtmp push streams

**Comment by gdesmott** [comment]
So what would the right way forward here? What would you suggest to applications needing to know if a stream has been properly terminated or not?

**Comment by xia-chu** [comment]
If we want to know this reason, we need to modify a lot of underlying code

**Comment by gdesmott** [comment]
> However, as for why this RTMP stream ended, we cannot know the reason at present

Then that won't help I'm afraid. :(

**Comment by xia-chu** [comment]
Closed this issue. 
This is not easy to do. Let's approach it this way first.
Thanks!
