### ISSUE TITLE
AAC error message

### ISSUE THREAD

**Issue by ParhamJ** [ZLMediaKit/ZLMediaKit#2726]
I have a question about supporting AAC in RTSP. When we use AAC in live streaming via RTSP, we encounter an error message in the console, but the output stream has an audio stream in AAC. Do you think we can ignore the notice?
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/a4d365b6-2453-433a-a2c3-f8a9e79d087d)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/c4d777e3-cb7c-4a02-b9bb-71207eaf51c8)

**Comment by ParhamJ** [comment]
I have a question about supporting AAC in RTSP. When we use AAC in live streaming via RTSP, we encounter an error message in the console, but the output stream has an audio stream in AAC. Do you think we can ignore the notice?
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/581722f7-fa7b-4e8c-a483-bd4cc8d6cd1a)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/2919c944-a42d-49ae-a65e-b1be07ffa15f)

**Comment by xia-chu** [comment]
This stream is very strange. Can you provide the rtsp capture file for this stream？

**Comment by ParhamJ** [comment]
Sure, this is the pcap file and the warning message:
![39b73c119ec61da0441cf40e1d6187c](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/8c3872b8-717c-4624-8749-8fa528d8e424)
[rtsp_s.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12231454/rtsp_s.zip)

**Comment by xia-chu** [comment]
I mean, using zlmediakit to capture packets while playing this stream
