### ISSUE TITLE
最新的docker镜像拉取启动失败，报错please modify the configuration named api.secret in ../conf/config.ini

### ISSUE THREAD

**Issue by dzhblj** [ZLMediaKit/ZLMediaKit#2727]
### 现象描述

使用docker pull命令拉取最新镜像，用以下命令启动报错main.cpp:396 start_main | Start server failed: please modify the configuration named api.secret in ../conf/config.ini)

### 如何复现?

1. 使用docker pull zlmediakit/zlmediakit:master命令拉取最新镜像
2. 使用如下命令启动镜像：docker run -id -p 1935:1935 -p 8080:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp zlmediakit/zlmediakit:master

### 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/139786391/e92b2474-8c1e-4363-800e-b1c6250d03b3)

**Comment by kangxiaojia0** [comment]
修改config.ini中secret的参数,修改代码后限制使用默认secret。

**Comment by zhoudg123456** [comment]
这个问题错误在Ubuntu22.04上，运行./MediaServer 的时候也碰到了，
2023-07-31 15:45:39.734 E [MediaServer] [12193-MediaServer] main.cpp:396 start_main | Start server failed: please modify the configuration named api.secret in /home/robot/ZLMediaKit/release/linux/Debug/config.ini
不知道如何解决

**Comment by dzhblj** [comment]
> 

镜像无法启动，进入不了容器，请问这种情况应该如何修改config.ini中的secret的参数并限制使用默认secret呢

**Comment by dzhblj** [comment]
> 修改config.ini中secret的参数,修改代码后限制使用默认secret。

镜像无法启动，进入不了容器，请问这种情况应该如何修改config.ini中的secret的参数并限制使用默认secret呢

**Comment by xia-chu** [comment]
启动镜像前挂载映射下配置文件即可 默认secret已经被禁用了

**Comment by zhoudg123456** [comment]
sudo ./MediaServer -c config.ini 也是报同样的错误

**Comment by dzhblj** [comment]
> 启动镜像前挂载映射下配置文件即可 默认secret已经被禁用了

试了启动的时候挂载配置文件仍然报错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/139786391/d6b36117-ab25-4edb-b803-71ebc9d6f2d9)
配置文件如下：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/139786391/5b7c3472-f2dc-46c8-b135-86c631a1e40a)

**Comment by zhoudg123456** [comment]
在main.cpp中
if (secret == "035c73f7-bb6b-4889-a715-d9eb2d1925cc" || secret.empty()) {
                // 使用默认secret被禁止启动
                throw std::invalid_argument("please modify the configuration named " + API::kSecret + " in " + g_ini_file);
            }

因此只要把secret 在config.ini中随便改一下，就可以OK，我这边已经成功启动了

**Comment by dzhblj** [comment]
> 启动镜像前挂载映射下配置文件即可 默认secret已经被禁用了
非常感谢，我的问题解决了，一开始试了将之前没有使用docker容器部署的服务配置文件拷贝过来挂载到容器下不行，后来想了一下我当时在centos上直接部署的时候使用的还是默认的secret，我将配置文件中的默认secret修改了之后重新启动容器挂载成功了

**Comment by dzhblj** [comment]
> 启动镜像前挂载映射下配置文件即可 默认secret已经被禁用了
非常感谢，我的问题解决了，一开始试了将之前没有使用docker容器部署的服务配置文件拷贝过来挂载到容器下不行，后来想了一下我当时在centos上直接部署的时候使用的还是默认的secret，我将配置文件中的默认secret修改了之后重新启动容器挂载成功了

**Comment by dzhblj** [comment]
> sudo ./MediaServer -c config.ini 也是报同样的错误


非常感谢，我的问题解决了，一开始试了将之前没有使用docker容器部署的服务配置文件拷贝过来挂载到容器下不行，后来想了一下我当时在centos上直接部署的时候使用的还是默认的secret，我将配置文件中的默认secret修改了之后重新启动容器挂载成功了

**Comment by dzhblj** [comment]
> 在main.cpp中 if (secret == "035c73f7-bb6b-4889-a715-d9eb2d1925cc" || secret.empty()) { // 使用默认secret被禁止启动 throw std::invalid_argument("please modify the configuration named " + API::kSecret + " in " + g_ini_file); }
> 
> 因此只要把secret 在config.ini中随便改一下，就可以OK，我这边已经成功启动了

恭喜成功上岸，哈哈

**Comment by zhaozhi1995** [comment]
只有我修改了config.ini中的secret还是运行不了吗，还有什么要注意的吗？尴尬。。。
