### ISSUE TITLE
[技术咨询] 录制是默认开启的吗

### ISSUE THREAD

**Issue by song01** [ZLMediaKit/ZLMediaKit#2729]
**咨询的功能模块**
- 录制对所有类型的流是默认开启的吗？可以关闭吗？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
不是 可以关闭，
addStreamProxy、on_publish 都可以选择关闭。

如果api不控制 最后读取配置文件配置enable_mp4.

**Comment by song01** [comment]
好的，谢谢
