### ISSUE TITLE
addStreamProxy接口 多个线程调用 拉取同一个离线的rtsp流 会出现部分code为0的情况

### ISSUE THREAD

**Issue by yxw13141618** [ZLMediaKit/ZLMediaKit#2731]
### 现象描述

多个请求调用addStreamProxy 拉取离线的rtsp流 部分请求会返回code为0 即认为取到流了。
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**: bd7982ecc1e5394adcf8a73eff7c6bdf8f9e73d1
* **操作系统及版本**:CentOS 8
* **硬件信息**:Intel
* **其他需要补充的信息**:怀疑是多个线程贡献数据结构，导致出现的问题

**Comment by xia-chu** [comment]
这是你的调用的bug 不能多线程同时用相同参数调用这个接口
重复调用统统返回0

**Comment by xia-chu** [comment]
因为需要先占位 否则会存在重复请求问题

**Comment by yxw13141618** [comment]
> 因为需要先占位 否则会存在重复请求问题

收到 谢谢大佬 我来改一下
