### ISSUE TITLE
[BUG] 无法读取 config.ini，导致无法运行 [严重]

### ISSUE THREAD

**Issue by dodu2014** [ZLMediaKit/ZLMediaKit#2732]
### 现象描述

windows 环境下编译后，无法运行，提示
``` txt
start_main | Start server failed: please modify the configuration named api.secret in D:/works/AKStream/ZLMediaKit/release/windows/Release/config.ini
```

切换到 a31108cc5102ebd515f5b0622d2012b6c16338c7 提交，无此问题，运行正常

### 如何复现?

更新到 bd7982ecc1e5394adcf8a73eff7c6bdf8f9e73d1 提交后，windows 环境编译，运行就报错。已成功复现多次

### 相关日志或截图

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15245544/b6c9a4ca-9bea-4d87-ba49-a7a0cea5d92f)

### 各种环境信息

* **代码提交记录/git commit hash**: bd7982ecc1e5394adcf8a73eff7c6bdf8f9e73d1
* **操作系统及版本**: win11 22h2
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by Dw9** [comment]
#2700 
是我们的日志提示的不够明显么...
please modify the configuration named api.secret in 

> D:/works/AKStream/ZLMediaKit/release/windows/Release/config.ini

**Comment by dodu2014** [comment]
config.ini 中是有 secret 的配置的，可是 bd7982ecc1e5394adcf8a73eff7c6bdf8f9e73d1 下，无法识别，一直提示这个问题

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15245544/acdd324a-97bc-4a17-b37e-96cb65bc2789)

**Comment by Dw9** [comment]
modify 修改 调整
为了安全 禁止使用默认的secret 请随意修改这个参数
