### ISSUE TITLE
[功能请求] vcpkg 自动编译请求

### ISSUE THREAD

**Issue by sang8052** [ZLMediaKit/ZLMediaKit#2733]
**描述该功能的用处，可以提供相关资料描述该功能**
vcpkg 是什么经常玩c++ 的大佬都知道这里就不废话了
上架vcpkg 不经可以大幅度的提高 zlmediakit 的知名度（借微软的鸡下蛋），还能方便c++ 开发 

已经向 vcpkg 提交了该 issue 
https://github.com/microsoft/vcpkg/issues/32886

**Comment by wasphin** [comment]
之前印象中不太接收应用类的 port，估计还得自己提 pr

**Comment by JackBoosY** [comment]
要不我来加？

**Comment by wasphin** [comment]
> 要不我来加？国人的东西我得支持一下哈哈

可以的。子模块需要拆成单独移植，jsoncpp 有现成的，zltoolkit、media-server、zlmediakit 需要新加。不确定是不是都需要有正式的 tag 版本信息。

**Comment by JackBoosY** [comment]
link: https://github.com/microsoft/vcpkg/pull/33024

**Comment by wasphin** [comment]
看已经合入 vcpkg 了，这个先关了，感谢 @JackBoosY
