### ISSUE TITLE
[技术咨询] webrtc播放时关于onPlay鉴权问题

### ISSUE THREAD

**Issue by wuchingyy** [ZLMediaKit/ZLMediaKit#2735]
rtmp的拉流播放，触发onPlay的对端端口参数是rtmp连接的端口，而webrtc播放触发的onPlay得到的对端端口是获取sdp的HttpSession的对端端口，这样会导致后续使用kick_session api时无法提供准确的port参数

这个是否可以在webrtc建立连接的时候再触发onPlay的hook呢？

**Comment by xia-chu** [comment]
确实存在这个问题 但是办不到啊。
你只能先getAllSession 然后再kick。

**Comment by xia-chu** [comment]
触发webrtc on_publish/on_play hook时 webrtc还没建联成功呢，只是创建好对象，交换sdp了；还要等对方stun/dtls握手

**Comment by xia-chu** [comment]
另外webrtc支持连接迁移和多连接 你kick_session意义不大

**Comment by wuchingyy** [comment]
但是有个尴尬的情况就是，由于没有强对应的关系（连接和具体用户），调用kick_session或者kick_sessions，只传入ip的话，会导致相同局域网的连接全部被踢掉。。。

**Comment by xia-chu** [comment]
> 但是有个尴尬的情况就是，由于没有强对应的关系（连接和具体用户），调用kick_session或者kick_sessions，只传入ip的话，会导致相同局域网的连接全部被踢掉。。。

正确踢人的方法是 用户获取客户端列表 你ui展示出客户端地址以及类型 管理员自行决定是否踢人。

**Comment by xia-chu** [comment]
on_play回调客户端ip给你是用于网络过滤的 做安全认证的 不是给你事后踢人用的
