### ISSUE TITLE
[技术咨询] addStreamProxy流没有转码

### ISSUE THREAD

**Issue by zhouanche** [ZLMediaKit/ZLMediaKit#2736]
原因：浏览器无法播放H265的流，使用addStreamProxy接口拉取265的流然后转换成hls或者264给前端浏览器直接播放
结果：直接拼接请求播放地址（示例 http://127.0.0.1/live/0/hls.m3u8?vhost=somedomain.com）浏览器仍然没法播放（有进度条没画面），但是vlc播放器可以播放，显示仍然是H265编码
求：为什么会转换失败？配置是默认配置，请求参数enable_hls=true已经加上

**Comment by xia-chu** [comment]
这个接口不支持转码 转码需要用addFFmpegSource接口
