### ISSUE TITLE
[技术咨询] 源站怎么设置

### ISSUE THREAD

**Issue by chen-tj** [ZLMediaKit/ZLMediaKit#2738]
**咨询的功能模块**
- 设置源站拉流

**咨询的具体内容和问题**
- 在zlmediakit配置文件中设置多个源站拉流，如何配置每个源站拉到的流对应的推流路径？
![q](https://github.com/ZLMediaKit/ZLMediaKit/assets/50590343/90434184-ea0b-44db-a579-605838ff86fa)

**Comment by xia-chu** [comment]
摄像头不是源站，你要zlm拉流代理 请查看addStreamProxy接口

**Comment by chen-tj** [comment]
> 摄像头不是源站，你要zlm拉流代理 请查看addStreamProxy接口

感谢回复，已了解！
