### ISSUE TITLE
 能支持 vcodec jpeg2000 推流到RTSP server吗？

### ISSUE THREAD

**Issue by ioniconline** [ZLMediaKit/ZLMediaKit#2744]
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> jpeg2000 (libopenjpeg))
Press [q] to stop, [?] for help
[rtp @ 0x559e20c30bc0] Unsupported codec jpeg2000
[out#0/rtsp @ 0x559e209aaa40] Could not write header (incorrect codec parameters ?): Operation not permitted
Error while filtering: Operation not permitted
[out#0/rtsp @ 0x559e209aaa40] Nothing was written into output file, because at least one of its streams received no packets.

**Comment by xiongguangjie** [comment]
不行，如果你是要direct_proxy 设置为1 ,应该可以rtsp推流rtsp播放 ，现在rtsp 服务器支持mjpeg 类似如下推流命令 
.\ffmpeg.exe -re -stream_loop -1  -i .\test.mp4  -c:v mjpeg  -pix_fmt yuv420p -color_range jpeg -huffman 0 -force_duplicated_matrix 1   -c:a copy  -f rtsp -rtsp_transport tcp rtsp rtsp://x.x.x.x/live/tet

**Comment by ioniconline** [comment]
> 不行，如果你是要direct_proxy 设置为1 ,应该可以rtsp推流rtsp播放 ，现在rtsp 服务器支持mjpeg 类似如下推流命令 .\ffmpeg.exe -re -stream_loop -1 -i .\test.mp4 -c:v mjpeg -pix_fmt yuv420p -color_range jpeg -huffman 0 -force_duplicated_matrix 1 -c:a copy -f rtsp -rtsp_transport tcp rtsp rtsp://x.x.x.x/live/tet

谢谢回复，mjpeg是没有问题的，我想了解下JPEG2000的流改如何推呢？ 还有其他办法吗？

**Comment by xiongguangjie** [comment]
> > 不行，如果你是要direct_proxy 设置为1 ,应该可以rtsp推流rtsp播放 ，现在rtsp 服务器支持mjpeg 类似如下推流命令 .\ffmpeg.exe -re -stream_loop -1 -i .\test.mp4 -c:v mjpeg -pix_fmt yuv420p -color_range jpeg -huffman 0 -force_duplicated_matrix 1 -c:a copy -f rtsp -rtsp_transport tcp rtsp rtsp://x.x.x.x/live/tet
> 
> 谢谢回复，mjpeg是没有问题的，我想了解下JPEG2000的流改如何推呢？ 还有其他办法吗？

https://datatracker.ietf.org/doc/rfc5371/

ffmpeg的rtsp 不支持 jpeg2000，但是live555 是支持的，而且也有相应的rtp 打包标准，如果你需要ZLM支持，需要二次开发

**Comment by ioniconline** [comment]
> 

ZLM是基于ffmpeg的rtsp 吗？

**Comment by xiongguangjie** [comment]
> > 
> 
> ZLM是基于ffmpeg的rtsp 吗？

不是的

**Comment by ioniconline** [comment]
你好，我想请教下如何使用live555 推 jpeg2000的视频流？
