### ISSUE TITLE
Start server failed: please modify the configuration named api.secret

### ISSUE THREAD

**Issue by feiyangqingyun** [ZLMediaKit/ZLMediaKit#2745]
./ZLMediaKit -d &
 [MediaServer] [25392-MediaServer] main.cpp:396 start_main | Start server failed: please modify the configuration named api.secret in /home/liu/ZLMediaKit/release/linux/Release/config.ini

**Comment by xiongguangjie** [comment]
can't use default api secret , because network safe , avoid be attacked

**Comment by github4529** [comment]
使用docker镜像，由于这个原因无法启动容器，而启动不了容器就修改不了配置文件

2023-08-08 11:12:59.595 E [MediaServer] [7-MediaServer] main.cpp:396 start_main | Start server failed: please modify the configuration named api.secret in ../conf/config.ini

死循环了

**Comment by tjfyjp** [comment]
使用docker镜像时，可以把配置文件挂载出来，然后通过修改宿主机上的config.ini，然后再启动容器可以解决。

**Comment by feiyangqingyun** [comment]
> 要不默认随机一个吧 跟mediaServerId一样 一定要手动修改 这个改动真是的不太好

是的，旧版本都没有这个问题。

**Comment by xia-chu** [comment]
> rverId一样 一定要手动修改 这个改动真是的不太

后面改成随机 然后打印出来吧

**Comment by zhang2349** [comment]
> > rverId一样 一定要手动修改 这个改动真是的不太
> 
> 后面改成随机 然后打印出来吧 不过这样会有个问题 就是每次启动secret都不一样了

mediaServerId是默认空的 然后随机一个  随机了之后会保存住的呀 后面就不变了

**Comment by xia-chu** [comment]
> mediaServerId是默认空的 然后随机一个 随机了之后会保存住的呀 后面就不变了

不会 如果删除配置文件 才会生成配置文件并持久化 否则每次重启 都是随机的

**Comment by xia-chu** [comment]
最新代码不会直接退出了 会改成随机secret并持久化。

**Comment by feiyangqingyun** [comment]
现在编译后是能正常运行了，不会提示Start server failed: please modify the configuration named api.secret ，但是又多了新问题，rtsp拉流无法播放了

**Comment by xia-chu** [comment]
> 现在编译后是能正常运行了，不会提示Start server failed: please modify the configuration named api.secret ，但是又多了新问题，rtsp拉流无法播放了

你要分析zlmediakit日志

**Comment by googleweb** [comment]
`function get_media_list() {
        let url = document.location.protocol+"//"+window.location.host+"/index/api/getMediaList?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc";
        let json = getData(url);
        json.then((json)=> fillStreamList(json));
      }
      setInterval(() => {
       // get_media_list();
      }, 5000);
`

docker webrtc页面的secret是默认的, 定时器里的get_media_list();是被注释掉的，页面不能刷新播放列表。
而且config.ini里secret是随机生成的，config.ini里修改了也不行，重启docker还是随机的。webrtc页面不能用啊，http://zlmediakit.com:8888/webrtc/却是可以的。

导致docker很尴尬，secret随机,页面固定，刷新media_list的函数还被注释，没法用，只能自己编译了。

**Comment by xia-chu** [comment]
网页获取流列表功能已经去掉了

**Comment by googleweb** [comment]
我已经收到您的信件!
