### ISSUE TITLE
[Technical Consultation] Request for Technical Consultation Regarding the startsendrtp Interface

### ISSUE THREAD

**Issue by MengFanLu1** [ZLMediaKit/ZLMediaKit#2747]
**Functionality Module of Inquiry**
- startsendrtp interface

**Specific Content and Questions of Inquiry**
- Whether the startsendrtp interface can push a specific audio file in the ZLMediaKit directory. There is a requirement to send voice files in the business at present, can we increase the interface to read a specific file in a specified directory and push it?

**Notes**
- Before seeking technical consultation, please carefully read the README and [wiki](https://github.com/xia-chu/ZLMediaKit/wiki). If necessary, you can also search for already responded issues simultaneously, and only create an issue if you haven't found an answer.

- Technical consultation does not belong to bug defects. Users are required to star (favorite) this project first, otherwise issues will be closed directly.

>**咨询的功能模块**
- startsendrtp接口

**咨询的具体内容和问题**
- startsendrtp接口是否能推送zlmediakit目录下的某一个音频文件，现在业务中有下发语音文件的需求，是否可以增加读取指定目录的某一个文件进行推送的接口。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
startSendRtp 支持加载mp4文件，参数from_mp4设置为1，app设置为record， stream设置为文件相对路径(放在record目录下)即可

**Comment by MengFanLu1** [comment]
> startSendRtp 支持加载mp4文件，参数from_mp4设置为1，app设置为record， stream设置为文件相对路径(放在record目录下)即可
好的，谢谢，测试后给你反馈

**Comment by MengFanLu1** [comment]
我现在有个疑问，我使用WEBRTC推流，ZLMEDIAKIT会把WEBRTC推的流落到本地，生成一个MP4文件，我看这个MP4文件的音频格式是PCM,MP4格式的文件是不支持PCM的音频的，作者是怎么做到的，修改ffmpeg了吗？我使用ffmpeg录制MP4文件时，指定音频格式为PCM，会报错，指定音频格式为AAC就可以录制

**Comment by xia-chu** [comment]
你ffmpeg命令咋写的?

**Comment by MengFanLu1** [comment]
> 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42708971/b1f10e80-7eaa-4663-bec0-fec81ff0b072)

**Comment by MengFanLu1** [comment]
> 你ffmpeg命令咋写的?

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42708971/bfa554b2-f061-4bab-b1a0-a79021e27ba4)

**Comment by MengFanLu1** [comment]
> 你ffmpeg命令咋写的?

我的国标28181实时对讲做出来了，我想着做个下发语音文件的模块，我现在尝试了
1.使用ffmpeg录制MP4，只有音频，音频格式为aac，放到record目录下，调用startsendrtp去推送，设备可以收到，但是全是杂音，是音频编码的问题
2.使用ffmpeg录制MP4，只有音频，音频格式为pcma，录制失败
3.使用ffmpeg录制wav格式的文件，音频格式为pcma，调用startsendrtp去推送，失败，startsendrtp只支持MP4的文件
4.市面上的设备还都得是PCMA的音频才可以
5.使用webrtc推流落到本地的文件，指定这个文件推送到设备，可以成功。

**Comment by xia-chu** [comment]
startSendRtp支持推送aac的mp4的 你用的ps还是es模式

**Comment by MengFanLu1** [comment]
> startSendRtp支持推送aac的mp4的 你用的ps还是es模式
ps和es都试过了，ps是96，es是8，都不行
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42708971/1426517e-0696-453c-a76e-4ff66aa96b7a)

**Comment by xia-chu** [comment]
你要用ps模式，es模式 aac rtp没法传adts头 对方无法解码的

**Comment by MengFanLu1** [comment]
> 你要用ps模式，es模式 aac rtp没法传adts头 对方无法解码的

不好意思，我没明白你所说的，难道ps模式我参数传错了，不是use_ps=1就是ps模式吗

**Comment by xia-chu** [comment]
> 不好意思，我没明白你所说的，难道ps模式我参数传错了，不是use_ps=1就是ps模式吗
use_ps=1是ps模式 我是说 这样应该没问题的 你可以推给zlmediakit本身试试

**Comment by MengFanLu1** [comment]
> > 不好意思，我没明白你所说的，难道ps模式我参数传错了，不是use_ps=1就是ps模式吗
> 
> use_ps=1是ps模式 我是说 这样应该没问题的 你可以推给zlmediakit本身试试

好的，我测试下，谢谢，我有个疑问，为啥webrtc推流，保存到zlmediakit的MP4文件的音频可以是pcm的

**Comment by xia-chu** [comment]
这个用的第三方库 ffmpeg不支持生成g711的MP4 但是却可以播放

**Comment by MengFanLu1** [comment]
> 这个用的第三方库 ffmpeg不支持生成g711的MP4 但是却可以播放

好的，谢谢
