### ISSUE TITLE
[技术咨询]用工具 推400路rtmp流给zlmediakit，然后关闭推流工具，zlmediakit内存不释放，长时间也不会释放

### ISSUE THREAD

**Issue by daimalvtu** [ZLMediaKit/ZLMediaKit#2753]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
反复多次这样测试 会导致zlm oom吗？这个不一定是内存泄露问题 跟malloc的策略有关

**Comment by daimalvtu** [comment]
不会，内存只会保持在实时节目数最高值的内存值，并不会持续增长

**Comment by xia-chu** [comment]
不会增长就不用理会
