### ISSUE TITLE
[技术咨询] 添加ffmpeg拉流代理5个cpu占用就达到100%以上

### ISSUE THREAD

**Issue by KingHang** [ZLMediaKit/ZLMediaKit#2754]
**咨询的功能模块**
添加ffmpeg拉流代理5个cpu占用就达到100%以上

**咨询的具体内容和问题**
- 添加ffmpeg拉流代理5个，i7 3632QM，8G内存的机器cpu占用就达到100%了，有什么办法可以降低这个占用吗

**Comment by xia-chu** [comment]
这是舆情行为 请修改配置文件ffmpeg模板参数

**Comment by KingHang** [comment]
可以给一个方向吗？调整哪个相关参数可以，谢谢大佬

**Comment by alexliyu7352** [comment]
拉取http-ts, htt-flv流(不转码)
cmd=%s -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
-reconnect_delay_max 60 -user_agent ZLMediaKit -err_detect ignore_err
-fflags +discardcorrupt -re -i %s  -c:v copy -c:a copy -bsf:a aac_adtstoasc
-flvflags no_duration_filesize -f flv %s
拉取hls流(不转码)
hls_cmd=%s -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max
60 -user_agent ZLMediaKit -err_detect ignore_err -fflags +discardcorrupt
-re -i %s  -c:v copy -c:a copy -bsf:a aac_adtstoasc -flvflags
no_duration_filesize -f flv %s
拉取rtmp流(不转码)
cmd_rtmp=%s -re -i %s  -c:v copy -c:a copy -bsf:a aac_adtstoasc -flvflags
no_duration_filesize -f flv %s
以下为转码的, 具体请根据协议更改, 如果是hls就去掉reconnect_at_eof参数, 如果不是http协议, 就去掉http协议的参数
cmd_h264=%s -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
-reconnect_delay_max 60 -user_agent ZLMediaKit -err_detect ignore_err
-fflags +discardcorrupt -re -i %s  -c:v libx264 -preset ultrafast -c:a copy
-bsf:a aac_adtstoasc -flvflags no_duration_filesize -f flv %s
cmd_h264_aac=%s -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
-reconnect_delay_max 60 -user_agent ZLMediaKit -err_detect ignore_err
-fflags +discardcorrupt -re -i %s  -c:v libx264 -preset ultrafast -c:a aac
-ac 2 -ar 44100 -b:a 128k -bsf:a aac_adtstoasc -flvflags
no_duration_filesize -f flv %s
cmd_aac=%s -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
-reconnect_delay_max 60 -cache_redirect 0 -user_agent
ZLMediaKit -err_detect ignore_err -correct_ts_overflow 0 -avoid_negative_ts
disabled -max_interleave_delta 0 -copyts -fflags +discardcorrupt -fflags
+genpts -vsync 0  -nofix_dts -re -i %s -map 0:v -map 0:a:0 -c:v copy  -c:a
aac -ac 2 -ar 44100 -b:a 128k -bsf:a aac_adtstoasc -flvflags
no_duration_filesize -f flv %s
cmd_h264_aac_baseline=%s -reconnect 1 -reconnect_at_eof 1
-reconnect_streamed 1 -reconnect_delay_max 60 -cache_redirect 0 -user_agent
ZLMediaKit -err_detect ignore_err -i %s -map 0:v -map 0:a:0 -c:v libx264
-profile:v baseline -preset veryfast -b:v 2560k -bufsize 2560k -maxrate
3000k -g 100 -c:a aac -ac 2 -ar 44100 -b:a 128k -bsf:a aac_adtstoasc
-flvflags no_duration_filesize -f flv %s
cmd_h264_aac_high=%s -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1
-reconnect_delay_max 60 -cache_redirect 0 -user_agent
ZLMediaKit -err_detect ignore_err -i %s -map 0:v -map 0:a:0 -c:v libx264
-preset veryfast -b:v 2560k -bufsize 2560k -maxrate 3000k -g 100 -c:a aac
-ac 2 -ar 44100 -b:a 128k -bsf:a aac_adtstoasc -flvflags
no_duration_filesize -f flv %s


KingHang ***@***.***> 于2023年8月10日周四 16:46写道：

**Comment by KingHang** [comment]
> 

感谢大佬
