### ISSUE TITLE
[编译问题] 编译时报错，main.cpp;396 start matnStart server failed: please modify the configuration named api.secret

### ISSUE THREAD

**Issue by sily-wei** [ZLMediaKit/ZLMediaKit#2755]
运行环境是Ubuntu ，有没有哪个大佬遇见过 给解释解释
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/56421731/3f153dc7-0a8d-4d1b-8f0b-32848ccec1d7)

**Comment by xia-chu** [comment]
就是字面意思 自己看日志
