### ISSUE TITLE
zlmediakit 使用docker部署，使用的是阿里云的ssl证书, 用https 访问失败

### ISSUE THREAD

**Issue by JonouZ** [ZLMediaKit/ZLMediaKit#2761]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by JonouZ** [comment]
我照着文档里面的https设置配置了一遍，然后启动也成功了，wvp我也设置 了https ，用https地址访问的时候，还是不行

**Comment by xia-chu** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD

**Comment by JonouZ** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD

我就是照这个文档配置的，也成功了出现了域名的日志，但是用https+域名访问的时候就不对了，访问不了

**Comment by xia-chu** [comment]
说明你需要购买域名和证书

**Comment by JonouZ** [comment]
> 说明你需要购买域名和证书

谢谢你，这个问题已经解决了，因为我用的是docker部署的，然后容器中的端口和宿主机的端口有冲突，导致的访问不了，也希望对大家有所帮助

**Comment by JamonLu** [comment]
我现在是同样的问题 ，想问下怎么解决的牙
