### ISSUE TITLE
[功能请求] hook 请求参数优化

### ISSUE THREAD

**Issue by hanxiang-li** [ZLMediaKit/ZLMediaKit#2762]
hook有些参数带有下划线，有些没有，建议统一一下
<img width="551" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/45918130/7c9ae3cc-1543-4c26-bc58-1ec3eebf1b62">

**Comment by xia-chu** [comment]
只能将错就错了 大规模修改会导致兼容性问题

**Comment by xia-chu** [comment]
感谢反馈！

**Comment by linkewei0580** [comment]
> 感谢反馈！

可以修改之前和修改之后的并存
