### ISSUE TITLE
[技术咨询] zlmediakit 部署 开启https

### ISSUE THREAD

**Issue by lasigou** [ZLMediaKit/ZLMediaKit#2763]
**咨询的功能模块**
zlmediakit开启https
使用生成SSL自签名证书并测试

**咨询的具体内容和问题**
日志打印：
[MediaServer] [750-event poller 0] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by JonouZ** [comment]
我也遇到这个问题，后来我换成了阿里的ssl证书，可以启动，但是https访问不了，http的视频可以观看

**Comment by xia-chu** [comment]
别用自签名的 请参考这个[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD)

**Comment by lasigou** [comment]
> 别用自签名的 请参考这个[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD)

**Comment by lasigou** [comment]
> 别用自签名的 请参考这个[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD)
没有域名可以弄成https吗

**Comment by xia-chu** [comment]
> > 别用自签名的 请参考这个[wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%8E%E4%B9%88%E5%BC%80%E5%90%AFhttps%E7%9B%B8%E5%85%B3%E5%8A%9F%E8%83%BD)
> 
> 没有域名可以弄成https吗

可是可以 不过需要浏览器信任 不过你既然提这个问题 估计你搞不定

**Comment by xia-chu** [comment]
zlmediakit自带default.pem这个证书 可以测试https

**Comment by 1239440286** [comment]
为什么我打开127.0.0.1显示404

**Comment by xia-chu** [comment]
> 为什么我打开127.0.0.1显示404

mkdir www
