### ISSUE TITLE
公司内网访问hls播放流，只有一台电脑能访问成功 

### ISSUE THREAD

**Issue by Liudibo123** [ZLMediaKit/ZLMediaKit#2764]
我的ZLMediaKit部署在阿里云服务器上，通过公司能忘访问hls播放流只能有一台电脑访问成功，通过外网访问没问题，麻烦大佬帮忙解答下，谢谢。。

**Comment by lystormenvoy** [comment]
问问题提供的信息太少，甚至舍不得配个图

**Comment by Liudibo123** [comment]
公司内网访问，在服务器那边IP是一样的，只有固定的一台电脑可以正常播放，其他电脑播放取流都是没有响应

**Comment by xia-chu** [comment]
这个应该是hls播放跨域导致不支持cookie导致的 目前访问http文件默认是不允许公网访问的，所以如果hls不支持cookie的情况下 是不允许访问ts文件的

**Comment by xia-chu** [comment]
两种解决方案，
- 1、不要跨域，让hls播放器支持cookie。
- 2、配置文件allow_ip_range置空，这样公网ip就能访问http文件和http api了，但是这样有安全风险。

**Comment by xia-chu** [comment]
考虑了良久 决定针对这个问题不做任何修改，我们不打算对ts切片的访问做任何特殊的授权放行，因为这样也会导致直播流的泄露。
