### ISSUE TITLE
hls取流失败

### ISSUE THREAD

**Issue by Liudibo123** [ZLMediaKit/ZLMediaKit#2766]
我的ZLMediaKit部署在阿里云服务器上，通过公司能忘访问hls播放流只能有一台电脑访问成功，通过外网访问没问题，麻烦大佬帮忙解答下，谢谢。。
公司内网访问，在服务器那边IP是一样的，只有固定的一台电脑可以正常播放，其他电脑播放取流都是没有响应

![正常报文](https://github.com/ZLMediaKit/ZLMediaKit/assets/34958165/c3d6e58a-bd30-488d-b291-14338bef52f1)

![非正常报文](https://github.com/ZLMediaKit/ZLMediaKit/assets/34958165/889785b1-0afc-4424-8e00-b1ef182c04b7)
![取流失败](https://github.com/ZLMediaKit/ZLMediaKit/assets/34958165/96ea3b9a-e2bb-49df-bb75-f6d4de9fd5e0)
![1692240053821](https://github.com/ZLMediaKit/ZLMediaKit/assets/34958165/35e69ffd-0ea7-4b31-ae55-d9e9b7ea130e)

**Comment by xia-chu** [comment]
访问ts文件失败的http错误码是多少？

**Comment by xia-chu** [comment]
#2764
