### ISSUE TITLE
除rtsp流外其他格式流拉不到

### ISSUE THREAD

**Issue by NEHCMA** [ZLMediaKit/ZLMediaKit#2767]
**咨询的具体内容和问题**
ZLMediaKit和wvp搭配使用 部署在同一服务器上  
wvp添加代理（live555编码h264rtsp流）后 视频播放一直加载无画面日志信息如下图：
![1692326248336](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/8d598147-5917-4485-bcb8-3655d0f44139)
一开始怀疑rtsp流有问题 调用接口测试 如下图   rtsp流转发正常
![1692256474160](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/f86d8225-5c2b-4e0d-bc0e-da8980be1065)
![1692256667345](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/0546b789-940d-4f7d-bdfe-cb0703a8d828)
使用ffmpeg代理方式能拉到
问下大佬们，知道问题原因吗？感谢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
媒体已经注册了 说明拉流成功了 如果是webrtc播放 需要修改配置文件directProxy为0

**Comment by xia-chu** [comment]
其他协议建议ffpaly播放测试

**Comment by NEHCMA** [comment]
zlm产生的rtmp、rtsp流
![1693188530111](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/ff1e308c-2914-48f8-a059-7ef0d654a741)
ffplay播放测试rtmp  失败
![1693187473556](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/abf8ce72-e6a6-48a3-b3c2-63afad683858)
ffplay播放测试rtsp   成功
![1693188130287](https://github.com/ZLMediaKit/ZLMediaKit/assets/65799303/3b34647f-e5f8-4181-9904-2a50170fa6e5)
为什么rtmp流播放失败了

**Comment by xia-chu** [comment]
把rtmp url发给我看看

**Comment by NEHCMA** [comment]
> 把rtmp url发给我看看

rtmp://172.16.66.246:1935/aaaaa/aaaaaaaa/

**Comment by xia-chu** [comment]
你这是局域网Ip啊

**Comment by NEHCMA** [comment]
没有映射到公网  只用于局域网...

**Comment by xia-chu** [comment]
所以我看不懂你打马赛克的目的
