### ISSUE TITLE
[BUG] addStreamProxy 的REST API接口问题

### ISSUE THREAD

**Issue by xubeiyan** [ZLMediaKit/ZLMediaKit#2773]
### 现象描述

调用`addStreamProxy`接口时，如果拉流正在处理，再次提交相同的请求时，会提前返回

例如，如果向`http://10.1.123.123:9000/index/api/addStreamProxy` 接口提交了GET 请求
```
GET /index/api/addStreamProxy?secret=abcde&url=rtmp:%2F%2F127.0.0.1%2Flive%2F0&vhost=__defaultVhost__&app=live&stream=0
```

当`url`中的地址`rtmp://127.0.0.1/live/0`不能够作为流的源时，一般需要10秒（应该是配置中`general.wait_track_ready_ms`）后，才会有响应

如果此时（即上一个请求仍未返回时）再次以同样请求此接口，会立刻（是立刻）返回
```json
{
  "code": 0,
  "data": {
    "key": "__defaultVhost__/proxy/0"
  }
}
```

就完成了此问题的复现，其实根本没有成功拉到流（因为此流根本不存在）。所以在正在尝试拉流时，如果接收到了同样的请求，应该丢弃而不是立即返回错误的返回值

### 如何复现?

1. （仅使用浏览器即可）假设REST API的地址是`http://10.1.123.123:9000/index/api/addStreamProxy`, `secret`为`abcde`，任意一个不存在的`rtmp`地址，例如`rtmp://127.0.0.1/live/test`。
2. 访问地址`http://10.1.123.123:9000/index/api/addStreamProxy?secret=abcde&vhost=__defaultVhost__&app=proxy&stream=123&url=rtmp://127.0.0.1/live/test`
3. 在等待请求时，手动停止请求，再次发起请求
4. 得到此流拉取成功的消息

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
{
			"api.apiDebug" : "1",
			"api.defaultSnap" : "./www/logo.png",
			"api.secret" : "abcde",
			"api.snapRoot" : "./www/snap/",
			"cluster.origin_url" : "",
			"cluster.retry_count" : "3",
			"cluster.timeout_sec" : "15",
			"ffmpeg.bin" : "/usr/bin/ffmpeg",
			"ffmpeg.cmd" : "%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
			"ffmpeg.log" : "./ffmpeg/ffmpeg.log",
			"ffmpeg.restart_sec" : "0",
			"ffmpeg.snap" : "%s -i %s -y -f mjpeg -t 0.001 %s",
			"general.check_nvidia_dev" : "1",
			"general.enableVhost" : "0",
			"general.enable_ffmpeg_log" : "0",
			"general.flowThreshold" : "1024",
			"general.maxStreamWaitMS" : "15000",
			"general.mediaServerId" : "your_server_id",
			"general.mergeWriteMS" : "0",
			"general.resetWhenRePlay" : "1",
			"general.streamNoneReaderDelayMS" : "20000",
			"general.unready_frame_cache" : "100",
			"general.wait_add_track_ms" : "3000",
			"general.wait_track_ready_ms" : "10000",
			"hls.broadcastRecordTs" : "0",
			"hls.deleteDelaySec" : "10",
			"hls.fileBufSize" : "65536",
			"hls.segDur" : "2",
			"hls.segKeep" : "0",
			"hls.segNum" : "3",
			"hls.segRetain" : "5",
			"hook.admin_params" : "secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc",
			"hook.alive_interval" : "10.0",
			"hook.enable" : "0",
			"hook.on_flow_report" : "https://127.0.0.1/index/hook/on_flow_report",
			"hook.on_http_access" : "https://127.0.0.1/index/hook/on_http_access",
			"hook.on_play" : "https://127.0.0.1/index/hook/on_play",
			"hook.on_publish" : "https://127.0.0.1/index/hook/on_publish",
			"hook.on_record_mp4" : "https://127.0.0.1/index/hook/on_record_mp4",
			"hook.on_record_ts" : "https://127.0.0.1/index/hook/on_record_ts",
			"hook.on_rtp_server_timeout" : "https://127.0.0.1/index/hook/on_rtp_server_timeout",
			"hook.on_rtsp_auth" : "https://127.0.0.1/index/hook/on_rtsp_auth",
			"hook.on_rtsp_realm" : "https://127.0.0.1/index/hook/on_rtsp_realm",
			"hook.on_send_rtp_stopped" : "https://127.0.0.1/index/hook/on_send_rtp_stopped",
			"hook.on_server_keepalive" : "https://127.0.0.1/index/hook/on_server_keepalive",
			"hook.on_server_started" : "https://127.0.0.1/index/hook/on_server_started",
			"hook.on_shell_login" : "https://127.0.0.1/index/hook/on_shell_login",
			"hook.on_stream_changed" : "https://127.0.0.1/index/hook/on_stream_changed",
			"hook.on_stream_none_reader" : "https://127.0.0.1/index/hook/on_stream_none_reader",
			"hook.on_stream_not_found" : "https://127.0.0.1/index/hook/on_stream_not_found",
			"hook.retry" : "1",
			"hook.retry_delay" : "3.0",
			"hook.timeoutSec" : "10",
			"http.charSet" : "utf-8",
			"http.dirMenu" : "0",
			"http.forbidCacheSuffix" : "",
			"http.forwarded_ip_header" : "",
			"http.keepAliveSecond" : "30",
			"http.maxReqSize" : "40960",
			"http.notFound" : "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>\u60a8\u8bbf\u95ee\u7684\u8d44\u6e90\u4e0d\u5b58\u5728\uff01</h1></center><hr><center>ZLMediaKit(git hash:1cc0f51/2023-03-09T15:24:32+08:00,branch:master,build time:2023-03-10T02:22:49)</center></body></html>",
			"http.port" : "9000",
			"http.rootPath" : "./www",
			"http.sendBufSize" : "65536",
			"http.sslport" : "0",
			"http.virtualPath" : "",
			"multicast.addrMax" : "239.255.255.255",
			"multicast.addrMin" : "239.0.0.0",
			"multicast.udpTTL" : "64",
			"protocol.add_mute_audio" : "1",
			"protocol.continue_push_ms" : "15000",
			"protocol.enable_audio" : "1",
			"protocol.enable_fmp4" : "1",
			"protocol.enable_hls" : "0",
			"protocol.enable_mp4" : "0",
			"protocol.enable_rtmp" : "1",
			"protocol.enable_rtsp" : "1",
			"protocol.enable_ts" : "1",
			"protocol.fmp4_demand" : "0",
			"protocol.hls_demand" : "0",
			"protocol.hls_save_path" : "./www",
			"protocol.modify_stamp" : "0",
			"protocol.mp4_as_player" : "0",
			"protocol.mp4_max_second" : "3600",
			"protocol.mp4_save_path" : "./www",
			"protocol.rtmp_demand" : "0",
			"protocol.rtsp_demand" : "0",
			"protocol.ts_demand" : "0",
			"record.appName" : "record",
			"record.fastStart" : "0",
			"record.fileBufSize" : "65536",
			"record.fileRepeat" : "0",
			"record.sampleMS" : "500",
			"rtc.externIP" : "",
			"rtc.port" : "8000",
			"rtc.preferredCodecA" : "PCMU,PCMA,opus,mpeg4-generic",
			"rtc.preferredCodecV" : "H264,H265,AV1,VP9,VP8",
			"rtc.rembBitRate" : "0",
			"rtc.tcpPort" : "8000",
			"rtc.timeoutSec" : "15",
			"rtmp.handshakeSecond" : "15",
			"rtmp.keepAliveSecond" : "15",
			"rtmp.modifyStamp" : "0",
			"rtmp.port" : "1935",
			"rtmp.sslport" : "0",
			"rtp.audioMtuSize" : "600",
			"rtp.lowLatency" : "0",
			"rtp.rtpMaxSize" : "10",
			"rtp.videoMtuSize" : "1400",
			"rtp_proxy.dumpDir" : "",
			"rtp_proxy.h264_pt" : "98",
			"rtp_proxy.h265_pt" : "99",
			"rtp_proxy.opus_pt" : "100",
			"rtp_proxy.port" : "10000",
			"rtp_proxy.port_range" : "30000-35000",
			"rtp_proxy.ps_pt" : "96",
			"rtp_proxy.timeoutSec" : "15",
			"rtsp.authBasic" : "0",
			"rtsp.directProxy" : "1",
			"rtsp.handshakeSecond" : "15",
			"rtsp.keepAliveSecond" : "15",
			"rtsp.lowLatency" : "0",
			"rtsp.port" : "5554",
			"rtsp.sslport" : "0",
			"shell.maxReqSize" : "1024",
			"shell.port" : "0",
			"srt.latencyMul" : "4",
			"srt.pktBufSize" : "8192",
			"srt.port" : "9000",
			"srt.timeoutSec" : "5"
		}
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
```
kuro@sakuramoyu:~/ZLMediaKit$ git log
commit 1cc0f51c076b4071a31eda0031708daac88bac64 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: ljx0305 <ljx0305@gmail.com>
Date:   Thu Mar 9 15:24:32 2023 +0800

    replace ffmpeg deprecated api avpicture_fill to av_image_fill_arrays (#2279)
```

```
ZLMediaKit(git hash:1cc0f51/2023-03-09T15:24:32+08:00,branch:master,build time:2023-03-10T02:22:49)
```
* **操作系统及版本**: 
```
kuro@sakuramoyu:~/ZLMediaKit$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

```
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个不算bug啊 就是这么设计的 你需要在调度系统规避这个问题

**Comment by xia-chu** [comment]
发起拉流时 zlmediakit会先保存对象到map表中，如果拉流失败了 再从map表中删除。
如果这期间 你重复发起拉流，zlm会查询map表中有没有记录 有就直接返回成功了

**Comment by xia-chu** [comment]
或者返回一个错误码？

**Comment by tjpgt** [comment]
我觉得这是个bug啊，不看怎么实现，只看功能性的话，既然第一次发起请求时需要等待实际拉流成功才会返回成功，那在此期间的其他请求也应该是同样的行为才对啊。返回错误码也可以，至少不应该是成功啊。

**Comment by xia-chu** [comment]
就算返回错误码 也无法区分正在拉流(等待成功) 还是已经拉流成功了。

**Comment by xia-chu** [comment]
而且已经拉流成功了，也不能代表这个流目前是否有效 也有可能在失败重连中

**Comment by xia-chu** [comment]
> 既然第一次发起请求时需要等待实际拉流成功才会返回成功，那在此期间的其他请求也应该是同样的行为才对啊

触发拉流的http请求 当然会等待拉流成功才会返回。
重复调addStreamProxy的请求只能返回错误码

**Comment by tjpgt** [comment]
我还是没理解，按我的想法，这就是类似于一个耗时任务，当我收到一个任务请求时，如果没在做这个任务，就开始做。在任务还没做完的时候，又收到了一个一模一样的请求，我发现我正在做这个任务，就可以回复说，你等等，我正在做同样的任务呢。或者我也可以先不回复，等任务完成后再回复结果。

当然实际已有的代码设计可能不太支持我的想法？

> 而且已经拉流成功了，也不能代表这个流目前是否有效 也有可能在失败重连中

流是否有效确实不知道，但是其实哪怕是第一次请求，返回成功，此时这个流也有可能已经失效了的吧？所以我觉得两次请求返回一样的结果也是合乎逻辑的。

**Comment by xia-chu** [comment]
如果拉一个重复的流 改成这样了：
```json
{
    "code": -1,
    "msg": " This stream already exists "
}
```
