### ISSUE TITLE
[技术咨询] 浏览器打开视频关闭。到第6个时不能播放，浏览器显示请求待处理

### ISSUE THREAD

**Issue by feng199464** [ZLMediaKit/ZLMediaKit#2774]
浏览器打开视频关闭。到第6个时开始都不能播放，浏览器显示请求待处理，请问这种情况该如何解决
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/46559381/8ee583dc-271c-4ab6-8223-d95f59a39202)

**Comment by lystormenvoy** [comment]
http协议限制吧，用ws协议的流

**Comment by v354412101** [comment]
推荐使用[wsPlayer](https://github.com/v354412101/wsPlayer)，支持websocket-fmp4协议播放，对浏览器连接数没有限制。

**Comment by feng199464** [comment]
我看服务都已经断开连接了，也没有给浏览器推流了，按理来说连接数是够的，浏览器对视频流这个有连接数限制吗

> 推荐使用[wsPlayer](https://github.com/v354412101/wsPlayer)，支持websocket-fmp4协议播放，对浏览器连接数没有限制。

**Comment by v354412101** [comment]
> 我看服务都已经断开连接了，也没有给浏览器推流了，按理来说连接数是够的，浏览器对视频流这个有连接数限制吗
> 
> > 推荐使用[wsPlayer](https://github.com/v354412101/wsPlayer)，支持websocket-fmp4协议播放，对浏览器连接数没有限制。

浏览器对http长连接是有限制的，只能同时并发6个。

**Comment by feng199464** [comment]
> > 我看服务都已经断开连接了，也没有给浏览器推流了，按理来说连接数是够的，浏览器对视频流这个有连接数限制吗
> > > 推荐使用[wsPlayer](https://github.com/v354412101/wsPlayer)，支持websocket-fmp4协议播放，对浏览器连接数没有限制。
> 
> 浏览器对http长连接是有限制的，只能同时并发6个。

那我能不能让客户端在关闭视频画面时，主动调一下API 关闭推流，能不能解决，因为视频是打开一个 关一个，理论上说 应该只存在一个长连接

**Comment by xia-chu** [comment]
换websocket-fmp4或websocket-flv或webrtc吧 没这个问题
