### ISSUE TITLE
ZLMediaKit服务端在实现rtsp流到webrtc流的转换时，有做gop缓存吗？

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#2775]
**咨询的功能模块**
rtsp流转webrtc流

**咨询的具体内容和问题**
我通过rtsp协议推流到ZLMediaKit服务端，然后通过webrtc网页端播放，但发现画面呈现的速度很慢，由于我的视频流的I帧间隔比较大，有10秒，所以这个现象也比较明显

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
有做gop缓存，你短期不能加载出来，可能是丢包了，获取gop命中失败，配置文件directProxy设置为0试试

**Comment by quxiaohui-debug** [comment]
非常感谢，把directProxy设置为0就可以了。

**Comment by quxiaohui-debug** [comment]
我是在局域网测试，应该不存在丢包，并且视频流不包含B帧

**Comment by xia-chu** [comment]
嗯 那就是rtp打包模式问题
