### ISSUE TITLE
[技术咨询] url 播放鉴权触发web hook次数

### ISSUE THREAD

**Issue by song01** [ZLMediaKit/ZLMediaKit#2776]
**咨询的功能模块**
- 不同协议url 播放时，会触发几次web hook?

**咨询的具体内容和问题**
-  hls在没有cookie的情况下，每次请求都会触发web hook吗
- flv,ts,rtmp,rtsp这些请求会触发几次web hook

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
- flv,ts,rtmp,rtsp这些请求会触发一次鉴权hook请求。
- hls如果在播放器支持cookie的情况下，会触发一次鉴权hook请求，如果播放器不支持cookie，但是如果一个播放器分配一个独特固定的url参数，也只会触发一次鉴权hook请求，否则每次请求m3u8文件都会触发一次请求。

**Comment by song01** [comment]
hls 带上一个独特固定的url参数，这个url参数的有效期是如何定义的？

**Comment by song01** [comment]
这个url参数 在触发一次鉴权hook请求后，什么情况下 才会再次触发鉴权hook请求

**Comment by xia-chu** [comment]
没有有效期 60秒不访问不刷新 就过期





------------------ 原始邮件 ------------------
发件人: song01 ***@***.***&gt;
发送时间: 2023年8月22日 09:19
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] url 播放鉴权触发web hook次数 (Issue #2776)





 
hls 带上一个独特固定的url参数，这个url参数的有效期是如何定义的？

**Comment by song01** [comment]
60秒不访问不刷新 这个值可以通过配置调整吗

**Comment by xia-chu** [comment]
> 60秒不访问不刷新 这个值可以通过配置调整吗

不能 没必要，有些经验值不应该暴露给用户设置，因为用户很可能是小白。
一个m3u8文件 不可能再播放hls中 超过60秒不访问，如果存在 那么就是ts切片超过60秒，这就不是hls直播了

**Comment by song01** [comment]
hls 带上一个独特固定的url参数 这种模式，测试发现如果先后打开两个播放器播放相同的url，只会触发一次鉴权hook，这个可以支持每个播放器播放的时候触发一次鉴权hook吗

**Comment by xia-chu** [comment]
一个播放一个URL即可 你在分发url时 应该确保这点
