### ISSUE TITLE
[技术咨询] webrtc模块datachannel功能是否会转发播放端消息给推流端

### ISSUE THREAD

**Issue by li-yueping** [ZLMediaKit/ZLMediaKit#2777]
**咨询的功能模块**
- webrtc模块datachannel功能

**咨询的具体内容和问题**
- webrtc播放器通过datachannel向ZLM发送消息，ZLM是否会将该消息通过datachannel转发给webrtc推流端

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
需要二开，限制是没有的

**Comment by xia-chu** [comment]
datachannel在zlm中的定位只作用二次开发 zlm目前不会去做任何datachannel使用上的定义
