### ISSUE TITLE
从我的流中打开或关闭音频流后，我无法获取该流。

### ISSUE THREAD

**Issue by ParhamJ** [ZLMediaKit/ZLMediaKit#2779]
这是我在更改流中的音频流状态（从包含音频流到删除音频流，反之亦然）时遇到的错误。 在从我的流更改音频流期间，输出流无法播放。 我必须重新启动MediaServer； 请检查屏幕截图。 谢谢
![9f5894d981f632448d7b5a56e43ec0c](https://github.com/ZLMediaKit/ZLMediaKit/assets/98977472/d6cfd496-2d3b-4dd8-9671-a2738f143b80)

**Comment by ParhamJ** [comment]
我们在更改视频编解码器（编码器）和视频分辨率时遇到了同样的问题。

**Comment by xia-chu** [comment]
zlm支持动态修改视频分辨率 你先声明有音频 然后又不发音频了 这个可能会导致播放器空等。
很多协议是不支持动态减少track的，因为它们没有变更元数据(sdp)的机制。
你这种用法本来就不规范。

**Comment by ParhamJ** [comment]
但是有些项目（如 "MediaMTX"）并没有这个问题，如果与协议（RTSP）有关的话。

**Comment by xia-chu** [comment]
你可以提供个mediamtx抓包文件 注意请重现下你所说的功能
