### ISSUE TITLE
[技术咨询] 添加推流代理addStreamPusherProxy接口报错

### ISSUE THREAD

**Issue by cyp8110** [ZLMediaKit/ZLMediaKit#2782]
**咨询的功能模块**
- 添加推流代理addStreamPusherProxy接口使用
- 添加拉流代理的接口调用后，在调用关闭拉流的接口，拉流代理地址依旧可用

**咨询的具体内容和问题**
- 添加推流代理addStreamPusherProxy接口报错
- 报错内容：{
    "code": -1,
    "msg": "publish 失败:error NetStream.Publish.BadName"
}
日志信息：

[logs(22).txt](https://github.com/ZLMediaKit/ZLMediaKit/files/12408241/logs.22.txt)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
你要提供一个有效的推流地址 很明显 对方rtmp服务器拒绝了zlmediakit的rtmp推流了 
你应该是推给zlm自己了 并且stream id用的同一个

**Comment by cyp8110** [comment]
了解，感谢大佬解惑
