### ISSUE TITLE
[BUG] 与wvp联调时，出现zlm无法发送心跳的问题

### ISSUE THREAD

**Issue by lr897219186** [ZLMediaKit/ZLMediaKit#2783]
### 现象描述
我将zlm部署在CentOS7.6虚拟机下，启动正常；同时windows环境下启动wvp后端服务连接zlm。一开始显示zlm连接成功，但数十秒后wvpzlm心跳过期，但根据wvp日志，似乎是zlm无法向wvp发送心跳。且即使停止wvp后端服务，zlm日志仍然继续打印 `hook http://192.168.236.129:18978/index/hook/on_server_keepalive 1ms,failed[network err]:3(connection refused)` 的错误

### 如何复现?
重启zlm，再重启wvp服务连接zlm，每次都是先提示连接成功，然后心跳超时

### 相关日志或截图
wvp日志：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/67771256/41bfc9f9-32d9-40af-af02-289b3a12a94c)

zlm日志：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/67771256/1c4ba33f-989c-4ed2-b75e-4f9a771b5a87)

<details>
<summary>展开查看详细日志</summary>
wvp日志：
<pre>
2023-08-23 11:57:20.858  INFO --- SipLayer : [SIP SERVER] tcp://192.168.1.100:5060 启动成功
2023-08-23 11:57:20.864  INFO --- SipLayer : [SIP SERVER] udp://192.168.1.100:5060 启动成功
2023-08-23 11:57:20.887  INFO --- HikariDataSource : HikariPool-1 - Starting...
2023-08-23 11:57:21.017  INFO --- HikariDataSource : HikariPool-1 - Start completed.
2023-08-23 11:57:21.066  INFO --- ZLMRunner : [zlm] 等待默认zlm中...
2023-08-23 11:57:21.068  INFO --- MediaServerServiceImpl : [zlm] 缓存初始化 
2023-08-23 11:57:21.325  INFO --- MediaServerServiceImpl : [ZLM] 正在连接 : lr_zlm -> 192.168.236.129:80
2023-08-23 11:57:23.429 ERROR --- AssistRESTfulUtils : 连接Assist失败: Connection refused: no further information, Failed to connect to /192.168.236.129:18081
2023-08-23 11:57:23.430  INFO --- AssistRESTfulUtils : 请检查media配置并确认Assist已启动...
2023-08-23 11:57:23.430  INFO --- MediaServerServiceImpl : [ZLM] 正在设置 ：lr_zlm -> 192.168.236.129:80
2023-08-23 11:57:23.433  INFO --- MediaServerServiceImpl : [ZLM] 设置成功 lr_zlm -> 192.168.236.129:80
2023-08-23 11:57:23.437  INFO --- MediaServerServiceImpl : [ZLM] 连接成功 lr_zlm - 192.168.236.129:80 
2023-08-23 11:57:23.439  INFO --- ZLMStatusEventListener : [ZLM] 上线 ID：lr_zlm
2023-08-23 11:57:23.457  INFO --- CivilCodeFileConf : [行政区划] 加载成功，共加载数据3219条
2023-08-23 11:57:23.463  INFO --- VManageBootstrap : 构建版本： 
2023-08-23 11:57:23.463  INFO --- VManageBootstrap : 构建时间： 
2023-08-23 11:57:23.463  INFO --- VManageBootstrap : GIT最后提交时间： 
2023-08-23 11:57:38.435  INFO --- MediaServerServiceImpl : [zlm心跳到期]：lr_zlm
2023-08-23 11:57:38.439  INFO --- MediaServerServiceImpl : [zlm心跳到期]：lr_zlm验证后zlm仍在线，恢复心跳信息,请检查zlm是否可以正常向wvp发送心跳
2023-08-23 11:57:53.441  INFO --- MediaServerServiceImpl : [zlm心跳到期]：lr_zlm
2023-08-23 11:57:53.444  INFO --- MediaServerServiceImpl : [zlm心跳到期]：lr_zlm验证后zlm仍在线，恢复心跳信息,请检查zlm是否可以正常向wvp发送心跳
</pre>

zlm日志：
<pre>
2023-08-23 11:59:34.327 D [MediaServer] [13189-event poller 2] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getServerConfig
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 39
Content-Type : application/x-www-form-urlencoded
Host : 192.168.236.129
User-Agent : okhttp/4.10.0
# content:
secret=p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er
# response size:5558

2023-08-23 11:59:34.442 D [MediaServer] [13189-event poller 2] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 74
Content-Type : application/x-www-form-urlencoded
Host : 192.168.236.129
User-Agent : okhttp/4.10.0
# content:
secret=p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er&schema=rtsp&vhost=__defaultVhost__
# response:
{
	"code" : 0
}

2023-08-23 11:59:36.490 D [MediaServer] [13189-event poller 2] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/setServerConfig
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 1322
Content-Type : application/x-www-form-urlencoded
Host : 192.168.236.129
User-Agent : okhttp/4.10.0
# content:
secret=p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er&hook.on_rtsp_realm=&hook.on_stream_changed=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_stream_changed&hook.on_flow_report=&hook.on_publish=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_publish&ffmpeg.snap=%25s%20-rtsp_transport%20tcp%20-i%20%25s%20-y%20-f%20mjpeg%20-t%200.001%20%25s&hook.timeoutSec=20&protocol.continue_push_ms=3000&hook.enable=1&hook.on_rtp_server_timeout=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_rtp_server_timeout&hook.on_http_access=&hook.on_stream_not_found=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_stream_not_found&hook.on_send_rtp_stopped=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_send_rtp_stopped&rtp_proxy.port_range=50000-50300&hook.on_rtsp_auth=&hook.on_record_mp4=http%3A%2F%2F127.0.0.1%3A18081%2Fapi%2Frecord%2Fon_record_mp4&hook.on_stream_none_reader=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_stream_none_reader&hook.on_server_keepalive=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_server_keepalive&hook.on_shell_login=&hook.on_play=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_play&api.secret=p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er&hook.on_server_started=http%3A%2F%2F192.168.236.129%3A18978%2Findex%2Fhook%2Fon_server_started&hook.on_record_ts=
# response:
{
	"changed" : 0,
	"code" : 0
}

2023-08-23 11:59:36.498 D [MediaServer] [13189-event poller 2] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 39
Content-Type : application/x-www-form-urlencoded
Host : 192.168.236.129
User-Agent : okhttp/4.10.0
# content:
secret=p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er
# response:
{
	"code" : 0
}

2023-08-23 11:59:37.120 W [MediaServer] [13189-event poller 2] WebHook.cpp:194 operator() | hook http://192.168.236.129:18978/index/hook/on_server_started 0ms,failed[network err]:3(connection refused):{
	"api.apiDebug" : "1",
	"api.defaultSnap" : "./www/logo.png",
	"api.secret" : "p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er",
	"api.snapRoot" : "./www/snap/",
	"cluster.origin_url" : "",
	"cluster.retry_count" : "3",
	"cluster.timeout_sec" : "15",
	"ffmpeg.bin" : "/usr/bin/ffmpeg",
	"ffmpeg.cmd" : "%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s",
	"ffmpeg.log" : "./ffmpeg/ffmpeg.log",
	"ffmpeg.restart_sec" : "0",
	"ffmpeg.snap" : "%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s",
	"general.check_nvidia_dev" : "1",
	"general.enableVhost" : "0",
	"general.enable_ffmpeg_log" : "0",
	"general.flowThreshold" : "1024",
	"general.maxStreamWaitMS" : "15000",
	"general.mediaServerId" : "lr_zlm",
	"general.mergeWriteMS" : "0",
	"general.resetWhenRePlay" : "1",
	"general.streamNoneReaderDelayMS" : "20000",
	"general.unready_frame_cache" : "100",
	"general.wait_add_track_ms" : "3000",
	"general.wait_track_ready_ms" : "10000",
	"hls.broadcastRecordTs" : "0",
	"hls.deleteDelaySec" : "10",
	"hls.fileBufSize" : "65536",
	"hls.segDur" : "2",
	"hls.segKeep" : "0",
	"hls.segNum" : "3",
	"hls.segRetain" : "5",
	"hook.alive_interval" : "10.0",
	"hook.enable" : "1",
	"hook.on_flow_report" : "",
	"hook.on_http_access" : "",
	"hook.on_play" : "http://192.168.236.129:18978/index/hook/on_play",
	"hook.on_publish" : "http://192.168.236.129:18978/index/hook/on_publish",
	"hook.on_record_mp4" : "http://127.0.0.1:18081/api/record/on_record_mp4",
	"hook.on_record_ts" : "",
	"hook.on_rtp_server_timeout" : "http://192.168.236.129:18978/index/hook/on_rtp_server_timeout",
	"hook.on_rtsp_auth" : "",
	"hook.on_rtsp_realm" : "",
	"hook.on_send_rtp_stopped" : "http://192.168.236.129:18978/index/hook/on_send_rtp_stopped",
	"hook.on_server_exited" : "https://127.0.0.1/index/hook/on_server_exited",
	"hook.on_server_keepalive" : "http://192.168.236.129:18978/index/hook/on_server_keepalive",
	"hook.on_server_started" : "http://192.168.236.129:18978/index/hook/on_server_started",
	"hook.on_shell_login" : "",
	"hook.on_stream_changed" : "http://192.168.236.129:18978/index/hook/on_stream_changed",
	"hook.on_stream_none_reader" : "http://192.168.236.129:18978/index/hook/on_stream_none_reader",
	"hook.on_stream_not_found" : "http://192.168.236.129:18978/index/hook/on_stream_not_found",
	"hook.retry" : "1",
	"hook.retry_delay" : "3.0",
	"hook.stream_changed_schemas" : "rtsp/rtmp/fmp4/ts/hls/hls.fmp4",
	"hook.timeoutSec" : "20",
	"hook_index" : 1,
	"http.allow_cross_domains" : "1",
	"http.allow_ip_range" : "127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255",
	"http.charSet" : "utf-8",
	"http.dirMenu" : "1",
	"http.forbidCacheSuffix" : "",
	"http.forwarded_ip_header" : "",
	"http.keepAliveSecond" : "30",
	"http.maxReqSize" : "40960",
	"http.notFound" : "<html><head><title>404 Not Found</title></head><body bgcolor=\"white\"><center><h1>\u60a8\u8bbf\u95ee\u7684\u8d44\u6e90\u4e0d\u5b58\u5728\uff01</h1></center><hr><center>ZLMediaKit(git hash:895e93c/%aI,branch:master,build time:2023-08-23T11:12:13)</center></body></html>",
	"http.port" : "80",
	"http.rootPath" : "./www",
	"http.sendBufSize" : "65536",
	"http.sslport" : "443",
	"http.virtualPath" : "",
	"mediaServerId" : "lr_zlm",
	"multicast.addrMax" : "239.255.255.255",
	"multicast.addrMin" : "239.0.0.0",
	"multicast.udpTTL" : "64",
	"protocol.add_mute_audio" : "1",
	"protocol.auto_close" : "0",
	"protocol.continue_push_ms" : "3000",
	"protocol.enable_audio" : "1",
	"protocol.enable_fmp4" : "1",
	"protocol.enable_hls" : "1",
	"protocol.enable_hls_fmp4" : "0",
	"protocol.enable_mp4" : "0",
	"protocol.enable_rtmp" : "1",
	"protocol.enable_rtsp" : "1",
	"protocol.enable_ts" : "1",
	"protocol.fmp4_demand" : "0",
	"protocol.hls_demand" : "0",
	"protocol.hls_save_path" : "./www",
	"protocol.modify_stamp" : "2",
	"protocol.mp4_as_player" : "0",
	"protocol.mp4_max_second" : "3600",
	"protocol.mp4_save_path" : "./www",
	"protocol.rtmp_demand" : "0",
	"protocol.rtsp_demand" : "0",
	"protocol.ts_demand" : "0",
	"record.appName" : "record",
	"record.fastStart" : "0",
	"record.fileBufSize" : "65536",
	"record.fileRepeat" : "0",
	"record.sampleMS" : "500",
	"rtc.externIP" : "",
	"rtc.port" : "8000",
	"rtc.preferredCodecA" : "PCMU,PCMA,opus,mpeg4-generic",
	"rtc.preferredCodecV" : "H264,H265,AV1,VP9,VP8",
	"rtc.rembBitRate" : "0",
	"rtc.tcpPort" : "8000",
	"rtc.timeoutSec" : "15",
	"rtmp.handshakeSecond" : "15",
	"rtmp.keepAliveSecond" : "15",
	"rtmp.port" : "1935",
	"rtmp.sslport" : "0",
	"rtp.audioMtuSize" : "600",
	"rtp.h264_stap_a" : "1",
	"rtp.lowLatency" : "0",
	"rtp.rtpMaxSize" : "10",
	"rtp.videoMtuSize" : "1400",
	"rtp_proxy.dumpDir" : "",
	"rtp_proxy.gop_cache" : "1",
	"rtp_proxy.h264_pt" : "98",
	"rtp_proxy.h265_pt" : "99",
	"rtp_proxy.opus_pt" : "100",
	"rtp_proxy.port" : "10000",
	"rtp_proxy.port_range" : "50000-50300",
	"rtp_proxy.ps_pt" : "96",
	"rtp_proxy.timeoutSec" : "15",
	"rtsp.authBasic" : "0",
	"rtsp.directProxy" : "1",
	"rtsp.handshakeSecond" : "15",
	"rtsp.keepAliveSecond" : "15",
	"rtsp.lowLatency" : "0",
	"rtsp.port" : "554",
	"rtsp.rtpTransportType" : "-1",
	"rtsp.sslport" : "0",
	"shell.maxReqSize" : "1024",
	"shell.port" : "0",
	"srt.latencyMul" : "4",
	"srt.pktBufSize" : "8192",
	"srt.port" : "9000",
	"srt.timeoutSec" : "5"
}

2023-08-23 11:59:44.121 W [MediaServer] [13189-event poller 2] WebHook.cpp:194 operator() | hook http://192.168.236.129:18978/index/hook/on_server_keepalive 1ms,failed[network err]:3(connection refused):{
	"data" : 
	{
		"Buffer" : 5,
		"BufferLikeString" : 1,
		"BufferList" : 0,
		"BufferRaw" : 4,
		"Frame" : 0,
		"FrameImp" : 0,
		"MediaSource" : 0,
		"MultiMediaSourceMuxer" : 0,
		"RtmpPacket" : 0,
		"RtpPacket" : 0,
		"Socket" : 29,
		"TcpClient" : 0,
		"TcpServer" : 23,
		"TcpSession" : 1,
		"UdpServer" : 8,
		"UdpSession" : 0
	},
	"hook_index" : 2,
	"mediaServerId" : "lr_zlm"
}
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
zlm配置：只修改了config.ini文件中的mediaServerId为lr_zlm

wvp配置：
<pre>
sip:
  ip: 192.168.1.100
  port: 5060
  domain: 3402000000
  id: 34020000002000000001
  password: 12345678
  alarm: true

media:
  id: lr_zlm
  ip: 192.168.236.129
  http-port: 80
  stream-ip: 192.168.236.129
  sdp-ip: 192.168.236.129
  hook-ip: 192.168.236.129
  http-ssl-port: 443
  secret: p3WiHNd0Rl5TmiEMvi2csNhpxcoYB8er
  rtp:
    enable: true
    port-range: 50000,50300 # 端口范围
    send-port-range: 50000,50300 # 端口范围
  record-assist-port: 18081
</pre>
</details>

### 各种环境信息

* **部署方式**：wvp在Windows idea中直接运行，zlm编译部署在虚拟集中运行；
* **部署环境**：zlm部署在CentOS 7.6下，ip为192.168.236.129；wvp在Wndows环境下，ip为192.168.1.100；
* **端口开放情况**：无开放端口
* **是否是公网部署**：否
* **是否使用https**：否
* **使用的设备品牌**：海康设备，测试注册成功，但应该与本问题无关；
* **你做过哪些尝试**：重新部署ZLM最新版无果；将部署了ZLM的虚拟机设为桥接，ip固定为与局域网ip同一网段下的静态地址，无果；
* **代码更新时间**：2023年8月23日 10:00

**Comment by lr897219186** [comment]
由于本人是新手，初步分析问题可能是zlm导致的，但由于不太确定所以在zlm和wvp两边都发布了问题以寻求帮助，如有不对还请各位大佬们多多批评指正，谢谢

**Comment by xia-chu** [comment]
这个很明显啊 wvp的http zlmediakit访问不了 它tcp服务都没开：
http://192.168.236.129:18978/index/hook/on_server_keepalive

**Comment by xia-chu** [comment]
可以在wvp部署的机器netstate -ntpl看看端口是否开着

**Comment by lr897219186** [comment]
> netstate -ntpl

感谢大佬回复！问题已经解决，我将部署zlm的虚拟机设为桥接，ip固定为wvp部署机的同一网段下ip，并在wvp配置中将hook ip设为更改后的虚拟机ip，就可以了
