### ISSUE TITLE
[功能请求] 统计webrtc视频流的播放人数

### ISSUE THREAD

**Issue by Shenlianxi** [ZLMediaKit/ZLMediaKit#2788]
**功能的用处**
播放端使用的是webrtc，推流端使用的rtsp进行推流，通过zlmediakit进行转码转为webrtc视频流，通过统计webrtc视频流的观看人数，进行决定是否可以进行关闭推流端的推流，节省推流端的流量

**期望实现该功能的方式和最终效果**
1.希望通过webhook或者api等形式获取webrtc视频流的观看人数，如传入参数为stream和app，获取到webrtc观看人数；
2.希望通过stream和app的参数传入，获取观众的信息（如观看ip，观看时间等）；

**Comment by xia-chu** [comment]
目前已经支持观看人数统计，可以通过getMediaList或getMediaInfo接口获取相关信息。
totalReaderCount是这个流所有协议的观看者人数，
readerCount是当前协议观看者人数，webrtc目前和rtsp是当做统一处理，schema都是rtsp，所以是rtsp+webrtc播放人数。

**Comment by xia-chu** [comment]
获取观众的信息可以通过getMediaPlayerList接口实现：
<img width="982" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/b59509f8-185c-4ddb-97b2-488e34fa8e62">

**Comment by Shenlianxi** [comment]
非常感谢作者的回复！
确实rtsp和webrtc会统一处理，在配置文件中也可以看出来~
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/19489306/15c067a2-6f46-4122-bf3c-4467dcad5092)
