### ISSUE TITLE
[技术咨询] Api getSnap  生成的截图是否会被自动清理？

### ISSUE THREAD

**Issue by ShuiFan0** [ZLMediaKit/ZLMediaKit#2789]
**咨询的功能模块**
- 截图功能

**咨询的具体内容和问题**
- 使用截图功能后，我发现目录下的www/snap目录下的每一个文件夹都一直存在一张截图。
- 这样长时间运行多次取流后，是否会造成截图大量堆积？
- 我将expire_sec设为0，依旧如此

**Comment by xia-chu** [comment]
一个流只会存在一个截图 这个应该是可以接受的
这个zlm不会去主动删除它 如果觉得碍事，可以搞个定时器自己删除

**Comment by ShuiFan0** [comment]
关键是现在的流都是动态出来的....随着时间的推移，会留下越来越多的文件...

**Comment by ShuiFan0** [comment]
> 一个流只会存在一个截图 这个应该是可以接受的 这个zlm不会去主动删除它 如果觉得碍事，可以搞个定时器自己删除

关键是现在的流都是动态出来的....随着时间的推移，会留下越来越多的文件...
