### ISSUE TITLE
[技术咨询] webrtc播放时能自动将h265格式的转为h264的吗，aac能转g711吗

### ISSUE THREAD

**Issue by Geey-Cloud** [ZLMediaKit/ZLMediaKit#2796]
**咨询的功能模块**
webrtc视频、音频格式转换
**咨询的具体内容和问题**
请问webrtc播放时能自动将h265格式的转为h264的吗，aac能转g711吗

**Comment by xia-chu** [comment]
不支持

**Comment by Geey-Cloud** [comment]
谢谢您的回答。我还有一个问题，请问服务器端推流h265,拉流播放时不会自动转码为h264吗？音频也不会从aac转到g711吗？

**Comment by xia-chu** [comment]
都不能转码的 transcode分支会把音频转成opus

**Comment by Geey-Cloud** [comment]
谢谢您的回答，我知道了。
