### ISSUE TITLE
[技术咨询] k8s部署zlk，通过oss挂载zlk的直播源，多个pod副本之间不能共享直播流

### ISSUE THREAD

**Issue by cyp8110** [ZLMediaKit/ZLMediaKit#2797]
**咨询的功能模块**
-  k8s部署zlk，通过oss挂载zlk的直播源，多个pod副本之间不能共享直播流

**咨询的具体内容和问题**
- 通过k8s部署zlk多副本时，开始推流到zlk中，好像只是推流到了某一个pod中，拉流的时候如果命中了那个没有接收到这个流的pod时会报错
- [34m2023-08-28 17:18:18.873 T [MediaServer] [7-event poller 1] TcpServer.cpp:173 operator() | 202-86(172.16.4.129:31701) mediakit::RtmpSession on err: 5(no such stream: defaultVhost/4213a2f63d104e83a66b6f4b3fa71b84/8984765f5a2b44a4bfaef962fc31db9f)[0m
[33m2023-08-28 17:18:18.873 W [MediaServer] [7-event poller 1] RtmpSession.cpp:30 onError | 202-86(172.16.4.129:31701) RTMP播放器(defaultVhost/4213a2f63d104e83a66b6f4b3fa71b84/8984765f5a2b44a4bfaef962fc31db9f)断开:no such stream: defaultVhost/4213a2f63d104e83a66b6f4b3fa71b84/8984765f5a2b44a4bfaef962fc31db9f,耗时(s):15[0m

前提是已经在k8s中进行了oss的存储挂载，进到容器内部查看视频流的存储信息是，各个pod中都有这个视频流，是否那个地方存在强制绑定的关系，这个如何解决。

拉流端报错信息：
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/37569483/94e7e572-65bd-4202-895a-7acfea8d029a)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by cyp8110** [comment]
容器镜像为dockerhub提供的官方最新镜像

**Comment by xia-chu** [comment]
多个副本直接本来就不能互相共享流，他们是独立的。
你可以部署多个源站实例，多个边缘站实例；推流随机到源站实例即可。
播放从边缘站拉流，这样就解决你这个问题了。
主要边缘站需要修改配置文件 设置源站实例的地址，配置文件参考cluster.origin_url
