### ISSUE TITLE
点播功能的hls文件会出现ts断层的现象

### ISSUE THREAD

**Issue by huanting0016** [ZLMediaKit/ZLMediaKit#2799]
**咨询的功能模块**
- zlmedia的点播功能，配置文件如下
- 当直播流一直在线的情况下，记录当前直播流的所有片段信息
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/53136616/b3a32360-ea23-4bb1-92c8-500d6a20097c)

**咨询的具体内容和问题**
- 确认直播流一直在线，但是hls文件保存的ts缺失了一部分
- 如下图的hls.m3u8文件
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/53136616/62f17cb3-7c37-4798-98c9-685b1f5b5f1c)
- 如下图的ts文件列表，缺少了 51-59_0.ts上面的所有ts文件记录
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/53136616/3c191f29-89db-48e0-aa30-4cc317c1ec83)
- 想问一下如何保持hls文件中的ts文件列表的连贯性，还有想了解为什么会出现文件大小差别较大的原因

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
你截图红框的第一个不就是51-59_0.ts 吗

**Comment by xiongguangjie** [comment]
你要先看hls.m3u8,然后去看目录

**Comment by xia-chu** [comment]
很明显 这个流断了 有重新上线了

**Comment by huanting0016** [comment]
好的，感谢；
排查了一下发现，再添加流的时候，没有设置重试次数，导致中间流短暂离线的时候又被重连上了，而在外面没有感知到（重连是不是webhook就不会发送on_stream_changed的通知），所以hls文件就被覆盖了
