### ISSUE TITLE
[技术咨询] ffmpeg推流到zlm失败，怎么授权

### ISSUE THREAD

**Issue by ivanlebron** [ZLMediaKit/ZLMediaKit#2802]
ffmpeg -re -i "test.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test

[rtsp @ 0x126e36aa0] method ANNOUNCE failed: 401 Unauthorized
[out#0/rtsp @ 0x126e396f0] Could not write header (incorrect codec parameters ?): Server returned 401 Unauthorized (authorization failed)
[vost#0:0/libx264 @ 0x126e37530] Error initializing output stream:

**Comment by xiongguangjie** [comment]
你有两个问题
1，这个视频有问题能播放？？？
2，你把鉴权的webhook 关掉（具体看注释，实在不行就关闭hook,具体看配置文件）

**Comment by ivanlebron** [comment]
1.可以播放
2.如果不关是否可行？
测试发现关闭hook可以，那么不关闭是否可行

**Comment by ivanlebron** [comment]
done
