### ISSUE TITLE
[技术咨询]录制flv

### ISSUE THREAD

**Issue by lj2508-com** [ZLMediaKit/ZLMediaKit#2808]
**咨询的功能模块**
- 录制功能

**咨询的具体内容和问题**
- 在首页看到支持录制为flv。但是我看了下录制的api只有mp4和hls。如果我想要录制flv需要怎么操作。有看到之前有议题issues。想问一下目前还需要自己开发吗

**Comment by xiongguangjie** [comment]
现在不支持，需要自己开发，其实已经有flv Record 的类，只是需要添加代码使用起来，但是flv录制没有太大意义

**Comment by xia-chu** [comment]
FlvRecorder会增加rtmp的观看者人数 这个会影响无人观看事件 我们也不推荐这个录制方式

**Comment by lj2508-com** [comment]
好的，了解。谢谢各位大佬
