### ISSUE TITLE
[BUG] SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate

### ISSUE THREAD

**Issue by dualven** [ZLMediaKit/ZLMediaKit#2809]
### 现象描述
linux下一直报这个警告： 
[MediaServer] [15-event poller 2] SSLBox.cpp:195 operator() | SSL_CTX_set_verify callback, depth: 0 ,err: self signed certificate
服务器一直报这个warning，但不影响 使用；

windows环境下没有这种情况 。

### 如何复现?

我自己制作 了一个ssl.pem ，./MediaServer -c ./conf/config.ini -s ssl.pem 这样运行后。就出现现象描述。

**Comment by xia-chu** [comment]
这个是zlm请求的https 发现对方用的是自签名的ssl证书 所以会打印这样的警告

**Comment by xia-chu** [comment]
不过不影响功能

**Comment by dualven** [comment]
好的，谢谢
