### ISSUE TITLE
[技术咨询] 请问在API中，mk_player_create()如何播放本地mp4文件以及本地USB摄像头

### ISSUE THREAD

**Issue by arzen** [ZLMediaKit/ZLMediaKit#2812]
**API**
使用mk_player_create()创建的播放器
-  如何播放本地mp4文件？
-  如何播放本地USB摄像头？
-  如何播放非H264/H265网络摄像头(有可能是YUV/RGB裸流)

api/test范例中没有相关的参考，所以在此请教，谢谢！

**Comment by xia-chu** [comment]
mk_player只支持rtsp/rtmp/hls/http-ts/http-flv协议 其他不支持。
我建议你直接用ffmpeg。
