### ISSUE TITLE
[技术咨询] http-flv 集群模式

### ISSUE THREAD

**Issue by Zweyer** [ZLMediaKit/ZLMediaKit#2813]
**咨询的功能模块**
- http-flv 集群模式

**咨询的具体内容和问题**
- 您好，我在查看集群方式文档时看到“zlmediakit也支持了通过配置文件的方式来实现集群模式”、“zlmediakit的溯源方式支持rtsp/rtmp/hls/http-ts(http-flv的方式暂未开放)”，请问 http-flv 集群是有什么难点没有实现，目前有计划实现吗？如果没有计划，我应该如何实现，请提供下思路，谢谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
现在http-flv也支持了
