### ISSUE TITLE
[功能请求] 建议忽略不支持的RTSP请求而不是响应403

### ISSUE THREAD

**Issue by pedoc** [ZLMediaKit/ZLMediaKit#2814]
**描述该功能的用处，可以提供相关资料描述该功能**
https://streamedian.com/ 实现了一个纯h5版的rtsp播放器,需要后端支持,配合WebSocket作为传输渠道进行rtsp的控制协议和数据转发最终实现前端直接支持rtsp协议的直播流.
然后我们在测试过程中,使用如下命令推送一个h265视频到zlm
```
ffmpeg -re -stream_loop -1 -i I:\Movie\big_buck_bunny-h265.mp4 -vcodec libx265 -acodec aac -f rtsp -rtsp_transport tcp rtsp://192.168.1.2/live/h265
```
然后在播放器中使用``rtsp://192.168.1.2/live/h265``作为播放地址进行播放
此时播放器会报告403错误,如图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/6604230/722f7332-8cbb-4242-a154-99957431863f)
以下是播放器和ZLM的RTSP信令交互
```
...省略部分消息
WSP/1.1 SWITCH
contentLength: 4
seq: 5

h265

WSP/1.1 WRAP
contentLength: 182
seq: 6

SETUP rtsp://192.168.1.2:554/live/h265/streamid=0 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
Date: Tue, 05 Sep 2023 04:38:31 GMT
CSeq: 3
User-Agent: SFRtsp 0.3

WSP/1.1 200 OK
seq: 6

RTSP/1.0 403 Forbidden
CSeq: 3
Date: Tue, Sep 05 2023 04:38:32 GMT
Server: ZLMediaKit(git hash:f26e253/2023-09-02T19:26:24+08:00,branch:master,build time:2023-09-05T12:26:42)
Session: vtnSXZ8DAIwG

...省略部分消息
```
当播放器向zlm发送了``SWITCH``之后,zlm回复了一个``403 Forbidden``

当前,我可以修改播放器端代码,不发送这个SWITCH,然后就不会报错.

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
对于vlc等播放器,zlm能够正常响应.
所以这可能是是一个兼容性增强,即增强一些不标准的客户端的健壮性.

**描述你期望实现该功能的方式和最终效果**
希望对于这种类似的不识别(非RFC标准)的直接丢弃或者直接回复200OK.

**环境**
zlm最新版本,提交id:f26e25323f6d8701a2ed522b0ed0fe4aa18c2564

**风险点**
1. 我不是很确定如此操作的话是否可能影响其他客户端.

**Comment by xia-chu** [comment]
这个走的是websocket协议吗？端口是554还是80？

**Comment by pedoc** [comment]
> 这个走的是websocket协议吗？端口是554还是80？

播放器走的是WebSocket协议,通信端口是80;
链路如下

请求方向:
播放器(浏览器端)->发送RTSP信令和数据到后端WebSocket代理服务->后端程序建立到zlm的RTSP信道(端口554)并将RTSP信令和数据通过此信道转发至zlm

响应方向:
->zlm通过RTSP信道回复RTSP信令和数据到后端的WebSocket代理服务->后端WebSocket代理服务找到对应的客户端链路并将数据发送给播放器

相当于后端这个WebSocket就是一个透明代理,是为了解决播放器无法直接使用tcp/udp协议而做的一个代理层.

**Comment by xia-chu** [comment]
所以为什么不直接访问zlm？

**Comment by xia-chu** [comment]
streamedian有什么它能做 zlm做不了的吗

**Comment by pedoc** [comment]
> 所以为什么不直接访问zlm？
是这样,这个项目太简单了,简单到生产环境不需要上zlm,而是直接通过rtsp协议连接前端相机.
然后在本地开发测试的时候,发现了这个现象.直接连接相机播放时不会出现此错误,也就是说相机端忽略了这个SWITCH.

> streamedian有什么它能做 zlm做不了的吗
streamedian他们实现了一个h5的播放器以及一个WebSocket代理服务(商用收费).当前市面上直接支持rtsp协议播放的只有这一个选择(截止目前),他的播放器是开源免费的,所以我自行实现了一个WebSocket代理服务端,用于一些非常小的场景.
此外,浏览器无法直接支持rtsp协议,所以才使用WebSocket进行传输.

当前zlm据我目前了解应该不支持 rtsp over websocket? 如有误请谅解

**Comment by xiongguangjie** [comment]
你这个通过addstreamproxy 不就行了，使用这种方式，也就录像或者私有信令有些应用场景

**Comment by pedoc** [comment]
> 你这个通过addstreamproxy 不就行了，使用这种方式，也就录像或者私有信令有些应用场景

感谢各位大佬的建议哈,应用场景上有多种方案可以达到目的,但这并非此issue的意图.

让我们回到issue本身上
即,如果有客户端向zlm发送了非rfc的RTSP信令,zlm的默认行为应如何处置的问题.

当前,zlm选择回复403.我个人的初衷是希望能够opt-out这个行为,比如回退到忽略或者是直接响应200 ok
当然,这么做本身可能也就是不标准的.
在兼容性和标准之间应该会有一个平衡.

如果觉得这种行为是不可接受的,请将issue标记为拒绝,留作其他人参考.

**Comment by xiongguangjie** [comment]
> 

1，zlm默认处理是返回403，
2，如果你要直接返回200 或者有自己的响应，可以二次开发，在下面截图的地方修改（如下所示）

![企业微信截图_16940666337895](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/413c98b0-5a02-4838-a0c7-357db7ae6460)

**Comment by pedoc** [comment]
好的,感谢指点

那我先关闭这个问题了
