### ISSUE TITLE
c api接口无法获取解码前的sps pps 等

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#2816]
**咨询的功能模块**
- c api 接口的使用

**咨询的具体内容和问题**
- c api接口 只能获取track的width height 等 但是不能拿到视频的sps pps vps 音频的aaccfg
- mk_track.cpp使用这样的方式是否可行？
- 新增接口getSps getPps getVps getAacCfg
<img width="499" alt="1693982210101_B65B4F21-2D5A-4c0b-9B2B-66E6F6505E2B" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/19390025/6c0afafb-07da-4464-9d9d-b72e4f5b5d51">

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by hh-kai** [comment]
这个方法我试了不行 有没有其它方法可以获取到视频、音频的相关参数 sps pps vps aaccfg
有了这些打开的视频流才能进行录像

**Comment by hh-kai** [comment]
换了这种方式 是否是可行的 还是说不推荐使用这样的方式
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/19390025/34e9a38e-5aca-4641-9758-a0ef59d29516)

**Comment by xiongguangjie** [comment]
你可以通过frame 将其中的sps pps vps aaccfg 解析出来

**Comment by hh-kai** [comment]
ok frame里面确实可以解析出来
