### ISSUE TITLE
[技术咨询] MP4录制配置咨询

### ISSUE THREAD

**Issue by donnasky** [ZLMediaKit/ZLMediaKit#2820]
想请教下录制MP4是用什么录制的，能大概介绍下原理吗？除了控制切片文件大小我能控制录制的质量吗？比如说每秒的帧数，画面质量等。

**Comment by xia-chu** [comment]
录制质量是源端控制的 zlm又不能编解码 当然无法控制。
mp4录制用的第三方库 https://github.com/ireader/media-server
