### ISSUE TITLE
[技术咨询]  wvp-pro 得webrtc页面视频播放正常 但是返回得地址无法播放

### ISSUE THREAD

**Issue by zhanpc** [ZLMediaKit/ZLMediaKit#2821]
**咨询的功能模块**
- webrtc功能

**咨询的具体内容和问题**
- wvp-pro 得webrtc页面视频播放正常 但是返回得地址无法播放 使用得是liveplayer插件   
-用的是webrtcs://+wvp-pro返回得rtcs地址

测试页面打开也是正常
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/86341644/65532984-f238-4d0c-ae27-05db823af90a)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/86341644/ca720308-6469-4c85-a494-e102f289ed57)

页面直接打开url是如下报错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/86341644/8d2dec84-1114-421f-86ba-1b04514c0888)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个地址是给js代码调用的 不是给你浏览器直接打开的

**Comment by xia-chu** [comment]
请使用zlm的[webrtc demo网页](https://zlmediakit.com/webrtc/)播放此url
