### ISSUE TITLE
[技术咨询]  vcpkg编译出来的怎么不支持webrtc

### ISSUE THREAD

**Issue by wuzhenda** [ZLMediaKit/ZLMediaKit#2825]
**咨询的功能模块**
- vcpkg编译

**咨询的具体内容和问题**
- 功能模块

按vcpkg编译条件，默认的install zlmediakit和完全安装  
.\vcpkg\vcpkg.exe  install  zlmediakit[core,mp4,openssl,webrtc,sctp]
都试过，在编译出来的tools\zlmediakit下的MediaServer.exe运行后没有webrtc部分。

**Comment by xia-chu** [comment]
你要把config.ini的中的rtc.port改成8000 默认是0 不开启的

**Comment by xia-chu** [comment]
不过vckpg编译的srtp应该没开 --enable-openssl
<img width="956" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/e156a706-f5d0-4c98-8bf1-0dc364c6bfee">

**Comment by linj121** [comment]
> 终于编译出来了，不过webrtc延时很大，和hls一样大概有10秒的延时，这正常吗？
> 
> 编译参考的[这儿](https://www.jianshu.com/p/f6f1c0b7e32b)

我也按照同样方法编译成功了，使用了完全安装，延迟在1-2s，平台是Ubuntu 20.04.6 LTS。

**Comment by linj121** [comment]
> 目前我使用vcpkg安装也碰到这个问题
> 
> 报错信息如下： `2024-02-28 17:56:48.468 E [MediaServer] [70334-event poller 2] SrtpSession.cpp:214 SrtpSession | srtp_create() failed: unspecified failure (srtp_err_status_fail) 2024-02-28 17:56:48.468 W [MediaServer] [70334-event poller 2] WebRtcSession.cpp:106 onError | 6-45(192.168.1.10:50638) 5(MS_THROW_ERROR)`
> 
> 我检查了 /Users/alex/workspace/study/vcpkg/ports/libsrtp/portfile.cmake，内如如下： <img alt="image" width="901" src="https://private-user-images.githubusercontent.com/5088081/308521539-bcb06cc0-8eac-4f47-8b98-f5014f8e655f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMjEzMTEsIm5iZiI6MTcwOTMyMTAxMSwicGF0aCI6Ii81MDg4MDgxLzMwODUyMTUzOS1iY2IwNmNjMC04ZWFjLTRmNDctOGI5OC1mNTAxNGY4ZTY1NWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMTkyMzMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM3NjJlYmRhZDhhMjA1YTIwYWMxMDExZmE0OTY4NmZhZDIwODIzMDVlZTZiZDg0MGZlY2I2ODg5OTcyNTllMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.92ifZBK-JxQR9058HYQUxMbnw2WmAQSSCQuHCy9zonI">
> 
> 请问是 vcpkg 安装都是这样吗？有什么处理办法？

得在`vcpkg_cmake_configure`的`OPTIONS`中添加这个选项再进行编译: `"-DENABLE_OPENSSL:BOOL=ON"`，如下：
```
vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        "-DENABLE_OPENSSL:BOOL=ON"
        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/cmake-project-include.cmake"
        -DTEST_APPS=OFF
)
```

**Comment by xia-chu** [comment]
新版本已经修复这个问题了
