### ISSUE TITLE
国标设备接入，gop缓存打开之后，有可能存在其它设备的缓存，播放出来跟实际设备对应不上

### ISSUE THREAD

**Issue by chen-da-git** [ZLMediaKit/ZLMediaKit#2829]
国标接入设备，gop缓存打开，创建RTP服务的端口为随机的，如果相同的端口，随机的时间比较短（比如，随机300的端口，然后刚关闭视频流，在打开另外的设备，随机的端口也是300的话，设备取的视频流刚开始为上个设备的gop缓存），取的视频为上个设备的gop缓存，这个影响视频播放的质量，有没有配置项避免这种情况，

**Comment by xia-chu** [comment]
说明这个端口没回收 回收了就不会这样

**Comment by chen-da-git** [comment]
你好，我看系统日志有，类似于这样的回收端口的日志信息，Rtsp.cpp:402 operator() | return port to pool:60028-60029 ，这种情况下，有没有办法避免

**Comment by chen-da-git** [comment]
你好，在创建rtp服务的时候，使用的是服务的随机端口，没有自己定义端口
![1694483581534](https://github.com/ZLMediaKit/ZLMediaKit/assets/59857213/14f6e1c8-8cd9-44b6-894e-ed892921f1b1)

**Comment by xia-chu** [comment]
gop跟MediaSource挂钩的 如果媒体注销了 就不会出现你所说的问题

**Comment by chen-da-git** [comment]
嗯，好的，感谢，这个会不会还有其它的缓存能导致这个问题，我们使用的是wvp的sip会话，会有周期性的关闭视频流的操作，复现问题的时候，端口是有回收的，

**Comment by xia-chu** [comment]
我觉得就是端口没回收 就复用导致的 zlm没什么bug的 代码质量上乘
