### ISSUE TITLE
zlmediakit库实现的websocket客户端是否支持设置HTTP代理服务器

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#2830]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
 websocket协议栈的客户端实现逻辑
**咨询的具体内容和问题**
 zlmediakit库实现的websocket客户端是否支持设置HTTP代理功能
- 此处展开您咨询内容的描述
我通过zlmediakit库分别实现了一个websocket客户端和websocket服务器，websocket客户端运行在局域网，websocket服务器运行在公网。并且已经在局域网设置了HTTP代理，却依旧无法连接到公网服务器。而其他的开源库（比如python的websocket-client库）实现的websocket客户端能够连接成功。
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
不支持的 是不是要读取环境变量？我也没去了解代理的原理 代理应该透明的 对程序来说不可见的

**Comment by quxiaohui-debug** [comment]
![img_v2_e9fee9ff-d686-42bd-bc10-362ab014c5fg](https://github.com/ZLMediaKit/ZLMediaKit/assets/56460673/8f8f5925-d4ed-4998-a016-a5dc926f4c69)
在有些特殊的场景下，代理不是透明的，需要程序处理。我增加了proxy_host和proxy_port两个配置项，并在调用startConnect函数时，将目的IP、端口修改为代理服务器IP和端口。问题就解决啦

**Comment by xia-chu** [comment]
这样的话 那你为什么不直接把zlm的连接地址修改为代理地址和端口呢？

**Comment by quxiaohui-debug** [comment]
这样子的话，代理服务器就不知道我们真实的目的地址了呀。个人感觉此时的代理服务器扮演着中介者的角色，我们把目的地址通过HTTP报文告诉它，由它代理我们转发。
