### ISSUE TITLE
[技术咨询] webrtc功能海康威视播放正常 大华无法播放

### ISSUE THREAD

**Issue by zhanpc** [ZLMediaKit/ZLMediaKit#2834]
**咨询的功能模块**
- webrtc功能模块的播放

**咨询的具体内容和问题**
- ZLMediaKit用海康威视摄像头调试过了 播放正常  使用大华之后 常规视频播放正常 webrtc无法播放 报错如下
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/86341644/79897d57-edb3-4c33-b893-b5947f7acc54)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个视频应该是H265的 webrtc不支持
