### ISSUE TITLE
[技术咨询] 100M带宽，内网ZLMediaKit拉取40个海康摄像头RTSP流，转为HLS。交换机NAT映射后，外网通过Video.js在前端页面加载流，卡顿，一段时间后流断开。

### ISSUE THREAD

**Issue by houluy** [ZLMediaKit/ZLMediaKit#2836]
**咨询的功能模块**
- ZLMediaKit拉RTSP转为HLS后，前端利用Video.js组件播放。

**咨询的具体内容和问题**
- 部署环境：

40路海康摄像头光纤连接至管理服务器，同网段一台Windows服务器运行ZLMediaKit，拉取40路RTSP流，转协议为HLS，通过交换机NAT向外网透出ZLMediaKit端口，出口带宽100M。外网Vue3前端页面，基于Video.js加载HLS视频流，分为4、9、16宫格播放。

- ZLMediaKit主要配置：

  + hls_demand=0
  + segNum=3
  + segKeep = 0
  + fileBufSize=65536

- 出现问题：

1. 视频流卡顿，几乎无法正常播放。某些时段能正常播放，但仅能坚持数十秒至数分钟，后开始转圈加载；或者坚持一会儿后，直接连接断开，没有任何数据返回；
3. ZLMediaKit Log反复输出：
`2023-09-15 11:54:20.291 T MediaServer.exe[20300-event poller 58] HttpSession.cpp:119 onError | 2004710-5632 close connection after send http body completed.`
`2023-09-15 11:55:45.298 T MediaServer.exe[20300-event poller 21] HttpSession.cpp:33 ~HttpSession | 2004860-3920`
`2023-09-15 11:54:55.774 D MediaServer.exe[20300-event poller 2] HttpCookieManager.cpp:100 onManager | 029d2fed2283afd97ba930cb9a1fc489 cookie过期:029d2fed2283afd97ba930cb9a1fc489
2023-09-15 11:54:55.774 W MediaServer.exe[20300-event poller 2] HlsMediaSource.cpp:42 ~HlsCookieData | 2004677-3064 HLS播放器(__defaultVhost__/example/1)断开,耗时(s):0`

- 咨询：

请问导致卡顿的原因大概在哪个方面？带宽不足 或是 HLS客户端的使用方式有问题（例如cookie问题？）或是 HLS协议配置有问题（目前没开启录制）？是否有推荐的测试或使用方式？

**Comment by xia-chu** [comment]
这是浏览器同源限制 你16宫格播放 那http链接数 都好几十个了 而浏览器最多只支持同源6路

**Comment by houluy** [comment]
噢，那如果需求是在Web页面同屏展示多个视频流，您建议应该怎么个思路实现？应该用ZLMediaKit转成哪种流？

**Comment by xia-chu** [comment]
用websocket-flv或者webrtc都可以
