### ISSUE TITLE
利用https访问zlm出现ip限制访问服务的问题

### ISSUE THREAD

**Issue by shiwuhai** [ZLMediaKit/ZLMediaKit#2838]
**咨询的功能模块**
- 利用https访问zlm

**咨询的具体内容和问题**
- 利用公网ip绑定的免费域名（域名没有备案），配置了nginx证书，用https访问zlm端口时出现Your ip is not allowed to access the service.
但是wvp可以用https正常访问。查看了服务器没有开启防火墙（公网ip没有限制端口），没有下载nginx。访问zlm端口时服务器显示建立了tcp连接，不知道是什么问题导致限制ip访问服务

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
配置文件有ip限制

**Comment by Telpo123** [comment]
> 配置文件有ip限制
是zlm的config.ini文件吗？

**Comment by xia-chu** [comment]
zlm的http文件服务器和http api默认不允许公网访问，你可以修改配置文件，加上ip白名单或者禁用

**Comment by shiwuhai** [comment]
> zlm的http文件服务器和http api默认不允许公网访问，你可以修改配置文件，加上ip白名单或者禁用

我之前看了我的ip是在ip_allow_range里面的，但是不知道为什么没生效。置空后可以用https访问了，感谢!

**Comment by ahalert** [comment]
借这个issue咨询下，使用nginx代理http和https的时候需要怎么配置？nginx是否直接proxy_pass zlm_http_IP:zlm_http_port 就行？zlm配置文件还需要配置https证书吗？

**Comment by xia-chu** [comment]
你代理了 应该就不用配置zlm的证书了
