### ISSUE TITLE
[技术咨询] 每次重新创建容器，secret都会随机生成，怎样才能固定下来，使用127.0.0.1访问也必须提供secret

### ISSUE THREAD

**Issue by guoz2013** [ZLMediaKit/ZLMediaKit#2839]
**API鉴权**
关于API鉴权问题，每次创建容器secret都会改变

**咨询的具体内容和问题**
是有有办法在创建容器的时候把secret固定下来，本地使用127.0.0.1访问，同样需要secret鉴权

**Comment by xia-chu** [comment]
你为什么要多次创建容器呢？如果secret固定了 那大家的secret都一样 岂不是容易被黑客攻击？

**Comment by xia-chu** [comment]
创建docker实例后 就不要重建容器啊， 用docker start 而不是 docker run

**Comment by guossf** [comment]
docker service 部署后，api_secret可以通过env环境变量去修改吗？

**Comment by xia-chu** [comment]
> docker service 部署后，api_secret可以通过env环境变量去修改吗？

 不能 不过k8s部署的话 可以挂载替换配置文件 docker也可以

**Comment by YLD2306** [comment]
@guoz2013 您好，请问一下随机生成的secret值，在哪个文件可以看到？我现在疑惑，望解答。

**Comment by xia-chu** [comment]
> 下随机生成的secret值，在哪个文件可以看到？我现在疑惑，望解答。

在main.cpp
