### ISSUE TITLE
[BUG] 相机国标rtp推流解析帧  打印关键帧  接口一直找不到关键帧

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2840]
想在国标rtp推流的地址做处理对帧进行转码，发现获取到的帧接口找不到关键帧，下图是我加的打印

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/b0be43db-9f9a-42a9-a843-418415108e3b)

结果是一直不会打印，怀疑判断I帧的方式有问题，还是我理解的有问题

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/65e43538-4e33-4155-913a-af4523d2fa72)

是不是这个地方  应该使用 || 而不是 &&
判断265关键帧
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/6c680794-bb33-46f8-a8b5-2f75b703968f)
判断264关键帧
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/0a889bde-cfd5-48e9-be8a-2c1a6263474d)

### 现象描述

通过接口打印发现未得到关键帧

### 如何复现?

海康相机国标rtp推流，在接口中打印 
if (frame->keyFrame()) {
                DebugL << "get key frame";
 }
未打印出关键帧

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这么判断是正确的，如果不行，吧ps流上传，我们分析下

**Comment by zhang-chuanfeng** [comment]
[a.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12656950/a.zip)
下面是ps包

**Comment by zhang-chuanfeng** [comment]
> 这么判断是正确的，如果不行，吧ps流上传，我们分析下
https://github.com/ZLMediaKit/ZLMediaKit/files/12656950/a.zip

**Comment by zhang-chuanfeng** [comment]
> 这么判断是正确的，如果不行，吧ps流上传，我们分析下

[数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)

**Comment by xiongguangjie** [comment]
> > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> 
> [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)

这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）

**Comment by zhang-chuanfeng** [comment]
> > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > 
> > 
> > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> 
> 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）

跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble注释掉了

**Comment by xiongguangjie** [comment]
> > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > 
> > > 
> > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > 
> > 
> > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> 
> 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&

不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1

**Comment by zhang-chuanfeng** [comment]
> first_slice_segment_in_pic_flag



> > > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > > 
> > > > 
> > > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > > 
> > > 
> > > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> > 
> > 
> > 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&
> 
> 不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1

如果没有分slice是不是这里就不对了；根据打印看如果加上这个判断是没有进入打印逻辑的。这里面细节我不太清楚。

**Comment by xiongguangjie** [comment]
> > first_slice_segment_in_pic_flag
> 
> > > > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > > > 
> > > > > 
> > > > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > > > 
> > > > 
> > > > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> > > 
> > > 
> > > 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&
> > 
> > 
> > 不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1
> 
> 如果没有分slice是不是这里就不对了；根据打印看如果加上这个判断是没有进入打印逻辑的。这里面细节我不太清楚。

是否正常播放，rtsp是否播放可以秒开，如果都可以，那就没问题

**Comment by xiongguangjie** [comment]
我看你的日志打印十分正常的，你可以到h265Track 里面去分析处理

**Comment by zhang-chuanfeng** [comment]
> > > first_slice_segment_in_pic_flag
> > 
> > 
> > > > > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > > > > 
> > > > > > 
> > > > > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > > > > 
> > > > > 
> > > > > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> > > > 
> > > > 
> > > > 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&
> > > 
> > > 
> > > 不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1
> > 
> > 
> > 如果没有分slice是不是这里就不对了；根据打印看如果加上这个判断是没有进入打印逻辑的。这里面细节我不太清楚。
> 
> 是否正常播放，rtsp是否播放可以秒开，如果都可以，那就没问题

rtsp是可以播的，我是想用keyFrame()接口做处理的，发现这个接口一直判断的不出关键帧。

**Comment by xiongguangjie** [comment]
> > > > first_slice_segment_in_pic_flag
> > > 
> > > 
> > > > > > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > > > > > 
> > > > > > > 
> > > > > > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > > > > > 
> > > > > > 
> > > > > > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> > > > > 
> > > > > 
> > > > > 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&
> > > > 
> > > > 
> > > > 不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1
> > > 
> > > 
> > > 如果没有分slice是不是这里就不对了；根据打印看如果加上这个判断是没有进入打印逻辑的。这里面细节我不太清楚。
> > 
> > 
> > 是否正常播放，rtsp是否播放可以秒开，如果都可以，那就没问题
> 
> rtsp是可以播的，我是想用keyFrame()接口做处理的，发现这个接口一直判断的不出关键帧。

因为一个Frame 里面可能有多个NAL,判断是否是关键帧需要切分NAL,然后去判断NAL ,这个操作是在H265Track 里面操作的

**Comment by zhang-chuanfeng** [comment]
> > > > > first_slice_segment_in_pic_flag
> > > > 
> > > > 
> > > > > > > > > 这么判断是正确的，如果不行，吧ps流上传，我们分析下
> > > > > > > > 
> > > > > > > > 
> > > > > > > > [数据流.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12657242/default.zip)
> > > > > > > 
> > > > > > > 
> > > > > > > 这个流无分析了下是完全正常的，判断关键帧是需要DecodecAble 是因为一帧有多个slice的情况（也就是一帧有多个NAL）
> > > > > > 
> > > > > > 
> > > > > > 跟据你提供的判断keyFrame()接口，一直不会打印出获取到关键帧；所以我把decodeAble用||的方式 没有使用&&
> > > > > 
> > > > > 
> > > > > 不可能的，decodeAble 其实就是判断 这个first_slice_segment_in_pic_flag 标志是否为1
> > > > 
> > > > 
> > > > 如果没有分slice是不是这里就不对了；根据打印看如果加上这个判断是没有进入打印逻辑的。这里面细节我不太清楚。
> > > 
> > > 
> > > 是否正常播放，rtsp是否播放可以秒开，如果都可以，那就没问题
> > 
> > 
> > rtsp是可以播的，我是想用keyFrame()接口做处理的，发现这个接口一直判断的不出关键帧。
> 
> 因为一个Frame 里面可能有多个NAL,判断是否是关键帧需要切分NAL,然后去判断NAL ,这个操作是在H265Track 里面操作的

ok  在track里面可以判断出 ;感谢
