### ISSUE TITLE
针对高分辨率的摄像头怎么配置保证视频流畅度

### ISSUE THREAD

**Issue by yuzhihaoGitHub** [ZLMediaKit/ZLMediaKit#2844]
##大神您好，针对高分辨率的摄像头怎么配置保证视频流畅度。比如我下面的这个海康摄像头
<img width="1073" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/53512354/6a3904cd-6cd8-4846-9272-750d840ba132">

**Comment by xia-chu** [comment]
这个需要转码降低码率 可以使用addFFmpegSource接口
