### ISSUE TITLE
[技术咨询] 服务器视频点播问题

### ISSUE THREAD

**Issue by OMG59E** [ZLMediaKit/ZLMediaKit#2845]
服务器上任意路径任意编码的本地视频，如何让其他人观看呢？请教下，有什么经济的方案吗?
ffmpeg转码推流至ZLMediaKit对吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
可以用addFFmpegSource接口 这个接口就是fork ffmpeg进程 ，可以读取文件 然后rtmp推流给zlm

**Comment by OMG59E** [comment]
小白再请教下多人点播同一视频的情况下，会fork多个进程吗？在没有观看的时候，是自己调api释放资源，还是自动释放？

**Comment by xia-chu** [comment]
addFFmpegSource/delFFmpegSource是你主动调的 所以这个行为取决于你

不过你配合未找到流hook和无人观看hook调用这个两个api 不会多次fork进程。
