### ISSUE TITLE
[BUG] 断流续播功能相关

### ISSUE THREAD

**Issue by wuchingyy** [ZLMediaKit/ZLMediaKit#2850]
### 现象描述

断流续推的功能，如果设置了1分钟，在开始后的10秒断流了，15秒恢复，这个时候是正常的，如果在50秒的时候又断流了而且在1分05秒的时候还没续播上的话，这个流就会被关闭了。通常的逻辑思维应该是在50秒的时候断流，应该在1分50秒的时候才关闭这个流。
如果这个断流是发生在1分5秒后发生的，假设是1分30秒再发生断流的，这个流能维持到2分30秒

### 如何复现?
假设配置continue_push_ms = 60000
1. 推一路流，开播后10秒拔网线（或者各种禁用网络的工具）
2. 过一会重新插上网线
3. 大概在快接近1分钟的时候再拔网线
4. 整体时间在1分5秒的时候插上网线，发现不能续推了

看代码关于这部分的实现是使用计时器延后销毁、执行析构函数，貌似看起来没有什么好的办法解决，不知道作者有没有什么建议、看法？

**Comment by xiongguangjie** [comment]
continue_push_ms 把时间设置长一些

**Comment by xia-chu** [comment]
实际上 延迟注销媒体的时间由continue_push_ms决定。
不过你推流多长时间，都不干扰延迟注销延时。

**Comment by xia-chu** [comment]
所以应该是先打印~RtmpSession析构日志
然后再延时continue_push_ms毫秒再打印媒体注销日志。

我相信日志会印证我说的。

**Comment by lunasaw** [comment]
> 实际上 延迟注销媒体的时间由continue_push_ms决定。 不过你推流多长时间，都不干扰延迟注销延时。

断续推流支持，推流器关闭后重新推流吗。推流器关闭进程，好像会触发流注销。有其他解决的办法吗，主要考虑的一个多文件连续播放的问题

**Comment by wuchingyy** [comment]
可能我没描述清楚，不是continue_push_ms参数调整多长的问题，还是一开始的例子，continue_push_ms设置60秒

假设出现在第30秒的时候网络抖动断流了，过几秒后恢复了，然后在第80秒的时候又抖动断流了，一直到第100秒才恢复过来，这个时候媒体已经注销了，因为第一次断流发生在第30秒，在第90秒的时候，第一个session的析构函数被执行，导致注销

实际期望的是，在80秒的时候断流，只要在第140秒之前连接回来都可以续推

**Comment by xia-chu** [comment]
> 假设出现在第30秒的时候网络抖动断流了，过几秒后恢复了，然后在第80秒的时候又抖动断流了，一直到第100秒才恢复过来，这个时候媒体已经注销了，因为第一次断流发生在第30秒，在第90秒的时候，第一个session的析构函数被执行，导致注销
> 
> 实际期望的是，在80秒的时候断流，只要在第140秒之前连接回来都可以续推

你说的不对啊 为什么会注销呢？只要你推流重连成功了 那么新的RtmpSession会获取MediaSource的归属权，它如果又断流了，
这个延时注销是重新计算延时的 根本就不会出现你说的情况啊

**Comment by xia-chu** [comment]
代码逻辑是这样的：
<img width="1093" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/632f8959-8a66-4b0f-9665-8532ef308147">

每次延时析构MediaSource对象 都是重新计时 互不干扰的。
而且可以有多个定时器持有MediaSource对象，只要MediaSource对象被持有 就不会注销。

**Comment by lunasaw** [comment]
> 么会注销呢？只要你推流

这个只能是网络断开吗，比如我ffmpeg程序终止了，然后向同样的流地址推，好像进程结束的时候，流就注销了，再推会重新注册流，这个连续推流多个文件怎么处理

**Comment by xia-chu** [comment]
> 这个只能是网络断开吗，比如我ffmpeg程序终止了，然后向同样的流地址推，好像进程结束的时候，流就注销了，再推会重新注册流，这个连续推流多个文件怎么处理

注释这个代码即可：
<img width="1501" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/79f8360c-00c5-4eaf-b5d3-81331ae3a813">

**Comment by wuchingyy** [comment]
这个MediaSource的归属权，我试过，是根据ip和客户端的端口来决定的，这要看系统有没有把这个连接杀掉，杀掉的话发起一个新连接，端口从原本的12345变成12346了，这样就判断不是owner了

正如您所说的，只要MediaSource被持有，就不会注销，像我之前举的例子，80秒断流，100秒才恢复的话，在到达90秒的时候，MediaSource是不被持有的，由第一个session对象发起的doDelayTask就可以生效了

**Comment by wuchingyy** [comment]
补充一下这个，可能会比较好理解
|-------------[SessionA]------[SessionB]-----[SessionB]-------[销毁]——————[原本期望是这里才销毁]
0                           30                        40                      80                       90                                       140

SessionA在30秒断开了，由于原本的socket已失效，重新发起一个连接SessionB，SessionB在80秒的时候断开了，到90秒的时候，会发生销毁的，因为MediaSource没有被持有

**Comment by lunasaw** [comment]
> > 这个只能是网络断开吗，比如我ffmpeg程序终止了，然后向同样的流地址推，好像进程结束的时候，流就注销了，再推会重新注册流，这个连续推流多个文件怎么处理
> 
> 注释这个代码即可： <img alt="图片" width="1501" src="https://user-images.githubusercontent.com/11495632/270849500-79f8360c-00c5-4eaf-b5d3-81331ae3a813.png">

okok 我尝试下，再问下rtp流支持断续推流吗

**Comment by xia-chu** [comment]
> 补充一下这个，可能会比较好理解 [SessionA-0]-----[SessionA-30]------[SessionB-40]-----[SessionB-80]-----[销毁-90]———[原本期望是这里才销毁-140]
> 
> SessionA在30秒断开了，由于原本的socket已失效，重新发起一个连接SessionB，SessionB在80秒的时候断开了，到90秒的时候，会发生销毁的，因为MediaSource没有被持有

SessionB已经断开了 在断开10秒后再销毁注销MediaSource没问题啊 就是这么设计的啊 就是延迟注销啊

**Comment by xia-chu** [comment]
断流续推功能是说 这个流不会由于推流客户端的断开导致注销 导致播放器断开。
你可以重启推流客户端接着推流(新的tcp链接) 并且播放器在无感知的情况下继续播放。

你说的复现步骤 是验证rtmp推流超时的功能 不是一回事，那么是参数rtmp.keepAliveSecond决定的 不是一回事
