### ISSUE TITLE
[技术咨询] arm64启动server在未进行任何拉流处理cpu保持在7%-8%是否有优化空间

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#2861]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

我在arm64的设备编译运行zlm server，发现正常启动后未进行任何拉流操作，cpu一直保持在7%-8%左右，是否有优化空间，正常没有流处理的cpu应该在休眠状态吧，arm64算低功耗设备。

下面是构建时开启的宏

option(ENABLE_API "Enable C API SDK" OFF)
option(ENABLE_API_STATIC_LIB "Enable mk_api static lib" OFF)
option(ENABLE_ASAN "Enable Address Sanitize" OFF)
option(ENABLE_CXX_API "Enable C++ API SDK" OFF)
option(ENABLE_FAAC "Enable FAAC" OFF)
option(ENABLE_FFMPEG "Enable FFmpeg" OFF)
option(ENABLE_HLS "Enable HLS" OFF)
option(ENABLE_JEMALLOC_STATIC "Enable static linking to the jemalloc library" OFF)
option(ENABLE_MEM_DEBUG "Enable Memory Debug" OFF)
option(ENABLE_MP4 "Enable MP4" OFF)
option(ENABLE_HLS_FMP4 "Enable HLS-FMP4" OFF)
option(ENABLE_MSVC_MT "Enable MSVC Mt/Mtd lib" OFF)
option(ENABLE_MYSQL "Enable MySQL" OFF)
option(ENABLE_OPENSSL "Enable OpenSSL" OFF)
option(ENABLE_PLAYER "Enable Player" OFF)
option(ENABLE_RTPPROXY "Enable RTPPROXY" ON)
option(ENABLE_SERVER "Enable Server" ON)
option(ENABLE_SERVER_LIB "Enable server as android static library" OFF)
option(ENABLE_SRT "Enable SRT" OFF)
option(ENABLE_TESTS "Enable Tests" OFF)
option(ENABLE_SCTP "Enable SCTP" OFF)
option(ENABLE_WEBRTC "Enable WebRTC" OFF)
option(ENABLE_X264 "Enable x264" OFF)
option(ENABLE_WEPOLL "Enable wepoll" ON)
option(DISABLE_REPORT "Disable report to report.zlmediakit.com" ON)
option(USE_SOLUTION_FOLDERS "Enable solution dir supported" OFF)

下图htop显示cpu使用率
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/871935eb-4bff-4081-a6c6-9ab3ea66fd4c)

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个设备性能很差吗？多少核心的？ ./MediaServer -t 1运行试试

**Comment by zhang-chuanfeng** [comment]
> 这个设备性能很差吗？多少核心的？ ./MediaServer -t 1运行试试

四核64位Cortex-A55，主频最高2.0GHz；执行差不多

**Comment by xia-chu** [comment]
可以perf top看下占用cpu的函数有哪些

**Comment by zhang-chuanfeng** [comment]
> 可以perf top看下占用cpu的函数有哪些

两块板子cpu使用同一个  两块板子运行linux内核一个4点多  一个5点多，板子厂商不是一家。同一个程序表现不一致。一个保持在3%差不多，一块保持在7%

**Comment by xia-chu** [comment]
zlm有条线程在不停的获取时间戳 每秒执行2000次 应该是这个问题

**Comment by zhang-chuanfeng** [comment]
> zlm有条线程在不停的获取时间戳 每秒执行2000次 应该是这个问题
有修改地方 我这边看怎么测试下

**Comment by xia-chu** [comment]
zltoolkit打上补丁试试：
```patch
Index: src/Util/util.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Util/util.cpp b/src/Util/util.cpp
--- a/src/Util/util.cpp	(revision 28b7aea107089c17c6f10e8657d27a0815f85b25)
+++ b/src/Util/util.cpp	(date 1676432895841)
@@ -395,6 +395,7 @@
 }
 
 uint64_t getCurrentMillisecond(bool system_time) {
+    return getCurrentMicrosecondOrigin() / 1000;
     static bool flag = initMillisecondThread();
     if (system_time) {
         return s_currentMillisecond_system.load(memory_order_acquire);
@@ -403,6 +404,7 @@
 }
 
 uint64_t getCurrentMicrosecond(bool system_time) {
+    return getCurrentMicrosecondOrigin();
     static bool flag = initMillisecondThread();
     if (system_time) {
         return s_currentMicrosecond_system.load(memory_order_acquire);

```

**Comment by zhang-chuanfeng** [comment]
> ```diff
> return getCurrentMicrosecondOrigin();
> ```
测试了可以  基本不占用cpu

**Comment by xia-chu** [comment]
但是这样修改后 有负载的话 cpu占用会上升

**Comment by zhang-chuanfeng** [comment]
> 但是这样修改后 有负载的话 cpu占用会上升
这个接口一直调用获取时间戳进行的优化 , 设备接入量不多应该影响不大吧
