### ISSUE TITLE
obs推流，webrtc拉流播放错误，未在已有issue中找到解决方案，烦请大佬指导下

### ISSUE THREAD

**Issue by zccGH** [ZLMediaKit/ZLMediaKit#2863]
obs推流测试：rtmp://172.18.44.35:1935/live/livestream
webrtc拉流播放：https//106.14.10.193:9080/index/api/webrtc?app=live&stream=livestream&type=play
日志记录：
`# request:
GET /index/api/webrtc?app=live&stream=livestream&type=play
# header:
Accept : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding : gzip, deflate
Accept-Language : zh-CN,zh;q=0.9,en;q=0.8
Host : 106.14.10.193:9080
Upgrade-Insecure-Requests : 1
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
# content:

# response:
{
        "code" : -400,
        "msg" : "Assertion failed: (!offer.empty(), http body(webrtc offer sdp) is empty), function operator(), file /root/zlmtest/ZLMediaKit/server/WebApi.cpp, line 1677."
}
`

**Comment by xiongguangjie** [comment]
要使用特定播放器

**Comment by zccGH** [comment]
> 要使用特定播放器

你好，我用vlc播放的，不行吗，要用啥播放器啊

**Comment by xiongguangjie** [comment]
> > 要使用特定播放器
> 
> 你好，我用vlc播放的，不行吗，要用啥播放器啊

不是有自带的播放器吗，就在www/webrtc 下面的html页面

**Comment by zccGH** [comment]
> > > 要使用特定播放器
> > 
> > 
> > 你好，我用vlc播放的，不行吗，要用啥播放器啊
> 
> 不是有自带的播放器吗，就在www/webrtc 下面的html页面

感谢大佬指点，我发现问题原因在于：我使用的播放器播放发送的请求是get请求，而这个拉流接口是需要post方式触发。
