### ISSUE TITLE
[技术咨询] oepnRtpServer主动模式的疑问

### ISSUE THREAD

**Issue by Jkanon** [ZLMediaKit/ZLMediaKit#2865]
openRtpServer接口主动模式下（TCP_MODE为2）不需要传入对端的地址和端口吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个需要再调用下connectRtpServer http api才行。
这个模式不是很好用。

**Comment by Jkanon** [comment]
> 这个需要再调用下connectRtpServer http api才行。 这个模式不是很好用。

哦哦，在线文档中还没有列出来，感谢答疑！
