### ISSUE TITLE
数据传输协议是否考虑增加MP2T/RTP/TCP以及MP2T/RTP协议

### ISSUE THREAD

**Issue by stonma** [ZLMediaKit/ZLMediaKit#2866]
目前IPTV很多数据传输协议使用的mp2t，大神咱们这块有考虑吗？
![MP2T](https://github.com/ZLMediaKit/ZLMediaKit/assets/93910320/6411fbf7-9139-41a3-b526-f8c7b5eaa857)

**Comment by xiongguangjie** [comment]
现在ZLM是支持rtp ts 负载的，但是rtsp 的rtp ts 负载不支持，只支持rtp 流的ts负载

**Comment by stonma** [comment]
> iptv通常是ffmpeg组播拉流生成hls文件 然后部署个nginx即可

感谢大神回复，目前iptv已经开始采用rtsp直接对接终端模式，传统的hls转换延迟太大

**Comment by stonma** [comment]
> 现在ZLM是支持rtp ts 负载的，但是rtsp 的rtp ts 负载不支持，只支持rtp 流的ts负载

rtp ts负载验证通过，非常感谢，rtsp的rtp ts负载看无配置，另外源码本身没有对应传输协议，不知是否后期会对这块有支持计划

**Comment by xia-chu** [comment]
> 不知是否后期会对这块有支持计划

老实讲 对rtsp-ts的支持兴趣不大

**Comment by xia-chu** [comment]
> 传统的hls转换延迟太大

 iptv直播其实不追求延时

**Comment by stonma** [comment]
> > 不知是否后期会对这块有支持计划
> 
> 老实讲 对rtsp-ts的支持兴趣不大

多谢大佬回复，只能自己琢磨了，后期遇到难题，期望得到大佬指点

**Comment by xia-chu** [comment]
> 多谢大佬回复，只能自己琢磨了，后期遇到难题，期望得到大佬指点

可以
