### ISSUE TITLE
[技术咨询] 开启webRTC及datachannel后能否转发推流端消息给播放端？

### ISSUE THREAD

**Issue by tiancaipl5** [ZLMediaKit/ZLMediaKit#2867]
咨询的功能模块

webrtc模块datachannel功能

咨询的具体内容和问题

webrtc推流端通过datachannel向ZLM发送消息，ZLM是否会将该消息通过datachannel转发给webrtc播放端

注意事项

技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个不会，现在的datachannel 只会回显（你发什么，zlm就返回给你什么）没其他需求需要你们二次开发

**Comment by xia-chu** [comment]
现在有个broadMessage的接口 可以给webrtc播放器广播消息
