### ISSUE TITLE
[技术咨询] WEBRTC推流返回Unauthorized

### ISSUE THREAD

**Issue by linkewei0580** [ZLMediaKit/ZLMediaKit#2869]
**咨询的功能模块**
- WEBRTC 推流

**咨询的具体内容和问题**
WEBRTC推流返回Unauthorized，哪个参数还要配置？
[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=10000
snapRoot=./www/snap/
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/75007961/8526261a-8672-4e93-a8e6-90425149b481)

2023-09-28 13:37:41.400 W [MediaServer] [43627-event poller 1] WebHook.cpp:194 operator() | hook http://192.168.1.173:8080/index/hook/on_publish 5ms,failed[auth failed]: code:401 msg:"Unauthorized":{
        "app" : "live",
        "hook_index" : 111,
        "id" : "13-29",
        "ip" : "192.168.1.128",
        "mediaServerId" : "zlmediakit-local2",
        "originType" : 8,
        "originTypeStr" : "rtc_push",
        "params" : "app=live&stream=test&type=push&secret=10000&session=13-29",
        "port" : 53759,
        "schema" : "rtc",
        "stream" : "test",
        "vhost" : "__defaultVhost__"
}

2023-09-28 13:37:41.401 D [MediaServer] [43627-event poller 1] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/webrtc?app=live&stream=test&type=push&secret=10000
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Content-Length : 5363
Content-Type : text/plain;charset=UTF-8
Host : 192.168.1.123
Origin : https://192.168.1.123
Referer : https://192.168.1.123/webrtc/
sec-ch-ua : "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-origin
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
# content:
v=0
o=- 5102642920861499285 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:voC+
a=ice-pwd:18yS7Li/RjnYkKjVQdajYg4u
a=ice-options:trickle
a=fingerprint:sha-256 C8:7E:8A:5B:9B:59:50:0D:EA:09:28:63:27:24:B2:1C:33:5A:5D:F5:C1:23:9A:1B:66:C1:5A:70:6D:F2:35:2B
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- 2c10369d-8d59-468b-88d3-cdeb13c19176
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:1393747032 cname:Tc/JriRlJ7iZq0Gy
a=ssrc:1393747032 msid:- 2c10369d-8d59-468b-88d3-cdeb13c19176
m=video 9 UDP/TLS/RTP/SAVPF 96 97 102 103 104 105 106 107 108 109 127 125 39 40 45 46 98 99 100 101 112 113 116 117 118
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:voC+
a=ice-pwd:18yS7Li/RjnYkKjVQdajYg4u
a=ice-options:trickle
a=fingerprint:sha-256 C8:7E:8A:5B:9B:59:50:0D:EA:09:28:63:27:24:B2:1C:33:5A:5D:F5:C1:23:9A:1B:66:C1:5A:70:6D:F2:35:2B
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:- dfc06aec-7aae-400e-b032-fffcf06c1bb0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:103 rtx/90000
a=fmtp:103 apt=102
a=rtpmap:104 H264/90000
a=rtcp-fb:104 goog-remb
a=rtcp-fb:104 transport-cc
a=rtcp-fb:104 ccm fir
a=rtcp-fb:104 nack
a=rtcp-fb:104 nack pli
a=fmtp:104 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:105 rtx/90000
a=fmtp:105 apt=104
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:125 rtx/90000
a=fmtp:125 apt=127
a=rtpmap:39 H264/90000
a=rtcp-fb:39 goog-remb
a=rtcp-fb:39 transport-cc
a=rtcp-fb:39 ccm fir
a=rtcp-fb:39 nack
a=rtcp-fb:39 nack pli
a=fmtp:39 level-asymmetry-allowed=1;packetization-mode=0;profile-
# response:
{
        "code" : -400,
        "msg" : "[auth failed]: code:401 msg:\"Unauthorized\""
}

**Comment by linkewei0580** [comment]
# response:
{
        "code" : -400,
        "msg" : "[auth failed]: code:401 msg:\"Unauthorized\""
}
返回的代码和文档的描述不一致？
typedef enum {
    Exception = -400,//代码抛异常
    InvalidArgs = -300,//参数不合法
    SqlFailed = -200,//sql执行失败
    AuthFailed = -100,//鉴权失败
    OtherFailed = -1,//业务代码执行失败，
    Success = 0//执行成功
} ApiErr;

**Comment by xia-chu** [comment]
这是你的on_publish hook返回的错误

**Comment by linkewei0580** [comment]
> 这是你的on_publish hook(http://192.168.1.173:8080/index/hook/on_publish )返回的错误

感谢，wvp-GB28181-pro的日志也打印原因了，之前这个文档也看到了，内容太多，忘记了
https://doc.wvp-pro.cn/#/_content/ability/push
2023-09-28 16:20:27.689 [http-nio-8080-exec-7] INFO  c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener:193 - [ZLM HOOK]推流鉴权：zlmediakit-local2->OnPublishHookParam{id='55-29', app='live', stream='test', ip='192.168.1.128', params='app=live&stream=test&type=push&session=55-29', port=54174, schema='rtc', vhost='__defaultVhost__'}
2023-09-28 16:20:27.690 [http-nio-8080-exec-7] INFO  c.genersoft.iot.vmp.media.zlm.ZLMHttpHookListener:211 - 推流鉴权失败： 缺少必要参数：sign=md5(user表的pushKey)
