### ISSUE TITLE
c api打开rtsp 始终因为超时导致无法获取正确的音频参数

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#2871]
**咨询的功能模块**
- mediaSink 
**咨询的具体内容和问题**
- 我有一个rtsp流用ffplay和vlc打开都秒开 声音和画面都正常
- 但是使用c api 来打开 始终因为超时 获取不到音频参数 视频能正确获取
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/19390025/c8dae6cc-d58c-49eb-a4ca-b89117d2c5e8)
上图是我的测试截图
增加了unready_track 和 wait_track时长 还是判定超时 导致忽略了音频track c api那里无法获取正确的音频参数
但是从图上可以看出实际打开成功后就已经拿到正确的音频参数 

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by hh-kai** [comment]
后面我又测试用之前的test_player 打开 也是秒开
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/19390025/68de882a-740e-4daf-8907-dd97b2c29c9c)
又试了potplayer打开这个rtsp也是秒开

**Comment by hh-kai** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/19390025/71155d6f-eef5-419e-b267-d03b562d36f2)
kWaitTrackReady置为true还是会找不到音频

**Comment by xia-chu** [comment]
你要不提个抓包文件？

**Comment by hh-kai** [comment]
[rtsp192.168.0.177-v3.pcapng.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12836941/rtsp192.168.0.177-v3.pcapng.zip)
这个是test_player打开后抓包的
[rtsp192.168.0.177-vlc.pcapng.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12836947/rtsp192.168.0.177-vlc.pcapng.zip)
这个是vlc打开时的抓包 vlc基本是秒开 声音画面同时出来的

**Comment by xia-chu** [comment]
`rtsp192.168.0.177-v3.pcapng.zip`
这个不是zlm作为服务器吗？客户端是其他软件：`JRMediaServer-3.0-build-`

**Comment by hh-kai** [comment]
是zlm作为服务器
客户端也是zlm编译出来的test_player

**Comment by hh-kai** [comment]
zlm是我单独拉的一个仓库 改动了录像的部分内容 用的c api 创建的rtsp server  应该不会影响到其它的
客户端是源码编译的 没有改动
服务器是运行在linux下的 客户端是运行在windows的

**Comment by yushimeng** [comment]
看你的音视频时间戳差的有点多啊.

**Comment by hh-kai** [comment]
服务端音视频时间戳用的本地系统时间 然后zlmedia::Stamp 校准的

**Comment by hh-kai** [comment]
我打印了服务端的时间戳 48k的aac稳定在21左右 30帧的h264稳定在32左右

**Comment by xia-chu** [comment]
> [rtsp192.168.0.177-v3.pcapng.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12836941/rtsp192.168.0.177-v3.pcapng.zip)

这个rtsp的sdp这样的
```sdp
v=0
o=- 0 0 IN IP4 0.0.0.0
s=Streamed by ZLMediaKit(git hash:1dcd4bc/2023-08-17T11:13:41+08:00,branch:master,build time:2023-08-17T14:23:47)
c=IN IP4 0.0.0.0
t=0 0
a=range:npt=now-
a=control:*
m=video 0 RTP/AVP 96
a=fmtp:96 packetization-mode=1; profile-level-id=641028; sprop-parameter-sets=Z2QQKKwbGqB4AiflhAAAAwAEAAADAPI8IhGo,aO4xshs=
a=rtpmap:96 H264/90000
a=control:trackID=0
m=audio 0 RTP/AVP 98
a=fmtp:98 streamtype=5;profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3;config=1190
a=rtpmap:98 mpeg4-generic/48000/2
a=control:trackID=1

```

**Comment by xia-chu** [comment]
看起来没啥问题 这个需要提供rtsp url给我调试下才行

这个issue已经很早了 先关闭了 如果作者还能看到 可以继续在此issue答复
