### ISSUE TITLE
WebRTC in non-localhost environments

### ISSUE THREAD

**Issue by perara** [ZLMediaKit/ZLMediaKit#2872]
Dear @xia-chu 
**Preface:** First and foremost, thanks for all of the amazing work you are doing with ZLMediakit. I really appreciate your hard work, and seen clearly from the stars and forks attained, a lot are interested in your work!

**Problem:** I've successfully set up WebRTC on my local machine, and have further packaged this into a docker container. When running the docker container using the host network, WebRTC works fine, but I'm having issues making it run when using **bridged mode** in docker. While i'm not fully certain of what the problem are, I recognize that the SDP is set to "localhost", but this would clearly not work, unless your attempting to access the stream locally.

I've looked in the WIKI on how to make WebRTC function from external networks, but I've not come accords any documentation on how to do this.  I've also opened the ports that I've set up for listening for the WebRTC.

Would you happen to know how I can adjust so that WebRTC works outside of localhost?
Best,

**Comment by xiongguangjie** [comment]
docker bridged mode, should mapping port (docker port and docker host port must same) and config rtc external ip
