### ISSUE TITLE
[技术咨询] rtp timeout媒体反复注册

### ISSUE THREAD

**Issue by panxy161x** [ZLMediaKit/ZLMediaKit#2876]
addStreamProxy之后流列表可以获取到对应信息，但是切片文件不生成，看日志一直超时导致反复注册
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/60061702/37396b8e-5b96-4d42-b30a-89589e8c637a)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
你的rtsp url不稳定 请查看带宽是否足够

**Comment by panxy161x** [comment]
> 你的rtsp url不稳定 请查看带宽是否足够

好的，感谢大佬
