### ISSUE TITLE
[技术咨询] 相对时间戳方式进行RTSP代理拉流的录像音视频不同步问题咨询

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2877]
**咨询的功能模块**
使用流程：ZLM使用addstreamproxy进行拉流，然后开启录像，在录像不断开的情况下，时间越长，录像音视频不同步教严重；ffplay播放器从ZLM拉流（directproxy=0/1 ）ffplay播放正常；

目前使用的时间戳模式是：2，相对时间戳stamp；关闭直接代理；发现相对时间戳进行录像会有下列问题；

1 在录像过程中打印RTSP的  RTP时间戳和NTP时间戳，是一样的，所以看样子是没有什么修正过程
RtspDemuxer.cpp:59 inputRtp | H265rtp:1696694041364 ntp1696694041364
RtspDemuxer.cpp:66 inputRtp | Audiortp:1696694041401 ntp1696694041401

2 录像时候发现随着时间的延长，每次录像的时候计算的 _relative_stamp:会越来越大；但是绝对时间戳的差值并没有明显的差距这么大
如图：1,2,3
        音视频的时间戳差值可能不是最准确的（但是起始的音视频绝对时间戳差值也没有很大，也就几十毫秒的样子）

![1](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/eefb7373-b70b-4952-b726-f9dff1bd6957)
![2](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/2f0eda18-9b37-4c91-9487-9ed3b787c402)

![3](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/22d40247-244f-4f07-b438-70c823c6de2f)

3 我的问题：
   3.1为什么绝对时间戳差值很小，相对时间戳累计的差值会这么大，相对时间戳也是绝对时间戳的自己的增量计算的呀；

   3.2 因为现在的代码逻辑吧这个相对时间戳差值加到音频上了，就导致原本交织的很好的音视频，音频被无端加了很大的偏移值，MP4打包就会出现音频被推后；这种文件不管谁向谁同步，播放都是不同步的； 如图4；可以看到打包之后音频被推后很多；（音频的相对时间戳已经比视频的大了，为什么这个差值还要加在音频上？--又仔细看了下，加载音频上没有问题；但是现在的情况是，音视频绝对时间戳差值小，且内容基本同步，但是相对时间戳差值变大导致添加_relative_stamp之后，把音频推到更后边去了，录像不同步了）

3.3 多台摄像机都有这个问题；肯定存在抖动或者回跳之类的，但是相对时间戳这个越来越大的差值就真的匪夷所思？

4我现在在用绝对时间戳测试，后需进一步反馈测试结果

![4](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/199fd88b-d1ee-4041-8b49-c6b20bccbe00)
图5是我自己加的打印；
![5](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/e93207d0-0154-4c5f-b74b-a45ab0693a4b)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xuandu** [comment]
用绝对时间戳录制了一天，录像好多了，没有音视频不同步了；
所以，如果我开启ZLM的配置文件的stamp=2不动，然后代码中如果某一路流是复合流（tracks>=2）,我就直接使用绝对时间戳可以吗；就相当于这个ZLM里有部分流使用的是相对时间戳，复合流都是使用的绝对时间戳；不知道ZLM是否支持？
见图：
![5](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/cb12a738-92bd-48cd-9789-872b38c3ffca)

**Comment by xuandu** [comment]
这个问题系正负时间戳回退导致
严格说这里需要优化下：
![yy](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/d98795f6-3540-4e69-94c8-9902389d2efd)
![差值2](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/6bb0ac92-2821-4b71-b96f-707d3c4bb849)
您看这个运行时截图，负增长的时候 +1；正增长小于3000就都加给delta，但是实际上正负增长的总值才是80；这一下就报相对时间戳的差值多了一个900.这个900 将来会加在录像的时间戳上的

**Comment by xia-chu** [comment]
zlm最大允许时间戳跳跃或回退3000ms 如果超过这个范围 就会强制时间戳+1。
所以你这个流的时间戳应该是发生了不规则的时间戳跳跃会回退导致的。

**Comment by xuandu** [comment]
是的，是发生了回退；但是这里的处理有问题，比如，先回退720，在正向跳800；理论上相对时间戳应该加80；但是实际上 回退720毫秒的时候相对时间戳+1（不影响啥），但是正向跳800的时候由于小于3000，是真的给相对时间戳加了800的；实际应该只加80；这种情况出现的次数越多，这个相对时间戳就会不准确；影响录像文件；

**Comment by xia-chu** [comment]
你这个流是rtsp的，rtp中的时间戳保存的是pts时间戳 如果有B帧 有存在回退的可能，不过就算这样回退或者跳跃应该也不会超过3秒。
rtp的时间戳和ntp时间戳有个映射关系，这个关系通过rtcp sender report汇报建立，zlm会根据两种恢复为ntp(pts)时间戳，然后
zlm会根据pts排序生成dts时间戳。

**Comment by xia-chu** [comment]
> 但是实际上 回退720毫秒的时候相对时间戳+1（不影响啥）
没有啊 回退小于3000ms 也不会强制+1的 看代码：

![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/3625fda1-924f-4a73-a521-9486d78a1f47)

**Comment by xuandu** [comment]
> > 但是实际上 回退720毫秒的时候相对时间戳+1（不影响啥）
> 
> 没有啊 回退小于3000ms 也不会强制+1的 看代码：
> 
> ![图片](https://user-images.githubusercontent.com/11495632/273810238-3625fda1-924f-4a73-a521-9486d78a1f47.png)

但实际上回退的maxcts是500毫秒，正向跳跃的界限是3秒，所以－720就是会走+1，而要+800就是会走+800

**Comment by xia-chu** [comment]
哦 看错了 确实是 要不你把MAX_CTS改成MAX_DELTA_STAMP然后来个pr？

**Comment by xia-chu** [comment]
当时用MAX_CTS的目的是 dts和pts最大允许相差500毫秒 当时认为这个回退是这个导致的

**Comment by xuandu** [comment]
我这个改完之后，测试了一天多发现还是治标不治本：问题如下：
1会出现 音频，视频大的正向（or反向）跳变，30几秒；
2会出现音频或者视频的DTS的回退（超过30秒）；
首先，稳定情况下， 相对（a_stamp-v_stamp）-绝对（a_stamp-v-stamp）这个差值应该是固定的；下述会把这个差值记作deltaX;
但是一旦出现小幅度的时间戳抖动，或者非常大的时间戳抖动，这个差值就会改变；
当出现特别大的时间戳跳变的时候，如音视频同时反跳或者正跳（PTS=DTS），跳跃之后的，音视频绝对时间戳的差值一般就会变小，但是音视频相对时间冲的差值减音视频绝对时间戳的差值就会改变，如图（运行途中截得，其实这个deltaX 会在每次有抖动跳变的时候进行变化，跳变次数多了，这个相对音视频的差值就会越来越大）：

![skipav](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/90b917ba-f84e-4d40-bad0-0f8f2d5e9a7c)

这里一定程度上确实存在音视频交织不均匀；但是摄像机我们并不能改变它；

所以我在想这里是否能优化一下（因为对代码理解还不深入，所以只是个人想法，不知道会不会影响整体逻辑）：
bool MultiMediaSourceMuxer::onTrackFrame(const Frame::Ptr &frame_in) 的
 if (_option.modify_stamp != ProtocolOption::kModifyStampOff) {
        // 时间戳不采用原始的绝对时间戳
        frame = std::make_shared<FrameStamp>(frame, _stamp[frame->getTrackType()], _option.modify_stamp);
       // 如果相对（a_stamp-v_stamp）超过多少毫秒，检测下绝对时间戳的差值，如果绝对音视频时间戳差值，小于相对音视频时间戳差值的时候，对相对音视频差值给与一定的纠正；
    }

如果音视频的绝对时间戳差值小于一定值（如5秒），您认为音视频是同步的；在此基础上，音视频相对时间戳的差值 大于音视频绝对时间戳的差值。在一定范围内对相对时间戳给与纠正，
就比如我的图上；您看这个两天后的记录deltaX已经变成9000多了
![2天后](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/513ec9ba-1cc0-41bf-8645-4a75301d7b40)

**Comment by xia-chu** [comment]
其实偶尔跳变下是无关紧要的 假设一个音频或视频帧的delta时间戳(增量时间戳)是40毫秒，zlm发现它的绝对时间戳变了 会把增量时间戳强制赋值为1，这种情况下 根本就不会导致音视频失去同步，因为音视频不同步最少要几百毫秒 我们才能察觉出来。

你这个设备不仅时间戳跳跃了 连数据帧也是跳跃的 也就是说 跳跃前音视频间的时间戳差值 和跳跃后的差值都对不上 才会出现这个问题。

**Comment by xia-chu** [comment]
这个问题基本无解的  因为mp4录制本来就用的delta时间戳 这种容器格式保存的就是每一帧数据的增量时间戳，没办法直接使用绝对时间戳 否则就无法满足时间戳单调递增的要求

**Comment by xuandu** [comment]
实际上确实是有很严重的反跳，但是画面是正着走的，只是时间戳反跳很大；
我这个设备，还不是偶尔出现一下，一小时就会出现6,7次，有大的跳变，有小的；宇视的；海康那个最终的录像状态和宇视的一样，我还没有看他的情况；
如果只是某一台设备，其实我完全可以不管他；但是事实上往往设备就那么几台；测试规模有限；

**Comment by xia-chu** [comment]
> 实际上确实是有很严重的反跳，但是画面是正着走的，只是时间戳反跳很大； 我这个设备，还不是偶尔出现一下，一小时就会出现6,7次，有大的跳变，有小的；宇视的；海康那个最终的录像状态和宇视的一样，我还没有看他的情况； 如果只是某一台设备，其实我完全可以不管他；但是事实上往往设备就那么几台；测试规模有限；

那你看看这里面修改MP4Muxer对象吧 在MP4Muxer.cpp

**Comment by xuandu** [comment]
我想着在MPrecord里传入相对时间戳，绝对时间戳，然后比较时间戳差值变化来决定每个录像文件是否给音频添加reletive_stamp;但是我们应用层说某些限制，需要使用相对时间戳，这个相对时间戳
if (_option.modify_stamp != ProtocolOption::kModifyStampOff) {
// 时间戳不采用原始的绝对时间戳
frame = std::make_shared(frame, _stamp[frame->getTrackType()], _option.modify_stamp);}  其实也已经受反跳次数的影响，差值越来越大了；那拉这个ZLM里的这路实时流，音视频的时间戳差值也是很大；不同的不播放就会出现要么卡住；要么播放异常；

本来我想着让他们用绝对时间戳，告诉我绝对时间戳不同步的话播放器也不能播；-----心累

**Comment by xia-chu** [comment]
> 本来我想着让他们用绝对时间戳，告诉我绝对时间戳不同步的话播放器也不能播；-----心累

跳变了 应该绝对时间戳还是同步的 否则摄像头的bug大了

**Comment by xuandu** [comment]
> > 本来我想着让他们用绝对时间戳，告诉我绝对时间戳不同步的话播放器也不能播；-----心累
> 
> 跳变了 应该绝对时间戳还是同步的 否则摄像头的bug大了

是的，他出现完跳变之后，绝对时间戳还是同步的；所以我想让应用层使用绝对时间戳；然后录像的时候我再想办法；可是他们说不能用绝对的；因为一旦音视频起始绝对时间戳相差很大，各计算各的，播放器就播放不了声音了；---所以我感觉僵住了

**Comment by xia-chu** [comment]
> 因为一旦音视频起始绝对时间戳相差很大，各计算各的，播放器就播放不了声音了

不会的 mp4容器保存的是delta时间戳 不会保存绝对时间戳的

**Comment by xuandu** [comment]
> > 因为一旦音视频起始绝对时间戳相差很大，各计算各的，播放器就播放不了声音了
> 
> 不会的 mp4容器保存的是delta时间戳 不会保存绝对时间戳的
但是转协议的时候如果使用绝对时间戳，这个时间戳应该是透传出去的，我们的播放器不一定能支持音视频时间戳差值很大的情况。(音视频非同一个时间起点)。尽管我觉得这应该是播放器的标配

**Comment by SU79840** [comment]
我这边是rtmp推流直播， 音视频时间戳同时跳变10s（因为推流段10s没有发送数据） 输入的时间戳是正常， 输出的音视频时间戳出现了很大的跳变， 导致音画严重不同步，ios无法播放
（括号内为 FrameStamp 类处理前的时间戳， 括号外为处理后的时间戳，为了避免日志过多，1s打印一次时间戳日志，配置 stamp=2）

<img width="1381" alt="企业微信截图_31058e1b-95a7-4881-8b32-ff74c2024379" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/22128895/8052ff57-70dd-4a07-a166-9af28c67a4d0">

**Comment by xuandu** [comment]
> 我这边是rtmp推流直播， 音视频时间戳同时跳变10s（因为推流段10s没有发送数据） 输入的时间戳是同步的， 输出的音视频时间戳就出现了很大的差值 （括号内为 FrameStamp 类处理前的时间戳， 括号外为处理后的时间戳，为了避免日志过多，1s打印一次时间戳日志，配置 stamp=2）
> <img alt="企业微信截图_31058e1b-95a7-4881-8b32-ff74c2024379" width="1381" src="https://user-images.githubusercontent.com/22128895/276800673-8052ff57-70dd-4a07-a166-9af28c67a4d0.png">

你如果只是偶尔一次 大于3秒的时间戳跳变，相对时间戳不会出来之后不会差很大的，绝对转相对的时候大于3秒是直接给相对时间戳+1处理的；不太懂为啥你这个也会差值这么大；我上边的情况是频繁的跳变引起的

**Comment by xia-chu** [comment]
> > 我这边是rtmp推流直播， 音视频时间戳同时跳变10s（因为推流段10s没有发送数据） 输入的时间戳是同步的， 输出的音视频时间戳就出现了很大的差值 （括号内为 FrameStamp 类处理前的时间戳， 括号外为处理后的时间戳，为了避免日志过多，1s打印一次时间戳日志，配置 stamp=2）
> > <img alt="企业微信截图_31058e1b-95a7-4881-8b32-ff74c2024379" width="1381" src="https://user-images.githubusercontent.com/22128895/276800673-8052ff57-70dd-4a07-a166-9af28c67a4d0.png">
> 
> 你如果只是偶尔一次 大于3秒的时间戳跳变，相对时间戳出来之后不会差很大的，绝对转相对的时候大于3秒是直接给相对时间戳+1处理的；不太懂为啥你这个也会差值这么大；我上边的情况是频繁的跳变引起的

如果音频和视频只是一方跳变 另外一方不跳变 或者跳变的幅度不一致 都会导致失去同步

**Comment by xia-chu** [comment]
反正跳变还想保持同步 我觉得挺扯淡的
既然要跳变 那用绝对时间戳算了
