### ISSUE TITLE
[技术咨询]  自动结束播放mediakit::WebRtcSession on err: 255(message too long)

### ISSUE THREAD

**Issue by xixi-2023** [ZLMediaKit/ZLMediaKit#2878]
摄像头视频播放几分钟后就自动结束播放，日志报mediakit::WebRtcSession on err: 255(message too long)异常
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/89331620/3c22c4ac-f9dd-4aea-a18f-911b7407f700)

**Comment by xia-chu** [comment]
这个先把配置文件directProxy设置为0试试

**Comment by xia-chu** [comment]
这个可能是rtp over tcp模式下 rtp长度太大 超过mtu了 然后再udp方式代理 无法通过udp发送这么大的包
