### ISSUE TITLE
[技术咨询] 在调用zlmediakit的/index/api/getSnap接口进行截图时，总是返回官方原始的图片

### ISSUE THREAD

**Issue by wangguodong8602** [ZLMediaKit/ZLMediaKit#2879]
**咨询的功能模块**
- 截图功能

**咨询的具体内容和问题**
- 在调用zlmediakit的/index/api/getSnap接口进行截图时，总是返回官方原始的图片

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by wangguodong8602** [comment]
2023-10-09 10:59:14.792 D [MediaServer] [22480-work poller 0] WebApi.cpp:250 http api debug | 
# request:
GET /index/api/getSnap?secret=Jr5i9NaOivO5RhRWBDeMQdNnOmkl8KlC&expire_sec=1&url=rtsp%3A%2F%2F127.0.0.1%3A554%2Frtp%2F34020000001180000001_34020000001310000001&timeout_sec=15
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Host : 127.0.0.1
User-Agent : okhttp/4.10.0
# content:

# response size:47255

**Comment by QuSongtao** [comment]
我也遇到一样的问题,请问楼主解决没有

**Comment by QuSongtao** [comment]
我好像解决了，你检查一下拼写看看。我用的POSTMAN测的
第一步  在流列表中看看已注册的流信息
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15939134/7cff553b-feca-4a0a-97a3-f354b8b79932)
第二步  调用拍照接口，好像只能用RTSP方式，RTMP貌似不行
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15939134/cb262bc4-b8a7-498a-9c85-f58a01a30c91)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/15939134/164df54c-9746-4d96-af37-a89acadb887f)

**Comment by sun-shu** [comment]
我也遇到了这个问题，我是这么解决的：

1. 修改配置文件截图FFmpeg模板 加上-rtsp_transport tcp
2. 核对配置文件里的FFmpeg 路径 MAC可以用命令 `where FFmpeg`来查找位置
3. 只能使用已经被推送的流 我使用addStreamProxy返回结果的路径就可以，其他的没经过推送的流就不行

**Comment by SMJ-YY** [comment]
你看一下是不是ffmpeg的安装地址给错了,我前天也是这样,后来查看ffmpeg日志发现是ffmoeg地址错了

**Comment by yangtongh** [comment]
同样的问题，有友友解决了吗，头疼
