### ISSUE TITLE
[功能请求] FFmpeg支持按需启动，空闲自动关闭

### ISSUE THREAD

**Issue by hu-xd** [ZLMediaKit/ZLMediaKit#2880]
**描述该功能的用处，可以提供相关资料描述该功能**

希望FFMpegSource也能像StreamProxy一样，实现有人请求时按需启动，无人查看时自动关闭（延时）

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
这个也是支持的啊 你要对接无人观看hook 或者配置文件auto_close设置为1啊

**Comment by hu-xd** [comment]
按需启动必须外部监听hook来实现吗？直接内置这个功能有吗？
无论从运行效率还是实现复杂性来说，内置一个都更好。
从用户体验来说，本来用户都开始播放了，再来推流，还要转码，都会导致延迟增加，中间再来几轮http调用来回，就更加大了。

**Comment by xia-chu** [comment]
按需addFFmpegSource拉流无法在zlm中内置实现 因为zlm不支持拉流地址是多少 所以需要你自己对接业务。
无人观看主动停止拉流已经实现了 配置文件auto_close设置为1就行

**Comment by hu-xd** [comment]
调用addFFmpegSource的时候已经把所有地址都配置进去了啊，怎么会不知道呢？

**Comment by xia-chu** [comment]
auto_close时会自动触发delFFmpegSource，所以你说的不成立。

**Comment by xia-chu** [comment]
相信我 你对接下hook 工作量比我在c++实现简单稳定可靠。

**Comment by hu-xd** [comment]
> auto_close时会自动触发delFFmpegSource，所以你说的不成立。

之所以提issue就是请求修改现有逻辑啊，现有的逻辑机制不适应，就需要改改呗。
现在add直接启动，close直接删除，就是因为没有一个：”存在但没有启动“ 的状态表达。
例如改为：onDemand=true的时候，add了但不运行，无人观看时停止了但不del。



> 相信我 你对接下hook 工作量比我在c++实现简单稳定可靠。 你要业务开发必定要对接hook和http api，增加一个hook监听以及调用一个http api本来就没多少事情

1，目前除了这事儿并没有什么其他的”业务“需要hook的。
2，对于开发也许事情不多，但是对于运行效率，视频启动延迟来说，会让按需+转码模式本不富裕的启动时间雪上加霜。
3，我们其实还与别的系统（WVP）共享ZLM，而hook是指向它的，由于ZLM并不支持多个hook #2882，会带来部署上更大的复杂度和更糟的启动延时。

**Comment by xia-chu** [comment]
> 现有的逻辑机制不适应，就需要改改呗。

- 1、这只是你的需求 从收到的反馈看 你的需求可能连1%的用户都不需要 况且这个需求本来就只需要通过一个stream_not_found的hook实现 并不是不能实现。

- 2、而且在流未找到时 你说zlm是默认去addFFmepgSource拉流呢还是addStreamProxy拉流还是触发客户端主动推流？你这样的功能需求本来就是不清晰的 容易歧义的 不符合统一的顶层的设计。那下次人家提需求要我stream_not_found时触发addStreamProxy我要不要去实现呢？

-  3、你说delFFmepgSource时不删除addFFmepgSource时的信息 那什么时候删除呢，内存什么时候释放呢？

- 4、你又说你的业务不需要对接hook，那你怎么实现推流和播放的鉴权？人家随便进出你的服务器吗？还有其他很多功能必须对接hook，默认关闭hook只是为了方便小白用户测试，你不对接hook直接商用合适吗？对接hook是必选项，不是可选项。

- 5、你对接hook再调用addFFmepgSource并不会慢多少，两次局域网http请求最多100毫秒，按需拉流本来就有启动延时，不管哪种方式都需要等待时间，增加不到100毫秒延时相对秒级延时来说不算什么。

- 6、不知道多hook是合理的设计，因为zlm的hook基本都是需要对方回复确认的，而不是哪种单方面通知的。你要支持多hook自己代理下即可，而且hook本来是业务的 从数据库加载hook地址或者其他前置处理都是常见的 通过zlm实现多hook是糟糕的设计。

- 6、

**Comment by xia-chu** [comment]
你的业务需求是你自己的工作 你不要寄托在开源项目开发者身上。
用户千人千面，不可能为了一点特殊需求就改变统一的顶层设计，
否则只会出现一个行为不一致充满bug的系统。

**Comment by hu-xd** [comment]
> > 现有的逻辑机制不适应，就需要改改呗。
> 
>     * 1、这只是你的需求 从收到的反馈看 你的需求可能连1%的用户都不需要 况且这个需求本来就只需要通过一个stream_not_found的hook实现 并不是不能实现。

视频流的按需推拉，实在不是什么特定于业务的东西，逻辑完全在流媒体服务器的范围内吧。

> 
>     * 2、而且在流未找到时 你说zlm是默认去addFFmepgSource拉流呢还是addStreamProxy拉流还是触发客户端主动推流？你这样的功能需求本来就是不清晰的 容易歧义的 不符合统一的顶层的设计。那下次人家提需求要我stream_not_found时触发addStreamProxy我要不要去实现呢？

一个流地址如果有注册了一个onDemand模式的FFmpegSource就启动FFmpegSource，如果有注册了一个onDemand模式的StreamProxy就启动StreamProxy，都没有再试试hook。

> 
>     * 3、你说delFFmepgSource时不删除addFFmepgSource时的信息 那什么时候删除呢，内存什么时候释放呢？
> 

确实不应该释放，应该永远存在。

>     * 4、你又说你的业务不需要对接hook，那你怎么实现推流和播放的鉴权？人家随便进出你的服务器吗？还有其他很多功能必须对接hook，默认关闭hook只是为了方便小白用户测试，你不对接hook直接商用合适吗？对接hook是必选项，不是可选项。
> 
>     * 5、你对接hook再调用addFFmepgSource并不会慢多少，两次局域网http请求最多100毫秒，按需拉流本来就有启动延时，不管哪种方式都需要等待时间，增加不到100毫秒延时相对秒级延时来说不算什么。
> 
>     * 6、不支持多hook是合理的设计，因为zlm的hook基本都是需要对方回复确认的，而不是那种单方面通知的。你要支持多hook自己代理下即可，而且hook本来是业务的 从数据库加载hook地址或者其他前置处理都是常见的 通过zlm实现多hook是糟糕的设计。

hook可以按照app区分，请求不同app下面的流地址，调用不同app的hook，没有特定app的hook再调用全局默认hook。

**Comment by hu-xd** [comment]
隔壁MediaMtx作为一个远比ZLM简单弱小（以至于我并不准备使用）的流媒体服务，它就在内部实现了按需拉流推流，也没见什么逻辑混乱，挺顺理成章的。这怎么看也不是什么外部“业务”，不就是流媒体服务的本门当行的“业务”嘛。

按需推流，自动延时停止
https://github.com/bluenviron/mediamtx#on-demand-publishing
按需拉流，自动延时停止
https://github.com/bluenviron/mediamtx/blob/b220c8c02000f6074c57c4ea68f686d8498245a9/mediamtx.yml#L281

**Comment by xia-chu** [comment]
你提到的MediaMtx的这个功能只是个测试用功能 根本就不支持根据流id切换输入源的功能 这个本来就是给你测试用的 又不能作为商用功能。
实际上zlm也提供了这种功能 你把zlm的stream_not_found hook设置为http://127.0.0.1/index/hook/on_stream_not_found_ffmpeg 也能主动ffmpeg拉流：

<img width="881" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/67793867-47f3-4d85-a277-d7f09fc32f12">

**Comment by xia-chu** [comment]
你自己的业务需求你自己开发吧 zlmediakit标准功能只会提供一个明确的、统一的、没有歧义的功能。

**Comment by xia-chu** [comment]
按需推流或者拉流 都必须对接on_stream_not_found hook，没有第二种选择，对所有协议所有方式一视同仁，这样开发者才不会困惑。

**Comment by hu-xd** [comment]
拉流推流的管理明明就是流媒体服务的核心业务，不想做没关系，非说这是其他层的什么“业务需求”就挺奇怪的，呵呵。

**Comment by xia-chu** [comment]
> 拉流推流的管理明明就是流媒体服务的核心业务，不想做没关系，非说这是其他层的什么“业务需求”就挺奇怪的，呵呵。

对对对 你说的对
