### ISSUE TITLE
[功能请求] StreamProxy支持视频编码转换

### ISSUE THREAD

**Issue by hu-xd** [ZLMediaKit/ZLMediaKit#2881]
**描述该功能的用处，可以提供相关资料描述该功能**

希望StreamProxy能够支持视频编码转换，例如把H.265转为H.264

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
addStreamProxy只支持协议代理 不支持转码
要转码只能通过addFFmepgSource接口实现。

**Comment by 286897655** [comment]
> addStreamProxy只支持协议代理 不支持转码 要转码只能通过addFFmepgSource接口实现。

他这里意思是 streamproxy中，比如拉rtsp流，在传输过程中，H264变成H265了。playerproxy没法重置track，我也遇到这个问题，怎么解决呢？
