### ISSUE TITLE
[功能请求] WebHook支持注册多个监听服务

### ISSUE THREAD

**Issue by hu-xd** [ZLMediaKit/ZLMediaKit#2882]
**描述该功能的用处，可以提供相关资料描述该功能**

希望WebHook可以注册多个监听服务，例如可以按照app来区分管理，每个app可以选择只要收到自己的流的相关事件

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**

**Comment by xia-chu** [comment]
这个希望你们自己通过http代理实现 zlm不想去做这种非常业务的功能
