### ISSUE TITLE
[BUG] 提示address  already in use,急救

### ISSUE THREAD

**Issue by 847365031** [ZLMediaKit/ZLMediaKit#2883]
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/35096712/0edbc082-5485-426b-824a-42b6bc2f0b8c)
如图所示 并不是一直会报这个错误 运行一段时间后会复现
 为什么请求api的时候会报这个错误呢 我已经通过最新分支编译成Docker镜像了 但是还是会出现如上错误

**Comment by xia-chu** [comment]
这个问题衡诡异啊 分析代码 zlm在创建tcp客户端时 绑定的网卡是 INADDR_ANY 端口是0 这种情况下怎么会绑定失败呢？

![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/7e80f503-55d0-4396-90d2-e4de9d57868d)

**Comment by 847365031** [comment]
w

> 这个问题衡诡异啊 分析代码 zlm在创建tcp客户端时 绑定的网卡是 INADDR_ANY 端口是0 这种情况下怎么会绑定失败呢？
> 
> ![图片](https://user-images.githubusercontent.com/11495632/273812975-7e80f503-55d0-4396-90d2-e4de9d57868d.png)

问题已经排查出来了 是因为另一个程序的问题 把系统端口占用完了导致的 ,谢谢

**Comment by xia-chu** [comment]
牛逼啊 你另外一个程序把几万个端口都占用完毕了？
