### ISSUE TITLE
[功能请求] ts切片文件目录，删除规则优化

### ISSUE THREAD

**Issue by chaoweiyi** [ZLMediaKit/ZLMediaKit#2886]
**描述该功能的用处，可以提供相关资料描述该功能**
1. ZLMediaKit，添加 rtsp/rtmp/hls 拉流代理；
2. 自定义http代理，提供hls.m3u8文件访问；
3. 根据观察，目录创建是按“yyyy-MM-dd/HH”规则创建，在每小时切换时，导致上1小时的文件访问404，播放中断；

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
目录删除时优化，最好与配置文件中的`hls.segRetain`保持一致，比如计算当前目录与上一个目录中的文件数，是否满足删除要求再执行删除操作，谢谢！

**Comment by xia-chu** [comment]
不对吧 只会删除hls的ts/fmp4切片文件的 它所在的文件夹不会删除的 也就是这个流注销前 会有很多空文件夹的
只有流注销了 才会从根目录删除所有文件夹和文件 流在线的情况下 不会删除文件夹的
