### ISSUE TITLE
[技术咨询] 对接nvr进行历史视频下载，但是下载到的都是12秒的视频切片，这个有办法直接下载到一个大文件吗？例如30秒

### ISSUE THREAD

**Issue by wangguodong8602** [ZLMediaKit/ZLMediaKit#2887]
**咨询的功能模块**
- 录像下载

**咨询的具体内容和问题**
- 录像下载到的都是12秒的视频切片，这个有办法延长时间吗？

**Comment by xia-chu** [comment]
这个不是zlm本身限制的 zlm只作为流媒体转发 这个视频下载对zlm来说就是直播 你可以在wvp的项目提issue
