### ISSUE TITLE
[BUG] HLS拉流，解析错误，ZL奔溃

### ISSUE THREAD

**Issue by chaoweiyi** [ZLMediaKit/ZLMediaKit#2888]
### 现象描述

1. 对接三方视图平台时，对方提供hls流，通过zl拉流，发生异常；
2. postman，addStreamProxy提交信息后，无返回结果，且连接不中断；
3. zl输出警告日志；
4. postman，getMediaList，获取不到数据，但控制台一直输出警告日志；
5. 可能原因，对方返回的m3u8内容，并不是ts文件，而是mp4文件；

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

![e1550717daf2d4d5357274ef9a9b63ef](https://github.com/ZLMediaKit/ZLMediaKit/assets/3336527/f1f052df-87ec-4ad7-b571-7e412ec195f8)

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
目前zlm还不支持hls-fmp4的拉流代理。
