### ISSUE TITLE
[BUG] msys2的mingw64环境编译 提示编译错误'nullptr_t' has not been declared

### ISSUE THREAD

**Issue by chenbingbcb** [ZLMediaKit/ZLMediaKit#2890]
拉ZLMediaKit最新的48f6281版本 win11下使用msys2的mingw64环境编译 提示编译错误3rdpart/ZLToolKitc/Util/util.h:408:20: error: 'nullptr_t' has not been declared 我猜测是c++23版本的相关更新引起 毕竟ZLMediaKit基于c++11 于是将ZLMediaKit版本更新到c35b5e9(submodule也相应更新)就编译ok了 该版本没引用nullptr_t
是不是ZLMediaKit最近要支持c++23?

**Comment by xia-chu** [comment]
这个加个头文件 #include <cstddef> 即可
在util.h中忘了加这个

**Comment by chenbingbcb** [comment]
> 这个加个头文件 #include 即可 在util.h中忘了加这个

试过在util.h加#include <cstddef>或#include <stddef.h>了 都还是一样错误 可能是各种宏没有符合条件就没开启

**Comment by xia-chu** [comment]
https://en.cppreference.com/w/cpp/types/nullptr_t

这是c++11的特性啊

**Comment by xia-chu** [comment]
不行就这样: using nullptr_t = decltype(nullptr);

**Comment by chenbingbcb** [comment]
https://en.cppreference.com/w/c/types/nullptr_t 我最开始是这个网址查看的 而且vscode查看定义跳转的是cstddef->stddef.h 之前试过复制stddef.h里的下面这段 出现别的编译错误
    namespace std
    {
        typedef decltype(__nullptr) nullptr_t;
    }

    using ::std::nullptr_t;
然后刚试了你发的这个using nullptr_t = decltype(nullptr); 也是出现别的编译错误
罢了 反正我就提个bug github正式修复我也不能本地改了随便提交

**Comment by chenbingbcb** [comment]
确切说 nullptr_t是c23才开始支持 不是c++23 抱歉报的时候写错 难道msys2的mingw64环境编译是用gcc而不是g++?
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16027616/269ccbde-0a8f-4aed-a698-9a70d95ff78a)

**Comment by xia-chu** [comment]
你打个补丁试试
```patch
Index: src/Util/util.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Util/util.h b/src/Util/util.h
--- a/src/Util/util.h	(revision a883b5ec1a65aa5d831079ee31f7f1d52e24fa01)
+++ b/src/Util/util.h	(date 1696928990593)
@@ -343,6 +343,7 @@
 class Any {
 public:
     using Ptr = std::shared_ptr<Any>;
+    using nullptr_type = decltype(nullptr);
 
     Any() = default;
     ~Any() = default;
@@ -405,7 +406,7 @@
         _data = nullptr;
     }
 
-    Any &operator=(nullptr_t) {
+    Any &operator=(nullptr_type) {
         reset();
         return *this;
     }

```

**Comment by chenbingbcb** [comment]
> 你打个补丁试试
> 
> ```diff
> Index: src/Util/util.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/src/Util/util.h b/src/Util/util.h
> --- a/src/Util/util.h	(revision a883b5ec1a65aa5d831079ee31f7f1d52e24fa01)
> +++ b/src/Util/util.h	(date 1696928990593)
> @@ -343,6 +343,7 @@
>  class Any {
>  public:
>      using Ptr = std::shared_ptr<Any>;
> +    using nullptr_type = decltype(nullptr);
>  
>      Any() = default;
>      ~Any() = default;
> @@ -405,7 +406,7 @@
>          _data = nullptr;
>      }
>  
> -    Any &operator=(nullptr_t) {
> +    Any &operator=(nullptr_type) {
>          reset();
>          return *this;
>      }
> ```

试了一样有别的编译错误
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16027616/1d769244-9907-451e-b57c-50ddabb64bbb)

**Comment by chenbingbcb** [comment]
> 确切说 nullptr_t是c23才开始支持 不是c++23 抱歉报的时候写错 难道msys2的mingw64环境编译是用gcc而不是g++? ![image](https://user-images.githubusercontent.com/16027616/273827497-269ccbde-0a8f-4aed-a698-9a70d95ff78a.png) ![image](https://user-images.githubusercontent.com/16027616/273828080-a1629233-f654-40a9-9160-0c82fac23de6.png)

个人认为可能还是跟编译器版本有关

**Comment by xia-chu** [comment]
@chenbingbcb 那个编译uint64_t失败的问题 请添加头文件 `#include <cstdint>`

**Comment by xia-chu** [comment]
这个ci通过了 不算bug
