### ISSUE TITLE
直播回看（时移）

### ISSUE THREAD

**Issue by xianghu1314** [ZLMediaKit/ZLMediaKit#2891]
允许指定回看的相对时移时长（即回看的时间起点与当前的时间差）。
时移回看依托直播录制能力，结合直播时移和点播的加速分发，实现在直播过程中进行回看的功能，用户可以实时选择从开播后的某个过往时间点开始进行回看，从而达到播放之前直播内容的效果。常用于赛事直播中的精彩片段回看，用户可以直接拖动进度条，进行回看，而不必等到直播结束，回看过程中直播流保持不变，用户可以在回看过程中切回直播。

**Comment by xianghu1314** [comment]
好的，我试一下

**Comment by TangLittle** [comment]
> hls支持直播时移的 配置文件segNum设置为0 即可

配置了segNum=0 请问一个直播流中途断开了一会儿推流 然后继续推流 怎么回放之前直播的内容呢？发现m3u8索引文件被覆盖重写了，只有最后一次推流开始后面的视频片段。
