### ISSUE TITLE
观看视频时，观众向Server发起一个http长连接请求(keepalive60s)，在50s后观众如何复用已经建立长连接再次发送请求？

### ISSUE THREAD

**Issue by D-NanSheng** [ZLMediaKit/ZLMediaKit#2892]
### 问题
- 第二次发起的请求并没有复用第一次请求建立的长连接。通过观察我发现http200回复包是在结束Session时才被wireshark抓包到的，在ZLMediaKit源码中Server找到视频源后就会将http200回复发送到socket一级缓存中等待发送，但是为什么这个回复会在结束Session的时候才会被发送呢？（并且我认为之所以没有复用请求是不是观众没有收到http200回复，所以不清楚Server能支持长连接？）
- 为了验证是否是在结束Session的时候才会回复http200，我又通过sudo curl --keepalive "http://127.0.0.1/live/stream-123456.flv" > ~/Desktop/output.flv 这个命令发起拉流请求，发现仅当我按下ctrl+c结束的时候 才会抓包到http200回复

**Comment by xiongguangjie** [comment]
1，多次http请求需要客户端使用同一个tcp链接
2，你这个是请求flv的视频文件

**Comment by D-NanSheng** [comment]
有帮助，感谢您的回复
