### ISSUE TITLE
在本地使用 OBS 推流, VLC media 拉流 延迟 3-4秒（为什么延迟怎么大呢？）。

### ISSUE THREAD

**Issue by tianmaoyu** [ZLMediaKit/ZLMediaKit#2897]
localhost 本地推拉，电脑硬件不差。

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/10215431/3692a17c-313c-462f-9560-1a24f8fe465a)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/10215431/f5a08a7f-3f63-4767-a5f9-57490410a047)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/10215431/c0de0686-7a45-48da-b59b-203037665431)

**Comment by xiongguangjie** [comment]
与播放器又关系（vlc 可以设置播放延迟），使用rtc 播放器或者官方自带的播放器 test_player
