### ISSUE TITLE
[技术咨询] 本地ffmpeg推送mp4，测试rtmp格式可以播放，但是rtsp以及flv格式播放不了

### ISSUE THREAD

**Issue by niuren930** [ZLMediaKit/ZLMediaKit#2901]
**咨询的功能模块**
- 你好，我在本地使用ffmpeg推送了一个MP4文件视频
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/111275223/e9c5ce9f-0060-4f7f-ab35-8efe51489c21)
推送至我在虚拟机上部署的docker版zlmediakit服务，
然后我在本地使用vlc测试播放，rtmp格式可以播放成功，地址是`rtmp://192.168.138.232/rtp/C3D9C639` 
然后我根据测试rtsp和flv地址却是失败的，地址是`http://192.168.138.232/rtp/C3D9C639/hls.m3u8`,`rtsp://192.168.138.232:554/rtp/C3D9C639` 

**咨询的具体内容和问题**
- 请问这是怎么回事呢？小白求解。谢谢啦
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/111275223/b94b43c4-e786-440c-86ab-4ccb1a347340)

**Comment by zongchaowenxue** [comment]
docker部署的？端口映射看一下

**Comment by xia-chu** [comment]
hls、flv应该能播放成功 rtsp不成功是因为默认udp传输是随机端口 你没映射

**Comment by xia-chu** [comment]
docker启动镜像指定：--network host

**Comment by niuren930** [comment]
已使用wvp-pro和zlm成功实现摄像机实时监控，谢谢啦，希望可以搞个QQ群，方便大家交流。

**Comment by xia-chu** [comment]
> 已使用wvp-pro和zlm成功实现摄像机实时监控，谢谢啦，希望可以搞个QQ群，方便大家交流。

qq群被封了 不搞了
