### ISSUE TITLE
[BUG] 第三方设备国标花屏

### ISSUE THREAD

**Issue by HalcyonHuang** [ZLMediaKit/ZLMediaKit#2903]
### 现象描述
 使用zlmedakit 对接了第三方小厂家的设备，设备端使用的是国标协议，zlmediakit 接收到国标rtp数据后，转换成标准rtp发送到自研媒体服务，播放过程中出现花屏，可能是由于每个p帧前面都有sps pps帧导致花屏，但是刚接触zlmediakit不知道怎么入手改。
 
![QQ图片20231013181137](https://github.com/ZLMediaKit/ZLMediaKit/assets/23181609/fdbcb61d-0bb8-4e05-9115-d3fa8f82f847)

![QQ图片20231013181402](https://github.com/ZLMediaKit/ZLMediaKit/assets/23181609/eb3ff647-b293-48a0-8b4a-4f6dd2fa97f7)

![QQ图片20231013181946](https://github.com/ZLMediaKit/ZLMediaKit/assets/23181609/8a57f5d8-5e6c-48b4-92a6-b4a7df2ec6af)

抓包文件:
[国标.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12892355/default.zip)

[124CCE3B_video.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12892370/124CCE3B_video.zip)
[124CCE3B_mp2.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12892371/124CCE3B_mp2.zip)
[124CCE3B_rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/12892372/124CCE3B_rtp.zip)
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
 使用的分支为:  remotes/old-origin/feature/transcode

7e95bd2078a9ea2575531d3703d250b71608cdb3

* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
一般是在关键帧前插入sps pps ,你的为什么会在p帧前插入呢？

**Comment by HalcyonHuang** [comment]
用的第三方小厂家的设备，偶尔出现花屏，很奇怪。

**Comment by xia-chu** [comment]
你这个mp2文件就播放有问题：
<img width="782" alt="图片" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/1c453f1b-ea4a-4510-a66e-7a20633524eb">

**Comment by HalcyonHuang** [comment]
这个bug应该是厂家的问题，非常感谢@xia-chu 的帮忙
