### ISSUE TITLE
rtsp实况转发

### ISSUE THREAD

**Issue by liujiaxin0010** [ZLMediaKit/ZLMediaKit#2905]
使用ZLMeditKit的addProxyStream方法实现rtsp流转发，rtsp返回的sdp中的媒体信息的payload type和rtp码流中的payload type不一致，
转发流无法播放，想问一下是不是转发过程中对原始rtp数据重新进行了解码后编码？

**Comment by wasphin** [comment]
抓段包看下？

**Comment by liujiaxin0010** [comment]
公司内外文件上次不了，起流过程中设备更改了视频编码格式，我看是设备到zlmediakit有rtp数据，zlmediakit到客户端之间没有rtp数据，

**Comment by xia-chu** [comment]
> 使用ZLMeditKit的addProxyStream方法实现rtsp流转发，rtsp返回的sdp中的媒体信息的payload type和rtp码流中的payload type不一致，

配置文件directProxy你设置多少？不一致说明你原始的就不一致的 zlm不管是直接代理还是非直接代理模式 都确保一致的

**Comment by liujiaxin0010** [comment]
directProxy设置的是1，设备起流过程中，已经开启代理，过程中修改了设备的视频编码格式导致原始数据就不一致了。

**Comment by xia-chu** [comment]
> directProxy设置的是1，设备起流过程中，已经开启代理，过程中修改了设备的视频编码格式导致原始数据就不一致了。

不会修改的 直接代理模式 rtp和sdp都不会修改payload type。你可以提供抓包文件截图或照片佐证你说的

**Comment by liujiaxin0010** [comment]
是不会修改，设备起流过程中，已经开启代理，设备原先是h265编码，代理转发过程中改成h264编码，此时zlm日志打印 H265Rtp.cpp:209  decodeRtp | 不支持该类型的265 RTP包，nal type62，rtp“：

**Comment by xia-chu** [comment]
> 是不会修改，设备起流过程中，已经开启代理，设备原先是h265编码，代理转发过程中改成h264编码，此时zlm日志打印 H265Rtp.cpp:209 decodeRtp | 不支持该类型的265 RTP包，nal type62，rtp“：

那这个这设备有点扯淡
