### ISSUE TITLE
[功能请求] 录像录制能否支持转码还有单个录像文件删除

### ISSUE THREAD

**Issue by 457775987** [ZLMediaKit/ZLMediaKit#2907]
目前在使用中发现两个问题：
1.录像文件只能按照目录以天为单位删除，无法指定删除莫一个
2.startRecord启动录像能否支持一下转码，比如h265的视频编码录制成了Mp4大部分播放器，甚至pc端的都播不了，需要转成h264，能否提供一下比较便捷的转码服务

**Comment by xia-chu** [comment]
1、zlm只负责生成录像 不负责删除，你需要结合数据库来管理和删除。
2、你可以搞个批处理脚本 用ffmpeg命令行转码即可 简单

**Comment by 457775987** [comment]
明白了，目前看只能外挂一个程序一起用，目前是开发了一个小程序和zlm绑定部署在节点，代为转码，删除文件
