### ISSUE TITLE
[BUG] 添加代理拉流报 This stream already exists，使用getMediaList/close_streams没有发现/关闭的流

### ISSUE THREAD

**Issue by laobaoabc** [ZLMediaKit/ZLMediaKit#2913]
### 现象描述
使用wvp+zlm添加代理拉流，运行一段时间后流离线(wvp查的getMediaList)。后续使用

1 使用 /index/api/addStreamProxy 添加代理拉流报 This stream already exists
2 使用 /index/api/getMediaList 查询流不存在
3 使用 /index/api/close_streams 没关闭的流

### 如何复现?

添加代理拉流运行一段时间后出现，触发条件未知

使用的无牌摄像头，拉流地址 rtsp://ip:554/ch01_sub.264?dev=1

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>

```
2023-10-20 17:43:44.888 D [MediaServer] [266-event poller 3] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/addStreamProxy
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 195
Content-Type : application/x-www-form-urlencoded
Host : 172.24.12.12:9092
User-Agent : okhttp/4.9.3
# content:
secret=xx&app=app&vhost=__defaultVhost__&stream=037a000200501fb9c1ed__D01_CH01_Sub&enable_audio=1&enable_mp4=0&url=rtsp%3A%2F%2Fadmin%3A123456%40172.24.12.24%3A554%2Fch01_sub.264%3Fdev%3D1
# response:
{
	"code" : -1,
	"msg" : "This stream already exists"
}



2023-10-20 17:48:13.075 D [MediaServer] [266-event poller 0] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getMediaList?secret=xx&app=app&vhost=__defaultVhost__&stream=037a000200501fb9c1ed__D01_CH01_Sub
# header:
Accept-Encoding : gzip,deflate
Connection : Keep-Alive
Content-Length : 0
Host : 172.24.12.12:9092
User-Agent : Apache-HttpClient/4.5.13 (Java/17.0.6)
# content:

# response:
{
	"code" : 0
}


2023-10-20 17:49:20.278 D [MediaServer] [266-event poller 0] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/close_streams?secret=xx&app=app&vhost=__defaultVhost__&force=1&stream=037a000200501fb9c1ed__D01_CH01_Sub
# header:
Accept-Encoding : gzip,deflate
Connection : Keep-Alive
Content-Length : 0
Host : 172.24.12.12:9092
User-Agent : Apache-HttpClient/4.5.13 (Java/17.0.6)
# content:

# response:
{
	"code" : 0,
	"count_closed" : 0,
	"count_hit" : 0
}



```

</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:  f69f3b30 xiongguangjie `<xiong_panda@163.com>` on 2023/9/9 at 10:59
* **操作系统及版本**: docker
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
- 1、addStreamProxy返回This stream already exists说明你已经添加这个流了
- 2、getMediaList查询流不存在，说明这个拉流地址有问题 zlm拉流失败
- 3、close_streams只能关闭一个已经拉流代理成功的流，未注册的流，你应该用delStreamProxy接口

**Comment by laobaoabc** [comment]
> * 1、addStreamProxy返回This stream already exists说明你已经添加这个流了
> * 2、getMediaList查询流不存在，说明这个拉流地址有问题 zlm拉流失败
> * 3、close_streams只能关闭一个已经拉流代理成功的流，未注册的流，你应该用delStreamProxy接口

明白了，非常感谢
