### ISSUE TITLE
[技术咨询] /index/api/delStreamProxy删除经常返回flag:false

### ISSUE THREAD

**Issue by woodrow-lwd** [ZLMediaKit/ZLMediaKit#2917]
**咨询的功能模块**
- 调用/index/api/delStreamProxy删除经常返回flag:false，可能原因是什么？

**咨询的具体内容和问题**
- 通过/index/api/addStreamProxy接口创建的流，调用/index/api/delStreamProxy删除经常返回flag:false，可能的原因是什么？

以下是一些接口参数日志，可以kanmd看到有时一直false、有时一直true：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/39107857/2b86dc5d-59ab-431e-bbf5-e19eb45ffd7d)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/39107857/bbfbcacc-1e51-425c-913c-c1509b0bb8d7)

**Comment by xia-chu** [comment]
说明这个流本来就不存在

**Comment by woodrow-lwd** [comment]
哦确实是，见笑了
