### ISSUE TITLE
ssrc 问题[技术咨询] 咨询描述(必填)

### ISSUE THREAD

**Issue by song01** [ZLMediaKit/ZLMediaKit#2920]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
同一个zlmediakit进程下，多个gb推流可以使用相同的ssrc吗？
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by song01** [comment]
单端口模式不支持同时播放相同的ssrc，多端口模式支持同时播放相同的ssrc，是这样吗？

**Comment by xiongguangjie** [comment]
> 单端口模式不支持同时播放相同的ssrc，多端口模式支持同时播放相同的ssrc，是这样吗？

是的
