### ISSUE TITLE
【功能需求】增加mp4上传，并进行切片，hls播放的restful-api

### ISSUE THREAD

**Issue by xueshuai0922** [ZLMediaKit/ZLMediaKit#2925]
**描述该功能的用处，可以提供相关资料描述该功能**
增加mp4上传，并进行切片，hls播放的restful-api
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
对于不懂C++的开发人员，提供开放此api，有助于项目的使用
**描述你期望实现该功能的方式和最终效果**

再次十分感谢如此高性能的开源流媒体服务器！

**Comment by xia-chu** [comment]
这个掉个ffmpeg的命令行就行 用java开发很简单的
