### ISSUE TITLE
目前通过k8s能简单实现ZLM的集群部署吗

### ISSUE THREAD

**Issue by Sirius7cangshu** [ZLMediaKit/ZLMediaKit#2926]
**集群部署**
目前在做ZLM集群相关的测试，但是不确定ZLM是否真的支持部署为集群服务

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
当然可以了 我现在就是这么部署的啊 不过你要自己开发点周边业务逻辑 具体业务不同而不同
