### ISSUE TITLE
[功能请求] 意见建议关于PT值在线改变

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#2927]
**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
      今天我在本地做拉流测试，数据源IPC是很多个人都在用的；是一个音视频都有的摄像头，人在说话
我测着测着发现，怎么音视频打印的时间戳差非常大；看一下日志打印，没有音频过来吗？？然后我在当下用ffplay拉了一下，发现有声音；而我自己拉的数据突然没声音了，录像也没声音；神奇，难道摄像头发着发着不发声音了；

正好是挂在win上就在recvrtp的地方直接断点调试了，然后发现音频的 PT值某个时间变了，询问下是被某个测试同事修改了，而我这边拉流是一直正常的；代码这里就直接return了
RtpPacket::Ptr RtpTrack::inputRtp：
 if (_pt == 0xFF) {
        _pt = header->pt;
    } else if (header->pt != _pt) {
        //TraceL << "rtp pt mismatch:" << (int) header->pt << " !=" << (int) _pt;
        return nullptr;
    }

这个问题本身其实应该怪摄像头，改变编码方式居然不断流，也不改SSRC；

所以这里是否可以打印提示下，或者，直接透传过去这种变编码数据（可能也并不合理）；
非常小的一个地方，也不是bug，但是如果有提示会更好；省去抓包分析，以及一些无厘头的猜测

**描述你期望实现该功能的方式和最终效果**
见上

**Comment by xia-chu** [comment]
不能 因为没法通过http api去定位到这个对象 这个对象获取不到。
就算能获取的到，也比较曲折，导致代码可读性差 代码很乱不优雅。
而且这种问题没必要去兼容 这个本来就是对方不常见的bug。

**Comment by xuandu** [comment]
嗯嗯，好的
