### ISSUE TITLE
[技术咨询] 关于RTP推流下手动录制功能

### ISSUE THREAD

**Issue by PassXml** [ZLMediaKit/ZLMediaKit#2929]
web api中有一项 /index/api/startRecord 的手动录制功能.

其中customized_path参数意味,自定义路径

但是我发现在手动录制国标RTP流的时候,发现该参数并没有生效

我自定义路径下并没有自动生成,但是record/rtp下有记录生成

请问这是正常的么?

而且record的文件名规则能大概讲下么

**Comment by xia-chu** [comment]
有效的 前提是你并没有在录制 只有从不录制到开启录制 这个参数才有效。
你可以MediaServer -l 0启动 然后操作下 再给我们日志分析 否则我都不想花精力从验证你的 
因为不可能对国标单独有这个限制 这个问题多半是你闹的乌龙 所以需要你提供足够的证据

**Comment by PassXml** [comment]
> 有效的 前提是你并没有在录制 只有从不录制到开启录制 这个参数才有效。 你可以MediaServer -l 0启动 然后操作下 再给我们日志分析 否则我都不想花精力从验证你说的 因为不可能对国标单独有这个限制 这个问题多半是你闹的乌龙 所以需要你提供足够的证据

谢谢..我只是想求证下这个参数的具体使用方法...例如<<只有从不录制到开启录制 >> 这个细节可能我就没有注意到，也许是存在其他流录制从而导致无法修改
