### ISSUE TITLE
[BUG] 缺少必要参数: "secret"

### ISSUE THREAD

**Issue by z-houbin** [ZLMediaKit/ZLMediaKit#2930]
### 现象描述
url 中已经携带参数，参数靠前正常靠后异常

### 如何复现?
正常
http://127.0.0.1:8081/index/api/close_streams?secret=foZquBwoStWYM74yP3yTmceXSjFC4UMI&schema=rtsp&vhost=__defaultVhost__&app=live&stream=c18dbade644041ca88f2cb01ca330a46&force=1

异常
http://127.0.0.1:8081/index/api/close_streams?schema=rtsp&vhost=__defaultVhost__&app=live&stream=c18dbade644041ca88f2cb01ca330a46&force=1&secret=foZquBwoStWYM74yP3yTmceXSjFC4UMI

**Comment by xiongguangjie** [comment]
没有问题呀，我测试了下

**Comment by xia-chu** [comment]
不可能有这个问题 你提bug日志都不给吗？

**Comment by z-houbin** [comment]
抱歉，我的问题 ，命令行中执行忘了加引号。
