### ISSUE TITLE
webrtc可以支持关闭srtp吗

### ISSUE THREAD

**Issue by feigegithub** [ZLMediaKit/ZLMediaKit#2931]
嵌入式设备CPU比较紧缺的设备收发webrtc音视频流由于加密的需求要用srtp，但是这比较耗CPU，能提供webrtc握手关闭srtp的功能吗

**Comment by xiongguangjie** [comment]
这个需要做下二次开发，参考这个 https://zhuanlan.zhihu.com/p/399775813

**Comment by feigegithub** [comment]
> 这个需要做下二次开发，参考这个 https://zhuanlan.zhihu.com/p/399775813

1，chrome关闭srtp

看stackflow的文档[[1]](https://zhuanlan.zhihu.com/p/399775813#ref_1)需要[Chrome Canary](https://link.zhihu.com/?target=https%3A//www.google.cn/intl/zh-CN/chrome/canary/)版本或Chrome Developer版本，故下载Chrome Canary 版本。找到安装目录，通过windows powershell打开chrome

.\chrome.exe --disable-webrtc-encryption


链接里面提到的这点通用性就不强，浏览器还得特定版本，而且运行还要加参数。据我了解srtp在最新版本的浏览器已经是强制打开的，有没什么办法直接在浏览器获取流解密后转回zlm，或者zlm不加密丢给前端处理加密再转给浏览器

**Comment by xiongguangjie** [comment]
> > 这个需要做下二次开发，参考这个 https://zhuanlan.zhihu.com/p/399775813
> 
> 1，chrome关闭srtp
> 
> 看stackflow的文档[[1]](https://zhuanlan.zhihu.com/p/399775813#ref_1)需要[Chrome Canary](https://link.zhihu.com/?target=https%3A//www.google.cn/intl/zh-CN/chrome/canary/)版本或Chrome Developer版本，故下载Chrome Canary 版本。找到安装目录，通过windows powershell打开chrome
> 
> .\chrome.exe --disable-webrtc-encryption
> 
> 链接里面提到的这点通用性就不强，浏览器还得特定版本，而且运行还要加参数。据我了解srtp在最新版本的浏览器已经是强制打开的，有没什么办法直接在浏览器获取流解密后转回zlm，或者zlm不加密丢给前端处理加密再转给浏览器

浏览器必需使用dtls, 你的问题不是嵌入式设备想直接使用rtp吗，你完全可以按照链接里面的进行参考

**Comment by xiongguangjie** [comment]
完全可以嵌入式使用rtp,浏览器使用dtls ，只是需要你修改 ZLM与嵌入式的程序

**Comment by feigegithub** [comment]
> 完全可以嵌入式使用rtp,浏览器使用dtls ，只是需要你修改 ZLM与嵌入式的程序

我是要嵌入式跟浏览器做互动，把嵌入式的流推到浏览器上播或者从浏览器上采集摄像头到嵌入式来播，所以从浏览器推拉流都涉及srtp加解密。如果浏览器必须用dtls，有没什么接口可以从浏览器获取到webrtc的srtp，解密后再推回嵌入式。

**Comment by xiongguangjie** [comment]
> > 完全可以嵌入式使用rtp,浏览器使用dtls ，只是需要你修改 ZLM与嵌入式的程序
> 
> 我是要嵌入式跟浏览器做互动，把嵌入式的流推到浏览器上播或者从浏览器上采集摄像头到嵌入式来播，所以从浏览器推拉流都涉及srtp加解密。如果浏览器必须用dtls，有没什么接口可以从浏览器获取到webrtc的srtp，解密后再推回嵌入式。

你这个如果经过公网服务器中转是可以实现的，如果是局域网内，访问嵌入式的浏览器，就很麻烦，那只能使用其他协议实现了
