### ISSUE TITLE
Rtsp拉流代理接口/index/api/addStreamProxy，url参数编码特殊字符个别识别错误

### ISSUE THREAD

**Issue by Gosiu** [ZLMediaKit/ZLMediaKit#2932]
### 现象描述

调用拉流代理接口/index/api/addStreamProxy，url参数传入后密码阶段个别特殊字符解码截断后面的内容，目前只发现%不行，@#&可以
### 如何复现?

1.首先调用拉流代理接口/index/api/addStreamProxy，url参数传入Jm123%123
2.然后查看后台输出为Jm123，特殊字符后面的没有了
3.期望Jm123%123
4.结果Jm123
5.目前只发现%不行，@#&可以

url为

rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1
### 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/146540588/426db163-f516-4579-be4d-0b18631173aa)

<details>
<summary>展开查看详细日志</summary>
<pre>
2023-10-27 09:58:35.272 D [MediaServer] [3862-event poller 0] RtspPlayer.cpp:88 play | rtsp://111.47.84.69:554/Streaming/Channels/101?transportmode=unicast&amp;profile=Profile_1 admin Jm13317934� 0
2023-10-27 09:58:35.361 W [MediaServer] [3862-event poller 0] RtspPlayer.cpp:685 onPlayResult_l | 255 DESCRIBE:401 Unauthorized
2023-10-27 09:58:35.361 D [MediaServer] [3862-event poller 0] WebApi.cpp:250 http api debug | 
# request:
GET /index/api/addStreamProxy?secret=PmIgBq6pUixIjey6J89oYKF1QW8DmZWc&app=3555&vhost=__defaultVhost__&rtp_type=0&stream=501&enable_audio=0&enable_mp4=0&url=rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1
# header:
Accept : */*
Accept-Encoding : gzip, deflate, br
Connection : keep-alive
Host : 172.16.10.174:9688
User-Agent : Apifox/1.0.0 (https://apifox.com)
# content:

# response:
{
        "code" : -1,
        "msg" : "DESCRIBE:401 Unauthorized"
}

2023-10-27 09:58:35.361 D [MediaServer] [3862-event poller 1] RtspPlayerImp.h:31 ~RtspPlayerImp | 
2023-10-27 09:58:35.361 D [MediaServer] [3862-event poller 1] RtspPlayer.cpp:36 ~RtspPlayer | 

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=PmIgBq6pUixIjey6J89oYKF1QW8DmZWc
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s

[general]
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=60000
mediaServerId=u2BxRqxX5NZGBFiw
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
admin_params=secret=gjhzs123
alive_interval=30.000000
enable=1
on_flow_report=
on_http_access=
on_play=http://172.16.10.139:8080/index/hook/on_play
on_publish=http://172.16.10.139:8080/index/hook/on_publish
on_record_mp4=http://127.0.0.1:18081/api/record/on_record_mp4
on_record_ts=
on_rtp_server_timeout=http://172.16.10.139:8080/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://172.16.10.139:8080/index/hook/on_send_rtp_stopped
on_server_exited=
on_server_keepalive=http://172.16.10.139:8080/index/hook/on_server_keepalive
on_server_started=http://172.16.10.139:8080/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://172.16.10.139:8080/index/hook/on_stream_changed
on_stream_none_reader=http://172.16.10.139:8080/index/hook/on_stream_none_reader
on_stream_not_found=http://172.16.10.139:8080/index/hook/on_stream_not_found
retry=1
retry_delay=3.000000
timeoutSec=20

[http]
allow_cross_domains=1
allow_ip_range=172.16.10.139,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=60
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:/,branch:,build time:2023-10-16T11:32:58)</center></body></html>
port=9688
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
port=0
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
tcpPort=0
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=19350

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=50000-50300
ps_pt=96
timeoutSec=60

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=60
keepAliveSecond=60
lowLatency=0
port=554
rtpTransportType=-1
sslport=332

[shell]
maxReqSize=1024
port=9000

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=30
; } ---

</pre>
</details>

### 各种环境信息

CentOS 7
* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
你的转义有问题，rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1 
转换为
rtsp://admin:Jm13317934%jm@111.47.84.69:554/Streaming/Channels/101?transportmode=unicast&amp;profile=Profile_1

但是密码为 Jm13317934%jm，是个错误的转义

**Comment by xiongguangjie** [comment]
> addStreamProxy

这个是个bug ,我修复了

**Comment by xiongguangjie** [comment]
使用这个分支来测试一下 https://github.com/xiongguangjie/ZLMediaKit/tree/fix_url_decodeing

**Comment by xia-chu** [comment]
不过admin:Jm13317934%jm再在RtspUrl中split时 %jm出问题了 确实还有问题

**Comment by xia-chu** [comment]
这个pr合并了 @Gosiu 麻烦测试验证下 谢谢

**Comment by Gosiu** [comment]
> 你的转义有问题，rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1 转换为 rtsp://admin:Jm13317934%jm@111.47.84.69:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1
> 
> 但是密码为 Jm13317934%jm，是个错误的转义

rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1
此为实际问题的url，其中的Jm13317934%25jm是转义后的密码，很抱歉在复现中使用了“Jm123%123”这一个不同的测试用例。但同样复现了%25转义失败的问题。我现在来测试。非常感谢各位大神的神速处理，学习了。

**Comment by Gosiu** [comment]
> 不过admin:Jm13317934%jm再在RtspUrl中split时 %jm出问题了 确实还有问题

rtsp%3A%2F%2Fadmin%3AJm13317934%25jm%40111.47.84.69%3A554%2FStreaming%2FChannels%2F101%3Ftransportmode%3Dunicast%26amp%3Bprofile%3DProfile_1
此为实际问题的url，其中的Jm13317934%25jm是转义后的密码，很抱歉在复现中使用了“Jm123%123”这一个不同的测试用例。但同样复现了%25转义失败的问题。我现在来测试。非常感谢各位大神的神速处理，学习了。

**Comment by Gosiu** [comment]
> 测试验证

测试完成，验证后问题已解决

**Comment by Gosiu** [comment]
> 这个pr合并了 @Gosiu 麻烦测试验证下 谢谢

测试完成，验证后问题已解决

**Comment by Gosiu** [comment]
@xiongguangjie @xia-chu

**Comment by xia-chu** [comment]
ok 感谢反馈
