### ISSUE TITLE
[功能请求] 构建ZLMediaKit时遇到的小问题(必填)

### ISSUE THREAD

**Issue by MQDHY** [ZLMediaKit/ZLMediaKit#2934]
**使用DockerFile自己构建ZLMediaKit时发现有个地方老是导致构建失败**
![1698400440399](https://github.com/ZLMediaKit/ZLMediaKit/assets/50725124/288df460-983e-4628-9d08-771f694ce84d)

**希望这里可以改成gitee的地址这样会好点，下载时不会因为是网络问题出现超时的情况**

**Comment by xia-chu** [comment]
这个应该改成默认gitee镜像了 请更新代码再测试
