### ISSUE TITLE
[技术咨询] 加快一天的MP4文件播放速度

### ISSUE THREAD

**Issue by Hareis** [ZLMediaKit/ZLMediaKit#2937]
将mp4录制的切片大小设置为86400s了，但是这样每次在播放之前需要下载近80M的元数据，导致web上加载很慢，

后面了解到有fmp4,能让web快速播放起来

但是搜索了zlmediakit相关的文档，没有看到有仅录制为fmp4的开关，而是hls-fmp4

请问下夏大 ，这块是应该怎么处理 ？还是 自己转mp4-fmp4

**Comment by xia-chu** [comment]
fmp4也加载不快 配置文件你可以开启fastStart 设置为1即可 这样web加载明显加快

**Comment by Hareis** [comment]
> fmp4也加载不快 配置文件你可以开启fastStart 设置为1即可 这样web加载明显加快

谢谢 需要重启服务吗？

**Comment by xia-chu** [comment]
killall -1 就行 热加载配置文件

**Comment by Hareis** [comment]
谢谢 笔芯
