### ISSUE TITLE
RTSP\GB28181 是否有 QoS 的支持？

### ISSUE THREAD

**Issue by zhanglm666** [ZLMediaKit/ZLMediaKit#2939]
咨询一下，ZLM 中的 RTSP 协议或者 GB28181 ，内部是否提供了基于 RTCP 的拥塞控制机制？

**Comment by xia-chu** [comment]
不支持 webrtc支持 其他没这个机制 。

**Comment by xia-chu** [comment]
rtsp一般都没qos机制 所以建议用tcp模式。
国标更没有了 设计上就没有
