### ISSUE TITLE
ZLM主动拉取SRT流，或者主动推送SRT流？

### ISSUE THREAD

**Issue by zhanglm666** [ZLMediaKit/ZLMediaKit#2942]
ZLM可以主动拉取SRT流，或者主动推送SRT流吗？如果可以，是哪些接口呢？谢谢

**Comment by xiongguangjie** [comment]
现在还不行，可以间接实现，使用addffmpegproxy 这个接口来实现

**Comment by zhanglm666** [comment]
> 现在还不行，可以间接实现，使用addffmpegproxy 这个接口来实现

没有addFFmpegProxy的接口，只用addFFmpegSource的接口，也就是只能通过ffmpeg主动拉srt流，不能主动推srt流。
