### ISSUE TITLE
[技术咨询] 4个客户端同时拉rtsp流，720p60fps  和 4k60fps 测试视频概率的不能完整拉流 （总共3600帧数据只能拉取到2000帧左右）

### ISSUE THREAD

**Issue by liyeqiang** [ZLMediaKit/ZLMediaKit#2944]
**咨询的功能模块**
- RTSP拉流

**咨询的具体内容和问题**
- 将720p /1080p /4K 帧率 30fps 60fps 测试视频分别放在服务器目录， 通过rtsp协议拉流， 每次4个客户端同时拉流， 其中720p60fps 和 4k60fps 概率出现拉流不完整
- 想问下有没有什么参数可以设置增大缓存，或者设置超时时间来改善这个问题

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
rtsp拉流请指定tcp模式 ffplay加上 -rtsp_transport tcp参数

**Comment by liyeqiang** [comment]
是tcp模式，  -rtsp_transport tcp参数带参数的
