### ISSUE TITLE
[技术咨询] addStreamProxy,addFFmpegSource

### ISSUE THREAD

**Issue by song01** [ZLMediaKit/ZLMediaKit#2945]
**咨询的功能模块**
- 拉流代理
**咨询的具体内容和问题**
- addFFmpegSource 通过fork FFmpeg进程的方式拉流代理，支持任意协议；
- addStreamProxy  底层原理是怎么样的？拉流失败重试的会消耗大量资源吗？
- addFFmpegSource 参数里没有重试相关参数，这时候如果src_url不可用的逻辑是怎样的？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
addFFmpegSource内部会无限重试。如果dst_url是zlm本身 zlm发现流不在线就会重启ffmpeg。如果dst_url是第三方服务器，zlm只判断ffmpeg进程是否在线 不在线会拉起。


addStreamProxy是调用zlm自己实现的播放器，支持rtsp/rtmp/hls/http-flv/http-ts. 基本不占用资源 性能极好。

**Comment by song01** [comment]
1. addStreamProxy 拉流过程中 如断网导致失败，重试的策略可以介绍一下吗？比如重试的时间间隔
2. addStreamProxy 开启mp4录制，拉流过程中 如断网导致失败，会生成多个1s左右的视频片段，这个是什么原因？或者怎样可以避免这些小片段的生成？

**Comment by xia-chu** [comment]
addStreamProxy失败重试间隔是2~60秒 连续失败次数越大  延时越高：
```c++

void PlayerProxy::rePlay(const string &strUrl, int iFailedCnt) {
    auto iDelay = MAX(_reconnect_delay_min * 1000, MIN(iFailedCnt * _reconnect_delay_step * 1000, _reconnect_delay_max * 1000));
    weak_ptr<PlayerProxy> weakSelf = shared_from_this();
    _timer = std::make_shared<Timer>(
        iDelay / 1000.0f,
        [weakSelf, strUrl, iFailedCnt]() {
            // 播放失败次数越多，则延时越长
            auto strongPlayer = weakSelf.lock();
            if (!strongPlayer) {
                return false;
            }
            WarnL << "重试播放[" << iFailedCnt << "]:" << strUrl;
            strongPlayer->MediaPlayer::play(strUrl);
            strongPlayer->setDirectProxy();
            return false;
        },
        getPoller());
}
```

**Comment by xia-chu** [comment]
addStreamProxy生成1s左右的视频片段的问题 你可以debug一下 修复了给个pr。

暂时没时间去调试这个问题 你自己先研究下吧

**Comment by song01** [comment]
addStreamProxy是调用zlm自己实现的播放器 这个怎么理解？相当于加了一个流的观看者吗？
这个方法也会生成一个新的流

**Comment by song01** [comment]
addStreamProxy 的参数retry_count 测试发现没有生效，getProxyInfo 返回的数据rePullCount 会大于retry_count指定的值

**Comment by song01** [comment]
retry_count 与rePullCount  关系应该是怎样的

**Comment by xia-chu** [comment]
> addStreamProxy是调用zlm自己实现的播放器 这个怎么理解？相当于加了一个流的观看者吗？ 这个方法也会生成一个新的流

zlm自己的代码拉流代理的 没用ffmpeg

**Comment by xia-chu** [comment]
> addStreamProxy 的参数retry_count 测试发现没有生效，getProxyInfo 返回的数据rePullCount 会大于retry_count指定的值

retry_count就是拉流失败最大连续次数。一直失败，累积超过这个次数就不会重试了。

肯定能生效的。

你讨论到代码细节层面的东西 需要你自己调试代码。

**Comment by xia-chu** [comment]
你说zlm功能有缺陷 应该给出证据 比如说日志 否则我们没太多时间去验证你说的问题 因为事实证明太多乌龙事件
