### ISSUE TITLE
[技术咨询] flv协议直播输出音频编码格式有没有配置项可以修改成AAC

### ISSUE THREAD

**Issue by zhangyu927** [ZLMediaKit/ZLMediaKit#2947]
**咨询的功能模块**
- flv直播
- 
**咨询的具体内容和问题**
- 您好，flv协议直播输出音频编码格式有没有配置项可以修改成AAC。
- 我的设备往ZLMediaKit推流音频编码是G711A，输出也是G711A, 播放地址：wss://127.0.0.1:443/rtp/32013344551311500520_32013344551311500520.live.flv，播放黑屏，控制台报错：[TransmuxingController] > DemuxException: type = CodecUnsupported, info = Flv: Unsupported audio codec idx: 7，大概是不支持这个音频编码格式，看了下公司其他流媒体输出的音频格式是AAC可以正常播放，如果能将音频转成AAC编码就好了，有没有对应的配置，感谢

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
目前不支持转码 你可以用addFFmpegSource接口间接实现转码
