### ISSUE TITLE
addFFmpegSource 接口，参数 enable_mp4=0 不起作用，参数 dst_url 使用 localhost

### ISSUE THREAD

**Issue by qq51529210** [ZLMediaKit/ZLMediaKit#2949]
### 现象描述

addFFmpegSource 接口，参数 enable_mp4=0 不起作用，依然保存了录像。
经过测试，是因为设置了 dst_url=rtmp://localhost  这个 localhost 造成的，因为不会触发 on_publish 。
如果设置成 192.168.x.x ，触发 on_publish 后返回的 json 中设置 enable_mp4=0 是正常的。

### 如何复现?

调用接口时，dst_url 使用 localhost 或者 127.0.0.1 即可，因为不会触发 on_publish。

### 程序版本

编译日期: 2023-06-12T19:00:11
代码日期: 2023-05-14T10:19:07+08:00
当前git分支: master
当前git hash值: 15e7629

**Comment by xia-chu** [comment]
新版本推流到127也会触发on_publish了 请更新代码
