### ISSUE TITLE
两个zlm之间如何使用webrtc传输？

### ISSUE THREAD

**Issue by zhanglm666** [ZLMediaKit/ZLMediaKit#2950]
**咨询的功能模块**
- webRTC

**咨询的具体内容和问题**
- 部署两个zlm，a和b，让a可以通过webRTC推流到b上。该如何实现？谢谢。

**Comment by Dw9** [comment]
1、目前还不支持rtc 级联； 可以让zlm推rtsp等来替代，效果基本一样；
2、拉zlm的流转rtc  whip推到其他服务上
你是两个zlm 基本上用方案1就ok

**Comment by zhanglm666** [comment]
> 1、目前还不支持rtc 级联； 可以让zlm推rtsp等来替代，效果基本一样； 2、拉zlm的流转rtc whip推到其他服务上 你是两个zlm 基本上用方案1就ok

这两个zlm夸公网，希望可以使用可靠性强的协议，例如srt、webrtc，但是都无法做到。srt可以让公网的zlm通过addFFmoegSource接口来拉srt流，但是我的公网zlm是无法访问到内网的zlm的，所以也无法通过srt拉取。请问，有其它合适的方案吗？谢谢。

**Comment by Dw9** [comment]
直接rtmp，rtsp over tcp这种不够用吗？ 如果你的网络太不靠谱，估计啥协议效果也不太好。
非要推rtc的话，ffmpeg 有个实现了whip 的版本，你可以试试，或者像方案2一样自己开发。

**Comment by zhanglm666** [comment]
ok, 感谢。
