### ISSUE TITLE
[BUG] 连接相机超时后，zlm无法响应任何请求

### ISSUE THREAD

**Issue by mopooo** [ZLMediaKit/ZLMediaKit#2956]
### 现象描述

某些情况下，请求zlm的addStreamProxy时所有相机都rtsp time out，强行重启zlm后正常

### 如何复现?

1. 请求多个相机rtsp拉流代理，均可正常播放，然后关闭player，触发无人观看，销毁对应流
2. 某个相机A出现故障
3. 再次请求多个相机rtsp拉流代理，其中包括了故障相机A，但此时显示A对应的流扔存在，两次后显示rtsp time out
4. 请求其他正常相机时也显示rtsp time out
5. 多次请求zlm接口时会出现异常，例如python端，('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
6. 强行重启zlm后正常相机均恢复正常

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容
[zl-1107.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13277030/zl-1107.log)

其中相机无人观看后注销：
[33m2023-11-07 13:41:23.609 W [MediaServer] [1-event poller 38] WebHook.cpp:603 operator() | 无人观看主动关闭流:hls://__defaultVhost__/live/R84_Aw_CamN-1[0m

相机可能出现故障

再次请求时：
[32m2023-11-07 14:11:17.889 D [MediaServer] [1-event poller 45] RtspPlayer.cpp:88 play | rtsp://192.168.93.4:554/Streaming/Channels/202 admin @Tyjt101 0[0m
[34m2023-11-07 14:11:17.889 T [MediaServer] [1-event poller 45] TcpClient.cpp:79 startConnect | mediakit::RtspPlayerImp-86 start connect 192.168.93.4:554[0m
[34m2023-11-07 14:11:19.965 T [MediaServer] [1-event poller 45] TcpServer.h:54 operator() | 203-1167(172.20.0.1:38120) mediakit::HttpSession[0m
[32m2023-11-07 14:11:19.965 D [MediaServer] [1-event poller 45] WebApi.cpp:250 http api debug | 
# request:
GET /index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925ee&vhost=__defaultVhost__&app=live&stream=R84_Aw_CamN-1&url=rtsp%3A%2F%2Fadmin%3A%40Tyjt101%40192.168.93.4%3A554%2FStreaming%2FChannels%2F202
# header:
Accept : */*
Accept-Encoding : gzip, deflate
Connection : keep-alive
Host : 10.10.3.14:8080
User-Agent : python-requests/2.28.1
# content:

# response:
{
	"code" : -1,
	"msg" : "This stream already exists"
}

之后出现各种rtsp time out，无法正常播放任何流，没办法只能重启：
[33m2023-11-07 14:27:38.760 W [MediaServer] [1-MediaServer] main.cpp:424 operator() | SIGTERM:exit[0m

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by mopooo** [comment]
更新一下现象：如果快速addStreamProxy请求十几次会超时的相机，zlm大概率会首先对此接口失去响应，然后调用webhook会出现超时（实际上用postman可以正常访问），再然后就是所有接口都失去响应，但日志里还会不断的刷GET_PARAMETER，估计是之前一些正常播放的流还存在，但zlm已经不能响应任何新的http请求了

**Comment by mopooo** [comment]
更新到11.10最新master代码后暂未复现，可以先关闭

**Comment by xwh1108** [comment]
插眼
