### ISSUE TITLE
[技术咨询] 通过addStreamProxy拉流,怎么样倍速播放

### ISSUE THREAD

**Issue by Tsukasa007** [ZLMediaKit/ZLMediaKit#2964]
**咨询的功能模块**
addStreamProxy拉流倍速播放

**咨询的具体内容和问题**
使用addStreamProxy添加一个NVR的回放流比如:rtsp://admin:admin@192.168.20.245:554/cam/playback?channel=1&subtype=0starttime=2023_11_09_08_17_00
使用wss://192.168.20.251:50443/live/playback/playback.live.flv播放时可以倍速播放吗,或者说是不是我的思路有问题请教一下,谢谢!

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
zlm只负责代理 不管数据是不是倍速的 如果源数据是倍速的 那么代理后的就是倍速的
当然最后能不能倍速 最后取决与播放器是否配合
