### ISSUE TITLE
[技术咨询 网络问题导致的推流断开，流不能及时注销

### ISSUE THREAD

**Issue by song01** [ZLMediaKit/ZLMediaKit#2965]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 推流端网络断开后，一段时间内getMediaList接口返回该流仍然存在；过了几分钟后，该流才注销

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
注销事件跟continue_push_ms相关 不会几分钟 就十多秒。

你也没提供日志证据 issue先关闭了
