### ISSUE TITLE
[技术咨询] openssl依赖版本问题，openssl3.1支持吗

### ISSUE THREAD

**Issue by walkTtalk** [ZLMediaKit/ZLMediaKit#2968]
**咨询的功能模块**
- openssl依赖版本问题，openssl3.1支持吗

**Comment by walkTtalk** [comment]
最高支持3.1版本吗。

**Comment by walkTtalk** [comment]
好像不支持。提示error while loading share libraries libssl.so.1.1 cannot open shared object file:no such file or directory

**Comment by xia-chu** [comment]
支持openssl3.0 3.1应该也支持 你说的是另外一回事

**Comment by walkTtalk** [comment]
> 支持openssl3.0 3.1应该也支持 你说的是另外一回事

谢谢，后续再关注这个问题吧，本来打算结合http3，但稳定版还得等1年。libsrtp 2.5.0好像对openssl3.0以上支持还没完善。后续再测试。
