### ISSUE TITLE
[技术咨询] 请教一下，通过WebSocket连接提示 http server do not support websocket default 问题

### ISSUE THREAD

**Issue by malapidan** [ZLMediaKit/ZLMediaKit#2975]

**Comment by xiongguangjie** [comment]
你的url 写错了吧，只会允许ws的url去取流，其他的ws请求都会被拒绝

**Comment by xia-chu** [comment]
ws-flv的播放url后缀是.live.flv。

如果访问zlm的ws服务，后缀不对就会报这错误

**Comment by malapidan** [comment]
> 你的url写错了吧，只允许ws的url去取流，其他的ws请求都会被拒绝

好的，谢谢

**Comment by malapidan** [comment]
> ws-flv的播放url后缀是.live.flv。
> 
> 如果访问zlm的ws服务，后缀就会报这个错误。
> 
> 如果你使用zlm的websocket传输非流媒体数据，那么需要自己二次开发。

好的，谢谢
