### ISSUE TITLE
[编译问题] 最新代码编译‘X509_up_ref’ was not declared in this scope; did you mean ‘X509_free’?

### ISSUE THREAD

**Issue by walkTtalk** [ZLMediaKit/ZLMediaKit#2977]
CMakeCache.txt已上传

```
X509_up_ref’ was not declared in this scope; did you mean ‘X509_free
```

<details>
<pre>
<summary>rror: ‘X509_up_ref’ was not declared in this scope; did you mean ‘X509_free’?
  303 |         X509_up_ref(certificate);
      |         ^~~~~~~~~~~
      |         X509_free
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp:309:9: error: ‘EVP_PKEY_up_ref’ was not declared in this scope; did you mean ‘EC_KEY_up_ref’?
  309 |         EVP_PKEY_up_ref(privateKey);
      |         ^~~~~~~~~~~~~~~
      |         EC_KEY_up_ref
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp: In constructor ‘RTC::DtlsTransport::DtlsTransport(toolkit::EventPoller::Ptr, RTC::DtlsTransport::Listener*)’:
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp:560:9: error: ‘DTLS_set_timer_cb’ was not declared in this scope
  560 |         DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
      |         ^~~~~~~~~~~~~~~~~
gmake[3]: *** [webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o] Error 1
gmake[3]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'
gmake[2]: *** [webrtc/CMakeFiles/webrtc.dir/all] Error 2
gmake[2]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'
gmake[1]: *** [server/CMakeFiles/MediaServer.dir/rule] Error 2
gmake[1]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'</summary>
<pre>

</pre>
</details>

#### openssl version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Sat Nov 11 14:22:53 2023 UTC
platform: linux-x86_64

#### gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/9.5.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure -enable-checking=release -enable-languages=c,c++ -disable-multilib
Thread model: posix
gcc version 9.5.0 (GCC)

### libsrtp-2.3.0版本

[CMakeCache.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/13335604/CMakeCache.txt)

**Comment by walkTtalk** [comment]
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp: In member function ‘bool RTC::DtlsTransport::DtlsEnvironment::ReadCertificateAndPrivateKeyFromContext(SSL_CTX*)’:
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp:303:9: error: ‘X509_up_ref’ was not declared in this scope; did you mean ‘X509_free’?
  303 |         X509_up_ref(certificate);
      |         ^~~~~~~~~~~
      |         X509_free
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp:309:9: error: ‘EVP_PKEY_up_ref’ was not declared in this scope; did you mean ‘EC_KEY_up_ref’?
  309 |         EVP_PKEY_up_ref(privateKey);
      |         ^~~~~~~~~~~~~~~
      |         EC_KEY_up_ref
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp: In constructor ‘RTC::DtlsTransport::DtlsTransport(toolkit::EventPoller::Ptr, RTC::DtlsTransport::Listener*)’:
/home/admin/codesource/zlm231113/ZLMediaKit/webrtc/DtlsTransport.cpp:560:9: error: ‘DTLS_set_timer_cb’ was not declared in this scope
  560 |         DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
      |         ^~~~~~~~~~~~~~~~~
gmake[3]: *** [webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o] Error 1
gmake[3]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'
gmake[2]: *** [webrtc/CMakeFiles/webrtc.dir/all] Error 2
gmake[2]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'
gmake[1]: *** [server/CMakeFiles/MediaServer.dir/rule] Error 2
gmake[1]: Leaving directory `/home/admin/codesource/zlm231113/ZLMediaKit/build'
gmake: *** [MediaServer] Error 2

**Comment by walkTtalk** [comment]
openssl version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Sat Nov 11 14:22:53 2023 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/openssl"
ENGINESDIR: "/usr/local/openssl/lib/engines-1.1"
Seeding source: os-specific

是这个问题吗？
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/20769982/a5355985-db4d-4654-967c-db9ae704ac6e)

**Comment by walkTtalk** [comment]
系统openssl输入是1.1.1k，/usr/bin/openssl 是1.0.2k。应该是这个问题了。我再重新编译一下。 

/usr/bin/openssl version -a
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,16,int) idea(int) blowfish(idx)
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  rdrand dynamic

**Comment by walkTtalk** [comment]
/usr/bin/openssl version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Sat Nov 11 14:22:53 2023 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/openssl"
ENGINESDIR: "/usr/local/openssl/lib/engines-1.1

----------------------------------------------------------------
 openssl version -a
OpenSSL 1.1.1k  25 Mar 2021
built on: Sat Nov 11 14:22:53 2023 UTC
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(int) idea(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG
OPENSSLDIR: "/usr/local/openssl"
ENGINESDIR: "/usr/local/openssl/lib/engines-1.1"

----------------------------------------------------------------
还是报错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/20769982/848a6bdb-e056-42ae-906c-87effb74fbd8)

**Comment by walkTtalk** [comment]
cmake .. -DENABLE_WEBRTC=true  -DOPENSSL_ROOT_DIR=/usr/local/openssl  -DOPENSSL_LIBRARIES=/usr/local/openssl/lib

这个指定的libraries也是我安装的位置呀。

**Comment by walkTtalk** [comment]
采纳  #2607 的建议，还是不行，报错。之前一直是这样安装openssl，没出现过这样的问题，是最近代码改动了什么吗。
export OPENSSL_ROOT_DIR=/usr/local/openssl
export OPENSSL_LIBRARIES=/usr/local/openssl/lib

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/20769982/0b59f006-0fc2-4c7b-9859-e093ab7a5905)

**Comment by walkTtalk** [comment]
执行到这一步报错。
[ 87%] Building CXX object webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o
cd /home/admin/codesource/zlm231116/ZLMediaKit/build/webrtc && /usr/local/bin/c++ -DENABLE_HLS -DENABLE_HLS_FMP4 -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/usr/local/openssl/include -I/home/admin/codesource/zlm231116/ZLMediaKit/build -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart -I/home/admin/codesource/zlm231116/ZLMediaKit/webrtc -I/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/.. -I/home/admin/codesource/zlm231116/ZLMediaKit/src -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart/jsoncpp/include -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart/media-server/libflv/include -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart/media-server/libmov/include -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/home/admin/codesource/zlm231116/ZLMediaKit/3rdpart/ZLToolKit/src -g -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -std=gnu++11 -MD -MT webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o -MF CMakeFiles/webrtc.dir/DtlsTransport.cpp.o.d -o CMakeFiles/webrtc.dir/DtlsTransport.cpp.o -c /home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp
/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp: In member function ‘bool RTC::DtlsTransport::DtlsEnvironment::ReadCertificateAndPrivateKeyFromContext(SSL_CTX*)’:
/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp:303:9: error: ‘X509_up_ref’ was not declared in this scope; did you mean ‘X509_free’?
  303 |         X509_up_ref(certificate);
      |         ^~~~~~~~~~~
      |         X509_free
/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp:309:9: error: ‘EVP_PKEY_up_ref’ was not declared in this scope; did you mean ‘EC_KEY_up_ref’?
  309 |         EVP_PKEY_up_ref(privateKey);
      |         ^~~~~~~~~~~~~~~
      |         EC_KEY_up_ref
/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp: In constructor ‘RTC::DtlsTransport::DtlsTransport(toolkit::EventPoller::Ptr, RTC::DtlsTransport::Listener*)’:
/home/admin/codesource/zlm231116/ZLMediaKit/webrtc/DtlsTransport.cpp:560:9: error: ‘DTLS_set_timer_cb’ was not declared in this scope
  560 |         DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
      |         ^~~~~~~~~~~~~~~~~
gmake[3]: *** [webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o] Error 1
gmake[3]: Leaving directory `/home/admin/codesource/zlm231116/ZLMediaKit/build'
gmake[2]: *** [webrtc/CMakeFiles/webrtc.dir/all] Error 2
gmake[2]: Leaving directory `/home/admin/codesource/zlm231116/ZLMediaKit/build'
gmake[1]: *** [server/CMakeFiles/MediaServer.dir/rule] Error 2
gmake[1]: Leaving directory `/home/admin/codesource/zlm231116/ZLMediaKit/build'
gmake: *** [MediaServer] Error 2

**Comment by xiongguangjie** [comment]
你的openssl 版本不对

**Comment by walkTtalk** [comment]
> 你的openssl 版本不对

//Path to a library.
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/local/openssl/lib/libcrypto.so

//Path to a file.
OPENSSL_INCLUDE_DIR:PATH=/usr/local/openssl/include

//No help, variable specified on the command line.
OPENSSL_LIBRARIES:UNINITIALIZED=/usr/local/openssl/lib

//No help, variable specified on the command line.
OPENSSL_ROOT_DIR:UNINITIALIZED=/usr/local/openssl

//Path to a library.
pkgcfg_lib__OPENSSL_crypto:FILEPATH=/usr/lib64/libcrypto.so

//Path to a library.
pkgcfg_lib__OPENSSL_ssl:FILEPATH=/usr/lib64/libssl.so


我看了这几个引用的都软连接新版本了呀。程序中是哪个变量决定着openssl版本库呀

**Comment by xia-chu** [comment]
![图片](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/4ad7ce5a-d4d6-4db4-a9fe-096b7083aeed)

**Comment by walkTtalk** [comment]
> ![图片](https://user-images.githubusercontent.com/11495632/283372291-4ad7ce5a-d4d6-4db4-a9fe-096b7083aeed.png)

谢谢作者回复，是我的openssl相关问题。openssl安装和版本没有问题。应该是后来安装的openssl-devel这个问题，导致cmake调用的是openssl-devel库。猜测是这样的。因为后来我重装系统没有安装openssl-devel就可以正常编译了。openssl-devel(1.0.2k)
