### ISSUE TITLE
[技术咨询] 如何将zlm已经录制完成的HLS加载成媒体源，供RTSP等协议使用？

### ISSUE THREAD

**Issue by zfjia** [ZLMediaKit/ZLMediaKit#2980]
**已有HLS的使用问题**
- 通过ZLM已经将前端设备的媒体录制成HLS-TS的方式，在本机的www/live目录下，可通过http-hls协议获取和点播；

**历史数据注册成source供二次使用**
- 现在有些场景需要将历史数据作为新的rtsp资源供外部用户访问，请问如何操作？现有zlm实现是否能够通过配置就可支持？还是需要二次开发才能完成？
- 目前尝试的方式：通过proxyplayer，从本地zlm拉取hls，再发布成一个media，然后供外部使用。但感觉这样有点太浪费资源了。有没有更好的方法？
- 可否采用类似MP4的方式，创建一个本地的基于HLS的源？

**注意事项**
- 已经阅读过wiki和相关issue，未找到相应的解决办法，还望回复。

**Comment by xia-chu** [comment]
这个不打算支持 既然已经录制成hls了 那么就建议直接hls播放。
如果想支持rtsp 那么可以先用ffmpeg转换成mp4。

文件点播是个很细分的领域 zlm主要精力不在这。

**Comment by zfjia** [comment]
感谢您的回复，让我了解到zlm的定位。
如果实现的话，能够给一个建议或思路指导，多谢多谢。

**Comment by xia-chu** [comment]
> 感谢您的回复，让我了解到zlm的定位。 如果实现的话，能够给一个建议或思路指导，多谢多谢。

ZLMediakit中其实有完整的hls播放器 这个改改就可以读本地hls文件了 代码在HlsPlayer这个对象
不过一般人估计改不动

**Comment by zfjia** [comment]
多谢指点，我去研究研究HlsPlayer。
        
            
        
    
    
    

    

        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年11月21日 10:48
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ZLMediaKit/ZLMediaKit] [技术咨询] 如何将zlm已经录制完成的HLS加载成媒体源，供RTSP等协议使用？ (Issue #2980)
        
      
    
  


感谢您的回复，让我了解到zlm的定位。 如果实现的话，能够给一个建议或思路指导，多谢多谢。

ZLMediakit中其实有完整的hls播放器 这个改改就可以读本地hls文件了 代码在HlsPlayer这个对象
不过一般人估计改不动
