### ISSUE TITLE
Streams being closed from no viewers

### ISSUE THREAD

**Issue by Fummowo** [ZLMediaKit/ZLMediaKit#2981]
Hiya,

I am trying to use ZLMediaKit to serve livestreams into the game VRChat, it works perfectly providing RTMP with OBS and serving HTTP-TS for PC and Quest platforms, and RTSP for lower latency 720p 30fps to PC!

However, I initially thought I was having trouble streaming to ZLMediaKit from Ffmpeg, but it turns out my ZLMediaKit docker container is closing all connections it's receiving and its relating back to `general.streamNoneReaderDelayMS` for some reason.

If I set it to `0` it closes all incoming streams immediately and if I set it to `100000` it will close after 100 seconds of no viewers.
I also have `auto_close=0` which should mean it doesn't close it right?

<details>
<summary>Here is a log of it happening: (with blurred ip)</summary>
<pre>
2023-11-14 13:53:22.264 I [MediaServer] [1-MediaServer] main.cpp:439 start_main | 程序退出中,请等待...
2023-11-14 13:53:23.264 I [MediaServer] [1-MediaServer] main.cpp:441 start_main | 程序退出完毕!
2023-11-14 13:53:23.265 I [MediaServer] [1-MediaServer] EventPoller.cpp:98 ~EventPoller | 0xffffa00dbe40
2023-11-14 13:53:23.265 I [MediaServer] [1-MediaServer] EventPoller.cpp:98 ~EventPoller | 0xffffa0085a00
2023-11-14 13:53:23.266 T [MediaServer] [1-MediaServer] TcpClient.cpp:28 ~TcpClient | ~mediakit::HttpRequester-1
2023-11-14 13:53:23.266 I [MediaServer] [1-MediaServer] EventPoller.cpp:98 ~EventPoller | 0xaaaafef21b10
2023-11-14 13:53:23.267 I [MediaServer] [1-MediaServer] EventPoller.cpp:98 ~EventPoller | 0xaaaafef21fe0
2023-11-14 13:53:23.269 I [MediaServer] [1-MediaServer] logger.cpp:86 ~Logger | 
2023-11-14 13:53:23.889 I [MediaServer] [1-MediaServer] System.cpp:177 systemSetup | core文件大小设置为:18446744073709551615
2023-11-14 13:53:23.889 I [MediaServer] [1-MediaServer] System.cpp:186 systemSetup | 文件最大描述符个数设置为:1048576
2023-11-14 13:53:23.889 I [MediaServer] [1-MediaServer] main.cpp:261 start_main | ZLMediaKit(git hash:d2374cb/2023-11-13T10:27:59+08:00,branch:master,build time:2023-11-13T04:10:56)
2023-11-14 13:53:23.893 D [MediaServer] [1-MediaServer] SSLBox.cpp:174 setContext | Add certificate of: default.zlmediakit.com
2023-11-14 13:53:23.893 D [MediaServer] [1-stamp thread] util.cpp:366 operator() | Stamp thread started
2023-11-14 13:53:23.893 I [MediaServer] [1-MediaServer] EventPoller.cpp:476 EventPollerPool | EventPoller created size: 2
2023-11-14 13:53:23.894 I [MediaServer] [1-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 554
2023-11-14 13:53:23.894 I [MediaServer] [1-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 1935
2023-11-14 13:53:23.894 I [MediaServer] [1-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 8080
2023-11-14 13:53:23.895 I [MediaServer] [1-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 10000
2023-11-14 13:53:23.895 I [MediaServer] [1-MediaServer] UdpServer.cpp:118 start_l | UDP server bind to [::]: 10000
2023-11-14 13:53:23.896 I [MediaServer] [1-MediaServer] UdpServer.cpp:118 start_l | UDP server bind to [::]: 8000
2023-11-14 13:53:23.896 I [MediaServer] [1-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 8000
2023-11-14 13:53:23.896 I [MediaServer] [1-MediaServer] UdpServer.cpp:118 start_l | UDP server bind to [::]: 9000
2023-11-14 13:53:23.897 I [MediaServer] [1-MediaServer] main.cpp:411 start_main | 已启动http api 接口
2023-11-14 13:53:23.898 I [MediaServer] [1-MediaServer] main.cpp:413 start_main | 已启动http hook 接口
2023-11-14 13:54:06.963 T [MediaServer] [1-event poller 0] TcpServer.h:54 operator() | 1-15(xxx.xxx.xxx.xxx:63060) mediakit::RtmpSession
2023-11-14 13:54:06.997 T [MediaServer] [1-event poller 0] RtmpProtocol.cpp:688 handle_chunk | MSG_SET_CHUNK:4096
2023-11-14 13:54:07.084 D [MediaServer] [1-event poller 0] RtmpSession.cpp:130 operator() | 1-15(xxx.xxx.xxx.xxx:63060) publish 回复时间:2ms
2023-11-14 13:54:08.191 I [MediaServer] [1-event poller 0] MediaSource.cpp:503 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/fummo
2023-11-14 13:54:08.191 T [MediaServer] [1-event poller 0] TcpServer.cpp:173 operator() | 1-15(xxx.xxx.xxx.xxx:63060) mediakit::RtmpSession on err: 5(close media: rtmp://__defaultVhost__/live/fummo)
2023-11-14 13:54:08.191 W [MediaServer] [1-event poller 0] RtmpSession.cpp:30 onError | 1-15(xxx.xxx.xxx.xxx:63060) RTMP推流器(__defaultVhost__/live/fummo)断开:close media: rtmp://__defaultVhost__/live/fummo,耗时(s):1
2023-11-14 13:54:08.191 T [MediaServer] [1-event poller 0] TcpServer.h:51 operator() | 1-15(xxx.xxx.xxx.xxx:63060) ~mediakit::RtmpSession
2023-11-14 13:54:08.192 W [MediaServer] [1-event poller 0] WebHook.cpp:583 operator() | 无人观看主动关闭流:rtmp://__defaultVhost__/live/fummo
2023-11-14 13:54:08.192 I [MediaServer] [1-event poller 0] MediaSource.cpp:503 emitEvent | 媒体注销:rtmp://__defaultVhost__/live/fummo
</pre>
</details>

<details>
<summary>my conf/config.ini</summary>
<pre>
#!!!!This configuration file is a sample configuration file, intended to tell readers, The specific meaning and function of each configuration item,
#!!!!When cmake is executed, this configuration file will be copied to the release/${operating system type}/${compilation type} (for example, release/linux/Debug) folder.
#!!!!This folder (release/${operating system type}/${compilation type}) is also the target path for executable program generation. When executing the MediaServer process, it will load the config.ini file in the same directory as the configuration file by default.
#!!!!If you modify this sample configuration file (conf/config.ini), it will not be loaded by the MediaServer process, because the MediaServer process loads release/${operating system type}/${compilation type}/config.ini by default.
#!!!!Of course, every time you execute cmake, the file will indeed be copied to release/${operating system type}/${compilation type}/config.ini ,
#!!!!However, it is generally recommended that you directly modify the release/${operating system type}/${compilation type}/config.ini file. Modifying this file generally has no effect unless you use the -c parameter to specify this file when running MediaServer.

[api]
#Whether to debug the http api. After debugging is enabled, the content and reply of each http request will be printed.
apiDebug=1
#Some more sensitive http apis need to provide secrets when accessing, otherwise they will not have permission to call
#If access is through 127.0.0.1, then the secret does not need to be provided.
secret=################################
#The screenshot is saved in the root directory of the path. The screenshot is generated and obtained through http api (/index/api/getSnap)
snapRoot=./www/snap/
#Default screenshot image. After starting FFmpeg to take a screenshot but before the screenshot is generated, you can return to the default preset image.
defaultSnap=./www/logo.png

[ffmpeg]
#FFmpeg executable program path, supports relative path/absolute path
bin=/usr/bin/ffmpeg
#FFmpeg command template for pulling and pushing streams. Through this template, you can set some parameters for re-encoding.FFmpeg command template for pulling and pushing streams. Through this template, you can set some parameters for re-encoding.
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
#FFmpeg's command to generate screenshots. You can change the screenshot resolution or quality by modifying the configuration.
snap=%s -i %s -y -f mjpeg -frames:v 1 %s
#The path of the FFmpeg log. If left blank, no FFmpeg log will be generated.
#Can be a relative (relative to the executable program directory) or absolute path
log=./ffmpeg/ffmpeg.log
#Automatic restart time (seconds), the default is 0, which means no automatic restart. This is mainly to avoid the out-of-sync phenomenon caused by long-term ffmpeg streaming.
restart_sec=0

#Conversion protocol related switches; if the addStreamProxy api and on_publish hook replies do not specify the conversion protocol parameters, these configuration items will be used
[protocol]
#Whether to enable frame-level timestamp coverage when switching protocols
# 0: Use the absolute timestamp of the source video stream without making any changes.
# 1: System timestamp when receiving data using zlmediakit (with smoothing)
# 2: Use the relative timestamp (increase amount) of the source video stream timestamp, and perform timestamp jump and rollback correction.
modify_stamp=0
#Whether to enable audio in the transfer protocol
enable_audio=1
#Add acc to mute audio. This switch has no effect when the audio is turned off.
add_mute_audio=1
#When no one is watching, whether to close directly (instead of on_none_reader passing hook, it returns close)
#When this configuration is set to 1, if no one is watching this stream, the on_none_reader hook callback will not be triggered.
#Instead, the stream will be closed directly
auto_close=0

#After the push stream is disconnected, you can reconnect within the timeout period and continue to push the stream, so that the player will continue to play.
#Set to 0 to turn off this feature (disconnection of the push stream will cause the player to be disconnected immediately)
#This parameter should not be greater than the player timeout; unit is milliseconds
continue_push_ms=15000

#Whether to enable conversion to hls(mpegts)
enable_hls=0
#Whether to enable conversion to hls(fmp4)
enable_hls_fmp4=0
#Whether to enable MP4 recording
enable_mp4=0
#Whether to enable conversion to rtsp/webrtc
enable_rtsp=1
#Whether to enable conversion to rtmp/flv
enable_rtmp=1
#Whether to enable conversion to http-ts/ws-ts
enable_ts=1
#Whether to enable conversion to http-fmp4/ws-fmp4
enable_fmp4=0

#Whether to treat mp4 recording as a viewer
mp4_as_player=0
#MP4 slice size in seconds
mp4_max_second=3600
#MP4 recording save path
mp4_save_path=./www

#hls recording save path
hls_save_path=./www

###### If you want to get the best user experience for a certain protocol, please set it to 0 (the first player can start in seconds without screen lag)
#Whether the hls protocol is generated on demand. If hls.segNum is configured as 0 (meaning hls recording), then hls will always be generated (regardless of this switch)
hls_demand=0
#Whether the rtsp[s] protocol is generated on demand
rtsp_demand=0
#Whether the rtmp[s], http[s]-flv, and ws[s]-flv protocols are generated on demand
rtmp_demand=0
#Whether the http[s]-ts protocol is generated on demand
ts_demand=0
#Whether the http[s]-fmp4 and ws[s]-fmp4 protocols are generated on demand
fmp4_demand=0

[general]
#Whether to enable virtual host
enableVhost=0
#The player or pusher will trigger the hook.on_flow_report event (how much traffic event is used) after disconnection.
#The flowThreshold parameter controls the threshold for triggering the hook.on_flow_report event. It is triggered only after the traffic exceeds the threshold. The unit is KB.
flowThreshold=1024
#The maximum waiting time for playback, in milliseconds
#Play When playing a stream, if the stream does not exist,
#ZLMediaKit will make the player wait up to maxStreamWaitMS milliseconds
#If the stream is successfully registered within this time, it will immediately return to the player to play successfully.
#Otherwise, it returns that the player has not found the stream. The purpose of this mechanism is to play it first and then push the stream.
maxStreamWaitMS=15000
#When no one is watching a stream, the maximum waiting time for triggering the hook.on_stream_none_reader event, in milliseconds
#When cooperating with the hook.on_stream_none_reader event, you can automatically stop pulling streams or stop receiving push streams when no one is watching.
streamNoneReaderDelayMS=0
#When pulling the streaming agent, if the stream is disconnected and reconnected successfully, whether to delete the previous media stream data? If deleted, it will start again.
#If you do not delete it, it will continue to write after the last data (when recording hls/mp4, it will continue to write after the previous file)
resetWhenRePlay=1
#Combined write cache size (unit: milliseconds). Combined write means that the server caches a certain amount of data before writing to the socket at once. This can improve performance, but will increase latency.
#When enabled, TCP_NODELAY will be turned off and MSG_MORE will be turned on at the same time.
mergeWriteMS=0
#The unique ID of the server, used to distinguish which server it is when triggering the hook.
mediaServerId=your_server_id

#The maximum waiting time for uninitialized tracks, in milliseconds. After timeout, uninitialized tracks will be ignored.
wait_track_ready_ms=10000
#If the stream has only a single Track, wait up to a few milliseconds. If no data from other Tracks is received after the timeout, it is considered to be a single Track.
#If the protocol metadata declares a specific track number, there is no such waiting time.
wait_add_track_ms=3000
#If the track is not ready, we cache the frame data first, but there is a maximum number limit to prevent memory overflow.
unready_frame_cache=100

[hls]
#HLS writes the buf size of the file. Adjusting the parameters can improve the file io performance.
fileBufSize=65536
#hls maximum slicing time
segDur=2
#In the m3u8 index, the number of slices retained by hls (the actual number of retained slices is 2~3 larger)
#If set to 0, the slice is not deleted but saved as on-demand
segNum=3
#The number of HLS slices that remain on the disk after they are removed from the m3u8 file
segRetain=5
#Whether to broadcast hls slice (ts/fmp4) completion notification (on_record_ts)
broadcastRecordTs=0
#Live hls file deletion delay, unit seconds, issue: #913
deleteDelaySec=10
#Whether to retain the hls file, this function is partially equivalent to the case of segNum=0
#The difference is that this reservation will not be reflected in the m3u8 file
#0 means not reserved and has no effect.
#1 is reserved, the hls file will not be deleted. If this function is turned on, pay attention to the disk size, or manually clean the hls file regularly.
segKeep=0

[hook]
#Whether to enable hook events. After enabling, both push and pull flows will be authenticated.
enable=0
#The player or streamer uses traffic events. If left blank, it will be closed.
on_flow_report=https://127.0.0.1/index/hook/on_flow_report
#Access http file authentication event. If left blank, authentication will be turned off.
on_http_access=https://127.0.0.1/index/hook/on_http_access
#Play the authentication event, leave it blank to close the authentication
on_play=https://127.0.0.1/index/hook/on_play
#Push the authentication event. If left blank, the authentication will be closed.
on_publish=https://127.0.0.1/index/hook/on_publish
#Record mp4 slice completion event
on_record_mp4=https://127.0.0.1/index/hook/on_record_mp4
# Record hls ts (or fmp4) slice completion event
on_record_ts=https://127.0.0.1/index/hook/on_record_ts
#rtsp playback authentication event. In this event, the user name and password of rtsp are compared.
on_rtsp_auth=https://127.0.0.1/index/hook/on_rtsp_auth
#Whether to enable exclusive authentication events for rtsp playback. If left blank, rtsp authentication will be turned off. RTSP playback authentication also supports URL authentication.
#It is recommended that developers uniformly use url parameter authentication. RTSP username and password authentication is generally used on devices.
#After rtsp exclusive authentication is enabled, the on_play authentication event will no longer be triggered.
on_rtsp_realm=https://127.0.0.1/index/hook/on_rtsp_realm
#Remote telnet debugging authentication events
on_shell_login=https://127.0.0.1/index/hook/on_shell_login
#Live stream registration or logout event
on_stream_changed=https://127.0.0.1/index/hook/on_stream_changed
#Filter the protocol type of on_stream_changed hook. You can choose to only listen to certain protocols of interest; leave it blank to not filter the protocol.
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
#Unwatched stream event, through which you can choose whether to close the unwatched stream. Used with general.streamNoneReaderDelayMS option
on_stream_none_reader=https://127.0.0.1/index/hook/on_stream_none_reader
#During playback, no stream event was found. By cooperating with the hook.on_stream_none_reader event, on-demand streaming can be completed.
on_stream_not_found=https://127.0.0.1/index/hook/on_stream_not_found
#Server startup report, which can be used to monitor server crash and restart events.
on_server_started=https://127.0.0.1/index/hook/on_server_started
#Server exit report, triggered when the server exits normally
on_server_exited=https://127.0.0.1/index/hook/on_server_exited
#Server keep-alive reporting
on_server_keepalive=https://127.0.0.1/index/hook/on_server_keepalive
#Callback when sending rtp (startSendRtp) is passively closed
on_send_rtp_stopped=https://127.0.0.1/index/hook/on_send_rtp_stopped
#rtp server timed out and did not receive data
on_rtp_server_timeout=https://127.0.0.1/index/hook/on_rtp_server_timeout

#Maximum waiting time for hook api reply, in seconds
timeoutSec=10
#Keepalive hook trigger interval, unit seconds, float type
alive_interval=10.0
#The number of hook notification failure retries, a positive integer. If it is 0, it will not retry, if it is 1, it will try again, and so on.
retry=1
#Hook notification failure retry delay, unit seconds, float type
retry_delay=3.0

[cluster]
#Set the source site pull URL template. The format is similar to printf. The first %s specifies app, and the second %s specifies stream_id.
#After turning on cluster mode, on_stream_not_found and on_stream_none_reader hooks will be invalid.
#Traceability mode supports the following types:
#rtmp mode: rtmp://127.0.0.1:1935/%s/%s
#rtsp mode: rtsp://127.0.0.1:554/%s/%s
#hls mode: http://127.0.0.1:80/%s/%s/hls.m3u8
#http-ts mode: http://127.0.0.1:80/%s/%s.live.ts
#Supports multiple origin sites. Different origin sites are separated by semicolon (;)
origin_url=rtmp://uk.example.com:1935/%s/%s;rtmp://us.example.com:1935/%s/%s
#Total traceability timeout, unit second, float type; if there are 3 origin sites, then the single traceability timeout is timeout_sec divided by 3
#The single traceability timeout should not exceed the general.maxStreamWaitMS configuration
timeout_sec=15
#The number of failed attempts to trace the origin. If it is -1, it will be tried permanently.
retry_count=3

[http]
#http server character encoding, default gb2312 on windows
charSet=utf-8
#http link timeout
keepAliveSecond=30
#The maximum number of bytes in the http request body. If the body of the post is too large, it is not suitable for caching the body in memory.
maxReqSize=40960
#404 web page content, users can customize the 404 web page
#notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>The resource you accessed does not exist! </h1></center><hr><center>ZLMediaKit-4.0</center></body></html>
#http server listening port
port=8080
#http file server root directory
#Can be a relative (relative to the executable program directory) or absolute path
rootPath=./www
#HTTP file server read file cache size, unit BYTE, adjusting this parameter can optimize file IO performance
sendBufSize=65536
#https server listening port
sslport=0
#Whether to display the folder menu. When enabled, you can browse the folder.
dirMenu=1
#Virtual directory, virtual directory name and file path are separated by ",", multiple configuration paths are separated by ";"
#For example, the assignment is app_a,/path/to/a;app_b,/path/to/b then
#Visit http://127.0.0.1/app_a/file_a and the corresponding file path is /path/to/a/file_a
#Visit http://127.0.0.1/app_b/file_b and the corresponding file path is /path/to/b/file_b
#When accessing other http paths, the corresponding file path is still in the rootPath.
virtualPath=
#Disable files with suffixes from using mmap cache and separate them with ","
#For example, the assignment is .mp4,.flv
#Then accessing files with the suffix .mp4 and .flv will not be cached
forbidCacheSuffix=
#You can put the real client IP before the http proxy in the http header：https://github.com/ZLMediaKit/ZLMediaKit/issues/1388
#Do not expose this key, otherwise it may lead to forged client IP
forwarded_ip_header=
#Allow all cross-domain requests by default
allow_cross_domains=1
#A whitelist of IP address ranges that allow access to http api and http file index. If left blank, there will be no restriction.
allow_ip_range=::1,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255

[multicast]
#rtp multicast cutoff multicast ip address
addrMax=239.255.255.255
#rtp multicast starting multicast ip address
addrMin=239.0.0.0
#multicast udp ttl
udpTTL=64

[record]
#The application name of mp4 recording or mp4 on-demand. By restricting the application name, you can prevent arbitrary on-demand playback.
#On-demand files must be placed in this folder
appName=record
#MP4 recording and writing file cache, unit BYTE, adjusting parameters can improve file io performance
fileBufSize=65536
#The amount of data streamed each time mp4 on demand is played, in milliseconds.
#Reducing this value can make on-demand data transmission smoother, and increasing this value can save more CPU resources.
sampleMS=500
#Whether to write the secondary keyframe index into the header after mp4 recording is completed
fastStart=0
#Whether MP4 on-demand (rtsp/rtmp/http-flv/ws-flv) plays files in a loop
fileRepeat=0

[rtmp]
#rtmp must complete the handshake within this time, otherwise the server will disconnect, in seconds
handshakeSecond=15
#rtmp timeout time, if no data from the client is received within this time,
#Or the tcp sending cache exceeds this time, the connection will be disconnected, in seconds
keepAliveSecond=15
#rtmp server listening port
port=1935
#rtmps server listening address
sslport=0

[rtp]
#Audio mtu size, this parameter limits the maximum number of bytes of rtp, it is recommended not to exceed 1400
#Increasing this value will significantly increase the live broadcast delay
audioMtuSize=600
#Video mtu size, this parameter limits the maximum number of bytes of rtp, it is recommended not to exceed 1400
videoMtuSize=1400
#The maximum length limit of rtp packet, unit KB, mainly used to identify the wrong rtp when the TCP context is destroyed.
rtpMaxSize=10
# When rtp is packaged, the low-latency switch is turned off by default (0). There are multiple slices (NAL) in one frame in h264. In this case, if it is turned on, it may cause the screen to blur.
lowLatency=0
# Whether the H264 rtp packaging mode uses stap-a mode (for compatibility with webrtc on older browsers) or Single NAL unit packet per H.264 mode
# Some old rtsp devices do not support stap-a rtp. Setting this configuration to 0 can improve compatibility.
h264_stap_a=1

[rtp_proxy]
#Export debugging data (including rtp/ps/h264) to this directory. Leave it blank to close data export.
dumpDir=
#udp and tcp proxy server, supports rtp (must be ts or ps type) proxy
port=10000
#rtp timeout time in seconds
timeoutSec=15
#Random port range, ensuring at least 36 ports
#This range also limits the rtsp server udp port range
port_range=30000-35000
#rtp h264 loaded pt
h264_pt=98
#rtp h265 loaded pt
h265_pt=99
#rtp ps loaded pt
ps_pt=96
#rtp opus loaded pt
opus_pt=100
#Whether RtpSender related functions are turned on in advance gop cache optimization cascading instant opening experience, enabled by default
#If you do not call the startSendRtp related interface, you can set it to 0 to save memory.
gop_cache=1

[rtc]
#RTC playback push stream, playback timeout
timeoutSec=15
#The visible ip of this machine to the rtc client is usually a public network ip when used as a server. There can be multiple, separated by ','. When left blank, the network card ip will be automatically obtained.
#It also supports environment variables, starting with $, such as "$EXTERN_IP"; please refer to: https://github.com/ZLMediaKit/ZLMediaKit/pull/1786
externIP=
#The rtc udp server listens to the port number, and all rtc clients will transmit stun/dtls/srtp/srtcp data through this port.
#This port is multi-threaded and supports connection migration caused by client network switching.
#It should be noted that if the server is in NAT and port mapping needs to be done, you must ensure that the external network mapped port is consistent with the port.
port=8000
#The rtc tcp server monitors the port number. If udp fails, tcp will be used to transmit data.
#This port is multi-threaded and supports connection migration caused by client network switching.
#It should be noted that if the server is in NAT and port mapping needs to be done, you must ensure that the external network mapped port is consistent with the port.
tcpPort = 8000
#Set the remb bit rate. If it is not 0, close twcc and enable remb. This setting is valid when rtc is pushed and can control the quality of the push.
#At present, twcc has been implemented to automatically adjust the bit rate, and remb is turned off to adjust the bit rate according to the real network conditions.
rembBitRate=0
#The audio codec types supported by rtc have higher priority in the front.
#The following examples are for all supported audio codecs
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
#The video codec types supported by rtc have higher priority in the front.
#The following examples are for all supported video codecs
preferredCodecV=H264,H265,AV1,VP9,VP8

[srt]
#srt playback push and playback timeout, unit seconds
timeoutSec=5
#The srt udp server listens to the port number, and all srt clients will transmit srt data through this port.
#This port is multi-threaded and supports connection migration caused by client network switching.
port=9000
#srt is the estimated parameter of latency cache in the protocol. RTT is estimated during the handshake phase, and latencyMul*rtt is the maximum cache duration. The larger this parameter is, the longer the waiting time for retransmission is.
latencyMul=4
#Packet cache size
pktBufSize=8192

[rtsp]
#Is the rtsp proprietary authentication method using base64 or md5?
authBasic=0
#Is the rtsp pull and push proxy in direct proxy mode?
#Supports any encoding format after direct proxying, but it will cause the GOP cache to be unable to locate the I frame, which may lead to blurred playback.
#And if the stream is pulled in tcp mode, if the rtp is larger than the mtu, the udp mode proxy cannot be used.
#Assuming that your streaming source address is not 264 or 265 or AAC, you can use direct proxy to support rtsp proxy
#If you are using rtsp push-pull streaming but playing webrtc, it is also recommended to turn off the direct proxy mode.
#Because when directly proxying, there may be no sps pps in the rtp, which will cause webrtc to be unable to play; in addition, webrtc does not support Single NAL Unit Packets type rtp.
#The rtsp direct proxy is enabled by default. Since rtmp does not have these problems, the direct proxy is forced to be enabled.
directProxy=0
#rtsp must complete the handshake within this time, otherwise the server will disconnect, unit seconds
handshakeSecond=15
#rtsp timeout time, if no data from the client is received within this time,
#Or the tcp sending cache exceeds this time, the connection will be disconnected, in seconds
keepAliveSecond=15
#rtsp server listening address
port=554
#rtsps server listening address
sslport=0
#Whether rtsp forwarding uses low-latency mode. When enabled, rtp packets will not be cached to improve concurrency and reduce the delay of one frame.
lowLatency=0
#Force negotiation of rtp transmission method (0:TCP,1:UDP,2:MULTICAST,-1:no limit)
#When the client initiates RTSP SETUP, if the transport type is inconsistent with this configuration, 461 Unsupported transport will be returned.
#Force the client to re-SETUP and switch to the corresponding protocol. Currently supports FFMPEG and VLC
rtpTransportType=0
[shell]
#Debugging the maximum buffer size received by the telnet server
maxReqSize=1024
#Debugging telnet server listening port
port=0

</pre>
</details>

Any help would be appreciated! :))

**Comment by xia-chu** [comment]
Yes, if you set `auto_close=0`, zlmediakit will not close streams when none player.

Also if you set `on_none_reader` hook, zlmediakit will ask your `http api server`  whether close stream when none player or not, if your server response   `close : true`, zlmediakit will close it.

**Comment by xia-chu** [comment]
But i had checked that , you had disabled hook.

**Comment by xia-chu** [comment]
Hi, you had enabled `cluster` feature. ZLMediaKit will close any streams when none player on `edge` server.

This is a little bug, zlmediakit need close stream only proxyed from origin server.

**Comment by xia-chu** [comment]
If you enabled cluster feature, ZLMediaKit will just as a `edge media server.` Please do not push any stream to it.

**Comment by Fummowo** [comment]
Hi @xia-chu , thank you for your reply :)
I only have 2 servers in different locations for geo-balancing and was hoping I could use both as origins for inputting streams but still be able to get the same stream from either server... Is that not possible?
Would I have to employ another software like AKStream to control this behaviour and sync the stream across both my servers?

**Comment by xia-chu** [comment]
You can deploy 2 origin media servers in different locations for accept rtmp pushers.

Then  deploy 2 edge media servers on same host, and set cluster origin url for it.

**Comment by Fummowo** [comment]
Hi @xia-chu ,
Isn't that a bit wasteful of system resources to run 2 servers? And the port mapping would be messy and unwanted...
In my case, I do not require separate origin and edge servers, so it would be a nice feature for the server to be able to tell the difference between streams pushed to it, and others proxied from other servers.

> This is a little bug, zlmediakit need close stream only proxyed from origin server.
You explained this was a bug, do you believe it will be fixed?

**Comment by xia-chu** [comment]
> You explained this was a bug, do you believe it will be fixed?

Please apply this patch:
```patch
Index: server/WebHook.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/server/WebHook.cpp b/server/WebHook.cpp
--- a/server/WebHook.cpp	(revision 78456e1f55eb3e0e8f962d42b11ad5beaf3ab127)
+++ b/server/WebHook.cpp	(date 1699955472865)
@@ -577,8 +577,8 @@
     });
 
     NoticeCenter::Instance().addListener(&web_hook_tag, Broadcast::kBroadcastStreamNoneReader, [](BroadcastStreamNoneReaderArgs) {
-        if (!origin_urls.empty()) {
-            // 边沿站无人观看时立即停止溯源
+        if (!origin_urls.empty() && sender.getOriginType() == MediaOriginType::pull) {
+            // 边沿站无人观看时如果是拉流的则立即停止溯源
             sender.close(false);
             WarnL << "无人观看主动关闭流:" << sender.getOriginUrl();
             return;

```

After you tested and bug fixed, will you please submit a pull request? Thanks!

**Comment by Fummowo** [comment]
@xia-chu I have applied your patch and can confirm its functioning as intended as far as I can tell!
I have tested it on both amd64 and arm64 architectures using the docker image building script.
I have published a branch containing the patch, ready for a pull request... 
However, I don't feel too good getting credit for your code. I would be a contributor from a patch you sent...
If you don't mind then I'm okay then, I just wanted to run that by you first since all I've done is test it :)

**Comment by xia-chu** [comment]
Yes, please send us a pull request. I'm happy to have more PRs. I hope you can contribute more PRs in the future.

**Comment by Fummowo** [comment]
> I hope that in this way, I can help more developers master the skill of submitting PRs, and in the future, these people can become continuous contributors.

That's a really nice way of thinking about that :)
I would like to help with localizing to english if possible! It would help alot of others find and use this awesome software :)
I also don't know C++ or and C for a matter of fact but it would be nice to help out wherever :)

**Comment by xia-chu** [comment]
> I would like to help with localizing to english if possible

Thank you very much. Currently, zlmediakit is not doing well in internationalization. If you could join us, it would be great！
