### ISSUE TITLE
[技术咨询] 实现流中嵌入矩形框

### ISSUE THREAD

**Issue by Galaxy-Ding** [ZLMediaKit/ZLMediaKit#2986]
**咨询的功能模块**
- 推流或者拉流部分

**咨询的具体内容和问题**
- 想要再流中嵌入矩形框，或者字体，而不是再推流到前端页面再次解码，再每一帧都处理，想问下这个有办法做到吗？

**注意事项**
- 已经搜索未有相关issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
一般是在客户端（推流端或者拉流端来做的），在服务器端也能做但是需要解码->画框->编码  (这个十分消耗资源)

**Comment by Galaxy-Ding** [comment]
> 一般是在客户端（推流端或者拉流端来做的），在服务器端也能做但是需要解码->画框->编码 (这个十分消耗资源)

感谢大佬回复，我这边是在这块是个新手，就是想问下ffmpeg，可以实现这样的功能？
我在网上找到的资料：https://blog.csdn.net/weixin_43742643/article/details/114117335

有个想法是
任意格式流->zlmedia 推成 ffmpeg 再画框->zlmedia推成任意流？

**Comment by xia-chu** [comment]
处理流程应该是这样的：

ffmpeg拉流 -> 解码 -> ai处理，画框 -> 推流给zlm

这个基本跟zlm无关

**Comment by Galaxy-Ding** [comment]
> 处理流程应该是这样的：
> 
> ffmpeg拉流 -> 解码 -> ai处理，画框 -> 推流给zlm
> 
> 这个基本跟zlm无关

感谢大佬的亲自回复。
是这样的，为了适配更多流，因此才想在产品上用zlm 去拉各种流，然后想ai 处理画框，再推出任意流。

**Comment by xia-chu** [comment]
你都ai处理了 还涉及编解码 zlm剩的那点拉流开销 忽略不计了
