### ISSUE TITLE
[技术咨询] 网络IO能力优化

### ISSUE THREAD

**Issue by 286897655** [ZLMediaKit/ZLMediaKit#2989]
**咨询的功能模块**
- 网络吞吐能力

**咨询的具体内容和问题**
- 压测ZLMediakit
- 压测方式，编译成两个程序，1、streamproxy 实现功能 调用http接口拉rtsp流转成rtmp协议推送给server
-                                                 2、server 实现功能，接收rtmp流，实现其他功能，实际压测只接收了rtmp流。
- 压测环境，物理机(2cpu/18核/2超线程=72逻辑核 虚拟化的kvm虚拟机 4c/16G 虚拟机)
- rtsp流情况，2K流，8M码率。
- 压测结果描述：
- 30路-200M流量，cpu约36%，load负载良好
- 60路-500M流量，cpu约70%，load 2-5，偶尔负载会超过5
- 120路-1G流量，cpu约120%，load 4-6，长时间load过高，socket会断

问题：
最主要的问题是，cpu看起来表现良好，占用不高，4c16g 看起来处理2G流量是没有问题的，但是实际超过500M 负载就偶尔高了，1G流量这种长时间负载高的会导致socket断。问题就是cpu不高，负载高，看起来像是网络吞吐上不去？这种该怎么优化？
测试过KVM虚机开启多队列网卡，绑核，RX-queue能性能优化方式，也只能一点点提升性能，但是也只是把cpu降低了一点，实际还是这种cpu低，但是负载高。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
zlm的默认配置是最佳体验 而不是最佳性能 需要关闭些转协议 开启合并写 才能达到最高性能

**Comment by xia-chu** [comment]
另外你的局域网带宽多少呢？

**Comment by 286897655** [comment]
> zlm的默认配置是最佳体验 而不是最佳性能 需要关闭些转协议 开启合并写 才能达到最高性能

转协议都是关闭了的，只开了转rtmp，因为要推送给另一个mediaserver，另一个mediaserver在压测的时候也是没有开别的录制转协议，纯粹只是接收rtmp

局域网带宽也是没问题的，10g以上，kvm的物理机上面-vhost-net 转发的cpu也仅10%。1G流量

主要的问题是 cpu不高，top的load高

**Comment by xia-chu** [comment]
截个图看下

**Comment by 286897655** [comment]
![性能压测](https://github.com/ZLMediaKit/ZLMediaKit/assets/16201246/41bdc4c0-9c0d-4edc-a309-46065722c021)

**Comment by 286897655** [comment]
能看到图片吗？你看左下是虚拟机内部，右下是物理机上的 右上是流量，左上是sar -r 现在有点怀疑是 脏页？但是不知道是不是这个原因

**Comment by xia-chu** [comment]
可以getThreadsLoad接口访问zlm 如果负载不高 但是日志却显示send timeout 或者其他超时 则说明带宽瓶颈了

**Comment by xia-chu** [comment]
qeum不是指令集转译吗 这个会严重影响性能吧？ 我测试性能都是在物理机测试的 就是怕干扰因素

**Comment by 286897655** [comment]
> qeum不是指令集转译吗 这个会严重影响性能吧？ 我测试性能都是在物理机测试的 就是怕干扰因素

这是KVM虚拟机，KVM和QEMU配套的，同架构的cpu不转义的，速度基本没差别。靠的是cpu的虚拟化指令集支持。有一点点差距吧。
昨天也试了别的流媒体，也发现了。不论是go的，还是c++的 都有这个问题吧，小流量都不明显，流量大了，都会偶现负载比cpu高，其中srs到是cpu和load对的上，但是它跑不了多核跑不了多少流量。我现在认为 不论是go的还是zlm，毕竟本质多线程嘛，还是有锁的，会不会是流量大了，有锁的存在，导致负载和cpu对不上？毕竟也不是长时间load高，就是偶尔。但是流量越大越有长时间load高。
我昨天试了把服务器电源模式调整成performance模式，4C虚机到不会500M就偶尔负载高了，但是1G流量下也会出现偶尔负载高。
现在我们只是要一个评估下4C虚机能跑多少流量的流，所以需要负载的一个范围。

**Comment by xia-chu** [comment]
可以设置zlm的mergeWriteMS为300 这样牺牲点延时 提高性能

**Comment by 286897655** [comment]
> 可以设置zlm的mergeWriteMS为300 这样牺牲点延时 提高性能

单独测试只拉流 不发送，这个参数应该涉及不到吧，在大流量下 1G 2G就会出现这个问题。
经过验证我只用mediaserver跑拉流，不转发，同时rtmp_on_demand这些开开按需生成，这样收到数据后不需要往ringbuffer塞，就不需要经过锁了，跑了2G流量基本上cpu和负载对的上，我现在认为之前那个理论还是准确的，就是我们要生成rtmp协议之类的 就要往ringbuffer塞数据就必须要lock，这样大流量之后就会导致负载上升，阻塞的锁会导致cpu没那么高，和go用channnel传差不多吧。现在性能我觉得已经挺好了，估计还要优化就得把那个ringbuffer优化的无锁的吧，我是没那本事。。。
大佬觉得我分析的对不对？或者我对负载和cpu占用百分比的认识不正确？

**Comment by xia-chu** [comment]
这个锁我觉得粒度很低 其实影响不大的 我压测发现 这个锁不怎么影响性能 可能是你虚拟机的原因

**Comment by 286897655** [comment]
> 这个锁我觉得粒度很低 其实影响不大的 我压测发现 这个锁不怎么影响性能 可能是你虚拟机的原因

嗯 我看过那块儿代码，锁的范围已经很小了，再优化最多做成无锁数据结果，但是性能不一定好，能明白。

**Comment by 286897655** [comment]
> 这个锁我觉得粒度很低 其实影响不大的 我压测发现 这个锁不怎么影响性能 可能是你虚拟机的原因

这个问题我已经搞清楚了，linux这个负载(load)和cpu没有关系，它强调的时候当前并发的任务队列，针对流媒体场景，比如4核虚机，ZLM开两个IO线程，那么load 上限就是2左右，开4个线程，那么load上限就是4左右。开8个线程，load上限就是8左右。
