### ISSUE TITLE
[技术咨询] 帧率越低，延时越大

### ISSUE THREAD

**Issue by CaptainNeil** [ZLMediaKit/ZLMediaKit#3002]
**咨询的功能模块**
- ZL API

**咨询的具体内容和问题**
- 使用devChannel向zl输入数据，8k分辨率，当帧率为30时，延时大概1s左右，当帧率为5时，延时大概在4~5秒之间

拉流时命令行：ffplay -i {url} -fflags nobuffer

**Comment by xia-chu** [comment]
什么协议？rtsp吗？

**Comment by xiongguangjie** [comment]
你gop 设置的是多少，gop/帧率是最高延迟（如果播放器处理的好久可以降低影响）

**Comment by CaptainNeil** [comment]
测出来了，延时不是ZL产生，sorry~
此贴关闭
