### ISSUE TITLE
[技术咨询] FLV长时间推流报错Error writing trailer of rtmp://xxxx/live/40206402832-4: End of file

### ISSUE THREAD

**Issue by RuiZhang-cn** [ZLMediaKit/ZLMediaKit#3007]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
FFMPEG推流相关
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
流程为:
车辆上传视频到视频服务器,视频服务器使用FFMPEG推流到ZLMediaKit,通过ZLMediaKit进行ws+flv观看
长时间进行FFMPEG推流,大概一个小时就会如下报错
日志为:
```
[flv @ 0x2d1de40] Failed to update header with correct duration.
[flv @ 0x2d1de40] Failed to update header with correct filesize.
Error writing trailer of rtmp://x/live/40206402832-4: End of file
frame=81969 fps= 17 q=-1.0 Lsize=  745425kB time=01:21:25.86 bitrate=1249.8kbits/s speed=0.999x    
video:727057kB audio:16724kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.220986%
[aac @ 0x2d37700] Qavg: 65536.000
Conversion failed!
```
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个应该是zlm主动掐断的链接 需要结合zlm日志看看

**Comment by RuiZhang-cn** [comment]
我又试了几次都没复现，先关掉吧，再有问题我补充一下zlm日志
