### ISSUE TITLE
[技术咨询] webrtc双向语音调试过程中遇到问题

### ISSUE THREAD

**Issue by walkTtalk** [ZLMediaKit/ZLMediaKit#3010]
**咨询的功能模块**
- webrtc双向语音调试

**咨询的具体内容和问题**
- 采用webrtc实现双向语音发现有问题

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/20769982/cbca13c7-558c-415a-92b9-2fdeb68d3e60)
-------

服务器向摄像头400状态，不清楚这一步为什么400
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/20769982/efd00d83-2698-4186-8bd6-6deea8215c7c)

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
这个一般是sip sdp不对导致的问题吧 我建议你在wvp提这个issue 我实难回答这个问题。
我也没搞过sip语音对讲。

这种我建议你可以抓包分析对比其他软件的语音对讲，自己摸索很难调通的

**Comment by walkTtalk** [comment]
> 这个一般是sip sdp不对导致的问题吧 我建议你在wvp提这个issue 我实难回答这个问题。 我也没搞过sip语音对讲。
> 
> 这种我建议你可以抓包分析对比其他软件的语音对讲，自己摸索很难调通的

好的，我只是尝试探索一下，抽空测试一下。先关了，后续若解决了可以再开启。

**Comment by walkTtalk** [comment]
> 这个一般是sip sdp不对导致的问题吧 我建议你在wvp提这个issue 我实难回答这个问题。 我也没搞过sip语音对讲。
> 
> 这种我建议你可以抓包分析对比其他软件的语音对讲，自己摸索很难调通的

谢谢，简单探索一下，不是必须要解决的问题。实际产品在运行，每次问题都是测试机在测试。

**Comment by 1282140634** [comment]
双向语音对讲我这边已经通过webrtc解决，测试了大华等摄像头效果还是可以的，有需要的小伙伴可以联系我

**Comment by walkTtalk** [comment]
> 双向语音对讲我这边已经通过webrtc解决，测试了大华等摄像头效果还是可以的，有需要的小伙伴可以联系我

老师，怎么联系呀。

**Comment by 1282140634** [comment]
> > 全体语音对讲我已经通过webrtc解决了，测试了大华等摄像头效果还是可以的，有需要的小伙伴可以联系我
> 
> 老师，怎么联系呀。
你这边有摄像头呀？如果有的话正好接我刚搭的wvp测试，我的wx 13173406517，相互学习～
