### ISSUE TITLE
[技术咨询] 新版本ZLMediaKit配置文件里，record配置项里的filesecond配置项取消了吗？

### ISSUE THREAD

**Issue by jiang2586** [ZLMediaKit/ZLMediaKit#3021]
**咨询的功能模块**
- config.ini配置文件里关于record filesecond配置项的咨询

**咨询的具体内容和问题**
- 之前用的老版本ZLMediaKit，配置文件的record配置项里有filesecond的参数配置，但下载了新版本没找到这个配置项。翻看之前的issue确实有介绍说可以通过filesecond控制录制视频的时长。
- 还请老师帮忙解惑，感谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
改成protocol.max_mp4_second了

**Comment by jiang2586** [comment]
> 改成protocol.mp4_max_second了

看到了，非常感谢老师指点！
