### ISSUE TITLE
[技术咨询] webrtc公网拉流只能播20s还很卡，然后报错WebRtcSession.cpp:106 onError...255(socket send timeout)

### ISSUE THREAD

**Issue by DDL-IN-MY-AGENDA** [ZLMediaKit/ZLMediaKit#3026]
**咨询的功能模块**
- webrtc在公网使用

**咨询的具体内容和问题**
- 大佬您好，我是应届本科生，我对ZLMediaKit十分感兴趣，想学习一下，以此开展我的毕业设计。
- 现在我遇到一个问题：在内网环境下，webrtc十分稳定，我尝试在公网部署后，播放时就只能播20来秒后会报错，且播放画面逐渐卡顿，延迟变大（我在内网部署的不会），目前我找不到报错原因，公网服务器对外端口以全部开放，这是日志，希望能够得到回复，感谢！
[2023-11-26_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13466827/2023-11-26_00.log)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by DDL-IN-MY-AGENDA** [comment]
这是控制台输出
![Snipaste_2023-11-26_21-25-41](https://github.com/ZLMediaKit/ZLMediaKit/assets/81623093/c4a2d087-40b6-4d36-b45d-bf2158a0292c)

**Comment by xiongguangjie** [comment]
服务器日志

**Comment by DDL-IN-MY-AGENDA** [comment]
> 看服务器日志，应该是网络问题，导致超时了，应该是被防火墙之类的，拦截了

感谢回复，我这边防火墙是关闭的，iptable对外的端口以及服务器安全组对外端口也是全放通的，webrtc服务需要开放的input端口我开了这些：
![Snipaste_2023-11-27_13-50-49](https://github.com/ZLMediaKit/ZLMediaKit/assets/81623093/eef0a07d-2745-49ae-8ac8-d253855be184)

**Comment by xiongguangjie** [comment]
> > 看服务器日志，应该是网络问题，导致超时了，应该是被防火墙之类的，拦截了
> 
> 感谢回复，我这边防火墙是关闭的，iptable对外的端口以及服务器安全组对外端口也是全放通的，webrtc服务需要开放的input端口我开了这些： ![Snipaste_2023-11-27_13-50-49](https://private-user-images.githubusercontent.com/81623093/285733780-eef0a07d-2745-49ae-8ac8-d253855be184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzM4ODgsIm5iZiI6MTcwMTA3MzU4OCwicGF0aCI6Ii84MTYyMzA5My8yODU3MzM3ODAtZWVmMGEwN2QtMjc0NS00OWFlLThhYzgtZDI1Mzg1NWJlMTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZWQzZjIwYjcyYjc0YThkZjU5ZTg2YTYxMWRlNmE1OGI2ODQxYWM1Mjc4YjUxZmUxM2FmOTdlNjczZTc1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cXPRu82_8aYdmQm9YcNZiu40tPCkqqH0kKXOCtnqFgM)

出方向也需要吧

**Comment by DDL-IN-MY-AGENDA** [comment]
> > > 看服务器日志，应该是网络问题，导致超时了，应该是被防火墙之类的，拦截了
> > 
> > 
> > 感谢回复，我这边防火墙是关闭的，iptable对外的端口以及服务器安全组对外端口也是全放通的，webrtc服务需要开放的input端口我开了这些： ![Snipaste_2023-11-27_13-50-49](https://private-user-images.githubusercontent.com/81623093/285733780-eef0a07d-2745-49ae-8ac8-d253855be184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNzM4ODgsIm5iZiI6MTcwMTA3MzU4OCwicGF0aCI6Ii84MTYyMzA5My8yODU3MzM3ODAtZWVmMGEwN2QtMjc0NS00OWFlLThhYzgtZDI1Mzg1NWJlMTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA4MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZWQzZjIwYjcyYjc0YThkZjU5ZTg2YTYxMWRlNmE1OGI2ODQxYWM1Mjc4YjUxZmUxM2FmOTdlNjczZTc1MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cXPRu82_8aYdmQm9YcNZiu40tPCkqqH0kKXOCtnqFgM)
> 
> 出方向也需要吧

出方向我是全放通了，我现在出入tcp udp都放通，iptable也放通，还是会报错

**Comment by DDL-IN-MY-AGENDA** [comment]
配置文件externIP设置的公网的ip

**Comment by xiongguangjie** [comment]
推流不要停呀，你的推流断了

**Comment by DDL-IN-MY-AGENDA** [comment]
推流没有停止呢，摄像头是调用着的，我如果重复多次拉流，他可以刷新出新的一帧图像

**Comment by DDL-IN-MY-AGENDA** [comment]
[2023-11-30_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13510567/2023-11-30_00.log)
大佬我这推流是一直在推的，我最后退出程序了推流才结束的，现在就是我服务刚开的时候也可以拉几秒，然后后面就播不了了，客户端推流和拉流都是采用的webrtcclient，浏览器也都是connect状态，目前我无法排查到具体哪里出问题了，盼回谢谢！
另外这是我的服务地址，https://120.26.201.55/webrtc/ 您可以测试下，感谢！

**Comment by DDL-IN-MY-AGENDA** [comment]
感谢回复，我推流用的是ZLMRTCClient.js的推流器，下来我用带宽高的机器试试看
