### ISSUE TITLE
docker编译失败

### ISSUE THREAD

**Issue by WalkerPlus** [ZLMediaKit/ZLMediaKit#3028]
### 相关日志及环境信息
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16448447/8d70e7ea-e4e4-4493-84a4-a41df120d2e3)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16448447/1c3099f1-c666-4c2a-a27c-c9f852e6bb65)

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by WalkerPlus** [comment]
[root@localhost ZLMediaKit]# bash build_docker_images.sh -t build -p amd64 -m Release -v t1
[+] Building 24.5s (14/22)
[+] Building 24.6s (14/22)
[+] Building 25.3s (16/22)
 => [internal] load build definition from dockerfile                                                                           0.0s
 => => transferring dockerfile: 2.84kB                                                                                         0.0s
 => [internal] load .dockerignore                                                                                              0.0s
 => => transferring context: 2B                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                               15.4s
 => [internal] load build context                                                                                              0.0s
 => => transferring context: 681.12kB                                                                                          0.0s
 => CACHED [build  1/11] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae2  0.0s
 => CANCELED [stage-1 2/8] RUN apt-get update &&          DEBIAN_FRONTEND="noninteractive"          apt-get install -y --no-i  9.8s
 => CACHED [build  2/11] RUN apt-get update &&          DEBIAN_FRONTEND="noninteractive"          apt-get install -y --no-ins  0.0s
 => CACHED [build  3/11] RUN mkdir -p /opt/media                                                                               0.0s
 => [build  4/11] COPY . /opt/media/ZLMediaKit                                                                                 0.7s
 => [build  5/11] WORKDIR /opt/media/ZLMediaKit                                                                                0.0s
 => [build  6/11] WORKDIR /opt/media/ZLMediaKit/3rdpart                                                                        0.0s
 => [build  7/11] COPY ./tools/libsrtp-2.3.0.tar.gz /opt/media/ZLMediaKit/3rdpart/                                             0.0s
 => [build  8/11] RUN tar xfv libsrtp-2.3.0.tar.gz &&     mv libsrtp-2.3.0 libsrtp &&     cd libsrtp && ./configure --enable-  7.2s
 => [build  9/11] RUN mkdir -p build release/linux/Release/                                                                    0.2s
 => [build 10/11] WORKDIR /opt/media/ZLMediaKit/build                                                                          0.0s
 => ERROR [build 11/11] RUN cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WEBRTC=true -DENABLE_FFMPEG=true -DENABLE_TESTS=false -  1.6s
------
 > [build 11/11] RUN cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WEBRTC=true -DENABLE_FFMPEG=true -DENABLE_TESTS=false -DENABLE_API=fa                               lse .. &&     make -j $(nproc):
#19 0.202 -- The C compiler identification is GNU 9.4.0
#19 0.275 -- The CXX compiler identification is GNU 9.4.0
#19 0.281 -- Check for working C compiler: /usr/bin/cc                                                                                                             #19 0.366 -- Check for working C compiler: /usr/bin/cc -- works
#19 0.369 -- Detecting C compiler ABI info                                                                                                                         #19 0.456 -- Detecting C compiler ABI info - done
#19 0.470 -- Detecting C compile features
#19 0.471 -- Detecting C compile features - done
#19 0.474 -- Check for working CXX compiler: /usr/bin/c++
#19 0.582 -- Check for working CXX compiler: /usr/bin/c++ -- works
#19 0.583 -- Detecting CXX compiler ABI info
#19 0.696 -- Detecting CXX compiler ABI info - done
#19 0.710 -- Detecting CXX compile features
#19 0.711 -- Detecting CXX compile features - done
#19 0.713 -- 编译类型: Release
#19 0.723 -- Git version is master 5adde2c/2023-11-27T09:20:53+08:00 2023-11-27T02:26:35
#19 0.724 -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
#19 0.867 -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
#19 0.926 -- found library: avutil
#19 0.978 -- found library: avcodec
#19 1.033 -- found library: swscale
#19 1.083 -- found library: swresample
#19 1.147 -- found library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so, ENABLE_OPENSSL defined
#19 1.149 -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION
#19 1.181 -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed
#19 1.186 -- ENABLE_MP4 defined
#19 1.187 -- ENABLE_HLS_FMP4 defined
#19 1.187 -- ENABLE_RTPPROXY defined
#19 1.187 -- ENABLE_HLS defined
#19 1.188 -- Performing Test HAVE_MMSG_HDR
#19 1.275 -- Performing Test HAVE_MMSG_HDR - Success
#19 1.276 -- Looking for sendmmsg
#19 1.381 -- Looking for sendmmsg - found
#19 1.382 -- Looking for recvmmsg
#19 1.470 -- Looking for recvmmsg - found
#19 1.471 -- set_file_group /opt/media/ZLMediaKit/3rdpart/ZLToolKit/src 1
#19 1.473 -- set_file_group /opt/media/ZLMediaKit/src 237
#19 1.479 -- srt 功能已开启
#19 1.481 -- found library: /usr/local/lib/libsrtp2.a
#19 1.481 -- SCTP LIBRARIES: /usr/lib/x86_64-linux-gnu/libusrsctp.so
#19 1.481 -- SCTP INCLUDE DIRS: /usr/include
#19 1.482 -- found library: /usr/include /usr/lib/x86_64-linux-gnu/libusrsctp.so
#19 1.482 -- WebRTC datachannel 功能已打开
#19 1.483 -- WebRTC 功能已开启
#19 1.493 CMake Warning at player/CMakeLists.txt:47 (message):
#19 1.493   test_player disabled, please install sdl2 ffmpeg/libavcodec
#19 1.493   ffmpeg/libavutil ffmpeg/libswresample
#19 1.493
#19 1.493
#19 1.499 -- Configuring done
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:194 (add_library):
#19 1.506   No SOURCES given to target: zltoolkit
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:95 (add_library):
#19 1.506   No SOURCES given to target: mpeg
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:68 (add_library):
#19 1.506   No SOURCES given to target: flv
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:55 (add_library):
#19 1.506   No SOURCES given to target: mov
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:32 (add_library):
#19 1.506   No SOURCES given to target: jsoncpp
#19 1.506
#19 1.506
#19 1.506 CMake Generate step failed.  Build files cannot be regenerated correctly.
------
error: failed to solve: executor failed running [/bin/sh -c cmake -DCMAKE_BUILD_TYPE=${MODEL} -DENABLE_WEBRTC=true -DENABLE_FFMPEG=t                               rue -DENABLE_TESTS=false -DENABLE_API=false .. &&     make -j $(nproc)]: exit code: 1

**Comment by WalkerPlus** [comment]
```
[root@localhost ZLMediaKit]# bash build_docker_images.sh -t build -p amd64 -m Release -v t1
[+] Building 24.5s (14/22)
[+] Building 24.6s (14/22)
[+] Building 25.3s (16/22)
 => [internal] load build definition from dockerfile                                                                           0.0s
 => => transferring dockerfile: 2.84kB                                                                                         0.0s
 => [internal] load .dockerignore                                                                                              0.0s
 => => transferring context: 2B                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                               15.4s
 => [internal] load build context                                                                                              0.0s
 => => transferring context: 681.12kB                                                                                          0.0s
 => CACHED [build  1/11] FROM docker.io/library/ubuntu:20.04@sha256:626ffe58f6e7566e00254b638eb7e0f3b11d4da9675088f4781a50ae2  0.0s
 => CANCELED [stage-1 2/8] RUN apt-get update &&          DEBIAN_FRONTEND="noninteractive"          apt-get install -y --no-i  9.8s
 => CACHED [build  2/11] RUN apt-get update &&          DEBIAN_FRONTEND="noninteractive"          apt-get install -y --no-ins  0.0s
 => CACHED [build  3/11] RUN mkdir -p /opt/media                                                                               0.0s
 => [build  4/11] COPY . /opt/media/ZLMediaKit                                                                                 0.7s
 => [build  5/11] WORKDIR /opt/media/ZLMediaKit                                                                                0.0s
 => [build  6/11] WORKDIR /opt/media/ZLMediaKit/3rdpart                                                                        0.0s
 => [build  7/11] COPY ./tools/libsrtp-2.3.0.tar.gz /opt/media/ZLMediaKit/3rdpart/                                             0.0s
 => [build  8/11] RUN tar xfv libsrtp-2.3.0.tar.gz &&     mv libsrtp-2.3.0 libsrtp &&     cd libsrtp && ./configure --enable-  7.2s
 => [build  9/11] RUN mkdir -p build release/linux/Release/                                                                    0.2s
 => [build 10/11] WORKDIR /opt/media/ZLMediaKit/build                                                                          0.0s
 => ERROR [build 11/11] RUN cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WEBRTC=true -DENABLE_FFMPEG=true -DENABLE_TESTS=false -  1.6s
------
 > [build 11/11] RUN cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WEBRTC=true -DENABLE_FFMPEG=true -DENABLE_TESTS=false -DENABLE_API=fa                               lse .. &&     make -j $(nproc):
#19 0.202 -- The C compiler identification is GNU 9.4.0
#19 0.275 -- The CXX compiler identification is GNU 9.4.0
#19 0.281 -- Check for working C compiler: /usr/bin/cc                                                                                                             #19 0.366 -- Check for working C compiler: /usr/bin/cc -- works
#19 0.369 -- Detecting C compiler ABI info                                                                                                                         #19 0.456 -- Detecting C compiler ABI info - done
#19 0.470 -- Detecting C compile features
#19 0.471 -- Detecting C compile features - done
#19 0.474 -- Check for working CXX compiler: /usr/bin/c++
#19 0.582 -- Check for working CXX compiler: /usr/bin/c++ -- works
#19 0.583 -- Detecting CXX compiler ABI info
#19 0.696 -- Detecting CXX compiler ABI info - done
#19 0.710 -- Detecting CXX compile features
#19 0.711 -- Detecting CXX compile features - done
#19 0.713 -- 编译类型: Release
#19 0.723 -- Git version is master 5adde2c/2023-11-27T09:20:53+08:00 2023-11-27T02:26:35
#19 0.724 -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
#19 0.867 -- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
#19 0.926 -- found library: avutil
#19 0.978 -- found library: avcodec
#19 1.033 -- found library: swscale
#19 1.083 -- found library: swresample
#19 1.147 -- found library: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so, ENABLE_OPENSSL defined
#19 1.149 -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION
#19 1.181 -- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed
#19 1.186 -- ENABLE_MP4 defined
#19 1.187 -- ENABLE_HLS_FMP4 defined
#19 1.187 -- ENABLE_RTPPROXY defined
#19 1.187 -- ENABLE_HLS defined
#19 1.188 -- Performing Test HAVE_MMSG_HDR
#19 1.275 -- Performing Test HAVE_MMSG_HDR - Success
#19 1.276 -- Looking for sendmmsg
#19 1.381 -- Looking for sendmmsg - found
#19 1.382 -- Looking for recvmmsg
#19 1.470 -- Looking for recvmmsg - found
#19 1.471 -- set_file_group /opt/media/ZLMediaKit/3rdpart/ZLToolKit/src 1
#19 1.473 -- set_file_group /opt/media/ZLMediaKit/src 237
#19 1.479 -- srt 功能已开启
#19 1.481 -- found library: /usr/local/lib/libsrtp2.a
#19 1.481 -- SCTP LIBRARIES: /usr/lib/x86_64-linux-gnu/libusrsctp.so
#19 1.481 -- SCTP INCLUDE DIRS: /usr/include
#19 1.482 -- found library: /usr/include /usr/lib/x86_64-linux-gnu/libusrsctp.so
#19 1.482 -- WebRTC datachannel 功能已打开
#19 1.483 -- WebRTC 功能已开启
#19 1.493 CMake Warning at player/CMakeLists.txt:47 (message):
#19 1.493   test_player disabled, please install sdl2 ffmpeg/libavcodec
#19 1.493   ffmpeg/libavutil ffmpeg/libswresample
#19 1.493
#19 1.493
#19 1.499 -- Configuring done
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:194 (add_library):
#19 1.506   No SOURCES given to target: zltoolkit
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:95 (add_library):
#19 1.506   No SOURCES given to target: mpeg
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:68 (add_library):
#19 1.506   No SOURCES given to target: flv
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:55 (add_library):
#19 1.506   No SOURCES given to target: mov
#19 1.506
#19 1.506
#19 1.506 CMake Error at 3rdpart/CMakeLists.txt:32 (add_library):
#19 1.506   No SOURCES given to target: jsoncpp
#19 1.506
#19 1.506
#19 1.506 CMake Generate step failed.  Build files cannot be regenerated correctly.
------
error: failed to solve: executor failed running [/bin/sh -c cmake -DCMAKE_BUILD_TYPE=${MODEL} -DENABLE_WEBRTC=true -DENABLE_FFMPEG=t                               rue -DENABLE_TESTS=false -DENABLE_API=false .. &&     make -j $(nproc)]: exit code: 1

```

**Comment by WalkerPlus** [comment]
> 遇到同样问题，求解

手动下包解决了

**Comment by monogatari-x** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wrkamvip** [comment]
有包的地址吗，能提供一下libflv、libmov、mepg包地址吗
