### ISSUE TITLE
[技术咨询]webrtc linux客户端和服务端咨询

### ISSUE THREAD

**Issue by zhangjiaxingict** [ZLMediaKit/ZLMediaKit#3031]
您好，我目前想做一个webrtc的技术有关的技术研究，在我的框架中需要一个可以在linux命令行中运行的webrtc客户端和服务端，阅读了我们的框架之后我可以确定的是Zlmediakit是一个很优秀的webrtc服务端，不知道linux命令行中运行的webrtc客户端我们有实现么？

另外，我是用RTP推流，可以使用WebRTC拉流么？如果此时带宽发生抖动，Zlmediakit会冲编码RTP推送的媒体流来避免卡顿么？

**Comment by xiongguangjie** [comment]
1，客户端没有实现，你需要借助其他的客户端实现
2，rtp推流，rtc 拉流是可以的， 带宽抖动导致播放卡顿，需要播放器来控制（如加入缓存之类的）

**Comment by zhangjiaxingict** [comment]
谢谢，我还有一个地方不太了解。因为服务端可以探测到实时带宽，RTP按照一定码率推流，如果服务端发现webrtc客户端没有足够的带宽来接收原始的RTP视频流，服务端会将RTP视频流重新编码为码率更低的视频流么？

毕竟此时网络带宽不足以接收RTP推送的高码率视频流。

**Comment by zhangjiaxingict** [comment]
谢谢，了解啦
