### ISSUE TITLE
[技术咨询] 官网提供的二进制程序只有 docker 吗

### ISSUE THREAD

**Issue by ifeisier** [ZLMediaKit/ZLMediaKit#3034]
官网提供的二进制程序只有 docker 吗

还有一个问题，c api 也需要开启 MediaServer 服务吗？

**Comment by xiongguangjie** [comment]
> 官网提供的二进制程序只有 docker 吗
> 
> 还有一个问题，c api 也需要开启 MediaServer 服务吗？

是的，有群友编译过windows 的二进制，C api 不需要启动MediaServer

**Comment by ifeisier** [comment]
> > 官网提供的二进制程序只有 docker 吗
> > 还有一个问题，c api 也需要开启 MediaServer 服务吗？
> 
> 是的，有群友编译过windows 的二进制，C api 不需要启动MediaServer

抱歉，对于 https://github.com/ZLMediaKit/ZLMediaKit#%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8 我可以这样理解吗？

1、使用c api，作为sdk使用
    可以理解为将 ZLMediaKit 作为一个第三方库使用？

3、如果想做c/c++开发，添加业务逻辑增加功能
   可以理解为直接开发 ZLMediaKit 程序，只是要通过 MediaServer 服务启动？

**Comment by ifeisier** [comment]
> > 官网提供的二进制程序只有 docker 吗
> > 还有一个问题，c api 也需要开启 MediaServer 服务吗？
> 
> 是的，有群友编译过windows 的二进制，C api 不需要启动MediaServer

感谢，祝您生活愉快。
