### ISSUE TITLE
请问有 config.ini 配置文件的详细说明吗

### ISSUE THREAD

**Issue by ifeisier** [ZLMediaKit/ZLMediaKit#3035]
我是用的是 docker。

**Comment by xiongguangjie** [comment]
> 我是用的是 docker。

源码conf里面有个示例有注释的，你可以阅读下

**Comment by alexliyu7352** [comment]
https://docs.zlmediakit.com/guide/media_server/config_file.html
https://docs.zlmediakit.com/zh/guide/media_server/config_file.html

xiongguangjie ***@***.***> 于2023年11月28日周二 18:10写道：

**Comment by ifeisier** [comment]
谢谢
