### ISSUE TITLE
[编译问题] 海思交叉编译报错(util.cpp:456:68: error: ‘pthread_setname_np’ was not declared in this scope)

### ISSUE THREAD

**Issue by RunFeng** [ZLMediaKit/ZLMediaKit#3037]
### 相关日志及环境信息
平台：海思3531D
编译器：arm-hisiv500-linux- （gcc version 4.9.4 20150629 (prerelease) (Hisilicon_v500_20170922)）

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
[zlm编译报错.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/13486065/zlm.txt)

```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:
[toolchain_hi3531d_500.cmake.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/13486083/toolchain_hi3531d_500.cmake.txt)

**Comment by xiongguangjie** [comment]
```c++
diff --git a/src/Util/util.cpp b/src/Util/util.cpp
index b4ee662..d26c131 100644
--- a/src/Util/util.cpp
+++ b/src/Util/util.cpp
@@ -70,6 +70,11 @@ int uv_exepath(char *buffer, int *size) {
 
 #endif //defined(__MACH__) || defined(__APPLE__)
 
+
+#if defined(__linux) || defined(__linux__) || defined(__MINGW32__)
+ #include <pthread.h>
+#endif
+
 using namespace std;
 
 namespace toolkit {
``` 

试一下，如上的patch ，添加pthread.h 的头文件

**Comment by RunFeng** [comment]
前面加了试过，问题还是存在
又按照上面描述添加后，问题还是存在，报错的位置一样的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/18656420/c2bfa68c-119e-4ea7-9d73-a82682928367)

**Comment by xiongguangjie** [comment]
> 前面加了试过，问题还是存在 又按照上面描述添加后，问题还是存在，报错的位置一样的 ![image](https://private-user-images.githubusercontent.com/18656420/286259246-c2bfa68c-119e-4ea7-9d73-a82682928367.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjE3MTIsIm5iZiI6MTcwMTIyMTQxMiwicGF0aCI6Ii8xODY1NjQyMC8yODYyNTkyNDYtYzJiZmE2OGMtMTE5ZS00ZWE3LTlkNzMtYTgyNjgyOTI4MzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDAxMzAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxZDVhZTQ0ZDZlYzBkMTcxYTNhYTU5YzI5YWM5MTIxZmY3NmZhYWIyYzdlMzU1OWU4Mzc5YTM3NGExYTgyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thWjyzzC09YGeJ6LmnYKBsHc-KJRNdhjpIIw_y3whhU)

这个工具链你找一下头文件，看是否有pthread.h 的头文件，是否有相应的函数，名字改了吗？？？

**Comment by xiongguangjie** [comment]
这个我记得好像是文件系统里面的头文件吧，不是没有指定目标系统的根目录呀

**Comment by RunFeng** [comment]
工具链里确实存在pthread.h，但是.h中并没有包含pthread_setname_np等接口（怀疑为交叉编译器是uclibc版本的问题，因为glibc对应的arm-hisiv400-linux-是包含的）。这里我收到修改zlm代码跳过使用pthread_setname_np等相关接口，至此这块不在保错。
但编译后续又出现如下错误：查看工具链中并不存在execinfo.h（arm-hisiv400-linux-是包含的）这地方我如何修改可以在不改变交叉编译器的情况下可编译通过呢？

/home/xxxxxx/ZLMediaKit_Nova/ZLMediaKit/server/System.cpp:16:22: fatal error: execinfo.h: No such file or directory
 #include <execinfo.h>
                      ^
compilation terminated.
make[2]: *** [server/CMakeFiles/MediaServer.dir/build.make:92: server/CMakeFiles/MediaServer.dir/System.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/xxxg/ZLMediaKit_Nova/ZLMediaKit/build_Hi3531d'

**Comment by xiongguangjie** [comment]
这个很久了，关闭吧，手上没有环境无法复现
