### ISSUE TITLE
[技术咨询] zlmediakit显示丢包，只有几个点播正常

### ISSUE THREAD

**Issue by ERAIT** [ZLMediaKit/ZLMediaKit#3047]
**咨询的功能模块**
- zlmediakit显示丢包，wvp-pro点播，同一个nvr，只有几个可以点播，多数zlmediakit显示rtp丢包

**咨询的具体内容和问题**
![Uploading image.png…]()

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by ERAIT** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/32009330/3b6cd1ff-77af-4b14-9afa-cab2590c7257)

**Comment by xiongguangjie** [comment]
用tcp试一下，应该是网络丢包了，还有就是设置udp的默认缓存

**Comment by ERAIT** [comment]
> 用tcp试一下，应该是网络丢包了，还有就是设置udp的默认缓存

用的windows系统

**Comment by huzhiqin888** [comment]
wvp-pro上改成tcp主动就可以了

**Comment by xiaohuiL** [comment]
> > 用tcp试一下，应该是网络丢包了，还有就是设置udp的默认缓存
> 
> 用的windows系统

你好，你的丢包问题解决了吗？我现在也是持续丢包

**Comment by zhang-chuanfeng** [comment]
> 用tcp试一下，应该是网络丢包了，还有就是设置udp的默认缓存

也会遇到打印丢包，udp默认缓存如何调整？

**Comment by zhang-chuanfeng** [comment]
> > 用tcp试一下，应该是网络丢包了，还有就是设置udp的默认缓存
> 
> 也会遇到打印丢包，udp默认缓存如何调整？

我看需要改源码  针对rtp_proxy是不是增加个可配置udp缓存大小
