### ISSUE TITLE
将[hook]中的enable=1后，不能触发on_stream_not_found的web hook回调

### ISSUE THREAD

**Issue by 728684457** [ZLMediaKit/ZLMediaKit#3058]

**Comment by xiongguangjie** [comment]
服务器的日志上传上来

**Comment by 728684457** [comment]
==========服务日志=========
2023-12-01 10:00:56.492 W [MediaServer] [622374-event poller 1] WebHook.cpp:194 operator() | hook http://192.168.30.32:18080/index/hook/on_server_keepalive 1ms,failed[network err]:3(connection refused):{
	"data" : 
	{
		"Buffer" : 33,
		"BufferLikeString" : 1,
		"BufferList" : 0,
		"BufferRaw" : 32,
		"Frame" : 0,
		"FrameImp" : 0,
		"MediaSource" : 1,
		"MultiMediaSourceMuxer" : 0,
		"RtmpPacket" : 0,
		"RtpPacket" : 0,
		"Socket" : 225,
		"TcpClient" : 1,
		"TcpServer" : 163,
		"TcpSession" : 0,
		"UdpServer" : 64,
		"UdpSession" : 0
	},
	"hook_index" : 5629,
	"mediaServerId" : "testabcd"
}

2023-12-01 10:00:59.493 W [MediaServer] [622374-event poller 1] WebHook.cpp:194 operator() | hook http://192.168.30.32:18080/index/hook/on_server_keepalive 1ms,failed[network err]:3(connection refused):{
	"data" : 
	{
		"Buffer" : 33,
		"BufferLikeString" : 1,
		"BufferList" : 0,
		"BufferRaw" : 32,
		"Frame" : 0,
		"FrameImp" : 0,
		"MediaSource" : 1,
		"MultiMediaSourceMuxer" : 0,
		"RtmpPacket" : 0,
		"RtpPacket" : 0,
		"Socket" : 225,
		"TcpClient" : 1,
		"TcpServer" : 163,
		"TcpSession" : 0,
		"UdpServer" : 64,
		"UdpSession" : 0
	},
	"hook_index" : 5630,
	"mediaServerId" : "testabcd"
}

2023-12-01 10:01:06.492 W [MediaServer] [622374-event poller 1] WebHook.cpp:194 operator() | hook http://192.168.30.32:18080/index/hook/on_server_keepalive 0ms,failed[network err]:3(connection refused):{
	"data" : 
	{
		"Buffer" : 33,
		"BufferLikeString" : 1,
		"BufferList" : 0,
		"BufferRaw" : 32,
		"Frame" : 0,
		"FrameImp" : 0,
		"MediaSource" : 1,
		"MultiMediaSourceMuxer" : 0,
		"RtmpPacket" : 0,
		"RtpPacket" : 0,
		"Socket" : 225,
		"TcpClient" : 1,
		"TcpServer" : 163,
		"TcpSession" : 0,
		"UdpServer" : 64,
		"UdpSession" : 0
	},
	"hook_index" : 5631,
	"mediaServerId" : "testabcd"
}

2023-12-01 10:01:08.018 D [MediaServer] [622374-event poller 3] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/getServerConfig
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 39
Content-Type : application/x-www-form-urlencoded
Host : 192.168.30.32:8066
User-Agent : okhttp/4.9.0
# content:
secret=CxmBsqBHBXfqZ2i3L2RwRXWCk9Lfe5ck
# response size:5593

2023-12-01 10:01:08.076 D [MediaServer] [622374-event poller 3] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 74
Content-Type : application/x-www-form-urlencoded
Host : 192.168.30.32:8066
User-Agent : okhttp/4.9.0
# content:
secret=CxmBsqBHBXfqZ2i3L2RwRXWCk9Lfe5ck&schema=rtsp&vhost=__defaultVhost__
# response:
{
	"code" : 0
}


2023-12-01 10:01:08.078 D [MediaServer] [622374-event poller 3] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/setServerConfig
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 1213
Content-Type : application/x-www-form-urlencoded
Host : 192.168.30.32:8066
User-Agent : okhttp/4.9.0
# content:
secret=CxmBsqBHBXfqZ2i3L2RwRXWCk9Lfe5ck&hook.on_rtsp_realm=&hook.on_stream_changed=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_stream_changed&hook.on_flow_report=&hook.on_publish=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_publish&hook.timeoutSec=20&protocol.continue_push_ms=3000&hook.enable=1&hook.on_rtp_server_timeout=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_rtp_server_timeout&hook.on_http_access=&hook.on_stream_not_found=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_stream_not_found&hook.on_send_rtp_stopped=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_send_rtp_stopped&rtp_proxy.port_range=30000-30500&hook.on_rtsp_auth=&hook.on_record_mp4=http%3A%2F%2F127.0.0.1%3A18081%2Fapi%2Frecord%2Fon_record_mp4&hook.on_stream_none_reader=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_stream_none_reader&hook.on_server_keepalive=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_server_keepalive&hook.on_shell_login=&hook.on_play=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_play&api.secret=CxmBsqBHBXfqZ2i3L2RwRXWCk9Lfe5ck&hook.on_server_started=http%3A%2F%2F192.168.30.32%3A18080%2Findex%2Fhook%2Fon_server_started&hook.on_record_ts=
# response:
{
	"changed" : 0,
	"code" : 0
}


2023-12-01 10:01:08.098 D [MediaServer] [622374-event poller 3] WebApi.cpp:258 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 39
Content-Type : application/x-www-form-urlencoded
Host : 192.168.30.32:8066
User-Agent : okhttp/4.9.0
# content:
secret=CxmBsqBHBXfqZ2i3L2RwRXWCk9Lfe5ck
# response:
{
	"code" : 0
}

**Comment by 728684457** [comment]
平时部署了几次都没问题 一到现场就连不上hook
