### ISSUE TITLE
Web hook functionality how to use?

### ISSUE THREAD

**Issue by junyujunyu** [ZLMediaKit/ZLMediaKit#3078]
**Consultation Function Module**
hook function

**Specific Content and Questions About Consultation**
- Here to describe your consulting content
- I couldn't find a corresponding example, I tested it myself.
（1）Modify Configuration
[hook]
enable=1
(2) Observe the output of MediaServer, there is already hook information.
(3) Capture and analyze it, it connects to 127.0.0.1:443, as shown below
Question:
How to prevent hook from outputting to MediaServer's 443, i.e., disable my own 443? 
Make hook output to other applications listening on 443 port, so that other applications can be informed of MediaServer's status for processing. I understand the hook function like this, yes? 

**Note**
- Before asking for technical consulting, please carefully read readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki), if necessary, you can also search for already answered issues, if you can't find the answer, submit an issue here

- Technical consulting is not a bug or defect, users must star (favorite) this project first, otherwise, the issue will be closed directly

>**咨询的功能模块**
web hook 功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 我未找到相应用例，自己测试是这样做的。
（1）修改配置
[hook]
enable=1
（2）观察MediaServer的输出，已经有hook信息。
（3）抓包分析，它是连到127.0.0.1:443,如下图
问题：
如何不要让hook输出到MediaServer的443，即禁掉自己的443？
让hook输出到其它应用监听的443端口，这样才能告诉其它应用MediaServer的状态，以便处理。我这样理解hook功能对嘛？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by junyujunyu** [comment]
我测试程序先占了443端口，再启动MediaServer会报错如下：
2023-12-04 15:37:13.304 E [MediaServer] [8194-MediaServer] main.cpp:399 start_main | Start server failed: Listen on :: 443 failed: address already in use

**Comment by xiongguangjie** [comment]
> Author

hook 置空就不会调用，或者修改url中的端口。如何使用，你要自己开发个服务器端http的，然后实现相应的接口，然后在配置文件中填写相应的url，zlm在事件发生时，会去调用相应的接口的。

**Comment by Elicsdy** [comment]
```
on_stream_none_reader=http://127.0.0.1:8089/index/hook/on_stream_none_reader
on_stream_not_found=http://127.0.0.1:8089/index/hook/on_stream_not_found
```

我的改成这样子，可以用

**Comment by junyujunyu** [comment]
已经测试过，这样改确实可以。谢谢！
