### ISSUE TITLE
[技术咨询] python推流到服务端视频出现未识别的sr rtcp包

### ISSUE THREAD

**Issue by hxbamboo** [ZLMediaKit/ZLMediaKit#3086]
**咨询的功能模块**
- **技术咨询**  python推流到服务端视频出现出现未识别的sr rtcp包，环境是ubuntu20.04

**咨询的具体内容和问题**
- 想通过python推流，通过aiortc库创建offer然后拉回answer后向上推流一直在completed，服务端日志一直报未识别的rtc包
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/72267471/12ffc88d-d876-4703-a0e0-fffbb7986e01)

这是我的代码
```
import asyncio
import json
import requests
import cv2
from aiortc import RTCPeerConnection, RTCSessionDescription, VideoStreamTrack

class VideoStreamTrackWithCapture(VideoStreamTrack):
    def __init__(self):
        super().__init__()
        self.cap = cv2.VideoCapture(0)
    def on_frame(self, frame, frame_time):
        super().on_frame(frame, frame_time)
    async def recv(self):
        while True:
            ret, frame = self.cap.read()
            if not ret:
                break
            processed_frame = cv2.cvtColor(frame,cv2.COLOR.BGR2YUV_I420)
            await self.send(processed_frame)
            await asyncio.sleep(0)
async def consume_signaling(pc, signaling_url,sdp):
    print(sdp)
    remote_answer = RTCSessionDescription(sdp=sdp, type='answer')
    # 设置远程端的 SDP answer
    await pc.setRemoteDescription(remote_answer)
    @pc.on("iceconnectionstatechange")
    def on_ice_connection_state_change():
        print("ICE connection state:", pc.iceConnectionState)
        if pc.iceConnectionState == "failed":
            print("WebRTC connection failed.")


    while pc.iceConnectionState != "connected":
        print(pc.iceConnectionState)
        await asyncio.sleep(1)

    print("WebRTC connection established.")


async def main():
    pc = RTCPeerConnection()
    signaling_url = "https://zlmediakit.com/index/api/webrtc?app=live&stream=test&type=push"

    # Add video track using OpenCV with display
    video_track = VideoStreamTrackWithCapture()
    pc.addTrack(video_track)
    # Create offer
    await pc.setLocalDescription(await pc.createOffer())
    offer_sdp = pc.localDescription.sdp
    offer_type = pc.localDescription.type
    print(offer_sdp, offer_type)
    headers = {
        'Content-Type': 'text/plain'
    }
    # Send the offer to the server
    res = requests.request('POST', signaling_url, data=offer_sdp, headers=headers)
    print(res.json())
    answer_sdp = res.json()['sdp']
    # await pc.close()
    await consume_signaling(pc, signaling_url, answer_sdp)


if __name__ == "__main__":
    asyncio.run(main())


```

**这是我创建的offer**

```
v=0
o=- 3910843445 3910843445 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=video 45725 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102
c=IN IP4 192.168.3.105
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=mid:0
a=msid:6a7b2190-1fc1-46bf-a5dd-cc8f0f1d0d3f fef48840-4583-411d-902d-7cb68a853203
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-mux
a=ssrc-group:FID 439624338 4066105575
a=ssrc:439624338 cname:d474470f-fb8e-458e-b679-af3b8d5118ff
a=ssrc:4066105575 cname:d474470f-fb8e-458e-b679-af3b8d5118ff
a=rtpmap:97 VP8/90000
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=rtpmap:98 rtx/90000
a=fmtp:98 apt=97
a=rtpmap:99 H264/90000
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=rtcp-fb:99 goog-remb
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=rtpmap:101 H264/90000
a=rtcp-fb:101 nack
a=rtcp-fb:101 nack pli
a=rtcp-fb:101 goog-remb
a=fmtp:101 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:102 rtx/90000
a=fmtp:102 apt=101
a=candidate:0f1549d22491e11c96a0aa888d9bfc81 1 udp 2130706431 192.168.3.105 45725 typ host
a=candidate:b651bd9b1bc9adcc78d97e3465fd5bf2 1 udp 2130706431 192.168.55.1 44755 typ host
a=candidate:7443d063a0903cf7a269cf9de0192394 1 udp 2130706431 10.125.192.1 36546 typ host
a=candidate:f48eb9afac503e43371f2e7fb79084b4 1 udp 2130706431 fd42:e31b:f34f:584b::1 45307 typ host
a=candidate:580b5f32035da7f14a30ea7a8d826c67 1 udp 2130706431 172.17.0.1 37621 typ host
a=candidate:95a5144d22d827ac85a6c13daea75649 1 udp 2130706431 172.18.0.1 59663 typ host
a=candidate:894d73749b008d7903bac7cb9edc982f 1 udp 1694498815 39.91.0.151 36546 typ srflx raddr 10.125.192.1 rport 36546
a=candidate:0ad8db753210ce9554cf251a9e51e792 1 udp 1694498815 39.91.0.151 37621 typ srflx raddr 172.17.0.1 rport 37621
a=candidate:297898e4296c74660bb3ab65d8da90ec 1 udp 1694498815 39.91.0.151 27245 typ srflx raddr 172.18.0.1 rport 59663
a=candidate:1bf0c8e79afdc1e20a7d7628281b22b4 1 udp 1694498815 39.91.0.151 45725 typ srflx raddr 192.168.3.105 rport 45725
a=end-of-candidates
a=ice-ufrag:McYD
a=ice-pwd:2fT7CURVLfHAcieFFOcu7C
a=fingerprint:sha-256 3D:78:5E:F0:E9:8D:5A:EF:E8:3F:09:CF:11:D5:84:56:62:08:48:91:D0:D6:05:0D:D5:6F:FE:B1:3A:69:7A:9C
a=setup:actpassive
a=mid:0
a=ice-lite
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:99 H264/90000
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=candidate:udpcandidate 1 udp 110 45.138.71.123 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 45.138.71.123 8000 typ host tcptype passive

```

**这是返回的answer**

```
v=0
o=- 3910843445 3910843445 IN IP4 45.138.71.123
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic: WMS *
a=ice-lite
m=video 8000 UDP/TLS/RTP/SAVPF 99 100
c=IN IP4 45.138.71.123
a=rtcp:8000 IN IP4 45.138.71.123
a=ice-ufrag:zlm44
a=ice-pwd:PaIGjwJ5OZ20Zu3J5PFXLlfC
a=fingerprint:sha-256 44:4B:2D:B5:39:49:7D:6F:91:AF:97:74:C0:43:72:D8:7C:7C:63:1F:65:F6:9A:8B:96:FD:3B:8A:64:13:64:0E
a=setup:passive
a=mid:0
a=ice-lite
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:99 H264/90000
a=rtcp-fb:99 goog-remb
a=rtcp-fb:99 nack
a=rtcp-fb:99 nack pli
a=fmtp:99 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:100 rtx/90000
a=fmtp:100 apt=99
a=candidate:udpcandidate 1 udp 110 45.138.71.123 8000 typ host
a=candidate:tcpcandidate 1 tcp 105 45.138.71.123 8000 typ host tcptype passive
```

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，

**Comment by hxbamboo** [comment]
> 你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，
现在是这样的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/72267471/aa2697bb-dc6d-40f3-a08f-7dc19fd87d99)
应该是没有注册成功？因为我没有看到注册媒体的消息，我现在应该向哪个方向改？或者需要怎么调整先注册呢


我发现当我把VideoStreamTrackWithCapture这个方法变为这样时他是有注册成功的消息的
```
class VideoStreamTrackWithCapture(VideoStreamTrack):
    def __init__(self):
        super().__init__()
```
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/72267471/0a552481-aea8-4fc0-93cd-bd1368764811)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/72267471/154fa0b1-d732-4bb0-835a-7d31ebe06a26)

但是此时视频流没有推上去，播放时是一个绿幕。

**Comment by xiongguangjie** [comment]
> > 你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，
> 
> 现在是这样的 ![image](https://private-user-images.githubusercontent.com/72267471/288613754-aa2697bb-dc6d-40f3-a08f-7dc19fd87d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTM3NTQtYWEyNjk3YmItZGM2ZC00MGYzLWEwOGYtN2RjMTlmZDg3ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjE2NGE5MjlkOGVlNGZkZjUzODkzOGIzM2U5MWFmZWIzODg2NTk2YjZhNTY5NWZkZjk4OTFjNTFjOWE4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBXQePCexKxIfPTRMS5Qe8_TPTv27b7JaCBbNiTOrdU) 应该是没有注册成功？因为我没有看到注册媒体的消息，我现在应该向哪个方向改？或者需要怎么调整先注册呢
> 
> 我发现当我把VideoStreamTrackWithCapture这个方法变为这样时他是有注册成功的消息的
> 
> ```
> class VideoStreamTrackWithCapture(VideoStreamTrack):
>     def __init__(self):
>         super().__init__()
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/72267471/288615031-0a552481-aea8-4fc0-93cd-bd1368764811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUwMzEtMGE1NTI0ODEtYWVhOC00ZmMwLTkzY2QtYmQxMzY4NzY0ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmVjOWVjMGFiZmQzNDhkMjEwNWM2M2ViOTU5OTE4YmQ4MzYzYzRlZmMxZDliNGUzOGI4ZThkYjQzNjkwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrEnQxkOsa2BfTbaWszPbqZjO1vTb1UU5pZVbzMdBeM) ![image](https://private-user-images.githubusercontent.com/72267471/288615281-154fa0b1-d732-4bb0-835a-7d31ebe06a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUyODEtMTU0ZmEwYjEtZDczMi00YmIwLTgzNWEtN2QzMWViZTA2YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjkxNDA5NDkxYWU1ZTMwZmVjZjZjOTI2YjQ5MDAyNGM2Nzk3Zjg3NTJlYjI4ZmMxMDI1N2ZlZjA2YmE1ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J8zEc5GinvIXOGhgcRW340qZGmg_ce9b6iOFI2xUiJM)
> 
> 但是此时视频流没有推上去，播放时是一个绿幕。

流已经推上去了，为何播放时是绿色的，需要你去排查视频源是否有问题

**Comment by hxbamboo** [comment]
> > > 你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，
> > 
> > 
> > 现在是这样的 ![image](https://private-user-images.githubusercontent.com/72267471/288613754-aa2697bb-dc6d-40f3-a08f-7dc19fd87d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTM3NTQtYWEyNjk3YmItZGM2ZC00MGYzLWEwOGYtN2RjMTlmZDg3ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjE2NGE5MjlkOGVlNGZkZjUzODkzOGIzM2U5MWFmZWIzODg2NTk2YjZhNTY5NWZkZjk4OTFjNTFjOWE4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBXQePCexKxIfPTRMS5Qe8_TPTv27b7JaCBbNiTOrdU) 应该是没有注册成功？因为我没有看到注册媒体的消息，我现在应该向哪个方向改？或者需要怎么调整先注册呢
> > 我发现当我把VideoStreamTrackWithCapture这个方法变为这样时他是有注册成功的消息的
> > ```
> > class VideoStreamTrackWithCapture(VideoStreamTrack):
> >     def __init__(self):
> >         super().__init__()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/72267471/288615031-0a552481-aea8-4fc0-93cd-bd1368764811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUwMzEtMGE1NTI0ODEtYWVhOC00ZmMwLTkzY2QtYmQxMzY4NzY0ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmVjOWVjMGFiZmQzNDhkMjEwNWM2M2ViOTU5OTE4YmQ4MzYzYzRlZmMxZDliNGUzOGI4ZThkYjQzNjkwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrEnQxkOsa2BfTbaWszPbqZjO1vTb1UU5pZVbzMdBeM) ![image](https://private-user-images.githubusercontent.com/72267471/288615281-154fa0b1-d732-4bb0-835a-7d31ebe06a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUyODEtMTU0ZmEwYjEtZDczMi00YmIwLTgzNWEtN2QzMWViZTA2YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjkxNDA5NDkxYWU1ZTMwZmVjZjZjOTI2YjQ5MDAyNGM2Nzk3Zjg3NTJlYjI4ZmMxMDI1N2ZlZjA2YmE1ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J8zEc5GinvIXOGhgcRW340qZGmg_ce9b6iOFI2xUiJM)
> > 但是此时视频流没有推上去，播放时是一个绿幕。
> 
> 流已经推上去了，为何播放时是绿色的，需要你去排查视频源是否有问题


好的，谢谢您，我还有一点不解，就是我那段代码建立连接后为什么没有注册

**Comment by xiongguangjie** [comment]
> > > > 你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，
> > > 
> > > 
> > > 现在是这样的 ![image](https://private-user-images.githubusercontent.com/72267471/288613754-aa2697bb-dc6d-40f3-a08f-7dc19fd87d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTM3NTQtYWEyNjk3YmItZGM2ZC00MGYzLWEwOGYtN2RjMTlmZDg3ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjE2NGE5MjlkOGVlNGZkZjUzODkzOGIzM2U5MWFmZWIzODg2NTk2YjZhNTY5NWZkZjk4OTFjNTFjOWE4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBXQePCexKxIfPTRMS5Qe8_TPTv27b7JaCBbNiTOrdU) 应该是没有注册成功？因为我没有看到注册媒体的消息，我现在应该向哪个方向改？或者需要怎么调整先注册呢
> > > 我发现当我把VideoStreamTrackWithCapture这个方法变为这样时他是有注册成功的消息的
> > > ```
> > > class VideoStreamTrackWithCapture(VideoStreamTrack):
> > >     def __init__(self):
> > >         super().__init__()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ![image](https://private-user-images.githubusercontent.com/72267471/288615031-0a552481-aea8-4fc0-93cd-bd1368764811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUwMzEtMGE1NTI0ODEtYWVhOC00ZmMwLTkzY2QtYmQxMzY4NzY0ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmVjOWVjMGFiZmQzNDhkMjEwNWM2M2ViOTU5OTE4YmQ4MzYzYzRlZmMxZDliNGUzOGI4ZThkYjQzNjkwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrEnQxkOsa2BfTbaWszPbqZjO1vTb1UU5pZVbzMdBeM) ![image](https://private-user-images.githubusercontent.com/72267471/288615281-154fa0b1-d732-4bb0-835a-7d31ebe06a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUyODEtMTU0ZmEwYjEtZDczMi00YmIwLTgzNWEtN2QzMWViZTA2YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjkxNDA5NDkxYWU1ZTMwZmVjZjZjOTI2YjQ5MDAyNGM2Nzk3Zjg3NTJlYjI4ZmMxMDI1N2ZlZjA2YmE1ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J8zEc5GinvIXOGhgcRW340qZGmg_ce9b6iOFI2xUiJM)
> > > 但是此时视频流没有推上去，播放时是一个绿幕。
> > 
> > 
> > 流已经推上去了，为何播放时是绿色的，需要你去排查视频源是否有问题
> 
> 好的，谢谢您，我还有一点不解，就是我那段代码建立连接后为什么没有注册

链接建立后，要等待流发送，需要获取到I帧与音频后才会注册（因为有些信息需要这些）

**Comment by hxbamboo** [comment]
> > > > > 你这个流是否注册成功了，是否一直报这个错误，一般是没有找到rtp会话才会报这个错误，一般是没发rtp之前，就发rtp导致的，
> > > > 
> > > > 
> > > > 现在是这样的 ![image](https://private-user-images.githubusercontent.com/72267471/288613754-aa2697bb-dc6d-40f3-a08f-7dc19fd87d99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTM3NTQtYWEyNjk3YmItZGM2ZC00MGYzLWEwOGYtN2RjMTlmZDg3ZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMjE2NGE5MjlkOGVlNGZkZjUzODkzOGIzM2U5MWFmZWIzODg2NTk2YjZhNTY5NWZkZjk4OTFjNTFjOWE4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBXQePCexKxIfPTRMS5Qe8_TPTv27b7JaCBbNiTOrdU) 应该是没有注册成功？因为我没有看到注册媒体的消息，我现在应该向哪个方向改？或者需要怎么调整先注册呢
> > > > 我发现当我把VideoStreamTrackWithCapture这个方法变为这样时他是有注册成功的消息的
> > > > ```
> > > > class VideoStreamTrackWithCapture(VideoStreamTrack):
> > > >     def __init__(self):
> > > >         super().__init__()
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ![image](https://private-user-images.githubusercontent.com/72267471/288615031-0a552481-aea8-4fc0-93cd-bd1368764811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUwMzEtMGE1NTI0ODEtYWVhOC00ZmMwLTkzY2QtYmQxMzY4NzY0ODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZmVjOWVjMGFiZmQzNDhkMjEwNWM2M2ViOTU5OTE4YmQ4MzYzYzRlZmMxZDliNGUzOGI4ZThkYjQzNjkwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lrEnQxkOsa2BfTbaWszPbqZjO1vTb1UU5pZVbzMdBeM) ![image](https://private-user-images.githubusercontent.com/72267471/288615281-154fa0b1-d732-4bb0-835a-7d31ebe06a26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTg2NTcsIm5iZiI6MTcwMTkxODM1NywicGF0aCI6Ii83MjI2NzQ3MS8yODg2MTUyODEtMTU0ZmEwYjEtZDczMi00YmIwLTgzNWEtN2QzMWViZTA2YTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAzMDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjkxNDA5NDkxYWU1ZTMwZmVjZjZjOTI2YjQ5MDAyNGM2Nzk3Zjg3NTJlYjI4ZmMxMDI1N2ZlZjA2YmE1ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J8zEc5GinvIXOGhgcRW340qZGmg_ce9b6iOFI2xUiJM)
> > > > 但是此时视频流没有推上去，播放时是一个绿幕。
> > > 
> > > 
> > > 流已经推上去了，为何播放时是绿色的，需要你去排查视频源是否有问题
> > 
> > 
> > 好的，谢谢您，我还有一点不解，就是我那段代码建立连接后为什么没有注册
> 
> 链接建立后，要等待流发送，需要获取到I帧与音频后才会注册（因为有些信息需要这些）

好的谢谢您，我再去试试
