### ISSUE TITLE
新增MP4下载功能，按照配置说明无法下载

### ISSUE THREAD

**Issue by houjiaxxin** [ZLMediaKit/ZLMediaKit#3092]
新增mp4下载接口，我参考配置文件说明
snapRoot=./www/snap/
#默认截图图片，在启动FFmpeg截图后但是截图还未生成时，可以返回默认的预设图片
defaultSnap=./www/logo.png
#downloadFile http接口可访问文件的根目录，支持多个目录，不同目录通过分号(;)分隔
downloadRoot=./www
配置文件中设置downloadRoot=/sxdata/record/record/rtp
下载链接访问http://10.100.100.162:6080/index/api/downloadFile?file_path=/sxdata/record/record/rtp/34020000001320000029/2023-12-03/16-09-33-12067.mp4
提示信息是:You can not download files outside the root directory,请问是否是程序存在问题还是我配置有不对的地方？

**Comment by xiongguangjie** [comment]
ZLM的日志，你的代码没改过吧

**Comment by houjiaxxin** [comment]
代码没有做过修改
zlm日志是 # 
request: GET /index/api/downloadFile?file_path=/sxdata/record/record/rtp/34020000001320000029/2023-12-03/16-09-33-12067.mp4
# header:
Accept : text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding : gzip, deflate
Accept-Language : zh-CN,zh;q=0.9
Connection : keep-alive
Cookie : SECKEY_ABVK=4/rWW3aB8CSEL+2cSPp6PJ8cUzIe8FsJMLUZrNHCwg6hay/Y/iPjSk6Z00nHDR1PbFjRfAdVoHgzV7wJE+p+OA%3D%3D; BMAP_SECKEY=ZE01iPiTucf7JQhsBUCunVuYbBddThoCOJdJLSKbtdpl1aT5H8rUEr_LFgDzp43hPOyB9Hy7VK3Fio70kJSkAE7LRiTNHJ-3K4QWUpA2hQZdTTcc0ZAhMts57pr5kp7fFih6p-ACUYVOUbzTOBCUaZKVgDiIh5fgtynDxeia3CpraVJUuQLu4wu--o6YadZo
Host : 10.100.100.162:6080
Upgrade-Insecure-Requests : 1
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
# content:

# response:
You can not download files outside the root directory

**Comment by xiongguangjie** [comment]
> downloadFile

根本没有downloadFile 这个接口，你要我怎么排查

**Comment by xiongguangjie** [comment]
你这个mp4_save_path 的配置是什么，要与这个保持一致的，同时修改配置文件后，需要重启服务才行的

**Comment by houjiaxxin** [comment]
mp4_save_path  与 downloadRoot=/sxdata/record/record/rtp  是一样的，配置完之后服务重启过了。

**Comment by houjiaxxin** [comment]
[2023-12-09_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13622334/2023-12-09_00.log)

**Comment by houjiaxxin** [comment]
> > mp4_save_path 与 downloadRoot=/sxdata/record/record/rtp 是一样的，配置完之后服务重启过了。
> 
> 完整的ZLM日志上传下，打开http的调试日志

[2023-12-09_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13622335/2023-12-09_00.log)

**Comment by houjiaxxin** [comment]
附上zlm config.ini相关配置
[api]
#是否调试http api,启用调试后，会打印每次http请求的内容和回复
apiDebug=1
#一些比较敏感的http api在访问时需要提供secret，否则无权限调用
#截图保存路径根目录，截图通过http api(/index/api/getSnap)生成和获取
snapRoot=./www/snap/
#默认截图图片，在启动FFmpeg截图后但是截图还未生成时，可以返回默认的预设图片
defaultSnap=./www/logo.png
#mp4下载路径设置
download_roots=/sxdata/record/record/rtp
[cluster]
origin_url=
retry_count=3
timeout_sec=15

[protocol]
#转协议时，是否开启帧级时间戳覆盖
modify_stamp=0
#转协议是否开启音频
enable_audio=0
#添加acc静音音频，在关闭音频时，此开关无效
add_mute_audio=1
#推流断开后可以在超时时间内重新连接上继续推流，这样播放器会接着播放。
#置0关闭此特性(推流断开会导致立即断开播放器)
#此参数不应大于播放器超时时间;单位毫秒
continue_push_ms=15000

#是否开启转换为hls
enable_hls=0
#是否开启MP4录制
enable_mp4=1
#是否开启转换为rtsp/webrtc
enable_rtsp=1
#是否开启转换为rtmp/flv
enable_rtmp=1
#是否开启转换为http-ts/ws-ts
enable_ts=0
#是否开启转换为http-fmp4/ws-fmp4
enable_fmp4=0

#是否将mp4录制当做观看者
mp4_as_player=0
#mp4切片大小，单位秒
mp4_max_second=20
#mp4录制保存路径
mp4_save_path=/sxdata/record/record/rtp

#hls录制保存路径
hls_save_path=./www

**Comment by xiongguangjie** [comment]
> > > mp4_save_path 与 downloadRoot=/sxdata/record/record/rtp 是一样的，配置完之后服务重启过了。
> > 
> > 
> > 完整的ZLM日志上传下，打开http的调试日志
> 
> [2023-12-09_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13622335/2023-12-09_00.log)

配置文件上传下，这个明显是downloadRoot 这个没设置正确

**Comment by houjiaxxin** [comment]
> > > > mp4_save_path 与 downloadRoot=/sxdata/record/record/rtp 是一样的，配置完之后服务重启过了。
> > > 
> > > 
> > > 完整的ZLM日志上传下，打开http的调试日志
> > 
> > 
> > [2023-12-09_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13622335/2023-12-09_00.log)
> 
> 配置文件上传下，这个明显是downloadRoot 这个没设置正确

[config.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/13622560/config.txt)

**Comment by xiongguangjie** [comment]
这个代码有些问题，先不要用这个接口（我不清楚这个接口设计的原因），你可以使用virtualPath 的配置选项来实现类似的需求

**Comment by xiongguangjie** [comment]
这个是接口上做了限制， file_path 只能是程序所在目录下的文件(downloadRoot 是一个相对路径，不是绝对路径)，如下所示
 程序路径 /home/MediaServer
downloadRoot=/sxdata/record/record/rtp
file_path 应该为 /home/sxdata/record/record/rtp/xxxx/xxxx/xxx.mp4 才能下载成功，其他的路径都会报错的

**Comment by xiongguangjie** [comment]
> 十分感谢，这个接口下载功能确实有很方便，不过这个限制在很多时候就没法用了，录像存储一般都是单独存放在独立大容量磁盘或者空间里，跟应用是隔离开的。已经很感谢了，辛苦

可以用虚拟路径 virtualPath，这个是配置选项，看配置文件的说明就行了

**Comment by houjiaxxin** [comment]
ok

**Comment by houjiaxxin** [comment]
很抱歉，说一下，按照虚拟目录方式还是走不通，这个功能我先不用了，等看看后面是否有更新吧

**Comment by xiaohuiL** [comment]
你好，我也遇到这个问题了，能修改的路径都改过了，都不行。你这边解决了吗？

**Comment by sincebyte** [comment]
我也遇到这个问题了，一般录像文件会单独放，肯定不和流媒体启动路径放在一起。

**Comment by wyfKelly** [comment]
zlm 重新编译部署，不放在root根目录下，就不会有这个问题
