### ISSUE TITLE
[技术咨询] 国标回放的时候出现 flv播放器一般只支持H264和AAC编码,该编码格式可能不被播放器支持:PCMA 什么原因导致的

### ISSUE THREAD

**Issue by WalkerPlus** [ZLMediaKit/ZLMediaKit#3105]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
> 国标回放的时候出现 flv播放器一般只支持H264和AAC编码,该编码格式可能不被播放器支持:PCMA 是 什么原因导致的

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个是播放器的原因,flv.js 是不支持pcma 的，可以换其他播放器，rtc 播放器支持pcma
