### ISSUE TITLE
音频格式设置优先顺序无效

### ISSUE THREAD

**Issue by Mrxufor** [ZLMediaKit/ZLMediaKit#3125]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
config.ini配置咨询
**咨询的具体内容和问题**
配置文件配置了preferredCodecA=mpeg4-generic,opus,PCMA,PCMU
但是不是优先使用mpeg4-generic的音频格式，是需要怎么设置呢

**Comment by xiongguangjie** [comment]
配置文件里面不是有说明吗？？？

**Comment by Mrxufor** [comment]
> 配置文件里面不是有说明吗？？？

现在主要是遇到一个问题，我大华摄像头配置的音频编码是AAC，但是音频编码却返回了PCMA，不知道是什么原因

**Comment by xiongguangjie** [comment]
> > 配置文件里面不是有说明吗？？？
> 
> 现在主要是遇到一个问题，我大华摄像头配置的音频编码是AAC，但是音频编码却返回了PCMA，不知道是什么原因

这个只针对rtc 有效，你大华摄像机，只能通过gb28181或者rtsp取流吧

**Comment by Mrxufor** [comment]
> > > 配置文件里面不是有说明吗？？？
> > 
> > 
> > 现在主要是遇到一个问题，我大华摄像头配置的音频编码是AAC，但是音频编码却返回了PCMA，不知道是什么原因
> 
> 这个只针对rtc 有效，你大华摄像机，只能通过gb28181或者rtsp取流吧

目前是通过gb28181，平台的话是使用WVP，主要是不知道为什么返回的音频编码为什么不对了，然后当时一直解决是不是那个配置的问题。

**Comment by xiongguangjie** [comment]
> > > > 配置文件里面不是有说明吗？？？
> > > 
> > > 
> > > 现在主要是遇到一个问题，我大华摄像头配置的音频编码是AAC，但是音频编码却返回了PCMA，不知道是什么原因
> > 
> > 
> > 这个只针对rtc 有效，你大华摄像机，只能通过gb28181或者rtsp取流吧
> 
> 目前是通过gb28181，平台的话是使用WVP，主要是不知道为什么返回的音频编码为什么不对了，然后当时一直解决是不是那个配置的问题。

这个是设备端决定的，与服务器没关系
