### ISSUE TITLE
[技术咨询] 使用rtsp/rtmp推流，webrtc拉流失败，找不到流

### ISSUE THREAD

**Issue by DDL-IN-MY-AGENDA** [ZLMediaKit/ZLMediaKit#3137]
**咨询的功能模块**
- 协议互转 rtsp/rtmp推流-->webrtc拉流

**咨询的具体内容和问题**
- 看介绍是支持多种协议互转的，我想使用rtsp推 webrtc拉，测试一下时延；rtsp推流上去后，用webrtc拉不到
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/81623093/1ea6f662-4818-48e7-951e-041e91a0bdc5)
webrtc客户端日志文件：
[webrtc 控制台日志.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13695499/webrtc.log)

rtsp和rtmp可以正常拉流

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by DDL-IN-MY-AGENDA** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/81623093/1cc3ff84-498d-42a8-8008-5d78490c430b)
服务端日志截图

**Comment by DDL-IN-MY-AGENDA** [comment]
rtsp.directProxy=1
单纯使用webrtc拉流和推流正常；内网环境

**Comment by xiongguangjie** [comment]
你stream没填对

**Comment by DDL-IN-MY-AGENDA** [comment]
> 你stream没填对

感谢回复！确实是流没填对；我换成了https://10.14.2.7/index/api/webrtc?app=live&stream=livestream&type=play，这个stream应该是对的吧。现在服务端有响应，无明显报错，客户端控制台输出conected后一段才输出连接不上，使用的是rtsp推流，rtsp拉流正常，但是webrtc播放不出来画面，一直转圈圈
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/81623093/57435c4a-4dfa-4a70-beeb-a7beed860d5f)
[控制台.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13701870/default.log)
[服务端日志 (2).log](https://github.com/ZLMediaKit/ZLMediaKit/files/13701885/2.log)

**Comment by xiongguangjie** [comment]
> Reference in ne

rtsp directProxy 设置为0

**Comment by DDL-IN-MY-AGENDA** [comment]
> > Reference in ne
> 
> rtsp directProxy 设置为0

改成0确实可以了，没注意看 我以为是要设置为1；感谢大佬问题解决了
