### ISSUE TITLE
[技术咨询] IPC推送H265的视频流到ZLMediakit报错

### ISSUE THREAD

**Issue by aidelingyu** [ZLMediaKit/ZLMediaKit#3138]
@
**咨询的功能模块**
- 视频流播放

**咨询的具体内容和问题**
- 网络摄像头通过GB28181的协议将H265视频流推送到zlm。如果使用本地编译的zlm，控制台会报错，导致H265编码的视频流无法播放。如果使用docker部署的zlm，就可以正常播放H265的视频流。想咨询一下docker和本地编译的代码有什么区别？我看git中提到需要修改ffmpeg的源码，我已经从gitee上下载了夏老师发布的ffmpeg源码并重新编译了，还是无法解决本地zlm不能播放H265的问题。请问夏老师，如果要本地zlm支持H265，除了重新编译ffmpeg，还需要修改zlm的代码吗？
保存信息如下：
![265报错](https://github.com/ZLMediaKit/ZLMediaKit/assets/23529219/df3769f2-96a4-41a5-a293-4b45117b8763)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
保存ps 与rtp的dump(具体看配置文件的注释)，然后上传上来，我来分析下

**Comment by aidelingyu** [comment]
@xiongguangjie 配置文件中，我把rtp_proxy下的dumpDir设置了路径，生成了3个文件，我压缩到一起了。麻烦老师帮忙给看一下。
[zlmPackage.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/13700365/zlmPackage.zip)

**Comment by xiongguangjie** [comment]
> @xiongguangjie 配置文件中，我把rtp_proxy下的dumpDir设置了路径，生成了3个文件，我压缩到一起了。麻烦老师帮忙给看一下。 [zlmPackage.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/13700365/zlmPackage.zip)

我分析了这三个文件，发现都是正常的呀，没有什么问题呀，你要上传出现问题的文件，不是正常的

**Comment by aidelingyu** [comment]
@xiongguangjie 这3个文件就是播放不出来的时候产生的文件。摄像头推这个流的时候，zlm日志就是提示ps解析失败，页面上提示播放超时。所以我才很疑惑，用docker部署的zlm就没这个问题，我本地编译的zlm的就这个问题。
![11](https://github.com/ZLMediaKit/ZLMediaKit/assets/23529219/78083774-65e6-4df2-aadf-4a20121c722e)

**Comment by aidelingyu** [comment]
@xiongguangjie 我发的3个文件中视频时间 和 报错日志的时间是吻合的。而且我这个平台上只有这一个摄像头，不存在有其他设备的冲突。

**Comment by xiongguangjie** [comment]
> @xiongguangjie 这3个文件就是播放不出来的时候产生的文件。摄像头推这个流的时候，zlm日志就是提示ps解析失败，页面上提示播放超时。所以我才很疑惑，用docker部署的zlm就没这个问题，我本地编译的zlm的就这个问题。

使用最新的代码，然后看看submodule 是不是最新的

**Comment by aidelingyu** [comment]
@xiongguangjie 我重新从 https://gitee.com/xia-chu/ZLMediaKit拉取了master分支的代码，重新编译。通过rtp_proxy生成的文件可以播放，但zlm日志还是说解析ps异常。

**Comment by aidelingyu** [comment]
@xiongguangjie 我重新从  https://gitee.com/xia-chu/ZLMediaKit 拉取了master分支的代码，重新编译。通过rtp_proxy生成的文件可以播放，但zlm日志还是说解析ps异常。

**Comment by xiongguangjie** [comment]
> @xiongguangjie 我重新从 https://gitee.com/xia-chu/ZLMediaKit 拉取了master分支的代码，重新编译。通过rtp_proxy生成的文件可以播放，但zlm日志还是说解析ps异常。

我这边怎么正常，没有报错，你从github 拉取试一下

**Comment by aidelingyu** [comment]
@xiongguangjie 我从github上拉了zlm的代码，播放h265还是一样的报错。大神你那边是正常的？能把你那边的zlm代码打包发我，我在本地编译试一下吗？

**Comment by aidelingyu** [comment]
@xiongguangjie 我仔细查看zlm的报错日志，发现接收摄像头H265视频流报错的方法，是第三方库media-server中libmpeg模块下的 mpeg-psm.c文件中的psm_read方法。该方法中有一个assert判断，`assert(mpeg_bits_tell(reader) == off + element_stream_info_length);`错误就是这个判断导致的。我尝试把该校验注释了，重新编译zlm代码，就可以正确接收摄像头推送的H265视频流了。大神你知道这个判断有什么用吗？

**Comment by xiongguangjie** [comment]
> @xiongguangjie 我仔细查看zlm的报错日志，发现接收摄像头H265视频流报错的方法，是第三方库media-server中libmpeg模块下的 mpeg-psm.c文件中的psm_read方法。该方法中有一个assert判断，`assert(mpeg_bits_tell(reader) == off + element_stream_info_length);`错误就是这个判断导致的。我尝试把该校验注释了，重新编译zlm代码，就可以正确接收摄像头推送的H265视频流了。大神你知道这个判断有什么用吗？

奇怪，你是release 编译吗，子模块的版本是对应的吧？

**Comment by aidelingyu** [comment]
@我就按照github中的步骤来编译的。
1、先拉代码。
2、进入源码根目录，执行git submodule update --init
3、在根目录下创建build目录
4、进入build目录，执行cmake ..
5、然后执行make
编译好后的文件在 <源码根目录>/release/linux/Debug下。
如果我把那个assert去掉不知道长时间使用会不会出现问题。
