### ISSUE TITLE
[BUG] 使用容器部署zlm之后，rtsp流无法播放

### ISSUE THREAD

**Issue by iwanlebron** [ZLMediaKit/ZLMediaKit#3157]
rtsp不能播放
<img width="739" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/70838c00-bd35-420d-a0a9-2b9bdd63b86c">

rtmp流可以播放
<img width="966" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/66f4697a-07ea-404c-9754-36111ff84a4f">

端口已经放开了
<img width="773" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/d37d3073-76af-4fc6-8f76-75b0ff33e6d0">

**Comment by iwanlebron** [comment]
这是配置

; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
secret=RYi7a5ZWhOkOQ8t04Q7q9hSZmjHvfuek
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/local/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s

[general]
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=FQ3TF8yT83wh5Wvz
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fileBufSize=65536
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://172.24.12.103:18978/index/hook/on_play
on_publish=http://172.24.12.103:18978/index/hook/on_publish
on_record_mp4=
on_record_ts=
on_rtp_server_timeout=http://172.24.12.103:18978/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://172.24.12.103:18978/index/hook/on_send_rtp_stopped
on_server_exited=https://127.0.0.1:18978/index/hook/on_server_exited
on_server_keepalive=http://172.24.12.103:18978/index/hook/on_server_keepalive
on_server_started=http://172.24.12.103:18978/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://172.24.12.103:18978/index/hook/on_stream_changed
on_stream_none_reader=http://172.24.12.103:18978/index/hook/on_stream_none_reader
on_stream_not_found=http://172.24.12.103:18978/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=20

[http]
allow_cross_domains=1
allow_ip_range=127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:fef85da/2023-08-31T10:53:46+08:00,branch:master,build time:2023-09-02T18:42:57)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
port=8000
preferredCodecA=PCMU,PCMA,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
tcpPort=8000
timeoutSec=15

[rtmp]
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
timeoutSec=15

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

**Comment by xiongguangjie** [comment]
流是怎么产生的（推流还是什么？）ZLM的日志上传上来

**Comment by iwanlebron** [comment]
通过obs推流的 
[zlm.log](https://github.com/ZLMediaKit/ZLMediaKit/files/13758461/zlm.log)

**Comment by xiongguangjie** [comment]
rtsp播放失败，是因为使用了udp需要 使用tcp播放（docker有网络隔离）；rtmp 播放失败是因为客户端主动断开了链接

**Comment by iwanlebron** [comment]
通过从容器映射出来的端口rtsp推流 ffmpeg推流进程会一直断 无法稳定推流
