### ISSUE TITLE
开启webrtc编译问题

### ISSUE THREAD

**Issue by Jason5592** [ZLMediaKit/ZLMediaKit#3159]
RUN cd /home/ZLMediaKit && \
        git submodule update --init --recursive && \
        mkdir -p build release/linux/Release/ &&\
        cd build && \
        cmake -DCMAKE_BUILD_TYPE=Release .. -DENABLE_WEBRTC=true && \
        cmake --build . --target MediaServer && \
        make -j4 && \
        rm -rf ../release/linux/Release/config.ini && \
        cp -r ../release/linux/Release/* /opt/media

**Comment by Jason5592** [comment]
编译时已开启webrtc

**Comment by Jason5592** [comment]
Request URL:
http://10.3.50.226:3001/index/api/webrtc?app=rtp&stream=50010600001320000210_50010600001310000210&type=play
Request Method:
POST
Status Code:
404 Not Found

**Comment by mtdxc** [comment]
要求有openssl和srtp，具体编译指令详见.github\workflows\linux.yml

**Comment by Jason5592** [comment]
感谢大佬，已解决
