### ISSUE TITLE
使用/addStreamProxy添加rtsp流，没人观看自动关闭流问题

### ISSUE THREAD

**Issue by lvzhouzhijun** [ZLMediaKit/ZLMediaKit#3168]
**咨询的功能模块**
- addStreamProxy添加rtsp流

**咨询的具体内容和问题**
- 我添加rtsp流，配置的是10分钟没人观看自动关闭流，但是我开启了录播功能，10分钟之后把我的录播也关闭了，我想在录播的时候不关闭流，有没有解决办法

**Comment by xiongguangjie** [comment]
mp4_as_player 配置设置为1

**Comment by lvzhouzhijun** [comment]
> mp4_as_player 配置设置为1

多谢老哥

**Comment by lvzhouzhijun** [comment]
> mp4_as_player 配置设置为1

我设置了，好像没用
