### ISSUE TITLE
[Technical Consultation] EHOME display flickers.

### ISSUE THREAD

**Issue by kaikaimiao** [ZLMediaKit/ZLMediaKit#3173]
Docker 环境下使用海康摄像头+freeehome配合实现ehome协议推流出来的视频会出现屏幕出错（花屏）的情况，您认为这是什么原因？

>docker 环境下使用海康摄像头+freeehome配合实现ehome协议推出来的流播放出来是花屏的情况，请问是什么原因

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by jiubiezaiyujianwole** [comment]
我也遇到这个问题，暂时还没有有效解决办法
