### ISSUE TITLE
摄像头配置的音频为aac或者是其他 有有时候会出现audio track ignored的情况

### ISSUE THREAD

**Issue by shishuai19910217** [ZLMediaKit/ZLMediaKit#3176]
摄像头配置的音频为aac或者是其他 有有时候会出现audio track ignored的情况
摄像头内置配置如下
![nei](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/f9b17fd7-9eae-4de3-862c-250d4e086012)
web页面显示编码没有音频
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/b081624c-1783-4974-8073-93bee8f2aadf)
log日志截图如下
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/c1bf1173-bb60-44bc-9203-10a4018da9df)
请问：这是什么问题导致的  ？（当前摄像头是支持传输音频的  ）

**Comment by xiongguangjie** [comment]
配置文件，已经禁止音频了呀

**Comment by shishuai19910217** [comment]
@xiongguangjie   老师您好,您说的配置文件是 zlm 的配置文件吧 ；我是明确打开了相关的配置的如下：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/6ca6a85e-e2f2-4eaf-aed0-3d694fd7fa81)
但是日志中还是
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/f7b0d6b3-d95a-4022-94f7-9c37866f00b4)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/6db38e01-9325-4eaa-99f8-09162e24c7c9)

**Comment by shishuai19910217** [comment]
> 配置文件，已经禁止音频了呀

老师您好，您说的配置文件是zlm的配置文件吧；我是明确打开了相关的配置的如下： 但是日志中还是
图像

图像
图像

@石帅19910217


添加评论
评论

**Comment by shishuai19910217** [comment]
@xiongguangjie 老师，而且我在摄像头的内置页面 将国标平台的地址修改成其他国标平台（在其他平台正常注册）后再换回当前平台再使用当前平台播放就有声音了如下图：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/44633525/06a9abc0-b8b3-4a48-963f-dd9189c64046)
两次的配置文件是一样的
