### ISSUE TITLE
[BUG] GB28181 RTP Jitterbuffer崩溃

### ISSUE THREAD

**Issue by 286897655** [ZLMediaKit/ZLMediaKit#3177]
### 现象描述

我这里使用ZLMediakit是当做一个第三方库使用的，其中GB28181的收流部分因为我们的业务逻辑和ZLM本身的GB28181不太一致，所以我们业务流程上重新做了开发，但是总体的步骤是一致的。在大多数环境都是好的，但是最近的一个我们的业务环境下，经常崩溃在Jitterbuffer上

### 如何复现?
不好复现，长时间传输流，且偶发崩溃
接入的摄像头是TP-LINK品牌的 就这里的会导致jitterbuffer崩溃，别的海康的就没啥问题
有生成的core文件和崩溃调用栈
### 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16201246/242d861e-e8e9-4ede-a1b9-7bd0aff1cf18)

### 配置
ZLMediakit当做库用，配置从程序中进行的配置
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16201246/407091bd-1779-4196-9988-dd8331c3a0b2)

### 各种环境信息
摄像头-TP-LINK 具体型号未知
服务器Centos-7.9
代码最新版本也有该问题

**Comment by xiongguangjie** [comment]
这个我看了下，发现你的sortPacket 中参数 packet 为空指针，这个应该是你的代码修改得有问题，一般除非你使用了onBeforeRtpSorted 回调，才会有置空的机会。
如果有二次开发的代码，就意味着，有二次开发调试的能力，这种问题不应该在issue 中提出，应该自己解决。

**Comment by 286897655** [comment]
> 这个我看了下，发现你的sortPacket 中参数 packet 为空指针，这个应该是你的代码修改得有问题，一般除非你使用了onBeforeRtpSorted 回调，才会有置空的机会。 如果有二次开发的代码，就意味着，有二次开发调试的能力，这种问题不应该在issue 中提出，应该自己解决。

我也很疑惑那里那个rtp packet为什么打印的是empty，rtp包路径我们和ZLM的GB28181基本是一致的 onBeforeRtpSorted 都是没有使用的。

**Comment by 286897655** [comment]
> 这个我看了下，发现你的sortPacket 中参数 packet 为空指针，这个应该是你的代码修改得有问题，一般除非你使用了onBeforeRtpSorted 回调，才会有置空的机会。 如果有二次开发的代码，就意味着，有二次开发调试的能力，这种问题不应该在issue 中提出，应该自己解决。

我看了下代码 那里那个packet为空是正常的，因为在75行 放到 _pkt_sort_cache_map 中缓存调用了 std::move 所以这里packet为nullptr了，我们的调用栈是78行 所以是合理的

**Comment by 286897655** [comment]
这个问题已经搞清楚了，和摄像头来了两个连接的关系导致了多线程操作，和jitterbuffer无关。先关闭了。
