### ISSUE TITLE
[BUG] 通过ps拉流 发现以下报错  

### ISSUE THREAD

**Issue by iwanlebron** [ZLMediaKit/ZLMediaKit#3194]
<img width="1400" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/ff41bfeb-f4f9-4aec-9bcb-e75eb216a80d">

基于最新版master分支编译

**Comment by monktan89** [comment]
你是不是没启用rtsp协议？

**Comment by iwanlebron** [comment]
起了

**Comment by monktan89** [comment]
> 起了

看看流注册时候zlm的日志
