### ISSUE TITLE
通过api已设置配置"http.allow_ip_range": ""，但是非容器网段访问还是会提示跨域

### ISSUE THREAD

**Issue by qilaohan** [ZLMediaKit/ZLMediaKit#3196]
**咨询的功能模块**
- 修改配置后前端播放flv视频格式依然提示跨域

**咨询的具体内容和问题**
- 使用容器部署，容器ip网段为172.16.5.169 使用同网段的172.16.5.228可正常播放视频
![1704771674957](https://github.com/ZLMediaKit/ZLMediaKit/assets/35245215/2d09c39a-3dfe-4254-886a-6a77f165c472)
![1e3da75460ee61d4f547a6f9bc5f9eb](https://github.com/ZLMediaKit/ZLMediaKit/assets/35245215/440d8314-2a64-4acd-a6bb-07dbfe4c9fda)
上图播放电脑ip端为172.16.251.157 网关为172.16.248.1  

已提前看了issues的相关问题，大家好像都是c开发的，我不懂c，然后容器部署后，登录容器查看了/opt/conf/config.ini同接口返回，已为空了

麻烦大佬了，开源不易，非常感谢！！！！

**Comment by xiongguangjie** [comment]
配置文件中，allow_cross_domains 设置为1

**Comment by qilaohan** [comment]
设置为1了，通过接口拿到配置也是1，见上面的第一张图@ @xiongguangjie

**Comment by qilaohan** [comment]
我是昨天部署的最新的master镜像 @xiongguangjie

**Comment by xiongguangjie** [comment]
这个不会呀，你这个url地址是不是ZLM的地址呀

**Comment by qilaohan** [comment]
url是zlm宿主机的ip，8080->80,按git的容器启动命令启动的，5.228是我windows电脑ip，5.169是windows电脑上虚拟机（zlm容器的宿主机）的ip，用jessibuca网页测试时发现只有我windows电脑上不会报跨域，其它电脑都会，zlm的日志能打印正确的其它电脑的ip

**Comment by qilaohan** [comment]
我换了一台物理机centos 通过容器部署后测试还是存在跨域问题，配置均已修改
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/35245215/c0806d8f-49d6-4644-ac62-46b417104bc0)
是否是镜像zlm用的不是/opt/media/conf/config.ini配置文件？这个我不得而知了，不知道其他兄弟有没有碰到这个问题

**Comment by qilaohan** [comment]
昨天用nginx代理然后加了响应头，发现之前报跨域的那台电脑还是会报跨域，所以确定不是ZLM的问题，今天早上在那台机装了抓包工具还没抓，结果就又不报跨域了，一次神奇的经历。  
排查步骤记录下：关闭zlm的允许跨域开关，自行通过nginx代理添加响应头，然后测试浏览器是否跨域，多用几个浏览器和电脑多测，有问题抓http包查看
