### ISSUE TITLE
获取截图或生成实时截图并返回接口 /index/api/getSnap，现在只返回zlmediakit 的logo

### ISSUE THREAD

**Issue by szj129766** [ZLMediaKit/ZLMediaKit#3199]
很早之前还是 好的，几周前更新的代码就不行了
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/51728146/b6d55dde-103d-4155-b2e7-92400b6810b2)

麻烦处理一下谢谢

**Comment by xiongguangjie** [comment]
日志，ffmpeg 的日志，你啥都没有

**Comment by szj129766** [comment]
这个是zlm 的日志
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/51728146/3de81cd5-1fec-479c-844d-dea58433ff39)

ffmpeg 的日志为 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/51728146/be812346-e9be-43b9-a3a4-e17a69cfe21c)

**Comment by xiongguangjie** [comment]
> 这个是zlm 的日志 ![image](https://private-user-images.githubusercontent.com/51728146/295510091-3de81cd5-1fec-479c-844d-dea58433ff39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODI4MzUsIm5iZiI6MTcwNDg4MjUzNSwicGF0aCI6Ii81MTcyODE0Ni8yOTU1MTAwOTEtM2RlODFjZDUtMWZlYy00NzljLTg0NGQtZGVhNTg0MzNmZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YmQwZDZmOGZmOTFiYzM3NDE3ZmU1ZDE1N2ZjZWI4NmMwM2VjYWUyY2EzMzg2NjQ5NDdmODU4ZjJhMTEwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQnQX-KteaUcjkYAF5lQ5QUGMEfWNIY-x0l6hXSt8KE)
> 
> ffmpeg 的日志为 ![image](https://private-user-images.githubusercontent.com/51728146/295509920-be812346-e9be-43b9-a3a4-e17a69cfe21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODI4MzUsIm5iZiI6MTcwNDg4MjUzNSwicGF0aCI6Ii81MTcyODE0Ni8yOTU1MDk5MjAtYmU4MTIzNDYtZTliZS00M2I5LWEzYTQtZTE3YTY5Y2ZlMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNWI4MDc3MGE5NDMxODdhZDU3M2JlYzBlODMzMTY4MmM1OTM1YTMxNDhiZmYxMWRiYzJmODJkZjA4YWRmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7JLR4WT2pgsjYWmmxFjZSGi9zq5N7nqM8TIxCTjZ1U)
找不到ffmpeg 呀，ffmpeg 没安装吧，或者找不到安装的路径

**Comment by szj129766** [comment]
> > 这个是zlm 的日志![图像](https://private-user-images.githubusercontent.com/51728146/295510091-3de81cd5-1fec-479c-844d-dea58433ff39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODI4MzUsIm5iZiI6MTcwNDg4MjUzNSwicGF0aCI6Ii81MTcyODE0Ni8yOTU1MTAwOTEtM2RlODFjZDUtMWZlYy00NzljLTg0NGQtZGVhNTg0MzNmZjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YmQwZDZmOGZmOTFiYzM3NDE3ZmU1ZDE1N2ZjZWI4NmMwM2VjYWUyY2EzMzg2NjQ5NDdmODU4ZjJhMTEwZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kQnQX-KteaUcjkYAF5lQ5QUGMEfWNIY-x0l6hXSt8KE)
> > ffmpeg 的日志为 ![图像](https://private-user-images.githubusercontent.com/51728146/295509920-be812346-e9be-43b9-a3a4-e17a69cfe21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4ODI4MzUsIm5iZiI6MTcwNDg4MjUzNSwicGF0aCI6Ii81MTcyODE0Ni8yOTU1MDk5MjAtYmU4MTIzNDYtZTliZS00M2I5LWEzYTQtZTE3YTY5Y2ZlMjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDEwMjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNWI4MDc3MGE5NDMxODdhZDU3M2JlYzBlODMzMTY4MmM1OTM1YTMxNDhiZmYxMWRiYzJmODJkZjA4YWRmZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7JLR4WT2pgsjYWmmxFjZSGi9zq5N7nqM8TIxCTjZ1U)
> > 找不到ffmpeg 呀，ffmpeg 没安装吧，或者找不到安装的路径

有ffmpeg的 ，我视频都可以播放的 其他都正常的 就这个截图有问题的

**Comment by ygxw** [comment]
我也遇到这个问题了，请问楼主怎么解决的

**Comment by szj129766** [comment]
配置里面的&nbsp; ffmpeag地址改一下




你叼个瘠薄
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月17日(星期六) 下午5:26
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] 获取截图或生成实时截图并返回接口 /index/api/getSnap，现在只返回zlmediakit 的logo (Issue #3199)





 
我也遇到这个问题了，请问楼主怎么解决的

**Comment by ygxw** [comment]
> 配置里面的&nbsp; ffmpeag地址改一下 你叼个瘠薄 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ZLMediaKit/ZLMediaKit" ***@***.***&gt;; 发送时间:&nbsp;2024年2月17日(星期六) 下午5:26 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] 获取截图或生成实时截图并返回接口 /index/api/getSnap，现在只返回zlmediakit 的logo (Issue #3199) 我也遇到这个问题了，请问楼主怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

昨天我这边也解决了，和你的问题不一样，我是ffmpeg地址配置对了的，只是截图的指令官方默认配置的rtsp，但是我用的不是rtsp的url。所以总结来说，都是ffmpeg截图相关操作错误，这是根源。

**Comment by lobster02** [comment]
请问 你们是如何修改的?

**Comment by ygxw** [comment]
> 请问 你们是如何修改的?

1、楼主遇到的问题是ffmpeg地址错误，你看下zlm的config.ini文件里ffmpeg配置的地址对不对，一般通过系统安装包安装的ffmpeg一般都可以，我估计楼主是自己编译的ffmpeg，所以需要重新修改ffmpeg地址。
2、我ffmpeg地址是对的，我错误的原因是config.ini截图指令用的官方默认的rtsp地址，结果我传的不是rtsp地址导致的，所以我就没改config.ini里的命令了，我直接把我们系统调用截图穿的那个媒体url地址改成rtsp就行了。

**Comment by lobster02** [comment]
谢谢，我尝试使用 http...flv 这种url，也可以实现截图功能。

**Comment by answer666** [comment]
> 致

你好，请问下 ffmpeg 的地址修改成什么呢？
