### ISSUE TITLE
[技术咨询] 如何设置录像文件的参数以降低录像文件体积？

### ISSUE THREAD

**Issue by YTed** [ZLMediaKit/ZLMediaKit#3200]
**咨询的功能模块**
视频录像功能

**咨询的具体内容和问题**
我使用 wvp-pro+zlmediakit  搭建了一个国标平台，接入了若干路海康摄像头视频，其中 7 路做了云端录像。

现在发现一个问题，录像文件体积太大了，服务器的 3T 硬盘 10 天不到就存满了，请问是否有方法设置录像文件大小？

**Comment by xiongguangjie** [comment]
不行这个是由终端编码决定的，除非转码，否则很难降低录像文件大小

**Comment by answer666** [comment]
> **咨询的功能模块** 视频录像功能
> 
> **咨询的具体内容和问题** 我使用 wvp-pro+zlmediakit 搭建了一个国标平台，接入了若干路海康摄像头视频，其中 7 路做了云端录像。
> 
> 现在发现一个问题，录像文件体积太大了，服务器的 3T 硬盘 10 天不到就存满了，请问是否有方法设置录像文件大小？

请问你怎么解决的啊？ 现在我也碰到了这个问题，怎么最小化减小内存占用
