### ISSUE TITLE
[技术咨询] 咨询描述(必填) 是否支持工业相机协议 gvcp或者gvsp

### ISSUE THREAD

**Issue by deilsky** [ZLMediaKit/ZLMediaKit#3203]
想咨询一下大佬作者：是否支持工业相机协议 gvcp或者gvsp；

**Comment by xiongguangjie** [comment]
这个不支持，我没听过这个协议，我还网上搜索了下，填补了我的知识空白

**Comment by deilsky** [comment]
> 这个不支持，我没听过这个协议，我还网上搜索了下，填补了我的知识空白
大佬，以后会考虑支持这几个工业相机协议么？

**Comment by xiongguangjie** [comment]
> > 这个不支持，我没听过这个协议，我还网上搜索了下，填补了我的知识空白
> > 大佬，以后会考虑支持这几个工业相机协议么？

基本上不会，这个特殊行业才会用到，除非工作中遇到了

**Comment by deilsky** [comment]
> > > 这个不支持，我没听过这个协议，我还网上搜索了下，填补了我的知识空白
> > > 大佬，以后会考虑支持这几个工业相机协议么？
> 
> 基本上不会，这个特殊行业才会用到，除非工作中遇到了
好的，感谢大佬解答。
