### ISSUE TITLE
新版本服务器用FFMPEG推流出现问题，旧版本推流正常。

### ISSUE THREAD

**Issue by zwfcz** [ZLMediaKit/ZLMediaKit#3205]
新版本服务器用FFMPEG推流出现问题，旧版本推流正常。
以下是在新版本中用FFMPEG推流后出现的问题。所以新版没办法用FFMPEG推流。
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/BoRB':
  Metadata:
    encoder         : Lavf58.18.104
    Stream #0:0: Video: h264 (Main) ([7][0][0][0] / 0x0007), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 30 fps, 30 tbr, 1k tbn, 60 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
av_interleaved_write_frame(): Broken pipe
[flv @ 0x6d8b240] Failed to update header with correct duration.
[flv @ 0x6d8b240] Failed to update header with correct filesize.
Error writing trailer of rtmp://127.0.0.1:1935/live/BoRB: Broken pipe
frame=   54 fps=0.0 q=-1.0 Lsize=     453kB time=00:00:01.73 bitrate=2140.1kbits/s speed=1.01e+03x    
video:1626kB audio:7kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed

**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by monktan89** [comment]
ffmpeg版本是多少？推流命令是什么，发出来看看吧

**Comment by zwfcz** [comment]
问题解决了，修改了FFMPEG命令就可以了

**Comment by kevin2027** [comment]
> 问题解决了，修改了FFMPEG命令就可以了

修改了什么，我也遇到了
