### ISSUE TITLE
[技术咨询] getRecordStatus请求参数和响应参数

### ISSUE THREAD

**Issue by Allenisme** [ZLMediaKit/ZLMediaKit#3206]
**咨询的功能模块**
- wiki的Restful接口

**咨询的具体内容和问题**
- wiki的Restful接口有列出getRecordStatus接口，但没有详细描述，请问请求参数和响应参数具体有哪些？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by monktan89** [comment]
这个接口没有实现，可以用getMediaList接口响应的isRecordingMP4或者isRecordingHLS字段查看

**Comment by Allenisme** [comment]
好的感谢
