### ISSUE TITLE
webrtc推流在低带宽时出现卡顿，好像twcc没起到作用？

### ISSUE THREAD

**Issue by victording123456** [ZLMediaKit/ZLMediaKit#3211]
我在使用webrtc进行推流时，低带宽下出现周期性卡顿，我查看了一下网络收发，发现当h264的I帧到来时，接收约5Mbps（1920*1080像素），此时网页画面出现卡顿几秒，过一会就恢复了，问题呈现周期性。

我看咱们的config.ini内这样描述的：
**#设置remb比特率，非0时关闭twcc并开启remb。该设置在rtc推流时有效，可以控制推流画质
#目前已经实现twcc自动调整码率，关闭remb根据真实网络状况调整码率
rembBitRate=0**
按照twcc的功能，在网络不佳时，能动态调整码率，消除峰值，可为啥还是有5Mb的峰值呢？需要对前端或后端做什么设置吗？

说明：我使用rtmp将桌面流推送到ZLMedia：
D:\test\bin\ffmpeg.exe -f gdigrab -draw_mouse 0 -i desktop -r 20 -pix_fmt yuv420p -vcodec libx264 -force_key_frames "expr:gte(t,n_forced*3)" -preset:v ultrafast -f flv rtmp://172.17.21.210/live/test

**Comment by xiongguangjie** [comment]
> 我在使用webrtc进行推流时，低带宽下出现周期性卡顿，我查看了一下网络收发，发现当h264的I帧到来时，接收约5Mbps（1920*1080像素），此时网页画面出现卡顿几秒，过一会就恢复了，问题呈现周期性。
> 
> 我看咱们的config.ini内这样描述的： **#设置remb比特率，非0时关闭twcc并开启remb。该设置在rtc推流时有效，可以控制推流画质 #目前已经实现twcc自动调整码率，关闭remb根据真实网络状况调整码率 rembBitRate=0** 按照twcc的功能，在网络不佳时，能动态调整码率，消除峰值，可为啥还是有5Mb的峰值呢？需要对前端或后端做什么设置吗？
> 
> 说明：我使用rtmp将桌面流推送到ZLMedia： D:\test\bin\ffmpeg.exe -f gdigrab -draw_mouse 0 -i desktop -r 20 -pix_fmt yuv420p -vcodec libx264 -force_key_frames "expr:gte(t,n_forced*3)" -preset:v ultrafast -f flv rtmp://172.17.21.210/live/test

调解码率是在推流端做的，需要rtc 推流才支持，为何卡顿，是因为你这个推流命令含有B帧

**Comment by victording123456** [comment]
"调解码率是在推流端做的，需要rtc 推流才支持，为何卡顿，是因为你这个推流命令含有B帧"

您指的推流端调解码率是指的FFMPEG端，还是ZLM里的webrtc端？我使用的ZLMRTCClient.js播放webrtc的地址http:ip:port/index/api/webrtc?app=live&stream=test&type=play。这样还不能使用twcc吗？

**Comment by xiongguangjie** [comment]
> "调解码率是在推流端做的，需要rtc 推流才支持，为何卡顿，是因为你这个推流命令含有B帧"
> 
> 您指的推流端调解码率是指的FFMPEG端，还是ZLM里的webrtc端？我使用的ZLMRTCClient.js播放webrtc的地址http:ip:port/index/api/webrtc?app=live&stream=test&type=play。这样还不能使用twcc吗？

要用ZLMRTCClient.js 推流才能使用twcc

**Comment by victording123456** [comment]
我就是使用的ZLMRTCClient.js，您的意思是只有使用webrtc协议推送给ZLM，才能通过twcc来调节源头的码率？rtmp推流不行？

**Comment by xiongguangjie** [comment]
> 我就是使用的ZLMRTCClient.js，您的意思是只有使用webrtc协议推送给ZLM，才能通过twcc来调节源头的码率？rtmp推流不行？

是的
