### ISSUE TITLE
[技术咨询] rtsp代理固定端口号

### ISSUE THREAD

**Issue by TensorUI** [ZLMediaKit/ZLMediaKit#3214]
**咨询的功能模块**
- rtsp代理

**咨询的具体内容和问题**
- 在仅使用rtsp服务器和rtsp代理的场景下，是否可以通过去除`assert(s_max_port` >= s_min_port + 36 - 1);`代码，并将配置文件的端口号范围缩小以固定端口号而不影响功能

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
> **咨询的功能模块**
> 
> * rtsp代理
> 
> **咨询的具体内容和问题**
> 
> * 在仅使用rtsp服务器和rtsp代理的场景下，是否可以通过去除`assert(s_max_port` >= s_min_port + 36 - 1);`代码，并将配置文件的端口号范围缩小以固定端口号而不影响功能
> 
> **注意事项**
> 
> * 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue
> * 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

你改默认的配置文件不就行了
