### ISSUE TITLE
[编译问题] 编译报错

### ISSUE THREAD

**Issue by arvinhan** [ZLMediaKit/ZLMediaKit#3216]
ubantu20系统

cd ZLMediaKit

# 更新子模块
git submodule update --init
mkdir build
cd build
cmake ..
make -j4（这个步骤一直报错）
编译记录如下：
make[2]: *** [webrtc/CMakeFiles/webrtc.dir/build.make:144: webrtc/CMakeFiles/webrtc.dir/SrtpSession.cpp.o] Error 1
make[2]: Leaving directory '/opt/ZLMediaKit/build'
make[1]: *** [CMakeFiles/Makefile2:547: webrtc/CMakeFiles/webrtc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 76%] Building CXX object ext-codec/CMakeFiles/ext-codec.dir/JPEGRtp.cpp.o
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/c++  -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/opt/ZLMediaKit/build -I/opt/ZLMediaKit/3rdpart -I/opt/ZLMediaKit/ext-codec -I/opt/ZLMediaKit/ext-codec/.. -I/opt/ZLMediaKit/src -I/opt/ZLMediaKit/3rdpart/jsoncpp/include -I/opt/ZLMediaKit/3rdpart/media-server/libflv/include -I/opt/ZLMediaKit/3rdpart/media-server/libmov/include -I/opt/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/opt/ZLMediaKit/3rdpart/ZLToolKit/src  -g   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g3 -std=gnu++11 -o CMakeFiles/ext-codec.dir/JPEGRtp.cpp.o -c /opt/ZLMediaKit/ext-codec/JPEGRtp.cpp
[ 77%] Linking CXX static library ../../release/linux/Debug/libsrt.a
cd /opt/ZLMediaKit/build/srt && /usr/bin/cmake -P CMakeFiles/srt.dir/cmake_clean_target.cmake
cd /opt/ZLMediaKit/build/srt && /usr/bin/cmake -E cmake_link_script CMakeFiles/srt.dir/link.txt --verbose=1
/usr/bin/ar qc ../../release/linux/Debug/libsrt.a  CMakeFiles/srt.dir/Ack.cpp.o CMakeFiles/srt.dir/HSExt.cpp.o CMakeFiles/srt.dir/NackContext.cpp.o CMakeFiles/srt.dir/Packet.cpp.o CMakeFiles/srt.dir/PacketQueue.cpp.o CMakeFiles/srt.dir/PacketSendQueue.cpp.o CMakeFiles/srt.dir/SrtSession.cpp.o CMakeFiles/srt.dir/SrtTransport.cpp.o CMakeFiles/srt.dir/SrtTransportImp.cpp.o CMakeFiles/srt.dir/Statistic.cpp.o
/usr/bin/ranlib ../../release/linux/Debug/libsrt.a
make[2]: Leaving directory '/opt/ZLMediaKit/build'
[ 77%] Built target srt
[ 78%] Building CXX object ext-codec/CMakeFiles/ext-codec.dir/L16.cpp.o
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/c++  -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/opt/ZLMediaKit/build -I/opt/ZLMediaKit/3rdpart -I/opt/ZLMediaKit/ext-codec -I/opt/ZLMediaKit/ext-codec/.. -I/opt/ZLMediaKit/src -I/opt/ZLMediaKit/3rdpart/jsoncpp/include -I/opt/ZLMediaKit/3rdpart/media-server/libflv/include -I/opt/ZLMediaKit/3rdpart/media-server/libmov/include -I/opt/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/opt/ZLMediaKit/3rdpart/ZLToolKit/src  -g   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g3 -std=gnu++11 -o CMakeFiles/ext-codec.dir/L16.cpp.o -c /opt/ZLMediaKit/ext-codec/L16.cpp
[ 78%] Building CXX object ext-codec/CMakeFiles/ext-codec.dir/Opus.cpp.o
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/c++  -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/opt/ZLMediaKit/build -I/opt/ZLMediaKit/3rdpart -I/opt/ZLMediaKit/ext-codec -I/opt/ZLMediaKit/ext-codec/.. -I/opt/ZLMediaKit/src -I/opt/ZLMediaKit/3rdpart/jsoncpp/include -I/opt/ZLMediaKit/3rdpart/media-server/libflv/include -I/opt/ZLMediaKit/3rdpart/media-server/libmov/include -I/opt/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/opt/ZLMediaKit/3rdpart/ZLToolKit/src  -g   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g3 -std=gnu++11 -o CMakeFiles/ext-codec.dir/Opus.cpp.o -c /opt/ZLMediaKit/ext-codec/Opus.cpp
[ 78%] Building C object ext-codec/CMakeFiles/ext-codec.dir/SPSParser.c.o
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/cc -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/opt/ZLMediaKit/build -I/opt/ZLMediaKit/3rdpart -I/opt/ZLMediaKit/ext-codec -I/opt/ZLMediaKit/ext-codec/.. -I/opt/ZLMediaKit/src -I/opt/ZLMediaKit/3rdpart/jsoncpp/include -I/opt/ZLMediaKit/3rdpart/media-server/libflv/include -I/opt/ZLMediaKit/3rdpart/media-server/libmov/include -I/opt/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/opt/ZLMediaKit/3rdpart/ZLToolKit/src  -g   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g3 -o CMakeFiles/ext-codec.dir/SPSParser.c.o   -c /opt/ZLMediaKit/ext-codec/SPSParser.c
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘decodeHrdPAarameters’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:678:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  678 |     if (iCpbCount > 32U)
      |                   ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘decodeVuiParameters’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:815:38: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  815 |         if (ptSps->iNumReorderFrames > 16U
      |                                      ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘h264DecSeqParameterSet’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:903:37: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  903 |         if (ptSps->iChromaFormatIdc > 3U)
      |                                     ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1004:31: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1004 |         ptSps->iRefFrameCount > 16U)
      |                               ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1050:54: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
 1050 |                 (uiCropLeft + uiCropRight ) * step_x >= iWidth ||
      |                                                      ^~
/opt/ZLMediaKit/ext-codec/SPSParser.c:1051:54: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
 1051 |                 (uiCropTop  + uiCropBottom) * step_y >= iHeight
      |                                                      ^~
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘scalingListData’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:1251:35: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1251 |                     if (matrix_id < delta) {
      |                                   ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘hevcDecodeShortTermRps’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:1368:15: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
 1368 |         if (k >= FF_ARRAY_ELEMS(rps->au8Used)) {
      |               ^~
/opt/ZLMediaKit/ext-codec/SPSParser.c:1397:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1397 |             for (i = 0; i < rps->uiNumNegativePics >> 1; i++) {
      |                           ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1421:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1421 |             for (i = 0; i < rps->uiNumNegativePics; i++) {
      |                           ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1434:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1434 |             for (i = 0; i < uiNbPositivePics; i++) {
      |                           ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘decodeSublayerHrd’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:1456:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1456 |     for (i = 0; i < nb_cpb; i++) {
      |                   ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘h265DecSeqParameterSet’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:1720:33: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1720 |     if (ptSps->iChromaFormatIdc > 3U) {
      |                                 ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1773:59: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1773 |         if (ptSps->stTemporalLayer[i].iMaxDecPicBuffering > (unsigned)HEVC_MAX_DPB_SIZE) {
      |                                                           ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1873:19: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1873 |     for (i = 0; i < ptSps->uiNbStRps; i++) {
      |                   ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1938:47: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
 1938 |         ow->uiLeftOffset + ow->uiRightOffset  >= ptSps->iWidth ||
      |                                               ^~
/opt/ZLMediaKit/ext-codec/SPSParser.c:1939:47: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
 1939 |         ow->uiTopOffset  + ow->uiBottomOffset >= ptSps->iHeight) {
      |                                               ^~
/opt/ZLMediaKit/ext-codec/SPSParser.c:1987:49: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1987 |     if (ptSps->iMaxTransformHierarchyDepthInter > ptSps->uiLog2CtbSize - ptSps->uiLog2MinTbSize) {
      |                                                 ^
/opt/ZLMediaKit/ext-codec/SPSParser.c:1993:49: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 1993 |     if (ptSps->iMaxTransformHierarchyDepthIntra > ptSps->uiLog2CtbSize - ptSps->uiLog2MinTbSize) {
      |                                                 ^
/opt/ZLMediaKit/ext-codec/SPSParser.c: In function ‘h265DecVideoParameterSet’:
/opt/ZLMediaKit/ext-codec/SPSParser.c:2125:41: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
 2125 |         if (ptVps->iVpsNumHrdParameters > (unsigned)ptVps->iVpsNumLayerSets) {
      |                                         ^
[ 78%] Linking CXX static library ../../release/linux/Debug/libext-codec.a
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/cmake -P CMakeFiles/ext-codec.dir/cmake_clean_target.cmake
cd /opt/ZLMediaKit/build/ext-codec && /usr/bin/cmake -E cmake_link_script CMakeFiles/ext-codec.dir/link.txt --verbose=1
/usr/bin/ar qc ../../release/linux/Debug/libext-codec.a  CMakeFiles/ext-codec.dir/AAC.cpp.o CMakeFiles/ext-codec.dir/AACRtmp.cpp.o CMakeFiles/ext-codec.dir/AACRtp.cpp.o CMakeFiles/ext-codec.dir/G711.cpp.o CMakeFiles/ext-codec.dir/G711Rtp.cpp.o CMakeFiles/ext-codec.dir/H264.cpp.o CMakeFiles/ext-codec.dir/H264Rtmp.cpp.o CMakeFiles/ext-codec.dir/H264Rtp.cpp.o CMakeFiles/ext-codec.dir/H265.cpp.o CMakeFiles/ext-codec.dir/H265Rtmp.cpp.o CMakeFiles/ext-codec.dir/H265Rtp.cpp.o CMakeFiles/ext-codec.dir/JPEG.cpp.o CMakeFiles/ext-codec.dir/JPEGRtp.cpp.o CMakeFiles/ext-codec.dir/L16.cpp.o CMakeFiles/ext-codec.dir/Opus.cpp.o CMakeFiles/ext-codec.dir/SPSParser.c.o
/usr/bin/ranlib ../../release/linux/Debug/libext-codec.a
make[2]: Leaving directory '/opt/ZLMediaKit/build'
[ 78%] Built target ext-codec
make[1]: Leaving directory '/opt/ZLMediaKit/build'
make: *** [Makefile:133: all] Error 2
root@-desktop:/opt/ZLMediaKit/build#

**Comment by monktan89** [comment]
如何不需要webrtc功能可以 cmake .. -DENABLE_WEBRTC=OFF -DENABLE_SCTP=OFF 试下

**Comment by arvinhan** [comment]
> 如何不需要webrtc功能可以 cmake ..-DENABLE_WEBRTC=OFF -DENABLE_SCTP=OFF 试下

这样可以编译成功


2024-01-16 20:17:36.223 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H264
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H265
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: JPEG
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: mpeg4-generic
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: opus
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMA
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMU
2024-01-16 20:17:36.224 I [MediaServer] [3974-MediaServer] Factory.cpp:41 registerPlugin | Load codec: L16
2024-01-16 20:17:36.224 D [MediaServer] [3974-MediaServer] System.cpp:133 startDaemon | 启动子进程:3977
2024-01-16 20:17:36.224 I [MediaServer] [3977-MediaServer] System.cpp:177 systemSetup | core文件大小设置为:18446744073709551615
2024-01-16 20:17:36.225 I [MediaServer] [3977-MediaServer] System.cpp:186 systemSetup | 文件最大描述符个数设置为:1048576
2024-01-16 20:17:36.225 I [MediaServer] [3977-MediaServer] main.cpp:256 start_main | ZLMediaKit(git hash:6514be7/2024-01-15T20:34:17+08:00,branch:master,build time:2024-01-16T20:01:23)
2024-01-16 20:17:36.231 D [MediaServer] [3977-MediaServer] SSLBox.cpp:174 setContext | Add certificate of: default.zlmediakit.com
2024-01-16 20:17:36.232 D [MediaServer] [3977-stamp thread] util.cpp:366 operator() | Stamp thread started
2024-01-16 20:17:36.234 I [MediaServer] [3977-MediaServer] EventPoller.cpp:500 EventPollerPool | EventPoller created size: 4
2024-01-16 20:17:36.234 I [MediaServer] [3977-MediaServer] main.cpp:350 start_main | 已启动http api 接口
2024-01-16 20:17:36.235 I [MediaServer] [3977-MediaServer] main.cpp:352 start_main | 已启动http hook 接口
2024-01-16 20:17:36.236 I [MediaServer] [3977-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 554
2024-01-16 20:17:36.236 I [MediaServer] [3977-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 1935
2024-01-16 20:17:36.237 I [MediaServer] [3977-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 80
2024-01-16 20:17:36.238 I [MediaServer] [3977-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 443
2024-01-16 20:17:36.239 I [MediaServer] [3977-MediaServer] TcpServer.cpp:218 start_l | TCP server listening on [::]: 10000
2024-01-16 20:17:36.240 I [MediaServer] [3977-MediaServer] UdpServer.cpp:120 start_l | UDP server bind to [::]: 10000
2024-01-16 20:17:36.240 I [MediaServer] [3977-MediaServer] UdpServer.cpp:120 start_l | UDP server bind to [::]: 9000

**Comment by elegentFrog** [comment]
这个问题解决了吗？
