### ISSUE TITLE
[技术咨询] startSendRtp中src_port能填写openRtpServer创建的随机端口吗？（udp端口）

### ISSUE THREAD

**Issue by mc373906408** [ZLMediaKit/ZLMediaKit#3218]
**咨询的功能模块**
- Rtp发送

**咨询的具体内容和问题**
- 在sip通话过程中，某客户端会把startSendRtp的发送端口当作接收端口，然后将数据往这个端口发送。（某客户端自动忽略了SDP中传给它的端口号）
- 我的问题是startSendRtp中src_port能填写openRtpServer创建的随机端口吗？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by mc373906408** [comment]
填写了之后，这个端口只能接收 无法发送

**Comment by mc373906408** [comment]
[抓包.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/13936655/default.zip)

**Comment by xiongguangjie** [comment]
> [#2109 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2109#issue-1461329419) 我看了这个issues，我的处理流程不一样，需要先用openRtpServer创建端口，收到一方流之后，再startSendRtp发送给另外一方

按照issue 来做，openRtpServer 后是无法再使用这个来发流的

**Comment by mc373906408** [comment]
没有openRtpServer 是无法接收到流的，没有流就没法发送

**Comment by mc373906408** [comment]
issue 只涉及到webrtc场景，sip通话不适用

**Comment by xiongguangjie** [comment]
> issue 只涉及到webrtc场景，sip通话不适用

这个只能二次开发了

**Comment by mc373906408** [comment]
这个问题貌似解决了
1、在ipv4环境下
2、设置openRtpServer的local_ip为0.0.0.0，re_use_port为1
3、设置startSendRtp的src_port为openRtpServer返回的port，recv_stream_id为空

仅测试过windows环境，sip与sip通话，能成功。

我自己思考是设定openRtpServer在ipv4上创建，send也在ipv4上发送，可以复用端口。
![8d4146769a289a38e5fd82d6065023c](https://github.com/ZLMediaKit/ZLMediaKit/assets/33921191/8ba11d12-dc8b-42de-a816-01e9dc05be3a)

夏楚大佬说在同一个端口创建了两个socket，内核是随机发送给某个socket，可能会出问题。

如果有这种需求可以参考我这个思路，不一定有效。
![0b1e4be798da626b02b1bd4d81e4a7f](https://github.com/ZLMediaKit/ZLMediaKit/assets/33921191/d1e4e98f-d773-4524-aded-53636c6a8355)
![dd93692281c8c609bc14c8d55a5c4bc](https://github.com/ZLMediaKit/ZLMediaKit/assets/33921191/9f1eeb22-f025-4a53-abca-248a4667faf8)
