### ISSUE TITLE
(addStreamProxy) RTSP方式拉流失败

### ISSUE THREAD

**Issue by annoel** [ZLMediaKit/ZLMediaKit#3219]
**咨询的功能模块**
- addStreamProxy RTSP方式拉流，海康的设备

**咨询的具体内容和问题**
- RTSP地址来源：远程调用海康接口返回RTSP地址，但是返回的是生产环境的内网地址也就是日志图片中的rtsp://10.10.1.10:5544/xxxxx；
- 然后我把这个地址给我映射出来了，在我本地调用addStreamProxy进行拉流，日志显示好像又实际去拉内网地址的那个流了，导致拉不了，有什么办法可以解决这个问题吗
- ![微信图片_20240115172959](https://github.com/ZLMediaKit/ZLMediaKit/assets/42574842/43234658-b45c-4775-9137-ce0bf89cec82)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
> * 但是返回的是生产环境的内网地址也就是日志图片中的

使用tcp拉流，不要用udp,否则无法拉流的

**Comment by annoel** [comment]
谢谢
还有一个问题就是，当我拉起流后，需要做一些准备工作，做完后，这期间流因为无人观看，自动关闭了，以下是我的配置文件中的配置：
- auto_close=1
- streamNoneReaderDelayMS=20000
- on_stream_none_reader=

然后，我调用addStreamProxy接口时，auto-close传的也是1，请问如果要延迟关闭无人观看流关闭的时间，应该如何设置，现在我这种配置加接口调用传参，流很快就关闭了

**Comment by annoel** [comment]
- 不要求触发on_stream_none_reader hook，全局配置streamNoneReaderDelayMS这个也可以
- 要求就是拉起流后无人观看的话不是自动关闭流吗，那这个多长时间后才会自动关闭流，这个时间在哪设置，我想把这个时间延长，不管是RESTful接口设置还是全局配置，只要可以自定义设置就可以，streamNoneReaderDelayMS这个设置20000，没起作用；感觉是触发事件调用的时间，

> 谢谢 还有一个问题就是，当我拉起流后，需要做一些准备工作，做完后，这期间流因为无人观看，自动关闭了，以下是我的配置文件中的配置：
> 
> * auto_close=1
> * streamNoneReaderDelayMS=20000
> * on_stream_none_reader=
> 
> 然后，我调用addStreamProxy接口时，auto-close传的也是1，请问如果要延迟关闭无人观看流关闭的时间，应该如何设置，现在我这种配置加接口调用传参，流很快就关闭了

**Comment by xiongguangjie** [comment]
> * auto_close

auto_close 设置为0，就可以了
