### ISSUE TITLE
[技术咨询] 请问大佬，test_player 如何运行？

### ISSUE THREAD

**Issue by luhengyu1** [ZLMediaKit/ZLMediaKit#3230]
我遇到了延迟问题，使用wvp + zlm + jessibuca播放摄像头视频，开始延迟就有3s左右，后续随着时间的累积，延迟也会慢慢累积，直至几十秒，我想定位一下问题所在。1. zlm本身延迟多少 2. 是否是网络原因 3. 是否是播放器原因
第一步就卡主了，我看wiki里建议用test_player测试，但是我不知道是不是这个player文件夹，如何运行。
如下是我编译后的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/b10cbfa7-235f-4098-bc9e-bffa032e3522)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/13534227-b92c-4dc0-9f8c-0830e0467459)

**Comment by luhengyu1** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/94d04d5e-54cc-4c2d-8cc2-a94ae6afd938)

**Comment by luhengyu1** [comment]
> 用rtc 协议播放（用自带的播放器ZLMRTCClient.js 来播放），这个延迟是准确的，test_player 依赖SDL，同时需要界面才能展示

请问大佬这个ZLMRTCClient 如何运行的，是否有demo，我不太懂前端，找到这个js文件也不会运行。。。

**Comment by xiongguangjie** [comment]
> > 用rtc 协议播放（用自带的播放器ZLMRTCClient.js 来播放），这个延迟是准确的，test_player 依赖SDL，同时需要界面才能展示
> 
> 请问大佬这个ZLMRTCClient 如何运行的，是否有demo，我不太懂前端，找到这个js文件也不会运行。。。

zlm有自带的demo, http访问，web目录就行了，参考https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97

**Comment by luhengyu1** [comment]
运行起来了，延迟1s左右，还可以，谢谢大佬。
