### ISSUE TITLE
[技术咨询]直播推流方切换了模式（照相或者视频拍摄），导致推流码率和帧数不一样了，最终导致花屏，如何处理

### ISSUE THREAD

**Issue by xueshuai0922** [ZLMediaKit/ZLMediaKit#3243]
**咨询的功能模块**
直播推流切换
**咨询的具体内容和问题**

直播推流方切换了模式（照相或者视频拍摄），导致推流码率和帧数不一样了，最终导致花屏，如何处理；
只要刷新直播，重新拉流就可以解决，这是流媒体前端播放组件问题还是流媒体服务器问题。

**Comment by xueshuai0922** [comment]
目前直播组件是bilibili 的flv.js ,能够通过flv.js进行判断总帧数是否增加，而进行确定是否重新让直播的前端组件进行拉流

**Comment by xueshuai0922** [comment]
**摄像模式**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36756769/693b9077-85ca-4a7e-a490-56df228393ce)
**拍照模式**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/36756769/e3becb4f-2d35-46bb-bec2-045a1ddb3c5a)

**Comment by xiongguangjie** [comment]
用rtc播放，使用zlmrtcclient.js (zlm有附带的demo)

**Comment by xueshuai0922** [comment]
> 用rtc播放，使用zlmrtcclient.js (zlm有附带的demo)

ok
