### ISSUE TITLE
[Bug] There is garbled Chinese on the console.

### ISSUE THREAD

**Issue by cdjzzzz** [ZLMediaKit/ZLMediaKit#3263]
### Phenomenon Description

VCPKG under tool MediaServer.exe is printed to console is garbled

### How to reproduce?

Open MediaServer.exe

### Configuration

Win11 pro version 64bit

>
### 现象描述

VCPKG下的tool MediaServer.exe打印到console是乱码

### 如何复现?

打开MediaServer.exe

### 配置

Win11 pro version 64bit

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by pecmd** [comment]
改一下cmd代码页  cmd执行 `chcp 65001` 再执行主程序
