### ISSUE TITLE
倍速推流到server，播放的时候卡顿严重

### ISSUE THREAD

**Issue by kaikaimiao** [ZLMediaKit/ZLMediaKit#3267]
ffmpeg  -re -i test2.mp4 -filter:v "setpts=1/4*PTS"   -f flv rtmp://192.168.0.132:1935/live/test13

使用ffmpeg倍速推流到server播放出现卡顿现象，已尝试用gpu加速 以及各种参数处理，还是卡顿

**Comment by xiongguangjie** [comment]
这个一般是播放器性能不够与服务器没太大关系
