### ISSUE TITLE
[BUG] 启动时通过 -c 指令指定启动配置文件，但是config.ini 还是被覆盖

### ISSUE THREAD

**Issue by yuetsao** [ZLMediaKit/ZLMediaKit#3268]
### 现象描述

1. 执行指令：
nohup /opt/media/MediaServer -d -m 3 -c /home/config.ini &' >> run.sh
2. /home/config.ini 配置会被覆盖

### 如何复现?

指定目录下的配置文件，但是配置文件被重写，导致每次都要重新配置java中的yml

**Comment by xiongguangjie** [comment]
上传ZLM的日志，这个不会覆盖日志的，除非你调用接口修改了配置

**Comment by yuetsao** [comment]
现象是确实每次启动所使用的配置文件都显示 mINI::Instance() 所自动生成

**Comment by yuetsao** [comment]
> 上传ZLM的日志，这个不会覆盖日志的，除非你调用接口修改了配置

不是覆盖日志，是不使用启动时所指定的配置文件

**Comment by yuetsao** [comment]
> 上传ZLM的日志，这个不会覆盖日志的，除非你调用接口修改了配置

使用的是代码中所自动生成的配置文件

**Comment by xiongguangjie** [comment]
上传日志我看下

**Comment by xiongguangjie** [comment]
你是不是api.secret 是默认的，导致程序修改相应配置，保存到配置文件了（为了安全性保证）

**Comment by yuetsao** [comment]
不是默认的，是自己生成的

**Comment by yuetsao** [comment]
> 你是不是api.secret 是默认的，导致程序修改相应配置，保存到配置文件了（为了安全性保证）

不是默认的（不是那个035开头的默认密钥），是咱们的代码生成的，满足格式要求（包括serverid和secret）

**Comment by yuetsao** [comment]
![1111111](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/15dfdea8-566f-4eca-b972-01fca411eb25)
![22222](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/a1857ecb-cc5c-4a9d-8318-3e8cf68b1b7e)
见图片 config.ini 为自动生成，但是启动参数已经指定配置文件的位置，被覆盖了

**Comment by yuetsao** [comment]
又经历了一系列的调试，还是始终覆盖，辛苦帮忙看下，感谢

**Comment by xiongguangjie** [comment]
你的ZLM日志呢，日志不上传，怎么看？？？

**Comment by yuetsao** [comment]
![Uploading 1111111.png…]()

**Comment by yuetsao** [comment]
![1111111](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/1db0836c-5116-4028-af79-8424145c3ee0)

**Comment by yuetsao** [comment]
> ![1111111](https://private-user-images.githubusercontent.com/18000628/300668683-1db0836c-5116-4028-af79-8424145c3ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODUxNTcsIm5iZiI6MTcwNjU4NDg1NywicGF0aCI6Ii8xODAwMDYyOC8zMDA2Njg2ODMtMWRiMDgzNmMtNTExNi00MDI4LWFmNzktODQyNDE0NWMzZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzMjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNmUwODQ2OGRiNmFjNWRiMmU3M2RjYjkzNWEwZTZhMDQxZDBiNmMxNzE4ZTg4ZmJjYTU4ZTJiYWZlNTM3YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cpy9nhgjugbAYKaluVC0S-1E40aoezzZ5l3mD6zg0o0)
meidaserver所有的日志

**Comment by xiongguangjie** [comment]
> ![1111111](https://private-user-images.githubusercontent.com/18000628/300668683-1db0836c-5116-4028-af79-8424145c3ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODczNzcsIm5iZiI6MTcwNjU4NzA3NywicGF0aCI6Ii8xODAwMDYyOC8zMDA2Njg2ODMtMWRiMDgzNmMtNTExNi00MDI4LWFmNzktODQyNDE0NWMzZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzNTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTQxNDVjMDcwMmUzM2Q3NzNiN2QwNzdiMjI5OTE4MGUyOWJhMTk4YTExZDhlZDc0ZjZhNjQyMzc2YmM3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wvoibFhqMg5JzHKdGkybKwxxkdXddYD9gaxDk2dClI)

the api.secret is invaild 这么大的日志你看不到？？？？

**Comment by yuetsao** [comment]
> > ![1111111](https://private-user-images.githubusercontent.com/18000628/300668683-1db0836c-5116-4028-af79-8424145c3ee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODczNzcsIm5iZiI6MTcwNjU4NzA3NywicGF0aCI6Ii8xODAwMDYyOC8zMDA2Njg2ODMtMWRiMDgzNmMtNTExNi00MDI4LWFmNzktODQyNDE0NWMzZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzNTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4OTQxNDVjMDcwMmUzM2Q3NzNiN2QwNzdiMjI5OTE4MGUyOWJhMTk4YTExZDhlZDc0ZjZhNjQyMzc2YmM3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0wvoibFhqMg5JzHKdGkybKwxxkdXddYD9gaxDk2dClI)
> 
> the api.secret is invaild 这么大的日志你看不到？？？？

是的，这是没有采用 -c命令的日志，我重新上传一个哈

**Comment by yuetsao** [comment]
![3333](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/b2f729c9-e29d-41cd-932f-9361e79ad666)
换成 -c启动还是说invalid，但是这个secret是咱们平台生成的那种，为啥总是这样提示呢（我将config.ini 放在了/home下）

**Comment by yuetsao** [comment]
![444444](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/f3a3f73b-eb1c-4fa7-8c9f-94ded4feb5e2)
这是我配置的secret

**Comment by yuetsao** [comment]
> ![444444](https://private-user-images.githubusercontent.com/18000628/300685532-f3a3f73b-eb1c-4fa7-8c9f-94ded4feb5e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTE0OTEsIm5iZiI6MTcwNjU5MTE5MSwicGF0aCI6Ii8xODAwMDYyOC8zMDA2ODU1MzItZjNhM2Y3M2ItZWIxYy00ZmE3LThjOWYtOTRkZWQ0ZmViNWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA1MDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzc3ODNjOTgzNTVkYjdmMjY1NzY1Y2NiOGE4OGU0MjI1MWMzZmQxM2JmMWEzYjg4MjJiMjEyMTA1NTA1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UR8fphuFUs6v1nRWQ1tJCnv5YZa4hXQT19Nw8_3Ndbg) 这是我配置的secret

假设我换成他新生成的5h开头的，下次他还是提示invalid

**Comment by yuetsao** [comment]
> ![444444](https://private-user-images.githubusercontent.com/18000628/300685532-f3a3f73b-eb1c-4fa7-8c9f-94ded4feb5e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTE0OTEsIm5iZiI6MTcwNjU5MTE5MSwicGF0aCI6Ii8xODAwMDYyOC8zMDA2ODU1MzItZjNhM2Y3M2ItZWIxYy00ZmE3LThjOWYtOTRkZWQ0ZmViNWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA1MDYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzc3ODNjOTgzNTVkYjdmMjY1NzY1Y2NiOGE4OGU0MjI1MWMzZmQxM2JmMWEzYjg4MjJiMjEyMTA1NTA1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UR8fphuFUs6v1nRWQ1tJCnv5YZa4hXQT19Nw8_3Ndbg) 这是我配置的secret

假设我换成他新生成的mh开头的，下次他还是提示invalid

**Comment by yuetsao** [comment]
![5555](https://github.com/ZLMediaKit/ZLMediaKit/assets/18000628/28f48b68-65c3-4f7c-bcdc-f4f7775ceff3)
wo我分析 secret.empty 为空，但是为什么会为空呢，home文件夹下有配置呀

**Comment by yuetsao** [comment]
确实如上述所说，每次指定了也会被覆盖，希望您重视，已经实验了很多遍了！

**Comment by yuetsao** [comment]
已修改源代码解决了，期待您的回复

**Comment by xiongguangjie** [comment]
没有复现，你自己找原因

**Comment by yuetsao** [comment]
> 没有复现，你自己找原因

嗯

**Comment by Farrahchen** [comment]
我也遇到了这个问题。。

**Comment by Farrahchen** [comment]
确实是代码写得有问题，我拉的分支版本是2.6.9

**Comment by zkhhxx** [comment]
我解决了这个问题
1、在config.ini中自定义secret，不要使用默认的secret
2、确保挂载路径正确，容器中路径/opt/media/conf/config.ini
