### ISSUE TITLE
[技术咨询] 国标rtp推流问题

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#3272]
**咨询的功能模块**
 rtp_proxy推流、hook接口中的on_stream_changed

**咨询的具体内容和问题**
国标视频码率过高时如 6Mbps的码率推流，udp方式推流，通过getRtpInfo可以看到可以查询到有流发送，但是通过getMediaList却没有看到流信息（如转hls,默认配置有开启），想确认是不是rtp流上来但是转不出stream的情况，导致on_stream_change回调检测不到流注册，流注销。这种情况下无法是由rtp推流也在接收rtp流  但是转不出来hls流。想咨询是否由这种情况出现

**注意事项**

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个主要要等到流注册后（流注册需要等待I帧，有可能还需要等待音频之类的），getMediaList 才有结果

**Comment by zhang-chuanfeng** [comment]
> 这个主要要等到流注册后（流注册需要等待I帧，有可能还需要等待音频之类的），getMediaList 才有结果

on_publish应该是回调成功的，除非按照你说的一直缓存不到I帧，无法转hls。
难道和码率大小有关  导致没有成功缓存到正确I帧，导致后续生成hls流失败。是否有参数可以调整帧缓存大小，如果码率过大时

**Comment by zhang-chuanfeng** [comment]
> 可以提供下rtp dump文件。 zlm的配置文件dumpDir设置下就会导出的

暂时环境没有 暂时先关闭了
