### ISSUE TITLE
[技术咨询] k8s部署集群模式时，源站是否能支持动态的扩缩容呢？

### ISSUE THREAD

**Issue by ops-xu** [ZLMediaKit/ZLMediaKit#3274]
**咨询的功能模块**
- k8s集群扩缩容

**咨询的具体内容和问题**
- 比如我源站部署两个pod时，pod的ip其实会因为重启等因素变更，也会因为扩缩容导致ip的数量变动。
- 源站主要用来推流，肯定会创建一个slb暴露ip给推流服务器，svc肯定是负载均衡的，也就是推流设备也不知道具体推流到哪个pod里。
- 边缘节点拉流服务器的源站配置origin_url，因为是集群内部，应该是配内网pod ip就足以，但是又由于源站pod扩缩容，这个配置无法固定。
- 按以上的理解的话，源站其实无法使用k8s的自动扩缩容，源站只能多Deployment单pod，通过svc固定访问方式。不知道我理解的是否正确。

**Comment by xiongguangjie** [comment]
> **咨询的功能模块**
> 
> * k8s集群扩缩容
> 
> **咨询的具体内容和问题**
> 
> * 比如我源站部署两个pod时，pod的ip其实会因为重启等因素变更，也会因为扩缩容导致ip的数量变动。
> * 源站主要用来推流，肯定会创建一个slb暴露ip给推流服务器，svc肯定是负载均衡的，也就是推流设备也不知道具体推流到哪个pod里。
> * 边缘节点拉流服务器的源站配置origin_url，因为是集群内部，应该是配内网pod ip就足以，但是又由于源站pod扩缩容，这个配置无法固定。
> * 按以上的理解的话，源站其实无法使用k8s的自动扩缩容，源站只能多Deployment单pod，通过svc固定访问方式。不知道我理解的是否正确。

这个不是可以通过webhook知道哪个流在哪里吗？

**Comment by ops-xu** [comment]
> > **咨询的功能模块**
> > 
> > * k8s集群扩缩容
> > 
> > **咨询的具体内容和问题**
> > 
> > * 比如我源站部署两个pod时，pod的ip其实会因为重启等因素变更，也会因为扩缩容导致ip的数量变动。
> > * 源站主要用来推流，肯定会创建一个slb暴露ip给推流服务器，svc肯定是负载均衡的，也就是推流设备也不知道具体推流到哪个pod里。
> > * 边缘节点拉流服务器的源站配置origin_url，因为是集群内部，应该是配内网pod ip就足以，但是又由于源站pod扩缩容，这个配置无法固定。
> > * 按以上的理解的话，源站其实无法使用k8s的自动扩缩容，源站只能多Deployment单pod，通过svc固定访问方式。不知道我理解的是否正确。
> 
> 这个不是可以通过webhook知道哪个流在哪里吗？

嗯，大概懂你意思了。可以自定义serverId，通过webhook把推流信息存一下，拉流请求上来触发not found时，再利用按需拉流的逻辑去推流服务器拉流。我再研究研究。🙏

**Comment by 445990772** [comment]
请假一下大佬，使用K8S有状态服务（StatefulSets）部署zlm集群，配置cluster节点下的参数有点不太清楚
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/9440839/1f939634-95f4-4a33-8fa2-a3c9d4af8141)
想问一下 origin_url配置为有状态服务的负载service地址就可以么？
