### ISSUE TITLE
[编译问题] 建议修改项目构建目录命令(必填)

### ISSUE THREAD

**Issue by phial3** [ZLMediaKit/ZLMediaKit#3276]
### 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

### 各种环境信息

建议构建目录命名加上系统架构，比如我本地 macOS，需要构建 Linux 可用的arm64和x86_64执行文件，容易混乱和搞错

<img width="273" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/27754514/52b30a90-29e6-4de8-a0ac-c809cfc51667">

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by wasphin** [comment]
提个 pr 怎么样？

**Comment by phial3** [comment]
> 提个 pr 怎么样？

👌
