### ISSUE TITLE
webrtc一直转圈圈

### ISSUE THREAD

**Issue by cwy1996** [ZLMediaKit/ZLMediaKit#3277]
**咨询的功能模块**
rwebrtc收流

wvp版本1月16日   与 zlm时间相近

均采用docker 部署

**咨询的具体内容和问题**
在webrtc界面播放只能单独播放音频流，单独播放视频或复合播放，持续黑屏转圈圈

zlm日志
[2024-02-01 135516.279 I [MediaServe.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/14121187/2024-02-01.135516.279.I.MediaServe.txt)

[ffmpeg.log.279.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/14121188/ffmpeg.log.279.txt)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by cwy1996** [comment]
rtsp流正常拉取视音频均正常

**Comment by xiongguangjie** [comment]
你这个客户端只要求播音频呀，你没有选择videoEnable这个选项吧（ZLMRTCClient.js 的初始化，对于的demo是video 勾选）

**Comment by cwy1996** [comment]
勾选了的，视频音频均勾选的话，就一直转圈圈切没有音频，仅勾选音频的话可播放音频。后续摄像头及wvp均改为tcp，结果一样。最后是将zlm的rtc的8000/udp  端口改为0禁了后，走tcp可以了。但是不明白为啥udp会丢这么多的包

**Comment by xiongguangjie** [comment]
> 勾选了的，视频音频均勾选的话，就一直转圈圈切没有音频，仅勾选音频的话可播放音频。后续摄像头及wvp均改为tcp，结果一样。最后是将zlm的rtc的8000/udp 端口改为0禁了后，走tcp可以了。但是不明白为啥udp会丢这么多的包

你上传的ZLM日志是这样显示的
