### ISSUE TITLE
[技术咨询] 升级webrtc拉取最新的ZLM程序，sdp交换请求失败，提示regex_error

### ISSUE THREAD

**Issue by pakaqiu666** [ZLMediaKit/ZLMediaKit#3279]
**咨询的功能模块**
- webrtc信令交换

**咨询的具体内容和问题**
-  sdp交换请求失败，提示regex_error

**请求内容**
# request:
POST /index/api/webrtc?app=audio&stream=34020000001320001022_34020000001320001022&type=push&sign=41db35390ddad33f83944f44b8b75ded
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate, br
Accept-Language : zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection : keep-alive
Content-Length : 1174
Content-Type : text/plain;charset=UTF-8
Host : yunplc.cn
Origin : https://a.cn:18080
Referer : https://a.cn:18080/
sec-ch-ua : "Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
Sec-Fetch-Dest : empty
Sec-Fetch-Mode : cors
Sec-Fetch-Site : same-site
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
# content:
v=0
o=- 4697697751060136320 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 63 9 0 8 13 110 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:ppn7
a=ice-pwd:v6H1emg3v9MVZM2wY/qG3biv
a=ice-options:trickle
a=fingerprint:sha-256 E6:70:FB:A8:1B:7F:29:65:3E:17:46:AF:B4:F8:94:02:1C:74:48:03:4D:AD:C7:0D:26:D4:47:11:A1:8B:B6:0B
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:- 99fe4966-3e7c-4963-bd0b-af66b5efd21c
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:126 telephone-event/8000
a=ssrc:3314026900 cname:XR7gOZg7p0+D00Ji
a=ssrc:3314026900 msid:- 99fe4966-3e7c-4963-bd0b-af66b5efd21c

# response:
{
        "code" : -400,
        "msg" : "regex_error"
}

[config.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/14121830/config.txt)
[info.log](https://github.com/ZLMediaKit/ZLMediaKit/files/14121934/info.log)  日志文件

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
上传ZLM的日志

**Comment by pakaqiu666** [comment]
> 上传ZLM的日志

你好 已上传
[info.log](https://github.com/ZLMediaKit/ZLMediaKit/files/14121941/info.log)

**Comment by mc373906408** [comment]
SSL_CTX_set_verify callback, depth: 1 ,er: unable to get local issuer certificate
上个版本也是自定义域名+公网IP吗？好像自定义域名的证书没通过

**Comment by pakaqiu666** [comment]
> SSL_CTX_set_verify callback, depth: 1 ,er: unable to get local issuer certificate 上个版本也是自定义域名+公网IP吗？好像自定义域名的证书没通过

我们其他环境用的公网+阿里云证书，这个也是一样的，虽然是提示没找到证书，但是好像不影响使用，可以正常播放，但是没法推流

**Comment by mc373906408** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33921191/efcd4681-0e93-4cde-892e-6404febc5f59)
std::string local_ip = SockUtil::get_local_ip() ;

把这行改成这样试下呢？  这是最新对webrtc的改动，你还原下

**Comment by pakaqiu666** [comment]
> ![image](https://private-user-images.githubusercontent.com/33921191/301440760-efcd4681-0e93-4cde-892e-6404febc5f59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Nzc1NjAsIm5iZiI6MTcwNjc3NzI2MCwicGF0aCI6Ii8zMzkyMTE5MS8zMDE0NDA3NjAtZWZjZDQ2ODEtMGU5My00Y2RlLTg5MmUtNjQwNGZlYmM1ZjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4NDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3ODA1NTAxMTI3NjIyMGM1YWFhODBkMTAyZDYxNjQ1ZmUxM2YwY2Y4ZTZiYjVkODZlZmYxMTI0ZGI3ZGViMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FwpWXydt4Cj-0jWeHOUktk4xjLMjUZBCEjzp_ZTdkeY) std::string local_ip = SockUtil::get_local_ip() ;
> 
> 把这行改成这样试下呢？ 这是最新对webrtc的改动，你还原下

谢谢~我试下

**Comment by mc373906408** [comment]
如果正常请回复我需要修改这处

**Comment by pakaqiu666** [comment]
> 如果正常请回复我需要修改这处

你好 我刚照你说的改了之后重新编译，依然提示这个错误
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/141847469/588cf948-e980-4bc6-beef-29849c74504d)

**Comment by mc373906408** [comment]
你这像是已经建立过连接，然后发送端停止发送了

**Comment by mc373906408** [comment]
> > 如果正常请回复我需要修改这处
> 
> 顺便关注下127.0.0.1 ip的问题 这个icecand 浏览器会忽略它

这个测试没问题

**Comment by pakaqiu666** [comment]
> 你这像是已经建立过连接，然后发送端停止发送了。看你的地址像是使用GB28181方式连接的。 能提供更多的信息吗？比如vlc播放Rtsp转发地址，是否正常？

对，是GB的方式连接，不过还没看到转发地址的日志就已经返回这个错误了，offer anwser 交换失败 {code: -400, msg: "regex_error"}，之前的log文件里包含了从请求index/api/webrtc后的所有日志了

**Comment by mc373906408** [comment]
不使用webrtc，用vlc试下rtsp。你编译把webrtc关了或者配置上关闭

**Comment by pakaqiu666** [comment]
> 不使用webrtc，用vlc试下rtsp。你编译把webrtc关了或者配置上关闭

直接用VLC去播放也播不了，估计是哪里的配置出问题了，导致webrtc播放不了

**Comment by mc373906408** [comment]
唉，说明是拉流问题啊，你不要去管推流

**Comment by pakaqiu666** [comment]
> 唉，说明是拉流问题啊，你不要去管推流

嗯嗯  我再排查下

**Comment by MengFanLu1** [comment]
我也是这个报错{code: -400, msg: "regex_error"}

**Comment by ulquolrra** [comment]
同样的错误
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/8358330/c5dc7788-4a31-4a3a-a858-405513ecfa20)

**Comment by machh** [comment]
我也是这个报错{code: -400, msg: "regex_error"}

**Comment by machh** [comment]
我也是这个报错{code: -400, msg: "regex_error"}
推流是rtmp , zlm是部署在阿里云， 
webrtc播放提示 regex_error

**Comment by xiongguangjie** [comment]
升级下 编译器版本，是这个[问题](https://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions) ，或者去除这个修改 https://github.com/ZLMediaKit/ZLMediaKit/pull/3251 等一下我修复下
