### ISSUE TITLE
请问发送端有什么bug呢？rtsp流是可用的，用rtsp播放器是可以正常播放的

### ISSUE THREAD

**Issue by Jason5592** [ZLMediaKit/ZLMediaKit#3280]
请问发送端有什么bug呢？rtsp流是可用的，用rtsp播放器是可以正常播放的

_Originally posted by @Jason5592 in https://github.com/ZLMediaKit/ZLMediaKit/issues/3278#issuecomment-1920801888_

**Comment by xiongguangjie** [comment]
你是那种协议推流（流是怎么来的），怎么播放的，一般出现这种情况，是rtp server 才会出现（使用tcp时）

**Comment by czk630597526** [comment]
我怀疑你是directProxy的问题。可以去看看配置文件

**Comment by Jason5592** [comment]
> 你是那种协议推流（流是怎么来的），怎么播放的，一般出现这种情况，是rtp server 才会出现（使用tcp时）

流是一款媒体播放器播放出来的

> 你是那种协议推流（流是怎么来的），怎么播放的，一般出现这种情况，是rtp server 才会出现（使用tcp时）

流是一款媒体播放器合成的视频流
