### ISSUE TITLE
[技术咨询] 如果使用k8s部署，端口暴露问题怎么解决（端口范围）？

### ISSUE THREAD

**Issue by yuetsao** [ZLMediaKit/ZLMediaKit#3281]
nodeport端口暴露只支持数组类型，如果一个一个的写，太多了，因为摄像头需要公网IP + 端口推流

**Comment by yuetsao** [comment]
比如这个：分配的ZLM为: your_server_id [123.XX.XX.XX:34722] 其中34722 都是随机分配的端口，我们在部署时必须把 pod中的34722映射到外部的34722 123开头的公网才能找到pod内的34722，几万个端口是在无法解决，但是在云服务器上直接部署就没有这个问题（直接开放所有端口即可）。

**Comment by yuetsao** [comment]
最后导致的结果就是：2024-02-02 00:10:55.717 [ThreadPoolTaskScheduler-265]  INFO --- com.genersoft.iot.vmp.service.impl.PlayServiceImpl: 214 [点播超时] 收流超时 deviceId: 34020000001320000001, channelId: 34020000001310000001,码流类型：主码流，端口：34722, SSRC: 0105001711

**Comment by xiongguangjie** [comment]
这个是k8s 的使用问题，去查找相关的资料，详情参考 https://stackoverflow.com/questions/57241749/how-to-expose-a-range-of-ports-in-kubernetes
