### ISSUE TITLE
[技术咨询] 如何开启rtp dump 文件

### ISSUE THREAD

**Issue by WalkerPlus** [ZLMediaKit/ZLMediaKit#3285]
**咨询的功能模块**
- 如何开启rtp dump 文件

**咨询的具体内容和问题**
- 就是想国标推流的时候，想抓一下rtp 包，该如何操作
- 目前我是设置
```
[rtp_proxy]
dumpDir=./www/dump/
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-30500
ps_pt=96
timeoutSec=15
```
但是，国标预览没有文件生成

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
设置dumpDir 路径就行了，

**Comment by WalkerPlus** [comment]
> 设置dumpDir 路径就行了，

设置了啊，还需要什么操作吗，就是开启推流就行吗
