### ISSUE TITLE
[技术咨询] /index/api/addFFmpegSource 接口的咨询

### ISSUE THREAD

**Issue by luhengyu1** [ZLMediaKit/ZLMediaKit#3287]
请问这个接口的作用是什么？返回的key是做什么用的
我的理解是将目标流通过ffmpeg指令模板多代理出来一个流，不知道是不是理解错了。
但是我调用这个接口，成功并返回key，但是wvp的拉流代理和推流代理列表都没有任何的反应。

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/c959a6de-5c98-49ad-bf2a-e6c42340b3b4)

**Comment by xiongguangjie** [comment]
1，可以删除这个addffmpegsource
2,模板是让你来修改ffmpeg的命令的
3，这个具体要看日志，与wvp的日志呢

**Comment by luhengyu1** [comment]
以下是zlm的日志，调用addffmpegsource接口的日志
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/96dfa56b-2612-4f09-97de-5c1f4d95f900)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/d33c7a64-c38f-40c5-8c04-dc32e54a5dbb)
第一次调用会超时
然后第二次调用就会直接获得key
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/23633cb4-6dcb-4319-83c2-e27285dd0d4c)
不知道是不是读了缓存之类的
wvp在这个过程没有任何日志（除了正常的心跳）
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/b25b5a93-824c-491c-af1b-1c75a8c626c3)
拉流 推流列表也没用任何反应

**Comment by luhengyu1** [comment]
另外，我修改ffmpeg模板，加了一个裁剪分辨率的参数似乎也没有反应
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/5b5b1ab7-1ed9-4355-9e37-645ec518c190)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/003fa1d3-6f45-4856-9ef4-bae61b2c9275)
是否是我的命令不对

**Comment by xiongguangjie** [comment]
> 以下是zlm的日志，调用addffmpegsource接口的日志 ![image](https://private-user-images.githubusercontent.com/87296715/302071065-96dfa56b-2612-4f09-97de-5c1f4d95f900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzEwNjUtOTZkZmE1NmItMjYxMi00ZjA5LTk3ZGUtNWMxZjRkOTVmOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjVhYmYyYTI0NWJjY2Q5YjIxZDUxNGY0NGZkZmQ5MmRjYTQ3ZDJhMmUwNDJiODRjNGRmOTg0NTAxYzZhMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UKknYkeG8KpKzv17kIYjnX84xMah-Dxzh9_Y2KbaZIE) ![image](https://private-user-images.githubusercontent.com/87296715/302071056-d33c7a64-c38f-40c5-8c04-dc32e54a5dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzEwNTYtZDMzYzdhNjQtYzM4Zi00MGM1LThjMDQtZGMzMmU1NGE1ZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZTgyOTI5MjczYTE3MDc2YzBmODljZGQ4YmQ3NmY2ODJiOTk0NmZhNTdlNzM0YWQzM2Y5ODM2YTc5ZDVjYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C4gb40qc4nGzxrgFiKxZTiC5XEWz_clanLButuV3oig) 第一次调用会超时 然后第二次调用就会直接获得key ![image](https://private-user-images.githubusercontent.com/87296715/302071135-23633cb4-6dcb-4319-83c2-e27285dd0d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzExMzUtMjM2MzNjYjQtNmRjYi00MzE5LTgzYzItZTI3Mjg1ZGQwZDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDkxZDU3YTM5NjkzNDUxOTAxZDM4ZjY4NTQ1Njc0NTE2OWM4YzcxOTQ3ZTg1ZmE3MGNjYjYwMTAwYTNhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbyT6rUhya_cc9k9AxSrPHf8jh-pgKWQLoUzlDeyAqU) 不知道是不是读了缓存之类的 wvp在这个过程没有任何日志（除了正常的心跳） ![image](https://private-user-images.githubusercontent.com/87296715/302071162-b25b5a93-824c-491c-af1b-1c75a8c626c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzExNjItYjI1YjVhOTMtODI0Yy00OTFjLWFmMWItMWM3NWE4YzYyNmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMzUwZDNiZTA0NGVjNmZiOWViYzRjNDYwZGY3MmY2ZDkxYTdhMmQ3Yzg5ZDU2MTUzN2E1NDczOWFiYjBhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s6gdErkE-DEubQxWIhOG5bglWmCRn5Wf6WSZeh7ZIuw) 拉流 推流列表也没用任何反应
这个主要是你ffmpeg 的source需要长时间才能准备好，才会导致超时的

**Comment by xiongguangjie** [comment]
> 另外，我修改ffmpeg模板，加了一个裁剪分辨率的参数似乎也没有反应 ![image](https://private-user-images.githubusercontent.com/87296715/302071527-5b5b1ab7-1ed9-4355-9e37-645ec518c190.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzE1MjctNWI1YjFhYjctMWVkOS00MzU1LTllMzctNjQ1ZWM1MThjMTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTY4MTc3Y2JjYzFmOWVlODdhMWEyYjU4MmExMGVhZTE3NDc4YjdlNDVhNzRlYjNmYjEyZmE5MTk1NTg1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.03n4jxHnqSkvHhCT6o_bL15ASZ9U_Glx_HC5gRIKndQ) ![image](https://private-user-images.githubusercontent.com/87296715/302071581-003fa1d3-6f45-4856-9ef4-bae61b2c9275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzMxNTksIm5iZiI6MTcwNzAzMjg1OSwicGF0aCI6Ii84NzI5NjcxNS8zMDIwNzE1ODEtMDAzZmExZDMtNmY0NS00ODU2LTllZjQtYmFlNjFiMmM5Mjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZmVlMWRiNGYyMDJjNTdkZTA4YWZmYzFhZDE5NWZiMWU2MGM1ZTE0MDE5M2FjYWI4YTdkOGZjMmMwOWNmMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BxV8StA5NsQsvuIP45HQ_nLpkRUZiB5pafviX_CIADg) 是否是我的命令不对

你怎么判断不生效的的，ffmpeg 不是有输出日志吗？？？
