### ISSUE TITLE
手机端浏览器如何播放

### ISSUE THREAD

**Issue by chenzongyuanczy** [ZLMediaKit/ZLMediaKit#3290]
**咨询的功能模块**
播放url规则模块
https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99
请问下链接如何在手机端浏览器播放？

**Comment by xiongguangjie** [comment]
使用zlmrtcclient.js 或者 whep播放器，或者hls.js flv.js 播放器

**Comment by chenzongyuanczy** [comment]
> 使用zlmrtcclient.js 或者 whep播放器，或者hls.js flv.js 播放器

hls.js flv.js没法在safari浏览器播放（电脑浏览器和安卓浏览器可以）

**Comment by chenzongyuanczy** [comment]
苹果用video标签就自动支持hls了 不需要hls.js
