### ISSUE TITLE
WebRTC P2P connection

### ISSUE THREAD

**Issue by TheMadius** [ZLMediaKit/ZLMediaKit#3291]
Hello.

Is it possible to connect 2 clients via P2P using STUN? Now all data goes through the server MediaServer

And the error below is critical?
```
2024-02-05 12:43:42.089 E [MediaServer] [2535308-event poller 0] DtlsTransport.cpp:744 ProcessDtlsData | cannot process data while not running
```

**Comment by Goga1992** [comment]
I confirm. I also observe traffic passing only through the server in all cases

**Comment by xiongguangjie** [comment]
rtc client can connect via p2p using stun, through sdp offer/anwser, this is not relay on ZLM

**Comment by xiongguangjie** [comment]
ZLM webrtc is sfu mode ,  all stream must through ; because ZLM is media stream server

**Comment by TheMadius** [comment]
Thanks for the answer
