### ISSUE TITLE
[技术咨询] feature/transcode分支是自动将H265流转H264的吗？

### ISSUE THREAD

**Issue by Neon-C23** [ZLMediaKit/ZLMediaKit#3303]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
feature/transcode分支的H265流如何转码到H264？

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
feature/transcode分支程序是否自动将H265转码H264？
如果不是，请问要如何配置？我未在config.ini中看到相关配置，也未搜索到相关的issue。
输入的流为 rtsp-h265 需要转为 flv-h264
非常感谢！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by Neon-C23** [comment]
补充说明：
输入的流为 rtsp-h265 需要转为 flv-h264

**Comment by Neon-C23** [comment]
> 不会，只会音频转码，转码为rtc 能够播放的

谢谢回答！
请问如果要转视频编码的话只能借助zlmediakit有关ffmpeg的http接口或者单独调用ffmpeg转码推流吗？

**Comment by xiongguangjie** [comment]
> > 不会，只会音频转码，转码为rtc 能够播放的
> 
> 谢谢回答！ 请问如果要转视频编码的话只能借助zlmediakit有关ffmpeg的http接口或者单独调用ffmpeg转码推流吗？

addffmpegsource 可以实现，或者购买https://github.com/tsingeye/ZLMediakit-Pro
