### ISSUE TITLE
流媒体接收RTSP流超时，无法进行RTSP流代理。

### ISSUE THREAD

**Issue by MQDHY** [ZLMediaKit/ZLMediaKit#3304]
在使用过程遇到在代理RTSP流，流地址是能正常访问的。但是读流的时候就会提示超时。
![1708257237291](https://github.com/ZLMediaKit/ZLMediaKit/assets/50725124/67ccfc0b-af06-4737-85bf-c72e0cddaaeb)

这种情况是当前这个RTSP流无法被流媒体识别吗？带着疑问进行了一下抓包分析。解析时发现数据包中提示有个版本3。
![a274f5b690b09573f1049eb64ec8839](https://github.com/ZLMediaKit/ZLMediaKit/assets/50725124/f546f5a1-dedd-4e3b-8364-956225274c31)

目前这个流如果需要流媒体解析的话，我需要怎么操作能解析这个流呢。希望作者大大指点一下

数据包如下
[20240219-10-14.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14325798/20240219-10-14.zip)

**Comment by xiongguangjie** [comment]
我这里看数据保报解析是正常的

**Comment by sanrenyiyue** [comment]
我也遇到同样的问题
