### ISSUE TITLE
[技术咨询] loadMP4File 接口，用vlc 播放一段时间，流还在，页面会卡住，这是什么情况

### ISSUE THREAD

**Issue by WalkerPlus** [ZLMediaKit/ZLMediaKit#3310]
**咨询的功能模块**
- loadMP4File 接口

**咨询的具体内容和问题**
- 用vlc 播放一段时间，流还在，页面会卡住，底下时长还在走这是什么情况
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/16448447/81bc1388-e8be-4f51-9d3f-d61336f620a5)

**注意事项**

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by WalkerPlus** [comment]
> 是不是已经循环播放呢？

不是，就是正常播放，才放几分钟

**Comment by xia-chu** [comment]
我重现不了这个问题 有可能是你视频有问题

**Comment by WalkerPlus** [comment]
> 我重现不了这个问题 有可能是你视频有问题

好的，我这边多测一下
