### ISSUE TITLE
请问这个未知ip是zlm用到的吗

### ISSUE THREAD

**Issue by luhengyu1** [ZLMediaKit/ZLMediaKit#3311]
![1708592292780](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/95740253-2307-4711-abbe-838cf4beea73)

无意间看到了有一个未知的ip 108.181.24.73:8888
并且他是可以访问的。

![1708591664355](https://github.com/ZLMediaKit/ZLMediaKit/assets/87296715/133139cd-e1c9-4971-b6d0-c3f372892aaf)

我仔细检查了我的配置文件，似乎没有用到这个ip地址

**Comment by xiongguangjie** [comment]
用于统计有哪些ZLM服务器的实例，可以关闭，至于方法，看源码
