### ISSUE TITLE
[BUG] 白名单问题

### ISSUE THREAD

**Issue by renlw123** [ZLMediaKit/ZLMediaKit#3312]
<img width="503" alt="企业微信截图_1708597123168" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/74169518/2372da76-a2c9-4ddd-abc1-6c7a93ad7067">

http 设置白名单功能，当访问的是目录的时候白名单是生效的，但是当访问具体资源的时候感觉有问题
例如：a机器ip不在白名单范围内，访问主页或者一些目录的时候虽然401，但是当访问具体资源的时候确是404（理应也应该是401才对）

**Comment by renlw123** [comment]
不知道是不是我配置错了

**Comment by xia-chu** [comment]
没有 zlm是先判断文件存不存在 再判断是否有权限访问

**Comment by renlw123** [comment]
[http]
allow_cross_domains=1
allow_ip_range=192.168.80.2
表面上白名单生效了，但是我通过vlc访问实际资源的时候显然白名单没有起到作用，还是可以访问的，所以我觉得应该是优先判断权限才对

![1709790972854](https://github.com/ZLMediaKit/ZLMediaKit/assets/74169518/bba5baff-c101-405c-8ced-89c3b04fad18)

**Comment by xiongguangjie** [comment]
> allow_cross_domains

#允许访问http api和http文件索引的ip地址范围白名单，置空情况下不做限制
这个白名单只限制api接口与文件索引，对于文件下载是不管的

**Comment by xia-chu** [comment]
hls下载不过白名单的逻辑 它走播放鉴权的逻辑
