### ISSUE TITLE
[功能请求] kStreamNoneReaderDelayMS设置为永久

### ISSUE THREAD

**Issue by sincebyte** [ZLMediaKit/ZLMediaKit#3313]
**描述该功能的用处，可以提供相关资料描述该功能**
当无人观看时，期望zlm继续保持录制到永久，当然目前了解到zlm不提供文件存储策略

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
否

**描述你期望实现该功能的方式和最终效果**
kStreamNoneReaderDelayMS设置为-1表示不判断是否有人观看。

**Comment by xiongguangjie** [comment]
无人观看你不处理不就行了

**Comment by sincebyte** [comment]
默认会处理，会关流，关了录制就没了

**Comment by xiongguangjie** [comment]
> 默认会处理，会关流，关了录制就没了

你wvp ??? ,如果是的，那只能去看wvp的配置或者实现了

**Comment by sincebyte** [comment]
是wvp，但kStreamNoneReaderDelayMS这个配置不是ZLM的嘛，就想问下能否支持-1，此时没人看时不关闭流

**Comment by xiongguangjie** [comment]
> 是wvp，但kStreamNoneReaderDelayMS这个配置不是ZLM的嘛，就想问下能否支持-1，此时没人看时不关闭流

mp4_as_player 配置选项设置为1

**Comment by sincebyte** [comment]
> > 是wvp，但kStreamNoneReaderDelayMS这个配置不是ZLM的嘛，就想问下能否支持-1，此时没人看时不关闭流
> 
> mp4_as_player 配置选项设置为1

明白了，录制也做为一个人在看，就不会触发无人观看hook了
