### ISSUE TITLE
ffmpeg推流能否在不将hook的enable置为0的情况下进行鉴权推流，我加secret发现也无法绕过鉴权，下面贴出我的日志和配置还有ffmpeg的命令

### ISSUE THREAD

**Issue by jiaofenbang** [ZLMediaKit/ZLMediaKit#3314]
如何绕过鉴权，在不关闭hook的情况下，因为每次关闭了，我wvp重新启动就会自动将这配置置为1，所以我想直接用admin_params绕过认证，但是发现无效,我是mac系统，zlm装在docker下
我的ffmpeg推流命令ffmpeg -re -stream_loop -1 -i /Users/asd/Desktop/t/oceans.mp4 -c:v copy -c:a copy -rtsp_transport tcp -f rtsp "rtsp://127.0.0.1:8555/live/oceans?secret=E8iSJo8fJ4f48igdxrT3qFxDAOPSGJ9Z"

config.ini配置项
![1708879017335](https://github.com/ZLMediaKit/ZLMediaKit/assets/95263080/968dc1d9-bb00-410f-b160-00bb8a6904f1)

zlm日志
![1708879227188](https://github.com/ZLMediaKit/ZLMediaKit/assets/95263080/4deb96e5-b4af-4cc6-aa6b-b5be401ae0bd)

**Comment by xiongguangjie** [comment]
最新的代码没有这个功能，除非你二开

**Comment by xia-chu** [comment]
admin_params已经去掉了 127.0.0.1不鉴权的机制也去掉了。
你可以在ffmpeg模板中设置推流url超级密码，你在hook中放行下这个超级密码就行
