### ISSUE TITLE
wsPlayer（ws-fmp4）格式不能正常播放

### ISSUE THREAD

**Issue by jamesZHANG500** [ZLMediaKit/ZLMediaKit#3315]
### 现象描述

使用[wsPlayer](https://github.com/v354412101/wsPlayer) 这个播放器播放视频流，23.11提交前的版本一直是正常，最近做了ZLM下升级，发现使用相同的播放器播放，视频一卡一卡的怀疑可能只有I帧被播放，有点奇怪不知道为什么。
了解到wsPlayer使用的是ws-fmp4格式播放，是不是这一块改动有什么问题，能帮看一下吗
同时我测试rtsp,rtmp,http-fmp4都能正常播放，在浏览器敲入http-fmp4地址可以直接出视频，所以可能出现在ws这一块

### 如何复现?
使用[wsPlayer](https://github.com/v354412101/wsPlayer)  播放就可以复现

**Comment by jamesZHANG500** [comment]
问题已解决，但是有点奇怪，简单记录一下，作者可以考虑是否要修复吧
这个问题只出现在我这边摄像头设备搭建的zlm软件中，设备创建流是使用DevChannel类创建的，
但是如果我使用最新代码部署到linux服务器中，让设备通过rtmp推流，然后使用wsPlayer播放是正常的，所以这个问题应该只有在设备DevChannel创建的流才会复现
具体代码，我不是很清楚，没办法通过看代码找问题，我只能通过作者提交的代码一步步回滚找问题，因为之前的版本是正常的，我通过创建多分支，先撤销作者提交回归到很老版本，然后一步步减少撤销最终定位到[优化平滑发送逻辑，解决时间戳跳变导致发送不平滑问题](https://github.com/ZLMediaKit/ZLMediaKit/commit/6ff5556b71162363d718428ec241b0efc5cd6410) 这个提交后就会出现问题，这个提交前就正常，撤销这个提交，解决变量命名报错，我这边使用最新代码也能正常播放了，因为只在设备端出现，不确定这个是不是bug，我就不提交pr了作者考虑一下，要不要修复吧。
另外顺便提一下，如果设备端要使用fmp4录像，达到断电异常录像也可以被打开，好像要做一下修改，反正我是这样做，才正常，不确定修改的方式是否正确，修改src/Record/Mp4Muxer.cpp

**Comment by jamesZHANG500** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/7957917/8c55ac40-4eaf-44af-a622-bad34d10eede)

**Comment by xia-chu** [comment]
> 如果设备端要使用fmp4录像，达到断电异常录像也可以被打开

这个修改可以来个pr 可以通过配置文件选择是否开启 谢谢！

**Comment by xia-chu** [comment]
[优化平滑发送逻辑，解决时间戳跳变导致发送不平滑问题](https://github.com/ZLMediaKit/ZLMediaKit/commit/6ff5556b71162363d718428ec241b0efc5cd6410)

这个提交应该是没问题的 因为默认关闭了平滑发送

**Comment by xia-chu** [comment]
fmp4播放变卡顿 可能是我去掉了50ms fmp4缓存的机制。 之前发现在某些播放器上，如果每帧数据都flush fmp4，会导致播放卡顿，但是浏览器上播放没这个问题，为了降低延时同时提高性能，就去掉缓存50ms fmp4的机制了，因为毕竟fmp4直播基本都是浏览器播放器。

不知道是不是跟你说的一个问题

**Comment by jamesZHANG500** [comment]
我这边复现的卡顿就是使用wsPlayer那个播放器在浏览器播放的，看起来一卡一卡的 但是调试浏览器ws传输数据都是一直是有的，一卡一卡看起来是每2秒会刷新一张图我这边设置I帧间隔刚好是2秒，所以怀疑可能是只播放了I帧。反正现在我撤销那个提交就正常 也不懂为什么

**Comment by xia-chu** [comment]
你配置文件开了paced_sender_ms?

**Comment by jamesZHANG500** [comment]
> 你配置文件开了paced_sender_ms?

没有

**Comment by xia-chu** [comment]
那有没有可能你输入的数据本身时间戳就不好 或者输入频率不平滑呢

**Comment by jamesZHANG500** [comment]
这个不好说，有这个可能吧 ，我这边使用的是rk3588板子出的视频，时间戳是他sdk提供的，输入频率是有数据就会调用devChannel inputFrame ，有可能是设备端的问题，因为我测试如果zlm作为服务器端，设备作为推流端 同样的播放器是可以在浏览器是正常播放的，所以这一块 也可以不用管，可能只是我的设备需要这样改

**Comment by jamesZHANG500** [comment]
> > 如果设备端要使用fmp4录像，达到断电异常录像也可以被打开
> 
> 这个修改可以来个pr 可以通过配置文件选择是否开启 谢谢！

那我就把这个提交个pr,增加一个配置参数record.enableFmp4 来控制_mp4_file->createWriter 的第2个参数 是否开启fmp4? 
这个提交太简答了 ，之前我也对zlm也做了少量修改 其中修改Http 访问支持参数传递 ，简单的信息如下图，你看一下 可以的话我就一起提交过来
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/7957917/34784117-41da-4711-8440-418ecd8cab9b)

**Comment by xia-chu** [comment]
都可以提交，不同的功能请麻烦做成两个pr。
