### ISSUE TITLE
[技术咨询] 国标被动对讲噪音很大

### ISSUE THREAD

**Issue by 331299** [ZLMediaKit/ZLMediaKit#3316]
**咨询的功能模块**
- startSendRtpPassive接口

**咨询的具体内容和问题**
- 使用udp对讲时，功能正常。但是使用tcp被动对讲时，测试用的一个海康和大华的摄像头，都有很多噪音，只有一个基于安卓的对讲机是正常的。
- 调用startSendRtpPassive时，使用的es流pt=8&use_ps=0&only_audio=1。如果使用ps流的话，海康的有声音和噪音，大华的没有声音。
- 邀请海康的摄像头使用tcp被动时，海康摄像头回复的sdp中，只有“RTP/AVP”，未包含“TCP/”，但是后续流程是对的，不确定它是真的不支持tcp被动对讲，还只是回复的sdp有问题。

**Comment by xiongguangjie** [comment]
这个我也遇到了，我感觉是国标设备的问题，现在ZLM pcma 发送是一个包20ms ,如果一个包变成100ms 会大大缓解这种情况，我感觉这是国标设备播放音频的问题

**Comment by 331299** [comment]
> 这个我也遇到了，我感觉是国标设备的问题，现在ZLM pcma 发送是一个包20ms ,如果一个包变成100ms 会大大缓解这种情况，我感觉这是国标设备播放音频的问题，我是海康设备

对，我试过自己写代码，读取文件，每次发送400byte，会好不少

**Comment by xiongguangjie** [comment]
> > 这个我也遇到了，我感觉是国标设备的问题，现在ZLM pcma 发送是一个包20ms ,如果一个包变成100ms 会大大缓解这种情况，我感觉这是国标设备播放音频的问题，我是海康设备
> 
> 对，我试过自己写代码，读取文件，每次发送400byte，会好不少

udp 发送效果咋样？？？

**Comment by 331299** [comment]
> udp 发送效果咋样？？？

udp对讲正常

**Comment by MengFanLu1** [comment]
我感觉是这样,海康的大多数设备是不支持TCP主动的,你回复的信令invite虽然描述的是tcp连接,tcp通道也建立上了,但是海康还是按照udp over rtp包来解析的,我试过海康支持TCP不会有噪音的

**Comment by 331299** [comment]
> 我感觉是这样,海康的大多数设备是不支持TCP主动的,你回复的信令invite虽然描述的是tcp连接,tcp通道也建立上了,但是海康还是按照udp over rtp包来解析的,我试过海康支持TCP不会有噪音的

我这的海康是不支持，大华的那个没法选择传输方式，一直是udp连过来的，但下发talk命令时，带上tcp，响应的sdp中也有tcp，后续也会按流程来，就是会有噪音。自己写代码发送测试过，海康那个，不按照rtp over tcp，即不加rtp包前面那两个字节的包长度，效果确实最好。大华的，如果不按照rtp over tcp来，会有问题，应该能侧面证明大华支持，就是不知道为什么会有噪音。

目前暂时把ext-codec/G711Rtp.cpp 中的20改为200，160改为1600，海康和大华的tcp对讲，效果好很多

**Comment by daixy111040536** [comment]
> **咨询的功能模块**
> 
> * startSendRtpPassive接口
> 
> **咨询的具体内容和问题**
> 
> * 使用udp对讲时，功能正常。但是使用tcp被动对讲时，测试用的一个海康和大华的摄像头，都有很多噪音，只有一个基于安卓的对讲机是正常的。
> * 调用startSendRtpPassive时，使用的es流pt=8&use_ps=0&only_audio=1。如果使用ps流的话，海康的有声音和噪音，大华的没有声音。
> * 邀请海康的摄像头使用tcp被动时，海康摄像头回复的sdp中，只有“RTP/AVP”，未包含“TCP/”，但是后续流程是对的，不确定它是真的不支持tcp被动对讲，还只是回复的sdp有问题。

你好，请教一下你采用的是哪款设备，我咨询海康客户，说他们设备都不支持公网对讲。。

**Comment by 331299** [comment]
> 你好，请教一下你采用的是哪款设备，我咨询海康客户，说他们设备都不支持公网对讲。。

DS-2DE2402IW-D3/W/XM，可能是这个吧，我问他们客服，倒是没说不能公网对讲，只是问他们噪音问题，他们也不清楚

**Comment by xiongguangjie** [comment]
> DS-2DE2402IW-D3/W/XM

这么巧合，用的同款摄像头

**Comment by 331299** [comment]
> 这么巧合，用的同款摄像头

都是某东。。。

**Comment by 331299** [comment]
@xiongguangjie 大神有没有解决方案，是只能改每次发送的音频时长了吗
