### ISSUE TITLE
webrtc, h264_stap_a=0 and firefox

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#3319]
Hello
For some multicast client I need to set 

`c++
mINI::Instance()[Rtp::kH264StapA] = 0;
`

At the same time, WebRtc stops working in Firefox.
Everything is fine in Chromium.

Before updating from 20231025 to the latest there was no such problem

**Comment by xiongguangjie** [comment]
because firefox not support packetization-mode is 0 https://bugzilla.mozilla.org/show_bug.cgi?id=1255408

this config setting only useful when you set directProxy is 0  if pusher is rtsp/rtc or other protocol pusher

**Comment by a-ucontrol** [comment]
Thank you
I did
``
       sdp = regex_replace(sdp, regex("packetization-mode=[^;]*;"), "packetization-mode=1;");
``
and the firefox working
