### ISSUE TITLE
zlm返回的播放地址可以动态变化吗

### ISSUE THREAD

**Issue by UChiHa-Obitoto** [ZLMediaKit/ZLMediaKit#3320]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
播放地址
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
zlm返回的播放地址可以根据请求动态变化吗
例如，内网请求返回http://ip:80/rtp/流id/live.flv
           外网请求返回http://域名:80/rtp/流id/live.flv
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个是业务服务（猜测你是用的wvp-pro，需要改wvp-pro）的事情，与ZLM没关系，你不使用vhost 就行

**Comment by UChiHa-Obitoto** [comment]
> 这个是业务服务（猜测你是用的wvp-pro，需要改wvp-pro）的事情，与ZLM没关系，你不使用vhost 就行

噢噢，那我去wvp那边问问

**Comment by UChiHa-Obitoto** [comment]
问了那边，已经解决，谢谢
