### ISSUE TITLE
[技术咨询] GB28181中语音对讲过程中采用TCP passtive，是否是每次都是新开一个端口？

### ISSUE THREAD

**Issue by daixy111040536** [ZLMediaKit/ZLMediaKit#3321]
咨询的功能模块

startSendRtpPassive接口
咨询的具体内容和问题

我在学习代码的时候，看到了语音对讲这个功能的接口时，
 if (args.passive) {
        // tcp被动发流模式
        _args.is_udp = false;
        // 默认等待链接
        bool is_wait = true;
        try {
            auto tcp_listener = Socket::createSocket(_poller, false);
            if (args.src_port) {
                //指定端口
                if (!tcp_listener->listen(args.src_port)) {
                    throw std::invalid_argument(StrPrinter << "open tcp passive server failed on port:" << args.src_port
                                                           << ", err:" << get_uv_errmsg(true));
                }
                is_wait = true;
            } else {
                auto pr = std::make_pair(tcp_listener, Socket::createSocket(_poller, false));
                //从端口池获取随机端口
                makeSockPair(pr, "::", false, false);
                // 随机端口不等待，保证调用者可以知道端口
                is_wait = false;
            }
这段代码中的src_port，如果2个设备指定了同一个src_port是不是就失败了？也就是zml是通过port来对应设备的吗？每次一个设备需要语音对讲，就分配一个port让设备连接上来吗？这样就知道是哪个设备连接上来了，是吗？那这样岂不是要消耗大量的端口。

**Comment by xiongguangjie** [comment]
是的 ，但是链接建立后，就可以回收端口了，也可以通过ssrc 来区分，但是很多设备都不按规则来，ssrc 不一定有效

**Comment by daixy111040536** [comment]
> 是的 ，但是链接建立后，就可以回收端口了，也可以通过ssrc 来区分，但是很多设备都不按规则来，ssrc 不一定有效

是指delay_task->cancel() 这一步会把_strongTask 置空，所以上文的tcplistener 也就没有持有者释放掉了是吗？这种方式如果是服务器要部署在公网，需要根据端口做安全配置还挺麻烦的，要预先留一堆端口用于做端口池分配使用？没有其他的方法了吗，设备连上来会发送报文过来吗？因为我看协议GB28181上没有规定这个,我在想如果设备连接上来，如果有发送rtp或者rtcp，我去获取ssrc了。

**Comment by xiongguangjie** [comment]
> 这种

端口反应配置就行了，没啥麻烦的，为了兼容性，这个是必要的

**Comment by daixy111040536** [comment]
> 是的 ，但是链接建立后，就可以回收端口了，也可以通过ssrc 来区分，但是很多设备都不按规则来，ssrc 不一定有效

这个可以用ssrc区分，在这种被动链接上是不是不可用，设备连上来还会发报文上来吗？

**Comment by xiongguangjie** [comment]
> 用端口区分还会有个时间差的问题，在大并发下端口被耗尽，我看超时是5s之后就回收了，如果这时候2台设备同时都分配到同一个端口，上一设备因为网络的问题，过来5s才连上来，这时候不就乱了吗
一共6万多个端口，你能有这么高的并发，端口耗尽会报错的，这个不会有冲突的

**Comment by daixy111040536** [comment]
> > 用端口区分还会有个时间差的问题，在大并发下端口被耗尽，我看超时是5s之后就回收了，如果这时候2台设备同时都分配到同一个端口，上一设备因为网络的问题，过来5s才连上来，这时候不就乱了吗
> > 一共6万多个端口，你能有这么高的并发，端口耗尽会报错的，这个不会有冲突的

比如你设置了10个端口,_port_pair_pool这个是队列，那么假设是1-10，那么如果这个时候有10个设备连上来，那么10个端口都被消耗掉了，然后这时候1设备5s超时，端口1回收到队列里，然后又被分配给新的设备了，但是如果旧设备的网络恢复了，它的定时器是10s，因为1端口又重新监听了，这个时候就是2个设备抢一个端口了，结果就是有概率会被发错设备了。当然这个range如果设置得很大，那么一圈下来的遇到这个问题的概率就很小，所以如果在压测过程中，就很有可能出现异常了。

**Comment by xiongguangjie** [comment]
> > > 用端口区分还会有个时间差的问题，在大并发下端口被耗尽，我看超时是5s之后就回收了，如果这时候2台设备同时都分配到同一个端口，上一设备因为网络的问题，过来5s才连上来，这时候不就乱了吗
> > > 一共6万多个端口，你能有这么高的并发，端口耗尽会报错的，这个不会有冲突的
> 
> 比如你设置了10个端口,_port_pair_pool这个是队列，那么假设是1-10，那么如果这个时候有10个设备连上来，那么10个端口都被消耗掉了，然后这时候1设备5s超时，端口1回收到队列里，然后又被分配给新的设备了，但是如果旧设备的网络恢复了，它的定时器是10s，因为1端口又重新监听了，这个时候就是2个设备抢一个端口了，结果就是有概率会被发错设备了。当然这个range如果设置得很大，那么一圈下来的遇到这个问题的概率就很小，所以如果在压测过程中，就很有可能出现异常了。

基本上不会有这个问题，tcp链接断开后，一般来说会话会结束的
