### ISSUE TITLE
[技术咨询] 关于滚动存储功能

### ISSUE THREAD

**Issue by sincebyte** [ZLMediaKit/ZLMediaKit#3327]
**咨询的功能模块**
过了一遍ZLM的配置，发现并没有滚动存储的配置，想咨询下是没完善文档，还是说这部分功能有其他的解决方案？

**咨询的具体内容和问题**
滚动存储功能十分有必要，通常用在类似： ”视频保存最近7天“ 这样的功能上。
ZLM作为一款优秀的流媒体服务器应该具备这样的功能

**Comment by xiongguangjie** [comment]
> **咨询的功能模块** 过了一遍ZLM的配置，发现并没有滚动存储的配置，想咨询下是没完善文档，还是说这部分功能有其他的解决方案？
> 
> **咨询的具体内容和问题** 滚动存储功能十分有必要，通常用在类似： ”视频保存最近7天“ 这样的功能上。 ZLM作为一款优秀的流媒体服务器应该具备这样的功能

通过webhook,自己扩展

**Comment by sincebyte** [comment]
@xiongguangjie 是指通过on_flow_report流事件来删除文件吗？
