### ISSUE TITLE
【技术咨询】点播失败，提示“点播超时”、“收流超时”

### ISSUE THREAD

**Issue by Farrahchen** [ZLMediaKit/ZLMediaKit#3330]
**咨询的功能模块**
- GB28181视频监控、海康录像机

**咨询的具体内容和问题**
- 播放监控视频报错：点播超时，收流超时

WVP日志如下：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/49346335/befff590-6f70-4abb-8043-851f8bc36e29)

ZLM日志：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/49346335/6720ad88-ed05-441d-9853-a2f804905045)

**Comment by xia-chu** [comment]
此问题与zlm无关 请去wvp提issue
