### ISSUE TITLE
截图api接口可否支持传addStreamProxy接口的stream标识抓取此流的截图，返回图片可否提供图片的保存位置信息，不返回图片文件流，这样交互更加便捷

### ISSUE THREAD

**Issue by qilaohan** [ZLMediaKit/ZLMediaKit#3331]
截图api接口可否支持传addStreamProxy接口的stream标识抓取此流的截图，返回图片可否提供图片的保存位置信息，不返回图片文件流，这样交互更加便捷。

**Comment by xia-chu** [comment]
返回图片位置 你也访问不了啊 这个接口有不是给本机使用的 是给浏览器访问的。

**Comment by xia-chu** [comment]
getSnap接口当初设计是为了通用型 所以也可以截图非zlm的图片，所以要指定截图url
