### ISSUE TITLE
[技术咨询] 求官方提供一份关于ZLM服务器部署规格的要求

### ISSUE THREAD

**Issue by sincebyte** [ZLMediaKit/ZLMediaKit#3338]
**咨询的功能模块**
我翻看了ZLM的文档已经ISSUES清单，没有发现官方或者三方对ZLM服务器部署规格的要求说明。
我们仅看到在对zlm介绍README上有如下阐述，但尚不清楚这样的性能需要在多少核心的CPU多少内存的情况下能达到。
```
极致性能，单机10W级别播放器，100Gb/s级别io带宽能力。
```

为更好促进zlm的发展，恳请官方出具一份部署规格要求，最好也包括压力测试结果。

万分感谢！

**Comment by xiongguangjie** [comment]
参考这个
https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95

如果你需要10W,100GB/s的

**Comment by sincebyte** [comment]
牛！
