### ISSUE TITLE
[技术咨询] zlm作为国标设备的流媒体服务器发现flv播放卡顿

### ISSUE THREAD

**Issue by xushuxiong** [ZLMediaKit/ZLMediaKit#3341]
**GB28181播放咨询**
- 您好，我在使用zlm作为国标设备的流媒体服务器的时候，发现tcp传输的rtsp流播放花屏；发现使用tcp传输的rtsp流播放画面正常，但是有时延迟，但是使用mpegts播放flv时发现卡顿，请问是需要调整配置文件的参数吗？

视频效果参照附件：

https://github.com/ZLMediaKit/ZLMediaKit/assets/48349578/766c266e-d4d5-4748-959b-32d814e7e6a8

https://github.com/ZLMediaKit/ZLMediaKit/assets/48349578/d7e76a9e-1049-41fb-80a9-f8401473537e

[](https://github.com/ZLMediaKit/ZLMediaKit/assets/48349578/e0d23fc0-fc9f-4033-80d8-22c2677a271f)

**Comment by xushuxiong** [comment]
您好，昨天出现的情况是使用zlm的测试工具进行拉5000路流，机器带宽的上行网络达500M左右（网卡本身是千兆的），然后接受国标设备的媒体数据就出现上诉情况，请问是因为测试的影响吗？还是在拉5000路的情况下会出现国标不稳定的情况？

**Comment by xia-chu** [comment]
vlc rtsp  over udp丢包正常，ffmpeg能好点。这个是他们的bug，他们是同步socket接收数据，很容易丢包。

**Comment by xia-chu** [comment]
flv卡顿这个问题 可能是带宽不够了 也可能zlm负载比较高，可以把配置文件enable_hls关闭试试
