### ISSUE TITLE
[技术咨询] ffmpeg 同时推500路rtsp视频流到zlmediakit， zlmediakit报错 RtpReceiver.h:167 output | packet dropped

### ISSUE THREAD

**Issue by yuansonghui** [ZLMediaKit/ZLMediaKit#3343]
版本commit :  Feb 19, 2024 
操作：通过ffmpeg 同时拉取600路视频流，通过rtsp协议推送到zlmediakit， mediakit 一直打印错误，且视频播放不了，如附件所示，请问这种场景一般是什么原因造成的，万分感谢！！！

![20240305145751](https://github.com/ZLMediaKit/ZLMediaKit/assets/13591186/aae43c32-c02c-4cbc-9480-59e9b2849ab1)

**Comment by yuansonghui** [comment]
SEQ 校验不正确，后面就一直错误了，会不会是串流了，导致拿到的sqe 都比现在的小

**Comment by yuansonghui** [comment]
![微信截图_20240305173611](https://github.com/ZLMediaKit/ZLMediaKit/assets/13591186/e34e2dd3-5e7b-487c-944e-8d4c695c086f)
也打印时间戳回头了，这会不会跟时间戳有关，但是我们把摄像机时间跟服务器时间都校对了，还是一样报这个错

**Comment by xiongguangjie** [comment]
1，提示丢包问题，你是要rtp over tcp 来推流到ZLM,你这种很可能是带宽太高（网卡可能是千兆，600路超过了），导致的丢包
2，ffmpeg 时间戳问题，一般是你写入ffmpeg 的时间戳有问题

**Comment by xia-chu** [comment]
你要压测最好先看一遍wiki中压测相关的文档，你现在压测可能有几个问题：

- 1、这么多ffmpeg进程推流，你压测服务器扛得住，ffmpeg推流有指定`-rtsp_transport tcp`吗？
- 2、zlm的hls关了吗？配置文件enable_hls设置为0。
- 3、你局域网带宽够吗？
