### ISSUE TITLE
[技术咨询] 关于开始录制接口

### ISSUE THREAD

**Issue by sincebyte** [ZLMediaKit/ZLMediaKit#3346]
**咨询的功能模块**
关于开始录制接口 /index/api/startRecord
如果将zlm的录制配置项：enable_mp4设置为0，是否表示播放默认不开启录制。
在enable_mp4设置为0的情况下，调用/index/api/startRecord还能进行录制吗？

**Comment by xiongguangjie** [comment]
> **咨询的功能模块** 关于开始录制接口 /index/api/startRecord 如果将zlm的录制配置项：enable_mp4设置为0，是否表示播放默认不开启录制。 在enable_mp4设置为0的情况下，调用/index/api/startRecord还能进行录制吗？
第一 enable_mp4 等于0 表示当牛注册上来时，不录制
第二 可以调用接口录制

**Comment by sincebyte** [comment]
@xiongguangjie 感谢回复~
