### ISSUE TITLE
[BUG] 使用ffmpeg录制zlm中的rtsp流，时长不正常，大小正常

### ISSUE THREAD

**Issue by iwanlebron** [ZLMediaKit/ZLMediaKit#3347]
### 现象描述

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/fb727467-f596-434f-bd8a-255d4524579e)

### 如何复现?

无法复现

### 各种环境信息

* **代码提交记录/git commit hash**: 6b9889a
* **操作系统及版本**: linux
* **硬件信息**:  ARM
* **其他需要补充的信息**:  openEuler 20.03

**Comment by iwanlebron** [comment]
Uploading test.mp4…

**Comment by iwanlebron** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/assets/105045937/cabb63ac-6583-42cf-886c-7a7c0a24491f

**Comment by iwanlebron** [comment]
ffmpeg录制参数 
"rtsp_transport":      "tcp",
"vcodec":              "copy",
"fflags":              "+genpts",
"flags":               "+global_header",
"f":                   "segment",
"segment_time":        segment,
"strftime":            1,
"segment_atclocktime": 1,
"reset_timestamps":    1,

**Comment by xia-chu** [comment]
抱歉 不知所云。

**Comment by iwanlebron** [comment]
录制的1分钟视频 实际只有不到1s  视频大小和正常录制的视频一致

**Comment by xia-chu** [comment]
> 录制的1分钟视频 实际只有不到1s 视频大小和正常录制的视频一致

如果直播播放没问题 但是ffmpeg入职有问题 那么多半是你录制命令有问题啊
