### ISSUE TITLE
hls.fmp4 在按需生成时，先播后拉流，不能正常播放

### ISSUE THREAD

**Issue by yduis6554** [ZLMediaKit/ZLMediaKit#3348]
**hls.fmp4,  当在按需生成时，触发无人观看，执行 clearCache()  时，会把 init.mp4 文件删除， 从而导致播放失败。**

![QQ图片20240306134222](https://github.com/ZLMediaKit/ZLMediaKit/assets/4230657/0efdc133-3d74-4c94-9d04-ce6c3b41028b)

以下引用： https://github.com/ZLMediaKit/ZLMediaKit/issues/3153  的内容

              https://github.com/ZLMediaKit/ZLMediaKit/blob/7c42ac4d79d310f52f40673b31d3499fc8cd5518/src/Record/HlsMediaSource.cpp#L89
原因找到了，这里触发onReaderChanged(0)
https://github.com/ZLMediaKit/ZLMediaKit/blob/7c42ac4d79d310f52f40673b31d3499fc8cd5518/src/Record/HlsRecorder.h#L52
如果在获取ts播放之后，触发的第一次inputFrame会删除ts，出现上述情况（如果顺序是先clearCache再获取ts就正常）
https://github.com/ZLMediaKit/ZLMediaKit/blob/7c42ac4d79d310f52f40673b31d3499fc8cd5518/src/Record/HlsMediaSource.cpp#L90
我的解决办法是判断_clear_cache结束后再执行regist，即在`regist();`上面插入一行 `} else if (index_file.empty()) {`就解决了，或者还有什么更优的解决方式吗

_Originally posted by @vvoidon in https://github.com/ZLMediaKit/ZLMediaKit/issues/3153#issuecomment-1871821745_

**Comment by xiongguangjie** [comment]
```
diff --git a/src/Record/HlsMakerImp.cpp b/src/Record/HlsMakerImp.cpp
index e987f820..d62c4398 100644
--- a/src/Record/HlsMakerImp.cpp
+++ b/src/Record/HlsMakerImp.cpp
@@ -72,7 +72,7 @@ void HlsMakerImp::clearCache(bool immediately, bool eof) {
         std::list<std::string> lst;
         lst.emplace_back(_path_hls);
         lst.emplace_back(_path_hls_delay);
-        if (!_path_init.empty()) {
+        if (!_path_init.empty() && eof) {
             lst.emplace_back(_path_init);
         }
         for (auto &pr : _segment_file_paths) {
```
这么修改下，看看怎么样

**Comment by yduis6554** [comment]
> ```
> diff --git a/src/Record/HlsMakerImp.cpp b/src/Record/HlsMakerImp.cpp
> index e987f820..d62c4398 100644
> --- a/src/Record/HlsMakerImp.cpp
> +++ b/src/Record/HlsMakerImp.cpp
> @@ -72,7 +72,7 @@ void HlsMakerImp::clearCache(bool immediately, bool eof) {
>          std::list<std::string> lst;
>          lst.emplace_back(_path_hls);
>          lst.emplace_back(_path_hls_delay);
> -        if (!_path_init.empty()) {
> +        if (!_path_init.empty() && eof) {
>              lst.emplace_back(_path_init);
>          }
>          for (auto &pr : _segment_file_paths) {
> ```
> 
> 这么修改下，看看怎么样

感谢指导。 这样的修改后，完美解决了这个问题。 

有个小插曲，就是在播放其它类型的时候，也会生成一个 init.mp4 文件，直到流被注销，才会被清理掉，  影响不大。

**Comment by xia-chu** [comment]
这个问题确实存在 感谢反馈
