### ISSUE TITLE
[技术咨询] 请问通过VLC拉rtmp流时，首帧会出现streamed by zlmediakit git hash.....信息，请问可以通过配置文件去除吗？还是只能改源码。

### ISSUE THREAD

**Issue by lwh504530121** [ZLMediaKit/ZLMediaKit#3350]
**咨询的功能模块**
- vlc播放rtmp流

**咨询的具体内容和问题**
- 通过VLC拉rtmp流时，首帧会出现streamed by zlmediakit git hash.....信息，请问可以通过配置文件去除吗？还是只能改源码。感谢！！

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
你可以去除 版本信息那些东西 但是不能去掉 streamed by zlmediakit。
我们在mit协议补充条款中已经声明不得移除zlm的标识
