### ISSUE TITLE
[技术咨询] hls 和 hls.fmp4 在按需生成时的处理逻辑

### ISSUE THREAD

**Issue by yduis6554** [ZLMediaKit/ZLMediaKit#3357]
**咨询的功能模块**
- hls功能模块

**咨询的具体内容和问题**
**- 当开启  hls  和  hls_fmp4 ，并同时开启 按需生成 时，先播放后拉流，会出现只会生成一种类型，就是最先访问的那种类型。
- 比如：同一个流， 先访问的 hls.m3u8  , 再访问 hls.fmp4.m3u8  这样的话，服务器不会生成 hls.fmp4.m3u8 文件，会直接使用hls.m3u8给播放器。  反之 如果 先访问 hls.fmp4.m3u8 ，也只会生成 hls.fmp4.m3u8， 即使是访问 hls.m3u8 也不会再生成hls.m3u8文件。
- 但是，当关闭按需生成时，就会生成 ts 和 mp4 两种类型。**

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个你是最新的代码吗？ 我看代码是不会出现你说的那种情况的

**Comment by yduis6554** [comment]
我是通过 C# 直接调用的SDK，调用 mk_media_create 创建的媒体。刚刚重新接了最新的代码，调试还是一样。  如果直接使用MediaServer.exe ，用ffmpag 推流就没有这种情况。下图是调试时参数配置。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/4230657/0859422e-34d2-4851-9d4f-435d57e54b61)

**Comment by xiongguangjie** [comment]
这个提供下日志

**Comment by xia-chu** [comment]
这个问题 我查看代码 应该是不存在的
