### ISSUE TITLE
[编译问题] 编译webrtc报错

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#3365]
### 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

cd /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/build/webrtc && ccache /usr/bin/c++  -DDISABLE_REPORT -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/build -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/.. -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/src -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart/jsoncpp/include -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart/media-server/libflv/include -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart/media-server/libmov/include -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/3rdpart/ZLToolKit/src  -O3 -DNDEBUG   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g0 -std=gnu++11 -o CMakeFiles/webrtc.dir/TwccContext.cpp.o -c /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/TwccContext.cpp
In file included from /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:26:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In constructor ‘RTC::SrtpSession::SrtpSession(RTC::SrtpSession::Type, RTC::SrtpSession::CryptoSuite, uint8_t*, size_t)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:191:27: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  191 |     MS_ASSERT((int)keyLen == policy.rtp.cipher_key_len, "given keyLen does not match policy.rtp.cipher_keyLen");
      |               ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/logger.h:11:39: note: in definition of macro ‘MS_ASSERT’
   11 | #define MS_ASSERT(con, ...) do { if(!(con)) { PrintE(__VA_ARGS__); std::runtime_error("MS_ASSERT"); } } while(false)
      |                                       ^~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In member function ‘bool RTC::SrtpSession::EncryptRtp(uint8_t*, int*)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:230:57: error: invalid conversion from ‘void*’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  230 |     srtp_err_status_t err = srtp_protect(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                         |
      |                                                         void*
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:230:84: error: cannot convert ‘int*’ to ‘size_t*’ {aka ‘long unsigned int*’}
  230 |     srtp_err_status_t err = srtp_protect(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                    |
      |                                                                                    int*
In file included from /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:28:
/usr/local/include/srtp2/srtp.h:430:40: note:   initializing argument 3 of ‘srtp_err_status_t srtp_protect(srtp_ctx_t*, uint8_t*, size_t*, size_t)’
  430 |                                size_t *pkt_octet_len,
      |                                ~~~~~~~~^~~~~~~~~~~~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In member function ‘bool RTC::SrtpSession::DecryptSrtp(uint8_t*, int*)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:243:59: error: invalid conversion from ‘void*’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  243 |     srtp_err_status_t err = srtp_unprotect(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           |
      |                                                           void*
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:243:86: error: cannot convert ‘int*’ to ‘size_t*’ {aka ‘long unsigned int*’}
  243 |     srtp_err_status_t err = srtp_unprotect(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                      |
      |                                                                                      int*
In file included from /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:28:
/usr/local/include/srtp2/srtp.h:476:42: note:   initializing argument 3 of ‘srtp_err_status_t srtp_unprotect(srtp_t, uint8_t*, size_t*)’
  476 |                                  size_t *len_ptr);
      |                                  ~~~~~~~~^~~~~~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In member function ‘bool RTC::SrtpSession::EncryptRtcp(uint8_t*, int*)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:255:62: error: invalid conversion from ‘void*’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  255 |     srtp_err_status_t err = srtp_protect_rtcp(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              |
      |                                                              void*
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:255:89: error: cannot convert ‘int*’ to ‘size_t*’ {aka ‘long unsigned int*’}
  255 |     srtp_err_status_t err = srtp_protect_rtcp(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                         |
      |                                                                                         int*
In file included from /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:28:
/usr/local/include/srtp2/srtp.h:1151:45: note:   initializing argument 3 of ‘srtp_err_status_t srtp_protect_rtcp(srtp_t, uint8_t*, size_t*, size_t)’
 1151 |                                     size_t *pkt_octet_len,
      |                                     ~~~~~~~~^~~~~~~~~~~~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In member function ‘bool RTC::SrtpSession::DecryptSrtcp(uint8_t*, int*)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:268:64: error: invalid conversion from ‘void*’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
  268 |     srtp_err_status_t err = srtp_unprotect_rtcp(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                |
      |                                                                void*
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:268:91: error: cannot convert ‘int*’ to ‘size_t*’ {aka ‘long unsigned int*’}
  268 |     srtp_err_status_t err = srtp_unprotect_rtcp(this->session, static_cast<void *>(data), reinterpret_cast<int *>(len));
      |                                                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                           |
      |                                                                                           int*
In file included from /home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:28:
/usr/local/include/srtp2/srtp.h:1196:47: note:   initializing argument 3 of ‘srtp_err_status_t srtp_unprotect_rtcp(srtp_t, uint8_t*, size_t*)’
 1196 |                                       size_t *pkt_octet_len);
      |                                       ~~~~~~~~^~~~~~~~~~~~~
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp: In member function ‘void RTC::SrtpSession::RemoveStream(uint32_t)’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/SrtpSession.cpp:279:5: error: ‘srtp_remove_stream’ was not declared in this scope
  279 |     srtp_remove_stream(this->session, uint32_t { htonl(ssrc) });
      |     ^~~~~~~~~~~~~~~~~~
make[3]: *** [webrtc/CMakeFiles/webrtc.dir/build.make:144: webrtc/CMakeFiles/webrtc.dir/SrtpSession.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/Sdp.cpp: In member function ‘void mediakit::RtcSdpBase::toRtsp()’:
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/Sdp.cpp:993:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
  993 |                 }
      |                 ^
/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/webrtc/Sdp.cpp:995:13: note: here
  995 |             default: {
      |             ^~~~~~~
make[3]: Leaving directory '/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/build'
make[2]: *** [CMakeFiles/Makefile2:547: webrtc/CMakeFiles/webrtc.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/build'
make[1]: *** [Makefile:133: all] Error 2
make[1]: Leaving directory '/home/ubuntu/zhangchuanfeng/media-server/ZLMediaKit/build'
make: *** [Makefile:22: zlmediakit] Error 2

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

### 各种环境信息
ubuntu18.04

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by zhang-chuanfeng** [comment]
发现和libsrtp库接口有关  ubuntu下安装libsrtp需要从源码编译。不同版本导致编译不过，是否考虑从源码编译呢

**Comment by wuqi** [comment]
> 发现和libsrtp库接口有关 ubuntu下安装libsrtp需要从源码编译。不同版本导致编译不过，是否考虑从源码编译呢

srtp新版本我记得改了接口...你得对照下

**Comment by zhang-chuanfeng** [comment]
> > 发现和libsrtp库接口有关 ubuntu下安装libsrtp需要从源码编译。不同版本导致编译不过，是否考虑从源码编译呢
> 
> srtp新版本我记得改了接口...你得对照下

用的之前版本可以

**Comment by zhang-chuanfeng** [comment]
> > 发现和libsrtp库接口有关 ubuntu下安装libsrtp需要从源码编译。不同版本导致编译不过，是否考虑从源码编译呢
> 
> srtp新版本我记得改了接口...你得对照下

我用以前的版本  2.4.2  但是webrtc会报错。
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/713593fb-e24b-4519-8a7a-416061a338ec)

**Comment by xiongguangjie** [comment]
> > > 发现和libsrtp库接口有关 ubuntu下安装libsrtp需要从源码编译。不同版本导致编译不过，是否考虑从源码编译呢
> > 
> > 
> > srtp新版本我记得改了接口...你得对照下
> 
> 我用以前的版本 2.4.2 但是webrtc会报错。 ![image](https://private-user-images.githubusercontent.com/59160162/312300397-713593fb-e24b-4519-8a7a-416061a338ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTY3NzMsIm5iZiI6MTcxMDMxNjQ3MywicGF0aCI6Ii81OTE2MDE2Mi8zMTIzMDAzOTctNzEzNTkzZmItZTI0Yi00NTE5LThhN2EtNDE2MDYxYTMzOGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA3NTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NTIxMWVhNzA0NDg2NDk0ZDBkNWNmN2U0Njg1MzM5NWQzMTg3OTAzZjJiZDAwMTM4YjdlZDE2MGI5OWNlMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tvFTr5-Khuiu_IItWLLdrDMTR89ixwvsi2lCGek4YQg)

这个也要考虑下openssl 的版本，wiki上有要求的

**Comment by jyy1990** [comment]
我也是报错，后来懒得搞了。我现在用vcpkg的方式安装，很顺利

**Comment by wuqi** [comment]
> 我也是报错，后来懒得搞了。我现在用vcpkg的方式安装，很顺利

vcpkg的那个我试了webrtc起不来...

**Comment by xia-chu** [comment]
vcpkg的srtp编译时 应该没enable-openssl

**Comment by yebo-luo** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/85433337/d56ad5fb-7f97-49b9-a192-015d491b4b09)
这个有影响吗，之前安装正常，现在换一台安装就有这个问题了
