### ISSUE TITLE
live.flv 有音频吗？

### ISSUE THREAD

**Issue by cdtaichen521** [ZLMediaKit/ZLMediaKit#3374]
MediaServer从相机拉取带音频的rtsp流，测试输出的rtsp流保持了音频，但是输出的live.flv没有音频，在这个环节的操作需要注意什么？

**Comment by xiongguangjie** [comment]
这个音频是不是不支持？什么格式的，如果rtsp 的directProxy 是1 这种情况是可能会出现的，主要是音频的编码格式可能有问题

**Comment by cdtaichen521** [comment]
今天检查了，MediaServer是有声音输出的。有没有参数可以控制MediaServer在输出音频的时候，将原来的G711A转换成AAC或者其他呢？







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月15日 11:19 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [ZLMediaKit/ZLMediaKit] live.flv 有音频吗？ (Issue #3374) |

这个音频是不是不支持？什么格式的，如果rtsp 的directProxy 是1 这种情况是可能会出现的，主要是音频的编码格式可能有问题

**Comment by xiongguangjie** [comment]
> 今天检查了，MediaServer是有声音输出的。有没有参数可以控制MediaServer在输出音频的时候，将原来的G711A转换成AAC或者其他呢？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2024年3月15日 11:19 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***>, ***@***.***> | | 主题 | Re: [ZLMediaKit/ZLMediaKit] live.flv 有音频吗？ (Issue #3374) | 这个音频是不是不支持？什么格式的，如果rtsp 的directProxy 是1 这种情况是可能会出现的，主要是音频的编码格式可能有问题 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

换播放器吧，这种除非转码（zlm-pro支持，但是要花钱）
