### ISSUE TITLE
wvp的页面webrtc一直是黑的，报错Assertion failed: (!media.empty())

### ISSUE THREAD

**Issue by jyy1990** [ZLMediaKit/ZLMediaKit#3375]
不好意思，这方面是个小白。想请赐教 谢谢

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/35125132/b0fc0a6f-0d77-429b-89ff-0dbf6ebaab94)

我现在不确定是wvp还是zlm哪个有问题，zlm我是用vcpkg装的满血版本，按理应该开了webrtc

**Comment by jyy1990** [comment]
{
	"code" : -400,
	"msg" : "Assertion failed: (!media.empty()), function checkValid, file /home/camera/vcpkg/buildtrees/zlmediakit/src/87569d891b-6048eb5128.clean/webrtc/Sdp.cpp, line 1319."
}

页面F12报这个错

**Comment by jyy1990** [comment]
**ZLM请求日志：**
# request:
POST /index/api/webrtc?app=rtp&stream=34040000002000000003_34040000002000000003&type=play
# header:
Accept : application/json, text/plain, */*
Accept-Encoding : gzip, deflate
Accept-Language : zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection : keep-alive
Content-Length : 105
Content-Type : text/plain;charset=UTF-8
Host : 10.101.59.3:9092
Origin : http://10.101.59.3:8080
Referer : http://10.101.59.3:8080/
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
# content:
v=0
o=- 8321476590358247365 2 IN IP4 127.0.0.1
s=-
t=0 0
a=extmap-allow-mixed
a=msid-semantic: WMS

# response:
{
        "code" : -400,
        "msg" : "Assertion failed: (!media.empty()), function checkValid, file /home/camera/vcpkg/buildtrees/zlmediakit/src/87569d891b-6048eb5128.clean/webrtc/Sdp.cpp, line 1319."
}

**Comment by cwy1996** [comment]
我也是，这边出现
# response:
{
	"code" : -400,
	"msg" : "Assertion failed: (!media.empty()), function checkValid, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 1326.",
	"sdp" : null
}

wvp  上的webrtc界面黑   但是复制对应的rtcs地址，zlm是可以播放的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/76695859/b07b4405-a42b-48bd-8415-6b960acda200)

**Comment by jyy1990** [comment]
> 我也是，这边出现
> 
> # response:
> { "code" : -400, "msg" : "Assertion failed: (!media.empty()), function checkValid, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 1326.", "sdp" : null }
> 
> wvp 上的webrtc界面黑 但是复制对应的rtcs地址，zlm是可以播放的 ![image](https://private-user-images.githubusercontent.com/76695859/313464957-b07b4405-a42b-48bd-8415-6b960acda200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjQ0MDUsIm5iZiI6MTcxMDcyNDEwNSwicGF0aCI6Ii83NjY5NTg1OS8zMTM0NjQ5NTctYjA3YjQ0MDUtYTQyYi00OGJkLTg0MTUtNmI5NjBhY2RhMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAxMDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MGIzMzYyNGVmNWQxOTQwYWExOTEzOGRmZDg5NDA1MzY2YjQ1MTViOWNmYmE3ODJjZjcyYmMzYjgzYzQzODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tfdRemzD4aPUk0rrXQuw6t08aJu2oNvokRSnmex9zPM)

webrtc有2个播放地址，我用zlm都播不了。
http地址点播放后请求直接报错，https地址点播放会卡着一直转圈
![Uploading image.png…]()

**Comment by jyy1990** [comment]
> 我也是，这边出现
> 
> # response:
> { "code" : -400, "msg" : "Assertion failed: (!media.empty()), function checkValid, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 1326.", "sdp" : null }
> 
> wvp 上的webrtc界面黑 但是复制对应的rtcs地址，zlm是可以播放的 ![image](https://private-user-images.githubusercontent.com/76695859/313464957-b07b4405-a42b-48bd-8415-6b960acda200.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjQ4NjksIm5iZiI6MTcxMDcyNDU2OSwicGF0aCI6Ii83NjY5NTg1OS8zMTM0NjQ5NTctYjA3YjQ0MDUtYTQyYi00OGJkLTg0MTUtNmI5NjBhY2RhMjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAxMTYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYzZjNGFjMjAzMDdlYjZkN2YyMGY5NjgwYmU3YTc5MWE2YmI0MjQ2ZWIxN2I5ZjBkYWM0Y2VkMTlkNzI5YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8dRI_PM0Z6QJIRcQQjDh4KDJ8sgsIEdDg-N3DYuzZmg)

webrtc有2个播放地址，我用zlm都播不了。
http地址点播放后请求直接报错，https地址点播放会卡着一直转圈
![56DBEE97-B54B-42B2-BD95-4FED144DC162](https://github.com/ZLMediaKit/ZLMediaKit/assets/35125132/f9bf55ba-04de-4f56-973e-5806490de412)

**Comment by xia-chu** [comment]
vcpkg安装的zlm 没开webrtc能力(或有点问题)，建议你docker安装或者直接源码安装。

@jyy1990 Assertion failed: (!media.empty())这个错误是你的offer sdp中没mline zlm不知道你的浏览器支持哪些编码 所以就无法返回音频和视频

**Comment by cwy1996** [comment]
> vcpkg安装的zlm没开webrtc能力(或者有点问题)，建议你docker安装或者直接源码安装。
> 
> @jyy1990断言失败：（！media.empty（））这个错误是你提供的sdp中没有mline zlm不支持你的浏览器支持哪些编码就无法返回知道音频和视频

请问
{
“code”：-400，
“msg”：“断言失败：（！media.empty（）），函数checkValid，文件/opt/media/ZLMediaKit/webrtc/Sdp.cpp，第1326行。”，
“sdp” ： 无效的
}

这个报错，wvp那边是灰屏报上述错误，但是复制对应的rtcs链接，但是zlm是可以播放的，请问这可能是哪方面的错误呢，

wvp自行编译的docker镜像，zlm用的是镜像版本，时间节点节点的话基本都是20240313这个时间的版本

**Comment by xia-chu** [comment]
wvp的webrtc js播放器可能有点问题

**Comment by xia-chu** [comment]
这个issue可以在wvp项目issue中提一下

**Comment by cwy1996** [comment]
> 这个问题可以在 wvp 项目问题中提一下

谢谢

**Comment by xia-chu** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/733d768a-3512-4353-9add-52c2f906e2c3)

**Comment by cwy1996** [comment]
> 这个issue可以在wvp项目issue中提一下

得到回复，需要将rtcPlayer.vue中的参数改一下，新版的默认false了

![1710750095950](https://github.com/ZLMediaKit/ZLMediaKit/assets/76695859/033d03d8-0e39-478f-adc5-394896128c29)

修改后可以了

**Comment by jyy1990** [comment]
> > 这个issue可以在wvp项目issue中提一下
> 
> 得到回复，需要将rtcPlayer.vue中的参数改一下，新版的默认false了
> 
> ![1710750095950](https://private-user-images.githubusercontent.com/76695859/313599730-033d03d8-0e39-478f-adc5-394896128c29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTA1NzEsIm5iZiI6MTcxMDc1MDI3MSwicGF0aCI6Ii83NjY5NTg1OS8zMTM1OTk3MzAtMDMzZDAzZDgtMGUzOS00NzhmLWFkYzUtMzk0ODk2MTI4YzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4MjQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZmRkMzY2OGE0NmY0YjhjYzk1MTE2YTdiOWE1ZDkzNjQ0MjhjMjNmMDUzNTZiY2Y3NjQxNTQ1M2U3MDUwNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ebcNiBijfhPSijbvBvo6X0rNMB3CShkxp-IZdtKwNJA)
> 
> 修改后可以了

厉害了，我也跟你一样用docker装zlm试试吧，我用的vcpkg看来有问题

**Comment by jyy1990** [comment]
感谢各位大佬

**Comment by xia-chu** [comment]
> > 这个issue可以在wvp项目issue中提一下
> 
> 得到回复，需要将rtcPlayer.vue中的参数改一下，新版的默认false了
> 
> ![1710750095950](https://private-user-images.githubusercontent.com/76695859/313599730-033d03d8-0e39-478f-adc5-394896128c29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTk2MTAsIm5iZiI6MTcxMDgxOTMxMCwicGF0aCI6Ii83NjY5NTg1OS8zMTM1OTk3MzAtMDMzZDAzZDgtMGUzOS00NzhmLWFkYzUtMzk0ODk2MTI4YzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzM5MmViNmZmNTE4ZWUzM2I0NTc2MmI3MTBmZmE3Njc4NmJjYmQ0NWZiMmM0ZDVjYzk3OTRmZDVhMWVjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynr7ScB5WkfwxmHAKa9UaUJyn6GDDeGkdl1tW0PrlD4)
> 
> 修改后可以了

@cwy1996 不给wvp来个pr吗

**Comment by cwy1996** [comment]
> > > 这个issue可以在wvp项目issue中提一下
> > 
> > 
> > 得到回复，需要将rtcPlayer.vue中的参数改一下，新版的默认false了
> > ![1710750095950](https://private-user-images.githubusercontent.com/76695859/313599730-033d03d8-0e39-478f-adc5-394896128c29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTk2MTAsIm5iZiI6MTcxMDgxOTMxMCwicGF0aCI6Ii83NjY5NTg1OS8zMTM1OTk3MzAtMDMzZDAzZDgtMGUzOS00NzhmLWFkYzUtMzk0ODk2MTI4YzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzM5MmViNmZmNTE4ZWUzM2I0NTc2MmI3MTBmZmE3Njc4NmJjYmQ0NWZiMmM0ZDVjYzk3OTRmZDVhMWVjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynr7ScB5WkfwxmHAKa9UaUJyn6GDDeGkdl1tW0PrlD4)
> > 修改后可以了
> 
> @cwy1996 不给wvp来个pr吗
issue 中@了，主要是代码没有修改，只是修改两个参数

**Comment by cwy1996** [comment]
> > > 这个issue可以在wvp项目issue中提一下
> > 
> > 
> > 得到回复，需要将rtcPlayer.vue中的参数改一下，新版的默认false了
> > ![1710750095950](https://private-user-images.githubusercontent.com/76695859/313599730-033d03d8-0e39-478f-adc5-394896128c29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTk2MTAsIm5iZiI6MTcxMDgxOTMxMCwicGF0aCI6Ii83NjY5NTg1OS8zMTM1OTk3MzAtMDMzZDAzZDgtMGUzOS00NzhmLWFkYzUtMzk0ODk2MTI4YzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAzMzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNzM5MmViNmZmNTE4ZWUzM2I0NTc2MmI3MTBmZmE3Njc4NmJjYmQ0NWZiMmM0ZDVjYzk3OTRmZDVhMWVjMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ynr7ScB5WkfwxmHAKa9UaUJyn6GDDeGkdl1tW0PrlD4)
> > 修改后可以了
> 
> @cwy1996 不给wvp来个pr吗

issue 中@了，主要是代码没有修改，只是修改两个参数，再次感谢您的帮助

**Comment by cwy1996** [comment]
wvp上已经合并代码

**Comment by window-li** [comment]
> vcpkg安装的zlm 没开webrtc能力(或有点问题)，建议你docker安装或者直接源码安装。
> 
> @jyy1990 Assertion failed: (!media.empty())这个错误是你的offer sdp中没mline zlm不知道你的浏览器支持哪些编码 所以就无法返回音频和视频
docker 安装的zlmediakit是不是默认也没有开启webrtc能力，如何动态启用webrtc那，还是只能重新编译？或者能不能提供一个默认开启webrtc能力的镜像
