### ISSUE TITLE
[技术咨询] 关于掉线的视频流，ZLM后台一直拉取，是否会影响性能？

### ISSUE THREAD

**Issue by lobster02** [ZLMediaKit/ZLMediaKit#3376]
**咨询的功能模块**
- 咨询如果摄像头视频流突然掉线，这时候ZLM具备重连机制，如果一直没有视频流上线，这时候ZLM重连机制是否会影响性能？

**咨询的具体内容和问题**
作者老哥下午好
- 1.之前测试同时拉取了多个视频流，如果其中一个掉线，ZLM在后台会自动重连，但是播放其他视频流的时候，明显感觉有卡顿。
- 2.另外如果断线的视频流上线以后，ZLM等待1或者2分钟才会重新连接成功，想咨询主动拉取摄像头流比较好，还是等待ZLM自动重连。

**Comment by xia-chu** [comment]
不会 zlm是异步io非阻塞的 重连不阻塞其他线程或本线程的其他fd的收发

**Comment by xia-chu** [comment]
zlm的重连延时时长是根据失败次数决定的 最大等待60s

**Comment by lobster02** [comment]
好的，感谢作者回复，有机会我再复现问题试试。
