### ISSUE TITLE
[技术咨询] wiki中的Restful接口文档更新

### ISSUE THREAD

**Issue by a24211317** [ZLMediaKit/ZLMediaKit#3378]
wiki中的Restful接口个别参数应该有变动#3342 ，请求文档更新。

**Comment by xiongguangjie** [comment]
或者看这个 https://github.com/ZLMediaKit/ZLMediaKit/wiki/postman-%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9A%84restful-api%E6%8E%A5%E5%8F%A3
