### ISSUE TITLE
[BUG] 点播串流

### ISSUE THREAD

**Issue by chenparty** [ZLMediaKit/ZLMediaKit#3379]
### 现象描述

国标点播的时候偶现串流的现象，就是播放A设备的某个通道,视频流播放出来是B设备的某通道。
一开始是让ZLM使用随机的端口来openRtpServer的，但是发现串流后，改成我这边指定递增的端口号来openRtpServer，还是发现会有偶发的串流现象，现象发生概率大概几十分之一。

### 如何复现?

偶现，无法稳定复现。
### 相关日志或截图

暂无
<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:测试过多个版本都有这个问题，包括最新的
* **操作系统及版本**:CentOS7.9
* **硬件信息**:阿里云服务器
* **其他需要补充的信息**:无

**Comment by xia-chu** [comment]
这个不是zlm的bug 这个是你调度的bug 跟zlm无关

**Comment by xia-chu** [comment]
你要确保设备停止推流 否则端口复用了 就可能串流
