### ISSUE TITLE
[技术咨询] 接收国标设备rtp视频转码会消耗多少性能

### ISSUE THREAD

**Issue by wangran99** [ZLMediaKit/ZLMediaKit#3382]
**咨询的功能模块**
- zlm接收1000路国标设备rtp视频到随机端口，大部分时间没人看视频，对性能影有多大影响？

**咨询的具体内容和问题**
-  大部分时间没人看国标视频，但是希望随时能看视频，所以长期推流1000路设备到zlm，担心性能问题，还是说zlm转码性能消耗很少可以忽略不记？视频推流不能断，zlm在接收转码，同时也有另外的录像程序在录制视频。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
你不开hls这种磁盘io消耗的协议 还好了。
主要成本是带宽成本，cpu/内存这些其实还好 没啥压力。
当然 如果你是局域网 那相当于全部几乎免费了

**Comment by wangran99** [comment]
配置文件里有一个无人观看自动关闭设备端口的配置，但是项目需求是端口数据不能停。有没有办法让zlm在无人观看的时候停止hls，有人看的时候自动开始hls转码，尽量少的减少hls转码减少的性能消耗？项目不要求用zlm录像

**Comment by xia-chu** [comment]
hls_demand不就是吗？

**Comment by wangran99** [comment]
> hls_demand不就是吗？

是的。感谢作者的开源。
