### ISSUE TITLE
ZLM占用内存达13G

### ISSUE THREAD

**Issue by Jason5592** [ZLMediaKit/ZLMediaKit#3383]
启动zlm会占用系统内存达13个G，而且启动和停止都会持续3分钟以上。
请问是编译问题还是配置问题呢？

**Comment by Jason5592** [comment]
直接top命令看不到zlm占用那么大的内存，但只要停止zlm的运行，系统会立即释放出达8G的内存资源出来

**Comment by Jason5592** [comment]
![企业微信截图_17107618264408](https://github.com/ZLMediaKit/ZLMediaKit/assets/16130857/90bd5d44-7b20-4637-bb7d-32cce9664682)

**Comment by xia-chu** [comment]
你可以进docker看看top

**Comment by Jason5592** [comment]
![企业微信截图_17108286489791](https://github.com/ZLMediaKit/ZLMediaKit/assets/16130857/0be0fbef-0ed2-445c-bf5f-ba8464b88629)
已通过知识星球加你微信了，没有遇到这种情况麽

**Comment by xia-chu** [comment]
这个问题是映射太多端口导致的 请使用--network=host模式吧

**Comment by Jason5592** [comment]
已解决，感谢夏大
