### ISSUE TITLE
[技术咨询] wmv格式视频的点播功能

### ISSUE THREAD

**Issue by learner-dhx** [ZLMediaKit/ZLMediaKit#3384]
**咨询的功能模块**
- http点播功能模块

**咨询的具体内容和问题**
- 我有很多wmv格式的视频需要进行点播推流，抱歉没能在您项目及文档中找到支持wmv格式视频的点播功能。我当前要人工把这些wmv视频转成 fmp4格式才能进行http点播推流，但是这并不方便，请问您对这种情况有什么好的实施建议吗？或者说最佳实践？详细一点，感谢😊

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
搞个批处理转换吧

**Comment by learner-dhx** [comment]
感谢建议  :–）
