### ISSUE TITLE
[技术咨询] 怎么才能利用ZLMEDIAKIT，对多个RTSP视频流读取并提取帧。

### ISSUE THREAD

**Issue by ijiami-01** [ZLMediaKit/ZLMediaKit#3388]
有没有demo，我这里有多个RTSP视频流，比如通过这个命令，ffmpeg -re -stream_loop -1 -i 'hello.mp4' -c copy -f rtsp rtsp://1.1.1.1:4530/gd1, 开启了一个视频流服务，但我希望用ZLMEDIAKIT来读取这个网络视频流并提取帧，要怎么做呢？

**Comment by xia-chu** [comment]
参考这个demo, 这位仁兄提供了：#3390
