### ISSUE TITLE
前端：求问支持【webrtc协议流h265】zlmediakit服务器的播放器组件推荐？

### ISSUE THREAD

**Issue by eeearthgirl** [ZLMediaKit/ZLMediaKit#3389]
- 前端页面能播放**webrtc协议流h265（zlm服务器）**的播放器组件推荐

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个需要浏览器支持才行（一般浏览器不支持）,h265 建议使用h265web.js 或者 Jessibuca
