### ISSUE TITLE
[BUG] WIN10系统使用C接口的mk_player播放视频，接收数据异常

### ISSUE THREAD

**Issue by 51w** [ZLMediaKit/ZLMediaKit#3390]
### 现象描述

使用mk_player_create，mk_player_set_on_result接口播放RTSP RTMP等链接，
在linux下正常接收数据，windows10系统上接收音视频数据丢帧严重。

    #include <iostream>
    #include "mk_mediakit.h"

    void API_CALL on_track_frame_out(void* user_data, mk_frame frame) 
    {
        static FILE* ff_264 = fopen("video.h264", "w");
        fwrite(mk_frame_get_data(frame), 1, mk_frame_get_data_size(frame), ff_264);
        fflush(ff_264);

        log_info("Video %d %d\n", mk_frame_get_dts(frame), mk_frame_get_pts(frame));
    }

    void API_CALL on_track_audio_out(void* user_data, mk_frame frame) 
    {
        static FILE* ff_aac = fopen("audio.aac", "w");
        fwrite(mk_frame_get_data(frame), 1, mk_frame_get_data_size(frame), ff_aac);
        fflush(ff_aac);

        log_info("Audio %d %d\n", mk_frame_get_dts(frame), mk_frame_get_pts(frame));
    }

    void API_CALL on_mk_play_event_func(void* user_data, int err_code, const char* err_msg, mk_track tracks[], int track_count) 
    {
        if (err_code == 0) {
            //success
            log_debug("play success!");
            int i;
            for (i = 0; i < track_count; ++i) {
                if (mk_track_is_video(tracks[i])) {
                    //监听track数据回调
                    mk_track_add_delegate(tracks[i], on_track_frame_out, user_data);
                }
                else
                {
                    mk_track_add_delegate(tracks[i], on_track_audio_out, user_data);
                }
            }
        }
        else {
            log_warn("play failed: %d %s", err_code, err_msg);
        }
    }

    void API_CALL on_mk_shutdown_func(void* user_data, int err_code, const char* err_msg, mk_track tracks[], int track_count) {
        log_warn("play interrupted: %d %s", err_code, err_msg);
    }

    int main()
    {
        mk_config config;
        config.ini = NULL;
        config.ini_is_path = 0;
        config.log_level = 0;
        config.log_mask = LOG_CONSOLE;
        config.ssl = NULL;
        config.ssl_is_path = 1;
        config.ssl_pwd = NULL;
        config.thread_num = 0;
        mk_env_init(&config);

        int rtmp_port = 1935;
        int rv = mk_rtmp_server_start(rtmp_port, 0);
        if (rv != rtmp_port)
        {
            log_error("mk_rtmp_server_start error.");
            return -1;
        }

        log_info("enter any key to start");
        getchar();

        mk_player player;
        player = mk_player_create();

        mk_player_set_on_result(player, on_mk_play_event_func, NULL);
        mk_player_set_on_shutdown(player, on_mk_shutdown_func, NULL);

        mk_player_play(player, "rtmp://127.0.0.1:1935/live/123456");

        
        mk_sem sem = mk_sem_create();
        mk_sem_wait(sem);

        if (player) {
            mk_player_release(player);
        }

        return 0;
    }

### 如何复现?

1.  编译生成zlm的C接口的动态库，使用VCPKG下载，或者CMAKE编译源码；
2.  使用上面代码作为测试程序服务端；
3.  抓取桌面推流 .\ffmpeg.exe -f gdigrab -framerate 30 -offset_x 0 -offset_y 0  -video_size 640x480 -i desktop  -vcodec h264 -f flv rtmp://127.0.0.1:1935/live/123456；
4.  测试程序服务端cmd界面输入字符；
5.  等待数秒后退出程序，播放测试程序生成的video.h264；
6.  video.h264 绿屏
![企业微信截图_20240319193309](https://github.com/ZLMediaKit/ZLMediaKit/assets/44690168/e79cedc5-85e1-4566-98e0-bea56c376c53)

7.  mk_play在linux系统正常接收数据。

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **mk动态库使用的版本 git checkout 7.0 或者main主分支**:
* **操作系统Windows10专业版**:

**Comment by xia-chu** [comment]
按道理 linux和Windows不应该出现差异性

**Comment by 51w** [comment]
> 按道理 linux和Windows不应该出现差异性

参考ZLMediaKit/player/test_player.cpp的C++接口，结果还是windows平台有问题；使用VCPKG下载库和自己编译的库现象一样。

这是使用VCPKG下载的库配的工程  [mk_player.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14681304/mk_player.zip)
VS工程生成的可执行程序  [Release.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14681400/Release.zip)

**Comment by xia-chu** [comment]
我主要是没Windows开发环境 H264存档的文件发我看下？

**Comment by 51w** [comment]
> 我主要是没Windows开发环境 H264存档的文件发我看下？

video.h264是有问题的文件，www目录有录制的m3u8正常的视频文件。 [Release.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14695376/Release.zip)

**Comment by 51w** [comment]
fopen读取模式w改为wb，问题解决。
