### ISSUE TITLE
[技术咨询] .live.mp4的流chome、安卓微信都能打开，但苹果微信无法播放，请问如何解决

### ISSUE THREAD

**Issue by bnuzhouwei** [ZLMediaKit/ZLMediaKit#3391]

**Comment by xiongguangjie** [comment]
这个要苹果的浏览器内核好像是苹果的，这个需要去看相关的兼容性

**Comment by xia-chu** [comment]
苹果ios浏览器默认不支持mse 跟这个有关？
苹果可以用hls-fmp4直播

**Comment by yduis6554** [comment]
https://github.com/ErosZy/WXInlinePlayer  
用这个播放器可以播放 flv， 同时也支持 CodeID=12  的flv播放.
DEMO地址：  https://eroszy.github.io/WXInlinePlayer/example/index.html
