### ISSUE TITLE
ZLMRTCClient.js

### ISSUE THREAD

**Issue by cuijianwei** [ZLMediaKit/ZLMediaKit#3396]
### 现象描述
Chrome 123.0.6312.59  下无法通过ZLMRTCClient.js 播放webrtc视频。

报错内容：
event.js:9 [RTCPusherPlayer] DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription.  Duplicate a=msid lines detected
    at RTCPeerConnection.setRemoteDescription (http://192.100.100.38/ZLMRTCClient.js:5194:40)
    at http://192.100.100.38/ZLMRTCClient.js:7907:20
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/1401149/9cc4a35e-2c5a-4e3c-a283-b119288bdb32)

### 如何复现?
使用自带的webrtc路径播放，
请求内容
`http://192.100.100.38/index/api/webrtc?app=live&stream=test1&type=play`

响应内容：
`{
    "code": 0,
    "id": "zlm_40",
    "sdp": "v=0\r\no=- 2909727614615201951 2 IN IP4 192.100.100.38\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\na=ice-lite\r\nm=video 0 UDP/TLS/RTP/SAVPF 112 113\r\nc=IN IP4 192.100.100.38\r\na=ice-ufrag:zlm_40\r\na=ice-pwd:KbKnUNoW3tqvu5BJ2IhTQQDu\r\na=ice-options:trickle\r\na=fingerprint:sha-256 0C:82:1D:C1:82:EC:B2:BB:38:E5:13:17:BA:4A:67:35:7E:D3:73:A9:86:34:36:6F:0D:B0:5D:AC:42:1F:60:FA\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=extmap:1 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=rtcp-mux\r\na=rtpmap:112 H264/90000\r\na=rtcp-fb:112 ccm fir\r\na=rtcp-fb:112 goog-remb\r\na=rtcp-fb:112 nack\r\na=rtcp-fb:112 nack pli\r\na=rtcp-fb:112 transport-cc\r\na=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=64001f\r\na=rtpmap:113 rtx/90000\r\na=fmtp:113 apt=112\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 cname:zlmediakit-rtp\r\na=ssrc:1 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:1 mslabel:zlmediakit-mslabel\r\na=ssrc:1 label:zlmediakit-label\r\na=ssrc:3 cname:zlmediakit-rtp\r\na=ssrc:3 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:3 mslabel:zlmediakit-mslabel\r\na=ssrc:3 label:zlmediakit-label\r\na=ssrc-group:FID 1 3\r\nm=audio 0 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 192.100.100.38\r\na=ice-ufrag:zlm_40\r\na=ice-pwd:KbKnUNoW3tqvu5BJ2IhTQQDu\r\na=ice-options:trickle\r\na=fingerprint:sha-256 0C:82:1D:C1:82:EC:B2:BB:38:E5:13:17:BA:4A:67:35:7E:D3:73:A9:86:34:36:6F:0D:B0:5D:AC:42:1F:60:FA\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=extmap:14 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=inactive\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 cname:zlmediakit-rtp\r\na=ssrc:2 msid:zlmediakit-mslabel zlmediakit-label\r\na=ssrc:2 mslabel:zlmediakit-mslabel\r\na=ssrc:2 label:zlmediakit-label\r\n",
    "type": "answer"
}`

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这个bug已经修复了，看这个issue 1e3959433522808f3390bc9748ae96af793906dc

**Comment by meyanchan** [comment]
大佬太及时啦
