### ISSUE TITLE
关于拉流代理新增时，拉流地址使用https协议的url

### ISSUE THREAD

**Issue by 417609651** [ZLMediaKit/ZLMediaKit#3403]
**咨询的功能模块**
- 拉流代理模块

**咨询的具体内容和问题**
- 在新增拉流代理的时候，拉流地址是https协议的url就会报错
- 
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/164440790/0b8fbec4-a3c7-476e-aecf-b25a2cc7a6eb)

**Comment by xiongguangjie** [comment]
ZLM报啥错误，是流有问题吧？？？

**Comment by 417609651** [comment]
目前已经解决啦，问题是在部署ZLM的时候忘记配置openssl了
