### ISSUE TITLE
[BUG] zlm拉流的时候用的端口和tcp握手的端口不是同一个端口

### ISSUE THREAD

**Issue by huzhiqin888** [ZLMediaKit/ZLMediaKit#3404]
![a929cecb32432b26323f85597bc55e9](https://github.com/ZLMediaKit/ZLMediaKit/assets/58691014/5b138365-976e-4d5f-9b48-2b176b305cc8)
zlm拉流的时候用的端口和tcp握手的端口不是同一个端口。sip包里面的端口是31966，但是tcp握手的端口是9273。这个影响到了视频的拉取。这个是bug吗，还是有配置可以更改

**Comment by wosledon** [comment]
![企业微信截图_17112778329333](https://github.com/ZLMediaKit/ZLMediaKit/assets/49866401/9e7bb618-95d3-42d5-b7cd-d0dadf8b2c2a)

你好，我在开发的时候遇到了一个问题，容器化部署以后，分配rtp的时候，ip参数上使用的容器内的ip，端口则是50889，我在配置时没有分配该段内的端口，导致推流一直存在问题，另外一个问题是容器内http的监听ip，在Host模式下，容器内无法使用宿主机ip访问api，但是可以使用localhost访问。。
![企业微信截图_17112802949369](https://github.com/ZLMediaKit/ZLMediaKit/assets/49866401/dcfbc319-7339-420d-a594-7e2545b766e4)
