### ISSUE TITLE
[技术咨询] iOS手机应用接入Demo代码参考(必填)

### ISSUE THREAD

**Issue by WS-Vincent** [ZLMediaKit/ZLMediaKit#3405]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- RTSP手机拉流

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
我如何想在iOS手机客户端集成一个仅仅支持RTSP拉流的播放客户端，可以参考哪些文件写Demo接入测试

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
请使用c sdk吧 参考这个demo: api/tests/player_opencv.c
