### ISSUE TITLE
使用 “webrtc推流/播放” 时，请问怎么在这个过程中，发送消息

### ISSUE THREAD

**Issue by meferi-hub** [ZLMediaKit/ZLMediaKit#3417]
**咨询的功能模块**
- webrtc推流/播放

**咨询的具体内容和问题**
- 有一个场景，在使用 “webrtc推流/播放” 时，在这个过程中，推流端与接收端，需要相互发送消息（类似于聊天），我在 [“webrtc信令交互格式“](https://github.com/ZLMediaKit/ZLMediaKit/wiki/webrtc%E4%BF%A1%E4%BB%A4%E4%BA%A4%E4%BA%92%E6%A0%BC%E5%BC%8F)
看到有类似的说明，但是不知道怎么用，或者是不是这个文档。请问有相关的文档吗？感谢
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
通过webrtc的datachannel,zlm 提供了broadcast 的类似接口

**Comment by xiongguangjie** [comment]
你可以使用im系统来做

**Comment by xia-chu** [comment]
/index/api/broadcastMessage接口
