### ISSUE TITLE
[功能请求] 在web端远程控制移动设备（安卓设备）

### ISSUE THREAD

**Issue by meferi-hub** [ZLMediaKit/ZLMediaKit#3418]
**描述该功能的用处，可以提供相关资料描述该功能**
在web端远程控制移动设备

 

**描述你期望实现该功能的方式和最终效果**
我们有一个场景，用户通过web页面，来远程控制移动设备（类似于向日葵远程控制）。
我们计划这样实现：
移动端捕获手机屏幕，并使用ZLMediaKit  webrtc以流的形式推送给web端，web端使用webrtc播放视频流。控制端向被控端使用类似信令的东西发送消息（点击、长按等指令），进行控制。
请问我上述这种场景我们的ZLMediaKit支持吗，或者有没有其他的建议。期待您的回复

**Comment by meferi-hub** [comment]
> zlm支持rtc传输流，至于如何发送控制信令，需要你们自己开发，或者借用broadcastMessage 接口来开发

您好，方便发一下 broadcastMessage  相关的文档吗

**Comment by xiongguangjie** [comment]
> > zlm支持rtc传输流，至于如何发送控制信令，需要你们自己开发，或者借用broadcastMessage 接口来开发
> 
> 您好，方便发一下 broadcastMessage 相关的文档吗

看postman 的接口，但是不建议这么高，这个是通过datachannel 来实现的

**Comment by meferi-hub** [comment]
> > > zlm支持rtc传输流，至于如何发送控制信令，需要你们自己开发，或者借用broadcastMessage 接口来开发
> > 
> > 
> > 您好，方便发一下 broadcastMessage 相关的文档吗
> 
> 看postman 的接口，但是不建议这么高，这个是通过datachannel 来实现的

我也觉得可以使用 datachannel ，但是没有找到相关的 api,请问你知道吗  [我已经提问了](https://github.com/ZLMediaKit/ZLMediaKit/issues/3420)

**Comment by xia-chu** [comment]
/index/api/broadcastMessage
