### ISSUE TITLE
[技术咨询] webrtc 接收消息

### ISSUE THREAD

**Issue by meferi-hub** [ZLMediaKit/ZLMediaKit#3420]
**咨询的功能模块**
- 使用webrtc，开启了推流、与接收（如下图），当打开在页面“datachannel”开关时，发生 消息（接收端向推流端发送），为什么在接收端收不到，是我操作不对吗？期待你得回复

![微信截图_20240328142937](https://github.com/ZLMediaKit/ZLMediaKit/assets/162565894/e88074a5-97ce-4879-90ac-3df3fc99514b)

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
需要调用/index/api/broadcastMessage 这个接口，详情看postman

**Comment by battleingame** [comment]
chrome升级后无法接受到消息 Firefox可以

**Comment by shanmengjie** [comment]
> chrome升级后无法接受到消息 Firefox可以

你好，我好像也碰到了这种问题，是chrome无法接受到服务端的SDP answer吗？

**Comment by xiongguangjie** [comment]
最新的ZLM我试了下是可以的 可以收到datachannel 的数据

**Comment by battleingame** [comment]
> > chrome升级后无法接受到消息 Firefox可以
> 
> 你好，我好像也碰到了这种问题，是chrome无法接受到服务端的SDP answer吗？
感谢，最新的ZLM解决了
