### ISSUE TITLE
[技术咨询] on_play回调事件透传cookie

### ISSUE THREAD

**Issue by sincebyte** [ZLMediaKit/ZLMediaKit#3422]
**咨询的功能模块**
zlm的回调真的太好用了，现在实现on_play时回调鉴权，但是我们的鉴权token存放在cookie里面。
目前可以通过on_play的param参数传递token，但这样的话每个播放协议都需要改造非常麻烦。
期望on_play回调事件能透传流媒体服务器接收到的cookie。
透传cookie也符合HTTP规范，相信这个功能可以简化流媒体服务鉴权的实现。

**Comment by xia-chu** [comment]
on_play是个抽象的hook 把一些协议的差异性屏蔽掉了 所以cookie也传递不过来
