### ISSUE TITLE
摄像头录像rtsp的流通过zlm拉流代理后，原rtsp路径中的时间参数未生效

### ISSUE THREAD

**Issue by qilaohan** [ZLMediaKit/ZLMediaKit#3425]
**咨询的功能模块**
- 调用zlm的拉流代理接口 生成flv的拉流地址

**咨询的具体内容和问题**
- 调用zlm的拉流代理接口/index/api/addStreamProxy
- 传入rtsp流地址：rtsp://admin:123456@172.16.5.229:554/C1010/DVideoAndAudio/S0/B1711676176/E1711676776/replay/remote/  ，其中 “B1711676176/E1711676776”为录像的开始、结束时间条件，用VLC测试此地址播放正常且为此时间范围内的录像
- 生成代理流地址：http://10.10.4.103/live/test2.live.flv  ，用VLC或播放器播放，可以看到录像画面，但是时间范围未生效，出现的画面和播放“rtsp://admin:123456@172.16.5.229:554/C1010/DVideoAndAudio/S0/B0/E0/replay/remote/”（不传时间）时的画面一样（录像机最早开始录像的画面），我想咨询下ZLM在代理如上的rtsp流时，会处理源url吗，我通过日志看不出来什么，摄像机和录像机品牌都是宇视，之前测试过海康的是可以（时间范围在?后面的参数，非url路径）
- 日志如下：
[日志.log](https://github.com/ZLMediaKit/ZLMediaKit/files/14798753/default.log)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个要抓包对比才能兼容，手上没有宇视的nvr 这个不好搞

**Comment by fuzhenwen201** [comment]
这里是zlm拉流代理的抓包和直接vcl播放的抓包，麻烦帮忙看下
[pcap包.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14942082/pcap.zip)

**Comment by xia-chu** [comment]
之前更新应该修复这个问题了 建议更新zlm代码测试再反馈
