### ISSUE TITLE
webrtc 播放初始化很久

### ISSUE THREAD

**Issue by yh4922** [ZLMediaKit/ZLMediaKit#3427]
流通过 `/index/api/addStreamProxy` 接口添加拉流

通过前端页面播放是 初始化需要 3~5s  初始化完成后 播放延迟是正常的很低

同一个原始的 rtsp 我用 `Monibuca` 转webrtc 播放 初始化很快 基本可以秒开

视频：左:ZLMediaKit        右:Monibuca
https://github.com/ZLMediaKit/ZLMediaKit/assets/18353610/4b75f6c0-a430-481d-831c-bf0dee4f2aad

有什么地方可以优化么

**Comment by yh4922** [comment]
配置用的是 默认配置 未做修改

**Comment by xia-chu** [comment]
应该是等待track就绪或者等待添加track导致的。

**Comment by yh4922** [comment]
如果是这个原因的话 应该其他的一会慢才对呀
我用另一个流媒体服务就很快连接上

**Comment by xia-chu** [comment]
> 如果是这个原因的话 应该其他的一会慢才对呀 我用另一个流媒体服务就很快连接上

其他的流媒体服务器没这么多转协议 很多细节不用考虑的
