### ISSUE TITLE
index/api/addStreamProxy接口中的url中RTSP的密码中还有+无法解析

### ISSUE THREAD

**Issue by zjzcn1** [ZLMediaKit/ZLMediaKit#3428]
curl --location --request POST 'http://127.0.0.1:8080/index/api/addStreamProxy?vhost=__defaultVhost__&app=proxy&stream=C101&url=rtsp://admin:Szc12345+@ip&rtp_type=tcp&secret=E9TjkgjHTvfl0N7SYtPNtG9L6igEFHn2' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)'

Szc12345+
addStreamProxy接口中的url中RTSP的密码中还有+无法解析，密码中是有+号的，但是解析结果没有+号

<img width="1138" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/43628956/0f4b33d3-0a9e-4ab5-b1a8-baf8ca6275e8">

**Comment by xia-chu** [comment]
如果你不会用curl 麻烦你用postman
