### ISSUE TITLE
HLS 拉流是否支持CDN

### ISSUE THREAD

**Issue by eonie** [ZLMediaKit/ZLMediaKit#3430]
**咨询的功能模块**
HLS 拉流
**咨询的具体内容和问题**
我们在使用的过程中发现CDN 命中率较低，播放时基本CDN 流量和回源流量各占一半，请问是否有功能可以在用户播放前通知CDN提前拉取 ts 文件？

**Comment by xiongguangjie** [comment]
？？？？？ 这个是cdn的问题吧，与ZLM有啥关系？？？

**Comment by eonie** [comment]
是这样的，用户请求的时候CDN还没有缓存ts文件，所以大部分的请求都触发了CDN的回源，可以理解为缓存穿透，SRS那边有个机制是当 ts 文件生成之后可以触发一个回调，在用户请求之前从CDN拉取 ts 文件，这样可以显著的提高CDN的命中率。
所以想问一下这边是否有同样的机制。

**Comment by xiongguangjie** [comment]
> 是这样的，用户请求的时候CDN还没有缓存ts文件，所以大部分的请求都触发了CDN的回源，可以理解为缓存穿透，SRS那边有个机制是当 ts 文件生成之后可以触发一个回调，在用户请求之前从CDN拉取 ts 文件，这样可以显著的提高CDN的命中率。 所以想问一下这边是否有同样的机制。

有的，看hook on_record_ts
