### ISSUE TITLE
[技术咨询] 请问如何关闭录制功能

### ISSUE THREAD

**Issue by luhengyu1** [ZLMediaKit/ZLMediaKit#3437]
**咨询的功能模块**
录制功能

**咨询的具体内容和问题**
请问如何关闭录制功能，我把配置文件的enable_mp4设置为0，好像还是一直在录制视频

**Comment by xiongguangjie** [comment]
hook的返回也要注意, 配置文件配置为不录制，录制接口不要调用

**Comment by xia-chu** [comment]
> hook的返回也要注意, 配置文件配置为不录制，录制接口不要调用

on_publish hook可以返回
```json
{
    "code" : 0,
    "enable_mp4": true
}
```
开启mp4录制，配置文件优先级最低。
