### ISSUE TITLE
[技术咨询] 如何实现拉取h264+rtsp 流，然后转发出去时，是通过rtp+GB28181封装的？

### ISSUE THREAD

**Issue by stayhomesu** [ZLMediaKit/ZLMediaKit#3438]
**咨询的功能模块**
zlmediakit的index/api/startSendRtp

**咨询的具体内容和问题**
我想咨询zlmediakit能否把rtsp流，提取里面的h264 再用国标28181通过PS 封装，发送到指定的目标。

我看到index/api/startSendRtp 接口的描述，是支持RTSP转发PS-RTP流的。

我的测试命令是：
拉取本地RTSP (是直接传的H264的流，未经过PS封装)：http://192.200.1.62/index/api/addStreamProxy?secret=ZhP9QVpdoHkcz63ulpwJHVz6sQ54piRT&vhost=__defaultVhost__&app=proxy&stream=test&url=rtsp://127.0.0.1:8554/stream

然后推流到远端：http://192.200.1.62/index/api/startSendRtp?secret=ZhP9QVpdoHkcz63ulpwJHVz6sQ54piRT&vhost=__defaultVhost__&app=proxy&stream=test&dst_url=我的目标ip&dst_port=15063&is_udp=1&src_port=9078&ssrc=52430

最后，我通过抓包，RTP负载部分，并不是PS格式的。感觉是直接rtsp转rtp，并没有重新进行PS封装后，再转rtp.
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/165801516/5d8d64fc-2826-46a6-96a8-a011aa852a4b)

我是哪里错了吗？还是我对这个接口理解错了？有没有办法实现我的需求？

**Comment by xiongguangjie** [comment]
这个是ps封装的rtp呀，有啥问题？？？？？？你的使用是正确的

**Comment by stayhomesu** [comment]
PS 封装，RTP的负载开头不是应该是00 00 01 ba吗？但我现在是78 开头。所以不是PS封装。

**Comment by xia-chu** [comment]
最近zlm修复了一个小bug，就是没指定 `use_ps=1`时 推的流是es流的问题。

你更新zlm，或者添加`use_ps=1`参数 就会推ps流了。

现在use_ps这个参数过期了，请使用type这个参数，支持 0(es) 1(ps) 2(ts)
