### ISSUE TITLE
请问 平台2000路摄像头大概需要什么配置

### ISSUE THREAD

**Issue by xufan-cmd** [ZLMediaKit/ZLMediaKit#3439]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 请问 平台2000路摄像头大概需要什么配置

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
一台4核的主机就够了 zlm不会是系统的性能瓶颈
相关性能参数，请查看wiki
