### ISSUE TITLE
[技术咨询]  Android 编译开启webrtc 编译失败

### ISSUE THREAD

**Issue by biqi12321** [ZLMediaKit/ZLMediaKit#3443]
Android 编译开启webrtc 编译失败

视频传输延时过高，计划控制在1s以内，不知道能不能实现
 
windows 下编译  idea   是配置不对吗？
Visual Studio 下编译是通过的
开启
 arguments(
                    "-DENABLE_API=on",
                    "-DENABLE_WEBRTC=on",
                    "-DENABLE_API_STATIC_LIB=on",
                    "-DENABLE_TESTS=off",
                    "-DENABLE_PLAYER=off",
                    "-DENABLE_SERVER_LIB=on"
                )
配置：
#定义openssl位置  报错
set(OPENSSL_ROOT_DIR D:/Development/OpenSSL-Win64)
set(OPENSSL_INCLUDE_DIR D:/Development/OpenSSL-Win64/include)
set(OPENSSL_CRYPTO_LIBRARY D:/Development/OpenSSL-Win64/lib)
#定义openssl位置 报错
set(SRTP_INCLUDE_DIRS D:/Development/libsrtp/libsrtp-2.6.0/include)
set(SRTP_LIBRARIES D:/Development/libsrtp/libsrtp-2.6.0/lib/)

[CXX1429] error when building with cmake using F:\DevelopmentProject\Android\TestDemo\DemoAll\zlmediakitlib\src\main\cpp\CMakeLists.txt: -- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Development/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Development/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 编译类型: Debug
-- Git version is  / 2024-04-07T11:54:16
-- found library: OPENSSL_SSL_LIBRARY-NOTFOUND;D:/Development/OpenSSL-Win64/lib, ENABLE_OPENSSL defined
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION
-- Performing Test HAVE_MYSQL_OPT_EMBEDDED_CONNECTION - Failed
-- MySQL not found.
-- ENABLE_MP4 defined
-- ENABLE_RTPPROXY defined
-- ENABLE_HLS defined
-- Performing Test HAVE_MMSG_HDR
-- Performing Test HAVE_MMSG_HDR - Success
-- Looking for sendmmsg
-- Looking for sendmmsg - found
-- Looking for recvmmsg
-- Looking for recvmmsg - found
-- Socket default buffer size is set to 262144
-- set_file_group F:/DevelopmentProject/Android/TestDemo/3rdpart/ZLToolKit/src 78
-- set_file_group F:/DevelopmentProject/Android/TestDemo/src 205
-- srt 功能已开启
-- found library: D:/Development/libsrtp/libsrtp-2.6.0/lib/
-- SCTP LIBRARIES: SCTP_LIBRARIES-NOTFOUND
-- SCTP INCLUDE DIRS: SCTP_INCLUDE_DIRS-NOTFOUND
-- WebRTC 功能已开启
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done

**Comment by xiongguangjie** [comment]
这个zlm现在rtc 不支持作为客户端，只支持作为服务器端

**Comment by sheng930920** [comment]
可以参考这个来处理 [https://github.com/ZLMediaKit/ZLMediaKit/issues/3351](url)

**Comment by biqi12321** [comment]
@sheng930920  这个地址打不开
实在没搞明白这个环境咋配置。写系统变量不认，指定也不知道该咋写。
rtsp 传输，除了延时高，其他很稳定。谢谢
基本功能是实现了。
正研究 api

**Comment by sheng930920** [comment]
地址在这里， 是可以正常打开的。[https://github.com/ZLMediaKit/ZLMediaKit/issues/3351](https://github.com/ZLMediaKit/ZLMediaKit/issues/3351)

**Comment by biqi12321** [comment]
ok，我看看，谢谢

**Comment by biqi12321** [comment]
@sheng930920    用你发的 编译好的ok了
需要用 armeabi-v7a 位  CMakeLists.txt  里添加了 add_compile_options(-fPIC)
我自己编译 openssl 可以，libsrtp   编译不过去。也用你写的sh 文件。
ndk里找不到这些，不过我降ndk 版本也找不到 ，不过满足需求了谢谢。
checking for aarch64-linux-android-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for aarch64-linux-android-g++... no
checking for aarch64-linux-android-c++... no
checking for aarch64-linux-android-gpp... no
checking for aarch64-linux-android-aCC... no
checking for aarch64-linux-android-CC... no
checking for aarch64-linux-android-cxx... no
checking for aarch64-linux-android-cc++... no
checking for aarch64-linux-android-cl.exe... no
checking for aarch64-linux-android-FCC... no
checking for aarch64-linux-android-KCC... no
checking for aarch64-linux-android-RCC... no
checking for aarch64-linux-android-xlC_r... no
checking for aarch64-linux-android-xlC... no
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for aarch64-linux-android-ar... no
checking for aarch64-linux-android-lib... no
checking for aarch64-linux-android-link... no
....
configure: error: can't find openssl >= 1.1.0 crypto lib

**Comment by sheng930920** [comment]
看了一下贴出来的编译日志， 可以把编译脚本修改如下测试看下

```sh
#!/bin/bash

source ./build-android-env.sh

ARCHIVE=libsrtp-2.6.0.tar.gz

DIR=libsrtp-2.6.0

INSTALL_DIR=$BUILD_DIR/libsrtp

OPENSSL_DIR=$BUILD_DIR/openssl

if [ -d $INSTALL_DIR ]; then
    rm -rf $INSTALL_DIR
fi

mkdir -p $INSTALL_DIR

if [ -d $DIR ];then
    rm -rf $DIR
fi

tar xzf $ARCHIVE

cd $DIR

function build() {
    TARGET_HOST=$1
    ANDROID_ARCH=$2
    OPENSSL_ARCH=$3
    export AR=$TOOLCHAIN/bin/llvm-ar
    export CC=$TOOLCHAIN/bin/$TARGET_HOST$MIN_SDK_VERSION-clang
    export AS=$CC
    export CXX=$TOOLCHAIN/bin/$TARGET_HOST$MIN_SDK_VERSION-clang++
    export LD=$TOOLCHAIN/bin/ld
    export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
    export STRIP=$TOOLCHAIN/bin/llvm-strip

    ./configure --host=${TARGET_HOST} \
    --prefix=$INSTALL_DIR/$ANDROID_ARCH \
    --enable-openssl  \
    --with-openssl-dir=$OPENSSL_DIR/$ANDROID_ARCH \

    make clean
    make && make install
}

build aarch64-linux-android arm64-v8a android-arm64
build armv7a-linux-androideabi armeabi-v7a android-arm
build i686-linux-android x86 android-x86
build x86_64-linux-android x86_64 android-x86_64


cd ..

rm -rf $DIR
```

**Comment by biqi12321** [comment]
@sheng930920   嗯这个发完就解决了
但出两个奇怪的问题 armeabi-v7a  又并不能 编译了 奇了个怪的

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'OPENSSL_armcap_P'; recompile with -fPIC

重新编译了openssl1.1.1，啥错都没有 也不要去添加 add_compile_options(-fPIC)。
测试机器：rk328，虚拟机  x86_64,  小米手机 
还是该听wiki的。
当时怎么就3.2.1 编译过去的! _ !    
感谢作者 xia-chu  还有@sheng930920 的帮助
问题结束！
[build1.1.1.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14975273/build1.1.1.zip)

**Comment by sheng930920** [comment]
相同的编译脚本， 本地测试去编译openssl 3.2.1、libsrtp 2.6.0 版本都可以正常编译， 如果编译异常， 一般都可以根据编译日志来排查解决

**Comment by biqi12321** [comment]
> 相同的编译脚本， 本地测试去编译openssl 3.2.1、libsrtp 2.6.0 版本都可以正常编译， 如果编译异常， 一般都可以根据编译日志来排查解决

乌班图上都能编译openssl 3.2.1、libsrtp 2.6.0 过去，放到Android项目里生成  libzlmediakitlib.so 时报错 ,错误就让你去 recompile with -fPIC， 如果openssl 用的3.2.1 Android项目我这只能生成arm64-v8a，x86_64
