### ISSUE TITLE
[技术咨询] MediaServer支持的HTTP API中的loadMP4File无法实现点播，请帮忙看下是什么原因？

### ISSUE THREAD

**Issue by xingkong777888** [ZLMediaKit/ZLMediaKit#3447]
![loadmp4file](https://github.com/ZLMediaKit/ZLMediaKit/assets/166283905/b6bd3faa-28e0-42c8-b477-0ad017a3dc12)
![不能播放的流](https://github.com/ZLMediaKit/ZLMediaKit/assets/166283905/b00beade-1c60-4c7c-bebd-db59fac4414c)

![vlc上无法播放流](https://github.com/ZLMediaKit/ZLMediaKit/assets/166283905/6eba2e9f-8416-48d3-8200-210e6ad88845)

生成的流里的__defaultVhost__ 是不是需要在哪里配置下？
ts://__defaultVhost__/live/test1

**Comment by xiongguangjie** [comment]
url不正确，去看wiki的url
