### ISSUE TITLE
[技术咨询] 国标取流的时候报错“上层分包逻辑异常”

### ISSUE THREAD

**Issue by GuBuChang** [ZLMediaKit/ZLMediaKit#3448]
**咨询的功能模块**
国标取流模块

**咨询的具体内容和问题**
使用国标协议从平台取流，报错上层分包逻辑异常，分析了报错描述和源码，未确定问题方案，请问可以从哪些方向排查这个问题？
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/73569810/e45bb858-2cb6-4de4-a5c7-307fc3fbb850)

**Comment by xiongguangjie** [comment]
对方平台的bug ,tcp缓存溢出导致的，使用udp

**Comment by GuBuChang** [comment]
RtpSession.cpp:63 onError | 94-1183(192.168.2.106:9896) 34020000001310000027 2(receive rtp timeout)
receive rtp timeout 能否设置revice rtp timeout的值

**Comment by xiongguangjie** [comment]
> RtpSession.cpp:63 onError | 94-1183(192.168.2.106:9896) 34020000001310000027 2(receive rtp timeout) receive rtp timeout 能否设置revice rtp timeout的值

看 rtp_proxy.timeoutSec
