### ISSUE TITLE
我想要在视频通话的时候切换摄像头，目前用的replaceTrack这个方法，但是不知道原始要替换的对象是什么

### ISSUE THREAD

**Issue by liyaomin** [ZLMediaKit/ZLMediaKit#3449]
const changestream = (): any => {
    let constraints = {
      audio: true,
      video: {
        deviceId:
          "e7a267551a98d3243fda46dd2bdd1a1735a282e281a94f7cc3cd631d6fc0ea32",
      },
    };
    window.navigator.mediaDevices
      .getUserMedia(constraints)
      .then(async (stream): Promise<any> => {
        console.log(stream);
        let local: any = document.getElementById("selfVideo");
        local.srcObject = stream;
        console.log(stream.getVideoTracks())
        // @ts-ignore
        mediaStream.replaceTrack(stream.getVideoTracks()[0]);
      }).catch((err) => {
        console.error(`Error happened: ${err}`);
      });
  };

**Comment by xiongguangjie** [comment]
这几个参考 https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/replaceTrack

**Comment by xiongguangjie** [comment]
> 不知道在zlm里面RTCPeerConnection实例对象表示的是什么

看相应播放器的源码，你自己理解下就行了

**Comment by liyaomin** [comment]
解决了
