### ISSUE TITLE
[BUG] Docker版本改动config.ini rootPath 改为其他配置，swagger 无法使用

### ISSUE THREAD

**Issue by CxistHans** [ZLMediaKit/ZLMediaKit#3454]
### 现象描述

在尝试调整config.ini 配置的时候，调整了 rootPath 为 ./data 后启动，  在线swagger无法使用
另外发现 默认还是生成相关的 www 目录及相关内容，www目录内的内容并没有到 rootPath 定义的data 中去

### 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/52312956/64032090-dcf4-4786-81ce-e361ce08c144)

</pre>
</details>

### 配置

```ini
[api]
defaultSnap=./www/logo.png
downloadRoot=./data
snapRoot=./data/snap/

[http]
rootPath=./data
virtualPath=web,./www;data,./data

[protocol]
hls_save_path=./data
mp4_save_path=./data
```

### 各种环境信息

* **操作系统及版本**:
docker 运行:
2024-04-05T14:13:43 版本: edca662
* **其他需要补充的信息**:
主要是想确认下目录相关的配置能不能进行调整，调整之后怎么让关联服务正常使用？
有没有相关的最佳实践的config.ini 配置？

**Comment by xia-chu** [comment]
你是说virtualPath不生效吗？

**Comment by CxistHans** [comment]
> 你是说virtualPath不生效吗？

virtualPath 生效了，我能进入目录去看到问题。 应该说是 rootPath 没有生效。
默认还是生成相关的 www 目录及相关内容，www目录内的内容并没有到 rootPath 定义的data 中去

**Comment by xia-chu** [comment]
所以你认为 设置http根目录了 zlm要把原来根目录的文件copy到新目录吗？

**Comment by CxistHans** [comment]
可以嘛？是这个原因？
只要保证改了之后，我能正常的使用swagger和 webassist 等开放服务。
据我所知这个好像还影响点播（从配置说明中看到，具体没有测试）
个人是希望挂载一个data目录，所有内容写入到data中，而不是挂载www目录。

**Comment by CxistHans** [comment]
@xia-chu 您好，请问后续如何了？是我配置问题？

**Comment by xia-chu** [comment]
不可以 这种需求时不合理的 修改配置文件 不应该像脚本一样 让zlm去copy文件夹

**Comment by CxistHans** [comment]
不让改，还让出现在配置中，感觉就是bug呀。。改了就应该兼容的，不一定说是copy文件夹，初始化的时候就得根据rootPath 来 @xia-chu
