### ISSUE TITLE
[技术咨询] 使用/index/api/stopRecord接口停止录制后还在继续录制

### ISSUE THREAD

**Issue by 1422595412** [ZLMediaKit/ZLMediaKit#3455]
**咨询的功能模块**
- 视频录制

**咨询的具体内容和问题**
- 正在录制中的流，调用停止录制流接口后，视频并没有停止，还在继续录制，调用查看录制状态接口显示还在录制中是什么原因？

**Comment by 1422595412** [comment]
大佬看到了还希望能回复一下，万分感谢

**Comment by xiongguangjie** [comment]
你日志文件，使用场景，都没有怎么回复？

**Comment by 1422595412** [comment]
使用的技术栈就是vue和Java，场景主要是使用rtsp推流进行视屏预览播放，然后就是使用视频的录制功能，使用文档中的/index/api/startRecord接口进行录制。推流和录制都是正常使用的，就是在录制过后进行停止一个流的录制时，会发现调一次/index/api/stopRecord接口停止不了，连续两次可以停止，大概就是这样，目前还不知道问题出在哪里。

**Comment by xia-chu** [comment]
“会发现调一次/index/api/stopRecord接口停止不了，连续两次可以停止，大概就是这样”

我觉得不可能
