### ISSUE TITLE
[技术咨询] c api 服务启动以后，如何优雅的关闭

### ISSUE THREAD

**Issue by mk-wang** [ZLMediaKit/ZLMediaKit#3458]
**咨询的功能模块**
c api

**咨询的具体内容和问题**

首先感谢作者，这个是一个强大，简单易用的库。

我在ios app中 模仿 api/test/server.c，启动了服务。

现在遇到的问题是在app结束的时候，没有办法优雅的退出，就算事先调用了mk_stop_all_server()，
也会崩溃在 AsyncLogWriter::~AsyncLogWriter -> AsyncLogWriter::flushAll

请问有办法让服务附属于某个进程，可以打开、关闭服务，并做好清理工作吗

**Comment by mk-wang** [comment]
用 Logger::Instance().setWriter(null_ptr) 可以解决一部分问题

但是后面 crash 跟 zltoolkit 里面单例对象的释放相关
例如 EventPoller::~EventPoller() 中调用了 InfoL，这时候 LogContextCapture 已经释放了

**Comment by xia-chu** [comment]
> 用 Logger::Instance().setWriter(null_ptr) 可以解决一部分问题
> 
> 但是后面 crash 跟 zltoolkit 里面单例对象的释放相关 例如 EventPoller::~EventPoller() 中调用了 InfoL，这时候 LogContextCapture 已经释放了

这应该是你的问题 zlm的测试和主程序都不存在你说的问题 zlm内部是做了单例释放顺序控制的

**Comment by xia-chu** [comment]
你先提供下崩溃堆栈
