### ISSUE TITLE
视频设备推送RTMP流到ZLMediaKit，ZLMediaKit转推到GB28181服务，参数配置疑问

### ISSUE THREAD

**Issue by lhqiang** [ZLMediaKit/ZLMediaKit#3467]
**咨询的功能模块**
让ZLMediaKit往其他国标服务器推流的restful api（/index/api/startSendRtp）

**咨询的具体内容和问题**
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/2876380/44186a32-780b-4cfe-b01b-9d1706112378)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/2876380/5158d8c4-5ef7-49bc-8598-7499ef460655)
SIP服务器ID：即国标监控平台的SIP信息ID，20位数字。
SIP服务器域：即国标监控平台的SIP信息ID的前10位。
SIP服务器地址：即国标监控平台的IP地址，目前仅支持IPV4地址。
SIP服务器端口：即国标监控平台SIP服务的端口号，默认为5060，设置范围：1~65535。
SIP服务器认证ID：即摄像头的ID，20位数字，设置类型为111~118。

**问题1 接口信息和SIP服务信息字段如何对应？
问题2 ZLMediaKit往其他国标服务器推流时   ZLMediaKit是作为一个软NVR设备还是可以多个设备推送？**

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
1，这个是国标服务器来配置的与ZLM没太大关系
2，zlm不是国标服务器，只是实现了国标服务器的媒体收发部分（通过http restful api 控制的）

**Comment by xia-chu** [comment]
rtp推流是无法携带业务数据的 所以sip号不是通过zlm携带
