### ISSUE TITLE
[技术咨询] restapi 调用来实现视频的播放和停止

### ISSUE THREAD

**Issue by answer666** [ZLMediaKit/ZLMediaKit#3470]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

播放/暂停指定设备的视频

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

我参考了下面的文档地址： https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99
https://github.com/ZLMediaKit/ZLMediaKit/wiki/ZLMediaKit%E6%8E%A8%E6%B5%81%E6%B5%8B%E8%AF%95

但是没有发现，通过设备ID 来针对性的推流和拉流，比较迷惑。
我的技术栈是 vue+PHP，目的是想通过 restapi 来控制当前某个摄像设备的播放和停止。 目前不知道如何下手。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个主要是播放器来控制的，停止你就销毁播放器不就行了，播放就开始拉流

**Comment by answer666** [comment]
> 这个主要是播放器来控制的，停止你就销毁播放器不就行了，播放就开始拉流

感谢回复。拉流的stream我应该怎么获取，我没太看明白，还有就是这个stream怎么和当前我要看的设备相关联呢？我想看到指定探头的画面。

**Comment by AvenSun** [comment]
@answer666 

请参考[ restful api接口](https://github.com/ZLMediaKit/ZLMediaKit/wiki/postman-%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9A%84restful-api%E6%8E%A5%E5%8F%A3)

**Comment by answer666** [comment]
> @answer666
> 
> 请参考[ restful api接口](https://github.com/ZLMediaKit/ZLMediaKit/wiki/postman-%E8%87%AA%E5%8A%A8%E7%94%9F%E6%88%90%E7%9A%84restful-api%E6%8E%A5%E5%8F%A3)

感谢你的回复。 我看了下手册， 是否刚开始需要调用“addStreamProxy” 才能进行下一步？ 但是 url 具体怎么拼写，我还不太明确， 试了几次都是 play rtsp timeout

**Comment by AvenSun** [comment]
[播放url规则](https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99)

绝大部分问题的答案都在WIKI中，如果刚接触ZLM建议通读一遍WIKI起码有个印象
