### ISSUE TITLE
[技术咨询] 支持rtp推流，webrtc拉流吗

### ISSUE THREAD

**Issue by gongluck** [ZLMediaKit/ZLMediaKit#3474]
使用zlm的SDK支持，自行打包rtp推进zlm，然后网页webrtc拉流吗？

**Comment by xiongguangjie** [comment]
这个zlm支持rtp->MediaServer->webrtc , 你说的是使用zlm的C api 吗？ 这个就要根据实际情况讨论了

**Comment by gongluck** [comment]
> 这个zlm支持rtp->MediaServer->webrtc , 你说的是使用zlm的C api 吗？ 这个就要根据实际情况讨论了

是使用C api

**Comment by xia-chu** [comment]
不支持 zlm c sdk只提供输入frame的接口
输入rtp要用cpp的接口才行
