### ISSUE TITLE
How to play h264+opus in browser without webrtc?

### ISSUE THREAD

**Issue by a-ucontrol** [ZLMediaKit/ZLMediaKit#3477]
I tried using mpegts .js, aac works, but opus doesn't.
This issue created in mpegts .js project https://github.com/xqq/mpegts.js/issues/180#issue-2216933466
Are there other options?

**Comment by xiongguangjie** [comment]
webcodecs  or wasm to decode audio ,  you should custom player like https://github.com/langhuihui/jessibuca or https://github.com/xqq/mpegts.js or https://github.com/numberwolf/h265web.js 。

**Comment by a-ucontrol** [comment]
Unfortunately [mpegts.js](https://github.com/xqq/mpegts.js) does not play h264+opus.
Please pay attention to this: https://github.com/xqq/mpegts.js/issues/180#issue-2216933466

**Comment by xiongguangjie** [comment]
> Unfortunately [mpegts.js](https://github.com/xqq/mpegts.js) does not play h264+opus. Please pay attention to this: [xqq/mpegts.js#180 (comment)](https://github.com/xqq/mpegts.js/issues/180#issue-2216933466)

browser play opus should use wasm or webcodecs , open source web player not implement play opus audio function , you must  develop to implement by your self

**Comment by xiongguangjie** [comment]
> [mpegts.js](https://github.com/xqq/mpegts.js) supports h264+opus if you transfer the mpegts file via an http server, but does not play the zlm mpegts stream I don't understand where the problem is, zlm or mpegts.js
> 
> Please tell me what to pay attention to?

you can judge by ffplay  play zlm mpegts stream

**Comment by suzp1984** [comment]
One thing I'm sure is that this is the [mpegts.js](https://github.com/xqq/mpegts.js)'s issue when it want to demux the ts stream.

**Comment by a-ucontrol** [comment]
Thank you!
