### ISSUE TITLE
[BUG] 使用流地址请求播放,提示404

### ISSUE THREAD

**Issue by shenwenye** [ZLMediaKit/ZLMediaKit#3478]
### 相关日志或截图
![微信图片_20240416201509](https://github.com/ZLMediaKit/ZLMediaKit/assets/167203234/d3aeafaa-4947-4d1f-bfba-1c349476194f)

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
![微信图片_20240416202635](https://github.com/ZLMediaKit/ZLMediaKit/assets/167203234/a6831f89-364e-4c23-aeb9-9f715af08361)
![微信图片_20240416202529](https://github.com/ZLMediaKit/ZLMediaKit/assets/167203234/1ad7e0fd-c6d9-4bd9-bcbf-1d70fabc952e)

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
[config.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/14996746/config.zip)

</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:无代码提交记录,通过git clone --depth 1 https://gitee.com/xia-chu/ZLMediaKit下载并执行git submodule update --init
* **操作系统及版本**:centos7
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
rtc 需要编译进去呀，参考wiki中，rtc的编译教程

**Comment by shenwenye** [comment]
已按照https://github.com/ZLMediaKit/ZLMediaKit/wiki/zlm%E5%90%AF%E7%94%A8webrtc%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97中的步骤进行编译,还是显示404



在 2024-04-17 09:30:05，"xiongguangjie" ***@***.***> 写道：

rtc 需要编译进去呀，参考wiki中，rtc的编译教程

**Comment by xiongguangjie** [comment]
这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来

**Comment by shenwenye** [comment]
就是使用wertc中的demo来播放的,显示黑屏,因为是通过堡垒机链接的,无法获取的日志文件,只有截图
















在 2024-04-17 10:00:03，"xiongguangjie" ***@***.***> 写道：

这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来

**Comment by xiongguangjie** [comment]
> 就是使用wertc中的demo来播放的,显示黑屏,因为是通过堡垒机链接的,无法获取的日志文件,只有截图 在 2024-04-17 10:00:03，"xiongguangjie" ***@***.***> 写道： 这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

demo 的console 的打印输出呢？还有http的请求的body ,返回是啥，我看你截图明显感觉不对，如果是堡垒机，你先排除网络问题吧

**Comment by shenwenye** [comment]
console打印,日志,返回数据均在压缩包呢!!!













在 2024-04-17 10:57:12，"xiongguangjie" ***@***.***> 写道：

就是使用wertc中的demo来播放的,显示黑屏,因为是通过堡垒机链接的,无法获取的日志文件,只有截图 在 2024-04-17 10:00:03，"xiongguangjie" @.> 写道： 这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

demo 的console 的打印输出呢？还有http的请求的body ,返回是啥，我看你截图明显感觉不对，如果是堡垒机，你先排除网络问题吧

**Comment by xiongguangjie** [comment]
> console打印,日志,返回数据均在压缩包呢!!! 在 2024-04-17 10:57:12，"xiongguangjie" ***@***.***> 写道： 就是使用wertc中的demo来播放的,显示黑屏,因为是通过堡垒机链接的,无法获取的日志文件,只有截图 在 2024-04-17 10:00:03，"xiongguangjie" @.> 写道： 这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> demo 的console 的打印输出呢？还有http的请求的body ,返回是啥，我看你截图明显感觉不对，如果是堡垒机，你先排除网络问题吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

没看到

**Comment by shenwenye** [comment]
在附件内













在 2024-04-17 11:09:36，"xiongguangjie" ***@***.***> 写道：

console打印,日志,返回数据均在压缩包呢!!! 在 2024-04-17 10:57:12，"xiongguangjie" @.> 写道： 就是使用wertc中的demo来播放的,显示黑屏,因为是通过堡垒机链接的,无法获取的日志文件,只有截图 在 2024-04-17 10:00:03，"xiongguangjie" @.> 写道： 这个需要你使用zlmrtc.js 来播放，你是咋播放的？？？zlm的日志上传上来 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.> demo 的console 的打印输出呢？还有http的请求的body ,返回是啥，我看你截图明显感觉不对，如果是堡垒机，你先排除网络问题吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

没看到

**Comment by xiongguangjie** [comment]
这个不应该报404，要么是你的堡垒机或者防火墙拦截了请求，要么是编译进去的rtc没有生效

**Comment by shenwenye** [comment]
这个解决了,是依赖包的问题,谢谢您!!!
