### ISSUE TITLE
[技术咨询] mp4录像如何通过起始结束时间来控制播放范围

### ISSUE THREAD

**Issue by truthsun22** [ZLMediaKit/ZLMediaKit#3482]
mp4录像都是按照比如3600秒保存的大分片文件，如果想从设定起始时间和结束时间，来看mp4某分片的某一小段视频，该如何做？有没有现成的API？还有就是如果mp4还在录制中，该如何处理？谢谢

**Comment by xiongguangjie** [comment]
没有现成的，你二开吧，你这种需求，一般都是自己开发程序来录制录像

**Comment by xia-chu** [comment]
通过rtsp和rtmp可以控制zlm seek到指定的时间
