### ISSUE TITLE
[技术咨询] MP4点播功能如何自动续播下一个mp4文件

### ISSUE THREAD

**Issue by dr34-m** [ZLMediaKit/ZLMediaKit#3483]
**咨询的功能模块**
- MP4文件点播功能

**咨询的具体内容和问题**

目前我遇到一个需求，要求查看回放，我希望通过MP4点播功能实现。我是在WEB实现该功能，采用webrtc播放录像；我只能通过webapi调用ZLMediaKit。

某个MP4点播并播放完之后，我要续播下一个MP4文件，我知道下一个mp4文件的路径，但是有以下几点我不明确：

* 如何知道当前MP4文件已经播放完毕（期间随时可能有seek或倍速操作）；
* 如何在前端无感的情况下把下一个mp4载入当前正在播放的流；

我当前的方案是逐个读取录像文件，获取每个播放文件的时长并入库，在播放结束后新建一个流播放下一个文件，但是这样会有下边的问题：

* 很明显的页面加载；
* 判断播放结束的方式很不优雅（js每隔0.1秒计算一次），容易有误差，会导致可能还没播放完就切到下一个流了；

如果ZLMediaKit可以实现以下功能，就能解决我的问题：

* 播放结束的回调；
* 更改mp4正在点播的mp4文件。

或者要是增加`自动续播下一个文件`的选项就更完美了。

非常感谢你们贡献了如此优秀的项目，希望能过得到贵方帮助。

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个需要二开，可以通过datachannel 来控制播放

**Comment by xia-chu** [comment]
这个不支持
