### ISSUE TITLE
[技术咨询] 关闭MP4录像保存

### ISSUE THREAD

**Issue by TonyWang8904** [ZLMediaKit/ZLMediaKit#3484]
**咨询的功能模块**
- 创建直播流

**咨询的具体内容和问题**
- 使用mk_media_create创建MediaSource后，添加H.264帧，可正常播放后，但是会在本地record生成mp4文件，播放结束后不自动删除，请问如何关闭该功能
相关代码如下：
```
MK_MEDIA mkMedia = ZLM_API.mk_media_create("__defaultVhost__", "live", "test", 0, 1, 1);
ZLM_API.mk_media_init_track(mkMedia, mkTrack);
ZLM_API.mk_media_init_complete(mkMedia);
while(buffer != null){
    ZLM_API.mk_media_input_h264(mkMedia, buffer, size,0,0);
}
ZLM_API.mk_media_release(mkMedia);
```

**Comment by xiongguangjie** [comment]
mk_media_create 这个不是有参数控制的呀 mp4_enabled 设置为1了，就会录制为mp4录像

**Comment by answer666** [comment]
> mk_media_create 这个不是有参数控制的呀 mp4_enabled 设置为1了，就会录制为mp4录像

你好，我这边对应看了下。 我没开启，但是还是录像了。
<img width="321" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/82018243/08c5b4f2-5788-4b41-8107-142a4d196da5">

**Comment by gl794262724** [comment]
如果是是配合wvp项目使用时，record-push-live也会自动录制
#推流时录制
record-push-live：在项目中默认true，可以更改为false
