### ISSUE TITLE
[技术咨询] 直播流播放H.265失败

### ISSUE THREAD

**Issue by TonyWang8904** [ZLMediaKit/ZLMediaKit#3485]
**咨询的功能模块**
- 创建直播流

**咨询的具体内容和问题**
- 海康IPC设置流H.264，使用海康SDK中NET_DVR_SetESRealPlayCallBack函数获取裸流，添加到mk_media_create创建MediaSource后，可正常播放，修改IPC设置流H.265，修改ZLM相应参数为265，播放错误错误
- IPC参数设置
![2024-04-20_180620](https://github.com/ZLMediaKit/ZLMediaKit/assets/12045700/f4b5beeb-4ca4-4462-a6a3-fac325006939)
- 相关代码
```
MK_MEDIA mkMedia = ZLM_API.mk_media_create("__defaultVhost__", "live", "test", 0, 1, 1);
MK_TRACK mkTrack = ZLM_API.mk_track_create(1, args);
ZLM_API.mk_media_init_track(mkMedia, mkTrack);
ZLM_API.mk_media_init_complete(mkMedia);
while(pBuffer.length > 0){
    ZLM_API.mk_media_input_h265(mkMedia, pBuffer, dwSize,0,0);
}
ZLM_API.mk_media_release(mkMedia);
```
- 使用VLC播放报错
![2024-04-20_175944](https://github.com/ZLMediaKit/ZLMediaKit/assets/12045700/747dba6e-3716-49d5-998d-6f498c202d8c)

请问如何解决，谢谢

**Comment by xiangshengjye** [comment]
h265的，你用vlc播放，只能播放rtsp地址的流

**Comment by jshqhxm** [comment]
hls的地址也是可以播放的，RTMP的流和FLv的流都是播放失败的

**Comment by TonyWang8904** [comment]
感谢各位，开发个前端用播放器就可以播放了，的确是VLC的问题，谢谢
