### ISSUE TITLE
zlmediakit提供的web hook机制如何确保有序性

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#3488]
### 现象描述
我在自己的业务服务器中监听zlmediakit上报的hook事件，发现有时候会出现业务服务器接收到hook事件的顺序与zlmediakit触发hook事件的顺序不一致的情况，对于一些顺序性敏感的业务，比较危险，比较媒体源注册、注销事件，业务服务器接收到的顺序不一样，那么处理逻辑完全不一样。原因是zlmediakit在触发hook事件时，每次都是创建新的HTTP客户端。如果能复用同一个HTTP客户端 ，应该就能解决这个问题了。

### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
我觉得 这最多只能算个特性 不能算zlm的bug。

目前zlm在触发hook时 有个hook_index的全局参数，希望能对你有用

**Comment by quxiaohui-debug** [comment]
好的，感谢答复
