### ISSUE TITLE
[技术咨询] 诉求:通过拉取历史流进行回放,支持暂停,拖拽

### ISSUE THREAD

**Issue by shenwenye** [ZLMediaKit/ZLMediaKit#3489]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
- 通过转换历史视频流后,ZLMediakit支持暂停,拖拽

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
- 目前拉取的历史流信息,在ZLM RTC demo中播放时,不支持暂停效果(点击暂停,画面停止,但再次点击播放,时间会跳转)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
目前无法支持
