### ISSUE TITLE
[技术咨询] RK3588使用mk动态库推流(低帧率1FPS)，再通过addStreamProxy拉流，帧率变为1000FPS

### ISSUE THREAD

**Issue by TRYOKETHEPEN** [ZLMediaKit/ZLMediaKit#3494]
**咨询的功能模块**
- zlmediakit c++ sdk（mk动态库）推流
- zlmediakit addStreamProxy拉流

**咨询的具体内容和问题**
RK3588开发板，使用mk动态库推流rtsp输出，本应为1FPS，记为流yolo。
使用vlc无法播放流yolo（参考https://github.com/ZLMediaKit/ZLMediaKit/issues/608 可能是播放器本身的问题）。
部署在另一台服务器上的zlmediakit通过addStreamProxy对流yolo拉流，录制的MP4文件帧率为1000FPS，zlmediakit的web管理页面显示的时间戳增量信息也异常，看起来像是把dts除了1000倍。
不知道是mk动态库的问题，还是zlmediakit的问题，请问有没有进一步排查的思路建议？

- 开发板工作流程：输入rtsp视频流为25FPS，每25帧从输入视频流取1帧，进行推理画框后，使用mk动态库推流rtsp输出。
- 推流相关代码如下：
（1）推流初始化：
![code2](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/6a8b0725-c3be-4666-9c1e-9d0e32850f93)
其中初始化时v_args.video的三项参数不指定，现象也一样。
（2）推流：
![code](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/383bc9c4-eb95-4f2f-b5fc-3ad92f77d915)
- 推流信息：只有一个视频轨道，格式为YUV420SP(NV12)，分辨率为1920*1080，视频编码为H.264，无音频。推流地址rtsp://192.168.1.107:554/live/yolo
- 开发板输出日志：可以看到推流的dts是正常的，每两个推流帧之间dts间隔约为1000ms<details><summary>展开查看详细日志</summary><pre>
#1714006149091 (frame4700) RGA cvtcolor
#1714006149098 (frame4700) RGA letterbox
省略
0.85 (1621,1637, 646, 661) earth 
#1714006149286 (frame4700) encode
#1714006149291 (frame4700) push rtsp
dts=1714006149291
#1714006150104 (frame4725) RGA cvtcolor
#1714006150111 (frame4725) RGA letterbox
省略
0.97 (1737,1920, 465, 843) wangka (part)
#1714006150216 (frame4725) encode
#1714006150221 (frame4725) push rtsp
dts=1714006150221</pre></details>
- 使用VLC播放流yolo现象：无画面，进度条正常变化，能显示编码信息。
![vlc现象](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/b285eed4-f3c1-4ca0-ad18-c019194affd3)
- 使用zlmediakit拉流的参数：http://172.18.100.49:8081/index/api/addStreamProxy?secret=省略&vhost={{defaultVhost}}&app=live&stream=record2&url=rtsp://172.18.4.2:15554/live/yolo&rtp_type=0&timeout_sec=1000&enable_hls=0&enable_hls_fmp4=0&enable_mp4=1&enable_rtsp=1&enable_rtmp=0&enable_ts=0&enable_fmp4=0&enable_audio=0&add_mute_audio=0&mp4_save_path=&mp4_max_second=10&hls_save_path=&modify_stamp=0&auto_close=0
其中rtsp://172.18.4.2:15554/live/yolo即为开发板推流rtsp://192.168.1.107:554/live/yolo的端口转发映射地址。
将modify_stamp分别设置为0、1、2，现象均一样。
- zlmediakit管理页面：显示的“时间戳增量信息”异常，应当是“累计接收帧数”+1时“时间戳增量信息”+1000左右才对。
![拉流现象](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/688c7fef-ea83-458a-86de-cb9ba61803d2)
- zlmediakit录制MP4文件：下载http://172.18.100.49:8081/record/live/record2/2024-04-25 下的录制视频，使用potplayer视频播放器打开，信息如下：
![POTPLAYER](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/adeefb24-360b-4be1-9e0c-e18eb1892d26)
暂停视频逐帧查看，每帧画面都是正常的，只是时间间隔异常，本应为1s左右，变成了1ms左右。

**开发板相关信息**
- 操作系统及版本:Debian 11, 内核5.10.160
- 硬件信息:RK3588，aarch64平台
- mk动态库：用的是https://github.com/airockchip/rknn-toolkit2/tree/master/rknpu2/examples/3rdparty/zlmediakit
- mk动态库的配置文件：[mk_config.ini.txt](https://github.com/ZLMediaKit/ZLMediaKit/files/15102863/mk_config.ini.txt)

**zlemdiakit服务相关信息**
- 操作系统及版本:Ubuntu 22.04, 内核5.15.0-97-generic
- zlmediakit docker版本：zlmediakit/zlemediakit:master，镜像ID为b872a073743e

**Comment by xiongguangjie** [comment]
z这个应该是编码器码流里面携带的帧率

**Comment by TRYOKETHEPEN** [comment]
> z这个应该是编码器码流里面携带的帧率

你好，编码器使用的是RK3588的MPP硬件编码器，fps相关参数如下：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/96d65507-ee83-4dbd-9746-16f19bd9fe9e)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/fd6a1c8b-4bdd-4514-8a54-0de0e45c18a0)
来自文档：https://opensource.rock-chips.com/images/b/bf/MPP_%E5%BC%80%E5%8F%91%E5%8F%82%E8%80%83_v0.3.pdf

开发板按照如下设置编码器后：
![encodefpssetting](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/75e12e47-c9de-4916-81bd-ab8519343b8d)

只是会使此处的fps变化，时间戳增量仍然异常，录制视频帧率仍然是900~1000fps：
![encode固定帧率](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/a4bba957-09c8-4ebc-8a00-9adff329d99c)

异常应该与编码器无关。

**Comment by TRYOKETHEPEN** [comment]
另外进行试验如下：
输入视频流为25FPS，对输入的每n帧中丢弃(n-1)帧，只对其中1帧进行AI视觉处理并输出。
n≥6时，时间戳增量稳定出现异常。
n=4或5时，时间戳增量不稳定异常，刷新一下可能又正常了。
n≤3时，时间戳增量稳定正常。

n=8:
![8抽7](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/e6013e12-1bf5-4552-bd96-04fec99cf00f)
n=5:
![5抽4](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/a6f70d55-f3a2-461e-95fe-87ce56a378fc)
![5抽4临界](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/0bc64189-ff04-41e6-a2d5-775108fc265c)
n=4:
![4抽3](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/afbe041f-30d1-403b-a66c-a994ccac63a7)
n=3:
![3抽2](https://github.com/ZLMediaKit/ZLMediaKit/assets/114904417/8e4b8fcd-b47d-4ec9-a74c-e9a6a5ab2a59)

**Comment by xiongguangjie** [comment]
ZLMediakit 的帧率，是通过解析sps里面的信息获取的（这个是h264的标准规定的，参考h264 sps vui 的解析），播放器也是这么做的，我看你的代码，dts 应该从0开始计数，你的代码直接获取系统时间，作为dts的，你要看dts的间隔值

**Comment by TRYOKETHEPEN** [comment]
> ZLMediakit 的帧率，是通过解析sps里面的信息获取的（这个是h264的标准规定的，参考h264 sps vui 的解析），播放器也是这么做的，我看你的代码，dts 应该从0开始计数，你的代码直接获取系统时间，作为dts的，你要看dts的间隔值

（1）sps我去学习一下，感谢回复。
（2）dts的间隔值是正常的。我也尝试了从0开始，每次+1000，现象一样。
（3）另外，这个yolo流转record4流，昨晚尝试了开启转hls后用web播放器播放，是正常的1FPS。

**Comment by xiongguangjie** [comment]
> > ZLMediakit 的帧率，是通过解析sps里面的信息获取的（这个是h264的标准规定的，参考h264 sps vui 的解析），播放器也是这么做的，我看你的代码，dts 应该从0开始计数，你的代码直接获取系统时间，作为dts的，你要看dts的间隔值
> 
> （1）sps我去学习一下，感谢回复。 （2）dts的间隔值是正常的。我也尝试了从0开始，每次+1000，现象一样。 （3）另外，这个yolo流转record4流，昨晚尝试了开启转hls后用web播放器播放，是正常的1FPS。
(2), 时间间隔正常，那你的截图中时间戳异常是咋回事，是怎么判断识别的，如果hls 正常的，其他协议应该也一样，因为都是用的同一个时间戳

**Comment by TRYOKETHEPEN** [comment]
“时间间隔正常，那你的截图中时间戳异常是咋回事”  这就是我提这个issue要问的问题呀

**Comment by xiongguangjie** [comment]
> “时间间隔正常，那你的截图中时间戳异常是咋回事” 这就是我提这个issue要问的问题呀

你是通过什么办法来判断时间戳异常的？你可以通过rtsp协议抓包来分析时间戳是否异常

**Comment by xuandu** [comment]
> ZLMediakit 的帧率，是通过解析sps里面的信息获取的（这个是h264的标准规定的，参考h264 sps vui 的解析），播放器也是这么做的，我看你的代码，dts 应该从0开始计数，你的代码直接获取系统时间，作为dts的，你要看dts的间隔值

H264 265 每个GOP的SPS都计算下FPS，影响性能吗？测试是在1毫秒内的；
现在有个问题变帧率视频，有时候是但帧率，到
  if (_option.modify_stamp != ProtocolOption::kModifyStampOff) {
        // 时间戳不采用原始的绝对时间戳
        frame = std::make_shared<FrameStamp>(frame, _stamp[frame->getTrackType()], _option.modify_stamp);
    }
这个地方的时候阈值300以外就会被平滑成间隔1毫秒；调大间隔总感觉治标不治本；想逐个GOP都计算FPS；然后来决定时间戳是否是跳变还是变帧率
