### ISSUE TITLE
使用最新版本，并且开启了https，部分https地址为null

### ISSUE THREAD

**Issue by git-403** [ZLMediaKit/ZLMediaKit#3495]
**咨询的功能模块**
 点播功能模块

**咨询的具体内容和问题**
按照文档开启了https，点播的时候返回的url地址有https_fmp4、https_ts、https_ts就是没有https_flv,但是在测试工具里将http_flv地址改成https端口改成https的端口能播放视频，麻烦问题下是那块配置的不对吗？，已经issue并且百度也查找了

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
wvp吧，去github 看相应的文档，用得啥就去看相应的文档

**Comment by git-403** [comment]
> wvp吧，去github看相应的文档，用得啥就看相应的文档

wvp打断点看zlm返回的时候就没有https_flv
