### ISSUE TITLE
和摄像头对接的时候遇到 流量消耗 过大的问题，请问可不可以通过查询zlm的日志定位问题

### ISSUE THREAD

**Issue by xufan-cmd** [ZLMediaKit/ZLMediaKit#3497]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
zlm的日志 是否记录了 流量使用情况
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
使用 zlm播放摄像头直播时遇到流量消耗过多的问题，查看nohup.out 发现摄像头 注册流的时间 到注销流的时间左右 几秒。但是流量卡的流量用的很大
**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
有接口(restful api 看wiki)可以获取流的码率，如getMediaInfo或者getMediaList

**Comment by xufan-cmd** [comment]
好的，谢谢
