### ISSUE TITLE
使用C API mk_player拉流一段时间断开

### ISSUE THREAD

**Issue by dev000il** [ZLMediaKit/ZLMediaKit#3498]
zlm C API
mk_player rtsp拉流
摄像机 海康鱼眼

使用场景
多线程拉流，每个线程中创建一个mk_player
  mk_player player = mk_player_create();
  mk_player_set_on_result(player, on_mk_play_event_func, ctx);
  mk_player_set_on_shutdown(player, on_mk_shutdown_func, ctx);
  mk_player_play(player, url);

运行一段时间后，进on_mk_shutdown_func
 play interrupted: 255 connection reset by peer

2024-04-26 14:23:20.115 W rknn_yolov5_video_zero_out[5986-event poller 2] RtspPlayer.cpp:689 onPlayResult_l | 255 connection reset by peer

**Comment by xiongguangjie** [comment]
这个对端关闭tcp链接了，
