### ISSUE TITLE
[技术咨询] 批量播放加载缓慢问题

### ISSUE THREAD

**Issue by xushuxiong** [ZLMediaKit/ZLMediaKit#3501]
**ws-ts播放问题**
- 使用zlmediakit进行批量播放视频，建立ws等待时间长

- 您好，我使用zlmediakit作为流媒体服务器进行摄像头视频流转发（基于rtsp），发现32个流地址同时播放时，ws连接等待时间长，画面一直转圈圈的问题，具体效果如视频所示（由于github无法上传超10M的文件，所以上传到图床，链接如下：[https://mp4.ziyuan.wang/player.php?hash=da7784874fe4f38213d8428ec71a585c](https://mp4.ziyuan.wang/player.php?hash=da7784874fe4f38213d8428ec71a585c)），配置文件如附件所示，请问是什么原因导致的，是需要进行其他配置修改吗？目前找不到排查方向，请大神帮忙看看，十分感谢！
[Uploading config.txt…]()

**Comment by xiongguangjie** [comment]
看服务器的日志（一闪而过，应该使用了无人观看去拉流的特性），好像你你的信令服务器（控制ZLM拉rtsp流的服务），响应很慢，5s来响应玩，这个你要把服务器的日志上传才能分析，是咋回事，大概率是你的信令服务器阻塞了

**Comment by xushuxiong** [comment]
> 看服务器的日志（一闪而过，应该使用了无人观看去拉流的特性），好像你你的信令服务器（控制ZLM拉rtsp流的服务），响应很慢，5s来响应玩，这个你要把服务器的日志上传才能分析，是咋回事，大概率是你的信令服务器阻塞了

我是同时播放32路ws，并且请求zlm已经是请求回来的，也就是有了32个播放地址，但是f12看ws请求里面的数据，确实卡顿的时候短暂没有刷，与此同时，在另一个客户端打开单路视频流也会出现卡顿转圈圈的现象，是因为ws播放的原因吗。

**Comment by xia-chu** [comment]
浏览器显示请求pendding了 应该是触发同源限制了
或者请求的这个流还没上线 zlm在hold这些链接
