### ISSUE TITLE
[技术咨询] 同时录制多个视频 长时间会出无限碎片

### ISSUE THREAD

**Issue by Hareis** [ZLMediaKit/ZLMediaKit#3502]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11290701/d206c230-e783-4db0-81cc-84c9fbefbaf1)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11290701/8995eaed-8c7d-4b6f-8e3f-4792345654e6)

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11290701/800ea7ee-a971-4a57-9b62-51fcfada701e)

目前公司有一个业务需要同时录制多个视频，
目前测试下来有个问题 当多个录制同时开启后 具体个数没测试出来 刚开始录制的是正常的 时间长了 会导致有部分录制产生无限的碎片

* 对就是那个满地的碎片*

**Comment by xiongguangjie** [comment]
感觉是你的推流端，在倍速推流，才会导致这样的
