### ISSUE TITLE
[技术咨询] 如何提高视频码率

### ISSUE THREAD

**Issue by Oushinan** [ZLMediaKit/ZLMediaKit#3504]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

**咨询的具体内容和问题**
使用WVP+ZLM，公网部署在同一台主机上，通过海康NVR连接大华球机
大华摄像头配置：H264，25fps, 720p
视频传输采用TCP被动
点播，码率只有几百k，画面不是很清晰

tcpdump抓收到的视频包，用wireshark统计-IO图表，显示码率也有几M，不知道准不准确
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/13740534/f5e865e0-fab9-4893-9c04-0144b716c02b)

对比青柿流媒体服务器LiveGBS，部署在同一台主机，接入相同设备，码率能达到2M多
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/13740534/2f0f5960-c8fa-4377-a072-1ac95dda6c30)

配置：转码只保留了rtsp,rtmp

请问能如何提高码率？

下面为MediaInfo信息：
{
    "aliveSecond": 23,
    "app": "rtp",
    "bytesSpeed": 337119,
    "code": 0,
    "createStamp": 1714377656,
    "isRecordingHLS": false,
    "isRecordingMP4": false,
    "originSock": {
        "identifier": "34020000001110000001_34020000001320000004",
        "local_ip": "10.10.25.165",
        "local_port": 50240,
        "peer_ip": "124.193.167.***",
        "peer_port": 62844
    },
    "originType": 3,
    "originTypeStr": "rtp_push",
    "originUrl": "rtp://__defaultVhost__/rtp/34020000001110000001_34020000001320000004",
    "params": "",
    "readerCount": 0,
    "schema": "rtsp",
    "stream": "34020000001110000001_34020000001320000004",
    "totalReaderCount": 1,
    "tracks": [
        {
            "channels": 1,
            "codec_id": 2,
            "codec_id_name": "mpeg4-generic",
            "codec_type": 1,
            "duration": 23296,
            "frames": 184,
            "loss": 0.0,
            "ready": true,
            "sample_bit": 16,
            "sample_rate": 8000
        },
        {
            "codec_id": 0,
            "codec_id_name": "H264",
            "codec_type": 0,
            "duration": 23441,
            "fps": 25.0,
            "frames": 588,
            "gop_interval_ms": 1920,
            "gop_size": 50,
            "height": 720,
            "key_frames": 14,
            "loss": 0.0,
            "ready": true,
            "width": 1280
        }
    ],
    "vhost": "__defaultVhost__"
}

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
在编码的地方设置(一般是在推流端），你这个是在海康的设备页面上设置

**Comment by Oushinan** [comment]
谢谢，设备视频已经设置了码率上限2048Kbps
发现问题应该是显示单位的问题
 ZLM给的"bytesSpeed": 337119，单位是Bps
WVP前端播放器jessibuca提供的码率也是KBps，结果前端显示变成了kb/s，应该乘个8就差不多了

谢谢大佬解答！
