### ISSUE TITLE
请问是否支持断掉Hls协议连接的客户端

### ISSUE THREAD

**Issue by liuqiyang7** [ZLMediaKit/ZLMediaKit#3506]
**咨询的功能模块**
请问是否支持断掉Hls协议连接的客户端？

**咨询的具体内容和问题**
请问是否支持断掉Hls协议连接的客户端？
尝试使用/index/api/kick_session和/index/api/kick_sessions接口没有效果，会生成一个新的sessionId，客户端并没有什么感知
期望可以把和客户端交互的session失效掉

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
这个没办法吧（http是短连接，hls 流是多次htt请求组成的），只能通过鉴权来禁止，或者你二开，没有cookie 的返回404

**Comment by liuqiyang7** [comment]
> 这个没办法吧（http是短连接，hls 流是多次htt请求组成的），只能通过鉴权来禁止，或者你二开，没有cookie 的返回404

但是第一次触发鉴权之后续会一直自动续签，不会再触发回调。  如果用户一直挂在后台播放我们也没有办法进行干预。

**Comment by xia-chu** [comment]
> > 这个没办法吧（http是短连接，hls 流是多次htt请求组成的），只能通过鉴权来禁止，或者你二开，没有cookie 的返回404
> 
> 但是第一次触发鉴权之后续会一直自动续签，不会再触发回调。 如果用户一直挂在后台播放我们也没有办法进行干预。

目前播放成功就可以一直播放下去 跟长连接的协议效果一致
