### ISSUE TITLE
视频播放端口CORS跨域资源共享，请问可以设置吗

### ISSUE THREAD

**Issue by 1343228975** [ZLMediaKit/ZLMediaKit#3509]
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
日志内容...
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
默认就允许跨域的

**Comment by 1343228975** [comment]
allow_cross_domains=1
请问一下这个配置要怎么配置可以让它不允许跨域，或者限定某个地址
 Access-Control-Allow-Origin中指定的来源只能是受信任的站点

**Comment by xiongguangjie** [comment]
> allow_cross_domains

设置为0 就不允许跨域了，如果要指定Access-Control-Allow-Origin的值，就需要二开了
