### ISSUE TITLE
allow_cross_domains设置为0但是还是会允许跨域

### ISSUE THREAD

**Issue by 1343228975** [ZLMediaKit/ZLMediaKit#3513]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能

播放端口跨域的问题

**咨询的具体内容和问题**
我设置了allow_cross_domains为0，但是还是会允许跨域，能帮忙看下吗
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/93633113/f4d022e4-812b-4de7-bdc9-cbf615dbd995)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/93633113/3552ff29-4583-43a0-826f-be427ecf9f2e)

**注意事项**

**Comment by 1343228975** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/93633113/dd9bf43e-9f74-4e8b-a981-0d19825bcc8e)
文件结构是这种，还需要改哪里吗，求大佬指导

**Comment by monktan89** [comment]
这个不应该设置为 1？

**Comment by xiongguangjie** [comment]
这个你代码是最新的吗？我看代码设置为0 ，就不会设置跨域的请求，你是不是经过了代理呀？？？

**Comment by 1343228975** [comment]
> 这个你代码是最新的吗？我看代码设置为0 ，就不会设置跨域的请求，你是不是经过了代理呀？？？

代码不是最新的，zlm可以升级吗？
这种部署的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/93633113/4a78427c-0f8e-44e7-a8d2-eede19714232)

**Comment by xia-chu** [comment]
升级吧
