### ISSUE TITLE
我在使用docker安装完成zlmediakit之后出现问题

### ISSUE THREAD

**Issue by bianhuamoxiangli** [ZLMediaKit/ZLMediaKit#3514]
我在使用docker安装完成zlmediakit之后出现问题
在运行容器之后 第一次拉流成功，并且可以播放流，但是第二次及以后 都无法播放了
网页啥的都能正常打开，就是这个拉取的流播不了
![8d324b578247ca66cf7f8e2be8e934e](https://github.com/ZLMediaKit/ZLMediaKit/assets/107593191/6a39eeba-4f84-4329-a788-ed7b239d8327)

**Comment by bianhuamoxiangli** [comment]
这个是运行的log
[2024-05-06_00.log](https://github.com/ZLMediaKit/ZLMediaKit/files/15228477/2024-05-06_00.log)

**Comment by monktan89** [comment]
能否拉流和你怎么部署没有关系，docker 部署你应该检测端口映射是否正确，看你的日志connect result: 3(connection refused) 这个是否权限问题还是直接禁止了
