### ISSUE TITLE
[功能请求] 增加一个直接分发buffer到外部udp的接口

### ISSUE THREAD

**Issue by mc373906408** [ZLMediaKit/ZLMediaKit#3516]
**描述该功能的用处，可以提供相关资料描述该功能**
比如SIP中DTMF使用RFC 2833发送，会发送一个pt值为101的RTP包，这个包不可被编解码，也就是不能创建MediaSource对象。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
希望有一个接口是能直接转发给外部设备。

**Comment by monktan89** [comment]
欢迎提 PR
