### ISSUE TITLE
推流无法播放

### ISSUE THREAD

**Issue by sling2007** [ZLMediaKit/ZLMediaKit#3517]
**咨询的功能模块**
- 作为rtsp服务器，被推送来了视频流，播放不出来。

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

拉流的视频正常播放。
但推流的播放不了，操作如下：

用ffmpeg -re -stream_loop -1  -i .\model.mp4 -vcodec h264 -an -f rtsp -rtsp_transport tcp rtsp://10.101.59.236/pppush/abc 推流后，能看到视频列表
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/4436803/e5fe6899-bc60-42bb-a303-60b12f3f1a6c)

在VLC可以播放这个推来的视频地址。rtsp://10.101.59.236:554/pppush/abc
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/4436803/0ef02a6f-3de2-4c63-ac3f-73291d91678f)

但在zlm的播放页，提示播放成功，但播放一直转圈等待。https://10.101.59.236/index/api/webrtc?app=pppush&stream=abc&type=play
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/4436803/f8ad9d52-c6bd-4c8e-ba54-609be3f2daa8)

所以，我是哪里用错了吗？ 

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
看wiki的webrtc 的说明，你这个是directProxy 没有设置为0
