### ISSUE TITLE
java Api中的服务启动事件为什么被注释掉了

### ISSUE THREAD

**Issue by liuqiyang7** [ZLMediaKit/ZLMediaKit#3518]
**咨询的功能模块**
java Api中的服务启动事件为什么被注释掉了

**咨询的具体内容和问题**
依赖版本
<dependency>
    <groupId>io.github.lunasaw</groupId>
    <artifactId>zlm-spring-boot-starter</artifactId>
    <version>1.0.3</version>
</dependency>

<img width="904" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/63906369/0c46f06b-1330-400d-8af7-4384b63e486c">

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
去wvp的github 下去问
