### ISSUE TITLE
[技术咨询] 请问现在docker版本的Release Note 在哪看？

### ISSUE THREAD

**Issue by CxistHans** [ZLMediaKit/ZLMediaKit#3521]
**咨询的功能模块**
- 官方Docker 镜像打包的tag问题

**咨询的具体内容和问题**
- [官方docker镜像](https://hub.docker.com/r/zlmediakit/zlmediakit) 主分支只有一个master分支，而且每次更新也都重复tag
- 以及其他几个tag的说明有吗？有什么区别？
- 主要想确认每次更新的历史记录在哪能看到，确认更新了些啥，不然不敢用最新的版本（怕不小心因为tag一样，拉到了最新的版本）
- 为啥考虑只一个tag？基于什么考虑呢？后续会不会调整？
- 还有就是生产环境建议容器化（docker/k8s）安装使用？

**Comment by xia-chu** [comment]
更新zlm源码后  ci会自动推送docker镜像到dockhub 跟最新代码保存同步的

**Comment by CxistHans** [comment]
> 更新zlm源码后 ci会自动推送docker镜像到dockhub 跟最新代码保存同步的

麻烦有空的时候再对应的回应下其他几个问题？

**Comment by xia-chu** [comment]
- 以及其他几个tag的说明有吗？有什么区别？
   其他tag都是feature分支

- 主要想确认每次更新的历史记录在哪能看到，确认更新了些啥，不然不敢用最新的版本
   看commit记录，master分支会及时修复bug的，而且现在也没啥bug，你看issue基本都是技术咨询

 - 为啥考虑只一个tag？基于什么考虑呢？后续会不会调整？
   精力有限，只保证对master分支的持续更新维护

- 还有就是生产环境建议容器化（docker/k8s）安装使用？
   直接用最新master代码或docker即可，有问题来issue提，我会第一时间优先解决bug
