### ISSUE TITLE
[技术咨询]输入复合流中音频参数变更，RTSP输出的时候SDP错误

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#3522]
**咨询的功能模块**
RTSP的SDP生成模块

**咨询的具体内容和问题**
RTP输入---因为开了转协议RTSP，所以track准备好之后，SDP信息就会通过multimediasource更新到rtspmediasource 层；客户端拉流就直接使用RTSP了；
输入端变更编码方式，时候我可以通知重开RTP服务；但如果只是变更参数如AAC的采样率通道数；变更后,RTSP 打包段的SDP是不会更新的，并且RTP输出的AAC是不带ADTS头的，所以这个SDP没办法实时变更是个问题；

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

怎么才能在AAC解包阶段检测到变更就重新生成SDP呢，或者每次RTSP拉流都重新生成SDP；

**Comment by xiongguangjie** [comment]
这个需要二开

**Comment by xuandu** [comment]
> 这个需要二开

是的，只是我能想到的就是把track 通过 delegate传给sink,然后给到multimediasource，给到rtspmux,  给到 RTSPmediasource；巨长，所有有没有什么好方法？

**Comment by xiongguangjie** [comment]
> > 这个需要二开
> 
> 是的，只是我能想到的就是把track 通过 delegate传给sink,然后给到multimediasource，给到rtspmux, 给到 RTSPmediasource；巨长，所有有没有什么好方法？

通过 addTrackCompleted 来想想办法更新sdp
