### ISSUE TITLE
ZLMediakit 按需拉流rtsp，webrtc可以降低码率吗

### ISSUE THREAD

**Issue by feiyiban** [ZLMediaKit/ZLMediaKit#3523]
rtsp推流时，rtsp正常是1080p的，那么可以控制webrtc拉流播放时成cif的嘛

**Comment by xiongguangjie** [comment]
不行，除非转码

**Comment by feiyiban** [comment]
我现在考虑两个分辨率的视频rtsp出来还是1080p，但webrtc出来是cif，有没有webrtc这个的转码逻辑代码

**Comment by xia-chu** [comment]
> 我现在考虑两个分辨率的视频rtsp出来还是1080p，但webrtc出来是cif，有没有webrtc这个的转码逻辑代码

https://github.com/tsingeye/ZLMediakit-Pro
