### ISSUE TITLE
怎么把RTP流推到ZLMediaKit上的

### ISSUE THREAD

**Issue by nyl1223** [ZLMediaKit/ZLMediaKit#3525]
项目解析JT1078的协议并封装成RTP包，我通过ffplay可以正常播放，
想问一下怎么把RTP推到ZLMediaKit上的

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xiongguangjie** [comment]
openrtpserver 或者直接通过向udp端口推送（zlm 默认会监听10000端口，接收rtp流）

**Comment by nyl1223** [comment]
> openrtpserver 或者直接通过向udp端口推送（zlm 默认会监听10000端口，接收rtp流）

我是通过TCP推流到ZLMediaKit的端口554上的，只到这一步就不往下走了
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45548160/b746591f-edce-4ba7-af76-f613210b6fd5)

**Comment by xiongguangjie** [comment]
> > openrtpserver 或者直接通过向udp端口推送（zlm 默认会监听10000端口，接收rtp流）
> 
> 我是通过TCP推流到ZLMediaKit的端口554上的，只到这一步就不往下走了 ![image](https://private-user-images.githubusercontent.com/45548160/329614399-b746591f-edce-4ba7-af76-f613210b6fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzE3ODYsIm5iZiI6MTcxNTU3MTQ4NiwicGF0aCI6Ii80NTU0ODE2MC8zMjk2MTQzOTktYjc0NjU5MWYtZWRjZS00YmE3LWFmNzYtZjYxMzIxMGI2ZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAzMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDVlNzVlM2EyMDFlMWY0MzQ1NmE5MmQ1YzM3ZDA3MTJmZmU2ZGQ4YTIyOTU0ZmFkYTFmOTdkZmQ2MDNjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBBrcS5LVzG-w7KlIYmpBfCYJjIUWILOpbnmUyJST2c)

ffmpeg 报啥错误，zlm的日志呢，啥都没有

**Comment by nyl1223** [comment]
> > > openrtpserver 或者直接通过向udp端口推送（zlm 默认会监听10000端口，接收rtp流）
> > 
> > 
> > 我是通过TCP推流到ZLMediaKit的端口554上的，只到这一步就不往下走了 ![image](https://private-user-images.githubusercontent.com/45548160/329614399-b746591f-edce-4ba7-af76-f613210b6fd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzE3ODYsIm5iZiI6MTcxNTU3MTQ4NiwicGF0aCI6Ii80NTU0ODE2MC8zMjk2MTQzOTktYjc0NjU5MWYtZWRjZS00YmE3LWFmNzYtZjYxMzIxMGI2ZmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAzMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDVlNzVlM2EyMDFlMWY0MzQ1NmE5MmQ1YzM3ZDA3MTJmZmU2ZGQ4YTIyOTU0ZmFkYTFmOTdkZmQ2MDNjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gBBrcS5LVzG-w7KlIYmpBfCYJjIUWILOpbnmUyJST2c)
> 
> ffmpeg 报啥错误，zlm的日志呢，啥都没有
抓包日志
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45548160/7fe2215a-148f-4b9a-9a14-6f0660414a3d)
zlm报错日志
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45548160/f7cb5083-b578-41d8-b652-e5e753a5c536)
直接读取一个input.h264文件，封rtp包 推流到zlm上
卡住不往下执行，是不是少什么步骤

**Comment by xia-chu** [comment]
FFmpeg推流命令咋写的？
