### ISSUE TITLE
服务器响应RECORD成功，为什么推流ZlmediaKit接收不到

### ISSUE THREAD

**Issue by nyl1223** [ZLMediaKit/ZLMediaKit#3528]
1078视频流推流到ZML功能
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/45548160/a89cd3c0-a58d-4098-bdde-b3b4b68659a5)
组装的RTP流直接用ffplay拉流是可以播的，是不是要把RTP包封装成PS才能推到ZML服务上
报错：
2024-05-11 11:39:28.036 W [MediaServer.exe] [11764-event poller 1] RtspSession.cpp:62 onError | 9-964(127.0.0.1:44666) RTSP推流器(__defaultVhost__/live/test)断开:pusher session timeout,耗时(s):15
**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
什么时候rtsp可以走1078的流了？

**Comment by xia-chu** [comment]
现在有个闭源的1078分支 你干兴趣的话可以邮箱联系我

**Comment by nyl1223** [comment]
> 什么时候rtsp可以走1078的流了？

我没直接推1078的流，我是处理成rtp包才推的
