### ISSUE TITLE
[技术咨询] ZLM的镜像里../www/snap 下的截图全是破损图片

### ISSUE THREAD

**Issue by shiningtalent** [ZLMediaKit/ZLMediaKit#3529]
**咨询的功能模块**
- 快照截图

**咨询的具体内容和问题**
- M的镜像里../www/snap 下的截图全是破损图片
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/21002314/05914761-8864-49a9-ae26-38ed44637aed)

下面是ffmpeg日志内容：
root@fcc65462fec1:/opt/media/bin/ffmpeg# cat ffmpeg.log.87

#### pid=87,cmd=/usr/bin/ffmpeg -rtsp_transport tcp -i rtsp://127.0.0.1:554/rtp/10000000001301002123_34020000001310000007 -y -f mjpeg -frames:v 1 /opt/media/bin/www/snap/5b39939487a5f4bf4713d9be2b9b450b/1715411633.jpeg.tmp #####

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[rtsp @ 0x5618cd130380] method DESCRIBE failed: 401 Unauthorized
rtsp://127.0.0.1:554/rtp/10000000001301002123_34020000001310000007: Server returned 401 Unauthorized (authorization failed)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
截图URL鉴权失败了 你要把鉴权信息加上
