### ISSUE TITLE
国标拉流播放跑一段时间崩溃

### ISSUE THREAD

**Issue by boygaoyun** [ZLMediaKit/ZLMediaKit#3530]
### 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055ea36e9d968 in typeinfo for mediakit::ProcessInterface ()
[Current thread is 1 (Thread 0x7fbf9a7fc700 (LWP 21))]
(gdb) bt
#0  0x000055ea36e9d968 in typeinfo for mediakit::ProcessInterface ()
#1  0x000055ea368c7437 in mediakit::RtpTrack::inputRtp (this=0x7fbf90007b80, type=mediakit::TrackVideo, sample_rate=90000, ptr=0x7fbf8c01cea0 "\200`\020K\225\071\347\224\006BL\323", len=1396)
    at /opt/media/kmediasever-ms/src/Rtsp/RtpReceiver.cpp:105
#2  0x000055ea368a93f2 in mediakit::RtpReceiverImp::inputRtp (this=0x7fbf90007b80, type=mediakit::TrackVideo, ptr=0x7fbf8c01cea0 "\200`\020K\225\071\347\224\006BL\323", len=1396) at /opt/media/kmediasever-ms/src/Rtp/GB28181Process.cpp:44
#3  0x000055ea368a0111 in mediakit::GB28181Process::inputRtp (this=0x7fbf84003650, data=0x7fbf8c01cea0 "\200`\020K\225\071\347\224\006BL\323", data_len=1396) at /opt/media/kmediasever-ms/src/Rtp/GB28181Process.cpp:159
#4  0x000055ea3676bba2 in mediakit::RtpProcess::inputRtp (this=0x7fbf8800abb0, is_udp=false, sock=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<toolkit::Socket> (use count 2, weak count 2) = {...}, data=0x7fbf8c01cea0 "\200`\020K\225\071\347\224\006BL\323", len=1396, 
    addr=0x7fbf8800a230, dts_out=0x0) at /opt/media/kmediasever-ms/src/Rtp/RtpProcess.cpp:116
#5  0x000055ea36799a51 in mediakit::RtpSession::onRtpPacket (this=0x7fbf8800a0a0, data=0x7fbf8c01cea0 "\200`\020K\225\071\347\224\006BL\323", len=1396) at /opt/media/kmediasever-ms/src/Rtp/RtpSession.cpp:134
#6  0x000055ea36798d2b in mediakit::RtpSession::onRecv (this=0x7fbf8800a0a0, data=std::shared_ptr<toolkit::Buffer> (use count 2, weak count 0) = {...}) at /opt/media/kmediasever-ms/src/Rtp/RtpSession.cpp:53
#7  0x000055ea3653858f in toolkit::emitSessionRecv (helper=std::shared_ptr<toolkit::SessionHelper> (use count 2, weak count 2) = {...}, buf=std::shared_ptr<toolkit::Buffer> (use count 2, weak count 0) = {...})
    at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:159
#8  0x000055ea3653a56f in toolkit::UdpServer::<lambda()>::operator()(void) const (__closure=0x7fbf8c011690) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:342
#9  0x000055ea3653c91a in std::_Function_handler<void(), toolkit::UdpServer::createSession(const PeerIdType&, const Ptr&, sockaddr*, int, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/9/bits/std_function.h:300
#10 0x000055ea363f093e in std::function<void ()>::operator()() const (this=0x7fbf8c005740) at /usr/include/c++/9/bits/std_function.h:688
#11 0x000055ea365543eb in toolkit::TaskCancelableImp<void ()>::operator()() const (this=0x7fbf6c003e50) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Thread/TaskExecutor.h:111
#12 0x000055ea365539e0 in toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}::operator()(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&) const (
    __closure=0x7fbf9a7f87a8, task=std::shared_ptr<toolkit::TaskCancelableImp<void()>> (use count 1, weak count 0) = {...}) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:259
#13 0x000055ea36554d15 in toolkit::List<std::shared_ptr<toolkit::TaskCancelableImp<void ()> > >::for_each<toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}>(toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}&&) (this=0x7fbf9a7f87b0, func=...) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Util/List.h:203
#14 0x000055ea36553d06 in toolkit::EventPoller::onPipeEvent (this=0x55ea36feaf20) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:257
#15 0x000055ea3654e732 in toolkit::EventPoller::<lambda(int)>::operator()(int) const (__closure=0x55ea36feb790, event=1) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:57
#16 0x000055ea365518c6 in std::_Function_handler<void(int), toolkit::EventPoller::addEventPipe()::<lambda(int)> >::_M_invoke(const std::_Any_data &, int &&) (__functor=..., __args#0=@0x7fbf9a7f8c74: 1)
    at /usr/include/c++/9/bits/std_function.h:300
#17 0x000055ea365542fe in std::function<void (int)>::operator()(int) const (this=0x55ea36feb790, __args#0=1) at /usr/include/c++/9/bits/std_function.h:688
#18 0x000055ea36550681 in toolkit::EventPoller::runLoop (this=0x55ea36feaf20, blocked=true, ref_self=true) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:331
#19 0x000055ea36561c37 in std::__invoke_impl<void, void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__f=
    @0x55ea36feb408: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x55ea36550320 <toolkit::EventPoller::runLoop(bool, bool)>, __t=@0x55ea36feb400: 0x55ea36feaf20) at /usr/include/c++/9/bits/invoke.h:73
#20 0x000055ea36561ad9 in std::__invoke<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> (__fn=
    @0x55ea36feb408: (void (toolkit::EventPoller::*)(toolkit::EventPoller * const, bool, bool)) 0x55ea36550320 <toolkit::EventPoller::runLoop(bool, bool)>) at /usr/include/c++/9/bits/invoke.h:95
#21 0x000055ea365619a9 in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::_M_invoke<0ul, 1ul, 2ul, 3ul> (this=0x55ea36feb3f8) at /usr/include/c++/9/thread:244
#22 0x000055ea365617b1 in std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> >::operator() (this=0x55ea36feb3f8) at /usr/include/c++/9/thread:251
#23 0x000055ea36561546 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (toolkit::EventPoller::*)(bool, bool), toolkit::EventPoller*, bool, bool> > >::_M_run (this=0x55ea36feb3f0) at /usr/include/c++/9/thread:195
#24 0x00007fbfc4e4bdf4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#25 0x00007fbfc5393609 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#26 0x00007fbfc4b36353 in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) list
</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
配置内容...
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
代码是什么版本的

**Comment by boygaoyun** [comment]
master分支  
![Uploading 微信截图_20240511170200.png…]()

**Comment by boygaoyun** [comment]
> 代码是什么版本的

master分支
最新节点
Commit: bcf0c71
Parents: 9d68b66
Author: xiongziliang <771730766@qq.com>
Committer: xiongziliang <771730766@qq.com>
Date: Sat Dec 23 2023 21:32:24 GMT+0800 (中国标准时间)
Update ZLToolKit

**Comment by xiongguangjie** [comment]
太老了更新最新的代码试一下

**Comment by xia-chu** [comment]
关联 #3532
