### ISSUE TITLE
国标拉流崩溃，大概率出现

### ISSUE THREAD

**Issue by boygaoyun** [ZLMediaKit/ZLMediaKit#3532]
### 如何复现?

<details>
<summary>展开查看详细日志</summary>
<pre>
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
--Type <RET> for more, q to quit, c to continue without paging--bt
Core was generated by `./MediaServer -s default.pem -c ../conf/config.ini -l 0'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe881948fc4 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
[Current thread is 1 (Thread 0x7fe839ffb700 (LWP 28))]
(gdb) bt full
#0  0x00007fe881948fc4 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
#1  0x000055820dab1c0a in __gthread_mutex_lock (__mutex=0x120) at /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:749
No locals.
#2  0x000055820dab1c5a in __gthread_recursive_mutex_lock (__mutex=0x120) at /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:811
No locals.
#3  0x000055820dab1d72 in std::recursive_mutex::lock (this=0x120) at /usr/include/c++/9/mutex:106
        __e = 32744
#4  0x000055820dab3a4e in std::lock_guard<std::recursive_mutex>::lock_guard (this=0x7fe839ff7130, __m=...) at /usr/include/c++/9/bits/std_mutex.h:159
No locals.
#5  0x000055820dcd8972 in mediakit::FrameDispatcher::addDelegate (this=0x18, delegate=std::shared_ptr<mediakit::FrameWriterInterface> (use count 1, weak count 0) = {...}) at /opt/media/kmediasever-ms/src/Extension/Frame.h:546
        lck = {_M_device = @0x120}
#6  0x000055820dcd7216 in mediakit::FrameDispatcher::addDelegate(std::function<bool (std::shared_ptr<mediakit::Frame> const&)>) (this=0x18, cb=...) at /opt/media/kmediasever-ms/src/Extension/Frame.cpp:318
No locals.
#7  0x000055820df630d5 in mediakit::GB28181Process::inputRtp (this=0x7fe82815aaf0, data=0x7fe84c01cc00 "\200`\365\016D\370\242 \006BL\323", data_len=1396) at /opt/media/kmediasever-ms/src/Rtp/GB28181Process.cpp:152
        h264_pt = 98
        h265_pt = 99
        ps_pt = 96
        opus_pt = 100
        header = 0x7fe84c01cc00
        pt = 96
        ref = std::shared_ptr<mediakit::RtpReceiverImp> (use count 1, weak count 0) = {get() = 0x7fe820a62940}
        __FUNCTION__ = "inputRtp"
#8  0x000055820de2eba2 in mediakit::RtpProcess::inputRtp (this=0x7fe81c8bd430, is_udp=false, sock=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<toolkit::Socket> (use count 2, weak count 2) = {...}, data=0x7fe84c01cc00 "\200`\365\016D\370\242 \006BL\323", len=1396, 
    addr=0x7fe81c118c30, dts_out=0x0) at /opt/media/kmediasever-ms/src/Rtp/RtpProcess.cpp:116
        __FUNCTION__ = "inputRtp"
        header = 0x7fe84c01cc00
        dump_dir = ""
        ret = false
#9  0x000055820de5ca51 in mediakit::RtpSession::onRtpPacket (this=0x7fe81c118aa0, data=0x7fe84c01cc00 "\200`\365\016D\370\242 \006BL\323", len=1396) at /opt/media/kmediasever-ms/src/Rtp/RtpSession.cpp:134
        rtp_ssrc = 105008339
        __FUNCTION__ = "onRtpPacket"
#10 0x000055820de5bd2b in mediakit::RtpSession::onRecv (this=0x7fe81c118aa0, data=std::shared_ptr<toolkit::Buffer> (use count 2, weak count 0) = {...}) at /opt/media/kmediasever-ms/src/Rtp/RtpSession.cpp:53
No locals.
#11 0x000055820dbfb58f in toolkit::emitSessionRecv (helper=std::shared_ptr<toolkit::SessionHelper> (use count 2, weak count 2) = {...}, buf=std::shared_ptr<toolkit::Buffer> (use count 2, weak count 0) = {...})
    at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:159
No locals.
#12 0x000055820dbfd56f in toolkit::UdpServer::<lambda()>::operator()(void) const (__closure=0x7fe8341a8e00) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Network/UdpServer.cpp:342
        helper = std::shared_ptr<toolkit::SessionHelper> (use count 2, weak count 2) = {get() = 0x7fe840587970}
        cacheable_buf = std::shared_ptr<toolkit::BufferOffset<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >> (use count 2, weak count 0) = {get() = 0x7fe8341fe800}
        helper_creator = {__this = 0x5582102b1de0, __weak_self = std::weak_ptr<toolkit::UdpServer> (use count 1, weak count 6) = {get() = 0x5582102b1de0}, __socket = warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<toolkit::Socket*, toolkit::Socket::createSocket(std::shared_ptr<toolkit::EventPoller> const&, bool)::{lambda(toolkit::Socket*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<toolkit::Socket> (use count 1, weak count 1) = {
            get() = 0x7fe84c005d10}, __addr_str = "\n\000\332\310", '\000' <repeats 14 times>, "\377\377\n\377\347\221\000\000\000", __id = "\310\332\000\000\000\000\000\000\000\000\000\000\377\377\n\377\347\221", __isStunSession = false}
#13 0x000055820dbff91a in std::_Function_handler<void(), toolkit::UdpServer::createSession(const PeerIdType&, const Ptr&, sockaddr*, int, bool)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /usr/include/c++/9/bits/std_function.h:300
No locals.
#14 0x000055820dab393e in std::function<void ()>::operator()() const (this=0x7fe834002b50) at /usr/include/c++/9/bits/std_function.h:688
No locals.
#15 0x000055820dc173eb in toolkit::TaskCancelableImp<void ()>::operator()() const (this=0x7fe834c3fcb0) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Thread/TaskExecutor.h:111
        strongTask = std::shared_ptr<std::function<void()>> (use count 2, weak count 1) = {get() = 0x7fe834002b50}
#16 0x000055820dc169e0 in toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}::operator()(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&) const (
    __closure=0x7fe839ff77a8, task=std::shared_ptr<toolkit::TaskCancelableImp<void()>> (use count 1, weak count 0) = {...}) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Poller/EventPoller.cpp:259
        this = 0x5582101dd8b0
        __FUNCTION__ = "operator()"
#17 0x000055820dc17d15 in toolkit::List<std::shared_ptr<toolkit::TaskCancelableImp<void ()> > >::for_each<toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}>(toolkit::EventPoller::onPipeEvent()::{lambda(std::shared_ptr<toolkit::TaskCancelableImp<void ()> > const&)#1}&&) (this=0x7fe839ff77b0, func=...) at /opt/media/kmediasever-ms/3rdpart/ZLToolKit/src/Util/List.h:203

</pre>
</details>

### 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
运行环境：docker环境下Ubuntu 20.0 ；master分支
</pre>
</details>

### 各种环境信息

* **代码提交记录/git commit hash**:  Commit: bcf0c719f103d86d0c9c92e5b297808a76dfa1ff
Parents: 9d68b668fce86cf5174630ef88e4c894f7eab8da
Author: xiongziliang <[771730766@qq.com](mailto:771730766@qq.com)>
Committer: xiongziliang <[771730766@qq.com](mailto:771730766@qq.com)>
Date: Sat Dec 23 2023 21:32:24 GMT+0800 (中国标准时间)
* 
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
嗨 你这个代码版本很早了 建议升级最新的master分支。

zlm是滚动发布模式，不维护LTS分支，所以如果你要反馈bug，请对齐代码到比较新的版本。
