### ISSUE TITLE
[技术咨询] WebSocketClient是否支持切换opcode

### ISSUE THREAD

**Issue by liwq4ever** [ZLMediaKit/ZLMediaKit#3536]
下午好：
首先感谢您开源这么棒的项目。
我这边有个websocket客户端，需要先发送TEXT文本内容，后续使用BINARY发送媒体。想请问下如何使用WebSocketClient在连接中切换opcode呢？

**Comment by xiongguangjie** [comment]
> WebSocketClient

这个需要二开，ZLM的代码中是模板定义的，一旦声明写死了，就无法切换了

**Comment by xia-chu** [comment]
主要是为了无感把TcpClient升级为over websocket， 才这么设计的。

**Comment by xia-chu** [comment]
zlm的websocket server和client端都是通过模板 可以升级tcp协议为websocket协议

**Comment by liwq4ever** [comment]
好的，感谢您的解答。
