### ISSUE TITLE
是否有arm架构服务器的docker版本镜像或者安装包

### ISSUE THREAD

**Issue by xiaolinrui** [ZLMediaKit/ZLMediaKit#3537]
大佬们好，请问下是否有arm架构服务器的docker版本镜像或者安装包，如有能发个链接地址不，谢谢！

**Comment by xiongguangjie** [comment]
docker hub 上面就有arm的

**Comment by xiaolinrui** [comment]
大佬，我已经找到了，好像是2021年的是吗？有空可否更新一个最新版的arm docker镜像，谢谢大佬，感激涕零，双手膜拜！

**Comment by xiongguangjie** [comment]
> 大佬，我已经找到了，好像是2021年的是吗？有空可否更新一个最新版的arm docker镜像，谢谢大佬，感激涕零，双手膜拜！

https://hub.docker.com/r/zlmediakit/zlmediakit/tags
![截图_17158228266409](https://github.com/ZLMediaKit/ZLMediaKit/assets/19631632/bf459c42-b6b6-4c5b-a526-35ee2bfaca44)

**Comment by wasphin** [comment]
非 arm64 平台也可以考虑试试指定 `platform` 进行下载
```
docker pull --platform=linux/arm64 zlmediakit/zlmediakit:master
```
