### ISSUE TITLE
[技术咨询] 使用C++ API的方式二次开发 发现了rtsp播放偶发画面卡死的现象

### ISSUE THREAD

**Issue by Pi-Boss** [ZLMediaKit/ZLMediaKit#3539]
**api_test**
- 我使用C++的方式将mk库导进了我的项目里。 仿照api_test中的api_tester_h264_pusher代码写了一个H264裸流转RTSP server的程序
使用vlc播放的时候发现视频播放几秒后经常会偶发的整个画面卡住不动。大概3秒后又继续在最新画面播放。 下面视频卡住之前vlc的运行日志。麻烦指示一下大概是哪里有问题。 H264裸流是从其它网络通讯中获取，然后通过zlmedia生成为rtsp server
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/33995858/715fad30-15cc-4aa0-b322-c04b06a424b0)

**Comment by xia-chu** [comment]
你输入的时间戳有问题

**Comment by Pi-Boss** [comment]
> 你输入的时间戳有问题

请问时间戳在哪里输入？ 我参考api_test中的demo去完成的

**Comment by xia-chu** [comment]
你应该参考h264_media_server.c范例。
顺便更新下zlm代码，h264 split的代码逻辑之前有点bug
