### ISSUE TITLE
[技术咨询] 录制视频回看

### ISSUE THREAD

**Issue by BobDLA** [ZLMediaKit/ZLMediaKit#3545]
**咨询的功能模块**
视频流的mp4录制及回放点播

**咨询的具体内容和问题**
使用zlmediakit录制了一路rtsp流为mp4文件，按默认设置视频按10S分片存储，  如果想回看该路流的完整视频，
*  现在的实现，是否只支持点播分片文件？ 如果要点播该流的完整视频， 是否要用用户应用后处理把视频拼接成完整视频？
*  现在zlm部分，是否能将录制的视频生成m3u8，用于点播？

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
现在不支持合并mp4切片功能
