### ISSUE TITLE
拉流rtsp需要提供用户名密码

### ISSUE THREAD

**Issue by zb1015** [ZLMediaKit/ZLMediaKit#3547]
拉流rtsp需要提供用户名密码
可是这个用户名和密码配置文件里没有

**Comment by wasphin** [comment]
本身不做鉴权，是不是配置 hook 服务做鉴权了？如果是需要看那边是怎么要求的。

**Comment by xiongguangjie** [comment]
rtsp的url里面可以携带用户名与密码的
