### ISSUE TITLE
webrtc服务，在ubantu搭建服务器，浏览器端播放正常，在安卓手机端播放显示超时

### ISSUE THREAD

**Issue by jamlu614** [ZLMediaKit/ZLMediaKit#3550]
**咨询的功能模块**
webrtc 拉流

**咨询的具体内容和问题**
在浏览器端测试webrtc可以正常播放，在安卓端拉流，使用当前项目的webrtc player 安卓端，拉流播放视频失败，点击播放按钮后，过一段时间，服务器打印显示信息。
![微信截图_20240517153555](https://github.com/ZLMediaKit/ZLMediaKit/assets/17973814/aa3ea773-fc47-4bdd-847d-1c5d20dcd0d9)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，要求用户先star(收藏)本项目，否则会直接关闭issue

**Comment by xia-chu** [comment]
是不是zlm部署在多网卡机器上了？可以把配置文件rtc.port设置为0，rtc.tcpPort设置为8000 强制用 over tcp模式
