### ISSUE TITLE
[技术咨询]   build_docker_images.sh 编译失败

### ISSUE THREAD

**Issue by chansanya** [ZLMediaKit/ZLMediaKit#3553]
**咨询的功能模块**
系统centos7 下，使用docker自编译镜像失败

执行命令 ： sh build_docker_images.sh -t build -p x86_64  -m Release -v 1.0.0

子模块也初始化了

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/47585031/f3f72bfa-0c33-412c-9ecf-96bf6d962c2e)

**咨询的具体内容和问题**
 上述命令报错

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/47585031/423d14ee-1db5-4005-b229-0f246b750fb7)

**Comment by wasphin** [comment]
看是代理有问题，下载依赖失败了

**Comment by chansanya** [comment]
是的去掉代理地址就可以了
## 原

https://mirror.ghproxy.com/https://github.com/cisco/libsrtp/archive/v2.3.0.tar.gz
## 修改

https://github.com/cisco/libsrtp/archive/v2.3.0.tar.gz
