### ISSUE TITLE
Unsupported mpeg: 6

### ISSUE THREAD

**Issue by yedajiang44** [ZLMediaKit/ZLMediaKit#3554]
使用`g711a`的音频推送rtp流出现`Unsupported mpeg: 6`的war
>配置文件的`rtp_proxy`节点已经配置了`g711a_pt=6`

```shell
ffmpeg -re -i /data/1.mp4 -vcodec h264 -acodec pcm_alaw -ac 1 -ar 8000 -f rtp_mpegts rtp://localhost:10000
```

请问下如何正确的推送`g711a`的音频？

**Comment by xiongguangjie** [comment]
使用rtmp 或者 rtsp , rtc，srt推流都可以的，这个rtp 推流也是可以的，你这个吧ZLM的完整日志上传上来

**Comment by yedajiang44** [comment]
```log
zlmediakit  | 2024-05-20 10:37:46.829 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:fmp4://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:37:46.829 I [MediaServer] [1-event poller 2] MultiMediaSourceMuxer.cpp:561 onAllTrackReady | stream: rtp://__defaultVhost__/rtp/4002AC5B , codec info: mpeg4-generic[8000/1/16] H264[852/480/30]
zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:rtmp://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:rtsp://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:ts://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:37:46.830 T [MediaServer] [1-event poller 2] Stamp.cpp:124 revise_l | Relative stamp changed: 0 -> 120
zlmediakit  | 2024-05-20 10:37:46.846 T [MediaServer] [1-event poller 2] Stamp.cpp:124 revise_l | Relative stamp changed: 34 -> 92
zlmediakit  | 2024-05-20 10:37:46.846 T [MediaServer] [1-event poller 2] Stamp.cpp:129 revise_l | Relative stamp changed: 0 -> 8
zlmediakit  | 2024-05-20 10:37:46.849 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:hls://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:37:47.033 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
zlmediakit  | 2024-05-20 10:37:47.803 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
zlmediakit  |     Last message repeated 2 times
zlmediakit  | 2024-05-20 10:37:48.532 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
zlmediakit  |     Last message repeated 2 times
zlmediakit  | 2024-05-20 10:37:49.229 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
zlmediakit  |     Last message repeated 2 times
zlmediakit  | 2024-05-20 10:37:49.229 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
zlmediakit  |     Last message repeated 5 times
zlmediakit  | 2024-05-20 10:38:02.369 W [MediaServer] [1-stamp thread] util.cpp:385 operator() | Stamp expired is abnormal: -724
zlmediakit  | 2024-05-20 10:38:04.639 T [MediaServer] [1-event poller 2] UdpServer.cpp:302 operator() | 2-58(::1:38279) mediakit::RtpSession on err: 2(receive rtp timeout)
zlmediakit  | 2024-05-20 10:38:04.639 W [MediaServer] [1-event poller 2] RtpSession.cpp:63 onError | 2-58(::1:38279) 4002AC5B 2(receive rtp timeout)
zlmediakit  | 2024-05-20 10:38:04.640 W [MediaServer] [1-event poller 2] RtpProcess.cpp:63 ~RtpProcess | 4002AC5B(::1:38279) RTP推流器(__defaultVhost__/rtp/4002AC5B)断开,耗时(s):20
zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:hls://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:ts://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:rtsp://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:rtmp://__defaultVhost__/rtp/4002AC5B
zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:fmp4://__defaultVhost__/rtp/4002AC5B
```

**Comment by xiongguangjie** [comment]
> ```
> zlmediakit  | 2024-05-20 10:37:46.829 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:fmp4://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:37:46.829 I [MediaServer] [1-event poller 2] MultiMediaSourceMuxer.cpp:561 onAllTrackReady | stream: rtp://__defaultVhost__/rtp/4002AC5B , codec info: mpeg4-generic[8000/1/16] H264[852/480/30]
> zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:rtmp://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:rtsp://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:37:46.830 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:ts://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:37:46.830 T [MediaServer] [1-event poller 2] Stamp.cpp:124 revise_l | Relative stamp changed: 0 -> 120
> zlmediakit  | 2024-05-20 10:37:46.846 T [MediaServer] [1-event poller 2] Stamp.cpp:124 revise_l | Relative stamp changed: 34 -> 92
> zlmediakit  | 2024-05-20 10:37:46.846 T [MediaServer] [1-event poller 2] Stamp.cpp:129 revise_l | Relative stamp changed: 0 -> 8
> zlmediakit  | 2024-05-20 10:37:46.849 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注册:hls://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:37:47.033 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
> zlmediakit  | 2024-05-20 10:37:47.803 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
> zlmediakit  |     Last message repeated 2 times
> zlmediakit  | 2024-05-20 10:37:48.532 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
> zlmediakit  |     Last message repeated 2 times
> zlmediakit  | 2024-05-20 10:37:49.229 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
> zlmediakit  |     Last message repeated 2 times
> zlmediakit  | 2024-05-20 10:37:49.229 W [MediaServer] [1-event poller 2] Frame.cpp:106 getCodecByMpegId | Unsupported mpeg: 6
> zlmediakit  |     Last message repeated 5 times
> zlmediakit  | 2024-05-20 10:38:02.369 W [MediaServer] [1-stamp thread] util.cpp:385 operator() | Stamp expired is abnormal: -724
> zlmediakit  | 2024-05-20 10:38:04.639 T [MediaServer] [1-event poller 2] UdpServer.cpp:302 operator() | 2-58(::1:38279) mediakit::RtpSession on err: 2(receive rtp timeout)
> zlmediakit  | 2024-05-20 10:38:04.639 W [MediaServer] [1-event poller 2] RtpSession.cpp:63 onError | 2-58(::1:38279) 4002AC5B 2(receive rtp timeout)
> zlmediakit  | 2024-05-20 10:38:04.640 W [MediaServer] [1-event poller 2] RtpProcess.cpp:63 ~RtpProcess | 4002AC5B(::1:38279) RTP推流器(__defaultVhost__/rtp/4002AC5B)断开,耗时(s):20
> zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:hls://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:ts://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:rtsp://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:rtmp://__defaultVhost__/rtp/4002AC5B
> zlmediakit  | 2024-05-20 10:38:04.640 I [MediaServer] [1-event poller 2] MediaSource.cpp:517 emitEvent | 媒体注销:fmp4://__defaultVhost__/rtp/4002AC5B
> ```

我查了下资料，ts/ps 的容器官方标准是不支持g711 的,ffmpeg 传过来的带g711 的ts流不行的，你可以通其他协议传过来

**Comment by xia-chu** [comment]
0x06 是PSI_STREAM_PRIVATE_DATA（ Rec. ITU-T H.222.0 | ISO/IEC 13818-1 PES packets containing private data）

**Comment by yedajiang44** [comment]
@xiongguangjie @xia-chu 那请问下是不是我想办法让ffmpeg输出ps+g711就可以了？
