### ISSUE TITLE
[BUG] /index/api/startRecord 接口参数customized_path不起作用

### ISSUE THREAD

**Issue by lvhjean** [ZLMediaKit/ZLMediaKit#3579]
## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by lvhjean** [comment]
补充：
接口：/index/api/startRecord文档中描述参数：customized_path 录像保存目录；
接口执行流程成功后；
通过接口：/index/api/getMp4RecordFile 查询不到视频（customized_path 描述：自定义搜索路径，与 startRecord 方法中的 customized_path 一样，默认为配置文件的路径）；参数去除customized_path ；发现视频存储在 原默认目录；

**Comment by lvhjean** [comment]
补充：
接口：/index/api/startRecord文档中描述参数：customized_path 录像保存目录；
接口执行流程成功后；
通过接口：/index/api/getMp4RecordFile 查询不到视频（customized_path 描述：自定义搜索路径，与 startRecord 方法中的 customized_path 一样，默认为配置文件的路径）；参数去除customized_path ；发现视频存储在 原默认目录；

**Comment by lvhjean** [comment]
问题误关闭

**Comment by lvhjean** [comment]
补充：
接口：/index/api/startRecord文档中描述参数：customized_path 录像保存目录；
接口执行流程成功后；
通过接口：/index/api/getMp4RecordFile 查询不到视频（customized_path 描述：自定义搜索路径，与 startRecord 方法中的 customized_path 一样，默认为配置文件的路径）；参数去除customized_path ；发现视频存储在 原默认目录；

**Comment by xia-chu** [comment]
你不提供日志或者其他证据 这种bug反馈我们会当做是误报 不会去花时间处理的
