### ISSUE TITLE
源类型是rtp_push播放白屏

### ISSUE THREAD

**Issue by x-f-123** [ZLMediaKit/ZLMediaKit#3597]
## 现象描述

如果源类型是rtp_push,点击开始白屏了，这是什么原因，我看类型是pull就可以播放，还是说类型是rtp_push播放跟这个不一样吗，是因为是H265的吗，我看日志里面有h265打印

## 如何复现?

1.首先通过10000端口接收 UDP 推流
2.然后刷新出来流，拿到应用名和流id，放到播放地址播放，然后是白屏
3.期望正常播放

## 相关日志或截图

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/5f71a870-483a-4009-9b8e-9a570dbacd0a)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/6def0ce8-0a45-445e-9557-de6bc4b0676e)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/1bd97f10-3d64-4065-a0cb-fa08d05a1b82)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/c854d2c3-9de6-4f66-8ca5-470742b4b314)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/a111ee60-505e-40fc-a421-2be87ef72303)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/90577e94-be9a-4390-9ba2-34124d4d97c1)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!

```
</pre>
</details>

## 配置

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/f2d8a86e-92dd-4edd-b8d7-296ba8bfb268)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/c12ae8fb-6e84-4980-9c31-4826a3fd6ddc)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/6bc6eb47-fcb6-4582-ac07-3e5b39568d62)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/459b97e1-19cb-4548-8660-552c1520cf7a)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/a55f7824-cb6a-4a4a-a945-608bb1d58480)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/1747da08-85f4-47b5-9558-95e6fa47b0fa)

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
有没有可能这个视频是H265的？

**Comment by x-f-123** [comment]
> 有没有可能这个视频是H265的？ webrtc目前不支持H265, 你要体验的话可以参考 #3589

我看点播放的时候，输出的日志，这里有写H264
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/129fa1dd-3ea9-4d00-8a5a-16f6de5bdacf)
还有，这个是通过UDP通过10000传过来的时候的日志，我看有写H265，是不是传过来的就是H265的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/171546112/79335fe5-8673-4e0d-aa53-95466dee4d45)

**Comment by x-f-123** [comment]
是什么样的原因才会导致白屏呢，播放的时候我看日志也没有报错，而且我看了，视频是H264的，这个是确定的，麻烦您解答一下呢

**Comment by xia-chu** [comment]
从日志看 这个流是265的 你截图中的H264只是播放器声明为支持H264罢了
