### ISSUE TITLE
[BUG] 使用ZLMediaKit代理拉取海康视频流出现竖条状马赛克

### ISSUE THREAD

**Issue by 935077727** [ZLMediaKit/ZLMediaKit#3598]
## 现象描述

使用ZlMediaKit代理拉流海康摄像头，然后使用ffmpeg 拉取ZLMediaKit对应的视频流出现竖条状马赛克，但是使用ffmpeg直接拉取海康摄像头的源视频流是图像完整的， 请问这个是不是bug，是不是默认配置参数需要改改。

ffmpeg 拉取视频流的 命令是 ： ffmpeg -i "rtsp://****" -vf fps=1 out_%04d.jpg

竖条状马赛克：
![out_0002](https://github.com/ZLMediaKit/ZLMediaKit/assets/20065528/18aaf383-8e83-4397-b53c-241a414f38c4)

直接拉取摄像头主码流的正常图片

![out_0001](https://github.com/ZLMediaKit/ZLMediaKit/assets/20065528/41291f57-6a5f-46e0-a8da-0d2d1017b4c1)

**Comment by SignalEmit** [comment]
看这是丢包导致的  ffmpeg  rtsp 默认走的udp拉流模式换成tcp模式试试
