### ISSUE TITLE
新国标2022是否兼容

### ISSUE THREAD

**Issue by seven54** [ZLMediaKit/ZLMediaKit#3605]
## 描述该功能的用处，可以提供相关资料描述该功能
现在海康威视摄像头新固件之后，只支持国标2022

**Comment by seven54** [comment]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/37871862/3ab4f8dc-6779-46ef-9b13-186ca8eba770)

**Comment by xiongguangjie** [comment]
你接一下，看有啥问题

**Comment by seven54** [comment]
我用局域网接入2022国标是可以正常的，但是外网接入是不行的。外网接入2016标准也是没有问题的。

**Comment by xiongguangjie** [comment]
外网使用tcp 传输流

**Comment by seven54** [comment]
外网tcp传输流测试过，也没有用。

**Comment by xiongguangjie** [comment]
是国标信令问题，还是流媒体传输有问题，zlm的日志是啥？

**Comment by seven54** [comment]
zlm的日志看不出什么，没有错误。也已正常推流。怀疑是wvp这边的通信问题

**Comment by YiuTerran** [comment]
你这个支持国标2022摄像头的型号是啥？我们想写一个兼容的，找不到合适的硬件做测试

**Comment by hyxiaodili** [comment]
@seven54 你的海康摄像头型号是？我这边在做2022的适配 网上找不到2022的摄像头

**Comment by seven54** [comment]
DS-2SE4C122DZ-D/GLT

**Comment by seven54** [comment]
V5.8.0 build 231218
