### ISSUE TITLE
[BUG] offer anwser 交换失败:Assertion failed: (pos != string::npos, 解析sdp fmtp 字段失败:96), function parse, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 591.

### ISSUE THREAD

**Issue by Retrasts** [ZLMediaKit/ZLMediaKit#3616]
## 现象描述

在测试信路威提供的rtsp时，使用一下链接创建拉流后，使用webrtc进行播放时报错

## 如何复现?

1、在代理测试中创建拉流
`/index/api/addStreamProxy?secret=****&vhost=__defaultVhost__&app=live&stream=test&url=rtsp%3A%2F%2F**.***.**.***%3A554%2Fh264ESVideoTest&retry_count=-1&rtp_type=1&timeout_sec=5&enable_hls=false&enable_hls_fmp4=false&enable_mp4=false&enable_rtsp=false&enable_rtmp=true&enable_ts=false&enable_fmp4=false&hls_demand=false&rtsp_demand=false&rtmp_demand=false&ts_demand=false&fmp4_demand=false&enable_audio=false&add_mute_audio=false&mp4_max_second=10&mp4_as_player=false&auto_close=false`
2、点击WebRTC测试，选择720P分辨率
3、点击开始，报错
`offer anwser 交换失败:Assertion failed: (pos != string::npos, 解析sdp fmtp 字段失败:96), function parse, file /opt/media/ZLMediaKit/webrtc/Sdp.cpp, line 591.`

## 相关日志或截图

![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/5aaa0968-5db1-4c64-85ba-999be70077d9)
```
#详细日志粘在这里!
```
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/9e377fb5-2f0b-4766-8cae-7ea32bd3f994)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/aa21713f-0a96-4bf5-8afe-dd7c65b1869a)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/2636de97-f426-4cda-b7e3-122cc0e1e093)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/4b09bce7-39cb-42b5-bfaf-45ede13fa92b)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/319b148e-4e76-43c7-aa2d-14a3f79a961c)

## 配置

```ini
使用docker启动，未对配置进行修改
```

## 各种环境信息

基于ESXI启动的centos虚拟机
使用docker启动，
`Docker version 20.10.12, build e91ed57
`

**Comment by xiongguangjie** [comment]
更新到最新的镜像，这个代码是什么时候的，同时浏览器什么版本的，

**Comment by Retrasts** [comment]
使用的是Edge，版本号 125.0.2535.92 (正式版本) (64 位)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/d64163c8-9ed0-4e15-8ebd-627874136b17)
请问如何查看代码版本?当前使用版本是两周前使用docker拉取的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/cd6929fa-e7c0-461e-9cb0-3ac784d3a249)

**Comment by Retrasts** [comment]
> 更新到最新的镜像，这个代码是什么时候的，同时浏览器什么版本的，
使用的是Edge，版本号 125.0.2535.92 (正式版本) (64 位)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/d64163c8-9ed0-4e15-8ebd-627874136b17)
请问如何查看代码版本?当前使用版本是两周前使用docker拉取的
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/cd6929fa-e7c0-461e-9cb0-3ac784d3a249)

**Comment by xiongguangjie** [comment]
你更新到最新的ZLM试一下吧，我测试是没问题的，我使用的也是125.0.2535.92  与你的一样

**Comment by Retrasts** [comment]
> 你更新到最新的ZLM试一下吧，我测试是没问题的，我使用的也是125.0.2535.92 与你的一样
更新成最新版的依然报错
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/38feb892-b1ff-463e-893d-327bd8aa96cb)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/e8803a27-d36e-4ad5-858b-4ab9d15c774c)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/29892fc2-e7d2-42e0-8d09-7b27589c120f)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/42233877/8d6c1d68-74b8-44dd-af6a-173bedb39cd6)

**Comment by xia-chu** [comment]
你要不提供下offer sdp内容？

**Comment by SophieRoyal** [comment]
我这边也同时报这个错误。

**Comment by SophieRoyal** [comment]
<img width="1315" height="120" alt="Image" src="https://github.com/user-attachments/assets/16f450a2-03b1-4260-b57e-c4963ea7aac6" />

**Comment by SophieRoyal** [comment]
<img width="970" height="252" alt="Image" src="https://github.com/user-attachments/assets/f15fd86d-6c5d-4711-9f97-7378e7d1ce7e" />

**Comment by xia-chu** [comment]
这个流应该是265的
