### ISSUE TITLE
[BUG] 关于断言

### ISSUE THREAD

**Issue by xuandu** [ZLMediaKit/ZLMediaKit#3617]
## 现象描述
最近点播的时候，由于MP4是错误的，导致mov-stco.c内部触发assert；但是debug才可以触发assert，release就直接跳过assert了，整个程序就crash了；见assert.h;
所以 1：是否编译release的时候可以把-DNDEBUG 删除；这样assert就能触发throw；程序不会崩溃
2：为什么debug的 （#ifndef NDEBUG ）时候才走 定义成throw；但是release就直接void了？
3：看代码也有很多地方用assert，也就是release情况下都会崩溃或者异常；不太理解这样做的用意

## 相关日志或截图
![_20240612093357](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/65c84b7a-d1c2-42bf-8dae-26368b1358aa)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
你可以修改，改成debug就抛出异常，当时这么做好像就是因为media-server 库断言导致崩溃（win下面），现在又出现了跳过断言导致崩溃，你还好权衡下怎么改吧。

**Comment by xia-chu** [comment]
这个是老陈库的问题， 后面我改下asser.h文件吧 release编译不再忽略断言 或者 @xuandu 你来个pr？ 我们快速合并下，否则我只能周末改了

**Comment by xuandu** [comment]
> 你可以修改，改成debug就抛出异常，当时这么做好像就是因为media-server 库断言导致崩溃（win下面），现在又出现了跳过断言导致崩溃，你还好权衡下怎么改吧。

WIN下走断言，抛出异常，没有捕获吗？“因为media-server 库断言导致崩溃（win下面）”
那我直接把这个判断宏的地方给删除会不会有影响？
![123456](https://github.com/ZLMediaKit/ZLMediaKit/assets/18655816/3de5e711-0d52-403e-99f6-fd18891dd819)

我不急，定位到位置，知道原因就行了；只是看很多地方的断言都是release不实现的；就不知道咋好了；

**Comment by xiongguangjie** [comment]
> > 你可以修改，改成debug就抛出异常，当时这么做好像就是因为media-server 库断言导致崩溃（win下面），现在又出现了跳过断言导致崩溃，你还好权衡下怎么改吧。
> 
> WIN下走断言，抛出异常，没有捕获吗？“因为media-server 库断言导致崩溃（win下面）” 那我直接把这个判断宏的地方给删除会不会有影响？ ![123456](https://private-user-images.githubusercontent.com/18655816/338818385-3de5e711-0d52-403e-99f6-fd18891dd819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzEzNjcsIm5iZiI6MTcxODE3MTA2NywicGF0aCI6Ii8xODY1NTgxNi8zMzg4MTgzODUtM2RlNWU3MTEtMGQ1Mi00MDNlLTk5ZjYtZmQxODg5MWRkODE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA1NDQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YTgyMGU0YTFiMmI2NmE0MmQwNWQwMTgwYjM3OTcxNTYzYWYyM2JiOTJkYTczYWMxODcxNGYwYzdmNzJkNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ixizvlEbEn7Qo1lLlqh5vgNUDKvMvztb-1Br6oQvh9M)
> 
> 我不急，定位到位置，知道原因就行了；只是看很多地方的断言都是release不实现的；就不知道咋好了；

你重新编译一下吧，测试一下吧，应该没有问题，这个应该会覆盖默认的实现
