### ISSUE TITLE
[功能请求] 按需拉流功能可以无人观看时自动拉流恢复观看时自动恢复代理流

### ISSUE THREAD

**Issue by TRUSS-ME** [ZLMediaKit/ZLMediaKit#3634]
## 描述该功能的用处，可以提供相关资料描述该功能
按需拉流功能可以无人观看时自动断流, 恢复观看时自动恢复代理流
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
现有功能只是自动停止推流,但是后台一直在拉流并且生成ts文件,并没有实现真正的按需拉流的功能
## 描述你期望实现该功能的方式和最终效果
希望拉流可以自动停止和启动

**Comment by xiongguangjie** [comment]
这个通过webhook 与 restful api 可以实现的

**Comment by PioLing** [comment]
配置文件的 auto_close 改成 1 ，试下

**Comment by PioLing** [comment]
另外，在拉流代理中途意外断开，也有重连次数启动，retry_count 在配置文件 和 webhook 都有

**Comment by ruikc** [comment]
> 配置文件的 auto_close 改成 1 ，试下

这个改成1不就是自动断开不触发on_none_reader hook,#此配置置1时，此流如果无人观看，将不触发on_none_reader hook回调，#而是将直接关闭流

**Comment by TRUSS-ME** [comment]
谢谢你们的解决方案, 问题已解决!

**Comment by Lunewcome** [comment]
请问怎么解决的？

**Comment by TRUSS-ME** [comment]
> 请问怎么解决的？

通过webhook 与 restful api, 打开hook功能, 然后写接口调用就行
