### ISSUE TITLE
[功能请求] 现文件资源完全裸露,可以直接访问,建议新增基础鉴权配置

### ISSUE THREAD

**Issue by RebelTinker** [ZLMediaKit/ZLMediaKit#3636]
## 描述该功能的用处，可以提供相关资料描述该功能
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/58228765/cb9df670-c7bd-4229-8ef5-45f1c297a466)

## 描述你期望实现该功能的方式和最终效果
希望访问默认端口的时候新增认证信息

**Comment by xiongguangjie** [comment]
http.dirMenu 设置为0 可以关闭，这么放开主要是否为了方便调试

**Comment by RebelTinker** [comment]
好的
