### ISSUE TITLE
是否有计划拉流代理增加h265转h264功能?

### ISSUE THREAD

**Issue by zhangzlyuyx** [ZLMediaKit/ZLMediaKit#364]
设备视频输出为rtsp h265(降低设备存储占用)，用流媒体服务器后，输出同时为h265，但h265在android/ios/h5端的播放兼容不是很好。

**Comment by xiongziliang** [comment]
这个涉及到FFmpeg转码，你这个issue先不关闭，后续考虑做这个，但是时间未定，看情况。

**Comment by tsingeye** [comment]
srs也是基于ffmpeg来进行转码的吧

**Comment by Yordroid** [comment]
> 这个涉及到FFmpeg转码，你这个issue先不关闭，后续考虑做这个，但是时间未定，看情况。
我们也有这个需求

**Comment by ZhouMin216** [comment]
不是可以通过/index/api/addFFmpegSource接口配合配置文件参数，在拉流时进行转码输出吗？

**Comment by ZhouMin216** [comment]
> 不是可以通过/index/api/addFFmpegSource接口配合配置文件参数，在拉流时进行转码输出吗？

我可以通过/index/api/addFFmpegSource接口拉取h265的流，然后转成h264推流到其他服务器上，但是推给自己时超时了。
详见[https://github.com/xia-chu/ZLMediaKit/issues/739](url)

**Comment by xlsky0713** [comment]
我们也急需这个功能，希望大神支持

**Comment by xia-chu** [comment]
addFFmpegSource接口就能满足你自己啊

**Comment by KevinLJJ** [comment]
急需该功能。。

**Comment by xia-chu** [comment]
先用addFFmpegSource接口顶顶吧

> 急需该功能。。

**Comment by KevinLJJ** [comment]
> 先用addFFmpegSource接口顶顶吧
> 
> > 急需该功能。。

烦请是否可以提供一个H265转H264的ffmepg.cmd模板，我看默认的模板已经包含`-c:v libx264`？，非常感谢您的回复！

**Comment by xia-chu** [comment]
> > 先用addFFmpegSource接口顶顶吧
> > > 急需该功能。。
> 
> 烦请是否可以提供一个H265转H264的ffmepg.cmd模板，我看默认的模板已经包含`-c:v libx264`？，非常感谢您的回复！

默认就转264的啊

**Comment by KevinLJJ** [comment]
> > > 先用addFFmpegSource接口顶顶吧
> > > > 急需该功能。。
> > 
> > 
> > 烦请是否可以提供一个H265转H264的ffmepg.cmd模板，我看默认的模板已经包含`-c:v libx264`？，非常感谢您的回复！
> 
> 默认就转264的啊

使用默认模板后，从VLC拉hls.m3u8流十几秒后出现间断花屏，烦请问您是否有遇到过？

**Comment by xia-chu** [comment]
zlm代码版本多少

> > > > 先用addFFmpegSource接口顶顶吧
> > > > > 急需该功能。。
> > > 
> > > 
> > > 烦请是否可以提供一个H265转H264的ffmepg.cmd模板，我看默认的模板已经包含`-c:v libx264`？，非常感谢您的回复！
> > 
> > 
> > 默认就转264的啊
> 
> 使用默认模板后，从VLC拉hls.m3u8流十几秒后出现间断花屏，烦请问您是否有遇到过？

**Comment by penghd** [comment]
我们测试，服务器端ffMpeg转码一路对CPU消耗就很大，因为服务器。没。显。卡，建议不要使用。
现在WVP-GB28181-PRO使用的前端JessiBuca可以播放H.265 FLV，CPU占用还可以。ZLM的H265 m3u8，在安卓里微信链接就直接可以顺畅打开，但IOS微信还是不行。

**Comment by xia-chu** [comment]
> 我们测试，服务器端ffMpeg转码一路对CPU消耗就很大，因为服务器。没。显。卡，建议不要使用。
> 现在WVP-GB28181-PRO使用的前端JessiBuca可以播放H.265 FLV，CPU占用还可以。ZLM的H265 m3u8，在安卓里微信链接就直接可以顺畅打开，但IOS微信还是不行。

是的  ios的hls在265时，要求为fmp4切片，而不是ts切片

**Comment by wujianGit123** [comment]
> 最简单的自己从那个test player proxy 那个例子程序改一下 拉下来然后自己转一遍在push回去就可以了啊

不用这么麻烦而且push回去经过几个独立进程的隔离，很难操作，srs的拉流ingest机制使用ffmpeg独立进程来拉流就是我及其讨厌的一个地方，这样做很难对码流进行操作，而且每拉一路视频就要启动一个ffmpeg进程，这是内存的极大浪费。
这个问题我实现了一套方案，首先设计一个分流器(我自己创建的概念)，分流器我觉得很有必要添加到zlm里面，用来方便对转码和码流发送(如gb28181)等进行管理，现在zlm的做法将gb28181发流的功能耦合到MultiMediaSourceMuxer类里面，这样大大增加了代码耦合度，有了分流器可以用单例管理实例获取分流器，然后执行转码和gb28181发流操作。
回到转码的问题，我的做法是zlm底层添加转码器接口，上层根据不同应用实现转码接口。我独立了一个基于ffmpeg库的专门用于转码的服务器进程，调用ffmpeg的函数来进行转码然后封装成zlm的frame数据，用自定义的通讯协议（主要是boost的serialization）与zlm服务器通讯传输转码前后的码流，这样设计使得转码流程对于zlm来说几乎是透明的，大大降低代码耦合度。
我本想提交分流器和转码器接口的相关代码到我fork的分支供原作者审核，奈何国内github被墙clone和提交不了。

**Comment by xia-chu** [comment]
可以在gitee提交pr



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wujianGit123 ***@***.***&gt;
发送时间: 2021年12月24日 18:10
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] 是否有计划拉流代理增加h265转h264功能? (#364)





  
最简单的自己从那个test player proxy 那个例子程序改一下 拉下来然后自己转一遍在push回去就可以了啊
  
不用这么麻烦而且push回去经过几个独立进程的隔离，很难操作，srs的拉流ingest机制使用ffmpeg独立进程来拉流就是我及其讨厌的一个地方，这样做很难对码流进行操作，而且每拉一路视频就要启动一个ffmpeg进程，这是内存的极大浪费。
 这个问题我实现了一套方案，首先设计一个分流器(我自己创建的概念)，分流器我觉得很有必要添加到zlm里面，用来方便对转码和码流发送(如gb28181)等进行管理，现在zlm的做法将gb28181发流的功能耦合到MultiMediaSourceMuxer类里面，这样大大增加了代码耦合度，有了分流器可以用单例管理实例获取分流器，然后执行转码和gb28181发流操作。
 回到转码的问题，我的做法是zlm底层添加转码器接口，上层根据不同应用实现转码接口。我独立了一个基于ffmpeg库的专门用于转码的服务器进程，调用ffmpeg的函数来进行转码然后封装成zlm的frame数据，用自定义的通讯协议（主要是boost的serialization）与zlm服务器通讯传输转码前后的码流，这样设计使得转码流程对于zlm来说几乎是透明的，大大降低代码耦合度。
 我本想提交分流器和转码器接口的相关代码到我fork的分支供原作者审核，奈何国内github被墙clone和提交不了。

**Comment by xia-chu** [comment]
feature/transcode分支已经实现

**Comment by fuuhoo** [comment]
> feature/transcode分支已经实现

主分支的docker有没有这个功能

**Comment by Neon-C23** [comment]
> feature/transcode分支已经实现

请问该分支编译出来的ZLMediaServer如何使用H265转H264，是自动转的吗？没在相关配置或文档看到有关说明。

**Comment by corey1202** [comment]
只是增加了语音转码，没有实现视频的H265转H264吧，自己在MultiMediaSourceMuxer 的 onTrackReady中增加了如下转换功能， 但是没有拉流端无法正确接收流， 提示 No start code is found. 等错误， 请问如何修改呢
H265Track::Ptr pH265Track = static_pointer_cast<H265Track>(track);
        H264Track::Ptr pH264Track(new H264Track);
        pH264Track->setVideoWidth(pH265Track->getVideoWidth());
        pH264Track->setVideoHeight(pH265Track->getVideoHeight());
        pH264Track->setVideoFps(pH265Track->getVideoFps());
        pH264Track->setBitRate(pH265Track->getBitRate());
        m_pVideoDecoder.reset(new FFmpegDecoder(track));
        m_pVideoEncoder.reset(new FFmpegEncoder(pH264Track));
        m_pVideoDecoder->setOnDecode([this](const FFmpegFrame::Ptr &frame) {
            m_pVideoEncoder->inputFrame(frame, false);
        });
        m_pVideoEncoder->setOnEncode([this, pH264Track](const Frame::Ptr &frame) {
            pH264Track->inputFrame(frame);
            this->onTrackFrame(frame);
        });
        addTrack(pH264Track);

**Comment by xia-chu** [comment]
可以试用这个docker：https://hub.docker.com/r/zlmediakit/zlmediakit-pro

**Comment by corey1202** [comment]
> 可以试用这个docker：https://hub.docker.com/r/zlmediakit/zlmediakit-pro

拉不下来呢

**Comment by xia-chu** [comment]
docker pull zlmediakit/zlmediakit-pro
用vpn拉

**Comment by corey1202** [comment]
不知道理解的对不对，要实现推流用的h265, 拉流自动转成H264。按照流程， 在MultimediaSourceMuxer::onTrackReady中自己实现转码即可吧，如果是H265编码，则调用 addTrack把生成的H264 track 添加进来， 否则添加H265的track；  要么自己实现 MultimediaSourceMuxer::addTrack() 里做这一步，想请教一下

**Comment by CxistHans** [comment]
@xia-chu  请问这个功能实现了？ addStreamProxy 的时候默认进行转码？ 例如加点参数，就能实现自动转码？

**Comment by PNP-cpp** [comment]
这个功能实现了没

**Comment by PNP-cpp** [comment]
> feature/transcode分支已经实现

合到主分支没

**Comment by xia-chu** [comment]
转码有个闭源分支 可以加我微信(xiachuziyue)详聊
