### ISSUE TITLE
[编译问题] libext-codec.a文件undefined reference to `vtable for mediakit::CommonRtmpDecoder'

### ISSUE THREAD

**Issue by cleverdouble** [ZLMediaKit/ZLMediaKit#3641]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11921104/be3cef74-3eaa-424f-b4af-8e40627b4292)
我在独立编译mediaserver时，遇到libext-codec.a的调用问

## 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
libext-codec.a依赖zlmediakit主框架代码，在编译zlm时，需要开启 -Wl,-export_dynamic 选项把主程序的链接符合暴露出去。
在编译libext-codec时，要开启 -Wl,-undefined -Wl,dynamic_lookup 去摘运行加载库时从主程序查找符号

**Comment by cleverdouble** [comment]
我是想手动移植代码，编译server，既要引用libzlmediakit.a，也引用libext-codec.a，但是在编译最后一步将所有.o文件链接时，提示上述错误，目前不清楚该如何处理了

**Comment by xiongguangjie** [comment]
> 我是想手动移植代码，编译server，既要引用libzlmediakit.a，也引用libext-codec.a，但是在编译最后一步将所有.o文件链接时，提示上述错误，目前不清楚该如何处理了

使用 -Wl,--start-group   -Wl ,--end-group  这样就不会有引用依赖的问题了

**Comment by cleverdouble** [comment]
已解决，感谢！
