### ISSUE TITLE
[BUG] ZLMediakit在开启webrtc进行编译时，视频流有人观看的时候也会在无人观看时间到达时自动触发on_stream_none_reader事件

### ISSUE THREAD

**Issue by LLLLLhy127** [ZLMediaKit/ZLMediaKit#3654]
## 现象描述

ZLMediakit在开启webrtc进行编译时，视频流有人观看的时候也会在无人观看时间到达时自动触发on_stream_none_reader事件
webrtc编译指令参照github如下：
$ mkdir build
$ cd build
$ cmake .. -DENABLE_WEBRTC=true  -DOPENSSL_ROOT_DIR=/usr/local/openssl  -DOPENSSL_LIBRARIES=/usr/local/openssl/lib
$ cmake --build . --target MediaServer

在指定cmake .. -DENABLE_WEBRTC=false并make -j4进行编译时不会触发该BUG

## 如何复现?

1、ZLMediakit开启webrtc编译

2、播放视频流

3、在streamNoneReaderDelayMS时间到达后会触发on_stream_none_reader事件
## 相关日志或截图
![微信截图_20240620170241](https://github.com/ZLMediaKit/ZLMediaKit/assets/116069581/6093d643-275a-4540-a946-b3e35551c851)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

配置：centos7.6
<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

编译日期: 2024-06-20T16:22:40
代码日期: %aI
当前git分支: master
当前git hash值: 9106dde

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个问题在 d34da067 就修复了

**Comment by LLLLLhy127** [comment]
定位到了问题原因，和ZLM无关，谢谢各位大佬

**Comment by arsn2021** [comment]
怎么解决的，具体是什么问题，我这里也有这个问题，隔几秒就会重连

**Comment by LLLLLhy127** [comment]
> 怎么解决的，具体是什么问题，我这里也有这个问题，隔几秒就会重连

我这次是因为在wvp中先点播实时视频再点播的回放，实时视频触发无人观看事件后设备把回放的流也断开了，单独点播回放是不会触发这个问题的
