### ISSUE TITLE
[BUG] 摄像头重启,拉流代理丢失

### ISSUE THREAD

**Issue by orchingly** [ZLMediaKit/ZLMediaKit#3664]
## 现象描述

wvp设置拉流代理,无人观看拉流,拉流代理正常; 重启摄像头,摄像头显示在线,没有自动拉流,wvp端启用拉流代理提示地址不存在
拉流地址配置的ddns的**域名**,不是IP

## 如何复现?
6月份的版本发现拉流代理失败,必现

## 相关日志或截图
无

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置
wvp pro 2.7.2 + ZLM 7.0
**Attention**: 拉流地址配置的是域名

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你这issue没任何实质信息 没任何价值
