### ISSUE TITLE
[BUG] 调用addStreamProxy接口时报none reserved port in pool，修改配置后热重启不生效

### ISSUE THREAD

**Issue by zeawayC** [ZLMediaKit/ZLMediaKit#3667]
## 现象描述
最开始config.ini中配置的port_range=30000-30500，再调用addStreamProxy接口时报none reserved port in pool，于是修改port_range=30000-34000，然后热重启MediaServer(killall -1 MediaServer),看到日志中已经加载新的配置信息，但再次调用addStreamProxy时还是会报none reserved port in pool的错误，是port_range不支持热重启么，还有个问题新增一个拉流代理需要几个端口（源是127.0.0.1的流，目录也是127.0.0.1，是只换了个app名称）

## 如何复现?
1. 先port_range 设置一个范围小的
2. 然后调用addStreamProxy将端口占满
3. 修改port_range（比之前范围大点）
4. 热重启killall -1 MediaServer
5. 再次调用addStreamProxy
6. 期忘可以分配到新的端口，结果报none reserved port in pool

## 相关日志或截图
第一次调用接口
<img width="1769" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/49052011/7693eb79-e99c-4e24-b486-9e7792d62d26">

热重启会加载了新的配置
<img width="1144" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/49052011/f715a8c9-d3a9-44ea-9dee-84501d1927f1">

再次调用接口
<img width="1778" alt="image" src="https://github.com/ZLMediaKit/ZLMediaKit/assets/49052011/f2edd58c-def9-49d3-82bf-4f9085372aa7">

## 配置

```ini
#该范围同时限制rtsp服务器udp端口范围
port_range=30000-34000
```

</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:968f6c69c3a0c67bb1ca6fa4d9144b69410b181c
* **操作系统及版本**:BCLinux 8.2
* **硬件信息**: VM 16C32G
* **crash backtrace**:无
```
无
```
* **其他需要补充的信息**:无

**Comment by xia-chu** [comment]
port_range确实不支持热加载

**Comment by zeawayC** [comment]
> port_range确实不支持热加载

嗯，好的，知道了，希望配置文件中标注下哪些不支持热加载
