### ISSUE TITLE
[BUG] 拉取海康平台rtsp报错

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#3668]
## 现象描述

从海康平台获取到rtsp播放地址，通过拉流代理接口取流，拉流代理接口成功后，报错 解析版本不对 rtsp player退出

## 如何复现?
拉流代理海康平台rtsp流

## 相关日志或截图

抓取的包：
[抓包文件.zip](https://github.com/user-attachments/files/15982297/default.zip)

zlm报错日志
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59160162/3935a7b5-cfa5-4ed6-8ae3-04f99c028efe)

没有按照rtp格式发包好像  能帮分析看下 感谢

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你这个流有问题：
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/11495632/9126c322-49b3-43ad-873b-a07e3a559ac7)

你先确定下vlc或ffplay能播放吧

**Comment by zhang-chuanfeng** [comment]
用这个包  前面的包有点不好分析
[海康平台rtsp拉流.zip](https://github.com/user-attachments/files/15983393/rtsp.zip)

rtsp用vlc是打不开的   ffmpeg解析rtsp流也是报错

**Comment by xiongguangjie** [comment]
> 用这个包 前面的包有点不好分析 [海康平台rtsp拉流.zip](https://github.com/user-attachments/files/15983393/rtsp.zip)
> 
> rtsp用vlc是打不开的 ffmpeg解析rtsp流也是报错

那还分析啥？vlc 与ffmpeg 都打不开，就就意味着，rtsp源不是标准的，做了改动

**Comment by xia-chu** [comment]
海康这个吊毛 传的什么玩意rtp

**Comment by zhang-chuanfeng** [comment]
> 海康这个吊毛 传的什么玩意rtp

估计他这个版本比较老  我再分析看看 只能特殊处理了
