### ISSUE TITLE
RtspMediaSourceImpl与MediaSource类型转换[BUG] BUG现象描述(必填)

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#3673]
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/56460673/712da66b-c2df-41a7-b3cb-77e38305f173)

## 现象描述
RTSP服务器处理RTSP推流端的Announce方法时，会查找MediaSource是否已经存在。若存在，则会转为RtspMediaSourceImpl对象。但实际上，媒体源注册时，s_media_source_map集合中保存的并不是RtspMediaSourceImpl对象，因此MediaSource不能转为RtspMediaSourceImpl对象。并且我将注册到s_media_source_map集合中的MediaSource对象的内存值和RtspMediaSourceImpl对象的内存值打印出来之后，发现两者也并不相等。

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
你把directProxy设置为1就是了

**Comment by quxiaohui-debug** [comment]
是的，我的确关闭了直接代理模式
