### ISSUE TITLE
[BUG] 在使用webrtc播放时，页面上的分辨率设置不生效

### ISSUE THREAD

**Issue by nxsf8023** [ZLMediaKit/ZLMediaKit#3684]
## 现象描述
我使用rtsp推流到zlmediakit服务，并使用webrtc在网页端播放，我想在网页端修改分辨率，但是没有效果。

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的

**Comment by nxsf8023** [comment]
> 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的

但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同

**Comment by xiongguangjie** [comment]
> > 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的
> 
> 但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同

你设备不一样，浏览器自己判断的，不一样不是很正常，这个要去找浏览器

**Comment by nxsf8023** [comment]
> > > 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的
> > 
> > 
> > 但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同
> 
> 你设备不一样，浏览器自己判断的，不一样不是很正常，这个要去找浏览器

但是一台设备上的画面会根据浏览器的size自动适应，但是另外一台就不会

**Comment by nxsf8023** [comment]
> > > 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的
> > 
> > 
> > 但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同
> 
> 你设备不一样，浏览器自己判断的，不一样不是很正常，这个要去找浏览器

但是一台设备上的画面会根据浏览器的size自动适应，但是另外一台就不会

**Comment by nxsf8023** [comment]
> > > 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的
> > 
> > 
> > 但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同
> 
> 你设备不一样，浏览器自己判断的，不一样不是很正常，这个要去找浏览器

但是一台设备上的画面会根据浏览器的size自动适应，但是另外一台就不会

**Comment by xiongguangjie** [comment]
> > > > 这个是浏览器的锅，浏览器会根据网络情况，自动调整码率与分辨率，rtc 传进去参数只是建议值，不一定被采用的
> > > 
> > > 
> > > 但是我在不同的设备上使用同样的配置进行webrtc播放时，网页端显示的画面不同
> > 
> > 
> > 你设备不一样，浏览器自己判断的，不一样不是很正常，这个要去找浏览器
> 
> 但是一台设备上的画面会根据浏览器的size自动适应，但是另外一台就不会

你应该去找浏览器方面的问题，版本不一样，设备固件等等，我也不知道是咋回事

**Comment by xia-chu** [comment]
不对啊 rtsp推流分辨率是固定的啊 这个跟播放无关啊 带宽估算只决定webrtc推流的分辨率啊

**Comment by xiongguangjie** [comment]
看错了，我以为是rtc推流

**Comment by xiongguangjie** [comment]
播放端是无法决定推流端的分辨率的，你设置了也是白设置的

**Comment by nxsf8023** [comment]
感谢解答，我们现在决定用canvas去重新绘制画面，减小浏览器播放的带宽负载
