### ISSUE TITLE
Feature Request: SVAC code stream support

### ISSUE THREAD

**Issue by Neo-Den** [ZLMediaKit/ZLMediaKit#3686]
## Describe the purpose of this feature, and provide relevant information to describe this feature
Support for audio and video streams encoded with SVAC

## Describe how you expect to achieve this feature and the final effect
Support for receiving, forwarding, and storing SVAC-coded streams.

>## 描述该功能的用处，可以提供相关资料描述该功能
对SVAC编码的音视频流支持
## 描述你期望实现该功能的方式和最终效果
支持对SVAC码流的接收、转发、存储

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
- 1、有开源免费的svac编解码器可用吗？我怎么产生svac的码流并且用播放器验证是否正常？
- 2、业界生态对svac的支持如何？rtsp/flv/mp4/ts/ps等对svac支持吗？如果不支持，zlm接入svac的意义何在？难道转码成H264/H265?

**Comment by xia-chu** [comment]
@Neo-Den svac已经支持了 不过未开源 感兴趣的话请加我微信 xiachuziyue私聊
