### ISSUE TITLE
[BUG] zlm录制mp4时异常中断

### ISSUE THREAD

**Issue by yumb-cd** [ZLMediaKit/ZLMediaKit#3688]
## 现象描述
docker部署的zlm容器，在使用zlm的录制MP4功能时，容器运行一段时间之后异常中断

## 如何复现?
1、利用docker部署zlm容器，需要打开mp4录制功能
2、让摄像头推流到该容器，大致800路左右会出现该问题

## 相关日志或截图
![zlm](https://github.com/ZLMediaKit/ZLMediaKit/assets/174667760/949c2662-6dc9-4527-ad9f-250ad1f72008)

**Comment by xiongguangjie** [comment]
程序太老了，更新到最新的

**Comment by xia-chu** [comment]
更新下docker吧 老版本可能有些隐藏的bug 而且多个版本不好维护
