### ISSUE TITLE
[BUG] 关于播放鉴权开启导致的截图功能异常

### ISSUE THREAD

**Issue by yaoxiaojian-liuxiaojun** [ZLMediaKit/ZLMediaKit#3700]
## 现象描述

播放鉴权开启,截图触发的播放鉴权回调不携带鉴权参数,导致截图生成异常.

## 如何复现?

    1. 播放鉴权开启
    2. 通过rest接口访问截图接口

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#截图触发播放鉴权：FQ3TF8yT83wh5Wvz->rtsp://127.0.0.1:42608/rtp/13020000002000000004_13020000002000000004?
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
确实有这个问题 所以你需要在on_play hook中对截图请求鉴权放行

**Comment by yaoxiaojian-liuxiaojun** [comment]
请问如何确认 on_play hook 的请求是截图呢? 因为我没有在 on_play hook 找到对应描述
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/59216715/0de0c91c-5179-4cf9-bb00-4ea7e7daf7fa)
是最新版支持区分吗?还是需要手动调整让截图的回调携带标识.

**Comment by xia-chu** [comment]
你可以通过特殊的url参数来区分是截图还是普通播放 获取你对127.0.0.1的播放器全部放行

**Comment by yaoxiaojian-liuxiaojun** [comment]
好的,了解.非常感谢
