### ISSUE TITLE
[BUG] 使用火狐播放ws-fmp4正常，但是使用其他浏览器(谷歌/IE)时播放会出现卡顿

### ISSUE THREAD

**Issue by nxsf8023** [ZLMediaKit/ZLMediaKit#3701]
## 现象描述

我将rtsp流推到zlmediakit后，使用wsplayer在网页端播放ws-fmp4时，谷歌/IE浏览器每隔几秒就会出现卡顿，无法定位问题原因

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
播放http-fmp4流畅吗？

**Comment by nxsf8023** [comment]
> 播放http-fmp4流畅吗
也是一样的现象，火狐不卡顿，其他浏览器都会卡顿

**Comment by xiongguangjie** [comment]
感觉是含有B帧，同时时间戳没打正确

**Comment by xia-chu** [comment]
@nxsf8023 wget下载一段http-fmp4并上传上来 我们分析下

**Comment by xia-chu** [comment]
ffplay 播放正常。
用ffprobe分析发现没有B帧，时间戳貌似也没啥问题

**Comment by xia-chu** [comment]
> 29-32_189.MP4

不科学吧 这个mp4是你wget下载zlm http-fmp4生成的？

**Comment by nxsf8023** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/assets/11623202/d337196c-4e6d-4f35-a8e0-5f62d8f46a33

这是我重新下载的mp4文件

**Comment by xia-chu** [comment]
> 14-06_14.mp4 
> 这是我重新下载的mp4文件

这个文体没法播放 请zip压缩后上传 确保文件能播放

**Comment by nxsf8023** [comment]
> > 14-06_14.mp4
> > 这是我重新下载的mp4文件
> 
> 这个文体没法播放 请zip压缩后上传 确保文件能播放

放弃ws-fmp4的方案了，目前测试下来，webrtc的直播效果在jetson设备上最好
