### ISSUE TITLE
创建RTPserver的时候好像需要等很久才能链接上

### ISSUE THREAD

**Issue by IOTWord** [ZLMediaKit/ZLMediaKit#3706]
## 现象描述

我在创建rtpserver的时候，创建成功，端口也正常返回了，但是需要等很久才能创建流
## 如何复现?
创建rtp参数：secret=otQdcznMjZLGq5zdSi5L1HjQytHSwHRT&re_use_port=0&stream_id=34020000001110000001_34020000001310000001_20240710000000_20240710001000&port=0&only_audio=0&tcp_mode=0

创建的时候创建成功，但是发现只要是打印MediaSink.cpp:30 addTrack | Audio disabled, audio track ignored的时候MediaSink.cpp:162 emitAllTrackReady | All track ready use 93ms用时就很短，只要是不打印MediaSink.cpp:30 addTrack | Audio disabled, audio track ignored 用时就很长
## 相关日志或截图
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/173667589/d8ab3fe6-ea70-457e-be80-b707e9e681f6)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/173667589/1d44e41d-cd2e-4178-af4a-fed2d2993d5d)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置
两次配置用到的是一个zlm

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:
这是什么现状呢？需要怎么处理

**Comment by xiongguangjie** [comment]
这个是ps流有问题，是因为等待sps/pps 太长

**Comment by IOTWord** [comment]
> 这个是ps流有问题，是因为等待sps/pps 太长

感谢回答~有点专业，能简单点怎么解决嘛

**Comment by xia-chu** [comment]
> > 这个是ps流有问题，是因为等待sps/pps 太长
> 
> 感谢回答~有点专业，能简单点怎么解决嘛

禁用音频即可 这个应该是pmt中声明有aac 但是数据中却没有。
可以配置文件设置下dumpDir 上传下rtp文件 给我们分析下

**Comment by IOTWord** [comment]
> > > 这个是ps流有问题，是因为等待sps/pps 太长
> > 
> > 
> > 感谢回答~有点专业，能简单点怎么解决嘛
> 
> 禁用音频即可 这个应该是pmt中声明有aac 但是数据中却没有。 可以配置文件设置下dumpDir 上传下rtp文件 给我们分析下

多谢老总

**Comment by IOTWord** [comment]
> dumpDir

[34020000001110000001_34020000001310000001_1720540800_1720541400.zip](https://github.com/user-attachments/files/16158392/34020000001110000001_34020000001310000001_1720540800_1720541400.zip)
夏总这是rtp文件，看看吧啥问题

**Comment by IOTWord** [comment]
> > > 这个是ps流有问题，是因为等待sps/pps 太长
> > 
> > 
> > 感谢回答~有点专业，能简单点怎么解决嘛
> 
> 禁用音频即可 这个应该是pmt中声明有aac 但是数据中却没有。 可以配置文件设置下dumpDir 上传下rtp文件 给我们分析下

[34020000001110000001_34020000001310000001_1720540800_1720541400.zip](https://github.com/user-attachments/files/16158406/34020000001110000001_34020000001310000001_1720540800_1720541400.zip)

夏总这是rtp文件，看看吧啥问题

**Comment by xia-chu** [comment]
这个流声明有aac 但是却实际没有

**Comment by IOTWord** [comment]
> 这个流声明有aac 但是却实际没有

我从哪里关闭这个acc呢？或者这个acc是我在哪里开启的呢

**Comment by xiongguangjie** [comment]
> > 这个流声明有aac 但是却实际没有
> 
> 我从哪里关闭这个acc呢？或者这个acc是我在哪里开启的呢

配置文件有个 protocol.enable_audio 设置为0

**Comment by IOTWord** [comment]
> enable_audio

我两次都是用的同一个两次配置用到的是一个zlm 配置。为啥有的可以有的不可以呢

**Comment by xiongguangjie** [comment]
> > enable_audio
> 
> 我两次都是用的同一个两次配置用到的是一个zlm 配置。为啥有的可以有的不可以呢
贴出日志，我现在只看到一种情况

**Comment by IOTWord** [comment]
> > > enable_audio
> > 
> > 
> > 我两次都是用的同一个两次配置用到的是一个zlm 配置。为啥有的可以有的不可以呢
> > 贴出日志，我现在只看到一种情况

谢谢您 解决了
