### ISSUE TITLE
在on_publish里面有个auto_close，我根据文档设置为false，但是流还是自动关闭了

### ISSUE THREAD

**Issue by IOTWord** [ZLMediaKit/ZLMediaKit#3709]
## 现象描述
在on_publish里面有个auto_close，我根据文档设置为false，但是流还是自动关闭了，不知道是不是我理解的不对
我有on_stream_none_reader事件实现了
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/173667589/b44966d3-31be-4f47-8f62-1cf5924aa690)

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置
streamNoneReaderDelayMS=10000

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
你的hook的返回结果针对单个流 会覆盖配置文件的值

**Comment by IOTWord** [comment]
> on_publish里面有个auto_close

hook中的on_publish里面有个auto_close我看注释说是不触发hook嘛，不管auto_close是true还是false都走hook呢

**Comment by xiongguangjie** [comment]
> > on_publish里面有个auto_close
> 
> hook中的on_publish里面有个auto_close我看注释说是不触发hook嘛，不管auto_close是true还是false都走hook呢

意思是说，无人观看只会调用一次（如果auto_close 设置为false，如果有人观看，然后无人看了，又会触发），不会多次调用，你把auto_close 设置为true就会自动注销这个流

**Comment by IOTWord** [comment]
> 如果有人观看，然后无人看了，又会触发），不会多次调用

感谢回答：您看我这样理解对不对，当on_publish鉴权接口也就说这个流一开始还没鉴权，所以开始流是无人观看的，鉴权中设置auto_close值是false的时候，鉴权通过后会从有人观看到无人观看调用一次无人观看on_stream_none_reader这个hook，如果这个on_stream_none_readerhook返回关闭那就流关闭，流关闭后，在打开流，在走on_publish鉴权，怎么感觉我这样理解on_publish鉴权的auto_close这个值是没用的呢？

**Comment by xia-chu** [comment]
auto_close设置为1 就会在无人观看时直接关闭流(不会触发on_none_reader hook),
如果设置为0，那么会触发on_none_reader hook，你在这个hook中响应是否close

**Comment by IOTWord** [comment]
> auto_close设置为1 就会在无人观看时直接关闭流(不会触发on_none_reader hook), 如果设置为0，那么会触发on_none_reader hook，你在这个hook中响应是否close

感谢
