### ISSUE TITLE
[BUG] 国标推流一直打印 ”Already existed a same track“

### ISSUE THREAD

**Issue by zhang-chuanfeng** [ZLMediaKit/ZLMediaKit#3712]
## 现象描述

国标推流正常后，发现日志一直打印 ”Already existed a same track“。发现 #3689 引入的

## 如何复现?
国标RTP推流，查看日志记录

## 相关日志或截图

![image](https://github.com/user-attachments/assets/73e5297e-b51f-4890-896f-14e274cd2024)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个可能是更新第三方库引入的问题，请参考这个issue #3702 打上补丁 就没这个问题了。

**Comment by PioLing** [comment]
![微信截图_20240712135549](https://github.com/user-attachments/assets/72049e05-d2dd-418a-8fa6-b2f1dcf5ef95)
和这个 “All track ready use” 两次有关联吗

**Comment by zhang-chuanfeng** [comment]
> 这个可能是更新第三方库引入的问题，请参考这个issue #3702 打上补丁 就没这个问题了。

已提交pr
https://github.com/ZLMediaKit/ZLMediaKit/pull/3713
