### ISSUE TITLE
rtsp推流 webrtc 播放不响应

### ISSUE THREAD

**Issue by wuwenjie007** [ZLMediaKit/ZLMediaKit#3718]
## 现象描述
使用rtsp推流 webrtc 播放不响应

## 如何复现?
首先 使用推流命令
ffmpeg -re -i \ZLMediaKit\vedio\22.mp4" -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/record/test
然后使用播放url
http://192.168.1.18:8000/index/api/webrtc?app=record&stream=test&type=play
结果播放器没有响应。

## 相关日志或截图
<img width="850" alt="1721015356414" src="https://github.com/user-attachments/assets/4adcf6cb-d0c8-49bf-9b88-e54f1ee7f0db">

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置
配置的日志如下：
[conifg.txt](https://github.com/user-attachments/files/16229871/conifg.txt)

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息
采用的Windows 11

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by PioLing** [comment]
webrtc 不支持aac

**Comment by xiongguangjie** [comment]
看wiki的rtc 相关的解答，要么是rtc.external_ip 或者就算rtsp.directproxy 配置不正确

**Comment by wuwenjie007** [comment]
> 看wiki的rtc 相关的解答，要么是rtc.external_ip 或者就是rtsp.directproxy 配置不正确

external_ip  这个没有配置，directproxy 已经配置为0了

**Comment by wuwenjie007** [comment]
> webrtc 不支持aac

那应该配置成什么格式的

**Comment by PioLing** [comment]
> > webrtc 不支持aac
> 
> 那应该配置成什么格式的

ffmpeg -stream_loop -1 -re -i ./ZLMediaKit/vedio/22.mp4 -vcodec copy -acodec libopus  -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/record/test
