### ISSUE TITLE
[BUG] rtsp流代理,在网页播放器播放hls.m3u8链接黑屏只有进度条在动,但是使用PotPlayer等PC播放器能正常播放

### ISSUE THREAD

**Issue by TRUSS-ME** [ZLMediaKit/ZLMediaKit#3722]
## 现象描述

rtsp流代理,在网页播放器播放hls.m3u8链接黑屏,只有进度条在动,但是使用PotPlayer等PC播放器能正常播放,前端使用video.js和hls.js无法正常播放画面
## 如何复现?

1.使用addStreamProxy接口添加rtsp推流
2.使用PotPlayer播放,正常播放
3.使用video.js,播放黑屏进度条在动
4.使用hls.js,播放白屏,进度条在动
5.点击网络请求中的ts文件,跳转播放器播放,能正常播放
6.m3u8文件内容截图,默认的hls最大切片时间segDur=2,segNum=3,也是如此

## 相关日志或截图
![image](https://github.com/user-attachments/assets/b22090a8-eb94-4544-b8e8-fb3cc0524050)
![image](https://github.com/user-attachments/assets/15cdcfd5-c8f4-4286-aaca-092863709190)
![image](https://github.com/user-attachments/assets/75f2c6b9-6cc9-4163-9e9a-4810915b2e21)
![image](https://github.com/user-attachments/assets/ac66fdb4-30a8-4535-b0bd-9260b99e71d3)
![image](https://github.com/user-attachments/assets/43b38049-1b00-4728-82db-ab59f6e3a4df)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
downloadRoot=./www
secret=L66GZfDu2CcLMyMiNcLF5dO0bJnjwIld
snapRoot=./www/snap/
cors_origin = *

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -frames:v 1 -an %s

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=2
segRetain=5

[hook]
alive_interval=10.0
enable=0
on_flow_report=
on_http_access=
on_play=
on_publish=
on_record_mp4=
on_record_ts=
on_rtp_server_timeout=
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=
on_server_exited=
on_server_keepalive=
on_server_started=
on_shell_login=
on_stream_changed=
on_stream_none_reader=
on_stream_not_found=
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=10

[http]
allow_cross_domains=1
allow_ip_range=
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:d735aa1/2024-07-14T09:32:41+08:00,branch:master,build time:2024-07-15T06:43:27)</center></body></html>
port=80
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=15000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=1
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
maxNackMS=5000
max_bitrate=0
min_bitrate=0
nackIntervalRatio=1.0
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
rtpCacheCheckInterval=100
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=0
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---
</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

ubuntu 20.04 AMD64
ZLMediaKit 当前版本最新

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**: 谢谢解答

**Comment by xiongguangjie** [comment]
应该浏览器对于视频或者音频不支持

**Comment by TRUSS-ME** [comment]
> 应该浏览器对于视频或者音频不支持

使用edge和google都不能正常播放, 但是用这两个js播放别的m3u8文件,比如https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8,这个就能正常播放, 想问这种rtsp转hls直播流,在网页应该怎么播放呢?

**Comment by xiongguangjie** [comment]
> > 应该浏览器对于视频或者音频不支持
> 
> 使用edge和google都不能正常播放, 但是用这两个js播放别的m3u8文件,比如[https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8,这个就能正常播放](https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8,%E8%BF%99%E4%B8%AA%E5%B0%B1%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%92%AD%E6%94%BE), 想问这种rtsp转hls直播流,在网页应该怎么播放呢?

要看rtsp流的 音视频编码格式，是否支持；你给的这个hls地址，是多分辨率的流，不是zlm；通常的解决办法是要么在服务器端转码，要么你自己二开hls.js 播放器，没有其他太好的解决方法

**Comment by TRUSS-ME** [comment]
> > > 应该浏览器对于视频或者音频不支持
> > 
> > 
> > 使用edge和google都不能正常播放, 但是用这两个js播放别的m3u8文件,比如[https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8,这个就能正常播放](https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8,%E8%BF%99%E4%B8%AA%E5%B0%B1%E8%83%BD%E6%AD%A3%E5%B8%B8%E6%92%AD%E6%94%BE), 想问这种rtsp转hls直播流,在网页应该怎么播放呢?
> 
> 要看rtsp流的 音视频编码格式，是否支持；你给的这个hls地址，是多分辨率的流，不是zlm；通常的解决办法是要么在服务器端转码，要么你自己二开hls.js 播放器，没有其他太好的解决方法
视频属性是这样的
![image](https://github.com/user-attachments/assets/01427c40-40bd-4ec5-b2ed-d2076f811b0c)

**Comment by xiongguangjie** [comment]
> 这个

你这个是h265，要么服务器转码，要么使用支持h264的web播放器如jessbuca 之类的

**Comment by TRUSS-ME** [comment]
> > 这个
> 
> 你这个是h265，要么服务器转码，要么使用支持h264的web播放器如jessbuca 之类的

jessbuca也播放不了,我能发给你视频流给您测试一下吗
https://jkjc.yciccloud.com:8008/live/ym_honghe_kunming/hls.m3u8

**Comment by xiongguangjie** [comment]
> > > 这个
> > 
> > 
> > 你这个是h265，要么服务器转码，要么使用支持h264的web播放器如jessbuca 之类的
> 
> jessbuca也播放不了,我能发给你视频流给您测试一下吗 https://jkjc.yciccloud.com:8008/live/ym_honghe_kunming/hls.m3u8

jessbuca 播放flv流，不要使用hls 播放

**Comment by TRUSS-ME** [comment]
> > > > 这个
> > > 
> > > 
> > > 你这个是h265，要么服务器转码，要么使用支持h264的web播放器如jessbuca 之类的
> > 
> > 
> > jessbuca也播放不了,我能发给你视频流给您测试一下吗 https://jkjc.yciccloud.com:8008/live/ym_honghe_kunming/hls.m3u8
> 
> jessbuca 播放flv流，不要使用hls 播放

好的, 现在使用jessbuca pro版可以播放了,太感谢了!
