### ISSUE TITLE
[BUG] 使用startSendRtp接口来创建流报错

### ISSUE THREAD

**Issue by ruikc** [ZLMediaKit/ZLMediaKit#3728]
## 现象描述
![image](https://github.com/user-attachments/assets/f25f6b1b-8500-45db-a46d-62b271ff0fbf)

## 如何复现?
使用get请求，添加上需要的参数，通过链接访问有报错
![image](https://github.com/user-attachments/assets/f25f6b1b-8500-45db-a46d-62b271ff0fbf)

## 相关日志或截图
![image](https://github.com/user-attachments/assets/f25f6b1b-8500-45db-a46d-62b271ff0fbf)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:macos
* **硬件信息**: m2 bookpro
* **crash backtrace**: 
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
少了必填参数呀
