### ISSUE TITLE
zlm性能测试只能是 800M

### ISSUE THREAD

**Issue by ralax123** [ZLMediaKit/ZLMediaKit#3735]
本地的cpu是16核,
内存是126G,
网卡是10G
 部署zml,模拟1000个客户端推送流, zml只能处理 800M左右
![image](https://github.com/user-attachments/assets/449306ea-7e19-492a-b895-967ae5efca1a)
![image](https://github.com/user-attachments/assets/a3cbe13c-32df-4630-a075-b88cfd7eac77)
![image](https://github.com/user-attachments/assets/dc8cba31-f674-47aa-87d4-aaeddb4f5c05)
cpu才用两个核,还有14核没用到
![image](https://github.com/user-attachments/assets/817cc992-6665-42a5-b517-3db81d4587b0)

**Comment by xia-chu** [comment]
你是不是开了hls录制？
