### ISSUE TITLE
[功能请求] MP4录制能否支持一个将H265转码成H264

### ISSUE THREAD

**Issue by 457775987** [ZLMediaKit/ZLMediaKit#3738]
## 描述该功能的用处，可以提供相关资料描述该功能

类似ffmpeg.cmd可以自定义命令，比如我想将实时码流H265转成H264

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷

现在很多播放器对H265格式的MP4都播不出来，导致需要很多工作去兼容，有些播放器能兼容H265，但是没有倍速，找到有倍速效果还不错的，又不能支持播H265的MP4，比如西瓜播放器对云存储MP4有很好的点播效果，还能合并多个MP4组合播，解决了云存储片段合并播放问题，但是不支持H265的MP4

## 描述你期望实现该功能的方式和最终效果
能够自定义录制命令，或者录制接口增加一个参数转码成普通的MP4格式

**Comment by xia-chu** [comment]
这个有闭源分支实现 如果有购买意愿 可以联系我邮箱 1213642868@qq.com
