### ISSUE TITLE
[BUG] 拉流端创建的解码线程优先级太低，解码任务得不到调度，导致视频画面卡顿

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#3743]
## 现象描述
在性能好的机器上这个问题不明显，但在性能差一点的机器上，这个问题就很容易出现。后来我把解码线程的优先级调到最高，就不会出现这个问题

## 相关日志或截图
![image](https://github.com/user-attachments/assets/e3f7438c-af6f-45bf-86bf-71b1bc565a37)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
应该不是这个问题 你如果要用到编解码 应该关闭cpu亲和性 这个有传染性

**Comment by quxiaohui-debug** [comment]
哦哦哦，我试试

**Comment by quxiaohui-debug** [comment]
关闭亲和性后，的确没有出现视频卡顿的问题了，感谢作者的答复 。
