### ISSUE TITLE
使用rtp/rtsp/rtmp推流的时候传参数   "params" : "token=1677193e-1244-49f2-8868-13b3fcc31b17&pusApp=live"发现pusApp参数获取不到，只能获取到token,还有就是rtp推流参数一个也获取不到

### ISSUE THREAD

**Issue by IOTWord** [ZLMediaKit/ZLMediaKit#3745]
rtp推流指令
ffmpeg -re -i "F:\aaa\test.mp4" -vcodec h264 -acodec aac -f rtp_mpegts rtp://127.0.0.1:10000?pushKey=66666666
on_push收到参数
![image](https://github.com/user-attachments/assets/79c7b1e8-1112-4ae9-a2ed-4beba3e44e52)

rtsp/rtmp推流指令
ffmpeg -re  -stream_loop -1 -i "F:\aaa\test.mp4" -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/rtp/test666?pushKey=66666666&pusApp=live
on_push收到参数
![image](https://github.com/user-attachments/assets/0acb6282-3782-4d6d-baae-180eb94062fc)

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
rtp 没有办法获取参数的，rtsp/rtmp/rtc/srt 才能获取到，因为协议的限制

**Comment by IOTWord** [comment]
> rtp 没有办法获取参数的，rtsp/rtmp/rtc/srt 才能获取到，因为协议的限制

多谢回答，请问参数只能获取到一个吗？token=1677193e-1244-49f2-8868-13b3fcc31b17&pusApp=live

**Comment by xia-chu** [comment]
改成命令：
ffmpeg -re -stream_loop -1 -i "F:\aaa\test.mp4" -vcodec copy -acodec copy -f flv -y “rtmp://127.0.0.1/rtp/test666?pushKey=66666666&pusApp=live"

**Comment by IOTWord** [comment]
> 改成命令： ffmpeg -re -stream_loop -1 -i "F:\aaa\test.mp4" -vcodec copy -acodec copy -f flv -y “rtmp://127.0.0.1/rtp/test666?pushKey=66666666&pusApp=live"

多谢夏总

**Comment by IOTWord** [comment]
> 改成命令： ffmpeg -re -stream_loop -1 -i "F:\aaa\test.mp4" -vcodec copy -acodec copy -f flv -y “rtmp://127.0.0.1/rtp/test666?pushKey=66666666&pusApp=live"

【问题请教】我现在在做推流这一块，但是发现推流后流产生，不知道这个流是设备流还是推出来的流？如何判定了
