### ISSUE TITLE
[编译问题] docker拉取镜像失败

### ISSUE THREAD

**Issue by qingtongsheng** [ZLMediaKit/ZLMediaKit#3746]
## 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

## 情况
使用docker 拉取镜像失败
## 使用命令
docker pull zlmediakit/zlmediakit:master
## 效果
![image](https://github.com/user-attachments/assets/55f3c119-94f7-4135-9b22-474b6f84f3d3)
请问下, 我这里是哪里出错了吗, 之前也拉取过镜像的,最近拉取就不行了

**Comment by xiongguangjie** [comment]
docker 镜像不是最近被封了吗，需要你翻墙去拉取

**Comment by xia-chu** [comment]
兄嘚 搞个vpn吧

**Comment by qingtongsheng** [comment]
好的, 谢谢指点
