### ISSUE TITLE
[BUG] 请求流媒体流列表API报错

### ISSUE THREAD

**Issue by yumb-cd** [ZLMediaKit/ZLMediaKit#3754]
## 现象描述

使用最新代码编译部署之后，访问流媒体获取流列表API（/index/api/getMediaList）报错

## 如何复现?

1、Linux CentOs7系统获取最新代码，并进行编译；
2、启动编译后的程序，并访问获取流列表API（/index/api/getMediaList），请求参数是：secret=xxx&schema=rtmp
3、期望返回流列表数据，结果返回如下信息：
{
    "code": -400,
    "msg": "mediakit::RtmpMediaSourceMuxer::totalReaderCount not implemented"
}

## 相关日志或截图
![zlm](https://github.com/user-attachments/assets/189b2dc8-94c0-4726-a15a-a41612cd6a6a)

## 配置
<details>
<summary>展开查看详细配置</summary>
<pre>

[api]
apiDebug=1
secret=xxx
snapRoot=/sambadata/www/snap/
defaultSnap=/sambadata/www/logo.png
downloadRoot=/sambadata/www

[ffmpeg]
bin=/usr/local/ffmpeg/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
snap=%s -i %s -y -f mjpeg -frames:v 1 -an %s
log=/sambadata/www/ffmpeg/ffmpeg.log
restart_sec=0

[protocol]
modify_stamp=2
enable_audio=1
add_mute_audio=1
auto_close=0
continue_push_ms=3000
paced_sender_ms=0
enable_hls=0
enable_hls_fmp4=0
enable_mp4=1
enable_rtsp=0
enable_rtmp=1
enable_ts=0
enable_fmp4=0

mp4_as_player=1
mp4_max_second=600
mp4_save_path=/sambadata/www
hls_save_path=/sambadata/www

hls_demand=0
rtsp_demand=0
rtmp_demand=0
ts_demand=0
fmp4_demand=0

[general]
enableVhost=0
flowThreshold=
maxStreamWaitMS=15000
streamNoneReaderDelayMS=600000
resetWhenRePlay=1
mergeWriteMS=0
mediaServerId=gfs_record_253_13
wait_track_ready_ms=10000
wait_add_track_ms=3000
unready_frame_cache=100
broadcast_player_count_changed=0

[hls]
fileBufSize=65536
segDur=600
segNum=1
segDelay=0
segRetain=1
broadcastRecordTs=0
deleteDelaySec=10
segKeep=0
fastRegister=1

[hook]
enable=1
on_flow_report=
on_http_access=
on_play=xxx/index/hook/on_play
on_publish=xxx/index/hook/on_publish
on_record_mp4=
on_record_ts=
on_rtsp_auth=
on_rtsp_realm=
on_shell_login=xxx/index/hook/on_shell_login
on_stream_changed=xxx/index/hook/on_stream_changed
stream_changed_schemas=rtmp
on_stream_none_reader=xxx/index/hook/on_stream_none_reader
on_stream_not_found=xxx/index/hook/on_stream_not_found
on_server_started=xxx/index/hook/on_server_started
on_server_exited=
on_server_keepalive=xxx/index/hook/on_server_keepalive
on_send_rtp_stopped=
on_rtp_server_timeout=

timeoutSec=60
alive_interval=5
retry=1
retry_delay=3

[cluster]
origin_url=
timeout_sec=15
retry_count=3

[http]
charSet=utf-8
keepAliveSecond=60
maxReqSize=40960
port=9120
rootPath=/sambadata/www
sendBufSize=65536
sslport=9121
dirMenu=0
virtualPath=
forbidCacheSuffix=
forwarded_ip_header=
allow_cross_domains=1
allow_ip_range=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[record]
appName=record
fileBufSize=65536
sampleMS=500
fastStart=0
fileRepeat=0
enableFmp4=0

[rtc]
timeoutSec=15
externIP=xx.xx.xx.xx
port=9122
tcpPort=9123
rembBitRate=0
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8

start_bitrate=0
max_bitrate=0
min_bitrate=0
maxRtpCacheMS=5000
maxRtpCacheSize=2048

nackMaxSize=2048
nackMaxMS=3000
nackMaxCount=15
nackIntervalRatio=1.0
nackRtpSize=8

[rtmp]
handshakeSecond=15
keepAliveSecond=15
port=9124
sslport=9125
directProxy=1
enhanced=0

[rtp]
audioMtuSize=600
videoMtuSize=1400
rtpMaxSize=10
lowLatency=0
h264_stap_a=1

[rtp_proxy]
dumpDir=
port=9126
timeoutSec=15
port_range=
h264_pt=98
h265_pt=99
ps_pt=96
opus_pt=100
gop_cache=1
rtp_g711_dur_ms = 100
udp_recv_socket_buffer=4194304

[srt]
timeoutSec=5
port=9127
latencyMul=4
pktBufSize=8192

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
port=9128
sslport=9129
lowLatency=0
rtpTransportType=-1

[shell]
maxReqSize=1024
port=
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这个不对吧，我等着没法复现，你是不是改过代码呀？

**Comment by xiongguangjie** [comment]
> 这个不对吧，我这边没法复现，你是不是改过代码呀？

**Comment by xia-chu** [comment]
走到这个逻辑了：
![image](https://github.com/user-attachments/assets/f946aaf6-9b3a-453a-8c09-2b6083e32531)

**Comment by PioLing** [comment]
> 走到这个逻辑了： ![image](https://private-user-images.githubusercontent.com/11495632/351569730-f946aaf6-9b3a-453a-8c09-2b6083e32531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDAxNTUsIm5iZiI6MTcyMTc5OTg1NSwicGF0aCI6Ii8xMTQ5NTYzMi8zNTE1Njk3MzAtZjk0NmFhZjYtOWIzYS00NTNhLThjMDktMmI2MDgzZTMyNTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDA1NDQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkYmVlNzViNzRiNjA1YzMyYWM1ZjE0NDcwZWQwZjU4YTA1MmQ3MjYzYjJiOWMxNDk3N2UwMmIwNjZkMGFjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CqRLP5PeegUGHh3saLY6DwW_ZyYgSSH1kNfqplvBjtA)

#3622 ,#3620

**Comment by yumb-cd** [comment]
这个问题不是必现的，我在linux服务器上启动了两个zlm，等待设备wvp的设备推流。
然后去访问流媒体的接口，有时候是正常返回，有时候是报错
{
"code": -400,
"msg": "mediakit::RtmpMediaSourceMuxer::totalReaderCount not implemented"
}

**Comment by xia-chu** [comment]
看情况 如果没来得及设置listener就可能会触发这个问题 不过临界区很小

**Comment by xia-chu** [comment]
仔细分析下 应该是源listener已经销毁了 但是MediaSource还没注销导致的 这个应该是continue_push_ms这个配置导致的

**Comment by xia-chu** [comment]
也很难所 RtmpMediaSourceMuxer和RtmpMediaSource都还没销毁 但是对应的MultiMediaSourceMuxer却销毁了。
这个应该发生在MultiMediaSourceMuxer正在析构 但是这个时候正好调用了getMediaList导致的

**Comment by xia-chu** [comment]
反正这个非常靠运气才能触发到

**Comment by xia-chu** [comment]
我这里修改下代码能复现了：
![image](https://github.com/user-attachments/assets/f1005d27-e8e2-46a0-bf0e-193d5db23a07)

**Comment by xia-chu** [comment]
总而言之 这个情况非常特殊 很难触发， 如果MultiMediaSourceMuxer正在虚构，这个时候异味着马上注销媒体，确实很多信息获取不到也没意义。
