### ISSUE TITLE
[BUG] on_stream_changed 回调中的媒体信息不正确

### ISSUE THREAD

**Issue by huangjunAAAA** [ZLMediaKit/ZLMediaKit#3756]
## 现象描述

on_stream_changed 回调中的媒体信息不正确
codecId 一直是0， codecIdName 一直是空

## 如何复现?

通过国标发起播放 海康/华为 的摄像头时一直是这样，方式为tcp/passive
信息系统采用的是wvp
版本是从dockerhub拉取的master版本，日期是20221205

## 相关日志或截图

![image](https://github.com/user-attachments/assets/a7b07372-6020-4bd6-90f3-c90651750ef4)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
[34m2024-07-24 10:10:11.258 T MediaServer[8-event poller 3] HttpSession.cpp:27 HttpSession | 1506-3(192.168.4.56:49216) [0m
[32m2024-07-24 10:10:11.258 D MediaServer[8-event poller 3] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getRtpInfo
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 95
Content-Type : application/x-www-form-urlencoded
Host : 192.168.4.56:8081
User-Agent : okhttp/3.14.9
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=65010600002000100001_65010611581314000005
# response:
{
	"code" : 0,
	"exist" : false
}

[0m
[36m2024-07-24 10:10:11.261 I MediaServer[8-event poller 3] Rtsp.cpp:392 getPortPair | got port from pool:31450-31451[0m
[36m2024-07-24 10:10:11.261 I MediaServer[8-event poller 3] TcpServer.cpp:200 start_l | TCP server listening on [::]: 31450[0m
[32m2024-07-24 10:10:11.261 D MediaServer[8-event poller 3] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/openRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 122
Content-Type : application/x-www-form-urlencoded
Host : 192.168.4.56:8081
User-Agent : okhttp/3.14.9
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=65010600002000100001_65010611581314000005&port=0&ssrc=0&enable_tcp=1
# response:
{
	"code" : 0,
	"port" : 31450
}

[0m
[32m2024-07-24 10:10:11.754 D MediaServer[8-event poller 3] RtpSession.cpp:32 RtpSession | 1507-31(124.117.253.46:2048) [0m
[33m2024-07-24 10:10:11.757 W MediaServer[8-event poller 3] GB28181Process.cpp:123 inputRtp | rtp payload type未识别(40),已按ts或ps负载处理[0m
[32m2024-07-24 10:10:11.765 D MediaServer[8-event poller 3] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/getMediaList
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 123
Content-Type : application/x-www-form-urlencoded
Host : 192.168.4.56:8081
User-Agent : okhttp/3.14.9
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&app=rtp&vhost=__defaultVhost__&stream=65010600002000100001_65010611581314000005
# response:
{
	"code" : 0
}

[0m
[36m2024-07-24 10:10:11.771 I MediaServer[8-event poller 3] RtpProcess.cpp:252 operator() | 65010600002000100001_65010611581314000005(124.117.253.46:2048) 允许RTP推流[0m
[36m2024-07-24 10:10:11.873 I MediaServer[8-event poller 3] GB28181Process.cpp:171 onRtpDecode | 65010600002000100001_65010611581314000005 judged to be PS[0m
[36m2024-07-24 10:10:11.873 I MediaServer[8-event poller 3] Decoder.cpp:240 onTrack | got track: H264[0m
[33m2024-07-24 10:10:11.873 W MediaServer[8-event poller 3] Decoder.cpp:151 onStream | unsupported codec type:unknown codec 189[0m
[36m2024-07-24 10:10:11.873 I MediaServer[8-event poller 3] Decoder.cpp:159 onStream | add track finished[0m
[32m2024-07-24 10:10:12.179 D MediaServer[8-event poller 3] MediaSink.cpp:137 emitAllTrackReady | all track ready use 306ms[0m
[36m2024-07-24 10:10:12.180 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注册:fmp4://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:10:12.180 I MediaServer[8-event poller 3] MultiMediaSourceMuxer.cpp:362 onAllTrackReady | stream: rtp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005 , codec info: H264[1920/1080/25] [0m
[36m2024-07-24 10:10:12.181 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注册:rtsp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:10:12.181 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注册:rtmp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:10:12.182 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注册:ts://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:10:12.203 I MediaServer[8-work poller 3] Process.cpp:178 run | start child process 391, log file:/opt/media/bin/ffmpeg/ffmpeg.log.391[0m
[36m2024-07-24 10:10:12.305 I MediaServer[8-work poller 3] Process.cpp:230 s_wait | process terminated, pid=391, exit code=1[0m
[32m2024-07-24 10:10:12.305 D MediaServer[8-work poller 3] WebApi.cpp:250 http api debug | 
# request:
GET /index/api/getSnap?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&expire_sec=1&url=http%3A%2F%2F127.0.0.1%3A8081%2Frtp%2F65010600002000100001_65010611581314000005.live.flv&timeout_sec=15
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Host : 192.168.4.56:8081
User-Agent : okhttp/3.14.9
# content:

# response:

#### pid=391,cmd=/usr/bin/ffmpeg -i http://127.0.0.1:8081/rtp/28181001315000005000_00871486411315130682.live.flv -y -f mjpeg -t 0.001 /opt/media/bin/www/snap/6765374450a2c8ae6661d1f5d03d314b/1701064319.jpeg.tmp #####

ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[tcp @ 0x55c2347e2820] Connection to tcp://127.0.0.1:8081 failed: Connection refused
http://127.0.0.1:8081/rtp/28181001315000005000_00871486411315130682.live.flv: Connection refused

#### pid=391,cmd=/usr/bin/ffmpeg -i http://127.0.0.1:8081/rtp/65010600002000100001_65010611581314000005.live.flv -y -f mjpeg -t 0.001 /opt/media/bin/www/snap/c7078249bdedd01e56c9388f8edeb2c9/1721787012.jpeg.tmp #####

ffmpeg version 3.4.11-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[tcp @ 0x557e32f36820] Connection to tcp://127.0.0.1:8081 failed: Connection refused
http://127.0.0.1:8081/rtp/65010600002000100001_65010611581314000005.live.flv: Connection refused

[0m
[33m2024-07-24 10:10:12.305 W MediaServer[8-work poller 3] Process.cpp:288 s_kill | kill process 391 failed:no such process[0m
[34m2024-07-24 10:10:12.317 T MediaServer[8-event poller 0] HttpSession.cpp:27 HttpSession | 1508-33(192.168.3.247:35398) [0m
[36m2024-07-24 10:10:13.868 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注册:hls://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[34m2024-07-24 10:10:43.011 T MediaServer[8-event poller 3] HttpSession.cpp:119 onError | 1506-3(192.168.4.56:49216) session timeout[0m
[34m2024-07-24 10:10:43.011 T MediaServer[8-event poller 3] HttpSession.cpp:33 ~HttpSession | 1506-3(192.168.4.56:49216) [0m
[34m2024-07-24 10:10:59.659 T MediaServer[8-event poller 0] HttpSession.cpp:27 HttpSession | 1509-46(192.168.4.56:49240) [0m
[32m2024-07-24 10:10:59.700 D MediaServer[8-event poller 3] WebApi.cpp:250 http api debug | 
# request:
GET /index/api/getMediaInfo?vhost=__defaultVhost__&schema=rtsp&app=rtp&stream=65010600002000100001_65010611581314000005&secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc
# header:
accept : application/json, text/plain, */*
accept-encoding : gzip, deflate, br, zstd
accept-language : zh-CN,zh;q=0.9,ja;q=0.8,zh-TW;q=0.7,en;q=0.6,ko;q=0.5
Connection : Keep-Alive
cookie : 
host : 192.168.4.56:8081
referer : https://wvp.zjht100.com/
sec-ch-ua : "Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"
sec-ch-ua-mobile : ?0
sec-ch-ua-platform : "Windows"
sec-fetch-dest : empty
sec-fetch-mode : cors
sec-fetch-site : same-origin
user-agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
X-Forwarded-For : 192.168.3.247
X-Forwarded-Proto : http
# content:

# response:
{
	"aliveSecond" : 47,
	"app" : "rtp",
	"bytesSpeed" : 241694,
	"code" : 0,
	"createStamp" : 1721787011,
	"isRecordingHLS" : true,
	"isRecordingMP4" : true,
	"originSock" : 
	{
		"identifier" : "65010600002000100001_65010611581314000005",
		"local_ip" : "172.21.0.2",
		"local_port" : 31450,
		"peer_ip" : "124.117.253.46",
		"peer_port" : 2048
	},
	"originType" : 3,
	"originTypeStr" : "rtp_push",
	"originUrl" : "rtp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005",
	"readerCount" : 0,
	"schema" : "rtsp",
	"stream" : "65010600002000100001_65010611581314000005",
	"totalReaderCount" : 1,
	"tracks" : 
	[
		{
			"codec_id" : 0,
			"codec_id_name" : "H264",
			"codec_type" : 0,
			"fps" : 25.0,
			"height" : 1080,
			"loss" : 0.0,
			"ready" : true,
			"width" : 1920
		}
	],
	"vhost" : "__defaultVhost__"
}

[0m
[33m2024-07-24 10:11:01.867 W MediaServer[8-event poller 0] HttpSession.cpp:105 onError | 1508-33(192.168.3.247:35398) FLV/TS/FMP4播放器(__defaultVhost__/rtp/65010600002000100001_65010611581314000005)断开:recv close request from client,耗时(s):49[0m
[34m2024-07-24 10:11:01.867 T MediaServer[8-event poller 0] HttpSession.cpp:33 ~HttpSession | 1508-33(192.168.3.247:35398) [0m
[34m2024-07-24 10:11:21.877 T MediaServer[8-event poller 0] HttpSession.cpp:27 HttpSession | 1510-47(192.168.4.56:49246) [0m
[36m2024-07-24 10:11:21.877 I MediaServer[8-event poller 0] TcpServer.cpp:40 ~TcpServer | Close tcp server [::]: 31450[0m
[33m2024-07-24 10:11:21.877 W MediaServer[8-event poller 0] RtpSession.cpp:58 onError | 1507-31(124.117.253.46:2048) 65010600002000100001_65010611581314000005 Server shutdown[0m
[32m2024-07-24 10:11:21.877 D MediaServer[8-event poller 0] RtpSession.cpp:43 ~RtpSession | 1507-31(124.117.253.46:2048) [0m
[36m2024-07-24 10:11:21.878 I MediaServer[8-event poller 0] Rtsp.cpp:401 operator() | return port to pool:31450-31451[0m
[33m2024-07-24 10:11:21.878 W MediaServer[8-event poller 3] RtpProcess.cpp:62 ~RtpProcess | 65010600002000100001_65010611581314000005(124.117.253.46:2048) RTP推流器(__defaultVhost__/rtp/65010600002000100001_65010611581314000005)断开,耗时(s):70[0m
[32m2024-07-24 10:11:21.878 D MediaServer[8-event poller 0] WebApi.cpp:250 http api debug | 
# request:
POST /index/api/closeRtpServer
# header:
Accept-Encoding : gzip
Connection : Keep-Alive
Content-Length : 95
Content-Type : application/x-www-form-urlencoded
Host : 192.168.4.56:8081
User-Agent : okhttp/3.14.9
# content:
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&stream_id=65010600002000100001_65010611581314000005
# response:
{
	"code" : 0,
	"hit" : 1
}

[0m
[36m2024-07-24 10:11:21.878 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注销:hls://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:11:21.879 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注销:ts://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:11:21.879 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注销:rtsp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[33m2024-07-24 10:11:21.880 W MediaServer[8-event poller 0] WebHook.cpp:179 operator() | hook http://127.0.0.1:10043/api/record/on_record_mp4 0ms,failed[network err]:connection refused:{
	"app" : "rtp",
	"file_name" : "10-10-12.mp4",
	"file_path" : "/opt/media/bin/www/record/rtp/65010600002000100001_65010611581314000005/2024-07-24/10-10-12.mp4",
	"file_size" : 34968349,
	"folder" : "/opt/media/bin/www/record/rtp/65010600002000100001_65010611581314000005/",
	"mediaServerId" : "your_server_id",
	"start_time" : 1721787012,
	"stream" : "65010600002000100001_65010611581314000005",
	"time_len" : 70.160003662109375,
	"url" : "record/rtp/65010600002000100001_65010611581314000005/2024-07-24/10-10-12.mp4",
	"vhost" : "__defaultVhost__"
}
[0m
[36m2024-07-24 10:11:21.880 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注销:rtmp://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[36m2024-07-24 10:11:21.880 I MediaServer[8-event poller 3] MediaSource.cpp:523 emitEvent | 媒体注销:fmp4://__defaultVhost__/rtp/65010600002000100001_65010611581314000005[0m
[33m2024-07-24 10:11:24.881 W MediaServer[8-event poller 0] WebHook.cpp:179 operator() | hook http://127.0.0.1:10043/api/record/on_record_mp4 0ms,failed[network err]:connection refused:{
	"app" : "rtp",
	"file_name" : "10-10-12.mp4",
	"file_path" : "/opt/media/bin/www/record/rtp/65010600002000100001_65010611581314000005/2024-07-24/10-10-12.mp4",
	"file_size" : 34968349,
	"folder" : "/opt/media/bin/www/record/rtp/65010600002000100001_65010611581314000005/",
	"mediaServerId" : "your_server_id",
	"start_time" : 1721787012,
	"stream" : "65010600002000100001_65010611581314000005",
	"time_len" : 70.160003662109375,
	"url" : "record/rtp/65010600002000100001_65010611581314000005/2024-07-24/10-10-12.mp4",
	"vhost" : "__defaultVhost__"
}
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
ZLM的日志上传上来

**Comment by xiongguangjie** [comment]
你这个截图有问题，这个hook携带的内容与代码对不上

**Comment by huangjunAAAA** [comment]
详细日志添加了。

**Comment by huangjunAAAA** [comment]
不好意思docker镜像的版本我搞错了，是20221205的x86版本。

**Comment by huangjunAAAA** [comment]
![image](https://github.com/user-attachments/assets/103d58ea-f74b-4f47-9518-8283f2027610)
最新版本的docker的情况也是这样，日志稍有不同

**Comment by huangjunAAAA** [comment]
我搞错了，应该是我的wvp的版本和zlm版本对应不上了。
