### ISSUE TITLE
[BUG] 同一个MP4文件使用ffmpeg推流，rtp, rtmp都可以，而rtsp不行

### ISSUE THREAD

**Issue by alwaystom** [ZLMediaKit/ZLMediaKit#3759]
## 现象描述
ZLMediaKit 版本  ZLMediaKit(git hash:fea7f36/2024-07-23T11:24:09+08:00,branch:,build time:2024-07-23T03:33:06)
同一个MP4文件使用ffmpeg推流，rtp, rtmp都可以，而rtsp不行

## 如何复现?

ffmpeg -re -i "4.mp4" -vcodec h264 -acodec aac -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test
## 相关日志或截图
ffmpeg报错如图
![image](https://github.com/user-attachments/assets/920f2da9-2b45-4849-acc0-fbd5fbbc53c5)
MediaServer开启trace级别日志没有任何报错

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置
默认配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息
ffmpeg版本 7.0.1

* **代码提交记录/git commit hash**:
* **操作系统及版本**: windows11
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by alwaystom** [comment]
![image](https://github.com/user-attachments/assets/5d7bf430-7002-461b-987e-4425079291f7)
视频xi信息

**Comment by xia-chu** [comment]
这问题怎么看也不是zlm问题啊

**Comment by alwaystom** [comment]
> 这问题怎么看也不是zlm问题啊

也尝试过更换视频和ffmpeg软件，确实无法解决问题😓，视频也符合h264视频编码和aac音频编码。

**Comment by PioLing** [comment]
是你ffmpeg 转码，可能gop 太大了（默认好像10 秒），

试下这个命令

ffmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test

**Comment by alwaystom** [comment]
> 是你ffmpeg 转码，可能gop 太大了（默认好像10 秒），
> 
> 试下这个命令
> 
> ffmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test

也不行，用这个视频 [https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4](url) ，ffmpeg试过6和7版本都不行

**Comment by xia-chu** [comment]
你应该提供zlm的日志

**Comment by PioLing** [comment]
> > 是你ffmpeg 转码，可能gop 太大了（默认好像10 秒），
> > 试下这个命令
> > ffmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test
> 
> 也不行，用这个视频 https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4 ，ffmpeg试过6和7版本都不行

![微信截图_20240730145105](https://github.com/user-attachments/assets/c376f42c-d8bc-4cc8-8ee3-b24011c4f6cb)
试了rtsp 推拉流，没有问题

**Comment by alwaystom** [comment]
> 你应该提供zlm的日志
zlm的日志如下，实际上没有相关信息
![image](https://github.com/user-attachments/assets/06a06bc7-6a01-462f-8124-a9b7bbc971ce)

**Comment by alwaystom** [comment]
> fmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test

换了一台 i5-7300HQ的Win10机器，使用相同ffmpeg版本和相同视频可以推流，但是使用i9-13900H的win11机器就会推送失败。

**Comment by alwaystom** [comment]
> fmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test

换了一台 i5-7300HQ的Win10机器，使用相同ffmpeg版本和相同视频可以推流，但是使用i9-13900H的win11机器就会推送失败。

**Comment by PioLing** [comment]
> > fmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test
> 
> 换了一台 i5-7300HQ的Win10机器，使用相同ffmpeg版本和相同视频可以推流，但是使用i9-13900H的win11机器就会推送失败。

网络环境一样吗？
是ffmpeg 推流失败 ？还是推上去了，从zlm 拉流 失败？ 什么日志

**Comment by alwaystom** [comment]
> fmpeg -re -i "4.mp4" -vcodec copy -acodec copy -f rtsp -v verbose -rtsp_transport tcp rtsp://127.0.0.1/live/test

破案了，554端口被别的应用绑定了（在我的电脑是是WindowsMeidaPlayer）,把554关联的进程关了就行，不过随之而来的问题是为什么端口可以重复绑定？
![image](https://github.com/user-attachments/assets/b964a197-1a36-4c3a-84b0-6c1c16ec7efb)
这是我电脑上的端口绑定情况，两个进程分别是
![image](https://github.com/user-attachments/assets/f9af9a5c-7992-4913-8310-2e918404c348)
