### ISSUE TITLE
[BUG] BUG现象描述(必填)

### ISSUE THREAD

**Issue by zhujianLeo** [ZLMediaKit/ZLMediaKit#3768]
## 现象描述
通过ffmpeg -re -stream_loop -1 -i /d/Dataset/16.hevc -c copy -f rtsp rtsp://127.0.0.1/live/3 命令将分辨率为3840x2160 fps 60编码为hevc的视频推流到mediaserver 通过vlc 或者potplayer 播放发现不能正常播放，只能显示一半并且在跳帧

## 相关日志或截图
![Snipaste_2024-07-30_15-10-04](https://github.com/user-attachments/assets/fe18f805-11c9-40cd-8080-cefd9eb78703)
![Snipaste_2024-07-30_15-11-29](https://github.com/user-attachments/assets/0f500381-5cd8-4054-b26a-d36b69540697)
![Snipaste_2024-07-30_15-11-44](https://github.com/user-attachments/assets/2938dd4e-5323-4990-a218-c116a6f05e1f)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by PioLing** [comment]
#3759

**Comment by xiongguangjie** [comment]
使用tcp ，看日志说是丢包了

**Comment by zhujianLeo** [comment]
ffmpeg -re -stream_loop -1 -i /d/Dataset/16.hevc -c copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/3
通过tcp推流后 vlc尝试通过rtmp://127.0.0.1/live/3拉流播放 发现无法正常播放
![Snipaste_2024-07-31_10-46-00](https://github.com/user-attachments/assets/e646e593-cd2f-481e-807e-28077806d3d9)

**Comment by PioLing** [comment]
> ffmpeg -re -stream_loop -1 -i /d/Dataset/16.hevc -c copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/3 通过tcp推流后 vlc尝试通过rtmp://127.0.0.1/live/3拉流播放 发现无法正常播放 ![Snipaste_2024-07-31_10-46-00](https://private-user-images.githubusercontent.com/10540718/353673519-e646e593-cd2f-481e-807e-28077806d3d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTY0MDYsIm5iZiI6MTcyMjM5NjEwNiwicGF0aCI6Ii8xMDU0MDcxOC8zNTM2NzM1MTktZTY0NmU1OTMtY2QyZi00ODFlLTgwN2UtMjgwNzc4MDZkM2Q5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAzMjE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODM5YTBkYzg2NmExYmJlNzUxMTNhMjQyZWZiN2E3MjUyOTZkNDZjMjQ4ZTY5Yjc4OGVhMjAxNTFlNWM3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FpLrASc9_pmSRyhOG-WL-z-Vb-DcQznexJJFZE7czw)

https://github.com/ZLMediaKit/ZLMediaKit/issues/3770#issuecomment-2259551758

**Comment by fclampqq** [comment]
我看了你的，我与你的不同吧。 我是直接用 ZLMK 拉  摄像头的RTSP的流。  你是推给ZLMK。
https://github.com/ZLMediaKit/ZLMediaKit/issues/3770

**Comment by PioLing** [comment]
> > ffmpeg -re -stream_loop -1 -i /d/Dataset/16.hevc -c copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/3 通过tcp推流后 vlc尝试通过rtmp://127.0.0.1/live/3拉流播放 发现无法正常播放 ![Snipaste_2024-07-31_10-46-00](https://private-user-images.githubusercontent.com/10540718/353673519-e646e593-cd2f-481e-807e-28077806d3d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzOTY0MDYsIm5iZiI6MTcyMjM5NjEwNiwicGF0aCI6Ii8xMDU0MDcxOC8zNTM2NzM1MTktZTY0NmU1OTMtY2QyZi00ODFlLTgwN2UtMjgwNzc4MDZkM2Q5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDAzMjE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwODM5YTBkYzg2NmExYmJlNzUxMTNhMjQyZWZiN2E3MjUyOTZkNDZjMjQ4ZTY5Yjc4OGVhMjAxNTFlNWM3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FpLrASc9_pmSRyhOG-WL-z-Vb-DcQznexJJFZE7czw)
> 
> [#3770 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/3770#issuecomment-2259551758)

叫你看 这issue 第一条评论，是和你rtmp 拉流关联的

**Comment by xiongguangjie** [comment]
> ffmpeg -re -stream_loop -1 -i /d/Dataset/16.hevc -c copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/3 通过tcp推流后 vlc尝试通过rtmp://127.0.0.1/live/3拉流播放 发现无法正常播放 ![Snipaste_2024-07-31_10-46-00](https://private-user-images.githubusercontent.com/10540718/353673519-e646e593-cd2f-481e-807e-28077806d3d9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjIwMjMsIm5iZiI6MTcyMjQyMTcyMywicGF0aCI6Ii8xMDU0MDcxOC8zNTM2NzM1MTktZTY0NmU1OTMtY2QyZi00ODFlLTgwN2UtMjgwNzc4MDZkM2Q5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYjgyYzI4MzI2ODRhZGI5Y2MyYTI2YTZlN2RhM2UzOTlhNDk1MDNiMmUzOTNhZTIzYjk4YjhiOTc4OTVhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T5vC5aOBuf5hv20ac-oWZsQKGhHL0BrGhUCb5uUBnc0)

你这个h265的编码vlc不支持rtmp 包含h265的编码格式，使用rtsp播放
