### ISSUE TITLE
播放的URL不变但是会一直触发回调鉴权

### ISSUE THREAD

**Issue by liuqiyang7** [ZLMediaKit/ZLMediaKit#3769]
## 现象描述
客户端使用HLS协议播放，播放的地址是不变的，大部分客户端是只会在第一次请求的时候触发鉴权，但是有一部分客户端每次在调用.m3u8接口的时候都会触发回调鉴权，每次都会返回一个新的Cookie。 正常情况下不是播放的URL不变就会给Cookie自动续期吗，不知道是BUG还是这里有什么特殊逻辑？

## 相关日志或截图
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/451825dc-dd3b-4fde-9ba2-44edc2733485">
打码的为同一个IP和两个流的地址

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了

**Comment by liuqiyang7** [comment]
> 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了

那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。

**Comment by xiongguangjie** [comment]
> > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> 
> 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。

有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的

**Comment by liuqiyang7** [comment]
> > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > 
> > 
> > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> 
> 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的

我确认我们的客户端都是不带cookie的

**Comment by liuqiyang7** [comment]
> > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > 
> > 
> > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> 
> 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的

https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035

**Comment by xiongguangjie** [comment]
> > > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > > 
> > > 
> > > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> > 
> > 
> > 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的
> 
> [#2776 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035)

那只能说明，你的有些携带了 query的参数，有些没有携带query的参数

**Comment by xiongguangjie** [comment]
逻辑是没有携带cookie 才会去检查query的参数

**Comment by liuqiyang7** [comment]
> > > > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > > > 
> > > > 
> > > > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> > > 
> > > 
> > > 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的
> > 
> > 
> > [#2776 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035)
> 
> 那只能说明，你的有些携带了 query的参数，有些没有携带query的参数

我们只会携带一个query的参数，并且对于每个客户端这个参数都是唯一且不会变的。 所以我才想知道zlm这边是不是除了query参数还有其他的什么校验，比如请求头什么的。

**Comment by xiongguangjie** [comment]
> > > > > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > > > > 
> > > > > 
> > > > > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> > > > 
> > > > 
> > > > 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的
> > > 
> > > 
> > > [#2776 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035)
> > 
> > 
> > 那只能说明，你的有些携带了 query的参数，有些没有携带query的参数
> 
> 我们只会携带一个query的参数，并且对于每个客户端这个参数都是唯一且不会变的。 所以我才想知道zlm这边是不是除了query参数还有其他的什么校验，比如请求头什么的。

检查query参数是整个的字符串，如http://xx.xxx..xx..x/live/test/hls.m3u8?a=1&c=2 与 http://xx.xxx..xx..x/live/test/hls.m3u8?c=2&a=1 不会认为是同一个链接的，即使是同一个播放器发出的请求。除了cookie 与 query 就没有了，cookie 优先

**Comment by liuqiyang7** [comment]
> > > > > > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > > > > > 
> > > > > > 
> > > > > > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> > > > > 
> > > > > 
> > > > > 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的
> > > > 
> > > > 
> > > > [#2776 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035)
> > > 
> > > 
> > > 那只能说明，你的有些携带了 query的参数，有些没有携带query的参数
> > 
> > 
> > 我们只会携带一个query的参数，并且对于每个客户端这个参数都是唯一且不会变的。 所以我才想知道zlm这边是不是除了query参数还有其他的什么校验，比如请求头什么的。
> 
> 检查query参数是整个的字符串，如http://xx.xxx..xx..x/live/test/hls.m3u8?a=1&c=2 与 http://xx.xxx..xx..x/live/test/hls.m3u8?c=2&a=1 不会认为是同一个链接的，即使是同一个播放器发出的请求。除了cookie 与 query 就没有了，cookie 优先

我把多个请求的链接拷出来比对过，是完全一致的。后面只携带一个参数，也不存在你说的这种情况。

**Comment by xiongguangjie** [comment]
> > > > > > > > 因为每一次hls的请求需要把cookie 带上来，否则无法区分是否已经经过鉴权了
> > > > > > > 
> > > > > > > 
> > > > > > > 那么为什么有些客户端会一直触发鉴权，有些客户端不会呢。我印象中zlm是有根据URL匹配cookie的逻辑的。
> > > > > > 
> > > > > > 
> > > > > > 有的把cookie 带上来了，有的没有，hls 协议不想其他协议有长链接的概念，都是很多次http请求组成的
> > > > > 
> > > > > 
> > > > > [#2776 (comment)](https://github.com/ZLMediaKit/ZLMediaKit/issues/2776#issuecomment-1686210035)
> > > > 
> > > > 
> > > > 那只能说明，你的有些携带了 query的参数，有些没有携带query的参数
> > > 
> > > 
> > > 我们只会携带一个query的参数，并且对于每个客户端这个参数都是唯一且不会变的。 所以我才想知道zlm这边是不是除了query参数还有其他的什么校验，比如请求头什么的。
> > 
> > 
> > 检查query参数是整个的字符串，如http://xx.xxx..xx..x/live/test/hls.m3u8?a=1&c=2 与 http://xx.xxx..xx..x/live/test/hls.m3u8?c=2&a=1 不会认为是同一个链接的，即使是同一个播放器发出的请求。除了cookie 与 query 就没有了，cookie 优先
> 
> 我把多个请求的链接拷出来比对过，是完全一致的。后面只携带一个参数，也不存在你说的这种情况。

这个代码就是这样写的，要么就是有些携带了cookie ， 你去好好排查一下，或者调试ZLM的代码

**Comment by xia-chu** [comment]
自己看代码吧：
![image](https://github.com/user-attachments/assets/c7f532fc-55b4-4d6f-adbd-65f4d92801b4)
