### ISSUE TITLE
addStreamProxy 拉取rtsp流 enable_rtsp 设置为0 rtsp源还是会生成（rtmp 也会有类似问题）

### ISSUE THREAD

**Issue by fclampqq** [ZLMediaKit/ZLMediaKit#3770]
## 现象描述
使用 /index/api/addStreamProxy?secret=xxxx&url=rtsp://admin:xxxx@192.168.11.110/LiveMedia/ch1/Media2&enable_mp4=false&stream=1&enable_hls_fmp4=false&enable_rtsp=false&enable_ts=false&ts_demand=false&vhost=__defaultVhost__&timeout_sec=20&enable_hls=false&enable_fmp4=false&enable_audio=true&app=live&rtp_type=0&retry_count=3&enable_rtmp=true  接口拉流成功 --->
{
	"code" : 0,
	"data" : 
	{
		"key" : "__defaultVhost__/live/1"
	}
}
服务端面页上也显示拉流成功
![拉流成功](https://github.com/user-attachments/assets/be67502e-98d3-4f20-8313-0cc3722d5904)

但使用VLC  播放   http://192.168.11.115:8080/live/1.live.flv  时无法播放，提示 未找到解码器

![无法播](https://github.com/user-attachments/assets/fd93e3d8-9b55-4e7b-b281-df0ad034e24e)

摄像头的配置
![华为配置](https://github.com/user-attachments/assets/4ac8b6f1-b0c7-4e79-8f42-61b886f83764)
原始RTSP流：  rtsp://admin:xxxx@192.168.11.110/LiveMedia/ch1/Media2   这个RTSP流是能直接被VLC播放的。

然后，我又用同样的参数 调 /index/api/addStreamProxy 接口，只是改了视频源地url ，改成
rtsp://stream.strba.sk:1935/strba/VYHLAD_JAZERO.stream
这个拉流成功并且能正常播放。

华为的RTSP怎么拉流成功，播不了呐。

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
vlc  flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以

**Comment by fclampqq** [comment]
> vlc flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以

额，不是呐。我又增加了一种 协议 HTTP-TS/WS-TS ，  

![image](https://github.com/user-attachments/assets/7931e60c-f2ee-4eda-979a-05ba05309e6c)

然后 我用 VLC 播放 http://192.168.11.110:8080/live/1.live.ts 

是可以播的呐 （摄像头的 编码没有改仍然是  265的 ）。

而且我点开看 解码器就是 265呐

![image](https://github.com/user-attachments/assets/a1faefb2-7114-4ebe-9633-be4fa2f65605)

**Comment by fclampqq** [comment]
> vlc flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以

而且还有一个 奇怪现象，我不开启 转rtsp 流时， 服务端也有rtsp 代理。比如这个：

/index/api/addStreamProxy?retry_count=3&enable_fmp4=false&ts_demand=false&rtp_type=0&timeout_sec=20&enable_hls=false&enable_hls_fmp4=false&enable_rtmp=true&enable_ts=false&secret=zgznvr&url=rtsp://admin:xxxx@192.168.11.110/LiveMedia/ch1/Media2&enable_mp4=false&enable_rtsp=false&app=live&stream=1&enable_audio=true&auto_close=false&vhost=__defaultVhost__

enable_rtsp 是否转 rtsp 协议    明明 设置为  enable_rtsp=false， 服务端还能看到rtsp
![image](https://github.com/user-attachments/assets/e70eabd7-e4d7-4639-b3be-c9273c8a4b02)

**Comment by fclampqq** [comment]
> > vlc flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以
> 
> 而且还有一个 奇怪现象，我不开启 转rtsp 流时， 服务端也有rtsp 代理。比如这个：
> 
> /index/api/addStreamProxy?retry_count=3&enable_fmp4=false&ts_demand=false&rtp_type=0&timeout_sec=20&enable_hls=false&enable_hls_fmp4=false&enable_rtmp=true&enable_ts=false&secret=zgznvr&url=rtsp://admin:xxxx@192.168.11.110/LiveMedia/ch1/Media2&enable_mp4=false&enable_rtsp=false&app=live&stream=1&enable_audio=true&auto_close=false&vhost=**defaultVhost**
> 
> enable_rtsp 是否转 rtsp 协议 明明 设置为 enable_rtsp=false， 服务端还能看到rtsp ![image](https://private-user-images.githubusercontent.com/25204796/353730160-e70eabd7-e4d7-4639-b3be-c9273c8a4b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU2MjIsIm5iZiI6MTcyMjQxNTMyMiwicGF0aCI6Ii8yNTIwNDc5Ni8zNTM3MzAxNjAtZTcwZWFiZDctZTRkNy00NjM5LWIzYmUtYzkyNzNjOGE0YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODkxMjE0NTRhYWQ0MTc2NDFiM2NiZGUwNzUwNTk5MjgyM2IzOWJiNGE4OTM2NDI0YmMyNjA3OTg3MWVkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lTFjYSnPljniW8Tc5pXRdlDyTGMwlOpCULfdlT3_5CE)

@xiongguangjie   这个问题能看一下吗？ 设置enable_rtsp=false ，但为什么 还是有 rtsp 代理呐？

**Comment by xiongguangjie** [comment]
> > vlc flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以
> 
> 额，不是呐。我又增加了一种 协议 HTTP-TS/WS-TS ，
> 
> ![image](https://private-user-images.githubusercontent.com/25204796/353723685-7931e60c-f2ee-4eda-979a-05ba05309e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjEzMzEsIm5iZiI6MTcyMjQyMTAzMSwicGF0aCI6Ii8yNTIwNDc5Ni8zNTM3MjM2ODUtNzkzMWU2MGMtZjJlZS00ZWRhLTk3OWEtMDViYTA1MzA5ZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNGUwOGI2OTAwNzA2Njg4NTRhZDY0ZjAwYWJmY2NhMzQxZGNlNjYxNDY5YTU5NjE3YTM4ZGZmYTFjZGQzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GvcamdujaQgOCiezarDM_s4pdYmQ43madzvUueTIzqI)
> 
> 然后 我用 VLC 播放 http://192.168.11.110:8080/live/1.live.ts
> 
> 是可以播的呐 （摄像头的 编码没有改仍然是 265的 ）。
> 
> 而且我点开看 解码器就是 265呐
> 
> ![image](https://private-user-images.githubusercontent.com/25204796/353724970-a1faefb2-7114-4ebe-9633-be4fa2f65605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjEzMzEsIm5iZiI6MTcyMjQyMTAzMSwicGF0aCI6Ii8yNTIwNDc5Ni8zNTM3MjQ5NzAtYTFmYWVmYjItNzExNC00ZWJlLTk2MzMtYmU0ZmEyZjY1NjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEwMTcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MzhkNmJkYWRhNzM0NGVlZTZjYjYyZTcxNTlhY2ZlMDAyMGNjZjczOGIyZTU0N2QwZGEzNGNiYjk1M2VkOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dA4oal2QOBvVMMeeEg4mv5BuKJ6FWardErt_X_jDEB8)

这个ts 支持h265的编码格式没问题的

**Comment by xiongguangjie** [comment]
> > > vlc flv 的容器是不支持h265的（因为官方也不支持），你需要用rtsp播放才可以
> > 
> > 
> > 而且还有一个 奇怪现象，我不开启 转rtsp 流时， 服务端也有rtsp 代理。比如这个：
> > /index/api/addStreamProxy?retry_count=3&enable_fmp4=false&ts_demand=false&rtp_type=0&timeout_sec=20&enable_hls=false&enable_hls_fmp4=false&enable_rtmp=true&enable_ts=false&secret=zgznvr&url=rtsp://admin:xxxx@192.168.11.110/LiveMedia/ch1/Media2&enable_mp4=false&enable_rtsp=false&app=live&stream=1&enable_audio=true&auto_close=false&vhost=**defaultVhost**
> > enable_rtsp 是否转 rtsp 协议 明明 设置为 enable_rtsp=false， 服务端还能看到rtsp ![image](https://private-user-images.githubusercontent.com/25204796/353730160-e70eabd7-e4d7-4639-b3be-c9273c8a4b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTU2MjIsIm5iZiI6MTcyMjQxNTMyMiwicGF0aCI6Ii8yNTIwNDc5Ni8zNTM3MzAxNjAtZTcwZWFiZDctZTRkNy00NjM5LWIzYmUtYzkyNzNjOGE0YjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA4NDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODkxMjE0NTRhYWQ0MTc2NDFiM2NiZGUwNzUwNTk5MjgyM2IzOWJiNGE4OTM2NDI0YmMyNjA3OTg3MWVkN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lTFjYSnPljniW8Tc5pXRdlDyTGMwlOpCULfdlT3_5CE)
> 
> @xiongguangjie 这个问题能看一下吗？ 设置enable_rtsp=false ，但为什么 还是有 rtsp 代理呐？
配置文件中 rtsp.directProxy的配置需要设置为0 才能生效，你设置为1 会导致直接代理不经过转封装，你设置了enable_rtsp 为false 也不会生效。这个算是个小bug吧，你先这么配置修改吧，后面我会修复的。

**Comment by fclampqq** [comment]
> rtsp.directProxy

好的，  rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时，  如果摄像头是265编码的，ZLMediaKit  确实不能正常转流出来。然后 HLS(fmp4)    HTTP-fMP4   协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将  265 转成  264 编码出来吗？ 因为我们是在WEB 网页上用，就看到  rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。

**Comment by xiongguangjie** [comment]
> > rtsp.directProxy
> 
> 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。

使用jessbuca 使用flv 来播放就可以播放h265的视频了

**Comment by fclampqq** [comment]
> > > rtsp.directProxy
> > 
> > 
> > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> 
> 使用jessbuca 使用flv 来播放就可以播放h265的视频了

好的，多谢~  明天我试试。

**Comment by fclampqq** [comment]
> > > rtsp.directProxy
> > 
> > 
> > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> 
> 使用jessbuca 使用flv 来播放就可以播放h265的视频了

会有计划 使 ZLMK 能将265转成 264输出吗？

**Comment by xiongguangjie** [comment]
> > > > rtsp.directProxy
> > > 
> > > 
> > > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> > 
> > 
> > 使用jessbuca 使用flv 来播放就可以播放h265的视频了
> 
> 会有计划 使 ZLMK 能将265转成 264输出吗？
pro版本支持（需要收费），但是比较消耗性能？参考这个 https://github.com/tsingeye/ZLMediakit-Pro

**Comment by fclampqq** [comment]
> > > > > rtsp.directProxy
> > > > 
> > > > 
> > > > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> > > 
> > > 
> > > 使用jessbuca 使用flv 来播放就可以播放h265的视频了
> > 
> > 
> > 会有计划 使 ZLMK 能将265转成 264输出吗？
> > pro版本支持（需要收费），但是比较消耗性能？参考这个 https://github.com/tsingeye/ZLMediakit-Pro

哦哦，好的。 我能问一下，你推荐的这个pro版， 265转 264 是  基于  ffmpeg  吗？ 还是自已代码写的呐？

**Comment by fclampqq** [comment]
> > > > > rtsp.directProxy
> > > > 
> > > > 
> > > > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> > > 
> > > 
> > > 使用jessbuca 使用flv 来播放就可以播放h265的视频了
> > 
> > 
> > 会有计划 使 ZLMK 能将265转成 264输出吗？
> > pro版本支持（需要收费），但是比较消耗性能？参考这个 https://github.com/tsingeye/ZLMediakit-Pro

怎么联系你们?具体沟通一下呐

**Comment by fclampqq** [comment]
> > > > > rtsp.directProxy
> > > > 
> > > > 
> > > > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> > > 
> > > 
> > > 使用jessbuca 使用flv 来播放就可以播放h265的视频了
> > 
> > 
> > 会有计划 使 ZLMK 能将265转成 264输出吗？
> > pro版本支持（需要收费），但是比较消耗性能？参考这个 https://github.com/tsingeye/ZLMediakit-Pro

怎么联系你们?能具体商务沟通一下不？ 1213642868@qq.com   我加你们这个QQ号了

**Comment by xiongguangjie** [comment]
> > > > > > rtsp.directProxy
> > > > > 
> > > > > 
> > > > > 好的， rtsp.directProxy 我已设置了。 然后，我仔细研究了一下， 使用 RTMP 协议时， 如果摄像头是265编码的，ZLMediaKit 确实不能正常转流出来。然后 HLS(fmp4) HTTP-fMP4 协议 又延迟太严重了。 但又改不了摄像头的265编码，这个ZLMK 有能力将 265 转成 264 编码出来吗？ 因为我们是在WEB 网页上用，就看到 rtmp 类型的 http-flv 完美支持，而且一点都不延迟。 无耐改不了摄像头的265编码。
> > > > 
> > > > 
> > > > 使用jessbuca 使用flv 来播放就可以播放h265的视频了
> > > 
> > > 
> > > 会有计划 使 ZLMK 能将265转成 264输出吗？
> > > pro版本支持（需要收费），但是比较消耗性能？参考这个 https://github.com/tsingeye/ZLMediakit-Pro
> 
> 怎么联系你们?能具体商务沟通一下不？ [1213642868@qq.com](mailto:1213642868@qq.com) 我加你们这个QQ号了

加微信 18675721 你说是熊二介绍过来的就行了
