### ISSUE TITLE
[BUG] webrtc 播放H.265视频流没有图像

### ISSUE THREAD

**Issue by wind-rain666** [ZLMediaKit/ZLMediaKit#3775]
## 现象描述

前端通过ZLMRTCClient.js播放H.265视频流时显示视频在播放，但是没有图像，切换编码为H.264时没有这个问题。
查看issue时，里面提到zlm和chrome都已支持H.265,是还需要什么配置吗？

## 如何复现?

使用ZLMRTCClient.js播放H.265视频流

## 相关日志或截图

![image](https://github.com/user-attachments/assets/0e21dcb0-387e-4538-8102-016cf330e964)

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
[rtsp]
authBasic=0
directProxy=0
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=332

```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:Ubuntu 20.04
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:
chrome版本: 125.0.6422.141

**Comment by xiongguangjie** [comment]
除了苹果的，其他浏览器都不支持rtc h265 , 你要在浏览器播放使用flv播放（找支持h265的播放器，如jessbuca/h265web.js 等）

**Comment by wind-rain666** [comment]
> 除了苹果的，其他浏览器都不支持rtc h265 , 你要在浏览器播放使用flv播放（找支持h265的播放器，如jessbuca/h265web.js 等）

感谢大佬，windows和linux下是否可以添加启动方式来支持H.265播放呢 #3589

**Comment by xiongguangjie** [comment]
> > 除了苹果的，其他浏览器都不支持rtc h265 , 你要在浏览器播放使用flv播放（找支持h265的播放器，如jessbuca/h265web.js 等）
> 
> 感谢大佬，windows和linux下是否可以添加启动参数来支持H.265播放呢 #3589

这个是浏览器的问题，不是zlm的，这个要么在服务器端转码如使用[ZLM-pro版本](https://github.com/tsingeye/ZLMediakit-Pro) 或者使用addffmpeg souce l来转码 ,要么自己修改播放器端（也就是浏览器）
