### ISSUE TITLE
[编译问题] 编译执行make时报错

### ISSUE THREAD

**Issue by yumb-cd** [ZLMediaKit/ZLMediaKit#3776]
## 相关日志及环境信息
![1](https://github.com/user-attachments/assets/1d8ceb08-f32c-4ff0-8c22-eb292fb1a4a5)

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>
cd /home/ZLMediaKit/build/webrtc && /usr/bin/c++  -DENABLE_HLS -DENABLE_MP4 -DENABLE_OPENSSL -DENABLE_RTPPROXY -DENABLE_VERSION -DHAVE_MMSG_HDR -DHAVE_RECVMMSG_API -DHAVE_SENDMMSG_API -I/home/ZLMediaKit/build 
-I/home/ZLMediaKit/3rdpart -I/home/ZLMediaKit/webrtc -I/home/ZLMediaKit/webrtc/.. -I/home/ZLMediaKit/src -I/home/ZLMediaKit/3rdpart/jsoncpp/include -I/home/ZLMediaKit/3rdpart/media-server/libflv/include -I/home/ZLMediaKit/3rdpart/media-server/libmov/include -I/home/ZLMediaKit/3rdpart/media-server/libmpeg/include -I/home/ZLMediaKit/3rdpart/ZLToolKit/src  -g   -fPIC -Wall -Wextra -Wno-unused-function -Wno-unused-parameter -Wno-unused-variable -Wno-deprecated-declarations -Wno-error=extra -Wno-error=missing-field-initializers -Wno-error=type-limits -g3 -std=gnu++11 -o CMakeFiles/webrtc.dir/DtlsTransport.cpp.o -c /home/ZLMediaKit/webrtc/DtlsTransport.cpp/home/ZLMediaKit/webrtc/DtlsTransport.cpp: 在成员函数‘bool RTC::DtlsTransport::DtlsEnvironment::ReadCertificateAndPrivateKeyFromContext(SSL_CTX*)’中:
/home/ZLMediaKit/webrtc/DtlsTransport.cpp:303:32: 错误：‘X509_up_ref’在此作用域中尚未声明
         X509_up_ref(certificate);
                                ^
/home/ZLMediaKit/webrtc/DtlsTransport.cpp:309:35: 错误：‘EVP_PKEY_up_ref’在此作用域中尚未声明
         EVP_PKEY_up_ref(privateKey);
                                   ^
/home/ZLMediaKit/webrtc/DtlsTransport.cpp: 在构造函数‘RTC::DtlsTransport::DtlsTransport(toolkit::EventPoller::Ptr, RTC::DtlsTransport::Listener*)’中:
/home/ZLMediaKit/webrtc/DtlsTransport.cpp:560:52: 错误：‘DTLS_set_timer_cb’在此作用域中尚未声明
         DTLS_set_timer_cb(this->ssl, onSslDtlsTimer);
                                                    ^
make[2]: *** [webrtc/CMakeFiles/webrtc.dir/DtlsTransport.cpp.o] 错误 1
make[2]: 离开目录“/home/ZLMediaKit/build”
make[1]: *** [webrtc/CMakeFiles/webrtc.dir/all] 错误 2
make[1]: 离开目录“/home/ZLMediaKit/build”
make: *** [all] 错误 2

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。
[CMakeCache.txt](https://github.com/user-attachments/files/16451259/CMakeCache.txt)

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

**Comment by yumb-cd** [comment]
cmake version 3.17.0-rc3
OpenSSL 3.3.1 4 Jun 2024 (Library: OpenSSL 3.3.1 4 Jun 2024)

**Comment by xia-chu** [comment]
libssl版本太老了 它跟OpenSSL二进制版本不是一回事
