### ISSUE TITLE
[BUG] fmp4封装超过一定I帧间隔，强制刷新segment，防止内存上涨

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#3804]
## 现象描述
截图中的这块代码 我测试并没有进入saveSegment();
这里的逻辑是不是不对
        if (frame->keyFrame()) {
           //  _non_iframe_video_count = 0;
        } else {
            _non_iframe_video_count++;
        }
是不是这样就满足要求了

## 相关日志或截图

![image](https://github.com/user-attachments/assets/409e11ed-edbc-4492-8692-6b8a0bafa442)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
说明你的视频是正常的 一直有关键帧啊。
这个兼容逻辑的存在是因为有些摄像头从264切换到265 导致判断关键帧逻辑失效了 从而内存溢出
