### ISSUE TITLE
[功能请求] 能否增加SRT推流、拉流的c api

### ISSUE THREAD

**Issue by GreenVegetables** [ZLMediaKit/ZLMediaKit#3813]
## 描述该功能的用处，可以提供相关资料描述该功能

感谢zlm的大神，我们的应用很早就接入了zlm，近期有用户反馈srt推流、拉流的需求，主要是其在弱网环境下有较好画面衔接表现

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷

无

## 描述你期望实现该功能的方式和最终效果

增加srt推流、拉流示例代码，和相应的c api

**Comment by xia-chu** [comment]
其实很多功能的实现要靠pr 如果没这方面的pr 开发者个人又没这块的需求 那么多半没动力和精力去实现的
毕竟这个工作量不算小

**Comment by GreenVegetables** [comment]
> 其实很多功能的实现要靠pr 如果没这方面的pr 开发者个人又没这块的需求 那么多半没动力和精力去实现的 毕竟这个工作量不算小

嗯嗯，同意。
