### ISSUE TITLE
[BUG] rtsp流解析出来的g711的音频采样不正确 貌似是固定的8000

### ISSUE THREAD

**Issue by hh-kai** [ZLMediaKit/ZLMediaKit#3821]
## 现象描述

![image](https://github.com/user-attachments/assets/f9545a58-2228-44dc-aae6-1d81dcb9c33c)

实际ffmpeg命令行读出来的是16000 
![image](https://github.com/user-attachments/assets/af4a3d7c-9203-49ac-9b60-c70c94f700ce)

抓包看 sdp里面的也是16000
![image](https://github.com/user-attachments/assets/bce3c5e4-da91-4cdd-b5eb-2df76d25393a)

这是固定的G771A或G711U的是8000吗?

使用这里的重采样 出来的数据也是不正确的
![image](https://github.com/user-attachments/assets/4f07464a-da08-4de1-8d8b-7cf8daef11ab)

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
是的 zlm把g711的采样率固定成8000了 原因是本来g711开始只支持8000采样率 而且转其他协议也有问题 很多协议不支持非8000的g711

![image](https://github.com/user-attachments/assets/e5bdb3d5-482d-4072-aa69-9cbf3aee8393)

**Comment by xia-chu** [comment]
不过我觉得这个设定可以先去掉了 你要不来个pr吧

**Comment by hh-kai** [comment]
我是解码音频播放 发现采样率不对 
我看了从sdp中解析的是正确的 在中途又变回默认的了
我想知道在哪里变的 
G711.cpp 这个在player中貌似没有用到

**Comment by xia-chu** [comment]
就这么改 来个pr呗？
