### ISSUE TITLE
[功能请求] Transcode 分支的代码已经一年多没有更新了很多新特性无法使用能否更新一下

### ISSUE THREAD

**Issue by Haoxw** [ZLMediaKit/ZLMediaKit#3825]
## 描述该功能的用处，可以提供相关资料描述该功能
Transcode 分支的代码已经一年多没有更新了，很多新特性无法使用，能否更新一下。

**Comment by mtdxc** [comment]
transcode2分支已合并到最新代码，请看看吧。

**Comment by Haoxw** [comment]
> Transcode2 branch has been merged into the latest code.
> 
> > transcode2分支已合并到最新代码。
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

transcode1 分支能否合并到最新代码，我们需要使用 G711A 转 AAC 在 FLV 格式中，非常感谢！！！！
