### ISSUE TITLE
[BUG] 往其他国标服务器推流不能播放

### ISSUE THREAD

**Issue by wk-dotcom** [ZLMediaKit/ZLMediaKit#3831]
## 现象描述
向LiveGBS推送GB28181流，LiveGBS一直提示找不到流，超时报错。通过FFMPEG向LiveGBS就可以推流成功播放，说明通道没啥问题。

## 如何复现?
步骤1，LiveGBS选择视频通道，点击播放；
步骤2，抓取INVITE报文，查看SDP描述的目标端口；
步骤3，参照[Wiki](https://github.com/ZLMediaKit/ZLMediaKit/wiki/GB28181%E6%8E%A8%E6%B5%81)让ZLMediaKit往其他国标服务器推流操作说明，向LiveGBS推流。
期望LiveGBS能播放流，结果LiveGBS不能播放流。

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```

#ZLM日志
2024-08-19 10:07:47.959 W [MediaServer] [2468-event poller 2] RtspSession.cpp:62 onError | 1-35(127.0.0.1:58488) RTSP推流器(__defaultVhost__/live/test)断开:recv teardown request,耗时(s):150
2024-08-19 10:07:49.264 W [MediaServer] [2468-event poller 1] EventPoller.cpp:209 async_l | take time: 7ms, thread may be overloaded
2024-08-19 10:07:53.268 W [MediaServer] [2468-event poller 3] EventPoller.cpp:209 async_l | take time: 43ms, thread may be overloaded
2024-08-19 10:07:55.297 W [MediaServer] [2468-event poller 1] EventPoller.cpp:209 async_l | take time: 16ms, thread may be overloaded
2024-08-19 10:08:15.380 W [MediaServer] [2468-event poller 1] EventPoller.cpp:209 async_l | take time: 25ms, thread may be overloaded
2024-08-19 10:08:22.159 W [MediaServer] [2468-event poller 1] EventPoller.cpp:209 async_l | take time: 32ms, thread may be overloaded
2024-08-19 10:08:23.315 W [MediaServer] [2468-event poller 3] EventPoller.cpp:209 async_l | take time: 9ms, thread may be overloaded
2024-08-19 10:08:23.367 W [MediaServer] [2468-event poller 1] EventPoller.cpp:209 async_l | take time: 7ms, thread may be overloaded
2024-08-19 10:08:23.928 I [MediaServer] [2468-event poller 1] MediaSource.cpp:517 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/test
2024-08-19 10:08:24.464 D [MediaServer] [2468-event poller 1] MediaSink.cpp:162 emitAllTrackReady | All track ready use 2304ms
2024-08-19 10:08:24.465 I [MediaServer] [2468-event poller 1] MediaSource.cpp:517 emitEvent | 媒体注册:fmp4://__defaultVhost__/live/test
2024-08-19 10:08:24.465 I [MediaServer] [2468-event poller 1] MultiMediaSourceMuxer.cpp:551 onAllTrackReady | stream: rtsp://127.0.0.1:554/live/test , codec info: mpeg4-generic[44100/2/16] H264[1720/1080/30] 
2024-08-19 10:08:24.465 I [MediaServer] [2468-event poller 1] MediaSource.cpp:517 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/test
2024-08-19 10:08:24.465 I [MediaServer] [2468-event poller 1] MediaSource.cpp:517 emitEvent | 媒体注册:ts://__defaultVhost__/live/test
2024-08-19 10:08:26.379 I [MediaServer] [2468-event poller 1] MediaSource.cpp:517 emitEvent | 媒体注册:hls://__defaultVhost__/live/test
2024-08-19 10:08:31.614 I [MediaServer] [2468-event poller 1] RtpSender.cpp:243 onConnect | 开始发送 rtp:192.168.86.2:30006, 是否为udp方式:1
2024-08-19 10:08:31.614 D [MediaServer] [2468-event poller 1] WebApi.cpp:261 http api debug | 
# request:
GET /index/api/startSendRtp?secret=i7FGYQh4r4a3l9bURAqCp7X3RaubEqK9&vhost=__defaultVhost__&app=live&stream=test&ssrc=200000996&dst_url=192.168.86.2&dst_port=30006&is_udp=1&src_port=31852&pt=96&use_ps=1
# header:
Accept : */*
Host : 127.0.0.1
# content:

# response:
{
        "code" : 0,
        "local_port" : 31852
}

#LivGBS日志：
[SMS] 2024/08/19 10:08:29 invite is coming...
[SMS] 2024/08/19 10:08:29 rtp udp server start --> udp://[::]:30006
[SMS] 2024/08/19 10:08:29 handle invite done, session count[1]
[SMS] 2024/08/19 10:08:29 rtcp udp server start --> udp://[::]:30007
[SMS] 2024/08/19 10:08:29 >>>>>>[tcp://192.168.86.2:15070]>>>>>>[tcp://192.168.86.2:58491]>>>>>>
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.86.2:15060;rport=58491;received=192.168.86.2;branch=z9hG4bK538424186
From: <sip:34020000002000000001@3402000000>;tag=52424186
To: <sip:34020000002020000001@3402000000>;tag=160424188
CSeq: 14 INVITE
Call-ID: 614424186
User-Agent: LiveGBS v240809
Contact: <sip:34020000002020000001@192.168.86.2:15070>
Content-Length: 220
Content-Type: APPLICATION/SDP

v=0
o=34020000002020000001 0 0 IN IP4 192.168.86.2
s=Play
c=IN IP4 192.168.86.2
t=0 0
m=video 30006 RTP/AVP 96 97 98
a=recvonly
a=rtpmap:96 PS/90000
a=rtpmap:97 MPEG4/90000
a=rtpmap:98 H264/90000
y=0200000996
[SMS] 2024/08/19 10:08:30 <<<<<<[tcp://192.168.86.2:15070]<<<<<<[tcp://192.168.86.2:58491]<<<<<<
ACK sip:34020000002020000001@3402000000 SIP/2.0
Via: SIP/2.0/TCP 192.168.86.2:15060;rport;branch=z9hG4bK478424917
From: <sip:34020000002000000001@3402000000>;tag=52424186
To: <sip:34020000002020000001@3402000000>;tag=160424188
Call-ID: 614424186
CSeq: 14 ACK
Content-Type: APPLICATION/SDP
Contact: <sip:34020000002000000001@192.168.86.2:15060>
Max-Forwards: 70
User-Agent: LiveGBS v240809
Content-Length: 239

v=0
o=34020000001320000996 699 699 IN IP4 192.168.86.55
s=Play
c=IN IP4 192.168.86.55
t=0 0
m=video 31852 RTP/AVP 96
a=sendonly
a=rtpmap:96 PS/90000
a=filesize:0
a=username:34020000001320000996
a=password:12345678
y=0200000996
[SMS] 2024/08/19 10:08:30 ack is coming...
[SMS] 2024/08/19 10:08:31 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] open reader...
[SMS] 2024/08/19 10:08:31 >>>>>>[tcp://192.168.86.2:15070]>>>>>>[tcp://192.168.86.2:58491]>>>>>>
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.86.2:15060;rport=58491;received=192.168.86.2;branch=z9hG4bK478424917
From: <sip:34020000002000000001@3402000000>;tag=52424186
To: <sip:34020000002020000001@3402000000>;tag=160424188
CSeq: 14 ACK
Call-ID: 614424186
User-Agent: LiveGBS v240809
Contact: <sip:34020000002020000001@192.168.86.2:15070>
Content-Length: 0

[SMS] 2024/08/19 10:08:32 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] start local stream...
[SMS] 2024/08/19 10:08:42 <<<<<<[tcp://192.168.86.2:15070]<<<<<<[tcp://192.168.86.2:58491]<<<<<<
BYE sip:34020000002020000001@3402000000 SIP/2.0
Via: SIP/2.0/TCP 192.168.86.2:15060;rport;branch=z9hG4bK294436407
From: <sip:34020000002000000001@3402000000>;tag=52424186
To: <sip:34020000002020000001@3402000000>;tag=160424188
Call-ID: 614424186
CSeq: 19 BYE
Contact: <sip:34020000002000000001@192.168.86.2:15060>
Max-Forwards: 70
User-Agent: LiveGBS v240809
Stream-ID: stream:34020000001320000996:34020000001320000996
Bye-As: api stream stop
Content-Length: 0

[SMS] 2024/08/19 10:08:42 bye is coming...
[SMS] 2024/08/19 10:08:42 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] open reader error, open stream timeout[15000 ms]
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] start local stream error, media session already stopped, open stream timeout[15000 ms]
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 0...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 1...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 2...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 3...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 4...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 5...
[SMS] 2024/08/19 10:08:46 stream writer[stream:34020000001320000996:34020000001320000996] close...
[SMS] 2024/08/19 10:08:46 stream writer[stream:34020000001320000996:34020000001320000996] close done
[SMS] 2024/08/19 10:08:46 stream writer[stream:34020000001320000996:34020000001320000996_sub] close...
[SMS] 2024/08/19 10:08:46 stream writer[stream:34020000001320000996:34020000001320000996_sub] close done
[SMS] 2024/08/19 10:08:46 hls writer[34020000001320000996_34020000001320000996] close...
[SMS] 2024/08/19 10:08:46 hls writer[34020000001320000996_34020000001320000996] close done
[SMS] 2024/08/19 10:08:46 hls writer[34020000001320000996_34020000001320000996_sub] close...
[SMS] 2024/08/19 10:08:46 hls writer[34020000001320000996_34020000001320000996_sub] close done
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 6...
[SMS] 2024/08/19 10:08:46 stream reader[stream:34020000001320000996:34020000001320000996] close...
[SMS] 2024/08/19 10:08:46 stream reader[stream:34020000001320000996:34020000001320000996] close done
[SMS] 2024/08/19 10:08:46 rtp udp server stop --> udp://[::]:30006
[SMS] 2024/08/19 10:08:46 rtcp udp server stop --> udp://[::]:30007
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 7...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 8...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy 9...
[SMS] 2024/08/19 10:08:46 MediaSession[stream:34020000001320000996:34020000001320000996][UDP] sync destroy done
[SMS] 2024/08/19 10:08:46 handle bye done, session count[0]
[SMS] 2024/08/19 10:08:46 >>>>>>[tcp://192.168.86.2:15070]>>>>>>[tcp://192.168.86.2:58491]>>>>>>
SIP/2.0 200 OK
Via: SIP/2.0/TCP 192.168.86.2:15060;rport=58491;received=192.168.86.2;branch=z9hG4bK294436407
From: <sip:34020000002000000001@3402000000>;tag=52424186
To: <sip:34020000002020000001@3402000000>;tag=160424188
CSeq: 19 BYE
Call-ID: 614424186
User-Agent: LiveGBS v240809
Contact: <sip:34020000002020000001@192.168.86.2:15070>
Content-Length: 0

</pre>
</details>

## 配置
配置没改动，默认配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:
RTP报文
[output.zip](https://github.com/user-attachments/files/16654763/output.zip)

**Comment by xia-chu** [comment]
请补充下zlmediakit版本信息。
不过这个问题我猜不可能是zlm的问题，因为zlm肯定级联对接过LiveGBS，但是我从来没收到相似的反馈。

大概率是你调用startSendRtp接口参数不对导致，如果你使用的是wvp-pro, 请在wvp-pro项目提issue。

**Comment by wk-dotcom** [comment]
版本信息：

编译日期: 2024-08-17T14:58:14
代码日期: **2024-03-05T10:42:22+08:00**
当前git分支: master
当前git hash值: ffdc13b

接口参数有啥问题呢？
GET /index/api/startSendRtp?secret=i7FGYQh4r4a3l9bURAqCp7X3RaubEqK9&vhost=defaultVhost&app=live&stream=test&ssrc=200000996&dst_url=192.168.86.2&dst_port=30006&is_udp=1&src_port=31852&pt=96&use_ps=1

RTP报文有空看一下呢？
见补充信息。

没有使用wvp-pro

**Comment by xia-chu** [comment]
首先你先更新下zlm到最新版本吧 再测试一遍 如果还是不行，请提供下抓包文件。

**Comment by wk-dotcom** [comment]
更新到最新版本可以播放了，感谢感谢
