### ISSUE TITLE
[编译问题] 使用wvp-GB28181-pro对接GB28181视频，前后端服务启动后，连接ZLM失败

### ISSUE THREAD

**Issue by R-Tsubasa** [ZLMediaKit/ZLMediaKit#3842]
## 相关日志及环境信息

- 使用`wvp-GB28181-pro`对接GB28181视频
- 使用Docker部署ZLM
- Docker启动命令：
```shell
docker run -id -p 1935:1935 -p 8086:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp --name zlm zlmediakit/zlmediakit:master
```
- Docker日志：[docker_log_20240822.log](https://github.com/user-attachments/files/16708899/docker_log_20240822.log)
- Docker中的INI配置信息：[config.log](https://github.com/user-attachments/files/16708921/config.log)（上传限制，后缀改成log了）
- 前后端服务已正常启动
- `wvp-GB28181-pro`后端服务日志：[wvp-2024-08-22.0.log](https://github.com/user-attachments/files/16708022/wvp-2024-08-22.0.log)
- 后端服务配置：[application-dev.log](https://github.com/user-attachments/files/16708980/application-dev.log)（上传限制，后缀改成log了）

## 操作与现象
1. 启动前后端服务
2. 启动Docker
3. 进入前端管理台-国标设备，添加设备
4. 点击刷新操作，后端服务报错，详见上方日志

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**: `Win11 专业版`
* **硬件信息**: `Intel i5-13500`
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
这个我觉得提issue给wvp比较合适，你应该是没配置好zlm或wvp。
