### ISSUE TITLE
rtmp播放首帧水印问题

### ISSUE THREAD

**Issue by b3ginner** [ZLMediaKit/ZLMediaKit#3845]
## 现象描述
你好，我在通过拉取摄像头rtsp流通过rtmp播放时首帧出现了streamed by zlmediakit git hash.....信息，我在其他issue中看到了可以去除版本信息那些东西 但是不能去掉 streamed by zlmediakit，我想知道能否通过配置文件去除版本信息，或者有什么方式能狗去除版本信息呢？
## 相关日志或截图
![42521724659162_ pic_hd](https://github.com/user-attachments/assets/84fae566-3176-4558-9724-d6bf898556a1)

**Comment by xiongguangjie** [comment]
这个是播放器的处理问题，会根据Server 的字段显示出相应的服务器，如果需要修改需要二开

**Comment by b3ginner** [comment]
> 这个是播放器的处理问题，会根据Server 的字段显示出相应的服务器，如果需要修改需要二开

好的 谢谢了
