### ISSUE TITLE
[BUG] ServiceController的make方法可能线程不安全

### ISSUE THREAD

**Issue by KkemChen** [ZLMediaKit/ZLMediaKit#3854]
## 现象描述

https://github.com/ZLMediaKit/ZLMediaKit/blob/ab22cac85bda02472604ff74a182904a75c9339b/server/WebApi.cpp#L341-L350

可能存在一种情况，两个线程都进到make方法，都构造了这个对象，其中会有一个emplace是失败的，然后assert也会失败；
是不是需要把
`std::lock_guard<std::recursive_mutex> lck(_mtx); `放到`auto server = std::make_shared<Type>(std::forward<_Args>(__args)...); `前面会好一点
## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xia-chu** [comment]
其实不影响什么 这个互斥锁只是为了保护线程安全问题导致的崩溃问题 所以只保护对_map的操作。
assert失败不是崩溃 只会抛异常 zlmediakit已经hook掉了assert

**Comment by KkemChen** [comment]
这样啊，也行👌
