### ISSUE TITLE
填加边缘计算回调

### ISSUE THREAD

**Issue by piaoyaoi** [ZLMediaKit/ZLMediaKit#3868]
希望作者大大能添加一个开放接口处理边缘计算，现在很多场景不光是要一个视频流，还要对视频流做识别报警处理，目前的实现是拉取zl的流，做了识别之后，再推流到zl，再从zl拉取识别后的流，中间的延迟就会比较大

**Comment by xia-chu** [comment]
你目前的做法和方案是推荐方法，这样解耦。
拉流再推流不会增加多少延时的 预计100ms左右

**Comment by piaoyaoi** [comment]
好的嘞，感谢作者大大这么好的项目
