### ISSUE TITLE
[功能请求] 需求描述(必填)请问向外部服务推流目前仅支持rtmp与rtsp吗？是否支持whip？

### ISSUE THREAD

**Issue by qq912150317** [ZLMediaKit/ZLMediaKit#3870]
## 描述你期望实现该功能的方式和最终效果
![1725613247142](https://github.com/user-attachments/assets/a68b1893-fe93-4d86-8054-c5754d988090)

**Comment by xiongguangjie** [comment]
通过whip 推流到其他服务器现在不支持

**Comment by qq912150317** [comment]
@xiongguangjie 了解了非常感谢
