### ISSUE TITLE
[BUG] centos7部署，gb28181推流。媒体注册成功,报错Unsupported mpeg：4

### ISSUE THREAD

**Issue by OHYuMingJiang** [ZLMediaKit/ZLMediaKit#3878]
## 现象描述
ZLMediakit部署在centos上，媒体注册成功。但是报错Unsupport mpeg：4
## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

<img width="945" alt="2024-09-10 124214" src="https://github.com/user-attachments/assets/e408c85a-c4c2-421a-8161-a3172a8c76eb">

</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

centos7

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by OHYuMingJiang** [comment]
<img width="945" alt="2024-09-10 124214" src="https://github.com/user-attachments/assets/43d37cfa-0bd2-4cc5-85fe-ce0a8eaaa46c">

**Comment by xia-chu** [comment]
4 是 PSI_STREAM_MP3， zlm不支持mp3
