### ISSUE TITLE
[BUG] When adding an RTSP video stream using addStreamProxy with enable_audio=0, why is WebRTC still able to play audio? 
[[BUG] addStreamProxy添加一个rtsp视频流，enable_audio=0, 为何webrtc还是能播出音频？]

### ISSUE THREAD

**Issue by pandalee86** [ZLMediaKit/ZLMediaKit#3880]
## Phenomenon Description
addStreamProxy adds an rtsp video stream, enable_audio=0
Then the tracks in the return value of getMeidaInfo also only have video, which is expected.
But why can the browser still broadcast audio using webrtc?
Does enable_audio=0 not prevent audio forwarding?

## How to reproduce?
postman calls addStreamProxy to add an IPC rtsp stream with audio enabled.
Open the ZLM RTC demo page in the browser and play the video stream just added using webrtc, the output has sound.

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**: 

>

## 现象描述
addStreamProxy添加一个rtsp视频流，enable_audio=0
然后getMeidaInfo返回值中的tracks中也只有video,符合预期。
但是为何浏览器用webrtc还是能播出音频？
是不是enable_audio=0并不能阻止音频的转发？

## 如何复现?
postman调用addStreamProxy添加一个启用了音频的IPC的rtsp流。
浏览器打开 ZLM RTC demo页面，用webrtc播放刚才添加的视频流，播出来的是有声音的。

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GPT4`

**Comment by xia-chu** [comment]
你把directProxy设置为0就行了

**Comment by pandalee86** [comment]
明白了
自测也OK
多谢！
