### ISSUE TITLE
[BUG] BUG Phenomenon Description (Required) Rtsp server onWholeRtspPacket function does not filter POST method

### ISSUE THREAD

**Issue by quxiaohui-debug** [ZLMediaKit/ZLMediaKit#3894]
## Phenomenon Description
![image](https://github.com/user-attachments/assets/0fb1ecfb-4263-48f9-b6cb-602b6a43b068)
No filtering of POST method, resulting in error when using RTSP over HTTP

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
![image](https://github.com/user-attachments/assets/0fb1ecfb-4263-48f9-b6cb-602b6a43b068)
没有过滤POST方法，导致在RTSP OVER HTTP方式时报错

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
ZLM的日志是啥，同时报什么错误

**Comment by xiongguangjie** [comment]
使用如下patch 修复下，的确ffmpeg 通过http -tunel 拉流有bug
```diff --git a/src/Rtsp/RtspSession.cpp b/src/Rtsp/RtspSession.cpp
index 46e62fe2..2cbaf217 100644
--- a/src/Rtsp/RtspSession.cpp
+++ b/src/Rtsp/RtspSession.cpp
@@ -128,7 +128,7 @@ void RtspSession::onRecv(const Buffer::Ptr &buf) {
 void RtspSession::onWholeRtspPacket(Parser &parser) {
     string method = parser.method(); //提取出请求命令字
     _cseq = atoi(parser["CSeq"].data());
-    if (_content_base.empty() && method != "GET") {
+    if (_content_base.empty() && method != "GET" && method != "POST" ) {
         RtspUrl rtsp;
         rtsp.parse(parser.url());
         _content_base = rtsp._url;```

**Comment by quxiaohui-debug** [comment]
是的，过滤掉POST方法就行了

**Comment by quxiaohui-debug** [comment]
那我关掉ISSUE了

**Comment by xiongguangjie** [comment]
> So I closed the ISSUE.
> 
> > 那我关掉ISSUE了
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我晚上提交后，就关闭这个issue

**Comment by quxiaohui-debug** [comment]
OK
