### ISSUE TITLE
[BUG] BUG现象描述(必填) Using addStreamProxy to transcode RTSP to FLV, the returned result URL cannot be played immediately, and it takes about 10 seconds to load. Is there any configuration that can solve this?

### ISSUE THREAD

**Issue by 295we** [ZLMediaKit/ZLMediaKit#3899]
## Phenomenon Description
After using addStreamProxy to transcode rtsp to flv, the returned result url cannot be played immediately, and it takes about 10 seconds to load before playing the successfully transcoded flv video.

## How to reproduce?
I am using zlm to transcode the monitored rtsp stream, and calling the addStreamProxy interface can immediately return the transcoded successful url. I can concatenate the url into a playable flv format url, but when I play this url immediately in my code, there is a network request with a delay of about 10 seconds before it can be played.

## Related logs or screenshots
![微信图片_20240914111221](https://github.com/user-attachments/assets/74a7e706-6b9f-4694-bf2d-d078e566822c)
The waiting time for this .live.flv stream is always around 9-10 seconds, but if I don't play it automatically and wait for the transcoding interface to return, and then call manual playback after 10 seconds, it can be played immediately. The flv playback uses bilibili's flvjs.

## Configuration

The zlm mediaServer configuration file has not been modified.

## Various environment information

The operating system is Huawei openEuler 24.03 LTS x86_64.

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
使用addStreamProxy转流rtsp为flv后，获取到的返回结果url不能立即播放，需要load十秒左右，才能正常播放转流成功的flv格式视频

## 如何复现?
我是使用zlm转流监控的rtsp流，调用addStreamProxy接口，可以立刻返回转流成功的url，我将url拼接成flv格式能播放的url，但是我在代码里面立马播放这个url，网络请求有个十秒左右的待处理，之后才能播放

## 相关日志或截图
![微信图片_20240914111221](https://github.com/user-attachments/assets/74a7e706-6b9f-4694-bf2d-d078e566822c)
这里这个.live.flv流等待的时间每次都是9-10秒左右，但若我不自动播放，而是等转流的接口返回之后，过个10来秒，调用手动播放，就可以秒播，播放flv使用的是b站的flvjs

## 配置

zlm的mediaServer配置文件没有改动

## 各种环境信息

操作系统是华为openEuler 24.03 LTS x86_64

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
ZLM的日志上传上来呀？一般都是声明了音频，但是没有音频数据，导致等到10s

**Comment by 295we** [comment]
![Snipaste_2024-09-14_11-40-14](https://github.com/user-attachments/assets/44b660e9-09b4-4acf-bada-ae891e5d9d09)
您好，这是我调转流接口的打印日志，辛苦您查看

**Comment by 295we** [comment]
> ZLM的日志上传了吗？一般是声明有音频，但是没有音频数据，导致要等待10s
> 
> > ZLM的日志上传上来呀？一般都是声明了音频，但是没有音频数据，导致要等10s
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

![Snipaste_2024-09-14_11-40-14](https://github.com/user-attachments/assets/a91c0346-3c1b-4db0-8bad-ff2d2eb08ebd)
您好，这是我调转流接口的日志，辛苦您查看

**Comment by xiongguangjie** [comment]
根据日志分析就是声明了音频，但是没有音频过来（需要等待10s超时），这个你禁用音频解决这个吧，通过配置文件protocol.enable_audio 设置为false 或者设置相应的接口参数，或者你找rtsp 的源厂商解决这个问题

**Comment by 295we** [comment]
> According to the log analysis, it is declared that there is audio, but no audio is coming (need to wait for 10s timeout), you can disable audio to solve this, through the configuration file `protocol.enable_audio` set to `false` or set the corresponding interface parameters, or you can find the RTSP source manufacturer to solve this problem.
> 
> > 根据日志分析就是声明了音频，但是没有音频过来（需要等待10s超时），这个你禁用音频解决这个吧，通过配置文件protocol.enable_audio 设置为false 或者设置相应的接口参数，或者你找rtsp 的源厂商解决这个问题
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`
谢谢您的解答，我设置了wait_track_ready_ms等待时长为1秒，发现也可以生效，非常感谢！
