### ISSUE TITLE
I'm currently receiving a continuous stream of byte arrays, can I push the stream to ZLM? Does this function currently exist? Which interface or event should I use? Please advise~

### ISSUE THREAD

**Issue by IOTWord** [ZLMediaKit/ZLMediaKit#3910]
## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
你能使用rtsp/rtmp/srt/rtc/rtp 推流到ZLM

**Comment by IOTWord** [comment]
> You can use rtsp/rtmp/srt/rtc/rtp to push streams to ZLM
> 
> > 你能使用rtsp/rtmp/srt/rtc/rtp 推流到ZLM
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`
不间断的流字节数组数据能推吗？支持吗

**Comment by xia-chu** [comment]
> 不间断的流字节数组数据能推吗？支持吗

裸帧不支持 这也超过了mtu udp发送不了的
