### ISSUE TITLE
[BUG] zlm sets recording to 1 minute per mp4 video, but no mp4 video is generated after 10 several hours

### ISSUE THREAD

**Issue by 199212zz** [ZLMediaKit/ZLMediaKit#3912]
## Phenomenon Description

wvp sets zlm to generate an mp4 video every 1 minute, but after running for 10 hours, it fails to generate an mp4 video at a normal 1-minute interval. After clicking the stop playback button on the wvp page, zlm will generate a total mp4 video for the segment of time that was not generated.

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

wvp设置zlm每隔1分钟生成一个mp4视频，运行10几小时后，无法正常间隔1分钟生成一个mp4视频，点击wvp页面停止播放按钮后，zlm会把未生成视频的这段时间内的视频生成一个总的mp4

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
> 无法正常间隔1分钟生成一个mp4视频

有可能一直没收到关键帧。是不是对方突然变更了编码格式？

**Comment by 199212zz** [comment]
应该不是，试了好几天，每次都运行几个小时后就这样，点击停止播放然后再继续播放，zlm又恢复间隔一分钟一个视频，看log也没看出啥问题来
