### ISSUE TITLE
After sending the video recording request successfully, when sending whether it is being recorded request, return false if not being recorded

### ISSUE THREAD

**Issue by lvzhouzhijun** [ZLMediaKit/ZLMediaKit#3913]
## Phenomenon Description
After sending a video recording request successfully, when sending a request to check if it is being recorded, it returns false without recording. Sometimes it also returns a -400 error. When I switch to another camera, this problem does not occur. I am not sure if it is a bug or a camera issue.

## Related logs or screenshots
![image](https://github.com/user-attachments/assets/f6a8c074-8296-42cd-8f0a-66febc4b3c2d)
![image](https://github.com/user-attachments/assets/e377b279-6f44-4b9e-a925-5ceec43706d7)

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
发送视频录制请求成功后，在发送是否正在录制请求，返回false没有在录制。有时候也会返回-400错误。我切换另外一个摄像头就不会出现这种问题。不太清除是bug，还是摄像头的问题。

## 相关日志或截图
![image](https://github.com/user-attachments/assets/f6a8c074-8296-42cd-8f0a-66febc4b3c2d)
![image](https://github.com/user-attachments/assets/e377b279-6f44-4b9e-a925-5ceec43706d7)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
这个原因不明 需要提供完整的日志文件 以及zlm版本信息

**Comment by lvzhouzhijun** [comment]
> 原因未知，请提供完整的日志文件和zlm版本信息。
> 
> > 这个原因不清楚需要提供完整的日志文件以及zlm版本信息
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

[2024-09-26_00.log](https://github.com/user-attachments/files/17145158/2024-09-26_00.log)
这个是今天的日志文件

**Comment by lvzhouzhijun** [comment]
![image](https://github.com/user-attachments/assets/dbebb15e-fef9-4e0f-94bc-8687e9e44bb3)
![image](https://github.com/user-attachments/assets/9913104f-4203-417a-a9c7-3d995def4edf)
可以看这两个时间段的

**Comment by lvzhouzhijun** [comment]
> 原因未知，请提供完整的日志文件和zlm版本信息。
> 
> > 这个原因狮子需要提供完整的日志文件以及zlm版本信息
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我是docker部署的，请问该怎么查看zlm版本信息

**Comment by lvzhouzhijun** [comment]
现在问题就是，第一次我开始录制视频，调用isRecording接口返回false，然后我就直接调用stopRecord接口直接停止，调用成功，但是没有调用hook回调接口，也没生成文件。第二次开始录制就会把第一次录制的文件进行生成然后调用hook接口回调

**Comment by xia-chu** [comment]
![image](https://github.com/user-attachments/assets/caf348d4-eb55-4a75-80b6-26e3873c5a84)
这个流有点bug 拉流不稳定 你更新下zlm 这个bug zlm后面兼容了

**Comment by lvzhouzhijun** [comment]
> ![图像](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTg5NzgsIm5iZiI6MTcyNzM5ODY3OCwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjIxNzhiYjM1MmQ0OWI1OWRlZDAwNTAxY2U0ODIyNGYyMDIwMzdmODM1YWNlOGVkYjcyZGNiZjFiMWIwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N26hLiER0lcKd6iRSA4sk94VJafpbOH3QoR_ac0L3sk) 此直播有几个 Bug。直播不稳定。您应该更新 zlm 来修复此 Bug。zlm 已更新以兼容后续版本。
> 
> > ![图像](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTg5NzgsIm5iZiI6MTcyNzM5ODY3OCwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjIxNzhiYjM1MmQ0OWI1OWRlZDAwNTAxY2U0ODIyNGYyMDIwMzdmODM1YWNlOGVkYjcyZGNiZjFiMWIwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N26hLiER0lcKd6iRSA4sk94VJafpbOH3QoR_ac0L3sk)
> > 这个流有点bug拉流不稳定你更新下zlm这个bug zlm后面兼容了
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

[2024-09-27_00.log](https://github.com/user-attachments/files/17157616/2024-09-27_00.log)
我用docker拉取了最新的master分支，但是还是有这个问题，上面是日志

**Comment by lvzhouzhijun** [comment]
> ![图像](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTg5NzgsIm5iZiI6MTcyNzM5ODY3OCwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjIxNzhiYjM1MmQ0OWI1OWRlZDAwNTAxY2U0ODIyNGYyMDIwMzdmODM1YWNlOGVkYjcyZGNiZjFiMWIwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N26hLiER0lcKd6iRSA4sk94VJafpbOH3QoR_ac0L3sk) 此直播有几个Bug。直播不稳定。您应该更新zlm来修复此Bug。zlm已更新以兼容后续版本。
> 
> > ![图像](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTg5NzgsIm5iZiI6MTcyNzM5ODY3OCwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZjIxNzhiYjM1MmQ0OWI1OWRlZDAwNTAxY2U0ODIyNGYyMDIwMzdmODM1YWNlOGVkYjcyZGNiZjFiMWIwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N26hLiER0lcKd6iRSA4sk94VJafpbOH3QoR_ac0L3sk)
> > 这个流有点bug拉流还没更新下zlm这个bug zlm后面兼容了
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

[Uploading 2024-09-27_00.log…]()
我试好几次录制，其中有一两次成功。但是失败之后，就成功不了。

**Comment by lvzhouzhijun** [comment]
> ![image](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI4NDYsIm5iZiI6MTcyNzQwMjU0NiwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMjJjYmY5MzQ1MDY5MWQyY2I5MDk3YmIwYWViMGVkZmViZTZhZDZmOTlmOWQ2ZTI5NjU1YWY2MmNmY2FmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ilSikmoA9EuAiwBjpeVb9K9h3jQzZI28KW8sTymd14) This stream has a few bugs. The stream is unstable. You should update zlm to fix this bug. zlm has been updated to be compatible afterwards.
> 
> > ![image](https://private-user-images.githubusercontent.com/11495632/371057774-caf348d4-eb55-4a75-80b6-26e3873c5a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MDI4NDYsIm5iZiI6MTcyNzQwMjU0NiwicGF0aCI6Ii8xMTQ5NTYzMi8zNzEwNTc3NzQtY2FmMzQ4ZDQtZWI1NS00YTc1LTgwYjYtMjZlMzg3M2M1YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAyMDIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMjJjYmY5MzQ1MDY5MWQyY2I5MDk3YmIwYWViMGVkZmViZTZhZDZmOTlmOWQ2ZTI5NjU1YWY2MmNmY2FmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6ilSikmoA9EuAiwBjpeVb9K9h3jQzZI28KW8sTymd14)
> > 这个流有点bug 拉流不稳定 你更新下zlm 这个bug zlm后面兼容了
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我试好几次录制，其中有一两次成功。但是失败之后，就成功不了。
[2024-09-27_00.log](https://github.com/user-attachments/files/17157927/2024-09-27_00.log)

**Comment by xia-chu** [comment]
> [2024-09-27_00.log](https://github.com/user-attachments/files/17157927/2024-09-27_00.log)

你这还是老代码啊
