### ISSUE TITLE
After SIP registration, audio transmission is implemented, and the Time in the PS stream in Wireshark capture is constantly increasing, how to solve it.

### ISSUE THREAD

**Issue by OHYuMingJiang** [ZLMediaKit/ZLMediaKit#3916]
## 现象描述
通过SIP注册后实现音频发送，在wireshark抓包后PS流中的Time不断增大如何解决

## 如何复现?

1.ffmpeg推流本机音频文件
   ffmpeg推流命令：ffmpeg -re -i "E:\eboy\ffmpeg-6.1.1-essentials_build\output-audio.aac"  -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test
   ZLMediaKit显示：

<img width="1273" alt="2" src="https://github.com/user-attachments/assets/2d92de23-38d0-4506-a528-bdb6c73b75c4">

2.通过/index/api/addStreamProxy进行拉流代理
   具体命令：http://192.168.1.68:8001/index/api/addStreamProxy?secret=JNM53msIN4IkQ5BvgLBqQ5qDh1Imlrnp&vhost=192.168.1.68&app=flvv&stream=flv&url=rtsp://127.0.0.1/live/test
    ZLMediaKit显示：
<img width="1265" alt="4" src="https://github.com/user-attachments/assets/9215b5db-e450-47d7-b3ee-8ff7f37e14a0">

3.通过/index/api/startSendRtp封装成PS流
    具体命令：http://192.168.1.68:8001/index/api/startSendRtp?secret=JNM53msIN4IkQ5BvgLBqQ5qDh1Imlrnp&vhost=192.168.1.68&app=flvv&stream=flv&ssrc=200000002&dst_url=192.168.1.182&dst_port=25069&is_udp=1&use_ps=1
   ZLMediaKit显示：
<img width="1264" alt="4" src="https://github.com/user-attachments/assets/93a0061e-9f24-4697-ac4c-b68f7f9895a2">

4.通过wireshark抓包发现Time不断增大，海康设备无法播放音频
<img width="1244" alt="1" src="https://github.com/user-attachments/assets/a19bc98f-a895-4fba-86cd-39dfaf2122e0">

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
这个是正常的，你这个流没有视频，只有音频就是不断增长的

**Comment by OHYuMingJiang** [comment]
请问这个Time是什么，有什么办法把他设置成0吗

**Comment by OHYuMingJiang** [comment]
> This is normal, your stream has no video, only audio is constantly growing.
> 
> > 这个是正常的，你这个流没有视频，只有音频就是不断增长的
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

请问这个Time是什么，有什么办法把他设置成0吗

**Comment by xiongguangjie** [comment]
> > This is normal, your stream has no video, only audio is constantly growing.
> > > 这个是正常的，你这个流没有视频，只有音频就是不断增长的
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 请问这个Time是什么，有什么办法把他设置成0吗

这个是标准规定的，除非二开，否则改不了

**Comment by OHYuMingJiang** [comment]
> > > This is normal, your stream has no video, only audio is constantly growing.
> > > > 这个是正常的，你这个流没有视频，只有音频就是不断增长的
> > > 
> > > 
> > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > 
> > 
> > 请问这个Time是什么，有什么办法把他设置成0吗
> 
> 这个是标准规定的，除非二开，否则改不了
请问这个Time是什么，是偏移量还是时间戳

**Comment by xiongguangjie** [comment]
> > > > This is normal, your stream has no video, only audio is constantly growing.
> > > > > 这个是正常的，你这个流没有视频，只有音频就是不断增长的
> > > > 
> > > > 
> > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > 
> > > 
> > > 请问这个Time是什么，有什么办法把他设置成0吗
> > 
> > 
> > 这个是标准规定的，除非二开，否则改不了
> > 请问这个Time是什么，是偏移量还是时间戳

rtp的时间戳
