### ISSUE TITLE
build failed on Apple M1 Pro

### ISSUE THREAD

**Issue by c1ngular** [ZLMediaKit/ZLMediaKit#3921]
## Related Logs and Environment Information

**Output of cmake && make command after clearing compilation cache**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
In file included from ～/ZLMediaKit/3rdpart/ZLToolKit/src/Util/util.cpp:601:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/cxxabi.h:51:1: error: functions that differ only in their return type cannot be overloaded
   50 | extern _LIBCXXABI_FUNC_VIS __cxa_exception*
      |                            ~~~~~~~~~~~~~~~~
   51 | __cxa_init_primary_exception(void* object, std::type_info* tinfo, void(_LIBCXXABI_DTOR_FUNC* dest)(void*)) throw();
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__exception/exception_ptr.h:36:47: note: previous declaration is here
   36 | _LIBCPP_OVERRIDABLE_FUNC_VIS __cxa_exception* __cxa_init_primary_exception(
      |                              ~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
make[2]: *** [3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Util/util.cpp.o] Error 1
make[1]: *** [3rdpart/CMakeFiles/zltoolkit.dir/all] Error 2
make: *** [all] Error 2
```

</pre>
</details>

[CMakeCache.txt](https://github.com/user-attachments/files/17068371/CMakeCache.txt)

## Various environment information

* **Code commit record/git commit hash**: f3e2a29
* **Operating system and version**: 14.6.1 (23G93)
* **Hardware information**: Apple M1 Pro
* **Other information to be supplemented**:

>

## 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/cxxabi.h:51:1: error: functions that differ only in their return type cannot be overloaded
   50 | extern _LIBCXXABI_FUNC_VIS __cxa_exception*
      |                            ~~~~~~~~~~~~~~~~
   51 | __cxa_init_primary_exception(void* object, std::type_info* tinfo, void(_LIBCXXABI_DTOR_FUNC* dest)(void*)) throw();
      | ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.0.sdk/usr/include/c++/v1/__exception/exception_ptr.h:36:47: note: previous declaration is here
   36 | _LIBCPP_OVERRIDABLE_FUNC_VIS __cxa_exception* __cxa_init_primary_exception(
      |                              ~~~~~~~~~~~~~~~~ ^
1 warning and 1 error generated.
make[2]: *** [3rdpart/CMakeFiles/zltoolkit.dir/ZLToolKit/src/Util/util.cpp.o] Error 1
make[1]: *** [3rdpart/CMakeFiles/zltoolkit.dir/all] Error 2
make: *** [all] Error 2
```

</pre>
</details>

[CMakeCache.txt](https://github.com/user-attachments/files/17068371/CMakeCache.txt)

## 各种环境信息

* **代码提交记录/git commit hash**: f3e2a29
* **操作系统及版本**: 14.6.1 (23G93)
* **硬件信息**: Apple M1 Pro
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by Dw9** [comment]
试试给下面宏拿出 namespace toolkit

#if defined(__MACH__) || defined(__APPLE__)
#include <limits.h>
#include <mach-o/dyld.h> /* _NSGetExecutablePath */

#ifndef HAS_CXA_DEMANGLE
// We only support some compilers that support __cxa_demangle.
// TODO: Checks if Android NDK has fixed this issue or not.
#if defined(__ANDROID__) && (defined(__i386__) || defined(__x86_64__))
#define HAS_CXA_DEMANGLE 0
#elif (__GNUC__ >= 4 || (__GNUC__ >= 3 && __GNUC_MINOR__ >= 4)) && \
!defined(__mips__)
#define HAS_CXA_DEMANGLE 1
#elif defined(__clang__) && !defined(_MSC_VER)
#define HAS_CXA_DEMANGLE 1
#else
#define HAS_CXA_DEMANGLE 0
#endif
#endif
#if HAS_CXA_DEMANGLE
#include <cxxabi.h>
#endif

**Comment by singlemonkey** [comment]
> > 试试给下面这一坨宏放最上面拿出 namespace toolkit
> 
> #ifndef HAS_CXA_DEMANGLE // We only support some compilers that support __cxa_demangle. // TODO: Checks if Android NDK has fixed this issue or not. #if defined(**ANDROID**) && (defined(**i386**) || defined(**x86_64**)) #define HAS_CXA_DEMANGLE 0 #elif (**GNUC** >= 4 || (**GNUC** >= 3 && **GNUC_MINOR** >= 4)) && !defined(**mips**) #define HAS_CXA_DEMANGLE 1 #elif defined(**clang**) && !defined(_MSC_VER) #define HAS_CXA_DEMANGLE 1 #else #define HAS_CXA_DEMANGLE 0 #endif #endif #if HAS_CXA_DEMANGLE #include <cxxabi.h> #endif

请问拿这一坨宏修改哪个文件？

**Comment by Dw9** [comment]
在 src/Util/util.cpp 里面， 内部已经合并了pr  https://github.com/ZLMediaKit/ZLToolKit/pull/252/files   回头更新下子模块

**Comment by xia-chu** [comment]
最新代码应该修复了
