### ISSUE TITLE
[Feature Request] Requirement Description (Required)

### ISSUE THREAD

**Issue by linjiaqi2017** [ZLMediaKit/ZLMediaKit#3927]
## Describe the purpose of this feature, and provide relevant information to describe this feature
You can add the function of whether to support Hikvision or Dahua sdp stream pulling and conversion protocol

## Is this feature used to improve project defects? If so, please describe the existing defects
You can add a way to pull streams

## Describe how you expect to achieve this feature and the final effect
Support Hikvision or Dahua sdp stream pulling and conversion protocol to use other protocols for broadcasting

>## 描述该功能的用处，可以提供相关资料描述该功能
可以添加是否支持海康或者大华sdp取流后转化协议的功能

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
可以增加一种取流的方式

## 描述你期望实现该功能的方式和最终效果
支持海康或者大华sdp取流后转化协议使用其他协议播的功能

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
sdp -> sdk ?

**Comment by linjiaqi2017** [comment]
sdk

**Comment by linjiaqi2017** [comment]
这边公司打算做一个大华sdk 取流的功能。我根据你在tests里面公开的海康sdk里面那个那个类deviceHK修改了一下，改成大华deviceDH 都是继承devicechannnel那个类。但是做集成后，发现回掉过来解码成yuv 然后再编码成h264就崩溃了，暂时崩溃在device.cpp 134行
![批注 2024-09-19 141533](https://github.com/user-attachments/assets/bb0b964e-7482-4e75-88cb-2d146be8f4c3)
我感觉可能是deviceDH类的没有重载这个函数，不知道还需要修改哪，可以帮忙看看吗？
zlmediakit 不熟悉的点是调用流程 (那些重载函数）和ZLToolKit

**Comment by linjiaqi2017** [comment]
请问一下可以帮忙看看这个问题吗

**Comment by xia-chu** [comment]
你编译时 开 x264好faac没

**Comment by linjiaqi2017** [comment]
编译已经开启了 开 x264和faac.
现在是崩溃在device.cpp initvideo 里面的addtrack这个函数，你那边可以尝试调试一下tests目录下面的 devicehk 试试。按理来说会出现相同的想象

**Comment by linjiaqi2017** [comment]
其实调试的过程发现 addtrack 是一个重写的虚函数，不知道有没有可能是应该调用哪一个类继承体系的addTrack.
还有sdk取流和协议取流ZLmediakit 流程上之前一些初始化是不是不大一样，我好像看到那个MediaSourceEvent
像addtrack这种 重写的虚函数，如果代码修改指定MultiMediaSourceMuxer::addtrack， 不会崩溃。但是业务是否正常就不好说了。这个MultiMediaSourceMuxer::addtrack不崩溃了，下一个inputFrame就崩溃了

**Comment by linjiaqi2017** [comment]
我不大理解的地方是那个线程那个地方getOwnerPoller，还有MediaSourceEvent，这两个地方

**Comment by linjiaqi2017** [comment]
请问一下可以帮忙看看这个问题吗

**Comment by xia-chu** [comment]
你在回调时 lambda捕获的参数是this? this可能都销毁了 你应该用weak_ptr

**Comment by linjiaqi2017** [comment]
具体说一下是哪一块的回调吗？Device.cpp 文件里面的devicechannel这个类吗

**Comment by xia-chu** [comment]
<img width="453" alt="image" src="https://github.com/user-attachments/assets/16a35f55-6d7e-4567-8ec6-6fb85c807fbd">
你在回调中访问了DevChannel类，这个类可能已经析构掉了，或者其他线程安全问题，你这属于二次开发，你代码怎么写的我们也不知道，所以没法协助你

**Comment by linjiaqi2017** [comment]
![批注 2024-09-29 161653](https://github.com/user-attachments/assets/96f89a0c-0e19-4bbd-95b1-357b9645eae2)
![批注 2024-09-29 161747](https://github.com/user-attachments/assets/0d57e9ad-86a6-4e2e-9060-074b35162df6)
代码是这么写

**Comment by linjiaqi2017** [comment]
这个回调是大华sdk的回调，回调出来视频流的，第一张图说明设置回调用了this 对象，第二个就是回调出来视频帧然后调用initVieo的函数。这个就是代码了，不好意思，之前没有粘贴，很抱歉，现在补上了

**Comment by linjiaqi2017** [comment]
我看你之前写的海康是 lambda捕获,静态回调函数也是一样吧

**Comment by linjiaqi2017** [comment]
我刚才换成和你海康一样的写法了，也是一样的

**Comment by linjiaqi2017** [comment]
你是说那个 self 需要修改成weak_ptr吗

**Comment by linjiaqi2017** [comment]
非常抱歉，还得再麻烦一下您

**Comment by linjiaqi2017** [comment]
有时间再麻烦一下您

**Comment by linjiaqi2017** [comment]
不好意思，能麻烦您再看一下，代码截图发过来了，不好意思

**Comment by xia-chu** [comment]
@linjiaqi2017 二次开发的bug 实在分析不了 ，DeviceHK目录下的代码早就没维护了，也不知道行不行。
而且你发的代码也只能管中窥豹。你用valgrind分析下吧
