### ISSUE TITLE
Memory usage rate cannot be reduced

### ISSUE THREAD

**Issue by qianniana** [ZLMediaKit/ZLMediaKit#3928]
## Phenomenon Description

After stopping playback, ZLMediait's memory usage does not automatically decrease. The memory usage will only decrease after restarting ZLMediait.
## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

停止播放之后，ZLMediait 的内存占用率不会自动下降。需要重启ZLMediait 内存占用率才会下降
## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
这是正常的 只要不会导致oom 就算正常
