### ISSUE TITLE
[BUG] addStreamProxy fails to start UDP receiving port when pulling RTSP UDP stream

### ISSUE THREAD

**Issue by Newleep** [ZLMediaKit/ZLMediaKit#3933]
## Phenomenon Description
On the Ubuntu system, when using MediaServer to pull the RTSP UDP stream, it keeps receiving timeouts. After packet capture, it is found that the UDP video stream can be received normally, excluding network problems
![image](https://github.com/user-attachments/assets/12af383e-2182-453e-964a-4fdb2aa73367)
Viewing the MediaServer port situation, MediaServer did not normally start the UDP receiving port
![image](https://github.com/user-attachments/assets/a02edee7-b2f7-450d-9e67-23d13137f26b)
Pulled the latest code on September 26, de7afaf992b16271d35f7a162bc0cb9695a02e9b, and tested against the code
Found that openRtpServer can open the UDP port, but when pulling the RTSP UDP stream, the port cannot be started normally
Then added logs for comparison and tested the method of starting the RTSP UDP port using the configured IP according to openrtpserver
![image](https://github.com/user-attachments/assets/d6410eeb-7c77-413e-9468-7a76a3c4d4e8)
From the logs, it can be seen that at the same time, the UDP port started by RTSP does not exist, and the port started by openrtpserver can be seen. The underlying method is to call the sockutil's bindudpsock method, and the parameters are the same except for the port
![image](https://github.com/user-attachments/assets/2278aec8-1b7a-4466-a0c0-5cb71cac19c2)

## How to reproduce?
The latest version of MediaServer, also tested half a year ago, a year ago, on Ubuntu 16.04 x64 laptops, Ubuntu 18.04 x64 servers, all have this problem

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
downloadRoot=./www
secret=abcd1234
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -frames:v 1 -an %s

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
listen_ip=::
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_audio_track_data_ms=1000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=0
on_flow_report=
on_http_access=
on_play=
on_publish=
on_record_mp4=
on_record_ts=
on_rtp_server_timeout=
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=
on_server_exited=
on_server_keepalive=
on_server_started=
on_shell_login=
on_stream_changed=
on_stream_none_reader=
on_stream_not_found=
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=10

[http]
allow_cross_domains=1
allow_ip_range=
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:de7afaf/2024-09-26T10:59:41+08:00,branch:master,build time:2024-09-27T14:21:20)</center></body></html>
port=6603
rootPath=./www
sendBufSize=65536
sslport=4436
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=15000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
maxRtpCacheMS=5000
maxRtpCacheSize=2048
max_bitrate=0
min_bitrate=0
nackIntervalRatio=1.0
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=6602
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
de7afaf992b16271d35f7a162bc0cb9695a02e9b
* **Operating system and version**:
*NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* **Hardware information**:
CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz x 2
MEMORY: 
![image](https://github.com/user-attachments/assets/8d6ad612-b3c0-42a5-8faa-3c05d28b3184)
DISK:
![image](https://github.com/user-attachments/assets/708b7654-ff2d-43dd-ac2f-efda25de0715)

* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
ubuntu系统上，使用MediaServer拉取rtsp udp流时，一直接收超时，抓包发现能正常接收到udp视频流，排除网络问题
![image](https://github.com/user-attachments/assets/12af383e-2182-453e-964a-4fdb2aa73367)
查看MediaServer端口情况，MediaServer没有正常启动udp接收端口
![image](https://github.com/user-attachments/assets/a02edee7-b2f7-450d-9e67-23d13137f26b)
拉了9月26号最新的代码，de7afaf992b16271d35f7a162bc0cb9695a02e9b，对着代码进行了测试
发现openRtpServer可以打开udp端口，但是rtsp拉udp流时无法正常启动端口
然后加了日志进行了对比，也测试了按照openrtpserver的方法，使用配置的ip启动rtsp拉udp的端口
![image](https://github.com/user-attachments/assets/d6410eeb-7c77-413e-9468-7a76a3c4d4e8)
从日志中可以看到，同一时间，rtsp启动的udp端口不存在，openrtpserver启动的端口能看到，底层方法都是调用的sockutil 的bindudpsock方法，除了端口其他的参数都是一样的
![image](https://github.com/user-attachments/assets/2278aec8-1b7a-4466-a0c0-5cb71cac19c2)

## 如何复现?
最新版MediaServer，也测试了半年前，一年前的版本，ubuntu16.04 x64笔记本，ubuntu18.04 x64服务器上均有该问题

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>
; auto-generated by mINI class {

[api]
apiDebug=1
defaultSnap=./www/logo.png
downloadRoot=./www
secret=abcd1234
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -i %s -y -f mjpeg -frames:v 1 -an %s

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
listen_ip=::
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_audio_track_data_ms=1000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=0
on_flow_report=
on_http_access=
on_play=
on_publish=
on_record_mp4=
on_record_ts=
on_rtp_server_timeout=
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=
on_server_exited=
on_server_keepalive=
on_server_started=
on_shell_login=
on_stream_changed=
on_stream_none_reader=
on_stream_not_found=
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=10

[http]
allow_cross_domains=1
allow_ip_range=
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:de7afaf/2024-09-26T10:59:41+08:00,branch:master,build time:2024-09-27T14:21:20)</center></body></html>
port=6603
rootPath=./www
sendBufSize=65536
sslport=4436
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=15000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
externIP=
maxRtpCacheMS=5000
maxRtpCacheSize=2048
max_bitrate=0
min_bitrate=0
nackIntervalRatio=1.0
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=6602
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5

; } ---

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
de7afaf992b16271d35f7a162bc0cb9695a02e9b
* **操作系统及版本**:
*NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

* **硬件信息**:
CPU: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz x 2
MEMORY: 
![image](https://github.com/user-attachments/assets/8d6ad612-b3c0-42a5-8faa-3c05d28b3184)
DISK:
![image](https://github.com/user-attachments/assets/708b7654-ff2d-43dd-ac2f-efda25de0715)

* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by PioLing** [comment]
Usually, you probably haven't enabled the firewall to allow the ports ?

**Comment by Newleep** [comment]
> Usually, you probably haven't enabled the firewall to allow the ports ?

![image](https://github.com/user-attachments/assets/369b770f-9fc7-4a42-873b-aed1e416f961)
没有开防火墙

**Comment by Newleep** [comment]
经过大量增加日志、抓包分析，最后发现ZLMediaKit接收udp流，会根据 rtsp replay中的server_port绑定udp的接收时的 发送端口
![lQDPJxlYLtbS8rfNAbDNAyqwG550Y6S1P_UG3pqGJV2EAw_810_432](https://github.com/user-attachments/assets/446c5cc1-594a-452f-9a39-b25157d6b02f)
但是实际发送端口并不是server_port中的端口，导致流媒体服务udp接收端口一直无法接收到数据
![lQDPJxyKumsfMrfNAYzNAyqwL1A5aeZgjz0G3pqGJV2EBA_810_396](https://github.com/user-attachments/assets/16374838-91e2-4501-ad8c-6c4ab734c38c)
暂时屏蔽bindpeeraddr后，能够正常接入rtsp udp流。
![lQDPKGxYKuFAk7fNAQnNAyqwcdPmUAoEWi4G3pqGJV2EAg_810_265](https://github.com/user-attachments/assets/2148b736-e575-4b0e-8da4-43f7521ef215)
![lQDPJxUUyhEX8rfNAWfNAyqwDUL1uGeTTGcG3pqGJV2EAA_810_359](https://github.com/user-attachments/assets/053fe4e6-835e-4688-9f6e-3f12b5072212)

**Comment by Newleep** [comment]
不是bug，可以修改下issue 类型
