### ISSUE TITLE
[BUG] addFFmpegSource Issue Feedback

### ISSUE THREAD

**Issue by zqs125** [ZLMediaKit/ZLMediaKit#3940]
## Phenomenon Description

需求：RTMP H265
环境：ffmpeg 7
现象：使用addFFmpegSource接口向服务端推rtmp h265的流，ffmpeg7的版本，所以是enhanced-rtmp模式的，为了兼容性，在服务端配置文件中对rtmp的配置为enhanced=0，我的理解是客户端播放器在播放时应该是enhanced=0的模式，可实际情况还是enhanced-rtmp模式，是我理解错了吗？

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

需求：RTMP H265
环境：ffmpeg 7
现象：使用addFFmpegSource接口向服务端推rtmp h265的流，ffmpeg7的版本，所以是enhanced-rtmp模式的，为了兼容性，在服务端配置文件中对rtmp的配置为enhanced=0，我的理解是客户端播放器在播放时应该是enhanced=0的模式，可实际情况还是enhanced-rtmp模式，是我理解错了吗？
## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
你需要把rtmp.directProxy设置为0才行 否则zlm直接代理rtmp
