### ISSUE TITLE
default.zlmediakit.com seems to have an expired certificate

### ISSUE THREAD

**Issue by lilei-John** [ZLMediaKit/ZLMediaKit#3941]
## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:
*2024-10-09 15:02:12.879 E [MediaServer] [39086-event poller 0] DtlsTransport.cpp:881 CheckStatus | OpenSSL error [desc:'SSL status: SSL_ERROR_SSL', error:'error:14102415:SSL routines:dtls1_read_bytes:sslv3 alert certificate expired']

>

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:
*2024-10-09 15:02:12.879 E [MediaServer] [39086-event poller 0] DtlsTransport.cpp:881 CheckStatus | OpenSSL error [desc:'SSL status: SSL_ERROR_SSL', error:'error:14102415:SSL routines:dtls1_read_bytes:sslv3 alert certificate expired']

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
这个是测试证书,并且已经过期了，你用你自己的证书就可以了

**Comment by xia-chu** [comment]
现在ssl免费证书只有3个月有效期 更新起来挺麻烦的
