### ISSUE TITLE
【Technical Inquiry】Is there an order for sending webhooks?

### ISSUE THREAD

**Issue by IOTWord** [ZLMediaKit/ZLMediaKit#3944]
I'd be happy to translate the text for you. Here is the translation:

请教下，web hook 的发送有没有顺序呢？比如 先流变化【流注销】后 在发录制视频事件

## 相关日志或截图

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## 配置

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git 提交哈希**：
* **操作系统和版本**：
* **硬件信息**：
* **崩溃回溯**：
```
#Paste the crash information backtrace here
```
* **其他需要补充的信息**：

Translation:

I have a question, is there an order for sending web hooks? For example, first sending the stream change [stream logout] and then sending the video recording event

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **Crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>
请教下，web hook 的发送有没有顺序呢？比如 先流变化【流注销】后 在发录制视频事件

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
有的看web hook ,wiki 上有的

**Comment by xia-chu** [comment]
有个hook_index的参数 这个判断hook的顺序 不过zlm本身就是多线程的 所以也没严格意思上的顺序
