### ISSUE TITLE
[BUG] low frame rate and stuck when using NVR to pull RTSP stream from ZLM 

### ISSUE THREAD

**Issue by BobDLA** [ZLMediaKit/ZLMediaKit#3955]
## Phenomenon Description

Using ZLM to serve MP4 file to RTSP stream. It works well when I directly use VLC to play the video stream.
However, when using Hikvision's NVR to pull the video stream. Even at the Hikvision NVR's playback, the recorded video stream is low frame rate and stuck.
Hikvision's NVR and the network are in a very lightly loaded state.
Is there something that needs to be specially set in the protocol or configuration file?

## How to reproduce?

on the media server, put the mp4 file under /data (mp4 in h264 1280x720 1s gop 1000k bitrate) and start the docker by
docker run -p 1935:1935 -p 8080:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp -v /data/:/opt/media/bin/www/record zlmediakit/zlmediakit:latest

using Hikvision NVR to read the stream by setting custom protocol to rtsp and specifying the resource path.
using VLC to open the ZLM stream, the stream is good
browser to the NVR video stream, the stream stuck several times in 1 minute.

## Related logs or screenshots

no detailed logs from ZLM side

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
using default config.ini
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

Using ZLM to serve MP4 file to RTSP stream. It works well when I directly use VLC to play the video stream.
However, when using Hikvision's NVR to pull the video stream. Even at the Hikvision NVR's playback, the recorded video stream is low frame rate and stuck.
Hikvision's NVR and the network are in a very lightly loaded state.
Is there something that needs to be specially set in the protocol or configuration file?

## 如何复现?

on the media server, put the mp4 file under /data (mp4 in h264 1280x720 1s gop 1000k bitrate) and start the docker by
docker run -p 1935:1935 -p 8080:80 -p 8443:443 -p 8554:554 -p 10000:10000 -p 10000:10000/udp -p 8000:8000/udp -p 9000:9000/udp -v /data/:/opt/media/bin/www/record zlmediakit/zlmediakit:latest

using Hikvision NVR to read the stream by setting custom protocol to rtsp and specifying the resource path.
using VLC to open the ZLM stream, the stream is good
browser to the NVR video stream, the stream stuck several times in 1 minute.

## 相关日志或截图

no detailed logs from ZLM side

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
using default config.ini
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
这个问题无法答复 因为海康的nvr是个黑河 无法得知它的行为逻辑。
或许它故意制造兼容性bug 也是可能的

**Comment by xia-chu** [comment]
这个问题无法答复 因为海康的nvr是个黑盒 无法得知它的行为逻辑
或许它故意制造兼容性bug 也是可能的

**Comment by BobDLA** [comment]
> This issue cannot be answered because Hikvision's NVR is a black box, and its behavior logic is unknown. Perhaps it intentionally creates compatibility bugs, which is also possible.
> 
> > 这个问题无法答复 因为海康的nvr是个黑盒 无法得知它的行为逻辑
> > 或许它故意制造兼容性bug 也是可能的
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

Yes, I even can't get the logs from the NVR side.So it's difficult to debug. 
Do you have any technical note for config.ini  about how to optimize the RTSP stream?
I see lots of configure items. for example:
lowLatency
buffer
Mtu

Will this setting impact the compibility?


Thanks

**Comment by xia-chu** [comment]
你可以修改下 record.sampleMS 为30 试试
