### ISSUE TITLE
[BUG] Displaying trailing and mosaic when watching WebRTC on Linux desktop systems of various distributions

### ISSUE THREAD

**Issue by tonygatescxp** [ZLMediaKit/ZLMediaKit#3959]
## Phenomenon Description
Experimental client environment
Operating System: Deepin 23 official version, Fedora 40, Ubuntu 22.04
Browser: Latest Google Chrome browser
Experimental server environment
Operating System: Ubuntu 22.04, Unified UOS Server 1070e, CentOS
CPU: Intel i5 13th generation
ZLMedia version: Compile date: 2024-10-13T00:37:08, Current git branch: master, Current git hash value: 61a93fa
SRS version: v6.0.113

Scenario premise: Drone pushes stream to ZLMedia via RTMP, VLC plays smoothly without lag or mosaic using RTMP or RTSP

Problem:
Browser uses WebRTC to watch ZLMedia's video, the picture keeps appearing with mosaic and lag issues, about 3 seconds later the picture recovers and becomes clear, and then repeats the lag
The same browser uses WebRTC to watch SRS's video, the picture is smooth and clear

Since SRS 6.0 is involved in the experiment, use the same ffmpeg command to re-push the stream:
1. From ZLMedia to ZLMedia (IP: x.x.x.150):
ffmpeg -i rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv rtmp://x.x.x.150/live/testlive
2. From ZLMedia to SRS (IP: x.x.x.248):
ffmpeg -i rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv rtmp://x.x.x.248/live/testlive

![image](https://github.com/user-attachments/assets/b3c9c323-6f8a-4aad-afb0-2009fa84e7f6)
![image](https://github.com/user-attachments/assets/4ad72f3d-bfee-4053-8331-97dbd4f571df)

The following is the information printed during the push stream
![image](https://github.com/user-attachments/assets/16544e34-09d9-4d1c-8785-248a7063d84a)

In addition, when using ffmpeg -i to pull the stream via RTMP, ffmpeg keeps printing warning messages, and the push stream fails
<img width="461" alt="Enterprise WeChat screenshot_e04ca643-8f74-4a6e-9681-10c6fe98b25a" src="https://github.com/user-attachments/assets/b2f7547c-5f20-4dc9-9fae-1ff808c81be4">

## How to reproduce?
Here, use ZLMedia to receive the video stream of the second-generation drone airport, use the Linux desktop system to watch the video, and you can reproduce the problem
Hope to solve the WebRTC lag issue

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
实验的客户端环境
操作系统：Deepin 23 正式版、Fedora 40、Ubuntu 22.04
浏览器：最新Google Chrome浏览器
实验的服务器环境
操作系统：Ubuntu 22.04、统信UOS Server 1070e、CentOS
CPU：Intel i5 13代
ZLMedia版本：编译日期: 2024-10-13T00:37:08、当前git分支: master、当前git hash值: 61a93fa
SRS版本：v6.0.113

场景前提：无人机通过 RTMP 推流至 ZLMedia，VLC使用RTMP或RTSP播放时，画面流畅无拖影无马赛克

问题：
浏览器使用WebRTC观看ZLMedia的视频，画面不断出现马赛克及拖影问题，大概3秒后画面恢复清晰并重新一轮拖影。
相同浏览器使用WebRTC观看 SRS 的视频，画面流畅清晰

由于有SRS 6.0参与实验，因此使用相同的 ffmpeg 命令重新推流：
1、由 ZLMedia推回 ZLMedia（IP：x.x.x.150）：
ffmpeg -i rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv rtmp://x.x.x.150/live/testlive
2、由 ZLMedia推向 SRS （IP：x.x.x.248）：
ffmpeg -i rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv rtmp://x.x.x.248/live/testlive

![image](https://github.com/user-attachments/assets/b3c9c323-6f8a-4aad-afb0-2009fa84e7f6)
![image](https://github.com/user-attachments/assets/4ad72f3d-bfee-4053-8331-97dbd4f571df)

以下是推流时打印出来的信息
![image](https://github.com/user-attachments/assets/16544e34-09d9-4d1c-8785-248a7063d84a)

另外，ffmpeg -i 使用RTMP拉流时，ffmpeg不断打印出告警信息，且推流是失败的
<img width="461" alt="企业微信截图_e04ca643-8f74-4a6e-9681-10c6fe98b25a" src="https://github.com/user-attachments/assets/b2f7547c-5f20-4dc9-9fae-1ff808c81be4">

## 如何复现?
这里使用ZLMedia接收大疆二代机场无人机的视频流，使用Linux各发行版的桌面系统观看视频，即可复现该问题
希望能解决WebRTC拖影的问题

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
上传一段可以复现此问题的视频

**Comment by xia-chu** [comment]
rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U 这个是什么链接？无人机的播放链接吗

**Comment by tonygatescxp** [comment]
rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U 这是无人机推进来的视频。

**Comment by tonygatescxp** [comment]
@xiongguangjie 
保存视频  ffmpeg -i rtmp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv /data/rtmp_flight.mp4
反推回ZLMedia命令  ffmpeg -re -i ./rtmp_flight.mp4 -c copy -f flv rtmp://x.x.x.150/live/testlive

这个视频文件推回去后，拖影问题可以复现，文件70M太大，已放在网盘，链接有效期30天，请尽快下载

链接: https://pan.baidu.com/s/1Lu_ZdAQ4SyUjV9IbGY5JKQ?pwd=dy5y 提取码: dy5y

**Comment by xiongguangjie** [comment]
> @xiongguangjie Save video ffmpeg -i rtmp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv /data/rtmp_flight.mp4 Push back to ZLMedia command ffmpeg -re -i ./rtmp_flight.mp4 -c copy -f flv rtmp://x.x.x.150/live/testlive
> 
> After pushing this video file back, the dragging shadow problem can be reproduced. The file is 70M and too large, it has been uploaded to the network disk, the link is valid for 30 days, please download as soon as possible
> 
> Link: https://pan.baidu.com/s/1Lu_ZdAQ4SyUjV9IbGY5JKQ?pwd=dy5y Extraction code: dy5y
> 
> > @xiongguangjie
> > 保存视频  ffmpeg -i rtmp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c copy -f flv /data/rtmp_flight.mp4
> > 反推回ZLMedia命令  ffmpeg -re -i ./rtmp_flight.mp4 -c copy -f flv rtmp://x.x.x.150/live/testlive
> 
> 这个视频文件推回去后，拖影问题可以复现，文件70M太大，已放在网盘，链接有效期30天，请尽快下载
> 
> 链接: https://pan.baidu.com/s/1Lu_ZdAQ4SyUjV9IbGY5JKQ?pwd=dy5y 提取码: dy5y
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

你不能上传到蓝奏云之类的地方吗（免登陆的）， 你这个需要登录

**Comment by tonygatescxp** [comment]
https://wwnc.lanzouo.com/ikg682d3jt2j   密码:cowi

**Comment by xiongguangjie** [comment]
> @xiongguangjie
> 
> https://wwnc.lanzouo.com/ikg682d3jt2j Password: cowi
> 
> > https://wwnc.lanzouo.com/ikg682d3jt2j   密码:cowi
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我这边用最新的代码试过了，没问题，我的推流命令是
.\ffmpeg.exe -re -stream_loop -1  -i  rtmp_flight.mp4  -c:v copy  -c:a copy   -f flv   rtmp://192.168.x.x/live/test

**Comment by tonygatescxp** [comment]
> > @xiongguangjie
> > https://wwnc.lanzouo.com/ikg682d3jt2j Password: cowi
> > > https://wwnc.lanzouo.com/ikg682d3jt2j   密码:cowi
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 我这边用最新的代码试过了，没问题，我的推流命令是 .\ffmpeg.exe -re -stream_loop -1 -i rtmp_flight.mp4 -c:v copy -c:a copy -f flv rtmp://192.168.x.x/live/test

你用于观看视频的操作系统是Deepin、CentOS、Ubuntu 这类的吗？ Windows和MacOS下都不会有拖影。
试了你提供的参数，类Linux桌面系统仍然有拖影和马赛克情况。

**Comment by tonygatescxp** [comment]
> > @xiongguangjie
> > https://wwnc.lanzouo.com/ikg682d3jt2j Password: cowi
> > > https://wwnc.lanzouo.com/ikg682d3jt2j   密码:cowi
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 我这边用最新的代码试过了，没问题，我的推流命令是 .\ffmpeg.exe -re -stream_loop -1 -i rtmp_flight.mp4 -c:v copy -c:a copy -f flv rtmp://192.168.x.x/live/test

今天又研究了一下，使用 264编码，并添加 -bf 0 参数后反推回 zlmedia ，马赛克和拖影不见了
ffmpeg -i rtsp://x.x.x.150/live/FlightLive/1xxxxx241N00CN18U -c:v libx264 -bf 0 -f flv rtmp://x.x.x.150/live/testlive

但就是麻烦，得自己外加一个命令从 zlmedia 拉出来再推回去，zlmedia要是自己能解决就更好了

**Comment by xiongguangjie** [comment]
> 你用于观看视频的操作系统是Deepin、CentOS、Ubuntu 这类的吗？ Windows和MacOS下都不会有拖影。

我是windows 系统，我认为这个不是ZLM的原因，我认为是浏览器的兼容性问题，你把浏览器的硬件解码选项关掉试试吧

**Comment by tonygatescxp** [comment]
提供了这么详细的信息，问题已经很明显的，也不解决吗？😅

**Comment by xia-chu** [comment]
webrtc不支持b帧，zlm没有去除b帧 但是srs有去除 这个应该是原因吧

**Comment by xia-chu** [comment]
首先你这视频本身就有问题，ffmpeg一堆警告日志：
<img width="503" alt="image" src="https://github.com/user-attachments/assets/0f5e62f2-4f63-4727-8e19-fdae43a6d677">
其次 我使用以下命令推流给zlm：
```
ffmpeg -re -i /path/to/rtmp_flight.mp4 -c copy -f flv rtmp://127.0.0.1/live/test
```

然后webrtc播放，效果还行，只有非常细微的拖影

**Comment by xia-chu** [comment]
这是我在Ubuntu下的播放效果
<img width="664" alt="image" src="https://github.com/user-attachments/assets/8f97f4be-2a82-4946-b39a-ff7bdcaa613b">

**Comment by tonygatescxp** [comment]
是的，视频是由大疆无人机推过来，受其限制我们也无法改变视频源的问题。

我们现在的临时解决方法是用 Shell脚本 不断地刷  ZLMedia 接口，发现有无人机视频推送，立马起个 ffmpeg -bf 0 重新拉出来再推成另外一个视频流，但存在大概1.5秒的延迟。

就是希望能直接从ZLMedia上解决这个问题

**Comment by xia-chu** [comment]
zlm在转发webrtc时未做b帧移除 后面可以考虑下是否添加下

**Comment by xia-chu** [comment]
这是b帧移除后的效果
```c++
srs_error_t SrsSample::parse_bframe()
{
    srs_error_t err = srs_success;

    uint8_t header = bytes[0];
    SrsAvcNaluType nal_type = (SrsAvcNaluType)(header & kNalTypeMask);

    if (nal_type != SrsAvcNaluTypeNonIDR && nal_type != SrsAvcNaluTypeDataPartitionA && nal_type != SrsAvcNaluTypeIDR) {
        return err;
    }

    SrsBuffer* stream = new SrsBuffer(bytes, size);
    SrsAutoFree(SrsBuffer, stream);

    // Skip nalu header.
    stream->skip(1);

    SrsBitBuffer bitstream(stream);
    int32_t first_mb_in_slice = 0;
    if ((err = srs_avc_nalu_read_uev(&bitstream, first_mb_in_slice)) != srs_success) {
        return srs_error_wrap(err, "nalu read uev");
    }

    int32_t slice_type_v = 0;
    if ((err = srs_avc_nalu_read_uev(&bitstream, slice_type_v)) != srs_success) {
        return srs_error_wrap(err, "nalu read uev");
    }
    SrsAvcSliceType slice_type = (SrsAvcSliceType)slice_type_v;

    if (slice_type == SrsAvcSliceTypeB || slice_type == SrsAvcSliceTypeB1) {
        bframe = true;
        srs_verbose("nal_type=%d, slice type=%d", nal_type, slice_type);
    }

    return err;
}
```

**Comment by TaterCheng** [comment]
Has the code to delete B frames been added to the latest version? I have the same problem.

**Comment by TaterCheng** [comment]
Has the code to remove B-frames been added to the latest version? I have the same problem.

**Comment by xia-chu** [comment]
> Has the code to remove B-frames been added to the latest version? I have the same problem.

No

**Comment by TaterCheng** [comment]
1、请问最近有添加这个功能的计划吗？
2、我检查过rtmp://192.168.0.120:1935/live/1581F6Q8D246C00G2VNH-81-0-0的帧类型，没有B帧，但是我通过下面命令转发后确实没有拖影了，原来的流没有B帧，推流后通过webrtc播放有拖影是为什么？
ffmpeg -i rtmp://192.168.0.120:1935/live/1581F6Q8D246C00G2VNH-81-0-0 -c:v libx264 -bf 0 -c:a copy -f flv rtmp://192.168.0.120:1935/live/test

C:\Users\ZF\Desktop\ffmpeg>ffmpeg -i rtmp://192.168.0.120:1935/live/1581F6Q8D246C00G2VNH-81-0-0 -vf "showinfo" -f null - 2>&1 | findstr  "type"
  configuration: --enable-gpl --enable-version3 --enable-shared --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   0 pts:      0 pts_time:0       pos:      526 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:1 type:I checksum:52031743 plane_checksum:[31B0A8A9 235CE905 9D878577] mean:[129 116 138] stdev:[38.9 12.7 7.4]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   1 pts:     60 pts_time:0.06    pos:    17908 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:EE973603 plane_checksum:[28F0B67F D4BB578F FE6A27E6] mean:[130 116 137] stdev:[38.8 12.8 7.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   2 pts:     91 pts_time:0.091   pos:    20820 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:AC4F5E6B plane_checksum:[2D3E99C0 24668225 1A7D4277] mean:[131 116 137] stdev:[38.3 12.7 7.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   3 pts:    121 pts_time:0.121   pos:    25463 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:76FBFFE9 plane_checksum:[F266A8AF 46D91CDB 64B93A5F] mean:[132 116 137] stdev:[37.8 12.8 7.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   4 pts:    151 pts_time:0.151   pos:    29442 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:1AF09F18 plane_checksum:[B01C7E8B E2022128 9671FF56] mean:[132 116 137] stdev:[37.6 12.8 7.6]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   5 pts:    181 pts_time:0.181   pos:    32067 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:30F9DD72 plane_checksum:[4970BCAF F142ACF3 CEEF73C1] mean:[133 117 138] stdev:[37.5 12.8 8.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   6 pts:    211 pts_time:0.211   pos:    35876 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:A26307B8 plane_checksum:[AFC87BA6 F5FF3DFF 96694E04] mean:[133 122 140] stdev:[37.5 11.9 12.4]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   7 pts:    242 pts_time:0.242   pos:    40653 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:20F05063 plane_checksum:[DAC4717D 4524015B 2143DD7C] mean:[133 124 140] stdev:[37.7 11.2 12.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   8 pts:    302 pts_time:0.302   pos:    44881 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:AB5B86FE plane_checksum:[43925FCC A169C6A2 77456081] mean:[133 124 139] stdev:[38.1 11.4 12.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:   9 pts:    302 pts_time:0.302   pos:    49602 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:5100875B plane_checksum:[93E05ED4 6E38AAD2 21007DA6] mean:[132 125 137] stdev:[38.4 11.4 9.8]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  10 pts:    363 pts_time:0.363   pos:    54279 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:7CEEC0E2 plane_checksum:[056FBBE2 6D088C98 36557859] mean:[132 125 136] stdev:[38.8 11.3 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  11 pts:    393 pts_time:0.393   pos:    58894 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:9772DFCA plane_checksum:[360507D8 87CD2DC4 6029AA2E] mean:[131 125 136] stdev:[39.1 11.3 7.0]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  12 pts:    423 pts_time:0.423   pos:    63546 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:52CCAC54 plane_checksum:[985FD7B2 0E8D8D18 C74B477B] mean:[131 125 135] stdev:[39.4 11.3 7.0]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  13 pts:    453 pts_time:0.453   pos:    67665 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:6FE3C1EB plane_checksum:[470E062C E4264848 54F47377] mean:[131 121 134] stdev:[39.6 11.7 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  14 pts:    484 pts_time:0.484   pos:    72277 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:FC474901 plane_checksum:[7A8859FC 5041769D D8507859] mean:[131 116 132] stdev:[39.7 13.6 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  15 pts:    514 pts_time:0.514   pos:    76811 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:DA01CB78 plane_checksum:[D1ED7E32 230A9E82 A390AEB5] mean:[131 116 132] stdev:[39.8 14.0 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  16 pts:    544 pts_time:0.544   pos:    80399 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:9E7A0E81 plane_checksum:[DA612171 382ED417 AD0918EA] mean:[131 116 132] stdev:[39.9 13.9 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  17 pts:    575 pts_time:0.575   pos:    84076 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:5503DEB8 plane_checksum:[11E9601B F687F5C4 26D188CA] mean:[132 116 132] stdev:[39.9 13.9 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  18 pts:    605 pts_time:0.605   pos:    87460 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:E7C26E62 plane_checksum:[AE9FD53B 6D9C0A5F F61F8EB9] mean:[132 116 132] stdev:[39.8 13.9 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  19 pts:    665 pts_time:0.665   pos:    92151 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:4E861180 plane_checksum:[DF533F9F 30BC7016 9EAD61BC] mean:[132 116 131] stdev:[39.9 13.9 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  20 pts:    695 pts_time:0.695   pos:    95643 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:2BE1D55C plane_checksum:[08C672C0 14E524A3 2C703DF9] mean:[132 117 132] stdev:[40.0 13.8 7.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  21 pts:    696 pts_time:0.696   pos:   100390 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:8D074CED plane_checksum:[DBCA13E3 4358CBBC 39AD6D3F] mean:[133 121 134] stdev:[40.2 12.7 11.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  22 pts:    756 pts_time:0.756   pos:   105247 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:B4DFB546 plane_checksum:[1E3D1979 AB682E90 CBFC6D3D] mean:[133 123 134] stdev:[40.3 11.9 11.5]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  23 pts:    786 pts_time:0.786   pos:   109694 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:598AF6EC plane_checksum:[5603C4C8 D8C5EFD2 22024243] mean:[133 123 134] stdev:[40.5 12.0 11.6]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  24 pts:    816 pts_time:0.816   pos:   113349 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:BF5BD1E4 plane_checksum:[C1EDC126 979DBEC8 2EF351E7] mean:[132 123 133] stdev:[40.7 12.0 9.6]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  25 pts:    847 pts_time:0.847   pos:   117569 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:56B529C8 plane_checksum:[6B67DDBA BF62AA3E F192A1B2] mean:[132 124 131] stdev:[40.7 11.9 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  26 pts:    877 pts_time:0.877   pos:   121727 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:8D061FA8 plane_checksum:[0D267CF0 FB214C0E A50C569B] mean:[131 124 131] stdev:[40.8 11.8 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  27 pts:    907 pts_time:0.907   pos:   125960 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:FEE8E55C plane_checksum:[18731F66 DED1B81A 90980DDC] mean:[131 124 131] stdev:[40.9 11.8 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  28 pts:    937 pts_time:0.937   pos:   130190 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:01AF19DC plane_checksum:[BDCCA2C1 92D58413 951EF2EA] mean:[130 121 131] stdev:[40.8 12.2 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  29 pts:    998 pts_time:0.998   pos:   134949 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:3BB3620D plane_checksum:[926CD464 61AF90F7 6772FC94] mean:[129 118 131] stdev:[40.8 13.7 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  30 pts:    998 pts_time:0.998   pos:   139563 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:1 type:I checksum:4430B4BD plane_checksum:[08987F4E 9CD6B94D D6FD7C13] mean:[128 118 132] stdev:[40.8 13.7 7.1]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  31 pts:   1058 pts_time:1.058   pos:   160378 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:E733EF41 plane_checksum:[799CBE50 9101E952 951C4790] mean:[128 118 132] stdev:[40.8 13.7 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  32 pts:   1088 pts_time:1.088   pos:   163084 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:DA8D4BAC plane_checksum:[79D7F32E B7CD395A CA061F15] mean:[128 118 132] stdev:[40.8 13.6 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  33 pts:   1119 pts_time:1.119   pos:   166680 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:40809E1D plane_checksum:[89BC970C CB9FA60C E64660F6] mean:[128 118 132] stdev:[40.9 13.6 7.2]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  34 pts:   1149 pts_time:1.149   pos:   170686 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:5261CB4B plane_checksum:[3171198E A3264B10 CE9866AD] mean:[128 118 132] stdev:[40.9 13.5 7.4]
[Parsed_showinfo_0 @ 000002376a63bdc0] n:  35 pts:   1179 pts_time:1.179   pos:   175029 fmt:yuv420p sar:0/1 s:1280x720 i:P iskey:0 type:P checksum:089B658F plane_checksum:[30B7CFB4 1CB0ACCF 2CEFE8EE] mean:[128 120 135] stdev:[41.0 13.2 8.6]
