### ISSUE TITLE
[BUG] When playing flv format live streaming, it prompts that flv player generally only supports H264 and AAC encoding, and the encoding format may not be supported by the player: H265 PCMA

### ISSUE THREAD

**Issue by 199212zz** [ZLMediaKit/ZLMediaKit#3962]
## Phenomenon Description

Currently, many models of Hikvision devices have been connected, and it has been found that some models of devices are always loading when playing live video, with the ZLM log indicating "flv player generally only supports H264 and AAC encoding, this encoding format may not be supported by the player: H265 PCMA". The liveplayer player is used, and the flv stream address is used. Please ask how to handle this, is there a problem with the configuration?

## How to reproduce?

Occurs randomly, the same camera can sometimes play and sometimes not. When it can't play, ZLM will report these descriptions. It's not clear whether this is related to the inability to play.

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

目前对接了很多型号的海康设备,发现部分型号设备播放直播的时候一直加载中,ZLM日志提示"flv播放器一般只支持H264和AAC编码,该编码格式可能不被播放器支持:H265 PCMA"，是用的liveplayer播放器，用的flv流地址，请问下这个该如何处理，是不是配置上有问题

## 如何复现?

随机发生,同一个摄像头有时候能播.有时候不能播.不能播的时候ZLM就会报这些描述.不知道是否跟不能播有关系

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
如果播放一切正常，忽略就行了，否则就换支持h265与pcma 播放的web播放器，如jessbuca 等
