### ISSUE TITLE
[BUG] Using WebRTC for streaming/playback, enabling data channel, unable to receive messages

### ISSUE THREAD

**Issue by abhello** [ZLMediaKit/ZLMediaKit#3963]
## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by abhello** [comment]
使用webrtc推流/播放，无法发送消息。
设置 usedatachannel: true 启用数据通道，调用 player.sendMsg(‘这是发送的消息’）发送消息，其中发送端在“player.on(ZLMRTCClient.Events.WEBRTC_ON_DATA_CHANNEL_MSG,function(event)）” 能输出消息，但是在接收端无法接收

**Comment by xia-chu** [comment]
要把推流端消息广播到播放端需要稍微修改下代码才行 默认不是这种行为

**Comment by abhello** [comment]
> To broadcast the push stream message to the playback end, you need to modify the code slightly. This is not the default behavior.
> 
> > 要把推流端消息广播到播放端需要稍微修改下代码才行 默认不是这种行为
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

方便指导一下吗？万分感谢

**Comment by xia-chu** [comment]
```patch
Index: webrtc/WebRtcPusher.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/webrtc/WebRtcPusher.cpp b/webrtc/WebRtcPusher.cpp
--- a/webrtc/WebRtcPusher.cpp	(revision 6ecd139b50bb00f1f1671d24c5b1e80824ef2645)
+++ b/webrtc/WebRtcPusher.cpp	(date 1729499449559)
@@ -175,4 +175,15 @@
      WebRtcTransportImp::onShutdown(ex);
 }
 
+#ifdef ENABLE_SCTP
+void WebRtcTransport::OnSctpAssociationMessageReceived(RTC::SctpAssociation *sctpAssociation, uint16_t streamId, uint32_t ppid, const uint8_t *msg, size_t len) {
+    if (_push_src) {
+        toolkit::Any any;
+        Buffer::Ptr buffer = std::make_shared<BufferLikeString>(std::string((char *)msg, len));
+        any.set(std::move(buffer));
+        _push_src->getRing()->sendMessage(any);
+    }
+}
+#endif
+
 }// namespace mediakit
\ No newline at end of file
Index: webrtc/WebRtcPusher.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/webrtc/WebRtcPusher.h b/webrtc/WebRtcPusher.h
--- a/webrtc/WebRtcPusher.h	(revision 6ecd139b50bb00f1f1671d24c5b1e80824ef2645)
+++ b/webrtc/WebRtcPusher.h	(date 1729499449557)
@@ -34,6 +34,10 @@
     // //  dtls related callbacks ////
     void OnDtlsTransportClosed(const RTC::DtlsTransport *dtlsTransport) override;
 
+#ifdef ENABLE_SCTP
+    void OnSctpAssociationMessageReceived(RTC::SctpAssociation *sctpAssociation, uint16_t streamId, uint32_t ppid, const uint8_t *msg, size_t len) override;
+#endif
+
 protected:
     ///////MediaSourceEvent override///////
     // 关闭  [AUTO-TRANSLATED:92392f02]
```

**Comment by abhello** [comment]
> ```diff
> Index: webrtc/WebRtcPusher.cpp
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/webrtc/WebRtcPusher.cpp b/webrtc/WebRtcPusher.cpp
> --- a/webrtc/WebRtcPusher.cpp	(revision 6ecd139b50bb00f1f1671d24c5b1e80824ef2645)
> +++ b/webrtc/WebRtcPusher.cpp	(date 1729499449559)
> @@ -175,4 +175,15 @@
>       WebRtcTransportImp::onShutdown(ex);
>  }
>  
> +#ifdef ENABLE_SCTP
> +void WebRtcTransport::OnSctpAssociationMessageReceived(RTC::SctpAssociation *sctpAssociation, uint16_t streamId, uint32_t ppid, const uint8_t *msg, size_t len) {
> +    if (_push_src) {
> +        toolkit::Any any;
> +        Buffer::Ptr buffer = std::make_shared<BufferLikeString>(std::string((char *)msg, len));
> +        any.set(std::move(buffer));
> +        _push_src->getRing()->sendMessage(any);
> +    }
> +}
> +#endif
> +
>  }// namespace mediakit
> \ No newline at end of file
> Index: webrtc/WebRtcPusher.h
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/webrtc/WebRtcPusher.h b/webrtc/WebRtcPusher.h
> --- a/webrtc/WebRtcPusher.h	(revision 6ecd139b50bb00f1f1671d24c5b1e80824ef2645)
> +++ b/webrtc/WebRtcPusher.h	(date 1729499449557)
> @@ -34,6 +34,10 @@
>      // //  dtls related callbacks ////
>      void OnDtlsTransportClosed(const RTC::DtlsTransport *dtlsTransport) override;
>  
> +#ifdef ENABLE_SCTP
> +    void OnSctpAssociationMessageReceived(RTC::SctpAssociation *sctpAssociation, uint16_t streamId, uint32_t ppid, const uint8_t *msg, size_t len) override;
> +#endif
> +
>  protected:
>      ///////MediaSourceEvent override///////
>      // 关闭  [AUTO-TRANSLATED:92392f02]
> ```

非常感谢您耐心的回答。请问有没有编译好的，这个语言不会

**Comment by xia-chu** [comment]
> 请问有没有编译好的，这个语言不会

不会就学，看wiki快速开始。
这个补丁需要你自己打上再编译，哪来已经编译好的？windows、linux、macos那么多平台，怎么可能给你手动编译嘛？
