### ISSUE TITLE
[Feature Request] 
需求描述(必填) 
录制音频的分贝曲线

Translated to English:

[Feature Request] 
Requirement Description (Required) 
Recording Audio Decibel Curve

### ISSUE THREAD

**Issue by lexang** [ZLMediaKit/ZLMediaKit#3971]
## Describe the purpose of this feature, and provide relevant information to describe this feature
A feature needs to be implemented to obtain the decibel data of the audio during recording, and then display the decibel curve on the frontend. One possible approach I can think of is to pull the stream and try to obtain the decibel data in my code, but this way it would not be associated with the recording file. Please ask if there is a way to achieve this.

## Is this feature used to improve project defects? If so, please describe the existing defects
No
## Describe how you expect to achieve this feature and the final effect

>## 描述该功能的用处，可以提供相关资料描述该功能
需要实现一个功能  在录制的时候获取音频的分贝数据 然后前端展示分贝曲线  我能想到的是把流拉取然后在我的代码里面试试获取分贝数据 但是这样跟录音文件就不关联了 请问有什么办法可以实现 

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
否
## 描述你期望实现该功能的方式和最终效果

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
这个你用个使用容器格式比较好 你要同时保留音频分贝值以及时间戳。

**Comment by lexang** [comment]
> It's better for you to use a container format. You want to keep both the audio decibel value and the timestamp at the same time.
> 
> > 这个你用个使用容器格式比较好 你要同时保留音频分贝值以及时间戳。
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

没明白。。。

**Comment by xia-chu** [comment]
私有容器 抱歉。

**Comment by lexang** [comment]
> Private Container Sorry.
> 
> > 私有容器 抱歉。
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

还是不懂 不知道你说的时候什么

**Comment by xiongguangjie** [comment]
参考这个https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Visualizations_with_Web_Audio_API#basic_concepts
