### ISSUE TITLE
[BUG]  using RTP to push streams, only receives audio data, but does not parse video data.

### ISSUE THREAD

**Issue by sling2007** [ZLMediaKit/ZLMediaKit#3972]
## Phenomenon Description
Calling Huawei IVS video platform (uniformly using rtsp transmission in h264 format), zlmediakit's stream pulling and playback are normal.
However, when IVS pushes streams to zlmediakit's rtp 10000 port, zlmediakit's console only sees audio data, but no video data.
Only video is needed in the business.

IVS's request and response are as follows.
zlmediakit's page and 10000 port packet capture are also as follows.
zlmediakit configuration is at the end.

## How to reproduce?

Expect to parse out video data and play successfully.

## Related logs or screenshots
Postman request to IVS return:
![image](https://github.com/user-attachments/assets/4823f192-ab9d-48fd-8fcc-40e2ee181afb)

zlmediakit monitoring page: only audio, no video
![image](https://github.com/user-attachments/assets/c4f71e5b-e784-4baa-b133-182187f39623)

Wireshark port monitoring:
![image](https://github.com/user-attachments/assets/4737a112-da52-44dd-bc76-904d2ae4138f)

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

RTP and RTSP related configurations are as follows.
[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1500

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=99
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=99
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=0
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
调用华为IVS视频平台(统一使用了rtsp传输的h264格式)，zlmediakit的拉流、播放正常。
但从IVS推流到zlmediakit的rtp 10000端口时，zlmediakit控制台只看到了audio数据，没有video数据。
业务中只需要video即可。

IVS的请求和响应，如下图所示。
zlmediakit的页面和10000端口抓包，也如下图。
zlmediakit配置见最后。

## 如何复现?

期望能解析出video数据，并播放成功。

## 相关日志或截图
postman中请求IVS的返回：
![image](https://github.com/user-attachments/assets/4823f192-ab9d-48fd-8fcc-40e2ee181afb)

zlmediakit的监控页面：只有audio，没有video
![image](https://github.com/user-attachments/assets/c4f71e5b-e784-4baa-b133-182187f39623)

wireshark的端口监控：
![image](https://github.com/user-attachments/assets/4737a112-da52-44dd-bc76-904d2ae4138f)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

RTP和RTSP的相关配置，如下图。
[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1500

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=99
h265_pt=99
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=99
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=0
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by sling2007** [comment]
zlmediakit中，接收audio和video的端口都是10000，这个对吗？   
我试过把audio改成30010，但这样也解析不到视频。

**Comment by xia-chu** [comment]
请提供下zlm的日志和版本号

**Comment by sling2007** [comment]
zlm的版本号：   分支：master 构建时间: 2024-04-21T06:43:54 版本: 664d0b6
zml的日志如下（其余重复刷屏的没有贴出来）

2024-10-24 13:44:12.252 T [MediaServer] [1-event poller 33] UdpServer.h:40 operator() | 8559-588(10.101.25.204:17784) mediakit::RtpSession
2024-10-24 13:44:12.252 W [MediaServer] [1-event poller 23] UdpServer.cpp:170 onRead_l | UDP packet incoming from other thread
2024-10-24 13:44:12.252 W [MediaServer] [1-event poller 23] UdpServer.cpp:170 onRead_l | UDP packet incoming from other thread
    Last message repeated 9 times
2024-10-24 13:44:12.252 I [MediaServer] [1-event poller 33] RtpProcess.cpp:269 operator() | 00000000(10.101.25.204:17784) 允许RTP推流
2024-10-24 13:44:12.252 W [MediaServer] [1-event poller 33] H265Rtp.cpp:215 decodeRtp | 不支持该类型的265 RTP包, nal type51, rtp:
version:2
padding:0
ext:20
csrc:0
mark:0
pt:99
seq:1
stamp:3386346273
ssrc:0
rtp size:52
payload offset:24
payload size:16

2024-10-24 13:44:12.252 W [MediaServer] [1-event poller 33] H265Rtp.cpp:215 decodeRtp | 不支持该类型的265 RTP包, nal type52, rtp:
version:2
padding:0
ext:20
csrc:0
mark:0
pt:99
seq:2
stamp:3386346273
ssrc:0
rtp size:41
payload offset:24
payload size:5



2024-10-24 13:44:12.291 W [MediaServer] [1-event poller 33] H265Rtp.cpp:90 unpackAp | invalid rtp data size:613 < 16384,rtp:
version:2
padding:0
ext:20
csrc:0
mark:1
pt:99
seq:14
stamp:3386353479
ssrc:0
rtp size:653
payload offset:24
payload size:617

2024-10-24 13:44:12.311 W [MediaServer] [1-event poller 33] H265Rtp.cpp:90 unpackAp | invalid rtp data size:651 < 24576,rtp:
version:2
padding:0
ext:20
csrc:0
mark:1
pt:99
seq:15
stamp:3386357073
ssrc:0
rtp size:691
payload offset:24
payload size:655

**Comment by sling2007** [comment]
另外用VLC的sdp文件，是可以在VLC里播放这个推流的。   （去掉audio，只保留video也是可以播放的。）

```
m=video 21202 RTP/AVP 99
a=rtpmap:99 H264
m=audio 21203 RTP/AVP 0  
a=rtpmap:0 PCMU/8000
a=framerate:25
c=IN IP4 10.101.59.170

```

所以帮忙看一下，是我在zlm哪里配置错了？    还是需要升级版本呢？     还是这个推流的数据格式有问题呢？

**Comment by xia-chu** [comment]
zlm的端口 虽然可以接收es流 但是不支持一个端口收多路es流。

**Comment by xia-chu** [comment]
你可以用两个端口分别接收音视频流 不过zlm不会把他们合并为一个流

**Comment by sling2007** [comment]
多谢回复和建议。刚测了一下，
1、使用zlm的10000端口接收video，  30001接收audio， 推流配置如下：
![image](https://github.com/user-attachments/assets/ff376d1d-97d2-43cd-8f31-33c9beb93a86)
2、目前zlm的监控页面上，看不到任何流了。
3、但是wireshark上还能看见，10000端口收到的UDP数据包。
4、zlm日志里报的错误和昨天类似，分别是“不支持该类型的265 RTP包”和“unpackAp | invalid rtp data size:651 < 24576,rtp:”。

所以有没有别的思路让我可以试试，比如配置zlm里的rtp size？   比如用ffmpeg先处理，再转到zlm？

日志如下：
2024-10-25 09:28:51.199 T [MediaServer] [1-event poller 26] UdpServer.h:40 operator() | 11539-589(10.101.25.204:17800) mediakit::RtpSession
2024-10-25 09:28:51.199 W [MediaServer] [1-event poller 14] UdpServer.cpp:170 onRead_l | UDP packet incoming from other thread
2024-10-25 09:28:51.199 W [MediaServer] [1-event poller 14] UdpServer.cpp:170 onRead_l | UDP packet incoming from other thread^M
    Last message repeated 8 times
2024-10-25 09:28:51.200 I [MediaServer] [1-event poller 26] RtpProcess.cpp:269 operator() | 00000000(10.101.25.204:17800) 允许RTP推流
2024-10-25 09:28:51.200 W [MediaServer] [1-event poller 26] H265Rtp.cpp:215 decodeRtp | 不支持该类型的265 RTP包, nal type51, rtp:^M
version:2^M
padding:0^M
ext:20^M
csrc:0^M
mark:0^M
pt:99^M
seq:1^M
stamp:3386346273^M
ssrc:0^M
rtp size:52^M
payload offset:24^M
payload size:16^M

2024-10-25 09:28:51.258 W [MediaServer] [1-event poller 26] H265Rtp.cpp:90 unpackAp | invalid rtp data size:651 < 24576,rtp:^M
version:2^M
padding:0^M
ext:20^M
csrc:0^M
mark:1^M
pt:99^M
seq:15^M
stamp:3386357073^M
ssrc:0^M
rtp size:691^M
payload offset:24^M
payload size:655^M

**Comment by xia-chu** [comment]
你确定华为的视频es流就是265的？

**Comment by xia-chu** [comment]
配置文件这里改下：
<img width="520" alt="image" src="https://github.com/user-attachments/assets/2fa6b9aa-7455-4539-b393-198aa86a6512">

H264改成99，H265改成其他，比如说102

**Comment by sling2007** [comment]
多谢，修改了这个Payload Type的值（H264改成99，H265改成其他，比如说102）后，的确可以了。
我确认是用的h264编码。
h264和h265的pt值，不可以一样吗？

**Comment by xia-chu** [comment]
> h264和h265的pt值，不可以一样吗？

一样的话 zlm怎么识别是264还是265？
