### ISSUE TITLE
[Feature Request] Requirement Description (Cluster Load Balancing Configuration)

### ISSUE THREAD

**Issue by Logers-kcm** [ZLMediaKit/ZLMediaKit#3978]
## Describe the purpose of this feature, and provide relevant information to describe this feature
Cluster Load Balancing Configuration
## Is this feature used to improve project defects? If so, please describe the existing defects
No
## Describe how you expect to achieve this feature and the final effect
I currently have three machines, one source station and two edge stations. How can the source station load balance to the two edge stations? If I modify the configuration file, the edge stations can find the source station, but how does the source station distinguish between multiple edge stations?
In the future, the source station will also be expanded. How will the business side perform load balancing between source stations?

>## 描述该功能的用处，可以提供相关资料描述该功能
集群负载均衡配置
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
否
## 描述你期望实现该功能的方式和最终效果
我目前三台机器，一台源站两台边沿站，请问源站如何负载均衡到两台边沿站上；如果改配置文件，边沿站能找到源站，但源站是如何分辨多个边沿站的呢？
以后源站也会进行扩充，那么业务端如何进行源站间的负载均衡呢？

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
现在边缘站能配置源站 源站无法选择边缘站。你推流的负载均衡要自己实现 你自己选择合适的源站。

拉流的话向边缘站发起拉流，边缘站会轮询源站，负载均衡算法是最简单的轮询方式，不会考虑在线播放器个数的，而是按次轮询源站；我觉得这基本够用了。

大规模的直播集群部署不是一般开发者和公司需要考虑的，大公司自己有研发能力，做点这样的业务开发完全可行。

**Comment by xia-chu** [comment]
如果要实现灵活的直播集群 我觉得可以不分源站和边缘站，用以下方式即可：
![image](https://github.com/user-attachments/assets/9447560d-96b2-4dc1-87c2-2a8aa81d8b29)
