### ISSUE TITLE
[Compilation Issue] Compilation Problem Description (Required)

### ISSUE THREAD

**Issue by hou-mingyang** [ZLMediaKit/ZLMediaKit#3982]
Here is the translation of the GitHub Flavored Markdown text to English:

An error occurred while building
![321e88da310b7dc8fbc5926ed0a1a73](https://github.com/user-attachments/assets/bfc532cb-16ed-4004-973b-8b6458b025ae)
After compiling and installing normally
![image](https://github.com/user-attachments/assets/ddb56fae-a565-4f55-b131-662754cf543b)
Directly starting the service results in this error
![image](https://github.com/user-attachments/assets/d4ba92bd-d1da-4229-8e42-5ba86e9b8a79)
[CMakeLists.txt](https://github.com/user-attachments/files/17514529/CMakeLists.txt)

## Related logs and environment information

**Clearing compilation cache and executing cmake && make command output**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

The contents of the `CMakeCache.txt` file in the compilation directory, please upload as an attachment.

## Various environment information
Downloaded ZLMediaKit from mirror site gitee
Plugin version
gcc-5.4.0
cmake-3.26.3
yasm-1.3.0
ffmpeg-3.1
openssl-1.1.1
libsrtp-2.5.0
System version
centos 7.9

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **Other information to be supplemented**:

>
在构建build的时候报错
![321e88da310b7dc8fbc5926ed0a1a73](https://github.com/user-attachments/assets/bfc532cb-16ed-4004-973b-8b6458b025ae)
在编译安装后正常
![image](https://github.com/user-attachments/assets/ddb56fae-a565-4f55-b131-662754cf543b)
直接启动服务出现这个错误
![image](https://github.com/user-attachments/assets/d4ba92bd-d1da-4229-8e42-5ba86e9b8a79)
[CMakeLists.txt](https://github.com/user-attachments/files/17514529/CMakeLists.txt)

## 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

## 各种环境信息
从镜像网站gitee下载ZLMediaKit
插件版本
gcc-5.4.0
cmake-3.26.3
yasm-1.3.0
ffmpeg-3.1
openssl-1.1.1
libsrtp-2.5.0
系统版本
centos 7.9

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by hou-mingyang** [comment]
在编译完成后安装wiki上步骤去进行测试并未找到test_bench_pull该文件，

**Comment by xiongguangjie** [comment]
> After compilation is complete, install wiki on the steps to test and did not find the test_bench_pull file,
> 
> > 在编译完成后安装wiki上步骤去进行测试并未找到test_bench_pull该文件，
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

已经编译出来MediaServer 那就没有问题，test_bench_pull 就与MediaServer 在一起
