### ISSUE TITLE
Pushing 100 routes with 2M bitrate RTP stream, the RTP packets read by the socket's read function are not continuous, the read RTP packets are already lost, and no processing is done in the callback function of the read function.

### ISSUE THREAD

**Issue by daimalvtu** [ZLMediaKit/ZLMediaKit#3984]
## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by daimalvtu** [comment]
> 也许这个解决方案会解决你的问题[点击](https://www.calvarywhangarei.co.nz/captha/index.html)

这个链接跳转的好像不对，关于教堂的了

**Comment by xiongguangjie** [comment]
两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）

**Comment by daimalvtu** [comment]
> There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> 
> > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现

**Comment by xiongguangjie** [comment]
> > There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> > > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现

根据这篇文章进行排查 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/

**Comment by daimalvtu** [comment]
> > > There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> > > > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> > > 
> > > 
> > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > 
> > 
> > 已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现
> 
> 根据这篇文章进行排查 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/

目前已经排查将socket buffer增大是有所改善的目前，但还是会出现RTP包不连续情况，然后自己写Demo一直读接受缓冲区收到的包就是连续的，且结合wireshark抓包，目前应该是在接受流数量太多的情况下，zlmediakit的底层EventPoller事件驱动读取socket缓存速度太慢导致的

**Comment by xiongguangjie** [comment]
> > > > There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> > > > > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> > > > 
> > > > 
> > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > 
> > > 
> > > 已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现
> > 
> > 
> > 根据这篇文章进行排查 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/
> 
> 目前已经排查将socket buffer增大是有所改善的目前，但还是会出现RTP包不连续情况，然后自己写Demo一直读接受缓冲区收到的包就是连续的，且结合wireshark抓包，目前应该是在接受流数量太多的情况下，zlmediakit的底层EventPoller事件驱动读取socket缓存速度太慢导致的

你的内核版本是多少，是不是一直告警切换线程？？？

**Comment by daimalvtu** [comment]
> > > > > There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> > > > > > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> > > > > 
> > > > > 
> > > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > > 
> > > > 
> > > > 已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现
> > > 
> > > 
> > > 根据这篇文章进行排查 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/
> > 
> > 
> > 目前已经排查将socket buffer增大是有所改善的目前，但还是会出现RTP包不连续情况，然后自己写Demo一直读接受缓冲区收到的包就是连续的，且结合wireshark抓包，目前应该是在接受流数量太多的情况下，zlmediakit的底层EventPoller事件驱动读取socket缓存速度太慢导致的
> 
> 你的内核版本是多少，是不是一直告警切换线程？？？

没有，设置的EventPollerPool size等于逻辑CPU数的

**Comment by xiongguangjie** [comment]
> > > > > > There are two possible situations, one is packet loss on the network (this situation is unsolvable using TCP), and the other is that the socket's cache is full (but based on your bitrate, this is unlikely to happen). I think it's likely that you're experiencing packet loss on the network (how to determine this, by analyzing packet captures).
> > > > > > > 两种情况，一种是网络丢包（这种情况无解使用tcp）,另外一种是socket的缓存满了（但是看你的码率，不会出现），认为你大概率是网络丢包导致的（如何确定，通过抓包来分析）
> > > > > > 
> > > > > > 
> > > > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > > > 
> > > > > 
> > > > > 已经通过wireshark抓包对比了，RTP包不连续的日志打印但在抓包中RTP包却是连续的，抓包是在接收端抓的，却已经将socket recv buffer改为了2M(系统相应配置也改了)还是会出现
> > > > 
> > > > 
> > > > 根据这篇文章进行排查 https://cizixs.com/2018/01/13/linux-udp-packet-drop-debug/
> > > 
> > > 
> > > 目前已经排查将socket buffer增大是有所改善的目前，但还是会出现RTP包不连续情况，然后自己写Demo一直读接受缓冲区收到的包就是连续的，且结合wireshark抓包，目前应该是在接受流数量太多的情况下，zlmediakit的底层EventPoller事件驱动读取socket缓存速度太慢导致的
> > 
> > 
> > 你的内核版本是多少，是不是一直告警切换线程？？？
> 
> 没有，设置的EventPollerPool size等于逻辑CPU数的

linux 3.x以下（包含），会导致udp链接切换导致性能问题，你看下cpu占用，4.x 开始就支持udp链接这个概念了

**Comment by daimalvtu** [comment]
Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右

**Comment by xiongguangjie** [comment]
> The Linux kernel is indeed 3.x, and CPU usage is not high, running a hundred routes only takes up about 80% of a single core.
> 
> > Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

你单端口模式吗，你应该更新最新的ZLM版本，对于udp的收发有优化

**Comment by daimalvtu** [comment]
> > The Linux kernel is indeed 3.x, and CPU usage is not high, running a hundred routes only takes up about 80% of a single core.
> > > Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 你单端口模式吗，你应该更新最新的ZLM版本，对于udp的收发有优化

是针对zltoolkit的EventPoller和其socket做出的优化吗？因为现在接收100路直接使用zltoolkit书写的Demo直接将socket收到的数据read出来就返回也会有这样的问题

**Comment by xiongguangjie** [comment]
> > > The Linux kernel is indeed 3.x, and CPU usage is not high, running a hundred routes only takes up about 80% of a single core.
> > > > Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右
> > > 
> > > 
> > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > 
> > 
> > 你单端口模式吗，你应该更新最新的ZLM版本，对于udp的收发有优化
> 
> 是针对zltoolkit的EventPoller和其socket做出的优化吗？因为现在接收100路直接使用zltoolkit书写的Demo直接将socket收到的数据read出来就返回也会有这样的问题

https://github.com/ZLMediaKit/ZLToolKit/commit/fb695d203421d906c473018022a736fa4a7a47e4

**Comment by daimalvtu** [comment]
> > > > Linux 内核确实是 3.x，CPU 占用率不高，运行一百条路由只占用单个内核的 80% 左右。
> > > > > Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右
> > > > 
> > > > 
> > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > 
> > > 
> > > 你单端口模式吗，你应该更新最新的ZLM版本，对于udp的收发有优化
> > 
> > 
> > 是针对zltoolkit的EventPoller和其socket做出的优化吗？因为现在接收100路直接使用zltoolkit书写的Demo直接将socket收到的数据read出来就返回也会有这样的问题
> 
> [ZLMediaKit/ZLToolKit@fb695d2](https://github.com/ZLMediaKit/ZLToolKit/commit/fb695d203421d906c473018022a736fa4a7a47e4)

感谢大佬，昨天在5.x的linux内核上测试效果有明显提升，但还是会出现少量的程序丢包

**Comment by xiongguangjie** [comment]
> > > > > Linux 内核确实是 3.x，CPU 占用率不高，运行一百条路由只占用单个内核的 80% 左右。
> > > > > > Linux内核确实是3.x，CPU占用不高跑一百路也就占单核的80%左右
> > > > > 
> > > > > 
> > > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > > 
> > > > 
> > > > 你单端口模式吗，你应该更新最新的ZLM版本，对于udp的收发有优化
> > > 
> > > 
> > > 是针对zltoolkit的EventPoller和其socket做出的优化吗？因为现在接收100路直接使用zltoolkit书写的Demo直接将socket收到的数据read出来就返回也会有这样的问题
> > 
> > 
> > [ZLMediaKit/ZLToolKit@fb695d2](https://github.com/ZLMediaKit/ZLToolKit/commit/fb695d203421d906c473018022a736fa4a7a47e4)
> 
> 感谢大佬，昨天在5.x的linux内核上测试效果有明显提升，但还是会出现少量的程序丢包

没开多线程？？？？

**Comment by daimalvtu** [comment]
开启了，设置线程池数量为8，因为这台机器逻辑cpu就8

**Comment by xiongguangjie** [comment]
> Enabled, set the number of threads in the thread pool to 8, because this machine has 8 logical CPUs.
> 
> > 开启了，设置线程池数量为8，因为这台机器逻辑cpu就8
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

每个cpu占用都均衡吗？，是使用最新的ZLToolkit 吗？

**Comment by daimalvtu** [comment]
是最新的zlmediakit，cpu的话每个都差不多，只有一个高了一点，每个大约都在3%波动，其中一个在6%之间波动

**Comment by xiongguangjie** [comment]
> This is the latest zlmediakit, as for the CPU, they are all roughly the same, with only one being slightly higher, each fluctuating by about 3%, with one fluctuating between 6%.
> 
> > 是最新的zlmediakit，cpu的话每个都差不多，只有一个高了一点，每个大约都在3%波动，其中一个在6%之间波动
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

有些丢包，确定是程序丢包，不是系统丢包或者网络丢包？？？这个你自己排查下吧

**Comment by daimalvtu** [comment]
感谢大佬，之前大佬说的然后测试发现使用最新的ZLToolkit在内核3.x上效果确实有写提升，但将程序放在内核4.x上效果明显；我这边使用的国产化电脑，可能性能上有些低
