### ISSUE TITLE
[BUG] Streaming with vmix to ZLMediakit results in video but no audio

### ISSUE THREAD

**Issue by xoraingroup** [ZLMediaKit/ZLMediaKit#3989]
## Phenomenon Description
Using vmix for windows to stream video file to ZLMediakit server causes the video to have no audio at all. 

## How to reproduce?

    1. Install vmix from `https://www.vmix.com/Software/Download.aspx`
    2. Run vmix and load a video file to stream to ZLMediakit Server, for example `rtmp://localhost/live/helloworld`
    3. Try to play it using `ffplay rtmp://localhost/live/helloworld`
    4. Expected result is that Video plays in box with audio
    5. Actual result is that there is video but no audio.

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
Normal logs are seen without any errors.
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
standard config.ini in conf/config.ini
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here

No crashes
```
* **Other information to be supplemented**:

>

Using vmix for windows to stream video file to ZLMediakit server causes the video to have no audio at all. 

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
standard config.ini in conf/config.ini
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此

No crashes
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xoraingroup** [comment]
@xia-chu can u have a look at this?

**Comment by xiongguangjie** [comment]
> @xia-chu can u have a look at this?

upload your zlm logs

**Comment by xoraingroup** [comment]
Hi here are the logs for streaming from vmix to zl. 

```
2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H264
2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H265
2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: JPEG
2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: mpeg4-generic
2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: opus
2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMA
2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMU
2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: L16
2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:1048576
2024-10-30 12:07:13.206 I [MediaServer] [13846-MediaServer] main.cpp:271 start_main | ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
2024-10-30 12:07:13.206 D [MediaServer] [13846-stamp thread] util.cpp:390 operator() | Stamp thread started
2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] EventPoller.cpp:616 EventPollerPool | EventPoller created size: 3
2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:396 start_main | 已启动http api 接口
2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:398 start_main | 已启动http hook 接口
2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 554
2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 1935
2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 80
2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 443
2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 10000
2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 10000
2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 9000
2024-10-30 12:07:26.348 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
2024-10-30 12:07:27.466 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:128 operator() | 1-25(49.13.210.123:55294) publish 回复时间:0ms
2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/helooworld
2024-10-30 12:07:27.856 D [MediaServer] [13846-event poller 0] MediaSink.cpp:192 emitAllTrackReady | All track ready use 176ms
2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:fmp4://__defaultVhost__/live/helooworld
2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MultiMediaSourceMuxer.cpp:593 onAllTrackReady | stream: rtmp://__defaultVhost__/live/helooworld , codec info: mpeg4-generic[48000/2/16] H264[1280/720/30]
2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/helooworld
2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:ts://__defaultVhost__/live/helooworld
2024-10-30 12:07:30.939 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:hls://__defaultVhost__/live/helooworld
2024-10-30 12:07:31.396 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
2024-10-30 12:07:31.706 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:367 operator() | 2-26(95.217.176.197:56114) play 回复时间:1ms
^C2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] main.cpp:464 operator() | SIGINT:exit
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 9000
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 10000
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 10000
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 443
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 80
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 1935
2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 2-26(95.217.176.197:56114) RTMP播放器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):34
2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 1-25(49.13.210.123:55294) RTMP推流器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):39
2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 554
2024-10-30 12:08:05.455 I [MediaServer] [13846-MediaServer] main.cpp:489 start_main | 程序退出中,请等待...
2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] main.cpp:491 start_main | 程序退出完毕!
2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 1
2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 2
````

And following are the logs when i started to play using ffplay 

ffplay rtmp://37.27.203.254/live/helooworld

```
ffplay version 7.1 Copyright (c) 2003-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, flv, from 'rtmp://37.27.203.254/live/helooworld':
  Metadata:
    |RtmpSampleAccess: true
    encoder         : Lavf57.82.101
    title           : Streamed by ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
  Duration: 00:00:00.00, start: 4.004000, bitrate: N/A
  Stream #0:0: Data: none
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:2: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720, 2500 kb/s, 29.97 fps, 29.97 tbr, 1k tbn
```

Stream playback didn't had audio.

**Comment by xiongguangjie** [comment]
> Hi here are the logs for streaming from vmix to zl.
> 
> ```
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H264
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H265
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: JPEG
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: mpeg4-generic
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: opus
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMA
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMU
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: L16
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:1048576
> 2024-10-30 12:07:13.206 I [MediaServer] [13846-MediaServer] main.cpp:271 start_main | ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
> 2024-10-30 12:07:13.206 D [MediaServer] [13846-stamp thread] util.cpp:390 operator() | Stamp thread started
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] EventPoller.cpp:616 EventPollerPool | EventPoller created size: 3
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:396 start_main | 已启动http api 接口
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:398 start_main | 已启动http hook 接口
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 554
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 1935
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 80
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 443
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 10000
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 10000
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 9000
> 2024-10-30 12:07:26.348 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
> 2024-10-30 12:07:27.466 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:128 operator() | 1-25(49.13.210.123:55294) publish 回复时间:0ms
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.856 D [MediaServer] [13846-event poller 0] MediaSink.cpp:192 emitAllTrackReady | All track ready use 176ms
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:fmp4://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MultiMediaSourceMuxer.cpp:593 onAllTrackReady | stream: rtmp://__defaultVhost__/live/helooworld , codec info: mpeg4-generic[48000/2/16] H264[1280/720/30]
> 2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:ts://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:30.939 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:hls://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:31.396 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
> 2024-10-30 12:07:31.706 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:367 operator() | 2-26(95.217.176.197:56114) play 回复时间:1ms
> ^C2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] main.cpp:464 operator() | SIGINT:exit
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 9000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 10000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 10000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 443
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 80
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 1935
> 2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 2-26(95.217.176.197:56114) RTMP播放器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):34
> 2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 1-25(49.13.210.123:55294) RTMP推流器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):39
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 554
> 2024-10-30 12:08:05.455 I [MediaServer] [13846-MediaServer] main.cpp:489 start_main | 程序退出中,请等待...
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] main.cpp:491 start_main | 程序退出完毕!
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 1
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 2
> ```
> 
> And following are the logs when i started to play using ffplay
> 
> ffplay rtmp://37.27.203.254/live/helooworld
> 
> ```
> ffplay version 7.1 Copyright (c) 2003-2024 the FFmpeg developers
>   built with Apple clang version 15.0.0 (clang-1500.3.9.4)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
>   libavutil      59. 39.100 / 59. 39.100
>   libavcodec     61. 19.100 / 61. 19.100
>   libavformat    61.  7.100 / 61.  7.100
>   libavdevice    61.  3.100 / 61.  3.100
>   libavfilter    10.  4.100 / 10.  4.100
>   libswscale      8.  3.100 /  8.  3.100
>   libswresample   5.  3.100 /  5.  3.100
>   libpostproc    58.  3.100 / 58.  3.100
> Input #0, flv, from 'rtmp://37.27.203.254/live/helooworld':
>   Metadata:
>     |RtmpSampleAccess: true
>     encoder         : Lavf57.82.101
>     title           : Streamed by ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
>   Duration: 00:00:00.00, start: 4.004000, bitrate: N/A
>   Stream #0:0: Data: none
>   Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
>   Stream #0:2: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720, 2500 kb/s, 29.97 fps, 29.97 tbr, 1k tbn
> ```
> 
> Stream playback didn't had audio.
> 
> > Hi here are the logs for streaming from vmix to zl.
> 
> ```
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H264
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: H265
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: JPEG
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: mpeg4-generic
> 2024-10-30 12:07:13.204 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: opus
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMA
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: PCMU
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] Factory.cpp:41 registerPlugin | Load codec: L16
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> 2024-10-30 12:07:13.205 I [MediaServer] [13846-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:1048576
> 2024-10-30 12:07:13.206 I [MediaServer] [13846-MediaServer] main.cpp:271 start_main | ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
> 2024-10-30 12:07:13.206 D [MediaServer] [13846-stamp thread] util.cpp:390 operator() | Stamp thread started
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] EventPoller.cpp:616 EventPollerPool | EventPoller created size: 3
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:396 start_main | 已启动http api 接口
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] main.cpp:398 start_main | 已启动http hook 接口
> 2024-10-30 12:07:13.207 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 554
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 1935
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 80
> 2024-10-30 12:07:13.208 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 443
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 10000
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] TcpServer.cpp:242 start_l | TCP server listening on [::]: 10000
> 2024-10-30 12:07:13.209 I [MediaServer] [13846-MediaServer] UdpServer.cpp:130 start_l | UDP server bind to [::]: 9000
> 2024-10-30 12:07:26.348 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
> 2024-10-30 12:07:27.466 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:128 operator() | 1-25(49.13.210.123:55294) publish 回复时间:0ms
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtmp://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.856 D [MediaServer] [13846-event poller 0] MediaSink.cpp:192 emitAllTrackReady | All track ready use 176ms
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:fmp4://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.856 I [MediaServer] [13846-event poller 0] MultiMediaSourceMuxer.cpp:593 onAllTrackReady | stream: rtmp://__defaultVhost__/live/helooworld , codec info: mpeg4-generic[48000/2/16] H264[1280/720/30]
> 2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:rtsp://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:27.857 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:ts://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:30.939 I [MediaServer] [13846-event poller 0] MediaSource.cpp:498 emitEvent | 媒体注册:hls://__defaultVhost__/live/helooworld
> 2024-10-30 12:07:31.396 W [MediaServer] [13846-event poller 0] RtmpProtocol.cpp:362 handle_C0C1 | 未打开ENABLE_OPENSSL宏，复杂握手采用简单方式处理，flash播放器可能无法播放！
> 2024-10-30 12:07:31.706 D [MediaServer] [13846-event poller 0] RtmpSession.cpp:367 operator() | 2-26(95.217.176.197:56114) play 回复时间:1ms
> ^C2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] main.cpp:464 operator() | SIGINT:exit
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 9000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 10000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] UdpServer.cpp:65 ~UdpServer | Close udp server [::]: 10000
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 443
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 80
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 1935
> 2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 2-26(95.217.176.197:56114) RTMP播放器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):34
> 2024-10-30 12:08:05.454 W [MediaServer] [13846-event poller 0] RtmpSession.cpp:28 onError | 1-25(49.13.210.123:55294) RTMP推流器(__defaultVhost__/live/helooworld)断开:Server shutdown,耗时(s):39
> 2024-10-30 12:08:05.454 I [MediaServer] [13846-MediaServer] TcpServer.cpp:51 ~TcpServer | Close tcp server [::]: 554
> 2024-10-30 12:08:05.455 I [MediaServer] [13846-MediaServer] main.cpp:489 start_main | 程序退出中,请等待...
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] main.cpp:491 start_main | 程序退出完毕!
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 1
> 2024-10-30 12:08:06.455 I [MediaServer] [13846-MediaServer] EventPoller.cpp:112 ~EventPoller | event poller 2
> ```
> 
> And following are the logs when i started to play using ffplay
> 
> ffplay rtmp://37.27.203.254/live/helooworld
> 
> ```
> ffplay version 7.1 Copyright (c) 2003-2024 the FFmpeg developers
>   built with Apple clang version 15.0.0 (clang-1500.3.9.4)
>   configuration: --prefix=/usr/local/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox
>   libavutil      59. 39.100 / 59. 39.100
>   libavcodec     61. 19.100 / 61. 19.100
>   libavformat    61.  7.100 / 61.  7.100
>   libavdevice    61.  3.100 / 61.  3.100
>   libavfilter    10.  4.100 / 10.  4.100
>   libswscale      8.  3.100 /  8.  3.100
>   libswresample   5.  3.100 /  5.  3.100
>   libpostproc    58.  3.100 / 58.  3.100
> Input #0, flv, from 'rtmp://37.27.203.254/live/helooworld':
>   Metadata:
>     |RtmpSampleAccess: true
>     encoder         : Lavf57.82.101
>     title           : Streamed by ZLMediaKit(git hash:cc59025/2024-10-27T12:05:04+08:00,branch:master,build time:2024-10-30T12:01:53)
>   Duration: 00:00:00.00, start: 4.004000, bitrate: N/A
>   Stream #0:0: Data: none
>   Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, 128 kb/s
>   Stream #0:2: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720, 2500 kb/s, 29.97 fps, 29.97 tbr, 1k tbn
> ```
> 
> Stream playback didn't had audio.
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

log show stream has audio , you not listen audio , you should check player and speaker or audio is slience

**Comment by xoraingroup** [comment]
@xiongguangjie Whats the status of this issue?

**Comment by xiongguangjie** [comment]
> @xiongguangjie Whats the status of this issue?

this is not bug of zlm ,is stream source issue or player or pc

**Comment by xoraingroup** [comment]
It works ok with nginx-rtmp, Ant Media Server and all other media servers but not zl. So it can't be source issue.

**Comment by xiongguangjie** [comment]
> Ant Media Server

give me a url that i can access , the log show every thing is ok

**Comment by xia-chu** [comment]
@xoraingroup 
Please download the stream by http-flv, like this:
```bash
wget http://37.27.203.254/live/helooworld.live.flv
```

And then you can upload this flv file here.

**Comment by xoraingroup** [comment]
It has audio but the hls fragments does not have audio. The issue is in hls mpeg ts fragments.

**Comment by xiongguangjie** [comment]
> It has audio but the hls fragments does not have audio. The issue is in hls mpeg ts fragments.

upload ts file
