### ISSUE TITLE
[BUG] After upgrading the code updated on November 1, 2024, the video recording of the streaming proxy is stored in the first file, and each subsequent file slice is 2 seconds

### ISSUE THREAD

**Issue by Yonn0818** [ZLMediaKit/ZLMediaKit#4000]
## Phenomenon Description
After upgrading to the code updated on November 1, 2024, the video recording of the streaming proxy is stored in the first file, but every subsequent file slice is 2 seconds long
Modified config.ini with mp4_max_second=900, started the streaming proxy, only the first mp4 file is 15 minutes, and every subsequent file is 2 seconds long, restarting the proxy has the same result, the first file is normal, and the subsequent files are 2 seconds long

## How to reproduce?
Upgrade to the new version of the code on November 1, modify config.ini with mp4_max_second=900, start the streaming proxy, wait for 15 minutes after completing the first file write, and then it becomes 2 seconds per file

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
[protocol]
mp4_max_second=900
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
升级2024年11月1号更新的代码后，拉流代理的录像存储在第一个文件完成后，后面每个文件切片都是2秒
修改的config.ini中的mp4_max_second=900，启动拉流代理后，只有第一个mp4文件是15分钟 之后的每个文件都是2秒，重启代理同样是第一个文件正常，后面文件都是2秒

## 如何复现?
升级11月1号的新版本代码，修改的config.ini中的mp4_max_second=900，启动拉流代理，等到15分钟后完成第一个第一个文件写入，之后就是2秒一个文件

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
[protocol]
mp4_max_second=900
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
拉流代理的什么协议？

**Comment by Yonn0818** [comment]
> What protocol does the pull stream proxy use?拉流代理使用什么协议？
> 
> > 拉流代理的什么协议？
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

拉流代理使用的RTSP，退回之前的老版本后就正常了，而且还发现一个新的问题，新版本录制的MP4视频打开非常慢，15分钟100MB的视频打开大约要15-20秒，老版本录制的视频基本上是秒开

**Comment by PioLing** [comment]
# https://github.com/ZLMediaKit/ZLMediaKit/issues/4000#issuecomment-2453891667 ，我也发现了，下载下来的mp4 ,用vlc不能拖拉进度条(ffplay 可以）

**Comment by xia-chu** [comment]
> 新版本录制的MP4视频打开非常慢，15分钟100MB的视频打开大约要15-20秒，老版本录制的视频基本上是秒开

你用什么协议打开mp4文件的？会不会是fastStart的问题

**Comment by PioLing** [comment]
> 你用什么协议打开mp4文

我这边用http 打开录制完成的mp4 ,也是一样慢

**Comment by PioLing** [comment]
> > 你用什么协议打开mp4文
> 
> On my side, opening the recorded mp4 with http is also slow
> 
> > > 你用什么协议打开mp4文
> 
> 我这边用http 打开录制完成的mp4 ,也是一样慢
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

一般升级都是默认原来配置的

**Comment by xia-chu** [comment]
配置文件fastStart设置为1 录制出的mp4 http打开就快了

**Comment by PioLing** [comment]
> I also found that the downloaded mp4 file cannot be dragged to the progress bar in VLC (ffplay can).
> 
> 我也发现了，下载下来的mp4 ,用vlc不能拖拉进度条(ffplay 可以）
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我用ffmpeg 转一下，例如 ffmpeg -i input.mp4 -c copy -f mp4 ./out.mp4，vlc 就可以识别进度条了

**Comment by PioLing** [comment]
> > I also found that the downloaded mp4 file cannot be dragged to the progress bar in VLC (ffplay can).
> > 我也发现了，下载下来的mp4 ,用vlc不能拖拉进度条(ffplay 可以）
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 我用ffmpeg 转一下，例如 ffmpeg -i input.mp4 -c copy -f mp4 ./out.mp4，vlc 就可以识别进度条(seek)了

把 config.ini 配置文件的[record]的 enableFmp4 改成 0 ，也可以解决vlc 播放mp4拖放问题

**Comment by hotleave** [comment]
第一个文件之后，2秒存一个录像文件的问题要怎么解决？

**Comment by xia-chu** [comment]
> 第一个文件之后，2秒存一个录像文件的问题要怎么解决？

这个问题可能是时间戳回退导致的 还没来得及本地测试复现

**Comment by xiongguangjie** [comment]
已经修复提交pr了，重复问题 #4007
