### ISSUE TITLE
The Transcode branch's code hasn't been updated with many new features in over a year; can it be updated now?

### ISSUE THREAD

**Issue by Haoxw** [ZLMediaKit/ZLMediaKit#4005]
## Describe the purpose of this feature, and provide relevant information to describe this feature
The Transcode branch's code hasn't been updated with many new features in over a year; can it be updated now?

## Describe how you expect to achieve this feature and the final effect

>## 描述该功能的用处，可以提供相关资料描述该功能
The Transcode branch's code hasn't been updated with many new features in over a year; can it be updated now?

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
featrue/transcode2 branch's code has't been updated,but featrue/transcode branch's code hasn't been updated,Thank you very much.

## 描述你期望实现该功能的方式和最终效果
featrue/transcode branch's code hasn't been updated,the new webrtc can not work fine.

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by Haoxw** [comment]
![Uploading ZL1.jpg…]()

**Comment by Haoxw** [comment]
featrue/transcode2 branch's code has't been updated,but featrue/transcode branch's code hasn't been updated,Thank you very much.

**Comment by mtdxc** [comment]
featrue/transcode2已经合并主线了。
真不行就自己动手merge下代码呗

**Comment by Haoxw** [comment]
First of all, thank you very much for your hard work! We are not very good at C++ code. For the sake of stability, we still hope that you can help us merge the existing main branch code of ZL into the featrue/transcode branch. Thank you very much! ! !  !

**Comment by Haoxw** [comment]
> featrue/transcode2 has already been merged into the main branch. If it really doesn't work, then just manually merge the code yourself.
> 
> > featrue/transcode2已经合并主线了。
> > 真不行就自己动手merge下代码呗
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`
First of all, thank you very much for your hard work! We are not very good at C++ code. For the sake of stability, we still hope that you can help us merge the existing main branch code of ZL into the featrue/transcode branch. Thank you very much! ! ! !
