### ISSUE TITLE
[Feature Request] Custom filename when recording video

### ISSUE THREAD

**Issue by weiai123312** [ZLMediaKit/ZLMediaKit#4006]
## Describe the purpose of this feature, and provide relevant information to describe this feature
When recording a video (startRecord interface), there is a parameter used to customize the video name.

## Is this feature used to improve project defects? If so, please describe the existing defects
When recording a video (startRecord interface), there is a parameter: customized_path used to specify the directory where the file is located.
However, a new "record" folder will still be created in the directory, but in fact, I do not want to use this folder, I want to save it directly to the directory.
And I also hope to directly get the video and make subsequent processing.

## Describe how you expect to achieve this feature and the final effect
Provide a parameter to specify the file name, or return the final save path (including the name) when stopping the recording.

>## 描述该功能的用处，可以提供相关资料描述该功能
录制视频（startRecord接口）时有一个参数，用于自定义视频名称
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
在录制视频（startRecord接口）时候有一个参数：customized_path 用于指定文件所在目录
但是仍会在目录下新建record 文件夹，但是实际上我并不想使用这个文件夹，我想直接保存到该目录下
并且我也希望直接能获取到该视频，并作随后的处理
## 描述你期望实现该功能的方式和最终效果
提供一个参数，用于指定文件名，或将最终保存路径（包含名称）在停止录像时返回

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
你可以哦通过webhook , on_record_ts 或者 on_record_mp4 来得知录像文件的生成，然后去处理。如果还是无法满足你的要在，你自己二开

**Comment by xia-chu** [comment]
record目录是用于点播时限制app名用的 为了安全考虑
