### ISSUE TITLE
[BUG] After upgrading to the latest code, when recording MP4, a new recording file is generated every 2 seconds after the first slice

### ISSUE THREAD

**Issue by hotleave** [ZLMediaKit/ZLMediaKit#4007]
## Phenomenon Description

As described in #4000, after updating the code on November 1st, when recording MP4 during RTSP streaming, the automatic segmentation time is set to 10 minutes, the first segment is fine, but from the second segment onwards, a new segment is created every 2 seconds. This should be the problem caused by the commit 6729257eabfe26a0df1657d8f9d034cb31b6cba9.

## How to reproduce?

Use the program from November 1st to record MP4 from RTSP streaming, set the automatic segmentation time to 600 seconds.

## Related logs or screenshots

![image](https://github.com/user-attachments/assets/e16097fa-9ac2-46eb-b721-e6375bf5c876)

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

 

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

 

* **Code commit record/git commit hash**: 8ccb4e9
* **Operating system and version**: Ubuntu 20.04
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

正如在 #4000 中描述的，在更新了 11月1日的代码后，在rtsp拉流时进行MP4录制时，自动分片时间设置成10分钟，第一个切片没有问题，但从第二个切片开始，每2秒一个切片。应该是 6729257eabfe26a0df1657d8f9d034cb31b6cba9 这次提交导致的问题

## 如何复现?

使用11月1日的程序使用从 rtsp 拉流录制MP4，设置自动分片时间 600 秒

## 相关日志或截图

![image](https://github.com/user-attachments/assets/e16097fa-9ac2-46eb-b721-e6375bf5c876)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**: 8ccb4e9
* **操作系统及版本**: Ubuntu 20.04
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
有日志吗？应该是时间戳回退导致的

**Comment by xiongguangjie** [comment]
看了下，感觉代码没啥问题

**Comment by xiongguangjie** [comment]
> Took a look, and it seems like there's no issue with the code.
> 
> > 看了下，感觉代码没啥问题
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

还真是的，的确第一个没问题，剩下的2s-3s一个

**Comment by xiongguangjie** [comment]
有逻辑bug , 这么修复一下
```diff --git a/src/Record/MP4Recorder.cpp b/src/Record/MP4Recorder.cpp
index b775da13..342abce9 100644
--- a/src/Record/MP4Recorder.cpp
+++ b/src/Record/MP4Recorder.cpp
@@ -126,7 +126,11 @@ bool MP4Recorder::inputFrame(const Frame::Ptr &frame) {
         if (_last_dts == 0 || _last_dts > frame->dts()) {
             // b帧情况下dts时间戳可能回退  [AUTO-TRANSLATED:1de38f77]
             // In the case of b-frames, the dts timestamp may regress
-            _last_dts = MIN(frame->dts(), _last_dts);
+            if(_last_dts == 0){
+                _last_dts = frame->dts();
+            }else{
+                _last_dts = MIN(frame->dts(), _last_dts);
+            }
         }
         auto duration = 5u; // 默认至少一帧5ms
         if (frame->dts() > 0 && frame->dts() > _last_dts) {```
