### ISSUE TITLE
[Feature Request] Ability to provide an interface to delete generated screen recordings and screenshots

### ISSUE THREAD

**Issue by hl370002800** [ZLMediaKit/ZLMediaKit#4012]
## Describe the purpose of this feature, and provide relevant information to describe this feature
Generated videos and images are stored in OSS and need to be cleaned up from local files, since the zlm mirror and service mirror are not on the same server, so only an interface can be provided for deletion
## Is this feature used to improve project defects? If so, please describe the existing defects
No
## Describe how you expect to achieve this feature and the final effect
Provide a REST interface to delete recordings, and when calling getSnap, provide a parameter to not generate local images

>## 描述该功能的用处，可以提供相关资料描述该功能
生成的视频和图片统一放入OSS后需要清理产生的本地文件,由于zlm的镜像和服务的镜像不在同一台服务器中,所以只能提供接口来调用删除
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
否
## 描述你期望实现该功能的方式和最终效果
提供一个rest接口来对录像进行删除,在调用getSnap的时候提供一个参数为不生成本地图片

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
录像调动 /index/api/deleteRecordDirectory 删除
截图现在没有相应的接口删除，一路流只会有一张图片的截图（老的会删除，不会报错老的），不会占用太大的空间

**Comment by hl370002800** [comment]
deleteRecordDirectory删除的好像是整个文件夹而不是单个视频文件;
我是使用zlm来截外部的流的照片,所以在/www/snap里面有很多以uuid的文件夹照片

**Comment by xiongguangjie** [comment]
> deleteRecordDirectory seems to delete the entire folder instead of a single video file; I'm using zlm to capture external stream photos, so there are many uuid folder photos in /www/snap
> 
> > deleteRecordDirectory删除的好像是整个文件夹而不是单个视频文件;
> > 我是使用zlm来截外部的流的照片,所以在/www/snap里面有很多以uuid的文件夹照片
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

你自己写个程序来管理吧，或者你二开ZLM

**Comment by xia-chu** [comment]
> 我是使用zlm来截外部的流的照片,所以在/www/snap里面有很多以uuid的文件夹照片

你这个外部的流个数是无限个吗？如果文件太多 定时删除截图根目录就行。或者你自己调用ffmpeg的命令行去截图也行啊
