### ISSUE TITLE
[Feature Request] The project currently provides pts based on the time of pulling the stream, can it provide pts based on the time of pushing the stream?

### ISSUE THREAD

**Issue by liding1992** [ZLMediaKit/ZLMediaKit#4014]
## Describe the purpose of this feature, and provide relevant information to describe this feature
If based on the push stream time, when multiple people preview the same RTSP video stream, they can accurately obtain the image data of a certain timestamp. Ensure that multiple people can obtain the correct image data for related image processing.

## Is this feature used to improve project defects? If so, please describe the existing defects
Currently, the project's RTSP video stream obtains PTS and DTS based on the time of pulling the stream (or starting from 0, or starting from a very small delay time). If different people want to obtain the same image data when previewing the stream, they can only get it based on the system timestamp at that time, with different delays and cache lengths, resulting in the inability to obtain the same or similar images when trying to obtain the same image data. If PTS can be unified from a starting time, different people can obtain the correct image data based on this PTS.

## Describe how you expect to achieve this feature and the final effect
It is hoped that when obtaining the data packet PTS of the RTSP video stream, this PTS can be incrementally counted according to the flow of the video, rather than starting from 0 when a user opens a video stream.

>## 描述该功能的用处，可以提供相关资料描述该功能
如果基于推流的时间，那么多人预览相同rtsp视频流的话，可以精确获取某个时间戳的图像数据。保证多人都能获取到正确的图像数据进行相关图像处理。

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
目前项目提供的rtsp视频流获取pts于dts都是基于拉流的时间（或者说都是从0开始，或者都是从一个很小的延迟时间开始）的。如果不同的人想要在预览视流时获取获取相同的图像数据，那么只能大家只能按照当时的系统时间戳获取，各自的延迟不同缓存长度不同，导致在想要获取相同图像数据的时候无法获取相同或者相近图像。如果可以pts都统一从一个时间开始，那么不同的人都可以根据这个pts来获取到正确的图像数据。

## 描述你期望实现该功能的方式和最终效果
希望rtsp视频流在获取数据包的pts时，这个pts可以是按照视频的流动递增的，而不是在用户打开一个视频流时从0开始计数。

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
你通过sei添加自定义数据吧

**Comment by xia-chu** [comment]
@liding1992 嗨 你这个问题其实很好办 用rtsp组播拉流就能解决 之前我们做视频矩阵就是这么做的
这个能保证时间戳一致 数据一致 接收数据的时间也基本一致
