### ISSUE TITLE
Connecting to Hikvision camera using the addStreamProxy interface to pull the stream reports an error

### ISSUE THREAD

**Issue by mrliu-lau** [ZLMediaKit/ZLMediaKit#4015]
## Phenomenon Description
Connecting to Hikvision camera using the addStreamProxy interface to pull the stream reports an error 401

## How to reproduce?
Hikvision camera RTSP stream address: rtsp://admin:Ky@123456@192.168.1.93:554/Streaming/Channels/1 (can be played normally in VLC)
HTTP request transcoding: rtsp%3A%2F%2Fadmin%3AKy%40123456%40192.168.1.93%3A554%2FStreaming%2FChannels%2F1

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
![1731572016119](https://github.com/user-attachments/assets/104ac125-ee32-4a7a-a01e-2f69e9c7fb6d)
![1731572054353](https://github.com/user-attachments/assets/26158816-5a26-4fb6-acc4-ee088a19c5d8)

```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!

[api]
apiDebug=1
defaultSnap=./www/logo.png
downloadRoot=./www
secret=d3UhWwcVVBKO5qYfBwVtGYkhFwibVzIY
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -frames:v 1 %s

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
listen_ip=::
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.1.63:8087/index/hook/on_play
on_publish=http://192.168.1.63:8087/index/hook/on_publish
on_record_mp4=http://192.168.1.63:8087/index/hook/on_record_mp4
on_record_ts=
on_rtp_server_timeout=http://192.168.1.63:8087/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://192.168.1.63:8087/index/hook/on_send_rtp_stopped
on_server_exited=
on_server_keepalive=http://192.168.1.63:8087/index/hook/on_server_keepalive
on_server_started=http://192.168.1.63:8087/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://192.168.1.63:8087/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.1.63:8087/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.1.63:8087/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=20

[http]
allow_cross_domains=1
allow_ip_range=::1,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:9106dde/2024-06-19T18:42:06+08:00,branch:master,build time:2024-06-19T10:43:39)</center></body></html>
port=28091
rootPath=./www
sendBufSize=65536
sslport=8443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
datachannel_echo=1
externIP=
maxNackMS=5000
maxRtpCacheMS=5000
maxRtpCacheSize=2048
max_bitrate=0
min_bitrate=0
nackIntervalRatio=1.0
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
rtpCacheCheckInterval=100
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=50001-50100
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=8554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5
```
</pre>
</details>

## Various environment information

LINUX AliOS 8.9

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
对接海康摄像头利用接口addStreamProxy拉流报错 401

## 如何复现?
海康摄像头RTSP流地址：rtsp://admin:Ky@123456@192.168.1.93:554/Streaming/Channels/1 （VLC可正常播放）
通过addStreamProxy拉流返回 DESCRIBE:401 Unauthorized
HTTP请求转码：rtsp%3A%2F%2Fadmin%3AKy%40123456%40192.168.1.93%3A554%2FStreaming%2FChannels%2F1
同时，没有接收到on_play事件

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
![1731572016119](https://github.com/user-attachments/assets/104ac125-ee32-4a7a-a01e-2f69e9c7fb6d)
![1731572054353](https://github.com/user-attachments/assets/26158816-5a26-4fb6-acc4-ee088a19c5d8)

```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!

[api]
apiDebug=1
defaultSnap=./www/logo.png
downloadRoot=./www
secret=d3UhWwcVVBKO5qYfBwVtGYkhFwibVzIY
snapRoot=./www/snap/

[cluster]
origin_url=
retry_count=3
timeout_sec=15

[ffmpeg]
bin=/usr/bin/ffmpeg
cmd=%s -re -i %s -c:a aac -strict -2 -ar 44100 -ab 48k -c:v libx264 -f flv %s
log=./ffmpeg/ffmpeg.log
restart_sec=0
snap=%s -rtsp_transport tcp -i %s -y -f mjpeg -frames:v 1 %s

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
listen_ip=::
maxStreamWaitMS=15000
mediaServerId=your_server_id
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=3
segRetain=5

[hook]
alive_interval=10.0
enable=1
on_flow_report=
on_http_access=
on_play=http://192.168.1.63:8087/index/hook/on_play
on_publish=http://192.168.1.63:8087/index/hook/on_publish
on_record_mp4=http://192.168.1.63:8087/index/hook/on_record_mp4
on_record_ts=
on_rtp_server_timeout=http://192.168.1.63:8087/index/hook/on_rtp_server_timeout
on_rtsp_auth=
on_rtsp_realm=
on_send_rtp_stopped=http://192.168.1.63:8087/index/hook/on_send_rtp_stopped
on_server_exited=
on_server_keepalive=http://192.168.1.63:8087/index/hook/on_server_keepalive
on_server_started=http://192.168.1.63:8087/index/hook/on_server_started
on_shell_login=
on_stream_changed=http://192.168.1.63:8087/index/hook/on_stream_changed
on_stream_none_reader=http://192.168.1.63:8087/index/hook/on_stream_none_reader
on_stream_not_found=http://192.168.1.63:8087/index/hook/on_stream_not_found
retry=1
retry_delay=3.0
stream_changed_schemas=rtsp/rtmp/fmp4/ts/hls/hls.fmp4
timeoutSec=20

[http]
allow_cross_domains=1
allow_ip_range=::1,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=30
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:9106dde/2024-06-19T18:42:06+08:00,branch:master,build time:2024-06-19T10:43:39)</center></body></html>
port=28091
rootPath=./www
sendBufSize=65536
sslport=8443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=3000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtc]
datachannel_echo=1
externIP=
maxNackMS=5000
maxRtpCacheMS=5000
maxRtpCacheSize=2048
max_bitrate=0
min_bitrate=0
nackIntervalRatio=1.0
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
rembBitRate=0
rtpCacheCheckInterval=100
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15
port=1935
sslport=0

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port=10000
port_range=50001-50100
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
port=8554
rtpTransportType=-1
sslport=0

[shell]
maxReqSize=1024
port=0

[srt]
latencyMul=4
pktBufSize=8192
port=9000
timeoutSec=5
```
</pre>
</details>

## 各种环境信息

LINUX AliOS 8.9

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by mrliu-lau** [comment]
后续使用大华摄像头测试发现没有这个问题
摄像头流：rtsp://admin:Ky@123456@192.168.1.90:554/cam/realmonitor?channel=1&subtype=0
因公司目前就这两款摄像头 暂时无法提供更多摄像头测试结果，所以不确定是否是摄像头的问题

**Comment by mrliu-lau** [comment]
![1731572016119](https://github.com/user-attachments/assets/48818cf0-fd66-4c49-a274-ac4d3965f66b)
![1731572054353](https://github.com/user-attachments/assets/d722e13e-bb1a-4626-b3fe-7d4dbb789924)
补充日志截图

**Comment by xiongguangjie** [comment]
抓包上传上来，让我们分析下吧vlc 以及zlm 的拉海康摄像头的抓包都抓一下，上传上来，我们对比下

**Comment by mrliu-lau** [comment]
好的 我这边抓一下

**Comment by mrliu-lau** [comment]
[抓包.zip](https://github.com/user-attachments/files/17746835/default.zip)
【VLC】
![1731578606218](https://github.com/user-attachments/assets/230fe5cc-d7f4-4374-94bd-65c058a86929)

【ZLM】
![1731578619883](https://github.com/user-attachments/assets/bec08d52-f150-40ec-831c-77cdee6a4efa)

大佬，帮忙看一下，万分感谢

**Comment by xiongguangjie** [comment]
> [抓包.zip](https://github.com/user-attachments/files/17746835/default.zip) 【VLC】 ![1731578606218](https://private-user-images.githubusercontent.com/47501246/386145666-230fe5cc-d7f4-4374-94bd-65c058a86929.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODA1NDAsIm5iZiI6MTczMTU4MDI0MCwicGF0aCI6Ii80NzUwMTI0Ni8zODYxNDU2NjYtMjMwZmU1Y2MtZDdmNC00Mzc0LTk0YmQtNjVjMDU4YTg2OTI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDljOGExODkwZTJmYzllZWEwMzFiYTcxMGYyMzU2YzlmYjUxNWQ2NDMzYjE0MDExYTRhYTZjYjAxMWE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._doId07URyEvOjOZz-8jzLMEZYnRpD88znXAfl9GWWo)
> 
> 【ZLM】 ![1731578619883](https://private-user-images.githubusercontent.com/47501246/386145665-bec08d52-f150-40ec-831c-77cdee6a4efa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODA1NDAsIm5iZiI6MTczMTU4MDI0MCwicGF0aCI6Ii80NzUwMTI0Ni8zODYxNDU2NjUtYmVjMDhkNTItZjE1MC00MGVjLTgzMWMtNzdjZGVlNmE0ZWZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMWNkZWE3MjQ2MWRkNGM4YjQ3OGU0ZTQzZDljOWRiZTU2M2ViYzM5OWM0ZWRkNjMyZDQ3ZmI5NThmMmRmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WrrZpguj3t-t5r6txW4oEiykAw4NxuCqSDAFUZNmjbI)
> 
> Master, please help take a look, thank you very much
> 
> > [抓包.zip](https://github.com/user-attachments/files/17746835/default.zip)
> > 【VLC】
> > ![1731578606218](https://private-user-images.githubusercontent.com/47501246/386145666-230fe5cc-d7f4-4374-94bd-65c058a86929.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODA1NDAsIm5iZiI6MTczMTU4MDI0MCwicGF0aCI6Ii80NzUwMTI0Ni8zODYxNDU2NjYtMjMwZmU1Y2MtZDdmNC00Mzc0LTk0YmQtNjVjMDU4YTg2OTI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZDljOGExODkwZTJmYzllZWEwMzFiYTcxMGYyMzU2YzlmYjUxNWQ2NDMzYjE0MDExYTRhYTZjYjAxMWE4MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._doId07URyEvOjOZz-8jzLMEZYnRpD88znXAfl9GWWo)
> 
> 【ZLM】 ![1731578619883](https://private-user-images.githubusercontent.com/47501246/386145665-bec08d52-f150-40ec-831c-77cdee6a4efa.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODA1NDAsIm5iZiI6MTczMTU4MDI0MCwicGF0aCI6Ii80NzUwMTI0Ni8zODYxNDU2NjUtYmVjMDhkNTItZjE1MC00MGVjLTgzMWMtNzdjZGVlNmE0ZWZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwMzA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMWNkZWE3MjQ2MWRkNGM4YjQ3OGU0ZTQzZDljOWRiZTU2M2ViYzM5OWM0ZWRkNjMyZDQ3ZmI5NThmMmRmZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WrrZpguj3t-t5r6txW4oEiykAw4NxuCqSDAFUZNmjbI)
> 
> 大佬，帮忙看一下，万分感谢
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

你改过代码？？？，你使用最新的代码试一下，这个抓包与代码对不上，绝对不可能出现这种情况的

**Comment by mrliu-lau** [comment]
没有改过代码 但应该用的不是最新的，请问是使用主分支最新的代码是吗

**Comment by xiongguangjie** [comment]
> Haven't modified the code, but it shouldn't be the latest one, is it supposed to use the latest code from the main branch?
> 
> > 没有改过代码 但应该用的不是最新的，请问是使用主分支最新的代码是吗
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

是的，如果还是不行就抓下包上传让我分析一下

**Comment by xia-chu** [comment]
打个补丁试试：
```path
Index: src/Rtsp/RtspPlayer.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/Rtsp/RtspPlayer.cpp b/src/Rtsp/RtspPlayer.cpp
--- a/src/Rtsp/RtspPlayer.cpp	(revision 25c5f63755f8f91ef96889363c9f5e4055b81a52)
+++ b/src/Rtsp/RtspPlayer.cpp	(date 1731900032507)
@@ -179,7 +179,7 @@
     // 发送DESCRIBE命令后的回复  [AUTO-TRANSLATED:39629cf0]
     // The response after sending the DESCRIBE command
     if ((parser.status() == "401") && handleAuthenticationFailure(authInfo)) {
-        sendOptions();
+        sendDescribe();
         return false;
     }
     if (parser.status() == "302" || parser.status() == "301") {
```

**Comment by mrliu-lau** [comment]
使用了最新的版本构建了镜像，同时引入了hook接口，目前已经可以了，谢谢大佬
