### ISSUE TITLE
[Feature Request] Could you please tell me if there is a way to convert h265 rtsp stream to h264 rtsp stream?

### ISSUE THREAD

**Issue by feipengcheng** [ZLMediaKit/ZLMediaKit#4022]
## Describe the purpose of this feature, and provide relevant information to describe this feature
Due to the old platform only supporting h264 encoded video streams

## Is this feature used to improve project defects? If so, please describe the existing defects
No

## Describe how you expect to achieve this feature and the final effect
Enter the address of the h265 format rtsp stream, for example rtsp://192.168.1.11/a/b, and then return an h264 stream address rtsp://192.168.1.11/a/b/h264

>## 描述该功能的用处，可以提供相关资料描述该功能
由于老的平台只支持h264编码的视频流
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
否
## 描述你期望实现该功能的方式和最终效果
输入h265格式的rtsp流的地址 比如 rtsp://192.168.1.11/a/b,然后返回一个h264的流地址rtsp://192.168.1.11/a/b/h264

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
> ## Describe the purpose of this feature, and provide relevant information to describe this feature
> Due to the old platform only supporting h264 encoded video streams
> 
> ## Is this feature used to improve project defects? If so, please describe the existing defects
> No
> 
> ## Describe how you expect to achieve this feature and the final effect
> Enter the address of the h265 format rtsp stream, for example rtsp://192.168.1.11/a/b, and then return an h264 stream address rtsp://192.168.1.11/a/b/h264
> 
> > ## 描述该功能的用处，可以提供相关资料描述该功能
> 
> 由于老的平台只支持h264编码的视频流
> 
> ## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
> 否
> 
> ## 描述你期望实现该功能的方式和最终效果
> 输入h265格式的rtsp流的地址 比如 rtsp://192.168.1.11/a/b,然后返回一个h264的流地址rtsp://192.168.1.11/a/b/h264
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

这个需要转码，要么使用addffmpegsource 或者使用商业版 https://github.com/tsingeye/ZLMediakit-Pro，或者你自己二次开发
