### ISSUE TITLE
[BUG] 信创环境下安全扫描漏洞

### ISSUE THREAD

**Issue by mxzhu** [ZLMediaKit/ZLMediaKit#4025]
## Phenomenon Description
The current HTTP configuration has cross-domain and whitelist configurations, but for other HTTP response header configurations that report medium and low-risk vulnerabilities during security scanning, they cannot be configured at present.
For example, x-frame-options, x-xss-protection, etc.
Currently, it has been deployed and used in the trusted environment (calling httpApi), and there have been relevant vulnerability feedbacks.

The current HTTP configuration has cross-domain and whitelist configurations, but for other HTTP response header configurations that report medium and low-risk vulnerabilities during security scanning, they cannot be configured at present.
For example, x-frame-options, x-xss-protection, etc.
Currently, it has been deployed and used in the trusted environment (calling httpApi), and there have been relevant vulnerability feedbacks.
## Related logs or screenshots
![image](https://github.com/user-attachments/assets/efed1c21-c871-4c9d-809d-38b185821f2b)

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
目前的http配置里面有跨域和白名单配置,但是对于其他在做安全扫描时会报出中低危漏洞的http响应头配置,目前则无法配置.
例如x-frame-options,x-xss-protection等
目前在信创环境下有部署使用(调用httpApi),已经有相关的漏洞反馈.

目前的http配置里面有跨域和白名单配置,但是对于其他在做安全扫描时会报出中低危漏洞的http响应头配置,目前则无法配置.
例如x-frame-options,x-xss-protection等
目前在信创环境下有部署使用(调用httpApi),已经有相关的漏洞反馈.
## 相关日志或截图
![image](https://github.com/user-attachments/assets/efed1c21-c871-4c9d-809d-38b185821f2b)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
你使用nginx 做下代理不就解决了吗

**Comment by mxzhu** [comment]
> You're using nginx as a proxy, isn't that a solution?
> 
> > 你使用nginx 做下代理不就解决了吗
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

好的,谢谢,我试试,
你说的是配置为只允许内部访问http相关接口,使用nginx代理对外提供api,同时在nginx配置安全漏洞相关的http header,我理解的是否有误?

**Comment by xiongguangjie** [comment]
> > You're using nginx as a proxy, isn't that a solution?
> > > 你使用nginx 做下代理不就解决了吗
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 好的,谢谢,我试试, 你说的是配置为只允许内部访问http相关接口,使用nginx代理对外提供api,同时在nginx配置安全漏洞相关的http header,我理解的是否有误?

这样的，ZLM不直接对外提供接口由自己的服务（或者是ngInx ）来中转
