### ISSUE TITLE
[Compilation Issue] After upgrading NDK, compilation and linking report errors, unable to find getDomainIP

### ISSUE THREAD

**Issue by CosmicWalter** [ZLMediaKit/ZLMediaKit#4038]
Development environment upgraded from NDK 16b to 23b, recompiled ZLMediaKit with the new Android compilation toolchain, reported that the getDomainIP symbol in ZLToolKit could not be found. The upgrade process only replaced the NDK compilation toolchain, and the compilation was normal before the upgrade. The compilation error log is as follows:

## Related logs and environment information

```
ld: error: undefined symbol: toolkit::SockUtil::getDomainIP(char const*, unsigned short, sockaddr_storage&, int, int, int, int)
>>> referenced by RtpSender.cpp
>>>               RtpSender.cpp.o:(std::__ndk1::__function::__func<mediakit::RtpSender::startSend(mediakit::MediaSourceEvent::SendRtpArgs const&, std::__ndk1::function<void (unsigned short, toolkit::SockException const&)> const&)::$_3, std::__ndk1::allocator<mediakit::RtpSender::startSend(mediakit::MediaSourceEvent::SendRtpArgs const&, std::__ndk1::function<void (unsigned short, toolkit::SockException const&)> const&)::$_3>, void ()>::operator()()) in archive ZLMediaKit/release/android/Release/libzlmediakit.a
```

The content of the `CMakeCache.txt` file in the compilation directory, please upload it as an attachment directly.
[CMakeCache.txt](https://github.com/user-attachments/files/17892221/CMakeCache.txt)

## Various environment information

* **Operating System: debian 12**:
* **Hardware Information: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz, 16 GB memory**:

开发环境从NDK 16b升级到23b，用新的安卓编译工具链重新编译ZLMediaKit，报ZLToolKit中的getDomainIP符号找不到，升级过程只替换了NDK编译工具链，升级之前编译正常。
**尝试过使用23b重新编译ZLToolKit，但因没有前人toolkit的编译脚本，导致编译后的zlm产物拉流失败，所以想用16b的ZLToolKit编译zlm。**
编译报错日志如下：

## 相关日志及环境信息

```
ld: error: undefined symbol: toolkit::SockUtil::getDomainIP(char const*, unsigned short, sockaddr_storage&, int, int, int, int)
>>> referenced by RtpSender.cpp
>>>               RtpSender.cpp.o:(std::__ndk1::__function::__func<mediakit::RtpSender::startSend(mediakit::MediaSourceEvent::SendRtpArgs const&, std::__ndk1::function<void (unsigned short, toolkit::SockException const&)> const&)::$_3, std::__ndk1::allocator<mediakit::RtpSender::startSend(mediakit::MediaSourceEvent::SendRtpArgs const&, std::__ndk1::function<void (unsigned short, toolkit::SockException const&)> const&)::$_3>, void ()>::operator()()) in archive ZLMediaKit/release/android/Release/libzlmediakit.a
```

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。
[CMakeCache.txt](https://github.com/user-attachments/files/17892221/CMakeCache.txt)

## 各种环境信息

* **操作系统：debian 12**:
* **硬件信息：Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz，16 GB 内存**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xia-chu** [comment]
我这周刚用最新的ndk编译过zlm全套代码 编译通过了

**Comment by CosmicWalter** [comment]
@xia-chu zltoolkit依赖boringssl和wolfssl，这两个有区别吗？我启用boring后，sslbox报找不到本地证书，然后emittrackready触发不了，导致无法播放https ts流。

**Comment by xia-chu** [comment]
zltoolkit依赖openssl，boringssl是在openssl的基础上修改的 api应该兼容；wolfssl我不了解
