### ISSUE TITLE
[Feature Request] File Access Hopes to Increase Authentication

### ISSUE THREAD

**Issue by RebelTinker** [ZLMediaKit/ZLMediaKit#4040]
## Describe the purpose of this feature, and provide relevant information to describe this feature
![image](https://github.com/user-attachments/assets/7406f5d0-3e59-465e-818a-c69a7c35e45e)

## Is this feature used to improve project defects? If so, please describe the existing defects
Currently, files are fully exposed and can be directly accessed
## Describe how you expect to achieve this feature and the final effect
It is hoped that file access will add authentication functionality

>## 描述该功能的用处，可以提供相关资料描述该功能
![image](https://github.com/user-attachments/assets/7406f5d0-3e59-465e-818a-c69a7c35e45e)

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
目前文件全部裸露可以直接获取
## 描述你期望实现该功能的方式和最终效果
文件访问希望增加鉴权功能

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
> ## Describe the purpose of this feature, and provide relevant information to describe this feature
> ![image](https://private-user-images.githubusercontent.com/58228765/389430633-7406f5d0-3e59-465e-818a-c69a7c35e45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjcwNTksIm5iZiI6MTczMjUyNjc1OSwicGF0aCI6Ii81ODIyODc2NS8zODk0MzA2MzMtNzQwNmY1ZDAtM2U1OS00NjVlLTgxOGEtYzY5YTdjMzVlNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OTJkZTZiOWIwMTM4NWUzOTkwMzllNGEyNTQwOGE2MmQxZjc1ZDVhMmU2MzQyYmIyNDMxNDgyZDg0MDZkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XmODwR83ilBCz11dON5JWQ6_sLfarAY2D-mEy3HP8zQ)
> 
> ## Is this feature used to improve project defects? If so, please describe the existing defects
> Currently, files are fully exposed and can be directly accessed
> 
> ## Describe how you expect to achieve this feature and the final effect
> It is hoped that file access will add authentication functionality
> 
> > ## 描述该功能的用处，可以提供相关资料描述该功能
> 
> ![image](https://private-user-images.githubusercontent.com/58228765/389430633-7406f5d0-3e59-465e-818a-c69a7c35e45e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjcwNTksIm5iZiI6MTczMjUyNjc1OSwicGF0aCI6Ii81ODIyODc2NS8zODk0MzA2MzMtNzQwNmY1ZDAtM2U1OS00NjVlLTgxOGEtYzY5YTdjMzVlNDVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4OTJkZTZiOWIwMTM4NWUzOTkwMzllNGEyNTQwOGE2MmQxZjc1ZDVhMmU2MzQyYmIyNDMxNDgyZDg0MDZkZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XmODwR83ilBCz11dON5JWQ6_sLfarAY2D-mEy3HP8zQ)
> 
> ## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
> 目前文件全部裸露可以直接获取
> 
> ## 描述你期望实现该功能的方式和最终效果
> 文件访问希望增加鉴权功能
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

有配置选项可以配置的，http.dirMenu 设置为0 可以取消这个配置，如果还是不放心，你就用代理(自己的程序或者nginx )来访问，不直接访问ZLM

**Comment by ziyuexiachu** [comment]
on_http_access hook就是鉴权用的
而且allow_ip_range也会限制ip
http.dirMenu 则是控制是否生成http目录(但是不限制下载)

**Comment by xia-chu** [comment]
on_http_access hook就是鉴权用的
而且allow_ip_range也会限制ip
http.dirMenu 则是控制是否生成http目录(但是不限制下载)

**Comment by xia-chu** [comment]
#4041
