### ISSUE TITLE
请求API时报错显示查询不到该参数

### ISSUE THREAD

**Issue by Ling280608** [ZLMediaKit/ZLMediaKit#4045]
# 请求API时报错显示查询不到该参数
![1732694455884](https://github.com/user-attachments/assets/4602764a-2557-474a-9780-f199370dfa65)

**Comment by xiongguangjie** [comment]
ZLM日志上传上来

**Comment by Ling280608** [comment]
> This isn't a request for ZLM, is it? The error content doesn't match, and this 404 also doesn't match ZLM.
> 
> > 你这个不是请求ZLM吧，错误内容对不上，而且你这个是404 也与ZLM对不上
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

Thanks, the problem has been solved, it's a port conflict.
> 感谢，问题已解决、80端口冲突
