### ISSUE TITLE
There are big shots who have compiled a complete aarch64 package, thank you for uploading it. My local machine is X86, the intranet server doesn't have internet access, I urgently need it, and I'm really helpless, thank you, big shots！！！

### ISSUE THREAD

**Issue by caorenyang** [ZLMediaKit/ZLMediaKit#4046]
## Related Logs and Environment Information

**Full output of cmake && make command after clearing compilation cache**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

Please upload the content of the `CMakeCache.txt` file in the compilation directory as an attachment.

## Various Environment Information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **Other information to be supplemented**:

>

## 相关日志及环境信息

**清除编译缓存后，完整执行 cmake && make 命令的输出**

<details>
<summary>展开查看详细编译日志</summary>
<pre>

```
详细日志粘在这里!
```

</pre>
</details>

编译目录下的 `CMakeCache.txt` 文件内容，请直接上传为附件。

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**: linux  5.10.0-182.0.0.95.oe2203sp3.aarch64
* **硬件信息**: 
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by wasphin** [comment]
直接用docker吧，有aarch64的

**Comment by caorenyang** [comment]
您好，我目前用的就是docker，发现很不稳定，容器经常自动停止运行。导致被骂！！！！
&nbsp;


＠紫色魔恋ず
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: "Xiaofeng ***@***.***&gt;; 
Date: 2024年11月30日(星期六) 上午10:42
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [ZLMediaKit/ZLMediaKit] There are big shots who have compiled a complete aarch64 package, thank you for uploading it. My local machine is X86, the intranet server doesn&#39;t have internet access, I urgently need it, and I&#39;m really helpless, thank you, big shots！！！ (Issue #4046)














 
Use Docker directly, it has aarch64
  
直接用docker吧，有aarch64的
  
TRANS_BY_GITHUB_AI_ASSISTANT

**Comment by sayakasama** [comment]
我自己试着编了下aarch64，但是运行有报错
134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer
2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error 312827976

**Comment by xiongguangjie** [comment]
> I tried to compile aarch64 myself, but there was an error when running it 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core file size set to: 18446744073709551615 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | maximum number of file descriptors set to: 4096 terminate called after throwing an instance of 'std::system_error' what(): Unknown error 312827976
> 
> > 我自己试着编了下aarch64，但是运行有报错
> > 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer
> > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
> > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
> > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
> > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
> > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
> > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
> > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
> > 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
> > 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> > 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
> > terminate called after throwing an instance of 'std::system_error'
> > what():  Unknown error 312827976
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

root权限下运行

**Comment by sayakasama** [comment]
> > I tried to compile aarch64 myself, but there was an error when running it 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core file size set to: 18446744073709551615 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | maximum number of file descriptors set to: 4096 terminate called after throwing an instance of 'std::system_error' what(): Unknown error 312827976
> > > 我自己试着编了下aarch64，但是运行有报错
> > > 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer
> > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
> > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
> > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
> > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
> > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
> > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
> > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
> > > 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
> > > 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> > > 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
> > > terminate called after throwing an instance of 'std::system_error'
> > > what():  Unknown error 312827976
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> root权限下运行

当前已经是root权限了

**Comment by xiongguangjie** [comment]
> > > I tried to compile aarch64 myself, but there was an error when running it 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core file size set to: 18446744073709551615 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | maximum number of file descriptors set to: 4096 terminate called after throwing an instance of 'std::system_error' what(): Unknown error 312827976
> > > > 我自己试着编了下aarch64，但是运行有报错
> > > > 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer
> > > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
> > > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
> > > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
> > > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
> > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
> > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
> > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
> > > > 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
> > > > 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> > > > 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
> > > > terminate called after throwing an instance of 'std::system_error'
> > > > what():  Unknown error 312827976
> > > 
> > > 
> > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > 
> > 
> > root权限下运行
> 
> 当前已经是root权限了
这个我以前遇到过，明显是权限没有，如果是docker 你就需要授予root权限

**Comment by sayakasama** [comment]
> > > > I tried to compile aarch64 myself, but there was an error when running it 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core file size set to: 18446744073709551615 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | maximum number of file descriptors set to: 4096 terminate called after throwing an instance of 'std::system_error' what(): Unknown error 312827976
> > > > > 我自己试着编了下aarch64，但是运行有报错
> > > > > 134|admin@lc1861evb_arm64:/ # /data/ota/MediaServer
> > > > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
> > > > > 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
> > > > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
> > > > > 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
> > > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
> > > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
> > > > > 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
> > > > > 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
> > > > > 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
> > > > > 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
> > > > > terminate called after throwing an instance of 'std::system_error'
> > > > > what():  Unknown error 312827976
> > > > 
> > > > 
> > > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > > 
> > > 
> > > root权限下运行
> > 
> > 
> > 当前已经是root权限了
> > 这个我以前遇到过，明显是权限没有，如果是docker 你就需要授予root权限

不是docker，是手持设备。权限这个我刚跟领导也确认了，确实是root权限了，完整的打印我贴了一下，是系统里缺什么东西吗？
[ZLM.txt](https://github.com/user-attachments/files/18001589/ZLM.txt)

**Comment by xiongguangjie** [comment]
你这个哪里是root 呀，用户名是admin

**Comment by sayakasama** [comment]
> This isn't root, the username is admin
> 
> > 你这个哪里是root 呀，用户名是admin
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

root用户也试过了 是一样的现象和信息打印 刚用的之前取下来的信息 没有放新的。
[ZLM_root.txt](https://github.com/user-attachments/files/18001704/ZLM_root.txt)

**Comment by xiongguangjie** [comment]
> > This isn't root, the username is admin
> > > 你这个哪里是root 呀，用户名是admin
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> root用户也试过了 是一样的现象和信息打印 刚用的之前取下来的信息 没有放新的。 这个设备是aarch64的，底层是安卓，会跟这个有关系吗？ [ZLM_root.txt](https://github.com/user-attachments/files/18001704/ZLM_root.txt)

android 没试过, 这个需要你自己去排查android 是否有啥限制了

**Comment by caorenyang** [comment]
哥 你编译完成了吗 求一份 谢谢&nbsp;


＠紫色魔恋ず
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年12月4日(星期三) 上午9:58
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [ZLMediaKit/ZLMediaKit] There are big shots who have compiled a complete aarch64 package, thank you for uploading it. My local machine is X86, the intranet server doesn&#39;t have internet access, I urgently need it, and I&#39;m really helpless, thank you, big shots！！！ (Issue #4046)














     
I tried to compile aarch64 myself, but there was an error when running it ***@***.***_arm64:/ # /data/ota/MediaServer 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core file size set to: 18446744073709551615 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | maximum number of file descriptors set to: 4096 terminate called after throwing an instance of 'std::system_error' what(): Unknown error 312827976
  
我自己试着编了下aarch64，但是运行有报错
 ***@***.***_arm64:/ # /data/ota/MediaServer
 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H264
 2024-12-03 14:40:24.395 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: H265
 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: JPEG
 2024-12-03 14:40:24.396 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: mpeg4-generic
 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: opus
 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMA
 2024-12-03 14:40:24.397 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: PCMU
 2024-12-03 14:40:24.398 I [MediaServer] [21384-MediaServer] Factory.cpp:34 registerPlugin | Load codec: L16
 2024-12-03 14:40:24.400 I [MediaServer] [21384-MediaServer] System.cpp:197 systemSetup | core文件大小设置为:18446744073709551615
 2024-12-03 14:40:24.401 I [MediaServer] [21384-MediaServer] System.cpp:206 systemSetup | 文件最大描述符个数设置为:4096
 terminate called after throwing an instance of 'std::system_error'
 what():  Unknown error 312827976
  
TRANS_BY_GITHUB_AI_ASSISTANT
  
root权限下运行
  
当前已经是root权限了
 这个我以前遇到过，明显是权限没有，如果是docker 你就需要授予root权限
   
不是docker，是手持设备。权限这个我刚跟领导也确认了，确实是root权限了，完整的打印我贴了一下，是系统里缺什么东西吗？
 ZLM.txt

**Comment by xia-chu** [comment]
后面我会考虑添加下arm64的ci自动编译并发布二进制包

**Comment by caorenyang** [comment]
谢谢
&nbsp;


＠紫色魔恋ず
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2024年12月25日(星期三) 上午10:55
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [ZLMediaKit/ZLMediaKit] There are big shots who have compiled a complete aarch64 package, thank you for uploading it. My local machine is X86, the intranet server doesn&#39;t have internet access, I urgently need it, and I&#39;m really helpless, thank you, big shots！！！ (Issue #4046)














 
Later I will consider adding arm64's CI automatic compilation and release of binary packages
  
后面我会考虑添加下arm64的ci自动编译并发布二进制包
  
TRANS_BY_GITHUB_AI_ASSISTANT
