### ISSUE TITLE
[BUG] HLS playback is not working, no video

### ISSUE THREAD

**Issue by xxdyh** [ZLMediaKit/ZLMediaKit#4047]
## Phenomenon Description

Windows, using the default config, automatically generates HLS when pushing streams, the first ts file has a picture, but the subsequent ts files do not have a picture.

## How to reproduce?

Using ffmpeg to push local video files will always reproduce

http://localhost/live/0.live.flv can play normally and has a picture
http://localhost/live/0/hls.m3u8 The first TS file has a picture, but the subsequent ones do not, only sound

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

Windows下，使用默认的config，推流自动生成HLS，第一个ts生成的时候有画面，后面的ts文件就没有画面了。

## 如何复现?

使用ffmpeg推流本地视频文件后必现

http://localhost/live/0.live.flv   能正常播放，且有画面
http://localhost/live/0/hls.m3u8 第一个TS文件有画面，后面就没有了，只有声音

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
上传日志，已经生成的ts文件

**Comment by xxdyh** [comment]
[Uploading hls.zip…]()

**Comment by xiongguangjie** [comment]
> Uploading hls.zip…
> 
> > Uploading hls.zip…
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

没文件呀

**Comment by xxdyh** [comment]
[0.zip](https://github.com/user-attachments/files/17972014/0.zip)
重新上传

**Comment by xiongguangjie** [comment]
你是最新的代码，这个不应该出现这种情况呀？？？？

**Comment by xxdyh** [comment]
文件太大传不上来，提供网盘地址：
链接: https://pan.baidu.com/s/1aa_pR2KynXtxhBae-ntQ1w?pwd=qj9f 提取码: qj9f 

推流命令：ffmpeg -re -i D:\1.mp4  -c:v libx264 -vcodec copy -acodec copy  -f flv rtmp://localhost/live/0

拉取的是最新代码编译的，以前是不存在这个BUG的，也测试了前一个版本的也存在这个问题，就是不知道从什么时候开始出现的

**Comment by xiongguangjie** [comment]
> The file is too large to upload, providing a cloud drive address: Link: https://pan.baidu.com/s/1aa_pR2KynXtxhBae-ntQ1w?pwd=qj9f Extraction code: qj9f
> 
> Streaming command: ffmpeg -re -i D:\1.mp4 -c:v libx264 -vcodec copy -acodec copy -f flv rtmp://localhost/live/0
> 
> The pulled code is the latest compiled version, this BUG did not exist before, and the previous version was also tested to have this problem, just don't know when it started to appear.
> 
> > 文件太大传不上来，提供网盘地址：
> > 链接: https://pan.baidu.com/s/1aa_pR2KynXtxhBae-ntQ1w?pwd=qj9f 提取码: qj9f
> 
> 推流命令：ffmpeg -re -i D:\1.mp4 -c:v libx264 -vcodec copy -acodec copy -f flv rtmp://localhost/live/0
> 
> 拉取的是最新代码编译的，以前是不存在这个BUG的，也测试了前一个版本的也存在这个问题，就是不知道从什么时候开始出现的
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`
不要使用百度网盘上传文件（因为需要登录），使用蓝奏云

**Comment by xiongguangjie** [comment]
我这边用自己的文件测试没有问题，但是我根据你上传的ts文件分析，应该是推的流 h264 aud 有问题，导致播放软件无法解析sps pps

**Comment by xxdyh** [comment]
> And also, your streaming command has a problem, the encoder is libx264 or copy, there is duplication.
> 
> > 而且你的推流命令，有问题，编码器是libx264 还是copy 有重复
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

应该用什么命令呢，之前这个推流命令写法是没有问题的

刚我又重新测试了下
1、ffmpeg -re -i D:\1.mp4  -c:v libx264  -f flv rtmp://localhost/live/0  
     有画面，没有声音，而且画面只有vlc播放器能放，网页的无法播放

2、ffmpeg -re -i D:\1.mp4  -vcodec copy -acodec copy  -f flv rtmp://localhost/live/0
     就和一开始的一样，只有第一个TS文件有画面

本地的ffmpeg版本也是最新的ffmpeg version 7.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers

**Comment by xiongguangjie** [comment]
> > And also, your streaming command has a problem, the encoder is libx264 or copy, there is duplication.
> > > 而且你的推流命令，有问题，编码器是libx264 还是copy 有重复
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 应该用什么命令呢，之前这个推流命令写法是没有问题的
> 
> 刚我又重新测试了下 1、ffmpeg -re -i D:\1.mp4 -c:v libx264 -f flv rtmp://localhost/live/0 有画面，没有声音，而且画面只有vlc播放器能放，网页的无法播放
> 
> 2、ffmpeg -re -i D:\1.mp4 -vcodec copy -acodec copy -f flv rtmp://localhost/live/0 就和一开始的一样，只有第一个TS文件有画面
> 
> 本地的ffmpeg版本也是最新的ffmpeg version 7.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers

你把视频文件提供下上传到蓝奏云之类的，不需要登录的，否则我没法分析

**Comment by xxdyh** [comment]
https://github.com/user-attachments/assets/974f250a-5cae-457f-bdfd-51b750b86866

**Comment by xiongguangjie** [comment]
> 1.mp4

压缩包上传

**Comment by xiongguangjie** [comment]
使用下面的补丁修复下吧，你这个码流比较异常
```diff --git a/ext-codec/H264.cpp b/ext-codec/H264.cpp
index 50dcfb22..38c1d9bc 100644
--- a/ext-codec/H264.cpp
+++ b/ext-codec/H264.cpp
@@ -267,31 +267,32 @@ bool H264Track::inputFrame_l(const Frame::Ptr &frame) {
     switch (type) {
         case H264Frame::NAL_SPS: {
             _sps = string(frame->data() + frame->prefixSize(), frame->size() - frame->prefixSize());
-            _latest_is_config_frame = true;
+            _latest_is_sps = true;
             ret = VideoTrack::inputFrame(frame);
             break;
         }
         case H264Frame::NAL_PPS: {
             _pps = string(frame->data() + frame->prefixSize(), frame->size() - frame->prefixSize());
-            _latest_is_config_frame = true;
+            _latest_is_pps = true;
             ret = VideoTrack::inputFrame(frame);
             break;
         }
         default:
             // 避免识别不出关键帧  [AUTO-TRANSLATED:8eb84679]
             // Avoid not being able to recognize keyframes
-            if (_latest_is_config_frame && !frame->dropAble()) {
+            if (latestIsConfigFrame() && !frame->dropAble()) {
                 if (!frame->keyFrame()) {
                     const_cast<Frame::Ptr &>(frame) = std::make_shared<FrameCacheAble>(frame, true);
                 }
             }
             // 判断是否是I帧, 并且如果是,那判断前面是否插入过config帧, 如果插入过就不插入了  [AUTO-TRANSLATED:40733cd8]
             // Determine if it is an I frame, and if it is, determine if a config frame has been inserted before, and if it has been inserted, do not insert it
-            if (frame->keyFrame() && !_latest_is_config_frame) {
+            if (frame->keyFrame() && !latestIsConfigFrame()) {
                 insertConfigFrame(frame);
             }
             if(!frame->dropAble()){
-                _latest_is_config_frame = false;
+                _latest_is_pps = false;
+                _latest_is_sps = false;
             }
             ret = VideoTrack::inputFrame(frame);
             break;
@@ -313,6 +314,10 @@ void H264Track::insertConfigFrame(const Frame::Ptr &frame) {
     }
 }
 
+bool H264Track::latestIsConfigFrame(){
+    return _latest_is_sps && _latest_is_pps;
+}
+
 class H264Sdp : public Sdp {
 public:
     H264Sdp(const string &strSPS, const string &strPPS, int payload_type, int bitrate) : Sdp(90000, payload_type) {
diff --git a/ext-codec/H264.h b/ext-codec/H264.h
index c65c8479..55b6f1ff 100644
--- a/ext-codec/H264.h
+++ b/ext-codec/H264.h
@@ -146,8 +146,11 @@ private:
     bool inputFrame_l(const Frame::Ptr &frame);
     void insertConfigFrame(const Frame::Ptr &frame);
 
+    bool latestIsConfigFrame();
+
 private:
-    bool _latest_is_config_frame = false;
+    bool _latest_is_pps = false;
+    bool _latest_is_sps = false;
     int _width = 0;
     int _height = 0;
     float _fps = 0;
```
