### ISSUE TITLE
[BUG] 摄像头直播串流

### ISSUE THREAD

**Issue by 199212zz** [ZLMediaKit/ZLMediaKit#4049]
## Phenomenon Description

The camera uses cascaded registration of WVP, and in the case of poor network conditions, it is likely to cause streaming issues, such as camera A registering WVP through cascaded registration, and camera B registering normally through the Hikvision platform. At this time, if A is always in playback, clicking the playback button of camera B on the WVP page, in the case of poor network conditions, will likely play the live video of A.

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

摄像头使用级联注册的wvp，在网络不好情况下大概率出现串流情况，如摄像头A通过级联注册wvp，摄像头B通过海康平台正常注册，此时若A一直在播放中，点击wvp页面上摄像头B的播放按钮，在网络不好的情况下，大概率会播放A的直播画面

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by PioLing** [comment]
这个你网络不好，sip 传输时丢了事务会话，导致信令和媒体会话不一致的，请使用tcp（tcp 被动 ...） 请求下级推流，应该可以解决

**Comment by 199212zz** [comment]
已经设置了心灵tcp,流tcp被动模式，还是会发生这种情况

**Comment by 199212zz** [comment]
信令

**Comment by PioLing** [comment]
在openrtpserver 接口传入 ssrc 的value 看看（即开启ssrc 校验）

**Comment by xia-chu** [comment]
使用wvp串流问题 一概和zlm无关。
这个是端口被混乱使用了 纯业务bug
