### ISSUE TITLE
[Feature Request] How to Overlay Text

### ISSUE THREAD

**Issue by JaneYork** [ZLMediaKit/ZLMediaKit#4053]
## Describe how you expect to achieve this feature and the final effect
How to overlay text on real-time video streams, similar to adding a watermark

>## 描述该功能的用处，可以提供相关资料描述该功能

## 描述你期望实现该功能的方式和最终效果
如何在实时视频流中叠加文字，类似打水印

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
播放器端做，或者服务器端去解码->叠加水印->编码 .需要二次开发（使用ffmpeg ），没有现成的

**Comment by xia-chu** [comment]
@JaneYork 这个需要先解码 然后添加水印 然后再编码，这个功能的基础是转码和滤镜
目前这个功能在zlmediakit pro闭源代码上已经实现了 感兴趣的话加我微信 xiachuziyue
