### ISSUE TITLE
[Feature Request] Removed the stream address, only leaving the app address, rtsp cannot pull the stream

### ISSUE THREAD

**Issue by ccDraw** [ZLMediaKit/ZLMediaKit#4056]
## Describe the purpose of this feature, and provide relevant information to describe this feature

The current requirement only wants the app's address, not the stream's address
![image](https://github.com/user-attachments/assets/e32b62a1-0ccb-4db6-ad53-ede647e7276c)
So I deleted the `mk_media_t` assertion and removed the path splicing
![image](https://github.com/user-attachments/assets/4447aa91-054d-4dc4-abd9-79a0a1a4a9bc)
, the program log is as follows
![image](https://github.com/user-attachments/assets/5c6570e3-5aa4-4e48-bc3a-b0321cbfb501)
The phenomenon is that the RTSP streaming fails. Please ask if there are any internal restrictions that require both app and stream parameters' paths.

## Version and environment
```
git rev-parse HEAD
72c285908c524fc3882c036cc964488279b9e47f
```
* **Operating system and version**:
* ubuntu20.04
* **Hardware information**:
* rk3588

>## 描述该功能的用处，可以提供相关资料描述该功能

现在的需求的只想要app的地址，不想要stream的地址
![image](https://github.com/user-attachments/assets/e32b62a1-0ccb-4db6-ad53-ede647e7276c)
于是我删除了`mk_media_t`的assert，同时删除路径拼接
![image](https://github.com/user-attachments/assets/4447aa91-054d-4dc4-abd9-79a0a1a4a9bc)
，程序日志如下
![image](https://github.com/user-attachments/assets/5c6570e3-5aa4-4e48-bc3a-b0321cbfb501)
现象是rtsp拉流失败。请问内部还有什么地方限制了需要app 和 stream的两个参数的路径吗。

## 版本及环境
```
git rev-parse HEAD
72c285908c524fc3882c036cc964488279b9e47f
```
* **操作系统及版本**:
* ubuntu20.04
* **硬件信息**:
* rk3588

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
不能这么修改，这是强制要求的，否则都会出问题的

**Comment by xia-chu** [comment]
url必须两级是由于rtmp协议的限制  rtmp就这么规定的
