### ISSUE TITLE
[Feature Request] GET request response adds Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by superHuang1** [ZLMediaKit/ZLMediaKit#4058]
## Describe the purpose of this feature, and provide relevant information to describe this feature
The browser plays cross-domain video files and captures the current video frame, but encounters CORS restrictions
## Is this feature used to improve project defects? If so, please describe the existing defects
Yes, when making a GET request to retrieve the video, the server does not return Access-Control-Allow-Origin, resulting in the inability to capture the current video frame
## Describe how you expect to achieve this feature and the final effect
None

>## 描述该功能的用处，可以提供相关资料描述该功能
浏览器播放跨域的视频文件，截取当前视频帧，会出现CORS 限制
## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
是，GET 请求获取视频，服务器未返回 Access-Control-Allow-Origin，会导致无法截取当前视频帧
## 描述你期望实现该功能的方式和最终效果
无

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
配置文件http.allow_cross_domains 设置为1 , 默认情况下是允许跨域的

**Comment by superHuang1** [comment]
> 配置文件`http.allow_cross_domains`设置为`1`，默认允许跨域。
> 
> > 配置文件http.allow_cross_domains 设置为 1 ，默认情况下是允许跨域的
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

![image](https://github.com/user-attachments/assets/962168a0-ba38-4cdc-bf31-7b9c56605ab2)
可以看到POST请求是携带了Access-Control-Allow-Origin响应头，GET请求的响应头并不携带Access-Control-Allow-Origin

**Comment by xiongguangjie** [comment]
> > 配置文件`http.allow_cross_domains`设置为`1`，默认允许跨域。
> > > 配置文件http.allow_cross_domains 设置为 1 ，默认情况下是允许跨域的
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> ![image](https://private-user-images.githubusercontent.com/94339281/395096919-962168a0-ba38-4cdc-bf31-7b9c56605ab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTIyMzQsIm5iZiI6MTczNDA1MTkzNCwicGF0aCI6Ii85NDMzOTI4MS8zOTUwOTY5MTktOTYyMTY4YTAtYmEzOC00Y2RjLWJmMzEtN2I5YzU2NjA1YWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAxMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmY2UxZmE4ZTg3MDdjMmZjNzc0NGNhYWNjODBiNjQ5OTMyOWFjODJkMjliMWM2NDllZjczZmQ0OTA3NDhmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BNRAjuK0yoY5Lvv9GU6dB22ZbyKEewQCiFF8Uf3sVnU) 可以看到POST请求是携带了Access-Control-Allow-Origin响应头，GET请求的响应头并不携带Access-Control-Allow-Origin

只有在Origin header 存在时，才会把跨域头写进去（没有跨域需要的情况下就不会添加跨域头的）

**Comment by superHuang1** [comment]
> > > 配置文件`http.allow_cross_domains`设置为`1`，默认允许跨域。
> > > > 配置文件http.allow_cross_domains 设置为 1 ，默认情况下是允许跨域的
> > > 
> > > 
> > > `TRANS_BY_GITHUB_AI_ASSISTANT`
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/94339281/395096919-962168a0-ba38-4cdc-bf31-7b9c56605ab2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNTIyMzQsIm5iZiI6MTczNDA1MTkzNCwicGF0aCI6Ii85NDMzOTI4MS8zOTUwOTY5MTktOTYyMTY4YTAtYmEzOC00Y2RjLWJmMzEtN2I5YzU2NjA1YWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEzVDAxMDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmY2UxZmE4ZTg3MDdjMmZjNzc0NGNhYWNjODBiNjQ5OTMyOWFjODJkMjliMWM2NDllZjczZmQ0OTA3NDhmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BNRAjuK0yoY5Lvv9GU6dB22ZbyKEewQCiFF8Uf3sVnU) 可以看到POST请求是携带了Access-Control-Allow-Origin响应头，GET请求的响应头并不携带Access-Control-Allow-Origin
> 
> 只有在Origin header 存在时，才会把跨域头写进去（没有跨域需要的情况下就不会添加跨域头的）

感谢，发现video标签发出的请求不会携带Origin，需要额外添加<video crossorigin="anonymous"/>
