### ISSUE TITLE
[BUG] addFFmpegSource 接口不是支持任意协议么

### ISSUE THREAD

**Issue by RebelTinker** [ZLMediaKit/ZLMediaKit#4068]
## 现象描述

调用这个接口提示只支持rtmp/rstp协议 我希望能支持rtp协议

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by RebelTinker** [comment]
希望通过 这个接口 推送到 openRtpServer接口开放的rtp端口 然后就可以用startSendRtp推送到国标

**Comment by xia-chu** [comment]
只要ffmpeg支持的输入 这个接口都支持

**Comment by RebelTinker** [comment]
目前我调用接口 提示 只支持RTMP 和RSTP 这个是因为我没有传递FFmpeg的命令么 我用的是zlm 默认的

**Comment by RebelTinker** [comment]
我的意思是 dst_url 这个参数  推送的目的地是只支持rtmp和rstp么

**Comment by xia-chu** [comment]
> 我的意思是 dst_url 这个参数 推送的目的地是只支持rtmp和rstp么

如果推送给zlm，那么还支持rtp，只要zlm支持的推流协议都行。
如果推送给其他服务器，随便你咋写，反正zlm也是执行ffmpeg命令行
