### ISSUE TITLE
关于支持音频转码的建议，比如G711转AAC

### ISSUE THREAD

**Issue by swwheihei** [ZLMediaKit/ZLMediaKit#407]
在安防监控领域，现阶段普遍采用H5的方式播放，但开源的H5播放器不支持G711音频，只支持AAC，例如flv.js。
wasm方式虽然可以支持，但对多路播放存在性能问题。

虽然摄像头可以修改音频为G711，但是主流的海康摄像头在语音对讲场景中，只支持G711音频。这样就会导致改为G711，web端没有声音甚至无法播放；改为AAC，web端正常，但摄像头没法播放声音。

求老大支持。

**Comment by dengchaowen-cx** [comment]
大神可以 分享一下 对讲实现的思路吗 我也想实现对讲 我c++11还是入门水平 不知道怎么下手 谢谢

**Comment by rmokerone** [comment]
同样有这样的需求，求指点。

**Comment by lovederh** [comment]
同上

**Comment by zh19900725** [comment]
同样有这个需求，请求指点

**Comment by xia-chu** [comment]
feature/transcode分支已经实现

**Comment by Haoxw** [comment]
> feature/transcode分支已经实现

这个功能如何配置启用G711A/U转ACC呢，配置文件？如果配置启用后，过来的混合视频流中过来的是G771A/U的音频，能够在转成FLV或HLS流的时候，能自动转码为AAC？feature/transcode分支和feature/transcode2分支有什么区别呢？谢谢！

**Comment by Haoxw** [comment]
feature/transcode分支中，这个771A/U转ACC的功能是在哪个CCP文件中实现的呢？谢谢！

**Comment by Haoxw** [comment]
> > feature/transcode分支中，这个771A/U转ACC的功能是在哪个CCP文件中实现的呢？谢谢！
> 
> 你搜索下FFmpegEncoder和FFmpegDecoder不就知道了？

我搜索一下，非常感谢！

**Comment by Haoxw** [comment]
> feature/transcode分支已经实现

这个功能如何配置启用G711A/U转ACC呢，配置文件？如果配置启用后，过来的混合视频流中过来的是G771A/U的音频，能够在转成FLV或HLS流的时候，能自动转码为AAC？
