### ISSUE TITLE
[BUG] The streaming type is multicast, but it prompts that it is not supported after filling in.

### ISSUE THREAD

**Issue by zylok520** [ZLMediaKit/ZLMediaKit#4072]
## Phenomenon Description
The streaming type is multicast, but after filling it in, it prompts that it is not supported

## Related logs or screenshots
![image](https://github.com/user-attachments/assets/2ab61f90-3347-4cb4-a248-9161503b8af4)

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述
推流类型为组播，填写后提示不支持

## 相关日志或截图
![image](https://github.com/user-attachments/assets/2ab61f90-3347-4cb4-a248-9161503b8af4)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
不支持

**Comment by xia-chu** [comment]
addStreamProxy接口只支持rtsp/rtmp/hls/http-flv/http-ts

**Comment by zylok520** [comment]
> Not supported
> 
> > 不支持
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

请教一 下。这个拉流方式为组播，需要怎么操作呢？我查了好多文档，不太详细。虚心请教一下谢谢！

**Comment by zylok520** [comment]
> The addStreamProxy interface only supports rtsp/rtmp/hls/http-flv/http-ts
> 
> > addStreamProxy接口只支持rtsp/rtmp/hls/http-flv/http-ts
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

请教一 下您 。这个拉流方式为组播的功能。先谢谢了

**Comment by xia-chu** [comment]
> 请教一 下您 。这个拉流方式为组播的功能。先谢谢了
@zylok520 组播拉流这个功能已经实现了 不过是闭源的 感兴趣的话加我微信 xiachuziyue
