### ISSUE TITLE
[BUG] Packet loss rate is always 0

### ISSUE THREAD

**Issue by 199212zz** [ZLMediaKit/ZLMediaKit#4074]
## Phenomenon Description

Calling zlm's /index/api/getMediaInfo interface, it will return loss, this value is always returned as 0, regardless of whether the network is slow or not

## Related logs or screenshots

<details>
<summary>Expand to view detailed logs</summary>
<pre>

```
#Please paste the detailed log here!
```
</pre>
</details>

## Configuration

<details>
<summary>Please expand to view detailed configuration</summary>
<pre>

```ini
#Please paste the contents of the config.ini file here!
```
</pre>
</details>

## Various environment information

* **Code commit record/git commit hash**:
* **Operating system and version**:
* **Hardware information**:
* **crash backtrace**:
```
#Paste the crash information backtrace here
```
* **Other information to be supplemented**:

>

## 现象描述

调用zlm的/index/api/getMediaInfo接口，里面会返回loss，这个值不管网络卡不卡，都是返回0

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

`TRANS_BY_GITHUB_AI_ASSISTANT`

**Comment by xiongguangjie** [comment]
这个是udp传输这个才有意义，其他的没用

**Comment by 199212zz** [comment]
改为udp后，网络卡的那一瞬间会变化，然后又恢复到了0

**Comment by xiongguangjie** [comment]
> After changing to UDP, the network card's instantaneous change will occur, then it will recover back to 0.
> 
> > 改为udp后，网络卡的那一瞬间会变化，然后又恢复到了0
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

那就是没有丢包呀

**Comment by 199212zz** [comment]
![2d9fe8542b6751d375eb3c509d9d18b](https://github.com/user-attachments/assets/49b89d99-b618-4b30-8370-dc98f759c58a)
网络卡的时候也一直为0，偶尔会变化，变化的是这样的值

**Comment by xiongguangjie** [comment]
> ![2d9fe8542b6751d375eb3c509d9d18b](https://private-user-images.githubusercontent.com/179063772/398304317-49b89d99-b618-4b30-8370-dc98f759c58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjEwMzksIm5iZiI6MTczNTAyMDczOSwicGF0aCI6Ii8xNzkwNjM3NzIvMzk4MzA0MzE3LTQ5Yjg5ZDk5LWI2MTgtNGIzMC04MzcwLWRjOThmNzU5YzU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNjEyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTEwMDUwNTJmMmNmNzIxNGVlNTIzZTZjZTQ4NzUzMTRkMzI0MTJjMmI2ZDNmMDc4ZmE3NWZiMjYxMDhjYzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7oEKhGGoNRhnYyCHQz3kLEXUclBeVEeuUokE3VVp9P0) The network card is always 0 when it's stuck, and it occasionally changes, the changing value is like this
> 
> > ![2d9fe8542b6751d375eb3c509d9d18b](https://private-user-images.githubusercontent.com/179063772/398304317-49b89d99-b618-4b30-8370-dc98f759c58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMjEwMzksIm5iZiI6MTczNTAyMDczOSwicGF0aCI6Ii8xNzkwNjM3NzIvMzk4MzA0MzE3LTQ5Yjg5ZDk5LWI2MTgtNGIzMC04MzcwLWRjOThmNzU5YzU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNFQwNjEyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTEwMDUwNTJmMmNmNzIxNGVlNTIzZTZjZTQ4NzUzMTRkMzI0MTJjMmI2ZDNmMDc4ZmE3NWZiMjYxMDhjYzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7oEKhGGoNRhnYyCHQz3kLEXUclBeVEeuUokE3VVp9P0)
> > 网络卡的时候也一直为0，偶尔会变化，变化的是这样的值
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

我看了一下，他是统计上一次与当前时刻的丢包率，除非统计的时间段发送丢包了，才会有值，否则一直未0

**Comment by 199212zz** [comment]
能修复下这个丢包率么，这样可以直观知道当前网络情况

**Comment by xiongguangjie** [comment]
> Can you fix the packet loss rate, so that you can intuitively know the current network situation?
> 
> > 能修复下这个丢包率么，这样可以直观知道当前网络情况
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

这个是正常的，不是啥bug, 以前丢包了，不表示以后一定会丢包

**Comment by xia-chu** [comment]
这个丢包率是统计最近一段时间间隔的实时丢包率 不是历史以来的总丢包率
