### ISSUE TITLE
[BUG] 点播失败，返回 status：486,message:Busy Here

### ISSUE THREAD

**Issue by 199212zz** [ZLMediaKit/ZLMediaKit#4075]
## 现象描述

使用wvp点播时，zlm返回 status：486,message:Busy Here

## 相关日志或截图

![image](https://github.com/user-attachments/assets/82adf4ab-0a76-4551-b1d1-6497b61e1d41)
![image](https://github.com/user-attachments/assets/d66ad741-be83-4455-af75-e2bcee70aff7)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
这个是设备再忙，拒绝了
