### ISSUE TITLE
[BUG] BUG现象描述(必填)rtpserver tcp监听概率出现失败，这种情况下抛出异常之后，udp处于监听状态没有释放。导致端口越占越多

### ISSUE THREAD

**Issue by c282364** [ZLMediaKit/ZLMediaKit#4079]
## 现象描述
rtpserver tcp监听概率出现失败，这种情况下抛出异常之后，udp处于监听状态没有释放。导致端口越占越多

 ##在使用什么功能产生的问题? 其异常表现是什么?
创建一个rtpserver： server = std::make_shared<RtpServer>();，然后server ->start()，参数指定启用tcp。概率出现【sockutil.cpp:447 bind_sock4 | Bind socket failed: address already in use】错误。 然后该端口udp处于监听状态没有释放掉。

## 如何复现?
不停的创建rtpserver然后start, 参数里启用tcp。主要参数如下。local_port：0，local_ip："0.0.0.0"，tuple：{ "vhost", "app", stream_id, ""};，tcp_mode：PASSIVE，re_use_port：true, ssrc:0, only_track:0, multiplex:false

## 相关日志或截图
2024-12-23 16:46:22.366 I [byAlgoContainer1] [8458-byAlgoContainer] Rtsp.cpp:442 getPortPair | got port from pool:33208-33209
2024-12-23 16:46:22.366 W [byAlgoContainer1] [8458-byAlgoContainer] sockutil.cpp:447 bind_sock4 | Bind socket failed: address already in use
2024-12-23 16:46:22.366 E [byAlgoContainer1] [8458-byAlgoContainer] WebApi.cpp:2325 createTask | start rtp failed, exception: Listen on 0.0.0.0 33208 failed: address already in use

端口占用截图如下
![端口占用](https://github.com/user-attachments/assets/390ca39e-c961-43aa-ba62-e7a598424b93)

## 配置
[api]
apiDebug=1
secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc

[general]
broadcast_player_count_changed=0
check_nvidia_dev=1
enableVhost=0
enable_ffmpeg_log=0
flowThreshold=1024
maxStreamWaitMS=15000
mediaServerId=bQBlP4EGAevsdt0Q
mergeWriteMS=0
resetWhenRePlay=1
streamNoneReaderDelayMS=20000
unready_frame_cache=100
wait_add_track_ms=3000
wait_audio_track_data_ms=1000
wait_track_ready_ms=10000

[hls]
broadcastRecordTs=0
deleteDelaySec=10
fastRegister=0
fileBufSize=65536
segDelay=0
segDur=2
segKeep=0
segNum=3
segRetain=5

[http]
allow_cross_domains=1
allow_ip_range=::1,127.0.0.1,172.16.0.0-172.31.255.255,192.168.0.0-192.168.255.255,10.0.0.0-10.255.255.255
charSet=utf-8
dirMenu=1
forbidCacheSuffix=
forwarded_ip_header=
keepAliveSecond=15
maxReqSize=40960
notFound=<html><head><title>404 Not Found</title></head><body bgcolor="white"><center><h1>您访问的资源不存在！</h1></center><hr><center>ZLMediaKit(git hash:/,branch:,build time:2024-09-11T16:28:42)</center></body></html>
port=8081
rootPath=./www
sendBufSize=65536
sslport=443
virtualPath=

[multicast]
addrMax=239.255.255.255
addrMin=239.0.0.0
udpTTL=64

[protocol]
add_mute_audio=1
auto_close=0
continue_push_ms=15000
enable_audio=1
enable_fmp4=1
enable_hls=1
enable_hls_fmp4=0
enable_mp4=0
enable_rtmp=1
enable_rtsp=1
enable_ts=1
fmp4_demand=0
hls_demand=0
hls_save_path=./www
modify_stamp=2
mp4_as_player=0
mp4_max_second=3600
mp4_save_path=./www
paced_sender_ms=0
rtmp_demand=0
rtsp_demand=0
ts_demand=0

[record]
appName=record
enableFmp4=0
fastStart=0
fileBufSize=65536
fileRepeat=0
sampleMS=500

[rtmp]
directProxy=1
enhanced=0
handshakeSecond=15
keepAliveSecond=15

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
opus_pt=100
port_range=30000-35000
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
rtpTransportType=-1

[shell]
maxReqSize=1024

## 各种环境信息
COMMIT_HASH "7c5ba5a"
COMMIT_TIME "2024-09-10T10:59:44+08:00"
BRANCH_NAME "master"
BUILD_TIME "2024-09-10T11:11:37"

  * 操作系统及版本, 
  * 
  * ubuntu18.04
  * 
  * 硬件信息, 
  -->11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz

**Comment by xiongguangjie** [comment]
日志呢？？？报什么错误？

**Comment by c282364** [comment]
2024-12-23 16:46:22.366 I [byAlgoContainer1] [8458-byAlgoContainer] Rtsp.cpp:442 getPortPair | got port from pool:33208-33209
2024-12-23 16:46:22.366 W [byAlgoContainer1] [8458-byAlgoContainer] sockutil.cpp:447 bind_sock4 | Bind socket failed: address already in use
2024-12-23 16:46:22.366 E [byAlgoContainer1] [8458-byAlgoContainer] WebApi.cpp:2325 createTask | start rtp failed, exception: Listen on 0.0.0.0 33208 failed: address already in use

**Comment by c282364** [comment]
不是必现 反复使用会出现。tcp端口监听失败以后 udp的一直监听状态 不会释放了

**Comment by xiongguangjie** [comment]
这个端口被别人占有了吧，这个端口范围应该是由ZLM独占的，而且你这个自己改了代码你就自己排查

**Comment by c282364** [comment]
嗯 我的意思是tcp listen失败以后 绑定的udp不会释放考虑
