### ISSUE TITLE
demo报错

### ISSUE THREAD

**Issue by xiaoshuangyang** [ZLMediaKit/ZLMediaKit#4081]
## 现象描述
我想问一下，为什么这个demo会报这样的错
![image](https://github.com/user-attachments/assets/461f6cfc-41c4-41f5-b4a7-f4bc378a31c8)

## 相关日志或截图

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by wasphin** [comment]
建议先了解相关概念

**Comment by mtdxc** [comment]
这是rtc的测试界面，不是用来测试rtsp的，建议多看看文档。
