### ISSUE TITLE
[BUG] 我用ffmpeg推流rtmp，AVC1+aac，rtmp链接有声音，但是webrtc没有声音

### ISSUE THREAD

**Issue by ZJDATY** [ZLMediaKit/ZLMediaKit#4086]
## 现象描述
我用ffmpeg推流rtmp，AVC1+aac，rtmp链接有声音，但是webrtc没有声音

Stream #0:0: Audio: aac (LC), 11025 Hz, stereo, fltp, 33 kb/s

是否是音频格式不支持，我转换尝试了多种aac 不同码率，采样率，都无法用webrtc播放出声音

## 相关日志或截图
下面是rtmp链接的播放信息
![image](https://github.com/user-attachments/assets/2420e94c-849c-4359-bde7-467b205033b7)

<details>
<summary>展开查看详细日志</summary>
<pre>

```
#详细日志粘在这里!
```
</pre>
</details>

## 配置

<details>
<summary>展开查看详细配置</summary>
<pre>

```ini
#config.ini内容粘在这里!
默认
```
</pre>
</details>

## 各种环境信息

* **代码提交记录/git commit hash**:
* **操作系统及版本**:
* **硬件信息**:
* **crash backtrace**:
```
#崩溃信息backtrace粘贴至此
```
* **其他需要补充的信息**:

**Comment by xiongguangjie** [comment]
webrtc 在web端不支持aac

**Comment by ZJDATY** [comment]
> WebRTC does not support AAC on the web side.
> 
> > webrtc 在web端不支持aac
> 
> `TRANS_BY_GITHUB_AI_ASSISTANT`

你好，感谢您能回复，那我怎么使用， rtmp里是flv，flv里的支持音频ZLM都不支持，rtsp流里的声音 ZLM也不支持。ffmpeg可以推送的哪种流，ZLM可以播出声音呢，需要转成哪种音频格式最好？

**Comment by xiongguangjie** [comment]
> > WebRTC does not support AAC on the web side.
> > > webrtc 在web端不支持aac
> > 
> > 
> > `TRANS_BY_GITHUB_AI_ASSISTANT`
> 
> 你好，感谢您能回复，那我怎么使用， rtmp里是flv，flv里的支持音频ZLM都不支持，rtsp流里的声音 ZLM也不支持。ffmpeg可以推送的哪种流，ZLM可以播出声音呢，需要转成哪种音频格式最好？

g711 8khz 单通道，这种兼容性最好

**Comment by mtdxc** [comment]
可用转码分支，将aac转opus或g711给rtc播放
