### ISSUE TITLE
[功能请求] 临时转码功能

### ISSUE THREAD

**Issue by YLPH255** [ZLMediaKit/ZLMediaKit#4090]
## 描述该功能的用处，可以提供相关资料描述该功能
该功能具体为：提供一个接口，传入一个流地址和指定转换成的格式和编码，平台接收后返回一个新的流地址并执行拉流转码请求，并对返回去的流地址进行监控，以实现场景下关闭拉流转码任务：1、一直无人观看一段时间（如5分钟）则关闭此拉流转码任务，2、有人观看，观看结束（无人再观看）后立即结束任务。此功能以一个接口实现临时转码功能，无人观看后关闭。目前未发现此功能，如有但本人未发现请指出。

## 该功能是否用于改进项目缺陷，如果是，请描述现有缺陷
否

## 描述你期望实现该功能的方式和最终效果
1、一个接口实现临时转码，无人观看自动关闭
2、接口鉴权
3、多次请求同一个流（此流任务未关闭情况下，无论指定的编码格式是否相同），提供复用能力提高性能

**Comment by xiongguangjie** [comment]
二开或者使用 购买商业版（https://github.com/tsingeye/ZLMediakit-Pro）
