### ISSUE TITLE
[请求帮助]使用api player取流后音视频同步如何处理

### ISSUE THREAD

**Issue by baiyfcu** [ZLMediaKit/ZLMediaKit#419]
目前是按DTS时间按序解码显示和播放声音，已经有音视频同步问题，音频比视频慢几秒，很多播放器处理会按视频同步音频或音频同步视频，通过查资料仅仅通过上述同步机制可能不够，可能还需要RTCP校正，提此ISSUES目的是在动手改代码前能得到个好的建议，Thanks.

**Comment by xiongziliang** [comment]
音频比视频慢几秒是指 你收到的音频时间戳和视频大体相同，但是相同时间戳的音频总是比视频慢几秒到吗？
如果是这个问题，那么视频源的时间戳本身就不够好了

**Comment by baiyfcu** [comment]
从解码顺序来看，音视频是按的时间戳顺序解码的，出来的效果是音频比视频慢几秒，已经排除的媒体源的问题，VLC等其它播放器正常

**Comment by xiongziliang** [comment]
> 从解码顺序来看，音视频是按的时间戳顺序解码的，出来的效果是音频比视频慢几秒，已经排除的媒体源的问题，VLC等其它播放器正常

你用的ZLMediaKit的rtsp播放器吗？

**Comment by xiongziliang** [comment]
你怎么获取流的 什么协议 什么代码

**Comment by baiyfcu** [comment]
> 你怎么获取流的 什么协议 什么代码

使用的ZLMediaKit的api mk_player取裸数据，其中有视频有音频，逻辑在解码显示和播放声音时遇到同步问题

**Comment by xiongziliang** [comment]
rtsp吗？ZLMediaKit的播放器不会操作时间戳，也就是发送端怎么发的就怎么给你

**Comment by baiyfcu** [comment]
是的 RTSP

**Comment by baiyfcu** [comment]
使用的是ZLMediaKit server rtsp代理转发的，时间戳是台大华相机给的

**Comment by xiongziliang** [comment]
rtsp拉流代理吗？

**Comment by baiyfcu** [comment]
> rtsp拉流代理吗？

是的

**Comment by baiyfcu** [comment]
流媒体时间转发的应该是没有问题，就是通过API mk_player取出来的裸数据需要处理好音视频同步，正在寻找其它播放器对于这块的音视频逻辑的处理

**Comment by xia-chu** [comment]
rtsp采用绝对时间戳，相对时间戳需要使用rtptime作为同步基准，目前ZLMediaKit不支持这个，后面可以实现下

**Comment by xia-chu** [comment]
rtp的时间戳已经重新，使用了ntp时间戳，所以这个问题算是修复了？issue先关闭了
