### ISSUE TITLE
怎么截取Rtmp推流的H264/AAC帧数据?

### ISSUE THREAD

**Issue by SuperPowerLF2** [zlmediakit/ZLMediaKit#46]
详细就是OBS推流到服务器时,我直接在服务器收到RTMP流时做处理,有没有既能知道谁推的流又能获取流的完整帧的位置.

**Comment by xiongziliang** [comment]
ZLMediaKit处理Rtmp推流的对象是RtmpSession类，该对象具体处理推流音视频rtmp数据的代码如下：

![image](https://user-images.githubusercontent.com/11495632/61505057-2183df80-aa10-11e9-8262-84d4f84a17e5.png)

上图中`_pPublisherSrc`变量其实是RtmpToRtspMediaSource类型，我们现在看看RtmpToRtspMediaSource对象的onWrite方法：
![image](https://user-images.githubusercontent.com/11495632/61505152-67d93e80-aa10-11e9-868b-e43117c22b84.png)
从上图中我们看到了_rtmpDemuxer变量，该变量是RtmpDemuxer对象，用于解析rtmp包并解复用为H264和AAC。
RtmpToRtspMediaSource派生于RtmpMediaSource对象，除了基类的功能，它还实现了rtmp转rtsp/hls、mp4录制的功能。实现这些功能前都要先解复用成H264和AAC才能实现。所以你可以在RtmpToRtspMediaSource对象中提取到你想要的帧数据，也能知道此处对应的推流来自哪里。

RtmpDemuxer对象是你实现你想要功能的关键，通过`RtmpDemuxer::getTracks`方法你能获取到音视频的Track对象，Track对象可以提取出譬如sps、pps等信息，也能获取到音视频流。

你可以通过这种方式来截取帧数据并处理：

![image](https://user-images.githubusercontent.com/11495632/61505674-3eb9ad80-aa12-11e9-96c2-924c9d1ce7de.png)

**Comment by SuperPowerLF2** [comment]
十分感谢!
