### ISSUE TITLE
怎么把音视频rtmp推流出去？

### ISSUE THREAD

**Issue by astatong** [zlmediakit/ZLMediaKit#47]
现已经实现了基于海康SDK（ubutnu1604、QtCreator5.12）的实时预览，需要将回调函数中获取到的流数据推送到流媒体服务器上。看了test_pusherMp4与DeviceHk，发现两个例子不太一样，也没明白具体的推流功能是怎么实现工作的。

**Comment by xiongziliang** [comment]
ZLMediaKit目前支持rtsp/rtmp推流，这两种推流器分别通过RtspPusher和RtmpPusher对象实现。
为了方便使用，目前已经通过MediaPusher对象对这两者进行了封装。

RtspPusher和RtmpPusher主要实现了推流协议，具体的rtsp和rtmp数据源其实是来自MediaSource类，
对象的类分别是RtspMediaSource和RtmpMediaSource。

RtmpPusher对象在构造是会绑定一个RtmpMediaSource类：
![image](https://user-images.githubusercontent.com/11495632/61504155-f51a9400-aa0c-11e9-9217-a5063bb147a5.png)

所以你要实现rtmp推流，那么你必须先生成一个RtmpMediaSource类（rtsp推流，则需要生成RtspMediaSource），并且在构造RtmpPusher对象时传入RtmpMediaSource类。


开发者应该使用MediaPusher对象（而不是直接使用RtmpPusher或RtspPusher对象），
MediaPuser支持推rtsp、rtmp流，使用更灵活。

MediaPuser的构造函数跟上述的RtmpPusher对象基本一致：
![image](https://user-images.githubusercontent.com/11495632/61504383-b89b6800-aa0d-11e9-9e60-4762b7cccc41.png)

通过上面的叙述，我们已经解释清楚了推流器的构造方法，那么MediaSource类该怎么构造呢？

目前RtmpMediaSource类可以通过RtmpMediaSourceMuxer对象构造生成(生成的RtmpMediaSource会自动注册到全局的map中)，而MultiMediaSourceMuxer对象封装了RtmpMediaSourceMuxer和RtspMediaSourceMuxer的构造方式。
但是MultiMediaSourceMuxer对象接口对于初学者而言比较复杂，
所以初学者可以使用[DevChannel](https://github.com/zlmediakit/ZLMediaKit/blob/master/src/Common/Device.h)类来生成RtmpMediaSource和RtspMediaSource.


你可以先构造DevChannel类，然后往里面输入H264数据和AAC数据，这样它就会自动生成RtmpMediaSource和RtspMediaSource然后自动注册到全局map。

然后通过这个构造函数：
![image](https://user-images.githubusercontent.com/11495632/61504707-eaf99500-aa0e-11e9-966b-42a97b83d42a.png)
构造MediaPusher对象并开始推流即可。


需要注意的是，DevChannel类构造后并不会马上生成RtmpMediaSource并注册，这个注册机制需要你输入完整的sps pps idr之后才能触发。所以你需要确保输入了这些数据之后，才能构建MediaPusher对象，否则MediaSource::find会返回查找失败。

最后你通过MediaPusher::publish接口开始推流即可(你可以推rtsp和rtmp)：
![image](https://user-images.githubusercontent.com/11495632/61504850-652a1980-aa0f-11e9-92ed-66a8fc376869.png)

**Comment by astatong** [comment]
感谢：）
