### ISSUE TITLE
TS未按GOP切片

### ISSUE THREAD

**Issue by yuqingbin** [zlmediakit/ZLMediaKit#49]
设置HLS 切片长度60S，发现有时候TS切片无法播放，之前老版本都是直接判断SPS采取保存的

**Comment by xiongziliang** [comment]
之前ZLMediaKit的TS文件是自己实现的，但是由于那个代码功能比较弱（只支持H264+aac）；所以我移除了旧代码而选择了第三方的库作为ts生成代码。

这个hls生成器，由于考虑到ts输入的通用性，也就是说ts输入时， 不管ts源产生于何种方式，都支持生成hls，这样就导致，无法判断哪里是I帧 哪里不是，因为是按ts包输入的 ，而并不是按帧输入的。


我测试了最新的hls相关代码，在ios上以及FFmpeg 、vlc都能正常播放，不会卡顿。

不知道你说的导致TS切片无法播放是哪种情况?

**Comment by yuqingbin** [comment]
输入源是RTSP拉流，如果拉流十几个小时，会出现切片的ts无法播放，不知道是是不是时间戳问题

**Comment by yuqingbin** [comment]
在 2019-07-19 09:50:34，"夏楚" <notifications@github.com> 写道：


之前ZLMediaKit的TS文件是自己实现的，但是由于那个代码功能比较弱（只支持H264+aac）；所以我移除了旧代码而选择了第三方的库作为ts生成代码。

这个hls生成器，由于考虑到ts输入的通用性，也就是说ts输入时， 不管ts源产生于何种方式，都支持生成hls，这样就导致，无法判断哪里是I帧 哪里不是，因为是按ts包输入的 ，而并不是按帧输入的。

我测试了最新的hls相关代码，在ios上以及FFmpeg 、vlc都能正常播放，不会卡顿。

不知道你说的导致TS切片无法播放是哪种情况?

**Comment by xiongziliang** [comment]
> 输入源是RTSP拉流，如果拉流十几个小时，会出现切片的ts无法播放，不知道是是不是时间戳问题

可能是时间戳回环导致的

**Comment by yuqingbin** [comment]
这个需要怎么修改呢

**Comment by yuqingbin** [comment]
规律是持续拉流13个小时后的ts片无法单独播放，重新断开拉流就可以

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/61697447-db10e680-ad69-11e9-8fda-41a8334dc7e4.png)
ZLMediaKit的回环时间默认13个小时
超过13个小时候，pts dst就变成0了

**Comment by xiongziliang** [comment]
> ![image](https://user-images.githubusercontent.com/11495632/61697447-db10e680-ad69-11e9-8fda-41a8334dc7e4.png)
> ZLMediaKit的回环时间默认13个小时
> 超过13个小时候，pts dst就变成0了

这个13个小时是rtp的最大时间戳决定的
rtp的时间戳默认是4个字节，最大 0xFFFFFFFF;
视频的采样率是90000，换算下来，最多13个小时回环一次(rtmp最多13 * 90 = 1170小时)。

**Comment by xiongziliang** [comment]
这个时间戳回环只会影响时间戳正好从0xFFFFFFFF到0的ts切片 影响很小 我觉得可以忽略了😂

**Comment by yuqingbin** [comment]
看ts片13小时之后的pts，dst都是0，都无法单独播放

**Comment by xiongziliang** [comment]
> 看ts片13小时之后的pts，dst都是0，都无法单独播放

这个时间戳为零无法恢复就很诡异了 ，这个流源自哪里？是否为拉流代理而来？时间戳到底谁生成的？

**Comment by yuqingbin** [comment]
IPC直接拉

**Comment by xiongziliang** [comment]
IPC拉流的时间戳来源于rtp：
![image](https://user-images.githubusercontent.com/11495632/61845760-2ac0f080-aed7-11e9-8111-6f48167b7d16.png)
你看看是不是IPC给的时间戳就一直为0？

**Comment by xiongziliang** [comment]
新版本代码应该修复这个问题了，之前可能是时间戳翻转导致的问题，现在不用担心这个问题了
