### ISSUE TITLE
rtsp做拉流的时候，怎么截取rtsp的关键帧？

### ISSUE THREAD

**Issue by fangrui198585-pione** [zlmediakit/ZLMediaKit#54]
rtsp做拉流的时候，怎么截取rtsp的关键帧？

**Comment by xiongziliang** [comment]
你是要用MediaPlayer接口还是PlayerProxy接口拉流？
这个两者截取关键帧的方式不一样的

**Comment by fangrui198585-pione** [comment]
哪种方式性能高一些

**Comment by xiongziliang** [comment]
PlayerProxy继承于MediaPlayer，它们的功能不同的，
PlayerProxy用于拉流代理，MediaPlayer用于播放器
这个性能无所谓高低

**Comment by fangrui198585-pione** [comment]
我们主要用来做拉流，把流传到服务器上，用哪个比较好。

**Comment by xiongziliang** [comment]
那你只能用PlayerProxy接口

**Comment by xiongziliang** [comment]
你相当于在服务器上做拉流打理对吧？然后生成截图？

**Comment by xiongziliang** [comment]
你可以参考这个issue ：#50
在PlayerProxy里面，获取到videoTrack,然后就能获取到Frame

**Comment by xiongziliang** [comment]
> 你可以参考这个issue ：#50
> 在PlayerProxy里面，获取到videoTrack,然后就能获取到Frame

还有参考这个issue：#46
