### ISSUE TITLE
采用deviceChannel注入的H264，如何确定rtsp或者hls客户端长时间无观看

### ISSUE THREAD

**Issue by cleverdouble** [zlmediakit/ZLMediaKit#55]
我想在客户端无观看时，手动关闭设备的链路，但不知道如何获取到客户端的连接状态，请问这部分接口或者回调在哪里呀

**Comment by xiongziliang** [comment]
你可以参考这个代码 控制无人观看是停止产生流:
![image](https://user-images.githubusercontent.com/11495632/61918920-e3456d80-af85-11e9-9905-ca5960127046.png)

还有参考这个代码，在有人观看是开始产生流：
![image](https://user-images.githubusercontent.com/11495632/61918953-0b34d100-af86-11e9-9d83-66e2e9318e40.png)

**Comment by cleverdouble** [comment]
我这边就想定时获取一下客户端连接的状态，如果flv的话是不是直接走readerCount就可以了？hls就暂时没有办法获取客户端访问状态了吗？

**Comment by xiongziliang** [comment]
是的 目前ZLMediaKit内部的实时内存流是通过MediaSource对象管理的，http-flv和rtmp共用的RtmpMediaSource。你可以根据app、流id 找到相应的RtmpMediaSource，然后根据readerCount方法就能知道总共有多少个播放器。

hls的播放机制是文件式，根http-flv、rtmp、rtsp完全不一样，目前还未实现链接数统计功能

**Comment by cleverdouble** [comment]
好的，你的回答解决了我的疑问，多谢啦～～～
