### ISSUE TITLE
发现了2个问题或者说是不足!

### ISSUE THREAD

**Issue by chenxiaolei** [zlmediakit/ZLMediaKit#56]
1,  HLS 不支持按需播放 
2,  kick_session API 不能关闭 flv播放器

**Comment by xiongziliang** [comment]
HLS目前确实不能按需播放
但是第二个问题应该不会，kick_session应该可以剔除任意的TCPSession

**Comment by xiongziliang** [comment]
现在ZLMediaKit实现了hls的按需拉流了
