### ISSUE TITLE
有计划支持ipv6吗

### ISSUE THREAD

**Issue by FandelXiong** [ZLMediaKit/ZLMediaKit#576]
经过实际的测试和查看相关源码是不支持ipv6的，不知道是否有计划支持ipv6呢

**Comment by xia-chu** [comment]
这个可能要等段时间 因为我最近都没精力大更新

**Comment by alongL** [comment]
**给实现 ipv6的支持提供一点帮助**

将这个文件放到  3rdpart\ZLToolKit\src\Network 目录下，覆盖原文件，可以支持ipv6（同时监听本机Ipv6地址和ipv4地址） 
[sockutil.zip](https://github.com/xia-chu/ZLMediaKit/files/5621903/sockutil.zip)

```
TcpServer::Ptr httpSrv(new TcpServer());
httpSrv->start<HttpSession>(80,"::0");//同时监听本机ipv6和ipv4地址
httpSrv->start<HttpSession>(80); //默认监听“0.0.0.0”, 只监听本机ipv4地址
```

本来想多改改提交个pull request，看了一下，要修改的地方还比较多，有些处理网络接口的地方还不是特别熟悉，暂时就只做少量修改，权当抛砖引玉，给ipv6的支持，提供一点有益的参考。  
这个文件只修改了listen, connect, get_peer_ip, get_peer_port ,  get_local_ip, get_local_port。
新加了一个类DnsCache1， 没有动原先的DnsCache。
新加一个数据结构zl_sockaddr ，用来兼容ipv4地址和ipv6地址。
后续实现ipv6时可以把所有的sockaddr 都换成此数据结构。
```
struct zl_sockaddr {
	unsigned short  family;
	union
	{
		struct sockaddr addr;
		struct sockaddr_in addr_in;
		struct sockaddr_in6 addr_in6;
	};
	size_t	addrlen;
};
```



---------------------------------------------------------------------------
客户端要支持ipv6还有一点，就是url地址，如果使用ipv6地址直接放入URL,要加入[ ]，目前对URL的处理容易把ipv6地址分割的冒号当成端口号分割的冒号，对此需要特殊处理一下。
例如：  http://[fd15:4ba5:5a2b:1008:20c:29ff:fe9c:91c1]:80/live/tv/hls.m3u8






更多参考：
1.ipv4 v6 兼容编程
https://blog.csdn.net/ligt0610/article/details/18667595

2.ipv6编程指引 
http://www.6ip.cu/pdf/long_trans_app_ipv6.pdf

3. ipv4 v6地址存储
https://stackoverflow.com/questions/26531531/efficient-way-to-store-ipv4-ipv6-addresses/63842120#63842120

4.nginx   ipv6相关数据结构定义
https://github.com/nginx/nginx/blob/912fb44e25c6ab2598e36b4544c709b871251b2e/src/core/ngx_inet.h#L44

**Comment by xia-chu** [comment]
大佬 强啊 谢谢了 不过建议你还是提交个pr 我合并再调整下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: along <notifications@github.com&gt;
发送时间: 2020年12月1日 18:56
收件人: xia-chu/ZLMediaKit <ZLMediaKit@noreply.github.com&gt;
抄送: 夏楚 <771730766@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[xia-chu/ZLMediaKit] 有计划支持ipv6吗 (#576)





 
给实现 ipv6的支持提供一点帮助
 
将这个文件放到  3rdpart\ZLToolKit\src\Network 目录下，覆盖原文件，可以支持ipv6（同时监听本机Ipv6地址和ipv4地址）
 sockutil.zip
 TcpServer::Ptr httpSrv(new TcpServer()); httpSrv-&gt;start<HttpSession&gt;(80,"::0");//同时监听本机ipv6和ipv4地址 httpSrv-&gt;start<HttpSession&gt;(80); //默认监听“0.0.0.0”, 只监听本机ipv4地址  
本来想多改改提交个pull request，看了一下，要修改的地方还比较多，有些处理网络接口的地方还不是特别熟悉，暂时就只做少量修改，权当抛砖引玉，给ipv6的支持，提供一点有益的参考。
 这个文件只修改了listen, connect, get_peer_ip, get_peer_port ,  get_local_ip, get_local_port。
 新加了一个类DnsCache1， 没有动原先的DnsCache。
 新加一个数据结构zl_sockaddr ，用来兼容ipv4地址和ipv6地址。
 后续实现ipv6时可以把所有的sockaddr 都换成此数据结构。
 struct zl_sockaddr { unsigned short  family; union { struct sockaddr addr; struct sockaddr_in addr_in; struct sockaddr_in6 addr_in6; }; size_taddrlen; };  
 
客户端要支持ipv6还有一点，就是url地址，如果使用ipv6地址直接放入URL,要加入[ ]，目前对URL的处理容易把ipv6地址分割的冒号当成端口号分割的冒号，对此需要特殊处理一下。
 例如：  http://[fd15:4ba5:5a2b:1008:20c:29ff:fe9c:91c1]:80/live/tv/hls.m3u8
 
更多参考：
 1.ipv4 v6 兼容编程
 https://blog.csdn.net/ligt0610/article/details/18667595
 
2.ipv6编程指引
 http://www.6ip.cu/pdf/long_trans_app_ipv6.pdf
  
ipv4 v6地址存储
 https://stackoverflow.com/questions/26531531/efficient-way-to-store-ipv4-ipv6-addresses/63842120#63842120 
 
4.nginx   ipv6相关数据结构定义
 https://github.com/nginx/nginx/blob/912fb44e25c6ab2598e36b4544c709b871251b2e/src/core/ngx_inet.h#L44

**Comment by alongL** [comment]
不是大佬，只不过前段时间做过一些c++支持ipv6的东西，有一点经验。

**Comment by alongL** [comment]
pr提交了 https://github.com/xia-chu/ZLToolKit/pull/44
感觉对于监听::0是实现了，但是很不完全。

**Comment by xia-chu** [comment]
已经全面支持ipv6
