### ISSUE TITLE
关于帧截取问题

### ISSUE THREAD

**Issue by fangrui198585-pione** [zlmediakit/ZLMediaKit#58]
帧截取要截取多少帧，有没有可供参考的？

**Comment by xiongziliang** [comment]
你可以参考这些issue：#54 #50 #46
如果你还是不知道怎么截取关键帧
那么你可以阐明你想在什么地方截取关键帧，我再回答你
你的问题不是很明了

**Comment by fangrui123456** [comment]
我想问的是在那个具体函数里面截取ｒｔｓｐ拉流的关键帧图片？
在ｐｌａｙｐｒｏｘｙ?还是rtsptortmpmediasource代码里面的函数？

**Comment by xiongziliang** [comment]
> 我想问的是在那个具体函数里面截取ｒｔｓｐ拉流的关键帧图片？
> 在ｐｌａｙｐｒｏｘｙ?还是rtsptortmpmediasource代码里面的函数？

![image](https://user-images.githubusercontent.com/11495632/62766603-6823a180-bac5-11e9-839b-41a3539f5b06.png)

**Comment by fangrui123456** [comment]
这里可以直接取到帧数据，然后解码ＹＵＶ到图片数据？

**Comment by xiongziliang** [comment]
是的，这里能取到视频帧，也能解码成yuv ，接下来怎么解码的流程，你可以参考test_player范例

**Comment by fangrui123456** [comment]
好的
