### ISSUE TITLE
关于HLS和FLV的延迟优化问题

### ISSUE THREAD

**Issue by cleverdouble** [zlmediakit/ZLMediaKit#63]
ZLMediaKit支持的流媒体播放方式非常全面，很优秀。在采用devChannel方式注入H264流播放时，flv延迟6s以上，hls延迟10s以上，这两个地方是否能够在代码中进行优化，或者如何修改相关参数来优化这两个的延迟时间呢？

**Comment by xiongziliang** [comment]
flv的延时主要是播放器端的 服务器是无缓存设计 
hls延时基本无解 协议使然

**Comment by cleverdouble** [comment]
> flv的延时主要是播放器端的 服务器是无缓存设计
> hls延时基本无解 协议使然

我是使用vlc播放的，默认cache 1000ms. 采用rtsp播放时，延时大概在2s内，采用rtmp和flv播放，延时大概是6s，这个6s是正常的吗？我看网上说flv延迟大概在1-2秒内。我这为什么是6s这么长的时间

**Comment by xiongziliang** [comment]
你可以使用我提供的test_player测试 那个才能反映真实的延时

**Comment by cleverdouble** [comment]
我通过抓取终端与播放端的实时视频码流，分析到的结果与你的描述一致，flv服务端无缓存设计，延迟大概在2s以内。只是vlc播放时延迟大概有6s以上。这个应该是vlc播放缓存的问题，采用页面播放应该没这个问题。谢啦～
