### ISSUE TITLE
这个服务器部署在公网如何设置参数能达到最优的效果

### ISSUE THREAD

**Issue by fedorxe** [zlmediakit/ZLMediaKit#64]
做拉流代理的时候，如何设置参数？TCP拉还是UDP拉？mtu如何设置？有啥优点？

**Comment by xiongziliang** [comment]
rtsp 拉流 ，ZLMediaKit目前支持3种方式，分别是tcp/udp/组播。
tcp拉流不额外占用端口号，而且不会丢包，所以这种理论上是最稳定的。
但是有些设备tcp方式拉流，其rtp大小远远大于mtu，这样导致在rtsp直接转发模式下，不能通过UDP方式转发。

假如你的设备rtsp编码格式是H264/H265/AAC，那么你可以直接直接拉流或非直接拉流。
假如你的设备rtp在tcp拉流方式下大于mtu，那么你可以直接udp方式拉流。
假如你的设备rtp在tcp拉流方式下小于于mtu，那么你可以直接tcp/udp方式拉流。

如果你不清楚你的设备状况，你可以选择直接udp方式拉流，这样所有设备都兼容。

**Comment by fedorxe** [comment]
拉流不就是直接拉流么？ 非直接拉流是啥意思？
设备状况怎么看，登录设备的设置页面的哪个地方可以查？  编码格式我知道怎么看， 设备rtp是否大于mtu这个怎么看？  mtu我知道程序的配置文件中有，设备的rtp怎么看？

**Comment by xiongziliang** [comment]
- 1、拉流代理目前分为直接和非直接方式，所谓直接就是拉流后，不对sdp、rtp解析和处理，直接代理。间接指的是，对sdp和rtp解析和解码，转换成H264 Frame后再重新生成sdp和rtp。
- 2、设备状况当然要在你的设备设置页面看啦，RTP是否大于MTU这个要你自己实测，你用ZLMediaKit拉流，如果是udp拉流，那么rtp肯定小于MTU，如果tcp拉流，那么有些设备rtp会大于mtu，ZLMediaKit也是支持的。如果是tcp拉流直接代理，如果rtp大于mtu，那么就不能直接udp方式转发出去，所以这个时候，如果播放器使用udp方式播放ZLMediaKit直接代理的这个流，就会播放失败

**Comment by xiongziliang** [comment]
直接代理的缺陷就是 ，在tcp直接拉流代理的情况下，如果设备发送的rtp大于mtu，并且播放器通过udp方式播放ZLMediaKit直接代理的流就会失败。

也就是满足这三个条件，才会出现异常：
- 1、ZLMediaKit直接拉流代理
- 2、ZLMediaKit tcp方式拉流
- 3、播放器用udp方式访问ZLMediaKit代理的这个流

上述只要一个条件不满足，都能正常播放
