### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by thaibienbac** [zlmediakit/ZLMediaKit#65]
Hi,
I am using Cmake to create VS2017 solution on windows, but some lib can not found.
![cmake](https://user-images.githubusercontent.com/13082850/62910840-5cc5c400-bdac-11e9-93d3-0c0f22c0f8e1.png)
When build solution, found this error:
![build solution](https://user-images.githubusercontent.com/13082850/62911275-fd68b380-bdad-11e9-8975-360fdf18a691.png)

Please help me solve this problem.

**Comment by xiongziliang** [comment]
Hi , friend ,it do not matter when some lib can not be found(they are all optional).
The second problem,you can change the code like this:
```cpp
if(!with_nalu_size){
		//不带4个字节的nalu_size,那么我们自己生成
		nalu_size_buf[0] = (uint8_t)((bytes >> 24) & 0xFF);
		nalu_size_buf[1] = (uint8_t)((bytes >> 16) & 0xFF);
		nalu_size_buf[2] = (uint8_t)((bytes >> 8) & 0xFF);
		nalu_size_buf[3] = (uint8_t)((bytes >> 0) & 0xFF);

		nalu_size_ptr = nalu_size_buf;
		data_ptr = data_in;
		bytes += 4;
	}else{
		nalu_size_ptr = data_in;
                 //change the code like this:
		data_ptr = (void *)data_in + 4;
                 //or  like this:
                 //data_ptr = (void *)((char *)data_in + 4);
	}
```

**Comment by xiongziliang** [comment]
And if you are Chinese ,you can speak Chinese

**Comment by thaibienbac** [comment]
Hi,

Thanks for your support,
Now i can build project successfull on Windows but when run test_server project, getting following error:
![error](https://user-images.githubusercontent.com/13082850/62916446-b20cd000-bdc2-11e9-9c99-af6c6bc4d47f.jpg)

**Comment by xiongziliang** [comment]
This seems to be caused by the failure of listening on TCP port.
You can change default port of http/https/rtsp/rtsps server by modify `test_server.exe.ini` file.

**Comment by thaibienbac** [comment]
Thanks,
By change SSL port, now it's work fine except rtsp server.
using VLC to play BigBuckBunny hls stream, rtmp stream, flv stream: very good
but rtsp stream always disconnect after few seconds.
can i setup rtsp server parameter for fluenly ?

**Comment by xiongziliang** [comment]
You can play rtsp stream by using  `rtp over tcp`,like this:
```
ffplay rtsp://xxxxxx -rtsp_transport tcp
```
