### ISSUE TITLE
推流中断恢复

### ISSUE THREAD

**Issue by xixihao123** [zlmediakit/ZLMediaKit#67]
你好，请问我推流端先断开再继续推流，播放器就没法继续播放了啊，用nginx就可以继续推流。

**Comment by xiongziliang** [comment]
是的 在推流端断开后 ZLMediaKit会强制关闭播放端

**Comment by xixihao123** [comment]
我想把它改成客户端不断开网络，如果有推流能继续接收包。需要改哪个地方啊。

**Comment by xiongziliang** [comment]
这个改动就很大了 并不建议这么做
