### ISSUE TITLE
关于 openRtpServer 的建议 

### ISSUE THREAD

**Issue by mis-czx** [ZLMediaKit/ZLMediaKit#671]
openRtpServer 是否可增加范围值 以方便特殊需求下的端口映射或者防火墙的端口设置 从控制端还需要遍历比较耗时

**Comment by xia-chu** [comment]
Linux系统本身就可以设置端口取值范围的
如果指定端口范围，那么就不能随机端口了，而是要程序自己管理一个端口池，
获取端口时，从程序里面获取一个程序认为的空闲端口，但是这个端口可能被其他程序占用了，
那么就要重试下一个端口，直到成功为止。这样做对程序本身来讲并没有带来什么好处，还增加了复杂性，而且还可能存在获取端口失败，或者不能物尽其用的问题。

**Comment by xia-chu** [comment]
这个特性 后面有时间加一下吧 也没什么难度 就是挺鸡肋的
本来udp端口 你指定范围为30000~65553就行，Linux默认差不多是这个范围

**Comment by mis-czx** [comment]
感谢

**Comment by chatop2020** [comment]
可以采用AKStream,AKStream已经维护了一个端口范围，在openRtpServer前AKStream会先从自己内部的端口池中获取一个可用端口，再向ZLMediaKit固定申请此端口，因此在AKStream的治理下，可以方便的管理udp端口段

**Comment by programcj** [comment]
@chatop2020 是否可以增加一个 对 OpenRtpServer 的超时的hook  ,这边有时候发送视频流超过延时时间了,或者 没有发送视频过来, 对 open的调用者 并不知道

**Comment by xia-chu** [comment]
已经支持随机端口限定端口范围功能，配置文件`port_range`选项
