### ISSUE TITLE
rtmp会话流程

### ISSUE THREAD

**Issue by xixihao123** [zlmediakit/ZLMediaKit#70]
请问这个rtmp服务器有没有流程图啊，推上来的rtmp流在哪个类中转发到其他rtmp播放器啊

**Comment by xiongziliang** [comment]
ZLMediaKit里面的tcp服务器会话类都派生于TcpSession类,rtmp的会话类对应为RtmpSession。
推流上来的rtmp数据会放在RtmpMediaSource里面，RtmpMediaSource的成员变量RingBuffer完成数据的分发。

具体还是看代码，图、文档什么的不健全
