### ISSUE TITLE
vs2017 编译问题 没有libssl32MD 是不是要自己准备一个ssl32md.lib?

### ISSUE THREAD

**Issue by gchihiha** [zlmediakit/ZLMediaKit#72]
![image](https://user-images.githubusercontent.com/25894997/63738791-83602080-c8bd-11e9-97e1-a0a4f229f209.png)

**Comment by xiongziliang** [comment]
不是 这个应该是你安装了64位的opensll 但是你编译的确实32位的程序

**Comment by gchihiha** [comment]
明白了 请等我好消息

**Comment by xiongziliang** [comment]
好的 :)
