### ISSUE TITLE
Is it support GB28181 tcp active

### ISSUE THREAD

**Issue by bobolovejingjing** [ZLMediaKit/ZLMediaKit#746]
ZLMediaKit 支持GB28181 TCP主动模式么？ TCP主动模式需要ZLMediaKit主动发起会话。

**Comment by xia-chu** [comment]
主动被动模式 是对sip服务器而言的 zlm只负责流媒体部分 所有对zlm来说 主动被动模式没区别

**Comment by xia-chu** [comment]
觉得本项目可以 给个star呗

**Comment by bobolovejingjing** [comment]
没有这样的一个接口，主动发送tcp握手信令




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月1日(星期一) 上午10:27
收件人:&nbsp;"xia-chu/ZLMediaKit"<ZLMediaKit@noreply.github.com&gt;;
抄送:&nbsp;"谭李波"<1125092116@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] Is it support GB28181 tcp active (#746)





 
主动被动模式 是对sip服务器而言的 zlm只负责流媒体部分 所有对zlm来说 主动被动模式没区别

**Comment by bobolovejingjing** [comment]
sip信令支持tcp主动，但是zlm不能向下级平台流媒体服务器发起建链请求

**Comment by xia-chu** [comment]
不能 目前确实没这个功能
#749

**Comment by bobolovejingjing** [comment]
那大佬啥时候可以把这块的东西补上

**Comment by xia-chu** [comment]
你是要支持主动拉流客户端 还是被动拉流服务器
现在zlm支持主动推流客户端和被动推流服务器

**Comment by bobolovejingjing** [comment]
主动拉流客户端




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xia-chu/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xia-chu/ZLMediaKit] Is it support GB28181 tcp active (#746)





 
你是要支持主动拉流客户端 还是被动拉流服务器
 现在zlm支持主动推流客户端和被动推流服务器

**Comment by tonyxia2016** [comment]
也需要这个GB28181 TCP主动模式，+1

**Comment by songwenhai** [comment]
完整GB28181平台需要TCP主动模式，希望尽快支持，感谢

**Comment by emily2ly** [comment]
完整GB28181平台需要TCP主动模式，希望尽快支持，感谢

**Comment by yxw13141618** [comment]
刚好也需要这个TCP主动模式  +1，希望大佬能够抽时间增加支持。感谢！

**Comment by chatop2020** [comment]
TCP主动模式就是由摄像头开一个rtp端口，zlmediakit去连接这个端口并获取rtp流，这个功能zlmediakit现在确实还没有，也希望大佬能看看是否可以实现，这样gb28181就会比较完整了。

**Comment by xia-chu** [comment]
这个功能优先级不高 我工作上也没这个工作 最近也没太多时间花这里 先关闭了 如果有热心人能提交pr 那么当然最好 开源项目共建共享 希望大家一起完善。

**Comment by wanghuahui** [comment]
的
