### ISSUE TITLE
addStreamProxy API will be error if source stream url contains "&"

### ISSUE THREAD

**Issue by thaibienbac** [zlmediakit/ZLMediaKit#76]
Hi,

My URL is "rtsp://admin:admin12345@192.168.100.231/cam/realmonitor?channel=1&subtype=1"
Log:

# args:

app : proxy

enable_rtmp : 1

enable_rtsp : 1

stream : cam2

subtype : 1

url : rtsp://admin:admin12345@192.168.100.231/cam/realmonitor?channel=1

vhost : __defaultVhost__

# response:

{
   "code" : -1,
   "msg" : "DESCRIBE:404 Not Found"
}

**Comment by xiongziliang** [comment]
You can urlencode you rtsp url or send request by json

**Comment by xiongziliang** [comment]
curl -X POST ：http://127.0.0.1/index/api/addStreamProxy -H 'Content-Type: application/json'  -d '{"url": "rtsp://admin:admin12345@192.168.100.231/cam/realmonitor?channel=1", "enable_rtmp": "1"....}'

**Comment by thaibienbac** [comment]
Thanks.
