### ISSUE TITLE
Websocket flv 

### ISSUE THREAD

**Issue by nokiovo79** [zlmediakit/ZLMediaKit#78]
Hi Friend,
how to use the websocket flv. What is the port and an example?
Thank you very much

**Comment by xiongziliang** [comment]
- You can  set the rtmp url to `rtmp://127.0.0.1/live/obs` and then push it to `ZLMediaKit` by `obs`.
- Then you can play it with vlc and the url is `rtmp://127.0.0.1/live/obs`.
- You can also play a rtmp live stream by websocket-flv ,the url is `ws://127.0.0.1/live/obs.flv`.
- You may need a websocket flv player, such as [flv.js](https://github.com/bilibili/flv.js).

**Comment by xiongziliang** [comment]
websocket-flv  server shared the same port as http server

**Comment by nokiovo79** [comment]
I tried but it's really slow.... there are settings to do on flv player?

**Comment by nokiovo79** [comment]
Not realtime ...

**Comment by xiongziliang** [comment]
How high is the delay of websocket-flv live stream?
The delay of my test is about the same as that of rtmp.

**Comment by nokiovo79** [comment]
But no Realtime. 5/10 second respect rtsp

**Comment by xiongziliang** [comment]
No , most of the latency occur on the player,the server forwarding latency can be ignored
