### ISSUE TITLE
android:undefined reference to '__android_log_print'

### ISSUE THREAD

**Issue by weller0** [zlmediakit/ZLMediaKit#79]
**### 环境:linux（deepin）
cmake:3.9.5
gcc:6.3.0
ndk:android-ndk-r14b**
编译android库文件出错了
1、ZLMediaKit/src/Http/HttpClient.cpp:183:59: error: 'INT64_MAX' was not declared in this scope
已经解决
INT64_MAX --> std::numeric_limits<std::int64_t>::max()
2\
../libzltoolkit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): **### error: undefined reference to '__android_log_print'**
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_pusherMp4.dir/build.make:99: recipe for target 'tests/test_pusherMp4' failed
make[2]: *** [tests/test_pusherMp4] Error 1
CMakeFiles/Makefile2:286: recipe for target 'tests/CMakeFiles/test_pusherMp4.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_pusherMp4.dir/all] Error 2
../libzltoolkit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_benchmark.dir/build.make:99: recipe for target 'tests/test_benchmark' failed
make[2]: *** [tests/test_benchmark] Error 1
CMakeFiles/Makefile2:368: recipe for target 'tests/CMakeFiles/test_benchmark.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_benchmark.dir/all] Error 2
[ 94%] Linking CXX executable test_pusher
../libzltoolkit.a(logger.cpp.o):logger.cpp:function toolkit::ConsoleChannel::write(toolkit::Logger const&, std::shared_ptr<toolkit::LogContext> const&): error: undefined reference to '__android_log_print'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_pusher.dir/build.make:99: recipe for target 'tests/test_pusher' failed
make[2]: *** [tests/test_pusher] Error 1
CMakeFiles/Makefile2:327: recipe for target 'tests/CMakeFiles/test_pusher.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_pusher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xiongziliang** [comment]
现在不建议使用脚本编译了，现在建议直接使用Android Studio编译，文件夹Android就是Android Studio工程。
