### ISSUE TITLE
Static Library .a in debug mode produce signal

### ISSUE THREAD

**Issue by nokiovo79** [zlmediakit/ZLMediaKit#81]
Hi friend,
I make project on my SO Linux. When produce the static Library (Debug) and use there, i have a problem when start and stop a streaming. I riceve the signal from ZLMediaKit and i haven’t idea.
Same project is ok when use your static Library in Release.
Can you help me?

**Comment by xiongziliang** [comment]
Can you copy and paste warnings or errors by screenshots?

**Comment by nokiovo79** [comment]
the error changes but it is certainly due to an exception or signal that is produced by the server. are there signals that are triggered by the server when a feed no longer transmits?

**Comment by nokiovo79** [comment]
strangely with the libraries you have produced does not happen

**Comment by xiongziliang** [comment]
How do you built the library ?

**Comment by nokiovo79** [comment]
Build for Linux script

**Comment by xiongziliang** [comment]
And how do you use the  static library in your project ,can you show me the setting of your project?
It is recommended that use the source of ZLMediaKit direct.
