### ISSUE TITLE
关闭支持HLS的开关

### ISSUE THREAD

**Issue by sunhui2013** [zlmediakit/ZLMediaKit#82]
HLS的切片会不会影响流媒体服务器的性能，有没有开关关闭HLS功能，HLS的切片是不可以放到内存中？

**Comment by xiongziliang** [comment]
HLS切片最大的问题是文件IO会比较耗时 ，除非是直播源太多，否则基本不影响性能。

**Comment by xiongziliang** [comment]
ZLMediaKit已经支持通过hook事件控制是否打开hls了

**Comment by alongL** [comment]
关于hls生成后放到内存中， 可以改配置  hls.filePath = /dev/shm  ，这对于加快IO有作用。
/dev/shm是内存文件系统
