### ISSUE TITLE
Change CMAKE_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by lucaszanella** [zlmediakit/ZLMediaKit#83]
Hi. In your CMakeLists.txt you use `CMAKE_SOURCE_DIR`. This makes me unable to add ZLMediaKit as an subdirectory so my project's cmake can build your project's cmake, because `CMAKE_SOURCE_DIR` inside your project maps to my project's `CMAKE_SOURCE_DIR`.

You should use `CMAKE_CURRENT_SOURCE_DIR`, I did and it worked

**Comment by xiongziliang** [comment]
Thank you very much for you feedback, i will change it later!
