### ISSUE TITLE
Add option to disable OPENSSL and other things

### ISSUE THREAD

**Issue by lucaszanella** [zlmediakit/ZLMediaKit#84]
I can't disable options like OPENSSL from my project's CMakeLists.txt, because your CMakeLists.txt file sets it again. Shouldn't it be better to change 

`set(ENABLE_OPENSSL true)`

to

```
if (NOT ENABLE_OPENSSL)
set(ENABLE_OPENSSL true)
endif()
```

?

Since your project uses openssl1.1, and ubuntu bionic does not have `libssl1.1-dev` (only `libssl1.1`), I wanted to get ahead with developing my project without having to compile `libss1.1 `for now. I'll in the future, but just to get things working fast I did this.

**Comment by xiongziliang** [comment]
I code have adapted for Openssl of multiple versions :
![image](https://user-images.githubusercontent.com/11495632/64931567-dd745600-d86b-11e9-9fbd-9ed335bd8f1d.png)

But i am sorry i don't know what exact version have supported.

The option you pasted of ENABLE_OPENSSL, i want to change it to `cmake options` which is better and flexible
