### ISSUE TITLE
[BUG]hook api问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#850]
其实这个问题应该是出在httpclient上面.
当hook执行调用远程服务器url的时候, 如果远程服务器返回的json结果没有content-lenght或者不时chunked的那么就直接忽略内容了.实际上有些服务器端返回json的时候的确没有返回content-length,开启gzip的时候甚至也没有chunked.
结果就直接_strRecvBody.clear();, 这样是否有点粗暴?

`

    size_t HttpRequester::onResponseHeader(const string &status,const HttpHeader &headers) {
        _strRecvBody.clear();
        //无Content-Length字段时默认后面没有content
        return 0;
    }

`

**Comment by xia-chu** [comment]
你看zlm代码，如果没content-length也支持的：
![图片](https://user-images.githubusercontent.com/11495632/116644367-bf5a5b80-a9a5-11eb-9ed8-dc79e1eb9932.png)

**Comment by alexliyu7352** [comment]
我这边测试的时候,的确如果没有返回content-length, 直接丢弃返回数据的
 stringstream ss(strRecvBody);
ss >> result;

这里直接报错, 因为是空的.
你那段代码, 不会执行到那边.

您可以尝试下, 的确有这个问题, 后来我给服务器加上了返回content-length才可以.

**Comment by zhang2349** [comment]
+1 
没有content-length是直接报错的

**Comment by xia-chu** [comment]
更新 试试

**Comment by xia-chu** [comment]
先关闭了
