### ISSUE TITLE
[BUG] tests/test_pusherMp4 cannot run

### ISSUE THREAD

**Issue by bichkhe** [ZLMediaKit/ZLMediaKit#853]
I run test_pusherMp4 with setuping a file in my computer and a link rtsp public
`int main(int argc,char *argv[]){
    return domain("/home/stallman/Documents/sample-mp4-file.mp4","rtsp://127.0.0.1/live/stream122");
}
`
I undestand that the first param is a file mp4 to read, the second param is rtsp stream is published from this file

I got a log

`2021-05-05 07:54:07.657 I test_pusherMp4[6971-140475310958336] MediaSource.cpp:403 emitEvent | 媒体注册:rtmp __defaultVhost__ live stream
2021-05-05 07:54:07.657 I test_pusherMp4[6971-140475310958336] MediaSource.cpp:403 emitEvent | 媒体注册:rtsp __defaultVhost__ live stream
2021-05-05 07:54:07.658 I test_pusherMp4[6971-140475310958336] MediaSource.cpp:403 emitEvent | 媒体注册:ts __defaultVhost__ live stream
2021-05-05 07:54:07.666 D test_pusherMp4[6971-140475310958336] RtspPusher.cpp:26 ~RtspPusher | 
2021-05-05 07:54:07.666 D test_pusherMp4[6971-140475310958336] RtspPusher.cpp:76 publish | rtsp://127.0.0.1/live/stream122 null null 1
**`2021-05-05 07:54:07.666 W test_pusherMp4[6971-140475310958336] test_pusherMp4.cpp:71 operator() | Publish fail:3 connection refused`**`

Process finished with exit code 1

Connection refused:  It ' seem it connect to rtsp://127.0.0.1/live/stream122 I need publish pushUrl not connect to it. Why?

Whether I undestand wrong a pusher

Would you mind please give me an example  with video on demand feature that get a list of files and publish theses to a rtsp/rtmp stream?

Thanks

**Comment by bichkhe** [comment]
![image](https://user-images.githubusercontent.com/3736457/117170510-4a977f00-adf4-11eb-81df-f59280461ae3.png)

**Comment by xia-chu** [comment]
you can startup `MediaServer`, and then startup `test_pusherMp4` to push rtsp to `MediaServer`.

**Comment by bichkhe** [comment]
I just want to create a publish url from a list of mp4 files without any player play it. As you said, whether  can I startup test_pusherMp4 without run MediaServer? Thanks xia-chu

**Comment by xia-chu** [comment]
test_pusherMp4 is a test program to load mp4 files, and then push it to rtsp or rtmp mediaserver.
I don't understand  what you said `I just want to create a publish url from a list of mp4 files without any player play it`

**Comment by xia-chu** [comment]
I'm sorry to reply to you just now. A lot of things have happened recently
