### ISSUE TITLE
[技术咨询]使用ehome协议拉起两个摄像头的流session id不匹配

### ISSUE THREAD

**Issue by GiantClam** [ZLMediaKit/ZLMediaKit#869]
**咨询的功能模块**
使用zlmediakit接入ehome协议的海康nvr，信令使用FreeEHome

**咨询的具体内容和问题**
当海康nvr接入两个摄像头时，通道1 session id与stream匹配，通道2不匹配，感觉是通道2的session id 进行大小端转换，对低位2个字节固定替换为4635就可以获得stream id，是否多通道情况下处理有区别？

通道1
![image](https://user-images.githubusercontent.com/1756007/118518398-ab1aaa80-b76a-11eb-995d-7dbb7dc4c2c1.png)

通道2
![image](https://user-images.githubusercontent.com/1756007/118518455-b8d03000-b76a-11eb-8629-8a523d1c7167.png)

**Comment by xia-chu** [comment]
有些摄像头是没法控制ssrc的，sip下发ssrc，设备不一定会照做

**Comment by xia-chu** [comment]
还有 zlm打印的ssrc是16进制，freeehome可能是10进制的 主要转换下

**Comment by GiantClam** [comment]
> 有些摄像头是没法控制ssrc的，sip下发ssrc，设备不一定会照做

更换任何品牌摄像头到第一通道都是正常，已经做过摄像头调换

**Comment by GiantClam** [comment]
> 还有 zlm打印的ssrc是16进制，freeehome可能是10进制的 主要转换下

已经做了转换，就是上面这种情况，并且用最新的代码，使用ehome协议，海康nvr接多个摄像头，非第一通道会花屏，我在rtpsplitter中做了打印，发现第一个通道使用isehome是true，但是其他通道都是false，不知道这两个问题是否有关系

**Comment by xia-chu** [comment]
> 并且用最新的代码，使用ehome协议，海康nvr接多个

你强制把isehome改成1试试？

**Comment by yanc1808** [comment]
遇到了相同的问题，只有通道1的session转16进制可以和stream匹配上，其他的通道都不行！！！

**Comment by GiantClam** [comment]
> > 并且用最新的代码，使用ehome协议，海康nvr接多个
> 
> 你强制把isehome改成1试试？

是可以的，或者直接去掉is_ehome这个bool值的使用，可以解决花屏的问题，但是stream id不匹配的问题还需要看看

**Comment by baiyfcu** [comment]
> > > 并且用最新的代码，使用ehome协议，海康nvr接多个
> > 
> > 
> > 你强制把isehome改成1试试？
> 
> 是可以的，或者直接去掉is_ehome这个bool值的使用，可以解决花屏的问题，但是stream id不匹配的问题还需要看看

调试确认下是不是 is_ehome这个判断是不是EHOME流不准确，代码里比对的是前4个字节，有些海康设备会有出入

**Comment by GiantClam** [comment]
> > > > 并且用最新的代码，使用ehome协议，海康nvr接多个
> > > 
> > > 
> > > 你强制把isehome改成1试试？
> > 
> > 
> > 是可以的，或者直接去掉is_ehome这个bool值的使用，可以解决花屏的问题，但是stream id不匹配的问题还需要看看
> 
> 调试确认下是不是 is_ehome这个判断是不是EHOME流不准确，代码里比对的是前4个字节，有些海康设备会有出入

在nvr下，非通道1的情况下没有"\x01\x00\x01\x00"，导致判断出错，已经试过两台新购的nvr，都是同样的情况

**Comment by GiantClam** [comment]
在nvr下，非通道1，stream id不一致的问题也找到了，如下图，第一个包收到长度为256的包，第7~第10字节是ssrc，因为包头没有特征，代码里判断走2字节rtp的处理，导致getssrc中跳8字节获取ssrc偏移了2个字节，之后的包都是标准的12字节rtp头，不知道是不是海康设备特殊包，现在我的处理是，跳过第一个包

<img width="571" alt="65AA7903-483C-42F4-A6C7-F8C4A586FB87" src="https://user-images.githubusercontent.com/1756007/119537128-51466000-bdbc-11eb-9832-2619975d0a46.png">

**Comment by xia-chu** [comment]
好 希望修改后能提个pr 谢谢！

**Comment by GiantClam** [comment]
![image](https://user-images.githubusercontent.com/1756007/120615880-4f029680-c48b-11eb-8f93-21e98a24c983.png)

我修改了这个地方，前两个字节是长度，第三个字节是通道号，第四个字节不确定有时是0有时是1，所以导致1通道以上的视频流被判断为不是ehome，ssrc获取不对，多测试测试，确认没问题，再提pr

**Comment by xia-chu** [comment]
谢谢

**Comment by xia-chu** [comment]
此issue没什么结果，zlm也没收到相关的pr，所以这个问题大概是无法修复。
开源软件需要共建共享一起来完善，我本身重未使用EHOME推流，工作更是风牛马不相及，所以这个问题我没有测试环境去复现和修复。
