### ISSUE TITLE
Pass copy of shared_ptr instead of reference in videoTrack callback

### ISSUE THREAD

**Issue by lucaszanella** [zlmediakit/ZLMediaKit#88]
`videoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([this](const Frame::Ptr &frame) {`

isn't passing a reference to a shared_ptr dangerous? I get the risk of having a reference to nothing once it's gone. Shouldn't you pass a copy of a shared_ptr?

**Comment by xiongziliang** [comment]
Sorry, I have searched all of the code , but i can not find any code like that you pasted.
![image](https://user-images.githubusercontent.com/11495632/64930584-bd8d6400-d864-11e9-949f-b3fabbd35fc9.png)

Where are you find the code below?
`videoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([this](const Frame::Ptr &frame) {`

**Comment by lucaszanella** [comment]
It's in the readme, I just added the `this` keyword. It's as well on your print, without the this

`videoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([](const Frame::Ptr &frame) {`

Anyways, these functions in the print screen take a reference to a shared_ptr as argument, which is not good I guess

**Comment by xiongziliang** [comment]
Lambda expression is recommend to capture argument as weak_ptr, and i always did it.

The code is readme:
`videoTrack->addDelegate(std::make_shared<FrameWriterInterfaceHelper>([](const Frame::Ptr &frame) {`
just showed it how to get frames from videoTrack ,and it will not capture any reference in lambda expression, and it will not capture `this` also.

The developer should capture reference as shared_ptr or weak_ptr they need in the principle of 
`avoid circular references` and `objects still exist in asynchronous callbacks`.
