### ISSUE TITLE
[技术咨询]部署到阿里云服务器

### ISSUE THREAD

**Issue by shenbaiyu** [ZLMediaKit/ZLMediaKit#881]
请问部署到阿里云服务器，拉流报错是什么问题呢
报这个错误：
liveplayer-lib.min.js:1 WebSocket connection to 'ws://0.0.0.0/rtp/06148719.flv?st=1621504013413' failed: Error during WebSocket handshake: Unexpected response code: 404**

部署到云端，需要注意什么呢

**Comment by xia-chu** [comment]
应该是没推流到zlm成功 注意安全组和防火墙设置
