### ISSUE TITLE
[技术咨询]Docker部署能否指定ssl证书？

### ISSUE THREAD

**Issue by chenfuxu920** [ZLMediaKit/ZLMediaKit#882]
**咨询的功能模块**
- ssl

**咨询的具体内容和问题**
- 我在config.ini和docker hub镜像页中都没有找到ssl证书配置的选项，根据wiki所说，是在启动的时候通过 -s 选项指定证书，那docker部署时应该怎么指定证书呢？通过编写新的markfile，修改 ENTRYPOINT 吗？
- 另外想请问下，此项目中支持ssl双向认证配置吗？

**Comment by xia-chu** [comment]
ssl双向认证配置这个一般很少见 而且应用常见比较特别 zlm的ssl一般用于https wss rtsps rtmps等场景 都几乎不存在严重严重客户端证书的需求 您说的是什么场景呢？

目前加载证书只能通过启动参数-s 指定 ，有其他需求吗？

**Comment by DIEGOMACAPA** [comment]
😍😍😍😍

**Comment by DIEGOMACAPA** [comment]
Legal

**Comment by chenfuxu920** [comment]
好的，明白了，谢谢，那我试试通过 ENTRYPOINT 指定启动参数吧
