### ISSUE TITLE
[技术咨询]关于设置关于切片文件prefix的参数

### ISSUE THREAD

**Issue by NangenX** [ZLMediaKit/ZLMediaKit#885]
**咨询的功能模块**
HLS 分发

**咨询的具体内容和问题**
这边在关于HLS配置项目中没有看到可以设置关于切片文件prefix的参数，这边想请教下是否支持prefix的设置。

**Comment by xia-chu** [comment]
不需要单独设置的 ts的prefix可以相对hls m3u8 url而言。
比如说你的m3u8 url是 http://domain.com/live/test/hls.m3u8
如果在m3u8文件中ts的url是 1.ts，那么http下载地址就是http://domain.com/live/test/1.ts
