### ISSUE TITLE
[技术咨询]websocket-rtsp必现要客户端拉流和设备侧推流都是websocket传输，客户端才可以看到websocket-rtsp的实况吗

### ISSUE THREAD

**Issue by 13659294036** [ZLMediaKit/ZLMediaKit#887]
**websocket-rtsp

**main函数中我加了作者你说的代码，rtspSrvWS->start<WebsocketSession<RtspSession,HttpSession,WebSocketHeader::BINARY>>(1554);
写了一个web客户端的demo，支持websocket-rtsp，用ffmpeg推流rtsp://127.0.0.1/live/test,web demo发送拉流请求**ws://127.0.0.1:1554/live/test**, websocket连接成功了，但是过一会跟zlm服务器断开连接，日志打印illegal connection，rtsp流数据都是空的。不知道我拉流的Url有误，还是zlm服务器推流也必须是websocket-rtsp才可以？

**Comment by xia-chu** [comment]
拉流url应该是ws://127.0.0.1:1554/live/test，没后缀的。
rtsp需要握手啊，所以你的ws-rtsp客户端怎么写的？

**Comment by 13659294036** [comment]
服务器还需要websocket中判断是否是rtsp流，仿照checkLiveStreamFMP4写的checkLiveStreamRtsp，后面实现握手应该就可以了

**Comment by xia-chu** [comment]
> 需要websocket中判断是否是rtsp流，仿

不需要的 跟这个不是一回事

**Comment by 13659294036** [comment]
我直接用那个ws://127.0.0.1:1554/live/test，websocket直接就判断是普通的websocket连接。rtsp无法解析这个url，错误提示不合法的rtsp连接

**Comment by xia-chu** [comment]
如果你不打算编写或不明白ws-rtsp客户端 建议你还是放弃次想法
