### ISSUE TITLE
GET_CONFIG 得到的配置在动态修改时，是不是线程安全的？

### ISSUE THREAD

**Issue by stone-wind** [zlmediakit/ZLMediaKit#89]
GET_CONFIG创建了静态配置变量，并通过NoticeCenter::Instance().addListener注册修改回调，
但是在emitEvent中调用修改回调时，其他线程可以同时访问静态配置变量，这个访问可能非线程安全。

**Comment by xiongziliang** [comment]
是的 如果访问是string类型的静态变量，确实不是线程安全的，这个确实是个隐患。
我本打算做个线程安全的string替换掉目前的string，但是由于目前热更新配置文件的场景并不多，而且目前也没遇到热更新配置文件导致的bug，所以目前将近用着。
