### ISSUE TITLE
[功能请求]zlm能否支持ts文件点播

### ISSUE THREAD

**Issue by 13659294036** [ZLMediaKit/ZLMediaKit#890]
ts文件和mp4是比较常见的文件格式，服务器支持最好

1.麻烦问一下zlm不支持ts文件点播的原因
2.如果自己开发的话，难度大吗，大概需要修改什么

多谢~~

**Comment by xia-chu** [comment]
ts转rtsp rtmp吗？点播现在推荐用http方式 不建议解复用方式的点播

**Comment by 13659294036** [comment]
1.不建议用解复用方式点播原因是什么
2.如果是rtsp方式点播ts，开发难度大吗，需要了解什么
3.如果是http方式点播ts，开发难度大吗？

**Comment by xia-chu** [comment]
解复用太麻烦了 要读取文件并解析提取出帧 并转换成其他容器格式和协议，性能和稳定性得不到保证。
如果是http方式点播ts，现在就支持啊，本质就是http文件分片下载，客户端解复用多种容器格式。
要实现rtsp方式点播ts还是比较麻烦的，要修改不少代码。
