### ISSUE TITLE
ws+fmp4客户端h5+mse开始显示出一帧图像后卡顿一个I帧间隔时间

### ISSUE THREAD

**Issue by caojunwei1988** [ZLMediaKit/ZLMediaKit#892]
**bug现象**
- 使用RTSP从源端拉流到ZLMedia，使用ws+fmp4发布
- h5+mse客户端显示出一帧图像后卡顿“一个I帧间隔时间”，如：I帧间隔50帧，帧率25，那么就是卡顿2S
-同时用rtsp从ZLMedia拉此流无此现象

**操作系统环境**
- centos7.5

**Comment by caojunwei1988** [comment]
补充：使用的H265的视频
初步怀疑和ws+fmp4这个机制有关，这块代码还没深入去看，是否fmp4打包导致？

**Comment by xia-chu** [comment]
你这个issue和 #891 没啥区别吧

**Comment by caojunwei1988** [comment]
> 你这个issue和 #894 没啥区别吧

有区别，894是部分视频会有这个问题，但是从ZLMedia用rtsp拉流到vlc显示正常。http+fmp4下载下来播放也是有花屏

**Comment by xia-chu** [comment]
fmp4下载的文件能否分享下
