### ISSUE TITLE
是否有考虑增加内存/字符串操作的安全函数库

### ISSUE THREAD

**Issue by PrimeQH** [ZLMediaKit/ZLMediaKit#893]
常见的内存/字符串操作类的函数，如memcpy_s、strcpy_s等函数。

**Comment by PrimeQH** [comment]
标签选择错误

**Comment by xia-chu** [comment]
据我所知 这些api并不跨平台



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QH ***@***.***&gt;
发送时间: 2021年5月27日 11:11
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] 是否有考虑增加内存/字符串操作的安全函数库 (#893)





 
常见的内存/字符串操作类的函数，如memcpy_s、strcpy_s等函数。
