### ISSUE TITLE
ws+fmp4客户端h5+mse播放过程间隔性花屏

### ISSUE THREAD

**Issue by caojunwei1988** [ZLMediaKit/ZLMediaKit#894]
**bug现象**
- ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
- 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
- 同一路流，用vlc拉取RTSP播放无此现象

**操作系统环境**
- centos7.5

**Comment by xia-chu** [comment]
换vlc ffmpeg花屏吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: caojunwei1988 ***@***.***&gt;
发送时间: 2021年5月27日 11:39
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] ws+fmp4客户端h5+mse播放过程间隔性花屏 (#894)





 
bug现象
  
ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布 

客户端H5+MSE，视频播放过程中出现间隔性花屏现象 

同一路流，用vlc拉取RTSP播放无此现象 
 
操作系统环境
  
centos7.5

**Comment by caojunwei1988** [comment]
vlc用rtsp从ZLMedia拉取不花屏

**Comment by caojunwei1988** [comment]
> 换vlc ffmpeg花屏吗 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: caojunwei1988 ***@***.***&gt; 发送时间: 2021年5月27日 11:39 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] ws+fmp4客户端h5+mse播放过程间隔性花屏 (#894) bug现象 ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布 客户端H5+MSE，视频播放过程中出现间隔性花屏现象 同一路流，用vlc拉取RTSP播放无此现象 操作系统环境 centos7.5 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

vlc用rtsp从ZLMedia拉取不花屏

**Comment by xia-chu** [comment]
vlc播放http-fmp4试试花屏不

**Comment by caojunwei1988** [comment]
> vlc播放http-fmp4试试花屏不

vlc播放不了这种链接（http://10.72.76.216:8070/live/44030601001310002461/6b62461d53884cd1966bcdcf4c3c4cfe.live.mp4）
链接直接从浏览器下载下来用播放器播放也有花屏

**Comment by xia-chu** [comment]
抱歉，这个issue忘记跟进了，花屏的fmp4文件还在吗？可以分享下吗

**Comment by caojunwei1988** [comment]
> 抱歉，这个issue忘记跟进了，花屏的fmp4文件还在吗？可以分享下吗

前几天出差了，没投入这个事情，抱歉。
问题：源流端------rtsp拉流----->ZLMedia------ws+fmp4------>客户端（间断性花屏）
对比：源流端------rtsp拉流----->ZLMedia------RTSP------>客户端（显示正常）

源端ES流文件：链接：https://pan.baidu.com/s/1nDZZaBMQeK_GiCarIPW4VA 提取码：1234 
源端RTSP打包ES 后发往ZLMedia的RTP文件：链接：https://pan.baidu.com/s/1TfScPzQ56p70WY4biIF9Kw 提取码：1234 
ws+fmp4客户端保存文件：链接：https://pan.baidu.com/s/1cE3IdiniMFNcXxVP0k4O9w 提取码：1234 

帮忙分析下，感谢！感谢！

**Comment by xia-chu** [comment]
好 我分析下

**Comment by xia-chu** [comment]
老哥 你怎么不压缩再上传啊 百度云盘可能压缩文件的

**Comment by xia-chu** [comment]
而且GitHub可以直接上传zip、MP4文件的

**Comment by caojunwei1988** [comment]
> 而且GitHub可以直接上传zip、MP4文件的

稍等我压缩重传下

**Comment by caojunwei1988** [comment]
> > 而且GitHub可以直接上传zip、MP4文件的
> 
> 稍等我压缩重传下
三个文件有七十几Mb，太大了github上传不了。我压缩zip上传网盘了。
链接：https://pan.baidu.com/s/1uP_9Is2obco8riw4E_kiug  提取码：1234

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/121460682-f3329300-c9df-11eb-9a72-9126a92e2450.png)

这个问题好像是判断h265是否为关键帧的逻辑有问题导致的 昨天修复了 你更新代码试试

**Comment by caojunwei1988** [comment]
> ![图片](https://user-images.githubusercontent.com/11495632/121460682-f3329300-c9df-11eb-9a72-9126a92e2450.png)
> 
> 这个问题好像是判断h265是否为关键帧的逻辑有问题导致的 昨天修复了 你更新代码试试

用最新master测试了一下，问题依旧存在。只要是fmp4（http-fmp4、ws+fmp4）都存在花屏的问题。

**Comment by ireader** [comment]
方便的话直接qq传给我吧， 没有百度网盘客户端。 QQ：579575545

**Comment by double2li** [comment]
> **bug现象**
> 
> * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> * 同一路流，用vlc拉取RTSP播放无此现象
> 
> **操作系统环境**
> 
> * centos7.5

mse不支持fmp4-265吧

**Comment by xia-chu** [comment]
> > **bug现象**
> > 
> > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > * 同一路流，用vlc拉取RTSP播放无此现象
> > 
> > **操作系统环境**
> > 
> > * centos7.5
> 
> mse不支持fmp4-265吧

是的 不支持 但是vlc ffplay支持

**Comment by caojunwei1988** [comment]
> > > **bug现象**
> > > 
> > > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > > * 同一路流，用vlc拉取RTSP播放无此现象
> > > 
> > > **操作系统环境**
> > > 
> > > * centos7.5
> > 
> > 
> > mse不支持fmp4-265吧
> 
> 是的 不支持 但是vlc ffplay支持

这个支持的，我现在H265的方案用的就是ws+fmp4------->浏览器MSE+H5。现在除了有一些录像回放存在问题，其他基本都调好了。

**Comment by xia-chu** [comment]
@caojunwei1988 老哥方便把rtsp暴露公网吗 我们好测试下

**Comment by caojunwei1988** [comment]
> @caojunwei1988 老哥方便把rtsp暴露公网吗 我们好测试下

我看下公司这边方不方便搭建。弄好了告诉你。

**Comment by caojunwei1988** [comment]
> > @caojunwei1988 老哥方便把rtsp暴露公网吗 我们好测试下
> 
> 我看下公司这边方不方便搭建。弄好了告诉你。
@xia-chu @ireader 
这个是公网的RTSP源。是一段10分钟左右的录像。这个URL中A字段每次访问的时候需要改一下，和上次不一样就可以。
rtsp://218.17.0.236:5545/record/11000000001110000020-1/time-1623383086-1623383795/s?A=70d16c8825465dba222da5c4ab46

谢谢!

**Comment by xia-chu** [comment]
暂时不要关 我下午测试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: caojunwei1988 ***@***.***&gt;
发送时间: 2021年6月11日 12:19
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] ws+fmp4客户端h5+mse播放过程间隔性花屏 (#894)





   
@caojunwei1988 老哥方便把rtsp暴露公网吗 我们好测试下
  
我看下公司这边方不方便搭建。弄好了告诉你。
 @xia-chu @ireader
 这个是公网的RTSP源。是一段10分钟左右的录像。这个URL中A字段每次访问的时候需要改一下，和上次不一样就可以。
 rtsp://218.17.0.236:5545/record/11000000001110000020-1/time-1623383086-1623383795/s?A=70d16c8825465dba222da5c4ab46
  
谢谢!

**Comment by double2li** [comment]
> > > > **bug现象**
> > > > 
> > > > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > > > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > > > * 同一路流，用vlc拉取RTSP播放无此现象
> > > > 
> > > > **操作系统环境**
> > > > 
> > > > * centos7.5
> > > 
> > > 
> > > mse不支持fmp4-265吧
> > 
> > 
> > 是的 不支持 但是vlc ffplay支持
> 
> 这个支持的，我现在H265的方案用的就是ws+fmp4------->浏览器MSE+H5。现在除了有一些录像回放存在问题，其他基本都调好了。

https://caniuse.com/?search=265

> > > > **bug现象**
> > > > 
> > > > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > > > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > > > * 同一路流，用vlc拉取RTSP播放无此现象
> > > > 
> > > > **操作系统环境**
> > > > 
> > > > * centos7.5
> > > 
> > > 
> > > mse不支持fmp4-265吧
> > 
> > 
> > 是的 不支持 但是vlc ffplay支持
> 
> 这个支持的，我现在H265的方案用的就是ws+fmp4------->浏览器MSE+H5。现在除了有一些录像回放存在问题，其他基本都调好了。

看下面对浏览器支持265的情况，只有Safari浏览器支持吧，你用的什么浏览器？
https://caniuse.com/?search=265

**Comment by double2li** [comment]
> > > > **bug现象**
> > > > 
> > > > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > > > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > > > * 同一路流，用vlc拉取RTSP播放无此现象
> > > > 
> > > > **操作系统环境**
> > > > 
> > > > * centos7.5
> > > 
> > > 
> > > mse不支持fmp4-265吧
> > 
> > 
> > 是的 不支持 但是vlc ffplay支持
> 
> 这个支持的，我现在H265的方案用的就是ws+fmp4------->浏览器MSE+H5。现在除了有一些录像回放存在问题，其他基本都调好了。

看下面对浏览器支持265的情况，只有Safari浏览器支持吧，你用的什么浏览器？
https://caniuse.com/?search=265

**Comment by double2li** [comment]
> > > > **bug现象**
> > > > 
> > > > * ZLMedia使用RTSP从源端拉流，使用ws+fmp4发布
> > > > * 客户端H5+MSE，视频播放过程中出现间隔性花屏现象
> > > > * 同一路流，用vlc拉取RTSP播放无此现象
> > > > 
> > > > **操作系统环境**
> > > > 
> > > > * centos7.5
> > > 
> > > 
> > > mse不支持fmp4-265吧
> > 
> > 
> > 是的 不支持 但是vlc ffplay支持
> 
> 这个支持的，我现在H265的方案用的就是ws+fmp4------->浏览器MSE+H5。现在除了有一些录像回放存在问题，其他基本都调好了。

看下面对浏览器支持265的情况，只有Safari浏览器支持吧，@caojunwei1988 你用的什么浏览器 ？
https://caniuse.com/?search=265

**Comment by xia-chu** [comment]
问题找到了 你这个流时间戳有问题：
![图片](https://user-images.githubusercontent.com/11495632/121991271-e93ed480-cdd1-11eb-936d-640efaf85e19.png)

NAL_TRAIL_R类型的帧有两帧时间戳相同，相当于264的P帧时间戳相同

**Comment by caojunwei1988** [comment]
> 问题找到了 你这个流时间戳有问题：
> ![图片](https://user-images.githubusercontent.com/11495632/121991271-e93ed480-cdd1-11eb-936d-640efaf85e19.png)
> 
> NAL_TRAIL_R类型的帧有两帧时间戳相同，相当于264的P帧时间戳相同

谢谢！我查一下源的问题，修正后再试下。
