### ISSUE TITLE
关于ZLMediaKit 依赖第三方库的配置

### ISSUE THREAD

**Issue by FoxesChen** [zlmediakit/ZLMediaKit#90]
LZ能否提供一个关于ZLMediaKit教程，或URL连接，适合象我这样的新手。

**Comment by FoxesChen** [comment]
是不是从Cmake里面，要配置下 这些第三方lib 和 include的路径，就可以了？

**Comment by xiongziliang** [comment]
> LZ能否提供一个关于ZLMediaKit教程，或URL连接，适合象我这样的新手。

URL链接的规则你可以参考[wiki](https://github.com/zlmediakit/ZLMediaKit/wiki/%E6%92%AD%E6%94%BEurl%E8%A7%84%E5%88%99)

**Comment by xiongziliang** [comment]
> 是不是从Cmake里面，要配置下 这些第三方lib 和 include的路径，就可以了？

ZLMediaKit可以在不依赖任何第三放lib的情况下完成编译，只是某些特性打不开而已(绝大部分还能使用)。

建议你在macOS或在ubuntu下编译，已经提供了编译脚本 很简单的

**Comment by FoxesChen** [comment]
谢谢你能回答。我已经处理好了。我把几个要用的第三方库 对应的include、lib、dll都下载到本地，然后告诉cmake 这些放在哪儿就可以了。虽然生成的project会报编译错误，但手动处理下就可以了。
