### ISSUE TITLE
[技术咨询]请问test_player播放rtsp流是没有声音的吗

### ISSUE THREAD

**Issue by DoubleX69** [ZLMediaKit/ZLMediaKit#900]
**test_player**

**咨询的具体内容和问题**
请问test_player播放rtsp流是没有声音的吗？
如何支持test_player播放rtsp流有声音呢？
先行谢过。

**Comment by xia-chu** [comment]
这个需要集成ffmpeg的音频解码器 然后再集成sdl的播放功能 其实也不难的

**Comment by DoubleX69** [comment]
> 
> 
> 这个需要集成ffmpeg的音频解码器 然后再集成sdl的播放功能 其实也不难的

感谢回复，我尝试下。
