### ISSUE TITLE
[功能请求]test_player支持rtsp流播放有声音

### ISSUE THREAD

**Issue by DoubleX69** [ZLMediaKit/ZLMediaKit#901]
**描述该功能的用处，可以提供相关资料描述该功能**
test_player可以播放rtsp流视频和音频，并且可以音画同步。

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**
test_player播放rtsp流没有声音。

**描述你期望实现该功能的方式和最终效果**
增加对rtsp流声音的处理，使用ffmpeg音频解码器处理流信息，增加sdl播放声音。
播放rtsp流可以做到音画同步。

**Comment by xia-chu** [comment]
这个暂时没空去做 而且在zlm中 这个东西也没啥必要，不是核心功能，除非我特别闲，否则真的不想花时间在这种事情上，现在还有很多更重要的事情去做，抱歉
