### ISSUE TITLE
addFFmpegSource推流到另一台主机的流媒体服务[技术咨询]

### ISSUE THREAD

**Issue by BigPotato1** [ZLMediaKit/ZLMediaKit#902]
**咨询的功能模块**
- addFFmpegSource推流

**咨询的具体内容和问题**
- addFFmpegSource推流到另一台主机的流媒体服务，报错{
    "code": -1,
    "msg": "ffmpeg已经退出,exit code = 1"
}

**Comment by BigPotato1** [comment]
![企业微信截图_16225926962590](https://user-images.githubusercontent.com/45842244/120410444-930b7380-c385-11eb-9749-98cb5b3232aa.png)
![企业微信截图_16225939346666](https://user-images.githubusercontent.com/45842244/120410452-969efa80-c385-11eb-8bad-5aa389795122.png)

**Comment by xia-chu** [comment]
推流连接失败 推流url无效 端口未打开
