### ISSUE TITLE
[技术咨询] 如何增加"在运行时通过HTTP接口更改HlsMaker::_file_index"的功能

### ISSUE THREAD

**Issue by ganttee** [ZLMediaKit/ZLMediaKit#903]
**咨询的功能模块**
- HLS

**咨询的具体内容和问题**
- 想要在运行时，通过HTTP接口更改`HlsMaker::_file_index`的值。WebApi部分可以找到从流信息找到源对象的例子，但是不知道怎么从源对象更改`HlsMaker::_file_index`，还请作者指点一下🙏

**Comment by ganttee** [comment]
RtpProcess->_muxer(MultiMediaSourceMuxer)->_muxer(MultiMuxerPrivate)->_hls(HlsRecorder)->_hls(HlsMakerImp)->_file_index
目前是依次增加setTsIndex函数，以修改ts的序列号。

是否有线程安全问题？

**Comment by ganttee** [comment]
```
static void accessFile(TcpSession &sender, const Parser &parser, const MediaInfo &mediaInfo, const string &strFile, const HttpFileManager::invoker &cb) {
    bool is_hls = end_with(strFile, kHlsSuffix);
    bool file_exist = File::is_file(strFile.data());
    if (!is_hls && !file_exist) {
        //文件不存在且不是hls,那么直接返回404
        sendNotFound(cb);
        return;
    }
```

HLS包含m3u8和ts分片两部分。但是上面的逻辑只校验了m3u8文件，如果请求的切片还没有生成是不是就返回404了。

这样是否是有问题的？

**Comment by xia-chu** [comment]
> ```
> static void accessFile(TcpSession &sender, const Parser &parser, const MediaInfo &mediaInfo, const string &strFile, const HttpFileManager::invoker &cb) {
>     bool is_hls = end_with(strFile, kHlsSuffix);
>     bool file_exist = File::is_file(strFile.data());
>     if (!is_hls && !file_exist) {
>         //文件不存在且不是hls,那么直接返回404
>         sendNotFound(cb);
>         return;
>     }
> ```
> 
> HLS包含m3u8和ts分片两部分。但是上面的逻辑只校验了m3u8文件，如果请求的切片还没有生成是不是就返回404了。
> 
> 这样是否是有问题的？

未生成ts切片是不会注册hls mediasource的，也不会生成m3u8文件

**Comment by xia-chu** [comment]
> RtpProcess->_muxer(MultiMediaSourceMuxer)->_muxer(MultiMuxerPrivate)->_hls(HlsRecorder)->_hls(HlsMakerImp)->_file_index
> 目前是依次增加setTsIndex函数，以修改ts的序列号。
> 
> 是否有线程安全问题？

_hls对象是动态创建销毁的 这个访问时最易线程安全 其他不用
