### ISSUE TITLE
[技术咨询]rtsp vlc播放正常，zlm使用rtspproxy 出现255 no such track with interleaved:4

### ISSUE THREAD

**Issue by chenxihai** [ZLMediaKit/ZLMediaKit#904]
华为摄像头提供的rtsp地址，使用vlc播放正常，想使用zlm将rtsp转flv，zlm播放rtsp时报255 no such track with interleaved:4，然后重试播放
![image](https://user-images.githubusercontent.com/68054900/120766255-a0268f00-c54c-11eb-8915-07717652c00f.png)，请指点！！谢谢

**Comment by xia-chu** [comment]
代码版本是多少？这个大概率是摄像头有bug 存在发送tcp缓冲覆盖的bug。
你先更新zlm试试 不行就改成udp模式拉流吧

**Comment by summitxf** [comment]
> 华为摄像头提供的rtsp地址，使用vlc播放正常，想使用zlm将rtsp转flv，zlm播放rtsp时报255 no such track with interleaved:4，然后重试播放 ![image](https://user-images.githubusercontent.com/68054900/120766255-a0268f00-c54c-11eb-8915-07717652c00f.png)，请指点！！谢谢

@chenxihai  兄弟，我用最新的版本碰见跟你一模一样的报错，请问你解决了吗？

**Comment by xia-chu** [comment]
可以吧rtsp地址暴露出来 我调试下

**Comment by summitxf** [comment]
方便给个私信地址吗？

**Comment by xia-chu** [comment]
你发这里 然后再删除就是了 我会收到邮件的

**Comment by summitxf** [comment]
> 你发这里 然后再删除就是了 我会收到邮件的
```text
rtsp://36.156.153.128:19554/07610246995139910101?DstCode=01&ServiceType=1&ClientType=1&StreamID=1&SrcTP=2&DstTP=2&SrcPP=1&DstPP=1&MediaTransMode=0&BroadcastType=0&SV=1&Token=H6/JfHfZU2YjthbKL9kwKbuwsNBJ3qSrZTFCjMlLM18=&
```

**Comment by summitxf** [comment]
收到了吗？

**Comment by xia-chu** [comment]
收到了 其实你发出去就可以立即删除

**Comment by xia-chu** [comment]
我看下去

**Comment by xia-chu** [comment]
可以正常拉流啊 没啥问题啊 看来你截图的问题还是这个摄像头在网速不好时会有bug

**Comment by xia-chu** [comment]
![图片](https://user-images.githubusercontent.com/11495632/173014031-25cb0442-7f1b-4291-9c4c-96dcfcbc6d60.png)
你看我test_player都可以播放

**Comment by summitxf** [comment]
隔断时间会重试，跟截图里面的报错一样  255 no such track with interleaved:4， 然后重新播放

**Comment by summitxf** [comment]
调用的这个方法 addStreamProxy

**Comment by xia-chu** [comment]
> 255 no such track with interleaved:4

这个问题本质是摄像头tcp发送存在bug 有tcp发送缓冲区覆盖问题

**Comment by summitxf** [comment]
那么就是网络问题了吗？ vlc和ffmpeg 转流 都可以的呢

**Comment by xia-chu** [comment]
vlc好FFmpeg默认udp拉流，你用zlm的udp拉流也没事

**Comment by summitxf** [comment]
zlm的udp拉 直接报session timeout

**Comment by xia-chu** [comment]
我这里确实也出现这个问题了：
<img width="1331" alt="图片" src="https://user-images.githubusercontent.com/11495632/173014796-34298d6f-7aac-4366-b2ef-63c17c702ace.png">

**Comment by summitxf** [comment]
明白了  抓包确实有丢包，大包截断了

**Comment by xia-chu** [comment]
这个问题 海康 宇视 华为都有；我在GB28181处理中有根据ssrc来恢复上下文的逻辑。
rtsp的有点不一样，但是也可以根据$来恢复上下文，但是挺麻烦的

**Comment by xia-chu** [comment]
这有点尴尬了 这个不是tcp上下文覆盖问题，应该是真的有乱七八糟的rtp：
<img width="1489" alt="图片" src="https://user-images.githubusercontent.com/11495632/173016217-709b1c2b-9733-41ab-8b8f-fa26fdff8fac.png">

**Comment by xia-chu** [comment]
确实不是tcp缓冲覆盖问题，而是华为发了点私货，未经协商的数据：
<img width="1340" alt="图片" src="https://user-images.githubusercontent.com/11495632/173017794-79a77764-946e-4c38-9f1e-26ba4f0cd700.png">

**Comment by summitxf** [comment]
107-9=8  多了8个未知的东西？

**Comment by xia-chu** [comment]
后面再改下吧

**Comment by summitxf** [comment]
![image](https://user-images.githubusercontent.com/2052347/173025263-70f9cce7-c89c-4400-8e79-72da7df51c03.png)
确实有很多tcp的错误包，这个zlm这边后续能升级处理吗？

**Comment by xia-chu** [comment]
兼容了 请更新zlm代码

**Comment by summitxf** [comment]
> @summitxf 兼容了 请更新zlm代码

早上验证过了，完美解决！赞！
