### ISSUE TITLE
[技术咨询]流媒体的docker镜像进行截图时，/index/api/getSnap 接口获取不到截图

### ISSUE THREAD

**Issue by BigPotato1** [ZLMediaKit/ZLMediaKit#905]
**咨询的功能模块**
- 流媒体获取视频流截图快照

**咨询的具体内容和问题**
-使用流媒体的docker镜像进行截图时，“/index/api/getSnap” 接口获取不到截图，返回“您访问的资源不存在”，原因好像是在ffmpeg截图命令中默认的是采用udp传输，而udp传输在传输1080p时很容易会丢包，导致截图返回为空。暂时尝试添加强制使用tcp传输，即调用流媒体接口“/index/api/setServerConfig”，将配置文件中“ffmpeg.snap”的值更改为“%s -rtsp_transport tcp -i %s -y -f mjpeg -t 0.001 %s”（注：调用接口更改配置时，注意“%”是需要用“%25”替换转义），强制使用tcp传输，暂时成功获取到截图，想问下是否有更好的解决方法。

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
截图你可以截其他格式的url 不用rtsp的就行

**Comment by xia-chu** [comment]
可以用http-flv这种 这种url握手很快 截图应该能快点

**Comment by ideazoom** [comment]
@xia-chu 我调用这个接口截图总是返回默认官方默认图片（ZLMediaKit字样的图片）。请问这是什么什么问题啊？

**Comment by BigPotato1** [comment]
> @xia-chu 我调用这个接口截图总是返回默认官方默认图片（ZLMediaKit字样的图片）。请问这是什么什么问题啊？
尝试一下我上面说的方法将UDP传输强制改为TCP传输

**Comment by Zeus723864** [comment]
请问怎么解决的？调用也是报错404，麻烦大佬可以帮我看看吗？
请求地址是：http://192.168.1.129:8087/index/api/getSnap?secret=1Lr2r12xusVdCjO6XYInWtBX6liae123&expire_sec=1&url=rtsp%3A%2F%2F192.168.1.129%3A554%2Frtp%2F34020000001320000001_34020000001320000001&timeout_sec=15
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/109774691/8e4f1970-e864-49fd-ae09-e33a7453b3a7)
![image](https://github.com/ZLMediaKit/ZLMediaKit/assets/109774691/2fa78349-308a-4278-b6fa-81a7bceece29)

**Comment by Zeus723864** [comment]
@xia-chu 大佬  我的也是404  麻烦可以帮忙看一下吗？

**Comment by Zeus723864** [comment]
已经解决了  是系统没有安装ffmpeg,安装之后将配置文件的地址修改一下就好了

**Comment by yangtongh** [comment]
> > 我调用这个接口截图总是返回默认官方默认图片（ZLMediaKit字样的图片）。请问这是什么问题啊？尝试一下我上面说的方法将UDP传输强制改为TCP传输

我是也这种问题

**Comment by yangtongh** [comment]
> 截图你可以截其他格式的url 不用rtsp的就行

rtsp不支持吗，如果非要用的话
