### ISSUE TITLE
无法播放GB28181流

### ISSUE THREAD

**Issue by xiaohui886688** [ZLMediaKit/ZLMediaKit#906]
**无法播放GB28181流**
- 有一些设备推流的时候，无法进行播放，日志如下：
![2021-06-06_212056](https://user-images.githubusercontent.com/4488929/120925903-4ae5ab80-c70d-11eb-9dc8-d703db109d35.png)

数据文件已发送至您的邮箱

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
- WindowsServer 2012

**Comment by xia-chu** [comment]
日志很明显，流推上来了 但是浏览器和flv.js不支持G711,所以没法播放。最新的zlmediakit支持关闭音频，你可以修改配置文件中的enableAudio改成0关闭就可以播放了

**Comment by xiaohui886688** [comment]
你好，大佬，最新的功能我试过了，将音频关闭了，依然是这个问题。
我将最新的dump包发送至您的邮箱了，您有时间看看呗。

**Comment by xia-chu** [comment]
你配置文件咋修改的？

**Comment by xiaohui886688** [comment]
配置如下：
![2021-06-07_164437](https://user-images.githubusercontent.com/4488929/120986987-b8e2af00-c7af-11eb-8bf9-d44526859589.png)
用最新的版本报错如下：
![2021-06-07_164424](https://user-images.githubusercontent.com/4488929/120987019-c1d38080-c7af-11eb-9c81-52eed6b472e5.png)

**Comment by xia-chu** [comment]
这个流有问题呢 没sps pps

**Comment by xiaohui886688** [comment]
有办法解决吗？大佬

**Comment by xia-chu** [comment]
多试试几次 这个摄像头可能有问题

**Comment by xia-chu** [comment]
这个issue先关闭了
