### ISSUE TITLE
播放和停止webrtc视频时ID不一致

### ISSUE THREAD

**Issue by songxue3073** [ZLMediaKit/ZLMediaKit#907]
播放webrtc视频流时webhook回调函数OnPlay中的Id与停止webrtc视频流时webhook回调函数OnFlowReport中的Id不一致，且OnFlowReport中的Ip为空，播放停止http-flv视频流是正常的

**Comment by wujincheng2333** [comment]
webrtc协议不一样，你可以通过增加连接参数去判断唯一，这样更好处理。就是每次播放都生成一个唯一id放在url参数上。这样就可以判断了

**Comment by xia-chu** [comment]
有道理😅 我没想到这个 确实可以这样 而且这样可以直接关键用户id播放流水号什么的&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wujincheng2333 ***@***.***&gt;
发送时间: 2021年7月6日 10:54
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] 播放和停止webrtc视频时ID不一致 (#907)





 
webrtc协议不一样，你可以通过增加连接参数去判断唯一，这样更好处理。就是每次播放都生成一个唯一id放在url参数上。这样就可以判断了
