### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by ryandingf** [ZLMediaKit/ZLMediaKit#908]
海康车载设备花屏，已是最新代码。
![2341623145844_ pic_hd](https://user-images.githubusercontent.com/18289349/121164849-6a521500-c882-11eb-9ec5-73ea0ce0957f.jpg)

**Comment by xia-chu** [comment]
ehome推流还是28181推流？

**Comment by ryandingf** [comment]
> ehome推流还是28181推流？

ehome推流

**Comment by ryandingf** [comment]
用的是FreeEhome（https://github.com/tsingeye/FreeEhome）推流

**Comment by xia-chu** [comment]
这个问题比较棘手 没测试环境 所以也没法修复

**Comment by xia-chu** [comment]
请参考这个issue #869

**Comment by xia-chu** [comment]
我们统一在issue #869 上讨论，这个issue先关闭
