### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by caopengfei** [ZLMediaKit/ZLMediaKit#909]
**咨询的功能模块**
使用ffmpeg推流报错

**咨询的具体内容和问题**
使用docker部署的服务（docker run -id -p 1935:1935 -p 8888:80 -p 8554:554 -p 10000:10000 -p 10000:10000/udp panjjo/zlmediakit）在使用下面的命令推流时报错：
ffmpeg -re -i test.mp4 -debug -f rtsp -rtsp_transport tcp rtsp://120.79.148.183:8554/live/aciga
详细的错误信息为
``` bash
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
 matched as AVOption 'debug' with argument '-f'.
Reading option 'rtsp' ... matched as output url.
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option 'rtsp://120.79.148.183:8554/live/aciga' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Successfully parsed a group of options.
Parsing a group of options: input url test.mp4.
Applying option re (read input at native frame rate) with argument 1.
Successfully parsed a group of options.
Opening an input file: test.mp4.
[NULL @ 000001fe8c07fc40] Opening 'test.mp4' for reading
[file @ 000001fe8c06bf00] Setting default whitelist 'file,crypto,data'
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] ISO: File Type Major Brand: mp42
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] Unknown dref type 0x206c7275 size 12
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] Setting codecpar->delay to 2 for stream st: 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] rfps: 28.833333 0.005219
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] rfps: 28.916667 0.000087
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] rfps: 29.000000 0.008256
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] Before avformat_find_stream_info() pos: 32505 bytes read:32768 seeks:0 nb_streams:2
[h264 @ 000001fe8c083940] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 000001fe8c083940] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 000001fe8c083940] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 000001fe8c083940] Format yuv420p chosen by get_format().
[h264 @ 000001fe8c083940] Reinit context to 544x960, pix_fmt: yuv420p
[h264 @ 000001fe8c083940] no picture
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fe8c07fc40] After avformat_find_stream_info() pos: 65721 bytes read:98304 seeks:0 frames:48
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2021-05-16T23:49:19.000000Z
    copyright       :
    copyright-eng   :
  Duration: 00:00:42.58, start: 0.000000, bitrate: 1654 kb/s
  Stream #0:0(und), 47, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-05-16T23:49:19.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1(und), 1, 1/90000: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 544x960, 0/1, 1520 kb/s, 28.91 fps, 28.92 tbr, 90k tbn, 58 tbc (default)
    Metadata:
      creation_time   : 2021-05-16T23:49:19.000000Z
      vendor_id       : [0][0][0][0]
      encoder         : JVT/AVC Coding
Successfully opened the file.
Parsing a group of options: output url rtsp.
Successfully parsed a group of options.
Opening an output file: rtsp.
[NULL @ 000001fe8c106cc0] Unable to find a suitable output format for 'rtsp'
rtsp: Invalid argument
[AVIOContext @ 000001fe8c089440] Statistics: 98304 bytes read, 0 seeks
```

**Comment by xia-chu** [comment]
改成 -acodec copy -vcodec copy

**Comment by caopengfei** [comment]
> 加上 -acodec copy -vcodec copy

使用命令：ffmpeg -i test.mp4 -acodec copy -vcodec copy -debug -f rtsp -rtsp_transport tcp rtsp://120.79.148.183:8554/live/aciga
还是一样报错，而且错误信息还是跟上面的一样：
ffmpeg version 4.4-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libglslang --enable-vulkan --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
 matched as AVOption 'debug' with argument '-f'.
Reading option 'rtsp' ... matched as output url.
Reading option '-rtsp_transport' ... matched as AVOption 'rtsp_transport' with argument 'tcp'.
Reading option 'rtsp://120.79.148.183:8554/live/aciga' ... matched as output url.
Finished splitting the commandline.
Parsing a group of options: global .
Successfully parsed a group of options.
Parsing a group of options: input url test.mp4.
Successfully parsed a group of options.
Opening an input file: test.mp4.
[NULL @ 0000021bdca7fc40] Opening 'test.mp4' for reading
[file @ 0000021bdca80400] Setting default whitelist 'file,crypto,data'
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] ISO: File Type Major Brand: mp42
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] Unknown dref type 0x206c7275 size 12
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] Setting codecpar->delay to 2 for stream st: 1
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] rfps: 28.833333 0.005219
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] rfps: 28.916667 0.000087
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] rfps: 29.000000 0.008256
    Last message repeated 1 times
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] Before avformat_find_stream_info() pos: 32505 bytes read:32768 seeks:0 nb_streams:2
[h264 @ 0000021bdca83b00] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0000021bdca83b00] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0000021bdca83b00] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0000021bdca83b00] Format yuv420p chosen by get_format().
[h264 @ 0000021bdca83b00] Reinit context to 544x960, pix_fmt: yuv420p
[h264 @ 0000021bdca83b00] no picture
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] All info found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000021bdca7fc40] After avformat_find_stream_info() pos: 65721 bytes read:98304 seeks:0 frames:48
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isom
    creation_time   : 2021-05-16T23:49:19.000000Z
    copyright       :
    copyright-eng   :
  Duration: 00:00:42.58, start: 0.000000, bitrate: 1654 kb/s
  Stream #0:0(und), 47, 1/48000: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-05-16T23:49:19.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1(und), 1, 1/90000: Video: h264 (High), 1 reference frame (avc1 / 0x31637661), yuv420p(left), 544x960, 0/1, 1520 kb/s, 28.91 fps, 28.92 tbr, 90k tbn, 58 tbc (default)
    Metadata:
      creation_time   : 2021-05-16T23:49:19.000000Z
      vendor_id       : [0][0][0][0]
      encoder         : JVT/AVC Coding
Successfully opened the file.
Parsing a group of options: output url rtsp.
Applying option acodec (force audio codec ('copy' to copy stream)) with argument copy.
Applying option vcodec (force video codec ('copy' to copy stream)) with argument copy.
Successfully parsed a group of options.
Opening an output file: rtsp.
[NULL @ 0000021bdcb400c0] Unable to find a suitable output format for 'rtsp'
rtsp: Invalid argument
[AVIOContext @ 0000021bdca89600] Statistics: 98304 bytes read, 0 seeks

**Comment by Dw9** [comment]
> rtsp: Invalid argument

把 -debug 去掉 或者 -loglevel debug
