### ISSUE TITLE
[技术咨询]

### ISSUE THREAD

**Issue by caopengfei** [ZLMediaKit/ZLMediaKit#910]
**咨询的功能模块**
使用obs推流失败

**咨询的具体内容和问题**
使用obs推流时，软件一直在断线重连
obs配置：
![微信截图_20210611183846](https://user-images.githubusercontent.com/10126284/121674182-4c83ea80-cae4-11eb-9e31-44f18c4e9dd3.png)
ZLMediaKit服务器日志：
![微信截图_20210611183948](https://user-images.githubusercontent.com/10126284/121674279-6d4c4000-cae4-11eb-9c21-f72d80d916fe.png)

**Comment by monktan89** [comment]
可以使用ffmpeg就行rtsp推流，类似于 ffmpeg -re -i  test.mp4 -vcodec h264 -acodec aac -f rtsp -rtsp_transport tcp rtsp://127.0.0.1/live/test

**Comment by caopengfei** [comment]
问题已解决，是因为部署在外网，所以连接有问题，估计是公司路由器做了限制，后来部署在本地测试没有问题了
