### ISSUE TITLE
[BUG] dev分支 rtsp 转 webrtc，使用ZLMRTCClient.js连接崩溃

### ISSUE THREAD

**Issue by harryharrygao** [ZLMediaKit/ZLMediaKit#911]
**操作系统环境**
- Mac OS

**bug现象**
- master和dev测试rtsp转rtmp等均正常（流通过addStreamProxy方式添加）
- dev分支测试转webrtc，打开ZLMRTCClient.js-dev/demo/index.html，访问http://127.0.0.1/index/api/webrtc?app=live&stream=xiong&type=play，试过几个开关项和分辨率，均崩溃，日志：

2021-06-11 23:31:28.565 I MediaServer[84795-0x700007d01000] WebRtcTransport.cpp:333 WebRtcTransportImp | 0x108b9d000
2021-06-11 23:31:28.568 D MediaServer[84795-0x700007d01000] WebApi.cpp:232 operator() | 
# request:
POST /index/api/webrtc?app=live&stream=xiong&type=play
# content:
v=0
o=- 4522788412557305336 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:22uR
a=ice-pwd:sPPMDusJgNqogcHpPckEU6Uu
a=ice-options:trickle
a=fingerprint:sha-256 7C:4C:25:6A:05:BF:E3:CB:11:3D:B9:39:00:A2:2C:A9:8D:A0:DF:A4:DC:2E:73:7B:E7:92:CD:EE:F2:F5:BA:5A
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 122 102 121 127 120 125 107 108 109 35 36 124 119 123 118 114 115 116 37
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:22uR
a=ice-pwd:sPPMDusJgNqogcHpPckEU6Uu
a=ice-options:trickle
a=fingerprint:sha-256 7C:4C:25:6A:05:BF:E3:CB:11:3D:B9:39:00:A2:2C:A9:8D:A0:DF:A4:DC:2E:73:7B:E7:92:CD:EE:F2:F5:BA:5A
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:122 VP9/90000
a=rtcp-fb:122 goog-remb
a=rtcp-fb:122 transport-cc
a=rtcp-fb:122 ccm fir
a=rtcp-fb:122 nack
a=rtcp-fb:122 nack pli
a=fmtp:122 profile-id=1
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-## crash date:2021-06-11 23:31:28
## stack:     
[0]: 0   MediaServer                         0x0000000101322c36 _ZL9sig_crashi + 70
[1]: 1   libsystem_platform.dylib            0x00007fff2065cd7d _sigtramp + 29
[2]: 2   ???                                 0x00000001056d4e7d 0x0 + 4386016893
[3]: 3   MediaServer                         0x0000000101f1bc8b _ZN3RTC11SrtpSession12DecryptSrtcpEPhPm + 43
[4]: 4   MediaServer                         0x0000000101f234a9 _ZN15WebRtcTransport13inputSockDataEPcmP8sockaddr + 617
[5]: 5   MediaServer                         0x0000000101f50628 _ZZN18WebRtcTransportImp8onCreateEvEN3$_3clERKNSt3__110shared_ptrIN7toolkit6BufferEEEP8sockaddri + 152
[6]: 6   MediaServer                         0x0000000101f5056e _ZNSt3__1L8__invokeIRZN18WebRtcTransportImp8onCreateEvE3$_3JRKNS_10shared_ptrIN7toolkit6BufferEEEP8sockaddriEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD_ + 94
[7]: 7   MediaServer  zsh: segmentation fault  ./MediaServer

## 另如果使用其他库，请求返回：

{
  "code": -400,
  "msg": "Assertion failed: (!origin.empty()), function checkValid, file ZLMediaKit_dev/webrtc/Sdp.cpp, line 1328."
}

**Comment by xia-chu** [comment]
你的srtp没编译进openssl



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: harryharrygao ***@***.***&gt;
发送时间: 2021年6月11日 23:44
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] dev分支 rtsp 转 webrtc，使用ZLMRTCClient.js连接崩溃 (#911)





 
操作系统环境
  
Mac OS 
 
bug现象
  
master和dev测试rtsp转rtmp等均正常（流通过addStreamProxy方式添加） 

dev分支测试转webrtc，打开ZLMRTCClient.js-dev/demo/index.html，访问http://127.0.0.1/index/api/webrtc?app=live&amp;stream=xiong&amp;type=play，试过几个开关项和分辨率，均崩溃，日志： 
 
2021-06-11 23:31:28.565 I MediaServer[84795-0x700007d01000] WebRtcTransport.cpp:333 WebRtcTransportImp | 0x108b9d000
 2021-06-11 23:31:28.568 D MediaServer[84795-0x700007d01000] WebApi.cpp:232 operator() |
 
request:
 
POST /index/api/webrtc?app=live&amp;stream=xiong&amp;type=play
 
content:
 
v=0
 o=- 4522788412557305336 2 IN IP4 127.0.0.1
 s=-
 t=0 0
 a=group:BUNDLE 0 1
 a=extmap-allow-mixed
 a=msid-semantic: WMS
 m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
 c=IN IP4 0.0.0.0
 a=rtcp:9 IN IP4 0.0.0.0
 a=ice-ufrag:22uR
 a=ice-pwd:sPPMDusJgNqogcHpPckEU6Uu
 a=ice-options:trickle
 a=fingerprint:sha-256 7C:4C:25:6A:05:BF:E3:CB:11:3D:B9:39:00:A2:2C:A9:8D:A0:DF:A4:DC:2E:73:7B:E7:92:CD:EE:F2:F5:BA:5A
 a=setup:actpass
 a=mid:0
 a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
 a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
 a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
 a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
 a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
 a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
 a=recvonly
 a=rtcp-mux
 a=rtpmap:111 opus/48000/2
 a=rtcp-fb:111 transport-cc
 a=fmtp:111 minptime=10;useinbandfec=1
 a=rtpmap:103 ISAC/16000
 a=rtpmap:104 ISAC/32000
 a=rtpmap:9 G722/8000
 a=rtpmap:0 PCMU/8000
 a=rtpmap:8 PCMA/8000
 a=rtpmap:106 CN/32000
 a=rtpmap:105 CN/16000
 a=rtpmap:13 CN/8000
 a=rtpmap:110 telephone-event/48000
 a=rtpmap:112 telephone-event/32000
 a=rtpmap:113 telephone-event/16000
 a=rtpmap:126 telephone-event/8000
 m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 122 102 121 127 120 125 107 108 109 35 36 124 119 123 118 114 115 116 37
 c=IN IP4 0.0.0.0
 a=rtcp:9 IN IP4 0.0.0.0
 a=ice-ufrag:22uR
 a=ice-pwd:sPPMDusJgNqogcHpPckEU6Uu
 a=ice-options:trickle
 a=fingerprint:sha-256 7C:4C:25:6A:05:BF:E3:CB:11:3D:B9:39:00:A2:2C:A9:8D:A0:DF:A4:DC:2E:73:7B:E7:92:CD:EE:F2:F5:BA:5A
 a=setup:actpass
 a=mid:1
 a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
 a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
 a=extmap:13 urn:3gpp:video-orientation
 a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
 a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
 a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
 a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
 a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
 a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
 a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
 a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
 a=recvonly
 a=rtcp-mux
 a=rtcp-rsize
 a=rtpmap:96 VP8/90000
 a=rtcp-fb:96 goog-remb
 a=rtcp-fb:96 transport-cc
 a=rtcp-fb:96 ccm fir
 a=rtcp-fb:96 nack
 a=rtcp-fb:96 nack pli
 a=rtpmap:97 rtx/90000
 a=fmtp:97 apt=96
 a=rtpmap:98 VP9/90000
 a=rtcp-fb:98 goog-remb
 a=rtcp-fb:98 transport-cc
 a=rtcp-fb:98 ccm fir
 a=rtcp-fb:98 nack
 a=rtcp-fb:98 nack pli
 a=fmtp:98 profile-id=0
 a=rtpmap:99 rtx/90000
 a=fmtp:99 apt=98
 a=rtpmap:100 VP9/90000
 a=rtcp-fb:100 goog-remb
 a=rtcp-fb:100 transport-cc
 a=rtcp-fb:100 ccm fir
 a=rtcp-fb:100 nack
 a=rtcp-fb:100 nack pli
 a=fmtp:100 profile-id=2
 a=rtpmap:101 rtx/90000
 a=fmtp:101 apt=100
 a=rtpmap:122 VP9/90000
 a=rtcp-fb:122 goog-remb
 a=rtcp-fb:122 transport-cc
 a=rtcp-fb:122 ccm fir
 a=rtcp-fb:122 nack
 a=rtcp-fb:122 nack pli
 a=fmtp:122 profile-id=1
 a=rtpmap:102 H264/90000
 a=rtcp-fb:102 goog-remb
 a=rtcp-## crash date:2021-06-11 23:31:28
 
exe:       MediaServer
 
signal:    11
 
stack:
 
[0]: 0   MediaServer                         0x0000000101322c36 _ZL9sig_crashi + 70
 [1]: 1   libsystem_platform.dylib            0x00007fff2065cd7d _sigtramp + 29
 [2]: 2   ???                                 0x00000001056d4e7d 0x0 + 4386016893
 [3]: 3   MediaServer                         0x0000000101f1bc8b _ZN3RTC11SrtpSession12DecryptSrtcpEPhPm + 43
 [4]: 4   MediaServer                         0x0000000101f234a9 _ZN15WebRtcTransport13inputSockDataEPcmP8sockaddr + 617
 [5]: 5   MediaServer                         0x0000000101f50628 _ZZN18WebRtcTransportImp8onCreateEvEN3$_3clERKNSt3__110shared_ptrIN7toolkit6BufferEEEP8sockaddri + 152
 [6]: 6   MediaServer                         0x0000000101f5056e _ZNSt3__1L8__invokeIRZN18WebRtcTransportImp8onCreateEvE3$3JRKNS_10shared_ptrIN7toolkit6BufferEEEP8sockaddriEEEDTclclsr3std3__1E7forwardIT_Efp_Espclsr3std3__1E7forwardIT0_Efp0_EEEOSC_DpOSD + 94
 [7]: 7   MediaServer  zsh: segmentation fault  ./MediaServer
 
另如果使用其他库，请求返回：
 
{
 "code": -400,
 "msg": "Assertion failed: (!origin.empty()), function checkValid, file ZLMediaKit_dev/webrtc/Sdp.cpp, line 1328."
 }

**Comment by harryharrygao** [comment]
谢谢秒级指点！😄
我是cmake提示错误时，用brew install srtp安装的，是不操作不对，求指点，太感谢了

**Comment by xia-chu** [comment]
源码编译srtp吧





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: harryharrygao ***@***.***&gt;
发送时间: 2021年6月11日 23:55
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] dev分支 rtsp 转 webrtc，使用ZLMRTCClient.js连接崩溃 (#911)





 
谢谢秒级指点！😄
 我是cmake提示错误时，用brew install srtp安装的，是不操作不对，求指点，太感谢了

**Comment by harryharrygao** [comment]
真是太给力了，webrtc正常播放了！！！！！！！！

下载https://github.com/cisco/libsrtp仓库中release的源码包
./configure --enable-openssl --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1k/
make
make install

然后重新编译ZLMediaKit

再次感谢大神！！！！！！！！！！
