### ISSUE TITLE
[技术咨询]在线测试地址都无法访问了

### ISSUE THREAD

**Issue by caopengfei** [ZLMediaKit/ZLMediaKit#912]
如题

**Comment by xia-chu** [comment]
是的 因为我带宽到期没公网ip了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: caopengfei ***@***.***&gt;
发送时间: 2021年6月12日 11:12
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]在线测试地址都无法访问了 (#912)





 
如题
