### ISSUE TITLE
Can HLS fragments cleanup be scheduled after specified time in seconds?

### ISSUE THREAD

**Issue by xoraingroup** [ZLMediaKit/ZLMediaKit#913]
Hi,

  Sorry I had to cleanup the template in this because even Google couldn't translate the strings so that I could fill the template properly.

Issue: When you start broadcasting using OBS, HLS fragments are generated. When you stop the stream the HLS fragments are removed immediately.

Is there any configuration in config file that can allow me to set a time in second, that will tell ZLMediaKit Server that remove the hls fragments after specified time mentioned in config when the stream is stopped.

Thank you

**Comment by xia-chu** [comment]
Sorry, there is no function you mentioned. What is the purpose of this function?

**Comment by xoraingroup** [comment]
Well the use case is when i am trying to stream video file to rtmp, the stream is running properly on destination and I can see it on hls player as well. But when the video file finishes, the stream on player stops immediately because the hls fragments are cleared up / deleted, even though there are still last 20 - 30 seconds of video remaining in hls.  For such purpose i was thinking if there is a kind of parameter that we can pass to MediaServer, so that it does the clean up of hls fragments after those config seconds. Is it possible to implement?

**Comment by xia-chu** [comment]
In fact, this function is relatively easy to implement. When deleting HLS files, we can delay the deletion

**Comment by xoraingroup** [comment]
Is it possible to tune it via configuration parameter in config.ini file?

**Comment by xia-chu** [comment]
Yes, need to add some code

> Is it possible to tune it via configuration parameter in config.ini file?

**Comment by xoraingroup** [comment]
Awesome. Waiting for update. Thank you

**Comment by xoraingroup** [comment]
Is this feature merged already?

**Comment by xia-chu** [comment]
Please give me two days. Thank you

**Comment by xoraingroup** [comment]
Sure and thank you for this. :)

**Comment by xia-chu** [comment]
It has been realized
