### ISSUE TITLE
[技术咨询]zlmediakit端口范围

### ISSUE THREAD

**Issue by jim-king-2000** [ZLMediaKit/ZLMediaKit#914]
为了使用zlmediakit，需要在防火墙上打开tcp/udp的那些端口？

**Comment by xia-chu** [comment]
这样看你用了zlm哪些服务 开启了哪些端口



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin ***@***.***&gt;
发送时间: 2021年6月15日 14:28
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]zlmediakit端口范围 (#914)

**Comment by xia-chu** [comment]
如果你不知道 你可以用netstate -ntpl查看zlm用的tcp端口 netstate -nupl看udp端口



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jim Jin ***@***.***&gt;
发送时间: 2021年6月15日 14:28
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]zlmediakit端口范围 (#914)

**Comment by jim-king-2000** [comment]
主要就是用RTSP - UDP拉流。会占用哪个端口段？

**Comment by penghd** [comment]
> 
> 
> 主要就是用RTSP - UDP拉流。会占用哪个端口段？

对外拉流不需要防火墙开放。

**Comment by xia-chu** [comment]
目前你如果用udp方式播放zlm的rtsp流，需要开放随机端口范围的udp端口，目前zlm的udp端口开辟都是随机的。Linux随机端口范围默认是30000~65535左右，你可以设置

**Comment by jim-king-2000** [comment]
非常感谢。
