### ISSUE TITLE
zlm无法拉到流[技术咨询]

### ISSUE THREAD

**Issue by liuxiswt** [ZLMediaKit/ZLMediaKit#917]
![image](https://user-images.githubusercontent.com/39022649/122323062-12d63800-cf59-11eb-948e-65c8755cb687.png)
使用的是wvp + ZLMediaKit，配置好后，无法拉到国标平台联级推的流数据。

**Comment by liuxiswt** [comment]
![image](https://user-images.githubusercontent.com/39022649/122325822-d953fb80-cf5d-11eb-9fa8-d02994020d94.png)
补充下图片，在线求解。。

**Comment by xia-chu** [comment]
zlm完全没收到rtp推流 请排查下网络问题

**Comment by liuxiswt** [comment]
我的网络和下级是一个局域网， 端口都可以互通。  本地测试推视频可以正常收到， 但是国标联级推流就收不到数据。 zlm 是用docker 直接拉的最新版。 抓包显示  只到AKC 后就无响应，直到超时退出。

**Comment by liuxiswt** [comment]
![image](https://user-images.githubusercontent.com/39022649/122504361-c0fee200-d02c-11eb-9ec0-c7c3d74766c4.png)备注抓包截图。

**Comment by wasphin** [comment]
抓包截图是 `SIP` 的, 而 `ZLMediaKit` 不处理 `SIP` 信令, 这个截图没有意义.

**Comment by penghd** [comment]
docker模式wvp要把auto选项关掉，请看wvp的wiki

**Comment by xia-chu** [comment]
issue关闭了？这个问题一般是wvp使用或网络设置不当导致的，跟zlm关系不大，建议在wvp项目提issue
