### ISSUE TITLE
[技术咨询]拉流个数

### ISSUE THREAD

**Issue by wjjboy** [ZLMediaKit/ZLMediaKit#919]
需要拉内网的摄像头流视频，想咨询下ZLMediaKit能支持多少路rtsp视频流的拉取(h.264 h.265编码都存在)。对应的硬件配置是怎么样的？

**Comment by xia-chu** [comment]
这个跟你的操作系统、硬件性能关系比较大。不过zlm rtsp拉流性能很强，你找不到比zlm拉rtsp流性能更强的开源软件了

**Comment by wjjboy** [comment]
> 这个跟你的操作系统、硬件性能关系比较大。不过zlm rtsp拉流性能很强，你基本找不到比zlm拉rtsp流性能更强的开源软件了

嗯嗯，是比较看好这个工具。但是没找到相关技术资料，所以想咨询一下。
拉流的话是否需要gpu, 一般8c16g的云主机可以支持多少录摄像头的视频流拉取？

**Comment by xia-chu** [comment]
不需要gpu

**Comment by wjjboy** [comment]
> 不需要gpu

嗯，那拉很多流的话cpu的需要多核还是高频？
还有能给到一台机器能拉流个数的测试数据么？
我们的场景需要拉1000-2000录摄像头，需要评估下机器的投入。

**Comment by xia-chu** [comment]
这么些流 8核够了 但是注意你带宽够不够？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: WuJiajun ***@***.***&gt;
发送时间: 2021年6月23日 14:21
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]拉流个数 (#919)





  
不需要gpu
  
嗯，那拉很多流的话cpu的需要多核还是高频？
 还有能给到一台机器能拉流个数的测试数据么？
 我们的场景需要拉1000-2000录摄像头，需要评估下机器的投入。

**Comment by wjjboy** [comment]
> 这么些流 8核够了 但是注意你带宽够不够？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: WuJiajun ***@***.***&gt; 发送时间: 2021年6月23日 14:21 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]拉流个数 (#919) 不需要gpu 嗯，那拉很多流的话cpu的需要多核还是高频？ 还有能给到一台机器能拉流个数的测试数据么？ 我们的场景需要拉1000-2000录摄像头，需要评估下机器的投入。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，网络是内网。

**Comment by ideazoom** [comment]
> 这个跟你的操作系统、硬件性能关系比较大。不过zlm rtsp拉流性能很强，你基本找不到比zlm拉rtsp流性能更强的开源软件了

我在虚拟机里测试（Centos7 CPU:2颗共16核，16G内存），只能拉10路，再多就报 "SETUP:500 Internal Server Error"错误。求解

**Comment by xia-chu** [comment]
那不就是你的摄像头只支持10路吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ideazoom ***@***.***&gt;
发送时间: 2021年6月24日 11:14
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]拉流个数 (#919)





  
这个跟你的操作系统、硬件性能关系比较大。不过zlm rtsp拉流性能很强，你基本找不到比zlm拉rtsp流性能更强的开源软件了
  
我在虚拟机里测试（Centos7 CPU:2颗共16核，16G内存），只能拉10路，再多就报 "SETUP:500 Internal Server Error"错误。求解

**Comment by ideazoom** [comment]
> 那不就是你的摄像头只支持10路吗？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ideazoom ***@***.***&gt; 发送时间: 2021年6月24日 11:14 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]拉流个数 (#919) 这个跟你的操作系统、硬件性能关系比较大。不过zlm rtsp拉流性能很强，你基本找不到比zlm拉rtsp流性能更强的开源软件了 我在虚拟机里测试（Centos7 CPU:2颗共16核，16G内存），只能拉10路，再多就报 "SETUP:500 Internal Server Error"错误。求解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

哦，原来如此啊。
