### ISSUE TITLE
Windows中，用ffmpeg抓取桌面，并以H264的格式推送给服务器。

### ISSUE THREAD

**Issue by FoxesChen** [zlmediakit/ZLMediaKit#92]
通过FFMPEG的接口，我将电脑桌面抓出来，通过 SwsContext()，sws_scale() ，将桌面帧AV_PIX_FMT_BGRA  转成 AV_PIX_FMT_YUV420P，然后我应该怎么样，和MediaPusher这个类对接，才能将这个数据推送给服务器？以RTSP/RTMP方式推送。

**Comment by xiongziliang** [comment]
你采集到YUV数据后，应该通过DevChannel接口输入YUV，DevChannel接口会编码成264,然后生成并注册成RtmpMediaSource。
在触发RtmpMediaSource注册事件时，后续的Rtmp推流流程请参考测试程序test_pusher.

**Comment by FoxesChen** [comment]
`
class DesktopDevChannel : DevChannel
{
public:
	typedef std::shared_ptr<DesktopDevChannel> Ptr;

	DesktopDevChannel(const string &strVhost, const string &strApp, const string &strId);
	~DesktopDevChannel();

	void initVideo(const VideoInfo &info) {
		DevChannel::initVideo(info);
	}

	void inputYUV(char *apcYuv[3], int aiYuvLen[3], uint32_t uiStamp) {
		DevChannel::inputYUV(apcYuv, aiYuvLen, uiStamp);
	}
};
`
我自己写了个类，这个类从DevChannel里面继承的。直接公开了InitVideo() 和 inputYUV() 这2个方法。

然后在main里面注册RtmpMediaSource 这个事件，就象这样
NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastMediaChanged, [pushUrl, poller](BroadcastMediaChangedArgs) {
		if (bRegist && pushUrl.find(schema) == 0)
		{
			createPusher(poller, "rtmp", DEFAULT_VHOST, "live", "stream", pushUrl);
		}
	});}

VideoInfo vi = { pCodecCtx->width, pCodecCtx->height, 25 };
desktopChan->initVideo(vi);

while(av_read_frame(pFormatCtx, packet) >= 0)  //ffmpeg 取桌面数据
{
    avcodec_decode_video2();
    sws_scale()
    int size = pCodecCtx->width * pCodecCtx->height * 3 / 2;
    desktopChan->inputYUV((char**)(pFrameYUV->data), &size, 0);
}

在程序运行到H264Encoder::inputData() 中的 x264_encoder_encode() 这个函数时，会内存异常。是不是我实现的流程有问题？ 还是我哪个地没初始化 或 是我的YUV 传的有问题？

**Comment by xiongziliang** [comment]
我怀疑是长宽高设置不正确 或者不是split开的Y/U/V 三向量数组

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/65577971-78c1a580-dfa7-11e9-927b-23539c7180f8.png)

**Comment by FoxesChen** [comment]
调用 inputYUV中，传递size，我修改了下。
int y_size = pCodecCtx->width * pCodecCtx->height;
int size[3] = { y_size,y_size / 4,y_size / 4 };
desktopChan->inputYUV((char**)(pFrameYUV->data), size, 0);
这样修改后，还是会内存报错。

关于yuv 我创建的从AV_PIX_FMT_BGRA转AV_PIX_FMT_YUV420P 的 SwsContext。然后再通过sws_scale 去转成YUV的。

**Comment by FoxesChen** [comment]
我把转换后的YUV数据发你邮箱看下，只有一帧的。分辨率是3286*1080 ，每隔40MS采集一次。

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/65606917-441d1080-dfde-11e9-8d33-e29eee7e3cba.png)
你应该参考这个[文件](https://github.com/zlmediakit/ZLMediaKit/blob/master/tests/DeviceHK/DeviceHK.cpp)

**Comment by xiongziliang** [comment]
> 调用 inputYUV中，传递size，我修改了下。
> int y_size = pCodecCtx->width * pCodecCtx->height;
> int size[3] = { y_size,y_size / 4,y_size / 4 };
> desktopChan->inputYUV((char**)(pFrameYUV->data), size, 0);
> 这样修改后，还是会内存报错。
> 
> 关于yuv 我创建的从AV_PIX_FMT_BGRA转AV_PIX_FMT_YUV420P 的 SwsContext。然后再通过sws_scale 去转成YUV的。

对你的YuvLen参数应该是错的，正确的应该是 width/ 0.5*width /  0.5*width

**Comment by FoxesChen** [comment]
好的。我研究下。

**Comment by FoxesChen** [comment]
采集的YUV处理好了后，我是这样送给InputYUV的。pFrameYUV 是通过 sws_scale 转后的YUV。输出到文件后，再通过YUV工具查看，是正常的。

`
                      //输出到文件
                       int y_size = pCodec_ctx->width * pCodec_ctx->height;
			fwrite(pFrameYUV->data[0], 1, y_size, fp_yuv);		//Y 
			fwrite(pFrameYUV->data[1], 1, y_size / 4, fp_yuv);	//U
			fwrite(pFrameYUV->data[2], 1, y_size / 4, fp_yuv);	//V

                       char *yuv[3];
			int yuv_len[3];
			int totalSize = pFrameYUV->width * pFrameYUV->height;
			yuv_len[0] = totalSize;
			yuv_len[1] = totalSize / 4;
			yuv_len[2] = totalSize / 4;
			yuv[0] = (char*)pFrameYUV->data;
			yuv[1] = (char*)pFrameYUV->data[1];
			yuv[2] = (char*)pFrameYUV->data[2];

			desktopChan->inputYUV((char**)pFrameYUV->data, yuv_len, 0);  //内存报错。
`

**Comment by xiongziliang** [comment]
你看我粘贴的代码截图，yuv_len参数是linesize，根本不是数据长度，而是每行数据宽度。

**Comment by xiongziliang** [comment]
你要分析我的给你的代码 ，你也可以分析x264的api，网上参考下就能知道你自己错在哪里。

**Comment by FoxesChen** [comment]
哦，知道了。谢谢

**Comment by FoxesChen** [comment]
直接改成这样就可以了。
`
                       yuv_len[0] = pFrameYUV->linesize[0];
			yuv_len[1] = pFrameYUV->linesize[1];
			yuv_len[2] = pFrameYUV->linesize[2];
`

**Comment by FoxesChen** [comment]
关于创建MediaPusher，我参照demo了，但发现没推流。createPusher 在事件里面注册，并且在事件里面被调用了。

`

void createPusher(const EventPoller::Ptr &poller, const string &schema, const string &vhost, const string &app, const string &stream, const string &url) {
	pusher.reset(new MediaPusher(schema, vhost, app, stream, poller));
	pusher->setOnShutdown([poller, schema, vhost, app, stream, url](const SockException &ex) {});
	pusher->setOnPublished([poller, schema, vhost, app, stream, url](const SockException &ex) {});
	pusher->publish(url);
}

`
