### ISSUE TITLE
[技术咨询]zlm不响应HEAD请求

### ISSUE THREAD

**Issue by janver** [ZLMediaKit/ZLMediaKit#920]
zlm不响应HEAD请求，使用easyplayer.js 播放hls 出现CORS问题

HEAD /live/test1/hls.m3u8 HTTP/1.1
Host: hmbs.xxx.ml:8443
User-Agent: Mozilla/5.0 
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Origin: https://hmbs.xxx.ml
Connection: keep-alive
Referer: https://hmbs.xxx.ml/

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hmbs.xxx.ml:8443/live/test1/hls.m3u8. (Reason: CORS request did not succeed).

**Comment by xia-chu** [comment]
zlm支持HEAD命令的，有相关代码：
<img width="986" alt="图片" src="https://user-images.githubusercontent.com/11495632/123032932-765cdb80-d419-11eb-8b4a-ff11d269ae4e.png">
<img width="894" alt="图片" src="https://user-images.githubusercontent.com/11495632/123032993-92607d00-d419-11eb-8330-efe3d1fed7de.png">


你尝试更新zlm代码试试

**Comment by janver** [comment]
用 master 最新代码还是不行（win x64）
用postman测试
`HEAD https://hmbs.xxx.ml:8443/live/test1/hls.m3u8: {
  "Error": "socket hang up",
  "Request Headers": {
    "origin": "https://hmbs.xxx.ml",
    "user-agent": "PostmanRuntime/7.28.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "b4b3fa09-d3a7-4764-9609-2c60cb331cfa",
    "host": "hmbs.xxx.ml:8443",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  }
}`

用 GET 请求相同 url 可以返回数据

**Comment by xia-chu** [comment]
<img width="1031" alt="图片" src="https://user-images.githubusercontent.com/11495632/126584724-a8fcafa0-4bfe-47a7-9240-725b2b29feee.png">
<img width="940" alt="图片" src="https://user-images.githubusercontent.com/11495632/126584729-9879cca5-abc4-4bec-a7cc-c47ad5b59c3c.png">

**Comment by xia-chu** [comment]
此issue先关闭了 HEAD命令作用不大
