### ISSUE TITLE
[功能请求]

### ISSUE THREAD

**Issue by rsxieliang** [ZLMediaKit/ZLMediaKit#922]
请问可以支持gt1078协议的的推流吗？

**Comment by xia-chu** [comment]
这个其实我在zlmediakit中已经实现过了  不过这个是工作内容，不便开源，公司也商用这个特性了。如果要开源 ，只能再实现一遍，但是这样也难免利益冲突，所以短期内不会去实现1078的，除非收到这方面的pr

**Comment by hugangfeng333** [comment]
这个还好吧，信令实现，GB28181是RTP+PS，而1078应该是RTP+H264。

**Comment by xia-chu** [comment]
1078的rtp比较特殊。这个代码还是不便开源的，开源出去可能会损害公司的利益，引起不必要的争端
