### ISSUE TITLE
libflv第三方库[BUG]

### ISSUE THREAD

**Issue by wujianGit123** [ZLMediaKit/ZLMediaKit#923]
mpeg4_hevc_t结构体定义中，成员变量data是4KB固定大小内存，但是当帧数据大于4KB时(很常见)就会导致内存越界，这个问题是第三方的bug还是zlm使用不当？

**Comment by xia-chu** [comment]
这个可能是第三方库bug 不知道新版本有没有修复

**Comment by wujianGit123** [comment]
我在第三方库那边反馈这个问题，对方回复“hevc中的4K buffer只用来保存vps、sps、pps”，意思应该是4K的内存足够保存vps、sps、pps信息，不应该把其他帧数据也传进结构体内(MP4MuxerInterface::addTrack调用h265_annexbtomp4)

**Comment by wujianGit123** [comment]
这种可能是流本身有问题的情况，正常vps、sps、pps帧应该不会有那么大

**Comment by xia-chu** [comment]
zlm只会输入vps sps pps到h265_annexbtomp4函数的，不会输入其他帧
