### ISSUE TITLE
[技术咨询]H265 RTP推流正常，调用addFFmpegSource 无法转码

### ISSUE THREAD

**Issue by xlsky0713** [ZLMediaKit/ZLMediaKit#924]
- addFFmpegSource 功能接口

- H265 RTP推流正常，调用addFFmpegSource 无法转码

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

以下为rtp的记录的日志文件，请大神看看，感谢`

[gb_play_34020000001110020005_34020000001320020014.mp2.log](https://github.com/ZLMediaKit/ZLMediaKit/files/6686378/gb_play_34020000001110020005_34020000001320020014.mp2.log)
[gb_play_34020000001110020005_34020000001320020014.rtp.log](https://github.com/ZLMediaKit/ZLMediaKit/files/6686383/gb_play_34020000001110020005_34020000001320020014.rtp.log)
[gb_play_34020000001110020005_34020000001320020014.video.log](https://github.com/ZLMediaKit/ZLMediaKit/files/6686384/gb_play_34020000001110020005_34020000001320020014.video.log)

**Comment by xia-chu** [comment]
你是不是拉的rtmp流？由于rtmp原生不支持flv,所以FFmpeg官方版本不支持265的rtmp和flv，你可以用我定制的版本：https://gitee.com/xia-chu/FFmpeg.

或者你在addFFmpegSource用http-fmp4/rtsp等支持265的协议拉流并转码

**Comment by xlsky0713** [comment]
我是直接拉的RTSP流，海康的摄像头，是不是这个码流有问题？
下面是ffmpeg的日志
[ffmpeg.log](https://github.com/ZLMediaKit/ZLMediaKit/files/6690602/ffmpeg.log)

**Comment by xia-chu** [comment]
你在shell里面自己执行命令慢慢尝试啊，尝试成功了再修改FFmpeg命令模板啊

**Comment by xia-chu** [comment]
一般需要加上`-f flv `:
```bash
C:/ffmpeg/bin/ffmpeg -re -rtsp_transport tcp -i rtsp://127.0.0.1:40299/rtp/gb_play_34020000001110020005_34020000001320020014 -f flv -vcodec libx264 -vprofile baseline -acodec aac -ar 44100 -strict -2 -ac 1 -f flv -s 1280x720 -q 10 -preset ultrafast -y -max_muxing_queue_size 9999  -f flv rtmp://127.0.0.1:1935/proxy/gb_play_34020000001110020005_34020000001320020014
```

**Comment by xlsky0713** [comment]
好的，谢谢

**Comment by frankfif** [comment]
海康摄像头H265转码成H264之后，flv流和hls流播放都正常，但是无法播放webrtc流
如果摄像头推送H264码流，播放所有格式的流都正常
请大神帮忙看看。

**Comment by xia-chu** [comment]
webrtc不支持b帧，转码时请指定baseline profile
