### ISSUE TITLE
[技术咨询]ZLM推流咨询

### ISSUE THREAD

**Issue by QyqByte** [ZLMediaKit/ZLMediaKit#925]
**ZLM推流**

- 请问使用OBS推流到ZLM时，如何设置**服务器地址**和**串流秘钥**才能使它不会一直断开又重连？

**Comment by monktan89** [comment]
zlm不会主动断开，可以贴出相关日志

**Comment by QyqByte** [comment]
> zlm不会主动断开，可以贴出相关日志

在obs推流重连之后，我这边有观看ZLM的日志信息，发现ZLM未收到相关的响应，即无相关的日志，但是OBS也并未显示“无效的推流地址”错误信息，就一直在重连；
我这边设置的OBS服务器地址是：rtsp://127.0.0.1/live/
串流秘钥是：test
我怀疑是这两个内容设置错误导致的，因为我用ffmpeg将本地mp4向ZLM推流的时候是可以成功推流的

**Comment by QyqByte** [comment]
> zlm不会主动断开，可以贴出相关日志

在obs推流重连之后，我这边有观看ZLM的日志信息，发现ZLM未收到相关的响应，即无相关的日志，但是OBS也并未显示“无效的推流地址”错误信息，就一直在重连；
我这边设置的OBS服务器地址是：rtsp://127.0.0.1/live/
串流秘钥是：test
我怀疑是这两个内容设置错误导致的，因为我用ffmpeg将本地mp4向ZLM推流的时候是可以成功推流的

**Comment by Dw9** [comment]
> 我这边设置的OBS服务器地址是：rtsp://127.0.0.1/live/

url设置的不对 obs推的是rtmp的流
非要用rtsp的话 使用obs-rtspserver插件

**Comment by lmh135** [comment]
请问拉取保存rtsp传过来的AAC audio怎么操作呢？

**Comment by xia-chu** [comment]
> 请问拉取保存rtsp传过来的AAC audio怎么操作呢？

你可以看看c api, 里面有播放数据回调函数设置接口

**Comment by lmh135** [comment]
@xia-chu 您好，我是想从比如 rtsp://192.168.1.1/stream0 读取ACC音频保存到uint8[]里

**Comment by xia-chu** [comment]
是啊 mk_player_set_on_data支持的

**Comment by lmh135** [comment]
@xia-chu 您好，再请教一下，我用api_test_pusher从url_push（rtsp://127.0.0.1/live/rtsp_push）用vlc观看没有音频是什么情况呢，代码没做任何修改，感谢

**Comment by lmh135** [comment]
您好，再请教一下支持将音频AAC转换为MP3格式吗？
或者拉取保存rtsp传过来的MP3 audio，感谢
@xia-chu

**Comment by xia-chu** [comment]
不支持 zlm不包含非流媒体的转码相关功能

**Comment by lmh135** [comment]
您好，再请教一下，支持回放已经录制好的AAC音频文件吗，非常感谢  @xia-chu

**Comment by lmh135** [comment]
请教一下出现404 Not found是什么情况呢？ 
![image](https://user-images.githubusercontent.com/66903524/126284071-98604649-a096-463d-a0af-e6c189f358d6.png)

**Comment by xia-chu** [comment]
> 请教一下出现404 Not found是什么情况呢？
> ![image](https://user-images.githubusercontent.com/66903524/126284071-98604649-a096-463d-a0af-e6c189f358d6.png)
> ![image](https://user-images.githubusercontent.com/66903524/126286553-66fe5478-2604-43ec-a032-3ac2301da15a.png)
> 
> @xia-chu
> ![image](https://user-images.githubusercontent.com/66903524/126286346-51819519-b130-4582-b7bc-14b728748349.png)
> 这里播放失败了要怎么重启呢？

这个rtsp url无效啊，你可以vlc或ffplay播放先验证你的url是否有效。
