### ISSUE TITLE
局域网内，将IPC直接使用GB281818.Solution推流到ZLMediaKit，频繁出现rtp丢包

### ISSUE THREAD

**Issue by ladybirds1996** [ZLMediaKit/ZLMediaKit#926]
![image](https://user-images.githubusercontent.com/33885117/122949408-37457080-d3ae-11eb-8319-35e6488f885f.png)

**Comment by ladybirds1996** [comment]
![image](https://user-images.githubusercontent.com/33885117/122949717-783d8500-d3ae-11eb-87b5-26832386a2ff.png)
rtp配置如图

**Comment by chatop2020** [comment]
如果你使用.net 开发，建议使用AKStream
AKStream是一套.net core写的基于ZLMediaKit的流媒体治理框架，开源地址https://github.com/chatop2020/AKStream

**Comment by ladybirds1996** [comment]
> 如果你使用.net 开发，建议使用AKStream
> AKStream是一套.net core写的基于ZLMediaKit的流媒体治理框架，开源地址https://github.com/chatop2020/AKStream
请问如果是在Linux的环境下，是否使用ZLMediaKit更为合适

**Comment by xia-chu** [comment]
Linux下zlm性能最好，Windows下一班仅供小规模使用 或者测试开发

**Comment by xia-chu** [comment]
丢包问题你可以先尝试更新zlm源码至最新，如果还是丢包，那么修改系统配置文件，增加udp socket读缓冲。
或者改成tcp推流。

**Comment by chatop2020** [comment]
> > 如果你使用.net 开发，建议使用AKStream
> > AKStream是一套.net core写的基于ZLMediaKit的流媒体治理框架，开源地址https://github.com/chatop2020/AKStream
> 
> 请问如果是在Linux的环境下，是否使用ZLMediaKit更为合适

从流媒体来讲，我非常建议使用Linux来承载服务，AKStream才用.net core开发，在Linux,Mac,Windows下都可以正常运行，AKStream是ZLMediaKit的治理框架，有大量的工作AKStream已经完成，会大在节省你的开发时间。
同时AKStream还同时支持X86_x64和Arm架构的CPU，是全平台全架构的高效流媒体服务的解决方案。
