### ISSUE TITLE
[技术咨询] 使用webrtc功能崩溃

### ISSUE THREAD

**Issue by wanglijun19871230** [ZLMediaKit/ZLMediaKit#930]
**咨询的功能模块**
- WebRTC

**咨询的具体内容和问题**
- 您好，我在使用dev分支测试webrtc的功能，问题详情如下，烦请解答，谢谢
- 编译的操作系统是Windows，编译工具是Visio Studio 2017
- 所使用的的librtp是v2.3.0Release进行编译，编译时选择了ENABLE_OPENSSL
- 操作步骤：
- 1、使用postman调用addStreamProxy添加拉流代理，URL如下：
- 192.168.14.100:8083/index/api/addStreamProxy?secret=035c73f7-bb6b-4889-a715-d9eb2d1925cc&vhost=__defaultVhost__&app=live&stream=test&url= rtsp://admin:HK123456@192.168.14.104:554/Streaming/Channels/101
- 2、使用webrtc中的index.html进行测试，点击开始后，MedisServer崩溃，报错如下图：
- 
![image](https://user-images.githubusercontent.com/13374867/123295726-95a65680-d548-11eb-872b-ddde54659144.png)

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
您在编译srtp时是不是没开启openssl功能？
./configure --enable-openssl这样吧
