### ISSUE TITLE
[BUG]http-flv播放失败

### ISSUE THREAD

**Issue by l756302098** [ZLMediaKit/ZLMediaKit#931]
https://user-images.githubusercontent.com/16911007/123360569-1e041600-d5a0-11eb-9058-ea04bde94296.mp4

**bug现象**
- 在dev分支下，播放flv经常出错

**bug产生时的使用场景**
- 产生bug时，我正在使用webrtc和flv功能

**bug是否可以复现，怎么复现**
- 在dev分支下即可复现

**操作系统环境**
- ubuntu1804,64位
- intel i5

**Comment by l756302098** [comment]
更新后正常

**Comment by xia-chu** [comment]
这个应该是H264合帧逻辑有点bug
