### ISSUE TITLE
[技术咨询] 如何阻止恶意UDP推流

### ISSUE THREAD

**Issue by bravecat** [ZLMediaKit/ZLMediaKit#937]
**咨询的功能模块**
接收UDP推流

**咨询的具体内容和问题**
getMediaList接口返回流列表为空，抓包发现恶意的第三方持续向UDP端口x推流。当用openRtpServer接口指定local_port为x时，发现播放的是第三方的流。

请问如果阻止或不播放恶意第三方的流？

**Comment by xia-chu** [comment]
不可能吧 这么巧？对方怎么知道端口号？

**Comment by bravecat** [comment]
我的UDP端口范围50个，循环着用，而对方持续对其中一个端口推流。

**Comment by xia-chu** [comment]
你是openRtpServer开启的端口吗？ 你可以调整下50个端口的范围 做成随机的，让对方猜不到。
如果对方ip不怎么变 可以加黑名单。另外，可以在代码中做限制，限制ssrc和客户端ip，以第一个包的ssrc和ip为准，后面攻击的丢弃

**Comment by zhang2349** [comment]
是停止流程有问题 导致对方没停止发流  对方也没做rtcp 所以对方也不知道你关了   等下次你还是开了这个端口  就有两路流在发送了吧

**Comment by xia-chu** [comment]
> 是停止流程有问题 导致对方没停止发流 对方也没做rtcp 所以对方也不知道你关了 等下次你还是开了这个端口 就有两路流在发送了吧

我也猜是的。

**Comment by bravecat** [comment]
应该是的。我本来想通过on_publish中的媒体源ip和端口与信令中的匹配来阻止，但发现一个是外网一个是内网，肯定匹配不了。

**Comment by bravecat** [comment]
应该是的。我本来想通过on_publish中的媒体源ip和端口与信令中的匹配来阻止，但发现一个是外网一个是内网，肯定匹配不了。

**Comment by xia-chu** [comment]
issue 先关闭了
