### ISSUE TITLE
[BUG]PusherProxy代码文件编码无Bom导致在VS2019编译失败

### ISSUE THREAD

**Issue by linjiacheng** [ZLMediaKit/ZLMediaKit#942]
**bug现象**
- PusherProxy代码文件编码无Bom导致在VS2019编译失败

**bug产生时的使用场景**
- 使用CMake-GUI + VS2019编译失败

**bug是否可以复现，怎么复现**
- CMake-GUI，Configue，选VS2019，Generate，Open Project，生成解决方案

**zlm代码git commit hash值**
- 最新代码

**操作系统环境**
- Windows 64位
- CMake 3.20.5
- VS 2019

**Comment by xia-chu** [comment]
已经推送添加bom的代码



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: donkie ***@***.***&gt;
发送时间: 2021年6月28日 15:40
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]PusherProxy代码文件编码无Bom导致在VS2019编译失败 (#942)





 
bug现象
  
PusherProxy代码文件编码无Bom导致在VS2019编译失败 
 
bug产生时的使用场景
  
使用CMake-GUI + VS2019编译失败 
 
bug是否可以复现，怎么复现
  
CMake-GUI，Configue，选VS2019，Generate，Open Project，生成解决方案 
 
zlm代码git commit hash值
  
最新代码 
 
操作系统环境
  
Windows 64位 

CMake 3.20.5 

VS 2019

**Comment by linjiacheng** [comment]
编译成功
