### ISSUE TITLE
[BUG]海康摄像头推流花屏黑屏

### ISSUE THREAD

**Issue by jyLittleWolf** [ZLMediaKit/ZLMediaKit#943]
**bug现象**
- 局域网环境下 海康摄像头推流花屏 黑屏闪一下后重新播放
- 查看日志有黄色日志警告
![Snipaste_2021-06-28_15-58-34](https://user-images.githubusercontent.com/42572991/123603265-4a33c700-d82c-11eb-8c12-cc284b365264.png)

**bug产生时的使用场景**
- 视频推流

**操作系统环境**
- window系统下docker部署ZLMediaKit 使用镜像panjjo/zlmediakit
- 使用Java的wvp-GB28181-pro信令服务

**Comment by xia-chu** [comment]
这个是zlm收到业务系统无人观看主动关闭请求导致的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jyLittleWolf ***@***.***&gt;
发送时间: 2021年6月28日 16:18
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]海康摄像头推流花屏黑屏 (#943)





 
bug现象
  
局域网环境下 海康摄像头推流花屏 黑屏闪一下后重新播放 

查看日志有黄色日志警告
  
 
bug产生时的使用场景
  
视频推流 
 
操作系统环境
  
window系统下docker部署ZLMediaKit 使用镜像panjjo/zlmediakit 

使用Java的wvp-GB28181-pro信令服务

**Comment by jyLittleWolf** [comment]
意思是信令服务向zlm发送了无人观看主动关闭请求

**Comment by xia-chu** [comment]
对 wvp还是akstream?

**Comment by jyLittleWolf** [comment]
wvp

**Comment by xia-chu** [comment]
wvp应该有无人观看自动断流的开关 你看看怎么关闭。

**Comment by jyLittleWolf** [comment]
无人观看自动断流关闭后就不再花屏，流传输模式upd改为tcp后不再黑屏了

**Comment by jyLittleWolf** [comment]
无人观看自动断流关闭后就不再花屏，流传输模式upd改为tcp后不再黑屏了
