### ISSUE TITLE
[技术咨询] 未注册的流无法使用close_stream接口关闭

### ISSUE THREAD

**Issue by RogueCultivators** [ZLMediaKit/ZLMediaKit#946]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
推流代理

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述
由于源rtsp中断，导致代理流列表缺少此代理信息，无法进行关闭

![image](https://user-images.githubusercontent.com/49176713/123623320-dd2a2c80-d83f-11eb-8d69-0f47aa13481d.png)
![image](https://user-images.githubusercontent.com/49176713/123623346-e3b8a400-d83f-11eb-830d-5014fbf99426.png)

**Comment by RogueCultivators** [comment]
当rtsp流重新可播放时,代理列表中会出现之前的代理数据，当rtsp无法播放时，无法停止代理

**Comment by xia-chu** [comment]
拉流代理失败的流 只能通过delStreamProxy接口删除

**Comment by RogueCultivators** [comment]
好的，感谢


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月29日 11:38:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询] (#946)




 
拉流代理失败的流 只能通过delStreamProxy接口删除
