### ISSUE TITLE
[功能请求] 请问是否有计划支持GB28181接收中RTP流的丢包率统计

### ISSUE THREAD

**Issue by zengzhiying** [ZLMediaKit/ZLMediaKit#947]
**对接GB28181视频时网络环境不好或者对方平台有问题时可能会出现某些视频丢包，期望可以获得rtp丢包率的统计参数**

**不属于缺陷**

**比如可以在getRtpInfo时能够根据每个流的stream_id获得当前的丢包率，也可以通过其他api统计，主要是方便定位问题观察状态等。最后非常感谢这么好的开源项目和作者的付出。**

**Comment by xia-chu** [comment]
嗯 丢包率确实可以统计，目前也有这方面的代码，需要集成下，后面空加下。
另外，希望大家有能力的 都提点pr啊，这些完善性的功能，我实现没多少时间去实现啊。

**Comment by zengzhiying** [comment]
谢谢，刚接触到项目不久，正在读源码，有机会一定提pr，感谢~
