### ISSUE TITLE
[技术咨询]gb28181,在没有播放，摄像头的视频情况下，无法录制视频

### ISSUE THREAD

**Issue by zhangleiyifan** [ZLMediaKit/ZLMediaKit#948]
**咨询的功能模块**
- 请描述您想咨询zlmediakit的哪部分功能
record目录下的录制的视频，必须是有播放才能保存，要不然无法保存，尝试了streamNoneReaderDelayMS设置这个为-1，还是不行？请问是否有方法保存视频

**咨询的具体内容和问题**
- 此处展开您咨询内容的描述

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by xia-chu** [comment]
mp4还是hls录制？

**Comment by zhangleiyifan** [comment]
@xia-chu mp4的录制

**Comment by zhangleiyifan** [comment]
@xia-chu mp4的录制，我在wvp的前端界面播放的话，record目录里面是能生成mp4文件，当我关闭了wvp的播放界面，那么生成文件就停止了，这个已测试了多次

**Comment by xia-chu** [comment]
嗯 因为没人看触发了无人观看主动断流，就不会录制Mp4了，你把无人观看主动断流功能关闭吧

**Comment by zhangleiyifan** [comment]
@xia-chu 很奇怪的是，当我在wvp项目中，设置streamNoneReaderDelayMS这个参数为-1的时候，直接播放不了了

**Comment by zhangleiyifan** [comment]
![image](https://user-images.githubusercontent.com/13143253/123910779-83477500-d9ad-11eb-8daf-33647a18cd98.png)

**Comment by wujincheng2333** [comment]
调到无限大。。。调个24小时估计够用

**Comment by zhangleiyifan** [comment]
@wujincheng2333 不行的这个参数感觉不起作用，我这不看的话，立马就没有视频产生了

**Comment by wys1010** [comment]
> @xia-chu 很奇怪的是，当我在wvp项目中，设置streamNoneReaderDelayMS这个参数为-1的时候，直接播放不了了

我这边测试也是这样的情况，填-1直接播放不了，目前改成一天，正常
