### ISSUE TITLE
[技术咨询] webrtc相关文档咨询

### ISSUE THREAD

**Issue by sd7934555** [ZLMediaKit/ZLMediaKit#949]
**咨询的功能模块**
- webrtc

**咨询的具体内容和问题**
- 想看看webrtc推流转协议，以及webrtc拉流播放的文档

**注意事项**
- 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue

- 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

**Comment by wuhenfeike** [comment]
webrtc 推流，webrtc和rtmp播放延迟三秒左右，hls无法播放，请问大神遇到这种情况了么？

**Comment by xia-chu** [comment]
> **咨询的功能模块**
> 
>     * webrtc
> 
> 
> **咨询的具体内容和问题**
> 
>     * 想看看webrtc推流转协议，以及webrtc拉流播放的文档
> 
> 
> **注意事项**
> 
>     * 技术咨询前请先认真阅读readme, [wiki](https://github.com/xia-chu/ZLMediaKit/wiki),如有必要，您也可以同时搜索已经答复的issue，如果没找到答案才在此提issue
> 
>     * 技术咨询不属于bug缺陷，建议先star本项目，否则可能会降低答复优先级

wiki已经更新了webrtc的相关文档了 请查看

**Comment by xia-chu** [comment]
> webrtc 推流，webrtc和rtmp播放延迟三秒左右，hls无法播放，请问大神遇到这种情况了么？

@wuhenfeike 我们在#959讨论
