### ISSUE TITLE
Video Source 4K

### ISSUE THREAD

**Issue by nokiovo79** [zlmediakit/ZLMediaKit#95]
Hi friend,
I have a problem with video source in 4K.
I use test_mp4. There are many artificial image. Do you have any idea ?

**Comment by xiongziliang** [comment]
Do you mean to use `test_pusherMp4` to push mp4 files?
Are you pushing to ZLMediaKit or other servers with `rtmp` or `rtsp`?
Can you share your 4K mp4 file? 
Thanks!

**Comment by nokiovo79** [comment]
http://downloads.4ksamples.com/videos/Honey%20Bees%2096fps%20In%204K%20(ULTRA%20HD)(4ksamples.com).
It’s a 4K video at 24fps and not 96fps as title.

I tried with mp4 pusher and with ffmpeg as pusher. But I have the same problem.
Instead between VLC stream(as server) and with ffplay is ok.

**Comment by xiongziliang** [comment]
Do you push this file(the 4K mp4 file) to ZLMediaKit by rtmp?

**Comment by nokiovo79** [comment]
No.... ever in rtsp

**Comment by xiongziliang** [comment]
I have push the 4K mp4 file to `ZLMediaKit` by `test_pusherMp4` with rtsp,and  i played it by ffplay,it is ok :
![image](https://user-images.githubusercontent.com/11495632/65674641-86e2f500-e07f-11e9-8c16-da934ee4ae94.png)

**Comment by xiongziliang** [comment]
I played the url like this `ffplay rtsp://127.0.0.1/live/rtsp_push -rtsp_transport tcp`

**Comment by xiongziliang** [comment]
You can push rtsp with ffmpeg like this:
```
ffmpeg -re -i  /path/to/4k.mp4   -rtsp_transport tcp -vcodec copy -acodec copy -f rtsp rtsp://somedomain.com/live/test
```

**Comment by xiongziliang** [comment]
`-rtsp_transport tcp` is very important

**Comment by nokiovo79** [comment]
Thank you very much.... great

**Comment by xiongziliang** [comment]
Have you solved your problem yet?

**Comment by nokiovo79** [comment]
Yes...
