### ISSUE TITLE
给录像文件名加上时长的建议

### ISSUE THREAD

**Issue by bravecat** [ZLMediaKit/ZLMediaKit#950]
https://github.com/ZLMediaKit/ZLMediaKit/blob/4ec311652afced781ecfc968585c618ab8cb3ebb/src/Record/MP4Recorder.cpp#L95

改为：
```c++
auto strFileWithLen = strFile.substr(0, strFile.length() - 4) + "_" +  std::to_string((int) info.time_len) + ".mp4";
rename(strFileTmp.data(),strFileWithLen.data());
```

这样可以通过文件名解析出录像起止时间，方便后续业务处理。

**Comment by xia-chu** [comment]
文件名其实一点用处都没 因为文件系统是最低效的文件管理方式 要组织查找这些录像 还是需要数据库开实现的 所以 开发者还是需要自行对接hook的 这些mp4录制文件和元数据需要开发者自己处理和保存。

**Comment by bravecat** [comment]
文件名加上时长不是代替数据库管理，对于程序外的第三方（比如下载部分文件用户），文件名只有开始时间总感觉少了什么。
