### ISSUE TITLE
自己插入帧时MediaSource.h文件 PacketCache类中inputPacket方法里—cache值会变成空是为什么[BUG]

### ISSUE THREAD

**Issue by lixinhan2019** [ZLMediaKit/ZLMediaKit#951]
**bug现象**
- bug产生时服务器的异常行为(例如: 崩溃/无法访问/丢包花屏)
- bug产生时，打印的上下文日志(可以截图或粘贴文本)
- 调试core文件时，崩溃触发点的函数调用栈(可以截图或粘贴文本)

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的什么功能模块？
- 我是将zlm,rtmpsession模块收流之后,对没一帧进行换脸,然后再把流推出去

**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤
- 因为加了很多其他模块代码无法一并提交,但是在本地可以复现

**zlm代码git commit hash值**
- git log查看

**操作系统环境**
- ubuntu20
- inter i7

自己插入帧时MediaSource.h文件 PacketCache类中inputPacket方法里—cache值会变成空是为什么

void inputPacket(uint64_t stamp, bool is_video, std::shared_ptr<packet> pkt, bool key_pos) {
        if(!_cache){
            InfoL << "_cache:值为空" << "  stamp:" << stamp
                    << "  is_video:" << is_video
                    << "  pkt_size:" << sizeof(pkt)
                    << "  key_pos:" << key_pos;
            return;
        }
        if (_policy.isFlushAble(is_video, key_pos, stamp, _cache->size())) {
            flushAll();
        }

        _cache->emplace_back(std::move(pkt));
        if (key_pos) {
            _key_pos = key_pos;
        }
    }
	_cache这个值经常会变成空,同时伴随想象是视频跳帧,您能给点意见吗?

2021-06-30 19:23:29.611 I FaceTransplant[15083-140206138386176] MediaSource.h:331 inputPacket | _cache:值为空  stamp:18581  is_video:0  pkt_size:16  key_pos:0
2021-06-30 19:23:36.825 I FaceTransplant[15083-140206138386176] MediaSource.h:331 inputPacket | _cache:值为空  stamp:39317  is_video:0  pkt_size:16  key_pos:0

**Comment by xia-chu** [comment]
你处理的方式和地方不对的 你应该在MultiMediaSourceMuxer里面拦截Track与Frame，进行处理和替换。之前我做过视频实时超分的项目 就是这么做的

**Comment by lixinhan2019** [comment]
好的,谢谢
