### ISSUE TITLE
[BUG] mpegTs流没办法解析出关键帧

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#954]
**bug现象**
我有一段h264+aac编码的mpegsTs流, 网上找的视频, 在测试的时候发现一直出现如下的信息
emitAllTrackReady | track not ready for a long time, ignored: H264

我很奇怪, 然后跟踪调试发现:

`
H264_TYPE(frame->data()[frame->prefixSize()]) 

`
音频解码是正常的, 而视频解码到这里所有的输出都是6, 也就是都是SEI, 没有其他编解码信息.
但是这视频使用vlc与ffmpeg都是直接可以播放的, 只是提示丢失pps信息.
现在请问大神, 这类情况应该怎么解决?

每帧的包头基本上都是 00 00 00 01 06 01
按照h264的格式, 都是06....
可是使用vlc却可以
h264 debug: found NAL_SPS (sps_id=0)
h264 debug: found NAL_PPS (pps_id=0 sps_id=0)

**bug产生时的使用场景**
通过Api拉流时候产生的
**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤
视频文件我发送给您信箱

**zlm代码git commit hash值**
cd7af6fa4e7e927e0681dba514b6c1a678d19a66

**操作系统环境**
ubuntu 18.04 x64

**Comment by monktan89** [comment]
可以截取一段文件发出来

**Comment by monktan89** [comment]
或者rtpdump一下把dump文件发出来

**Comment by alexliyu7352** [comment]
实际上这是一个ts文件, 但是不能上传ts文件, 请下载改名成ts

https://user-images.githubusercontent.com/24582085/124179292-38c91400-dae5-11eb-853d-29adf7e64791.mp4

**Comment by alexliyu7352** [comment]
大概找到问题了, 在您的代码中和ireader大佬的代码中处理h264解的时候区别是, 您

`

       size_t prefixSize(const char *ptr, size_t len){
                if (len < 4) {
                    return 0;
                }
                if (ptr[0] != 0x00 || ptr[1] != 0x00) {
                    //不是0x00 00开头
                    return 0;
                }
            
                if (ptr[2] == 0x00 && ptr[3] == 0x01) {
                    //是0x00 00 00 01
                    return 4;
                }
            
                if (ptr[2] == 0x01) {
                    //是0x00 00 01
                    return 3;
                }
                return 0;
            }

`

您这里直接判断这一帧的头是0x00 00 00 01就返回4.这就是只是处理了第一个NAL单元.
而在本测试视频中, H264_TYPE(frame->data()[frame->prefixSize()])始终是返回6, 那么在后续的逻辑中这个帧直接会被丢弃.

而ireader大佬这里处理的代码是

`

          static inline const uint8_t* h264_startcode(const uint8_t *data, size_t bytes)
              {
                  size_t i;
                  for(i = 2; i + 1 < bytes; i++)
                  {
                      if(0x01 == data[i] && 0x00 == data[i-1] && 0x00 == data[i-2])
                          return data + i + 1;
                  }
          
                  return NULL;
              }
              void h264_stream(const Frame::Ptr &frame)
              {
                  ptrdiff_t n;
                  const unsigned char* p, *next, *end;
          
                  end = (const unsigned char*)frame->data() + frame->size();
                  p = h264_startcode((const unsigned char*)frame->data(), frame->size());
          
                  while (p)
                  {
                      next = h264_startcode(p, end - p);
                      if (next)
                      {
                          n = next - p - 3;
                      }
                      else
                      {
                          n = end - p;
                      }
          
                      while (n > 0 && 0 == p[n - 1]) n--; // filter tailing zero
          
                      assert(n > 0);
                      if (n > 0)
                      {
                          handler(param, p, (size_t)n);
                          WarnL << H264_TYPE(p[0]);
                      }
          
                      p = next;
                  }
              }



`

他这里进行了一个循环, 应该是切分出来每个NAL单元, 然后通过handler在交于上层进行处理.

我简单的修改了一下代码, 有两个实现方式:
1. prefixSize计算时候进行一次循环并判断h264_type, 就是类似如上的代码, 如果这个帧内包含如果是有非SEI, AUD的type, 那么就以这个type的offset返回, 比如这个测试视频, 算出来为15的时候, 就是正常了.
2. 就是在shouldDrop这里修改逻辑, 还是遍历寻找是否有多个NAL单元, 如果找不到那么就按照shouldDrop的逻辑走, 如果找到,那么就修改frame的data的offset

但是总觉得这两种方案实现都有些问题, 请教大神如何修改比较好?

**Comment by alexliyu7352** [comment]
`

      auto frame = std::make_shared<H264FrameNoCacheAble>((char *) data, bytes, (uint32_t)dts, (uint32_t)pts, prefixSize((char *) data, bytes));
                  _merger.inputFrame(frame,[this](uint32_t dts, uint32_t pts, const Buffer::Ptr &buffer, bool) {
                      onFrame(std::make_shared<FrameWrapper<H264FrameNoCacheAble> >(buffer, dts, pts, prefixSize(buffer->data(), buffer->size()), 0));
                  });

`
或者说在这里进行一次处理?把当前的直接一帧, 拆分成多帧?

**Comment by xia-chu** [comment]
> 实际上这是一个ts文件, 但是不能上传ts文件, 请下载改名成ts
> 3.mp4

建议你把dump出的rtp传上来 zip格式就行 ts的没法直接处理

**Comment by xia-chu** [comment]
可能在spilt帧的逻辑有点问题 还要你先提交rtp文件测试才行

**Comment by alexliyu7352** [comment]
我这是http-ts流, 请问下大神怎么dump成rtp呢?我一旦用ffmpeg转成rtp....ffmpeg会重新封装, 这时候就正常了,没有粘帧的问题了.


抱歉, 对大神的代码之前研究还不彻底, 以为您的代码中没有处理多个NAL粘一起的问题, 实际上您有这个代码.
按照您当前的逻辑, 
auto frame = std::make_shared<H264FrameNoCacheAble>((char *) data, bytes, (uint32_t)dts, (uint32_t)pts, 
prefixSize((char *) data, bytes));
int type = H264_TYPE(*((uint8_t *) frame->data() + frame->prefixSize()));
这里的type始终为6, 因此在接下去的
 _merger.inputFrame(frame,[this](uint32_t dts, uint32_t pts, const Buffer::Ptr &buffer, bool) {
                    onFrame(std::make_shared<FrameWrapper<H264FrameNoCacheAble> >(buffer, dts, pts, prefixSize(buffer->data(), buffer->size()), 0));
                });

onFrame始终不会触发, 因为直接在shouldDrop中丢掉了这个帧.您有spilt帧的逻辑, 但是是在onFrame执行后调用
void H264Track::inputFrame(const Frame::Ptr &frame)来实现的, 这段代码没问题.
但是现在的问题就是, 首先多个帧粘合在一起了, 但是在第一步就直接在shouldDrop丢掉了, 没有进行spilt帧.

所以, 我的想法就是直接先处理粘帧的问题, 然后在进行您的帧合并, 不知道是否这样会导致其他问题?我这测试到是可以了.
但是这样效率会是问题, 因为在onFrame后续处理时候void H264Track::inputFrame(const Frame::Ptr &frame)这里仍旧会调用一次splitH264.

`

      auto frame = std::make_shared<H264FrameNoCacheAble>((char *) data, bytes, (uint32_t)dts, (uint32_t)pts, prefixSize((char *) data, bytes));
                  int type = H264_TYPE(*((uint8_t *) frame->data() + frame->prefixSize()));
                  if (type != H264Frame::NAL_B_P && type != H264Frame::NAL_IDR) {
                      //非I/B/P帧情况下，split一下，防止多个帧粘合在一起
                      splitH264(frame->data(), frame->size(), frame->prefixSize(), [&](const char *ptr, size_t len, size_t prefix) {
      //                    auto sub_frame = std::make_shared<H264FrameNoCacheAble>((char *) ptr, len, (uint32_t)dts, (uint32_t)pts, prefix);
                          H264FrameInternal::Ptr sub_frame = std::make_shared<H264FrameInternal>(frame, (char *) ptr, len, prefix);
                          _merger.inputFrame(sub_frame,[this](uint32_t dts, uint32_t pts, const Buffer::Ptr &buffer, bool) {
                              onFrame(std::make_shared<FrameWrapper<H264FrameNoCacheAble> >(buffer, dts, pts, prefixSize(buffer->data(), buffer->size()), 0));
                          });
                      });
                  } else {
                      _merger.inputFrame(frame,[this](uint32_t dts, uint32_t pts, const Buffer::Ptr &buffer, bool) {
                          onFrame(std::make_shared<FrameWrapper<H264FrameNoCacheAble> >(buffer, dts, pts, prefixSize(buffer->data(), buffer->size()), 0));
                      });
                  }


`

**Comment by alexliyu7352** [comment]
我创建了一个可以拉http-mpegts流的补丁. 能否直接架设一个http服务把这个ts文件放进去.
然后用我这个补丁直接拉ts流测试?

`
        
        Index: src/Http/TsPlayer.cpp
        IDEA additional info:
        Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
        <+>UTF-8
        ===================================================================
        diff --git a/src/Http/TsPlayer.cpp b/src/Http/TsPlayer.cpp
        new file mode 100644
        --- /dev/null	(date 1625214873885)
        +++ b/src/Http/TsPlayer.cpp	(date 1625214873885)
        @@ -0,0 +1,246 @@
        +//
        +// Created by alex on 2021/4/6.
        +//
        +
        +#include "TsPlayer.h"
        +
        +namespace mediakit {
        +
        +    TsPlayer::TsPlayer(const EventPoller::Ptr &poller) {
        +        _segment.setOnSegment([this](const char *data, size_t len) { onPacket(data, len); });
        +        setPoller(poller ? poller : EventPollerPool::Instance().getPoller());
        +    }
        +
        +    TsPlayer::~TsPlayer() {}
        +
        +    void TsPlayer::play(const string &strUrl) {
        +        _ts_url.append(strUrl);
        +        playTs();
        +    }
        +
        +    void TsPlayer::teardown_l(const SockException &ex) {
        +        _timer.reset();
        +        shutdown(ex);
        +    }
        +
        +    void TsPlayer::teardown() {
        +        teardown_l(SockException(Err_shutdown, "teardown"));
        +    }
        +
        +    void TsPlayer::playTs(bool force) {
        +        if (!force && alive()) {
        +            //播放器目前还存活，正在下载中
        +            return;
        +        }
        +        setOnCreateSocket([this](const EventPoller::Ptr &poller) {
        +            return Socket::createSocket(poller, true);
        +        });
        +        if (!(*this)[kNetAdapter].empty()) {
        +            setNetAdapter((*this)[kNetAdapter]);
        +        }
        +//        _timer.reset(new Timer(playTimeOutSec, [weakSelf]() {
        +//            auto strongSelf = weakSelf.lock();
        +//            if (!strongSelf) {
        +//                return false;
        +//            }
        +//            strongSelf->onPlayResult(SockException(Err_timeout, "play http ts timeout"));
        +//            return false;
        +//        }, getPoller()));
        +        if (force) {
        +            HttpClient::clear();
        +        }
        +        setMethod("GET");
        +        sendRequest(_ts_url, 600, 60);
        +    }
        +
        +    void TsPlayer::onPacket(const char *data, size_t len) {
        +        _segment.input(data, len);
        +    }
        +
        +    ssize_t TsPlayer::onResponseHeader(const string &status, const HttpClient::HttpHeader &headers) {
        +        _status = status;
        +        if (status != "200" && status != "206") {
        +            //http状态码不符合预期
        +            shutdown(SockException(Err_other, StrPrinter << "bad http status code:" + status));
        +            return 0;
        +        }
        +        auto content_type = const_cast< HttpClient::HttpHeader &>(headers)["Content-Type"];
        +        if (content_type.find("video/mp2t") == 0 || content_type.find("video/mpeg") == 0) {
        +            _is_ts_content = true;
        +        }
        +        if (_first) {
        +            _first = false;
        +            onPlayResult(SockException(Err_success, "play success"));
        +        } else {
        +            onPlayResult(SockException(Err_eof, "play reconnect"));
        +        }
        +        //后续是不定长content
        +        return -1;
        +    }
        +
        +    void TsPlayer::onResponseBody(const char *buf, size_t size, size_t recvedSize, size_t totalSize) {
        +        if (_status != "200" && _status != "206") {
        +            return;
        +        }
        +        if (recvedSize == size) {
        +            //开始接收数据
        +            if (buf[0] == TS_SYNC_BYTE) {
        +                //这是ts头
        +                _is_first_packet_ts = true;
        +            } else {
        +                WarnL << "可能不是http-ts流";
        +            }
        +        }
        +        TsPlayer::onPacket(buf, size);
        +    }
        +
        +    void TsPlayer::onResponseCompleted() {
        +        //接收完毕
        +        teardown_l(SockException(Err_success, "play completed"));
        +    }
        +
        +    void TsPlayer::onDisconnect(const SockException &ex) {
        +        if (_first) {
        +            //第一次失败，则播放失败
        +            _first = false;
        +            onPlayResult(ex);
        +            return;
        +        }
        +        if (ex.getErrCode() == Err_shutdown) {
        +            //主动shutdown的，不触发回调
        +            onShutdown(ex);
        +        } else {
        +            weak_ptr<TsPlayer> weakSelf = dynamic_pointer_cast<TsPlayer>(shared_from_this());
        +            getPoller()->async([weakSelf]() {
        +                auto strongSelf = weakSelf.lock();
        +                if (strongSelf) {
        +                    strongSelf->playTs(true);
        +                }
        +            }, false);
        +        }
        +        WarnL << ex.getErrCode() << " " << ex.what();
        +    }
        +
        +    bool TsPlayer::onRedirectUrl(const string &url, bool temporary) {
        +        return HttpClient::onRedirectUrl(url, temporary);
        +    }
        +
        +
        +//////////////////////////////////////////////////////////////////////////
        +
        +    TsPlayerImp::TsPlayerImp(const EventPoller::Ptr &poller) : PlayerImp<TsPlayer, PlayerBase>(poller) {
        +
        +    }
        +    void TsPlayerImp::onPacket(const char *data, size_t len) {
        +        if (!_decoder) {
        +            _decoder = DecoderImp::createDecoder(DecoderImp::decoder_ts, this);
        +        }
        +
        +        if (_decoder) {
        +            _decoder->input((uint8_t *) data, len);
        +        }
        +    }
        +
        +    void TsPlayerImp::onAllTrackReady() {
        +        PlayerImp<TsPlayer, PlayerBase>::onPlayResult(SockException(Err_success, "play hls success"));
        +    }
        +
        +    void TsPlayerImp::onPlayResult(const SockException &ex) {
        +        if (ex) {
        +            if (ex.getErrCode() == Err_eof) {
        +                reConnect();
        +            } else {
        +                PlayerImp<TsPlayer, PlayerBase>::onPlayResult(ex);
        +            }
        +        } else {
        +            _frame_cache.clear();
        +            _stamp[TrackAudio].setRelativeStamp(0);
        +            _stamp[TrackVideo].setRelativeStamp(0);
        +            _stamp[TrackAudio].syncTo(_stamp[TrackVideo]);
        +            setPlayPosition(0);
        +            weak_ptr<TsPlayerImp> weakSelf = dynamic_pointer_cast<TsPlayerImp>(shared_from_this());
        +            //每50毫秒执行一次
        +            _timer = std::make_shared<Timer>(0.05f, [weakSelf]() {
        +                auto strongSelf = weakSelf.lock();
        +                if (!strongSelf) {
        +                    return false;
        +                }
        +                strongSelf->onTick();
        +                return true;
        +            }, getPoller());
        +        }
        +    }
        +
        +    void TsPlayerImp::onShutdown(const SockException &ex) {
        +        PlayerImp<TsPlayer, PlayerBase>::onShutdown(ex);
        +        _timer = nullptr;
        +    }
        +
        +    vector<Track::Ptr> TsPlayerImp::getTracks(bool trackReady) const {
        +        return MediaSink::getTracks(trackReady);
        +    }
        +
        +    void TsPlayerImp::reConnect() {
        +        isReconnect = true;
        +    }
        +
        +    void TsPlayerImp::inputFrame(const Frame::Ptr &frame) {
        +        //计算相对时间戳
        +        int64_t dts, pts;
        +//        WarnL << "当前dts/pts[" << frame->dts() << "/" << frame->pts() << "] 最后dts[" << last_dts << "]";
        +        // 放弃掉小于缓存中最后一个帧dts的其他帧
        +        if (last_dts >= frame->dts() && isReconnect) {
        +            return;
        +        }
        +        last_dts = frame->dts();
        +        isReconnect = false;
        +        _stamp[frame->getTrackType()].revise(frame->dts(), frame->pts(), dts, pts);
        +        //根据时间戳缓存frame
        +        _frame_cache.emplace(dts, Frame::getCacheAbleFrame(frame));
        +
        +//        WarnL << "缓存时间[" << getBufferMS() << "]";
        +        if (getBufferMS() > 30 * 1000) {
        +            //缓存超过30秒，强制消费至15秒(减少延时或内存占用)
        +            while (getBufferMS() > 15 * 1000) {
        +                MediaSink::inputFrame(_frame_cache.begin()->second);
        +                _frame_cache.erase(_frame_cache.begin());
        +            }
        +            //接着播放缓存中最早的帧
        +            setPlayPosition(_frame_cache.begin()->first);
        +        }
        +    }
        +
        +    int64_t TsPlayerImp::getPlayPosition() {
        +        return _ticker.elapsedTime() + _ticker_offset;
        +    }
        +
        +    int64_t TsPlayerImp::getBufferMS() {
        +        if (_frame_cache.empty()) {
        +            return 0;
        +        }
        +        return _frame_cache.rbegin()->first - _frame_cache.begin()->first;
        +    }
        +
        +    void TsPlayerImp::setPlayPosition(int64_t pos) {
        +        _ticker.resetTime();
        +        _ticker_offset = pos;
        +    }
        +
        +    void TsPlayerImp::onTick() {
        +        auto it = _frame_cache.begin();
        +        while (it != _frame_cache.end()) {
        +            if (it->first > getPlayPosition()) {
        +                //这些帧还未到时间播放
        +                break;
        +            }
        +            if (getBufferMS() < 3 * 1000) {
        +                //缓存小于3秒,那么降低定时器消费速度(让剩余的数据在3秒后消费完毕)
        +                //目的是为了防止定时器长时间干等后，数据瞬间消费完毕
        +                setPlayPosition(_frame_cache.begin()->first);
        +            }
        +            //消费掉已经到期的帧
        +            MediaSink::inputFrame(it->second);
        +            it = _frame_cache.erase(it);
        +        }
        +    }
        +}//namespace mediakit
        \ No newline at end of file
        Index: src/Http/TsPlayer.h
        IDEA additional info:
        Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
        <+>UTF-8
        ===================================================================
        diff --git a/src/Http/TsPlayer.h b/src/Http/TsPlayer.h
        new file mode 100644
        --- /dev/null	(date 1625134378397)
        +++ b/src/Http/TsPlayer.h	(date 1625134378397)
        @@ -0,0 +1,151 @@
        +//
        +// Created by alex on 2021/4/6.
        +//
        +
        +/*
        + * Copyright (c) 2020 The ZLMediaKit project authors. All Rights Reserved.
        + *
        + * This file is part of ZLMediaKit(https://github.com/xia-chu/ZLMediaKit).
        + *
        + * Use of this source code is governed by MIT license that can be found in the
        + * LICENSE file in the root of the source tree. All contributing project authors
        + * may be found in the AUTHORS file in the root of the source tree.
        + */
        +
        +#ifndef HTTP_TSPLAYER_H
        +#define HTTP_TSPLAYER_H
        +
        +#include <unordered_set>
        +#include "Util/util.h"
        +#include "Poller/Timer.h"
        +#include "Http/HttpDownloader.h"
        +#include "Player/MediaPlayer.h"
        +#include "HlsParser.h"
        +#include "HttpTSPlayer.h"
        +#include "Rtp/Decoder.h"
        +#include "Rtp/TSDecoder.h"
        +
        +using namespace toolkit;
        +namespace mediakit {
        +
        +    class TsPlayer : public  HttpClientImp , public PlayerBase {
        +    public:
        +        TsPlayer(const EventPoller::Ptr &poller);
        +        ~TsPlayer() override;
        +
        +        /**
        +         * 开始播放
        +         * @param strUrl
        +         */
        +        void play(const string &strUrl) override;
        +
        +        /**
        +         * 停止播放
        +         */
        +        void teardown() override;
        +
        +    protected:
        +        /**
        +         * 收到ts包
        +         * @param data ts数据负载
        +         * @param len ts包长度
        +         */
        +        virtual void onPacket(const char *data, size_t len) = 0;
        +
        +    private:
        +        /**
        +         * 收到http回复头
        +         * @param status 状态码，譬如:200 OK
        +         * @param headers http头
        +         * @return 返回后续content的长度；-1:后续数据全是content；>=0:固定长度content
        +         *          需要指出的是，在http头中带有Content-Length字段时，该返回值无效
        +         */
        +        ssize_t onResponseHeader(const string &status,const HttpHeader &headers) override;
        +        /**
        +         * 收到http conten数据
        +         * @param buf 数据指针
        +         * @param size 数据大小
        +         * @param recvedSize 已收数据大小(包含本次数据大小),当其等于totalSize时将触发onResponseCompleted回调
        +         * @param totalSize 总数据大小
        +         */
        +        void onResponseBody(const char *buf,size_t size,size_t recvedSize, size_t totalSize) override;
        +
        +        /**
        +         * 接收http回复完毕,
        +         */
        +        void onResponseCompleted() override;
        +
        +        /**
        +         * http链接断开回调
        +         * @param ex 断开原因
        +         */
        +        void onDisconnect(const SockException &ex) override;
        +
        +        /**
        +         * 重定向事件
        +         * @param url 重定向url
        +         * @param temporary 是否为临时重定向
        +         * @return 是否继续
        +         */
        +        bool onRedirectUrl(const string &url,bool temporary) override;
        +
        +    private:
        +        void playTs(bool force = false);
        +        void teardown_l(const SockException &ex);
        +
        +    private:
        +        struct UrlComp {
        +            //url忽略？后面的参数
        +            bool operator()(const string& __x, const string& __y) const {
        +                return split(__x,"?")[0] < split(__y,"?")[0];
        +            }
        +        };
        +
        +    private:
        +        bool _first = true;
        +        string _ts_url;
        +        int64_t _last_sequence = -1;
        +        Timer::Ptr _timer;
        +        TSSegment _segment;
        +        //是否为mpegts负载
        +        bool _is_ts_content = false;
        +        //第一个包是否为ts包
        +        bool _is_first_packet_ts = false;
        +        //是否判断是否是ts并split
        +        bool _split_ts;
        +        string _status;
        +    };
        +
        +    class TsPlayerImp : public PlayerImp<TsPlayer, PlayerBase> , public MediaSink{
        +    public:
        +        typedef std::shared_ptr<TsPlayerImp> Ptr;
        +        TsPlayerImp(const EventPoller::Ptr &poller = nullptr);
        +        ~TsPlayerImp() override {};
        +        virtual void reConnect();
        +
        +    private:
        +        void onPacket(const char *data, size_t len) override;
        +        void onAllTrackReady() override;
        +        void onPlayResult(const SockException &ex) override;
        +        vector<Track::Ptr> getTracks(bool trackReady = true) const override;
        +        void inputFrame(const Frame::Ptr &frame) override;
        +        void onShutdown(const SockException &ex) override;
        +        void onTick();
        +
        +        int64_t getPlayPosition();
        +        void setPlayPosition(int64_t pos);
        +        int64_t getBufferMS();
        +
        +    private:
        +        int64_t _ticker_offset = 0;
        +        int64_t last_dts = -1;
        +        bool isReconnect = false;
        +        Ticker _ticker;
        +        Stamp _stamp[2];
        +        Timer::Ptr _timer;
        +        DecoderImp::Ptr _decoder;
        +        multimap<int64_t, Frame::Ptr> _frame_cache;
        +    };
        +
        +}//namespace mediakit
        +#endif //HTTP_TSPLAYER_H
        Index: src/Player/PlayerBase.cpp
        IDEA additional info:
        Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
        <+>UTF-8
        ===================================================================
        diff --git a/src/Player/PlayerBase.cpp b/src/Player/PlayerBase.cpp
        --- a/src/Player/PlayerBase.cpp	(revision cd7af6fa4e7e927e0681dba514b6c1a678d19a66)
        +++ b/src/Player/PlayerBase.cpp	(date 1624853292754)
        @@ -13,6 +13,7 @@
         #include "Rtsp/RtspPlayerImp.h"
         #include "Rtmp/RtmpPlayerImp.h"
         #include "Http/HlsPlayer.h"
        +#include "Http/TsPlayer.h"
         using namespace toolkit;
         
         namespace mediakit {
        @@ -48,10 +49,12 @@
                 return PlayerBase::Ptr(new RtmpPlayerImp(poller),releasePlayer);
             }
         
        -    if ((strcasecmp("http",prefix.data()) == 0 || strcasecmp("https",prefix.data()) == 0) && end_with(url, ".m3u8")) {
        +    if ((strcasecmp("http",prefix.data()) == 0 || strcasecmp("https",prefix.data()) == 0) && (end_with(url, ".m3u8") || end_with(url_in, ".m3u8"))) {
                 return PlayerBase::Ptr(new HlsPlayerImp(poller),releasePlayer);
             }
        -
        +    if ((strcasecmp("http",prefix.data()) == 0 || strcasecmp("https",prefix.data()) == 0) && (end_with(url, ".ts") || end_with(url_in, ".ts"))) {
        +        return PlayerBase::Ptr(new TsPlayerImp(poller),releasePlayer);
        +    }
             return PlayerBase::Ptr(new RtspPlayerImp(poller),releasePlayer);
         }
         



`

**Comment by alexliyu7352** [comment]
问题已经解决, 感谢大神的辛苦劳动!
