### ISSUE TITLE
Assertion failed: (!origin.empty()) ？移动端使用webrtc请求index/api/webrtc?app=live&stream=test&type=play

### ISSUE THREAD

**Issue by ChokWah** [ZLMediaKit/ZLMediaKit#956]
移动端iOS使用webrtc请求index/api/webrtc?app=live&stream=test&type=play

提示：
   "code" : -400,
   "msg" : "Assertion failed: (!origin.empty()), function checkValid, file /home/qiujian1/ZLMediaKit/webrtc/Sdp.cpp, line 1328."

当初怀疑是这个bug ： [https://github.com/ZLMediaKit/ZLMediaKit/issues/911](url)

但是使用https://xxxxxxxxxx/webrtc/index_push.html网页可以成功播放，推流。

为何在iOS端不成功？是我创建的SDP有问题吗？

```bash
v=0

o=- 8769071783484440310 2 IN IP4 127.0.0.1

s=-

t=0 0

a=group:BUNDLE 0 1

a=msid-semantic: WMS stream

m=audio 9 RTP/AVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=ice-ufrag:Xu9W

a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf

a=ice-options:trickle renomination

a=mid:0

a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level

a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id

a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id

a=sendrecv

a=msid:stream audio0

a=rtcp-mux

a=rtpmap:111 opus/48000/2

a=rtcp-fb:111 transport-cc

a=fmtp:111 minptime=10;useinbandfec=1

a=rtpmap:103 ISAC/16000

a=rtpmap:104 ISAC/32000

a=rtpmap:9 G722/8000

a=rtpmap:102 ILBC/8000

a=rtpmap:0 PCMU/8000

a=rtpmap:8 PCMA/8000

a=rtpmap:106 CN/32000

a=rtpmap:105 CN/16000

a=rtpmap:13 CN/8000

a=rtpmap:110 telephone-event/48000

a=rtpmap:112 telephone-event/32000

a=rtpmap:113 telephone-event/16000

a=rtpmap:126 telephone-event/8000

a=ssrc:2013852990 cname:5qhSCaiXtzrutCLW

a=ssrc:2013852990 msid:stream audio0

a=ssrc:2013852990 mslabel:stream

a=ssrc:2013852990 label:audio0

m=video 9 RTP/AVPF 96 97 98 99 100 101 127

c=IN IP4 0.0.0.0

a=rtcp:9 IN IP4 0.0.0.0

a=ice-ufrag:Xu9W

a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf

a=ice-options:trickle renomination

a=mid:1

a=extmap:14 urn:ietf:params:rtp-hdrext:toffset

a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time

a=extmap:13 urn:3gpp:video-orientation

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type

a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing

a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id

a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id

a=recvonly

a=rtcp-mux

a=rtcp-rsize

a=rtpmap:96 H264/90000

a=rtcp-fb:96 goog-remb

a=rtcp-fb:96 transport-cc

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34

a=rtpmap:97 rtx/90000

a=fmtp:97 apt=96

a=rtpmap:98 H264/90000

a=rtcp-fb:98 goog-remb

a=rtcp-fb:98 transport-cc

a=rtcp-fb:98 ccm fir

a=rtcp-fb:98 nack

a=rtcp-fb:98 nack pli

a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034

a=rtpmap:99 rtx/90000

a=fmtp:99 apt=98

a=rtpmap:100 red/90000

a=rtpmap:101 rtx/90000

a=fmtp:101 apt=100

a=rtpmap:127 ulpfec/90000
```

**Comment by xia-chu** [comment]
不是 可能是zlm兼容性问题 建议注释这句代码：`Sdp.cpp, line 1328.`试试

**Comment by ChokWah** [comment]
@xia-chu 是我自己代码问题。已解决。

看报错信息就是SDP生成的不对，我看了下SDP的结构，必要字段对比。https://developer.aliyun.com/article/781443

正常的m=video 后面是支持的协议，包含UDP/TLS/RTP/SAVPF，而我生成的只有RTP/SAVPF。

猜测是我代码构造peerconnection不对。参考别人的代码，重新生成的offer，返回正常，200以及answer。

**Comment by wasphin** [comment]
应该不是这个问题,  `RTP/SAVPF` 应只会触发加密算法不支持, 不会触发上面的 ASSERT.
```
POST /index/api/webrtc?app=test&stream=sdp&type=push HTTP/1.1
Host: 127.0.0.1:8350
User-Agent: curl/7.61.1
Accept: */*
Content-Length: 2806
Expect: 100-continue

v=0
o=- 8769071783484440310 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS stream
m=audio 9 RTP/AVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Xu9W
a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf
a=ice-options:trickle renomination
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:stream audio0
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:2013852990 cname:5qhSCaiXtzrutCLW
a=ssrc:2013852990 msid:stream audio0
a=ssrc:2013852990 mslabel:stream
a=ssrc:2013852990 label:audio0
m=video 9 RTP/AVPF 96 97 98 99 100 101 127
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Xu9W
a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf
a=ice-options:trickle renomination
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=recvonly
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 red/90000
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 ulpfec/90000

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 61
Content-Type: application/json
Date: Sat, Jul 03 2021 08:49:49 GMT
Keep-Alive: timeout=30, max=100
Server: ZLMediaKit-5.0(build in Jun 24 2021 11:49:57)

{
   "code" : -400,
   "msg" : "不支持的加密算法:"
}
```

**Comment by ChokWah** [comment]
@wasphin 不支持加密算法应该是HTTPS的问题吧，换了http就不提示这个了（Chrome因为thisisunsafe可以临时信任）

我自己本地跑了ZLMediaKit。然后打开WebRtc.index网页，两个网页本来可以一边推流一边拉流。

突然又不行了。提示sdp交换失败，还在研究怎么回事。

**Comment by ChokWah** [comment]
如果报SDP类型的错误，可以看一下。请求参数有没有设置错误。一般是body的k-v没对上，可以在改cpp源码打印一下。排除格式错误问题。

**Comment by xia-chu** [comment]
也没有setup字段，dtls相关的信息都没有

**Comment by xia-chu** [comment]
一般有这两种字段的：
```bash
a=fingerprint:sha-256 21:21:07:E8:3C:D0:3B:45:87:9A:31:86:DE:4F:C1:BA:E1:0E:96:BA:41:36:6E:3A:3F:C6:C8:92:95:5B:71:5F
a=setup:actpass
```

**Comment by wasphin** [comment]
不启用 dtls srtp 就是这样的

**Comment by xia-chu** [comment]
> 不启用 dtls srtp 就是这样的

客户端也能不启用dtls？

**Comment by wasphin** [comment]
安卓有，https://webrtc.googlesource.com/src/+/refs/heads/main/sdk/android/api/org/webrtc/PeerConnection.java#530

**Comment by ChokWah** [comment]
@xia-chu WebRtc代码设置dtls一直是true。我看用index网页构造出来的sdp也没有dtls呀。

**Comment by ChokWah** [comment]
@xia-chu @wasphin 感谢两位，已排查清楚，是我本地webrtc的设置问题。

1. Assertion failed: (!origin.empty())出现，注释了发现Assertion failed: (!session_name.empty())。说明我请求的格式不对，打印sdp，用postman排查成功。（原因是自己请求错了类型）
2. index网页突然连接不上，拉最新的master代码，删除build重新编译，在release/mac/debug重新运行解决。
3. Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer。纯WebRtc的问题了。把发送的offer对照收到的answer。发现group设置了012，0音频，1视频，2dataChannel。answer只有常规的01。把dataChannel移除。设置成功，返回远端视频流。

**Comment by xia-chu** [comment]
datachannel我设置下为inactive就行了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zuohuaChen ***@***.***&gt;
发送时间: 2021年7月7日 17:41
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] Assertion failed: (!origin.empty()) ？移动端使用webrtc请求index/api/webrtc?app=live&amp;stream=test&amp;type=play (#956)

**Comment by hxbamboo** [comment]
> @xia-chu 是我自己代码问题。已解决。
> 
> 看报错信息就是SDP生成的不对，我看了下SDP的结构，必要字段对比。https://developer.aliyun.com/article/781443
> 
> 正常的m=video 后面是支持的协议，包含UDP/TLS/RTP/SAVPF，而我生成的只有RTP/SAVPF。
> 
> 猜测是我代码构造peerconnection不对。参考别人的代码，重新生成的offer，返回正常，200以及answer。

您好，代码是如何操作的，我现在也是遇到了assertion failed

**Comment by CnYiXiaoNaiHe** [comment]
> 应该不是这个问题, `RTP/SAVPF` 应只会触发加密算法不支持, 不会触发上面的 ASSERT.
> 
> ```
> POST /index/api/webrtc?app=test&stream=sdp&type=push HTTP/1.1
> Host: 127.0.0.1:8350
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Length: 2806
> Expect: 100-continue
> 
> v=0
> o=- 8769071783484440310 2 IN IP4 127.0.0.1
> s=-
> t=0 0
> a=group:BUNDLE 0 1
> a=msid-semantic: WMS stream
> m=audio 9 RTP/AVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:Xu9W
> a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf
> a=ice-options:trickle renomination
> a=mid:0
> a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=sendrecv
> a=msid:stream audio0
> a=rtcp-mux
> a=rtpmap:111 opus/48000/2
> a=rtcp-fb:111 transport-cc
> a=fmtp:111 minptime=10;useinbandfec=1
> a=rtpmap:103 ISAC/16000
> a=rtpmap:104 ISAC/32000
> a=rtpmap:9 G722/8000
> a=rtpmap:102 ILBC/8000
> a=rtpmap:0 PCMU/8000
> a=rtpmap:8 PCMA/8000
> a=rtpmap:106 CN/32000
> a=rtpmap:105 CN/16000
> a=rtpmap:13 CN/8000
> a=rtpmap:110 telephone-event/48000
> a=rtpmap:112 telephone-event/32000
> a=rtpmap:113 telephone-event/16000
> a=rtpmap:126 telephone-event/8000
> a=ssrc:2013852990 cname:5qhSCaiXtzrutCLW
> a=ssrc:2013852990 msid:stream audio0
> a=ssrc:2013852990 mslabel:stream
> a=ssrc:2013852990 label:audio0
> m=video 9 RTP/AVPF 96 97 98 99 100 101 127
> c=IN IP4 0.0.0.0
> a=rtcp:9 IN IP4 0.0.0.0
> a=ice-ufrag:Xu9W
> a=ice-pwd:WxKa9k4wCHIlm2Tqh1Ls4rvf
> a=ice-options:trickle renomination
> a=mid:1
> a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
> a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
> a=extmap:13 urn:3gpp:video-orientation
> a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
> a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
> a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
> a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
> a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
> a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
> a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
> a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
> a=recvonly
> a=rtcp-mux
> a=rtcp-rsize
> a=rtpmap:96 H264/90000
> a=rtcp-fb:96 goog-remb
> a=rtcp-fb:96 transport-cc
> a=rtcp-fb:96 ccm fir
> a=rtcp-fb:96 nack
> a=rtcp-fb:96 nack pli
> a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c34
> a=rtpmap:97 rtx/90000
> a=fmtp:97 apt=96
> a=rtpmap:98 H264/90000
> a=rtcp-fb:98 goog-remb
> a=rtcp-fb:98 transport-cc
> a=rtcp-fb:98 ccm fir
> a=rtcp-fb:98 nack
> a=rtcp-fb:98 nack pli
> a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e034
> a=rtpmap:99 rtx/90000
> a=fmtp:99 apt=98
> a=rtpmap:100 red/90000
> a=rtpmap:101 rtx/90000
> a=fmtp:101 apt=100
> a=rtpmap:127 ulpfec/90000
> 
> HTTP/1.1 200 OK
> Access-Control-Allow-Origin: *
> Connection: keep-alive
> Content-Length: 61
> Content-Type: application/json
> Date: Sat, Jul 03 2021 08:49:49 GMT
> Keep-Alive: timeout=30, max=100
> Server: ZLMediaKit-5.0(build in Jun 24 2021 11:49:57)
> 
> {
>    "code" : -400,
>    "msg" : "不支持的加密算法:"
> }
> ```

加密算法不支持怎么处理

**Comment by tjh6767** [comment]
Assertion failed: (!origin.empty()), function checkValid, file /var/www/html/ZLMediaKit/webrtc/Sdp.cpp, line 1355
大佬是怎么解决这个问题的？

**Comment by xia-chu** [comment]
> Assertion failed: (!origin.empty()), function checkValid, file /var/www/html/ZLMediaKit/webrtc/Sdp.cpp, line 1355 大佬是怎么解决这个问题的？

这什么客户端？您可以注释掉 /var/www/html/ZLMediaKit/webrtc/Sdp.cpp, line 1355解决这个问题
