### ISSUE TITLE
HLS设置为点播后，是否支持倍速播放，倍速设置是否可以自定义

### ISSUE THREAD

**Issue by poorboy1991** [ZLMediaKit/ZLMediaKit#958]
- 将config.ini中segNum设置为0后，ZLMediaKit支持不删除切片保存为点播，然后在访问https://localhost/live/test/hls.m3u8 可以看到m3u8的点播，但是是正常的一倍速，请问作者ZLMediaKit是否支持可以在云端修改倍速

**Comment by xia-chu** [comment]
不能 hls点播倍速播放完全取决于播放器

**Comment by poorboy1991** [comment]
好的
