### ISSUE TITLE
[技术咨询] webrtc延时较大

### ISSUE THREAD

**Issue by wuhenfeike** [ZLMediaKit/ZLMediaKit#959]
webrtc 推流，webrtc和rtmp播放延迟三秒左右，hls无法播放，请问大佬遇到这种情况了么？是那里配置可以降低延时么？我的全部操作在win10上面进行。

**Comment by wujincheng2333** [comment]
可能推流端设置了缓存

**Comment by wuhenfeike** [comment]
@wujincheng2333 老大，1，怎么设置这个推流端缓存？2，hls不能播放是现在还不支持么

**Comment by ChokWah** [comment]
@wuhenfeike 请问你是在哪一端使用WebRtc推拉流？设置sdp里有session_name吗

**Comment by xia-chu** [comment]
webrtc推流和播放都3秒延时？不太可能吧

**Comment by xia-chu** [comment]
hls用什么播放器播放的？zlm默认编码是264+g711u ， ffplay支持的

**Comment by wuhenfeike** [comment]
@xia-chu 用的ffplay播放的，服务器和webrtc推流都是在windows系统跑的，参数都是用的默认的，没改动。

**Comment by xia-chu** [comment]
先拍个视频看看 说实话 我不太相信

**Comment by wuhenfeike** [comment]
@xia-chu 好的，回头我拍个视频，但是怎么发你呢？

**Comment by xia-chu** [comment]
github issue可以直接上传mp4文件

**Comment by wuhenfeike** [comment]
@xia-chu 
![91C31039-E688-422E-993F-405EC6DF94CC](https://user-images.githubusercontent.com/5409708/125183108-57967b80-e246-11eb-9f68-6c8ffed33952.png)
![C95D6187-C989-4B38-B514-DBF428FFE482](https://user-images.githubusercontent.com/5409708/125183110-59f8d580-e246-11eb-887a-49f631cabc13.jpeg)

https://user-images.githubusercontent.com/5409708/125183111-5d8c5c80-e246-11eb-9c63-c6db8d16e4b3.MP4

**Comment by wuhenfeike** [comment]
@xia-chu 延时的图片和视频已经上传，另外有张图片是m3u8无法播放的

**Comment by wuhenfeike** [comment]
@xia-chu 推流几乎没延迟，是播放延迟

**Comment by xia-chu** [comment]
你更新下zlm试试 可能跟之前rtp ntp时间戳相关问题有关

**Comment by wuhenfeike** [comment]
@xia-chu 更新最新的代码测试还是有延时和m3u8无法播放的问题。

**Comment by xia-chu** [comment]
@wuhenfeike webrtc延时问题我这里没法复现 我这延时很小的，你是不是开启合并写功能呢？
hls没法播放也可能跟配置有关，建议把配置文件粘贴上来。

前段时间比较忙，答复issue比较晚，抱歉。

**Comment by wuhenfeike** [comment]
@xia-chu 配置都是用的默认配置，我用的服务器都是windows编译exe文件跑的，没在linux上。

**Comment by xia-chu** [comment]
你这个问题 没其他人反馈过 我这边很早前也是Windows上开发测试的 没发现这个问题。
现在我已经没Windows开发环境了 没法测试这个问题， 你可以先在Linux测试试试 谢谢！

**Comment by zhongpingyong** [comment]
+1，webrtc测试播放端3秒延迟，服务是在linux上

**Comment by xia-chu** [comment]
> +1，webrtc测试播放端3秒延迟，服务是在linux上

webrtc推流吗？ webrtc播放吗

**Comment by zhongpingyong** [comment]
> > +1，webrtc测试播放端3秒延迟，服务是在linux上
> 
> webrtc推流吗？ webrtc播放吗

webrtc播放

**Comment by xia-chu** [comment]
看你的视频录像 确实延时大 但是我测试没发现这个问题 也无法复现 另外也没有其他人反馈这个问题 你可以更新最新代码再测试下 issue我先关闭了
