### ISSUE TITLE
关于MediaPusher的使用。接#92

### ISSUE THREAD

**Issue by FoxesChen** [zlmediakit/ZLMediaKit#96]
关于创建MediaPusher，我参照demo了，但发现没推流。createPusher 在事件里面注册，并且在事件里面被调用了。

`

void createPusher(const EventPoller::Ptr &poller, const string &schema, const string &vhost, const string &app, const string &stream, const string &url) {
pusher.reset(new MediaPusher(schema, vhost, app, stream, poller));
pusher->setOnShutdown([poller, schema, vhost, app, stream, url](const SockException &ex) {});
pusher->setOnPublished([poller, schema, vhost, app, stream, url](const SockException &ex) {});
pusher->publish(url);
}

`

**Comment by xiongziliang** [comment]
pushe对象是不是一个临时对象？

**Comment by FoxesChen** [comment]
强引用。全局。

**Comment by xiongziliang** [comment]
你整个代码粘贴出来

**Comment by FoxesChen** [comment]
`MediaPusher::Ptr pusher;
Timer::Ptr g_timer;
DesktopDevChannel::Ptr desktopChan;

void createPusher(const EventPoller::Ptr &poller, const string &schema, const string &vhost, const string &app, const string &stream, const string &url) {
	pusher.reset(new MediaPusher(schema, vhost, app, stream, poller));
	pusher->setOnShutdown([poller, schema, vhost, app, stream, url](const SockException &ex) {});
	pusher->setOnPublished([poller, schema, vhost, app, stream, url](const SockException &ex) {});
	pusher->publish(url);
}

int main(){
	auto poller = EventPollerPool::Instance().getPoller();
	std::string pushUrl = "rtmp://192.168.1.185:9001/live/rtsp_push_2";
	desktopChan.reset(new DesktopDevChannel(DEFAULT_VHOST, "live", "desktop"));
	NoticeCenter::Instance().addListener(nullptr, Broadcast::kBroadcastMediaChanged, [pushUrl, poller](BroadcastMediaChangedArgs) {

		if (bRegist && pushUrl.find(schema) == 0)
		{
			SPDLOG_DEBUGF_FMT("createPusher");
			createPusher(poller, "rtmp", DEFAULT_VHOST, "live", "stream", pushUrl);
		}
	});

	VideoInfo vi = { pCodec_ctx->width, pCodec_ctx->height, 25 };
	desktopChan->initVideo(vi);
	
	while (av_read_frame(fmt_ctx, &pkt) >= 0){
	        char *yuv[3];
			int yuv_len[3];
			yuv_len[0] = pFrameYUV->linesize[0];
			yuv_len[1] = pFrameYUV->linesize[1];
			yuv_len[2] = pFrameYUV->linesize[2];
			yuv[0] = (char*)pFrameYUV->data;
			yuv[1] = (char*)pFrameYUV->data[1];
			yuv[2] = (char*)pFrameYUV->data[2];

			desktopChan->inputYUV((char**)pFrameYUV->data, yuv_len, 0);
			
			av_packet_unref(&pkt);
		    Sleep(40);
	}
}`

**Comment by xiongziliang** [comment]
![image](https://user-images.githubusercontent.com/11495632/65675430-c4944d80-e080-11e9-88f5-500701e105e8.png)
这三个参数你为什么要不一样？

**Comment by FoxesChen** [comment]
原来如此。改成一样的，就可以了。
