### ISSUE TITLE
[技术咨询] GB28181以UDP方式收流的性能问题

### ISSUE THREAD

**Issue by zengzhiying** [ZLMediaKit/ZLMediaKit#961]
**问题描述**
- 本地网卡使用ZLM的openRtpServer接口开启多个端口接收国标的rtp包，压测发现路数逐渐变高时，ZLM的消费逐渐跟不上，导致频繁丢包 ，视频播放画面卡住或者无法播放的情况。（但是TCP方式接流没有问题）

**详细环境描述**
- 前提准备：rtp文件通过ZLM保存了摄像头1路视频文件，然后编写代码读取该文件并发送来模拟多路流的情况，文件本身没有问题，UDP方式150路以下播放流畅。测试的代码稍后会附上。
- 操作系统：CentOS 8.4
- 网络环境：本地lo回环网卡
- cpu：双路Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz 共20核心40线程
![image](https://user-images.githubusercontent.com/13583823/124525394-c2544b00-de31-11eb-9cd5-de284315350f.png)
- 内存：512G
- 内核参数：net.core.rmem_max已经调大至4M，文件句柄数调大至666666
- 代码中udp缓冲区大小也已经调大为32M
- ZLM编译参数：开启Release参数编译生成目录没问题release/linux/Release/，且已编译jemalloc
![image](https://user-images.githubusercontent.com/13583823/124525613-7950c680-de32-11eb-8740-f3fb51c5ec4a.png)

**测试过程以及现象**
- 模拟推流150路以内，随便挑选1路播放流畅，随着路数增大播放逐渐变得卡顿，到300路的时候卡顿和丢包变得严重。模拟推流过程为：首先批量开启指定的端口和stream_id，然后使用测试代码读取文件投递到指定的端口中。
![image](https://user-images.githubusercontent.com/13583823/124527607-99838400-de38-11eb-80d2-6ef0e2a96c76.png)
- cpu占用
![image](https://user-images.githubusercontent.com/13583823/124527727-dc455c00-de38-11eb-9a8e-123ef05a3e08.png)
发送程序占用200%多，ZLM占用100%，其实在150路的时候就已经占用100%了，但是随着路数的增加cpu始终不再增加，利用不了多核。
- 丢包情况
![image](https://user-images.githubusercontent.com/13583823/124527857-44943d80-de39-11eb-869f-6d1c223ac35b.png)
- 接收端队列比较长
![image](https://user-images.githubusercontent.com/13583823/124527942-86bd7f00-de39-11eb-82c8-05a5026803ca.png)
看某个端口接收队列经常是不断变长，好大会之后才变短，发送端队列看着都正常
![image](https://user-images.githubusercontent.com/13583823/124528143-08ada800-de3a-11eb-85bb-7bbbae8a1b9c.png)
- 带宽占用
![image](https://user-images.githubusercontent.com/13583823/124528264-617d4080-de3a-11eb-8b28-ec8f6f858b27.png)
- perf情况
![image](https://user-images.githubusercontent.com/13583823/124528423-b4ef8e80-de3a-11eb-80c5-b58556dc7c3e.png)

但是如果是改用tcp接流的话，1000路都没有问题，播放很流畅，cpu和带宽占用如下：
![image](https://user-images.githubusercontent.com/13583823/124528524-f1bb8580-de3a-11eb-89b3-800f0906876a.png)
cpu占用1600%
![image](https://user-images.githubusercontent.com/13583823/124528542-03049200-de3b-11eb-8d0c-6002184b14a4.png)
带宽占用也正常

请问大佬有否有可能因为tcp是传统的线程模型，而udp是协程的方式轮询socket导致的这种性能差异？

开端口的python代码如下(task.py)：
```python
#!/usr/bin/python3
import requests
import sys
url="http://127.0.0.1:8080"

openRtpServer = "/index/api/openRtpServer"
closeRtpServer="/index/api/closeRtpServer"
listRtpServer = "/index/api/listRtpServer"

port=30000
num = 300

def start():
    global port
    global num
    cnt = 0
    for i in range(num):
        args={
            "port": port,
            "enable_tcp" : 1,
            "stream_id": str(cnt)
        }
        port+=2
        cnt += 1
        resp = requests.post(url+openRtpServer,data=args)
        print(resp.json())



def stop():
    global port
    global num
    cnt = 0
    for i in range(num):
        args={
            "stream_id": str(cnt)
        }
        port+=2
        cnt+=1
        resp = requests.post(url+closeRtpServer,data=args)
        print(resp.json())


def list():
    resp = requests.get(url+listRtpServer)
    data = resp.json()
    print(data)
    if 'data' in data:
        print(len(data['data']))
    else:
        print(0)

if __name__ == '__main__':
    if sys.argv[1] == 'start':
        start()
    elif sys.argv[1] == 'stop':
        stop()
    elif sys.argv[1] == "list":
        list()
```
开启端口：`./task.py start`
查看端口：`./task.py list`
停止端口：`./task.py stop`
读取rtp文件发送的golang代码如下：
```go
package main

import (
	"os"
	"fmt"
	"net"
	"io"
	"time"
	"bufio"
	"encoding/binary"
)

var done chan int

func init() {
	done = make(chan int, 10000)
}

func sendRtpFile(fileName, protocol, addr string, n int) {
	defer func() {
		err := recover()
		if err != nil {
			fmt.Println("sendRtpFile err:", err)
		}
		done <- 1
	}()

	switch protocol {
	case "tcp":
		//
	case "udp":
		//
	default:
		fmt.Println("Protocol error:", protocol)
		return
	}

	f, err := os.Open(fileName)
	if err != nil {
		fmt.Println("Open file err:", err)
		return
	}

	defer f.Close()

	conn, err := net.Dial(protocol, addr)
	if err != nil {
		fmt.Printf("%s server err: %s\n", protocol, err)
		return
	}

	defer conn.Close()

	buf := bufio.NewWriter(conn)

	for i := 0; i < n; i++ {
		sizeBuf := make([]byte, 2)
		n, err := f.Read(sizeBuf)

		for n == 2 && err == nil {
			size := int(binary.BigEndian.Uint16(sizeBuf))
			if size == 0 {
				fmt.Println("Read size error!")
				break
			}

			if protocol == "tcp" {
				buf.Write(sizeBuf)
			}
			
			io.CopyN(buf, f, int64(size))
                        buf.Flush()
			time.Sleep(2000 * time.Microsecond)
			n, err = f.Read(sizeBuf)
		}
		fmt.Println("Number of reads:", i + 1)
		f.Seek(0, 0)
	}
}

func main() {
        // rtp文件
	fileName := "/data/rtp/gb_play_37021100002005000101_34020000001320000011.rtp"
        // 主机
	host := "127.0.0.1"
        // 起始端口 30000,30002,30004,...
	port := 30000
        // 模拟总的路数
	coroutines := 300
        // 使用的协议
	protocol := "udp"

	for i := 0; i < coroutines; i++ {
		go sendRtpFile(fileName, protocol, fmt.Sprintf("%s:%d", host, port), 1)
		time.Sleep(10 * time.Millisecond)
		port += 2
	}

	for i := 0; i < coroutines; i++ {
		<-done
	}
	fmt.Println("exit.")
}
```
测试文件就是ZLM保存的rtp文件。
上面是具体问题的情况，麻烦大佬有空能帮忙看一下，如果有贴的不全的，我随时再补上，感谢！

**Comment by xia-chu** [comment]
是的 之前zlm有负载均衡问题 昨晚刚修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zengzhiying ***@***.***&gt;
发送时间: 2021年7月6日 09:32
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] GB28181以UDP方式收流的性能问题 (#961)





 
问题描述
  
本地网卡使用ZLM的openRtpServer接口开启多个端口接收国标的rtp包，压测发现路数逐渐变高时，ZLM的消费逐渐跟不上，导致频繁丢包 ，视频播放画面卡住或者无法播放的情况。（但是TCP方式接流没有问题） 
 
详细环境描述
  
前提准备：rtp文件通过ZLM保存了摄像头1路视频文件，然后编写代码读取该文件并发送来模拟多路流的情况，文件本身没有问题，UDP方式150路以下播放流畅。测试的代码稍后会附上。 

操作系统：CentOS 8.4 

网络环境：本地lo回环网卡 

cpu：双路Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz 共20核心40线程
  

内存：512G 

内核参数：net.core.rmem_max已经调大至4M，文件句柄数调大至666666 

代码中udp缓冲区大小也已经调大为32M 

ZLM编译参数：开启Release参数编译生成目录没问题release/linux/Release/，且已编译jemalloc
  
 
测试过程以及现象
  
模拟推流150路以内，随便挑选1路播放流畅，随着路数增大播放逐渐变得卡顿，到300路的时候卡顿和丢包变得严重。模拟推流过程为：首先批量开启指定的端口和stream_id，然后使用测试代码读取文件投递到指定的端口中。
  

cpu占用
 
 发送程序占用200%多，ZLM占用100%，其实在150路的时候就已经占用100%了，但是随着路数的增加cpu始终不再增加，利用不了多核。 

丢包情况
  

接收端队列比较长
 
 看某个端口接收队列经常是不断变长，好大会之后才变短，发送端队列看着都正常
  

带宽占用
  

perf情况
  
 
但是如果是改用tcp接流的话，1000路都没有问题，播放很流畅，cpu和带宽占用如下：
 
 cpu占用1600%
 
 带宽占用也正常
 
开端口的python代码如下(task.py)：
 #!/usr/bin/python3 import requests import sys url="http://127.0.0.1:8080" openRtpServer = "/index/api/openRtpServer" closeRtpServer="/index/api/closeRtpServer" listRtpServer = "/index/api/listRtpServer" port=30000 num = 300 def start():     global port     global num     cnt = 0     for i in range(num):         args={             "port": port,             "enable_tcp" : 1,             "stream_id": str(cnt)         }         port+=2         cnt += 1         resp = requests.post(url+openRtpServer,data=args)         print(resp.json()) def stop():     global port     global num     cnt = 0     for i in range(num):         args={             "stream_id": str(cnt)         }         port+=2         cnt+=1         resp = requests.post(url+closeRtpServer,data=args)         print(resp.json()) def list():     resp = requests.get(url+listRtpServer)     data = resp.json()     print(data)     if 'data' in data:         print(len(data['data']))     else:         print(0) if __name__ == '__main__':     if sys.argv[1] == 'start':         start()     elif sys.argv[1] == 'stop':         stop()     elif sys.argv[1] == "list":         list()
 
开启端口：./task.py start
 查看端口：./task.py list
 停止端口：./task.py stop
 读取rtp文件发送的golang代码如下：
 package main import ( "os" "fmt" "net" "io" "time" "bufio" "encoding/binary" ) var done chan int func init() { done = make(chan int, 10000) } func sendRtpFile(fileName, protocol, addr string, n int) { defer func() { err := recover() if err != nil { fmt.Println("sendRtpFile err:", err) } done <- 1 }() switch protocol { case "tcp": // case "udp": // default: fmt.Println("Protocol error:", protocol) return } f, err := os.Open(fileName) if err != nil { fmt.Println("Open file err:", err) return } defer f.Close() conn, err := net.Dial(protocol, addr) if err != nil { fmt.Printf("%s server err: %s\n", protocol, err) return } defer conn.Close() buf := bufio.NewWriter(conn) for i := 0; i < n; i++ { sizeBuf := make([]byte, 2) n, err := f.Read(sizeBuf) for n == 2 &amp;&amp; err == nil { size := int(binary.BigEndian.Uint16(sizeBuf)) if size == 0 { fmt.Println("Read size error!") break } if protocol == "tcp" { buf.Write(sizeBuf) } io.CopyN(buf, f, int64(size))                         buf.Flush() time.Sleep(2000 * time.Microsecond) n, err = f.Read(sizeBuf) } fmt.Println("Number of reads:", i + 1) f.Seek(0, 0) } } func main() {         // rtp文件 fileName := "/data/rtp/gb_play_37021100002005000101_34020000001320000011.rtp"         // 主机 host := "127.0.0.1"         // 起始端口 30000,30002,30004,... port := 30000         // 模拟总的路数 coroutines := 300         // 使用的协议 protocol := "udp" for i := 0; i < coroutines; i++ { go sendRtpFile(fileName, protocol, fmt.Sprintf("%s:%d", host, port), 1) time.Sleep(10 * time.Millisecond) port += 2 } for i := 0; i < coroutines; i++ { <-done } fmt.Println("exit.") }
 
测试文件就是ZLM保存的rtp文件。
 上面是具体问题的情况，麻烦大佬有空能帮忙看一下，如果有贴的不全的，我随时再补上，感谢！

**Comment by zengzhiying** [comment]
好的，太及时了^^^，我再拉一下新的代码复测一下，谢谢！

**Comment by xia-chu** [comment]
结果怎么样？ 
配置文件中，一下配置全部改成1也能提高性能的。转协议比较损耗性能，zlm默认开启一直转协议(而不是按需)
```ini
[general]
###### 以下是按需转协议的开关，在测试ZLMediaKit的接收推流性能时，请把下面开关置1
###### 如果某种协议你用不到，你可以把以下开关置1以便节省资源(但是还是可以播放，只是第一个播放者体验稍微差点)，
###### 如果某种协议你想获取最好的用户体验，请置0(第一个播放者可以秒开，且不花屏)

#hls协议是否按需生成，如果hls.segNum配置为0(意味着hls录制)，那么hls将一直生成(不管此开关)
hls_demand=0
#rtsp[s]协议是否按需生成
rtsp_demand=0
#rtmp[s]、http[s]-flv、ws[s]-flv协议是否按需生成
rtmp_demand=0
#http[s]-ts协议是否按需生成
ts_demand=0
#http[s]-fmp4、ws[s]-fmp4协议是否按需生成
fmp4_demand=0
```

**Comment by zengzhiying** [comment]
已经测试了400路udp视频播放很流畅，cpu占用700%，带宽2G左右，推的时候稍微提高了下速度，相当于接近500路了，具体极限还没有测，等下测一下
![image](https://user-images.githubusercontent.com/13583823/124536478-a8733200-de4a-11eb-8a77-2f05815c4f4a.png)
![image](https://user-images.githubusercontent.com/13583823/124536489-ac9f4f80-de4a-11eb-97c6-60990554c9e5.png)
另外按需生成也是默认的0，没改成1，等下改成1再试试

**Comment by zengzhiying** [comment]
改成1开启按需生成后，cpu确实省很多，1200路视频只占用不到600%的cpu，播放很流畅，估计到2000路应该问题不大，只是我那个发送rtp的程序好像撑不住了，得优化下
![image](https://user-images.githubusercontent.com/13583823/124540550-330b5f80-de52-11eb-8e5f-12d7a5a7baca.png)

大佬这波优化太秀了~

**Comment by xia-chu** [comment]
你还是按需拉流改成0 这样好跟之前的数据对比



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zengzhiying ***@***.***&gt;
发送时间: 2021年7月6日 12:05
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] GB28181以UDP方式收流的性能问题 (#961)





 
改成1开启按需生成后，cpu确实省很多，1200路视频只占用不到600%的cpu，播放很流畅，估计到2000路应该问题不大，只是我那个发送rtp的程序好像撑不住了，得优化下
 
 
大佬这波优化太秀了~

**Comment by zengzhiying** [comment]
改回去0了，然后同样1200路，cpu占用接近2400%，上下文切换很高，估计是我的cpu资源不够了，播放有些卡，数据消费不完
![image](https://user-images.githubusercontent.com/13583823/124545115-0445b700-de5b-11eb-808e-df6148c0edaf.png)
下降到1000路后，cpu占用2100%上下，播放基本流畅
![image](https://user-images.githubusercontent.com/13583823/124545350-7918f100-de5b-11eb-927a-f045ff4b0adf.png)

**Comment by xia-chu** [comment]
> 改回去0了，然后同样1200路，cpu占用接近2400%，上下文切换很高，估计是我的cpu资源不够了，播放有些卡，数据消费不完
> ![image](https://user-images.githubusercontent.com/13583823/124545115-0445b700-de5b-11eb-808e-df6148c0edaf.png)
> 下降到1000路后，cpu占用2100%上下，播放基本流畅
> ![image](https://user-images.githubusercontent.com/13583823/124545350-7918f100-de5b-11eb-927a-f045ff4b0adf.png)

看图 客户端和zlm已经互相抢占cpu了 top显示id(空闲)百分比已经接近于0。 可以看看perf top看看zlm主要占用cpu的函数，看看有没有优化空间

**Comment by xia-chu** [comment]
用recvmmsg应该能降低不少cpu占用，这个后续优化

**Comment by zengzhiying** [comment]
perf内容：
![image](https://user-images.githubusercontent.com/13583823/124572926-a2497980-de7b-11eb-86fd-879537b5788d.png)

**Comment by xia-chu** [comment]
http-ts性能太拉胯了 ts包太小的原因 后面合并包优化下&nbsp;
你可以先把ts按需生成打开 应该能降低不少cpu使用率

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zengzhiying ***@***.***&gt;
发送时间: 2021年7月6日 17:09
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询] GB28181以UDP方式收流的性能问题 (#961)





 
perf内容：

**Comment by zengzhiying** [comment]
确实，现在1500，降低了6个核的使用
![image](https://user-images.githubusercontent.com/13583823/124602466-776f1d80-de9b-11eb-8f54-0fe7b40bcdf5.png)
perf看也正常了
![image](https://user-images.githubusercontent.com/13583823/124602653-aab1ac80-de9b-11eb-8788-9f2a75d250c0.png)

**Comment by xia-chu** [comment]
HTTP-TS直播性能大幅提高了 可以更新代码后再测试下

**Comment by zengzhiying** [comment]
嗯，现在测试提高了，同样情况下占用1600%的cpu
![image](https://user-images.githubusercontent.com/13583823/124694412-c9ec2080-df13-11eb-9398-0fad2f01a728.png)

**Comment by xia-chu** [comment]
2400% 优化到 1600% ？

**Comment by xia-chu** [comment]
perf top 看下

**Comment by zengzhiying** [comment]
top: 
![image](https://user-images.githubusercontent.com/13583823/124707565-90271400-df2b-11eb-8984-5b4665f9c773.png)
perf top:
![image](https://user-images.githubusercontent.com/13583823/124707406-5eae4880-df2b-11eb-9a75-0336b01f9c35.png)

**Comment by xia-chu** [comment]
ts的内存拷贝有点多 其实可以优化下 但是那样malloc又增加了

**Comment by xia-chu** [comment]
你这个码流是 4Mb/s 1080P的吗

**Comment by xia-chu** [comment]
@zengzhiying 加个qq好友聊聊性能优化的事情？

**Comment by zengzhiying** [comment]
嗯，对的，码流是4.5Mb/s左右
![image](https://user-images.githubusercontent.com/13583823/124718083-54df1200-df38-11eb-9512-ba9a1b5b4198.png)
10路占用45Mbps
![image](https://user-images.githubusercontent.com/13583823/124718688-eea6bf00-df38-11eb-94f9-421201a81388.png)

**Comment by zengzhiying** [comment]
好的，QQ: 503778919，微信也是这个，

**Comment by xia-chu** [comment]
2000路tcp，带宽接近8G，只保留rtsp/rtmp，其余的hls,mp4,ts都是设置成按需了：
![41625645924_ pic_hd](https://user-images.githubusercontent.com/11495632/124728040-d5eed700-df41-11eb-8d85-4065089d7a36.jpg)
![31625645913_ pic_hd](https://user-images.githubusercontent.com/11495632/124728055-d9825e00-df41-11eb-8c33-b4bea4ea463b.jpg)
![21625645899_ pic_hd](https://user-images.githubusercontent.com/11495632/124728979-a2607c80-df42-11eb-8cb3-9587f26a2cda.jpg)

**Comment by chaoyue999** [comment]
大神  哪里可以下载rtp文件？

**Comment by zengzhiying** [comment]
您好，rtp文件可以直接开启ZLMediaKit的保存功能，就可以自动保存成rtp文件了。
设置dumpDir后就会在指定目录下自动保存文件
















在 2021-11-15 11:11:54，"chaoyue999" ***@***.***> 写道：

大神 哪里可以下载rtp文件？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenhan3242** [comment]
您好，我是个小白，现在要测试这个，可以麻烦您指导一下吗
扣1593243158  有偿

**Comment by liuyaozhenshuai** [comment]
请问您的服务器有配置显卡吗，接收28181rtp流转协议给前端的过程是否消耗了显卡资源？

**Comment by xia-chu** [comment]
> 请问您的服务器有配置显卡吗，接收28181rtp流转协议给前端的过程是否消耗了显卡资源？

怎么会更显卡扯上关系呢

**Comment by handsometong** [comment]
代码配置udp缓存大小和编译jemalloc有具体的教程或者操作步骤吗

**Comment by handsometong** [comment]
<img width="1568" alt="image" src="https://user-images.githubusercontent.com/12708876/231932546-2143650d-c1b4-4c86-9144-22383b051c86.png">
用go脚本推流，报RtpProcess timeout:0是什么原因

**Comment by miszuoer** [comment]
@zengzhiying 大神，请教个问题哈，我使用了你的开端口和发送rtp文件的脚本进行测试，但是我的zlm在300路就开始丢包了呢，我没有配置zlm对收到的流进行转发，请问这是否会有影响呢

**Comment by liqq1228** [comment]
> 已经测试了400路udp视频播放很流畅，cpu占用700%，带宽2G左右，推的时候稍微提高了下速度，相当于接近500路了，具体极限还没有测，等下测一下 ![image](https://user-images.githubusercontent.com/13583823/124536478-a8733200-de4a-11eb-8a77-2f05815c4f4a.png) ![image](https://user-images.githubusercontent.com/13583823/124536489-ac9f4f80-de4a-11eb-97c6-60990554c9e5.png) 另外按需生成也是默认的0，没改成1，等下改成1再试试

您好，代码能否共享下，谢谢

**Comment by thelastwizardofthecentury** [comment]
请问2000路国标接入，同时录像需要磁盘写入是多少？

**Comment by xia-chu** [comment]
> 请问2000路国标接入，同时录像需要磁盘写入是多少？

2000乘以每路码率 大概可以算出来。
不过不是所有摄像头都在录像吧？

**Comment by thelastwizardofthecentury** [comment]
需要同时录像的，要能接入2000路国标，同时播放，并且需要保存7天录像，如果单台节点不满足就需要部署多台节点，所以想了解下具体的性能


> > 请问2000路国标接入，同时录像需要磁盘写入是多少？
> 
> 2000乘以每路码率 大概可以算出来。 不过不是所有摄像头都在录像吧？

**Comment by thelastwizardofthecentury** [comment]
#mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能
fileBufSize=65536 ，我如果设置2m缓存，这样io性能是否有提升？

**Comment by xia-chu** [comment]
> #mp4录制写文件缓存，单位BYTE,调整参数可以提高文件io性能 fileBufSize=65536 ，我如果设置2m缓存，这样io性能是否有提升？

这个是经验值 要你自己去试试 理论上 在机械硬盘上加大缓存可以减少磁盘寻道次数 提高性能。
