### ISSUE TITLE
util包中SqlConnection.cpp文件不存在

### ISSUE THREAD

**Issue by wuyongguo1** [ZLMediaKit/ZLMediaKit#962]
![image](https://user-images.githubusercontent.com/86996958/124539314-cd1dd880-de4f-11eb-8c83-10b34fac6cda.png)

**Comment by xia-chu** [comment]
那个readme有点老了 代码迭代后 这个文件就删除了 不影响使用的

**Comment by wuyongguo1** [comment]
> 前面的readme 老了 代码迭代后这个有点文件就删除了不影响使用的

好的，谢谢
