### ISSUE TITLE
[BUG] 新版本H265编码的Http-FLV无法播放，旧版本可以

### ISSUE THREAD

**Issue by Allenisme** [ZLMediaKit/ZLMediaKit#965]
**bug现象**
- 最新版本H265编码的Http-FLV无法播放，vlc提示“无法识别无法判别此音频或视频编解码器”，但m3u8，ts可以播放。
- 旧版本日志：![image](https://user-images.githubusercontent.com/17775578/124575392-f3f30380-de7d-11eb-9bdf-ab02b69d4b8d.png)
- 新版本日志：![image](https://user-images.githubusercontent.com/17775578/124575530-0ec57800-de7e-11eb-8af8-7573ebf1dcdb.png)

**bug产生时的使用场景**
- 国标28181

**bug是否可以复现，怎么复现**
- clone最新代码编译

**zlm代码git commit hash值**
- bf8642d62f2606bb99d3ed3408ee9ce4cd2325e8

**操作系统环境**
- win10 64位
- intel i7 8700

**Comment by xia-chu** [comment]
flv本来就不支持265
你是wvp吧？wvp应该是不识别修改后的codec name了

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allen ***@***.***&gt;
发送时间: 2021年7月6日 17:20
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] 新版本H265编码的Http-FLV无法播放，旧版本可以 (#965)





 
bug现象
  
最新版本H265编码的Http-FLV无法播放 

旧版本日志： 

新版本日志： 
 
bug产生时的使用场景
  
产生bug时，您正在使用zlm的什么功能模块？ 
 
bug是否可以复现，怎么复现
  
clone最新代码编译 
 
zlm代码git commit hash值
  
bf8642d 
 
操作系统环境
  
win10 64位 

intel i7 8700

**Comment by Allenisme** [comment]
> flv本来就不支持265 你是wvp吧？wvp应该是不识别修改后的codec name了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Allen ***@***.***&gt; 发送时间: 2021年7月6日 17:20 收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] 新版本H265编码的Http-FLV无法播放，旧版本可以 (#965) bug现象 最新版本H265编码的Http-FLV无法播放 旧版本日志： 新版本日志： bug产生时的使用场景 产生bug时，您正在使用zlm的什么功能模块？ bug是否可以复现，怎么复现 clone最新代码编译 zlm代码git commit hash值 [bf8642d](https://github.com/ZLMediaKit/ZLMediaKit/commit/bf8642d62f2606bb99d3ed3408ee9ce4cd2325e8) 操作系统环境 win10 64位 intel i7 8700 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

大佬，那我只能用旧版或者用m3u8吗？

**Comment by Allenisme** [comment]
![image](https://user-images.githubusercontent.com/17775578/124711491-b8654180-df30-11eb-8877-4c84bc3a97db.png)
大佬，这个枪机是没有音频的，为什么还会识别出PCMU呢？

**Comment by xia-chu** [comment]
> ![image](https://user-images.githubusercontent.com/17775578/124711491-b8654180-df30-11eb-8877-4c84bc3a97db.png)
> 大佬，这个枪机是没有音频的，为什么还会识别出PCMU呢？

应该是有音频的 可能只是静音音频而已

**Comment by Allenisme** [comment]
> > ![image](https://user-images.githubusercontent.com/17775578/124711491-b8654180-df30-11eb-8877-4c84bc3a97db.png)
> > 大佬，这个枪机是没有音频的，为什么还会识别出PCMU呢？
> 
> 应该是有音频的 可能只是静音音频而已

这个枪机就在身边，确实是没有麦克风的

**Comment by xia-chu** [comment]
数据才能说话 你在zlm的代码里面加个日志 看有没有711的frame

**Comment by xia-chu** [comment]
dump出rtp给我测试也行

**Comment by Allenisme** [comment]
[rtp.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6776010/rtp.zip)
![image](https://user-images.githubusercontent.com/17775578/124735060-439e0180-df48-11eb-99cf-cdfc27c076b6.png)
麻烦大佬看看

**Comment by xia-chu** [comment]
。。。我是说zlm的dump功能， 你设置下配置文件中的dumpDir

**Comment by Allenisme** [comment]
[dump.zip](https://github.com/ZLMediaKit/ZLMediaKit/files/6776164/dump.zip)

大佬不好意思

**Comment by sd7934555** [comment]
> 不好意思 这个是新引入的bug 已修复

今天不小心升级了docker，httpflv和rtmp直接拉垮了。。websocket正常，直接回退docker的版本到1.2.0才行

**Comment by Allenisme** [comment]
太好了，谢谢大佬

**Comment by Allenisme** [comment]
![image](https://user-images.githubusercontent.com/17775578/124905103-47995480-e018-11eb-8983-46bb1409722b.png)
大佬，拉完代码编译报错了

**Comment by xia-chu** [comment]
这个明天修复吧



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allen ***@***.***&gt;
发送时间: 2021年7月8日 18:14
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG] 新版本H265编码的Http-FLV无法播放，旧版本可以 (#965)





 

 大佬，拉完代码编译报错了
