### ISSUE TITLE
[BUG]getTracks逻辑问题

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#967]
`

    vector<Track::Ptr> MediaSink::getTracks(bool trackReady) const{
        vector<Track::Ptr> ret;
        lock_guard<recursive_mutex> lck(_mtx);
        for (auto &pr : _track_map){
            if(trackReady && !pr.second->ready()){
                continue;
            }
            ret.emplace_back(pr.second);
        }
        return ret;
}

`

这段代码的逻辑是否有问题?bool trackReady按照您的注释是"trackReady 是否获取全部已经准备好的Track"
如果是这样的话 那么应该是这样才对阿?还是我理解错误
if(trackReady != pr.second->ready())

**Comment by xia-chu** [comment]
trackReady参数标明是否获取已经就绪的track。
如果要求获取的track处于就绪状态，但是某个track未就绪，那么久忽略。
所以逻辑没问题的

**Comment by alexliyu7352** [comment]
比如, 我想要获得当前未就绪的track, 
所以参数是false, 
但是if(trackReady && !pr.second->ready())始终是为假, 最终我获得的包含了已经就绪的

**Comment by xia-chu** [comment]
trackReady参数的意思是时候过滤掉未就绪的track。这个函数没过滤已就绪track的功能，实际上 我也不明白过滤掉已就绪状态track的意义。 你可以新增一个方法

**Comment by alexliyu7352** [comment]
明白了...被你的注释误导了.
实际上应该是
true: 过滤掉未就绪的track
false: 不进行过滤

那这个对应的注释以及参数名称也许修改下比较不引起歧义?比如参数名称修改为filterUnready

**Comment by alexliyu7352** [comment]
主要是
