### ISSUE TITLE
[技术咨询]无法拉取RTSP视频流

### ISSUE THREAD

**Issue by KevinLJJ** [ZLMediaKit/ZLMediaKit#969]
**咨询的功能模块**
- 动态添加rtsp/rtmp/hls拉流代理

**咨询的具体内容和问题**
- 调用该接口时，服务器日志` MediaSink.cpp:52 operator() | cached frame of unready track(CodecH264) is too much, now cleared`，一直重试播放。摄像机的RTSP流设置的是H265，为何这边显示的是CodecH264？

非常感谢！

**Comment by xiongguangjie** [comment]
rtsp 是根据sdp 来判断是什么类型的，你可以抓一下包，看sdp 对不对
