### ISSUE TITLE
[技术咨询]关于mp4文件录制的几个问题

### ISSUE THREAD

**Issue by BaotaoWang** [ZLMediaKit/ZLMediaKit#970]
1、录制的mp4文件会保存几天或者保存多少个？
2、可否不自动保存mp4文件？
3、如果不保存mp4文件的话，是否影响http-fmp4流？

**Comment by xia-chu** [comment]
http-fmp4基于内存 跟mp4录像完全是两回事的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: BaotaoWang ***@***.***&gt;
发送时间: 2021年7月8日 11:44
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]关于mp4文件录制的几个问题 (#970)





 
1、录制的mp4文件会保存几天或者保存多少个？
 2、可否不自动保存mp4文件？
 3、如果不保存mp4文件的话，是否影响http-fmp4流？

**Comment by 1983094983** [comment]
咨询一个问题：
1.MP4的录制stopRecord是如何触发写入索引数据的？ 本人找了一遍代码没有发现写入MP4 header的地方
情况：mingw & cmake 编译，调用录制接口录制rtmp 的流，停止录制后发现mp4没有mov atom数据。 有可能是我配置或者是编译的原因导致的吗

谢谢xia-chu 大大
