### ISSUE TITLE
[技术咨询]video-js无法播放rtmp流

### ISSUE THREAD

**Issue by wyx1997** [ZLMediaKit/ZLMediaKit#972]
**咨询的功能模块**
RTMP模块、AMF解析模块

**咨询的具体内容和问题**
推流经ZLM转发后生成的rtmp流，在VLC上能播放，但是在网页端video-js上无法播放，调试发现好像是AMF解析模块对video-js发送的AMF信息不能正确解析，例如VLC发送的信息中没有AMF0_DATE字段，但是video-js发送的信息中有，导致解析出现异常，请问这种情况有什么解决办法呢？万分感谢！

网页端video-js部分的代码：

![image](https://user-images.githubusercontent.com/29030808/125018762-53ccf280-e0a8-11eb-9b7c-f81d94687094.png)

调试信息：（我修改了源码，尝试解析video-js发送的AMF信息，前面还可以解析，后面就解析失败了）

![image](https://user-images.githubusercontent.com/29030808/125019378-84615c00-e0a9-11eb-85d3-e608303d2274.png)

**Comment by xia-chu** [comment]
不对吧 现在flash都下架了 你还能用rtmp播放啊？

**Comment by wyx1997** [comment]
用的360浏览器，是学校项目需要，凑合能播放就行，关键是还要用opencv读取流，所以选择推的RTMP流。大佬有什么建议吗，就是ZLM推出的流能够在网页上播放的，而且还能用opencv读取的

**Comment by mingyuejingque** [comment]
fmp4 可以在网页上播放， opencv应该也能读取。

**Comment by wyx1997** [comment]
好的，我去试试，非常感谢！


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月12日 15:02:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZLMediaKit/ZLMediaKit] [技术咨询]video-js无法播放rtmp流 (#972)




 
fmp4 可以在网页上播放， opencv应该也能读取。

**Comment by xia-chu** [comment]
@wyx1997 zlm生成rtmp flash一直可以播放的 你测试还是不行？

**Comment by wyx1997** [comment]
VLC可以播放，但是videojs不行，不知道是不是videojs配置的问题，目前已经转用HLS了

**Comment by xia-chu** [comment]
你没启用openssl吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wyx1997 ***@***.***&gt;
发送时间: 2021年7月15日 20:21
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]video-js无法播放rtmp流 (#972)





 
VLC可以播放，但是videojs不行，不知道是不是videojs配置的问题，目前已经转用HLS了

**Comment by wyx1997** [comment]
现在编译的时候不是默认开启openssl了吗？我看CMakeLists里面有写：
option(ENABLE_OPENSSL "Enable OpenSSL" true)
要开启openssl还要其它配置吗？

**Comment by xia-chu** [comment]
cmake找不到openssl就不行啊





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wyx1997 ***@***.***&gt;
发送时间: 2021年7月15日 20:31
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]video-js无法播放rtmp流 (#972)

**Comment by wyx1997** [comment]
我刚刚重新编译了一下看了下，是找到了openssl的

**Comment by xia-chu** [comment]
问题解决了吗哥们？ 编译openssl后，flash肯定能播放的，毋庸置疑。

**Comment by xia-chu** [comment]
前段时间忙，忘了跟踪此问题了

**Comment by wyx1997** [comment]
抱歉，忘回复了，最近的测试结果显示，除了VLC，其他五六个能直接播放rtmp的插件都不能播经过ZLM转发的rtmp，所以有点怀疑是ZLM这边哪里出了问题，不知道是配置还是代码问题。

**Comment by xia-chu** [comment]
播放zlmediakit的rtmp时 截图下zlmediakit日志

**Comment by wyx1997** [comment]
![00L}~2 34P`RUV U1N4 BT5](https://user-images.githubusercontent.com/29030808/128196572-68a7a350-0e75-4695-9e6d-b7cfe0de06ae.png)

**Comment by xia-chu** [comment]
老哥 多看看zlmediakit的日志 你的问题早就解决了 你url都是错的 播放个毛啊 日志都不分析吗？

**Comment by wyx1997** [comment]
请问下哪里url是错的呢，最下面的黄色的输出不是改过来了吗

**Comment by xia-chu** [comment]
> 请问下哪里url是错的呢，最下面的黄色的输出不是改过来了吗

抱歉 只关注到前面两次播放url错误的日志 后面确实播放成功了，没画面？

**Comment by wyx1997** [comment]
没画面

**Comment by xia-chu** [comment]
rtmp有vod和live模式 你是不是选成vod模式了？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wyx1997 ***@***.***&gt;
发送时间: 2021年8月4日 22:33
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [技术咨询]video-js无法播放rtmp流 (#972)





 
没画面

**Comment by wyx1997** [comment]
啊这，我对这方面不太懂，请问这两种模式是在配置文件中设置吗，还是在播放器那边操作呢，怎么判断是否选成了vod模式了呢？
