### ISSUE TITLE
请问有ehome相关的文档吗?[技术咨询]

### ISSUE THREAD

**Issue by lovederh** [ZLMediaKit/ZLMediaKit#973]
**咨询的功能模块**
ehome
- 请描述您想咨询zlmediakit的哪部分功能
ehome如何使用
**咨询的具体内容和问题**
没有找到关于ehome使用的资料, 不知道要如何配置或者调用

**Comment by xia-chu** [comment]
可以了解下freeehome这个项目 他是信令服务器

**Comment by lovederh** [comment]
> 可以了解下freeehome这个项目 他是信令服务器
这个项目我下载了, 不过是个未完成的项目, 没法运行测试, 里面的前端和服务端的接口都对应不上

**Comment by xia-chu** [comment]
那你要二次开发了 很多时候 &nbsp;不是开源都能解决的&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lovederh ***@***.***&gt;
发送时间: 2021年7月12日 10:01
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] 请问有ehome相关的文档吗?[技术咨询] (#973)





  
可以了解下freeehome这个项目 他是信令服务器
 这个项目我下载了, 不过是个未完成的项目, 没法运行测试, 里面的前端和服务端的接口都对应不上
