### ISSUE TITLE
[技术咨询]“RtpReceiver.cpp:70 inputRtp | ssrc不匹配,rtp已丢弃”是什么情况导致的

### ISSUE THREAD

**Issue by 445990772** [ZLMediaKit/ZLMediaKit#976]
**咨询的功能模块**
- rtp拉流后解码报“RtpReceiver.cpp:70 inputRtp | ssrc不匹配,rtp已丢弃:305005921 != 305007210”

**咨询的具体内容和问题**
- 前端刷新拉流的时候日志输出 ssrc不匹配，rtp丢弃，具体日志截图如下
- ![image](https://user-images.githubusercontent.com/9440839/125038584-298b2d00-e0c8-11eb-8dbe-c515aa68d274.png)

**Comment by xia-chu** [comment]
这个属于多个摄像头冲突使用一个端口导致，属于sip调度系统紊乱问题

**Comment by 445990772** [comment]
已解决，感谢。

**Comment by jackyHJ** [comment]
@445990772 大佬，请问一下怎么解决的

**Comment by 445990772** [comment]
设备原因导致的，改成动态分配端口。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 中午11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] [技术咨询]“RtpReceiver.cpp:70 inputRtp | ssrc不匹配,rtp已丢弃”是什么情况导致的 (#976)





 
@445990772 大佬，请问一下怎么解决的
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by limjoe** [comment]
@445990772 设备推送 rtp 流没有说指定端口呢？你是怎么解决的呢？
目前我是所有的设备都推送到 zlm 的 10000 UDP/TCP 端口，设备量大了以后，上述日志就比较多，而且会造成服务器系统软中断处理进程异常跑满100%cpu。 机器的网络通讯会异常，导致服务器死机

**Comment by limjoe** [comment]
目前找到原因了，之前的网络链路是：IPC -> 云端 IP -> 云端 LB -> k8s traffic -> ZLM pods

之前很有可能是 k8s traffic 转发流时，zlm 把 trafficip 当做远端 IP 了

**Comment by DoNtLyToMe** [comment]
@445990772 请问设备端如何设置动态分配端口
