### ISSUE TITLE
[功能请求]HLS 分片文件使用fmp4格式替代ts格式

### ISSUE THREAD

**Issue by musicwood** [ZLMediaKit/ZLMediaKit#977]
**描述该功能的用处，可以提供相关资料描述该功能**
苹果平台的浏览器支持hevc over fmp4的hls流
微软的edge浏览器在系统（win10）安装hevc支持的前提下，可以使用hls.js播放hevc over fmp4 的hls流

**该功能是否用于改进项目缺陷，如果是，请描述现有缺陷**

**描述你期望实现该功能的方式和最终效果**
测试页面：https://hls-js.netlify.app/demo/
测试hls播放地址：https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_adv_example_hevc/v14/prog_index.m3u8
win10 hevc 插件：链接: https://pan.baidu.com/s/1MLkjS9xybzLN8WCY-HCUSQ 提取码: 9nm6

**Comment by musicwood** [comment]
![2cd4809d9a37dc4e5369dc826129f29](https://user-images.githubusercontent.com/3955713/125060387-e7b9b100-e0de-11eb-9229-01dc8d1aec4b.png)
edge安装插件以后在edge://gpu/页面可以看到可以支持hevc了

**Comment by xia-chu** [comment]
zlm你们有fmp4文件生成相关的代码 生成这个倒是不难

**Comment by musicwood** [comment]
周末查了一些资料，国内有些厂商的实现是264的hls使用ts封装，265的hls使用fmp4封装，这样做兼容性最好。zlm可以考虑多加一种hls的url格式，交由用户选择使用哪种封装的hls。

**Comment by denniste** [comment]
其实，对于监控来使用，大部分时候，干脆放弃hls（可仅作为其他技术无法播放时的补充）就使用zlm中的 flv,livets,fmp4 挺好的，flv和 livets ，直接用 [这个](https://github.com/xqq/mpegts.js) 。至于fmp4，倒是有个类似的 [h5播放](https://github.com/deepch/RTSPtoWSMP4f/blob/master/web/static/js/app.js) 改改就可播放。我测试过 gb28181的源，测试的时候吓一跳，飞快。对有些摄像头来说，甚至比摄像头本身的rtsp还要快（如果有数个客户端访问该rtsp时），一般情况，gb28181下，都能和rtsp同步（顶多差1秒多）。

**Comment by xia-chu** [comment]
hls确实比较废 特别是h265的hls

**Comment by alexliyu7352** [comment]
hls还是有不少用处的, 特别是自己做cdn的时候. 使用hls比较好.
大型一点的云监控必须要使用cdn的.而hls对cdn的兼容性是最好的.
不使用第三方cdn的时候, 自己架设bgp服务器做cdn, 套一个nginx反向代理+缓存就可以了.

**Comment by xia-chu** [comment]
这个已经支持 通过配置文件enable_hls_fmp4开启
