### ISSUE TITLE
[BUG] Build on Windows failed (latest source code)

### ISSUE THREAD

**Issue by pubpy2015** [ZLMediaKit/ZLMediaKit#978]
**bug现象**
- bug产生时服务器的异常行为(例如: 崩溃/无法访问/丢包花屏)
- bug产生时，打印的上下文日志(可以截图或粘贴文本)
- 调试core文件时，崩溃触发点的函数调用栈(可以截图或粘贴文本)

![image](https://user-images.githubusercontent.com/59004953/125111936-b78b0600-e110-11eb-80d0-88ef17dee09f.png)

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的什么功能模块？

**bug是否可以复现，怎么复现**
- 请描述bug复现时的操作步骤

**zlm代码git commit hash值**
- git log查看

latest source code

**操作系统环境**
- 什么类型的操作系统，32位，64位？
- 什么cpu类型？
Windows 10 Pro 64 bit
Intel Core i7 10070

**Comment by xia-chu** [comment]
```patch
Index: src/Network/Buffer.h
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/Network/Buffer.h	(revision a85d03ab4834460fd714bbec374658731ae0c6c8)
+++ src/Network/Buffer.h	(date 1625914964178)
@@ -28,12 +28,14 @@
 #include "Network/sockutil.h"
 using namespace std;
 
-namespace std {
-    template <typename T> struct is_pointer<shared_ptr<T> > : std::true_type {};
-    template <typename T> struct is_pointer<shared_ptr<T const> > : std::true_type {};
-}
-
 namespace toolkit {
+
+template <typename T> struct is_pointer : public std::false_type {};
+template <typename T> struct is_pointer<shared_ptr<T> > : public std::true_type {};
+template <typename T> struct is_pointer<shared_ptr<T const> > : public std::true_type {};
+template <typename T> struct is_pointer<T*> : public true_type {};
+template <typename T> struct is_pointer<const T*> : public true_type {};
+
 //缓存基类
 class Buffer : public noncopyable {
 public:
@@ -92,13 +94,13 @@
     }
 
     template<typename T>
-    static typename std::enable_if<std::is_pointer<T>::value, const T &>::type
+    static typename std::enable_if<toolkit::is_pointer<T>::value, const T &>::type
     getPointer(const T &data) {
         return data;
     }
 
     template<typename T>
-    static typename std::enable_if<!std::is_pointer<T>::value, const T *>::type
+    static typename std::enable_if<!toolkit::is_pointer<T>::value, const T *>::type
     getPointer(const T &data) {
         return &data;
     }

```

**Comment by xia-chu** [comment]
please test the patch。

**Comment by pubpy2015** [comment]
Thanks,
now only 1 error here:
![image](https://user-images.githubusercontent.com/59004953/125161786-85c87c80-e1ae-11eb-8898-fb9a6e2b5597.png)
 my cmake:
![image](https://user-images.githubusercontent.com/59004953/125161796-8e20b780-e1ae-11eb-91c3-937bf7a853f4.png)

**Comment by pubpy2015** [comment]
if disable WEBRTC everything OK

**Comment by pubpy2015** [comment]
if enable OpenSSL and WebRTC, error here:
![image](https://user-images.githubusercontent.com/59004953/125178078-85120380-e20b-11eb-9546-768ddffb9c59.png)

if abort build "test_rtcp_nack" project, some warnings still exist but everything OK. 
![image](https://user-images.githubusercontent.com/59004953/125178205-cce55a80-e20c-11eb-9509-0bda8ed54bee.png)

**Comment by xia-chu** [comment]
Compiling webrtc is troublesome. You need to compile and install libsrtp2 first, then `cmake -DENABLE_WEBRTC=on -DSRTP_PREFIX=/path/to/srtp2`.

**Comment by pubpy2015** [comment]
Can you help me step by step build with enable WebRTC on Windows ?
I can download libsrtp2 here: https://github.com/cisco/libsrtp and build completed on windows, but dont know how to import to your projects.
CMake GUI has an error on this:
![image](https://user-images.githubusercontent.com/59004953/125631020-e5050216-da41-4bf4-b2cf-2dd84c6473a2.png)

**Comment by xia-chu** [comment]
<img width="887" alt="图片" src="https://user-images.githubusercontent.com/11495632/125740042-cec71491-facd-4cec-966a-e69178ec4872.png">

Can you add `-DSRTP_PREFIX=/path/to/srtp2` by press  `Add Entry` button?

**Comment by xia-chu** [comment]
when you build srtp2, you need configure it enbale `--enable-openssl`

**Comment by pubpy2015** [comment]
Yes,

but still error.
this is cmake for srtp2:
![ảnh](https://user-images.githubusercontent.com/59004953/125745593-2b181485-8b51-4e3b-8f80-5e2964342718.png)

cmake for ZLMediaKit with DSRTP_PREFIX entry:
![ảnh](https://user-images.githubusercontent.com/59004953/125745736-9fc41eec-c637-42ff-b540-9b2532a536a5.png)

**Comment by xia-chu** [comment]
`SRTP_PREFIX` ; not `DSRTP_PREFIX`

**Comment by pubpy2015** [comment]
Thanks, but still error.
libsrtp2 here is correct source ?: https://github.com/cisco/libsrtp
![ảnh](https://user-images.githubusercontent.com/59004953/125750750-596e6138-ed76-4921-af75-56dd4a3ebcd8.png)

**Comment by wasphin** [comment]
The `SRTP_PREFIX` should point to the path that contains both the headers path(which is `include`) and libraries path(which is `lib`). e.g.:
```
D:/some-path <-- this should be the SRTP_PREFIX
`-- lib
|   `-- srtp2.lib
`-- include
    `srtp2/srtp.h
```
You may need to install the libsrtp2 after building it, or, you can also manually create paths like above.

Haven't try it under Windows, though.

**Comment by pubpy2015** [comment]
Thanks,

I have modified like that, but still no success:
Do you have free time now ?, i will send TeamViewer, please help me to build this project 
![ảnh](https://user-images.githubusercontent.com/59004953/125769745-8fd5fe3a-a716-4973-ae00-4932b8952ddf.png)

![ảnh](https://user-images.githubusercontent.com/59004953/125769914-8eb7d392-59c5-4ecb-b83e-ef9abca98e63.png)
![ảnh](https://user-images.githubusercontent.com/59004953/125769946-07087006-5ee1-4cec-be06-f7137392c8ef.png)
![ảnh](https://user-images.githubusercontent.com/59004953/125769972-14b9e228-741d-4c13-9410-2cb4b152ee54.png)

**Comment by wasphin** [comment]
You missed the `srtp2`, shoud be something like
```
xxx/include/srtp2/srtp.h
            ^^^^^
```

**Comment by pubpy2015** [comment]
Thank you very much.

The correct path is:
xxx/bin/lib/srtp2.lib
xxx/include/srtp2/srtp.h

**Comment by pubpy2015** [comment]
Build completed with enable WEBRTC.
But i dont know how to start with WebRTC. 
My scenario is: using AddStreamProxy to add rtsp stream from ip camera to MediaServer and using browser to play.
I will learn about WebRTC. Close issue here.

**Comment by pubpy2015** [comment]
Sorry, today I am clone your latest code and build with enable WebRTC but not success.
There are some errors on webrtc project:
![image](https://user-images.githubusercontent.com/59004953/128375497-6f482e0d-ae0e-4b78-a21b-55bc91ddff46.png)

**Comment by xia-chu** [comment]
you can replace `std::max(_rtt, 5)` to `_rtt > 5 ?  _rtt : 5`

**Comment by pubpy2015** [comment]
Thanks
