### ISSUE TITLE
[BUG]使用addFFmpegSource方式将H265转换成H264时，转换之后的rtc格式的流每隔10秒播放一次画面

### ISSUE THREAD

**Issue by frankfif** [ZLMediaKit/ZLMediaKit#979]
**bug现象**
摄像头以H265格式推流至zlmediakit，使用addFFmpegSource方式进行流转码，srcUrl=rtsp://127.0.0.1/rtp/34020000001320000230_34020000001320000231,dstUrl=rtmp://127.0.0.1/convert/3402000000132000023
0_34020000001320000231，将H265格式的流转换成H264格式的流，转码之后的flv/hls格式的流播放地址均可以正常播放，但rtc格式的流在
浏览器中播放时，发现每隔10秒，播放器的播放界更新一次，不是实时流了，类似每隔10秒中播放一次图片，比较有规律，请问是某个配置
的问题，还行需要调整代码，谢谢。
使用的代码是：最新master分支，下载编译时间：2021-7-10
注：摄像头以H264推流时，播放flv、hls、rtc等格式的流时，均无问题。

**bug是否可以复现，怎么复现**
测试了好多次，必现

**操作系统环境**
- Ubuntu 18.04.4 64位

**Comment by xia-chu** [comment]
ffmpeg转码时 指定下profile为baseline &nbsp;由于webrtc不支持b帧 所以这样。 另外 推流协议建议用rtmp ffmpeg生成的rtp webrtc可能没法直接播放



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: frankfif ***@***.***&gt;
发送时间: 2021年7月10日 20:11
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] [BUG]使用addFFmpegSource方式将H265转换成H264时，转换之后的rtc格式的流每隔10秒播放一次画面 (#979)





 
bug现象
 摄像头以H265格式推流至zlmediakit，使用addFFmpegSource方式进行流转码，srcUrl=rtsp://127.0.0.1/rtp/34020000001320000230_34020000001320000231,dstUrl=rtmp://127.0.0.1/convert/3402000000132000023
 0_34020000001320000231，将H265格式的流转换成H264格式的流，转码之后的flv/hls格式的流播放地址均可以正常播放，但rtc格式的流在
 浏览器中播放时，发现每隔10秒，播放器的播放界更新一次，不是实时流了，类似每隔10秒中播放一次图片，比较有规律，请问是某个配置
 的问题，还行需要调整代码，谢谢。
 使用的代码是：最新master分支，下载编译时间：2021-7-10
 注：摄像头以H264推流时，播放flv、hls、rtc等格式的流时，均无问题。
 
bug是否可以复现，怎么复现
 测试了好多次，必现
 
操作系统环境
  
Ubuntu 18.04.4 64位

**Comment by frankfif** [comment]
非常感谢，秒回，ffmpeg命令模板中增加-profile:v baseline，即可, @xia-chu

**Comment by yuzhihaoGitHub** [comment]
大神您好，怎么知道流从h265转成h264了呢，有没有哪个接口可以查看呢
