### ISSUE TITLE
关于faac的编译。

### ISSUE THREAD

**Issue by FoxesChen** [zlmediakit/ZLMediaKit#98]
关于libaac，在windows下， 我用mingw来编译 ，然后将 *.o的文件 用gcc来拼成 dll 和 lib，发现在vs里面引用这个lib 会提示 无法找到函数。从github  和  sourceforge里面 下载的代码都出现了这个问题。是不是我的gcc 在连接时，有问题。操作步骤如下：
./bootstrap
./configure --without-mp4v2 --enable-shared
make
make install
gcc -shared -o libfaac.dll *.o -Wl,--output-def,libfaac.def,--out-implib,libfaac.lib

**Comment by xiongziliang** [comment]
你直接使用源码吧 我之前都是直接使用faac的源码

**Comment by FoxesChen** [comment]
哦，知道了。我这边直接装了个vs2008，然后才编译通过的。
