### ISSUE TITLE
[功能请求] ffmpeg拉流转码方式

### ISSUE THREAD

**Issue by alexliyu7352** [ZLMediaKit/ZLMediaKit#982]
目前ffmpeg拉流转码后是通过push到rtmp接口实现流输出的, 这样等于
拉流----->转码/转封包格式---->推流rtmp----->解复用帧----->>>按不通协议输出

为何不直接使用ffmpeg拉流后输出比如mpeg-ts格式的流直接到程序内然后在解复用, 这样就少了一个重新打包成rtmp, 然后退流rtmp的过程了. 减少了耗时和出问题的环节.

我有看一些其他的服务器有使用类似这样的命令, 直接输出流到管道
-codec copy -threads 0 -f mpegts -mpegts_m2ts_mode 1 -mpegts_copyts 1 -mpegts_flags +resend_headers -

**Comment by sultan801** [comment]
Thank you my friend

**Comment by xia-chu** [comment]
如果不转换成rtmp zlm怎么接收FFmpeg拉的流呢？ zlm只能通过标准输入输出协议对接FFmpeg
