### ISSUE TITLE
[BUG]master分支代码webrtc/index.html页面push/play出错

### ISSUE THREAD

**Issue by qiujiancn** [ZLMediaKit/ZLMediaKit#983]
**bug现象**
- 前段时间dev分支，webrtc/index_play.html & webrtc/index_push.html 两个页面是可以推流和播放成功的：
http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=play
http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=push

- 今天我看没有dev分支了，master分支已经合并了webrtc功能，然后再次使用webrtc/index.html 页面，发现无论是push还是play，这个推流地址都返回404 not find：
http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=play
http://127.0.0.1/index/api/webrtc?app=live&stream=test&type=push
（ip已使用正确的ip地址）

**bug产生时的使用场景**
- 产生bug时，您正在使用zlm的webrtc功能模块

**bug是否可以复现，怎么复现**
- 必现错误，已经无法使用webrtc推流和播放功能了

**zlm代码git commit hash值**
1 parent 77283f3 commit 6bc39058abf24f21cac008b024327a88370915bd

**操作系统环境**
- 什么类型的操作系统，32位，64位？64位/centos7.6

**Comment by wasphin** [comment]
master 分支默认未开启 webrtc 功能, 而原 dev 默认是开启的.

https://github.com/ZLMediaKit/ZLMediaKit/blob/6bc39058abf24f21cac008b024327a88370915bd/CMakeLists.txt#L58

**Comment by xia-chu** [comment]
wiki有webrtc特性怎么启动编译的文章 建议看一下

**Comment by qiujiancn** [comment]
理解有误，sorry
