### ISSUE TITLE
[技术咨询]rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示

### ISSUE THREAD

**Issue by wangyangshuo** [ZLMediaKit/ZLMediaKit#987]
rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示
rtsp流是大华的流格式

**Comment by monktan89** [comment]
addStreamProxy 返回code 0 只能说明连接拉流服务器成功了  实际流信息还是得等到新的媒体源注册

**Comment by wangyangshuo** [comment]
用直连摄像头的rtsp流可以注册上，但是用硬盘录像机大华的rtsp流形式为什么注册不上呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 老衲不出家 ***@***.***&gt;
发送时间: 2021年7月15日 20:14
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: wangyangshuo ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987)





 
addStreamProxy 返回code 0 只能说明连接拉流服务器成功了  实际流信息还是得等到新的媒体源注册

**Comment by wasphin** [comment]
提的问题很抽象, 是不是可以提供点实际日志/截图/抓包什么的?

**Comment by wangyangshuo** [comment]
![1](https://user-images.githubusercontent.com/34498226/125874855-eebb96cb-5ac8-464c-9c74-abb11deac0ab.png)
这是调用addStreamProxy后显示的

**Comment by xia-chu** [comment]
这个版本的zlm已经很早了 建议更新下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangyangshuo ***@***.***&gt;
发送时间: 2021年7月16日 08:41
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987)

**Comment by wangyangshuo** [comment]
![image](https://user-images.githubusercontent.com/34498226/125875251-070e716b-84ba-45fa-8faf-874b5880ef01.png)
我是直接在这里面下的MediaServer_windows64.zip   是从这下载吗?

**Comment by wasphin** [comment]
那个 Releases 上看日期是 2019 年的, 有点老了, 已经改了很多了, 可以参考 wiki 里的[快速开始](https://github.com/ZLMediaKit/ZLMediaKit/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B)编译一个.

**Comment by wangyangshuo** [comment]
![image](https://user-images.githubusercontent.com/34498226/125880942-99d619b3-b4d0-44a0-a8cc-55ddb932eec2.png)
![image](https://user-images.githubusercontent.com/34498226/125880952-bd16243e-cd38-494c-8d0c-83514641f083.png)
用最新编译的可以添加上流，但是VLC一直放不出来呢?

**Comment by xia-chu** [comment]
265的视频吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangyangshuo ***@***.***&gt;
发送时间: 2021年7月16日 10:11
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987)





 

 
 用最新编译的可以添加上流，但是VLC一直放不出来呢?

**Comment by wangyangshuo** [comment]
264的视频




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZLMediaKit/ZLMediaKit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 上午10:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987)





 265的视频吗 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: wangyangshuo ***@***.***&amp;gt; 
 发送时间: 2021年7月16日 10:11 
 收件人: ZLMediaKit/ZLMediaKit ***@***.***&amp;gt; 
 抄送: 夏楚 ***@***.***&amp;gt;, Comment ***@***.***&amp;gt; 
 主题: 回复：[ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987) 
 
 
 
 
 
   
 
   
  用最新编译的可以添加上流，但是VLC一直放不出来呢?

**Comment by wangyangshuo** [comment]
![image](https://user-images.githubusercontent.com/34498226/125884175-b4d5ce72-94cd-4523-a82f-f908173f4791.png)

**Comment by xia-chu** [comment]
你用vlc播放的url是多少



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wangyangshuo ***@***.***&gt;
发送时间: 2021年7月16日 10:50
收件人: ZLMediaKit/ZLMediaKit ***@***.***&gt;
抄送: 夏楚 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[ZLMediaKit/ZLMediaKit] rtsp流添加addStreamProxy返回code0成功,但是在获取流列表里面没有显示[技术咨询] (#987)

**Comment by wangyangshuo** [comment]
http://插件所在的ip地址/live/test.flv

**Comment by wangyangshuo** [comment]
![image](https://user-images.githubusercontent.com/34498226/125885047-b21c6d68-fd6a-466d-9ec0-9341bc140d9f.png)

等待时间长了之后就会变成这样

**Comment by xia-chu** [comment]
哥们问题解决没？最近有点忙，忘了跟踪此问题了。

**Comment by wangyangshuo** [comment]
从大华硬盘录像机 还是不能播放  可以直接取摄像头的rtsp流

**Comment by wangyangshuo** [comment]
硬盘录像机加流不能直播  回放流加流后可以播放

**Comment by xia-chu** [comment]
rtsp url能暴露公网吗 我测试下
