### ISSUE TITLE
[功能请求]多路流通过切换变成新的一路流

### ISSUE THREAD

**Issue by BenLocal** [ZLMediaKit/ZLMediaKit#988]
例如同时拉取live/a，live/b，live/c三路流
某一时间通过rest api触发，将live/a推流到live/d；
某一时间通过rest api触发，将live/b推流到live/d；
某一时间通过rest api触发，将live/c推流到live/d；

最终播放器一直播放live/d，不会中断还可以录制

**Comment by wasphin** [comment]
a/b/c 的帧需要对齐吗? 还是只管推不需要处理数据?

**Comment by BenLocal** [comment]
我想到的可能场景：
1. 同一个场所不同设备的流，a/b/c 音频源是一样的，切换的时候，帧可能需要对齐（如果不对齐我不清楚切换的时候音频播放会不会体验变差）。
2. 不同场地不同设备的流，a/b/c 音频源不是一样的，这种对不对齐都没有影响。

**Comment by xia-chu** [comment]
这个功能是可以实现的 但是还是很多地方要注意
1、切换不同源的视频时，可能需要解码器重置，所以应该在遇到关键帧时切换，并且需要保证每一帧关键帧前面有sps pps帧。
2、aac这种音频，在传输时都不会传输adts头，所以如果采样率等信息变了，是没法切换的。
3、有些视频录制容器不支持切换分辨率(sps/pps)的，貌似mp4就不行的。

要切换不同的流有很多坑要处理，有些坑还处理不了。
这个功能更多的是应用，而不应该是zlm的功能，在zlm的api使用上，用户输入不同源的数据就行，zlm不需要另外改造的。
所以此功能请求不会接受。
