### ISSUE TITLE
[BUG]flv播放失败，不能正常播放

### ISSUE THREAD

**Issue by chenchengwork** [ZLMediaKit/ZLMediaKit#989]
**bug现象**
flv播放失败，不能正常播放
![2021-07-17 17-30-22 的屏幕截图](https://user-images.githubusercontent.com/5061635/126032731-55987774-6015-454c-9739-264092eb49ce.png)

**bug产生时的使用场景**
- 使用/index/api/addStreamProxy，持续拉取rtsp流，视频流的编码确定是h264

- git commit 892b2d2ef97447b7f3c32c57a5170865c924b37e

**操作系统环境**
- 操作系统ubuntu18.0
- CPU是intel64

**Comment by monktan89** [comment]
pcma播放器不一定能支持

**Comment by chenchengwork** [comment]
pcma编码是如何出来的，我拉的h264编码的视频流呀

**Comment by xia-chu** [comment]
配置文件关闭音频，你就能播放了：
<img width="763" alt="图片" src="https://user-images.githubusercontent.com/11495632/126117788-34cdfb29-d95b-4439-ba50-3dc337dc32dc.png">
