### ISSUE TITLE
[技术咨询]如何自己新增web hook?

### ISSUE THREAD

**Issue by liangjw-editor** [ZLMediaKit/ZLMediaKit#995]
**咨询的功能模块**
web hook

**咨询的具体内容和问题**
我想自己新增一个web hook可以在使用proxy接口代理rtsp取流时因rtsp地址有效期过期后取流失败或者代理成功后因有效期过期重试播放时回调给第三方服务器，告知此rtsp地址无法打开，我应该怎么做，可以借鉴哪个部分、哪几个文件？

**Comment by xia-chu** [comment]
可以在PlayerProxy 对象这里：
<img width="1161" alt="图片" src="https://user-images.githubusercontent.com/11495632/126117591-ae5fb3f1-66bf-4cd4-a4e1-f901c0ae931c.png">
发送事件广播，然后在WebHook.cpp监听此事件并发送http请求

**Comment by xia-chu** [comment]
issue 先关闭了 有问题继续在此issue讨论
