### ISSUE TITLE
[功能请求]webhook api增加心跳heart beat功能

### ISSUE THREAD

**Issue by frankfif** [ZLMediaKit/ZLMediaKit#997]
好处：第三方系统可以方便的感知流媒体服务的运行状态，如：是否掉线，服务当前占用的内存等系统情况

**Comment by xia-chu** [comment]
zlm有崩溃重启hook，另外也有getStatistic http api获取服务器内存对象统计信息。
这些都可以监控治理zlmediakit服务。

**Comment by xia-chu** [comment]
issue 先关闭了 有问题继续在此issue讨论

**Comment by taojishou** [comment]
如果是webhook的heart beat功能会比较好一些  get有时候跨网段麻烦一些

**Comment by xia-chu** [comment]
> 如果是webhook的heart beat功能会比较好一些  get有时候跨网段麻烦一些

这个功能我们开发组另外一位组员已经实现并合并master分支了，你可以查看下提交记录

**Comment by taojishou** [comment]
似乎心跳没起作用?
