### ISSUE TITLE
[技术咨询]g711无法在web端播放

### ISSUE THREAD

**Issue by lovederh** [ZLMediaKit/ZLMediaKit#999]
大华摄像头音频 主码流 设置为AAC, 辅码流设置为g711, 声音播放不出来
音频配置如下: 
![image](https://user-images.githubusercontent.com/8230698/126291305-351c4500-88a3-41d0-ba2e-149d1ec0f9b5.png)
控制台报错信息如下: 
![image](https://user-images.githubusercontent.com/8230698/126291427-c046d830-d646-4218-9dbd-aa57547a7b72.png)

**Comment by zhang2349** [comment]
https://github.com/ZLMediaKit/ZLMediaKit/blob/566a49e2278201fbe624705e9c654d06e4eb7166/src/Http/HttpSession.cpp#L357
没输出这句话吗

**Comment by lovederh** [comment]
> https://github.com/ZLMediaKit/ZLMediaKit/blob/566a49e2278201fbe624705e9c654d06e4eb7166/src/Http/HttpSession.cpp#L357
> 
> 
> 没输出这句话吗

应该是我的输出需要设置什么, 我这没设置, 现在是没有输出的

**Comment by xia-chu** [comment]
flv.js不支持g711 你必须要设置为aac才能在web上播放。或者你干脆关闭音频吧，配置文件中有enableAudio的配置

**Comment by lovederh** [comment]
> flv.js不支持g711 你必须要设置为aac才能在web上播放。或者你干脆关闭音频吧，配置文件中有enableAudio的配置

不行啊, 业务要求有声音, 在哪里设置开启日志呢

**Comment by xia-chu** [comment]
那能怎么样？你就换个wasm支持711的播放器呗。

**Comment by xia-chu** [comment]
issue 先关闭了 有问题继续在此issue讨论
